govulncheck-allowlist.json

Add `GO-2024-2842` in the exception list
None, but given warning in https://github.com/stackrox/stackrox/actions/runs/9172134384/job/25218755631 it should be fixed:
```
GO-2024-2842 Unexpected authenticated registry accesses in github.com/containers/image/v5
Found vulnerabilities. If they are false positives, add them to govulncheck-allowlist.json
```

fix(release): vulncheck exception

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/ConditionNumber.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.test.ts
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.ts

This PR adds the `condition-number` option  to the compound search filter 🔍 . The `ConditionNumber` component will do the following:
1. Show a dropdown to choose a condition (ie. `Is less than`, etc.)
2. Allow inputting a number
3. Restrict the number to a range (between a `min` and `max` value) on blur
4. Disables the `plus` and `minus` buttons when it reaches the `min` or `max` value
5. Has a search button that will trigger the search once it's clicked. We don't want to modify the search on every interaction
Note: This new option will replace the `dropdown-slider` option after discussions with UX

ROX-23515: Adding condition-number input to compound search filter

---

ui/apps/platform/src/Containers/Dashboard/Widgets/ComplianceLevelsByStandard.tsx
ui/apps/platform/src/Containers/Dashboard/Widgets/ComplianceLevelsByStandardChart.tsx

**Manage standards** affects compliance dashboard but not **Compliance by standard** on main dashboard.
Response to `getAggregatedResults` query by `ComplianceLevelsByStandard` component includes `complianceStandards` property:
```json
{
"data": {
"complianceStandards": [
{"id": "PCI_DSS_3_2", "PCI DSS 3.2.1"}
],
"controls": {
"results": [
{
"aggregationKeys": {"id": "PCI_DSS_3_2", "scope": "STANDARD"},
"numFailing": 15,
"numPassing": 27,
"numSkipped": 80,
"unit": "CONTROL"
}
]
}
}
}
```
1. Edit ComplianceLevelsByStandard.tsx file.
* Include `complianceStandards` in `ComplianceData` type.
* Add condition to `processData` function.
* Move `slice` and `reverse` into `processData` function because of difficulty to keep them in `useMemo` hook.
Ironically, I had recommended not including them …

ROX-23672: Filter compliance standards on main dashboard

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx
ui/apps/platform/src/services/ComplianceResultsService.ts

Adds sorting to the Compliance V2 Profile Checks table
Note: UX shows ability to sort by compliance statuses, however these columns are unsortable now due to our backend search framework. Will revisit these in a later release.
Manual testing, backend implementation not available. Tested by clicking on column header and checking the api call.
before:
after:

ROX-24096: Add profile checks sorting

---

central/scannerdefinitions/handler/handler.go
pkg/features/list.go
scanner/matcher/updater/vuln/updater.go
scanner/matcher/updater/vuln/updater_test.go

This will modify Central to serve multi-bundle vulnerabilities upon the client passing `X-Scanner-V4-Accept` headers with a specific application-specific content type. It will modify Scanner V4 to pass such header if the multi-bundle feature is set to "true", which is now the default. A test was added for the multi-bundle updater.
Deploy the image and observe Scanner V4 requesting multi-bundle vulnerabilities, and Central granting them.
This can be confirmed by observing the two Matchers running updates concurrently.
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand …

feat(central): defs: Switch to multi bundle definitions

---

central/cluster/datastore/telemetry.go
pkg/telemetry/phonehome/segment/segment.go
pkg/telemetry/phonehome/segment/segment_test.go
pkg/telemetry/phonehome/telemeter/telemeter.go
pkg/telemetry/phonehome/telemeter/telemeter_test.go

`WithMessageIDPrefix` option makes Segment client generate the message ID based on the prefixed message content hash. Provided with the current date, it will generate same ID for equal messages during a day. This in turn will allow Segment to drop duplicates occurring in a 1 day range.
This is to complement, or prepare for #11011, where a cache is implemented to block duplicate events on the client side.
Unit tests.
See the custom `messageId`:
```json
{
"anonymousId": "70232094-8d6e-4292-a71a-dc6f5df57a29",
"context": {
"device": {
"id": "70232094-8d6e-4292-a71a-dc6f5df57a29",
"type": "Secured Cluster Server"
},
"groups": {
"Tenant": [
"7de3653e-5d0a-47f2-b231-e9a2438be867"
]
},
"library": {
}, …
```

ROX-24045: Telemetry `WithMessageIDPrefix` option

---

tests/endpoints_test.go

From time to time we have an error on connecting to central in our non groovy e2e tls test. This PR adds retry mechanism to those calls (only if error is not expected).
CI

ROX-22051: retry tls dial in test

---

.github/workflows/build.yaml

We had disabled the `roxctl` scan job because of a bug in roxctl that caused the job to fail in case no vulnerabilities were found. This bug has been fixed in 4.4.2, which is now released.

ROX-23940: re-enable roxctl scan

---

qa-tests-backend/src/test/groovy/DeploymentCheck.groovy
scripts/ci/logcheck/allowlist-patterns

This PR fixes two things: ensure we use quay.io images instead of docker.io images since they are suspectible to rate limiting, extend the allow list pattern for suspicious logs to also cover more errors related to image enrichment.
- see CI pass.

ROX-23284: fix suspicious logs

---

central/telemetry/centralclient/instance_config.go
pkg/telemetry/phonehome/gatherer.go
pkg/telemetry/phonehome/gatherer_test.go

Refactoring of the phonehome telemetry gatherer framework:
* Remove the gatherer cache in favor of the generic telemeter cache, enabled with the `WithNoDuplicates` option.
* Remove the "Heartbeat" event in favor of the daily, potentially duplicate, "Updated * Identity" event.
Tests:
* Unit tests

ROX-24045: telemetry gatherer to use `WithNoDuplicates`

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ObservedCveModeSelect.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/VulnerabilityStateTabs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadCveFilterToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/searchUtils.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/sortUtils.tsx

Adds the implementation for the core "Images without vulnerabilities" functionality. When this option is selected:
- The "CVEs" table will disappear ("Images" will be selected if the user was previously viewing CVEs)
- All filters, pagination, and sorting will be reset
- Entity counts and table GraphQL queries will no longer use a "Vulnerability State" filter, and instead will always contain a filter of `"Image CVE Count:0"`. (This is currently being implemented by the BE.)
- CVE related fields will be hidden from the tables
- The "CVE", "CVE Severity", and "CVE Status" options will be removed from the toolbar
An additional change, since it was discovered during this PR, is that all URL parameter changes on the Workload CVE Overview page are now batched with `"replace"` in places where …

ROX-24183: images without vulns queries

---

ui/apps/platform/src/Components/NotifierConfiguration/NotifierConfigurationForm.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ReportConfiguration.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ReviewConfig.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigWizardForm.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/useFormikScanConfig.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/compliance.scanConfigs.utils.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/emailTemplateFormUtils.ts
ui/apps/platform/src/constants/productBranding.ts
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts

Frontend counterpart to backend #10954
1. Conditionally render reusable elements with `ROX_COMPLIANCE_REPORTING` feature flag.
2. Add compliance email template to utils file.
3. Judgment call to use `notifierConfigurations` instead of `notifiers` in form state to avoid ambiguity with notifiers themselves, especially since there are convert functions.
1. Edit NotifierConfigurationForm.tsx file.
* Replace incorrect specific `deliveryDestinations` with correct generic `fieldIdPrefixForFormikAndPatternFly` prop.
2. Add ReportConfiguration.tsx file.
* Render reusable `NotifierConfigurationForm` element.
3. Edit ReviewConfig.tsx file.
* Conditionally render reusable `NotifierConfigurationView` element.
4. Edit ScanConfigWizardForm.tsx file.
* Conditionally render `ReportConfiguration` element …

ROX-23679: Add delivery destination to scan config in Compliance 2.0

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ObservedCveModeSelect.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DefaultFilterModal.tsx

Updates the Workload CVE page to have a more descriptive header above the table, and moves the Namespace View and Default filter buttons into this header.
The NS view and Default Filter buttons should only be displayed for "Observed" - we need to remove them for Deferred and FP tabs. https://issues.redhat.com/browse/ROX-24318
With CVEs:
Without CVEs:
Feature flag off:

ROX-24182: update workload CVE overview header

---

ui/apps/platform/cypress/integration/vulnmanagement/clusterCves.test.js
ui/apps/platform/cypress/integration/vulnmanagement/clusters.test.js
ui/apps/platform/cypress/integration/vulnmanagement/dashboard.test.js
ui/apps/platform/cypress/integration/vulnmanagement/dashboardToEntityPage.test.js
ui/apps/platform/cypress/integration/vulnmanagement/deployments.test.js
ui/apps/platform/cypress/integration/vulnmanagement/entitypages.test.js
ui/apps/platform/cypress/integration/vulnmanagement/imageComponents.test.js
ui/apps/platform/cypress/integration/vulnmanagement/imageCves.test.js
ui/apps/platform/cypress/integration/vulnmanagement/images.test.js
ui/apps/platform/cypress/integration/vulnmanagement/namespaces.test.js
ui/apps/platform/cypress/integration/vulnmanagement/nodeComponents.test.js
ui/apps/platform/cypress/integration/vulnmanagement/nodeCves.test.js
ui/apps/platform/cypress/integration/vulnmanagement/nodes.test.js
ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
ui/apps/platform/src/routePaths.ts

Updates the Navigation Sidebar and Workload CVE page to conditionally display whether or not VM 2.0 is GA, or tech preview.
With the `ROX_VULN_MGMT_2_GA` flag disabled. Notice the VM 2.0 navigation items, tech preview badges, tech preview banner, and intact VM 1.0 navigation.
With the `ROX_VULN_MGMT_2_GA` flag enabled. The VM 1.0 navigation is removed, VM 2.0 is replaced with just `Vulnerability Management`, and all tech preview designations are gone.

ROX-24078: Update navigation and tech preview status for VM 2.0

---

.github/workflows/scanner-dev-vuln-update.yaml

This fixes the following error:
```
[run-updater](https://github.com/stackrox/stackrox/actions/runs/9195096942/job/25290347930#step:2:1)
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/stackrox/stackrox/.github/actions/download-artifact-with-retry'. Did you forget to run actions/checkout before running your local action?
```
See the CI run for this PR …

fix(ci): fix Scanner dev vuln updates

---

image/templates/helm/stackrox-secured-cluster/templates/collector.yaml

This should prevent the node-inventory container triggering SELinux violations on OpenShift with SELinux enabled.
This has already been tested [with an overlay](https://github.com/stackrox/acs-fleet-manager/pull/1799) in ACSCS in the integration environment.
Testing in ACSCS integration environment.
The [Grafana dashboard](https://grafana-route-rhacs-observability.apps.acs-int-us-01.isbr.p1.openshiftapps.com/d/4032f3c17643119901e107a0a1786d5b9e4c9565/rhacs-dataplane-cluster-metrics?orgId=1) shows no SELinux violations.

ROX-24119: Configure node-inventory container to be privileged

---

.openshift-ci/begin.sh
tests/e2e/run-scanner-v4.sh

Use bigger machine types for worker nodes for the Scanner V4 tests when running on OCP because of the huge resource requirements. 
Just CI.
Verified that the expected machine types are printed to the CI logs.

test(scannerv4): Use e2-standard-16 machines on OCP

---

central/notifiers/acscsemail/client_impl.go

Sets the actual API path matching to the ACSCS service implementation.
Existing CI tests are sufficient. Integration testing with actual ACSCS service will be added once it's ready.

fix: sendMsgPath for acscsEmail integration

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/useClusterVulnerabilities.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/AffectedClustersTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/sortFields.ts

As titled.
Visit a Cluster single page, and verify that the default sort is by CVSS, descending:
Sort ascending:
CVE descending
CVE ascending
CVE status descending
CVE status ascending
CVE type descending
CVE type ascending

ROX-23078: Add sorting to Cluster single page table

---

tests/options_test.go

Added search tag `Image CVE Count` in #11204 but did not update the options map test e2e. This causes CI failure.
Passing CI is enough.
performed …

ROX-24381: Fix TestOptionsMap

---

scripts/ci/metrics.sh

Looking at the `JobName` column, we have:
- `branch-ci-stackrox-stackrox-master-...`
- `branch-ci-stackrox-stackrox-nightlies-...`
- `branch-ci-stackrox-stackrox-release-...`
- `periodic-...` (interop, power, ibm)
- `pull-ci-stackrox-stackrox-master-... `
- `pull-ci-stackrox-stackrox-release-...`
- `rehearse-...`
- `go`
- `go-postgres`
- `local-roxctl-tests`
- `scan-go-binaries`
- `shell-unit-tests`
- `ui`
The current filtering effectively leaves just the top category: `branch-ci-stackrox-stackrox-master-...`. This is too strict.
I guess we want to keep omitting any PR-related jobs, and don't want to report on the release-related jobs either for now.
Instead of just selecting the `-master-` jobs I instead excluded the `-release-` jobs, in order to start reporting on the nightlies.
I also …

tests: Improve query

---

pkg/channelmultiplexer/channelmultiplexer.go
pkg/channelmultiplexer/channelmultiplexer_test.go

The `ChannelMultiplexer` has a context to stop the goroutines that it spawns. Previously the context was hardcoded as `context.Background` making impossible for the consumers of the multiplexer to cancel the goroutines unless all added channels are closed. 
This PR adds an option to the `ChannelMultiplexer` to configure a context so it can be cancelled from the consumer side.
This PR also fixes a leak that could happen if the multiplexer is started but no input is added to the multiplexed channels:
```golang
// This will block indefinitely until something is pushed to the channel `ch` or the channel is closed
for i := range ch {
select {
case <-ctx.Done():
return
case multiplexedStream <- i:
}
```
- ~[ ] Determined and documented …

feat(cm): Add option in the ChannelMultiplexer to configure a context

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ObservedCveModeSelect.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/string.utils.ts

A handful of UX fixes, mostly related to the new "With CVEs"/"Without CVEs" views, that help streamline the difference between the three Vulnerability State tabs and the ability to filter by "with cves"/"without cves".
1. Removes the red "critical" color from the icon in the dropdown, opting for plain black
2. Adjusts the header title and description above the table for all of the three vulnerability state tabs, including removing the default filters and namespace buttons from the Deferred/FP tables.
3. Resets the filters, page, sorting, and current entity tab when switching between the three vulnerability states. With this change and the previous change, this makes the tabs feel more like independent sets of data. Prior to these changes, switching tabs looked like a minor state update, …

ROX-24318: workload CVE ux polish

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/ClustersTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/usePlatformCves.ts
ui/apps/platform/src/Containers/Vulnerabilities/utils/sortFields.ts

Adds sort fields to the Platform CVE Overview page.
Manual verification of the correct sorting parameters being sent over the API:
Default sort of CVE table CVSS descending (data and response are mocked):
CVSS acs:
CVE desc:
CVE asc:
CVE status desc:
CVE status asc:
CVE type desc:
CVE type asc:
Default sort of the Cluster table is be CVE count desc:
CVE count asc:
Cluster desc:
Cluster asc:
Cluster type desc:
Cluster type asc:
k8s version desc:
k8s version asc:

ROX-23059: +ROX-23061 platform CVE sorting

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/DetailsPageHeader.tsx
ui/apps/platform/src/services/ComplianceResultsService.ts

Create a table to display check details results by cluster
Notes:
- That check details modal when clicking on the status will come at a later date. We need to figure out how we are going to pull that info into the `CheckDetailsPage` component. However, we should be able to use the `CheckStatusModal` once we pull that data in.
- Changed error handling so that the table can still be displayed in the off chance that fetching check stats results in an error
- Now we only show the label group for non-zero counts

ROX-24003: Check details table results

---

central/views/imagecve/view_impl.go

The query was split into two parts to improve performance in #11008 : First to get the filtered CVE IDs and the second to get the required details for those CVE IDs. Since first query already returns IDs after applying pagination limit and offset, we do not need to apply them again in the second query.
Manual test to verify that pages > 1 in Workload CVEs view returns …

fix(be): Fix imagecveView not returning results for offsets > 0

---

.github/workflows/scanner-db-init-dump.yaml
.github/workflows/scanner-dev-vuln-update.yaml

Change scanner-related workflows to checkout the source-code to access `./.github/actions/download-artifact-with-retry` introduced by #11019.
Added `pr-scanner-db-init-bundle` and `pr-update-scanner-vulns`, and checked CI results are :heavy_check_mark: 

fix(scanner): Fix download artifact action usage

---

.github/workflows/check-image-vulnerabilities.yml

Add a `FIXED VERSION` column to the output table. This helps release engineers decide what to do with the vulnerabilities. I also filtered out `LOW` severity vulnerabilities.
Example output:
```terraform
Scan results for image: quay.io/rhacs-eng/main:4.3.8-rc.1
(TOTAL-COMPONENTS: 3, TOTAL-VULNERABILITIES: 3, LOW: 0, MODERATE: 2, IMPORTANT: 1, CRITICAL: 0)
+--------------------------------+----------------------+----------------+-----------+---------------+----------------------------------------------------------------------+
|           COMPONENT            |       VERSION        |      CVE       | SEVERITY  | FIXED VERSION |                                 LINK                                 |
+--------------------------------+----------------------+----------------+-----------+-------- …
```

feat(ci): add fixed version to table

---

.tekton/basic-component-pipeline.yaml
.tekton/determine-image-tag-task.yaml
.tekton/main-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml
Makefile
image/rhel/konflux.Dockerfile
image/roxctl/konflux.Dockerfile
operator/konflux.Dockerfile
status.sh

This also addresses ROX-22338.
These aren't relevant and won't be done:

ROX-19958: Adjust Fast Stream builds to be manifest-deployable

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.cy.jsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/useAffectedNodes.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodeCves.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodes.ts
ui/apps/platform/src/Containers/Vulnerabilities/utils/sortFields.ts

Adds sorting to the Node table on the Node CVE single page.
Manual verification that the correct sort parameter is sent over API calls for each field.

ROX-23043: node CVE page sorting

---

central/complianceoperator/v2/rules/datastore/datastore.go
central/complianceoperator/v2/rules/datastore/datastore_impl.go
central/complianceoperator/v2/rules/datastore/datastore_impl_test.go
central/complianceoperator/v2/rules/datastore/mocks/datastore.go
central/complianceoperator/v2/rules/datastore/singleton.go
pkg/search/options.go
pkg/set/set.go

Get Controls by RuleNames.
RuleNames are group by Name, Control and Standard to reduce the number of results. This improves performance later on to enrich API responses, otherwise the results would have been (Standard * Control * Rule Name * Cluster).
Specification:
1. Return all controls, standards and rule names for a list of rule names.
2. Only return distinct results, do not return results per cluster.
Follow-up PR: https://github.com/stackrox/stackrox/pull/11266/files
- Unit tests
- More testing follows with the API implementations

ROX-24374: Get Controls by RuleNames

---

qa-tests-backend/src/test/groovy/TLSChallengeTest.groovy
sensor/common/sensor/central_communication_impl.go
sensor/common/sensor/sensor.go

These are changes I was making when getting familiar with the test while investigating the flakes in ROX-22594. The flakes turned out to have an unrelated cause, but I think these improvements are worth merging anyway.
- improve messages and comments
- use consistent gerund form
- add a couple of log messages
- add a check for multiple clusters
- add comments to messages which are checked by tests
CI is enough.

tests: Improve messages related to ROX-22594.

---

operator/pkg/central/reconciler/reconciler.go
operator/pkg/common/extensions/pause_reconcile.go
operator/pkg/securedcluster/reconciler/reconciler.go

This will allow us to quiesce the operator to not interfere with the manipulations we do during testing.
The annotation seems undocumented for `Central` so I'm not adding docs for this either.

ROX-24404: Support pause-reconcile for SecuredCluster.

---

ui/apps/platform/cypress/integration/vulnmanagement/clusterCves.test.js
ui/apps/platform/cypress/integration/vulnmanagement/clusters.test.js
ui/apps/platform/cypress/integration/vulnmanagement/dashboard.test.js
ui/apps/platform/cypress/integration/vulnmanagement/dashboardToEntityPage.test.js
ui/apps/platform/cypress/integration/vulnmanagement/deployments.test.js
ui/apps/platform/cypress/integration/vulnmanagement/entitypages.test.js
ui/apps/platform/cypress/integration/vulnmanagement/imageComponents.test.js
ui/apps/platform/cypress/integration/vulnmanagement/imageCves.test.js
ui/apps/platform/cypress/integration/vulnmanagement/images.test.js
ui/apps/platform/cypress/integration/vulnmanagement/namespaces.test.js
ui/apps/platform/cypress/integration/vulnmanagement/nodeComponents.test.js
ui/apps/platform/cypress/integration/vulnmanagement/nodeCves.test.js
ui/apps/platform/cypress/integration/vulnmanagement/nodes.test.js
ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationContent.tsx
ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
ui/apps/platform/src/routePaths.ts

An almost total revert of https://github.com/stackrox/stackrox/pull/11220
__Much easier to review with "Hide whitespace" enabled.__
We would like to keep VM 1.0 available in read-only mode during the initial VM 2.0 GA release. This retains the old VM 1.0 dashboard, clearly marked as "Deprecated", so that users can more gradually migrate workflows to VM 2.0.
- Remove the "Risk Acceptance" page and the Observed/Deferred/False Positive CVE lists from VM 1.0 when "ROX_VULN_MGMT_UNIFIED_DEFERRALS" is enabled.
- Remove the "Watch image" functionality from VM 1.0
View the sidebar navigation with `ROX_VULN_MGMT_2_GA` enabled:
View the sidebar navigation with `ROX_VULN_MGMT_2_GA` disabled:

chore(ui): Re-enable VM 1.0 in navigation, mark deprecated

---

ui/apps/platform/src/Components/NotifierConfiguration/NotifierConfigurationForm.tsx
ui/apps/platform/src/Components/NotifierConfiguration/NotifierMailingLists.tsx

Thanks to Brad for careful testing to notice that you cannot delete trailing comma in **Distribution list** text input box.
Because `mailingLists` property has `string[]` type in payload and response, the usual single-source-of-truth principle of React implies on change:
* Call `splitAndTrimMailingListsString` to convert to split and trim string value from `TextInput` element.
* Call `mailingLists.join(', ')` to convert back to string.
Here is the unintended result:
1. As soon as someone types a trailing comma, `splitAndTrimMailingListsString` appends an empty string to the array, and join with `', '` appends a space to the string.
2. A backspace deletes the space, but leaves the comma.
3. The split-join round trip replaces the space.
A hypothetical solution would replace `TextInput` …

ROX-24331: Fix problem with comma in report form mailing lists

---

ui/apps/platform/src/Components/PatternFly/RepeatScheduleDropdown.tsx

Recently, I saw error in browser console while testing improvments to vulnerability reporting.
1. Visit /main/vulnerabilities/reports and then click **Create report**.
2. Fill required fields in step 1 and then click **Next**.
* Before change: see error without `key` prop.
* After change: see absence of error with `key` prop.

ROX-24439: Add key prop for None option in RepeatScheduleDropdown

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersTable.tsx
ui/apps/platform/src/services/ComplianceResultsService.ts

Adds sorting to the Compliance V2 Check Details table
Note: UX shows ability to sort by last scanned time, however this columns is currently unsortable due to our backend search framework. Will revisit this in a later release.
Default (Cluster name, asc):
Reverse (Cluster name, desc):

ROX-24002: Check details sorting

---

scanner/cmd/updater/main.go

Per title. 
Context: https://redhat-internal.slack.com/archives/C033Z8KMZAM/p1716905645750129 …

fix(scanner-updater): double the timeout of the export job

---

sensor/debugger/message/fake.go
sensor/kubernetes/complianceoperator/handler_impl.go
sensor/kubernetes/complianceoperator/handler_impl_test.go
sensor/kubernetes/complianceoperator/updater.go
sensor/kubernetes/complianceoperator/updater_test.go
sensor/kubernetes/complianceoperator/utils.go
sensor/kubernetes/sensor/sensor.go
sensor/tests/complianceoperator/sync_test.go
sensor/tests/complianceoperator/yaml/co-deployment.yaml
sensor/tests/helper/helper.go
sensor/tests/helper/k8s.go

Reconcile ScanConfigs. On sensor-central connection startup the ScanConfigs known by central will be sent to sensor. Upon receiving them, sensor will reconcile any resources (created by ACS) in the cluster.
- ~Depends on #11239~ …

ROX-23788: Reconcile ScanConfigs in sensor

---

ui/apps/platform/src/Containers/VulnMgmt/Entity/Image/VulnMgmtImageOverview.js
ui/apps/platform/src/routePaths.ts

_Easier to review with "Hide whitespace" on_
This removes the Risk Acceptance page and list of CVEs under [VM 1.0 -> Image List Page -> Image Sidebar] when `ROX_VULN_MGMT_UNIFIED_CVE_DEFERRALS` is on. With the exception of "Watch Images", this makes VM 1.0 read-only.
Remove "Watch images" functionality from VM 1.0 when VM 2.0 is GA.
Visit a VM 1.0 image sidebar with the feature flag off. Notice that the list of CVEs is present in the panel, and that "Risk Acceptance" exists in the navigation.
Visit the same sidebar with the feature flag on. The list of CVEs is replaced with an alert, and "Risk Acceptance" is removed from the navigation.
Clicking the link in the alert correctly takes you to the corresponding image single page in VM 2.0.

chore(ui): Remove risk acceptance vm 1.0

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/useNodeVulnerabilities.ts
ui/apps/platform/src/services/types.ts

Adds sorting to the last node/platform cve table - the node single page.
As in previous sorting PRs -- manual verification that the correct parameters are sent to the API when sorting via table headers.

ROX-23052: Add sorting to Node single page table

---

ui/apps/platform/src/routePaths.ts

Fixes missing import due to two PRs being merged to master - one that removed the only call to this function and then a second that added a new call to this function.
Both PRs fully passed CI and were merge-able without conflict, but will result in a failing build.
This should only result in failures on builds of:
- fcdea9f07b8dc9039b1e2ba42c99ec9114bcda34
- 2d8a7ee22a5434502b58581a73bf7bd9d90a9d26
- any commit to `master` before this PR is merged
CI

fix(ui): Add missing import from semantic merge conflict

---

scanner/enricher/nvd/nvd.go

Previously the URL was encoded as follows:
https://services.nvd.nist.gov/rest/json/cves/2.0/?noRejected=&pubEndDate=2020-01-26T23%3A59%3A59Z&pubStartDate=2019-09-29T00%3A00%3A00Z&startIndex=6158&noRejected
Now it's:
https://services.nvd.nist.gov/rest/json/cves/2.0/?pubEndDate=2020-01-26T23%3A59%3A59Z&pubStartDate=2019-09-29T00%3A00%3A00Z&startIndex=6158&noRejected
CI (see label) …

fix(scanner): remove extra noRejected from NVD 2.0 API query

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.constants.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Table/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/compliance.scanConfigs.constants.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/compliance.constants.ts
ui/apps/platform/src/services/ComplianceCommon.ts
ui/apps/platform/src/services/ComplianceResultsService.ts
ui/apps/platform/src/services/ComplianceResultsStatsService.ts
ui/apps/platform/src/types/search.ts

Refactoring done mainly surrounding service calls
Includes:
- Added 3 constants files for default page size and searchable/sortable fields
- `compliance.constants.ts`
- `compliance.coverage.constants.ts`
- `compliance.scanConfigs.constants.ts` 🙃 
- `RawQuery` related service parameters converted to a single object argument
- Safer, harder to mess up order
- Separates unique parameters (`checkName`, `clusterID`, etc) required in the path from the ubiquitous parameters (`page`, `sortOption`, etc) found in the query
- Created a function used to build query parameters for nested RawQuery in compliance requests (@sachaudh)
Oops.. things still seem to work

chore(ui): Refactor compliance service querying

---

central/notifiers/acscsemail/client_impl.go
central/notifiers/acscsemail/client_impl_test.go

We're going to use the service CA operator to generate a CA for the internal emailsender service used by the acscsEmail integration.
I added a configuration to the transport for the acscsEmail http.Client so that we trust those certificates.
Added a unit test that generates a new CA and server certificate and makes sure the function to extend the rootCAs is working properly.

ROX-23253: trust service-ca operator CA in acscsEmail integration

---

sensor/kubernetes/complianceoperator/utils.go
sensor/kubernetes/localscanner/service_certificates_repository.go
sensor/utils/utils.go

Added default stackrox labels to all objects created by Sensor.
Owner References are not supported cross namespace: https://github.com/kubernetes/kubernetes/issues/94631#issuecomment-689201744
- CI

ROX-22547: Add stackrox labels to compliance operator use-cases

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/useAffectedNodes.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodeCves.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodes.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/useClusterVulnerabilities.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/usePlatformCves.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/useAffectedClusters.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/usePlatformCveMetadata.ts
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageResources.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageResources.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/TableEntityToolbar.tsx

Two commits, two cleanups:
1. Remove all cases under **VM 2.0** where we manually reset the `page` when the `perPage` value changes. This happens automatically in the hook call as of 9 months ago.
2. Update signatures of **Node/Platform CVE** custom hooks to prefer a single object instead of positional parameters when the hook expects many parameters with overlapping types
Manual smoke tests of Node and Platform CVE pages.
CI e2e tests.

chore(ui): Node & Platform CVE refactor + cleanup

---

image/rhel/Dockerfile
image/rhel/download.sh

snappy is no longer available. This PR removes it as it may not be required due to removal of rocksdb
- https://github.com/stackrox/stackrox/pull/10875/files
CI

fix: do not install snappy

---

scanner/matcher/updater/vuln/updater.go

We currently only log after the update is imported successfully. This makes it hard to tell which update is currently happening/failed. Adding this log prior to running the update process makes this easier to debug
I didn't …

chore(scanner): log update import prior to attempt

---

CHANGELOG.md

Simply the addition of a changelog entry for slim Collector image deprecation.
None - purely documentation change.

ROX-23155: Add slim/full collector image deprecation notice

---

Makefile
scripts/ci/lib.sh
tools/test/go.mod
tools/test/go.sum

This works, but requires a few more things before merge, see checklist.
One word regarding the false-positive GitGuardian check: it seems to be interpreting a `--secret=blah` flag as if `blah` is a secret string, while in fact in this case `blah` is just a name of a Kubernetes `Secret` resource! I was digging for at least 10 minutes on how to mark this as a false positive in the source code, but came back with nothing. Maybe we're doomed to click the false positive button 🤷🏻 
CI (`*-operator-e2e-tests` jobs) should be enough, with additional manual inspection of loaded data as mentioned in the checklist above.
performed one does not seem sufficient. As a reviewer, you must …

ROX-23308: fetch metrics from image prefetcher

---

ui/apps/platform/package.json
ui/yarn.lock

https://prettier.io/blog/2024/06/01/3.3.0
Update sooner than later to reduce complexity of supporting releases for longer time period.
Here are bug fixes that do not affect current code, but could affect lint for future code.
https://prettier.io/blog/2024/06/01/3.3.0#format-embedded-gql-in-template-literal-statements-16064httpsgithubcomprettierprettierpull16064-by-keithlaynehttpsgithubcomkeithlayne
https://prettier.io/blog/2024/06/01/3.3.0#allow-linebreaks-in-member-expressions-in-template-interpolations-16116httpsgithubcomprettierprettierpull16116-by-bakkothttpsgithubcombakkot
https://prettier.io/blog/2024/06/01/3.3.0#add-missing-parentheses-to-tsinfertype-16031httpsgithubcomprettierprettierpull16031-by-fiskerhttpsgithubcomfisker
2. `yarn build` in …

chore(ui): Update prettier 3.3.0 devDependencies in ui

---

ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviders.tsx

This PR improves the discovery of authn mechanisms within the access control page.
It adds a new info alert which directs users to the documentation of the short-lived token feature as well as the creation of the m2m config.
Additionally, we link our central-login github action for folks to check out.
- see Screenshots

ROX-24176: improve discovery of authn mechanism

---

image/rhel/download.sh

Use the EOL el8 snappy version from the vault instead of picking from el9.

fix: update snappy url

---

ui/apps/platform/package.json
ui/yarn.lock

As suggested in https://issues.redhat.com/browse/ROX-19807 -- an easy change with little (zero?) downside.
Non-functional change

chore(ui): Pin graphql to 16.8.1 instead of 16.0.0

---

pkg/httputil/proxy/config.go

Add the default openshift service we use in OpenShift Auth to the list of default no_proxy targets we have.
N/A.

fix(proxy): add openshift svc to default excludes

---

generated/api/v1/auth_service.swagger.json
generated/api/v1/authprovider_service.swagger.json
generated/storage/auth_provider.pb.go
pkg/auth/authproviders/oidc/backend_impl.go
pkg/auth/authproviders/oidc/backend_impl_test.go
proto/storage/auth_provider.proto

Allow to configure extra scopes within the OIDC auth provider besides the standard `openid profile email` ones.
This allows for custom scopes to be added to allow things like populating the `groups` claim or other specifics.
In addition, the API documentation has been updated to make the `config` field of auth providers more transparent.
- see CI.

ROX-23628: configure extra scopes

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx

As titled.
Visit a Workload CVE Image page and observe the correct default sort:

ROX-24506: Change image page default sort from CVE -> severity

---

.tekton/central-db-pull-request.yaml
.tekton/central-db-push.yaml
.tekton/main-pull-request.yaml
.tekton/main-push.yaml
.tekton/operator-pull-request.yaml
.tekton/operator-push.yaml
.tekton/roxctl-pull-request.yaml
.tekton/roxctl-push.yaml
.tekton/scanner-v4-db-pull-request.yaml
.tekton/scanner-v4-db-push.yaml
.tekton/scanner-v4-pull-request.yaml
.tekton/scanner-v4-push.yaml

ROX-20230: bump image expiration on Konflux to 1 year

---

central/clusterinit/store/postgres/gen.go
central/clusterinit/store/postgres/store.go

Use the cached store for init bundles. Init bundles isn't a high cardinality store and less frequently written to, however quite often read from during the mTLS gRPC interceptor.
It's best to use the cached store for this purpose to lower the potential for latency in requests as well as avoid availablity issues.
N/A.

ROX-20304: cache init bundles

---

central/complianceoperator/v2/scanconfigurations/service/service_impl.go
central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go

CO comes with `default` and `default-auto-apply` scan settings.  As such we cannot use those as names of scan configurations.  This PR blocks that.
provided convince any reviewer …

ROX-24529: compliance disallow default

---

tests/e2e/lib.sh

Per ROX-24404, this is required to stop the operator undoing changes made by tests.
CI - ocp-* is sufficient.

ROX-24404: pause-reconcile for qa e2e tests

---

pkg/features/list.go
tests/e2e/lib.sh

As titled.
This also enables the flag on ocp e2e jobs - so we need to carefully verify that does not cause CI problems for UI e2e tests.
Awaiting CI

chore: Enable VM 2.0 fixability filters flag

---

.github/workflows/build.yaml

These images are built in a separate workflow which can fail so scanning them here is not optimal. ref: https://redhat-internal.slack.com/archives/CLUNQEEMA/p1717611701252899
Note: scanner v2 checks here are OK because the v2 images are copied in this workflow and will exist before the check is tried.
CI

fix(CI): skip v4 check in this workflow

---

operator/Makefile
operator/hack/common.sh
operator/hack/retry-kubectl.sh
operator/tests/central/central-basic/020-verify-password.yaml
operator/tests/central/central-basic/060-use-new-password.yaml
operator/tests/central/central-misc/064-assert-after-unset-expose-monitoring.yaml
operator/tests/common/central-cr-assert.yaml
operator/tests/common/central-cr-with-scanner-v4-assert.yaml
operator/tests/common/delete-central-assert.yaml
operator/tests/common/image-pull-secrets.yaml
operator/tests/common/init-bundle-fetch.yaml
operator/tests/common/monitoring-auth-reader-assert.yaml
operator/tests/common/pods-debug.yaml
operator/tests/common/secured-cluster-cr-assert.yaml
operator/tests/controller/metrics/100-assert-rbac-works.yaml
operator/tests/controller/metrics/100-rbac.yaml
operator/tests/controller/metrics/200-assert.yaml
operator/tests/scripts/validate-crs.sh
operator/tests/securedcluster/sc-basic/040-assert.yaml

This change:
* introduces a wrapper script for kubectl which on failures retries if it finds signs of i/o timeouts in stderr
* uses this script for operator tests
With some luck this will fix flakes such as:
- https://issues.redhat.com/browse/ROX-21559
- https://issues.redhat.com/browse/ROX-22097
- https://issues.redhat.com/browse/ROX-22929
In case it does not solve them, we'll at least get detailed timestamps that will allow us to investigate these timeouts deeper.
- `ci/prow/ocp-4-preview-operator-e2e-tests` failed to create its cluster …

tests: retry kubectl on i/o timeouts

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx

As titled, first of four pages in Workload CVEs that needed to be updated for consistency.
_Better reviewed with "Hide whitespace" on_
Existing e2e tests.
Manual testing of both image and deployment tables to validate the following states:
- Loading
- Error
- Empty
- FilteredEmpty
- Complete

refactor(ui): Update Image CVE page to use TbodyUnified/TableUIState

---

central/notifiers/acscsemail/client_impl.go
central/notifiers/acscsemail/client_impl_test.go
pkg/env/managed.go
pkg/features/list.go

This PR adds two minor changes to the acscsemail integration.
- The feature flag ROX_ACSCS_EMAIL_NOTIFIER is now `true` by default since development of that feature is done, thus going forward only `ROX_MANAGED_CENTRAL` needs to be explicitly set to use the integration
- Remove `.cluster.local` suffix for default emailsender URL because cert generated by service-ca operator does only allow `emailsender.rhacs.svc`. 
- CI is sufficent
provided convince any reviewer or any external reader that you did …

ROX-22376: config changes for acscsemail integration

---

qa-tests-backend/src/test/groovy/K8sRbacTest.groovy

This PR changes the set comparison output as in failures is too big and is not rendered by spock. 
CI
```groovy
import org.javers.core.Javers
import org.javers.core.JaversBuilder
import org.javers.core.diff.ListCompareAlgorithm
import spock.lang.Specification
import spock.lang.Tag
@Tag("BAT")
class Test extends Specification{
def "test"() {
Javers javers = JaversBuilder.javers()
.withListCompareAlgorithm(ListCompareAlgorithm.AS_SET)
.build()
when:
def a = ['a','p','p', 'l', 'e']
def b = ['r','e','d','h','a','t']
def diff = javers.compareCollections(a, b, String)
then:
assert diff.changes.empty, diff.prettyPrint()
}
}
```
```
Condition not satisfied:
diff.changes.empty
|    |       |
|    |       false
|    [ListChange{ property: 'list', …
```

ROX-22885: K8sRbacTest better output

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx
ui/apps/platform/src/services/ComplianceResultsService.ts

Adds sorting and pagination to the Compliance V2 Cluster Details table

ROX-24009: Cluster details sorting and pagination

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx

As titled, updates the Workload CVE Image single page table for consistency.
_Easier to review with "Hide whitespace" enabled_
Existing Cypress tests.
Manual testing of table functionality:
https://github.com/stackrox/stackrox/assets/1292638/9d0c5f21-3f29-4c6b-8ce1-a26a8a422a8f
Test the filtered-empty state and table "Clear filters" action:
Test the empty state by visiting an image with no CVEs:

ROX-24513: Update Image single page to use TbodyUnified

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx

The "fixability filters" flag was recently enabled, which caused these tests to run in CI. It was then discovered that the tests require "unified deferrals" to be enabled as well.
This slipped through CI since UI e2e tests do not run against PRs when a feature flag is changed.
CI

fix: Block "no cves view" tests when unified deferrals flag is off

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigActionDropdown.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigActionsColumn.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Table/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts

Frontend counterpart to #11117
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx#L450-L512
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx#L195-L270
Factor out row actions and **Action** dropdown as sibling files:
* Consistency becomes easier to maintain.
* Data dependencies that were implicit from closure become explicit as props.
Although I considered components subfolder, I decided on same folder as rendering components for visibility.
1. Add ScanConfigActionDropdown.tsx file.
* Adapt from table actions but omit delete action.
ViewVulnReportPage.tsx file was my example. …

ROX-24105: Add interaction for on-demand compliance report

---

ui/apps/platform/cypress/integration/compliance-enhanced/ComplianceEnhanced.helpers.js
ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedScanConfigs.test.js
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPageHeader.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/EditScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Table/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ReportConfiguration.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ReviewConfig.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigOptions.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigWizardFooter.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigWizardForm.tsx

Remove rough edges in user experience before cross-functional acceptance testing.
1. Edit ComplianceEnhanced.helpers.js file.
* Add TODO comments for unused functions that has obsolete assertions.
* Update assertion for **Schedules** heading.
2. Edit CoveragesPageHeader.tsx file.
* Replace **Compliance coverage** with **Coverage** so `h1` element is consistent with link title in left navigation, following the recent pattern in **Vulnerabilities**.
3. Edit EditScanConfigDetail.tsx file.
* Add **Edit** to `h1` element parallel with breadcrumb item to be consistent with **Create** in both.
4. Edit ScanConfigsTablePage.tsx file.
* Replace `TabNavHeader` and `TabNavSubHeader` elements with heading page section for **Schedules** that is parallel with **Coverage**.
5. Edit …

ROX-24463: Improve clarity in compliance schedules

---

central/notifiers/email/email.go
central/notifiers/email/email_test.go

Added closing delimiter `--` for the last iteration in `email.go` for Email MIME. Update unit tests in `email_test.go` to verify the final closing boundary has the following structure: `--boundaryValue--`. Introduce function `obtainLastAndExpectedBoundaryString` to obtain last and expected boundary for tests. Introduce a unit test `TestEmailMsgWithMultipleAttachments` with multiple attachments. Introduce a unit test `TestEmailMsgNoAttachmentsWithLogo` without attachments, but with logo.
Modified the unit test `TestEmailMsgWithAttachment` in `central/notifiers/email/email_test.go` which checks for the close delimiter via `assert.Equal(t, expectedFinalBoundary, lastBoundary)`. Add the check for the tests …

chore(reports): Add close delimiter for Email MIME boundary

---

image/rhel/konflux.Dockerfile

These were copied from downstream dockerfile where they are remnants from some former rocksdb times, I believe.
See
- https://redhat-internal.slack.com/archives/CELUQKESC/p1717439341338869
- https://redhat-internal.slack.com/archives/CELUQKESC/p1717703961788399
These won't be done.
Actually, won't do any this time. I take responsibility to fix any issues in Konflux-built product arising from this.

chore: Stop installing `snappy` and `zstd` in Konflux-built main

---

image/postgres/Dockerfile

There's no need to own executable by `postgres` user, hence removed `chown`.
There's no need to add executable flag because `COPY` statement preserves it and the original file has it, hence removed `chmod`.
I don't think changelog is needed, rest too.
Only CI but it should show if central-db malfunctions.

ROX-20855: Unmark central-db docker-entrypoint.sh as owned by postgres

---

scripts/ci/jobs/ocp_nongroovy_e2e_tests.py

This is in the context of ROX-22594 - [I don't really trust](https://issues.redhat.com/browse/ROX-22594?focusedId=24632449&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24632449) the whole k8s interaction layer underlying qa test suite. Rather than invest time into debugging and fixing groovy code, I'd like to take a step back and use this opportunity to try and port `TLSChallengeTest` to Go (possibly as a baby step towards ROX-9116).
However in order not to lose coverage, we'd have to start running the nongroovy-e2e job against OCP.
I certainly don't expect this job to succeed on the first run, but adding this script is the first prerequisite step towards making this a reality.
Will be tested once [the …

tests: add a script to run nongroovy tests on ocp

---

ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviders.tsx

After introducing the banner about additional information of short-lived access in the access control page when auth providers selected, the banner always showed (i.e. when listing providers as well sa creating them).
During creation the banner is more confusing instead of helpful, so changed the logic to only show when we're listing the providers.
- see CI

fix(ui): show short-lived access banner only in list

---

image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml
image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl
image/templates/helm/stackrox-secured-cluster/templates/collector.yaml.htpl
pkg/features/list.go

This PR adds the `ROX_RUNTIME_FILTERS`  feature flag, the proper name for this is still being discussed but updating shouldn't be too much trouble, so I'm erring on the side of moving things forward. The collector version is also updated to one that can actually use the flag and the helm charts are updated so collector can access the CRI sockets for it to be able to grab the container metadata it needs.
Used roxctl to generate helm charts with and without the feature flag, deployed secured-cluster-servcives with both sets of charts and verified everything worked as expected.
performed one does not seem sufficient. As a …

feat(collector): add runtime configuration feature flag

---

central/processlisteningonport/store/postgres/full_store.go
pkg/protocompat/message.go
pkg/protocompat/nil_test.go
pkg/protoutils/nil_test.go

We have generated methods for marshaling that have better performance thane `proto` version that is based on reflection. Let's use them.
Moved nil tests to a package that is actually tested.
CI

fix: use generated Un/Marshal in protocompat

---

sensor/common/detector/detector.go
sensor/common/networkflow/manager/manager_impl.go
sensor/common/networkflow/manager/manager_impl_test.go

This PR adds a few improvements in how the NetworkFlows are processed:
- The NetworkFlows do not start getting processed after the initial sync is done with k8s.
- The NetworkFlows use the `GetSnapshot` function instead of the `Get` function.
performed one does …

chore(runtime-improvements): NetworkFlow processing improvements

---

central/complianceoperator/v2/scanconfigurations/service/convert.go
central/complianceoperator/v2/scanconfigurations/service/service_impl.go
central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go
central/complianceoperator/v2/scanconfigurations/service/singleton.go

List/Get scan config does not return notifiers attached to the scan config. This PR fixes the bug
It is also acceptable to skip testing for changes that are too taxing to test before merging. In …

ROX-24561: Added notifier in scanstatus

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.constants.ts
ui/apps/platform/src/services/ComplianceCommon.ts
ui/apps/platform/src/services/ComplianceResultsService.ts
ui/apps/platform/src/services/ComplianceResultsStatsService.ts

This PR integrates Advanced Filters into the Compliance Profile Clusters page. After discussions with David Shrewsberry and Brad, I'm also adjusting a few things on the Compliance Profile Checks page.
1. The compliance status dropdown was removed on both pages because it didn't make sense in this context
2. Hooking up URL search to filter API results
3. Adding search filter chips

ROX-24570: Adding table filters to Profile Clusters

---

ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.test.ts
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.css
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/FilterAutocomplete.css
ui/apps/platform/src/Containers/Vulnerabilities/components/FilterAutocomplete.cy.jsx
ui/apps/platform/src/Containers/Vulnerabilities/components/FilterAutocomplete.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/FilterDropdowns.css
ui/apps/platform/src/Containers/Vulnerabilities/searchFilterConfig.ts

Implements advanced filters for the Node CVE single page, as well as the core components to be used throughout VM 2.0
For the `AdvancedFilterToolbar`, I opted to create an entirely new component instead of modify the existing component from Workload CVEs. This will make it easier to swap between the two with a feature flag until the functionality is stable, at which point we can just delete the old components.
Queries are currently mocked for this page, so manually verify the correct values are being sent in the request.
Test clearing query filters:

ROX-23038: search filters node CVE single page

---

central/scannerdefinitions/handler/handler.go

Just moved functions around for (what I believe is) easier file readability. I put related functions closer to each other and put all `get` related functions closer to `get` and `post` related functions closer to `post`. I put the utility functions at the bottom.
This is part 2 of a larger overhaul:
1. https://github.com/stackrox/stackrox/pull/11282
2. This
3. https://github.com/stackrox/stackrox/pull/11283 …

chore(central): move scannerdefinitions funcs for readability

---

ui/apps/platform/src/Components/ExpandRowTh.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx

Adds and implements in VM 2.0 a new component that auto-sets the width on the table header for the column that holds the button to expand a table row. Additionally ensures the `aria-label` prop is set for this otherwise empty header cell.
The width is calculated based on the contents of a `Td` component with the `expand` prop set.
Note that manual widths for other table columns need to be applied to remove this problem completely, but applying this to the first column (that collapses to a width of zero) greatly reduces the impact.
Before:
https://github.com/stackrox/stackrox/assets/1292638/c7bb0cbc-61a1-4d82-88de-b3f4c198a2b9
After:
https://github.com/stackrox/stackrox/assets/1292638/8910c0a0-ccae-41e6-8f08-036775b0432d

fix(ui): Add ExpandRowTh component for table headers

---

sensor/common/compliance/auditlog_manager.go
sensor/common/compliance/auditlog_manager_impl.go
sensor/common/compliance/auditlog_manager_test.go

The test `TestUpdaterSkipsOnOfflineMode` was flaking due to races in the internal ticker. This PR makes the ticker injectable so it can be controlled in the test. It also makes use of the `Stopper` interface instead of the `stopSignals` to manage the stop process.
In addition to reviewing code here, reviewers **must** also review testing and request further testing in case …

ROX-18831: Fix auditlog tests

---

ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedScanConfigs.test.js
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigOptions.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/compliance.scanConfigs.utils.test.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/compliance.scanConfigs.utils.tsx

* Not clear on form that **Time** of scan schedule is UTC.
* To make even less clear, scan schedule details present local times.
* Scan schedule time and **Last run** time need consistent time zone.
* David Shrewsberry confirmed that Central and Compliance Operator interpret `{ hour, minute }` in `scanSchedule` as UTC.
* Replace 12-hour AM/PM which implies local time with 24-hour with UTC.
1. Edit compliance.scanConfigs.utils.tsx file.
* Add `getTimeWithHourMinuteFromISO8601` function for `lastExecutedTime` and `listUpdatedTime` from responses.
* Factor out `getHourMinuteStringForScheduleBase` and `getScheduleBaseForHourMinuteString` functions to convert between `{ hour, minute }` in payload/response and HH:MM string for `TimePicker` element.
* Include **UTC** suffix in …

ROX-24565: Replace local time with UTC in scan schedules

---

ui/apps/platform/src/Containers/Dashboard/SummaryCount.tsx
ui/apps/platform/src/Containers/Dashboard/SummaryCounts.tsx
ui/apps/platform/src/utils/searchUtils.ts

When the `ROX_VULN_MGMT_2_GA` feature flag is enabled, we will navigate to the Images tab in Workload CVEs when the dashboard image summary count is clicked. When the `ROX_VULN_MGMT_2_GA` feature is disabled, we will navigate to the VM 1.0 Image List page when the dashboard image summary count is clicked.
https://github.com/stackrox/stackrox/assets/4805485/e44ec92f-dc1d-414a-a6c2-72ac960a6f6e
https://github.com/stackrox/stackrox/assets/4805485/10cb9246-aa5f-4f8e-9da4-c6091ecbebec

ROX-17542: Updating image summary count link on dashboard to VM 2.0

---

ui/apps/platform/cypress/integration/vulnmanagement/VulnerabilityManagement.helpers.js
ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx

As titled. Removes the old "VM 1.0"/"VM 2.0" naming in the navigation sidebar and replaces both with a single "Vulnerabilities" top level item.
With VM 2 GA, NODE/PLATFORM and UNIFIED_DEFERRALS disabled:
With VM 2 GA, NODE/PLATFORM disabled, and UNIFIED_DEFERRALS enabled:
With VM 2 GA, UNIFIED_DEFERRALS disabled, and  NODE/PLATFORM enabled:
With VM 2 GA disabled, UNIFIED_DEFERRALS and NODE/PLATFORM enabled:
With all feature flags enabled:

ROX-24679: Unify VM 1.0 and VM 2.0 navigation under "Vulnerabilities"

---

.github/workflows/scanner-build.yaml
scanner/Makefile

Separate the Go and image build steps in CI in hopes of speeding things up. This also aligns closer to the main image build step.
This builds the Go binary with `CGO_ENABLED=1` for `amd64`.
This also updates a few make targets:
* `image-scanner` target now only runs the `image/scanner/bin` target outside of CI
* `ossls-notices-no-download` is deleted
* `ossls-notices` now just creates an empty `THIRD_PARTY_NOTICES` directory outside of CI
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/r …

chore(ci): separate scanner go and image build

---

ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsPage.tsx
ui/apps/platform/src/hooks/useURLSearch.ts

When filtering by `Compliance status`, the `ADD` for the select dropdown would not trigger an API call. This PR fixes that issue
https://github.com/stackrox/stackrox/assets/4805485/2fccbb6c-8f79-45b6-9de6-9324df26f944
https://github.com/stackrox/stackrox/assets/4805485/f845f9bd-4b14-43f8-817e-468d527bacc9

fix(ui): Fix compliance status dropdown search

---

scripts/ci/jobs/policy-checks.sh

New version of protobuf does not guarantee that json content will be 100% identical. They add a jitter with number of spaces to force not relaying on it but on content.
This PR fixes this behaviour by ignoring white spaces.
- https://github.com/golang/protobuf/commit/492a476312755200fbec6fb289efcfa9918d228b
CI

fix: policy checks to ignore whitespace difference

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js
ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.test.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/FilterAutocomplete.tsx
ui/apps/platform/src/Containers/Vulnerabilities/searchFilterConfig.ts
ui/apps/platform/src/Containers/Vulnerabilities/searchOptions.ts
ui/apps/platform/src/Containers/Vulnerabilities/types.ts
ui/apps/platform/src/Containers/Vulnerabilities/utils/searchUtils.tsx

Updates the Workload CVE list page to conditionally use advanced filters.
As part of this work the following was needed:
- Slightly relaxed the parsing of search filters to not require strict search term names
- Use this relaxed parsing function throughout Node and Platform CVEs, instead of creating specifics for each of those subsections
- Remove the "Image CVE ID" filter and replace it with "Image CVE Name"
Manual testing.
Updated Cypress tests to account for new filter component. (CI will tests against the old component until the feature flag is enabled. Local run with the new component below).

ROX-24612: workload CVE list advanced filters

---

central/graphql/resolvers/inputtypes/vuln_req_test.go
central/vulnerabilityrequest/utils/util.go
migrator/migrations/m_179_to_m_180_openshift_policy_exclusions/postgres/policy_migrator.go
migrator/migrations/m_192_to_m_193_report_config_migrations/migration_impl.go
migrator/migrations/policymigrationhelper/policy_migrator.go
sensor/common/sensor/central_communication_test.go
sensor/kubernetes/eventpipeline/resolver/resolver_test.go
tools/roxvet/analyzers/donotcompareproto/analyzer.go

This PR fixes calls to `DeepEqual` and `cmp.Equal` on proto objects.
CI

fix: equal calls on proto objects

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts

Replace count from `getComplianceScanConfigurationsCount` call with `totalCount` property in response of `listComplianceScanConfigurations` service function.
Prerequisite for backend team to delete the obsolete endpoint.
1. Edit ScanConfigsTablePage.tsx file.
* Delete `getComplianceScanConfigurationsCount` function call.
* Replace `scanSchedules` with `listData?.configurations` from `listComplianceScanConfigurations` function call.
* Replace `scanSchedulesCount` with `listData?.totalCount` from `listComplianceScanConfigurations` function call.
2. Edit ComplianceScanConfigurationService.ts file.
* Add `ListComplianceScanConfigurationsResponse` type.
https://github.com/stackrox/stackrox/blob/master/proto/api/v2/compliance_scan_configuration_service.proto#L68-L71
* Return both …

ROX-24698: Use totalCount from listComplianceScanConfigurations

---

central/graphql/resolvers/cluster_count_by_platform_type.go
central/graphql/resolvers/platform_cve_core.go
central/graphql/resolvers/platform_cve_core_test.go
central/graphql/resolvers/resolver.go
central/graphql/resolvers/test_setup_utils.go
central/graphql/resolvers/test_utils.go
pkg/metrics/resolver_string.go
pkg/metrics/resolvers.go

Added graphQL resolvers for PlatformCVEs. These resolvers get the data from PlatformCVEView added in PR #10588 
Added unit tests
Manual testing by running graphQL queries
performed testing and you …

ROX-23582: Platform CVEs graphQL resolvers

---

sensor/common/compliance/service.go
sensor/common/compliance/service_impl.go
sensor/common/compliance/service_impl_test.go

Some of the goroutines were not being closed properly in the tests.
Before these changes, if the tests were executed with a high `count`, the tests would fail due to leaked goroutines.
- Note: this is a follow-up of #11457 
performed one does not seem sufficient. …

fix(leak): Fix leak in compliance service

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/AttributeSelector.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/EntitySelector.tsx

This PR will undo the change that allowed us to disable the entity/attribute selectors when there was only one option. There were some concerns about possibly confusing the user with the disabled inputs. They might wonder why they can't open it.

fix(ui): Don't disable the entity/attribute selector

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/deploymentSingle.test.js
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx

Conditionally uses Advanced Filters on the Workload CVE Deployment single page.
Manual verification of the functionality of each filter against the table data.
Existing e2e tests that have been updated for the new components.

ROX-24615: Deployment single page advanced filters

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveSingle.test.js
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx

Updates the Image CVE single page to use advanced filters when the feature flag is enabled.
Manual testing of filtered results.
Updating of existing e2e tests:

ROX-24613: image CVE single advanced filters

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.test.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.constants.ts
ui/apps/platform/src/utils/dateUtils.ts

The following are fixed:
1. Removed the unnecessary Image CVE Type option
2. Duplicate values can't be added to searchFilter
3. Empty values can't be added to searchFilter
4. Applying a search value for the text and autocomplete inputs will clear the input field
5. The date picker should use the format `MM/DD/YYYY` instead of `YYYY-MM-DD` so it aligns with what the backend expects
6. Updating tests

fix(ui): Advanced Filters bug fixes and improvements

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/namespaceView.test.js
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/DeploymentFilterLink.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx

Updates the namespace view to use advanced filters and regex search by default.
Also adds a Cypress test to verify that filters are correctly passed to the overview page and displayed as chips. The move to advanced filters broke this subtly and was not detected.

ROX-24484: Add advanced filters and regex to namespace view

---

image/templates/CHANGING_CHARTS.md
image/templates/helm/shared/templates/02-scanner-05-network-policy.yaml
image/templates/helm/shared/templates/02-scanner-v4-05-db-network-policy.yaml
image/templates/helm/shared/templates/02-scanner-v4-05-indexer-network-policy.yaml
image/templates/helm/shared/templates/02-scanner-v4-05-matcher-network-policy.yaml
image/templates/helm/stackrox-central/internal/config-shape.yaml
image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
image/templates/helm/stackrox-central/templates/00-stackrox-application.yaml
image/templates/helm/stackrox-central/templates/01-central-10-db-networkpolicy.yaml
image/templates/helm/stackrox-central/templates/01-central-10-networkpolicy.yaml
image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml
image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl
image/templates/helm/stackrox-secured-cluster/templates/admission-controller-netpol.yaml
image/templates/helm/stackrox-secured-cluster/templates/collector-netpol.yaml
image/templates/helm/stackrox-secured-cluster/templates/sensor-netpol.yaml
pkg/helm/charts/tests/centralservices/testdata/all-values-explicit.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/central.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/openshift-monitoring.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/monitoring.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/openshift-monitoring.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-slim.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/sensor-netpol.test.yaml

Add the enableNetworkPolicies flag (default true) to the ACS Operator's CentralServices and SecuredClusterServices charts. Disabling it will prevent NetworkPolicy objects from being created.
- ~~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~
- `go test -v github.com/stackrox/rox/pkg/helm/charts/tests/centralservices`
- `go test -v github.com/stackrox/rox/pkg/helm/charts/tests/securedclusterservices`
- CI
performed one does not seem sufficient. As a reviewer, …

ROX-23972: Add enableNetworkPolicies option to Helm charts

---

tests/cluster_delete_test.go
tests/e2e/run.sh

These were initially skipped because I was running out of time. Turns out they actually work, so do not skip them. Except for `TestClusterDeletion`, where `ViolationCount` stays at 2 for some reason which needs to be investigated.
CI.
FTR the nongroovy job for scanner v4 was already [falilng due to ooms](https://issues.redhat.com/browse/ROX-24727) before this change.
The ocp-preview cluster creation permanently fails, unrelated to this change.

test: Enable more nongroovy tests on OCP.

---

sensor/common/component.go
sensor/common/internalmessage/internal_message_pubsub.go
sensor/common/networkflow/manager/manager_impl.go
sensor/common/networkflow/manager/manager_impl_test.go
sensor/kubernetes/listener/resource_event_handler.go
sensor/kubernetes/sensor/sensor.go

Some components don't need to start processing until the k8s resources are done syncing. This PR:
- Enables components to subscribe to a `ResourceSyncFinished` message that will be published when the k8s listeners are done with the initial sync.
- Subscribes the network flows manager to this new message.
In addition to reviewing code here, reviewers **must** also review …

feat(sync-message): Publish resource sync message

---

ui/apps/platform/package.json
ui/yarn.lock

Update with 3 weeks before 4.5 release.
https://docs.cypress.io/guides/references/changelog#13-11-0
* Enhanced the type definitions available to `cy.intercept()` and `cy.wait()`. The body property of both the request and response in an interception can optionally be specified with user-defined types.
https://docs.cypress.io/guides/references/changelog#13-10-0
* Updated js-cookie from 2.2.1 to 3.0.5.
* Updated randomstring from 1.1.5 to 1.3.0
CI

chore(e2e): Update cypress 13.11.0 devDependencies in ui

---

ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedScanConfigs.test.js
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigOptions.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/useFormikScanConfig.tsx

Thank you, David Vail for careful testing to discover the problems.
Thank you, Brad for background info to understand the wizard.
1. Validation error does not appear for leading or trailing spaces in **Name**.
2. Even when validation error for **Name**, the only visual feedback is change of text color from black to red.
Compare to visual feedback that PatternFly `TimePicker` element provides.
3. **Next** button goes to step 2 when **Time** has validation error on step 1.
1. Validation RegExp in `matches` method does not fail, because of `trim` method.
Although yup `trim` is useful for so `required` fails not just for empty string, it does not trim the string in formik state. Therefore, it hides errors unless either frontend or backend code quietly trims strings.
2. PatternFly `TextInput` …

ROX-24737: Fix validation in compliance schedules wizard step 1

---

govulncheck-allowlist.json

Add two new vulns but remove one which is already fixed.
Note: You'll see this step in CI still fail due to CVE-2024-0406. That'll be addressed separately (https://github.com/stackrox/scanner/pull/1544).
CI
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand …

chore(vulns): update vuln list

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ProfileSelection.tsx

During bug bash, I scanned all pages with axe DevTools.
1. /main/compliance/coverage/profiles/profile/checks/check?detailsTab=Results
> ARIA attributes must conform to valid values
`<button type="button" data-ouia-component-type="PF5/TabButton" data-ouia-safe="true" class="pf-v5-c-tabs__link" id="pf-tab-Results-pf-1718214190870qxggf298ymi" aria-controls="pf-tab-section-Results-pf-1718214190870qxggf298ymi" role="tab" aria-selected="true">Results</button>`
aria-controls="pf-tab-section-Results-pf-1718214190870qxggf298ymi"
> ARIA role should be appropriate for element
`<nav class="pf-v5-c-tabs pf-v5-u-pl-md pf-v5-u-background-color-100 pf-v5-u-flex-shrink-0" data-ouia-component-type="PF5/Tabs" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Tabs-1" role="region">`
ARIA role …

ROX-24699: Fix accessibility problems in compliance pages

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageResources.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageResources.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/CvePageHeader.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/SeverityCountLabels.tsx
ui/apps/platform/src/constants/tables.ts

A variety of very small, quick polish fixes from the bug bash. One commit == one fix.
1. Correctly capitalize tooltip for severity counts
3. Make the Pagination on the Deployment page full sized, to match other pages
5. Fix the "double-history" bug on the CVE page, and allow Severity to be sortable
Visit Workload CVEs, click a CVE name in the table. Hitting the back button a single time will return you to the Workload CVE list page. Sortable by Severity below:
7. Fix the action-menu overflow issue that was re-introduced with PF 5
9. Adds fallback text of "unknown" to Image table columns when values are empty
11. Fix the toggling of Resource table expandable sections
13. Add missing `:` character in CVE page header label :) 
See above

fix(ui): workload CVE quick fixes

---

pkg/scannerv4/client/client.go
pkg/scannerv4/client/options.go
scanner/indexer/remote.go
sensor/common/scannerclient/grpc_client.go

The current implementation meant Sensors which used Scanner V4 would continuously print debug logs indicating it is unable to connect to the Scanner V4 Matcher. It also wastes resources attempting to connect to something which we know does not exist. I expect this same thing to happen to Scanner V4 Matcher, as it connects to the Scanner V4 Indexer, which does not implement the Matcher service.
This PR adds an option to the Scanner V4 client to make it clear when only indexing is desired so we do not waste any resources/logging. …

ROX-24281: do not create matcher client if undesired

---

central/image/datastore/fixable_test.go
central/views/imagecve/view_test.go
pkg/env/vulnerability_management.go
pkg/search/postgres/common.go
pkg/search/postgres/joins.go
pkg/search/postgres/select.go

Not proud of this approach. It is just something to patch the leaks until we have a better solution.
`image_cve_edges` table joins `images` and `image_cves` tables. However, there is another way to join `images` and `image_cves` : `images - image_component_edges - image_components - image_component_cve_edges - image_cves`. Now whenever a search query includes fields from both `image_cve_edges` table and one of the component tables, the BFS based SQL query builder ends up building a query where `image_cve_edges` table is joined only on one of `ImageId` or `ImageCveId` but not the other field. This ends up in a situation where cves get mapped to wrong images.
Example:
Consider following data
```
images
-------
sha-1
sha-2
image_cves
------------
cve-1
cve-2
image_cve_edges …
```

ROX-17252: Attempt at temporary fixing data inconsistencies with Image / Image CVE search

---

pkg/testutils/full_init.go
pkg/testutils/full_init_test.go

This PR fixes how proto timestamps are generated. Instead of digging deep into a struct and set every field (which may lead to invalid time) we generate duration that will be added to unix epoch. 
CI

fix: generate a valid time in proto initializer

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/ClustersTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/AffectedClustersTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/searchFilterConfig.ts

As titled.
Also discovered when working this PR - we need a follow up for fixability filters throughout Platform CVEs: https://issues.redhat.com/browse/ROX-24735
Follow up question for UX and PM - Do we need the status filter here? It seems like if we can filter by fixability status per-cluster, we should also show that information in the table.
Clear filters:

ROX-23064: advanced filters platform CVE detail page

---

tests/performance/scale/tests/kube-burner/cluster-density/metrics.yml

Add gathering of `container_memory_working_set_bytes` during kube-burner tests.
We are currently gathering memory RSS. That can be pretty low compared to the threshold where a container will be OOMKilled. WSS is a better representation of this threshold, and we should gather that metric because we can use that value to define Kubernetes container resource requirements/limits.
- ~[ ] Investigated and inspected CI test results~ - changes are not relevant for CI …

chore(performance): Add container memory WSS to kube-burner metrics

---

.tekton/main-build.yaml
.tekton/operator-build.yaml
.tekton/roxctl-build.yaml
.tekton/scanner-v4-build.yaml

| | [f62237f](https://github.com/stackrox/stackrox/pull/11473/commits/f62237ff24ca1dd14b20adc00b890e41f7960cad) - default CPU limits | [e21dca1](https://github.com/stackrox/stackrox/pull/11473/commits/e21dca11f3fc73d0fdf18f4432caee5839c9aa29) - increased CPU limits |
|-|-|-|
| scanner v4 | 8 min | 6 min |
| roxctl | 10 min | 6 min |
| operator | 10 min | 5 min |
`main` is still the bottleneck with 33 minutes build time though.

ROX-23139: bump CPU requests for builds on Konflux

---

ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/ClustersTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/searchFilterConfig.ts

Last one for VM, excluding exception management 🎉 
Follow ups:
It looks like the "Snoozed" filter cannot be removed via the advanced filters dropdown.

ROX-23073: Add advanced filters to Platform CVE cluster page

---

go.mod
go.sum

See https://github.com/stackrox/scanner/pull/1544 for the Scanner-side.
That PR, alone, does not resolve the issue, as the `replace` directive is only used when the affected `go.mod` is the main module. So, we will have to add the `replace` directive here, too.
CI (scan-go-binaries label)
performed one does not …

chore(deps): bump scanner and archiver deps

---

sensor/common/scan/scan.go
sensor/common/scan/scan_test.go

When Delegated Scanning is being used and no integrations are found for registry authentication, a 'no auth' integration is created. If the creation of the 'no auth' integration fails, the associated error was not logged, this PR adds the error to the log message to aid troubleshooting.
Unit tests

ROX-24557: delegated scanning add no auth error to log

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/deploymentSingle.test.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/ConditionNumber.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.test.ts
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.ts

This PR fixes a few Advanced Filters bugs:
1. Change `text` to `autocomplete` for Image Operating System ([jira](https://issues.redhat.com/browse/ROX-24762))
2. Remove `Image Created Time` and `Image Scan Time` ([jira](https://issues.redhat.com/browse/ROX-24758))
3. Remove the term `Image` from `Image CVE` ([jira](https://issues.redhat.com/browse/ROX-24754))
4. Fix issue with unchecking an option in the Checkbox Select ([jira](https://issues.redhat.com/browse/ROX-24753))
5. When using the `condition-number` type for a search, it should not display `undefined` if the condition is not changed at least once ([jira 1](https://issues.redhat.com/browse/ROX-24752)) ([jira 2](https://issues.redhat.com/browse/ROX-24705))
6. Should be able to clear `CVE Snoozed` values from dropdown …

fix(ui): More Advanced Filters Fixes

---

pkg/search/postgres/store.go
pkg/search/postgres/store_cache.go
pkg/search/postgres/store_cache_test.go

This PR adds an optimization to cached datastore stores. Before, we would pass any request with a non-empty `v1.Query` to the underlying store bypassing the cache completely. We do this to let the store evaluate the query. Now, instead of fetching the entire objects from the store, we only fetch the IDs based on the query. The remaining object data is then loaded from the cache. This effectively reduces the network payload between the database and Central when queries are used.
* see tests
* manual testing
performed …

feat(cache): cache payload for query requests

---

.github/workflows/build.yaml

The top-level Makefile contains the following code:
```
ifneq (,$(findstring -debug,$(shell git rev-parse --abbrev-ref HEAD)))
DEBUG_BUILD ?= yes
endif
DEBUG_BUILD ?= no
```
This is supposed to activate debugging builds in case the current branch name contains the string `-debug`. This seems to work reliably for local builds. But, [as documented](https://github.com/stackrox/stackrox/blob/1c13091541b4ec6e47a2198a124fd26bbb5108f1/README.md?plain=1#L525), this feature is also supposed to work in CI, which is currently not the case. The reason being that in CI the checkout is in **detached HEAD mode** and hence the call to `git rev-parse` only returns `HEAD`. A quick research has yielded that there are multiple workarounds and semi-solutions for this, but I haven't found anything that I feel …

fix: Enable debugging builds in GitHub Actions

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/SearchFilterAutocomplete.tsx

Fixes an occasional test flake due to the dropdown state in the autocomplete filter. Thanks to @pedrottimark for catching this in a PR test run.
The cause:
- During tests, sometimes we would enter text into the autocomplete dropdown and then immediately click the "apply" button
- This caused the suggestion dropdown to close, and then open again in 500ms when the debounce callback fired
- In some cases, we would attempt to click an element that was obscured by this dropdown right when the 500ms threshold had elapsed causing a test failure
Example failure:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/11555/pull-ci-stackrox-stackrox-master-ocp-4-12-ui-e2e-tests/1801646444411621376
From the testing I've done, I wasn't able to see a reason for …

fix(ui): Add fix for failing tests due to inconsistent dropdown state

---

tests/roxctl/bats-tests/cluster/scanner-generate.bats
tests/roxctl/bats-tests/local/deployment-bundles-psps.bats

The roxctl bats tests for PSPs contain some bugs. This PR is taking care of them. …

fix(tests): Fix roxctl PSP tests

---

scripts/ci/lib.sh

First run of make do all other stuff causing a lot of output while we are interested in the last line. 
This PR fixes that with `tail -1`
Scale test.
```
/home/janisz/go/src/github.com/stackrox/stackrox/.gotools/bin/prometheus-metric-parser
```
`-B` is used to force rebuild of all required steps
```
make prometheus-metric-parser -B -C . --silent          
+ tools/test/go.sum
+ prometheus-metric-parser
/home/janisz/go/src/github.com/stackrox/stackrox/.gotools/bin/prometheus-metric-parse
```
performed testing and you …

fix: scale test install prometheus-metric-parser

---

.openshift-ci/ci_tests.py
.openshift-ci/post_tests.py
.openshift-ci/tests/test_runners.py
scripts/ci/jobs/gke_scanner_v4_tests.py
scripts/ci/jobs/ocp_scanner_v4_tests.py
tests/e2e/run-scanner-v4.bats
tests/e2e/run-scanner-v4.sh

K8s objects and pod logs can be useful for failure debug, This PR gets them for the scanner-v4 bats e2e test suite.
- Data gathered for each bats test under "Additional Stackrox Artifacts"
- Data gathered for failing bats test

ROX-24284: Get k8s logs from scanner v4 bats tests

---

image/templates/helm/stackrox-secured-cluster/templates/_defaults.tpl
image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/base-config.test.yaml

This PR extends the secured-cluster Helm chart so that a provided central endpoint prefixed with `https://` but without explicit port is treated as having the port `:443` explicitly attached to it.
Manually tested by deploying sensor, providing a central endpoint without explicit port, but with https:// prefix.

ROX-23426: Implement central endpoint port defaulting

---

CHANGELOG.md
roxctl/central/generate/generate.go
roxctl/scanner/generate/generate.go
roxctl/sensor/generate/generate.go
tests/roxctl/bats-tests/cluster/deployment-bundles-psps.bats
tests/roxctl/bats-tests/cluster/scanner-generate.bats
tests/roxctl/bats-tests/local/deployment-bundles-psps.bats

Within the roxctl the different subcommands for generating deployment bundles were defaulting to generate the bundles including PSPs, which is not a reasonable choice anymore.
This PR:
* flips the defaults of these toggles.
* updates the CHANGELOG
* updates the bats tests for roxctl deployment bundles
**Update:** Now depends on https://github.com/stackrox/stackrox/pull/11584.
CI + manually (invoking the different `roxctl generate` commands).

ROX-24399: Disable PSP generation for roxctl deployment bundles

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadCveFilterToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/CVEStatusDropdown.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/searchUtils.tsx

On Platform CVE pages, the CVE status dropdown should filter based on the `Cluster CVE Fixable` field instead of the default `Fixable` field used on Node and Platform CVE pages. This change allows us to specify which field to use as a component prop.
Load a Platform CVE page and use the filter, verifying the correct field in the URL and network request. (Disregard the displayed errors due to unfinished query implementation.)
Load a Workload CVE page and ensure the original "Fixable" filter is visible in the URL and network request:

ROX-24735: Customizable CVE status filter field

---

central/pruning/pruning.go
pkg/search/postgres/common.go

Alert pruning combined all the retention configs into one massive query with 4 separate or clauses.  
```
select alerts.Id::text as Alert_ID 
from alerts 
where (((alerts.LifecycleStage = 0) and (alerts.State = 2) and alerts.Time <= now() at time zone 'utc' - INTERVAL '5 MINUTES')
or ((alerts.LifecycleStage = 2) and alerts.Time <= now() at time zone 'utc' - INTERVAL '5 MINUTES') 
or (alerts.Deployment_Inactive = true and (alerts.LifecycleStage = 2) and alerts.Time <= now() at time zone 'utc' - INTERVAL '5 MINUTES') 
or ((alerts.LifecycleStage = 0) and (alerts.State = 3) and alerts.Time <= now() at time zone 'utc' - INTERVAL '5 MINUTES') 
or ((alerts.LifecycleStage = 2) and (alerts.State = 3) and alerts.Time <= now() at time zone 'utc' - INTERVAL '5 MINUTES'));
```
At scale this resulted …

ROX-24559: pruning alert improvements

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/StatusIcon.tsx

Linda reported distracting first impressions during recent team test:
* Text of tips are redundant for **Pass** and **Fail** status.
* Text of tip for **Manual** status is hard to read with **check** at the beginning and end of the phrase. Especially because **manual check** at the end is the concept to explain.
1. Both `CheckDetailsTable` and `ClusterDetailsTable` render individual status.
2. The `tooltipText` property is required in `statusIconTextMap` object and therefore in **Compliance status** table cell.
1. Edit compliance.coverage.utils.tsx file.
* Replace `tooltipText: string` with `tooltipText: string | null` to make omission of text a visible decision instead of a potentially invisible accident.
* Replace strings with `null` for `PASS` and `FAIL` status.
* Rewrite string for …

ROX-24839: Improve clarity of tooltips for compliance status

---

central/graphql/resolvers/node_cve_core.go
central/graphql/resolvers/node_cve_core_test.go
central/graphql/resolvers/nodes.go

Add node cve count by severity resolver and its test
It is acceptable to assume …

ROX-23382: Add node cve count by severity resolver

---

ui/apps/platform/cypress/integration/compliance-enhanced/ComplianceEnhanced.helpers.js
ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx

Visual counterpart to follow up unify routes in #11114
Some customers misunderstand relationship between Compliance 1.0 and 2.0 as analogous to Vulnerability Management 1.0 and 2.0 (in which 2.0 supersedes and replaces 1.0).
Because of recent change to unify vulnerabilities links with **Dashboard (Deprecated)** under **Vulnerabilities** if all feature flags are turned on, **Dashboard** under **Compliance** contrasts (we hope) so customers do not misunderstand.
1. Edit cypress/integration/compliance-enhanced/ComplianceEnhanced.helpers.js
* Delete **(2.0)** from item text.
2. Edit src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
* Delete divided navigation.
* Comment in initial draft of unified navigation. Sorry about the indentation change!
* Add **Tech preview** for **Coverage** and …

ROX-24843: Unify compliance links in left navigation

---

pkg/booleanpolicy/evaluator/pathutil/augmented_obj_meta.go
pkg/protoreflect/field.go
pkg/search/walker.go

**This is protobuf V2 pre-migration modification!** We have identified a few problems during work on #10951 PR. And we want to move changes that can be done before switching to protobuf V2.
This PR is added logic to ignore (or skip) internal fields generated by proto-generation tools.
In some cases, we are checking if the struct is `proto.Message` to support non-proto structs in walkers.
Only CI pipeline because nothing …

ROX-22019: Skip internal fields used by protobuf framework in walkers

---

central/apitoken/service/service_impl.go
central/apitoken/service/service_impl_test.go

When creating ROX tokens , the order of roles is randomized based on the insert order in the database. Sort Tokens makes them ordered alphabetically.
Changes:
→ Updated the ListAllowedTokenRoles function within the service_impl.go, by including : slices.Sort(result) in order to ensure consistent order of the roles listing.
→ Added a test case: service_impl_test.go to validate the sorting functionality. Utilized mock data and checked that the resulting sorted list matched the expected sorted list.
Confirmed sorting logic by comparing the actual output with an expected result in the test case. …

ROX-22718: Sort Tokens

---

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.helpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approvedDeferralsTable.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approvedFalsePositivesTable.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionDetailsCell.tsx

Fixes the passing of CVE filters from Deferred and FP tabs in Workload CVEs to the Exception Management list page.
This was a simple case of lowercase => uppercase. 💼 
The fix: +5 characters
The tests: +81, -20 lines...
Added e2e tests that cover this functionality.

ROX-24830: Fix passing of CVE filter to exception mgmt list page

---

ui/apps/platform/cypress/integration/vulnmanagement/VulnerabilityManagement.helpers.js
ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx

Reverts the navigation title from "Vulnerabilities" back to "Vulnerability Management".
Existing e2e tests.
Visual inspection:

chore(UI): Revert VM nagivation title change

---

CHANGELOG.md

The current tool used to handle gRPC requests and generate code keeps backward compatibility to return the "error" field next to the "message" field for error messages.
The fields contain the same value: https://github.com/grpc-ecosystem/grpc-gateway/blob/26318a510414ca4d63a664faab34ec717e77d97b/runtime/errors.go#L135
With the new version of gRPC Gateway (v2) this field is dropped. Since we are migrating to a new version of the protobuf framework, we want to also drop this field from responses. …

ROX-24873: Add deprecation notice for error field in error message

---

central/image/service/service_impl.go

When the [Unqualified Search Registries feature](https://github.com/stackrox/stackrox/pull/10351) was added, an optimization was included that cleared the 'Names' field for an image under the assumption that if metadata for the image was nil then the previous names were invalid.
https://github.com/stackrox/stackrox/blob/0b85615b6c41cf53e4ecc3daf3fc30e0f7479c9e/central/image/service/service_impl.go#L336-L339
Although the assumption is true, as deployments scale, sensors restart, new clusters introduced, the same wrong 'name' may appear for an image in the future - which would result in cache misses.  
This can be considered an edge case because in practice there likely would be no 'ID'  for an image (which is required to save the image to central-db) in this scenario unless the pod spec …

ROX-24725: revert names optimization

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/usePlatformCves.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/utils/stringUtils.ts
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/SnoozeCvesModal/SnoozeCvesModal.tsx

Changes required to sync the UI with the production BE GraphQL queries.
Uses build 4.4.x-1011-gd887ad5d6a from https://github.com/stackrox/stackrox/pull/11604 for testing.
Remove all Chrome API stubs and visit the Platform CVE page:
View the Clusters tab:
View "Snoozed" CVEs:
Test other filters:

ROX-24833: Integrate Platform CVE Overview with BE queries

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigActionDropdown.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigActionsColumn.tsx

Request from Doron after watching screen video from Surabhi.
1. Visit /main/compliance/schedules and open a row actions menu.
* Before changes, see **Run scan now** and **Send report now**
* After changes, see **Run scan** and **Send report**
2. Click a link to visit a scan schedule page, and then click **Actions**.
* Before changes, see **Run scan now** and **Send report now**
* After changes, see **Run scan** and **Send report**

ROX-24863: Remove now from Run scan and Send report actions

---

.tekton/basic-component-pipeline.yaml
.tekton/central-db-build.yaml
.tekton/determine-image-tag-task-oci-ta.yaml
.tekton/operator-build.yaml
.tekton/roxctl-build.yaml
.tekton/scanner-v4-db-build.yaml

Pipeline adapted based on https://github.com/konflux-ci/build-definitions/blob/main/pipelines/docker-build-oci-ta/patch.yaml.
This pipeline is used by `central-db`, `operator`, `roxctl`, `scanner-v4-db` - other builds still use the PVC workspace until migrated. 
- `show-summary` removed per https://github.com/konflux-ci/build-definitions/blob/main/pipelines/docker-build-oci-ta/patch.yaml#L120-L126
- added a second custom task that supports OCI TA
- the `.git` & `.prefetch` images will be placed in the same Quay repository as the image (e.g. `quay.io/rhacs-eng/central-db`) and expire at the same time, controlled by `params.image-expires-after` …

ROX-24784: Migrate workspaces to OCI artifacts in Konflux builds

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodeCves.ts

Changes required to sync the UI with the production BE GraphQL queries on the Node CVE Overview page.
Uses build 4.4.x-1054-g98250e1bd8 from https://github.com/stackrox/stackrox/pull/11623 for testing.
Visit Node CVEs:
Nodes tab:
Filters:
Snoozed CVEs:

ROX-24836: Integrate Node CVE overview page with API

---

ui/apps/platform/src/Components/ComplianceUsageDisclaimer.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfilesToggleGroup.tsx
ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx

1. Certain ARIA roles must contain particular children
`<ul class="pf-v5-c-nav__list" role="list">`
Related node
`<li class="pf-v5-c-divider" role="separator"></li>`
2. ARIA attributes must conform to valid values
`<button type="button" data-ouia-component-type="PF5/TabButton" data-ouia-safe="true" class="pf-v5-c-tabs__link" id="pf-tab-E8-pf-1718893766426hxhq5vpnpf7" aria-controls="pf-tab-section-E8-pf-1718893766426hxhq5vpnpf7" role="tab" aria-selected="true">E8</button>`
Invalid ARIA attribute value
`aria-controls="pf-tab-section-E8-pf-1718893766426hxhq5vpnpf7"`
3. Heading levels should only increase by one
`<h4 class="pf-v5-c-alert__title"><span class="pf-v5-screen-reader">Info alert:</span>Usage disclaimer</h4>`
1. This is a generic problem with any divider in left navigation.
Defaults …

ROX-24889: Fix accessibility issues in compliance coverage

---

pkg/features/list.go
sensor/common/detector/enricher.go
sensor/common/detector/enricher_test.go
tools/roxvet/analyzers/validateimports/analyzer.go

Backporting https://github.com/stackrox/stackrox/pull/11359 into the `4.4` release branch
Required manual backport due to merge conflicts.
CI / Unit tests

chore: manually backport #11359 into 4.4 release branch

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.cy.jsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/useNodeCveMetadata.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/useNodeCveSummaryData.ts

Changes required to sync the UI with the production BE GraphQL queries on the Node CVE Single page.
Uses build 4.4.x-1054-g98250e1bd8 from https://github.com/stackrox/stackrox/pull/11623 for testing.
1. This PR splits the metadata hook into two hooks, like done in Platform CVEs, in order to only re-fetch data that is reliant on query filters.
2. This also hooks up the `onClearFilters` button of `<TbodyUnified />` to allow proper clearing of filters via the table.
Visit a Node CVE single page:
Filters:

ROX-24837: Integrate node CVE single page with BE

---

central/graphql/resolvers/cluster_count_by_type.go
central/graphql/resolvers/clusters.go
central/graphql/resolvers/platform_cve_core.go
central/graphql/resolvers/platform_cve_count_by_fixability.go
central/graphql/resolvers/platform_cve_count_by_type.go
central/views/platformcve/db_response.go
central/views/platformcve/empty.go
central/views/platformcve/mocks/types.go
central/views/platformcve/types.go
central/views/platformcve/view_impl.go
central/views/platformcve/view_test.go

- Rename ClusterCountByPlatformType resolver to ClusterCountByType so that it matches the query called by UI implementation
- Add PlatformCVECountByType resolver
- Add PlatformCVECountByFixability resolver
- Unit tests
- Manual tests by calling the newly added queries
performed one does not seem sufficient. …

ROX-23386: Add PlatformCVECountByType and PlatformCVECountByFixability; rename ClusterCountByPlatformType to match UI implementation

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ComplianceProfilesProvider.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPageHeader.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfilesToggleGroup.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ScanConfigurationsProvider.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.routes.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ProfilesTableToggleGroup.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ScanConfigurationSelect.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/hooks/useNavigateWithScanConfig.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/hooks/useScanConfigRouter.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/compliance.scanConfigs.constants.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/compliance.constants.ts
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts
ui/apps/platform/src/utils/searchUtils.ts

- Handles fetching, scan schedule selection, and setting.
- Wraps the entire coverage page, including the ComplianceProfilesProvider.
- Uses `useURLParameter` to track selections and manage the `QueryValue`, converting it to a string or undefined.
- Undefined indicates that all scan schedule results are shown.
- **`createScanConfigFilter`**: creates the `SearchFilter` object using the scan config query (`scanSchedule`)
- **`combineSearchFilterWithScanConfig`**: combines `searchFilter` with `selectedScanConfig`
- **Alphabetized**: Benchmark tabs are now alphabetized with 'Other' remaining at the end

ROX-23689: Compliance scan schedule filter

---

pkg/postgres/pgutils/error.go
pkg/postgres/pgutils/error_test.go
pkg/search/postgres/store_cache.go
pkg/search/postgres/store_cache_test.go

When walking the store cache, we currently do not respect context cancelations. Since we don't control the callback function, this may lead to unexpected runtimes and disregard of timeouts. This PR adds explicit context checks for the cached store to more closely mimmick the behavior of the underlying postgres store.
Additionally, context errors are now classified as non-transient to prevent retry deadlocks. The reason for this change is that after a context deadline is expired, it won't unexpire and the retry will be fruitless.
see unit tests
`roxcurl "/v1/export/vuln-mgmt/workloads?timeout=1"` <-- this would previously get stuck in a 5 minute deadlock due to calling `GetImage` with an expired context. …

fix(store): respect context cancelation

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/deploymentSingle.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/PlatformCvesByStatusSummaryCard.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/CvesByStatusSummaryCard.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/BySeveritySummaryCard.tsx

Updates the text for severity and status summary cards to be less cryptic and to explicitly describe what type of results are hidden, or have a zero count.
e.g.
"Results hidden" => "Critical hidden"
"Results hidden" => "Fixable hidden"
"No results" => "0 Important"
Results with values == 0 and values > 0:
Results with values hidden via filters:

ROX-24858: Replace "No results" text in summary cards

---

ui/apps/platform/src/Containers/Compliance/List/SidePanel.js
ui/apps/platform/src/Containers/Compliance/List/Table.js
ui/apps/platform/src/Containers/Compliance/List/TableGroup.js

1. /main/compliance/clusters/id
`<div class="flex flex-1 items-center pl-4 leading-normal font-700">remote</div>`
2. /main/compliance/clusters/id/controls
`<div class="flex items-center flex-shrink-0 font-700 text-sm p-3 pr-4 opacity-50">122 CONTROLS</div>`
1. Classic `text-primary-700` has insufficient 3.65 color contrast ratio.
2. Small, heavy, and dim: `font-700` `text-sm` `opacity-50`
Was also unique combination of size, weight, and opacity.
1. Replace `text-primary-700` with `pf-v5-u-link-color` utility class.
2. Move and edit TableGroup.js file.
* Render as ordinary text.
* Because `TableGroup` is only for compliance standards, replace generic pluralize of …

ROX-24892: Fix accessibility issues in compliance clusters

---

pkg/httputil/proxy/proxy.go

Sensor during its start synchronizes secrets with the orchestrator. Some types of secrets - `kubernetes.io/dockerconfigjson`, `kubernetes.io/dockerconfig` - contain URLs of registries. In the sync process, those URLs are contacted to store the information about their TLS status. To do that, Sensor calls proxy-aware `Dial` and does TLS `Handshake`. In cases when the destination accepts the connection but never does the handshake (hangs forever), the sync of secrets will freeze and never finish. Sensor would appear healthy, but its data stores will be not fully populated and the state will be corrupted.
At the first glimpse, this is not trivial to spot*, but one of the symptoms is that the node scanning feature would not be able to match the k8s node by name in Sensor (cause the stores are …

ROX-24163: Add timeout to TLS handshake

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.css
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx

This PR makes a few fixes to the CompoundSearchFilter's date-picker input:
1.  Fixes an issue with the "invalid date" error text causing a visual bug
2. Fixes an issue with the "invalid date" error text persisting even after changing the input field value to be the correct format
3. Adding a button to trigger the "onSearch". This fixes an issue where it was searching on every character change while typing into the input field. This is why the button is needed because we need to differentiate between the value in the input field and the value we search on.

ROX-24757: Fix date picker issues

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx

This PR fixes inconsistent results showing up when filtering for the Profile Checks and Clusters tables. Seems like adding additional filters of the same kind (ie. `Profile Check: ocp` then `Profile Check: och`) was not triggering another API call. Made a fix to use the same `onURLSearch` function like we do in the detail pages
https://github.com/stackrox/stackrox/assets/4805485/8f893dc7-0e5d-4aec-83ac-ba4751e89ca1

ROX-24856: Fix inconsistent filtering results in compliance

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/PlatformCvesByStatusSummaryCard.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/PlatformCvesByTypeSummaryCard.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/useClusterSummaryData.ts

Changes required to sync the UI with the production BE GraphQL queries for the Platform CVE Cluster Single page.
Uses build 4.4.x-1011-gd887ad5d6a from https://github.com/stackrox/stackrox/pull/11604 for testing.
Load a Cluster single page (note there is an API bug causing the mismatch in the counts):
Applied filters:

ROX-24835: Platform CVE cluster page integration

---

.github/actions/download-artifact-with-retry/action.yaml
.github/actions/upload-artifact-with-retry/action.yaml
.github/workflows/build.yaml

When checking #11593 I noticed that the download-artifact-with-retry action was not retrying and was not propagating error to its users. This was due to the steps using `name:` as the reference for outcome where it should be `id:`. This also causes the propagation error because the `continue-on-error: true` in the first step is propagated to the action user (`build.yaml` in this case).
- The original forced download failure (missing artifact on #11593) https://github.com/stackrox/stackrox/actions/runs/9573456734/job/26395165226#step:10:25
- Repro with debug commits to force a failure and switched to `id` on this PR. Retry is attempted and failure is propagated: https://github.com/stackrox/stackrox/actions/runs/9603709451/job/26487955525#step:10:1 …

fix(CI): artifact download/upload retry & failure propagation

---

.github/workflows/build.yaml

Per title. See ROX-24132.
- should fail build-and-push-main (STACKROX_BRANDING, *)
- should fail push-main-manifests (STACKROX_BRANDING)
- should still push RHACS_BRANDING manifest image
- should slack failure
- should run e2e tests (requiring RHACS_BRANDING manifest image)
- https://github.com/stackrox/stackrox/actions/runs/9570258114
- https://redhat-internal.slack.com/archives/C068WMY4SEQ/p1718736598588399
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/11593/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1803131900773011456
I had expected the `pre-build-ui` step with STACKROX_BRANDING to fail due to [`75dea4a` (#11593)](https://github.com/stackrox/stackrox/pull/11593/commits/75dea4a91eb49f93cabdab0eb41db3f88c17dc00). But the UI artifact …

ROX-24132: Build manifests if all archs are available per brand

---

ui/apps/platform/package.json
ui/yarn.lock

Update with 1 week before 4.5 release.
https://docs.cypress.io/guides/references/changelog#13-12-0
Bug fixes
* We now trigger `input` and `change` events when typing `{upArrow}` and `{downArrow}` via `.type()` on `input[type=number]` elements.
* Fixed an issue where `inlineSourceMaps` was still being used when `sourceMaps` was provided in a user's TypeScript config for TypeScript version 5.
* Fixed an issue where receiving HTTP responses with invalid headers raised an error. Now Cypress removes the invalid headers and gives a warning in the console with debug mode on.
Dependency updates
* Updated firefox-profile from 4.3.1 to 4.6.0.
* Updated typescript from 4.7.4 to 5.3.3.
* Updated url-parse from 1.5.9 to 1.5.10.
* compliance/complianceDashboard.test.js
* …

chore(e2e): Update cypress 13.12.0 devDependencies in ui

---

pkg/defaults/complianceoperator/files/nist-high-benchmark-revision-4.json

The NIST high and moderate had the same id making it so high was overwritten when we insert the benchmark on startup. This PR fixes this issue by changing the id of NIST high.
- These are the benchmarks in centraldb:
performed one does not seem sufficient. As a …

ROX-24928: Fix duplicated benchmark ids

---

ui/apps/platform/cypress/integration/accessControl/accessControl.helpers.js
ui/apps/platform/cypress/integration/accessControl/accessControlAccessScopes.test.js
ui/apps/platform/cypress/integration/accessControl/accessControlAuthProviders.test.js
ui/apps/platform/cypress/integration/accessControl/accessControlOrigin.test.js
ui/apps/platform/cypress/integration/accessControl/accessControlPermissionSets.test.js
ui/apps/platform/cypress/integration/accessControl/accessControlRoles.test.js
ui/apps/platform/src/Containers/AccessControl/AccessControlDescription.tsx
ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopeFormWrapper.tsx
ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx
ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSetForm.tsx
ui/apps/platform/src/Containers/AccessControl/Roles/RoleForm.tsx

> Page should contain a level-one heading
Apparently `h2` is left over from initial attempt to build side panel in PatternFly.
1. Replace `h2` with `h1` element:
* integration test assertions
* entity page components
2. Replace `h3` with `h2` element in auth provider form.
1. Fix **Heading levels should only increase by one** issues for `Alert` element in a separate contribution.
1. Visit /main/access-control, click **Create auth provider**, and then click **OpenID Connect**.
* Before changes, see accessibility issue.
* After changes, see `h1` instead of `h2` and `h2` element instead of `h3` element.
2. Go back, click **Roles**, and then click a link to visit an entity page.
* After changes, see `h1` instead of `h2` element.
3. Go back, click **Permission sets**, and then click a link to …

chore(ui): Fix accessiblility issues for heading in access control

---

ui/apps/platform/src/Containers/SystemHealth/DiagnosticBundle/FilterByStartingTimeValidationMessage.tsx
ui/apps/platform/src/Containers/SystemHealth/DiagnosticBundle/GenerateDiagnosticBundle.tsx

Remove a left over color contrast issue and solve a unique heading issue as bonus.
> Element has insufficient color contrast of 2.99 (foreground color: #2b9af3, background color: #ffffff, font size: 10.5pt (14px), font weight: normal). Expected contrast ratio of 4.5:1
```html
<div data-testid="starting-time-message" class="">default time: 20 minutes ago</div>
```
> Heading levels should only increase by one
```html
<h6 class="pf-v5-c-popover__title-text"><h2>Diagnostic bundle</h2></h6>
```
1. Info icon color does not have sufficient color contrast ratio for text.
2. Default value of `headerComponent` prop is incorrect for heading hierarchy of page and `h2` element in `headerContent` prop is inconsistently redundant. …

chore(ui): Fix accessibility issue of color contrast in system health

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/sortFields.ts

Removes the ability to sort columns that are unsupported by the API
- Node CVEs list "Affected Nodes" column
- Platform CVEs list "CVE status" column
Fixes sorting of:
- Node CVEs list "Top CVSS" column
Sorting no longer available:
Sort Node CVEs by Top CVSS:

ROX-24922: Fix column sorting for node/platform cves

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx

Fixes an issue where invalid Severity and Status values we applied to the filter chips, and then removed entirely when toggling Snoozed CVEs.
This is due to passing a `QuerySearchFilter` to the toggle button instead of a `SearchFilter`. The former is an object type that represents filter values as they are passed to the API, while the latter is a more general type that represents any user created search object. Since the first is a subset of the second, it is allowed to be passed to this component and is subsequently parsed into a `QuerySearchFilter` a second time, causing the invalid filter chips.
Although this SnoozeButton component is planned for removal, this is an issue that could reappear so we should evaluate alternatives to avoid this happening again in the future.
- Branded, …

ROX-24923: Fix filter handling when toggling snoozed cves

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodesTable.tsx

Connects the "Clear filters" button in the table empty state for the Node CVE overview page and Node CVE single page.
Apply a filter on the following pages that causes a response with zero results:
1. Overview page Node list
2. Overview page CVE list
3. Node single page
Test that "Clear filters" removes the applied filters.

ROX-24924: Implement clearFilters functionality node cve list

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/StatusCountIcon.tsx

Follow up discussion with Maria to display **Manual** counts as bar in graph and column in tables.
* **Pass**: glass full viewpoint
* **Fail** and **Manual**: glass empty viewpoint and indicator of effort
* **Other**: rare
Reorder columns in table consistent with bars in graph.
1. Brainstorm how to reduce duplication of icon and color:
* compliance.coverage.utils.tsx file seems like source of truth
* StatusCountIcon.tsx file
2. Brainstorm pro and con of two naming conventions:
* ComplianceCommon.ts file seems like source of truth: `'PASS'`, `'FAIL'`, `'MANUAL'`, and so on
* ComplianceEnhanced UI has `'pass'`, `'fail'`, `'manual'`, and `'other'` (the latter is frontend only)
3. Limit width of compliance bar in last column?
2. `yarn build` in ui and then compute branch …

ROX-24915: Add manual column in compliance checks and clusters tables

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.tsx
ui/apps/platform/src/Components/PatternFly/SearchFilterChips.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadCveFilterToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx

This PR fixes an issue where the search filter chips displayed the compound search filter's select option value rather than the option label

ROX-24760: Search filter chips for select dropdowns should use labels

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ProfilesTableToggleGroup.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/hooks/useScanConfigRouter.ts
ui/apps/platform/src/Containers/Dashboard/SummaryCounts.tsx
ui/apps/platform/src/utils/searchUtils.ts

This PR preserves the search query params when switching between the "Checks" and "Clusters" view in Compliance Coverage
https://github.com/stackrox/stackrox/assets/4805485/f80d34b7-1667-4dcb-b4b2-5b432c44d37b

ROX-24855: Preserve search query params in Compliance Coverage

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx

This PR adds the ability to specify a default entity for the compound search filter
1)If you tab over to `CVEs`, it will go to `CVE+Name`
2) If you tab over to `Images`, it will go to `Image+Name`
3) If you tab over to `Deployments`, it will go to `Deployment+Name`
https://github.com/stackrox/stackrox/assets/4805485/cd3be122-1554-48f6-b0e3-d592b3a14f1d

ROX-24713: Specify default entity

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPageHeader.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ScanConfigurationsProvider.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ProfilesTableToggleGroup.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ScanConfigurationSelect.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/hooks/useScanConfigRouter.ts
ui/apps/platform/src/services/ComplianceResultsStatsService.ts
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts

Add the scan configurations select component to the compliance details pages.
Notes:
- Scan configurations are now alphabetized in the select component.
- Formatting and filter reset have been added directly to the ScanConfigurationsSelect component.
- Scan configurations unrelated to the current details page will be disabled.
- State has been lifted out of the ScanConfigurationsSelect component.
- A utility function has been created to handle the disabled state.

chore(ui): Add scan config select to details pages

---

qa-tests-backend/src/test/groovy/Services.groovy
qa-tests-backend/src/test/groovy/SummaryTest.groovy

This PR does not fix anything (unfortunately). I just outputs more info to analyze the flake when it happens (and it happens rarely). 
- It was not meant to run on Openshift, but I still gathered some info, so that it could be changed to run there in the future. 

ROX-24364: Add more debug info to the SummaryTest

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/usePlatformCves.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/ClustersByTypeSummaryCard.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/usePlatformCveMetadata.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/usePlatformCveSummaryData.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/searchUtils.tsx

Changes required to sync the UI with the production BE GraphQL queries for the **Platform CVE Single page**.
Uses build 4.4.x-1011-gd887ad5d6a from https://github.com/stackrox/stackrox/pull/11604 for testing.
1. The `usePlatformCveMetadata` hook to fetch page header and summary card data was split into `usePlatformCveMetadata` and `usePlatformCveSummaryData` hooks. Since the summary card data is affected by a change in filters, but the header data isn't, a split here avoids showing more indeterminate loading elements on the page and saves us some additional error handling.
2. Since a Platform CVE's `ID` field is a concatenation of `<CVE Name>`, `#`, `<CVE_TYPE>` we need to encode/decode this value in the URL. Otherwise the browser will interpret the `#` as the fragment identifier of the …

ROX-24834: Integrate Platform CVE single page with GQL queries

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoverageEmptyState.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/StatusCountIcon.tsx

Various fixes for issues found during our bug bash
* Add an empty state page for when no scan schedules have been created.
* Rotate the "Other" status icon. Hamburger icon was causing confusion.
* Differentiate between no results and no results due to filters.

chore(ui): Compliance coverage page bugs

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/AffectedClustersTable.tsx

__Easier to review with "Hide whitespace" on__
Adds the CVE status column to Platform CVE single page clusters.
This uses the same method that is used in Workload CVEs:
1. For a given CVE, fetch all clusters affected by that CVE
2. For each cluster, fetch all vulnerabilities under that cluster, **filtered by the target CVE**
3. If any CVE under the cluster has a `fixedByVersion` that is not `''`, then the CVE is considered fixable for that cluster
Visit a Platform CVE page with clusters that are not fixable:
Compared to data in VM 1.0:
Visit a Platform CVE page with clusters that are fixable (via mock API request). Verify that `fixedByVersion` returns non-empty values in staging.

ROX-24925: Add CVE status column to platform CVE page

---

ui/apps/platform/src/Components/NotifierConfiguration/NotifierConfigurationForm.tsx

As title states. The ACSCS email notifier should show up as an option when the feature flag is turned on in both VM and Compliance reporting.

ROX-24089: Adding acscsEmail type to notifiers filter in reporting

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/StatusCountIcon.tsx

Provide visual contrast between **Other** statuses and **Manual** status to follow up separate counts in #11669
* in tables
* in labels
* it segmented bars (prepare for the next release)
Especially prepare for potential change to segmented bars.
Thank you, Alan and Brad for timely consensus about color:
* `--pf-v5-global--warning-color--100` for check status in tables
* `'gold'` for check count in labels
1. Brainstorm how to reduce duplication of icon and color:
* compliance.coverage.utils.tsx file seems like source of truth
* StatusCountIcon.tsx file
2. Brainstorm pro and con of two naming conventions:
* ComplianceCommon.ts file seems like source of truth: `'PASS'`, `'FAIL'`, `'MANUAL'`, and so on
* ComplianceEnhanced UI has `'pass'`, `'fail'`, `'manual'`, and `'other'` (the latter is …

ROX-24974: Distinguish color of manual status for compliance checks

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/SnoozeCvesModal/SnoozeCvesModal.tsx

Adds telemetry event tracking for Node and Platform CVE global snooze functionality.
_There are currently no e2e tests for Node and Platform CVEs, nor is there an existing precedent for testing telemetry via the UI in automated tests. This should be remedied as part of the requirements for the upcoming e2e tests._
Snooze CVEs on the Node CVE overview page and observe the sent telemetry event:
Snooze CVEs on the Platform CVE overview page and observe the sent telemetry event:

ROX-24972: Add telemetry for Node/Platform global snooze

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageDetails.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/useClusterExtendedDetails.ts
ui/apps/platform/src/configureApolloClient.js

Found one item from the mocks/requirements that was not implemented. This adds the "Cloud provider" to the Cluster details tab if a known cloud provider is detected for the cluster.
Visit Cluster details and see the addition of the cloud provider field.

ROX-24952: Add cloud provider to Platform CVE cluster details

---

ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx

Two tweaks to the filters for Node/Platform CVEs:
1. Remove "CVE snoozed" as an option from the filter bar. This will solely be controlled via the button until we are able to move this to a tab based UX.
2. Remove the `Platform` and `Node` prefixes before `CVE` in the search dropdowns.
Visit Node and Platform CVEs, and verify via the dropdowns:

ROX-24926: Adjust filter bar categories for Node/Platform CVEs

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx

This PR will add sorting by severity for the Deployment Single CVEs table in Workload CVEs.

ROX-24850: Add sorting by severity for Workload CVE Deployment single

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/hooks/useAnalytics.ts

Adds telemetry event tracking for Node and Platform CVE entity tab buttons.
_Node and Platform CVE e2e coming in future PRs. e2e testing for analytics tracking has not been established yet but is on the radar._
Visit Node CVEs and view the automatic event tracking for the default entity tab:
Click the Node tab and view the event tracking:
Refresh in-place and view the automatic event tracking for the navigated-to entity tab:
Repeat the above steps for the Platform CVE page:

ROX-24971: Telemetry for entity tabs

---

CHANGELOG.md

Due to merge conflicts manually backporting https://github.com/stackrox/stackrox/pull/11642 into the 4.4 release branch
👀 📖

chore: backport 11642 to release 4.4

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx

This PR should clear the filters when switching between `Workloads`, `Deferred`, and `False positives` tabs in Workload CVEs single pages (Image CVE, Image, Deployment)

ROX-24851: Filters should not persist between tabs

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx

This PR will filter the results for profile checks and clusters using substring matching

ROX-24857: Use substring matching for checks/cluster names

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx

Colors of icons in status columns and (soon) of bars in chart:
* Pass: primary blue
* Fail: danger red
* Manual: warning yellow
* Other: disabled gray
Colors of bar in **Compliance** column of profiles tables:
* Less than 50% pass: danger red
* Less than 75% pass: warning yellow
* Otherwise: primary blue
1. The thresholds themselves:
* invisible information
* might not be intuitive from customer viewpoint
* might conflict with the spirit of the disclaimer
2. Colors **danger red** and **warning yellow** of bars in table:
* imply incorrect comparison with **Fail** and **Manual** bars in chart
* but correct comparison is with **Pass** bar in chart and **Pass** column in table
1. Functions in compliance.coverage.utils.tsx file:
* `getCompliancePfClassName` function is called by profile …

ROX-24979: Make compliance bar color consistent with pass status

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx

Update Coverage Page Routing
As `ProfileChecksPage` and `ProfileClustersPage` continue to share increasing amounts of code, it makes sense to create a shared component that uses nested routing for the different tables.
Benefits:
* Easier to maintain the shared layouts and data between the components
* Improved performance, unnecessary reinitialization of shared components
* Main page still working as intended.
* Component initialization:
* Before: Changing `ProfilesTableToggleGroup` caused shared components to reinitialize.
* After: Only the components below the Advanced Filter section will reinitialize

chore(ui): Refactor coverage page routing

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPageHeader.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx

Thank you Linda, for noticing inconsistent heading layout.
1. Because `CoveragesPageHeader` did not render `PageSection` element, the heading matches a classic CSS rule.
2. Because `ScanConfigsTablePage` did not render `Title` and `Text` elements in a `Flex` there was not 8px padding between as in most recent page headings.
1. Edit CoveragePageHeader.tsx file.
* Replace utility class padding with `PageSection` element.
* Delete `justifyContent` prop which does not seem to be needed.
2. Edit ScanConfigsTablePage.tsx file.
* Add `Flex` element.
* As bonus, align button center.
1. Visit /main/compliance/coverage
* Before changes, inconsistent heading layout:
* After changes, consistent heading layout:
2. Visit /main/compliance/schedules
* Before changes, inconsistent heading layout:
* After …

ROX-25017: Make Compliance Coverage and Schedules heading consistent

---

.github/workflows/scanner-release-vuln-update.yaml

The `Scanner release vulnerability update` workflow's `upload-release-vulnerabilities` job has been failing due to `No space left on device` or `write /tmp: no space left on device` ([see this one](https://github.com/stackrox/stackrox/actions/runs/9703577065))
This PR removes directories containing 'stuff' that isn't used by the `upload-release-vulnerabilities` job.
The directories were chosen by referencing a few random sources (such as [this](https://github.com/jlumbroso/free-disk-space/blob/main/action.yml) and [this](https://github.com/actions/runner-images/issues/2840#issuecomment-790492173)). Is more cleanup that could be done if more space needed, however these seemed to be the least invasive.
This should, at the time of writing this, free up an additional `~16GB` (almost doubling …

chore: free up GHA disk space for scanner vuln update job

---

central/signatureintegration/datastore/datastore_impl.go
central/signatureintegration/datastore/datastore_test.go
central/signatureintegration/service/service_impl.go
pkg/signatures/cosign_sig_verifier.go

We have the logic to reprocess immediately when signature integrations have changed (i.e. the verification data has changed). Previously this only worked on detecting changes within the
public keys, now that we've added certificate verification we should also reprocess when that is being changed.
Also fixes an issue when using the fulcio roots within a Central container. Fulcio roots are persisted locally, unfortunately in a containerized environment with read-only filesystem this will fail. Again, unfortunately, we will have to set an environment variable to point to a writeable directory, which for the time being is within the `/tmp`.
1. Create signature integration with certificates which is valid for the image you scan.
```json
{
"name": "testing",
"cosignCertificates": [
{ …
```

fix: reprocess when certificates change in signature integration

---

operator/tests/common/central-cr.yaml

This was an accidental change in one of my PRs (#11737 ) that should be reverted. 
It breaks some CI tests.
change me!

ROX-25002: revert accidental central cr change

---

central/graphql/resolvers/search_test.go
pkg/search/postgres/query/map_query.go

The issue occurs when doing a selecting a map type field when all the values of that field are nil. For example, consider that all images in the database have nil labels.  The query `select images.id, images.metadata_v1_labels from images` would return rows where image id is non-empty but labels is nil. The transform function did not handle this case very well and crashed when trying to json unmarshal the nil label. This PR adds some checks to avoid that.
Unit test and manual test

ROX-24721: Fix crash when image labels are nil

---

central/development/service/service_impl.go

Use retryable http client in DevelopmentService to fix issues when badssl.com is down.
CI (nongroovy tests) 

ROX-24295: retry http calls in URLHasValidCert

---

central/metrics/central.go

When working on ROX-24163, we noticed that many k8s events are being processed longer that the highest bucket of the prometheus metric. It was also unclear what is the time unit for the measurement.
This PR improves this area. I decided to add the unit to the description and not to change the metric name (despite prometheus naming convention suggest that), for backwards compatibility with metrics gathered in the past.
- No validation - trivial change

ROX-24163: Improve k8s events metrics

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/SnoozedCveToggleButton.cy.jsx
ui/apps/platform/src/Containers/Vulnerabilities/components/SnoozedCveToggleButton.tsx
ui/apps/platform/src/Containers/Vulnerabilities/hooks/useSnoozedCveCount.ts

Adds an indication that there are snoozed cves by displaying the count in the toggle button, if the count is available and greater than zero.
Automated test changes.
Visit Platform CVEs when no CVEs are snoozed:
Snooze a CVE and observe the change in the button:
View snoozed CVEs and observe the count is removed:
Repeat for the Node CVE page.

ROX-24926: Show snoozed CVE count in button toggle when available

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadCveFilterToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/telemetry.ts
ui/apps/platform/src/hooks/useAnalytics.ts

Adds telemetry for Workload CVE advanced filters.
This also softens the type requirements for the filter events -- rationale will be commented inline.
_Support for verification of telemetry in e2e tests coming soon._
Manual application of filters and verification of sent events for each page.
Workload CVE overview page, verify that all filters are tracked and only filters that are allowed to track values contain the value in the payload.
Perform the same manual checks on:
- Namespace view
- Image single
- Image CVE single
- Deployment single

ROX-24532: Update telemetry for Workload CVEs advanced filters

---

sensor/kubernetes/listener/watcher/crd/crdwatcher_test.go

Wait for resources to be created before asserting to avoid possible races.
I've run the tests multiple times locally.

ROX-24944: Improve crdwatcher unit test

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.constants.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ProfileDetailsHeader.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ProfileStatsWidget.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/StatusCountIcon.tsx

Adds Profile Stats Widget to Coverage Page
* Uses `getComplianceProfilesStats` to fetch check stats on all profiles
* Displays a bar chart for passing, failing, manual, and other check stat percentages
* Heavily resembles widgets from the main dashboard page
Before:
After:

ROX-23690: Profile stats bar chart

---

.github/workflows/check-image-vulnerabilities.yml

The workflow `RELEASE: Check image vulnerabilities` executes scans using `roxctl`, it was recently observed that the results were 'flapping' for a particular vulnerability.  This could be related to a know discrepancy issue when scan data is saved to central DB.  
To reduce the likelihood of this happening, adding the `--force` flag which causes the scan to 'skip' central DB and data pulled directly from Scanner.
It is itself a test
Manually dispatched job from branch: https://github.com/stackrox/stackrox/actions/runs/9715822082

chore: add force flag to check image vulns workflow

---

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/ClustersTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/sortUtils.tsx

Two more, hopefully final, sorting fixes for Node and Platform CVEs:
- Re-add the ability to sort the "Affected nodes" column, using alternative sort parameters (thanks @charmik-redhat )
- Change default sort of Platform CVEs => Clusters table to sort on "Cluster" instead of "CVEs"
Visit Node CVEs and sort by "Affected nodes":
Sort ascending:
Visit Platform CVEs => Clusters and observe the first column, clusters, is the default sort:

fix(ui): Adjust sorting for Node and Platform CVE tables

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ScanConfigurationSelect.tsx

Linda observed that **Reset filter** is enabled for default **All scan schedules**
1. Visit /main/compliance/coverage
* Before changes, see **Reset filter** is enabled (unexpected).
* After changes, see **Reset filter** is disabled (expected).
2. Select a specific scan schedule.
* Before or after changes, see **Reset filter** is enabled (expected).

ROX-25030: Disable reset for all schedules in compliance coverage

---

pkg/httputil/proxy/proxy.go

The call to `http.NewRequest` is not context aware. This PR changes the call and uses `NewRequestWithContext`.
CI should be happy

chore(improvement): Make call to http.NewRequest context aware

---

central/cluster/datastore/datastore_impl.go
image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl
image/templates/helm/stackrox-secured-cluster/values.yaml.htpl
pkg/fixtures/cluster.go
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/admission-control.test.yaml
roxctl/sensor/generate/generate.go

Context on this ticket can be found [in Jira](https://issues.redhat.com/browse/ROX-21288).
The gist is this:
There is a timeout defined for the Admission Controller webhooks. In vanilla K8s this is 30 seconds max, in OpenShift it is hard-coded as "13 seconds".
(When the admission controller webhooks, for whatever reasons, doesn't respond in time it is expected that we fail open.)
But for some reason that we don't understand completely yet, having our webhook timeout being silently capped at 13s causes problems during certain situations -- currently under investigation)
There are reliable data points from the field indicating that setting the webhook timeout to 10s solves these issues.
NOTE: We shall not change the timeout for existing users. This is just updating the default timeout for …

ROX-21288: Adjust default timeout for Admission Controller Webhooks

---

central/vulnmgmt/vulnerabilityrequest/datastore/datastore_impl.go
central/vulnmgmt/vulnerabilityrequest/datastore/datastore_impl_test.go
central/vulnmgmt/vulnerabilityrequest/utils/util.go

On request approval, only v1 approvers were being updated. But when unified cve deferral feature flag is enabled in VM 2.0, v2 approvers list should be updated as well.
Updated unit tests to check for approversv2 field being updated.
Manually tested to see that list of approved vulnerability requests has approversV2 populated.
change me!

ROX-22867: Update ApproversV2 on request approval when unified cve deferral is enabled

---

Makefile
migrator/migrations/m_201_to_m_202_vuln_request_v1_to_v2/migration_test.go

This PR is enabling roxvet `gogoprotofunctions` check on go files with `//go:build sql_integration` tag.
Run `make roxvet` - before and after changes.

chore(fix): Apply gogoprotofunctions roxvet on sql_integration tags

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/SearchFilterAutocomplete.tsx

This PR helps differentiate between autocomplete and text inputs. Alan recommended just adding the search icon and letting the dropdown help differentiate for now. There's no appropriate icon we can use to differentiate right now. This is something we can look into post-release

ROX-24714: Differentiate between autocomplete and text inputs

---

ui/apps/platform/cypress/integration/networkGraph/networkDeploymentSidebar.test.js

Disables this Network Graph e2e test for **non-openshift** clusters. This is due to an issue with gke-latest that causes a misclassification of an internal traffic flow as external traffic. See https://issues.redhat.com/browse/ROX-23907 and https://issues.redhat.com/browse/ROX-24594.
We should be able to remove this skip once https://issues.redhat.com/browse/ROX-24594 is resolved.
Inspect CI results

chore(ui): Disables NetGraph e2e test for GKE clusters

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/AttributeSelector.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/EntitySelector.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/SimpleSelect.tsx

Fixes the layout of the new compound filter bar to prevent the initial dropdowns from shrinking to a width that is less than the width of the displayed text. This cause text truncation and poor UX. The fix is done with `flex-shrink: 0`, to prevent these items from shrinking to accommodate the negative free space of the flex parent.
Visual change that is not something that is typically covered by automated UI tests.
Tested in Firefox and Safari.
Before the change:
After the change:

fix(ui): Prevent filter dropdowns from shrinking below min size

---

ui/apps/platform/src/Containers/VulnMgmt/List/Cves/VulnMgmtListCves.js

Counterpart to https://github.com/stackrox/stackrox/pull/11759 to avoid API error responses via allowed UI actions.
This updates the support matrix of the UNIFIED_DEFERRALS flag, LEGACY_SNOOZE flag, Image CVEs, and Node/Platform CVEs in the following ways in the deprecated VM 1.0 section:
*Ability to View Snoozed CVEs*
- For Image CVEs, only when UNIFIED_DEFERRALS is `false` (same as before this PR)
- For Node/Platform CVEs, _always_ (same as before this PR)
*Ability to mutate Snoozed/Unsnoozed CVEs*
- For Image CVEs, only when UNIFIED_DEFERRALS is `false` (same as before this PR)
- For Node/Platform CVEs, only when LEGACY_SNOOZE is `true` (The only functional change in this PR)
TODO - Which of these do we need for this change?
Image CVEs with
UNIFIED_DEFERRALS enabled:
UNIFIED_DEFERRALS …

fix(ui): Adjust VM 1.0 logic to only allow snooze when FF is enabled

---

ui/apps/platform/src/Containers/Violations/Details/K8sCard.tsx
ui/apps/platform/src/Containers/Violations/Details/NetworkFlowCard.tsx
ui/apps/platform/src/Containers/Violations/Details/ProcessCard.js

> Buttons must have discernable text
```html
<button aria-disabled="false" class="pf-v5-c-button pf-m-plain" type="button" data-ouia-component-type="PF5/Button" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Button-plain-1">
```
To solve this problem, you need to fix at least (1) of the following
* Element does not have inner text that is visible to screen readers
* aria-label attribute does not exist or is empty
* aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
* Element has no title attribute
* Element's default semantics were not overridden with role="none" or role="presentation"
> dl elements must only directly contain properly ordered dt and dd groups, script, template, or div elements
```html
<dl …
```

chore(ui): Fix accessibility issues in Violation tab

---

ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/ClustersTable.tsx

1. Changes the column header of the Clusters Table to "Platform Type" to more accurately reflect the displayed data
2. Adds the "Cluster Platform Type" search field in addition to the "Cluster Type" search field
Verify column header change and addition of "Platform Type" search attribute.

fix(ui): Clarify usage of "Cluster Platform Type" in Platform CVEs

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ReportConfiguration.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ReviewConfig.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/compliance.scanConfigs.utils.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/emailTemplateFormUtils.ts
ui/apps/platform/src/constants/productBranding.ts

Thank you, Surabhi seeing the incorrect text and providing the correct backend templates, which are source of truth for frontend.
1. Edit compliance.scanConfigs.utils.tsx file.
* Replace different names with `reportName` from product branding.
* Replace `customBodyDefault` with `getBodyDefault` function.
* Add `profiles` argument to `getSubjectDefault` function.
https://github.com/stackrox/stackrox/blob/1e6cf12ca1926da6f68e5d933a77cf911bc0d888/central/complianceoperator/v2/report/manager/complianceReportgenerator/consts.go
2. Edit 3 files that need default body for Compliance Report.
* Replace `customBodyDefault` with `getBodyDefault` function.
3. Edit file for Vulnerability Report.
* Revert some of the changes from refactoring, pending investigation whether short name for subject and …

ROX-25031: Correct default body and subject of compliance report

---

pkg/env/tls_handshake.go
pkg/grpc/endpoints.go
pkg/grpc/server.go
pkg/grpc/tls_conn_creds.go
pkg/tlsutils/alpn_demux.go
tests/client_ca_test.go
tests/endpoints_test.go

Calling `tlsConfig.Handshake` may cause the call to block forever - see [ROX-24163](https://issues.redhat.com/browse/ROX-24163). This PR changes all calls to `Handshake()` to `HandshakeContext(ctx)` and applies arbitraty timeout of 2s if no suitable parent context is found.
- existing tests in CI
- deployed to cluster and looked at the logs

ROX-24899: Change all TLS Handshake calls to use context 

---

CHANGELOG.md

This update was overlooked in a previous PR. Explains the implications of the reduced webhook timeout.
This just updates the CHANGELOG.

ROX-21288: Update CHANGELOG regarding the new webhook timeout

---

central/testutils/export.go
roxctl/central/login/login.go
roxctl/central/m2m/exchange/exchange.go
roxctl/central/m2m/exchange/exchange_test.go
roxctl/scanner/downloaddb/downloaddb.go
tests/endpoints_test.go

`jsonpb.Unmarshal` must be used with `AllowUnknownFields: true` to ensure backwards compat with older Sensors.
This PR changes all occurrences of the `jsonpb.Unmarshal` into one that has this field set.
- In CI we trust

ROX-14208: Do not use `jsonpb.Unmarshal` with default options

---

operator/apis/platform/v1alpha1/securedcluster_types.go
operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml
operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml

Reduce default admission controller webhook timeout within operator to 10 seconds
This has been overlooked in a previous PR.
Documentation will be covered in a separate PR.
change me!

fix: Operator: Reduce defaultwebhook timeout to 10 seconds

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodes.ts

Changes the `operatingSystem` field to `osImage` in the Node CVE node list. This shows the actual operating system in use, instead of just "linux", etc.

fix(ui): Swap node cve list from operatingSystem to osImage

---

ui/apps/platform/src/Containers/Vulnerabilities/components/ExceptionRequestModal/ExceptionRequestModal.tsx
ui/apps/platform/src/hooks/useAnalytics.ts

Add telemetry events for when a CVE is Deferred or marked as False Positive.
Defer a CVE and verify that the correct tracking information is sent:
Mark a CVE as False Positive and verify similarly:

ROX-25039: Add telemetry for workload cve exception requests

---

scanner/datastore/postgres/vuln_update.go
scanner/enricher/fixedby/fixedby.go
scanner/mappers/mappers.go
scanner/matcher/updater/distribution/updater.go
scanner/matcher/updater/vuln/updater.go

Was combing through the Scanner V4 code and found a few places I wanted to update:
* Datastore - Figured it'd be nice to log which update operations we no longer track
* Mapper/updater - some code cleanup
1. Deployed the Central cluster with Scanner V4 enabled
2. Found the following logs:
```
{"level":"info","host":"scanner-v4-matcher-7dd46887cb-55rhb","component":"matcher/updater/vuln/Updater.runMultiBundleUpdate","timestamp" …
```

chore(scanner): misc minor cleanup

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/components/NodeComponentsTable.tsx

Fixes the query fields used to determine the fixability and fix version of a node component for a given CVE.
Using one example -- in staging the Node `staging-secured-clust-pnltj-worker-d-qd577` has CVE `RHSA-2024:1897` which is declared to be "Fixable". However expanding the node component list shows all affected components as "Not fixable".
The VM 1.0 Dashboard lists this as "Fixable" as well, but unfortunately does not show the fixability or fix version on a per component level:
It appears the problem is due to the `nodeVulnerabilities.nodeComponents.fixedIn` field of the following query being an empty string:
```graphql
node(id: $id) {
id
nodeVulnerabilities(query: $query, pagination: $pagination) {
cve
summary
cvss
scoreVersion
nodeComponents(query: $query) {
name
source
version …
```

fix(ui): Update query fields used for node component fixability

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx

Linda observed **54 years ago** in **Last scanned** column.
Thank you Brad, for digging me out of a mental ditch.
1. Several teammates observed that 2024 - 54 - 1970 (that is, ~beginning of Unix epoch~ `null` value).
2. ~It seems like initial numeric time is zero for a short time for initial scan~ Initial `lastScanTime` is `null` like `lastExecutedTime` on creation of scan schedule.
3. ~I tested that `new Date(0).toISOString()` is `1970-01-01T00:00:00Z` but compared with `slice(0, 10)` because central usually returns dates with many decimal places for seconds.~
Follow example of conditional rendering for `lastExecutedTime` in compliance schedules
1. Edit getTimeDifferenceAsPhrase file.
* Factor out `getTimeDifferenceAsPhrase` function to encapsulate details, including edge case.
2. …

ROX-25050: Replace temporary null for compliance lastScanTime

---

scanner/enricher/fixedby/fixedby.go
scanner/enricher/fixedby/fixedby_test.go
scanner/enricher/fixedby/versiontype_string.go

Previously, we did not support "package-level fixed by" for the Go stdlib. That's because it was versioned as something like "go1.21.9" (with the "go" prefix). This was seen as an invalid semver.
This PR just truncates that prefix.
CI + tested image quay.io/stackrox-io/scanner:4.2.0 - 
```
{
"name": "stdlib",
"version": "go1.20.4",
"vulns": [
{
"cve": "GO-2023-1878",
"summary": "Insufficient sanitization of Host header in net/http",
"link": "https://go.dev/issue/60374", …
```

ROX-23298: support fixedby for Go stdlib

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ReviewConfig.tsx

Explain both sides of the coin:
* Create: does scan immediately
* Edit: does not scan immediately
1. Visit /main/compliance/schedules, click **Create scan schedule** and move through to **Review** step.
* Before change, without information.
* After change, with information.
**Save for new versus existing scan schedule**
Compliance Operator runs a new scan schedule immediately upon creation, but does not run until scheduled time when you save changes to an existing scan schedule.

ROX-25033: Inform about scan on create but not edit in compliance

---

central/cve/cluster/service/service_impl.go
central/cve/node/service/service_impl.go
central/vulnmgmt/vulnerabilityrequest/service/service_impl.go
central/vulnmgmt/vulnerabilityrequest/service/service_impl_test.go

- In VM 2.0, `ROX_VULN_MGMT_UNIFIED_CVE_DEFERRAL` is enabled by default. The legacy v1 APIs would no longer be compatible with this flag enabled and users must use newly added v2 APIs for deferring CVEs. This change will send an error if v1 APIs are used to defer CVEs.
- In VM 2.0, we do not want users to snooze Node and Platform CVEs by default. If someone wants to use the snooze feature, they must enable the `ROX_VULN_MGMT_LEGACY_SNOOZE` feature flag . This change will prevent users from using the snooze APIs if the feature flag is disabled.
- CHANGELOG will be updated in a separate PR.
Manually verified the change by calling the APIs with both feature flags enabled and disabled. …

ROX-23222 + ROX-20245: Disable VM1.0 deferral/snooze services in VM2.0

---

central/detection/alertmanager/alert_manager_impl_test.go
central/serviceaccount/service/service_impl_test.go
pkg/protomock/mock_matcher.go

This PR is adding a helper function for matching expected `proto.Message` arguments in mock calls.
Unit tests in our CI pipeline.

ROX-22019: Add protomock to check expected proto structs

---

sensor/kubernetes/eventpipeline/resolver/resolver_test.go

Ignore unexported fields as in proto v2 there are some that are different in every object e.g. internal mutex.
This PR also extracts `diff` and use it instead of `cmp.Equal` to compare same objects as current code compares different types slices of structs and strings.
- https://github.com/stackrox/stackrox/pull/3895/files#r1662409083

tests(sensor): ignore unexported fields

---

tests/ca_setup_test.go

As badssl.com is not meant to use in CI and retries does not help with making our test stable lets skip them until we find a better alternative.
change me!

fix(nongroovy): skip SetupCATest

---

pkg/jsonutil/conversion_test.go

This PR is adding a simple test for the existing `OptCompact` flag used in `jsonutil.ProtoToJSON`.
This is important to avoid regressions in protobuf V2 switch.
- executed test locally

chore(test): Add ProtoToJSON OptCompact flag test

---

pkg/protoutils/clone_test.go

This PR is adding safety for protoutils Clone test to ignore internal fields during testing of fields.
This is important for protobuf V2 migration, because internal protobuf framework fields could have different state in cloned proto Message and also they have references that could lead to infinite loops.
Tested on protobuf V2 switch branch and just ported commit to `master`.

chore(test): Ignore internal proto fields for protoutils clone test

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/hooks/useHasRequestExceptionsAbility.ts
ui/apps/platform/src/routePaths.ts

1. Hides the "Node CVEs" navigation item when the user does not have at least READ_ACCESS to the Cluster resource. Node CVE APIs will return an error when this is the case, making the section unusable
2. Hides UI elements that allow deferring CVEs when the user does not have READ_WRITE_ACCESS on the "VulnerabilityManagementRequests" resource
Sadly we do not yet have a way to test different role/permission sets e2e at this point.
View the Navigation with a user that has READ access on "Cluster".
View the Navigation with a user that has NO access on "Cluster".
View the Workload CVE pages with a user that has READ_WRITE access on "VM Requests" and verify exception UI items are present and functional:
View the Workload CVE pages with a user that has less than READ_WRITE access on "VM …

fix(ui): Hide VM 2.0 UI items when insufficient permissions

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPage.tsx

The widget should not be displayed when there are no stats yet available to display.
After immediately creating a scan schedule, while waiting on stats to be available
https://github.com/stackrox/stackrox/assets/61400697/5e506a33-3bb2-424c-bf84-0f0f28e47ac3

fix(ui): Handle widget when stats not available

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/CVEsTable.tsx

In Platform CVE's only we need to pass the CVE ID instead of the CVE name as the path component in the URL due to requirements in the BE API. This fixes the CVE links from the Cluster single page -> Platform CVE single page.
From Platform CVEs navigate to a Cluster single page. In the table, use a CVE link to navigate to the CVE single page. When the page loads, the entirety of the page should render without a perpetual loading component in the header.

fix(ui): Ensure CVE ID is used to create link in Cluster single page

---

central/config/datastore/datastore.go
central/config/datastore/datastore_test.go
central/config/datastore/mocks/datastore.go
central/config/service/service.go

Allow users with read access on VulnerabilityManagementRequests to access /v1/config/private/exception/vulnerabilities API
Bug reporter on UI team deployed PR image twice. First time, they uncovered another problem; second time, issue was finally fixed.

fix(vm): Loosen restriction on GET exception config

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigOptions.tsx

Fixes overlapping error text on the time picker component
The `TimePicker` component currently displays error messages using `position: absolute`. Since we already display helper text under the input field that turns red when there is a Formik error, we can disable the `TimePicker` invalid messages to prevent overlapping. The `TimePicker` component will still display an error status icon when there is an issue with the formatting.
Overlapping text:
Initial view:
After clicking next:
Entering an invalid time:
Entering a valid time:

ROX-25032: Fix overlapping time picker validation

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/types/image.proto.ts

As titled, UI counterpart to https://github.com/stackrox/stackrox/blob/718bbe5634201802d2d696296e114cf835fb7085/proto/storage/image.proto#L150
Allows the UI to use the newly supported Go-lang component source as a filter type:

fix(ui): Add GO component source to UI types

---

sensor/kubernetes/complianceoperator/handler_impl.go

We were passing the ScanSetting to the ScanSettingBinding update function. This led to failures in the updates of ScanSettingBindings.
I'll open a follow-up PR with the automatic tests

chore(fix): Pass the correct obj to the update function

---

sensor/common/centralclient/client_test.go
tests/client_ca_test.go

This PR is adjusting a few tests in preparation for protobuf V2 migration.
1. `sensor/common/centralclient/client_test.go` - since we are loading the certificate from the file and the file has a new line, when that is encoded, new line stays. This value is directly used as Base64, and it is an invalid Base64 format. This is a valid issue. I didn't look into detail why that works with current versions of libraries.
2. `tests/client_ca_test.go` - this is a bit deeper case of protoassert. We should use the provided protobuf functions for comparison.
Local test run for Unit tests
CI pipeline for e2e tests

chore(test): Tweak a few tests to be protobuf V2 compatible

---

sensor/kubernetes/sensor/sensor.go

This information tends to be precious when investigating installation-related customer issues.
Having this directly in the log will improve turnaround times.
Created an OpenShift cluster and deployed sensor to it. Logs contain:
```
kubernetes/sensor: 2024/07/04 07:28:01.501673 sensor.go:81: Info: Loaded Helm cluster configuration with fingerprint "97664b32f9bf952c4680609a2f7d071dd9c76d489573396bb9ec80564d7419b1"
kubernetes/sensor: 2024/07/04 07:28:01.501769 sensor.go:97: Info: Cluster name from Helm configuration: "manual"
kubernetes/sensor: 2024/07/04 07:28:01.501800 sensor.go:100: Info: Install method: "MANAGER_TYPE_KUBERNETES_OPERATOR"
```
Which is as expected.

feat(sensor): Log cluster name and install method

---

qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy

This test fails constantly when run locally on OCP. Let's disable it while we are working on a fix.
I haven't
change me!

ROX-18729: Disable test failing constantly

---

CHANGELOG.md
ui/apps/platform/src/Components/ScannerV4IntegrationBanner.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationPage.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationTiles/ImageIntegrationsSection.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsListPage.tsx

Move Scanner V4 into GA by removing UI labels. Somewhat reverts https://github.com/stackrox/stackrox/pull/10519
See 
TODO

chore(ui): remove tech preview label for Scanner V4

---

central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl.go
central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl_test.go

Let's relax the restriction on having a duplicate profile with a different version, previously we made sure no same profile was run at the same time, even if they have different name, ex. ocp-cis, and ocp-cis-1-5 is not allowed to run at the same time. 
However, the Compliance Operator does not require this, as long as the same name profile is only used once. So we can run ocp-cis with ocp-cis-1-5 and ocp-cis-1-5, but we should not reference ocp-cis in two scans.
change me!

ROX-25099: Relax restriction on profile name duplication

---

scanner/mappers/mappers.go
scanner/mappers/mappers_test.go

Scanner V4 will sometimes return duplicate vulnerabilities for a given package in a given image. This may happen when Claircore matches the same vulnerability entry in a vulnerability data stream twice (for example: matches against two repository names which are associated with the same entry).
This PR is meant to remove those duplicates.
CI + Deployed to an OpenShift cluster:
```
$ roxctl -e <central endpoint> --insecure-skip-tls-verify image scan …
```

ROX-23942: remove duplicate vulns

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.css
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigOptions.css
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigOptions.tsx

This PR fixes an issue caught today where the compound search filter will show the date-picker error message positioned absolutely. This initially fixed a different error ([PR](https://github.com/stackrox/stackrox/pull/11578)), but now it seems hidden behind the search filter chips. The following changes were made to resolve the issue:
1. The CSS was removed that set it to position absolutely
2. Thanks to @bradr5 and @pedrottimark for recommending adding a different CSS styling that does fix the previous issue ([PR](https://github.com/stackrox/stackrox/pull/11578))
3. Removing the absolute positioning will undo a fix that @bradr5 made for his Timepicker in Compliance ([PR](https://github.com/stackrox/stackrox/pull/11859)) so we specifically add the absolute positioning for that …

fix(ui): Fix date picker error text placement

---

central/complianceoperator/v2/scanconfigurations/service/service_impl.go
central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go
central/sensor/service/connection/connection_impl.go
central/sensor/service/connection/connection_test.go
pkg/centralsensor/caps_list.go
scripts/ci/logcheck/restart-ok-patterns.json
sensor/kubernetes/complianceoperator/env.go
sensor/kubernetes/complianceoperator/handler_impl.go
tests/compliance_operator_v2_test.go

Central sends the scan configuration to Sensor on startup (if any).
This feature can be disabled by setting the environment variable`ROX_SYNC_SCAN_CONFIGS_ON_STARTUP` to `false` in sensor.
Note: Since this test scales down sensor, it could happen that collector pods restart. In order to prevent the test for failing due to unexpected collector restarts, I've added an exception for the compliance-e2e tests.
- [1808518704468594688](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/11827/pull-ci-stackrox-stackrox-master-ocp-4-12-compliance-e2e-tests/1808518704468594688) [1808518720402755584](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/11827/pull-ci-stackrox-stackrox-master-ocp-4-15-compliance-e2e-tests/1808 …

ROX-23789: ScanConfig sync in Central

---

qa-tests-backend/src/test/groovy/NodeInventoryTest.groovy

This assertion has been flaky.
Given that violations for images can change often, based on the base image version and current CVEs, it is enough to verify that we have found components to ensure the Node Inventory is working correctly.
change me!
Repeated automated CI tests

ROX-24871: Remove test assertion for checking violations

---

qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy

Per [spec](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting) these default to `Always` which we do not want with image prefetching. https://issues.redhat.com/browse/ROX-24962 is a case where this caused a test failure. This PR sets the default to `IfNotPresent` for qa-e2e-tests.
CI with all-qa label and extra cluster flavors.
Note: because there are no failures there are no pod events captured showing that `:latest` images are not fetched at deploy time but I have faith.

fix(CI): cache images tagged :latest

---

CHANGELOG.md

ROX-25067: deprecate S3 -> GCS interop

---

operator/apis/platform/v1alpha1/central_types.go
operator/apis/platform/v1alpha1/common_types.go
operator/apis/platform/v1alpha1/securedcluster_types.go
operator/bundle/manifests/platform.stackrox.io_centrals.yaml
operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml
operator/config/crd/bases/platform.stackrox.io_centrals.yaml
operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml

The work done in ROX-23972 made the UI look weird; this tries to fix some wording so it looks better.
Before:
TODO - verifying with Marcin best way to validate

ROX-23972: Fix Operator Network descriptions in UI

---

scripts/ci/tools/get-info-about-osci-jobs/get-info-about-osci-jobs.sh
scripts/ci/tools/get-info-about-osci-jobs/get-info-for-shas.sh

Removes the check for the collection method used in CI tests.
~~- [ ] CHANGELOG is updated~~
~~- [ ] Documentation PR is created and linked above~~
Two failures but they don't use the scripts that were modified
Ran 
```
./get-info-for-shas.sh ncommit=4 sha=3c7bc3b7e08d11eeef2122c7b3ea801db4e07599
```

Jv remove get info about osci jobs

---

ui/apps/platform/src/Containers/Compliance/List/Header.js

Inconsistent behavior:
* /main/compliance has export options which include **Download Evidence as CSV** button.
The data exists, because CSV file includes rows for compliance operator standards.
* /main/compliance/controls for standard has export options include **Download Evidence as CSV** button only for 5 built-in standards.
Header.js file assumes only built-in standards in `standardLabel` object.
1. Because `standardId` has `undefined` value:
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Compliance/List/Header.js#L19
Therefore,
* Page header lacks standard name:
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Compliance/List/Header.js#L38
* Export button lacks option: …

ROX-25189: Export evidence for compliance operator standards

---

.github/workflows/scanner-dev-vuln-update.yaml

Otherwise NVD will always download for every PR opened.
Changes to workflow that are executed right away and don't benefit from automated testing.
CI

fix(scanner): Make NVD download conditional

---

ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerConfiguration.tsx
ui/apps/platform/src/Containers/Violations/Details/NetworkPolicies/NetworkPoliciesTab.tsx

Fix existing errors in browser console so it is easier to see recent regressions.
**Problem**
> Encountered two children with the same key, `central-tls`.
> Keys should be unique so that components maintain their identity across updates.
> Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
at dl
at DescriptionList
at ContainerConfiguration
**Analysis**: The `name` of `EmbeddedSecret` objects is not a unique key.
**Solution**: Concatenate `name` and `path` for a unique key.
**Problem**
> Each child in a list should have a unique "key" prop.
> Check the render method of `NetworkPoliciesTab`
**Analysis**: The `key` prop is on a child element for element rendered by `map` method.
**Solution**: Move `key` prop. …

chore(ui): Fix key prop errors in violation details

---

pkg/renderer/kubernetes_helm_test.go
roxctl/helm/output/output_lint_test.go

Printing yamls make a lot of noise in CI output. Let's remove it.
Also warnings from helm prints the whole chart ([example](https://github.com/stackrox/stackrox/actions/runs/9872012673/job/27261202032?pr=11925#step:6:25520)) Let's pass required values so output will be clean.
CI

tests: do not print file content in test

---

qa-tests-backend/src/test/groovy/NodeInventoryTest.groovy

In ROX-24871, we discovered that the original test code to verify the correct functionality of the Node Inventory is flaky.
This was due to the test expecting that each and every scanned node will have an active vulnerability.
Depending on the age of the base image and Scanners CVE  sources, this is not always the case.
In #11865, I removed that assertion and replaced it with an assertion to `getScanTime()`, the idea being that a newly arrived node inventory will result in an updated scan time.
This assertion also was flaky, as our E2E test suite relies on an existing StackRox deployment, which means that a Node Inventory will very likely already exist by the time this test is run. Given that we keep the default rescan interval of 4 hours for a scan, we cannot expect a new scan to arrive …

ROX-24871: Remove flaky scan time assertion

---

scripts/lib.sh
tests/e2e/lib.sh

If we went already as far as a stackrox deployment, then let's wait some more to give central a chance to initialize.
Also, current output is not super intuitive to someone who does not already know this function by heart:
```
INFO: Wed Jul 10 15:31:39 UTC 2024: Waiting for Central to be ready in namespace stackrox
waiting (0/600)
waiting (6/600)
waiting (11/600)
INFO: Wed Jul 10 15:32:25 UTC 2024: Central deployment is ready in namespace stackrox.
INFO: Wed Jul 10 15:32:25 UTC 2024: Waiting for Central API endpoint
INFO: Wed Jul 10 15:32:25 UTC 2024: Found ingress endpoint: 34.66.167.49
INFO: Wed Jul 10 15:32:25 UTC 2024: PING_URL is set to https://34.66.167.49:443/v1/ping
INFO: Wed Jul 10 15:32:28 UTC 2024: Status is now: ok
INFO: Wed Jul 10 15:32:31 UTC 2024: Status is now: ok
..INFO: …
```

ROX-23594: improve wait_for_api output and wait longer

---

.openshift-ci/post_tests.py
scripts/ci/collect-service-logs.sh

This timed out on [two](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-release-4.5-merge-eks-ebpf-qa-e2e-tests/1811048962430341120) [separate](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-release-4.5-merge-eks-qa-e2e-tests/1811048962468089856) EKS cluster jobs when releasing 4.5.
- give it more time in an attempt to succeed
- log actions with timestamps to allow us to find out what takes so long
Example output before this change:
```
16:51:37: Running post command: ['scripts/ci/collect-service-logs.sh', 'stackrox', '/tmp/k8s-service-logs/part-1/k8s-logs']
NAME       STATUS   AGE
stackrox …
```

tests: improve and give collect-service-logs.sh more time

---

.github/workflows/scanner-release-vuln-update.yaml

Release vulns again continue to fail. This time it's because of some invalid VCS information in the Go binary. This PR just leaves that out.
Made this run on my PR prior to merge. Now that NVD API is giving 200s again, looks like it's finally running successfully. https://github.com/stackrox/stackrox/actions/runs/9878607837

ci(scanner): remove vcs information from binary

---

CHANGELOG.md

With the migration to protobuf V2, we also have to migrate to `grpc-gateway` V2. Migration to `grpc-gateway` brings some changes related to error messages. They have unified error messages and simplified handling for them.
We do not have the possibility of replacing the error message format for stream APIs, so we will announce the deprecation of this message and replace it with the next release.
Endpoints are are impacted with this change are:
```
- get /v1/debug/authz/trace
- get /v1/export/deployments
- get /v1/export/images
- get /v1/export/nodes
- get /v1/export/pods
- get /v1/export/vuln-mgmt/workloads
```
Changes in this PR should be part of: This https://github.com/openshift/openshift-docs/pull/78414
If we manage to get changes into …

ROX-24873: Added deprecation message for gRPC stream error fields

---

qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
qa-tests-backend/src/test/groovy/SummaryTest.groovy

kube-proxy pods are only tracked in sensor as static pods if the owner reference is not from a tracked owner (e.g. a Node). When the test retrieves the static pods from the orchestrator, it should check first if the owner is tracked and, if the owner is not tracked, it should check if the pod is a kube-proxy pod.

ROX-25197: Fix kube proxy pod retrieval

---

qa-tests-backend/src/test/groovy/SummaryTest.groovy

We want to gather more data on the failures for this test. Reenabling it after the release was cut, so that we do not add more flakes to handle in the release process.
I have not.
change me!

ROX-24364: Reenable Summary test for counting objects

---

ui/apps/platform/src/Containers/Vulnerabilities/components/ExpandableLabelSection.tsx

This PR does as the title mentions. We want to hide the labels expandable when there are no labels. It looks odd and isn't useful.
Before
After

ROX-25129: Hide label expandable when there are no labels

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/string.utils.ts
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageScanningIncompleteLabelLayout.tsx
ui/apps/platform/src/messages/vulnMgmt.messages.ts

For context about the changes here, check out [this thread](https://redhat-internal.slack.com/archives/C03JMGWJYMD/p1719328756778209).
One line change
Before
After
Before
After

ROX-24951: Update images without vulnerabilities description

---

Makefile

This is a small change to the main Makefile that forwards `SHORTCOMMIT` inside the context of dockerized build. This simplifies building in git worktrees, where git is not available from within the container.
I expect those changes to be no-op in the usual build environment.

build(Makefile): more docker env

---

ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getAffectedNodes.json
ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodeCVEMetadata.json
ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodeCVESummaryData.json
ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodeMetadata.json
ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodeVulnSummary.json
ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodeVulnerabilities.json
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/NodeCve.helpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/cveDetailPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeCvesOverviewPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeDetailPage.test.ts
ui/apps/platform/cypress/selectors/navigation.js

Adds Cypress tests for the top level permissions requires across Node CVE pages.
Note: this includes fixtures for the core graphql requests needed on Node and Node CVE single pages. In the case of the Node CVE single page, we will need to mock requests for **every** test since it is likely that there will be zero Node CVEs in the CI environment.
In the case of the Node single page, there should be at least one node available on all systems so it is likely that we do not need to mock every request. In the initial permissions test, I did mock the response as an empty response to an arbitrary node id would display the "Not found" page in the UI. In this case we are not interested in the data being returned, only that the requests are made that would return _some_ data.
CI

chore(ui): Add permission tests for Node CVE pages

---

.github/workflows/scanner-offline-bundle-update.yaml
.github/workflows/scripts/scanner-update-offline-bundle.sh

`Scanner release offline vulnerability bundle update` was failing because in 4.5 we switched over from a `vulns.json.zst` file to a `vulnerabilities.zip` file. This was not accounted for in the offline vuln updater CI job. See https://github.com/stackrox/stackrox/actions/runs/9893807082/job/27329862714 for an example.
This PR checks for `vulns.json.zst` in 4.4, otherwise `vulnerabilities.zip`.
Made this run on the PR prior to merge. You can see https://definitions.stackrox.io/v4/offline-bundles/scanner-v4-defs-4.5.zip is there, and it did not exist prior to this PR.

fix(scanner): upload correct offline vulns for 4.5+

---

operator/hack/common.sh
operator/hack/operator-midstream.envsubst.yaml

ACS Operator catalog source remains unhealthy when deployed on ocp 4.16 cluster due to podsecurity policy violation.
This PR adds `spec.grpcPodConfig.securityContextConfig` to the operator midstream CR.
Not doing these:
Performed locally on the cluster 

fix(qa): Fix operator deployment on OCP 4.16 ppc64le clusters

---

sensor/common/detector/detector.go
sensor/common/detector/enricher.go
sensor/common/image/service_impl.go
sensor/common/imagecacheutils/common.go
sensor/common/reprocessor/handler.go

This PR creates a type for image cache so when we add generic options the changes will be minimal.
- https://github.com/stackrox/stackrox/pull/11924
CI

chore: extract image cache type

---

ui/apps/platform/cypress/helpers/compoundFilters.ts
ui/apps/platform/cypress/helpers/request.js
ui/apps/platform/cypress/helpers/visit.js
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/NodeCve.helpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/cveDetailPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeCvesOverviewPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeDetailPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/vulnerabilities.selectors.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveSingle.test.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodesTable.tsx

Adds tests asserting the correct filters are present across Node CVE pages.
CI

chore(ui): Add Node CVE tests for available filters

---

ui/apps/platform/src/Containers/Clusters/Components/ClusterSummary.js

Fix existing errors in browser console so it is easier to see recent regressions.
Error in browser console:
> Failed prop type: The prop `clusterRetentionInfo` is marked as required in `ClusterSummary`, but its value is `null`.
1. GET /v1/clusters response includes `clusterIdToRetentionInfo: {}` property for /main/clusters page
2. GET /v1/clusters/id response includes `clusterRetentionInfo: null` property for /main/clusters/id page
My bad, multiple mistakes in `PropTypes.oneOf([PropTypes.shape({}), PropTypes.null]).isRequired`
* `PropTypes` does not have `null` property.
* `oneOf` tests values, not types as intended.
* `PropTypes.object` is more or less `typeof clusterRetendionInfo === 'object'` which includes `null` in JavaScript.
If this `ClusterSummary` component had a future, I would …

chore(ui): Fix PropTypes error for clusterRetentionInfo

---

ui/apps/platform/src/Containers/Compliance/ScanButton.js

Fix existing errors in browser console so it is easier to see recent regressions.
This is a more recent regression that most in the batch of chores.
Error in browser console:
> Failed prop type: The prop `scanInProgress` is marked as required in `ScanButton`, but its value is `undefined`.
Added prop to 2 occurrences of `ScanButton` element in #8957
Which refetch queries:
* https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx#L42-L51
* https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx#L42-L51
But did not add prop to the other 2 occurrences:
* https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Compliance/Ent …

chore(ui): Declare scanInProgress as optional in compliance pages

---

ui/apps/platform/src/Containers/NetworkGraph/components/CIDRFormRow.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceSideBar.tsx
ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx
ui/apps/platform/src/Containers/NetworkGraph/utils/deploymentUtils.ts

**Problem** reported by axe DevTools
**Details** tab of side panel:
> `ul` and `ol` elements must only directly contain `<li>`, `<script>` or `template` elements
Related nodes
```html
<li class="pf-v5-c-divider pf-v5-u-mb-sm" role="separator"></li>
```
**Analysis**
DeploymentDetalis.tsx file:
1. Presentation `<Divider component="li" className="pf-v5-u-mb-sm" />` element is sibling to `DetailSection` items.
2. `DetailSection` items render `h1` instead of `h2` elements.
**Solution**
1. Move `Divider` element into `li` element.
2. Replace `Text` with `Title` and `h1` with `h2` heading level.
**Residue** Investigate why side panel has `role="dialog"` attribute.
**Problem**
> ARIA attributes must conform to valid values
```html
<button type="button" data-ouia-component-type="PF5/TabButton" …
```

chore(ui): Fix accessibility issues in Network Graph tabs and button

---

ui/apps/platform/src/Components/ScannerV4IntegrationBanner.tsx
ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlePage.tsx
ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlesPage.tsx
ui/apps/platform/src/Containers/Collections/CollectionFormModal.tsx
ui/apps/platform/src/Containers/Collections/CollectionsFormPage.tsx
ui/apps/platform/src/Containers/Collections/CollectionsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ComplianceProfilesProvider.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ScanConfigurationsProvider.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigDetailPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigWizardForm.tsx
ui/apps/platform/src/Containers/Dashboard/Widgets/DeploymentsAtMostRisk.tsx
ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicyCategory.tsx
ui/apps/platform/src/Containers/ExceptionConfiguration/useVulnerabilitiesExceptionConfig.ts
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesModal.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/ExceptionRequestModal/ExpiryField.tsx
ui/apps/platform/src/hooks/useRestQuery.ts

Finally have time to take care of a few tech debt items. This PR involves rewording `loading` to `isLoading` to adhere more to the naming conventions we see in libraries like Apollo GraphQL.
It's just a wording change. We will just double-check that all tests pass as usual.
1. Checking that there are no apparent issues in the UI
2. No linting errors

ROX-22865: Change loading to isLoading for useRestQuery

---

qa-tests-backend/src/main/groovy/orchestratormanager/OrchestratorMain.groovy
qa-tests-backend/src/test/groovy/ProcessVisualizationTest.groovy

AKS kube-proxy pods are not tracked as static pods because the owner reference is the kube-proxy DaemonSet and in those cases we only track the DaemonSet. The test needs to assert with the kube-proxy DaemonSet.

ROX-16461: Fix kube-proxy assertion

---

qa-tests-backend/scripts/images-to-prefetch.txt
qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
scripts/ci/lib.sh

This PR allows image-prefetch to override the default imagePullPolicy when it is in use. And sets it to `Never` in that case to help keep the image list in sync with additional images. The quay.io limitation is tracked with ROX-25258.
- fails the test that relies on it [1](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/11915/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1811077422594920448), [2](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/11915/pull-ci-stackrox-stackrox-master-ocp-4-15-qa-e2e-tests/1811077448385695744), with a better failure message [3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/11915/pull-ci-stackrox-stackrox-master-gke-qa-e2e-test …

chore(CI): use pull policy Never to bar prefetch misses

---

image/templates/helm/shared/templates/02-scanner-v4-01-security.yaml
image/templates/helm/shared/templates/02-scanner-v4-07-indexer-deployment.yaml
image/templates/helm/shared/templates/02-scanner-v4-07-matcher-deployment.yaml

Currently the three Scanner V4 pods (indexer, matcher and db) contain security context settings, which render them incompatible with the `restricted-v2` SecurityContextConstraint, instead they are running under the `nonroot-v2` SCC, which is less restrictive than `restricted-v2`.
With certain modifications to the way the containers are set up to run we can satisfy the hardened requirements of `restricted-v2` for `indexer` and `matcher`, but not for `db` (`db` will continue running as `nonroot-v2` for the time being).
As far as I know we currently don't mention the details about the SCC configuration in our documentation. Hence nothing would need to be updated.
CI plus manual tests should be sufficient to test for regressions.
I …

ROX-21117: Restrict Scanner V4 SCCs

---

.github/workflows/scanner-release-vuln-update.yaml

When current workflow fails its not obvious why:
This PR prints the output from `curl`
Dispatched workflow from branch:

chore: Print return code from curl in scanner download nvd workflow

---

qa-tests-backend/src/test/groovy/IntegrationsSplunkViolationsTest.groovy

The `IntegrationsSplunkViolationsTest` has been flaky. 
If we set aside situations where the image pull did not work, most of the flakes can be attributed to missing alerts. 
Splunk Alerts are an integral part of our Splunk TA, therefore we have been asserting on them.
However, we did that in a brittle way.
This PR introduces a more robust way to assert that Splunk generates the required alerts.
The dataflow is as follows: 
Splunk queries ACS for all Violations it knows in regular intervals.
The Violations arrive in Splunk as regular events and are being indexed (query `search sourcetype=stackrox-violations`). 
Every 5 minutes, a Splunk Cronjob runs that converts all indexed Violations into Alerts.
Alerts from any source in Splunk can be queried via a specialized query (query `| from …

ROX-15348: Fix flaky Splunk integration test

---

central/globaldb/metrics/metrics.go
central/globaldb/postgres.go

Adds metrics to report on the number of live and dead tuples.  Being able to view this growth will provide us additionally intelligence on how to tune vacuum jobs as well as when we may need to recommend a manual vacuum.
pulled the artifacts from one of the tests and verified the metrics files that are in the debug/diagnostic bundles.
```
rox_central_postgres_dead_tuples{table="active_components"} 0
rox_central_postgres_dead_tuples{table="active_components_active_contexts_slices"} 0
rox_central_postgres_dead_tuples{table="administration_events"} 1
rox_central_postgres_dead_tuples{table="alerts"} 302
rox_central_postgres_dead_tuples{table="api_tokens"} 3 …
```

ROX-25299:  add metrics to see dead tuple growth

---

central/deployment/cache/cache.go
central/deployment/datastore/datastore.go
central/deployment/datastore/datastore_impl.go
central/deployment/datastore/datastore_test_constructors.go
central/deployment/datastore/singleton.go
central/detection/lifecycle/manager.go
central/detection/lifecycle/manager_impl.go
central/detection/lifecycle/singleton.go
central/networkgraph/flow/datastore/cluster.go
central/networkgraph/flow/datastore/cluster_impl.go
central/networkgraph/flow/datastore/flow_impl.go
central/networkgraph/flow/datastore/singleton.go

DeletedDeployments is used as a naked type of expiring cache. It alsos stores boolean (always true). In this PR I've changed it store an empty struct to reduce used memory and exposed a smaller interface.
CI

chore: custom struct for deleted deployment

---

ui/apps/platform/src/Containers/Risk/riskTableColumnDescriptors.js

> Scrollable region must have keyboard access `<div class="rt-table" role="grid">`
https://dequeuniversity.com/rules/axe/4.9/scrollable-region-focusable?application=AxeChrome
Classic routes that render tables have `onRowClick` event handler:
* which does not have associated keyboard action
* which is probably invisible to screen readers
Add in name column a link to open the side panel.
1. After we finish this batch of accessiblity issues, adjust style rules to render links with PatternFly style in classic tables.
1. Visit /main/risk.
* Before changes, see presence of accessibility issue.
If the number of deployments is low enough that there is no scrollbar, reduce the height of the page until scrollbar appears.
See tab key navigation skips the table.
* After changes, see absence of …

chore(ui): Add links to risk for keyboard accessibility

---

ui/apps/platform/src/Containers/AccessControl/AuthProviders/RuleGroups.tsx

We've received feedback in the past that the custom rule keys select box, which also supports adding custom options, isn't as obvious that it does support this.
The PR improves the helper texts and placeholders around that, and we'll see whether that will improve the solution. We decided against doing a
custom component for this one as depicted in the mocks regarding the complexities it will increase within the formik for the rules.
Empty fields:
Choosing existing key:
Creating a custom key:
N/A.
performed testing …

ROX-24255: improve custom rule keys UX

---

ui/apps/platform/cypress/integration/networkGraph/networkDeploymentSidebar.test.js

The collector and maple teams have [resolved the issue](https://issues.redhat.com/browse/ROX-23907) causing this test failure on GKE, so let's re-enable it.
- CI
- monitor nightly CI results

ROX-25038: Re-enables the NetGraph sidebar test on GKE clusters

---

ui/apps/platform/src/Containers/Integrations/IntegrationTiles/NotifierIntegrationsSection.tsx

Fix existing errors in browser console so it is easier to see recent regressions.
**Problem**
Error in browser console:
> Each child in a list should have a unique "key" prop.
> heck the render method of `NotifierIntegrationsSection`.
**Analysis**: `<></>` in `map` method does not have `key` prop.
**Solution**
https://react.dev/reference/react/Fragment#rendering-a-list-of-fragments
> Here’s a situation where you need to write Fragment explicitly instead of using the `<></>` syntax. When you render multiple elements in a loop, you need to assign a key to each element. If the elements within the loop are Fragments, you need to use the normal JSX element syntax in order to provide the key attribute.
1. Visit …

chore(ui): Fix key prop errors in notifier integrations

---

pkg/protoconv/time_test.go

This PR adds test coverage for specific `protoconv` time functions. This is important to protbuf V2 migration because protobuf V2 framework does not include validation, and it has to be done explicitly.
This will allow us to confirm that the protobuf V2 switch is correct and that the behavior has not changed.
Run tests locally.

ROX-22019: Add test coverage for protoconv time functions

---

scripts/ci/metrics.sh

We do not mark batch load job a failed even when there are failures. This PR fixes that.
CI

chore: return error if batch loading fails

---

.github/CODEOWNERS
Makefile
proto/storage/compliance_operator_v2.proto
proto/storage/proto.lock

To improve the liklihood of backwards compatibility we need to use the `proto.lock` to tell us when storage proto changes are not compatible with the previous version.  As part of that we also need to make sure we are updating the `proto.lock` file as we go.  So the `storage-protos-compatible` has been updated so that it will also flag if the `proto.lock` is out of date.  As you can see by the `proto.lock` file that is part of this PR, it was already out of date from a recent change.
Please look at #12045 to see the style job fail for an out of date `'proto.lock` https://github.com/stackrox/stackrox/actions/runs/9995368467/job/27627340681?pr=12045
and #12046 for an example of an incompatible storage proto update and the error that generates …

ROX-25302:  check for outdated proto.lock

---

ui/apps/platform/src/Containers/Clusters/clustersTableColumnDescriptors.js

Unlike some other classic tables, for which axe DevTools reports an issue:
> Scrollable region must have keyboard access `<div class="rt-table" role="grid">`
This table has an `input` element for bulk actions, but **not** a link to open the side panel for the primary entity.
https://dequeuniversity.com/rules/axe/4.9/scrollable-region-focusable?application=AxeChrome
Classic routes that render tables have `onRowClick` event handler:
* which does not have associated keyboard action
* which is probably invisible to screen readers
In theory, this classic table has a very short shelf life, but fix it just in case of change in plans or priorities.
1. Add in name column a link to open the side panel.
1. Find in Files `data-testid="cluster-name"` reminds me that rewrite of clusters table in …

chore(ui): Add links to clusters for keyboard accessibility

---

.openshift-ci/pre_tests.py
qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy
qa-tests-backend/src/test/groovy/RuntimeViolationLifecycleTest.groovy
scripts/ci/jobs/gke_version_compatibility_tests.py
tests/e2e/lib.sh

3.74 test removed (not supported on GKE)
https://issues.redhat.com/browse/ROX-18223
CORE_BPF collection used, to avoid eBPF download flakes on older versions
Based on failures: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-release-4.5-merge-gke-version-compatibility-tests/1811048972521836544
And ticket posted above (3.74 only supported on OCP 3.11)

fix(tests): Fix GKE version compatibility tests

---

.github/workflows/retest_periodic.yml

Typically takes about a minute so should be safe to run every 10 minutes rather than every hour.
No validation done. It would be nice if we ran a linter 🤔

test: Run auto retest bot more often

---

ui/apps/platform/src/Containers/VulnMgmt/List/Clusters/VulnMgmtListClusters.js
ui/apps/platform/src/Containers/VulnMgmt/List/Cves/VulnMgmtListCves.js
ui/apps/platform/src/Containers/VulnMgmt/List/Deployments/VulnMgmtListDeployments.js
ui/apps/platform/src/Containers/VulnMgmt/List/ImageComponents/VulnMgmtListImageComponents.js
ui/apps/platform/src/Containers/VulnMgmt/List/Images/VulnMgmtListImages.js
ui/apps/platform/src/Containers/VulnMgmt/List/Namespaces/VulnMgmtListNamespaces.js
ui/apps/platform/src/Containers/VulnMgmt/List/NodeComponents/VulnMgmtListNodeComponents.js
ui/apps/platform/src/Containers/VulnMgmt/List/Nodes/VulnMgmtListNodes.js
ui/apps/platform/src/Containers/VulnMgmt/VulnMgmt.utils/entities.ts

Unlike some other classic tables, for which axe DevTools reports an issue:
> Scrollable region must have keyboard access `<div class="rt-table" role="grid">`
These tables have links in various columns to open the side panel for secondary entities, but **not** a link to open the side panel for the primary entity.
https://dequeuniversity.com/rules/axe/4.9/scrollable-region-focusable?application=AxeChrome
Classic routes that render tables have `onRowClick` event handler:
* which does not have associated keyboard action
* which is probably invisible to screen readers
Thank you Brad for discovery that Vulnerability Management renders hidden table for PDF export, therefore page crash:
> Invariant failed: You should not use `Link` outside of a `Router`
Even though **Export** button is available …

chore(ui): Add links to vulnmanagement for keyboard accessibility

---

ui/apps/platform/cypress/integration/compliance/Compliance.selectors.js
ui/apps/platform/src/Containers/Compliance/List/Table.js
ui/apps/platform/src/Containers/Compliance/List/tableColumns.js
ui/apps/platform/src/Containers/Compliance/List/tableColumns.test.js

> Scrollable region must have keyboard access `<div class="rt-table" role="grid">`
https://dequeuniversity.com/rules/axe/4.9/scrollable-region-focusable?application=AxeChrome
Classic routes that render tables have `onRowClick` event handler:
* which does not have associated keyboard action
* which is probably invisible to screen readers
1. Move tableColumns.js file into Compliance/List folder.
* Replace `getNameCell` function with `TableCellLink` element.
* Replace `controlColumns` object with `getColumnsForControl` function which has `query` argument because control links need same search as controls table.
For example, `?Cluster=%2A&standard=CIS%20Kubernetes%20v1.5`
* Replace redundant `Cell` properties to use ordinary `accessor` property for cluster and namespace in …

chore(ui): Add links to compliance tables for keyboard accessibility

---

pkg/jsonutil/conversion.go

The new protojson library has randomization for spaces to ensure lib users are not relying on stable string output.
This PR fixes usage in our wrapper that outputs compact JSON.
Problem is found by Unit Test - no changes on unit test is important.
Executed unit test locally (several times).

ROX-22019: Ensure random space is removed from compact proto to json

---

pkg/protocompat/message.go
pkg/protocompat/message_test.go
pkg/protocompat/time.go
pkg/protomock/mock_matcher.go
pkg/protoutils/slices.go

This PR introduces Equalable interface and use it in `protocompat.Equal` so instead of relaying on `proto.Equal` implementation we can use generated `EqualVT` method that does not rely on reflection.
CI

fix: call EqualVT in Equal

---

central/enrichment/singleton.go
central/image/service/service.go
central/image/service/service_impl.go
central/image/service/singleton.go
central/policy/service/service.go
central/policy/service/service_impl.go
central/policy/service/singleton.go
pkg/images/cache/imagemetadata.go
pkg/images/enricher/enricher.go
pkg/images/enricher/enricher_impl.go
pkg/images/enricher/enricher_impl_test.go

Extract an ImageMetadata cache that is used in multiple places. It's a prefactor for https://github.com/stackrox/stackrox/pull/11924
CI

chore: extract ImageMetadata cache

---

tests/roxctl/bats-tests/cluster/deployment-bundles-psps.bats
tests/roxctl/istio-support.sh

It's easier to write other tests if they can assume that there is only one connected cluster.
Stumbled upon this when [rewriting](https://github.com/stackrox/stackrox/pull/11986) TLSChallengeTest in go.
I verified that a test that runs later only sees one cluster.

test(roxctl): cleanup cluster entries when done

---

.github/workflows/build.yaml
.github/workflows/scanner-build.yaml

This PR changes the job matrix to build only amd64/stackrox images for PRs unless [ci-build-all-arch](https://github.com/stackrox/stackrox/labels/ci-build-all-arch) label is specified.
The reason to do this is that we do not have a CI for other architectures on PR unless asked so in most cases we waste time and resources building other architectures. Building more than we need causes docker.io to throtled our calls made by qemu install action that is necessary to build other architectures.
- https://github.com/stackrox/stackrox/pull/7657
---
CI

tests(CI): do not build all arch for PRs

---

.openshift-ci/post_tests.py

From time to time we're getting unexplained connection refused errors to central which seems to be fine otherwise:
```
ERROR:	Analyst: rpc error: code = Unavailable desc = transport: dial tcp 35.193.54.114:443: connect: connection refused 
```
```
curl: (7) Failed to connect to 35.193.54.114
```
According to a [random troubleshooting doc](https://www.freekb.net/Article?id=3689) that Google spit up `openshift-ingress` ns is where the reverse-proxy pods live. Let's grab their logs so we can investigate closer the next time it happens.
See above.

tests: grab openshift-ingress logs too

---

central/compliance/datastore/internal/store/postgres/store.go
central/deployment/cache/cache.go
central/user/datastore/internal/store/store.go
central/user/datastore/internal/store/store_impl.go
pkg/expiringcache/cache.go
pkg/expiringcache/cache_test.go
pkg/expiringcache/mocks/cache.go
pkg/images/cache/imagemetadata.go
pkg/images/enricher/enricher_impl.go
pkg/images/enricher/enricher_impl_test.go
pkg/notifier/alert_set.go
pkg/telemetry/phonehome/segment/segment.go
pkg/telemetry/phonehome/segment/segment_test.go
sensor/common/detector/detector.go
sensor/common/detector/enricher.go
sensor/common/detector/enricher_test.go
sensor/common/image/cache/cache.go
sensor/common/image/service_impl.go
sensor/common/image/service_impl_test.go
sensor/common/imagecacheutils/common.go
sensor/common/registry/registry_store.go
sensor/common/registry/tlscheck.go
sensor/common/reprocessor/handler.go
sensor/kubernetes/listener/resources/deployment_store.go
sensor/kubernetes/sensor/sensor.go

This PR adds types to expirable cache so instead of using `interface{}` as key and value we have a types that help controlling what is stored inside. Also it fixes image cache that used to store different values under the same key. As image cache uses specific version of key (it's not always image id) I created a type to prevent accidental string passing and force usage of cache key provider. It also changes Get method to return two values as we cannot explicitly return `nil` (only `var empty V`) with generic solution. 
- https://github.com/stackrox/stackrox/pull/11925#discussion_r1673965036
Prefactor:
- https://github.com/stackrox/stackrox/pull/12022
- https://github.com/stackrox/stackrox/pull/11961
- https://github.com/stackrox/stackrox/pull/11968
- …

fix: make expiring cache type aware

---

qa-tests-backend/src/test/groovy/IntegrationsTest.groovy

add a comment to explain the cloudflare r2 resources.
change me!

chore: add comment on cloudflare r2 subscription

---

central/main.go
pkg/features/telemetry/telemetry.go
pkg/features/telemetry/telemetry_test.go

Add Amplitude telemetry to our feature flag framework.
Example Amplitude user property (https://app.amplitude.com/analytics/redhat/project/437169/search/amplitude_id%3D950554248271?sessionHandle=-B_ZDk0%252BfO_N1RcsRP_BnpM_7696ee0c-e503-400b-a5a4-66a7ef2a6b8a&eventId=26d995c7-870f-47b3-a323-8bafc5e114b5):
```
{
"$insert_id": "4b432686-0538-4114-9991-f41516708d58",
"$schema": 13,
"_time": 1721826011086,
"amplitude_attribution_ids": [
"6edb01323e178bcb5223b1cd6733933f"
],
"amplitude_id": 950554248271,
"app": 424524,
"city": null,
"client_event_time": "2024-07-24 13:00:11.086000",
"client_upload_time": "2024-07-24 13:00:14.738000",
"country": null,
"data": {
"group_first_event": {
"260245": [
39293239385
]
},
"group_ids": {
"260245": [
39293239385
]
},
"path": "/2/httpapi", …
```

ROX-25352: feature flags telemetry

---

ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodeCVEs.json
ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodes.json
ui/apps/platform/cypress/helpers/request.js
ui/apps/platform/cypress/helpers/sort.js
ui/apps/platform/cypress/helpers/tableHelpers.js
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/NodeCve.helpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeCvesOverviewPage.test.ts

Adds Cypress tests for the Node CVE overview page.
- Tests that links in the table correctly point to the relevant detail pages
- Tests that sorting of the overview tables correctly sends the sort parameters to the queries
Note that due to the unpredictability of data in a CI environment, this doesn't e2e test that the data table is sorted correctly. Since the sorting is done server-side, we at most test that the UI interaction sends the correct sort parameters to the backend, and that sorting is only enabled on the correct columns.
Local Cypress run + Inspected CI results

test(ui): node overview page tests

---

pkg/jsonutil/conversion.go

This PR is adding a comment to describe reasons for calling `json.Compact` in the `ProtoToJSON` function.
Changing only comment.
Only CI - no special validation is done.

ROX-22019: Tweak comment for compact proto to JSON output

---

tests/compliance_operator_v2_test.go

We are getting build fails in the CI pipeline for `e2e` tests, but only compliance `e2e` tests.
The error is:
```
./compliance_operator_v2_test.go:38:2: coNamespace redeclared in this block
./compliance_operator_test.go:26:2: other declaration of coNamespace
FAIL	github.com/stackrox/rox/tests [build failed]
```
We have a collision of constant names in this package.
```
coNamespace
```
This is not visible in IDE (at least for me), because IDE is handling files with defined `//go:build` tags. In this case we have one constant behind `test_e2e` build tag and another behind `compliance` tag. It looks like that problem happens only when both tags are enabled in the build.
An example: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-nightlies-ocp-4-15- …

chore(fix): Fix build for compliance e2e tests

---

tests/common.go

This function was not used since 2021 let's remove it.
https://github.com/stackrox/stackrox/commit/6e9b30e3f69e8073a5b935b4a953fe91c10595d7#diff-b132e138e2fec90b24968747b9a0d420f79e4fd5fc922f0d4914068b3bc81b7eR33
CI

test(nongroovy): remove unused function

---

pkg/protocompat/message.go
pkg/protomock/mock_matcher.go
pkg/protoutils/slices.go

Prevent accidental usage by marking as deprecated. This function is used only in one place:
https://github.com/stackrox/stackrox/blob/cdfb007fd7e9dc81715f6324a38994541096f0ba/pkg/protoutils/any.go#L34
Also move Equalable interface to the place where it's used the most.
CI

chore: mark protocompat.Clone as deprecated

---

ui/apps/platform/src/app.tw.css

> Scrollable region must have keyboard access
src/app.tw.css imports react-vis/dist/style.css from from node_modules folder:
```css
.rv-discrete-color-legend{box-sizing:border-box;overflow-y:auto;font-size:12px}
```
Unlike table rows, there is no interaction in the legend of sunburst graphs.
Add rule to override property in app.tw.css file.
Automated testing is independent of presentation style.
2. `yarn build` in ui/apps/platform
3. `yarn start` in ui/apps/platform
1. Visit /main/compliance, click **Scan environment**, click namespaces count link, click a namespace link to open the side panel, and then scroll down to see sunburst graphs.
* Before changes, see presence of accessibility issue.
* After changes, see absence of accessibility issue.
Inspect …

fix(ui): Fix accessibility issue in legend of sunburst graphs

---

.github/workflows/scanner-build.yaml

We have failures like this: https://github.com/stackrox/stackrox/actions/runs/10096815144/job/27920233643
The assumption is that typo in line `36` (`s/arch/goarch`) is causing the issue:
https://github.com/stackrox/stackrox/blob/f405221b4639dd639cd2950c24a2763fdbc44576/.github/workflows/scanner-build.yaml#L33-L37
**EDIT:** I was able to reproduce it with this PR by using label [ci-build-all-arch](https://github.com/stackrox/stackrox/labels/ci-build-all-arch).
This run: https://github.com/stackrox/stackrox/actions/runs/10097827676/job/27923556491?pr=12151
A comment is also tweaked to point to the exact build step.
CI pipeline runs with labels and without them
Only local testing done was:
```
❯ matrix='{ "build_and_push": { "name":["default"], "goos":["linux"], "goarch":["amd64"] }, …
```

chore(fix): Fix scanner multi arch build

---

central/policy/service/service_impl.go
central/policy/service/service_impl_test.go
central/policycategory/datastore/datastore_impl.go

This PR adds pagination to list policies api. This changes has been tested manually and verified that pagination works in policies
GET https://localhost:8000/v1/policies?query=&pagination.offset=0&pagination.limit=10
response attached
[Untitled.txt](https://github.com/user-attachments/files/16149692/Untitled.txt)

ROX-22797: Add pagination to list policies endpoint

---

pkg/registries/docker/docker.go
pkg/scanners/quay/quay.go

The ACS Quay Image Integration can be set as a 'scanner' - upon doing so the quay scanner logic [creates an underlying registry](https://github.com/stackrox/stackrox/blob/b01b02b2efff186817db44577db8b8537b3f6688/pkg/scanners/quay/quay.go#L54) used when 'matching' the scanner integration to an image during scanning.  This PR disables the usage of the 'repo list' for that registry to improve matching and align with the default behavior of other non-autogenerated registries.
None
Deployed changes to an infra cluster, changed the default quay integration to and from scanner type, and observed debug logs indicating whether repo list was disabled as desired.
Before fix:
```sh
pkg/registries/docker: 2024/07/25 22:26:56.409193 docker.go:98: Debug: created integration "Public Quay.io" with repo …
```

ROX-21485: Disable repo list for quay scanner's registry

---

.github/renovate.json5

Per title and see related ticket.
No contribution to it.
Only ran config validation cli. Will have to observe renovate behavior after merging this.

ROX-22359: Make renovate active only outside of working hours

---

Makefile

We have a problem highlighted in:
- https://github.com/stackrox/stackrox/pull/12137
```yml
make roxvet
+ roxvet
+ roxvet
roxvet: tests/compliance_operator_v2_test.go:38:2: coNamespace redeclared in this block
Makefile:779: recipe for target 'roxvet' failed
make: *** [roxvet] Error 123
```
CI

fix: run roxvet on other tags

---

sensor/common/registry/registry_store.go
sensor/kubernetes/listener/resources/secrets.go

Code was added in https://github.com/stackrox/stackrox/pull/8210 and assuming was meant to be removed in https://github.com/stackrox/stackrox/pull/8732 but was missed ([was partially removed](https://github.com/stackrox/stackrox/pull/8732/files#diff-facd557d8edc441d1d39f8de8ff4ccebe7f19fdd6bce46fa6c7b5de377a39b0cL74-L83))
This PR removes the dead code
The `// notsecret` comments were added to suppress false positive alerts from the internal gitleaks `pre-commit` hook that was blocking the updates to `sensor/kubernetes/listener/resources/secrets.go`
CI
None, relying on CI / compilation.

chore(deadcode): Remove known secret IDs from Sensor

---

ui/apps/platform/cypress/helpers/request.js
ui/apps/platform/cypress/helpers/sort.js
ui/apps/platform/cypress/helpers/visit.js
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/NodeCve.helpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/cveDetailPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeCvesOverviewPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeDetailPage.test.ts

Small refactors of existing integration tests:
1. Break up permission tests into a single assertion per test
2. Do away with "mock" functions and use staticResponseMaps instead
Local `yarn cypress`, CI

chore(ui): node cypress test refactors v1

---

ui/apps/platform/cypress/helpers/request.js
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeCvesOverviewPage.test.ts

Adds a new helper for a cleaner pattern in the Node Overview page tests. The pattern here is a multi-step cousin of the widely used `interactAndWaitForResponses()` function. Instead of passing a callback for the interaction, this helper inverts control and returns functions that allow the caller to specify when to wait for the request, and to do so multiple times.
This results in a more readable pattern of "act -> wait -> assert" than the callback driven approach used in the previous Node CVE sorting tests.
Inspiration from comment thread here https://github.com/stackrox/stackrox/pull/12018#discussion_r1686972491
_May be easier to review in "Split" view - or compared side-by-side to the previous code in a non-diff view._
CI

chore(ui): Alternative API for multi interact-and-wait scenarios

---

ui/apps/platform/src/Components/NotFoundMessage/NotFoundMessage.tsx
ui/apps/platform/src/Containers/AccessControl/AccessControlLinks.tsx
ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsTable.tsx
ui/apps/platform/src/Containers/Collections/CollectionsTable.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsTable.tsx
ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step3/TableModal.tsx
ui/apps/platform/src/Containers/Search/FilterLinks.tsx
ui/apps/platform/src/Containers/Search/ViewLinks.tsx
ui/apps/platform/src/Containers/SystemConfig/Details/PrivateConfigDataRetentionDetails.tsx
ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/ClustersHealthCardHeader.tsx
ui/apps/platform/src/Containers/User/RolesForResourceAccess.tsx
ui/apps/platform/src/Containers/Violations/violationTableColumnDescriptors.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionDetailsCell.tsx

Some links do not have **Copy** on right-click menu in browser:
* The following work correctly: **Copy Link Address** and so on, also keyboard access to link.
* But cannot copy link text for use elsewhere.
1. **David Vail** discovered that it is a limitation of PatternFly `Button` element:
* with `variant="link"` which was our original idiom for link style
* plus `component={LinkShim}` which solved **element is detached from the DOM** errors from cypress when pages re-render during integration tests
2. The current combination of PatternFly and classic style rules works for ordinary React Router `Link` element.
**But** for links that have button style, **Copy** command is not necessarily relevant, therefore leave them alone. Also leave edge cases:
* Links at upper edge do not have …

fix(ui): Replace some Button and LinkShim with React Router Link

---

sensor/kubernetes/listener/resources/secrets.go
sensor/kubernetes/listener/resources/secrets_test.go

The annotation used to associate a pull secret with a service account has changed in OCP 4.16 from:
```yaml
kubernetes.io/service-account.name: default
```
to 
```yaml
openshift.io/internal-registry-auth-token.service-account: default
```
OCP 4.15
```yaml
$ oc version
Server Version: 4.15.22
Kubernetes Version: v1.28.11+add48d0
...
$ oc get secret default-dockercfg-k4wgc -o yaml | yq '.metadata.annotations'
kubernetes.io/service-account.name: default
...
$ oc get secret deployer-dockercfg-pb5r9 -o yaml | yq '.metadata.annotations'
kubernetes.io/service-account.name: deployer
...
```
OCP 4.16
```yaml
$ oc version
Server Version: 4.16.3
Kubernetes Version: v1.29.6+aba1e8d
...
$ oc get secret default-dockercfg-f99p5 -o yaml | yq '.metadata.annotations' …
```

ROX-25526: Fix OCP Internal Registry Scan Regressions

---

qa-tests-backend/test-images/trigger-policy-violations/most/Dockerfile
qa-tests-backend/test-images/trigger-policy-violations/most/Makefile

Changes the base image to `quay.io/centos/centos:stream9` and installs systemd. Also adds the platform flag to the docker build command so we ensure the amd64 version is built for CI.

use centos:stream9

---

deploy/common/k8sbased.sh
tests/e2e/lib.sh

ROX-25218, ROX-23907: Consider 34.118.224.0/20 as a private network in GKE tests
See https://github.com/stackrox/stackrox/pull/11934.
~- [ ] added unit tests~
~- [ ] modified existing tests~
Passing CI is sufficient.

ROX-25218, ROX-23907: Consider 34.118.224.0/20 as a private network

---

.github/workflows/build.yaml
.github/workflows/scanner-build.yaml

Qemu install action downloads image from docker.io that from time to time throttles us causing build failures. This PR do not install qemu when it's not needed to reduce dependency on docker.io.
- https://github.com/stackrox/stackrox/pull/12041
CI

tests: do not install Qemu on amd64 build

---

deploy/common/deploy.sh

This PR addresses the issue of a failing race condition QA test due to invalid JSON payloads. The root cause was identified as a duplicated field in the JSON payload, disguised by the use of both snake case and camel case for the same field.
- **Error Encountered**: POST cluster requests were returning a 400 error with no accompanying message.
- **Initial Hypotheses**:
- Suspected camel case vs. snake case issue (hypothesis disproved as both formats are supported).
- Investigated content type, noting curl sends www-encoded content (hypothesis disproved).
- **Unit Test Creation**: Developed a unit test replicating the failing payload.
- **Findings**: Identified that the JSON payload contained duplicated fields due to mixed casing (snake and camel case).
- **Fix**: Corrected the JSON …

ROX-25476: fix race condition QA tests

---

sensor/upgrader/preflight/access.go

The error message produced by the preflight check "Kubernetes authorization" contains many duplicated names of k8s resources. This makes it unnecessary long and unreadable - see screenshot.
In this PR, I remove the duplicates and sort the names of resources in the error message.
⚠️ This PR does not fix the cause of the missing authorization - for that a follow-up may appear soon.

ROX-25421: Compact error msg through removing duplicates 

---

.github/CODEOWNERS

The PR adds @stackrox/merlin as the owner of `pkg/features`.
1. Installed the `jasonnutter.vscode-codeowners` extension
2. Checked the owner of the files under `pkg/features` is identified as @stackrox/merlin.

ROX-25362: add `pkg/features` to `.github/CODEOWNERS`

---

.github/workflows/build.yaml
.github/workflows/scanner-build.yaml

To mitigate rate limiting by docker.io we should login to have our own pool of request to use.
Refs:
- https://github.com/stackrox/stackrox/pull/12041
- https://github.com/stackrox/stackrox/pull/12205
CI

chore: login to docker.io to fix builds

---

.github/pull_request_template.md

The PR adds the following task to the PR template:
___
PR template change + updated the PR description check script.
Documentation only.

ROX-25256: add GA requirements to the PR template

---

central/globaldb/v2backuprestore/service/http_handlers.go
central/image/datastore/store/postgres/store.go
central/metadata/service/service_impl_test.go
central/notifiers/awssh/notifier.go
central/probeupload/service/service_impl.go
central/processlisteningonport/datastore/datastore_impl.go
central/processlisteningonport/store/postgres/full_store.go
pkg/cryptoutils/cryptocodec/crypto_codec_test.go
pkg/grpc/common/authn/servicecerttoken/token.go
pkg/postgres/pgutils/scan.go
pkg/protocompat/message.go
pkg/protocompat/message_test.go
pkg/protocompat/nil_test.go
pkg/search/postgres/common.go
sensor/admission-control/settingswatch/common.go
sensor/admission-control/settingswatch/k8s.go
sensor/admission-control/settingswatch/mount.go
sensor/admission-control/settingswatch/persist.go
tests/admctrl_configmap_test.go

We don't need another layer of compatibility so we can switch to `UnmarshalVT`
```yaml
rules:
- id: a
languages:
- go
message: WIP
pattern: protocompat.Unmarshal($A, $X)
fix: $X.UnmarshalVT($A)
severity: WARNING
- id: b
languages:
- go
message: WIP
patterns:
- pattern: $A.Unmarshal($X)
- metavariable-regex:
metavariable: $A
regex: ([^json|yaml])
fix: $A.UnmarshalVT($X)
severity: WARNING
```
CI

chore: switch to UnmarshalVT

---

make/stackrox.mk
tests/Makefile
tests/cluster_delete_test.go
tests/common.go
tests/endpoints_test.go

After introducing //go:build directives in https://github.com/stackrox/stackrox/pull/11933 our e2e tests were not being executed since I had set the go build targets incorrectly. This PR fixes the build targets and go tags for files used by multiple different test targets such as `tests/common.go`
Looked through CI to confirm that all tests run again

fix(e2e-tests): Nongroovy e2e tests not running

---

central/config/datastore/datastore_test.go
central/config/datastore/singleton.go

After some feature flag cleanup, it was noticed that the configuration was systematically rewritten on instance start, and the logic to conditionally rewrite on change was dropped.
This probably came from a mistaken pattern application in the default initialization logic, which this PR aims at restoring.
Instrumented the development code with a log in the database singleton configuration upsert at initialization codeblock.
Checked the log did appear on first central instance start.
Restart central
Checked the log did **NOT** appear on second central instance start

fix: ensure config is only rewritten when changed

---

tools/local-sensor/main.go

Right now `local-sensor` always tries to create a real k8s client even if a fake client is configured. This is a problem because forces the user to have a cluster even if they don't intent to use it. This PR fixes this issue by only creating the real k8s client if the fake client was not configured previously.

feat(local-sensor): Only create real k8s client when needed

---

.github/renovate.json5

This is to have less noise from Konflux.
See https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1722013572686099 related.
The default active list of managers from our config was
```yaml
"enabledManagers": [
"tekton",
"dockerfile",
"rpm",
"git-submodules",
"custom.regex",
"argocd",
"crossplane",
"fleet",
"flux",
"helm-requirements",
"helm-values",
"helmfile",
"helmsman",
"helmv3",
"jsonnet-bundler",
"kubernetes",
"kustomize"
],
```
No auto-tests.
Ran validator.

chore: Limit Renovate focus to Konflux things

---

ui/apps/platform/src/Components/URLSearchInputWithAutocomplete.js

> Ensures must meet minimum color contrast ratio thresholds
> Element has insufficient color contrast of 3.33 (foreground color: #468bc3, background color: `#ebf6ff`, font size: 8.9pt (11.9px), font weight: normal). Expected contrast ratio of 4.5:1
```html
<div class="css-12jo7m5 bg-primary-200 text-primary-700 border border-primary-300 react-select__multi-value__label">Cluster:</div>
```
Find in Files: `bg-primary-200 text-primary-700` from Inspector panel of browser
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Components/URLSearchInputWithAutocomplete.js#L16-L18
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Components/URLSearchInputWithAutocomplete.js#L26
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Components/URLS …

chore(ui): Fix accessibility issue of color contrast in search label

---

central/blob/datastore/datastore.go
central/sensor/service/connection/connection_impl.go
central/sensor/service/connection/messagestream/sizing_events.go
compliance/collection/metrics/metrics.go
sensor/admission-control/manager/manager_impl.go
sensor/common/deduper/deduper.go
sensor/common/metrics/sizing_events.go
sensor/common/sensor/central_communication_impl.go
sensor/kubernetes/listener/resources/networkpolicy_store.go
sensor/tests/helper/trace.go

To remove proto compat generator we need to remove all wrapper methods references. This PR removes `Size` in favour to `SizeVT`
CI

chore(proto): switch from Size() to SizeVT()

---

ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
ui/apps/platform/src/Containers/NetworkGraph/external/ExternalGroupSideBar.tsx
ui/apps/platform/src/Containers/NetworkGraph/genericEntities/GenericEntitiesSideBar.tsx
ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceSideBar.tsx
ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx

> ARIA dialog and alertdialog nodes should have an accessible name
```html
<div role="dialog" class="pf-topology-resizable-side-bar">
```
To solve this problem, you need to fix at least (1) of the following:
* aria-label attribute does not exist or is empty
* aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
* Element has no title attribute
https://dequeuniversity.com/rules/axe/4.9/aria-dialog-name?application=AxeChrome
`TopologySideBar` element renders the HTML element above.
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx#L187-L257
It renders any of the following children which have headings for an accessible name.
* …

fix(ui): Specify accessible name of Network Graph side panel

---

.github/renovate.json5

I.e. these ones must not be created https://github.com/stackrox/stackrox/pull/12271, https://github.com/stackrox/stackrox/pull/12272.
Use [includePaths](https://docs.renovatebot.com/configuration-options/#includepaths) instead of [fileMatch](https://docs.renovatebot.com/configuration-options/#filematch) since the former one is not set in parent configs.
Context: https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1722842262116049?thread_ts=1722013572.686099&cid=C05TS9N0S7L
No automated tests.
Ran validator.

ROX-22359: Stop renovating Dockerfiles other than Konflux ones

---

tests/performance/scale/tests/kube-burner/cluster-density/run-workload.sh
tests/performance/scale/tests/metadata-collector/main.go

Makes it possible to add a test name to performance test metadata. Many related tests can have the same name. This makes it possible to group tests and do analysis on groups of tests. For example tests with different numbers of namespaces, deployments per namespace, and pods per deployment, but everything else kept the same can have the same test name.
A couple of other minor changes are also made.
A full path is used for the metadata path in the `run-workload.sh` script.
Also if the k8s version does not match x.y it is truncated to x.y in the metadata.
~~- [ ] CHANGELOG is updated~~
~~- [ ] Documentation PR is created and linked above~~
~~- [ ] added e2e …

ROX-25290: Add test name to performance test meta data

---

.github/workflows/style.yaml

Style checks have been failing due to disk space (lack thereof). This reclaims even more disk space in hopes we can continue styling.
Copied this over from https://github.com/stackrox/stackrox/blob/master/.github/workflows/scanner-release-vuln-update.yaml
This **is** the test!

fix(ci): style checks running out of disk space

---

central/scannerdefinitions/handler/handler.go
central/scannerdefinitions/handler/handler_test.go

Simplifies the scanner definitions handler by combining related functions for Scanner v2 and V4. This also removes an annoying misleading log about missing offline files, when they're not needed.
I also removed `startUpdaterAndOpenFile` because it's no longer used.
This is the first PR in a series of PRs to fix this file for bugs and readability purposes:
* https://github.com/stackrox/stackrox/pull/11212 <-- This
* https://github.com/stackrox/stackrox/pull/11825 (replaces https://github.com/stackrox/stackrox/pull/11282 which was originally merged into here but was somehow lost...)
* https://github.com/stackrox/stackrox/pull/11836
* https://github.com/stackrox/stackrox/pull/11837
* https://github.com/stackrox/stackrox/pull/11841
* https://github.com/stackrox/stackrox/pull/11842
* …

chore(central): simplify v2 and v4 handling

---

ui/apps/platform/src/Components/CompoundSearchFilter/attributes/policy.ts
ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTableSearchFilter.tsx

This PR makes a few changes to the Policy Violations page to accommodate the implementation of advanced filters:
1. Adding feature flag logic 
2. Changing the placement of the search filter and the bulk actions dropdown
3. Creating a component for the policy violations search filter
https://github.com/user-attachments/assets/0e6e4021-d5c9-4b72-98dc-3f288ba7927d

ROX-25333: Add autocomplete inputs to policy violations filters

---

.github/renovate.json5

Simply copied settings from Scanner repo.
I hope this is it, and the config should serve us (and not the other way around).
No automated testing.
Only ran Renovate validator cli.

RXO-22359: Update Renovate config

---

.golangci.yml

golangci-lint currently does not run on e2e tests. This PR adds this tag to litner configuration:
- #12146
---
CI

chore(lint): lint ./tests

---

tests/tls_challenge_test.go

Skip false positive finding
- https://github.com/stackrox/stackrox/pull/12311
```
tests/tls_challenge_test.go:101:2: G101: Potential hardcoded credentials (gosec)
nginxTLSSecretName := "nginx-tls-conf"
```
CI

fix(e2e): false positive nosec

---

central/scannerdefinitions/handler/handler.go

Recreation of https://github.com/stackrox/stackrox/pull/11825. Done because the original PR was getting hard to manage.
This PR simply moves functions around. It does not modify them.
No tests

chore(central): reorder scannerdefs funcs for readability

---

ui/apps/platform/src/Containers/MainPage/Banners/Banners.tsx
ui/apps/platform/src/Containers/MainPage/Header/Header.css
ui/apps/platform/src/Containers/MainPage/Header/Header.tsx
ui/apps/platform/src/Containers/MainPage/Header/Notifications.tsx
ui/apps/platform/src/Containers/MainPage/MainPage.tsx
ui/apps/platform/src/app.tw.css

> All page content should be contained by landmarks
https://dequeuniversity.com/rules/axe/4.9/region?application=AxeChrome
```html
<div class="pf-v5-c-banner pf-m-red pf-v5-u-text-align-center"><span class="pf-v5-u-text-align-center">The database is currently not available. If this problem persists, please contact support.</span></div>
```
> ARIA progressbar node must have an accessible name
https://dequeuniversity.com/rules/axe/4.9/aria-progressbar-name?application=AxeChrome
```html
<div role="progressbar" class="Toastify__progress-bar Toastify__progress-bar--animated Toastify__progress-bar--default" style="animation-duration: 800000ms; animation-play-state: paused; opacity: 0;"></div>
```
Indeed, MainPage.tsx file renders banner elements outside of landmark elements.
1. Move …

fix(ui): Move banner elements into landmarks for accessibility

---

tests/cert_test.go
tests/client_ca_test.go
tests/common.go
tests/endpoints_test.go
tests/tls_challenge_test.go

1. The primary change is to explicitly refer to the image pull secret in the pod template rather than patch the default service account, since the latter seems unreliable.
In [this flake](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/12292/pull-ci-stackrox-stackrox-master-ocp-4-16-nongroovy-e2e-tests/1820850312693420032) the nginx image for the proxy failed to pull due to `unauthorized: access to the requested resource is not authorized`. Upon inspection, the `default` service account was lacking the necessary image pull secret reference (which the test did patch in on setup).
I don't know if this means it does the patching in a wrong way, which becomes a no-op in some corner case, or some other operation reverted its patch somehow (though the …

tests: TestTLSChallenge improvements

---

ui/Makefile

Downstream builds have problems due to Cachito not playing well with `yarn`'s `--cwd`. The simple replacement is to do `cd` instead. Each command in Makefile is executed in a separate shell and so the `cd`-s effect applies only to the line where it's done (verified by surrounding with `pwd`-s).
See https://redhat-internal.slack.com/archives/C02AD1GUA0Y/p1723018428884079 / https://gitlab.cee.redhat.com/stackrox/rhacs-midstream/-/merge_requests/3327 / https://redhat-internal.slack.com/archives/C02AX10EQJW/p1723027057303309
This PR will be obsolete by https://github.com/stackrox/stackrox/pull/11967 which may be merged soon and so we may just ignore this https://github.com/stackrox/stackrox/pull/12313.
No automated testing changes.
Built downstream …

build: Fix downstream UI builds while with `yarn`

---

ui/apps/platform/src/Containers/NetworkGraph/simulation/CodeCompareIcon.tsx
ui/apps/platform/src/Containers/NetworkGraph/simulation/SimulationFrame.tsx

> Element has insufficient color contrast of 2.43 (foreground color: #2b9af3, background color: #e0e9f2, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
https://dequeuniversity.com/rules/axe/4.9/color-contrast
```html
<div class="pf-v5-u-info-color-100">Simulated view</div>
```
> `<svg>` elements with an img role must have an alternative text
https://dequeuniversity.com/rules/axe/4.9/svg-img-alt
```html
<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" height="1em" width="1em" viewBox="0 0 512 512" role="img" style="vertical-align: -0.125em;">
```
https://www.patternfly.org/accessibility/design-for-accessibility
> As long as you follow our recommendations, any UI built with PatternFly …

ROX-25655: Fix accessibility issue of contrast in SimulationFrame

---

operator/pkg/common/extensions/secret_reconciliator_test.go
pkg/protoassert/assert.go
pkg/protoconv/networkpolicy/conversion_test.go
sensor/upgrader/plan/preserve_test.go

Since we switched to proto v2 there is no need to use the old lib in `protoassert`. This also fixes some of not valid usage of `protoassert`
---
CI

fix(proto): do not use legacy proto in protoassert

---

ui/apps/platform/src/Components/CompoundSearchFilter/attributes/policy.ts
ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Containers/Violations/ViolationsTableSearchFilter.tsx

This PR adds a multi-select dropdown for the Lifecycle stage filter in Policy Violations.

ROX-25332: Adding Lifecycle stage to the policy violations filter

---

ui/apps/platform/src/Containers/MainPage/Body.tsx
ui/apps/platform/src/Containers/MainPage/MainPage.tsx

Follow up #12209
> Document should not have more than one banner landmark
https://dequeuniversity.com/rules/axe/4.9/landmark-no-duplicate-banner
> Ensures landmarks are unique
https://dequeuniversity.com/rules/axe/4.9/landmark-unique
For both:
```html
<header class="pf-v5-c-page__header ignore-react-onclickoutside theme-dark">
```
Related node:
```html
<header class="pf-v5-c-modal-box__header">
```
Thank you **David** for observing transient changes in browser Elements pane.
Initial elements:
```html
<body class="theme-light">
<div id=="root">
<div></div>
<div></div>
<svg></svg>
```
Click **Manage CIDR blocks** button:
```html
<body class="theme-light pf-v5-c-backdrop__open">
<div id=="root" aria-hidden="true">
<div aria-hidden="true"></div>
<div aria-hidden="true"></div>
<svg …
```

ROX-25662: Fix accessibility issues with header for global modals

---

pkg/grpc/server_test.go

There is a small typo in the test name.
- ~[ ] CI results are inspected~ - nothing to look at, this change should not cause any test failures - it just a test name change
Let CI run it

chore(test): Fix test name typo

---

pkg/secrets/scrub.go
pkg/secrets/scrub_test.go

This PR adds an option to proto scrubbing which avoids replacing zero values. This is useful to indicate via the API if a field has been set or not. Concretely, I want to use this distinction to confirm via the UI if a cloud source integration with a deprecated API token field has been set (`credentials.secret`). Without this change, the payload
```json
{"credentials": {"secret": "", "clientId": "id", "clientSecret": "secret"}}
``` 
would be scrubbed to (note that `***` is returned regardless of original values)
```json
{"credentials": {"secret": "***", "clientId": "***", "clientSecret": "***"}}
``` 
This makes it indistinguishable from the deprecated 
```json
{"credentials": {"secret": "token", "clientId": "", "clientSecret": ""}}
```
With this PR, the scrubbed value of the line above is …

ROX-24169: option for zero value scrubbing

---

ui/apps/platform/src/Components/CompoundSearchFilter/attributes/policy.ts
ui/apps/platform/src/Containers/Violations/ViolationsTableSearchFilter.tsx

This PR adds a multi-select dropdown for the Severity filter in Policy Violations.

ROX-25336: Adding severity to the policy violations filter

---

ui/apps/platform/src/Components/CompoundSearchFilter/attributes/alert.ts
ui/apps/platform/src/Containers/Violations/ViolationsTableSearchFilter.tsx

This PR adds a multi-select dropdown for the Inactive deployment filter in Policy Violations.

ROX-25331: Adding inactive deployment to the policy violations filter

---

pkg/protoconv/time.go
pkg/timestamp/microts.go
pkg/timestamp/microts_test.go

This cleanup leftovers after proto switch. Since we have a new proto we should use it everywhere.
CI

chore(proto): remove legacy timestamp

---

image/rhel/Dockerfile
image/rhel/konflux.Dockerfile
scanner/image/scanner/Dockerfile
scanner/image/scanner/konflux.Dockerfile

In https://github.com/stackrox/scanner/pull/1588 I discovered that updated Konflux build tasks treat `/etc/pki/entitlements` in a special way, that's due to added support for subscription-manager activation.
This, however, clashes with `chown ... /etc/pki` that we do historically (https://github.com/stackrox/scanner/pull/229)  in `Dockerfile`-s resulting in build-time errors like
```
chown: changing ownership of '/etc/pki/entitlement': Operation not permitted
```
I scanned the code and it seems that we only modify `/etc/pki/ca-trust` so we don't need to chown the entire `/etc/pki`.
<details>
<summary>Here are few relevant fragments</summary>
https://github.com/stackrox/stackrox/blob/04d711a6702831b48c1c7c0770b1d6cef1fb9733/image/templates/helm/stackrox-secured-cluster/templates/admission-c …

fix: Modify chown path from /etc/pki to /etc/pki/ca-trust

---

central/graphql/generator/codegen/typewalk.go
pkg/protoutils/message.go
pkg/protoutils/message_test.go
tools/deserialize-proto/main.go
tools/generate-helpers/pg-table-bindings/funcs.go
tools/generate-helpers/pg-table-bindings/main.go

This PR switches to new proto implementation. The goal is to drop this dependency as it's deprecated.
https://pkg.go.dev/github.com/golang/protobuf/proto#MessageType
CI

chore(proto): replace proto.MessgeType

---

ui/apps/platform/src/Components/CompoundSearchFilter/attributes/alert.ts
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/ConditionDate.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTableSearchFilter.tsx

This PR adds a date picker for the Violation time filter in Policy Violations. This also includes adding the ability to say `Before`, `On`, or `After` on a specific date.

ROX-25337: Adding violation time to the policy violations filter

---

Makefile

Adds a target to update the proto lock file.
`make update-storage-protolock` can be used when `storage/proto` changes are made and the `proto.lock` file needs updated.
See #12355 for the updated `proto.lock` from running `make update-storage-protolock` after proto changes are done.

chore(protolock): Add make target to update proto.lock

---

central/alert/datastore/datastore.go
central/alert/datastore/datastore_impl.go
central/alert/datastore/internal/store/mocks/store.go
central/alert/datastore/internal/store/store.go
central/alert/datastore/mocks/datastore.go
central/postgres/pruning.go
central/processlisteningonport/datastore/datastore_impl.go
central/pruning/pruning.go
central/pruning/pruning_test.go
pkg/search/postgres/store.go

Follow on to #11886 to use the new `PruneMany` that will prune outside of a transaction as we aren't as worried about semantics with Prune.  We just want the data gone.  So if one batch fails we will continue onto the next one instead of failing the entire prune job which is what was happening when we used `DeleteMany`.  Pruning is a different animal where we just want to purge as much as we can and move along
Had to do a lot of this manually.  
- spin up a scale test environment
- Hook up 4 fake workload sensors that slam alerts
- change the alert retention configs to by 1 day-ish
- Verify in the logs and the database that alerts are being deleted per the updated retention configs. …

ROX-24916: use prune option the store has

---

pkg/protoreflect/descriptors.go
pkg/protoreflect/descriptors_test.go

This PR cleanups `pkg/protoreflect` by:
- removing unused functions, fields and vars
- unexporting local functions
- switching form deprecated proto to the new version 
---
CI

chore(proto): cleanup pkg/protoreflect

---

pkg/errox/utils.go
pkg/errox/utils_test.go
pkg/scanners/clairify/clairify.go

The change hides potentially sensitive addresses from some errors returned by `/v1/images/scan`, when using clairify scanner.
```console
me@work$ curl -u admin:password 'https://localhost:8443/v1/images/scan' --data '{"imageName": "ubuntu:23.04"}' -ks | jq
{
"error": "image enrichment error: error scanning image: docker.io/library/ubuntu:23.04 error: scanning \"docker.io/library/ubuntu:23.04\" with scanner \"Stackrox Scanner\": Get \"https://scanner.stackrox.svc:8080/scanner/sha/sha256:ea1285dffce8a938ef356908d1be741da594310c8dced79b870d66808cb12b0f\": dial tcp 34.118.237.164:8080: connect: connection refused",
"code": 13,
"message": "image enrichment error: error scanning image: docker.io/library/ubuntu:23.04 error: scanning \"docker.io/library/ubuntu:23.04\" with scanner \"Stackrox …
```

ROX-21226: conceal addresses from clairify scanner errors

---

ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx
ui/apps/platform/src/Containers/Violations/types.ts

This PR segments the Policy Violations into `Active` and `Resolved` violations. 
The old-style filters allowed you to filter using `Violation State` in the filter. This approach didn't seem like the right way to go about things. We were already pre-filtering the view by `Active` violations. Applying `Violation State: Active` as a filter does nothing, and applying `Violation State: Resolved` as a filter increases the counts since we are showing resolved violations over time.
https://github.com/user-attachments/assets/974dcee2-da28-415c-9989-e7594f08bd1f

ROX-25338: Add Active and Resolved tab in Policy Violations

---

.github/workflows/scanner-db-integration-tests.yaml

This adds (optional) Scanner V4 DB integration tests to CI. This relies on https://github.com/stackrox/rox-ci-image/pull/212
CI

chore(ci): add Scanner V4 DB integration tests

---

.tekton/main-build.yaml
.tekton/main-pipeline.yaml

Per title, replaces <https://github.com/stackrox/stackrox/pull/12054>.
Tracking build issues in:
- https://issues.redhat.com/browse/KFLUXBUGS-1523
- https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1723056835366329
No changes to automated tests.
Only Konflux CI.

ROX-25621: Add multi-arch Konflux builds to main image

---

ui/apps/platform/cypress.config.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js
ui/apps/platform/cypress/support/e2e.js

Adds a couple of logs to Cypress e2e tests to better coordinate the timing of flakes will possible issues in central logs.
1. Logs the current timestamp to the console at the beginning of each Cypress test file
2. Adds the current timestamp to the error log during a test failure in the Cypress UI
See addition of timestamp and name of test suite in the text logs:
```
Running:  accessControl/accessControlPermissionSets.test.js                             (9 of 112)
2024-08-06T19:47:50.780Z running test suite: accessControlPermissionSets.test.js
Access Control Permission sets
✓ cannot find the page if no permission
✓ list has heading, button, and table head cells
✓ list has default names
✓ list link for default Admin goes to form which has label instead of button and disabled input values
✓ …
```

chore(ui): Add more timestamp output to cypress e2e runs

---

pkg/netutil/ephemeral_port.go
qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
sensor/common/networkflow/manager/manager_impl.go
sensor/common/networkflow/manager/manager_impl_test.go

Collector sometimes doesn't get the port number of some sockets, this may be due to it missing some syscall or the kernel simply not filling in the data. This last case most commonly happens with connectionless UDP messaging, where the kernel leaves the side that starts the communication empty.
In any case, we shouldn't be showing port 0 in the network graph, so this patch will make it so port 0 takes the least precedence, so it will only show up if both sides of the connection are 0.
Added unit tests to ensure port 0 is not picked when using UDP.
Currently working on some changes for OCP Virt integration that make port 0 show up consistently, fixed with this change.

ROX-11587: Prevent port 0 from being used as a server

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/hooks/useURLPagination.test.tsx
ui/apps/platform/src/hooks/useURLParameter.test.tsx
ui/apps/platform/src/hooks/useURLParameter.ts
ui/apps/platform/src/hooks/useURLSort.test.js
ui/apps/platform/src/hooks/useURLStringUnion.test.tsx

Fixes the issue with URL state functions requiring an explicit `'replace'` parameter to be passed when making multiple state changes in order to avoid multiple pushes to the browser's history stack.
This PR contains 3 main commits that might be easier to review in sequence to get a better sense of the change:
1. Proof of concept to automatically batch URL parameter updates into a single atomic update
2. Refactor to remove global module state in favor of React context
3. Refactor of existing code to remove the unnecessary `'replace'` parameter at each call site
Of the 20+ files touched in this PR, [ui/apps/platform/src/hooks/useURLParameter.ts](https://github.com/stackrox/stackrox/pull/12282/files#diff-4fcf6e26eda811c7c48207521e83c20ec3e1546ead71898df7b7b84c554a29f7) is the only functional …

fix(ui): microtask useURLParameter fix

---

ui/apps/platform/src/Containers/ConfigManagement/Entity/widgets/FailedPoliciesAcrossDeployment.js

Fixes an issue where the "Enforced" field for Policies on a deployment always displays "Yes" in the Config Mgmt UI, regardless of enforcement status on the policy or if there are any enforced alerts for that policy/deployment combo.
I was unable to find a way with the existing search framework to determine if there were any **enforced alerts for a single deployment**, so this change displays whether or not the policy will enforce at all, but not necessarily whether there was an enforced alert for the deployment. This is in line with what the code currently does, but I don't have context on the intentions as the code in this section is > 5 years old.
> I tried to do this with `alertCount(query: "Enforcement:r/.*")` and similar filters, but could not find a filter that resulted in > 0 …

ROX-23846: Failed policy enforcement fix in config mgmt

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameLink.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/VulnerabilityStateTabs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx

> Ensure ARIA attributes are not prohibited for an element's role
https://dequeuniversity.com/rules/axe/4.10/aria-prohibited-attr?application=AxeChrome2
<div class="pf-v5-c-toolbar__group pf-v5-u-w-100" aria-label="applied search filters"><div class="pf-v5-l-flex pf-m-space-items-xs search-filter-chips"></div></div>
> aria-label attribute cannot be used on a div with no valid role attribute.
The offending `div` has no valid role because it is an empty element when no filters are applied. To fix, conditionally render this element only when there are applied filters and valid children.
Bonus! This removes a little bit of extra whitespace in the layout due to the empty element's padding.
---
> Ensure all ARIA attributes have valid values …

ROX-25748: Workload CVE a11y fixes

---

.github/workflows/scanner-release-vuln-update.yaml

```
2024-08-16T19:51:07.2144164Z ***"level":"warn","bundle":"nvd","component":"libvuln/updates/Manager.Run","error":"stat nvd.zip: no such file or directory","updater":"nvd","time":"2024-08-16T19:51:07Z","message":"failed configuring updater, excluding from current run"***
```
This appears to be caused by the directory change in the `Update vulnerabilities` step of job `upload-release-vulnerabilities` in workflow`Scanner release vulnerability update`:
N/A
Pending manual dispatch to verify: https://github.com/stackrox/stackrox/actions/runs/10426645191

fix: NVD data missing from latest ACS bundles

---

CHANGELOG.md
image/templates/helm/shared/templates/_openshift.tpl

Decided to use the following API:
```
❯ kubectl api-resources --api-group=project.openshift.io 
NAME              SHORTNAMES   APIVERSION                NAMESPACED   KIND
projectrequests                project.openshift.io/v1   false        ProjectRequest
projects                       project.openshift.io/v1   false        Project
```
which is of compatibility level 1 -- I think that's the best we can aim for using the current approach(?).
change me!

ROX-23343: Use different APIVersion of OpenShift auto-sensing

---

tools/retest/github.go
tools/retest/main_integration_test.go

We observed issue that auto-retest were not working correctly and does not respect capping. This was because we pull only first page of comments, which could result in a situation that we do not count all comments that were already created causing an infinite loop.
- https://github.com/stackrox/stackrox/pull/11986
---
CI

fix(retest): pull all PR comments for auto-retest

---

.devcontainer/devcontainer.json
.github/workflows/batch-load-test-metrics.yml
.github/workflows/build.yaml
.github/workflows/ci-failures-report.yml
.github/workflows/lint.yml
.github/workflows/scanner-build.yaml
.github/workflows/scanner-db-init-dump.yaml
.github/workflows/scanner-db-integration-tests.yaml
.github/workflows/scanner-dev-vuln-update.yaml
.github/workflows/scanner-release-vuln-update.yaml
.github/workflows/style.yaml
.github/workflows/unit-tests.yaml
.openshift-ci/Dockerfile.build_root
BUILD_IMAGE_VERSION
scale/signatures/deploy.yaml
tests/e2e/run-e2e-tests.sh

As titled. The updated image includes the change to `ubi8:latest` for the base image as well as an updated version of `ossls` to support license scanning in npm's `package-lock.json` file. This is the last known blocker for https://github.com/stackrox/stackrox/pull/11967.
Although not required to unblock #11967, I created the following PRs for consistency, although results have been mixed.
- Update to openshift-release config https://github.com/openshift/release/pull/55625 (TODO - This certainly needs more work to get the correct images in Prow based jobs. This is orthogonal to the need for the change in the current PR though.) 🟡 - no rehearse-able jobs
- Update to stackrox/infra https://github.com/stackrox/infra/pull/1354 🔴 failing with …

chore: Update rox-ci-image to 0.4.2

---

image/templates/helm/stackrox-secured-cluster/templates/admission-controller.yaml
pkg/pods/namespace.go
pkg/satoken/load.go
pkg/satoken/paths.go
sensor/admission-control/main.go
sensor/kubernetes/clusterhealth/updater.go
sensor/kubernetes/sensor/sensor.go
sensor/kubernetes/upgrade/command_handler_impl.go
sensor/kubernetes/upgrade/deployment.go
sensor/kubernetes/upgrade/process.go
sensor/upgrader/bundle/dynamic_objects.go
sensor/upgrader/common/namespaces.go
sensor/upgrader/common/shared_objects.go
sensor/upgrader/config/config.go
sensor/upgrader/preflight/namespace.go
sensor/upgrader/snapshot/snapshot.go

An experiment in entirely discarding the usage of SAToken namespace in favor of using POD_NAMESPACE as a followup to https://github.com/stackrox/stackrox/pull/11852
This is a big change with potentially large side effects since the SAToken namespace has been the source of truth for the namespace of sensor and admission-control up until now.
Associated docs PR: https://github.com/openshift/openshift-docs/pull/80351
Relying entirely on `POD_NAMESPACE` as our source of truth for the namespace that any given pod lives in could lead to unintended behavior since so far we've been using the SAToken namespace as our first option in both CreateSensor() as well as admissioncontrol mainCmd().
Our automated tests are not complaining now.
I've done the folllowing testing on GKE clusters as well as …

ROX-25673: Remove SA token namespace usage in favor of POD_NAMESPACE

---

ui/apps/platform/eslint.config.js
ui/apps/platform/src/Components/TextSelect/TextSelect.js
ui/apps/platform/src/Components/ToggleSwitch/ToggleSwitch.js

~My bad to base on another branch without need :(~ rebased to remove commits
These lint rules apply to HTML elements and attributes, therefore have continually decreasing relevance because continually increasing proportion of UI code renders HTML indirectly via PatternFly elements.
1. Remove from `devDependencies` after change from yarn to npm.
2. `yarn build` in ui/apps/platform

chore(ui): Remove jsx-a11y from ESLint config

---

ui/apps/platform/src/Containers/Dashboard/Widgets/AgingImagesChart.tsx
ui/apps/platform/src/Containers/Dashboard/Widgets/ComplianceLevelsByStandardChart.tsx
ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicyCategoryChart.tsx

> Interactive controls must not be nested
https://dequeuniversity.com/rules/axe/4.9/nested-interactive
> Focusable elements with an interactive control ancestor (any element that accepts user input such as button or anchor elements) are not announced by screen readers and create an empty tab stop. That is, you could tab to the element but the screen reader will not announce its name, role, or state.
```html
<svg width="483.5" height="260" role="img" aria-labelledby="victory-container-8-title" aria-describedby="victory-container-8-desc" viewBox="0 0 483.5 260" style="pointer-events: all; width: 100%; height: 100%;">
```
Element has focusable descendants
```html
<a href="/main/vulnerability-management/images?s[Image Created Time]=30d-90d&amp;sort[0][id]=Image Created …
```

ROX-25812: Change role for accessibility of chart links on dashboard

---

central/graphql/handler/handler_benchmark_test.go
central/testutils/export.go

See the title
Manual run of `ROX_SCALE_TEST=true go test -v -tags sql_integration -bench . -timeout 7200s` in:
- `central/graphql/handler`
- `central/deployment/service`
- `central/image/service`
- `central/vulnmgmt/service`

tests: Add benchmark tests for some GraphQL queries

---

image/templates/helm/stackrox-central/config/centraldb/postgresql.conf.default

The default logging configuration doesn't provide much information. Extend it to log essential details, which will be useful for troubleshooting, but not produce a torrent of logs.
Config changes were applied to a running central db and the resulting logs were verified.

ROX-25827: Configure Central DB to be more verbose

---

central/alert/service/service_test.go
central/cluster/datastore/datastore_sac_test.go
central/complianceoperator/v2/scans/datastore/datastore_impl_test.go
central/credentialexpiry/service/service_impl_test.go
central/metadata/service/service_impl_test.go
central/processbaseline/datastore/datastore_impl_test.go
central/vulnmgmt/vulnerabilityrequest/service/service_impl_test.go
migrator/migrations/m_183_to_m_184_move_declarative_config_health/migration_test.go
pkg/protoassert/assert.go
pkg/protocompat/empty_test.go
pkg/protocompat/time_test.go
pkg/protocompat/uint32_test.go
pkg/protoconv/time_test.go
pkg/protoutils/time_test.go
pkg/scanners/scannerv4/scannerv4_test.go

This is the follow-up to address https://github.com/stackrox/stackrox/pull/12335#pullrequestreview-2228330829
It changes protoassert to use EqualVT instead of `proto.Equal` as default types does not have `EqualVT` we need to use `proto.Equal` on them or convert to native types (e.g. duration or time)
CI

chore(proto): use EqualVT in protoassert

---

central/complianceoperator/v2/checkresults/datastore/datastore_impl.go
central/complianceoperator/v2/checkresults/datastore/datastore_impl_test.go
central/complianceoperator/v2/checkresults/datastore/stats_views.go
pkg/search/options.go

The status field uses a filter grab things like `fail_count`, `pass_count`, etc.  Things like this on the UI.
Those values are created using a filter and an a query alias.  We previously had no way to expose an efficient sort on an alias like this.  #12319 introduced the ability to add a custom sort option that can reference an alias.  This enables us to sort on these count values that are based on filters of a single column.  (Note:  This does not support `Other` as `Other` is grouped on the UI.  The API returns the individual counts so if we need to sort `Other` we would have to split it up)
Added some unit tests.
Tested all the endpoints that utilize the returning of these fields manually against a cluster.  Exercised both ascending and descending sort.

ROX-25769:  compliance use custom field sort

---

operator/pkg/central/extensions/reconcile_pvc.go
operator/pkg/central/extensions/reconcile_pvc_test.go

While working on [ROX-25446](https://issues.redhat.com/browse/ROX-25446), we found that the obsolete pvc annotation does not handle the annotation properly. If the annotation is applied, it also remove the central-db pvc owner reference. We should only honor the obsolete annotation for Central PVC.
This PR is targeted for release-4.5. The codes are being removed in master.
change me!

ROX-25836: Keep central db owner reference with obsolete annotation

---

tests/upgrade/postgres_run.sh

ROX-25435 was missed by the upgrade test because the upgrade test goes from 4.1.3 to current.  The issue in that ticket was introduced by a bug in a dependency in 4.3.1 and exacerbated by a worse bug in the same dependency in 4.5.0.   To find such we need to test both going from 4.1.3 to current AND walking each release between 4.1.3 and current.  This update simply adds a list of releases and walks through them.  We will update the release process to update the list each time a new patch is added.
To prove it works here is the failure when it hits 4.5.0.  https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/12203/pull-ci-stackrox-stackrox-master-gke-upgrade-tests/1818334937766432768
We cannot check in the test until we have 4.5.1 but I thought it …

ROX-25512:  walk upgrade

---

ui/apps/platform/eslint-plugins/pluginAccessibility.js
ui/apps/platform/src/Containers/Collections/CollectionForm.tsx

> Landmarks should have a unique role or role/label/title (i.e. accessible name) combination
https://dequeuniversity.com/rules/axe/4.10/landmark-unique
```html
<div class="pf-v5-c-expandable-section__content" id="expandable-rules-section" aria-labelledby="expandable-section-toggle-1723488786584mhx9u11lf7f" role="region">
```
Related node:
```html
<div class="pf-v5-c-expandable-section__content" id="expandable-attachment-section" aria-labelledby="expandable-section-toggle-1723488786586cks1i4znbh" role="region">
```
The landmark must have a unique `aria-label`, `aria-labelledby`, or `title` to make landmarks distinguishable
> When passing the `isDetached` property into `<ExpandableSection>`, you must also manually pass in the same `toggleId` and `contentId` properties to both …

ROX-25761: Improve accessibility of expandable sections in Collections

---

ui/apps/platform/eslint-plugins/pluginAccessibility.js
ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicyCategoryChart.tsx

> svg elements with img role must have an alternative text
https://dequeuniversity.com/rules/axe/4.9/svg-img-alt
```html
<svg width="483.5" height="260" role="img" aria-describedby="victory-container-1-desc" viewBox="0 0 483.5 260" style="pointer-events: all; width: 100%; height: 100%;">
```
> `aria-labelledby` attribute does not exist, references elements that do not exist or references elements that are empty
One `Chart` element lacks `ariaTitle` prop.
1. Edit pluginAccessibility.js file. Waiting until after we merge other contributions to rebase and then add rule.
* Add positive `Chart-ariaTitle-prop` rule.
2. Add unique `ariaTitle` prop to `Chart` element.
1. Fix other accessibility issue: Interactive controls must not be nested
1. Visit /main/dashboard
* Before changes, see presence …

ROX-25785: Add title for accessibility of chart on dashboard

---

pkg/features/features.go
pkg/features/list.go

ROX-25472: Add Microsoft Sentinel feature flag
This PR adds a feature flag to disable/enable the Microsoft Sentinel notifier.
- Run feature flag unit tests locally
- CI
- Build successfull

ROX-25472: Add Microsoft Sentinel feature flag

---

CHANGELOG.md
generated/api/v1/cve_service.pb.go
generated/api/v1/cve_service.swagger.json
pkg/grpc/marshaler.go
pkg/grpc/marshaler_test.go
pkg/grpc/server.go
proto/api/v1/cve_service.proto

This PR ensures backward compatibility for duration parsing in the JSON API. The updated proto version now exclusively handles durations in seconds, which introduces a breaking change. To mitigate this, we've implemented a custom marshaller that utilizes the previous proto version behaviour by using stdlib json marshaler. Additionally, we've announced the deprecation of the currently supported format, which will be fully removed in version 4.8 (ROX-25678).
The UI also requires updates to avoid using the deprecated format (ROX-25679):
https://github.com/stackrox/stackrox/blob/127dad71566547d3f79ea6d9894e75ad1ddda294/ui/apps/platform/src/constants/timeWindows.ts#L17-L23
For reference, see:
- https://github.com/golang/protobuf/issues/1374
- [Google Protobuf JSON …

ROX-25677: keep backward compatibility for duration format

---

central/views/common/queries.go
central/views/imagecve/view_test.go
pkg/search/options.go

The severity field uses a filter to get the counts by severity.  This is in support of things like the UI below:
Those values are created using a filter and an a query alias. We previously had no way to expose an efficient sort on an alias like this. https://github.com/stackrox/stackrox/pull/12319 introduced the ability to add a custom sort option that can reference an alias. This enables us to sort on these count values that are based on filters of a single column.
Added some unit tests.
Tested all the endpoints that utilize the returning of these fields manually against a cluster. Exercised both ascending and descending sort.  Tested in a graphql editor setting the following sort options and verifying that the order of data returned, was first by `important` and then by `critical`.

ROX-25770: vm custom sort field

---

central/notifiers/pagerduty/pagerduty.go
central/notifiers/splunk/splunk.go
central/splunk/violations.go
central/testutils/export.go
go.mod
pkg/auth/authproviders/registry_httphandler.go
pkg/auth/authproviders/registry_httphandler_test.go
pkg/httputil/error.go
pkg/httputil/error_test.go
pkg/jsonutil/proto.go
pkg/jsonutil/proto_test.go
pkg/notifiers/prune.go
sensor/kubernetes/listener/resources/dispatcher.go
sensor/upgrader/bundle/fetcher.go
tools/deserialize-proto/main.go
tools/deserialize-proto/main_test.go
tools/roxvet/analyzers/validateimports/analyzer.go

This PR replaces deprecated jsonpb with protojson. To make minimal changes the new function is created in `jsonutil` that creates new marshaler, use it and then writes to provided buffer.
CI

chore(proto): replace jsonpb with protojson

---

pkg/concurrency/signal.go
sensor/common/centralclient/grpc_connection.go
sensor/common/sensor/sensor.go
sensor/debugger/central/grpc_client.go

The `okSignal` and the `stopSignal` should be in the **un-triggered** state when we attempt to reconnect to central. If they're not reset then we can land in a situation where both are triggered and the `select` statement [here](https://github.com/stackrox/stackrox/blob/967702465ce812f74aec0b0cb26f2ae959d4e49d/sensor/common/sensor/sensor.go#L434-L442) will randomly choose one of them. In such a case, if `stopSignal` is chosen we will retry when unnecessary (potentially infinite times) leading to slow reconnects.

fix(sensor-connection): Reset the ok and stop signals on reconnection

---

central/deployment/datastore/datastore_impl.go

Update risk scores only of the ranker is present. This doesn't change anything on the main path, but makes it easier to use deployment datastorage in isolation, e.g. for other tools.
Manually validated via creating an isolated tool using the storage in this way.

ROX-25643: Handle missing ranker for ns/cluster

---

ui/apps/platform/src/css/acs.css

https://dequeuniversity.com/rules/axe/4.10/color-contrast
Element has insufficient color contrast of 2.95 (foreground color: #969696, background color: #ffffff, font size: 8.3pt (11px), font weight: normal). Expected contrast ratio of 4.5:1
```html
<label for="rc-editable-input-1" style="text-transform: uppercase; font-size: 11px; line-height: 11px; color: rgb(150, 150, 150); text-align: center; display: block; margin-top: 12px;">hex</label>
```
Related Node
```html
<div class="chrome-picker " style="width: 225px; background: rgb(255, 255, 255); border-radius: 2px; box-shadow: rgba(0, 0, 0, 0.3) 0px 0px 2px, rgba(0, 0, 0, 0.3) 0px 4px 8px; box-sizing: initial; font-family: Menlo;">
```
Default `color` on `input` that has …

ROX-25886: Fix accessibility of contrast in System Configuration

---

ui/apps/platform/src/Components/ExportButton.js
ui/apps/platform/src/Components/RelatedEntity.js
ui/apps/platform/src/Components/RelatedEntityListCount.js
ui/apps/platform/src/Components/WorkflowPDFExportButton.js
ui/apps/platform/src/css/trumps.css

Compliance dashboard also has issue with **Export** button.
> Elements must meet minimum color contrast ratios
https://dequeuniversity.com/rules/axe/4.10/color-contrast
**ExportButton** components
```html
<div class="flex items-center">Download Page as PDF</div>
```
Element has insufficient color contrast of 2.28 (foreground color: #ffffff, background color: #5fb2f7, font size: 10.5pt (14px), font weight: normal). Expected contrast ratio of 4.5:1
Related Node
```html
<button type="button" class="btn border-primary-600 bg-primary-600 text-base-100 w-48 hover:bg-primary-700 hover:border-primary-700  min-w-48 w-full" data-testid="download-pdf-button"><div class="flex items-center">Download Page as PDF</div></button>
```
**RelatedEntity** components
```html
<div>remote</div>
```
Element has …

ROX-25885: Fix accessibility of contrast in Configuration Management

---

.github/workflows/scanner-release-vuln-update.yaml

Changes the `Scanner release vulnerability update` workflow to upload to the user facing GCS bucket when run from master branch, and a test GCS bucket when run from any other branch. 
Also changes slack notifications to only be sent on failures on master branch runs (vs. any branch)
Why:
- Reduces chances of uploading garbage to the user facing GCS bucket
- Changes in non-master branches may not be tested / valid
- Reduces chances of users experiencing 'flapping data'
- Any vuln bundle changes uploaded to GCS via a non-master branch will be overwritten by the next scheduled job on master.
- Helps support focus on what's important
- Notifications sent from non-master runs are a distraction
No tests added
**Will need to validate on master post merge.**
Manually dispatched: …

chore: Scanner V4 only perform GCS upload from master branch

---

ui/apps/platform/eslint-plugins/pluginAccessibility.js

Follow up with prevention after remediation in #11774
1. `yarn lint` in ui/apps/platform for example of K8sCard.tsx file:
* no error with `toggleButtonProps` prop and `aria-label` property
* error with temporary edit to delete `aria-label` property.
* error with temporary edit to delete `toggleButtonProps` prop.

ROX-25963: Add lint rule for accessiblity of CardHeader onExpand

---

ui/apps/platform/eslint-plugins/pluginAccessibility.js
ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ExternalBackupIntegrations/GcsIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ExternalBackupIntegrations/S3CompatibleIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ExternalBackupIntegrations/S3IntegrationForm.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/CVESummaryLink.tsx
ui/apps/platform/src/css/trumps.css

Thank you, **David** for suggesting that `a` element has same issue!
> Interactive controls must not be nested
https://dequeuniversity.com/rules/axe/4.10/nested-interactive
**Images**
```html
<button aria-disabled="false" class="pf-v5-c-button pf-m-link pf-m-inline" type="button" data-ouia-component-type="PF5/Button" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Button-link-18">
```
Related Node
```html
<a href="/main/vulnerability-management/images?workflowState[0][t]=IMAGE&amp;workflowState[0][i]=sha256%3A0a4a31f1922e01645702401ac550fd89346244e2868cb9620f32f87fac0b7a5a&amp;workflowState[1][t]=IMAGE_CVE&amp;workflowState[1][i]=CVE-2022-37434%23alpine%3Av3.13">CVE-2022-37434</a>
```
**Auth providers**
```html
<button aria-disabled="false" class="pf-v5-c-button pf-m-link …
```

ROX-25916: Fix accessibility issues because Button contains Link

---

ui/apps/platform/src/Containers/Clusters/ClusterDeployment.tsx

Improve the explanation of what toggling the automatic upgrade button does in the UI
Created a cluster and had a look at the UI

ROX-25717: Improve the text for configuring cluster for updates

---

tests/e2e/lib.sh

Setting pause-reconcile annotation to `true` causes problem when deleting central and secured-cluster services in static clusters(ppc64le) before deploying and running tests.
This PR removes the annotation before cleanup of central and secured-cluster is performed. 
Change validated by running the change against an ocp 4.16 ppc64le cluster.

fix(CI): Remove pause-reconcile annotation before cleanup

---

go.mod
go.sum

roxctl tests are failing for this 
```
not ok 98 roxctl-development netpol connectivity diff generates conns diff report between resources from two directories dot output # in 392 ms
```
- #12536
---
CI

revert: bump np-guard/cluster-topology-analyzer

---

image/templates/CHANGING_CHARTS.md

This is *just* an addition to the internal documentation.
Doesn't require any!
Just proof-reading.

doc: Document whitspace trimming coding style for our helm charts

---

.github/workflows/scanner-dev-vuln-update.yaml

Inspired by https://github.com/stackrox/stackrox/pull/12453. This prevents PR builds of dev vulns from notifying the team. There is currently too much noise when testing, so this removes it.
This is the test
no

chore(ci): only notify failed master builds

---

scripts/ci/jobs/gke_operator_e2e_tests.py
scripts/ci/jobs/ocp_operator_e2e_tests.py
tests/e2e/lib.sh

Operator e2e jobs were not calling the piece of code responsible for recording image availability issues. This was likely because the same piece of code is also checking the status of stackrox deployment in a place which is not happening for operator e2e jobs.
This refactors the code a little such that only the necessary part is executed within operator jobs.
Ran the following query before and after creating this PR:
```
SELECT
*
FROM
`acs-san-stackroxci.ci_metrics.stackrox_tests`
WHERE
Classname = 'Image_Availability'
AND JobName LIKE '%operator%'
LIMIT
20
```
Before: `no results`
After:

tests(operator): call handle_e2e_progress_failures too

---

compliance/index/v4/node_test.go

This PR fixes failing `TestNodeIndexerSuite` that for some reasons started discovering more repositories than before.
CI

ROX-26003: fix TestNodeIndexerSuite

---

ui/apps/platform/eslint-plugins/pluginAccessibility.js
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/VulnerabilityStateTabs.tsx

> Landmarks should have a unique role or role/label/title (i.e. accessible name) combination
https://dequeuniversity.com/rules/axe/4.10/landmark-unique
**DeploymentPage**
```html
<nav class="pf-v5-c-tabs pf-v5-u-pl-md pf-v5-u-background-color-100" data-ouia-component-type="PF5/Tabs" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Tabs-1">
```
Related Node
```html
<nav class="pf-v5-c-tabs pf-m-box" data-ouia-component-type="PF5/Tabs" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Tabs-2">
```
**ImagePage**
```html
<nav class="pf-v5-c-tabs pf-v5-u-pl-md pf-v5-u-background-color-100" data-ouia-component-type="PF5/Tabs" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Tabs-3">
```
Related Node
```html
<nav class="pf-v5-c-tabs pf-m-box" …
```

ROX-25972: Fix accessibility issue of Tabs with nav element

---

sensor/admission-control/certs.go

When user installs in a namespace different namespace than `stackrox` then the messages from admission control are a bit scary and might steer users in a wrong way (especially if their actual problem is elsewhere).
Example:
```
main: 2024/08/28 20:40:36.506102 certs.go:51: Error: mTLS certificate with common name ADMISSION_CONTROL_SERVICE: 00000000-0000-0000-0000-000000000000 is not valid for DNS name admission-control.rhacs-operator.svc: x509: certificate is valid for admission-control.stackrox, admission-control.stackrox.svc, not admission-control.rhacs-operator.svc
main: 2024/08/28 20:40:36.506145 certs.go:65: Info: No usable certificates found, attempting to fetch certificates from sensor ...
```
This change tries to relax the wording a bit.
None.

feat(admission-control): less scary cert-related messages

---

operator/hack/common.sh
operator/hack/olm-operator-install.sh

https://quay.io/repository/rhacs-eng/stackrox-operator-bundle and https://quay.io/repository/rhacs-eng/stackrox-operator were made public today. This means we no longer need to have an image pull secret for the operator itself.
A nice side-effect is that there is no longer a delay while we wait for OLM to notice we patched it in.
Note this does not change anything about image pull secrets used by the operands.
Not a user-visible change
- upstream we don't currently ship the operator
- downstream users use a cluster-wide secret anyway
CI should be sufficient. I took a look at a few jobs before and after the change and here are anecdotal results (the timing varies a lot depending on OLM's mood at the moment, but it looks like the 5m wait is indeed gone).
<details>
<summary>GKE before: 56s …

tests(operator): no image pull secrets for operator

---

scanner/decisions/0009-nvd-cvss-scores.md
scanner/decisions/0010-nvd-cvss-scores.md

There is a desire to show both vendor-specific CVSS score as well as NVD's score. This PR adds the ADR for updating Scanner's API for this purpose.
Just a document
no
performed one does not seem sufficient. As a reviewer, you must not approve the change until you …

ROX-23657: NVD CVSS score ADR

---

pkg/cryptoutils/cryptocodec/crypto_codec_test.go
pkg/grpc/common/authn/servicecerttoken/token.go
tests/admctrl_configmap_test.go

This is the continuation of PR that replaces UnmarshalVT with UnmarshalVTUnsafe that reduces number of allocs
- #12494
---
CI

chore(proto): use UnmarshalVTUnsafe in pkg

---

central/sensor/service/connection/upgradecontroller/metrics.go
central/sensor/service/connection/upgradecontroller/process_check_ins.go
central/sensor/service/connection/upgradecontroller/register_connection.go
central/sensor/service/connection/upgradecontroller/trigger.go
central/sensor/service/connection/upgradecontroller/upgrade_controller_impl.go

This PR adds prometheus metric for counting the triggers of the upgrader.
- Deployed to the cluster and triggered various actions
Examplary record:
```
rox_central_upgrader_triggered_total{centralVersion="4.6.x-255-g51668cac50",clusterID="63e84bed-4d36-4d8a-8bbc-fcf2f15c00d9",sensorVersion="",triggerOrigin="new-connection-reconciliation",upgradeType="UPGRADE"} 1
rox_central_upgrader_triggered_total{centralVersion="4.6.x-255-g51668cac50",clusterID="63e84bed-4d36-4d8a-8bbc-fcf2f15c00d9",sensorVersion="4.5.0",triggerOrigin="ui-click",upgradeType="UPGRADE"} 1
```

ROX-25609: Add secured cluster upgrader metrics

---

Makefile

chore(feature): Add GENERATE_PATH env var to go-generated-srcs 
To execute `go-generated-srcs` faster you can now use `GENERATE_PATH=./central/notifiers/... make go-generated-srcs` to generate code only for a subset of files.

chore(feature): Add GENERATE_PATH env var to go-generated-srcs 

---

ui/apps/platform/cypress/integration/clusters/redirectFromDashboard.test.js
ui/apps/platform/eslint-plugins/pluginAccessibility.js
ui/apps/platform/src/Components/GroupedTabs.js
ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterModal.tsx
ui/apps/platform/src/Containers/Clusters/NoClustersPage.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPage.tsx

> ARIA attributes must conform to valid values
https://dequeuniversity.com/rules/axe/4.10/aria-valid-attr-value
```html
<button type="button" data-ouia-component-type="PF5/TabButton" data-ouia-safe="true" class="pf-v5-c-tabs__link" id="pf-tab-ACTIVE-pf-1724248588744l3gaytp96j" aria-controls="pf-tab-section-ACTIVE-pf-1724248588744l3gaytp96j" role="tab" aria-selected="true">
```
Circular reference in which `aria-controls` refers to `id` of `button` element.
> identifies the element (or elements) whose contents or presence are controlled by the element on which this attribute is set
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls
> If a `<TabContent>` component is defined outside of a `<Tabs>` component, use the `tabContentRef` and `tabContentId` …

ROX-25884: Add contentId prop for accessibity of empty Tab elements

---

image/rhel/konflux.Dockerfile
ui/Makefile

Adds the `--ignore-scripts` option to `npm ci` when building in konflux pipelines.
There is [an issue](https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1724060332345539) when building in konflux for s390x and ppc64le architectures that causes npm to error out with `ENOMEM` errors during the dependency installation phase.
I suspect, but have not proven, that this could be related to this issue: https://github.com/nodejs/node/issues/25382 where child processes request as much memory as the parent process. Further evidence of this was detected when running `npm ci` with `--loglevel warn --foreground-scripts` which causes `preinstall`/`postinstall`/etc modules scripts to be run in serial after the modules are downloaded. The logs showed that there were four instances of a `postinstall` …

fix(ui): Disable npm postinstall scripts on konflux builds

---

CHANGELOG.md
central/policy/service/service_impl.go
central/policy/service/service_impl_test.go

As the title says, check in an API DELETE request, if the specified policy is a default one, and if it is, have the API return a helpful error message instead.
First, added a unit test to prevent regression in the future.
Second, to test manually end-to-end, I deployed an image from this PR, then I made a `curl` call to try to delete one of ACS's default policies, "30-Day Scan Age".
```
$ curl 'https://localhost:3000/v1/policies/a3eb6dbe-e9ca-451a-919b-216cf7ee11f5' \
>   -X 'DELETE' \
>   -H 'Accept: application/json, text/plain, */*' \
>   -H 'Accept-Language: en-US,en;q=0.9' \
>   -H 'Authorization: Bearer ...   
>   -H 'Accept-Language: en-US,en;q=0.9' \
>   -H 'Connection: keep-alive' \
>   -H 'Cookie: ajs_user_id=OkHeTkS1+VtT9LZ/1ubKdf8JMiRxYBJZJcVzDcOaWPc=; …
```

ROX-22701: Prevent deleting default policies through the API

---

.tekton/basic-component-pipeline.yaml
.tekton/main-pipeline.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml
image/postgres/konflux.Dockerfile
image/rhel/konflux.Dockerfile
image/roxctl/konflux.Dockerfile
operator/konflux.Dockerfile
operator/konflux.bundle.Dockerfile
scanner/image/db/konflux.Dockerfile
scanner/image/scanner/konflux.Dockerfile

Adds ecosystem preflight check (https://github.com/redhat-openshift-ecosystem/openshift-preflight) task to all pipelines in this repository.
~To discuss: add also for operator-bundle? It is "only" a collection of text files and triggers some warnings, see below.~
https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1725522951955559?thread_ts=1725459706.460459&cid=C05TS9N0S7L -> not required for operator-bundle. But adding LICENSE can't hurt, right?
All other components pass the check, if we ignore the issue caused by KFLUXBUGS-1495 that sets the `version` label on container images to an empty string.
- ~[ ] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag~
- ~[ ] added regression …

ROX-25723: add ecosystem preflight check

---

ui/apps/platform/src/Components/EmailTemplate/EmailTemplateModal.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/CvesByStatusSummaryCard.tsx

Follow up to fix residue in Vulnerabilities after **Platform CVEs** and **Node CVEs** in #12563
> Landmarks should have a unique role or role/label/title (i.e. accessible name) combination
https://dequeuniversity.com/rules/axe/4.10/landmark-unique
```html
<div id="" class="pf-v5-c-card pf-m-compact pf-m-flat" role="region" aria-live="polite" aria-busy="false" data-ouia-component-type="PF5/Card" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Card-2">
```
Related Node
```html
<div class="workload-cves-table-container" role="region" aria-live="polite" aria-busy="false">
```
Landmarks should have a unique role, because multiple elements on page have `role="region"` attribute.
ARIA live region does not require `role="region"` attribute: …

ROX-26019: Fix more accessiblity issues for landmarks of live regions

---

ui/apps/platform/cypress/integration/configmanagement/ConfigurationManagement.helpers.js
ui/apps/platform/cypress/integration/vulnmanagement/VulnerabilityManagement.helpers.js
ui/apps/platform/cypress/integration/vulnmanagement/VulnerabilityManagement.selectors.js
ui/apps/platform/eslint-plugins/pluginGeneric.js
ui/apps/platform/eslint.config.js
ui/apps/platform/src/Components/ScannerV4IntegrationBanner.tsx
ui/apps/platform/src/Containers/Clusters/Components/CredentialExpiration.tsx
ui/apps/platform/src/Containers/Clusters/StaticConfigurationSection.js
ui/apps/platform/src/Containers/Compliance/List/SidePanel.js
ui/apps/platform/src/Containers/Compliance/widgets/VerticalBarChart.js
ui/apps/platform/src/Containers/ConfigManagement/SidePanel/SidePanel.js
ui/apps/platform/src/Containers/Images/VulnsTable.js
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/MachineAccessIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/SignatureIntegrationForm.tsx
ui/apps/platform/src/Containers/Login/LoginPage.js
ui/apps/platform/src/Containers/Risk/RiskDetails.js
ui/apps/platform/src/Containers/VulnMgmt/Entity/Cve/VulnMgmtCveOverview.js
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/AffectedComponents/AffectedComponentsModal.tsx
ui/apps/platform/src/Containers/VulnMgmt/WorkflowSidePanel.js
ui/apps/platform/src/Containers/Vulnerabilities/components/ExceptionRequestModal/CveSelections.tsx
ui/apps/platform/src/css/trumps.css

Write generic lint rules to follow up specific lint rule for accessibility in #12497
1. Add eslint-plugins/pluginGeneric.js file.
* Add positive `ExternalLink-a`, `Link-target-rel`, and `a-target-rel` lint rules.
2. Edit eslint.config.js file.
* Import plugin.
* Add generic recommended rules for product files.
1. Edit ScannerV4IntegrationBanner.tsx file.
* Rewrite according to lead-in link pattern.
* Render `ExternalLink` element.
2. Edit CredentialExpiration.tsx file.
* Render `ExternalLink` element.
3. Edit StaticConfigurationSection.js file.
* Rewrite as separate sentences.
* Render `ExternalLink` element.
4. Edit compliance SidePanel.js file.
* Add `rel="noopener noreferrer"` prop.
* Replace explicit color with style rules.
* Replace `ExternalLink` from react-feather with …

fix(ui): Add pluginGeneric and improve consistency of external links

---

scanner/cmd/updater/main.go

Later releases increased this timeout. Some older version of 4.4.z have failed due to timeout. This protects future versions from dealing with this timeout
not needed
I didn't

chore(scanner): bump vuln timeout

---

ui/apps/platform/package-lock.json
ui/apps/platform/package.json

Uninstalls `npm-run-all` and other dependencies that were automatically detected as unused as a result of the `yarn` -> `npm` migration.
CI

ROX-25750: Remove npm run all dependency

---

compliance/collection/compliance/compliance.go
compliance/collection/main.go
compliance/index/v4/node.go
compliance/index/v4/node_test.go
pkg/env/node_scan_v4.go

This is a follow up to https://github.com/stackrox/stackrox/pull/12555.
After a change in the Red Hat Repo to CPE mapping json the unit test started failing, as it is dynamically pulling the latest mapping information from Red Hat.
This PR introduces a configuration structure for the NodeIndexer to configure the called URLs (amongst other options).
This allows us to test against a statically served mapping JSON, removing the dependency on Red Hat infrastructure.
Additionally, this configuration is needed to be in sync with Scanner v4 settings, as it utilizes the same scanners that the NodeIndexer uses, and ideally both Indexers are configured identically.
I recommend to review the PR by looking at the separate commits one after the other.
Running the unit tests locally without Network …

ROX-26018: Introduce NodeIndexer configuration

---

CHANGELOG.md
central/sensorupgrade/service/service_impl.go
central/sensorupgrade/service/service_impl_test.go
pkg/env/managed.go
ui/apps/platform/src/Containers/Clusters/Components/AutoUpgradeToggle.tsx

This PR decouples the sensor upgrader from the `ROX_MANAGED_CENTRAL` env var and introduces new variable `ROX_SENSOR_UPGRADER_ENABLED` (default: true) that controls whether the upgrader is enabled.
I additionally fix here the potential issue where the test suite can be incorrectly stopped by a subtest.
⚠️ It is okay to review but don't merge yet - we want to wait with the enabling until we investigate all potential blockers for the upgrader.

ROX-25451: Re-enable Sensor upgrader

---

image/templates/helm/stackrox-secured-cluster/templates/collector.yaml.htpl

For Node Indexing to work on the compliance container, some changes to the Helm chart are needed.
Namely, we are mounting a small part of the Node filesystem as read only, and set the fitting environment variables.
Used the updated Helm chart to deploy, then manually changed the images to the ones from #12448, which contain the new code. 
Used the updated Helm chart to deploy to OpenShift 4 and to  a GKE cluster. On the GKE cluster I verified that the deployment is functional and does not contain any of the settings needed for Node Indexing.

ROX-25540: Update Helm charts

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/SearchFilterAutocomplete.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/SimpleSelect.tsx

Fixes accessibility issues in Workload, Node, and Platform CVEs (as well as any other place using the new search filter components).
With any of the new filter component dropdowns opened:
1. Ensure every ARIA input field has an accessible name
2. Ensure ARIA attributes are not prohibited for an element's role
The `aria-label` attribute was previously placed on the containing `<div>` element via the `<Select>` component, instead of on the visible `<ul>` element via the `<SelectList>` component.
Adjust the placement of the `aria-label` in the reusable `<SimpleSelect>` component so that it targets the semantic rendered menu element.
---
With the autocomplete dropdown open:
1. Ensure all ARIA attributes have valid values
The `aria-controls` attribute references an element that does not exist. …

ROX-26095: fix filter bar accessibility issues

---

central/delegatedregistryconfig/delegator/delegator.go

Adjusts an error's message that prior would not include the image full name:
```
error delegating scan to cluster "caee1aa5-eb10-42fd-8637-2813df3d8e49" for "": too many parallel scans to local scanner
```
Notice the empty `""`, it would now become (for example):
```
error delegating scan to cluster "caee1aa5-eb10-42fd-8637-2813df3d8e49" for image "docker.io/library/nginx:latest": too many parallel scans to local scanner
```
The missing image name would only surface on 'early' failures handled here:
https://github.com/stackrox/stackrox/blob/784baf57f42afa59ba78b0c1cb0d0d515cc4cb01/central/image/service/service_impl.go#L680-L686
Failures with the actual scan (such as 404 pulling metadata) were NOT affected.
N/A
To trigger the "too many parallel requests" error, on an OCP infra cluster …

ROX-26050: Fix empty image name in delegator error message

---

.tekton/basic-component-pipeline.yaml
.tekton/operator-build.yaml
operator/Makefile
operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml

* Passing the `operator` Makefile directory ensures the operator image has the `x.y.0-...` tag format
* marking the additional architectures in the operator bundle 
- ~[ ] existing tests pass
Used [instructions](https://github.com/stackrox/stackrox/tree/master/operator#launch-the-operator-on-the-cluster-with-olm-and-the-bundle) to deploy the operator with OLM from the bundle and steps from https://issues.redhat.com/browse/ROX-23707 to deploy ACS.

ROX-24401: fix operator image tag and supported architectures

---

generated/storage/policy.pb.go
pkg/postgres/schema/alerts.go
pkg/postgres/schema/policies.go
proto/storage/policy.proto

The customer is experience frequent timeouts with the following query:
```
select "alerts".serialized from alerts where (alerts.Policy_Id = $1 and ((alerts.State = $2) or (alerts.State = $3)))
```
There is not an index on the `Policy_Id` and the `or` on `state` negates the index on `state` causing a full table scan.
(Note:  the `and ((alerts.State = $2) or (alerts.State = $3))` gets blanketly added to almost all queries of alerts in a non-obvious way.  I'm not a huge fan of that nor the `or`.  But that is a battle for another day.)
Before this change, query such as:
```
select "alerts".serialized from alerts where (alerts.Policy_Id = 'dce17697-1b72-49d2-b18a-05d893cd9368' and ((alerts.State = 0) or (alerts.State = 2)))
```
would explain as:
```
Seq Scan on alerts as alerts (rows=49 …
```

ROX-26104: add index on policy id to alert table

---

ui/apps/platform/package-lock.json
ui/apps/platform/package.json

https://docs.cypress.io/guides/references/changelog#13-14-0
* Added new `experimentalJustInTimeCompile` configuration option for component testing. This option will only compile resources directly related to your spec, compiling them 'just-in-time' before spec execution. This should result in improved memory management and performance for component tests in cypress open and cypress run modes, in particular for large component testing suites.
https://docs.cypress.io/guides/references/experiments#Experimental-Just-In-Time-Compile
* `.type({upArrow})` and `.type({downArrow})` now also works for date, month, week, time, datetime-local and range input types. 
* Updated `detect-port` from 1.3.0 to 1.6.1.
https://docs.cypress.io/guides/references/changelog#13-13-3
* Updated `image-size` from …

chore(e2e): Update cypress 13.14.2 devDependencies in ui

---

ui/apps/platform/src/Components/ReportJobsHelpAction.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ConfigDetails.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
ui/apps/platform/src/types/reportJob.ts
ui/apps/platform/src/utils/reportJob.ts

This PR splits the Scan schedule details page into tabs that show configuration details and all report jobs. This also includes some layout/styling changes to VM reports

ROX-25934: Add tab to see 'All report jobs'

---

central/hash/manager/deduper.go
central/hash/manager/deduper_test.go
central/sensor/service/connection/sensorevents.go

This PR aims to fix a bug in how the deduper logic handles reconnections. 
The deduper contains two maps `successfullyProcessed` and `received`:
`successfullyProcessed` contains the hashes of events that have been successfully processed. This means central is done with these events and can be removed from memory.
`received` contains hashes of events that have been received in central but have not yet being processed. These events are pushed in a queue that gets deleted once sensor reconnects. This means that central loses all these events but holds the information of the hashes. 
On reconnection the content of both maps gets invalidated (the `processed` field of each entry is set to `false`).
The problem lies on the `ShouldProcess` function as it does not check if the `processed` field is …

fix(deduper): Fix ShouldProcess function in the deduper

---

ui/apps/platform/cypress/integration/networkGraph/networkDeploymentSidebar.test.js

A recent change has made it so that a network flow is displayed between `collector` and `central` when running on OCP clusters, which breaks existing e2e tests.
This fix disables the assertion on the presence or absence of `central` when the filter is applied in order to get tests green again. When @Maddosaurus returns from OOO we will confirm whether or not this should be the expected behavior on OCP _and_ GKE clusters moving forward, and update this test again if needed.
For more context: https://redhat-internal.slack.com/archives/CFMQ5C2TT/p1726047673403259
CI

ROX-26121: Do not assert on presence of central in NG test

---

.github/workflows/scanner-mapping-update.yaml
pkg/scannerv4/mappers/mappers.go
scanner/config.yaml.sample
scanner/config/config.go
scanner/image/scanner/download-mappings.sh
scanner/updater/rhel/doc.go
scanner/updater/rhel/updaterset.go

Red Hat security data is migrating to a new location: `https://security.access.redhat.com/data`. This PR updates all instances of the old `redhat.com/security/data` to the new location.
Claircore will need to be bumped to complete this migration, but that'll be done in a separate PR.
Set the label `pr-update-scanner-vulns` to ensure vuln updates still run properly

chore(scanner): update Red Hat sec data location

---

.github/actions/download-artifact-with-retry/action.yaml
.github/workflows/scanner-versioned-definitions-update.yaml
.github/workflows/scripts/scanner-get-released-tags.sh
.github/workflows/scripts/scanner-output-release-versions.sh
scanner/updater/version/RELEASE_VERSION
scanner/updater/version/VULNERABILITY_BUNDLE_VERSION

I noticed current runs for this job are uploading vulnerability bundles for all PRs, even without the label. This PR ensures that label must be included before bothering to create bundles for the PR. While I was here, I also did other miscellaneous fixes. All fixes done here are:
* Don't bother running `parse-versions`, `prepare-environment`, and `build-upload-pr-vulnerabilities` in PRs unless the `pr-update-scanner-vulns` label is set
* Removed `Set Updater` steps in jobs, as it's not needed
* Moved setting `STACKROX_NVD_ZIP_PATH: nvd.zip` to be job-global, as the file is always hardcoded to nvd.zip wherever it's used
* Moved a few steps around
* Updated `upload-definitions`'s `checkout` steps and swapped `actions/download-artifac@v4` with …

chore: fix versioned vulns job

---

sensor/admission-control/settingswatch/common.go
sensor/admission-control/settingswatch/k8s.go
sensor/admission-control/settingswatch/mount.go
sensor/admission-control/settingswatch/persist.go
sensor/common/centralclient/client.go
sensor/tests/helper/trace.go

This is the continuation of PR that replaces UnmarshalVT with UnmarshalVTUnsafe that reduces number of allocs
- #12494
---
CI

chore(proto): use UnmarshalVTUnsafe in sensor

---

ui/apps/platform/package-lock.json
ui/apps/platform/package.json
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.tsx
ui/apps/platform/src/Containers/Collections/errorUtils.ts

https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/
* https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#inferred-type-predicates
> TypeScript now infers a type predicate for the `filter` function.
* https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#control-flow-narrowing-for-constant-indexed-accesses
> TypeScript is now able to narrow expressions of the form `obj[key]` when both `obj` and `key` are effectively constant.
* https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#the-jsdoc-import-tag
> TypeScript now supports a new `@import` comment tag that has the same syntax as ECMAScript imports.
* https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#regular-expression-syntax-checking
> TypeScript now …

chore(ui): Upgrade TypeScript 5.5.4 and related devDependencies in ui

---

image/templates/helm/shared/config-templates/scanner-v4/matcher-config.yaml.tpl

This is very simple change to change the default Scanner Matcher configuration to pass the bundle schema version instead of the StackRox release when pulling vulnerabilities. This is possible now that we are publishing versioned bundles and [configuration has been changed to support this](https://github.com/stackrox/stackrox/pull/12394).
Tests for this functionality were covered/performed in the linked PRs.
1. Create a scanner image with a release tag: `make -C scanner image-scanner GOTAGS=release`
2. Deploy StackRox Central to a Openshift cluster.
3. Observe logs containing the correct bundle version being requested from Central:
```
{"level":"info","host":"scanner-v4-matcher-7dd948d5d5-wjzp9","component":"matcher/updater/vuln/Updater.fetch","url":"https://central.stackrox.svc/api/extensi …
```

feat(scanner): Use versioned bundles

---

.tekton/basic-component-pipeline.yaml
.tekton/main-pipeline.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml
operator/konflux.bundle.Dockerfile

This should fix build failure seen in https://github.com/stackrox/stackrox/pull/12684 / https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/operator-bundle-build-d8jck
```
[build] ============================== 15 passed in 0.04s ==============================
[build] + operator-sdk
[build] go: go.mod requires go >= 1.22 (running go 1.21.11; GOTOOLCHAIN=local)
[build] make: *** [Makefile:178: /stackrox/operator/.gotools/bin/operator-sdk] Error 1
[build] subprocess exited with status 2
[build] subprocess exited with status 2
[build] Error: building at STEP "RUN make bundle-post-process": exit status 2
```
The reason is that ubi9 has only Go 1.21.11 and so we need to use `openshift-golang-builder` instead.
Once switched to …

build: Switch operator-bundle build from Go 1.21 to 1.22

---

central/apitoken/datastore/internal/schedulestore/postgres/store.go
central/config/store/postgres/store.go
central/delegatedregistryconfig/store/postgres/store.go
central/installation/store/postgres/store.go
central/notifier/encconfig/datastore/store/postgres/store.go
central/sensorupgradeconfig/datastore/internal/store/postgres/store.go
migrator/migrations/postgreshelper/schema/convert_test_child1.go
migrator/migrations/postgreshelper/schema/convert_test_child1_p4.go
migrator/migrations/postgreshelper/schema/convert_test_child2.go
migrator/migrations/postgreshelper/schema/convert_test_g2_grand_child1.go
migrator/migrations/postgreshelper/schema/convert_test_g3_grand_child1.go
migrator/migrations/postgreshelper/schema/convert_test_g_grand_child1.go
migrator/migrations/postgreshelper/schema/convert_test_grand_child1.go
migrator/migrations/postgreshelper/schema/convert_test_grandparents.go
migrator/migrations/postgreshelper/schema/convert_test_parent1.go
migrator/migrations/postgreshelper/schema/convert_test_parent2.go
migrator/migrations/postgreshelper/schema/convert_test_parent3.go
migrator/migrations/postgreshelper/schema/convert_test_parent4.go
migrator/migrations/postgreshelper/schema/convert_test_short_circuits.go
migrator/migrations/postgreshelper/schema/convert_test_single_key_structs.go
migrator/migrations/postgreshelper/schema/convert_test_single_uuid_key_structs.go
migrator/migrations/postgreshelper/schema/convert_test_structs.go
tools/generate-helpers/pg-table-bindings/migration_tool.go.tpl
tools/generate-helpers/pg-table-bindings/singleton.go.tpl

This is the continuation of PR that replaces UnmarshalVT with UnmarshalVTUnsafe that reduces number of allocs
- #12494
---
CI

chore(proto): use UnmarshalVTUnsafe in singelton

---

ui/apps/platform/src/Containers/Policies/Wizard/Step2/PolicyBehaviorForm.tsx

Policy rules are dependent on the selected lifecycle, which can lead to errors if rules are created and the lifecycle is changed later. To avoid potential issues, we should clear the rules when the lifecycle is modified, similar to the approach used in the edit workflow.
1. Select a lifecycle.
2. Add a rule.
3. Return to edit the lifecycle stage selection.
4. Confirm that the rules have been cleared.

ROX-25763: Clear policy rules when lifecycle changes

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPage.tsx
ui/apps/platform/src/services/ComplianceResultsStatsService.ts

Stats currently update only when changing profiles; they should also reflect the filtered schedule.
Created two separate schedules that both scan on `ocp4-cis`: one with `control-cluster` and the other with `staging-secured-cluster`. When the scan schedule is not filtered, we see combined scan stats. When filtering by an individual schedule, stats should only reflect the selected cluster.
Without schedule filter (both clusters included):
With schedule filter (only one cluster):

ROX-25764: Update compliance stats widget on schedule selection

---

ui/apps/platform/src/hooks/useURLSort.test.js

The `useURLSort` hook will require a very large refactor/rewrite in order to support multiple sort options. This PR adds many more test cases to ensure the existing functionality is well tested before implementing a change.
`npm run test`

test(ui): Add more coverage to `useURLSort` unit tests

---

ui/apps/platform/src/Containers/Policies/Detail/PolicyOverview.tsx
ui/apps/platform/src/Containers/Policies/Modal/PolicyImport.utils.test.ts
ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.tsx
ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.utils.ts
ui/apps/platform/src/Containers/Policies/policies.utils.test.ts
ui/apps/platform/src/Containers/Policies/policies.utils.ts
ui/apps/platform/src/types/policy.proto.ts

Updates the "Origin" column on the policies table to account for new, externally managed policies. This also replaces the "Type" field on policy detail pages with "Origin" for consistency in naming, since both sections communicate the same information but using a different term.
Depends on #12659 
_Note that a follow up conversation is on the agenda with UX to determine how closely we should align Access Control sections with the below terminology._
Before:
|`Policy.isDefault`|`Policy.source`|display text|
|-----------------|-----------------|-----------|
|true|`undefined`|**System**|
|false|`undefined`|**User**|
After
|`Policy.isDefault`|`Policy.source`|display text|
|-----------------|-----------------|-----------|
|true|IMPERATIVE|**System**|
|true|DECLARATIVE|**System**| …

ROX-25617: Add display value for external policy origin in UI

---

Makefile
config-controller/internal/controller/suite_test.go
config-controller/pkg/client/client_test.go
config-controller/test/e2e/e2e_suite_test.go

I had originally excluded all config-controller unit tests, but now that we have a few that need to be run in CI, I am including the `config-controller` directory and am commenting out the tests that still don't work.  The commented tests have a TODO to ensure we follow up on this.
Check results of unit tests. Of course they should pass, but the results should include passing tests from `config-controller/pkg/client` and `config-controller/api`

ci: Enable config-controller unit tests

---

ui/apps/platform/src/Components/NotifierConfiguration/NotifierConfigurationView.tsx
ui/apps/platform/src/Components/ReportJobsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ReviewConfig.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ConfigDetails.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/JobDetails.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/ReportParametersDetails.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/ScheduleDetails.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportReviewForm.tsx
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts

1. We created a new `ReportJobsTable` component that takes care of rendering the jobs table. We will use this table for both Compliance and VM Reports. We'll use it for Compliance first.
2. I removed the card-specific components from `ConfigDetails`, allowing both `JobDetails` and `ConfigDetails` to be combined and grouped within a card in the expandable section of the jobs table.
3. I added a type for the `ConfigDetails` props.
4. I created a `ReportJobs` component that will do data-fetching (eventually) and render the data in the `ReportJobsTable` component. For now, I'm just using mock data.
5. I modified `JobDetails` to take `reportStatus` and `isDownloadAvailable` instead of `reportSnapshot` so its more reusable in the Compliance context.
6. I added a new …

ROX-25939: Add report jobs table

---

scripts/ci/jobs/gke_nongroovy_compatibility_tests.py

Adds a dummy target `gke-nongroovy-compatibility-tests` so that I can add it to the openshift CI
None

ROX-25183: Dummy compatibility target

---

pkg/k8sintrospect/collector.go
pkg/k8sintrospect/default_config.go
tools/roxvet/analyzers/validateimports/analyzer.go

Add CRs to `_ungrouped` directory in the diagnostic bundle.
```
stackrox
├── admission-control
│  ....
├── sensor
│   ...
├── stackrox
│   ├── ...
└── _ungrouped
├── central-stackrox-central-services.yaml
├── configmap-admission-control.yaml
├── configmap-kube-root-ca.crt.yaml
├── secret-sh.helm.release.v1.stackrox-central-services.v1.yaml
├── secret-sh.helm.release.v1.stackrox-secured-cluster-services.v1.yaml
└── securedcluster-stackrox-secured-cluster-services.yaml
```
- Create a Kubernetes cluster and install the RHACS operator into it
- Install StackRox using the Central and SecuredCluster custom resources
- Fetch a diagnostic bundle from Central, run `ls -la ./_ungrouped`

ROX-25440: Add stackrox CRs to diagnostic bundle

---

ui/apps/platform/src/Containers/Clusters/ClusterDeployment.tsx

Follow-up to: https://github.com/stackrox/stackrox/pull/12460
This applies only to legacy-installation method of secured cluster. The previously used text could suggest that the toggle was for switching between manual or automated upgrades. That was not correct, as the toggle does not do this. Instead it configures the cluster to *enable* automated or on-click upgrades of the clusters. Switching this toggle off would cause all upgrade attempts to fail no matter how they were triggered. Whether the upgrade is triggered automatically or manually is set in a different place (on the clusters page).
Additionally, I separated optically the step of the configuration (with the toggle) from the download step, to make it more prominent and visible. This should help users read the text about the …

ROX-26274: Improve the UI text for upgradability of clusters 

---

tests/e2e/lib.sh

This PR is adding an additional check on the collector DaemonSet state before checking pod states. This will ensure that all pods are re-scheduled and ready after any change on DaemonSet. Collector rollout usually takes longer because of the update strategy:
```
"updateStrategy": {
"rollingUpdate": {
"maxSurge": 0,
"maxUnavailable": 1
},
"type": "RollingUpdate"
}
```
also, we have always had a few pods deployed by collector daemonset.
Here are some test logs that indicate this problem:
```
Sensor is running
NAME        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
collector   3         3         3       0            3           <none>          22s
Waiting for collectors to start
Collectors are running
INFO: Mon Sep  9 16:05:42 UTC 2024: Will wait for collectors …
```

chore(CI): Add collector DaemonSet state check before checking pods

---

ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsToolbar.tsx
ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersToolbar.tsx
ui/apps/platform/src/Containers/Collections/CollectionsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ScanConfigClustersTable.tsx
ui/apps/platform/src/Containers/NetworkGraph/simulation/DeploymentScopeModal.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ApprovedDeferrals/ApprovedDeferrals.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ApprovedFalsePositives/ApprovedFalsePositives.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/DeferredCVEs/DeferredCVEs.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/FalsePositiveCVEs/FalsePositiveCVEs.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ObservedCVEs/ObservedCVEs.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/PendingApprovals/PendingApprovals.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx
ui/apps/platform/src/services/DiscoveredClusterService.ts

A handful more refactoring changes related to UI pagination.
The previous PR with a change to `getPaginationParams()` only covered sections that were strictly necessary in order to implement multiple sort parameters in `useURLSort()`. As a quick check, I searched for `page - 1` and found more sections that were trivial to refactor to use the helper function.
This additionally removes all instances where `setPage(1);` is called when changing the current `perPage` value. The `useURLPagination()` hook was updated a while back to do this automatically internally, so the additional call is redundant.
CI
Manual testing of:
- Admin Events page
- Listening endpoints page
- Discovered clusters page
- Collections page
- Compliance schedules page
- Net Graph deployment scope
- VM Exception …

chore(ui): Move more UI code to common page util

---

ui/apps/platform/src/Components/CheckboxSelect.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/ConditionDate.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/ConditionNumber.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/SearchFilterAutocomplete.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/MyJobsFilter.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportStatusFilter.tsx
ui/apps/platform/src/utils/ensure.ts

1. Creates a **ReportStatusFilter** and **MyJobsFilter** component that we can eventually reuse in VM Reporting too
2. I moved the **CheckboxSelect** component out of the **CompoundSearchFilter** directory and into the general components directory. This way, we can reuse it for standalone filters. It should also take a toggle icon now.
> **Note**: We have another **CheckboxSelect** component in `apps/platform/src/Components/PatternFly/CheckboxSelect.tsx` that uses the deprecated PF **Select** component. I'm thinking of doing a separate refactor to use this updated one instead. It should take care of this tech debt item.

ROX-25937: Add status and toggle filters for report jobs

---

.konflux/scripts/subscription-manager/subscription-manager-bro.sh
.tekton/main-pipeline.yaml

See the ticket's description. The key is already set up.
No change to automated testing.
- Put the key in `.konflux/scripts/subscription-manager/activation-key` locally and ran `subscription-manager-bro.sh self-test`.
- CI.

ROX-26047: Switch to prod subscription-manager activation key

---

image/postgres/konflux.Dockerfile
image/rhel/konflux.Dockerfile
image/roxctl/konflux.Dockerfile
operator/konflux.Dockerfile
operator/konflux.bundle.Dockerfile
scanner/image/db/konflux.Dockerfile
scanner/image/scanner/konflux.Dockerfile

See the mentioned ticket.
I did not include `VERSIONS_SUFFIX` arg in the check because it will be soon undone for the Stable Stream, although I tested that it's set too.
No autotests.
If CI is green, it's good.
Also:
- tested the `RUN` statement actually catches unset args - https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-build-mc6rz/logs
- tested that `VERSIONS_SUFFIX` is set - https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/roxctl-build-6wnsm/logs?task=build-container-ppc64le

ROX-25565: Fail Konflux builds if required ARGs aren't provided

---

central/debug/service/service.go

This is part of the effort to triage SAST findings.  There is a slim chance that the error converting a time could leak some unencoded user input.  So I updated it to log the time error and then to provide back to the user an encoded version of the input.  Possible this still fails the findings.
Before the change (Notice the script tags in the output have no escaping):
```
dashrews-mac:stackrox dashrews$ roxctl --insecure-skip-tls-verify -e central-stackrox.apps.ds-09-19-toothsome-kittens-s.ocp.infra.rox.systems:443 -p $(cat deploy/openshift/central-deploy/password) central debug download-diagnostics --since "2006-01-02T14:06:06.000Z"
INFO:	Downloading diagnostic bundle...
INFO:	Successfully wrote diagnostic zip file to "stackrox_diagnostic_2024_09_19_14_21_33.zip"
dashrews-mac:stackrox …
```

ROX-26240: sanitize error

---

ui/apps/platform/src/Containers/Audit/ListeningEndpoints/hooks/useDeploymentListeningEndpoints.tsx
ui/apps/platform/src/Containers/Dashboard/hooks/useDeploymentsAtRisk.ts
ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
ui/apps/platform/src/hooks/useFetchNamespaceDeployments.ts
ui/apps/platform/src/services/AlertsService.ts
ui/apps/platform/src/services/DeploymentsService.ts
ui/apps/platform/src/services/VulnerabilityExceptionService.ts
ui/apps/platform/src/utils/searchUtils.test.ts
ui/apps/platform/src/utils/searchUtils.ts

Refactors similar `getPaginationParams()` and `getListQueryParams()` [functions](https://github.com/stackrox/stackrox/pull/12746/files#diff-1bdd625dddb142ce420ab6fe119c5762c807a393a2e53fb2db68b7932000bcb9) to do the following:
- Have `getListQueryParams()` call `getPaginationParams()` internally instead of duplicating the offset calculation logic in both helpers
- Move the `0`/negative bounds checking into `getPaginationParams()`
- Remove the ability of `page` and `perPage` to be optional in `getListQueryParams()` (all callers of this function provide the correct arguments)
As a result of this refactor, the following was done:
- Remove the calculation of `page - 1` at every call site of `getListQueryParams()` -- this is now done internally in `getPaginationParams()` so we can consistently …

chore(ui): Refactor UI search utils for consistent pagination

---

pkg/protoconv/time.go
pkg/protoconv/time_test.go
pkg/scannerv4/mappers/mappers.go
pkg/scannerv4/mappers/mappers_test.go

While reading through this file, I noticed we never used the published times we retrieved from NVD. This change uses the NVD time when the main datasource does not have it. This is relevant for Alpine and Debian vulnerabilities, for example.
Scanned alpine:3.17.0 with current staging and saw this for `busybox`:
```
{
"name": "busybox",
"version": "1.35.0-r29",
"vulns": [
{
"cve": "CVE-2023-42364",
"cvss": 5.5,
"summary": "A use-after-free vulnerability in BusyBox v.1.36.1 allows attackers to cause a denial of service via a crafted awk pattern in the awk.c evaluate function.",
"link": "https://www.cve.org/CVERecord?id=CVE-2023-42364",
"fixedBy": "1.35.0-r31",
"scoreVersion": "V3",
"cvssV3": {
"vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
"exploitabilityScore": 1.8, …
```

ROX-26305: use NVD published time as a fallback

---

scanner/matcher/matcher.go
scanner/matcher/updater/vuln/updater.go
scanner/matcher/updater/vuln/updater_test.go
scanner/updater/import.go

When testing [VEX support](https://github.com/stackrox/stackrox/pull/12452), I noticed Scanner V4 DB's CPU was periodically active. Looking at the Scanner V4 Matcher logs, I realized that the GC is run upon every successful update cycle, even if that means there was nothing updated (success in this case just means there were no errors).
This PR now limits the GC to only run upon update cycles that not only don't error out, but also actually update something.
It's not perfect, as it's still possible a Matcher replica that does nothing towards updating the vulnerabilities runs the GC[1], but that's ok, as it's not nearly as common as this scenario.
[1] Imagine there are two Matcher replicas and there are new vulnerability updates. It is possible (highly unlikely, though) that only one of …

fix: do not run GC every update cycle

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigActionDropdown.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigActionsColumn.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts

1. Add an option in the actions dropdown to "Generate download".
2. Add an option in the table row actions to "Generate download".
3. Update the `runComplianceReport` function to work for both sending a report and generating a download.

ROX-25932: Add generate download button for compliance reporting

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx

I tried to disable the feature flag manually in the UI and looks like it slipped onto the master. This should revert that.

fix(ui): Fixing feature flag enablement

---

central/complianceoperator/v2/report/manager/complianceReportgenerator/report_gen_impl.go
central/notifiers/acscsemail/acscsemail.go
central/notifiers/acscsemail/acscsemail_test.go
central/notifiers/email/email.go
central/notifiers/email/email_test.go
central/reports/scheduler/schedule.go
central/reports/scheduler/v2/reportgenerator/report_gen_impl.go
pkg/notifiers/mocks/report_notifier.go
pkg/notifiers/report_notifier.go

While we were testing a sample Compliance Report, we discovered that the filename contained the hard-coded string "Vulnerability_Report", from the original use-case of reports for CVEs only.
This change fixes that by using the actual user-specified Report Name from the Report configuration in place of that hard-coded string.
1. Updated existing automated test
2. Deployed this PR build, and sent samples of both kinds of reports and then inspected their filenames
[Updated, 2024-09-20, after addressing PR comments]:
Vulnerability Report named "Van3"
Compliance report named "van-scooby-1"

ROX-26130: Make central notifier email library take report name param

---

central/clusterinit/backend/backend_test.go
central/clusterinit/store/store.go

Fix: Forbid multiple CRSs with the same name.
Attempted to create multiple CRSs with the same name using `roxctl central crs generate`.
+ new unit test.

fix: Disallow CRS name duplicates

---

migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/migration_impl.go

The upgrade of the grpc dependency to 1.66 also pulls an update of VTProto which changes some the encoding behaviour of empty oneOf types (to encode similarly to github.com/golang/protobuf/proto).
After investigation of the (reflection-based) encoding behaviour of the golang protobuf library, it turns out the way the vulnerability requests are built from CVE exceptions is flawed as it generated a non-nil oneOf wrapper type wrapping around a nil object.
This fixes the way this specific object is encoded in the test corner case of `cve-2023-138`.
Stripped of the generated encoding code, and tested how `proto.Marshal` encodes the system-built vulnerability request.
The existing CI should ensure that the refactor does not break the existing tests.

fix: proper use of proto OneOf wrapper in migration 202 to 203

---

ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerConfiguration.tsx
ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerConfigurationDescriptionList.tsx
ui/apps/platform/src/Containers/Violations/Details/Deployment/DeploymentOverview.tsx
ui/apps/platform/src/Containers/Violations/Details/Deployment/DeploymentTabWithReadAccessForDeployment.tsx
ui/apps/platform/src/Containers/Violations/Details/Deployment/DeploymentTabWithoutReadAccessForDeployment.tsx
ui/apps/platform/src/Containers/Violations/Details/Deployment/PortConfiguration.tsx
ui/apps/platform/src/Containers/Violations/Details/Deployment/SecurityContext.tsx

Bug:
When the deployment no longer exists, we don't display anything in the Deployment tab of the Violations detail page. This is misleading because the alert does keep track of some of the deployment details. 
Fix:
This is a partial fix. We can display the available details from the alert's deployment object. However, if the user requires more deployment information, that you would see if the deployment was still available, we would need to store that information in the alert object. 

ROX-26287: Missing deployment info in violations deployment tab

---

pkg/features/list.go
roxctl/central/central.go
roxctl/central/crs/common.go
roxctl/central/crs/crs.go
roxctl/central/crs/generate.go
roxctl/central/crs/list.go
roxctl/central/crs/revoke.go
tests/roxctl/bats-tests/cluster/crs-lifecycle.bats

This PR implements CRS management capabilities (generating, listing, revoking) in roxctl.
These features are currently hidden behind a feature flag -- **not yet exposed to users**.
**NOTE**: A follow-up commit with some sort of unit-testing (bats, probably) needs to be added.
Currently manual testing.
CI test added.

ROX-25909: CRS Support for roxctl

---

scripts/ci/lib.sh

Adding change that will respect global `mention_author`. This should fix the issue with tagging the author only if a new JIRA is created.
N/A
I tested only changed bits of code with set/unset global var.

chore(CI): Fix mention author only when new JIRA is created

---

ui/apps/platform/eslint-plugins/pluginGeneric.js
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ExternalBackupIntegrations/GcsIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ExternalBackupIntegrations/S3IntegrationForm.tsx
ui/apps/platform/src/Containers/Risk/RiskDetails.js

Prerequisite to change origin of docs site in only one line of code.
```diff
- return `https://docs.openshift.com/acs/${getVersionMajorMinor(completeVersion)}/${subPath}`;
+ return `https://docs.redhat.com/acs/${getVersionMajorMinor(completeVersion)}/${subPath}`;
```
Especially to help contributors from other teams be consistent.
Brad wrote `getVersionedDocs` helper function in #4494
* Include version number so doc page corresponds to product version.
* Encapsulate openshift versus redhat in origin of path.
Based on information from Kerry, the change is more than just the origin.
Dear reviewer, forgive these additional changes:
1. Replace `a` with `anchor` in rule keys which I forgot when we improved the prose in #12558
2. Replace `nodeAttribute` with `attribute` in 2 existing rules to …

fix(ui): Add no-anchor-href-docs-string generic lint rule

---

pkg/postgres/pgutils/utils.go
pkg/postgres/pgutils/utils_test.go
pkg/postgres/types.go
pkg/search/postgres/query/cidr_query.go
pkg/search/postgres/query/cidr_query_test.go
pkg/search/postgres/query/common.go
pkg/search/postgres/query/query_functions.go
tools/generate-helpers/pg-table-bindings/store.go.tpl

The ongoing External-IPs effort will leverage PostgreSQL capabilities around the 'cidr' type (efficient querying of columns `Containing` another CIDR).
This PR implements a small binding to deal with the null value, and a search query generator.

ROX-25898: CIDR type support in postgres framework

---

config-controller/api/v1alpha1/policy_types.go
config-controller/api/v1alpha1/policy_types_test.go
config-controller/config/crd/bases/config.stackrox.io_securitypolicies.yaml
config-controller/internal/controller/policy_controller.go
image/templates/helm/stackrox-central/templates/00-securitypolicies-crd.yaml

1. Added expiration timestamp of exclusion to the CRD
2. Removed policyVersion from CRD
3. Validations for default policy in CR which will not be supported in 4.6
Manual testing to see policy creation in UI, as well as policy reconcile error in logs because isDefault is true (unsupported in 4.6)
```
2024-09-23T23:03:17Z	INFO	Reconciling	{"controller": "securitypolicy", "controllerGroup": "config.stackrox.io", "controllerKind": "SecurityPolicy", "SecurityPolicy": {"name":"boo-default","namespace":"stackrox"}, "namespace": "stackrox", "name": "boo-default", "reconcileID": "189b73a1-77da-448e-a268-fa344cb6a9b4", "namespace": "stackrox", "name": "boo-default"}
2024-09-23T23:03:17Z	ERROR	Reconciler error	{"controller": "securitypolicy", "controllerGroup": "config.stackrox.io", …
```

ROX-26054: expiration timestamp, policy CR validation

---

ui/apps/platform/src/Containers/Policies/Table/PoliciesTablePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/components/NodeComponentsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts
ui/apps/platform/src/hooks/patternfly/useTableSort.ts
ui/apps/platform/src/hooks/useTableSort.ts
ui/apps/platform/src/hooks/useURLSort.test.js
ui/apps/platform/src/hooks/useURLSort.ts
ui/apps/platform/src/services/types.ts
ui/apps/platform/src/types/search.ts
ui/apps/platform/src/types/table.ts
ui/apps/platform/src/utils/searchUtils.ts

Reworks the `useURLSort()` hook to add the ability to sort by multiple fields in a single sort operation.
> Reviewing the `useURLSort.ts` file will likely be easier in "Split" mode due to the extent of the changes
This is nearly a rewrite of the hook, but was done in place instead of creating a separate hook for the following reasons:
1. Most importantly, customers may have saved links using _singular_ sort fields, and switching to an API that enforced an array of sort fields would break these links.
2. Since most tables will have a mix of columns that use single and multi sort, and the backend API requires `sortOption` and `sortOptions` fields respectively, we want to be able to easily distinguish when a sort operation is intended to span multiple options and when it should be sent as a …

feat(ui): Update useURLSort to support multi sort

---

ui/apps/platform/src/Containers/Policies/Detail/PolicyDetail.tsx
ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.tsx
ui/apps/platform/src/Containers/Policies/Wizard/PolicyWizard.tsx
ui/apps/platform/src/Containers/Policies/policies.utils.ts

Updates the Policy List page and Policy Detail page to better warn user when editing or deleting an **external** policy. The resync behavior will be noted in the confirmation modal when deleting a policy, as well as at the top of the page in an alert when editing a policy. As part of this change, the modals for deleting policies have been updated to reflect the recommendations in the [PatternFly docs](https://www.patternfly.org/components/modal/design-guidelines#confirmation-dialogs).
- The Disable/Enable functionality needs to be updated to correctly communicate when a policy is managed externally.
- Would be nice to add full e2e tests for policy create/edit/delete if time.
From the Policy List page, select one or more **Locally managed** policies and choose the bulk delete option: …

ROX-25619: External policy edit warnings

---

CHANGELOG.md
central/secret/internal/store/postgres/store.go
generated/api/v1/secret_service.swagger.json
generated/storage/secret.pb.go
pkg/features/list.go
proto/storage/secret.proto

This PR "rolls back" feature flag `ROX_SECRET_FILE_SEARCH` that was added in 4.4.
I'll let CI run.

ROX-25439: Remove ROX_SECRET_FILE_SEARCH feature flag

---

.github/workflows/scanner-versioned-definitions-update.yaml
scanner/updater/export.go

1. Stop running the single-bundle updater for PRs, as it's no longer used.
2. Fix the frequency of reaching out to the vulnerability providers. It was (probably) meant to be 15 requests/second, but it's actually 1 request/second. This change makes it ~16 requests/second.
This **is** the test
CI

chore(ci): scanner v4 vuln update improvements

---

ui/apps/platform/eslint-plugins/pluginGeneric.js
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step4/PolicyScopeForm.tsx
ui/apps/platform/src/services/CollectionsService.ts
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts
ui/apps/platform/src/services/DeploymentsService.ts
ui/apps/platform/src/services/VulnerabilitiesService.js

Follow up to contributions by David for consistent pagination as prerequisites for multi sort.
I added `!node.shorthand` to ignore properties without values as in destructuring.
Find in Files for the following:
* `pagination: PropTypes.shape(` has 1 result in 1 file
* `pagination: getPaginationParams(` has 30 results in 28 files
* `pagination: queryService.getPagination(` has 13 results in 13 files
* `pagination: {` has 9 results in 8 files but lint reports only 5 results in 4 files because the others are either in TypeScript type alias or `gql` template literals.
```
src/services/CollectionsService.ts
56:9   error  Require that pagination property has function call like getPaginationParams  generic/pagination-function-call
210:17  error  Require that pagination property has function call …
```

fix(ui): Add pagination-function-call generic lint rule

---

.github/workflows/scanner-offline-bundle-update.yaml
.github/workflows/scripts/scanner-offline-bundle-matrix.sh
.github/workflows/scripts/scanner-update-offline-bundle.sh

This PR modifies the offline bundle workflow to create offline bundles versioned by vulnerability schema versions, keeping backward compatibility with 4.4 and 4.5 releases.
Changes:
1. Create a matrix based on vulnerability schema found across all supported releases, as defined by `scanner/updater/version/RELEASE_VERSIONS` file.
2. For each execution in the matrix, create a corresponding `scanner-v4-defs-<schema version>.zip` bundle; 4.[45].x releases will be created as well, to ensure backward compatibility.
3. Upload each generated bundle to Github.
4. Download from GitHub and upload to GCP buckets, different locations based workflow triggers (dev or release).
Currently Scanner does not have integration tests infra or automated UTs for the workflow scripts.
1. Run the workflow from the …

ROX-25689: Versioned vulnerabilities in Offline bundles

---

ui/apps/platform/src/Components/ReportJob/MyActiveJobStatusTh.tsx
ui/apps/platform/src/Components/ReportJob/ReportJobsHelpAction.tsx
ui/apps/platform/src/Components/ReportJob/ReportJobsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useWatchLastSnapshotForReports.ts

This PR cleans up a few things in regards to the reporting feature:
1. Moving `ReportJobsHelpAction` and `ReportJobsTable` into a `Components/ReportJob` directory
2. Added a new `MyActiveJobStatusTh` component that we can reuse in both VM Reports and Compliance. I just copied over the exact rendered component you see in VM Reports
3. Cleaned up the code within the `useWatchLastSnapshotForReports` hook. This is pre-work for the eventual one we'll need to make for compliance reporting
I manually tested it out to see if it behaves similarly
https://github.com/user-attachments/assets/b326ed8a-52da-4959-9e2f-8b54e926f525

refactor(ui): Clean up reporting related components

---

scanner/decisions/0012-reindexing.md

Scanner V4 re-indexing design. See https://github.com/stackrox/stackrox/pull/12648 for the associated implementation
no
Documentation

doc(scanner): ADR: re-indexing

---

CHANGELOG.md
central/deployment/datastore/internal/store/postgres/store.go
generated/storage/deployment.pb.go
pkg/features/list.go
proto/storage/deployment.proto

This PR "rolls back" feature flag `ROX_DEPLOYMENT_SECRET_SEARCH` that was added in 4.4.
This branch is based on `mtodor/ROX-25439-remove-features-part2` - used in PR #12791
I'll let CI run.

ROX-25439: Remove ROX_DEPLOYMENT_SECRET_SEARCH feature flag

---

CHANGELOG.md
central/deployment/datastore/internal/store/postgres/store.go
generated/storage/deployment.pb.go
pkg/features/list.go
proto/storage/deployment.proto

This PR "rolls back" feature flag `ROX_DEPLOYMENT_ENVVAR_SEARCH` that was added in 4.4.
This branch is based on `mtodor/ROX-25439-remove-features-part3` - used in PR #12792 
I'll let CI run.

ROX-25439: Remove ROX_DEPLOYMENT_ENVVAR_SEARCH feature flag

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.tsx
ui/apps/platform/src/Components/ReportJob/types.ts
ui/apps/platform/src/Components/ReportJob/utils.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/MyJobsFilter.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportRunStatesFilter.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportStatusFilter.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
ui/apps/platform/src/utils/ensure.ts

This PR changes the behavior in the scan config details page to keep the state in the URL vs. in the component.

ROX-26320: Putting report job filter state into URL

---

ui/apps/platform/src/Components/PatternFly/SearchFilterChips.tsx
ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersToolbar.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPage.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTableSearchFilter.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadCveFilterToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/telemetry.ts

Prerequisite refactor to allow multi-sort-by-severity in https://github.com/stackrox/stackrox/pull/12764. This removes the usage of `useURLSearch()` from the `<SearchFilterChips>` component and relies on the parent component to pass the state and setter down.
Why?
Due to the new sort functionality needing to update sort parameters each time the filter changes, we need to hook into the `setSearchFilter()` function that sets the search in the URL. However, the widely used `SearchFilterChips` component calls its own version of `useURLSearch()` internally, regardless of other calls up the component tree, and uses this hook to clear the filters.
This results in incorrect sorting when the user removes a severity sort via the filter chips.
The fix is to pass the `setSearchFilter()` function down …

chore(ui): Move application of search filter out of filter chips

---

generated/internalapi/sensor/collector.pb.go
generated/internalapi/sensor/collector_vtproto.pb.go
proto/internalapi/sensor/collector.proto

Adds protobuf definitions for collector runtime configuration to `internalapi/sensor`. This is part of the [collector runtime configuration epic](https://issues.redhat.com/projects/ROX/issues/ROX-22981). The goal of which is to make collector features configurable at runtime. This PR by itself won't have any impact. There will be other PRs in collector to use the configuration and PRs impacting central and sensor to complete the work.
The changes just add internal protobuf definitions that are not used, so there is nothing to test.

ROX-26404: Internal protobuf definitions for collector runtime config

---

pkg/scanners/scannerv4/convert.go
pkg/scanners/scannerv4/convert_test.go
pkg/scanners/scannerv4/scannerv4.go

In Go, `nil` does not always equal `nil`. As much as I love calling methods with `nil` receivers, this is a case when `nil != nil` is a huge pain. This mimics https://github.com/stackrox/stackrox/blob/4.5.2/pkg/scanners/clairify/convert.go#L248 which only sets `HasLayerIndex` when we know the value we are setting `HasLayerIndex` to is not `nil`.
This also adds a Debug log, which may be helpful in the future to identify differences between the version of the image whose metadata we have and the version of the image which is scanned.
CI

fix(scannerv4): check if layer index is nil

---

.tekton/determine-image-digest-task.yaml
.tekton/operator-bundle-build.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/wait-for-image-task.yaml
operator/bundle_helpers/patch-csv.py
operator/konflux.bundle.Dockerfile

This PR changes the existing pipeline for the operator-bundle so that instead of injecting the operator-image tag into the CSV file we resolve this tag to an image digest and then inject that into the CSV.
**Note:** This is a simplified PR: there are no checks about the actual availability of the "replaced" version (think: "previous") of the operator.
I have not added any new tests.

ROX-26151: Pin operator image in operator-bundle (3rd)

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx

Fixes an issue where the total results count and pagination counts are derived from the `imageCVECountBySeverity` field, which breaks down CVEs by severity and fixability, but **does not** include counts for CVEs with `Unknown` severity.
This resulted in incorrect counts in the table on the Workload CVE image page, as well as inaccessible data when paginating to the last page.
Visit an image that contains CVEs of "Unknown" severity. This data is transient, but at the time of this PR `registry.redhat.io/redhat/redhat-operator-index:v4.14` is one such image.
Before:
View the image page and notice the CVE count above the table matches the sum of the counts in the summary cards. Also notice that there are 2 critical CVEs and 1 important, and that the data spans 9 table pages.
Sort by severity …

ROX-26013: Fix image cve count when unknown severities are present

---

ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedScanConfigs.test.js
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ConfigDetails.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx

This PR adds changes some text:
1. We will use `Send report` instead of `Send report now` in VM Reports to align with the wording used in Compliance.
2. We will changed `Last run` to `Last scanned` in the Scan Schedules table to be more specific and correct about the terminology.

refactor(ui): Wording changes for compliance and reporting

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/vulnerabilityUtils.test.ts
ui/apps/platform/src/Containers/Vulnerabilities/utils/vulnerabilityUtils.ts

Fixes the "First discovered" data on the affected images page by using `image->imageComponents->imageVulnerabilities->discoveredAtImage` instead of `image->scanTime`.
Note the time displayed in the header label versus the time displayed in the individual table rows.
Before:
After:

ROX-26308: Fix First discovered time for affected images

---

central/postgres/pruning.go
central/pruning/pruning.go
pkg/env/postgres_default_timeout.go
pkg/env/process_pruning.go

Currently the only thing that could be tuned for the pruning process is whether it's enabled. The way how pruner works right now might be causing high memory utilization, due to queries doing large amount of reads. This could be adjusted via frequency and the orphan cut-off line. Introduce those two configurations to help with troubleshooting.
Manually verified that it's possible to get expected pruning configuration:
* Deploy the modified image
* Configure pruning interval, timeout and orphan window so that pruning will happen frequently, the timeout will be low to prevent any other pruning activity (e.g. alerts cleanup) to stuck for a long time, and the orphan window long enough to essentially skip all the processes.
```
queryid             | 3727384489359643919
query               | …
```

ROX-25828: Make Pruner more configurable

---

CHANGELOG.md
generated/storage/alert.pb.go
proto/storage/alert.proto

To investigate alerts easier and being able to call them in the UI the alert notification now adds the alert ID. See the `id` field in the screeshot attached.
Trigger an alert and inspect the log.

ROX-26422: Include alert ID in API responses and alert notifications

---

ui/apps/platform/cypress/integration/listeningEndpoints/listeningEndpointsTable.test.js

Fixes a test failure in UI e2e tests due to an assumption made on the postgres path that has changed after an [upstream+downstream convergence on postgres](https://github.com/stackrox/stackrox/pull/12498).
See the new expected path in this test failure video: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/branch-ci-stackrox-stackrox-master-merge-gke-ui-e2e-tests/1840755940098314240/artifacts/merge-gke-ui-e2e-tests/stackrox-stackrox-e2e-test/artifacts/videos/listeningEndpoints/listeningEndpointsTable.test.js.mp4
The proof is in the pudding (CI).

chore(ui): Change postgres path in listening endpt test

---

ui/apps/platform/cypress.config.js

As discussed in team meeting, see effect of `requestTimeout` on occasional test failures for generic requests
History: increased from default 5 seconds to 10 seconds about 2 years ago on 2022-10-04 in #3307
https://docs.cypress.io/guides/references/configuration#Timeouts
CI

chore(ui): Increase cypress requestTimeout to 20 seconds

---

.tekton/operator-bundle-pipeline.yaml

This is a fix for the injection of the related Images. Before this change the image references looked like this:
```
image: '"quay.io/rhacs-eng/roxctl:sha256:2fed1592ce09139868bda931c6e33d5312924d1a4e25e7d96fd86e8f2f0085aa"'
```
notice the double quotation marks and the double colon between the repo name and the hash.
With this change the references look like this:
```
image: "quay.io/rhacs-eng/roxctl@sha256:2fed1592ce09139868bda931c6e33d5312924d1a4e25e7d96fd86e8f2f0085aa"
```
Extracted the CSV from the image and verified that it looks good now.

fix:  Fix image references in operator bundle for the related images

---

config-controller/api/v1alpha1/policy_types.go
config-controller/api/v1alpha1/policy_types_test.go
config-controller/api/v1alpha1/test.json
config-controller/config/crd/bases/config.stackrox.io_securitypolicies.yaml
image/templates/helm/stackrox-central/templates/00-securitypolicies-crd.yaml

Added the new policy name field to the CR spec, updated tests.  Added more kubebuilder validation checks for existing CR fields.
@kylape @c-du I think this PR will need to merge before Cong's or atleast right after each other to ensure demoable master.
Unit tests

ROX-26434: Adding policyName field to the policy CR spec

---

pkg/scanners/scannerv4/convert_test.go

Makes this test compatible with 4.5. It is **not** compatible with 4.4, though
This IS the test

fix(ci): make scanner v4 test backwards compatible

---

compliance/collection/compliance/compliance.go

In some test cases in the CI Sensor was unavailable for over 10 minutes. Compliance tries to reconnect to Sensor for maximally 3 minutes. Compliance starts retrying immediately after the connection is down. There are many cases where compliance misses Sensor by few seconds.
See comments in: https://issues.redhat.com/browse/ROX-26311
If https://github.com/stackrox/stackrox/pull/12815 is merged, then this PR must include a revert of the part that disables checking for compliance restarts.
I did nothing so far - this is pretty difficult to test the way it was caught by the CI.
The error condition difficult to reproduce the way it was seen in CI, but I did the following:
- Confirmed that if Sensor is down for over 3 mins, then Compliance container fails with error as from the ticket.
- …

ROX-26311: Compliance connecting to Sensor shall retry longer

---

central/search/service/service_impl_test.go
pkg/search/postgres/query/bool_query.go
pkg/search/postgres/query/common.go
pkg/search/postgres/query/enum_query.go
pkg/search/postgres/query/numeric_query.go
pkg/search/postgres/query/time_query.go

Wildcard strings already work for string, map, and string array type fields. They did not work for bool, time and numeric fields. This PR adds the ability to do wildcard searches for bool, time and numeric fields. The null values for numeric and bool types might be stored as 0 and false in the db respectively, but there is no way for the framework to know whether that 0 value is a real 0 or a default value. So we just consider 0s as non null values for now.
```
select deployments.Id::text as Deployment_ID, deployments.OrchestratorComponent from deployments where deployments.OrchestratorComponent is not null order by deployments.RiskScore desc LIMIT 10
```
```
select deployments.Id::text as Deployment_ID, deployments.ServiceAccountPermissionLevel from deployments where …
```

ROX-26301: Allow 'is null' and 'is not null' queries for bool, enum and numeric fields

---

central/notifiers/email/email.go
central/notifiers/email/email_test.go

This changes adds the required Date header to all emails send by the ACS system.
(from the Jira ticket description)
> In ACS the emails that are sent from the "Vulnerability Management (2.0)" > Vulnerability Reporting function are missing the Date header in the email.
> 
>This header is mandatory in emails as specified by the RFC 5322
> 
> https://datatracker.ietf.org/doc/html/rfc5322#section-3.6
> 
> Mails without a date header are still processed but gather a higher than normal spam score due to RFC non-compliance. Additionally the mails are not properly ordered in the email client (eg. Thunderbird) because of the missing date. This can create confusion on the time a vulnerability report has actually been generated.
* Added additional checks for this new header to this function's unit …

ROX-26041: Add required Date header to email messages

---

ui/apps/platform/src/Components/FilteredWorkflowSelector/FilteredWorkflowSelector.tsx
ui/apps/platform/src/Components/FilteredWorkflowSelector/types.ts
ui/apps/platform/src/Components/FilteredWorkflowSelector/useFilteredWorkflowState.ts
ui/apps/platform/src/Components/FilteredWorkflowSelector/useFilteredWorkflowURLState.ts
ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx

This PR adds a new selector to the Policy Violations to choose a filtered workflow (`Application view`, `Platform view`, `Full view`). The state for the filtered workflow will be kept in the URL as `filteredWorkflowState`. The value will be used to filter the table in Policy Violations. That functionality will come in the following PR once the backend adds the capability. We will disable the `Application view` and `Platform view` for now.

ROX-25786: Create FilteredWorkflowSelector component

---

.github/workflows/scanner-offline-bundle-update.yaml
.github/workflows/scripts/scanner-offline-bundle-generate.sh

This changes the offline definition bundles prefix to ensure 4.5 remains compatible with the latest offline bundle. By using a new prefix, 4.5 will accept its specific bundle (`scanner-defs-4.5.zip`) and ignore the newer definitions. This prevents 4.5 to reject the bundle, since today 4.5 rejects multiple definitions in a single zip. The goal is for the latest bundle to contain all definitions, even though size will increase, but it allows backward compatibility, and customers can use `roxctl scanner download-db` if needed.
The follow changes to adopt the new prefix will be performed at https://github.com/stackrox/scanner/pull/1643 
There are some short/small refactoring and style-related changed as well.
I've added `pr-update-scanner-vulns`, and checked upload step:
```
uploading files …
```

refactor(scanner): Use separate v4 prefix for new bundles

---

.openshift-ci/pre_tests.py
qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy
qa-tests-backend/src/test/groovy/RuntimeViolationLifecycleTest.groovy
scripts/ci/jobs/gke_version_compatibility_tests.py
tests/e2e/lib.sh

Backport of #11946 to fix compatibility tests on which would otherwise use eBPF, but should use CORE_BPF (to ensure compatibility with all kernels)
Uses NO_COLLECTION for 3.74 tests, and CORE_BPF for everything else.
~- [ ] CHANGELOG is updated **OR** update is not needed~
~- [ ] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed~
~- [ ] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag~
~- [ ] added unit tests~
Validated on previous PR, and CI should be enough to verify that it works in this case.

fix(tests): backport GKE compatibility fixes to 4.5

---

pkg/images/integration/set_impl.go
pkg/registries/mocks/set.go
pkg/registries/set.go
pkg/registries/set_impl.go
pkg/registries/set_impl_test.go
sensor/common/registry/metrics/metrics.go
sensor/common/registry/registry_store.go
sensor/common/registry/registry_store_test.go
sensor/common/registry/tlscheck_cache.go
sensor/common/registry/tlscheck_cache_test.go

This PR adds metrics for various aspects of Sensors registry store to assist troubleshooting and provide insight into the current state of the store.
PR stacked on top of:
- https://github.com/stackrox/stackrox/pull/12360
Deployed ACS to OCP 4.16 infra cluster, setup port-forward to sensor metrics port (9090), and observed metrics with pull secrets by name feature on / off:
With Pull Secrets by Name DISABLED:
```sh
$ curl 127.0.0.1:9090/metrics | grep registry_store
rox_sensor_registry_store_central_integrations_count 8
rox_sensor_registry_store_cluster_local_hosts_count 3
rox_sensor_registry_store_global_secret_entries_count 4
rox_sensor_registry_store_pull_secret_entries_count 216
rox_sensor_registry_store_pull_secret_entries_size 344968
rox_sensor_registry_store_tls_check_count 4 …
```

ROX-25722: Add metrics to sensor registry store

---

central/notifiers/all/all_test.go

Add notifier import test to notify engineers their notifier must be added to the `all.go` file.

chore: Add notifier import test

---

.github/CODEOWNERS

This PR marks the roxctl code that integrates with NP-Guard and the respective tests as owned by IBM-Research team.
The goal is to make clear who are the goto people in case some functionality changes in the NP-Guard dependencies and the tests start failing.
Unfortunately "outside collaborators cannot be added to a team, team membership is restricted to members of the organization", so I needed to list all three involved users from the IBM Research team.
I also renamed `draco` to `install` team as otherwise Github claimed that the codeowners file contains errors.
None

chore(ownership): Make IBM Research team codeowners of NP-Guard

---

qa-tests-backend/src/test/groovy/Services.groovy

This PR is adding logging to the flaky test.
It is not visible from the provided logs and dumps what violations we get during a test. The image and signatures verified for it are the same for successful and failed tests.
Will let CI do that

ROX-25897: Add logging to display found violations in test

---

go.mod
pkg/protoassert/assert.go

The current version of `protoassert` has a few issues:
* When two protos are not equal, they are given a second chance to be equal if their JSONs match. This can cause a bug when `nil != nil` (see https://github.com/stackrox/stackrox/pull/12820 where the current implementation would not have caught this bug)
* ElementsMatch does not consider a scenario like the following: [a, a, b] [a, b, b]. These would be seen as equal, when they should not be
This change aims to mimic https://github.com/stretchr/testify more closely.
This IS the test

chore: better protoassert accuracy

---

sensor/kubernetes/listener/listener_impl.go
sensor/kubernetes/listener/resource_event_handler.go

Sensor does not wait for the informers to be stopped before attempting to create them again, it simply triggers a stop signal that should (eventually) stop them. This could make [this function](https://github.com/stackrox/stackrox/blob/1652234a402221333b96505cda5cbb192aed230a/sensor/kubernetes/listener/resource_event_handler.go#L387) to fail if the informers are not fully stopped before starting them again. This PR aims to add a shutdown logic and waits for the informers to be fully stopped. …

feat(listener): Shutdown shared informers synchronously

---

pkg/scannerv4/mappers/mappers.go
pkg/scannerv4/mappers/mappers_test.go
scanner/decisions/0013-manual-cvss-source.md
scanner/updater/manual/README.md
scanner/updater/manual/manual.go

This makes changes to the CVSS score mapping in Scanner. This originally started when dealing with merge conflicts in https://github.com/stackrox/stackrox/pull/12452, but as I tried to resolve them, the changes became too much for that PR. So, I created this one.
This PR:
* refactors the CVSS score processing by only attempting to compute the one related to the updater as well as NVD
* Accounts for manual vulnerabilities getting CVSS scores from NVD (or other sources)
* Simply uses the Severity we get from ClairCore. There is no real reason to change it (actually, the client currently never uses it, so we really don't need it at all)
CI

chore(scanner): refactor CVSS score mapping

---

ui/apps/platform/src/Components/FilteredWorkflowSelector/FilteredWorkflowSelector.tsx
ui/apps/platform/src/Components/FilteredWorkflowSelector/useFilteredWorkflowURLState.ts
ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx
ui/apps/platform/src/services/AlertsService.ts

This PR takes the `filteredWorkflowState` in the URL and determines what search filters to pass to the API using the query parameter. The logic goes like this:
- Application view - `Platform Component: false` and `Entity Type: DEPLOYMENT`
- Platform view - `Platform Component: true` and `Entity Type: DEPLOYMENT`
- Full view - No query

ROX-25787: Filter Policy Violations using Filtered Workflow Selector

---

tools/retest/main.go

The auto-retest feature is very useful for retriggering rarely occurring flakes. Unfortunately, it requires a PR to have all checks passed or it would not start. This limits the usability of it, so I propose to add a list of checks that are allowed to fail for the retest to start.
I tried to query GH API for the "required" checks, but that is not trivial, thus I propose a manually curated list of checks.
I added the code coverage check as the first example.
PR inspired by trying to test this flake on CI: https://github.com/stackrox/stackrox/pull/11027
I ran it locally with my token against #11027 and observed the output.

feat(auto-retest): Add list of exceptions for PR checks

---

Makefile

Looks like latest versions of podman do not tell anything about itself in the output of `docker --version`, but does that in `docker version`. Search for both.
Tested the build manually.

chore(build): Search podman in more docker output

---

central/deployment/utils/utils.go
central/deployment/utils/utils_test.go
central/networkbaseline/service/service_impl.go
central/networkbaseline/service/service_impl_test.go
central/networkgraph/service/masker.go
central/networkgraph/service/service_impl_test.go

Network graph masking alters the entities in network flows when these (entities) are not allowed access to by the requester roles (more precisely their access scope).
This becomes problematic when flows should be compared to the network baseline, as the entity IDs are masked as well.
This PR aims at relaxing the masking rules in order to allow flow comparison to the network baseline (deterministically computed masked ID so rules can be applied on baseline comparison as well).
The existing test coverage should be enough.
Deploy
- create a restricted scope (e.g. stackrox namespace only), an admin role with this restricted scope, and an API token for that role
- check the network graph for the stackrox namespace on the deployed cluster
- capture the deployment name and IDs in the stackrox …

ROX-23835, ROX-26239: Mask graph deployment IDs for baseline compare 

---

CHANGELOG.md
central/graphql/resolvers/loaders/image_cves.go
central/views/imagecve/view_impl.go
pkg/env/postgres_default_timeout.go

We found in a customer case some issues with the VM2.0 queries timing out.  After making some adjustments in Postgres we could get them to run, but we don't have enough resources to make those settings permanent.  What we can do is extend the timeout for these queries.  The default of 1 minute is too short.  So this PR seeks to make a configurable timeout that is narrow in focus to VM and defaults to 3 minutes.
Manual testing.  Artificially set the VM query timeout to 1 ms.  Went to VM page and verified an error was received.
```
{
"errors": [
{
"message": "context deadline exceeded",
"path": [
"imageCVEs"
]
}
],
"data": null
}
```
Set the timeout back to a normal value and verified that the query completed.

ROX-26372:  VM query timeout

---

Makefile

This recreates https://github.com/stackrox/stackrox/pull/11476 with insider build/push/test permissions.
No auto testing changes.
`make image` succeeds locally. CI should be happy.

fix: missing whitespace in Makefile around LOCAL_VOLUME_ARGS

---

tests/performance/scale/config/metrics-acs-base.yml
tests/performance/scale/config/metrics-acs-central.yml
tests/performance/scale/config/metrics-acs-collector.yml
tests/performance/scale/config/metrics-acs-sensor.yml
tests/performance/scale/config/metrics-acs.yml
tests/performance/scale/config/metrics-full.yml
tests/performance/scale/config/metrics-ocp-base.yml
tests/performance/scale/tests/kube-burner/cluster-density/run-workload.sh
tools/allowed-large-files

This PR is refactoring `kube-burner` metrics file.
Metrics are split into several parts:
1. base OCP metrics file. Taken from: https://github.com/kube-burner/kube-burner-ocp/blob/fd4c2d7c249bb0b066ff05139bd87f8b9daa4bd5/cmd/config/metrics-aggregated.yml
2. base ACS - OCP capture `openshift-.*` namespaces, but we need `stackrox` namespace for our tests.
3. each component has a dedicated metrics file. They are collected from `/metrics` endpoints of each component
- All sections are combined into a single file that can be used to collect all metrics with `kube-burner`.
- All ACS relevant metrics are combined in `metrics-acs.yml` - this is an option where we can combine OCP and ACS metrics queries where needed.
Since metrics are pulled outside of the test template, we need to copy it before …

chore(perf): Refactor metrics and update the list of collected metrics

---

generated/storage/alert.pb.go
pkg/postgres/schema/alerts.go
proto/storage/alert.proto

As the size of the `alert` table grows, pruning becomes slower and slower.  We've improved that over time by batching, it, but there are more gains to be had.  This PR adds an index onto the time field in the alert.  This provides an extra nugget of information for Postgres to use as it determines what rows we are looking for.
Migration on 12K alerts took milliseconds to add the index.
Added the index on a local database of 1M records.  That took 2 seconds.
Verified queries will now use the index if Postgres finds it prudent to use it.
```
explain analyze select alerts.Id::text as Alert_ID 
from alerts 
where ((alerts.Time <= now() at time zone 'utc' - INTERVAL '4 DAYS'));
QUERY PLAN                                         
------------------------------------------------------------------ …
```

ROX-24990:  alert time index to help pruning

---

CHANGELOG.md
pkg/registrymirror/store.go
pkg/registrymirror/store_test.go
sensor/common/scan/scan.go
sensor/common/scan/scan_test.go

Addresses an edge case when a podspec's image is referenced by tag, and the registry contents for that tag change after the image has been deployed. To ensure the correct metadata and layers are pulled, we add the image ID from the runtime (if provided) to the 'pull sources' used in delegated scanning - this way the correct metadata and layers are pulled.
Prior to this change the current/latest tag contents were used, which may not have matched the previously deployed image.
Setup: Enabled delegated scanning, created an image, pushed it to quay, created a deployment, then updated the image, pushed it to quay, and created a second deployment. 
<details>
<summary>Creating Deployments</summary>
Creating Deployment dave-1:
```
$ cat Dockerfile 
FROM …
```

ROX-26428: Ensure image ID is not lost when evaluating mirrors

---

generated/storage/process_indicator.pb.go
pkg/postgres/schema/process_indicators.go
proto/storage/process_indicator.proto

Process indicator pruning worker struggles if the table grows too large. One of the reasons is that limiting query results only to the old records is not supported by any index:
signal_time < now() AT time zone 'utc' - INTERVAL '$1 MINUTES'
Add the index process_indicators_signal_time_idx, which together with the configuration option for orphan window allow us to specify how much data to prune for process indicators.
CI is enough.
* Generated large `process_indicators` table (35 Gb)
* Applied the new image to start the migration (parallel index creation took about 3min on the out-of-the box cluster)
* Verified the index is created
* Tested the pruning query, the index is used when needed:
```
-- a query with larger orphan window, 3 hours and less data, bitmap scan with the new index is in …
```

ROX-25828: Add index on process_indicators.signal_time

---

operator/bundle_helpers/patch-csv.py

Goes on top of https://github.com/stackrox/stackrox/pull/12918, see https://github.com/stackrox/stackrox/pull/12918#discussion_r1793830904
Example:
```
$ operator/bundle_helpers/patch-csv.py --help
usage: patch-csv.py [-h] --use-version version --first-version version --operator-image image
[--related-images-mode {downstream,omit,konflux}] [--add-supported-arch ADD_SUPPORTED_ARCH]
[--echo-replaced-version-only] [--unreleased UNRELEASED]
Patch StackRox Operator ClusterServiceVersion file
options:
-h, --help            show this help message and exit
--use-version version
Which SemVer version of the operator to set in the patched CSV, e.g. 3.62.0 (default: None)
--first-version version
The first version of the operator that was published (default: None)
--operator-image image
Which operator …
```

Inline related images help

---

central/complianceoperator/v2/scanconfigurations/store/postgres/store.go
central/deployment/datastore/internal/store/postgres/store.go
central/vulnmgmt/vulnerabilityrequest/datastore/internal/store/postgres/store.go
pkg/postgres/walker/schema.go
pkg/postgres/walker/walker.go
pkg/search/walker.go
tools/generate-helpers/pg-table-bindings/store.go.tpl

Removes feature flag functionality from the template and code. This PR requires parts 1-4 to be merged first.
This reverts functionality added with #8636 for using feature flags in proto files.
This branch is based on `mtodor/ROX-25439-remove-features-part4` - used in PR #12793
I did run `make go-generated-srcs` - for `GENERATE_PATH=central/deployment/datastore/internal/store/postgres/gen.go`

ROX-25439: Change template and remove flag options

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigActionDropdown.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/hooks/useWatchLastSnapshotForComplianceReports.ts
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts

This PR disables the table row actions and the actions dropdown on the details page when a scan is running or a report job is preparing or waiting for a run. 
I've also adjusted the API endpoints and how we pass data in the request in preparation for backend integration.

ROX-26264: Backend integration

---

.github/workflows/scanner-offline-bundle-update.yaml

Fix for CI errors `ERROR: missing "gcloud" executable`
Ex: https://github.com/stackrox/stackrox/actions/runs/11262989448
Not 100% sure on root cause on how this was working previously - the current `ubuntu-latest` (`24.04`) runner does NOT include the `Google Cloud CLI`, previous versions (`22.04`) do however.
N/A no automated tests for this job
Created this PR and added label to trigger CI, workflow `Scanner release offline vulnerability bundle update` ran successfully: https://github.com/stackrox/stackrox/actions/runs/11263430502?pr=12968

fix(ci): Scanner job broken due to `gcloud` CLI missing

---

README.md
scripts/quick-helm-install.sh

Added `--set central.persistence.none=true` to the central helm install commands in the readme as well as the `quick-helm-install.sh` scripts.
Just ran the quick-helm-install.sh script locally and it works, no more pvc error

ROX-26555: Add central persistence helm flag to readme

---

operator/Makefile
operator/bundle_helpers/patch-csv.py
operator/konflux.bundle.Dockerfile

See subject. This PR has been rebased and modified so that it only deals with the problem that `spec.relatedImages` must only be populating if (and only if) we are in "Konflux mode". This has been implemented in the form of a new command-line flag for the patching script, which is used by the konflux Dockerfile.
[ROX-26151](https://issues.redhat.com/browse/ROX-26151)
Nothing done here.
Inspected the CSV.
Downstream `spec.relatedImages`:
```
- name: rhacs-rhel8-operator-9905fb7988a9203b3aaa3295e19149fd2312872c11e3aca2686cb3c4dcee7054-annotation
image: registry.redhat.io/advanced-cluster-security/rhacs-rhel8-operator@sha256:9905fb7988a9203b3aaa3295e19149fd2312872c11e3aca2686cb3c4dcee7054
- name: manager
image: registry.redhat.io/advanced-cluster-security/rhacs-rhel8-operator@sha256:9905fb798 …
```

fix: (konflux) Add spec.relatedImages iff executing in Konflux mode

---

ui/apps/platform/cypress/integration/policies/policyWizardStep3-dnd.test.js
ui/apps/platform/cypress/integration/policies/policyWizardStep3.test.js
ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.test.ts
ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx
ui/apps/platform/src/Containers/Policies/policies.utils.ts

Frontend counterpart to #12896
Feature flag for policy criteria is only to allow frontend to precede backend.
At end of sprint, either:
* Remove `featureFlagDependency` property, because policy criteria is released.
* Comment out policy criteria, if policy criteria cannot be released.
1. Copy, paste, and then edit **CVSS** policy criteria.
* Paste after, because order of criteria is order in `policyCriteriaDescriptors` array.
* Because the `name` property is the correspondence between frontend and backend, I confirmed the field name with Surabhi in advance.
https://github.com/stackrox/stackrox/blob/20498cae2fffe60f74e6561c458688411e2b8acd/pkg/booleanpolicy/fieldnames/list.go
Prerequisite before `npm run deploy` in ui folder
```sh
export ROX_NVD_CVSS_UI=true
```
I tested in modal …

ROX-24859: Add NVD CVSS policy criteria

---

central/alert/mappings/options.go
pkg/search/mocks/options_map.go
pkg/search/options_map.go

Alerts are stored in the db with type `Alert` but the v1/alerts/ APIs respond with `ListAlert` type objects. `ListAlert` has its own search fields that are exposed in the API. However, since db stores objects of type `Alert` , `ListAlert`'s search fields are updated to contain the search paths (`table_name.field_name`) as  `Alert`'s fields to ensure that search works. This implementation also ends up removing fields from the `OptionsMap` of the `AlertsSchema`. Because of this, it is not possible to add any new internal fields to `Alert` and use them for internal searches. This PR fixes this by cloning the `Alert` OptionsMap before reconciling with `ListAlert` OptionsMap. This way the search fields supported by schema will not change and can be used for internal searches.
Will test …

fix(be): Fix alert search not working for new fields

---

.github/actions/job-preamble/action.yaml
.github/workflows/build.yaml

Fixes errors like: https://github.com/stackrox/stackrox/actions/runs/11275363888/job/31358119043
Investigation showed that `gcloud` was removed from the ubuntu-latest image:
Compare:
- new runner: https://github.com/actions/runner-images/blob/ubuntu24/20241006.1/images/ubuntu/Ubuntu2404-Readme.md
- older runner: https://github.com/actions/runner-images/blob/ubuntu22/20240922.1/images/ubuntu/Ubuntu2204-Readme.md (has Google Cloud CLI )
Forcing previously failing image vuln check job to run by removing gating for PRs.
Proof build: https://github.com/stackrox/stackrox/actions/runs/11276418382/job/31361542063?pr=12982.

fix: install gcloud CLI in job-preamble

---

.github/workflows/build.yaml

This reverts commit 5425b0e56415b905dd26bae0c1fff2338b991508 (https://github.com/stackrox/stackrox/pull/12977). 
The postgres repodata is now rectified.
Passing build is sufficient.

fix: Revert "fix: temporarily disable arm64 main build (#12977)"

---

image/rhel/Dockerfile
image/roxctl/konflux.Dockerfile
operator/Dockerfile
operator/konflux.Dockerfile
scanner/image/scanner/konflux.Dockerfile

Fixing the warning:
```
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 16)
```
See [PR run](https://github.com/stackrox/stackrox/actions/runs/11250698536/job/31281104596?pr=12405) for example.

chore: upper case AS in Dockerfiles

---

central/sensor/service/connection/connection_impl.go
central/sensor/service/connection/upgradecontroller/trigger.go
ui/apps/platform/src/Containers/Clusters/cluster.helpers.test.js
ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx
ui/apps/platform/src/constants/productBranding.ts

This PR updates some texts regarding the upgradability of the secured clusters. 
It addresses the following issues:
1. We should not indicate that a version is managed by Helm if it is managed by an operator
2. We should not speak of **upgrade** when in fact we mean **downgrade**
3. We should not use the word **required** when we propose a **downgrade**
in the following manner:
1. Instead we indicate that the version is not managed by ACS but by external tools - for example Helm or an operator
2. We use **upgrade** only if sensor is behind Central. In opposite case, we use word **downgrade**
3. If we discover that sensor can be downgraded, we do not use **required** but **possible** instead. The goal is to not stress the necessity.
What this PR is not addressing:
1. Instead of proposing a …

ROX-26411: Improve the upgrader nudge texts

---

ui/apps/platform/src/Components/CompoundSearchFilter/attributes/policy.ts
ui/apps/platform/src/Components/CompoundSearchFilter/components/ConditionDate.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/SearchFilterAutocomplete.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTableSearchFilter.tsx

This PR fixes a few issues from the bug bash:
1. Filtering out empty string options in the autocomplete component.
2. Removing the Entity Type filter.
3. Adding labels and annotations for namespaces and deployments and labels for clusters.
4. Giving a better error text when using an invalid date format.

ROX-26532: Fixing policy violations search filter bugs

---

central/reports/common/report_formatter.go
central/reports/scheduler/schedule.go
central/reports/scheduler/v2/reportgenerator/consts.go
central/reports/scheduler/v2/reportgenerator/report_gen_impl.go
pkg/csv/writer.go

This PR adds nvd cvss field to vuln report
Tested these changes by manually dwnloading report when nvdcvss filter is set to truwe and when filter is set to false
[RHACS_Vulnerability_Report_Test_09_October_2024_false.csv](https://github.com/user-attachments/files/17318839/RHACS_Vulnerability_Report_Test_09_October_2024_false.csv)
[RHACS_Vulnerability_Report_Test_08_October_2024 2_true.csv](https://github.com/user-attachments/files/17318840/RHACS_Vulnerability_Report_Test_08_October_2024.2_true.csv)
change me!

ROX-25822: Query nvd cvss for vuln report

---

ui/apps/platform/cypress/integration/collections/collectionsCrudWorkflow.test.js
ui/apps/platform/cypress/integration/collections/deploymentMatching.test.js
ui/apps/platform/src/Containers/Collections/CollectionForm.tsx
ui/apps/platform/src/Containers/Collections/RuleSelector/ByLabelSelector.tsx
ui/apps/platform/src/Containers/Collections/RuleSelector/ByNameSelector.tsx
ui/apps/platform/src/Containers/Collections/RuleSelector/RuleSelector.cy.jsx
ui/apps/platform/src/Containers/Collections/RuleSelector/RuleSelector.tsx
ui/apps/platform/src/Containers/Collections/converter.test.ts
ui/apps/platform/src/Containers/Collections/converter.ts
ui/apps/platform/src/Containers/Collections/hooks/useCollectionFormSubmission.ts
ui/apps/platform/src/Containers/Collections/types.ts

As specified, should behave the same as before but `All` should be replaced as `None specified` to be more explicit about what the selection includes.
Creating a new collection and viewing existing collections should result in no errors or awkward wordage.

ROX-24563: Changing All to NoneSpecified in Collections

---

scripts/ci/logcheck/check-restart-logs_test.bats
scripts/ci/logcheck/restart-ok-patterns.json
scripts/ci/logcheck/test_fixtures/rox-5861-exception-compliance-previous.log

This PR removes ignore for compliance container restarts.
After merging of: #12859 - we don't see Pod Restart failures. Because of that PR: #12815 is not relevant anymore.
Still, we should remove existing invalid ignores from our code.
Run tests locally. This time, with set `ARTIFACT_DIR` env variable.

chore(CI): Remove ignore pod restarts for compliance container

---

qa-tests-backend/src/test/groovy/CertRotationTest.groovy

Part of: [ROX-26411](https://issues.redhat.com/browse/ROX-26411)
This has not been caught in #12833.
CI

ROX-26596: Fix text assertion - cluster is helm managed

---

migrator/clone/clone_test.go
migrator/clone/mock_central.go
migrator/clone/postgres/db_clone_manager_impl.go
migrator/clone/postgres/db_clone_manager_impl_external_test.go
migrator/clone/postgres/db_clone_manager_impl_test.go

When the minimum supported sequence number was implemented the check was in correct.  The check should have been to compare the minimum sequence number with the sequence number the software supports.  Previously it was comparing minimum to minimum which would never allow us to move the minimum sequence number to reduce rollback support.
Updated the unit tests.  and lots of manual tests.
Tested the following scenarios.
- 4.5.2 -> this PR -> 4.5.2 -- ensured upgrade and rollback were both successful.
- 4.5.2 -> this PR -> test PR #12980 -> this PR -- ensured upgrade and rollback were both successful.
- 4.5.2 -> this PR -> test PR #12981 -> this PR -- ensured upgrades succeeded, but unable to rollback from test PR back to this PR or earlier.
```
Migrator: 2024/10/10 15:10:15.536264 …
```

ROX-26526: fix migrator min sequence comparison

---

pkg/scanners/clairify/clairify.go

Scanner v2 logs the image name for which it is retrieving vulnerabilities (gRPC method): https://github.com/stackrox/scanner/blob/2.34.2/api/v1/imagescan/service.go#L205
We are currently not sending the image name over, though we are sending it when fetching the components: https://github.com/stackrox/stackrox/blob/4.5.3/sensor/common/scannerclient/grpc_client.go#L183
This change adds that same line to the vulnerability request
none
trivial

chore: add image name to vuln request to scanner v2

---

.tekton/basic-component-pipeline.yaml
.tekton/main-pipeline.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml

Adding required task rpms-signature-scan to the Konflux pipelines.
Konflux CI is passing. Looked at the `rpms-signature-scan` Task output to confirm that there are no unsigned RPMs in our images.
`main` build is broken because of the source build upload issue, I cannot confirm with 100% certainty that it works, but I would be surprised if there was an unsigned RPM in just this image.

ROX-26528: add rpms-signature-scan task to Konflux pipelines

---

.github/workflows/scanner-versioned-definitions-update.yaml

I was looking at the logs, and, unfortunately, `gsutil` doesn't log what it's copying very well... So, I add logs here. I also did two other super tiny changes while I'm here
no
CI

chore(ci): improve scanner vuln workflow logging

---

central/complianceoperator/v2/report/manager/manager_impl.go
central/complianceoperator/v2/report/manager/manager_test.go
central/complianceoperator/v2/report/manager/singleton.go
central/complianceoperator/v2/report/manager/watcher/scanconfigwatcher.go
central/complianceoperator/v2/report/manager/watcher/scanconfigwatcher_test.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher_test.go
central/complianceoperator/v2/report/manager/watcher/utils.go

Adds the logic to identify when a ScanConfiguration has started and completed. This is necessary for the accurate reporting of compliance 2.0
- Depends on #12890

ROX-26448: add scheduler watcher

---

ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/ReportParametersDetails.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx
ui/apps/platform/src/hooks/useManagedColumns.ts

Follow up from pre bug bash meeting.
Add `ROX_SCANNER_V4` wherever conditional rendering has `ROX_NVD_CVSS_UI` feature flag.
After release, we will keep the former even though we delete the latter.
1. Rename `isNvdCvssEnabled` as `isNvdCvssColumnEnabled` in Workflow CVEs.
* Add omitted `isNvdCvssColumnEnabled` for `colSpan` in AffectedImagesTable.tsx file.
2. Rename `isNvdCvssEnabled` as `isIncludeNvdCvssEnabled` in Vulnerability Reporting.
* Replace `FormLabelGroup` with `FormGroup` element following example in DefaultFilterModal.tsx file. Same appearance, but allows more checkboxes in the future.
3. Edit `featureFlagDependency` property in policyCriteriaDescriptor.ts file.
4. Add `filterManagedColumns` function in useManagedColumns.ts file.
1. What if policy has omitted field? This is …

ROX-26635: Conditionally render NVD CVSS only if ROX_SCANNER_V4

---

.tekton/main-pipeline.yaml

See https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1728643044463389
No change to automated testing.
If it passes CI, the fix helped.

build: Try build `main` image's source container harder

---

compliance/index/v4/node.go
compliance/index/v4/node_test.go
compliance/index/v4/testdata/certs
image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl
pkg/env/node_scan_v4.go
sensor/common/sensor/sensor.go

The ClairCore components that are running inside Compliance for NodeIndex require a mapping JSON file to be available.
This file needs to be served through Central, going through Sensor, to ensure proper adherence to our architecture and offline functionality. The endpoint already existed for delegated scanning and needed slight modifications.
I want to highlight the following changes:
- Add collector to Sensor authorizer
- Update default mapping url setting
- Deploy this image to an OS4 cluster
- Observe Node Index on compliance to be able to successfully generate a report (previously not possible)

ROX-26626: Sensor serving mappings

---

ui/apps/platform/cypress/helpers/tableHelpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/deploymentSingle.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveSingle.test.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js

chore(ui): Add cypress tests for Workload CVE column mgmt

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ComplianceProgressBar.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/StatusCountIcon.tsx

Add the ability to filter by status on the compliance coverages page tables.
Without filters:
With 'Pass' filter applied:
With 'Pass' and 'Manual' filter applied:
Compliance header tooltip:

ROX-25813: Add compliance coverages page status filtering

---

pkg/env/compliance_operator.go

Modifies the default timeout and number of retries of the ScanSettings generated by ACS

feat(compliance): Update scan timeout settings

---

ui/apps/platform/cypress/helpers/tableHelpers.ts
ui/apps/platform/src/Components/ColumnManagementButton.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/TableEntityToolbar.tsx

A couple of small changes to better handle layout of the VM toolbar on screens smaller than the 2xl or 3xl width. A small enhancement until we are able to do a more thorough revisit of the toolbar layout and markup throughout VM.
1. Removed an extraneous "separator" element
2. Changed the "Manage columns" button to "⚙️ Columns"
3. Group the right side elements into a `<ToolbarGroup>` in order to allow wrapping this is less disjoint
Before:
After:

chore(ui): workload CVE toolbar layout tweaks

---

ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx

When the `ROX_PLATFORM_COMPONENTS` flag is `false`, do not send any `Platform Components` filter in the query.
Flag off, observe network calls:

fix(ui): Omit the Violations Platform Component filter when ff off

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/SearchFilterAutocomplete.tsx
ui/apps/platform/src/Components/FilteredWorkflowViewSelector/FilteredWorkflowViewSelector.tsx
ui/apps/platform/src/Components/FilteredWorkflowViewSelector/types.ts
ui/apps/platform/src/Components/FilteredWorkflowViewSelector/useFilteredWorkflowViewURLState.ts
ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTableSearchFilter.tsx

This PR fixes some issues related to the `Platform Components` feature:
1. We will be use the term "Applications view" instead of "Application view". 
Reference from Alan: Nitpick, but should we call it "Applications view" to denote multiple workloads in the cluster? "Application view" feels like it's focused on a single application. "Platform view" is fine, because even though there are many underlying workloads, we are still talking about a single platform. Can we do this in 4.6?
2. The subtext for "Platform view" was changed to "Display findings for platform components in Openshift" because we are not dealing with layered services right now.
3. When changing views, the filters and pagination will be cleared. 
4. When changing between "Active" and "Resolved", the view and filters will …

fix(ui): Platform components bug bash issues

---

config-controller/internal/controller/policy_controller.go
config-controller/main.go
config-controller/pkg/client/client.go

1.  Use the standard rox logging library in pkg for logging instead of the controller framework logging.
2.  Modify logs to debug and reword info logs for readability and consistency.
3.  Set the manager cache option for resync period to 4h (default is 10h) to allow the config controller to force resync CRs every 4h.
Manual for logging, forced resync untested.

ROX-26109, ROX-25497: Standard logging, resync period changes

---

qa-tests-backend/src/test/groovy/IntegrationsSplunkViolationsTest.groovy

Disable failing Splunk Integration test
change me!

ROX-26297: Disable Splunk integration test

---

ui/apps/platform/src/Containers/Compliance/Entity/Header.js

no automated tests for PDF contents
Before:
I saved a PDF of the Compliance 1.0 results for a cluster, and the header read **CLUSTER "2BFA1A54-66D0-4E4D-BB34-42F2CD91460D" Report**
After:
I saved a PDF of the Compliance 1.0 results for the same cluster, and the header read **CLUSTER "remote" Report**

ROX-26655: Replace entity ID with name in Compliance 1.0 PDF headers

---

.tekton/main-build.yaml

Let the Konflux team manage these resources as they seem to be on track of doing that
https://github.com/konflux-ci/build-definitions/pull/1247
No changes to automated testing.
Only CI.

build: Drop clamav-scan resource requests

---

ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyGroupCard.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx

1. One side of coin: it is risky to hide **NVD CVSS** field if `ROX_SCANNER_V4` feature flag is not enabled, because it is possible that filed could come from outside UI:
* imported policy JSON file
* declarative custom resource for policy
2. Other side of coin: users need to know that NVD CVSS scores require Scanner V4.
* The policy field does nothing without scores.
* Van commented that information might motivate some customers to adopt Scanner V4.
Optional information for a policy field is worthwhile to support generically.
Mansur approved `Alert` element via Slack.
1. Edit policyCriteriaDescriptors.tsx file.
* Add optional `infoText` property.
* Delete `ROX_SCANNER_V4` from `featureFlagDependencies` property.
2. Edit PolicyGroupCard.tsx file.
* Add `pf-v5-u-font-size-sm` as …

ROX-26667: Render information about NVD CVSS field in policy wizard

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/SearchFilterAutocomplete.tsx

When sending an autocomplete query, we need to exclude any filters that are already applied for the current search term we are querying. 
i.e. If we want a list of CVEs matching a query, and we have a current filter of `CVE:CVE-ABC-123`, we need to instead pass just `CVE:` otherwise the results will include at most that single CVE.
Build up the filter list with some Namespaces:
See that an applied namespace does not restrict the return results:
Switch to image name and see that the applied **Namespace** filter affects the results:
Apply an Image name filter and ensure that follow up searches return a list of images:
Repeat with additional fields:

ROX-26644: Do not pass current filter during autocomplete

---

pkg/scannerv4/mappers/mappers.go

This warning has proven to be very noisy, especially when an NVD score is missing (which is common these days...). Let's make this Debug level to reduce regular noise
no
I didn't

chore(scanner): change loglevel to reduce noise

---

ui/apps/platform/src/Containers/Violations/Details/ViolationDetailsPage.tsx

Good eyes, Surabhi.
Inconsistency on Policy tab of Violations for field that has relational operator, for example **Fixable Severity at Least Important** policy that has **Severity** field. See **Manual testing** below.
One big step forward to fix chronic TypeScript errors and one small step backward:
https://github.com/stackrox/stackrox/pull/12351/files?diff=split&w=1#diff-5c53620827639310dcbb0614ba692ae5369b2680042b73d4edde5d2deec81773R137
Visual Studio Code for 3 components render `PolicyDetailContent` element:
1. src/Containers/Policies/Detail/PolicyDetail.tsx file has `policy: ClientPolicy` tooltip
2. src/Containers/Policies/Wizard/Step6/ReviewPolicyForm.tsx file has `values: ClientPolicy` tooltip
3. src/Containers/Violations/Details/ViolationDetailsPage.tsx file has `policy: Policy` …

fix(ui): Make Policy tab of Violations consistent with Policies

---

ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx

Fixes the expand/collapse functionality of the network graph flows section expanders.
Visit network graph and open a deployment side panel. Click the flows sections to expand/collapse.

ROX-26565: Fix netgraph flows section expanders

---

.tekton/operator-bundle-pipeline.yaml

Context: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1729514992332749?thread_ts=1729502472.979589&cid=C04PZ7H0VA8
`operator-bundle` Konflux pipeline appears in the PR checks: https://github.com/stackrox/stackrox/pull/13068/checks?check_run_id=31826851633

fix: build-container instead of build-image-index in operator-bundle

---

compliance/collection/compliance/compliance.go
compliance/collection/compliance/node_scanner.go
compliance/collection/metrics/metrics.go
pkg/nodes/enricher/enricher_impl.go
pkg/nodes/enricher/metrics.go

For the introduction of Node Indexing (Node Scanning on Scanner v4), we also want to update the existing metrics.
I have added a label indicating the scanner version to existing metrics where possible, everywhere else I have introduced a new metric for Node Indexing following the pattern of the old metric.
The latter was done in most places where we would need a service release of Scanner v2 to account for the new labels, which is a lot of work for a deprecated component.
The only exception is the metric `calltToNodeInventoryDuration`, which isn't applicable to Node Indexing, as we do not call an external service component anymore, so I did not add/migrate that.
On a running OpenShift 4 cluster with ACS / Scanner v4 deployed, updated the Compliance and Central images and verified that the …

ROX-26474: Expand metrics for Node Indexing

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobStatus.tsx
ui/apps/platform/src/hooks/useRestQuery.ts

This PR adds a few more bug fixes for Compliance Reporting:
- Using the right type of Alert 
- Allowing the ability to pass an `options` object to `useRestQuery` which tweaks the behavior. We had an issue where an Error state would flicker during polling because of how our table state logic was organized. Because every repeated request would clear the error message, we would get an `Idle` state between polls. This resulted in the Error state disappearing and reappearing.
- We capitalize the error message shown in the tooltips
https://github.com/user-attachments/assets/bea171ad-ecf7-4c44-8707-0be7c4ea8524

fix(ui): Compliance Reporting fixes

---

sensor/tests/helper/collector.go

The network flows are processed every 30s. This means we need between 30s and a minute (exactly the timeout in the assertion) to process the two flows that collector sends in the runtime test.
The test sends a message for each flow so if we are lucky they could be processed in one tick (30s) or two ticks (1 minute) if we are unlucky. If the second scenario occurs the 1 minute timeout might not be enough to process both network flows.
This PR fixes this issue by having the collector in the test send one message with both flows instead of two messages.

ROX-25990: Send both flows in a single message

---

CHANGELOG.md
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ClairIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ClairifyIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/GoogleIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationTiles/IntegrationTile.tsx
ui/apps/platform/src/Containers/Integrations/utils/integrationsList.ts

StackRox team is developing Scanner V4, which is the replacement for StackRox Scanner. It is time to deprecate the old one.
GCR has been deprecated by Google for some time, and it will be shut down in 2025 (see https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation).
no

ROX-26669, ROX-26670: Deprecate StackRox Scanner and GCR

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts
ui/apps/platform/src/Containers/Vulnerabilities/components/CvePageHeader.tsx

This change re-introduces the date a CVE was published to the folllowing new Vulnerability Management views:
1. Workload CVEs table
2. Workload CVE single detail view
3. Image single detail view, CVEs in image table
4. Deployment single detail view, CVEs in deployment table
tbd
tbd
Workload CVEs with "Published" column heading with tooltip
Workload CVEs Published date with tooltip showing absolute date, instead of the inane relative date
CVE detail view with Published in header:
Image detail CVEs table with "Published" column heading with tooltip
Image detail CVEs table with Published date with tooltip showing absolute date, instead of the inane relative date
Deployment detail CVEs table with "Published" column heading

ROX-24588: Reintroduce Published date in VM 2.0

---

tests/policy_as_code_test.go

1. Added new policy create by creating CR as a test.
2. Added notifier support to existing create, save as, update, delete test.
Green CI.

chore(be): e2e test for policy CR create

---

.tekton/main-pipeline.yaml

See https://github.com/stackrox/scanner/pull/1679 for description.
In `stackrox` repo, only `main` wasn't set up right.
No automated testing changes.
Main build source will fail due to KFLUXBUGS-1508 but I'll check that the build gets to that failure.
The already mentioned https://github.com/stackrox/scanner/pull/1679 and other container pipelines are the evidence that the source image can be linked to the index image without problems.

ROX-24468: Link source container to the index image

---

ui/apps/platform/src/utils/queryStringUtils.test.ts
ui/apps/platform/src/utils/queryStringUtils.ts

Increase `qs.parse` arrayLimit to fix search filter handling
This change addresses an issue where search filters with more than 20 elements were being converted to objects due to the default `arrayLimit` in `qs.parse`. Since `parseFilter` inside `useURLSearch` does not handle objects, this was causing filters to be ignored during the sanitization step
Considerations:
- A future enhancement could involve modifying `parseFilter` to handle objects in addition to arrays. This would eliminate the need to set an arbitrary `arrayLimit` and allow search filters with more than 200 elements to be processed correctly without conversion to an object causing issues.
```js
// parseFilter inside useURLSearch
Object.entries(rawFilter).forEach(([searchKey, searchVal]) => {
if (typeof searchVal === …
```

ROX-25706: Increase url search filter array limit

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigWizardForm.tsx
ui/apps/platform/src/hooks/useAnalytics.ts

This update introduces tracking for the following events:
- **Wizard Step Changes:** Tracks when users move between steps in the policy wizard. This should help identify areas where users may encounter difficulties or abandon the process.
- **Wizard "Save" Button Clicks:** Tracks the frequency of successful schedule creations versus failed attempts – include why a failure occurred.
An example use case for this telemetry is tracking unique visits at each step of the wizard. This can help identify where users are most likely to abort the wizard.
Segment overview:
Raw data:

ROX-24991: Compliance scheduling analytics

---

ui/apps/platform/src/Containers/Clusters/Components/Scanner/ScannerStatus.tsx

Currently, the tooltip only displays the health status of the active scanner, which may cause confusion when users see pods for both `scanner-slim` and `scanner-v4` but only receive health data for one.
As a short-term change, we've added a message to the tooltip indicating that the health status reflects only the active scanner.
Before:
After:

ROX-23364: Indicate only active scanner health info displayed

---

tests/common.go
tests/delegated_scanning_test.go
tests/delegated_scanning_test_utils.go

Adds retries to various actions that have caused the delegated scanning e2e tests to fail. Specifically:
- Retry obtaining a reference to the Sensor pod if multiple Sensor pods are found
- When registry mirrors are set in OCP, OCP will drain every pod from every node, this takes time.  To speed up Sensor reconnecting to Central the tests restart Sensor and then wait for the Central/Sensor connection to be HEALTHY.  In one of the observed failures the connection was ready but there were two Sensor pods running (presumable one in a 'terminating' state).  The retries should give the pod enough time to shutdown before proceeding with the tests.
- Similarly, after the Central/Sensor connection was HEALTHY (which is determined via an API request to Central) - a subsequent request to the Central …

ROX-26663: Add additional retries to Delegated Scanning Tests

---

central/role/datastore/defaults.go
tests/policy_as_code_test.go

**Note**: Intended to be merged after https://github.com/stackrox/stackrox/pull/13091 because it includes the commits from that PR.
Since config-controller's role did not have the ability to view notifiers, it was unable to create policies that referred to notifiers.
This commit contains a couple of changes:
* Grants read-only access to config-controller for "integrations", which includes notifiers
* Adds a notifier to the "create" integration test to validate this behavior.
* Fixes the TestSaveAsCRUpdateDelete test to add the notifier to the policy when creating in Central.  Before it was setting it on the policy struct returned from Central, which was later only used to pull an ID (i.e. the whole policy struct was never used again).

ROX-26674: Grant config-controller ability to view notifiers

---

.tekton/central-db-build.yaml
.tekton/main-build.yaml
.tekton/operator-build.yaml
.tekton/operator-bundle-build.yaml
.tekton/roxctl-build.yaml
.tekton/scanner-v4-build.yaml
.tekton/scanner-v4-db-build.yaml

When looking for information about `CHAINS-GIT_URL` in the scope of ROX-24468, I ran into a few mentions that `source_url` is a better choice than `repo_url`. I couldn't parse exactly where or when the difference matters but it seems about handling forked builds and Konflux integration tests. Without thinking much about it, I suggest we just switch provided new templates render with `source_url` (and we flipped back to `repo_url` for consistency with our oldest pipelines).
- https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1702354906424429
- https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1717768756743769?thread_ts=1717750916.369879&cid=C04PZ7H0VA8
No updates to automated testing.
If Konflux CI gets sufficiently far, it's good enough.

build: Switch `git-url` from `repo_url` to `source_url`

---

ui/apps/platform/cypress/constants/SystemHealth.js
ui/apps/platform/cypress/integration/systemHealth/integrations.test.js
ui/apps/platform/src/Components/ReportJob/ReportJobsTable.tsx
ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsTable.tsx
ui/apps/platform/src/Containers/SystemHealth/Components/IntegrationsHealth.tsx
ui/apps/platform/src/Containers/SystemHealth/DeclarativeConfigurationHealth/DeclarativeConfigurationHealthCard.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/AffectedComponents/AffectedComponentsModal.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ApprovedDeferrals/ApprovedDeferralsTable.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ApprovedFalsePositives/ApprovedFalsePositivesTable.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/DeferredCVEs/DeferredCVEsTable.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/FalsePositiveCVEs/FalsePositiveCVEsTable.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/PendingApprovals/PendingApprovalsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestOverview.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx

Fix errors reported by first draft of lint rules for managed columns.
1. **CVE severity** and **CVE status**
* Edit DeploymentVulnerabilitiesTable.tsx file.
And then, fix some reported by first draft of lint rule for consistent text of `Th` and `dataLabel` prop of `Td` element.
1. **Error message**
* Edit IntegrationsHealth.tsx file.
Temporarily edit IntegrationHealthWidgetVisual.tsx file to provide response from staging.
* Edit DeclarativeConfigurationHealthCard.tsx file for consistency.
* Edit SystemHealth.js file to replace `data-testid` with `data-label` attribute.
* Edit integrations.test.js file.
2. **Affected components**
Too bad, so sad, Risk Acceptance is orphan code.
* Edit DeferredCVEsTable.tsx file.
* Edit FalsePositiveCVEsTable.tsx file.
3. **Dockerfile line where component …

fix(ui): Make dataLabel consistent in DeploymentVulnerabilitiesTable

---

tests/delegated_scanning_test.go

Make sure the delegated scanning config is reset at end of test suite so that other tests are not impacted.
CI

ROX-26720: Reset dele scan config at end of suite

---

tests/e2e/run-scanner-v4.bats

Disable test for ROX-26581: run-scanner-v4.bats: Fresh installation of HEAD Helm charts with Scanner v4 enabled in multi-namespace mode.
Apparently, the operator refuses to install central into non-standard namespace and provides the following reason:
```
Status:
Central:
Admin Password:
Admin Password Secret Reference:  central-admin-pass
Info:                             The admin password is configured to match the "password" entry in the central-admin-pass secret.
Conditions:
Last Transition Time:  2024-10-23T09:06:57Z
Status:                False
Type:                  Deployed
Last Transition Time:  2024-10-23T09:06:57Z
Status:                True
Type:                  Initialized
Last Transition Time:  2024-10-23T09:11:48Z
Message:               Unable to continue with install: …
```

ROX-26581: Disable failing scanner v4 tests

---

central/networkgraph/aggregator/aggregator_impl.go
central/networkgraph/aggregator/aggregator_test.go
pkg/features/list.go
pkg/networkgraph/utils.go
pkg/networkgraph/utils_test.go

With the new external IPs feature, this feature flag enables/disables displaying raw IP information in the network graph.
If the flag is not enabled, external discovered entities are aggregated into the Internet entity bucket.
So far validated locally, enabling / disabling the feature flag and observing a change to the display in the network graph.

ROX-25616: aggregate discovered entities using feature flag

---

CHANGELOG.md
central/reports/common/report_formatter.go
central/reports/common/report_formatter_test.go

We do not currently take care of the characters in the report name, while we use underscores as the separator for the prefix and the suffix, like in:
```
RHACS_Vulnerability_Report_Long file name with spaces and..._17_September_2024.csv
```
The PR suggests:
* Do not add the ellipsis for the long names, but just cut;
* Keep only a limited set of characters, replace others with '_';
* Use UTC time for the suffix.
Unit tests. Manual e2e.

ROX-26748: keep only 'safe' characters in the CSV report file name

---

central/imageintegration/store/defaults.go
central/sensor/service/pipeline/nodeindex/pipeline.go
central/sensor/service/pipeline/nodeindex/pipeline_test.go
central/sensor/service/pipeline/nodeinventory/pipeline.go
compliance/collection/compliance/compliance.go
compliance/index/v4/node.go
image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl
sensor/common/sensor/sensor.go
ui/apps/platform/src/Containers/Integrations/utils/integrationsList.ts

A collection of tasks that were discovered in demos or explorative testing
- Remove Scanner v4 from delayed integration (to prevent race conditions)
- Update categories of Scanner v4 integration in UI to reflect changed roles
- Ensure Central NodeIndex pipeline only runs if Scanner v4 and NodeIndex are enabled
- Enable NodeIndex pipeline by default on central
- Set up ClairCore logger to remove default debug logging on compliance
1. Deploy changes to an OpenShift 4 cluster with primary SSD storage enabled (required for Scanner v4/Matcher) with `export ROX_SCANNER_V4=true MONITORING_SUPPORT=true`  for the deploy script.
2. Enable Indexing on Central 
- `ks set env deployment/central ROX_NODE_INDEX_ENABLED=true`
3. (Optional) Lower initial and rescan interval of the index
- `ks set env …

ROX-26662: Node Indexing Tasks

---

image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl

As described [in the issue](https://issues.redhat.com/browse/ROX-26764) the secured-cluster-services Helm chart might cause >4k lines long error dumps instead of a user-friendly error message in case the init bundles has not been provided. This is due to a wrong invocation of the `srox.fail` templating function.
Verified manually using
```
$ roxctl helm output secured-cluster-services --remove --debug; helm install --dry-run -n stackrox --set clusterName=foo --set centralEndpoint=https://localhost:443 stackrox-secured-cluster-services ./stackrox-secured-cluster-services-chart
```
None.

ROX-26764: Fix bogus failing in Helm chart

---

central/clusterinit/service/service_impl.go
deploy/common/k8sbased.sh
tests/e2e/lib.sh

Central currently exposes CRS issuing functionality via gRPC. This is not currently used anywhere. But it is probably a good idea to tie this service call to the feature flag so that it is guaranteed for released images that we won't end up with any CRS's in the wild (as of now).
With this change CRS issuing would fail on central side. Triggered here using roxctl:
```
$ roxctl -e "$CENTRAL_ENDPOINT" central crs generate foo -o=crs.yaml
[...]
ERROR:	missing CRS support in Central: rpc error: code = Unimplemented desc = Support for generating Cluster Registration Secrets (CRS) is not enabled
```
Conducted a simple manual test using roxctl.
Nothing.
Manually.

fix: Only allow CRS generation if feature flag is enabled.

---

scripts/ci/lib.sh

This PR should fix issue where nightly build is taken for merge commits.
Tested on following commits:
- `e58fa182d0799191eacd1b97e982da7b4ef41cf5` - not nightly
- `c6d1447df8c794e5acaeb8d716becc452e11b60f` - tagged as nightly
- **old code first**
```
❯ git checkout e58fa182d0799191eacd1b97e982da7b4ef41cf5
❯ BUILD_TAG="$(git tag --sort=creatordate --contains | tail -1)" || echo "Warning: Cannot get tag"
❯ echo $BUILD_TAG
4.6.x-nightly-20241028
❯ git checkout c6d1447df8c794e5acaeb8d716becc452e11b60f
❯ BUILD_TAG="$(git tag --sort=creatordate --contains | tail -1)" || echo "Warning: Cannot get tag"
❯ echo $BUILD_TAG
4.6.x-nightly-20241028
```
- **new code**
```
❯ git checkout e58fa182d0799191eacd1b97e982da7b4ef41cf5
❯ BUILD_TAG="$(git describe --exact-match --tags HEAD)" || echo "Warning: …
```

chore(CI): Fix issue with mix of nightly and merge commit builds

---

compliance/collection/compliance/compliance.go
compliance/collection/compliance/node_scanner.go
compliance/collection/metrics/metrics.go

This PR introduces updated metrics to better address the new reality of two scanner versions being available for generating Node Package information.
No metric is removed, as we need to keep the old metrics around for as long as Scanner v2 is officially supported to maintain backwards compatibility.
The idea is to introduce new versions of the metrics with correct names, deprecating the old ones where possible. For this case, metrics are duplicated and given the correct name and help text.
Some metrics are directly observed in the old Scanner v2 code (stackrox/scanner), . In these cases, the metric is created seperately and exists once for Scanner v2 and once for Scanner v4.
Overview: 
- numberofRHELPackages: **Duplication added**
- numberOfContentSets: **Duplication added**
- …

ROX-26699: Introduce unified transmissions metric

---

central/sensor/service/pipeline/nodeindex/three_pipelines_test.go
central/sensor/service/pipeline/nodeinventory/pipeline.go
central/sensor/service/pipeline/nodeinventory/two_pipelines_test.go

This PR adds a unit test to ensure that the 3 pipelines interacting together (Kubernetes Node Informer, Node Scanning v2, Node Indexing v4) are producing the expected results and behavior.
Added unit test

ROX-26744: Add pipeline unit test

---

ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/DeferredCVEs/DeferredCVEActionsColumn.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/DeferredCVEs/DeferredCVEsTable.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/FalsePositiveCVEs/FalsePositiveCVEActionsColumns.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/FalsePositiveCVEs/FalsePositiveCVEsTable.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/imageVulnerabilities.graphql.ts

This is a 4.4 specific fix.
Resolves a customer issue in the old VM images page where the `vulnerabilityRequest` object in a network response is `null` for CVEs that have _approved false positive vulnerability requests_. This `null` is not handled on the front end and results in a runtime error, crashing the page.
Note that this is a partial fix and does not resolve the underlying issue of `vulnerabilityRequest` being `null`, which logically should not occur. The fix here is to prevent the entirety of the page crashing when this behavior is encountered.
The fix displays `'N/A'` in the table fields, which is the existing behavior in the Deferred CVEs table. Additionally the menu from the row is removed, as the functionality from the menu option is invalid if there is no …

ROX-24326: Prevent UI crashes when vuln req is null in response

---

central/image/service/service_impl.go

Fixes an issue with roxctl (or API) scans that are delegated to a secured cluster.  When the metadata pull + indexing succeeds but matching fails the output appears to be a 'successful' scan - however `.scan` will be missing from the scan result (will include metadata only).
Now an error will be returned.
Also adds logging the delegated scanning request ID to the error so when examining administrative events or central logs we can differentiate between ad-hoc scans and non.
No additional tests added.
Deployed ACS 4.5.3 and while Scanner V4 was still loading vulns delegated a scan.  
This scan 'SHOULD' return an error instead of a 'partial' response:
```
$ rctl image scan -f --image=nginx --cluster=remote | jq ".name,.metadata.dataSource,.notes,.scan"
{
"registry": "docker.io",
"remote": …
```

ROX-26605: return error on matching fail for delegated ad-hoc scans

---

.tekton/central-db-build.yaml
.tekton/main-build.yaml
.tekton/main-pipeline.yaml
.tekton/operator-build.yaml
.tekton/operator-bundle-build.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/roxctl-build.yaml
.tekton/scanner-v4-build.yaml
.tekton/scanner-v4-db-build.yaml

Configure timeouts for wait-for-image tasks based on the timeouts for the respective pipeline runs.
This is just a CI (Konflux change).
Nothing added.
Inspecting CI.

ROX-26618: Tweak timeouts for wait-for-image

---

ui/apps/platform/cypress/integration/integrations/machineAccessConfigs.test.ts

Found last week by accident that feature flag has been turned on since 2024-02-14 in #9932
No conditional code in src folder.
1. Ask Merlin team to delete any leftover conditional code from backend
* integrations/machineAccessConfigs.test.ts

chore(ui): Delete test skip for ROX_AUTH_MACHINE_TO_MACHINE

---

central/sensor/service/service_impl.go
pkg/centralsensor/caps_list.go

https://github.com/stackrox/stackrox/pull/12740 added a Central API that re-issues all the Secured Cluster certificates.
It should have included also this piece, to advertise this functionality via a capability.
Tested by deploying with `./deploy/k8s/deploy-local.sh` that the capability gets propagated to sensor.

ROX-25949: Add capability for Secured Cluster cert reissue

---

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/ImageResourceTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/DeploymentResourceTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx

Prerequisite for lint rule to require `dataLabel` prop.
1. Investigate what to do about checkbox and kebab.
2. VulnReportsTable.tsx file: `MyLastJobStatusTh` element encapsulates text that lint rule needs to verify that `dataLabel` prop is consistent.
2. `npm run lint` in ui/apps/platform
3. `npm run build` in ui/apps/platform and then compute branch - master for the following
main.js 0 = 4619653 - 4619653
total 426 = 11801827 - 11801401
files 0 = 178 - 178
1. Visit /main/vulnerabilities/reports and then create a report.
VulnReportsPage.tsx file.
* Before changes without `dataLabel` props, see absence of responsive labels at 760px width.
* After changes with `dataLabel` props, see …

fix(ui): Add dataLabel prop to Td element in Vulnerabilities

---

ui/apps/platform/src/Containers/Policies/Wizard/Step5/NotifiersForm.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx

Remove minor inconsistency as prerequisite for lint rule to require `dataLabel` prop.
1. Add `no-Td-data-label` lint rule in new pluginPatternFly.js file.
2. Add `Td-dataLabel` lint rule in new pluginPatternFly.js file.
2. `npm run build` in ui/apps/platform
Prerequisite: create a notifier integration.
1. Visit /main/policy-management/policies/?action=create and then advance to **Actions** step.
* Before and after changes, see `data-label` attributes and labels at 760px screen width.
2. Visit /main/vulnerabilities/workload-cves/images/id and expand a vulnerability
* Before and after changes, see `data-label` attributes and labels at 760px screen width.

chore(ui): Replace data-label with dataLabel in Td elements

---

ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsTable.tsx
ui/apps/platform/src/Containers/Policies/Modal/EnableDisableNotificationModal.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step3/TableModal.tsx

Prerequisite for lint rule to require `dataLabel` prop.
1. FlowsTable.tsx file: Investigate pro and con of `columnNames` versus literal strings.
2. ViolationsTablePanel.tsx file: Investigate pro and con of `violationTableColumnDescriptors` versus literal strings.
3. AccessScopesTable.tsx and PermissionSetsTable.tsx files: Investigate `dataLabel` prop for radio buttons.
4. RiskAcceptance folder: Investigate possibility to delete unreachable files.
2. `npm run lint` in ui/apps/platform
3. `npm run build` in ui/apps/platform and then compute branch - master for the following
main.js 0 = 4619653 - 4619653
total 90 = 11801491 - 11801401
files 0 = 178 - 178
1. Visit …

fix(ui): Add dataLabel prop to Td element elsewhere

---

ui/yarn.lock

Upgrades `body-parser` from 1.20.0 => 1.20.3 in 4.5
Verify CI run

fix(ui): Upgrade body-parser to 1.20.3

---

ui/apps/platform/src/Components/PatternFly/FormMessage.tsx
ui/apps/platform/src/Containers/AccessControl/AccessControlRouteNotFound.tsx
ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopeForm.tsx
ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopeFormWrapper.tsx
ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopes.tsx
ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopesList.tsx
ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSetForm.tsx
ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSets.tsx
ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSetsList.tsx
ui/apps/platform/src/Containers/AccessControl/Roles/RoleForm.tsx
ui/apps/platform/src/Containers/AccessControl/Roles/Roles.tsx
ui/apps/platform/src/Containers/AccessControl/Roles/RolesList.tsx
ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/EmailIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/MachineAccessIntegrationForm.tsx
ui/apps/platform/src/Containers/NetworkGraph/common/NetworkPolicies.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaseline.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
ui/apps/platform/src/Containers/NetworkGraph/simulation/NotifyYAMLModal.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestApprovalButtonModal.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCancelButtonModal.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestDenialButtonModal.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/ReportFormErrorAlert.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/DeliveryDestinationsForm.tsx

Because of change to 4.6 code freeze, replace enum first, and then add `no-Variant` lint rule after.
1. In general, more consistency lowers the barrier to contributors from other teams.
2. In specific, `AlertVariant` enum is an extra import.
The source of truth for prop values of PatternFly elements is string **enumeration**, not string **enum**.
For example,
https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Alert/Alert.tsx#L80
```tsx
variant?: 'success' | 'danger' | 'warning' | 'info' | 'custom';
```
**not**
https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Alert/Alert.tsx#L12-L18
```tsx
export enum AlertVariant {
success = 'success',
danger = 'danger',
warning = 'warning',
info = 'info',
custom = …
```

chore(ui): Replace AlertVariant enum with string

---

ui/apps/platform/src/Components/PatternFly/ConfirmationModal/ConfirmationModal.tsx
ui/apps/platform/src/Containers/Collections/CollectionsTable.tsx
ui/apps/platform/src/Containers/Collections/CollectionsTablePage.tsx
ui/apps/platform/src/Containers/Dashboard/Widgets/PolicyViolationTiles.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationPage.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsTable.tsx
ui/apps/platform/src/Containers/NetworkGraph/components/NodeUpdateSection.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step3/TableModal.tsx
ui/apps/platform/src/Containers/SystemHealth/DiagnosticBundle/GenerateDiagnosticBundle.tsx
ui/apps/platform/src/Containers/SystemHealth/UsageStatistics/ShowAdministrationUsage.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ApprovedDeferrals/ApprovedDeferralsSearchFilter.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ApprovedFalsePositives/ApprovedFalsePositivesSearchFilter.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/DeferredCVEs/DeferredCVEsTable.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/FalsePositiveCVEs/FalsePositiveCVEsTable.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ImageVulnsSearchFilter.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ImpactedEntities/ImpactedEntities.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ObservedCVEs/ObservedCVEsTable.tsx
ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/PendingApprovals/PendingApprovalsSearchFilter.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx

Because of change to 4.6 code freeze, replace enum first, and then add `no-Variant` lint rule after.
1. In general, more consistency lowers the barrier to contributors from other teams.
2. In specific, `ButtonVariant` enum is an extra import.
The source of truth for prop values of PatternFly elements is string **enumeration**, not string **enum**.
For example,
https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Button/Button.tsx#L79
```tsx
variant?: 'primary' | 'secondary' | 'tertiary' | 'danger' | 'warning' | 'link' | 'plain' | 'control' | 'stateful';
```
**not**
https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Button/Button.tsx#L8-L18
```tsx
export enum ButtonVariant {
primary = 'primary',
secondary = …
```

chore(ui): Replace ButtonVariant enum with string

---

CHANGELOG.md
pkg/features/list.go
pkg/scannerv4/mappers/mappers.go
pkg/scannerv4/mappers/mappers_test.go
tools/allowed-large-files

Since we are not ready to display both CVEs and RHSAs in the UI and reports (separating CVEs from RHSAs), we must continue to show RHSAs instead of CVEs for fixed vulnerabilities affecting Red Hat products.
This is configurable via feature flag; however, for those who may choose to just have a complete break away from RHSAs.
CI + tested with `registry.redhat.io/advanced-cluster-security/rhacs-scanner-db-rhel8@sha256:ca6719b04994956335e2a57af104cc185576838ff26a2405e49e42bf0f8cca94`:
The RHSAs look correct, and the NVD CVSS scores look correct, too

ROX-26671: revert to previous behavior and use RHSA

---

ui/apps/platform/eslint-plugins/pluginPatternFly.js
ui/apps/platform/eslint.config.js
ui/apps/platform/src/Components/EmptyStateTemplate/EmptyStateTemplate.tsx
ui/apps/platform/src/Components/PatternFly/BacklogListSelector.tsx
ui/apps/platform/src/Components/PatternFly/CheckboxSelect.tsx
ui/apps/platform/src/Components/PatternFly/DayPickerDropdown.tsx
ui/apps/platform/src/Components/PatternFly/FormMultiSelect.tsx
ui/apps/platform/src/Components/SelectSingle/SelectSingle.tsx
ui/apps/platform/src/Containers/AccessControl/SelectSingle.tsx
ui/apps/platform/src/Containers/Collections/CollectionResults.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ProfileDetailsHeader.tsx
ui/apps/platform/src/Containers/Dashboard/ClusterSelect.tsx
ui/apps/platform/src/Containers/Dashboard/NamespaceSelect.tsx
ui/apps/platform/src/Containers/Dashboard/Widgets/NoDataEmptyState.tsx
ui/apps/platform/src/Containers/MainPage/InviteUsers/InviteUsersConfirmationNoEmail.tsx
ui/apps/platform/src/Containers/NetworkGraph/common/AdvancedFlowsFilter/AdvancedFlowsFilter.tsx
ui/apps/platform/src/Containers/NetworkGraph/common/NetworkPolicies.tsx
ui/apps/platform/src/Containers/NetworkGraph/components/DisplayOptionsSelect.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx
ui/apps/platform/src/Containers/NetworkGraph/simulation/ViewActiveYAMLs.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step1/PolicyCategoriesSelectField.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaFieldInput.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step3/TableModal.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step4/PolicyScopeForm.tsx
ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesFilterSelect.tsx
ui/apps/platform/src/Containers/SystemConfig/Form/FormSelect.tsx
ui/apps/platform/src/Containers/SystemHealth/DiagnosticBundle/DiagnosticBundleForm.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx

Merge **after** 4.6 code freeze.
1. In general, more consistency lowers the barrier to contributors from other teams.
2. In specific, `WhateverVariant` enum is an extra import.
The source of truth for prop values of PatternFly elements is string **enumeration**, not string **enum**.
For example,
https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/EmptyState/EmptyState.tsx#L29
```tsx
variant?: 'xs' | 'sm' | 'lg' | 'xl' | 'full';
```
**not**
https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/EmptyState/EmptyState.tsx#L7-L13
```tsx
export enum EmptyStateVariant {
'xs' = 'xs',
sm = 'sm',
lg = 'lg',
'xl' = 'xl',
full = 'full'
}
```
Although `PageSectionVariants` and `TextVariants` (plural instead of singular) have …

chore(ui): Add pluginPatternFly with limited no-Variant lint rule

---

central/sensor/service/pipeline/nodeindex/three_pipelines_test.go
central/sensor/service/pipeline/nodeinventory/pipeline.go
image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl
image/templates/helm/stackrox-secured-cluster/templates/collector.yaml.htpl

This PR does three things:
1. Conditionally enable Node Indexing support on Central if deployed on OpenShift 
1. Disable Node Indexing on Compliance by default
1. Rework logic to discard v2 Node Scanning messages
---
1. is a fix for an introduced bug. Currently Node Indexing is enabled on central when running on managed services.
2. is done as Node Indexing will not be released as GA. By disabling it in Compliance, we ensure we don't generate any additional I/O or CPU load on the Collector DaemonSet by not running Node Index scans in the first place.
3. is done to ensure proper operation of NodeScanning in environments with mixed Secured Cluster versions, e.g. some clusters run v4-only, some clusters run v2-only.
---
Deployed on a test instance with Helm and manually verified …

fix: Change Node Indexing default settings

---

ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx

Thank you, **David** for telling me about `isActionCell` prop!
Besides inconsistent layout, inconsistent props for cells that have exceptions prevent a lint rule to require `dataLabel` prop.
1. Find in Files `isActionCell` has 10 results in 9 files
2. Find in Files `<ActionsColumn` has 19 results in 18 files
3. Find in Files `pf-v5-u-px-0` has 7 results in 7 files
* 3 for `Td` element relevant here
* 4 for `ToolbarContent` element not relevant here
1. Add (or replace `className` prop with) `isActionCell` prop.
1. Replace `className="pf-v5-u-text-align-right"` prop of empty `Td` cell with:
* `isActionCell` prop
* `ActionsColumn` child element
2. `npm run lint` in ui/apps/platform
3. `npm run build` in ui/apps/platform and then compute branch - master …

chore(ui): Add missing isActionCell prop to Td elements

---

ui/apps/platform/eslint-plugins/pluginPatternFly.js

Add lint rule for to prevent future inconsistencies like some fixed in #13113
```js
// Although Td element renders prop as data-label attribute,
// require dataLabel prop to simplify other lint rules.
```

chore(ui): Add no-Td-data-label lint rule for PatternFly

---

ui/apps/platform/eslint-plugins/pluginGeneric.js

Add lint rule for **managed columns** to prevent future inconsistencies like some fixed in #13085
Inconsistencies are easy to overlook, especially for responsive data label:
* When we change column heading text.
* When we add column management to an existing table.
```js
// Require that Td element has key and title from defaultColumns configuration.
// That is, if Td element has props for column management:
// className={getVisibilityClass('whichever')}
// dataLabel="Whatever"
// Then defaultColumns has whichever: {title: "Whatever"} property.
```
Added corresponding rule for `Th` element:
```js
// Require that Th element has key and text from defaultColumns configuration.
// That is, if Th element has prop for column management:
// className={getVisibilityClass('whichever')}
// Whatever …
```

chore(ui): Add Td-defaultColumns lint rule in pluginGeneric

---

ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.tsx
ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.utils.ts

Replace `map` method for `columns` with individual `Th` and `Td` elements:
* To benefit from lint rules for consistency.
* To be able to generate table columns for comparison.
* To increase our ability to reuse knowledge and skills to update tables easily.
Also replace `items` prop of empty `Td` element:
* `isActionsCell` prop
* `ActionsColumn` child element
main.js 0 = 4619921 - 4619921
total 387 = 11745226 - 11744839
files 0 = 180 - 180
No visual nor behavioral (sorting) change for `Th` elements.
1. Visit /main/policy-management/policies
* Before changes …

chore(ui): Replace columns configuration in PoliciesTable

---

central/complianceoperator/v2/pipelines/complianceoperatorscansv2/pipeline.go
central/complianceoperator/v2/pipelines/complianceoperatorscansv2/pipeline_test.go
central/complianceoperator/v2/report/manager/manager.go
central/complianceoperator/v2/report/manager/manager_impl.go
central/complianceoperator/v2/report/manager/manager_test.go
central/complianceoperator/v2/report/manager/mocks/manager.go
central/complianceoperator/v2/report/manager/watcher/scanconfigwatcher_test.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher_test.go
central/complianceoperator/v2/report/manager/watcher/utils.go

This PR aims to handle two situations:
- (1) CO sends Scan updates with different timestamps. This happens when a Scan gets triggered, sometimes CO sends a timestamp in the PENDING phase and then a different one in the LAUNCHING phase. This will be address in CO version 1.6.1 but we still need to handle this for older CO versions. In this situation we simply reset the ScanWatcher and start watching the Scan with the newer timestamp.
- (2) CO deletes Scans and re-creates them. Sometimes when the ScanSetting and the ScanSettingBinding is created, CO creates a Scan, immediately deletes it, and then re-creates it. This is handle by stopping the ScanWatcher if a REMOVE event is received.
- Observe that the reports are correct
- We only create one ScanWatcher per Scan in the situation (1)
- We …

fix(reporting): Aggregate timestamps in the scan watcher

---

tests/performance/scale/config/metrics-acs-scanner-v4-indexer.yml
tests/performance/scale/config/metrics-acs-scanner-v4-matcher.yml
tests/performance/scale/config/metrics-acs.yml
tests/performance/scale/config/metrics-full.yml
tools/allowed-large-files

This PR adds Scanner V4 metrics to be collected by kube-burner perf&scale test runs.
*Info for reviewer*
- Most of our components are prefixed with the name of the container. In the case of the scanner, there is the additional prefix (`scanner_v4_`) for metrics stored in Elastic. Please ensure that container names are correct in PormQL queries.
I didn't do any validation. 😞

chore(scale): Add scanner v4 metrics

---

config-controller/api/v1alpha1/policy_types.go
config-controller/config/crd/bases/config.stackrox.io_securitypolicies.yaml
image/templates/helm/stackrox-central/crds/config.stackrox.io_securitypolicies.yaml

Setting description field to optional specifically for it to be removed from the list of required fields in the generated CRD spec.
Manually on a cluster, applied a policy CR with the description field missing from the spec and verified policy gets created.
```
$:~/go/src/github.com/stackrox/stackrox/c/helm/chart$ kubectl -n stackrox create -f /tmp/policy-cr.yaml 
securitypolicy.config.stackrox.io/boo-test created
$:~/go/src/github.com/stackrox/stackrox/c/helm/chart$ cat /tmp/policy-cr.yaml 
apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
name: boo-test
spec:
policyName: boo-test
rationale: A demo!
categories:
- Anomalous Activity
- DevOps Best Practices
lifecycleStages:
- DEPLOY
scope:
- namespace: "boo-namespace"
severity: HIGH_SEVERITY
policySections:
- …
```

fix(be): CRD validation desc optional

---

pkg/utils/ignore_error.go
sensor/tests/helper/helper.go

The remove functions for resources like namespaces in the integration tests helper can be nil if the creation fails. If they are nil, the defer statements that call them will panic.
This PR adds a new function `IgnoreErrorAndCheckNil` that will call the given function if the function is not nil.
- Comment [these lines](https://github.com/stackrox/stackrox/blob/fd1ef713d1d87a2ec9fbdc61f5b1bddbac9eb8d5/sensor/tests/helper/helper.go#L264-L266)
- Manually create the namespace `sensor-integration`
- Run any integration tests: `go test -race -count=1 github.com/stackrox/rox/sensor/tests/resource/service`
- You should see the tests panics before these changes because the `removeNamespace` function is nil and with the changes the tests fail but not panic.

ROX-26326: Ignore remove functions if nil

---

pkg/mtls/certwatch/certwatch.go

Line breaks mine for readability:
Before:
```
pkg/mtls/certwatch: 2024/11/04 10:18:33.861395 certwatch.go:61: Info: TLS certificate loaded, using the following cert for HTTPS:
(SerialNumber: 8653177060486310112,
Subject: CN=*.scanner-v4-indexer.rhacs-operator.svc,
DNSNames, [*.scanner-v4-indexer.rhacs-operator.svc *.scanner-v4-indexer.rhacs-operator.svc.cluster.local scanner-v4-indexer.rhacs-operator.svc scanner-v4-indexer.rhacs-operator.svc.cluster.local]),
watch dir: "/run/secrets/stackrox.io/monitoring-tls"
```
After:
```
pkg/mtls/certwatch: 2024/11/05 07:52:39.252566 certwatch.go:61: Info: TLS certificate loaded, using the following cert for HTTPS:
(SerialNumber: 8653177060486310112,
Subject: CN=*.scanner-v4-indexer.rhacs-operator.svc,
DNSNames: …
```

feat(certwatch): log issuer, fix typo

---

ui/apps/platform/package-lock.json
ui/apps/platform/package.json
ui/apps/platform/src/utils/responseErrorUtils.ts

As titled.
The changes a dependency that is used on every network call and essentially impacts every piece of the UI for the app. I have done smoke testing of read-only requests throughout that app, as well as smoke testing of write requests in Integrations, Policies, and VM.
Since the only import of runtime code for `axios` is in the `instance.js` file, it should be unlikely that we hit any API edge cases that are missed with the manual testing above and the coverage we get via Cypress tests.

ROX-22791: Bump axios and axios-fetch to latest versions

---

central/cluster/datastore/telemetry.go
central/telemetry/centralclient/instance_config.go
pkg/telemetry/phonehome/client_config.go
pkg/telemetry/phonehome/segment/segment.go
pkg/telemetry/phonehome/segment/segment_test.go
pkg/telemetry/phonehome/telemeter/telemeter.go
pkg/telemetry/phonehome/telemeter/telemeter_test.go

The PR adds version information to the telemetry object context, so that we could see version change on the analytics platform. And also the User-Agent of the actual sender.
*Segment receives*:
```json
{
"anonymousId": "0121d10e-e4ce-43b0-b780-e7bf604d24a5",
"context": {
"app": {
"build": "development",
"version": "4.6.x-806-gdbcb79fc0e"
},
"device": {
"id": "0121d10e-e4ce-43b0-b780-e7bf604d24a5",
"type": "Central Server",
"version": "4.6.x-806-gdbcb79fc0e"
},
"library": {
},
"userAgent": "Rox Central/4.6.x-806-gdbcb79fc0e (linux; amd64)"
},
"event": "Telemetry Enabled",
"messageId": "4f791d61-4b26-45ab-9923-a40a96fc6421",
"originalTimestamp": "2024-10-24T12:34:23.559067784Z",
"receivedAt": "2024-10-24T12:34:23.848Z", …
```

chore(telemetry): add Version to the telemetry context
