stackrox/stackrox

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/useNodeVulnerabilities.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/useAffectedNodes.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodeCves.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodes.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/useClusterVulnerabilities.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/usePlatformCves.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/usePlatformCveMetadata.ts
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx
ui/apps/platform/src/services/ComplianceResultsService.ts
ui/apps/platform/src/services/ComplianceResultsStatsService.ts
ui/apps/platform/src/utils/searchUtils.test.ts
ui/apps/platform/src/utils/searchUtils.ts

Duplicate pull request of  https://github.com/stackrox/stackrox/pull/11293 since GHA seems to be stuck on that one.

chore(ui): refactor pagination util

---

ui/apps/platform/src/Containers/AccessControl/PermissionSets/ResourceDescription.tsx

Fix the missing trailing period in the permission description.
responsible for the …

fix(ui): trailing period for permission description

---

ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/AcscsEmailIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/IntegrationForm.tsx

BE integration tbd but the payload should look good

ROX-24088: Adding ACSCS Default Email Integration form

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/ConditionNumber.tsx
ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.test.ts

This PR adds an `onSearch` function to `CompoundSearchFilter`. Using the returned `searchKey` and `searchValue` results, we can modify the URL search

feat(ui): Adding onSearch to CompoundSearchFilter

---

central/complianceoperator/v2/report/manager/manager_impl.go

fix(be): Add max concurrency for on demand compliance reports

---

tests/endpoints_test.go

Fixing test failure seen in #11326.

fix: revert change from bdff0f6

---

central/debug/service/service.go
pkg/postgres/stats/stats.go

ROX-23754: postgres dead tuples and analyze stats #10980
Add some more postgres info to the diagnostic bundle

chore: Backport #10980 to `release-4.4`

---

sensor/common/sensor/central_communication_test.go
sensor/debugger/message/fake.go
sensor/kubernetes/complianceoperator/handler_impl.go
sensor/kubernetes/complianceoperator/utils.go
sensor/tests/connection/k8sreconciliation/reconcile_test.go

Some clean-ups and readability improvements to #11051

chore(clean-up): Follow up on reconcile scan configs

---

.openshift-ci/ci_tests.py

This should clear its cache, avoiding flakes as described in ticket.

ROX-24263: Bounce catalog operator pod.

---

central/complianceoperator/v2/scanconfigurations/service/convert.go

fix(be): Fix to store report notifiers to storage

---

central/complianceoperator/v2/benchmarks/datastore/datastore.go
central/complianceoperator/v2/benchmarks/datastore/datastore_impl.go
central/complianceoperator/v2/benchmarks/datastore/datastore_impl_test.go
central/complianceoperator/v2/benchmarks/datastore/mocks/datastore.go
central/complianceoperator/v2/profiles/datastore/datastore_impl.go

ROX-23319: Get Benchmark by Profile Name
- Added CI test
- Complete test follows in API implementations

ROX-23319: Get Benchmark by Profile Name

---

ui/apps/platform/src/Containers/Policies/Detail/ExcludedDeployment.tsx
ui/apps/platform/src/Containers/Policies/Detail/Restriction.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step4/PolicyScopeCard.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step4/PolicyScopeForm.tsx

Wizard step 4: 
Policy detail:

ROX-24475: Change "Label" in Policy Scope to "Deployment label"

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts

Like https://github.com/stackrox/stackrox/pull/11378 and https://github.com/stackrox/stackrox/pull/11397, but for the Deployment single page.
_Easier to review with "Hide whitespace" on_
Existing e2e tests.
Manual testing of table states:
https://github.com/stackrox/stackrox/assets/1292638/5fab4c2f-3aba-4d4a-a59b-cb62fe3cb7b7
Deployment with zero CVEs:

ROX-24514: Update Deployment page to use TbodyUnified

---

image/postgres/konflux.Dockerfile
image/rhel/konflux.Dockerfile
image/roxctl/konflux.Dockerfile
operator/konflux.Dockerfile
scanner/image/db/konflux.Dockerfile
scanner/image/scanner/konflux.Dockerfile

ROX-20236: Set `release` Dockerfile label explicitly

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/Components/CompoundSearchFilter/components/EntitySelector.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx
ui/apps/platform/src/services/ComplianceCommon.ts
ui/apps/platform/src/services/ComplianceResultsService.ts

This PR integrates Advanced Filters into the Compliance Profile Check Details page.
1. The compliance status dropdown was also added
2. Hooking up URL search to filter API results
3. Adding search filter chips

ROX-24575: Adding table filters to Profile Check Details

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.constants.ts

This PR fixes an error that was brought up with the last few merges related to Compliance.

fix(ui): Compliance errors

---

scanner/indexer/indexer.go

Before it was just a debug log, as it was possible we'd see a lot of log spam. Now, it is enhanced to log a warning upon the first failure. This is so users who use the default log level may still see this warning. Note: it's just a warning, as we can still proceed. It just won't be pretty.
Out side the scope of this PR: Test various registries to see how many support the Range Header
not really
In addition to reviewing code …

chore(scanner): warn when registry does not support range header

---

central/networkgraph/entity/gatherer/load_bundled.go

This is a recreation of #11234 with a rebase, so that CI can build it.

chore(fix): Close unclosed file handle 

---

pkg/protocompat/time_test.go

This PR is adding unit tests (or sections) that will cover execution paths that return an error.
This is important for protobuf V2 migration because `gogo` proto conversion functions do validation, but protobuf V2 (or V1) framework does not do that, and validation has to be called manually. To avoid wrong implementation of compatibility functions with protobuf V2 we should cover paths where errors can be returned.
The intention of added tests is not to cover validation implemented in a specific proto framework, but to cover that compatibility functions can return an error. We had an issue during the protobuf V2 switch that changes in the compatibility layer did not ever return an error, and that caused unexpected behavior in caller functions.
Implementation of validations are different in …

ROX-22019: Tests to cover protocompat time functions with errors

---

.github/api_guidelines.md

This extends the existing API guidelines to also include guidelines regarding deprecation of APIs.
The guidelines include announcement methods done historically (e.g. during resource consolidation for permissions) and others (e.g. the 2 release deprecation annoucement).
N/A.

chore(docs): API deprecation guidelines

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx

Conditionally uses Advanced Filters on the Workload CVE Image single page.
Manual verification of the functionality of each filter against the table data.
Existing e2e tests that have been updated for the new components.

ROX-24614: image single page advanced filters

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx

As titled, like many before it and a few more after it.

ROX-23047: Advanced filters for node single page

---

ui/apps/platform/src/Components/ComplianceUsageDisclaimer.tsx
ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx
ui/apps/platform/src/hooks/useLocalStorage.ts

Adds a usage disclaimer to both Compliance V1 and V2 to satisfy legal
Before accepting:
After accepting:
* Alert disappears in all three places and local storage key updated

ROX-24510: Compliance usage disclaimer

---

central/graphql/resolvers/node_cve_core.go
central/graphql/resolvers/node_cve_core_test.go
central/graphql/resolvers/resolver.go
central/graphql/resolvers/resource_total_count_by_severity.go
central/graphql/resolvers/test_setup_utils.go
central/views/common/types.go
central/views/nodecve/db_response.go
pkg/metrics/resolver_string.go
pkg/metrics/resolvers.go

Add node cve single page and list page resolvers.

ROX-23380,ROX-23583: Add Node CVE resolvers single and list page

---

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/ClustersTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx
ui/apps/platform/src/Containers/Vulnerabilities/searchFilterConfig.ts

As titled.
Visit Platform CVEs and apply filters:
Clear filters:

ROX-23055: Add advanced filters bar to Platform CVE overview page

---

ui/apps/platform/src/Containers/Risk/Process/Details.js

Requested by Maria. 
Should look like below:

ROX-24582: Risk -> Running Processes word change

---

central/alert/service/service_test.go
central/graphql/resolvers/utils_test.go
pkg/testutils/full_init.go
pkg/testutils/full_init_test.go

In test we compare object with `nil` while more readable is `assert.Nil`
CI

test: replace Equal nil with Nil

---

scripts/ci/get-slack-user-id.sh

chore: added slack user ID

---

ui/apps/platform/cypress/integration/configmanagement/ConfigurationManagement.helpers.js

ROX-24480: Config Mgmt e2e test fixes

---

operator/apis/platform/v1alpha1/securedcluster_types.go
operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml
operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml

As part of https://issues.redhat.com/browse/ROX-23426 I have implemented defaulting logic (in a separate PR) for the central endpoint port so that if no port is specified for `https://...` endpoints, then the port 443 will be used.
This PR extends the Operator docs slightly to inform the user about this change. …

ROX-23426: Document default port 443 for HTTPS endpoints

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/deploymentSingle.test.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveSingle.test.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx
ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
ui/apps/platform/src/Components/CompoundSearchFilter/utils/searchFilterConfig.test.ts
ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.test.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx

This PR changes the compound search filter to use sentence case ([jira](https://issues.redhat.com/browse/ROX-24759))

ROX-24759: Use sentence case in compound search filter

---

.github/workflows/scanner-build.yaml
scripts/ci/govulncheck.sh

Scan the Scanner V4 binary/image and Scanner V4 DB image.
CI

ci(scanner): scan go binary and images

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/useNodeSummaryData.tsx

Changes required to sync the UI with the production BE GraphQL queries on the Node CVE - Node Single page.
Uses build 4.4.x-1054-g98250e1bd8 from https://github.com/stackrox/stackrox/pull/11623 for testing.
Visit a Node single page:
Apply filters:

ROX-24838: Integrate Node Single page with BE queries

---

ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx

As defined in the ticket & mocks: https://www.figma.com/proto/AGW1QHV3smDPH6onJ0mJS4/Disclaimer?page-id=0%3A1&node-id=6-2086&viewport=-1182%2C-69%2C0.79&t=ZnOqlnj1TqxHtka9-1&scaling=scale-down&content-scaling=fixed

ROX-24746: Network graph policy simulator text changes

---

scanner/mappers/mappers_test.go

fix: replace Equal on proto with protoassert. 

---

CHANGELOG.md

Adds changelog for: https://github.com/stackrox/stackrox/pull/11359
N/A

ROX-24725: Add changelog for sensor scan enhancmenets

---

ui/apps/platform/src/Containers/Clusters/ClusterEditForm.tsx
ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/ClustersHealth.utils.ts
ui/apps/platform/src/types/cluster.proto.ts

Trying to reproduce https://issues.redhat.com/browse/ROX-24306 should not cause a page crash

ROX-24306: System health page crash fix

---

central/compliance/manager/run_test.go
central/policy/service/service_impl_test.go
pkg/booleanpolicy/default_policies_test.go
pkg/protoassert/assert.go
sensor/common/detector/enricher_test.go
sensor/kubernetes/listener/resources/deployment_store_test.go
tests/policy_test.go
tools/roxvet/analyzers/donotcompareproto/analyzer.go

- #11531
- #11533
- #11503
- #11507
- #11575
- #11571 :point_left: 
- #11572 
- https://github.com/stackrox/stackrox/pull/11582
- https://github.com/stackrox/stackrox/pull/11583
- https://github.com/stackrox/stackrox/pull/11585
- https://github.com/stackrox/stackrox/pull/11588  
- https://github.com/stackrox/stackrox/pull/11618 
- https://github.com/stackrox/stackrox/pull/11619

tests: protoassert.SliceContains

---

central/deployment/datastore/test/datastore_sac_test.go
central/policy/service/service_impl_test.go
roxctl/scanner/downloaddb/downloaddb_test.go
roxctl/sensor/generate/generate_test.go
sensor/kubernetes/listener/resources/deployment_store_test.go

New version of proto contains mutex which could cause problems when doing a shallow copy. This PR fixes that.
- #11531
- #11533
- #11503
- #11507
- #11575
- #11571
- #11572  
- https://github.com/stackrox/stackrox/pull/11582 :point_left:
- https://github.com/stackrox/stackrox/pull/11583 
- https://github.com/stackrox/stackrox/pull/11585
- https://github.com/stackrox/stackrox/pull/11588 
- https://github.com/stackrox/stackrox/pull/11618 
- https://github.com/stackrox/stackrox/pull/11619 
provided …

fix: do not copy protos

---

pkg/testutils/full_init.go

We have faced a test failure because of used randomized numbers. We expect that generated numbers are unique, but from time to time, we get a collision.
I have added more info to the ticket on how to reproduce and possible solutions. This solution will simply use the predefined seed. With constant random seed, tests should be reproducible and always fail or pass.
A bit more robust and safer solution would be to add a tracker of generated numbers and track uniqueness, but that would add complexity to implementation and it would also lead to larger memory utilization to keep track of produced numbers.
It also changes the comparison of types to use predefined constants in `protocompat` instead of strings. This is important for the protobuf V2 switch.
- ~[ ] Unit test and regression tests …

ROX-24908: Change uniqueInitializer to use seeded random

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx

This PR fixes the empty state text to be clearer when we paginate far enough that no results are showing for a table. We can't disable the buttons because PF doesn't allow for that. This is the next best thing we can do.

ROX-24761: Better empty state text when paginating too far

---

migrator/migrations/m_201_to_m_202_vuln_request_v1_to_v2/schema/convert_vulnerability_requests_test.go
migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/schema/convert_image_cve_edges_test.go
migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/schema/convert_image_cves_test.go
migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/schema/convert_images_test.go
migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/schema/convert_vulnerability_requests_test.go

fix(be): Fix style checks

---

.github/pull_request_template.md

The PR aims to improve some aspects around the UX of the current PR template:
* less noise if the boilerplate text is not removed
* few words, most of the time folks already know all this or learned how to ignore it
* less editing for more common cases, e.g., no need to strike out bullet points if they don't apply
* harder (hopefully) to ignore by reviewers because checklists are more "in your face" …

chore: Improve PR template UX

---

pkg/features/list.go

Enables Advanced Filters and Unified Deferrals, which are feature complete.
Manual verification.

chore(ui): Enable intermediate VM 2.0 feature flags

---

pkg/cloudproviders/aws/metadata.go
pkg/cloudproviders/azure/metadata.go

Change the metadata logs from `Error` to `Debug`. The reason is that metadata is fetched heuristically, and therefore failures may be expected for certain cluster setups. A consequence of failed metadata requests is that the cluster type may be undetermined, but it should not have serious consequences as may be suggested by the error level logs.
change me!

fix(metadata): debug logs

---

central/notifiers/acscsemail/acscsemail.go
operator/tests/common/central-cr.yaml
pkg/administration/events/codes/codes.go

This PR adds logging to the acscsEmail integration so that error logs will appear in AdministrationEvents to allow customers of ACSCS who don't have access to central logs to see problems with their email sending.
This is important to communicate e.g rate limitting issues.
- Deploy a central to an openshift cluster use `ROX_MANAGED_CENTRAL=true`
- Create a acscsEmail integration
- Hit test on that integration
- Make sure an error log appears in adminstation events in UI

fix: log acscsEmail errors to admin events

---

central/testutils/export.go

A previous CI run of the new export benchmark tests did fail (timeout).
Re-running the tests did not reproduce the failure, but in order to limit the risk of such a flake re-occurring, the size of the test dataset was reduced to the minimum.
Manual run of the altered benchmark in all impacted service directories:
Test: `go test -v -tags sql_integration -bench .`
Impacted directories:
- central/deployment/service
- central/image/service
- central/vulnmgmt/service

tests: reduce export benchmark dataset size for non-scale tests

---

.github/actions/junit2jira/action.yaml
scripts/ci/lib.sh
tests/e2e/run-scanner-v4.bats
tests/roxctl/authz-trace.sh
tests/roxctl/slim-collector.sh
tests/roxctl/token-file.sh

I have observed test flakes of the nature (e.g. https://issues.redhat.com/browse/ROX-24983)
```sh
curl: (7) Failed to connect to 34.134.5.28 port 443: Connection refused
```
`curl` by default does not retry in such cases. To make our tests more resilient, let's classify connection refused errors as transient.
CI

ROX-24983: retry on connection refused

---

pkg/features/list.go

chore(flags): compliance enable features

---

ui/apps/platform/cypress/integration/integrations/signatureIntegrations.test.js
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/SignatureIntegrationForm.tsx
ui/apps/platform/src/types/signatureIntegration.proto.ts

Extend the signature integration form to also cover the newly introduce configuration for certificate verification. This is required to support customers to be able to configure their certificate / chain and other related information to verify cosign signatures with certificates instead of public keys.
The previous PRs in the series give a context in the history and the backend implementation, but from the front-end side only this PR to extend the form is required.
Default view when creating integration:
View when creating certificate verification data:
Help icon to indicate regular expression support and document syntax:
Read view when integration with certificate verification data has been created:
- see CI.
In addition to reviewing …

ROX-24076: Add cert verification in signature integration form

---

qa-tests-backend/src/test/groovy/ImageSignatureVerificationTest.groovy

Fix an issue which cause policy evaluation in some cases to evaluate against an _unenriched_ image due to the time of creating the deployment and policy being nearly equal.
In case enrichment took a bit longer, evaluation might have already kicked in and used the unenriched image, which obviously fails the policy.
By ensuring we have fetched metadata, we ensure we have finished enriching all images _before_ creating the policy and subsequent alerts.
-see CI.

ROX-24645: fix ImageSignature tests flake

---

proto/storage/proto.lock

Updates to the protolock based on 4.5 changes.
- [x ] contributed **no automated tests**
CI is sufficient for the protolock file.
change me!

chore(protolock): update protolock

---

scripts/ci/bats/image_list.bats
scripts/ci/lib.sh

We seen a failure in upgrade test related to missing central-db image. The test need to wait for image.
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-master-merge-gke-upgrade-tests/1801193388913987584#1:build-log.txt%3A706
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-master-merge-gke-upgrade-tests/1801193388913987584#1:build-log.txt%3A408-410
change me!

fix: require central-db for upgrade test

---

CHANGELOG.md

Simply updating the changelog
~- [ ] Investigated and inspected CI test results~
provided convince any reviewer or any external …

ROX-23416:  compliance changelog

---

pkg/features/list.go

As titled.
Should not be merged before the following are merged:
https://github.com/stackrox/stackrox/pull/11634
https://github.com/stackrox/stackrox/pull/11657
Manual API response inspection.

chore: Enable Node/Platform CVE feature flag

---

pkg/features/list.go

As titled.
Manual API response inspection.

chore: Enable VM 2.0 GA feature flag

---

sensor/kubernetes/listener/resource_event_handler.go

Document the `handleAllEvents` function.
This is just a comment

chore(doc): Add comment in handleAllEvents

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/useNodeVulnerabilities.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/useClusterVulnerabilities.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/telemetry.ts
ui/apps/platform/src/hooks/useAnalytics.ts

As titled, based on the equivalent change in Workload CVEs. https://github.com/stackrox/stackrox/pull/11747
_Will add automated tests for telemetry in the future._
Follow the manual verification process described in https://github.com/stackrox/stackrox/pull/11747 for the following pages:
- Node CVE Overview
- Node single page
- Node CVE single page
- Platform CVEs Overview
- Cluster single page
- Platform CVE single page

ROX-24509: Add filter telemetry Node/Platform CVEs

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/SearchFilterAutocomplete.tsx

This PR adds the "Add" option to autocomplete, allowing you to search for a value even if no suggestions are available.
https://github.com/stackrox/stackrox/assets/4805485/946a633e-fe68-4cc6-81ea-000af6f9661d

ROX-24712: Include Add in autocomplete options

---

ui/apps/platform/src/Containers/Vulnerabilities/components/ExceptionRequestModal/CveSelections.tsx

Just as the title mentions. See the following discussion for more context: https://issues.redhat.com/browse/ROX-24829

ROX-24829: hide the affected images count to avoid confusion

---

generated/api/v1/vuln_mgmt_service.swagger.json
generated/api/v1/vuln_mgmt_service_grpc.pb.go
proto/api/v1/vuln_mgmt_service.proto

Make it more clear that the streaming output is a sequence of json objects, rather than one single json document.
change me!

fix(docs): vulnmgmt export API output schema

---

.openshift-ci/common.py
.openshift-ci/post_tests.py

A timestamp in these logs will help debug issues like https://issues.redhat.com/browse/ROX-25046.
CI

chore(CI): add timestamp to python layer logging

---

central/complianceoperator/v2/report/manager/complianceReportgenerator/consts.go

Added separator to compliance report email to make it more readable.
change me!

fix(be):  Added separator to complaince report email

---

.github/workflows/scanner-nvd-update.yaml
.github/workflows/scanner-release-vuln-update.yaml
.github/workflows/scripts/scanner-update-nvd.py

This PR has a workflow to download NVD data to GCS bucket.
We need another PR to modify current NVD updater/enricher to fetch CVSS data from GCS bucket. In this way we can avoid hammering NVD Api.
change me!

ROX-22618: download NVD data to GCS bucket

---

qa-tests-backend/src/main/groovy/services/BaseService.groovy

⚔️ Beware, Adventurer! 🐉
In the depths of this code lies a formidable dragon (gRPC retry config). Many brave souls (@janisz @stehessel) have ventured here and met their end. Heed this warning and proceed with caution, for meddling with this enchanted section may awaken the beast within. May your code be bug-free and your journey fruitful.
https://stackoverflow.com/q/407202
change me!

test(qa): add note on grpc retries

---

image/templates/helm/shared/templates/02-scanner-05-network-policy.yaml
image/templates/helm/shared/templates/02-scanner-v4-05-db-network-policy.yaml
image/templates/helm/shared/templates/02-scanner-v4-05-indexer-network-policy.yaml
image/templates/helm/shared/templates/02-scanner-v4-05-matcher-network-policy.yaml
image/templates/helm/stackrox-central/internal/config-shape.yaml
image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
image/templates/helm/stackrox-central/templates/00-stackrox-application.yaml
image/templates/helm/stackrox-central/templates/01-central-10-db-networkpolicy.yaml
image/templates/helm/stackrox-central/templates/01-central-10-networkpolicy.yaml
image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml
image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl
image/templates/helm/stackrox-secured-cluster/templates/admission-controller-netpol.yaml
image/templates/helm/stackrox-secured-cluster/templates/collector-netpol.yaml
image/templates/helm/stackrox-secured-cluster/templates/sensor-netpol.yaml
pkg/helm/charts/tests/centralservices/testdata/all-values-explicit.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/central.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/openshift-monitoring.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/monitoring.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/openshift-monitoring.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-slim.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/sensor-netpol.test.yaml

Comments in https://github.com/stackrox/stackrox/pull/11586/files justify why
Tested:
```
go test -v github.com/stackrox/rox/pkg/helm/charts/tests/centralservices
go test -v github.com/stackrox/rox/pkg/helm/charts/tests/securedclusterservices
```

ROX-23972: Change system. to network. for netpols

---

ui/apps/platform/cypress/integration/vulnerabilities/VulnerabilityReporting/VulnerabilityReporting.helpers.js
ui/apps/platform/cypress/integration/vulnerabilities/VulnerabilityReporting/reportsTable.test.js

Write two smoke tests for now.
1. Visit /main/vulnerabilities/reports and then use Elements and Network panels in browser to write test actions and assertions.
* vulnerabilities/VulnerabilityReporting/reportsTable.test.js

ROX-23954: Write integration tests for vulnerability reports

---

CHANGELOG.md

Update CHANGELOG with VM 2.0 changes
CI is enough
change me!

fix(be): Update changelog for VM 2.0 changes

---

central/complianceoperator/v2/scanconfigurations/service/convert.go
tests/compliance_operator_v2_test.go

This PR adds an e2e test for the update configuration path.

test(compliance): Add update scan configuration e2e test

---

pkg/secrets/reconcile.go

We have several locations where we walk recursively over structs and this does not work well with proto-generated structs, because we walk over internal fields that have recursive references with protobuf V2. That combination creates infinite look.
This solution will skip internal fields in proto-generated structs used by protobuf framework, and it will work on all fields from custom structs.
- executed unit tests locally on the V2 proto switch branch
- letting CI run validated changes in this PR

chore(proto): Add skip internal fields for secrets reconcile

---

qa-tests-backend/src/main/groovy/services/AuthProviderService.groovy

This PR adds retry to getAuthProviders call.
CI

ROX-23347: retry get auth providers

---

tests/backup_test.go
tests/cluster_delete_test.go
tests/e2e/run.sh
tests/excluded_scopes_test.go
tests/feature_flag_test.go
tests/graphql_sorting_test.go
tests/metadata_test.go

https://issues.redhat.com/browse/ROX-24688 was split in to 3 per-team tickets. Update some references to the new clones.
CI is more than enough.

test: Update refs to now-split ticket.

---

qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
qa-tests-backend/src/main/groovy/orchestratormanager/OrchestratorMain.groovy
qa-tests-backend/src/test/groovy/SummaryTest.groovy

Refactor the `Verify namespace details` test.

ROX-14763: Verify namespace details refactor

---

.github/workflows/check-pr-description.yaml
.github/workflows/check-pr-title.yaml
.github/workflows/scripts/check-pr-description.sh
.github/workflows/scripts/common.sh

Automated testing for the checked tasks in PR description.
```console
me@work $ scripts/local-env.sh check-pr-description "
start
change me!
"
start
change me!
"
::error::'change me!' found.
::debug::'CHANGELOG' task is checked.
::debug::'Documentation' task is checked.
::error::'inspected CI results' task is not checked.
::error::'added unit tests' task is not checked.
::debug::'modified existing tests' task is checked.
me@work $ echo $?
1
```
```console
me@work $ scripts/local-env.sh check-pr-description "
start
don't change me!
"
::debug::'CHANGELOG' task is checked.
::debug::'Documentation' task is checked.
::debug::'inspected CI results' task is checked.
::debug::'added unit …
```

chore: check PR description health

---

.github/workflows/build.yaml
operator/Makefile
operator/bundle_helpers/patch-csv.py

From 4.5 release the semantics/names of tags have changed.
Once 4.5 branch was cut and the 4.6.x tag created, commits on master would have expected to be 4.6.x and upgradable from 4.5, but the 4.5 release process is still in progress, so no 4.5 images exist, and producing a 4.6.x bundle would fail.
This is an ugly (for lack of better ideas) workaround that tests whether `X.(Y-1).0` exists and if not tries to use `X.(Y-2).0`.
Ran the make target from console.

fix: backtrack one y version if previous one is not released yet.

---

qa-tests-backend/src/test/groovy/K8sRbacTest.groovy

re-enabling a test that has been disabled for over a year.  Seems OK.
Literally re-enabling a test.  That is sufficient.

ROX-14666:  investigate rbac test

---

central/externalbackups/plugins/all/all.go

Currently I'm getting `external backup with type "s3compatible" is not implemented` when trying to create an S3 compatible backup.
```sh
roxcurl /v1/externalbackups -X POST --data-raw {...}
```

fix: register s3compatible plugin

---

central/externalbackups/plugins/s3compatible/s3compatible.go

The `aws-sdk-go-v2` package does not automatically add the `https` prefix. This made endpoint configured like `play.min.io:9000` fail. This change adds the `https` prefix if it's missing.
- Create a new set of access keys in the [mino-console](https://play.min.io:9443/).
- Create a new bucket, for example test-s3.
- Use the following go test to test the integration:
```golang
func TestS3Compatible(t *testing.T) {
integration := &storage.ExternalBackup{
Name:          "test-s3-compatible",
Type:          types.S3CompatibleType,
BackupsToKeep: 2,
Config: &storage.ExternalBackup_S3Compatible{
S3Compatible: &storage.S3Compatible{
Bucket:          "test-s3",
AccessKeyId:     "<access-key>",
SecretAccessKey: "<secret-access-key>",
Region:          "us-east-1",
ObjectPrefix:    "",
// ====== …
```

chore(fix): Add https prefix if it's missing

---

qa-tests-backend/src/test/groovy/SummaryTest.groovy

This is failing pretty consistently in AKS. Let's disabled it for now.

chore(disable-test): Disable test in aks

---

ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/S3CompatibleIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/IntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsTable.tsx
ui/apps/platform/src/Containers/Integrations/utils/integrationsList.ts
ui/apps/platform/src/Containers/Integrations/utils/tableColumnDescriptor.ts
ui/apps/platform/src/types/externalBackup.proto.ts
ui/apps/platform/src/types/integration.ts

This adds a new type of backup integration type meant for non-AWS S3 compatible storage providers (e.g. MinIO, Cloudflare R2, Backblaze B2, ...). See https://github.com/stackrox/stackrox/pull/11877 and https://github.com/stackrox/stackrox/pull/11878 for the corresponding backend changes.
I have attempted to follow the patterns from the existing S3 and GCS back integrations types. Changelog and documentation will be done outside of this PR. I'm also planning a follow up to create a UI e2e test for these changes.
Config changes that are different from AWS S3 plugin:
* container IAM role is only supported for AWS S3 for now.
* S3 compatible plugin may configure a URL style setting.
see …

ROX-25048: S3 compatible integration forms

---

central/externalbackups/datastore/telemetry.go

Add telemetry baseline for S3 compliant backup integrations.

chore(telemetry): S3 compliant backups

---

qa-tests-backend/src/main/groovy/services/ExternalBackupService.groovy
qa-tests-backend/src/main/groovy/util/Env.groovy
qa-tests-backend/src/test/groovy/IntegrationsTest.groovy

Add a qa-e2e test for the new S3 compatible backup type. The test uses Cloudflare R2 (S3 compatible storage provider) to host the bucket.
see test

ROX-25049: add S3 compatible qa-e2e test

---

central/compliance/datastore/internal/store/postgres/store.go
central/deployment/datastore/datastore_impl.go
central/detection/lifecycle/manager_impl.go
central/networkgraph/flow/datastore/flow_impl.go
central/user/datastore/internal/store/store_impl.go
pkg/expiringcache/cache.go
pkg/expiringcache/cache_test.go
pkg/expiringcache/mocks/cache.go
pkg/images/enricher/enricher_impl.go
pkg/telemetry/phonehome/segment/segment.go
sensor/common/detector/enricher.go
sensor/common/image/service_impl.go
sensor/common/image/service_impl_test.go
sensor/common/registry/tlscheck.go

This PR is a prefactor for adding a types to expiringcache. As we cannot return typed `nil` we will need another indicator that value is nil thus we have a boolean to handle that.
- https://github.com/stackrox/stackrox/pull/11924
- https://github.com/stackrox/stackrox/pull/11961
CI

chore(expiringcache): return additional bool from Get

---

pkg/images/enricher/enricher_impl_test.go

To minimize changes when adding types to generic store let's extract common code to a function.
- https://github.com/stackrox/stackrox/pull/11924
CI

test(enricher): cleanup duplicated code

---

central/cloudsources/manager/singleton.go
central/main.go
central/pruning/pruning.go
central/sensor/service/pipeline/clusterstatusupdate/pipeline.go
pkg/features/list.go
tests/e2e/lib.sh

Remove the cloud sources feature flag and turn it on permanently.
change me!

chore: remove cloud sources feature flag

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx

ROX-24756: Don't lowercase CVE in placeholder

---

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approvedDeferralsTable.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approvedFalsePositivesTable.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/deniedRequestsTable.test.ts
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx

This PR removes the border in the expanded row for the CVEs table within the Request Details page. I also decided to update the table to use the TBodyUnified component.
Visual check of the UI

ROX-24789: Make table borders consistent

---

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx

Fixes the compound search filter component tests
See if CI Passes

fix(ui): Fix compound search filter tests

---

central/externalbackups/plugins/s3compatible/s3compatible.go
central/externalbackups/plugins/s3compatible/s3compatible_test.go
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ExternalBackupIntegrations/S3CompatibleIntegrationForm.tsx

I thought to change the endpoint validation slightly to be more in line with other features. Using `FormatURL` avoid manual formatting and covers more edge cases. It also allows for `http` endpoints if they are explicitly defined as such (may occur when users are self-hosting their providers). I also changed the help text in the UI to account for `http` being allowed.
qa-e2e already test different endpoint schemes.

fix: s3compatible endpoint validation

---

pkg/auth/authproviders/oidc/backend_impl_test.go
pkg/auth/authproviders/oidc/provider.go

Retry the provider creation for OIDC providers since this caused a flake when reaching out to sso.r.c.
I've decided to only retry the issuer verification (i.e. provider creation) and not pass a retry client for other OIDC flows, since retrying those may lead to unexpected errors as they are
in most cases not idempotent operations.
N/A.

ROX-25055,ROX-25056: retry OIDC provider creation

---

pkg/scanners/clairv4/clairv4.go

Fix the `FIXME` noticed while browsing the code paths here.
N/A

chore: use url.JoinPath

---

ui/apps/platform/cypress/fixtures/integrations/externalBackups.json
ui/apps/platform/cypress/integration/integrations/externalBackups.test.js
ui/apps/platform/cypress/integration/integrations/integrations.helpers.js

Add a ui-e2e test for the S3 compatible form added in #11847.
See CI

ROX-25048: add ui e2e test

---

.github/workflows/scanner-dev-vuln-update.yaml
.github/workflows/scanner-release-vuln-update.yaml

We should be able to choose from different NVD sources
```
Run set -eu
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
10  114M   10 11.5M    0     0  13.7M      0  0:00:08 --:--:--  0:00:08 13.7M
58  114M   58 67.6M    0     0  37.5M      0  0:00:03  0:00:01  0:00:02 37.5M
100  114M  100  114M    0     0  45.3M      0  0:00:02  0:00:02 --:--:-- 45.3M
200
```
Updater in CI
```
{"level":"debug","bundle":"nvd","component":"libvuln/updates/NewManager","factory":"nvd","time":"2024-07-17T15:47:32Z","message":"factory unconfigurable"} …
```

ROX-25219: Make data source configurable

---

ui/apps/platform/src/Containers/Integrations/utils/integrationUtils.ts
ui/apps/platform/src/Containers/Integrations/utils/tableColumnDescriptor.ts

* introduce 24-hour clock format in backup schedules. We already established 24-hour clocks in compliance schedules.
* change `@` to `at`.
change me!

chore: change backup schedule to 24-hour clock

---

generated/api/v2/compliance_results_stats_service.swagger.json
generated/api/v2/compliance_rule_service.swagger.json
generated/api/v2/vuln_exception_service.swagger.json
make/protogen.mk

When v2 APIs were newly introduced, we did not want to document them right away before they were ready to become GA. So we created a list of v2 APIs that are ready to go in api docs so that only those APIs are exposed. Now that v2 APIs have existed since a couple of releases, we should change the implementation to allow all v2 APIs to be exposed in docs.
Verifying that all v2 APIs are present in API docs is enough
Manual verification

fix(be): Expose all v2 APIs in docs

---

roxctl/central/debug/authz_trace_test.go
roxctl/central/login/login_test.go
roxctl/central/m2m/exchange/exchange_test.go
roxctl/central/userpki/list/list_test.go

The PR is part of a PR split stack.
See #11772 description for more information
PR stack:
- #11772
- #11900 
- #11901 
- #11902 
- #11903 
- #11904 
- #11905 
Manual run of `go test -v` in each directory where a test was either created or modified

tests: Proto -> JSON serialization tests for roxctl other central cmds

---

pkg/auth/authproviders/registry_httphandler.go
pkg/auth/authproviders/registry_httphandler_test.go
pkg/auth/authproviders/serialized_test_auth_status.json
pkg/auth/user/util_test.go

The PR is part of a PR split stack.
See #11772 description for more information
PR stack:
- #11772
- #11900 
- #11901 
- #11902 
- #11903 
- #11904 
- #11905 
Manual run of `go test -v` in each directory where a test was either created or modified

tests: Proto -> JSON serialization tests for pkg/auth

---

PR_GA.md

ROX-25354: PR GA requirements document

---

central/metrics/central.go
central/metrics/init.go
central/pruning/pruning.go

This PR adds pruning metrics to measure time taken to prune the entities.
Ran scale tests to verify metrics are measured
Ran scale tests to verify metrics are measured

ROX-19731: Added duration metric for pruning images

---

.github/pull_request_template.md

Removes mutual exclusive items by conflating them. Hopefully this will further reduce the busy work filling out the template while keeping the reminding value.
It also reshapes the comment sections to cater for folks working from laptops. 
Verified that the template renders as I envision.

chore: Further simplify the PR template

---

tests/ca_setup_test.go
tests/e2e/lib.sh
tests/e2e/yaml/central-cr-midstream.envsubst.yaml
tests/e2e/yaml/central-cr-with-scanner-v4.envsubst.yaml
tests/e2e/yaml/central-cr.envsubst.yaml

This lets us run `TestCASetup` on OCP too, see one of the issues in ROX-24688.

tests: Propagate additional CA when using operator too.

---

pkg/auth/authproviders/registry_httphandler.go
pkg/auth/authproviders/registry_httphandler_test.go
pkg/auth/authproviders/serialized_test_auth_status.json
pkg/auth/user/util_test.go
roxctl/common/report/report_test.go
roxctl/image/check/check_test.go
roxctl/image/scan/scan_test.go
roxctl/scanner/downloaddb/downloaddb_test.go

The PR is part of a PR split stack.
See #11772 description for more information
PR stack:
- #11772
- #11900 
- #11901 
- #11902 
- #11903 
- #11904 
- #11905 
Manual run of `go test -v` in each directory where a test was either created or modified

tests: Proto -> JSON serialization tests for roxctl non-central cmds

---

go.mod
go.sum

This PR sets scanner dependency to correct commit in the `scanner` repo.
Didn't do any validation locally.
Commands used:
```
go mod edit -require=github.com/stackrox/scanner@9da484b1a94e9a990209d2bd63e63186bc8cba67
go mod tidy
```

ROX-22019: Set scanner dependency to protobuf V2 merge commit

---

tests/compliance_operator_test.go

I stumbled upon unintentionally using `namespace` when working on another test in the same package.
This new name will help prevent this.
While at it, also use consts rather than vars.
CI is enough.

test: less generic name, var->const

---

pkg/retry/retry.go
pkg/retry/retry_test.go

This will be used by [another PR](https://github.com/stackrox/stackrox/pull/11986), sending this out separately to reduce the size, as it's mostly independent.
Unit tests show this working, also works fine in the aforementioned PR.

feat: Add WithContext to retry package.

---

.tekton/central-db-build.yaml
.tekton/main-build.yaml
.tekton/operator-build.yaml
.tekton/roxctl-build.yaml
.tekton/scanner-v4-build.yaml
.tekton/scanner-v4-db-build.yaml

See https://github.com/stackrox/scanner/pull/1577
No changes to automated tests.
If Konflux CI runs in this PR, the change worked.

build: Add "appstudio" to the PR branch name filter for Konflux CI

---

scripts/ci/lib.sh

The function `check_rhacs_eng_image_exists` can also work in many situations without the bearer token.
change me!

ROX-24401:  Optional Quay token during operator bundle building

---

.github/renovate.json5

Context:
* https://redhat-internal.slack.com/archives/C079XCJEZK6/p1721759446936969
* https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1721809083784519
* https://github.com/stackrox/stackrox/pull/9787/files
No auto-tests changes.
Checked that the file passed renovate validation.
Checked regular expression with regex101.com
Not sure how it will work though.

chore: Try calm down Dockerfile Renovate-ion

---

migrator/main.go

Log migrator errors with stack trace so it will be easier to detect where it happened.
CI

ROX-25434: verbose migrator error logging 

---

central/main.go
pkg/features/feature.go
pkg/features/features.go
pkg/features/features_test.go
scanner/cmd/scanner/main.go
sensor/admission-control/main.go
sensor/kubernetes/main.go
sensor/upgrader/main.go

Add logging to our feature flag framework. Upon service start up, a log line such as this one is produced
```pkg/features: 2024/07/24 17:29:52.180003 features.go:82: Info: Feature flags [dev-preview] {"ROX_ACSCS_EMAIL_NOTIFIER": true, "ROX_ACTIVE_VULN_MGMT": false, "ROX_AGGREGATE_DEPLOYMENT_REFERENCE_OPTIMIZATION": false, "ROX_ATTEMPT_MANIFEST_DIGEST": true, "ROX_AUTH_MACHINE_TO_MACHINE": true, "ROX_CAPTURE_INTERMEDIATE_EVENTS": true, "ROX_CLUSTER_AWARE_DEPLOYMENT_CHECK": true, "ROX_COLLECTOR_RUNTIME_CONFIG": false, "ROX_COMPLIANCE_ENHANCEMENTS": true, "ROX_COMPLIANCE_HIERARCHY_CONTROL_DATA": true, "ROX_COMPLIANCE_REMEDIATION": true, "ROX_COMPLIANCE_REPORTING": true, "ROX_DEFAULT_FALSE": false, "ROX_DEFAULT_TRUE": true, "ROX_DELEGATE_WATCHED_IMAGE_REPROCESSING": true, …
```

ROX-25352: log feature flags

---

qa-tests-backend/src/test/groovy/SACTest.groovy

The default behavior when network flows are fetched is to fetch them for the last 5 minutes or so.
Code: https://github.com/stackrox/stackrox/blob/d78c1351fbf6ae8350e0fdc94d425081252705b0/central/networkgraph/service/service_impl.go#L263
The problem we are getting in tests is that the first request catches additional flows compared to the second. This change should use the same starting time, keeping the scope of included network flows "the same".
**Consideration**
We can face problems on the opposite side. New flows are created after the first request.
I'll let the CI pipeline run and validate the changes.

ROX-24184: Use fixed since time for fetching network flows in SACTest

---

deploy/common/deploy.sh

This PR is adding additional logging to investigate if failure is caused by request content.
Please take a look at the ticket for more details.
Nothing added - just improved logging for a test.

ROX-25476: Improve logging for failing test to see request content

---

ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx

As title states. Adds simple logic for now.

ROX-24747: Adding disclaimer banner to NG

---

pkg/features/options.go

chore: remove deprecation message from FF `enabled`

---

.github/workflows/build.yaml
.github/workflows/scanner-build.yaml

Putting the arm64 back into the default PR builds to support local deploys from Macbooks.  arm was removed from PR builds in #12041 
nothing to test really.

tests(CI): add arm64 back to PR builds

---

.tekton/scanner-v4-build.yaml
.tekton/scanner-v4-pipeline.yaml

Enable multiarch builds for scanner V4 on konflux.
The new workflow consists of building images for amd64 in the same way that was being done before these changes and using the buildah-remote bundle for ppc64le, s390x and arm64. Once built, a manifest is created for grouping all 4 images. On top of this, the needed konflux- tags area applied to all archs and a separate manifest is created for these.
This PR only changes konflux CI, no needed tests should be needed other than a successful build.
Ran the new workflows and checked quay to see all images and manifest have been successfully published.

ROX-20757: Enable konflux multiarch build for scanner v4

---

.tekton/basic-component-pipeline.yaml
.tekton/operator-build.yaml
.tekton/operator-bundle-build.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/roxctl-build.yaml

Enable multiarch builds for the basic-component-pipeline, which controls builds for:
- scanner-v4-db
- central-db
- roxctl
- stackrox-operator
The new workflow consists of building images for amd64 in the same way that was being done before these changes and using the buildah-remote bundle for ppc64le, s390x and arm64. Once built, a manifest is created for grouping all 4 images. On top of this, the needed `konflux-` tags area applied to all archs and a separate manifest is created for these.
This PR only changes konflux CI, no needed tests should be needed other than a successful build.
Ran the new workflows and checked quay to see all images and manifest have been successfully …

ROX-20757: Enable multiarch for basic-component-pipeline

---

qa-tests-backend/src/test/groovy/ProcessVisualizationTest.groovy

`Verify process visualization on default: #depName` fails due to some missing processes but those processes are later found in `Verify process paths, UIDs, and GIDs on #depName` and `Verify process arguments on #depName`. This suggest that the failures are due to timing issues. Increasing the waiting time for the processes to appear should fix the issue.
This is particularly flaky in aro. Running CI multiple times to verify the solution:
- Four green runs
- [1818232412014907392](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/12175/pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests/1818232412014907392) failed to create the cluster
- …

ROX-25292: Increase the timeout

---

ui/apps/platform/cypress/helpers/request.js
ui/apps/platform/cypress/helpers/tableHelpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/NodeCve.helpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeCvesOverviewPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/vulnerabilities.helpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/cveListExceptionFlow.test.js
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx

Adds tests for pagination to the Node CVE overview page.
CI

chore(ui): Node overview page pagination tests

---

migrator/OVERVIEW.md
migrator/README.md

Add a migration overview document to provide more color on migrations, compatibility, and testing them.  Subsequent documentation on best practices in configuring the schema will follow in separate PR or simply be provided in confluence.
Just adding a doc, none necessary.

ROX-25301:  Add a migration overview

---

go.mod
go.sum

Bump docker/docker to fix https://github.com/stackrox/stackrox/security/code-scanning/1444099 
change me!
change me!

chore(deps): bump docker/docker fix CVE 2024 41110

---

qa-tests-backend/src/test/groovy/IntegrationsSplunkViolationsTest.groovy

After additional sanity checks for Splunk have been introduced in #12090, we should update this test as well.
While working on it, I also bumped the grace times for both search queries, as we have found in testing that initial data ingestion can take a long time, depending on the Node load Splunk runs on.
This is a follow-up to #12090 and requires the changes from that to be merged. Until then it is not ready for review.
Local testing against an OpenShift 4 infra cluster, CI

ROX-25407: Stabilize Splunk Violation Test

---

.github/workflows/build.yaml
.github/workflows/scanner-build.yaml

We currently show all reported vulnerabilities, which leads to a total of 1.9k issues found. This is overwhelming, so this PR reduces the findings to critical and important severity.
Ran the roxctl command locally.

chore(ci): filter for high severity in code scanning

---

go.sum

Incidentally broke style in #12239 12239
change me!

fix: style after bumping docker/docker package

---

qa-tests-backend/src/main/groovy/objects/Notifiers.groovy

retry get on localhost?:8080 as from time to time we get connection reset exception.
CI

ROX-22854: retry get on localhost

---

migrator/README.md
tools/roxvet/analyzers/validateimports/analyzer.go

All is in the title. See the developer documentation in the updated migrator readme for more details.
This change introduces a roxvet rule, along with documentation. This should not require any automated tests.
Inroduced a feature flag in a migration, run roxvet against the codebase and check for reported violation.

ROX-25360: Prevent use of feature flags in migrations

---

go.mod
pkg/cloudproviders/aws/metadata.go
pkg/cloudproviders/aws/metadata_test.go

Migrate metadata package to AWS sdk v2.
```
roxcurl /v1/clusters | jq .
...
"providerMetadata": {
"region": "us-west-2",
"zone": "us-west-2d",
"aws": {
"accountId": "051999192406"
},
"verified": true,
"cluster": {
"type": "EKS",
"name": "sh-07-26-1",
"id": "arn:aws:eks:us-west-2:051999192406:cluster/sh-07-26-1"
}
...
```
change me!

chore: migrate metadata to aws v2

---

.github/renovate.json5

https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1721809083784519
No.
Passed validation.

chore: Print renovate config for debugging

---

scripts/ci/lib.sh

The message about starting pre-fetcher can be read as related to subsequent messages about checking whether images are built. Try and improve on this.
Example from `ocp-qa-e2e`:
```
INFO: Mon Aug  5 06:30:49 UTC 2024: Starting image pre-fetcher of pre-built images (NOT built for current commit)...
+ deploy
go: downloading github.com/stackrox/image-prefetcher/deploy v0.2.2
INFO: Mon Aug  5 06:30:56 UTC 2024: Using /go/src/github.com/stackrox/stackrox/.gotools/bin/deploy v0.2.2 for image prefetch deployment
make: Entering directory '/go/src/github.com/stackrox/stackrox/operator'
echo '{ "apiVersion": "v1", "kind": "Namespace", "metadata": { "name": "prefetch-images" } }' | /go/src/github.com/stackrox/stackrox/operator//hack/retry-kubectl.sh apply -f -
namespace/prefetch-images created …
```

tests: better messages about image pre-fetcher

---

operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml

This addresses the following important security recommendation:
```
Error: SIGMA.container_requesting_net_raw ([CWE-269](https://cwe.mitre.org/data/definitions/269.html)): [[#def6]](https://cov01.lab.eng.brq2.redhat.com/osh/task/625038/log/rhacs-operator-bundle-container-1.0.0-697/scan-results-all.html#def6) [important]
bundle/manifests/rhacs-operator.v1.0.0.clusterserviceversion.yaml:1411: Sigma main event: The Kubernetes container requests the `NET_RAW` capability, either explicitly or by default, granting access to the host's network interfaces.
bundle/manifests/rhacs-operator.v1.0.0.clusterserviceversion.yaml:1411: remediation: Explicitly remove the `NET_RAW` capability for a container by adding either `NET_RAW` or `ALL` to the `securityContext.capabilities.drop` list, avoid adding …
```

chore: drop ALL capabilities from operator pod

---

.github/workflows/scanner-dev-vuln-update.yaml
.github/workflows/scanner-release-vuln-update.yaml

Update Scanner dev vuln update pipeline to clear disk space. I also updated the release pipeline to call the job preamble
Not needed
This IS the test
This IS the test

fix(ci): clear disk space for scanner vulns

---

pkg/features/README.md

Added a few use cases.
Peer review.

ROX-25354: Feature flags `README.md` update

---

compliance/collection/auditlog/auditlog_impl.go
compliance/collection/auditlog/auditlog_impl_test.go
go.mod
go.sum

This is a fix for a rare possibility where the reader would read incomplete log lines. Spot once by a flake in a unit test.
1. Bump the `stackrox/tail` commit in `go.mod` to point to the new commit on the [stackrox/inotify-file-watcher](https://github.com/stackrox/tail/tree/stackrox/inotify-file-watcher) branch.
2. Make use of the new `CompleteLines`.
3. Minor: synchronize a unit test.
It seems to be too hard to reproduce and write a good test for this problem.

ROX-25574: bump `stackrox/tail` commit, use `CompleteLines` option

---

ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getAffectedNodes.json
ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodeCVEMetadata.json
ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodeCVESummaryData.json
ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodeVulnerabilities.json
ui/apps/platform/cypress/helpers/request.js
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/NodeCve.helpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/cveDetailPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeDetailPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/vulnerabilities.selectors.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/deploymentSingle.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx

Adds tests for the Node CVE single page based on common abstractions merged for the Node CVE overview page. Tests are roughly one test addition per commit in this PR.
Local cypress run, CI

chore(ui): Node CVE single page tests

---

pkg/features/list.go

Add feature flag for Policy as code. 
https://docs.google.com/document/d/1uoNXl2g1ALBfvKPyuQePASfgiuSjevw1ML68OJ8ihmM/edit#heading=h.bjfewz98ai7a
change me!

ROX-25656: Add feature flag for Policy-As-Code

---

sensor/common/centralclient/client.go

chore: sensor - use TrustInfo.UnmarshalVT over proto.Unmarshal

---

central/metadata/service/service_impl.go

chore: Metadata - use TrustInfo.MarshalVT instead of proto.Marshal

---

ui/apps/platform/cypress/fixtures/vulnerabilities/nodeCves/getNodeVulnerabilities.json
ui/apps/platform/cypress/helpers/tableHelpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/NodeCve.helpers.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeDetailPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx

Adds tests for the Node CVEs -> Node single page
Local Cypress run against staging, CI

chore(ui): Node single page tests

---

central/scannerdefinitions/handler/handler.go
central/scannerdefinitions/handler/handler_test.go

Recreation of https://github.com/stackrox/stackrox/pull/11836 to help improve the readability of the scannerdefinitions handler.

chore(central): rename vars/funcs in scannerdefs handler

---

ui/apps/platform/src/Components/CompoundSearchFilter/attributes/policy.ts
ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTableSearchFilter.tsx

This PR adds a multi-select dropdown for the Enforcement action filter in Policy Violations.

ROX-25330: Adding enforcement to the policy violations filter

---

tests/e2e/run.sh

A followup to #11875 where this one was missed.
Passing CI is enough.

tests: fix stale TODO ticket reference

---

.tekton/basic-component-pipeline.yaml
.tekton/determine-image-tag-task.yaml
.tekton/fetch-external-networks-task.yaml
.tekton/fetch-scanner-vuln-mappings-task.yaml
.tekton/main-pipeline.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml

Per title.
Goes after https://github.com/stackrox/stackrox/pull/12337
No change to automated tests.
Only CI (excluding EC).

ROX-25620: Update Konflux task repos

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.ts
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts

Regression test for https://github.com/stackrox/stackrox/pull/12366
change me!

test(ui): Apollo "fixed in" bug regression test

---

CHANGELOG.md
deploy/common/k8sbased.sh
pkg/renderer/kubernetes_test.go
pkg/renderer/templater.go
roxctl/central/generate/validate.go
roxctl/central/generate/validate_test.go
roxctl/central/generate/volumes.go
tests/roxctl/bats-tests/local/expect/flavor-interactive.expect.tcl

Remove central pvc from roxctl and rendering
I will add deprecation notice in the change log later.
change me!

ROX-25559: Remove central pvc from roxctl

---

deploy/common/k8sbased.sh
qa-tests-backend/scripts/run-compatibility.sh

ROX-25721: Ensure that central is deployed correctly via helm command

---

sensor/kubernetes/listener/resources/secrets.go
sensor/kubernetes/listener/resources/secrets_test.go

Backports https://github.com/stackrox/stackrox/pull/12188 to `release-4.4`

ROX-25526: Backport OCP 4.16 Scan Regression Fix to 4.4

---

central/scannerdefinitions/handler/handler.go

Recreation of both https://github.com/stackrox/stackrox/pull/11837 and https://github.com/stackrox/stackrox/pull/11841.
No

fix(central): bugfixes and readability updates for scannerdefs

---

.tekton/basic-component-pipeline.yaml
.tekton/main-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml

We only need a single deprecated-image-check execution if we pass the image manifest digest and URL.
https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1723738910783329
Passing Konflux pipelines.

ROX-25623: reduce deprecated-image-check by feeding manifest

---

sensor/kubernetes/listener/resources/secrets.go
sensor/kubernetes/listener/resources/secrets_test.go

Backports https://github.com/stackrox/stackrox/pull/12188 to `release-4.5`

ROX-25526: Backport OCP 4.16 Scan Regression Fix to 4.5

---

ui/apps/platform/src/constants/timeWindows.ts

The JSON <-> Protobuf conversion standard specifies that durations should be expressed in JSON as fractional seconds.
As long as the technical code infrastructure of the backend relied on protobuf and gRPC v1 (from a go ecosystem perspective), various duration string formats were supported.
With the migration away from the not-supported-anymore v1 ecosystem, the flexibility around the duration representation is going away.
This change aims at making the UI code send duration information to the backend in a format supported by the JSON Protobuf serialization standard.
TODO

ROX-25679: Use seconds in CVE suppression API calls

---

pkg/tlsutils/dial_context.go

Improve error message when dial fails.
From [CI logs](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/12281/pull-ci-stackrox-stackrox-master-ocp-4-12-scanner-v4-tests/1825465285704945664) of #12281:
```
```

refactor(roxctl): concealed error in `tlsutils`

---

pkg/scannerv4/client/client.go

Previously, `IndexAndScan` image called `GetOrCreateImageIndex`, which overwrote the `method` field in the logs.
Now, I created a `getOrCreateImageIndex` helper function which doesn't log things, so the method won't be overwritten anymore. This way, it's clearer which function was actually called.
No
Honestly, I didn't. Seems trivial (I'm sure I'll regret this later)

chore(scanner): refactor getOrCreateImageIndex for logging

---

central/notifiers/acscsemail/trigger.txt

Removes the trigger file used for testing the new emailsender <> central compatibility test.
Not necessary, only removed a trigger file

ROX-24936: remove trigger for emailsender test

---

qa-tests-backend/src/test/groovy/ProcessVisualizationTest.groovy

The `ldconfig` process expected in the `elasticsearch` container sometimes takes up to 10 minutes to get reported.
See this snapshot of the `process_indicators` table in centraldb:
This leads `Verify process visualization on default: #depName` to fail due to missing the `ldconfig` process when later is found in `Verify process paths, UIDs, and GIDs on #depName` and `Verify process arguments on #depName`. 
This PR ignores the `ldconfig` if we timeout waiting for it to be reported.
- ~~[ ] Trigger multiple runs in CI until we get one that skips `ldconfig`~~ 👈  I couldn't reproduce it in CI

ROX-25292: Ignore ldconfig if we timeout

---

central/sensor/service/service_impl.go
central/sensorupgrade/controlservice/service.go
go.mod
go.sum
pkg/centralsensor/legacy_caps.go
pkg/centralsensor/legacy_sensor_version_info.go
pkg/centralsensor/legacy_sensor_version_info_test.go
pkg/centralsensor/sensor_hello.go
pkg/grpc/authn/basic/extractor.go
pkg/grpc/authz/interceptor/interceptor.go
pkg/grpc/logging/logging.go
pkg/grpc/ratelimit/ratelimit.go
pkg/grpc/ratelimit/ratelimit_impl.go
pkg/grpc/ratelimit/ratelimit_impl_test.go
pkg/grpc/recovery.go
pkg/grpc/requestinfo/requestinfo.go
pkg/grpc/requestinfo/requestinfo_test.go
pkg/grpc/server.go
pkg/grpc/testutils.go
pkg/grpc/testutils/authz.go
pkg/grpc/util/stream.go
roxctl/central/export/images/images.go
roxctl/common/connection.go
sensor/common/compliance/service_impl.go
sensor/common/networkflow/service/service_impl.go
sensor/common/sensor/central_communication_impl.go
sensor/debugger/central/communicate_server.go

This PR upgrades grpc-middleware to new stable version v2.
CI

chore(grpc): upgrade middleware to v2

---

.github/workflows/emailsender-central-compatibility.yaml

Fix the wrong default branch name for emailsender-central-compatibility GH action from main to master
Also adds the emailsender-central-compatibility.yaml workflow file to the triggers.
Not necessary.

fix: change emailsender test to run on master push

---

central/metrics/central.go
central/metrics/init.go

Two published metrics are not maintained anymore and will be removed. A metrics for cached stores was added but not published in #8586 . This is now also corrected.
Existing CI should cover.
Build, deploy, query `/metrics` endpoint.

chore(cleanup): remove unmaintained metrics and publish missing one

---

central/cve/node/datastore/datastore.go
central/cve/node/datastore/datastore_impl.go
central/cve/node/datastore/datastore_impl_test.go
central/cve/node/datastore/mocks/datastore.go
central/cve/node/datastore/store/mocks/store.go
central/cve/node/datastore/store/store.go
central/pruning/pruning.go
central/pruning/pruning_test.go
central/pruning/singleton.go

This is the part-2 of a 3 part change to prevent immediate removal of orphaned Node CVEs.
Part-1 [#12283]: Added proto changes, generated store and datastore. Added environment variables to enable/disable these changes.
Part-2 [#12372]: 
- Updates node store implementation to mark orphaned CVEs and restore them when rediscovered.
- Updates GraphQL implementations to exclude orphaned CVEs
Part-3: Adds pruning job to periodically prune orphaned Node CVEs that have not been restored for a set duration. 
Unit tests and manual testing

Rox 25519: Part-3: Prune orphaned node CVEs

---

generated/internalapi/central/sensor_events_vtproto.pb.go
generated/internalapi/sensor/compliance_iservice_vtproto.pb.go

Fixes parallel changes to some proto and to the proto code generation.
In CI we trust.

fix: resolve parallel merge conflict (re-generate protos)

---

tests/upgrade/postgres_run.sh

This is part of the release process. This PR update the previous versions in upgrade test.
change me!

chore(e2e): Bump upgrade test 4.4 version to 4.4.5

---

migrator/migrations/m_206_to_m_207_add_default_policy_edge/schema/convert_policies.go
migrator/migrations/m_206_to_m_207_add_default_policy_edge/schema/convert_policy_categories.go
migrator/migrations/m_206_to_m_207_add_default_policy_edge/schema/convert_policy_category_edges.go

It looks like we do not have vtprotobuf in 4.5 and hence the fix.
change me!

fix(migrations): Fix a merge conflicts for policy category edge

---

.openshift-ci/README.md

Add documentation to access the running cluster and how to find build logs.

chore(docs): Add openshift-ci debug documentation

---

scanner/decisions/0011-separate-versioning-for-vuln-bundles.md

ADR to move away from bundle versions based on Stackrox releases into a separate version stream, bumped based on detect ClairCore changes.
N/A, ADR.
N/A, ADR.

doc(scanner): ADR: Versioning of vulnerability bundles

---

generated/storage/notifier_vtproto.pb.go

chore(fix): Update generated files

---

go.mod
go.sum

Backport 12356 to 4.5
change me!

chore(deps): bump github.com/docker/docker from 26.1.4 to 26.1.5

---

deploy/common/deploy.sh

The `generate_ca` function is not used anywhere.
Ran `./deploy/k8s/deploy-local.sh` and checked that the deployment worked.

chore(cleanup): remove unused code in deploy script

---

ui/apps/platform/package-lock.json

Updates all occurrences of micromatch 4.0.x to 4.0.8
CI

ROX-24270: update micromatch dependency

---

.github/workflows/scanner-dev-vuln-update.yaml
.github/workflows/scanner-versioned-definitions-update.yaml
.github/workflows/scripts/scanner-get-released-tags.sh
.github/workflows/scripts/scanner-output-release-versions.sh
scanner/updater/version/VULNERABILITY_BUNDLE_VERSION

The original dev workflow has been changed to versioned definitions update workflow and it should consume `scanner/updater/version/VULNERABILITY_BUNDLE_VERSION` file and generate versioned bundles
I created `.github/workflows/scripts/scanner-get-released-tags.sh` because I suspect `scanner-release-output-versions.sh` won't be needed as we will change `scanner-release-vuln-update` workflow in the future. 
`.github/workflows/scripts/scanner-get-released-tags.sh` is based on `scanner-release-output-versions.sh` , and it reads new `scanner/updater/version/VULNERABILITY_BUNDLE_VERSION`
Note: the PR-triggered bundle run is removed since the workflow is updated to matrix steps. Let me know if we want to keep that. 
change me!

ROX-25687: versioned definitions update workflow

---

ui/apps/platform/package-lock.json

Updates `async` to latest patch version.
devDependency - validate CI run

ROX-25230: update async dep

---

ui/yarn.lock

Backport of async 3.2.0 => 3.2.6 fix.
Dev dependency - validate CI

fix(ui): [Backport] Update UI 'async' dependency

---

ui/yarn.lock

Backports the upgrade of async 3.2.0 => 3.2.6 to 4.4
Verify CI run

fix(ui): [Backport] Update UI async dependency

---

pkg/features/list.go

Fixing enablement for the latest feature flags

fix(ui): Fixing feature flag enablement

---

.github/actions/junit2jira/action.yaml
.github/workflows/unit-tests.yaml

tests: do not mention on known CI failures

---

Makefile

https://github.com/stackrox/stackrox/pull/12548 updated the go version to 1.22. This version updates the builder image version for non-x86_64 builds.
Built sackrox locally with `make image`.

chore: update builder image for non-x86_64 builds to golang:1.22

---

ui/yarn.lock

Reverts a commit that was not intended for 4.5.2
change me!

fix(ui): Revert async update commit

---

.github/workflows/scanner-versioned-definitions-update.yaml

Fixed nvd artifacts download path
Use fully qualified path to refer to the NVD bundle
https://github.com/stackrox/stackrox/actions/runs/10838504222/job/30076913763
https://console.cloud.google.com/storage/browser/scanner-v4-test/vulnerability-bundles/yli3-fixNVDExporting
```
***"level":"debug","bundle":"nvd","component":"libvuln/updates/NewManager","factory":"nvd","time":"2024-09-12T21:04:50Z","message":"factory unconfigurable"***
***"level":"info","bundle":"nvd","component":"enricher/nvd/Enricher/Configure","feed_path":"/__w/stackrox/stackrox/nvd.zip","time":"2024-09-12T21:04:50Z","message":"enricher configured with feed path"***
***"level":"info","bundle":"nvd","component":"libvuln/updates/Manager.Run","total":1,"batchSize":4,"time":"2024-09-12T21:04:50Z","message":"running updaters"*** …
```

fix: NVD exporting in versioned bundle updates

---

image/templates/CHANGING_CHARTS.md

chore(docs): Add secret path to CHANGING_CHARTS docs

---

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/useNodeVulnerabilities.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/useAffectedNodes.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodeCves.ts
ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodes.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/useClusterVulnerabilities.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/ClustersTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/usePlatformCves.ts
ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/useAffectedClusters.ts
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageResources.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageResources.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
ui/apps/platform/src/services/AdministrationEventsService.ts
ui/apps/platform/src/services/ReportsService.ts

Refactors the UI code to use our existing `getPaginationParams()` helper utility to calculate page size, offset, and sort options before sending requests over the API.
This is a prerequisite to implementing multiple sort options over the API because it will allow a single point of change when the possible values returned by the `useURLSort()` hook are widened to support multiple sort options.
However, this change is beneficial on its own as it removes duplicate logic from 20+ places and uses the identical logic that was established in the helper function. This logic has been the source of multiple bugs when it was not implemented correctly or copy-pasted from an incorrect implementation.
For reference, here is the source of the `getPaginationParams()` helper that is being used:
```js …
```

chore(ui): Use standard pagination parameter utils throughout

---

central/sensorupgrade/service/service_impl.go

Remove extra log forgotten in https://github.com/stackrox/stackrox/pull/12150
I haven't

chore(cleanup): Remove extra logging

---

pkg/scannerv4/mappers/mappers.go
pkg/scannerv4/mappers/mappers_test.go

* Replace regexp checks with prefix checks for efficiency
* identify OSV vulns that have non-CVSS severities early for better logging
CI

chore: minor mappers improvements

---

scripts/ci/jobs/gke_nongroovy_compatibility_tests.py

Adds  a dummy target for gke-nongroovy-compatibility-tests that CI can call.
None. This same target already exists in our master branch

ROX-25183: Dummy compatibility target for release-x.y

---

CHANGELOG.md

ROX-26293: Add CHANGELOG for Microsoft Sentinel

ROX-26293: Add CHANGELOG for Microsoft Sentinel

---

tests/upgrade/postgres_run.sh

chore(upgrade): Bump 4.5 previous version in upgrade test to 4.5.2

---

central/graphql/resolvers/image_cve_core.go
central/views/imagecve/db_response.go
central/views/imagecve/mocks/types.go
central/views/imagecve/types.go
central/views/imagecve/view_impl.go
central/views/imagecve/view_test.go
central/views/read_options.go

This PR adds publish date field to imageCVEs query so UI can display  publish date in Workload CVEs table
Testing:
Made get query in graphiql to test the query response. see screenshot attached
change me!

ROX-24581 : Changes to add publish date to  imageCVEs query

---

go.mod
go.sum
tests/roxctl/bats-tests/local/roxctl-netpol-connectivity-diff-development.bats
tests/roxctl/bats-tests/local/roxctl-netpol-connectivity-diff-release.bats

See #12686 
This PR aims at easing the test run.
In CI we trust.

chore(deps): np-guard/cluster-topology-analyzer/v2 from 2.2.1 to 2.3.0

---

central/telemetry/centralclient/instance_config.go
central/telemetry/centralclient/interceptors.go
pkg/telemetry/phonehome/request_params.go
pkg/telemetry/phonehome/request_params_test.go

In addition to the API paths, let's allow for tracking specified user agents.
The `ROX_TELEMETRY_USERAGENT_LIST` variable is used to define a list of sub-strings to look the `User-Agent` header value for.
Debug log on Segment with default settings captured an 'API Call' event with:
```json
"properties": {
"Code": 200,
"Method": "GET",
"Path": "/v1/auth/status",
"User-Agent": "Rox Central/4.6.x-586-g3c6b5b6b82 (linux; amd64) grpc-go/1.65.0 ServiceNow/1.0"
}
```

ROX-26351: Track API Calls with specified user-agents

---

pkg/auth/authproviders/oidc/backend_impl.go
pkg/auth/authproviders/oidc/wrappers.go

When debugging why a private OIDC provider would not work with ACS even in `fragment` mode ([RFE-6357](https://issues.redhat.com/browse/RFE-6357)), I noticed that Central would not emit any logs despite the UI erroring with "provider creation timeout". This is because UI's timeout to backend is much shorter than backend's timeout to the IdP so essentially UI cancels the request before it can fail on the backend.
This PR logs before and after OIDC provider creation to make it clear in the logs how far we went. And since we touch this, it does not harm to print which issuer URL is being queried and hence succeeds since this might affect the overall timeout.
CI run; only logs change.

chore: Add logs to help debug oidc provider creation

---

image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml
image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl
image/templates/helm/stackrox-secured-cluster/templates/collector.yaml.htpl

Inconsistent style spotted by @SimonBaeumer ++
CI should be enough. According to @SimonBaeumer this is still behind feature flag which customers cannot flip.

chore(helm): Make runtime_config camel case.

---

central/search/service/service_impl.go
central/search/service/service_impl_test.go

The autocomplete searcher first queries the database to get 10 matches, then removed duplicates from those matches. If there are too many duplicates, this results in autocomplete ultimately returning fewer matches. This PR increases the number of results queried from db to 100. This is chosen as a reasonably large limit to increase the chances of returning 10 suggestions after removing duplicates. If we still find a lot of duplicates, then we just return what we have. This may not be the best solution but we also want to return in a reasonable time.
Existing unit tests for the search service should be sufficient for this trivial change.
Manual testing

ROX-26300: Increase pagination limit to try to get more unique autocomplete results

---

migrator/migrations/m_206_to_m_207_add_default_policy_edge/schema/convert_policies.go
migrator/migrations/m_206_to_m_207_add_default_policy_edge/schema/convert_policy_categories.go
migrator/migrations/m_206_to_m_207_add_default_policy_edge/schema/convert_policy_category_edges.go

There are concurrent changes between proto framework upgrades and migration creation.
The point is to merge the evolutions to a point that the cleanup PR for the proto framework upgrade can be merged
In CI we trust

chore(proto): migrate new migration to UnmarshalVTUnsafe

---

central/graphql/handler/handler.go
central/ui/mux.go
pkg/grpc/server.go

The security posture of the UI can be improved by adding HTTP headers to the response.
Here we add a few recommended values to the UI HTTP response headers.
Deploy, Open the stackrox UI, check the returned headers.

ROX-21381: Add security headers to UI mux

---

.tekton/operator-bundle-pipeline.yaml
.tekton/retrieve-image-tag-from-file-task.yaml
operator/bundle_helpers/patch-csv.py
operator/konflux.bundle.Dockerfile

Pin all the related images.
This is purely a CI change.
Just a CI change.

ROX-26151: Pin related images in operator bundle

---

central/convert/storagetov1/cloud_source.go
central/convert/storagetov1/cloud_source_test.go
ui/apps/platform/src/Containers/Integrations/Banners/OcmDeprecatedToken.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationTiles/IntegrationTilesPage.tsx

Create a banner on the integrations page if an OCM integration with the deprecated API token field (`credentials.secret`) has been configured. If no such integration is found, no banner is shown.
Depends on https://github.com/stackrox/stackrox/pull/12277 and https://github.com/stackrox/stackrox/pull/12333.
see screenshots

ROX-24169: deprecation banner

---

ui/apps/platform/src/Components/ReportJob/MyLastJobStatus.test.tsx
ui/apps/platform/src/Components/ReportJob/MyLastJobStatus.tsx
ui/apps/platform/src/Components/ReportJob/ReportJobsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportRunStatesFilter.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/hooks/useWatchLastSnapshotForComplianceReports.ts
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/JobDetails.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobStatus.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useRunReport.ts
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.test.ts
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.ts
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts
ui/apps/platform/src/services/ReportsService.ts
ui/apps/platform/src/services/ReportsService.types.ts
ui/apps/platform/src/types/reportJob.ts

This PR will change the column "My active job status" to "My last job status" for Compliance.

feat(ui): Adding 'My last job status' to Compliance

---

sensor/common/compliance/service_impl.go
sensor/common/compliance/service_impl_test.go

We need to lock before adding to the `stoppers` Set as `Communicate` can be called concurrently.

ROX-26378: Lock before adding to map

---

central/notifier/service/service_impl.go
central/notifiers/microsoftsentinel/sentinel.go
central/notifiers/microsoftsentinel/sentinel_test.go
central/notifiers/utils/encryption.go
central/notifiers/utils/encryption_test.go
dev-tools/create-notifier-secret.sh
dev-tools/debug-helm-chart.sh
generated/api/v1/notifier_service.swagger.json
generated/storage/notifier.pb.go
image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl
proto/storage/notifier.proto

ROX-26408: Encrypt Microsoft Sentinel Notifier Secret
change me!
- Added unit tests

ROX-26408: Encrypt Microsoft Sentinel Notifier Secret

---

central/globaldb/postgres.go

The original implementation was borrowed from wiki [[1]], but the query there was designed to work even with ancient versions of PostgreSQL. Since PostgreSQL 12 there is pg_partition_tree that simplify things a bit. Use it and reshare the query slightly for better readability.
[1]: https://wiki.postgresql.org/wiki/Disk_Usage
I've created tables from both old and new queries and compared the results to make sure they're the same:
```sql
SELECT * FROM (
SELECT
n.table_name,
n.rows_estimate - o.row_estimate AS diff_rows,
n.total_bytes - o.total AS diff_total,
n.indexes_bytes - o.index AS diff_index,
n.toast_bytes - o.toast AS diff_toast
FROM table_size_new n
JOIN table_size_old o
ON n.table_name = o.table_name) q
WHERE
q.diff_rows != 0 OR
q.diff_total != 0 OR
q.diff_index != 0 OR …
```

ROX-25642: Simplify the table size query

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ProfileStatsWidget.tsx

Ensure compliance stats widget bar chart values add up to 100%
This addresses the issue of rounding errors when summing percentages across different statuses. Since rounding can introduce small deviations, adjustments are made to ensure the total percentage always adds up to 100%.
The key concept here is that the **maximum deviation when rounding is ±0.5 x n** (number of statuses). In our case, since there are 4 statuses, the max deviations can be up to 2%.
Considered solutions:
1. **Adjust based on lowest absolute error**: This approach would adjust the bar that deviates the least from its raw percentage when rounded.
2. **Adjust based on lowest relative error**: This would adjust the bar that has the smallest proportional error relative to its original value.
3. **Adjust based on …

ROX-25760: Compliance stats should add to 100%

---

ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/CloudSourceIntegrations/OcmIntegrationForm.tsx

OCM introduced new basic read permissions for all service accounts. This makes additional permissions not needed anymore.
change me!

chore(ui): remove hint for sub viewer role

---

image/templates/helm/stackrox-secured-cluster/templates/collector.yaml.htpl

Adds a ConfigMap for collector. This ConfigMap is optional so that collector can run without it. Changes will be made to collector to read the runtime configuration from the ConfigMap in this [PR](https://github.com/stackrox/collector/pull/1878). This is part of the [epic](https://issues.redhat.com/browse/ROX-22981) to control collector features at runtime.
Created the following yaml file for a ConfigMap
```
apiVersion: v1
kind: ConfigMap
metadata:
name: collector-config
namespace: stackrox
data:
config.json: |
{
"networkConnectionConfig": {
"enableExternalIps": true
}
}
```
Saved the contents in config-map.yml.
Ran
```
kubectl create -f config-map.yml
```
Deployed ACS on a GKE infra cluster using `deploy/deploy-local.sh`.
Changed the collector image from one obtained from …

ROX-26515: Add a configmap to collector

---

.tekton/basic-component-pipeline.yaml
.tekton/main-pipeline.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml

See commit descriptions.
No automated testing.
Only CI.

chore: Update Konflux pipelines

---

.github/workflows/build.yaml

Disabling arm64 main builds, because they are broken: repodata for pg13 is missing for rhel8-arm64.
- https://redhat-internal.slack.com/archives/C3W3U0RGW/p1728469303271559
- example failed build: https://github.com/stackrox/stackrox/actions/runs/11265155268/job/31326837015
- Bug Report: https://www.postgresql.org/message-id/18650-0608adc985c84965%40postgresql.org
Main image is built and CI passes.

fix: temporarily disable arm64 main build

---

scripts/ci/get-slack-user-id.sh

@parametalol
Let's see in Slack.

chore: add the new Michaël's GitHub to Slack user mapping

---

central/scannerdefinitions/handler/handler.go
central/scannerdefinitions/handler/handler_test.go

This PR modifies Central definition/vulnerability handlers to the ingest offline vulnerability data bundles that are versioned. Previously, bundles were tied to StackRox release versions, but with this change, they are now independently versioned via a separate bundle version stream. Also, this support latest bundles with multiple definitions version for V4, enabling the use-case of single latest bundles for all supported releases.
1. Adjustments to how versions are validated;
2. Handling of multiple definitions files the latest ZIP bundles for both Scanner V2 and V4 definitions.
3. Improved error handling for version mismatches and unsupported bundles.
4. Refactored functions for opening and validating bundles, aiming to make the code more resilient to future changes in ZIP structures.
- …

ROX-25691: Update offline bundle handlers for version bundles

---

central/complianceoperator/v2/pipelines/complianceoperatorresultsv2/pipeline.go
central/complianceoperator/v2/pipelines/complianceoperatorresultsv2/pipeline_test.go
central/complianceoperator/v2/pipelines/complianceoperatorscansv2/pipeline.go
central/complianceoperator/v2/pipelines/complianceoperatorscansv2/pipeline_test.go
central/complianceoperator/v2/report/manager/manager.go
central/complianceoperator/v2/report/manager/manager_impl.go
central/complianceoperator/v2/report/manager/manager_test.go
central/complianceoperator/v2/report/manager/mocks/manager.go
central/complianceoperator/v2/report/manager/singleton.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher_test.go
go.mod

Adds the logic to identify when a scan has started and completed. This is necessary for the accurate reporting of compliance 2.0

ROX-26447: Add scan watcher

---

ui/apps/platform/cypress/integration/integrations/cloudSourcesIntegrations.test.ts
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/CloudSourceIntegrations/OcmIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/CloudSourceIntegrations/PaladinCloudIntegrationForm.tsx

Handle credential testing similar to other integrations:
* default to test credentials on save.
* add a check box for disabling the testing.
see screenshot

feat(ui): add checkbox for cloud source test

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsPage.tsx

By request of PM and UX, we will be adding a banner to schedules page that will say the following:
"Reporting is only available for clusters running Compliance Operator v.1.6 or newer"
NOTE: You can hide whitespace to see a cleaner code diff

ROX-26622: Adding a banner to the scheduling page

---

roxctl/common/auth/token_test.go
roxctl/common/environment/environment-impl.go
roxctl/common/environment/environment-impl_test.go
roxctl/common/flags/api_token_file.go
roxctl/common/flags/password.go
roxctl/maincommand/command.go
tests/roxctl/token-file.sh

Improving handling of the `password` and `token-file` CLI parameters: give preference to the arguments when environment variables are set.
Previously `roxctl` would complain:
```console
me@work$ ROX_API_TOKEN_FILE=tokenfile roxctl central whoami -p password
ERROR:	determining auth method: cannot use basic and token-based authentication at the same time
```
```console
me@work$ roxctl central cert --password abc --token-file xyz
ERROR:	if any flags in the group [password token-file] are set none of the others can be; [password token-file] were all set
me@work$ ROX_ADMIN_PASSWORD=wrong roxctl central whoami --password good
UserID:
admin
...
me@work$ ROX_ADMIN_PASSWORD=wrong roxctl central whoami --token-file tmp/token
UserID:
auth-token:485e1468-df27-4a92-b480-c18b8ecfe8cb
...
me@work$ …
```

chore(roxctl): `password` and `token-file` args

---

generated/api/v1/network_graph_service.swagger.json

#12689 did not update the generated files appropriately. This PR fixes that.

fix(generated): update stale generated files

---

config-controller/api/v1alpha1/policy_types.go
config-controller/config/crd/bases/config.stackrox.io_securitypolicies.yaml
image/templates/helm/stackrox-central/templates/00-securitypolicies-crd.yaml

`kubectl get securitypolicy` becomes: `kubectl get sp`

feat: Add short name 'sp' to SecurityPolicy

---

ui/apps/platform/src/Components/ReportJob/MyLastJobStatusTh.tsx
ui/apps/platform/src/Components/ReportJob/ReportJobsTable.tsx
ui/apps/platform/src/Components/TableStateTemplates/TbodyUnified.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/hooks/useWatchLastSnapshotForComplianceReports.ts
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts
ui/apps/platform/src/utils/getTableUIState.test.ts
ui/apps/platform/src/utils/getTableUIState.ts

This PR includes some tweaks to the Compliance Reporting code to make things work. The backend fixes are still in progress so the filters don't 100% work yet. The `completedAt` time is still null too. Hoping backend fixes those soon, but the UI is in place. 
https://github.com/user-attachments/assets/d6895a96-15ac-4699-bf73-f14129796ffa

fix(ui): Backend integration for compliance reporting

---

ui/apps/platform/src/Components/ReportJob/ReportJobsTable.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/hooks/useDeleteDownloadModal.ts
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts

This PR includes some final tweaks to the Compliance Reporting code to make things work. 
https://github.com/user-attachments/assets/ea0ef0f8-1bb1-421d-8ad6-5653f534acb1

fix(ui): Delete downloadable report

---

central/processbaseline/service/service_impl.go
tools/roxvet/analyzers/validateimports/analyzer.go

This is a PR to perform e2e tests for external contribution PR #12898 

fix(slice): fix slice init length

---

pkg/scanners/scannerv4/convert.go
pkg/scanners/scannerv4/convert_test.go

EmbeddedVulnerability should include all CVSS scores
```
make cli_darwin-amd64
./bin/darwin_amd64/roxctl helm output central-services --image-defaults=development_build --debug-path=./image --debug --remove
export KUBECONFIG=<kubeconfig path from downloaded infra artifacts>
vals_dir=<path to dir holding helm values files>
helm upgrade --install -n stackrox stackrox-central-services --create-namespace ./stackrox-central-services-chart \
-f "$vals_dir/central_values.yaml" -f "$vals_dir/secret_values.yaml"
```
I had to set `export ROX_NVD_CVSS_UI=true` which is a temporary env var.

ROX-26097: Add CVSS metrics to EmbeddedVulnerabilities

---

pkg/features/list.go

Enable Microsoft Sentinel feature flag by default.

ROX-26295: Enable ROX_MICROSOFT_SENTINEL feature flag by default

---

ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
ui/apps/platform/src/Containers/Violations/types.ts

This PR adds an "Attempted" tab to Policy Violations to prevent an accidental regression. See the following thread for more information: https://redhat-internal.slack.com/archives/C7ERNFL0M/p1729175069739059 
I noticed that the Resolved and Attempted tabs still show the table actions, so this PR will also include conditional logic to hide those actions depending on the Violation State.

ROX-26673: Adding Attempted tab to Policy Violations

---

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveListExceptionFlow.test.js

These tests expect there to be two CVEs to complete the flow of deferring multiple CVEs in a single request.
Skipping for now to avoid persistent failures during the release, and we will need to determine an alternate approach after 4.6 is cut.
CI

ROX-20891: Skip e2e tests that rely on multi-CVE images

---

central/complianceoperator/v2/report/manager/complianceReportgenerator/report_gen_impl.go

Adds rationale and instructions to the CSV report.
- Example Report: 
[StackRox_test_scan_21_October_2024.zip](https://github.com/user-attachments/files/17458851/StackRox_test_scan_21_October_2024.zip)

feat(report): Add rationale and instructions to the csv report

---

.github/actions/junit2jira/action.yaml
scripts/ci/lib.sh

Bump to version which supports CSV export from recursive testsuite as emitted by kuttl.
The change from previous version is unit-tested in the junit2jira repo, but here:
FTR, `shell-unit-tests` had this line in its log near junit2jira invocation, but it's also the case on current `master`:
```
ServiceException: 401 Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).
```

chore(junit2jira): bump vesrion

---

pkg/features/list.go

Enable feature flag by default
Successful CI is enough

ROX-26722: Enable platform components feature flag

---

central/graphql/resolvers/clusters.go
central/graphql/resolvers/clusters_postgres_test.go
central/graphql/resolvers/clusters_test.go
central/graphql/resolvers/compliance.go
central/graphql/resolvers/compliance_test.go
central/graphql/resolvers/gen/main.go
central/graphql/resolvers/generated.go
central/graphql/resolvers/scope_object_test.go
central/role/sachelper/cluster.go
central/role/sachelper/sachelper.go
ui/apps/platform/src/queries/controls.js

This change is the combination of the two following PRs without the SAC helper refactoring part:
* #13055
* #13056 
See the referenced PRs
#13055
#13056

chore(graphql): Compliance dashboard without cluster read permission

---

central/complianceoperator/v2/scanconfigurations/service/convert.go
central/complianceoperator/v2/scanconfigurations/service/service_impl.go
central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go
central/complianceoperator/v2/scanconfigurations/service/singleton.go

Implement the API endpoints to retrieve the report history.

ROX-26594: Implement GetComplianceReport API

---

central/complianceoperator/v2/report/manager/complianceReportgenerator/report_gen.go
central/complianceoperator/v2/report/manager/complianceReportgenerator/report_gen_impl.go
central/complianceoperator/v2/report/manager/complianceReportgenerator/singleton.go
central/complianceoperator/v2/report/manager/complianceReportgenerator/type.go
central/complianceoperator/v2/report/manager/manager.go
central/complianceoperator/v2/report/manager/manager_impl.go
central/complianceoperator/v2/report/manager/manager_test.go
central/complianceoperator/v2/report/manager/mocks/manager.go
central/complianceoperator/v2/scanconfigurations/service/convert.go
central/complianceoperator/v2/scanconfigurations/service/download.go
central/complianceoperator/v2/scanconfigurations/service/download_test.go
central/complianceoperator/v2/scanconfigurations/service/service_impl.go
central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go
central/complianceoperator/v2/scanconfigurations/service/singleton.go
central/main.go
central/reports/common/blob.go

Implement the download report logic

ROX-26451: Implement report download

---

sensor/common/registry/lazy_tls_image_registry.go

Reduces the scope the read lock is held by the lazy registry to reduce contention.
Routines waiting for the write lock were not given priority over routines waiting for the read lock as expected.  Instead what was observed was routines were occasionally 'alternating' such that after the write lock was released the read lock was obtained even when other routines were waiting for the write lock.
The `.Metadata` call behind the read lock was taking ~2 seconds, the read/write lock alternating would eventually trigger the non-release build mutex timeout because the routines waiting for the write lock would have to wait for multiple Metadata calls before they were allowed to enter the write protected block.  Over time this would have self corrected, but this change should reduce that …

ROX-26720: Reduce read lock scope

---

CHANGELOG.md

The endpoint `v2/compliance/scan/configurations/reports/run` method has changed from `PUT` to `POST`.
This just an entry in the changelog

chore(changelog): Add entry regarding reports run method change

---

pkg/features/list.go

Wait until Surabhi says merge.
CI

ROX-26689: Turn on ROX_NVD_CVSS_UI feature flag

---

central/complianceoperator/v2/report/manager/complianceReportgenerator/report_gen_impl.go
central/complianceoperator/v2/report/manager/complianceReportgenerator/report_gen_impl_test.go
central/complianceoperator/v2/report/manager/manager_impl.go
central/complianceoperator/v2/report/manager/manager_test.go
central/complianceoperator/v2/report/manager/singleton.go
central/complianceoperator/v2/report/manager/utils/errors.go
central/complianceoperator/v2/report/manager/utils/snapshot.go
central/complianceoperator/v2/report/manager/watcher/scanconfigwatcher.go
central/complianceoperator/v2/report/manager/watcher/scanconfigwatcher_test.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher_test.go
central/complianceoperator/v2/scanconfigurations/service/service_impl.go
central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go
central/main.go
pkg/env/compliance_operator.go
pkg/features/list.go

Improvements and bug fixes for compliance reporting.
- Stop using Sensor's pipeline's context in the reporting logic. This is because if sensor disconnect the context will be cancelled and all the watcher will stop.
- Add more granularity in the scan watcher's error handling.
- Add env vars to modify the scan watcher's timeouts.
- Ignore rogue scans (scans that are not created by ACS) since we cannot report on them.
- If a scanconfig watcher receives a duplicated scan do not error just override the previous scan if the `startedAt` field is newer. Otherwise ignore the scan.
- Enable the FF.
Note to reviewers: Reviewing the PR commit by commit might be easier.

fix(reporting): Compliance reporting improvements

---

govulncheck-allowlist.json

These vulnerabilities were resolved after https://github.com/stackrox/stackrox/pull/12548 was merged.

chore(vulns): update vuln list

---

.tekton/central-db-build.yaml
.tekton/main-build.yaml
.tekton/operator-build.yaml
.tekton/operator-bundle-build.yaml
.tekton/roxctl-build.yaml
.tekton/scanner-v4-build.yaml
.tekton/scanner-v4-db-build.yaml

See https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1730108686767279
No change to automated tests.
The approach was validated beforehand (see the Slack thread).
After merging this, I'll try re-triggering on `master` but it is only possible after merging.

ROX-26765: Rename pipelineruns to enable on-push rerunning

---

pkg/secrets/scrub_test.go

Extend the type coverage of the `scrub` annotation validation to more generated proto types.
manual run of the altered unit test.

tests: validate scrub annotation on more proto types

---

config-controller/api/v1alpha1/policy_types.go

fix(be): Remove validation:required from policy description

---

.github/workflows/scripts/scanner-offline-bundle-matrix.sh
scanner/updater/version/VULNERABILITY_BUNDLE_VERSION

chore(scanner): Pin point v2 vuln schema to 4.6.0

---

sensor/common/centralclient/client.go

Turns the warning into an error and makes it much more visible in the log. Style similar to other ASCII demarcations in logs.
Manually tested that the error appears and confirmed that it looks good in the logs.
Screenshots of how this looks in k9s / bash

ROX-26093: Improve sensor behavior when using wrong init bundle

---

.github/workflows/build.yaml

Disabling job per #11296 and the decision captured in the google doc referenced in that PR.
change me!

chore(job): disable scan job

---

CHANGELOG.md

chore(changelog): Update CHANGELOG.md

---

tests/delegated_scanning_test.go

To reduce CI flakes: Adds retries to delegated scanning e2e tests when a timeout occurs executing an 'ad-hoc' delegated scan.
CI

ROX-26663: Delegated Scanning e2e - add retries on timeout

---

operator/Makefile

Fixes a test setup failure on `release-4.4` branch:
- in this branch OLM is not properly pinned
- [latest release of OLM](https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/v0.29.0) is broken and effectively retracted
- On `master` and `release-4.5` OLM is already pinned in https://github.com/stackrox/stackrox/pull/11049
I'm just using a fixed version here from the same era as the pinned operator-sdk version used in this branch. For this legacy branch there is no point using a more `go.mod`-based pinning scheme like in the aforementioned change.
CI is enough.

chore(oprerator): Pin OLM version.

---

.tekton/basic-component-pipeline.yaml
.tekton/main-pipeline.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml

I apply some changes I spotted while diffing our old pipelines with the new freshly generated ones.
I suggest reviewing it by PRs because I tried making commits self-describing.
No automated testing changes.
Only CI.

build: Update Konflux pipelines

---

ui/yarn.lock

Updates dompurify for 4.4. A similar fix to `master` as seen here https://github.com/stackrox/stackrox/pull/13196 but using `yarn` for package management.
Smoke test of embedded redoc docs as described here https://github.com/stackrox/stackrox/pull/13196

ROX-26834: Update dompurify

---

ui/yarn.lock

Updates to the latest DOMPurify against 4.5 with the `yarn` package manager.
Manual test of embedded redoc docs as described here https://github.com/stackrox/stackrox/pull/13196

ROX-26833: Update dompurify

---

sensor/kubernetes/certrefresh/securedcluster/cert_repo_init.go

This PR fixes a small mistake in the naming scheme of the new secured cluster certificates.
The affected code is not used yet, so there are no backwards compatibility issues.
Existing tests are sufficient.

ROX-25948: Fix Scanner-V4 DB secret name

---

pkg/features/list.go

This feature flag was never used.

chore: Remove compliance hierarchy flag

---

sensor/kubernetes/certrefresh/localscanner_tls_issuer.go
sensor/kubernetes/certrefresh/localscanner_tls_issuer_test.go
sensor/kubernetes/certrefresh/tls_issuer_common.go
sensor/kubernetes/certrefresh/tls_issuer_common_test.go

This PR only moves code from `localscanner_tls_issuer*` to `tls_issuer_common*`, to make reviewing https://github.com/stackrox/stackrox/pull/13229 easier.
The follow-up PR will introduce a new TLS issuer, and this code is shared by both.
Existing tests are sufficient, I just moved code in a different file in the same package.

ROX-26719: Extract common TLS issuer code

---

ui/apps/platform/package-lock.json

Updates `yaml` 1.x and 2.x to the latest compatible versions.
The `yaml` dependencies are used in two places: monaco editor display of YAML files and the Redoc API docs. Smoke test of both instances:

chore(ui): Update yaml dependencies in UI

---

central/externalbackups/plugins/gcs/gcs.go
central/externalbackups/plugins/s3/s3.go
central/externalbackups/plugins/s3compatible/s3compatible.go
pkg/administration/events/codes/codes.go
pkg/administration/events/domain.go
pkg/administration/events/resources/resources.go
pkg/logging/fields.go
ui/apps/platform/src/services/AdministrationEventsService.ts

This PR enables administration events for external backup integrations. I've also aligned some of the code and error behavior between the three existing backup types. 
see screenshot above

feat: enable admin events for backups

---

sensor/common/awscredentials/registry.go
sensor/common/awscredentials/registry_test.go

`aws-sdk-go` has been deprecated and will be removed eventually (see https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/). This is the last package to migrate from `aws-sdk-go` to `aws-sdk-go-v2` (S3 backup is staying on v1 intentionally).
I also added a client timeout and proxy setup to the AWS config.
I verified that ECR image integrations are auto-generated for EKS clusters.

chore: migrate sensor awscredentials to aws-go-sdk-v2

---

CHANGELOG.md

The PR removes back (#12220) the `CHANGELOG.md` line, accidentally restored by #12150.
Peer review.

ROX-25358: Update CHANGELOG.md

---

scanner/datastore/postgres/mocks/indexer_metadata_store.go

chore(style): fix scanner style

---

ui/apps/platform/eslint-plugins/pluginPatternFly.js

Follow up simplifications to rendering of tables.
Winston Churchill:
> Now this is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning.
Potential inconsistency between responsive label and column head.
1. We rarely test at narrow enough width of about 760px.
2. Corresponding prop and text are sometimes separated by hundreds of lines.
Find in Files
1. `<Td` with **Match Whole Word**: 468 results in 87 files.
2. `<Td\w+` with **Match Whole Word** and **Use Regular Expression**: 36 results in 3 files.
* `<TdHealthy`
* `<TdUnhealthy`
* `<TdDegraded`
* `<TdUnavailable`
* `<TdUnitialized`
* `<TdTotal`
3. `<\w+Td` with **Match Whole Word** and **Use Regular Expression**: 4 results in 4 files.
* `<CVESelectionTd`
Find in Files
1. `<Th` with **Match …

chore(ui): Require consistent Td dataLabel and Th text

---

go.mod
roxctl/central/db/restore/v2_restorer.go
roxctl/central/db/transfer/progress_bar.go
roxctl/central/generate/interactive.go

`golang.org/x/crypto/ssh/terminal` is deprecated in favor of `golang.org/x/term` (in fact, `golang.org/x/crypto/ssh/terminal` calls `golang.org/x/term` under the hood now).
These changes remove all usage of `golang.org/x/crypto/ssh/terminal` and replace it with `golang.org/x/term`.

chore: move from x/crypto/ssh/terminal to x/term

---

pkg/env/postgres_query_tracer.go
pkg/search/postgres/common.go

Decided to make it easier for devs to log queries for debug and investigation.  So added an env var and put a log statement behind a flag.  We really only want this to be done in select circumstances as it will log a lot of stuff.  That is why I chose this path instead of simply putting it as a debug log.  It will produce a lot of noise and thus should be intentional.
spun up a cluster.  looked at logs and saw no queries.  Toggled flag on, checked logs and verified queries present.  Toggled flag off, checked logs and verified no queries present.

chore(query): log queries behind flag

---

CHANGELOG.md

chore(deps): Add 4.4.7 release changelog

---

.github/workflows/build.yaml
.github/workflows/scanner-build.yaml

(cherry picked from commit 434edc59d18f6fdc3f330929b3550758ba08d48d)
Scans can't be uploaded so we need to turn that off.
change me!

fix(CI): disable roxctl scan results upload (#13083)

---

ui/apps/platform/cypress/integration/violations/Violations.helpers.js
ui/apps/platform/cypress/integration/violations/Violations.selectors.js
ui/apps/platform/cypress/integration/violations/violations.test.js
ui/apps/platform/src/Containers/Violations/Details/ViolationDetailsPage.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx
ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
ui/apps/platform/src/constants/violationStates.js

This PR adds two label chips to the Violations details page—one for the "Violation state" and one for the "Resolved on" time. If the state is not "Resolved", the second chip won't show up.

ROX-26546: Add extra label chips to Violation details

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ClusterSelection.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ReportConfiguration.tsx

This PR adds the "Operator version" to the Compliance Schedule creation flow. The banner at the top of the page informs the user which versions will work for Reporting.

ROX-26821: Adding operator version to Compliance schedule creation

---

sensor/common/clusterentities/metrics/metrics.go
sensor/common/clusterentities/store.go
sensor/common/clusterentities/store_test.go

Reverts stackrox/stackrox#13155 as it seems to be causing issues like, for example: ROX-22281

Revert "ROX-25990: Add history for containerIDs in Sensor"

---

tests/upgrade/postgres_run.sh

Add 4.5.5 to the upgrade test
change me!

chore(upgrade): upgrade test to add 4.5.5

---

pkg/env/durationsetting.go
pkg/env/metrics.go
pkg/metrics/server.go
pkg/metrics/util.go
pkg/timeutil/must_parse.go
pkg/utils/must.go
pkg/utils/panic/hard_panic.go

This is a prefactoring to avoid future cycles between env and logging: `pkg/env` dependencies to not import anything that logs.
CI.
Current dependencies on/for this PR:
* [master](../tree/master)
* **PR #13397** 👈
* **PR #13371**

chore(refactor): `pkg/*` prefactoring

---

pkg/registries/factory.go
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/AzureIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/MicrosoftSentinelForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/IntegrationForm.tsx

This is a pre-factoring PR with small issues I noticed while working on #13427. I out sourced the changes to avoid polluting the diff in that PR. Summary of changes:
* sorting alphabetically in a few places.
* export `AzureIntegrationForm` instead of `ClairIntegrationForm` in Azure form (I would be curious if somebody could explain to me why it worked before 😅).
* removal of unnecessary use of spread operator.
CI

chore: pre-factor UI forms

---

.github/workflows/scanner-nvd-update.yaml

The upload step should not be dependent on both nvd feeds and nvd api data. 
[Stackrox definitions](https://console.cloud.google.com/storage/browser/definitions.stackrox.io/v4/nvd;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=1&inv=1&invt=AbidVw&project=stackrox-hub&prefix=&forceOnObjectsSortingFiltering=false)

fix: NVD upload

---

image/rhel/konflux.Dockerfile
image/roxctl/konflux.Dockerfile
operator/konflux.Dockerfile
scanner/image/scanner/konflux.Dockerfile

Enabling the release builds for Konflux builds.
No new tests are required.
https://github.com/stackrox/stackrox/pull/13348#issuecomment-2479649184

ROX-24276: Enable release builds on Konflux with GOTAGS

---

image/templates/helm/shared/templates/_scanner-v4_volume.tpl

Removed three superfluous lines in the Helm templating.
No doc changes needed.
Existing unit/CI tests.

fix: Remove helm-templating code without effect

---

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx

Added pagination component to the Exception Management CVE table per request. Should look like below
Page 2 + network request: 
change me!

ROX-26302: Adding pagination to Exception Management CVEs table

---

operator/hack/common.sh

The install plan only appears after the job completes. describe the jobs and install plans to ease troubleshooting.
CI is sufficient. This fails very rarely so hard to test the new code.

test: dump more resources on missing install plan

---

ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/AzureIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ClairifyIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/GhcrIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/JiraIntegrationForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/MicrosoftSentinelForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/QuayIntegrationForm.tsx

Follow up to #13427. Adjust the spelling in a few UI integrations forms from title case to sentence case. 
change me!

chore: title case to sentence case

---

scripts/ci/lib.sh

Awaiting prefetcher was [unintentionally always passing](https://redhat-internal.slack.com/archives/C0321S70YK1/p1731415449297889?thread_ts=1731355279.014839&cid=C0321S70YK1) because of running inside an `if` condition.
This change makes it intentional for the:
- potentially-flaky parts to not fail the job, and
- the parts which should in theory never fail - to fail the job
It also adds some messages and a summary file to help investigate failures.
- created a dummy PR based on this one which forces the pull timeout to 1s to make the prefetching fail: https://github.com/stackrox/stackrox/pull/13514
- looked at one of the jobs
- made sure the query works as expected:

tests: improve image_prefetcher_await_set()

---

ui/yarn.lock

ROX-27156: Update serialize js

---

ui/yarn.lock

ROX-27157: Update serialize js

---

central/imageintegration/store/defaults.go
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/GhcrIntegrationForm.tsx

Add a hint that users should skip test integration when adding an anonymous ghcr.io image integration. This is because otherwise the ping to `ghcr.io/v2/` will be rejected with a 403.
see screenshot

fix: skip test integration hint for ghcr.io

---

scanner/updater/version/VULNERABILITY_BUNDLE_VERSION

As per https://spaces.redhat.com/display/StackRox/Upstream+Release+Automation#UpstreamReleaseAutomation-scanner-updater-configuration
PR as part of the release workflow
In CI we trust

chore: Pin point v2 vuln schema to 4.6.1

---

sensor/tests/connection/connection_test.go

While working on https://github.com/stackrox/stackrox/pull/12989 (which will not be merged itself), I noticed a test flaking due to missing retries. Here, I add 5 retries to that test as an improvement.

ROX-27267: Add retries to ScannerDefinitionsProxy test

---

operator/tools/kuttl/go.mod

This is to help shepherd https://github.com/stackrox/stackrox/pull/13572 across which is stuck due to https://github.com/dependabot/dependabot-core/issues/9527
I'm not updating kuttl itself on purpose to see what dependabot does.

chore(tests): bump go in kuttl tools dir to 1.22.7

---

scripts/ci/bats/fixtures/service-both.json
scripts/ci/bats/fixtures/service-hostname.json
scripts/ci/bats/fixtures/service-ip.json
scripts/ci/bats/fixtures/service-unready.json
scripts/ci/bats/lib_service_endpoint.bats
scripts/ci/lib.sh

The ticket in $SUBJECT collected failures of the following jobs:
- `rosa-qa-e2e-tests`
- `rosa-hcp-qa-e2e-tests`
- `eks-qa-e2e-tests`
- `eks-qa-ebpf-e2e-tests`
- `osd-aws-qa-e2e-tests`
Apparently on ROSA, EKS and OSD-AWS the load balancer reports the ingress endpoint through the `.hostname` key rather than `.ip`.
Added support for this, along with BATS unit tests.
Triggered the previously problematic jobs.

ROX-27323: Suport hostname in LB ingress.

---

scripts/ci/bats/fixtures/service-two-ingresses.json
scripts/ci/bats/lib_service_endpoint.bats
scripts/ci/lib.sh

A followup to #13587 to cover a case which does not happen at the moment, but might in the future.
Also:
- mention the function name in test names for ease of searching.
- remove useless variable

fix(tests): support many endpoints case in service_get_endpoint

---

tests/upgrade/postgres_run.sh

As part of the patch release process
PR CI run

chore(release): Add 4.6.1 previous version in upgrade test

---

central/notifier/datastore/telemetry.go

ROX-27487: Add telemetry for Microsoft Sentinel Notifier

ROX-27487: Add telemetry for Microsoft Sentinel Notifier

---

pkg/features/list.go
tests/e2e/lib.sh

Simply adding a feature flag for the CVE Data Model refactor so it is there for us to use.
CI Sufficient

ROX-27403: Feature Flag for CVE Data Model refactor

---

image/postgres/Dockerfile
image/postgres/konflux.Dockerfile
image/rhel/konflux.Dockerfile
image/roxctl/konflux.Dockerfile
operator/konflux.Dockerfile
operator/konflux.bundle.Dockerfile
scanner/image/db/konflux.Dockerfile
scanner/image/scanner/konflux.Dockerfile

Context: https://issues.redhat.com/browse/ROX-27485 and https://github.com/stackrox/stackrox/pull/13577
Konflux CI shall pass.

ROX-27485: Add comment not to delete source-location LABEL

---

tests/common.go
tests/tls_challenge_test.go

Noticed when investigating https://issues.redhat.com/browse/ROX-27446
CI is enough.

tests: TestTLSChallenge improvements

---

central/complianceoperator/v2/report/manager/generator/mocks/report_gen.go
central/complianceoperator/v2/report/manager/generator/report_gen.go
central/complianceoperator/v2/report/manager/generator/report_gen_impl.go
central/complianceoperator/v2/report/manager/generator/report_gen_impl_test.go
central/complianceoperator/v2/report/manager/utils/results_aggregator.go
central/complianceoperator/v2/report/manager/utils/results_aggregator_test.go
central/complianceoperator/v2/report/result.go

Refactor the walk-by function to make it more testable.

ROX-27419: Refactor walk by function

---

CHANGELOG.md

The announcement (originally made in this [PR](https://github.com/stackrox/stackrox/pull/9903)) that the
```
/v1/availableAuthProviders
/v1/tls-challenge
```
APIs will require authentication in a future release was mistakenly added to the `Deprecated features` instead of the `Technical Changes` section of the 4.4 release.
This has also made it into the RHACS docs, which will have to be fixed as well.
Testing not needed.

ROX-22480: Move endpoint auth announcement to correct section

---

image/templates/helm/shared/templates/02-scanner-06-deployment.yaml.htpl
image/templates/helm/shared/templates/02-scanner-v4-07-db-deployment.yaml
image/templates/helm/shared/templates/02-scanner-v4-07-indexer-deployment.yaml
image/templates/helm/stackrox-secured-cluster/templates/_init-tls-certs.tpl
image/templates/helm/stackrox-secured-cluster/templates/admission-controller.yaml
image/templates/helm/stackrox-secured-cluster/templates/collector.yaml.htpl
image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl

Less duplication by factoring out the common parts for reuse.
See [ROX-27517](https://issues.redhat.com/browse/ROX-27517).
Since this is a mere refactoring, I am solely depending on the existing tests.
change me!

ROX-27517: TLS certificate init container refactoring

---

ui/apps/platform/src/queries/controls.js

The compliance dashboard page relies on graphQL queries to populate its widgets.
One of these queries needs the cluster IDs and names to perform data aggregations. The current method requires users visiting the compliance dashboard to have Cluster read permissions, which might allow them to see more data than an administrator would like them to.
This change should allow the UI to rely on the new graphQL compliance verb and drop the need for the cluster read permission for the compliance dashboard.
PR stack:
- #13055
- #13056
Configure the access control to have a user who is only granted the Compliance Read permission, open the compliance dashboard and check it opens without error and displays the widgets correctly.

feat(ui): Compliance dashboard without Cluster read permission

---

scripts/ci/get-slack-user-id.sh

Adding Slack user ID to get-slack-user-id.sh
N/A

chore(onboard): adding slack user id to get-slack-user-id.sh

---

ui/apps/platform/src/Containers/Integrations/utils/integrationsList.ts

ROX-27616: Fix microsoft typo on integrations page

---

CHANGELOG.md

Update CHANGELOG.md for 4.6.2

---

README.md

Fixed two README.md quickstart errors

doc: Fixed two README.md quickstart errors

---

pkg/features/list.go

As titled.
TODO: Test functionality when image build completes

chore: Enable SBOM generation

---

central/graphql/resolvers/images_test.go
central/graphql/resolvers/test_utils.go

Add scoped access control test to the graphQL image resolver to ensure functional consistency in upcoming performance improvement change
Unit test run in IDE

tests: add SAC test to graphQL image resolver

---

scripts/ci/lib.sh

Bump junit2jira version to v0.0.23
This version includes the fix for golang test ingestion. More info in PR: https://github.com/stackrox/junit2jira/pull/33
I'll let CI run and validate that junit2jira works properly

chore(CI): Bump junit2jira version to v0.0.23

---

central/rbac/service/list_subjects_test.go
pkg/search/result.go

This looks like dead code that should have been removed in some post-migration cleanup.
Cleanup of write-only struct field. The existing CI should be sufficient.
In CI we trust.

chore(cleanup): remove write-only search result field

---

pkg/search/postgres/common_test.go

Tests in this file works without DB so there is no need to guard it with tag.
Refs: 
- https://github.com/stackrox/stackrox/pull/13799
CI

chore: run unit test without pg requirement

---

pkg/search/postgres/common_test.go
pkg/search/postgres/joins.go

Preparation work for `select xxx, yyy, count(...) from table group by xxx, yyy` type of queries (avoid transfer of large amount of data for counting purposes when the database can do the job).
Here the focus is to make sure the later work does not break the existing count query generation.
Manual run of new unit tests

tests: add tests for postgres Count queries

---

sensor/kubernetes/certrefresh/localscanner_tls_issuer_test.go
sensor/kubernetes/certrefresh/securedcluster_tls_issuer_test.go
sensor/kubernetes/certrefresh/tls_issuer_common_test.go

This PR extract similar code from the local scanner and the secured cluster certificate refresh tests, into a common `verifySecrets` function.
This is also a prefactor for https://github.com/stackrox/stackrox/pull/13596, where this function will be used in more tests.
Testing change only, CI is sufficient.

ROX-27014: Cert refresh testing cleanup - extract verifySecrets

---

pkg/features/list.go

This reverts commit 8ab4d1aca761dba8d7ed7059ab2cc16a316bf0f3.
After wider review of this change we have decided to make some adjustments for consistency. In addition, this being enabled causes some e2e tests to fail in some frequent circumstances so it is better to disable it now and re-enable once this has had more time to bake.
change me!
change me!

fix: Revert "chore: Enable platform CVE split feature flag (#13788)"

---

central/externalbackups/plugins/s3compatible/s3compatible.go
go.mod
go.sum

The new version of the aws sdk changes the checksum validation/calculation default to calculate checksum. This is not supported by some S3 compatible providers (like Cloudflare).
This PR sets the client to calculate checksum only if required. This should solve the e2e failures we are seeing here #13878

fix(s3-compatible): Validate checksum only if required

---

deploy/common/k8sbased.sh

The `k8sbased.sh` script tries to check if the Helm-chart to be deployed supports CRS or not. While doing so, it forgets that the Helm chart to be used can be overriden by the caller.
Additionally, since the `compat` tests leverage this deployment mechanism do deploy recent sensor alongside old centrals, another check has been introduced, which checks for CRS-issuing ability of the deployed central.

ROX-27765: Respect CRS-availability check in deploymnt script

---

central/cve/converter/utils/convert_utils.go
central/image/datastore/store/postgres/store.go
central/image/datastore/store/postgres/store_test.go
central/views/read_options.go

This PR copies epss probability to epss probability column in image cve table
change me!
change me!

ROX-27728: Copy epss probability  column values

---

image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml
image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl
image/templates/helm/stackrox-secured-cluster/templates/admission-controller.yaml
image/templates/helm/stackrox-secured-cluster/values-public.yaml.example
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/admission-control.test.yaml

Opened this PR for testing https://github.com/stackrox/stackrox/pull/13838 on CI
See https://github.com/stackrox/stackrox/pull/13838

feat(helm): support admission control failurePolicy configuration

---

.github/workflows/build.yaml

This PR allows running a build for a specific commit. 
I tested it on my fork and I was able to run commits from stackrox repo that were not on my fork.
CI

fix(ci): build for a specific commit

---

qa-tests-backend/Makefile
qa-tests-backend/src/main/groovy/util/Env.groovy
qa-tests-backend/src/main/groovy/util/Helpers.groovy
qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
qa-tests-backend/src/test/groovy/AttemptedAlertsTest.groovy
qa-tests-backend/src/test/groovy/BaseSpecification.groovy
qa-tests-backend/src/test/groovy/CSVTest.groovy
qa-tests-backend/src/test/groovy/ComplianceTest.groovy
qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
qa-tests-backend/src/test/groovy/Enforcement.groovy
qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
qa-tests-backend/src/test/groovy/K8sEventDetectionTest.groovy
qa-tests-backend/src/test/groovy/PolicyConfigurationTest.groovy
qa-tests-backend/src/test/groovy/ProcessVisualizationTest.groovy
qa-tests-backend/src/test/groovy/VulnMgmtWorkflowTest.groovy

cherry-pick of some test-flakiness fixes to release-4.4 to make the tests green so that I can merge my PR https://github.com/stackrox/stackrox/pull/13945
change me!

ci: Update test fixes for r4.4

---

central/notifiers/generic/generic_test.go

Address the review comment in #13824 
N/A

ROX-27688: Use assert.NotContains to check for newlines in unit test

---

central/delegatedregistryconfig/datastore/telemetry.go
central/delegatedregistryconfig/datastore/telemetry_postgres_test.go
central/main.go

I got curious about the usage of delegated image scanning and noticed that there is no active telemetry for it. Therefore, this PR adds telemetry for the delegated scanning config. Concretely, the change adds two properties:
```
Delegated Scanning Enabled For: ALL
Total Delegated Registries: 2
```
CI and tested in segment debugger https://app.segment.com/redhat-devtools/sources/acs_instances_backend_dev/debugger

ROX-25373: add telemetry for delegated registry config

---

pkg/search/postgres/common_test.go
pkg/search/postgres/joins.go

Follow-up to address a review comment on #13799 
Manual run of the changed tests.
CI will cover the rest.

tests: improve readability of expected postgres statement text

---

qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy

In ticket ROX-27701, the name of the variable failing checks is misleading.
This PR changes the variable name to a more appropriate one.
PR CI run

test: use more accurate variable name

---

image/templates/helm/shared/templates/02-scanner-06-deployment.yaml.htpl
image/templates/helm/shared/templates/02-scanner-v4-07-db-deployment.yaml
image/templates/helm/shared/templates/02-scanner-v4-07-indexer-deployment.yaml
image/templates/helm/stackrox-secured-cluster/templates/_init-tls-certs.tpl
image/templates/helm/stackrox-secured-cluster/templates/admission-controller.yaml
image/templates/helm/stackrox-secured-cluster/templates/collector.yaml.htpl
image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl

See https://issues.redhat.com/browse/ROX-27847.
change me!

ROX-27847: Reduce init container requirements

---

.tekton/basic-component-pipeline.yaml
.tekton/main-pipeline.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/retag-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml

from https://github.com/stackrox/konflux-tasks/pull/31
No change.
Manually verified operator-bundle pipeline and the snapshots.

ROX-27764: Stop providing PipelineRun in AppStudio's label

---

.github/CODEOWNERS

Update the code owner of `pkg/search` to be core workflows
none as it is just code owner file.

chore(owners): add search to CWF

---

pkg/queue/queue.go

The logs for dropping items in the queue can be very spammy. This PR switches the default logger for the `RateLimitedLogger` to avoid spamming the logs.

fix(log): Rate limit the log for drop item

---

central/alert/mappings/options.go
generated/storage/alert.pb.go
proto/storage/alert.proto

Removed search tags from ListAlert proto and changed `central/alert/mappings/options.go` to point at Alert and not ListAlert for getting search options
Tested in the app and the Violations dashboard is still showing autocomplete options when you attempt to search. Violations also appear as expected.

ROX-26586: Remove search tags from ListAlert

---

ui/apps/platform/src/Containers/Policies/Wizard/Step5/PolicyActionsForm.tsx

Update policy activation description text in the Policy Management creation workflow

ROX-27862: Update policy activation state

---

image/templates/helm/shared/config-templates/scanner-v4/matcher-config.yaml.tpl

Somehow I didn't apply this suggestion in my PR: https://github.com/stackrox/stackrox/pull/13779#discussion_r1940058461 although I was pretty sure I clicked the `commit change`
change me!

fix: matcher vuln URL

---

central/scannerdefinitions/handler/updater_test.go
image/rhel/fetch-stackrox-data.sh

(cherry picked from commit 9f3eb2c008a911e3c8b74cb4a2e86ab2259b7421)
change me!
change me!

fix(ci): due to diff CDN behavior (backport #14052 to release 4.4)

---

pkg/grpc/endpoints.go
pkg/grpc/server.go
pkg/grpc/server_test.go
pkg/testutils/http.go

We still have some issues with `Test_APIServerSuite/Test_TwoTestsStartingAPIs` golang unit test. We had one failure so far.
This PR changes the logic a bit to handle the stopping of the server differently. This will allow us to see if `Stop()` failed or not. PR also fixes the output of used ports at the end of the test.
**Update 2025-01-30**
> we should have proper order of start/stop log lines
The order of logs can be different. Because logs are output by two different routines. The conclusion that I have made for logs is not correct.
I have tested this in Ubuntu VM (~10k executions - bash for loop to 100 with `go test .. -count 100`) - I didn't have a single failure. But I'm also not able to get any failure on the main branch.

ROX-27818: Ensure api Stop is properly called and finished

---

.github/CODEOWNERS

A few protos which I believe we should always be aware of.
no
no

chore(CODEOWNERS): add more Scanner team ownership

---

ui/apps/platform/src/Containers/NetworkGraph/external/EntityDetailsTable.tsx
ui/apps/platform/src/Containers/NetworkGraph/external/ExternalEntitiesSideBar.tsx
ui/apps/platform/src/Containers/NetworkGraph/external/ExternalIpsTable.tsx
ui/apps/platform/src/Containers/NetworkGraph/types/topology.type.ts
ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.ts
ui/apps/platform/src/services/NetworkService.js
ui/apps/platform/src/types/networkFlow.proto.ts

Create the side panel table for viewing flows on a single external entity.

ROX-27639: Add side panel for single external entity

---

pkg/features/list.go

Practical prerequisite to bug bash both sync and async. Merge when core and scanner team say go!
CI

ROX-27423: Enable ROX_EPSS_SCORE feature flag

---

central/notifiers/microsoftsentinel/README.md

docs: Add service principal command to Sentinel notifier

---

pkg/search/postgres/common.go
pkg/search/postgres/common_test.go

This PR adds explanation for IN operator decisions.
See: https://github.com/stackrox/stackrox/pull/13915#discussion_r1935516617
Refs: https://issues.redhat.com/browse/ROX-27944
CI

chore(pg): add comment about IN operator

---

scripts/ci/sensor-wait.sh

Current title of an example ticket:
`Stackrox_Deployment / Was Stackrox deployed to the cluster FAILED`
New title:
`Stackrox_Deployment / Waiting for sensor in ns stackrox to be ready timed out. FAILED`
LGTM: ![image](https://github.com/user-attachments/assets/61ca8166-6553-42ca-b68e-c12419fa8553)

tests: improve ticket titles for failed sensor and collector check

---

pkg/features/list.go
tests/e2e/lib.sh
ui/apps/platform/cypress/helpers/nav.ts
ui/apps/platform/cypress/helpers/request.js
ui/apps/platform/cypress/integration/risk/risk.test.js
ui/apps/platform/cypress/integration/violations/Violations.helpers.js
ui/apps/platform/cypress/integration/violations/Violations.selectors.ts
ui/apps/platform/cypress/integration/violations/filteredWorkflowViews.test.ts
ui/apps/platform/cypress/integration/violations/violations.test.js
ui/apps/platform/cypress/integration/violations/violationsSearchFilter.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeCvesOverviewPage.test.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.ts
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/namespaceView.test.js
ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.ts
ui/apps/platform/cypress/selectors/navigation.ts
ui/apps/platform/src/Containers/MainPage/Navigation/HorizontalSubnav.tsx

Enables the feature flag and updates e2e tests to support the changes.
Local e2e test runs, but lets wait and see what CI says.

chore(ui): Enable the platform CVE split feature flag

---

ui/apps/platform/cypress/integration/violations/Violations.helpers.js
ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx

Updates Violations to include:
- Page titles dependent on the workflow view
- Page help text dependent on the workflow view
- Page descriptions dependent on the violation state tabs
Page titles/help text:
Violation state tab descriptions:

chore(ui): Add descriptions for Violation page states

---

tools/allowed-large-files
ui/apps/platform/cypress/integration/integrations/signatureIntegrations.test.js
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/SignatureIntegrationForm.tsx

Add more explanations and help texts to the image signature integration form. Most importantly, clarify that certs must not be expired and that we do not support integration with Rekor transparency log.
I also added some placeholders for the public key and certificate fields.
looked at UI rendering

chore(image-signatures): improve UX of the integration form

---

ui/apps/platform/cypress/integration/integrations/signatureIntegrations.test.js

I missed a small spelling change in the UI cypress tests.
CI passes

ROX-27978: image signature e2e test

---

central/image/service/http_handler.go
pkg/apiparams/sbom.go
roxctl/image/sbom/sbom.go

ROX-27784: remove cluster flag from http handler and roxctl api

---

tests/performance/load/groups/mainDashboard.js
tests/performance/load/groups/vulnerabilityManagementDashboard.js

The dashboards have evolved a bit since the last capture of the associated requests.
This change aims at re-aligning the performance tests with the actual dashboard state.
CI run with label.

tests: refresh queries for main and vulnerability dashboards

---

image/templates/helm/shared/templates/02-scanner-03-tls-secret.yaml
image/templates/helm/shared/templates/02-scanner-v4-03-db-tls-secret.yaml
image/templates/helm/shared/templates/02-scanner-v4-03-indexer-tls-secret.yaml
image/templates/helm/shared/templates/02-scanner-v4-03-matcher-tls-secret.yaml
image/templates/helm/stackrox-central/templates/01-central-05-db-tls-secret.yaml
image/templates/helm/stackrox-central/templates/01-central-05-tls-secret.yaml
image/templates/helm/stackrox-central/templates/01-central-06-default-tls-cert-secret.yaml
image/templates/helm/stackrox-central/templates/_labels.tpl
image/templates/helm/stackrox-secured-cluster/templates/admission-controller-secret.yaml
image/templates/helm/stackrox-secured-cluster/templates/collector-secret.yaml
image/templates/helm/stackrox-secured-cluster/templates/sensor-secret.yaml
operator/internal/central/extensions/reconcile_admin_password.go
operator/internal/central/extensions/reconcile_central_db_password.go
operator/internal/central/extensions/reconcile_tls.go
operator/internal/common/extensions/reconcile_scanner_db_password.go
operator/internal/common/extensions/reconcile_scanner_v4_db_password.go
operator/internal/common/extensions/secret_reconciliator.go
operator/internal/common/extensions/secret_reconciliator_test.go
operator/internal/common/labels/labels.go
operator/internal/common/labels/labels_test.go
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/tls-secrets.test.yaml
sensor/kubernetes/certrefresh/certrepo/service_certificates_repository.go
sensor/kubernetes/certrefresh/certrepo/service_certificates_repository_test.go
sensor/utils/utils.go

Adding `http://rhacs.redhat.com/tls=true` label to all TLS secrets. This allows listing all secrets containing TLS material using a label selector.
Jira Ticket: https://issues.redhat.com/browse/ROX-25844
Implemented table driven unit testing for Merging labels-->testing completed for func `MergeLabels`, located in `labels_test.go`
Additional testing included in `tls-secrets.test.go` for creating TLS secrets with rhacs.redhat.com/tls=true

ROX-25844: Add Labels to all TLS Secrets

---

sensor/common/detector/detector.go
sensor/common/detector/enricher.go
sensor/common/detector/metrics/metrics.go

Add metrics to the scan logic in the detector.

feat(metrics): Add metrics to the scan logic in the detector

---

central/cluster/datastore/datastore_impl_postgres_test.go

Add tests for https://github.com/stackrox/stackrox/pull/13777
This PR only adds tests.

ROX-27597: Unit tests for cluster sensor capabilities

---

ui/apps/platform/src/Containers/Clusters/ClusterEditForm.tsx
ui/apps/platform/src/Containers/Clusters/Components/ClusterSummary.js
ui/apps/platform/src/Containers/Clusters/Components/CredentialExpiration.tsx
ui/apps/platform/src/Containers/Clusters/Components/CredentialExpirationWidget.tsx
ui/apps/platform/src/Containers/Clusters/Components/CredentialInteraction.tsx
ui/apps/platform/src/Containers/Clusters/clustersTableColumnDescriptors.js
ui/apps/platform/src/types/cluster.proto.ts

As title states -- I added the text to the widget rendered in the cell so it also shows in the cluster detail page.

ROX-27179: Adding "Auto-refresh enabled" text to Clusters page

---

.github/contributing.md

chore: document auto retest feature

---

tests/performance/load/groups/mainDashboard.js
tests/performance/load/groups/vulnerabilityManagementDashboard.js

Follow-ups for #14167 
Should be caught by the existing performance test (run with label)
Build new docker image of `tests/performance/load` and ran it in a new container. Checked the created GET queries have the expected form.

tests: improve readability of load test queries

---

ui/apps/platform/src/Components/SelectSingle/SelectSingle.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/MachineAccessIntegrationForm.tsx

This fixes a problem with the roles getting cut off in the selection if there are more than 10 roles.
looked at the rendered UI

fix(ui): roles cut off in m2m integration form

---

ui/apps/platform/src/Containers/Vulnerabilities/components/GenerateSbomModal.tsx

No functional changes - SBOMs will be produced in `SPDX` format (not `SBDX`): https://spdx.github.io/spdx-spec/v2.3/
N/A
👁️ 📖

fix(typo): Change SBDX to SPDX in SBOM UI

---

qa-tests-backend/src/main/groovy/services/ClusterService.groovy
qa-tests-backend/src/test/groovy/ComplianceTest.groovy
qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
qa-tests-backend/src/test/groovy/PolicyConfigurationTest.groovy

Fix qa-test by not running on ARO - only AKS is supported. The current `isAKS` is changed to `isAzure` to reflect its implementation, and a new `isAKS` is introduced based on the cluster metadata type.
CI

ROX-27995: don't run test on ARO

---

pkg/scannerv4/mappers/mappers.go
pkg/scannerv4/mappers/mappers_test.go

some follow-ups to address concerns from the team
change me!

chore: EPSS minor fixes

---

go.mod

[Add documentation to helm-operator fork](https://github.com/stackrox/stackrox/commit/6489156267fbe47183041ae818f10c4350e1e4d5)

docs: Add documentation to helm-operator fork

---

central/complianceoperator/manager/manager.go
pkg/images/enricher/enricher_impl.go
pkg/postgres/pgutils/error.go
pkg/postgres/pgutils/retry.go

Wrap some errors related to retries and context cancellations. This is a follow up to a dog fooding investigation trying to trace errors such as
> `Enriching image {"image": "quay.io/prometheus/blackbox-exporter:v0.25.0", "image_id": "", "error": "image enrichment errors: [error scanning image: quay.io/prometheus/blackbox-exporter:v0.25.0 error: context canceled, fetching signature integrations: context canceled]", "request_image": "quay.io/prometheus/blackbox-exporter:v0.25.0"}`
CI

chore: improve retry and context errors

---

.github/CODEOWNERS

As I have some knowlede about qa tests and Spock and Groovy in general I'd like to review changes for qa test.
CI

chore: set janisz as owner of qa tests

---

.github/dependabot.yaml

This is a workaround for dependabot issue of not updating custom actions.
- https://github.com/dependabot/dependabot-core/issues/6345
- https://github.com/stackrox/stackrox/pull/14230
---
CI

fix(dependabot): use dependabot for custom actions

---

qa-tests-backend/src/test/groovy/ImageSignatureVerificationTest.groovy

The image signature qa-tests setup images and deployments before verifying any policy violations. We have seen examples of this setup not completing within the current retry time. In https://storage.googleapis.com/test-platform-results/logs/branch-ci-stackrox-stackrox-master-ocp-4-12-merge-qa-e2e-tests/1877618595001798656/build-log.txt it took 47 out of 90 attempts just to see the image in Central's database. The image signature fetcher did not complete in the remaining time.
This is essentially an attempt at a low effort fix. If we see this popping up again, we can dive deeper. I changed the number of retries to `20 x 30s` from `90 x 2s` to i) increase the total time and ii) lower the attempts to reduce log spam.
CI

ROX-23899: increase image signature test setup retry time

---

central/telemetry/centralclient/interceptors.go
central/telemetry/centralclient/interceptors_test.go

I realized that we do not whitelist our GitHub action user agents, ~and therefore don't collect any telemetry for them~.
Edit: Actually we do whitelist the paths `/v1/auth/m2m/exchange` and `/api/cli/download/` explicitly, so we do collect telemetry. Anyways, I think it's probably a good idea to consolidate the collection around user agents.
change me!

fix(telemetry): whitelist GitHub action user agents

---

central/signatureintegration/store/postgres/gen.go
central/signatureintegration/store/postgres/store.go

Use the in-memory cached store for image signature integrations. Signature integrations are fetched in the enrichment step for each image, which creates unnecessary database requests. The cardinality of signature integrations is typically very low (`0-4` based on telemetry) with rare writes, but many reads due to enrichment. In summary, a perfect opportunity for caching.
I did a one-off test using the the X-Large scale test profile for this PR and current master.
```
this PR: rox_central_reprocessor_duration_seconds -> 53 minutes
master: rox_central_reprocessor_duration_seconds -> 62 minutes
```
CI

perf: cache signature integrations

---

central/telemetry/centralclient/runtime_config_test.go
pkg/telemetry/phonehome/client_config.go

Let's add a mutex to protect a concurrently accessed variable.
Let's also not call `Enable()` and `Disable()` in the tests, as they have undesired side effects, such as track calls and started gathering.
Unit tests.

ROX-28067: fix the race in central telemetry client test

---

scanner/services/indexer.go
scanner/services/matcher.go

Do the same thing as https://github.com/stackrox/stackrox/pull/13986 but for Scanner V4.
no
I didn't

chore(scanner): use consts for authz

---

qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy

Attempts to reproduce the CI flake reported in ROX-27701 , a time gap was observed in the backend logs between internal calls during the AuthProvider reconciliation.
Test log (local time UTC+1):
```
15:28:52 | DEBUG | DeclarativeConfigTest     | DeclarativeConfigTest     | updated declarative auth provider to be invalid in configMap 1cd370b7-f0e7-4029-b782-701860f89216
15:30:50 | DEBUG | DeclarativeConfigTest     | Helpers                   | Caught exception. Retrying in 3s (attempt 39 of 60): Condition not satisfied:
```
Backend logs (UTC), *The important part here is the gap between 14:28:56 and 14:30:48*:
```
2025/02/17 14:28:51.960282 pkg/auth/authproviders/oidc: backend_impl.go:308: Info: Creating OIDC provider backend ef53ca8f-bcf7-529d-8249-8befd36c8a7b
2025/02/17 14:28:56.779267 …
```

ROX-27701: Increase retry for declarative AuthProvider reconciliation

---

.github/CODEOWNERS
go.mod

Merlin and Maple are dead
long live sensor-ecosystem!
---
```bash
pkg/fixtures/image.go:          {"virtmerlin/harbor-image-resource", "sha256:fa141bbec513b64b0f8bc874998ab8b422966260c774baabebfca2bbe7238837"},
```
CI

chore(team): 🧙 + 🍁 = sensor-ecosystem

---

central/cluster/datastore/datastore_impl.go
pkg/centralsensor/sensor_hello.go
pkg/centralsensor/sensor_hello_test.go
sensor/kubernetes/sensor/sensor.go

This PR removes a function that was duplicated in central and sensor.
The `pkg/centralsensor/sensor_hello.go` file already contained `SensorHello` related helpers, and since `HelmManagedConfigInit` is part of `SensorHello`, it could be a good place this function.
Refactor, automated tests are sufficient.

refactor: remove duplicate securedClusterIsNotManagedManually

---

central/apitoken/datastore/datastore_impl.go

prefactoring for https://github.com/stackrox/stackrox/pull/14320. Change `Mutex` to `RWMutex`.
change me!

ROX-28149: use RWMutex in apitokens datastore

---

pkg/postgres/pgtest/postgres.go

This PR changes the default DB name from test name + random string to a hash + random string.
It's done because test name can contain more problematic characters then only `/`, `-`, `_` which are handled now.
Also I found a problem when running sub test as they names quickly grows (it's parents name + test name).
I tried to run tests from https://github.com/stackrox/stackrox/pull/14320 but create a DB for every sub-test. It was failing for a test with the longest name (even when I filtered commas and quoted name). It turned out the db name is too long and is trimmed.
https://stackoverflow.com/a/50472982
```
2025-02-20 13:55:31.951 UTC [202] LOG:  execute stmtcache_4289df684cfb5cd56f2a16daac7064ebddd27a39288d31f4: SELECT EXISTS(SELECT 1 FROM pg_catalog.pg_database WHERE datname = $1) …
```

fix(test): DB creation with hash instead of name

---

Makefile

Fixes local builds on arm64 architectures.
Ran `make image` on my arm64 machine.

chore: update builder image for non-x86_64 builds to golang:1.23

---

central/apitoken/datastore/datastore.go
central/postgres/pruning.go
central/postgres/pruning_test.go
central/pruning/pruning.go
pkg/env/api_token.go

Prune API tokens that either have been expired or have been revoked.
CI

ROX-28184: prune expired API tokens

---

operator/tests/central/central-misc/010-central-cr.yaml
operator/tests/central/central-misc/020-verify-password.yaml
operator/tests/common/central-cr.yaml

We had a check for the explicitly set password. This leaves it alone (in `central-basic`)  and changes `central-misc` test to check the auto-generated password. This allows us to close the long-standing ticket.
CI is enough.

ROX-7442: check generated admin password

---

tests/delegated_scanning_test.go

Adds retries for common errors seen during dele scan tests. This PR does not address root causes or all known errors - more improvements will be added in the future as more failures are assessed. 
Failures assessed:
Run | Error | Comment and/or Root Cause
--- | --- | ---
1891507107337867264	| could not advance in the tar archive: unexpected EOF	| Quay, network, resource, etc. flake
1891507336430751744, 1890483470010945536, 1890331264980881408 | unable to check TLS for registry "icsp.invalid": dial tcp: lookup icsp.invalid on 172.30.0.10:53: no such host | Sensor accepted ad-hoc scan request before mirroring CRs were fully loaded resulting in Sensor making TCP connection to a non-existant host.
1887833250030686208	| http: non-successful response (status=401 body="{\"error\": \"Invalid …

ROX-26663: Dele Scan Tests - add retries for common errors

---

Makefile

To prevent breaking local arm builds when go version is bumped, this PR retrieves the go version from the `go.mod` file.
Ran `make image` on my arm64 machine.

ROX-28206: Extract go version for local arm64 builds from go.mod

---

tests/e2e/lib.sh
tests/e2e/run-scanner-v4-install.bats

The local-execution mode for scanner V4 isntall tests wasn't maintained properly -- here are a couple of smaller fixes for this mode of operation.

test: Support local execution for scanner V4 install tests

---

sensor/kubernetes/listener/resources/env.go
sensor/kubernetes/listener/resources/store_provider.go

The entity store is broken in it's current state. It leads to a quick and endless growth of active endpoints reported by sensor. This issue was discovered during the 4.7.0 release for sensor running in the long running "fake-load" cluster.
With this change we're forcing the memory to 0, which restores previous behaviour for endpoints. We tested that by running the commit before the store refactoring (#13340) was introduced and comparing it with the commit of the PR merge. See image:
It is suspected that the problem with the store leads to sensor reporting network flows for deployments that already have been deleted. Currently there is no logic in central to detect and delete such network flow table entries, which ultimately leads to piling up loads of data in the central DB that can't be …

ROX-28242: Disable entity store memory

---

tools/gorm-snapshot/main.go

This tool helps taking current schema snapshots to facilitate migration tool switch.
Manual testing.

ROX-28128: Add gorm-snapshot tool

---

central/image/service/service_impl.go

Pass the parent context to `acquireScanSemaphore`. This also allows us to use the standard `context.WithTimeout` instead of our custom `concurrency` module. In addition, I added structured logs for failed acquisitions. The acquisitions can now either fail if the parent context is canceled - in this we assume the cancellation is intentional and do not indicate a retry -, if the timeout is hit, or if there was an internal server error.
tested context cancellations on a test cluster

ROX-28260: pass parent context to scan semaphore

---

sensor/common/scan/scan.go

Pass parent context to the sensor scan semaphore and return the err. This also allows us to get rid of the custom `concurrency.Timeout` usage.
See also https://github.com/stackrox/stackrox/pull/14431.
CI

ROX-28260: pass parent context to sensor scan semaphore

---

deploy/common/k8sbased.sh
qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
qa-tests-backend/src/main/groovy/util/CollectorUtil.groovy
qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
tests/e2e/lib.sh

Jv rox 26347 e2e tests for collector runtime config wait for collector DON'T REVIEW

---

scripts/fixxxer.sh
scripts/fixxxers/10-deps-go-mod-tidy.sh
scripts/fixxxers/operator/30-manifests.sh

- The fixers need to run in specific order to prevent [failures](https://github.com/stackrox/stackrox/actions/runs/13627510628/job/38087812279).
- While at it, run `go mod tidy` on all modules, not just ones under `operator/`.
- [this run with this change](https://github.com/porridge/stackrox/actions/runs/13627824243/job/38088759979) cherry-picked in my repo

chore: sort fixxxers and mod tidy everywhere

---

go.mod

Fix go.mod to stop GHA jobs from failing because of a diff.
change me!

fix: go.mod for 4.7 release branch

---

go.mod
go.sum

Backports:
- https://github.com/stackrox/stackrox/pull/14460
Refs:
- https://github.com/stackrox/stackrox/pull/14467
- https://github.com/stackrox/stackrox/pull/14465

ROX-28272: bump oauth2 fork

---

ui/apps/platform/src/services/DelegatedRegistryConfigService.ts

Prerequisite to clean up delegated scanning interactions.
1. Delete copy-paste from DeclarativeConfigHealthService.ts file.
2. Do copy-paste important comments from backend source of truth:
https://github.com/stackrox/stackrox/blob/master/proto/api/v1/delegated_registry_config_service.proto
1. Delete frontend-only `uuid` property (for drag-and-drag interaction that was abandoned) in a separate contribution.
main.js 0 = 4646307 - 4646307
total 18 = 11566776 - 11566758
files 0 = 177 - 177
1. Visit /main/clusters/delegated-image-scanning, change configuration, and …

ROX-28323: Make frontend DelegatedRegistryConfigService file clearer

---

image/templates/helm/stackrox-central/templates/02-config-controller-03-networkpolicy.yaml

Adds a NetworkPolicy for config-controller.
Network Graph now shows a network policy for config-controller

ROX-27691: Added NetworkPolicy for config-controller

---

.github/workflows/scanner-e2e-test.yaml
go.mod
scanner/Makefile
scanner/config/config.go
scanner/config/config_test.go
scanner/e2etests/helmchart/templates/db-deployment.yaml
scanner/e2etests/helmchart/templates/scanner-config.yaml
scanner/e2etests/helmchart/templates/scanner-deployment.yaml
scanner/matcher/matcher.go

Right now, E2E tests assume all vulnerabilities are loaded when Scanner is ready. This PR adds a flag to the Matcher so it explicitly waits for all vulnerabilities to be loaded by the updater before proceeding. It also updates the functional test workflow to handle this properly.
We're also migrating to Viper for configuration management, allowing settings to be defined via environment variables and config files (with env vars taking precedence).
Lastly, renaming "Scanner End-to-End Tests" to "Functional Tests" since that better reflects what they actually do.
1. To simplify ensuring Scanner V4 is ready to perform scans.
2. To standardize config management with Viper, and allow temporary changes to the config without modifying deployments configmaps.
3. The term "Functional Tests" is a …

ROX-28189: Add vulnerability readiness for functional tests

---

roxctl/helm/derivelocalvalues/derivelocalvalues.go
roxctl/helm/derivelocalvalues/derivelocalvalues_test.go
roxctl/helm/derivelocalvalues/extraction_test.go
roxctl/helm/derivelocalvalues/k8s_access_test.go
roxctl/helm/derivelocalvalues/map_util_test.go

Unit tests and a couple of fixes in JSONPath expressions.
Unit tests.

ROX-14460: `roxctl helm derive-local-values` tests and fixes

---

.github/workflows/style.yaml
scripts/check-image-version.sh
scripts/ci/jobs/check-image-version.sh

Check if all stackrox and scanner build and test image version are in sync.
- https://github.com/stackrox/stackrox/pull/14484#pullrequestreview-2663521249
CI

fix(CI): check test image version in sync

---

.github/actions/junit2jira/action.yaml
scripts/ci/lib.sh

We need auto retry http client 
- https://github.com/stackrox/junit2jira/releases/tag/v0.0.24
change me!

chore(deps): bump juni2jira to v0.0.24

---

central/globalindex/mapping/mapping.go
central/graphql/resolvers/gen/main.go
central/graphql/resolvers/generated.go
central/graphql/resolvers/loaders/componentsV2.go
central/graphql/resolvers/loaders/image_cves_v2.go

Adds the loaders and generated updates for the new CVE data model.  
CI is sufficient here for now.  These code paths will be tested as the resolvers that use the loaders are added in subsequent PRs.

ROX-28406: CVE data model loaders and gen

---

central/image/service/service_impl.go
pkg/logging/fields.go
sensor/common/centralclient/grpc_connection.go
sensor/common/delegatedregistry/delegated_registry_handler.go
sensor/common/message/message.go
sensor/common/networkflow/manager/manager_impl.go
sensor/common/processsignal/pipeline.go
sensor/common/sensor/central_communication_impl.go
sensor/common/trace/trace.go
sensor/kubernetes/eventpipeline/component/message.go
sensor/kubernetes/eventpipeline/output/output_impl.go
sensor/kubernetes/eventpipeline/pipeline_impl.go

Pass the cluster ID via the gRPC context from sensor to central. This is useful to surface the cluster ID in administration logs to distinguish requests and error logs when multiple secured clusters are connected.
I created a general approach to create structured logs from function contexts. This could be used to add information other than the cluster ID in the future.
see above, CI

ROX-28261: pass cluster ID from sensor

---

compliance/cmd/compliance/main.go
pkg/continuousprofiling/profiler.go
pkg/env/continuous_profiling.go
scanner/cmd/scanner/main.go
sensor/admission-control/main.go

Use `POD_NAME` as AppName if `ROX_CONTINUOUS_PROFILING_APP_NAME`. This will deployments with multiple pods to have a unique AppName in pyroscope. Having a unique AppName per pod enables the second part of this PR, setting-up pyroscope in admission-control, compliance, and scanner.
- Deploy ACS
- Deploy pyroscope with `helm -n stackrox install pyroscope grafana/pyroscope`
- Set `ROX_CONTINUOUS_PROFILING` to `true`
- Optionally, if pyroscope is deployed in another namespace/cluster:
- Set `ROX_CONTINUOUS_PROFILING_SERVER_ADDRESS` to the proper server address
- Admission-control, compliance, and scanner should start sending profiles to pyroscope after the env vars are set

ROX-28265: Use pod name and enable pyroscope in all components

---

.github/workflows/scanner-versioned-definitions-update.yaml

If any bundle is successfully built we attempt to upload it. But, the job still fail to notify other bundles were not successful.
This is important because we don’t want a single failure to block the use of bundles that can still be usable.
In progress: Currently building this with `pr-update-scanner-vulns` for general validation.

ROX-28500: scanner/updater: Upload any successful bundle

---

go.mod
go.sum

chore(deps): bump go-jose

---

pkg/random/random.go
pkg/random/random_test.go

Add edge case test to `GenerateString` added in 
- https://github.com/stackrox/stackrox/pull/14605
CI

chore(rand): add tests to GenerateString

---

central/cve/cluster/datastore/store/postgres/full_store.go
central/image/datastore/store/postgres/store.go
central/postgres/pruning.go
migrator/migrations/m_172_to_m_173_network_flows_partition/migration.go
pkg/postgres/pgadmin/admin_utils.go
pkg/postgres/pgutils/scan.go

This PR extracts a common code that scans strings from rows into a dedicated function.
CI

chore(PG): create ScanStrings function

---

tests/upgrade/postgres_run.sh

https://spaces.redhat.com/display/StackRox/Upstream+Release+Automation#UpstreamReleaseAutomation-update-upgrade-testUpdateUpgradeTest
change me!

chore(upgrade): add 4.7.0 to upgrade test

---

qa-tests-backend/src/main/groovy/services/AlertService.groovy
qa-tests-backend/src/main/groovy/services/ApiTokenService.groovy
qa-tests-backend/src/main/groovy/services/AuthProviderService.groovy
qa-tests-backend/src/main/groovy/services/AuthService.groovy
qa-tests-backend/src/main/groovy/services/BaseService.groovy
qa-tests-backend/src/main/groovy/services/CVEService.groovy
qa-tests-backend/src/main/groovy/services/CloudSourcesService.groovy
qa-tests-backend/src/main/groovy/services/ClusterInitBundleService.groovy
qa-tests-backend/src/main/groovy/services/ClusterService.groovy
qa-tests-backend/src/main/groovy/services/CollectionsService.groovy
qa-tests-backend/src/main/groovy/services/ComplianceManagementService.groovy
qa-tests-backend/src/main/groovy/services/ComplianceService.groovy
qa-tests-backend/src/main/groovy/services/ConfigService.groovy
qa-tests-backend/src/main/groovy/services/CredentialExpiryService.groovy
qa-tests-backend/src/main/groovy/services/DeclarativeConfigHealthService.groovy
qa-tests-backend/src/main/groovy/services/DeploymentService.groovy
qa-tests-backend/src/main/groovy/services/DetectionService.groovy
qa-tests-backend/src/main/groovy/services/DevelopmentService.groovy
qa-tests-backend/src/main/groovy/services/DirectHTTPService.groovy
qa-tests-backend/src/main/groovy/services/ExternalBackupService.groovy
qa-tests-backend/src/main/groovy/services/FeatureFlagService.groovy
qa-tests-backend/src/main/groovy/services/GraphQLService.groovy
qa-tests-backend/src/main/groovy/services/GroupService.groovy

To ensure our code works as expected let's add `@CompileStatic` so we get know on `stylecheck` if anything could be wrong with types.
To make it easier to review I've splitted this task into 2 PRs.
CI

chore(qa): compile static on services

---

image/templates/helm/stackrox-central/internal/config-shape.yaml
image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
image/templates/helm/stackrox-central/internal/expandables.yaml
image/templates/helm/stackrox-central/templates/01-central-12-central-db.yaml
image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl
image/templates/helm/stackrox-central/templates/02-config-controller-02-deployment.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/affinity.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/central.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/host-aliases.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/node-selector.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/priority-class-name.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/resources.test.yaml
pkg/helm/charts/tests/centralservices/testdata/helmtest/tolerations.test.yaml

Added the ability to override more deployment-related fields in config controller:
- Node Selector
- Affinity
- Tolerations
- Host Aliases
- Resources
- Priority Classes
Added helmtests for the values that were updated (and moved one out of the `central` helmtest and into it's own test alongside the one for config controller)

ROX-26749: Updated config controller to support more overrides

---

central/telemetry/centralclient/interceptors_test.go

Make the test run alone.
Unit tests.

chore(test): refactor a telemetry interceptor test

---

central/telemetry/centralclient/interceptors.go
central/telemetry/centralclient/interceptors_test.go

This PR enables campaign for Jenkins plugin.
See:
- https://github.com/stackrox/jenkins-plugin/pull/402
---
CI

ROX-27001: jenkins plugin campaign

---

central/image/datastore/store/postgres/store.go
central/image/datastore/store/v2/postgres/store.go
central/node/datastore/store/postgres/store.go

ROX-28253: use RunCursorQueryForSchemaFn in image

---

config-controller/api/v1alpha1/policy_types.go
config-controller/api/v1alpha1/policy_types_test.go
config-controller/config/crd/bases/config.stackrox.io_securitypolicies.yaml
image/templates/helm/stackrox-central/crds/config.stackrox.io_securitypolicies.yaml

This PR removes 3 fields from the policy CRD and any uses of those fields.
- MitreVectorsLocked
- CriteriaLocked
- IsDefault
One thing we may want to check on is that if anyone with existing CRs in their clusters with these three fields on them
will have trouble upgrading to 4.8 when it releases.

ROX-26757: Remove Read-Only Fields From Policy CRD

---

ui/apps/platform/package-lock.json
ui/apps/platform/package.json
ui/apps/platform/src/index.tsx

Manually backporting the changes from #14661.

ROX-28200: Load monaco-editor locally instead of CDN

---

scanner/indexer/indexer.go
scanner/internal/httputil/transport.go

This should not change anything, but it protects against future changes. I also modified scanner/internal/httputil/transport.go just to remove some indentation.
no
CI

chore(scanner): safer TLS settings

---

central/administration/events/datastore/telemetry.go
central/apitoken/datastore/telemetry.go
central/auth/datastore/telemetry.go
central/cloudsources/datastore/telemetry.go
central/delegatedregistryconfig/datastore/telemetry.go
central/externalbackups/datastore/telemetry.go
central/imageintegration/datastore/telemetry.go
central/notifier/datastore/telemetry.go
pkg/telemetry/phonehome/gatherer.go
pkg/telemetry/phonehome/gatherer_test.go

This PR introduces 3 helpers, that adapt custom functions to be used with `AddTotal`:
`Bind2nd`:
```go
func f(context.Context, int) (int, error);
bound := Bind2nd(f)(x)
// bound(ctx) === f(ctx, x)
AddTotal(ctx, props, "key", bound)
```
`Len`:
```go
// Len(arr) === func(_ context.Context) (int, error) { return len(arr), nil }
AddTotal(ctx, props, "key", Len(arr))
```
`Constant`:
```go
// Constant(x) === func(_ context.Context) (int, error) { return x, nil }
AddTotal(ctx, props, "key", Constant(x))
```
Unit tests.

refactor(telemetry): `Bind2nd`, `Len`, `Constant` gatherer helpers

---

scripts/ci/lib.sh

Do not curl over all images again if only one is failing.
CI

refactor(CI): image wait loop

---

central/policy/datastore/datastore_impl.go
central/policy/datastore/datastore_impl_postgres_test.go
central/policy/datastore/singleton.go
central/policy/service/service_impl_postgres_test.go
central/policy/store/mocks/store.go
central/policy/store/store.go
central/policycategory/datastore/datastore_impl.go
central/policycategory/datastore/datastore_impl_test.go
central/search/service/service_impl_test.go
config-controller/internal/controller/policy_controller.go

There was an issue when a user would create and then immediately after try to update a policy via the API if the category name they passed in didn't match the expected casing.
Valid: This Is A Valid Category
Invalid: This would have Caused Problems
This PR simply updates the category names to match the expected casing, and thus resolves the issue.
Edit: This PR also contains transaction support for the Policy datastore.

ROX-26676: Fix Issue With Category Name Casing

---

central/signatureintegration/datastore/telemetry.go
central/signatureintegration/datastore/telemetry_test.go

Add more signature integration metrics: total number of integrations with public keys, custom certificates and chains.
Unit tests.

ROX-28422: Signature integrations metrics: certs and keys totals

---

qa-tests-backend/src/test/groovy/SummaryTest.groovy

The Summary Service was removed in 4.7 making the compatibility tests fail in this branch. Removing the `COMPATIBILITY` tag to ignore this test in the compatibility step.
The `release-4.5` is not affected by this because back in 4.5 this test was skipped.

ROX-28680: Remove TopNav test from compatibility tests

---

.github/workflows/scripts/prepare-upgrade-test.sh

PR to update the upstream GHA automation with https://github.com/stackrox/test-gh-actions/pull/191.
Automated PR failed, because changes from 
* https://github.com/stackrox/stackrox/commit/b5beed513133fba7803f71f94a2834d5b3959e7d
* https://github.com/stackrox/stackrox/commit/1cbbf6990c5762d42bb04f99d3ff231ac2e22484
were not brought to the downstream/test-gh-actions scripts.

fix(ROX-28658): retry all Jira operations (#191)

---

roxctl/central/debug/debug.go
roxctl/central/initbundles/initbundles.go
roxctl/declarativeconfig/create/auth_provider.go
roxctl/maincommand/command_test.go
roxctl/netpol/connectivity/connectivity.go

Ensure short and long command descriptions are different and not both are empty.
Unit tests.

chore(roxctl): Fix and test some `roxctl` usage strings

---

operator/tools/controller-gen/go.mod
operator/tools/yq/go.mod
tests/performance/scale/go.mod
tools/test/go.mod

Some `go.mod` files from tests and tools have non standard formatting. I ran `go mod tidy` so that their formatting is consistent.
Minor style change, no testing needed.

chore: run go mod tidy in tools and tests modules

---

central/reports/scheduler/v2/reportgenerator/consts.go
central/reports/scheduler/v2/reportgenerator/report_gen_bench_test.go
central/reports/scheduler/v2/reportgenerator/report_gen_impl.go
central/reports/scheduler/v2/reportgenerator/report_gen_impl_test.go

Removed functions related to using graphql to query report data that is replaced with using select query framework
change me!
change me!

Removed functions related to using graphql to query report data

---

ui/apps/platform/config-overrides.js
ui/apps/platform/package-lock.json
ui/apps/platform/package.json

Updates to the latest version of Redoc to address the ticket in the title.
Smoke test of general UI.
Smoke test of Redoc API pages.
Verify that source map loading still works for our application files.

ROX-28759: Update to latest redoc

---

CHANGELOG.md
image/templates/helm/stackrox-central/internal/config-shape.yaml
image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
image/templates/helm/stackrox-central/templates/01-central-15-exposure.yaml
image/templates/helm/stackrox-central/templates/_init.tpl.htpl
image/templates/helm/stackrox-central/values-public.yaml.example.htpl

Add a Helm flag to add a reencrypt route on OpenShift clusters. The reencrypt route serves a certificate that was signed by the OpenShift CA.
Sadly I was not able to add unit tests because of outdated `route` API specifications in helmtest (see https://github.com/garethr/openshift-json-schema/issues/7). I imagine that is also the reason why there are no tests for the existing routes today.
Edit: I'll do follow ups for the official documentation and the operator CR.
see screenshot

ROX-28296: add OpenShift reencrypt route

---

pkg/sac/for_resource_helpers.go
pkg/sac/for_resource_helpers_test.go
pkg/sac/query_helper_test.go

Add helpers to check that a user has full access to a resource, and to filter the namespaces the user has access to.
The initial trigger is ROX-27669, which requires Vulnerability Management Approvers to have access to all deployed images with vulnerability data (see #14474 ).
CI

feat(sac): add helpers for resource global and namespace access

---

pkg/signatures/cosign_sig_verifier.go
pkg/signatures/cosign_sig_verifier_test.go

Backport of https://github.com/stackrox/stackrox/pull/14782.
change me!

ROX-28699: fix verification of multiple cosign signatures (#14782)

---

qa-tests-backend/scripts/run-compatibility.sh
qa-tests-backend/src/test/groovy/ReconciliationTest.groovy

The `ReconciliationTest` were deleting the sensor deployment and creating later on. This process does not work well with the CRS installation method as the created deployment will not be able to use the certificates issued for the previous one. This PR changes the logic in the test by scaling down/up the sensor deployment instead of deleting/creating it.

ROX-28714: Fix ReconciliationTest

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCveViewContext.ts
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/CreateOnDemandReportModal.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/CreateReportDropdown.tsx

This PR adds the "Create report" dropdown in the "User workloads", "Platform", "All vulnerable images", and "Inactive images" sections of VM. Clicking on the dropdown will allow you to create an on-demand report. A modal will open and allow you to trigger a report generation.
Manually tested

ROX-28472: Add create report dropdown in VM

---

image/rhel/konflux.Dockerfile

Triggered by https://github.com/stackrox/stackrox/pull/14489
No change.
Only Konflux build CI. If it passes, we're good.

build: Remove rocksdb dependencies from Konflux builder stage

---

central/auth/datastore/datastore_impl.go
central/auth/datastore/datastore_impl_test.go

* Remove need for `upserted` bool and second call to `configureConfigControllerAccess`
* Removed need to loop over configs twice in test by removing `getTestConfig`
* Made the test more precise by implementing a M2M config matcher for Kube SA

Update merge of configureConfigController

---

central/authprovider/telemetry/telemetry.go
central/debug/service/service.go
central/debug/service/service_test.go
central/graphql/resolvers/groups.go
central/group/datastore/datastore.go
central/group/datastore/datastore_impl.go
central/group/datastore/datastore_impl_test.go
central/group/datastore/internal/store/mocks/store.go
central/group/datastore/internal/store/postgres/gen.go
central/group/datastore/internal/store/postgres/store.go
central/group/datastore/internal/store/postgres/store_test.go
central/group/datastore/internal/store/store.go
central/group/datastore/mocks/datastore.go

---
- #14784
- #14781
- #14779
- #14778 :point_left: 
- #14763
- #14759
- #14758
- #14757
- #14747
- #14742
---
CI

ROX-28697: use Walk instead of GetAll in group

---

sensor/kubernetes/listener/resources/rbac/binding_fetcher.go
sensor/kubernetes/listener/resources/rbac/binding_fetcher_test.go

If the binding fetcher fails to grab the [Cluster]RoleBindings, sensor won't be able to enhance the deployments correctly potentially making us miss some violations. This is ok-ish because we have a reprocess mechanism that will trigger a reprocess of all deployments every 4h, so any violation missed will be triggered then. That being said, we could do better for short lived deployments. Also, the integrations tests will not wait for the reprocess to get triggered, so any error retrieving the bindings will make the test fail.
This PR introduces a retry logic in the binding fetcher to improve in the situations described above.

ROX-27959: Add retries in the binding fetcher

---

central/graphql/resolvers/generated.go
central/notifiers/email/email.go
generated/api/v1/notifier_service.swagger.json
generated/storage/notifier.pb.go
generated/storage/notifier_vtproto.pb.go
proto/storage/notifier.proto
proto/storage/proto.lock
ui/apps/platform/cypress/integration/integrations/notifiers.test.js
ui/apps/platform/src/Components/EmailNotifier/EmailNotifierForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/EmailIntegrationForm.tsx

[Request](https://github.com/stackrox/stackrox/issues/14172)
Manually on GKE cluster

ROX-28250: Setting InsecureSkipVerify in tlsConfig for email notifier

---

central/compliance/data/repository.go
central/debug/service/service.go
central/debug/service/service_test.go
central/graphql/resolvers/notifiers.go
central/notifier/datastore/datastore.go
central/notifier/datastore/datastore_impl.go
central/notifier/datastore/datastsore_test.go
central/notifier/datastore/internal/store/mocks/store.go
central/notifier/datastore/internal/store/postgres/gen.go
central/notifier/datastore/internal/store/postgres/store.go
central/notifier/datastore/internal/store/postgres/store_test.go
central/notifier/datastore/internal/store/store.go
central/notifier/datastore/mocks/datastore.go
central/notifier/datastore/telemetry.go
central/notifier/processor/singleton.go
central/notifier/service/service_impl.go
central/policy/handlers/handler.go
central/policy/handlers/handler_test.go
qa-tests-backend/src/main/groovy/services/NotifierService.groovy
qa-tests-backend/src/test/groovy/IntegrationsTest.groovy

---
- #14784
- #14781
- #14779
- #14778
- #14763 :point_left: 
- #14759
- #14758
- #14757
- #14747
- #14742
---
CI

ROX-28697: use Walk instead of GetAll in notifier

---

.github/actions/job-preamble/action.yaml
.openshift-ci/begin.sh
scripts/ci/lib.sh
scripts/ci/metrics.sh

Two main things:
- Dealing with SQL injections per https://redhat-internal.slack.com/archives/C0321S70YK1/p1742320757786619
- Populating `ci_system` per https://redhat-internal.slack.com/archives/C0321S70YK1/p1742319210220179?thread_ts=1731937635.189999&cid=C0321S70YK1
For everything else I suggest reviewing this PR by commits where I provided explanations and justifications in commit messages.
Please tell me how can I dry-run my changes to `slack_top_n_failures`. I found no way to launch it.
No change.

chore: Improve BigQuery metrics

---

central/graphql/resolvers/node_cve_core_test.go
central/graphql/resolvers/resource_count_by_severity.go
central/views/common/db_response.go
central/views/common/empty.go
central/views/common/queries.go
central/views/common/types.go
central/views/imagecve/db_response.go
central/views/imagecve/view_impl.go
central/views/imagecve/view_test.go
central/views/nodecve/db_response.go
pkg/search/options.go

The counts on the UI are sometimes off leading to confusion because we do not account for the possibility of receiving CVEs of `unknown` severity.   Basically the total count of CVEs in the table may differ from the totals in the cards because the cards are not accounting for all possible severities.  This PR updates the backend so that the UI can then update the cards.
Added a unit test.

ROX-28895: backend changes to account for unknown CVE severity

---

central/cve/converter/utils/convert_utils_v2_test.go
central/graphql/resolvers/image_components.go
central/graphql/resolvers/image_components_v2_postgres_test.go
central/image/datastore/store/common/v2/merge_v2.go
central/image/datastore/store/common/v2/parts_test.go
central/image/datastore/store/common/v2/split.go
central/image/datastore/store/common/v2/split_v2.go
central/image/datastore/store/postgres/store.go
central/image/datastore/store/v2/postgres/store.go
central/views/imagecveflat/view_test.go
generated/storage/image.pb.go
pkg/images/enricher/enricher_impl.go
pkg/scancomponent/component_id.go
proto/storage/image.proto

There is a possiblity that a component of the same name can occur various times within the same image.  Things like location, etc can vary.  In those case we should store those as separate components within image.  Since we don't support composite keys particularly well, in order to do this we need to create a hash of the object to make sure we are dealing with a duplicate vs a similar component.  
CVE will undergo a similar exercise in a separate PR to keep the review noise down.
Updated many unit tests.  Started a cluster to ensure everything worked.

ROX-27399:  cdm component ID using hash

---

pkg/objects/deployments.go

Remove unused function and preallocate memory.
CI

fix: cleanup objects deployments

---

scripts/ci/lib.sh

Quick fix, which needs more understanding.
CI
```
INFO: Fri Mar 28 10:46:44 UTC 2025: Getting a central debug dump
INFO:	Retrieving debug metrics. This may take a couple of minutes...
INFO:	Successfully wrote debug zip file to "debug-dump/stackrox_debug_2025_03_28_10_46_44.zip"
total 568
```

ROX-28673: Fix central certificate usage in `ci/lib.sh`

---

CHANGELOG.md
ui/apps/platform/cypress/integration/integrations/signatureIntegrations.test.js
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/SignatureIntegrationForm.tsx
ui/apps/platform/src/types/signatureIntegration.proto.ts

Add the UI for the Rekor transparency log integration to the signature verification form. See #14609 for the backend changes. I opted for `helperText` instead of pop overs for the explanations to avoid making users click unnecessarily. I also think it looks a bit nicer without the pop over buttons. Let me know if that is acceptable or if you prefer the pop over style helper texts.
Note that I had some issues with the `TextArea` components being minimized despite containing values. This happens when editing an existing integration (on creation the min size is rendered correctly). I'd appreciate some advise from the UI experts here :) 
see screenshots

ROX-28577: rekor log integration UI

---

pkg/helm/charts/tests/centralservices/testdata/helmtest/openshift-routes.test.yaml

Wait for https://github.com/stackrox/helmtest/pull/160 to be merged.
CI

chore: add helm tests for routes

---

pkg/mtls/ca.go
pkg/mtls/ca_test.go

This PR simplifies `LoadCAForSigning` and `LoadCAForValidation` by eliminating the `loadCA` helper and directly handling the CA logic within each function. It also adds a test for `LoadCAForValidation`.
Related to [ROX-27962](https://issues.redhat.com/browse/ROX-27962)
Refactor, automated tests should be sufficient.

refactor(ca): LoadCA clean-up, improve testing coverage

---

tests/e2e/lib.sh

`record_upgrade_test_progess` still had references to rocksdb variables.  Those variables are unbound because they no longer exist.
CI changes only

chore: remove legacy rocksdb vars from upgrade test post processing

---

central/graphql/resolvers/image_cve_core.go
central/views/imagecve/singleton.go
central/views/imagecve/view_impl.go
central/views/imagecve/view_test.go

Initial implementation of the new data model attempted to avoid the use of performance workaround the old model used.  For instance only use the one aggregation that is being sorted on to get the IDs, and then use the IDs to calculate the other aggregations for that page of data only.  So all aggregations are only performed on a subset of the data instead of all of the data.
CI.  Separate ticket to fix the UT for this that was broken elsewhere.
Applied this image to a long running cluster that has been up for days.  Loaded the impacted page and ensured the data loaded MUCH more quickly.
Performance testing will continue and future data will be collected.  For now this was a visual validation and visual was plenty as it was obviously faster.

ROX-29050: cdm CVE view faster

---

scripts/ci/get-slack-user-id.sh

chore: Enable tagging guzalv in slack notifications

---

pkg/search/postgres/store.go

Extracted from:
- https://github.com/stackrox/stackrox/pull/14949
---
CI

ROX-28941: use RunQueryForSchemaFn in GetMany

---

qa-tests-backend/scripts/images-to-prefetch.txt
qa-tests-backend/src/main/groovy/services/SignatureIntegrationService.groovy
qa-tests-backend/src/test/groovy/ImageSignatureVerificationTest.groovy

Add qa-e2e tests for keyless cosign verification using a custom RHTAS instance. The RHTAS instance is hosted on our staging-central cluster.
CI

ROX-28854: add qa-e2e for RHTAS

---

central/clusterinit/backend/backend_impl.go
central/clusterinit/store/postgres/gen.go
central/clusterinit/store/postgres/store.go
pkg/postgres/schema/cluster_init_bundles.go
pkg/sac/resources/list.go
tools/generate-helpers/pg-table-bindings/resource_type_test.go

In order to remove the concept of permission checker at store and query generation level, the instances of permission checker types are getting removed.
This PR focuses on removing the permission checker for cluster init bundles.
Refactor. The CI should cover the behaviour.
CI

ROX-28314: Replace InitBundles permissionChecker w/ internal resource

---

CHANGELOG.md
central/graphql/resolvers/image_vulnerabilities_test.go
central/graphql/resolvers/test_setup_utils.go
central/graphql/resolvers/vulnerability_requests_test.go
central/namespace/datastore/datastore_test_constructors.go
central/pruning/pruning_vuln_req_test.go
central/vulnmgmt/vulnerabilityrequest/datastore/datastore.go
central/vulnmgmt/vulnerabilityrequest/datastore/datastore_impl.go
central/vulnmgmt/vulnerabilityrequest/datastore/datastore_impl_test.go
central/vulnmgmt/vulnerabilityrequest/datastore/singleton.go
central/vulnmgmt/vulnerabilityrequest/manager/querymgr/query_manager_impl_test.go
central/vulnmgmt/vulnerabilityrequest/manager/requestmgr/manager_impl_benchmark_test.go
central/vulnmgmt/vulnerabilityrequest/manager/requestmgr/manager_impl_create_req_test.go
central/vulnmgmt/vulnerabilityrequest/manager/requestmgr/manager_impl_reobserve_test.go
central/vulnmgmt/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go
pkg/sac/for_resource_helpers.go
pkg/sac/for_resource_helpers_test.go
pkg/sac/query_helper_test.go

Backported fix for ROX-27669 from PRs #14474 and #14540 
Manual test by creating a deferral and trying to approve with roles having different scopes and permissions

ROX-27669 : backport fix in #14474 and #14540 to 4.7 branch

---

qa-tests-backend/src/main/groovy/services/ComplianceManagementService.groovy

fix ComplianceTest by retrying compliance call.
See:
- https://github.com/stackrox/stackrox/pull/15087

ROX-28904: fix ComplianceTest

---

deploy/common/k8sbased.sh
deploy/common/sensor-local-patch.yaml

We have problems fitting ACS stack on GKE during race tests. The problem manifests in that collector pods can not be deployed to a cluster. Even if colloctor is using only 0.06 cores - sometimes we do not have 0.06 cores available on a node. (one failed test had 3.88 cores requested, where 3.92 is available - 0.06 can not fit there)
One of the largest containers with CPU requests is sensor (2 cores). The largest utilization for sensor is ~0.8 cores for race tests. Setting CPU request below that should not make any problems for sensor stability in this test, because the actual node utilization is low.
This PR simply applies the same CPU request customization to sensor as for any other test.
**Changes:**
- removed code duplication
- added a dedicated YAML file for a patch. Similar to …

ROX-28371: Reduce sensor CPU request in tests

---

qa-tests-backend/src/main/groovy/services/ProcessService.groovy

Retry ProcessService calls to fix issues related to networking errors.
See:
- https://github.com/stackrox/stackrox/pull/15086

ROX-28921: retry in ProcessService

---

ui/apps/platform/cypress/integration/configmanagement/deployments.test.js
ui/apps/platform/src/Containers/ConfigManagement/Entity/Deployment/DeploymentFindings.tsx
ui/apps/platform/src/Containers/ConfigManagement/Entity/widgets/FailedPoliciesAcrossDeployment.tsx
ui/apps/platform/src/Containers/Workflow/widgets/ViolationsAcrossThisDeployment.js

Manual backport of #15017 to 4.7 because of a failed cherry-pick and file name conflict.
change me!

fix(ui): Backport 15017 to release 4.7

---

central/networkgraph/entity/datastore/datastore_impl.go

Address review comments from #14965 
Basic refactor. CI should cover the cases.
CI

chore: better readability in netentity datastore context management

---

central/cve/image/v2/datastore/datastore.go
central/cve/image/v2/datastore/datastore_sac_test.go
central/graphdb/testutils/datastore.go
central/graphdb/testutils/graphdump.go
central/imagecomponent/v2/datastore/datastore_sac_test.go
pkg/postgres/pgtest/postgres.go

Simple adds in datastore sac tests to the v2 CVE and Component datastores that could not be updated because the data required a working image store first.  
CI

ROX-28188: cve and component datastore tests

---

central/views/imagecve/view_test.go

After the CVE ID was updated, the CVE view test no longer worked with the flag enabled.  This PR fixes the test by using the new IDs to calculate the matches.
test changes only.

ROX-29053: fix CVE View test after updates to the ids

---

scanner/updater/version/VULNERABILITY_BUNDLE_VERSION

In prep for the 4.7.3 release, update VULNERABILITY_BUNDLE_VERSION per release instructions
None added
CI

chore: Update vuln bundle version to 4.7.3

---

.github/workflows/cut-rc.yml

Cut RC release workflow failing to create long running clusters: https://github.com/stackrox/stackrox/actions/runs/14741159820/job/41458128600#step:1:52
This PR should help address that failure.
change me!

fix: long running cluster name

---

tests/e2e/run-scanner-v4-install.bats

ROX-28514, to be in sync with the image prefetcher. Since the [image prefetches uses `quay.io/rhacs-eng`](https://github.com/stackrox/stackrox/blob/76d18648e9e4fa3548258f82079a464794d1124b/scripts/ci/lib.sh#L494) we should be using the same to actually benefit from the image prefetching.
CI plus manual execution of the test suite.

ROX-28514: Set DEFAULT_IMAGE_REGISTRY to quay.io/rhacs-eng

---

operator/internal/central/extensions/common_test.go

This PR extracts several functions from the test helper `testSecretReconciliation`, for clarity and future reuse.
It is intended as a pre-factor for [ROX-27962](https://issues.redhat.com/browse/ROX-27962) but can be seen as an independent refactor as well.
Existing tests should be enough.

refactor(test): extract helper functions from testSecretReconciliation

---

.github/workflows/unit-tests.yaml

Per title.
See https://redhat-internal.slack.com/archives/CC5UHD0KA/p1745397407589049
This PR is about enabling tests themselves.
1. Looked at the CI results.
2. Induced test failure in <https://github.com/stackrox/stackrox/pull/15149>:
1. https://github.com/stackrox/stackrox/actions/runs/14793190280?pr=15149#summary-41534579206
2. https://github.com/stackrox/stackrox/actions/runs/14793190280/job/41534579206?pr=15149#step:6:836
3. https://issues.redhat.com/browse/ROX-29155

ROX-29154: Add UI Component tests to GHA

---

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/OnDemandReportsTab.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/OnDemandReportsTable.tsx
ui/apps/platform/src/services/ReportsService.ts
ui/apps/platform/src/services/ReportsService.types.ts

This PR adds the table for the on-demand reports in the on-demand reports tab. A few missing pieces will come in future PRs. I left some comments in the code.
Manual checking

ROX-28474: Adding on demand reports table

---

operator/internal/securedcluster/scanner/auto_sense.go
operator/internal/securedcluster/scanner/auto_sense_test.go

As has been discussed already, there is no convincing argument (anymore?) for restricting the local scanner functionality to OCP when deploying using the operator.
With this change in place one can happily connect to a GKE cluster and use
```
make -C operator install run
```
for letting the operator reconcile SecuredCluster CRs with local scanning enabled.
This is not a customer-facing change, because we don't ship operator for non-OCP.
change me!

ROX-28669: Do not restrict enabling of local scanners to OCP

---

migrator/migrations/m_189_to_m_190_vulnerability_requests_add_name/schema/new/vulnerability_requests.go
migrator/migrations/m_189_to_m_190_vulnerability_requests_add_name/schema/old/vulnerability_requests.go
migrator/migrations/m_189_to_m_190_vulnerability_requests_add_name/store/previous/store.go
migrator/migrations/m_189_to_m_190_vulnerability_requests_add_name/store/updated/store.go
migrator/migrations/m_191_to_m_192_vulnerability_requests_searchable_scope/schema/new/vulnerability_requests.go
migrator/migrations/m_191_to_m_192_vulnerability_requests_searchable_scope/schema/old/vulnerability_requests.go
migrator/migrations/m_191_to_m_192_vulnerability_requests_searchable_scope/store/previous/store.go
migrator/migrations/m_191_to_m_192_vulnerability_requests_searchable_scope/store/updated/store.go
migrator/migrations/m_201_to_m_202_vuln_request_v1_to_v2/schema/vulnerability_requests.go
migrator/migrations/m_201_to_m_202_vuln_request_v1_to_v2/store/store.go
migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/schema/vulnerability_requests.go
migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/store/vulnerabilityrequests/store.go

As per title
Refactor, the CI should cover
CI

chore(sac): use new resource for migration VM stores & schemas

---

central/views/imagecve/view_impl.go
central/views/imagecveflat/view_impl.go
pkg/search/derivationtype_string.go
pkg/search/options.go
pkg/search/postgres/pagination.go
pkg/search/postgres/query/common.go

This fixes the riskiest images dashboard.  If time allows after things are working, the flat CVE queries will be refactored to be more sustainable.
manually tested and verified widget works.

ROX-29109:  cdm riskiest dashboard

---

migrator/migrations/m_189_to_m_190_vulnerability_requests_add_name/store/previous/store.go
migrator/migrations/m_189_to_m_190_vulnerability_requests_add_name/store/updated/store.go
migrator/migrations/m_191_to_m_192_vulnerability_requests_searchable_scope/store/previous/store.go
migrator/migrations/m_191_to_m_192_vulnerability_requests_searchable_scope/store/updated/store.go
migrator/migrations/m_197_to_m_198_add_oidc_claim_mappings/store/authproviders/store.go
migrator/migrations/m_197_to_m_198_add_oidc_claim_mappings/store/groups/store.go
migrator/migrations/m_200_to_m_201_compliance_v2_for_4_5/stores/rules/store.go
migrator/migrations/m_200_to_m_201_compliance_v2_for_4_5/test/stores/profiles/store.go
migrator/migrations/m_200_to_m_201_compliance_v2_for_4_5/test/stores/results/store.go
migrator/migrations/m_200_to_m_201_compliance_v2_for_4_5/test/stores/rules/store.go
migrator/migrations/m_200_to_m_201_compliance_v2_for_4_5/test/stores/scans/store.go
migrator/migrations/m_201_to_m_202_vuln_request_v1_to_v2/store/store.go
migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/store/imagecveedges/store.go
migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/store/imagecves/store.go
migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/store/images/store.go
migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/store/vulnerabilityrequests/store.go

Follow-up (step 2) for review comment on #14389 
Refactor, CI should cover
CI

refactor: use globally scoped store constructor for migrations

---

scripts/ci/gke.sh

To prevent kubelet from garbage-collecting pre-fetched images. See https://issues.redhat.com/browse/ROX-29118
CI

chore: double GKE disk size

---

pkg/search/postgres/store.go
pkg/search/postgres/store_cache_test.go
pkg/search/postgres/store_test.go

Follow-up (step 3) for review comments on #14389 
Refactor, CI should cover.
CI

refactor: unexport postgres store globally scoped upsert checker

---

scripts/ci/jobs/gke_external_pg_17_qa_e2e_tests.py

This PR creates a base test for PG17. It's here to tests if prow configuration is correct and tests runs. After merge it will be extended with external db installation.
- https://github.com/openshift/release/pull/63992
---
CI

ROX-27583: Create a test script

---

sensor/tests/helper/helper.go

We are facing GKE instability from time to time. Because of that, we should make our tests resilient to networking or cluster instability.
This PR addresses one issue with `namespace` creation. We already have retry logic for some resource types, but they are not ready for 5 minutes of downtime.

ROX-28418: Add retry for namespace creation

---

.github/workflows/check-crd-compatibility.yaml

Depends on https://github.com/stackrox/stackrox/pull/15192
Heavily based on @JoukoVirtanen 's https://github.com/stackrox/stackrox/pull/10288 who gets all the credit for the heavy lifting!
See individual commits which describe changes since that PR:
- fix job-preamble call and volumes to work with current version
- use replaced version not a future release (tag numbering changed recently)
- pin schema checker to avoid surprises, it's recent enough to rejects both field and enum values removals
- shorten commands using some shell variables
- check the config CRD too (but not fail for now, since it's already broken - I reported this to the relevant team but we don't need to block this PR on the fix)
- disable the style checks which we already violate and some violations which we can fix …

tests: check CRD compatibility to previous release

---

ui/apps/platform/cypress/integration/configmanagement/deployments.test.js
ui/apps/platform/src/Containers/ConfigManagement/Entity/Deployment/DeploymentFindings.tsx
ui/apps/platform/src/Containers/ConfigManagement/Entity/widgets/FailedPoliciesAcrossDeployment.tsx
ui/apps/platform/src/Containers/Workflow/widgets/ViolationsAcrossThisDeployment.js

Manual cherry-pick of #15017 to 4.6
change me!

fix(ui): Manual Backport 15017 to release 4.6

---

scripts/release-tools/kube-burner-configs/berserker-load/connection-load-deployment.yml
scripts/release-tools/kube-burner-configs/berserker-load/endpoint-load-deployment.yml
scripts/release-tools/kube-burner-configs/berserker-load/process-load-deployment.yml

The berserker log level was set to debug. This removes the log level environment variable for berserker, so the log level should be set to the default.
change me!

fix(berserker): Change berserker log level

---

central/views/imagecveflat/view_impl.go

Applying the same filter used in image cve view to image cve flat view.  It should limit the number of aggregations performed and improve performance.  
Note:  Further testing will occur after this is merged and in a nightly so it can easily be provisioned into a long running cluster.
brought up and made sure results were valid.  Will test further performance in a long running cluster after merging.

ROX-29051: cdm more faster

---

central/graphql/resolvers/plotted_image_vulnerabilities.go

Certain dashboards and widgets pull data from plotted vulnerabilities.  Those need to use use the new data model.  This changes updates the plotted vulns to pull and return that data.
Brought up a cluster and verified the dashboards populated as expected.

ROX-29131: cdm plotted vuln

---

central/views/imagecveflat/view_impl.go

Reverting this because it is incomplete and breaks some widgets and sorts.
CI

ROX-29051: cdm revert faster

---

pkg/networkgraph/externalsrcs/id_test.go

Looks like this part of code is not tested. Let's add a test to it.
change me!

tests: add tests for externalsrcs ids

---

ui/apps/platform/cypress/integration/systemConfig/systemConfig.selectors.js
ui/apps/platform/src/Containers/SystemConfig/Details/PlatformComponentsConfigDetails.css
ui/apps/platform/src/Containers/SystemConfig/Details/PlatformComponentsConfigDetails.tsx
ui/apps/platform/src/Containers/SystemConfig/Details/SystemConfigDetails.tsx
ui/apps/platform/src/types/config.proto.ts

This PR displays the platform components configuration in the details view. Some things, not in this PR, that will come in subsequent PRs:
1. Clicking on "View more" will show a modal to display the full rule (or rules for custom components)
2. Editing the Platform Components Configuration
TBD

ROX-28170: Adding a platform components configuration details section

---

central/views/imagecveflat/view_impl.go
pkg/search/options.go

I broke the queries when I put in the pre-fetching because sort columns are properly added to the select because what we want to sort on is an aggregation.  So have to put in some custom logic there.  
change me!

ROX-29226:  cdm speed broke sort

---

qa-tests-backend/src/test/groovy/VulnMgmtTest.groovy
qa-tests-backend/src/test/groovy/VulnScanWithGraphQLTest.groovy

(cherry picked from commit a9e9a9bf204b6ff4b6a776012dd7b091d9855546)
Backporting to fix:
N/A
CI

chore: fix e2e tests and upd scanner version (#15160)

---

go.mod
go.sum

This PR updates github.com/np-guard/netpol-analyzer from v1.4.2 to v1.4.4
- The new version contains a minor update to the report with the new explain flag (that was added in v1.4.2).
- Ran bats tests locally and in CI
- Ran locally manual smoke tests

chore(deps): bump np-guard/netpol-analyzer from v1.4.2 to v1.4.4

---

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx

Adds the ability to select "Unknown" severity when configuring VM reports.

ROX-29017: Add ability to select 'Unknown' vuln severity in reports

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AdvisoryLinkOrText.tsx
ui/apps/platform/src/types/cve.proto.ts

Frontend counterpart to (future) backend changes described in https://github.com/stackrox/stackrox/pull/15100#discussion_r2085332552
1. Scanner is source of truth for advisory link.
2. Central stores advisory and provides it to roxctl and UI.
3. UI renders advisory in sub-table components:
* `DeploymentComponentVulnerabilitiesTable`
* `ImageComponentVulnerabilitiesTable`
Follow naming pattern in recent change from single string property to object that has pair of string properties:
```ts
// epss property is null if not available
export type EPSS = {
epssProbability: number; // float fraction between 0 and 1 inclusive
epssPercentile: number; // float fraction between 0 and 1 inclusive
};
```
1. Edit AdvisoryLinkOrText.tsx file to update rendering:
* `advisory: null | undefined` as hyphen …

ROX-29228: Add Advisory type and update AdvisoryLinkOrText component

---

.github/CODEOWNERS

Add cloud sources and image signature qa-e2e tests to `sensor-ecosystem`.
CI

chore: update sensor-ecosystem code owners entry

---

generated/storage/compliance_operator_v2.pb.go
generated/storage/compliance_operator_v2_vtproto.pb.go
proto/storage/compliance_operator_v2.proto
proto/storage/proto.lock

Storage proto changes to add the information of failed clusters when a report is generated.
- depends on #13361
- The entire functionality is tested in #15232

ROX-27490: Add failed clusters to storage protos

---

scripts/ci/lib.sh
scripts/ci/roxctl.sh
scripts/grab-data-from-central.sh
tests/e2e/lib.sh

Reset the incorrectly set server name when calling roxctl.
CI

ROX-28673: an attempt to quickly fix nightly CI

---

.tekton/central-db-build.yaml
.tekton/main-build.yaml
.tekton/operator-build.yaml
.tekton/operator-bundle-build.yaml
.tekton/retag-collector.yaml
.tekton/retag-scanner-db-slim.yaml
.tekton/retag-scanner-db.yaml
.tekton/retag-scanner-slim.yaml
.tekton/retag-scanner.yaml
.tekton/roxctl-build.yaml
.tekton/scanner-v4-build.yaml
.tekton/scanner-v4-db-build.yaml

Announcement: https://groups.google.com/a/redhat.com/g/konflux-announce/c/NxOyzi8wGxo/m/QXRGc1QqCQAJ
Konflux pipelines pass.

ROX-29078: Switch to per component service account

---

.github/workflows/check-crd-compatibility.yaml

Should be good now that the checks pass:
- https://github.com/stackrox/stackrox/pull/15223
CI is enough

ROX-29203: fail on config CRD check failures

---

central/networkgraph/flow/datastore/internal/store/postgres/store.go

Ephemeral PR to stack enhancements and get builds.

ROX-26854: Addition enhancements for External-IPs pruning

---

pkg/signatures/factory.go

Parallelize signature verification when multiple signature integrations are configured.
```
goos: darwin
goarch: amd64
pkg: github.com/stackrox/rox/pkg/signatures
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
│    control    │        parallel-integrations         │
│    sec/op     │    sec/op      vs base               │
VerifyAgainstSignatureIntegrations/numInt=1,_numSig=1,_verifyBundle=false-12        99.61µ ± 15%   130.11µ ± 20%  +30.62% (p=0.009 n=6)
VerifyAgainstSignatureIntegrations/numInt=1,_numSig=1,_verifyBundle=true-12         5.218m ± 10%    5.122m ±  5%        ~ (p=1.000 n=6)
VerifyAgainstSignatureIntegrations/numInt=1,_numSig=5,_verifyBundle=false-12        430.2µ ±  2%    441.1µ ±  3%   +2.54% (p=0.002 n=6)
VerifyAgainstSignatureIntegrations/numInt=1,_numSig=5,_verifyBundle=t …
```

ROX-28720: parallelize signature verification per integration

---

pkg/signatures/cosign_sig_verifier.go

Parallelize signature verification when a container image is associated with multiple signatures. This is relevant for many images including OpenShift platform images, many of which currently have 4 signatures.
```
goos: darwin
goarch: amd64
pkg: github.com/stackrox/rox/pkg/signatures
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
│    control    │        parallel-integrations         │          parallel-verifiers          │
│    sec/op     │    sec/op      vs base               │    sec/op      vs base               │
VerifyAgainstSignatureIntegrations/numInt=1,_numSig=1,_verifyBundle=false-12        99.61µ ± 15%   130.11µ ± 20%  +30.62% (p=0.009 n=6)   115.15µ ±  1%  +15.60% (p=0.004 n=6)
VerifyAgainstSignatureIntegrations/numInt=1,_numSig=1,_verifyBundle=true-12         5.218m ± 10% …
```

ROX-28720: parallelize signature verifiers

---

scripts/retry-kubectl.sh

Example error that this change is trying to start retrying:
```
+ ./hack/olm-operator-install.sh stackrox-operator quay.io/rhacs-eng/stackrox-operator-index v4.8.0-505-gde105b0fb1 v4.6.0 latest
2025-04-17T09:02:43Z Creating namespace...
error: error validating "STDIN": error validating data: failed to download openapi: Get "https://api.rox-ci-65735424.ocp.ci.rox.systems:6443/openapi/v2?timeout=32s": EOF; if you choose to ignore these errors, turn validation off with --validate=false
make: *** [Makefile:386: deploy-previous-via-olm] Error 1
make: Leaving directory '/go/src/github.com/stackrox/stackrox/operator'
****
**** 09:03:10: ERROR: test failed [Test failed: exit 2]
```
The alternative would be to retry `: EOF` but I'd rather take baby steps...
ran the `error_regex=` snippet and the …

ROX-29014: retry more kubectl errors

---

pkg/signatures/cosign_sig_fetcher.go
pkg/signatures/factory.go

Slight refactor of the signature fetching logic to make use of `SliceUnique` instead of re-implementing a similar logic on the fly.
CI

refactor(signatures): use SliceUnique in signature fetch

---

qa-tests-backend/src/main/groovy/objects/Namespace.groovy
qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
qa-tests-backend/src/test/groovy/CSVTest.groovy
qa-tests-backend/src/test/groovy/NamespaceTest.groovy

This PR improves assertions in `NamespaceTest`. Instead of reporting a single issue it will check all requirements.
See: https://www.jetbrains.com/guide/java/tutorials/writing-tests-with-spock/verify-all/
CI

ROX-28831: improve NamespaceTest assertion

---

qa-tests-backend/src/test/groovy/AutocompleteTest.groovy
qa-tests-backend/src/test/groovy/CSVTest.groovy
qa-tests-backend/src/test/groovy/VulnMgmtTest.groovy
qa-tests-backend/src/test/groovy/VulnMgmtWorkflowTest.groovy
qa-tests-backend/src/test/groovy/VulnScanWithGraphQLTest.groovy
tests/e2e/lib.sh

Turn on the new CVE Data Model flag in CI.
- A couple of tests needed to be updated
- A couple of tests require more extensive updates due to the fact that they build IDs which is no longer feasible.  So those tests will need to be updated to do the same thing differently.  Tickets have been created for those and referenced in the TODO where they are ignored.
Changes only to CI so CI is sufficient.

ROX-28897: turn on new CVE data model flag in CI

---

ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTableHeaderText.tsx
ui/apps/platform/src/Containers/NetworkGraph/components/FlowTable.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/ExternalFlows.tsx
ui/apps/platform/src/Containers/NetworkGraph/hooks/useNetworkBaselineStatus.ts
ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.ts
ui/apps/platform/src/services/NetworkService.js
ui/apps/platform/src/types/networkBaseline.proto.ts

ROX-28881: Split deployment external flows into anomalous and baseline

---

pkg/grpc/codec.go
pkg/grpc/codec_test.go

This PR wrap errors that occured in grpc codec to get more information what failed exactly.
CI

chore(grpc): wrap errors in codec

---

.openshift-ci/ci_tests.py
image/postgres/scripts/docker-entrypoint.sh
image/postgres/scripts/init-entrypoint.sh
tests/e2e/lib.sh
tests/upgrade/lib.sh
tests/upgrade/postgres_upgrade_run.sh

Add set of knobs needed to steer upgrade process.
E2E test for the PostgreSQL upgrade procedure.
Manual testing those tests against an infra cluster, plus running them on CI.

ROX-20769: Configuration for PG major version upgrade and E2E test

---

ui/apps/platform/src/Containers/NetworkGraph/api/useModifyBaselineStatuses.ts
ui/apps/platform/src/Containers/NetworkGraph/components/FlowTable.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx
ui/apps/platform/src/Containers/NetworkGraph/deployment/ExternalFlows.tsx
ui/apps/platform/src/Containers/NetworkGraph/hooks/useNetworkBaselineStatus.ts

Adds IP/CIDR search filtering to the External Flows section in Network Graph

ROX-29440: Network graph external flows filtering

---

qa-tests-backend/src/test/groovy/AutocompleteTest.groovy

We don't need to run Autocomplete tests as part of version compatibility tests as search service is not used by sensor.
Passing CI should be enough

ROX-29434: Remove AutocompleteTest from version compatability tests suite

---

pkg/features/list.go

My IDE keeps highlighting some texts in yellow and I try to correct the obvious typos as I go. Here are two of them.
I haven't

chore(typos): Fix random text typos

---

sensor/common/compliance/command_handler_impl.go
sensor/common/compliance/service_impl.go
sensor/common/detector/detector.go
sensor/common/scannerclient/reset_notifiable.go
sensor/kubernetes/clusterhealth/updater.go
sensor/kubernetes/clustermetrics/cluster_metrics.go
sensor/kubernetes/clusterstatus/updater.go
sensor/kubernetes/complianceoperator/updater.go
sensor/kubernetes/telemetry/command_handler.go

For debugging purposes. Ensure consistent tracing of the sensor event propagation.
This should help investigation of offline/online mode switches.
Testing this logging would require refactoring the structure of the components to allow for injection of mock loggers, then the addition of unit tests that currently do not bring a significant value on functional coverage.

chore(sensor): make sensor event logging consistent across components

---

image/templates/helm/stackrox-central/templates/01-central-15-exposure.yaml

I initially thought that we should couple the passthrough route to the reencrypt route because of Sensor communication. But a user may want to configure the reencrypt route independently of the passthrough routes - for example, if there a different mechanism for Sensor connection is already established. Therefore I think it would be more convenient to be able to enable the reencrypt route without also enabling the passthrough routes.
CI

fix: decouple passthrough and reencrypt routes

---

central/complianceoperator/v2/report/errors.go
central/complianceoperator/v2/report/manager/manager_impl.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher_test.go
central/complianceoperator/v2/report/manager/watcher/validator.go
central/complianceoperator/v2/report/manager/watcher/validator_test.go

Validate the `ScanResults` and generate the `failedClusters` map.
- depends on #15201
- The entire functionality is tested in #15232

ROX-27490: Validate Results

---

.tekton/central-db-build.yaml
.tekton/main-build.yaml
.tekton/operator-build.yaml
.tekton/operator-bundle-build.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/retag-collector.yaml
.tekton/retag-pipeline.yaml
.tekton/retag-scanner-db-slim.yaml
.tekton/retag-scanner-db.yaml
.tekton/retag-scanner-slim.yaml
.tekton/retag-scanner.yaml
.tekton/roxctl-build.yaml
.tekton/scanner-v4-build.yaml
.tekton/scanner-v4-db-build.yaml

Per title and ticket.
Update the references in operator-bundle as well.
Passing CI suffices.

ROX-29479: switch to custom Konflux quay.io repositories

---

central/complianceoperator/v2/scanconfigurations/service/convert.go
central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go

- depends on #15231
This PR populates the `v2` protos with the `FailedClusters`.
- Deploy in two clusters with Compliance Operator
- Create a Scan Schedule with both cluster
- Make one of the scans fail mid scan (e.g. disconnect sensor from central)
- Query central API and observe the status is set to PARTIAL ERROR

ROX-26974: Populate API fields

---

pkg/scannerv4/mappers/mappers.go
pkg/scannerv4/mappers/mappers_test.go

fixed in version in format of introduced=9.0.13&lastAffected=9.0.62 doesn't provide anything useful, so set it as empty
Unit tests added, let me know if manual tests are needed although I think unit tests are good enough.

ROX-29284: set last affected as empty fixed by version

---

ui/apps/platform/src/Components/ReportJob/JobStatusPopoverContent.tsx
ui/apps/platform/src/Components/ReportJob/MyLastJobStatus.test.tsx
ui/apps/platform/src/Components/ReportJob/ReportJobStatus.test.tsx
ui/apps/platform/src/Components/ReportJob/ReportJobStatus.tsx
ui/apps/platform/src/Components/ReportJob/ReportJobStatusFilter.test.tsx
ui/apps/platform/src/Components/ReportJob/ReportJobStatusFilter.tsx
ui/apps/platform/src/Components/ReportJob/types.ts
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsTablePage.tsx
ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/ConfigReportsTab.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/OnDemandReportsTab.tsx

This PR refactors the labels used in report jobs for both Compliance Reporting and Vulnerability Reporting to improve clarity.
Based on Mansur's proposal

ROX-29491: Refactoring compliance report job labels

---

ui/apps/platform/src/Components/ReportJob/PartialReportModal.tsx
ui/apps/platform/src/services/ComplianceScanConfigurationService.ts

This PR just adds frontend-only pagination for the failed clusters table for partial reporting.
change me!

ROX-29490: Adding pagination for failed clusters table

---

ui/apps/platform/src/Containers/MainPage/Navigation/NavigationSidebar.tsx

1. Update page components for consistency:
* breadcrumb
* heading
* title
1. Visit /main/compliance/coverage
* Before changes:
See **Coverage** and presence of **Tech preview** label
See **Schedules** and presence of **Tech preview** label
See **Dashboard** and absence of label
* After changes, see
See **OpenShift Coverage** and absence of label
See **OpenShift Schedules** and absence of label
See **Dashboard** and presence of **Deprecated** label

ROX-29443: Update NavigationSidebar for Compliance GA

---

ui/apps/platform/src/Containers/SystemConfig/Form/PlatformComponentsConfigForm.tsx
ui/apps/platform/src/Containers/SystemConfig/Form/SystemConfigForm.tsx
ui/apps/platform/src/Containers/SystemConfig/SystemConfigPage.tsx
ui/apps/platform/src/services/SystemConfigService.ts

This PR adds the ability to reset the Red Hat layered products rule to the default regex.
Note: Hide whitespace in the diff view to make it easier to see the changes.
https://github.com/user-attachments/assets/57a4396b-2c1f-4fb9-beed-db99d8811a7d

ROX-29489: Allow resetting RHLP rule to default

---

central/complianceoperator/v2/report/manager/generator/report_gen_impl.go
central/complianceoperator/v2/report/manager/generator/report_gen_impl_test.go
central/complianceoperator/v2/scanconfigurations/service/convert.go
generated/api/v2/compliance_scan_configuration_service.pb.go
generated/api/v2/compliance_scan_configuration_service.swagger.json
generated/storage/compliance_operator_v2.pb.go
proto/api/v2/compliance_scan_configuration_service.proto
proto/storage/compliance_operator_v2.proto
proto/storage/proto.lock

This PR separates the `PARTIAL_ERROR` state into `PARTIAL_SCAN_ERROR_EMAIL` and `PARTIAL_SCAN_ERROR_DOWNLOAD`
- Deploy in two clusters with Compliance Operator
- Create a Scan Schedule with both cluster
- Make one of the scans fail mid scan (e.g. disconnect sensor from central)
- Query the API and observe the status are no longer `PARTIAL_ERROR`

feat(reporting): Separate partial download and partial email

---

central/complianceoperator/v2/report/manager/generator/report_gen_impl.go
central/complianceoperator/v2/report/manager/generator/report_gen_impl_test.go

The Blob store uses a different access scope than Compliance. We need to use the correct context to Upsert in the Blob store.
This should fix [ROX-29485](https://issues.redhat.com/browse/ROX-29485)

fix(access): Use the proper ctx to upsert the blob store

---

ui/apps/platform/package-lock.json
ui/apps/platform/package.json

As titled.
Manual UI smoke test.
CI.

chore(ui): Update axios to 1.9.0

---

ui/apps/platform/package-lock.json

As titled.
UI dev server smoke test.
CI.

chore(ui): Upgrade express/path-to-regex

---

ui/apps/platform/package-lock.json

As titled, another dev dependency
Smoke test development workflow.
CI.

chore(ui): Update loader-utils

---

ui/apps/platform/package-lock.json

Updates recursive-readdir to get a transitive dep on minimatch that isn't pinned to an exact version, as well as the updated minimatch.
This is a dev/node only dependency change, so smoke test dev workflow and `npm run start`.
CI.

chore(ui): Update recursive-readdir + minimatch

---

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigsPage.tsx

ROX-29527: Change Compliance banner text 

---

central/testutils/export.go
central/vulnmgmt/service/service.go
central/vulnmgmt/service/service_impl.go
central/vulnmgmt/service/service_impl_benchmark_test.go
central/vulnmgmt/service/service_impl_postgres_test.go
central/vulnmgmt/service/singleton.go
generated/api/v1/vuln_mgmt_service.pb.go
generated/api/v1/vuln_mgmt_service.swagger.json
generated/api/v1/vuln_mgmt_service_vtproto.pb.go
proto/api/v1/vuln_mgmt_service.proto

Add a live pods count to /v1/export/vuln-mgmt/workloads API response. This is done by counting the pods that have non-zero live instances.
Unit tests and manual tests

ROX-28783: Add live pod count to workloads API

---

ui/apps/platform/package-lock.json

Updates canvg
Manual test of PDF generation in legacy pages.
CI

chore(ui): Update canvg

---

ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviders.tsx

We already link to our GitHub action, so having the Tekton task there sounds reasonable (copied from [ROX-28625](https://issues.redhat.com/browse/ROX-28625)).
Before:
After:
I manually verified that the new text and link are present and look as expected.

ROX-28625: Add link to Tekton task to access control UI page

---

CHANGELOG.md

Update CHANGELOG.md for 4.7.4

---

central/complianceoperator/v2/checkresults/datastore/datastore.go
central/complianceoperator/v2/checkresults/datastore/datastore_impl.go
central/complianceoperator/v2/checkresults/datastore/datastore_impl_test.go
central/complianceoperator/v2/checkresults/datastore/mocks/datastore.go
central/complianceoperator/v2/checkresults/store/postgres/store.go
central/complianceoperator/v2/checkresults/utils/utils.go
central/complianceoperator/v2/pipelines/complianceoperatorresultsv2/pipeline.go
central/complianceoperator/v2/pipelines/complianceoperatorscansv2/pipeline.go
central/complianceoperator/v2/report/manager/manager_impl.go
central/complianceoperator/v2/report/manager/manager_test.go
central/complianceoperator/v2/report/manager/singleton.go
central/complianceoperator/v2/report/manager/watcher/scanconfigwatcher.go
central/complianceoperator/v2/report/manager/watcher/scanconfigwatcher_test.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher.go
central/complianceoperator/v2/report/manager/watcher/scanwatcher_test.go
central/convert/internaltov2storage/compliance_check_results.go
generated/storage/compliance_operator_v2.pb.go
generated/storage/compliance_operator_v2_vtproto.pb.go
pkg/postgres/schema/compliance_operator_check_result_v2.go
pkg/search/options.go
proto/storage/compliance_operator_v2.proto
proto/storage/proto.lock

This PR aims to remove old/invalid CheckResults to keep the coverage page sync with the reports.
- If a Scan finishes successfully old CheckResults will be deleted.
- If a Scan fails we will remove all CheckResults.
- Deploy in two clusters with Compliance Operator 
- Create a Scan Schedule with both cluster
- Make one of the scans fail mid scan (e.g. disconnect sensor from central)
- Observe the failed scans have no results in the coverage page

ROX-29251: Remove old CheckResults

---

central/config/service/service.go

Moved the logic for checking regexes to occur before saving them, also added validation to ensure that none of the regexes in the rules are zero-length
change me!

fix(pcc): Fix saving rules before checking them

---

ui/apps/platform/cypress/integration/violations/violations.test.js

This PR fixes a violations test error by removing the test. See the comment thread in the JIRA for context.
https://issues.redhat.com/browse/ROX-28627
- [] CI results are [inspected](https://docs.google.com/document/d/1d5ga073jkv4CO1kAJqp8MPGpC6E1bwyrCGZ7S5wKg3w/edit?tab=t.0#heading=h.w4ercgtcg0xp)
Checking CI

ROX-28627: Fix violations test error

---

central/image/datastore/store/common/v2/parts_test.go
central/image/datastore/store/common/v2/split.go
central/image/datastore/store/common/v2/split_v2.go
central/image/datastore/store/postgres/store.go
central/image/datastore/store/v2/postgres/store.go
central/image/datastore/store/v2/postgres/store_test.go

When upgrading to new CVE data model, the CVEs will be inserted to the new tables for the first time. As there are be no prior CVEs in the new tables, their created at and first image occurrence timestamps will move to present time. However, the CVEs can be present in the system from before (in the old tables). So this change will try to reconcile created at and first system occurrence timestamps from the old tables if the CVEs are getting inserted into new tables for the first time. 
Unit test and manual test

ROX-29564: Get created at and first image occurrence from old tables

---

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageSignatureVerification.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageDetailBadges.tsx
ui/apps/platform/src/Containers/Vulnerabilities/types.ts

Add signature integration tab to the image details page.
change me!

ROX-29085: add signature integration tab

---

central/graphql/resolvers/images.go
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageDetailBadges.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/SignatureCountLabelLayout.tsx

Add signature count badge to image details page.
change me!

ROX-29086: signature count in image page

---

pkg/scannerv4/mappers/mappers.go
pkg/scannerv4/mappers/mappers_test.go

Follow up https://github.com/stackrox/stackrox/pull/15457
`url.ParseQuery("plain string")` returns "" so I added a new case
change me!

chore(scanner): ignore invalid fixedIn format

---

CHANGELOG.md

changelog update only
CI, just changelog

ROX-28899: changelog for CVE Data Model

---

scanner/updater/version/VULNERABILITY_BUNDLE_VERSION

As prescribed by the upstream release documentation.
change me!

chore: Update scanner VULNERABILITY_VERSION file

---

ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx

**Context**
The file upload logic previously relied on a basic check using _.includes('.yaml')_ to validate file extensions. This approach had several issues:
- Files like example.yaml.txt were incorrectly accepted.
- Files with .yml extensions (which are commonly used) were incorrectly rejected.
- This caused a confusing UX issue: when generating a simulated network policy, the downloaded file has a .yml extension by default, yet that same file could not be uploaded back into the tool due to this check (_.includes('.yaml')_).
You can see where the simulator offers a .yml download here:
🔗 https://github.com/stackrox/stackrox/blob/b845233cac1263e60dace0fa2125b95b050b0c1a/ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesYAML.tsx#L30
**What was changed**
-  The file …

fix(ui): Validate .yaml and .yml extensions properly

---

pkg/env/external_ips.go

Makes it so that external entities are pruned by default even when external entities is disabled.

fix(central): Prune external IPs by default

---

.github/dependabot.yaml
.github/workflows/style.yaml
operator/tests/controller/metrics/200-access-no-auth.yaml
operator/tests/controller/metrics/200-access-no-http2.yaml
operator/tests/controller/metrics/200-access-privileged.yaml
operator/tests/controller/metrics/200-access-unprivileged.yaml
operator/tests/run.sh
scripts/ci/jobs/check-dependabot-pinned-image.sh
scripts/ci/lib.sh

See ticket.
This also configures dependabot to keep updating the image monthly. Weekly is probably be too spammy.

ROX-29157: Pin and prefetch UBI image in operator-e2e

---

tests/e2e/run-scanner-v4-install.bats

In the scanner V4 install test suite we are passing the `--debug` flag to `roxctl` to allow for quicker feedback cycles. This flag will cause the Helm chart templates to be read from your local repo checkout, instead of using the ones built into `roxctl`.
This is not possible when `roxctl` was built in release mode -- without the `--debug` flag.
This PR changes the test suite so that it attempts to detect this situation and if `roxctl` is built in release mode it does not pass this flag.
Ran CI in release mode.

fix: Do not use --debug flag for roxctl when built in release mode

---

tests/e2e/run-scanner-v4-install.bats

Since we [stopped using release scripts to deploy](https://github.com/stackrox/stackrox/pull/14801) in some scanner-v4-install e2e tests, they started to fail in release builds. First due to [inability to use --debug](https://github.com/stackrox/stackrox/pull/15712), now due to wrong image names (see ROX-29737).
This attempts to work around the wrong image name by using opensource flavor, since the registry is already [overridden elsewhere](https://github.com/stackrox/stackrox/blob/9298f834183f0b5f14f2772db502c0f00e84f45c/tests/e2e/run-scanner-v4-install.bats#L134).
No good way to test release build on a PR TTBOMK.

ROX-29737: Use correct image names in release builds.

---

ui/apps/platform/package-lock.json
ui/apps/platform/package.json

https://github.com/Redocly/redoc/blob/main/CHANGELOG.md
* enhance accessibility for menu items with keyboard support
1. `npm run build` in ui/apps/platform
2. `npm run start` in ui/apps/platform with staging demo
1. Click ? and then click:
* **API Reference (v1)** 
* **API Reference (v2)**

ROX-29749: Update redoc 2.5.0 in dependencies

---

ui/apps/platform/package-lock.json
ui/apps/platform/package.json

https://github.com/ljharb/qs/blob/main/CHANGELOG.md#6140
* update dependencies
https://github.com/ljharb/qs/blob/main/CHANGELOG.md#6131
* `parse`: avoid a crash with `interpretNumericEntities: true`, `comma: true`, and iso charset
* `stringify`: ensure a non-string `filter` does not crash
* `stringify`: avoid a crash when a `filter` key is `null`
* update dependencies
https://github.com/ljharb/qs/blob/main/CHANGELOG.md#6123
* `parse`: properly account for `strictNullHandling` when `allowEmptyArrays`
* Update `@types/qs` and so on after merge of PatternFly 5.4 and ESLint 9.29.0 updates to prevent merge conflicts.
1. `npm run build` in ui/apps/platform
2. CI

ROX-29748: Update qs 6.14.0 in dependencies

---

.github/workflows/scanner-versioned-definitions-update.yaml
pkg/features/list.go
scanner/cmd/updater/main.go
scanner/matcher/updater/vuln/updater.go
scanner/matcher/updater/vuln/updater_test.go
scanner/updater/export.go

Only multi-bundle vuln zip file should be accepted from now on
CVEs can be loaded and images are able to be scanned:
[Testing ACS](https://104.197.208.33:8443/main/vulnerabilities/all-images/images/sha256:0959314c68bc02396d6f23000b688ece6122be485a776206f5d9e27fea30970b?vulnerabilityState=OBSERVED&detailsTab=Vulnerabilities)
Password:  `GpwOqhwcL26oDSKCGHTi2Mn5Y`
Bundle: https://storage.googleapis.com/scanner-v4-test/vulnerability-bundles/yli3-rmvSingleBundle/vulnerabilities.zip

ROX-26366: remove single bundle vuln

---

deploy/charts/monitoring/templates/networkpolicy.yaml
scripts/release-tools/kube-burner-configs/cluster-density/config.yml
scripts/release-tools/kube-burner-configs/no-load-only-elasticsearch/config.yml
tests/performance/scale/config/metrics-full.yml

This is a backport of changes from #15093
This is needed so that metrics from long running clusters for the 4.6 release branch will be saved.
A test workflow was run here https://github.com/stackrox/test-gh-actions/actions/runs/15154299926

ROX-28665: Save metrics from long running clusters backport to 4.6

---

central/complianceoperator/v2/compliancemanager/manager_impl.go
central/complianceoperator/v2/compliancemanager/manager_impl_test.go
tests/compliance_operator_v2_test.go

CO allows to schedule scans from profiles of different products (e.g. rhcos, node) since version 1.4.1

ROX-29772: Allow node profiles of different products

---

pkg/docker/config/config.go
pkg/docker/config/config_test.go

This PR updates docker config definition with k8s changes and tests. 
See:
- #416

chore(deps): update docker config

---

image/templates/helm/stackrox-secured-cluster/internal/defaults/10-env.yaml.htpl
pkg/helm/charts/tests/centralservices/testdata/helmtest/env.test.yaml
pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/env.test.yaml

refactor(ALPN): Split sensor helm defaults - Add helm tests

---

operator/tests/upgrade/upgrade/005-assert.yaml
operator/tests/upgrade/upgrade/005-errors.yaml
operator/tests/upgrade/upgrade/010-assert.yaml
operator/tests/upgrade/upgrade/010-errors.yaml
operator/tests/upgrade/upgrade/030-assert-central.yaml
operator/tests/upgrade/upgrade/030-errors.yaml
operator/tests/upgrade/upgrade/031-assert-secured-cluster.yaml
operator/tests/upgrade/upgrade/031-errors.yaml
operator/tests/upgrade/upgrade/035-assert.yaml
operator/tests/upgrade/upgrade/035-central-cr-with-scanner-v4.yaml
tests/e2e/run-scanner-v4-install.bats

See https://github.com/stackrox/stackrox/pull/15929.
Similar problem currently also exists in the scanner-v4-install test suite.
This PR updates the test case expectations accordingly.
Just test changes, nothing user-facing.
Just CI.

fix(test): Operator upgrade in scanner-v4-install tests

---

central/metrics/central.go
central/metrics/central_test.go
central/metrics/init.go
central/reprocessor/reprocessor.go
central/reprocessor/reprocessor_test.go
central/reprocessor/reprocessor_unit_test.go
central/sensor/service/connection/connection_impl.go
pkg/env/reprocessing_interval.go
pkg/maputil/syncmap.go
pkg/maputil/syncmap_test.go

(cherry picked from commit 933c55842eb6a2abebe018120d3a3ca7e88c0c11)
Backport 15802 to release 4.8
change me!

ROX-29755: Recover reprocessing when Sensor's are 'stuck' (#15802)

---

.tekton/basic-component-pipeline.yaml
.tekton/images-mirror-set.yaml
.tekton/main-pipeline.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/retag-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml

Same as https://github.com/stackrox/stackrox/pull/16012 but for 4.8
No change.
Only CI.

ROX-30101: Reformat `.tekton/*.yaml`-s to fix MintMaker / 4.8

---

.tekton/basic-component-pipeline.yaml
.tekton/images-mirror-set.yaml
.tekton/main-pipeline.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/retag-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml

Same as https://github.com/stackrox/stackrox/pull/16012 but for `master`.
No change.
Only CI.

ROX-30101: Reformat `.tekton/*.yaml` to fix MintMaker / master

---

.tekton/basic-component-pipeline.yaml
.tekton/images-mirror-set.yaml
.tekton/main-pipeline.yaml
.tekton/operator-bundle-pipeline.yaml
.tekton/retag-pipeline.yaml
.tekton/scanner-v4-pipeline.yaml

Same as https://github.com/stackrox/stackrox/pull/16012 but for `release-4.6`.
No change.
Only CI.

ROX-30101: Reformat `.tekton/*.yaml`-s to fix MintMaker / 4.6

---

pkg/env/postgres_query_tracer.go
pkg/postgres/pgtest/postgres.go

I got tired of commenting out the teardown when trying to debug unit tests run locally.  So I added a flag.
change me!

chore: flag to keep test dbs

---

tests/e2e/run-scanner-v4-install.bats

Cherry-picking of master commits (in this order)
```
commit 8cf9210982c5ec2b74b7bc69a6753a93c937d207
Author: Moritz Clasmeier <111092021+mclasmeier@users.noreply.github.com>
Date:   Fri Jul 4 15:42:46 2025 +0200
fix(tests): Proper output sequencing on scanner V4 test case teardown (#15813)
Co-authored-by: Moritz Clasmeier <mclasmeier@redhat.com>
```
```
commit e64b4f65c83aeb180f02daf01e6df837b597b0cf
Author: Moritz Clasmeier <111092021+mclasmeier@users.noreply.github.com>
Date:   Wed Jul 9 07:53:48 2025 +0200
fix(test): Operator upgrade in scanner-v4-install tests (#15934)
```
```
commit 1aed17f899195ab8e1ee5cbbba814f7f25f80459
Author: Moritz Clasmeier <111092021+mclasmeier@users.noreply.github.com>
Date:   Fri Jul 11 10:28:31 2025 +0200
ROX-29711: Fix scanner-v4-install-tests suite …
```

fix(test): Backporting several changes to scanner-v4-install tests

---

sensor/common/heritage/heritage.go

The heritage data is updated when changes to the Sensor deployment are detected. However, the function used for detecting the changes:
```go
func (m *endpointManagerImpl) onDeploymentCreateOrUpdate(deployment *deploymentWrap) {
data := m.endpointDataForDeployment(deployment)
updates := map[string]*clusterentities.EntityData{
deployment.GetId(): data,
}
if isSensor(deployment) {   /// PROBLEM: This returns true also for changes other than the sensor deployment.
if err := m.updateHeritageData(data); err != nil {
log.Warnf("Error updating Sensor heritage data: %v", err)
}
}
m.entityStore.Apply(updates, false, "OnDeploymentCreateOrUpdateByID")
```
seems to be triggered with `isSensor(deployment)==true` also when other objects in sensor's namespace are updated.
This may lead to updates to …

ROX-29185: Limit heritage updates on cache-hit

---

ui/.gitignore

This PR adds `.gitignore` entries to exclude cursor rules files (`.cursor/` and `.cursorrules/`) from version control while we experiment with different cursor configurations.
- We're currently experimenting with cursor rules and configurations
- These files contain editor-specific settings that may change frequently during experimentation
- Ignoring them prevents cluttering the git history with temporary configuration changes
- Allows team members to experiment with their own cursor settings without conflicts
Add rules and see if git ignores them.

feat(ui): Add .gitignore entries for AI rules experimentation

---

tests/upgrade/postgres_run.sh

Update upgrade test versions after `4.6.8` and `4.7.5` release.

ROX-30027: Bump upgrade test versions

---

ui/apps/platform/src/Components/PatternFly/CheckboxSelect.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx

- CheckboxSelect component: Complete rewrite using PatternFly v5 Select, MenuToggle, and related components
- API improvements: Removed deprecated name prop, updated event handlers for v5 patterns
- Enhanced UI: Added selection count badge and improved toggle layout using Flex components
- Import updates: Migrated from @patternfly/react-core/deprecated to @patternfly/react-core
- Usage updates: Updated SelectOption imports in consuming components
- Components/PatternFly/CheckboxSelect.tsx - Complete component migration
- ViewVulnReport/ReportJobs.tsx - Updated SelectOption import and aria-label
- forms/ReportParametersForm.tsx - Updated SelectOption import, removed name props
https://github.com/user-attachments/assets/69ab56ce-7b57-451f-9ab9-f6fdcf30f48a …

refactor(ui): Migrate CheckboxSelect from deprecated implementation

---

central/main.go

Declarative configuration is a background process. Its initial configuration can be performed once the GRPC server is up and running.
This PR moves the declarative configuration process out of the GRPC server instantiation code.
N/A
Deploy built image.
Check declarative configuration still works.

ROX-29416: Move declarative configuration out of grpc service startup

---

sensor/kubernetes/complianceoperator/handler_impl.go
sensor/kubernetes/complianceoperator/handler_impl_test.go

Sometimes the handling (create/update/delete) of k8s resources might fail. If this happens Scans might not be created/updated/deleted. This is not crucial in normal operations as the errors will be surface and the user can simply re-apply the changes, but if this happens, the tests will fail.
This PR adds a retry logic to the manipulation of compliance resources to mitigate these issues.

ROX-28952: Add retry in the compliance handler

---

central/image/service/service_impl.go

Semaphore acquisition errors may be logged frequently when Central is shutting down. Since many scans may be queued in parallel, this can lead to log spam and confuse debugging of the actual shutdown reasons. Therefore, let's reduce the log level to DEBUG.
CI

chore: reduce semaphore error log level

---

sensor/common/admissioncontroller/alert_handler.go
sensor/common/compliance/auditlog_manager_impl.go
sensor/common/compliance/multiplexer.go
sensor/common/compliance/service_impl.go
sensor/common/component.go
sensor/common/image/service_impl.go
sensor/common/networkflow/manager/manager_impl.go
sensor/common/reprocessor/handler.go
sensor/common/signal/signal_service.go
sensor/common/unimplemented/unimplemented.go
sensor/kubernetes/admissioncontroller/config_map_persister.go
sensor/kubernetes/clusterhealth/updater.go
sensor/kubernetes/clustermetrics/cluster_metrics.go
sensor/kubernetes/clusterstatus/updater.go
sensor/kubernetes/complianceoperator/updater.go

This PR refactors sensor components to reduce code duplication and make it easier to identify components that do not process messages.
- Cleaner code: Removes boilerplate empty method implementations
- Better maintainability: Centralized no-op behavior in a single location
- Clearer intent: Components that don't process messages are explicitly marked
- Reduced duplication: 15 files updated with consistent pattern
change me!

 fix: improve sensor component identification

---

central/clusterinit/backend/backend_impl.go

After the changes for Secured Cluster certificate auto rotation and Cluster Registration Secrets, most Secured Clusters TLS certificates are not tied to an init bundle.
This causes this log line to appear excessively, because the validation is executed for every unary RPC call (e.g. image scans requests). It also looks like an error, when it's actually expected.
Not needed.

chore: remove init bundle debug log

---

ui/apps/platform/src/ConsolePlugin/ProjectSecurityTab/Index.tsx
ui/apps/platform/webpack.ocp-plugin.config.js

Adds extension to the Project detail page to add a security tab.
👀

ROX-30359: Add extension for project detail page security tab

---

sensor/tests/complianceoperator/sync_test.go
sensor/tests/helper/k8s.go

This PR improves sync_test.go logs by converting comments into logs and adding additional information to `Eventually` assertions. This make it easier to debug problems.

chore(sensor): improve sync test logs

---

operator/EXTENDING_CRDS.md
operator/api/v1alpha1/securedcluster_types.go
operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml
operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml
operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
operator/internal/central/extensions/reconcile_defaulting_test.go
operator/internal/central/values/defaults/defaults.go
operator/internal/common/defaulting/test_helpers/helpers.go
operator/internal/common/marshal.go
operator/internal/securedcluster/extensions/reconcile_defaulting.go
operator/internal/securedcluster/extensions/reconcile_defaulting_test.go
operator/internal/securedcluster/values/defaults/defaults.go
operator/internal/securedcluster/values/defaults/defaults_test.go

This leverages the code added in #16188:
- moves some code into common locations for reuse
- moves one static default from secured cluster CRD schema into a new defaulting flow
- addresses a couple of review comments from that PR
- updates the developer documentation
- will update when the bulk of defaults are moved
CI

fix: first stab at secured cluster static default move

---

operator/internal/securedcluster/constants.go
operator/internal/securedcluster/reconciler/reconciler.go
operator/internal/securedcluster/values/translation/translation.go
operator/internal/securedcluster/values/translation/translation_test.go
pkg/kubernetes/configmaps.go

Follow-up to https://github.com/stackrox/stackrox/pull/15706
Relates to https://issues.redhat.com/browse/ROX-29674
The `TLSCABundleConfigMapName` and `TLSCABundleKey` constants will have to be used by Sensor, so I'm moving them to `pkg`, to not have dependencies between Sensor and Operator.

fix: move admission-control CA bundle ConfigMap constants to pkg

---

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/OnDemandReportJobDetails.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/OnDemandReportsTable.tsx
ui/apps/platform/src/services/ReportsService.ts
ui/apps/platform/src/utils/searchUtils.test.ts
ui/apps/platform/src/utils/searchUtils.ts

This PR has the following changes:
-  Created OnDemandReportJobDetails.tsx to display comprehensive report configuration:
- Basic report details (name, type, area of concern)
- Scope filtering details with search filter chips
- Vulnerability parameters (cve severity, cves discovered since, optional columns)
- Modified OnDemandReportsTable.tsx to make request names clickable buttons that open the details modal
- Updated ReportsService.ts with sample data for testing modal functionality
- Added getSearchFilterForRequestQueryString() to parse query strings into search filter objects with extra test coverage

ROX-28475: Show report job details on request name click

---

tests/compliance_operator_test.go
tests/e2e/run.sh

This PR fixes `stack overflow` by infinite recursive call due to a typo (missing `.c`)
This reverts:
- https://github.com/stackrox/stackrox/pull/16346

ROX-30478: fix tests

---

central/namespace/datastore/datastore.go
central/namespace/datastore/datastore_test.go
central/namespace/datastore/internal/store/postgres/gen.go
central/namespace/datastore/internal/store/postgres/store.go

Remove namespace searcher.  Used Cursor to create the new test file.
CI and UT prove functionality remains unchanged.

ROX-30409: remove namespace searcher

---

central/cve/image/datastore/datastore_impl_test.go
central/cve/node/datastore/datastore_impl_test.go

Fix the node cve search test that was previously using mocks to use the new search methods.    Cursor helped convert this test from using mocks to using actual data which provides a more useful test.
Decided to keep the image cve search skipped because it was deprecated with the new CVE data model and thus pointless to fix.
Tests were in fact the only changes here.

ROX-30277: fix some search tests

---

pkg/eventual/format.go
pkg/eventual/format_test.go
pkg/eventual/options.go
pkg/eventual/options_test.go
pkg/eventual/value.go
pkg/eventual/value_test.go

`eventual.Value[T]` is a value that is initially unset, and `Value.Get() T` will block until the value is set with `value.Set(T)`.
CI

feat(eventual): `pkg/eventual`

---

tests/upgrade/postgres_run.sh

https://spaces.redhat.com/spaces/StackRox/pages/284431271/Upstream+Release+Automation#UpstreamReleaseAutomation-finish-releaseFinishRelease

chore(upgrade): Bump 4.7 previous version in upgrade test to 4.7.6

---

ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/Overview/VirtualMachineCvesOverviewPage.tsx

Adds our standard heading to the overview page, including title and description text.

ROX-30524: Virtual machines overview header and description

---

CLAUDE.md

The title says it all.
This can (or should) probably be further enhanced by other workflows.
This is just the bare bones initial analysis as provided by Claude Code.

chore: add initial CLAUDE.md

---

ui/apps/platform/src/Containers/Policies/Wizard/Step4/PolicyScopeForm.tsx

Migrate PolicyScopeForm Select component from deprecated PatternFly Select to PatternFly v5 with modern typeahead multi-select functionality for image exclusion.
https://github.com/user-attachments/assets/74bb3d96-320b-4884-acaf-0d72ba0ccc0e
https://github.com/user-attachments/assets/60258327-e8c7-4f66-82a1-06d4ac009373

refactor(ui): migrate PolicyScopeForm Select to PatternFly v5

---

central/graphql/resolvers/generated.go
central/notifiers/email/email.go
generated/api/v1/notifier_service.swagger.json
generated/storage/notifier.pb.go
generated/storage/notifier_vtproto.pb.go
proto/storage/notifier.proto
proto/storage/proto.lock
ui/apps/platform/cypress/integration/integrations/notifiers.test.js
ui/apps/platform/src/Components/EmailNotifier/EmailNotifierForm.tsx
ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/EmailIntegrationForm.tsx

UI and BE changes to add new field to email notifier integration to specify the SMTP EHLO/HELO hostname.
Manual testing on gke cluster and sending a Test message via the email integration successfully.

ROX-30654: New email integration field

---

CHANGELOG.md

This is the best I could get in the absence of more concrete info - https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1755085848063029
No change.
I did not.

ROX-30685: Add a release note about Konflux changes

---

ui/apps/platform/cypress/constants/PoliciesPage.js
ui/apps/platform/cypress/integration/policies/policyWizardStep3-dnd.test.js
ui/apps/platform/cypress/integration/policies/policyWizardStep3.test.js
ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaFieldInput.tsx
ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx
ui/apps/platform/src/Containers/Policies/Wizard/policyValidationSchemas.ts
ui/apps/platform/src/messages/common.ts

Refactor PolicyCriteriaFieldInput to use PatternFly v5 wrapper components for better consistency and maintainability.
Key Changes:
- Replace deprecated PatternFly Select components with modern v5 implementations
- Use SelectSingle component for single select cases instead of custom Select implementation
- Use CheckboxSelect component for multiselect cases with automatic checkbox and badge handling
- Simplify state management by removing manual toggle state and handlers
- Improve TypeScript type safety with explicit parameter types
- Reduce code complexity while maintaining existing functionality and test IDs
- Remove 60+ lines of custom Select implementation in favor of reusable wrapper components
https://github.com/user-attachments/assets/df995255-e600-44d5-a338-f005aa97d9b1 …

refactor(ui): migrate PolicyCriteriaFieldInput to PatternFly v5

---

tests/compliance_operator_v2_test.go

This test is flaky. Let's try to retry client operations.

ROX-30690: retry client in co tests

---

central/graphql/resolvers/components_v1.go
central/graphql/resolvers/image_components.go
central/graphql/resolvers/image_cve_core.go
central/graphql/resolvers/image_scan.go
central/graphql/resolvers/image_vulnerabilities.go
central/graphql/resolvers/images.go
central/graphql/resolvers/images_v2.go
central/graphql/resolvers/utils.go
central/graphql/resolvers/vulnerabilities_v1.go
central/graphql/resolvers/vulnerability_requests.go
central/image/datastore/store/common/v2/split_v2.go

This PR catches some places that were missing from #16414. At a first glance it may seem like this PR duplicates a ton of code, which it definitely does. This is in an effort to make it easier for whoever the poor soul is that has to come back in the future (it will probably be me) and remove the Image V1 code once we do away with the previous `storage.Image` proto.
CI

ROX-30454: Pass #2 at GraphQL for ImageV2

---

CHANGELOG.md

It's best to review this change by commits.
No change.
Looked at the rendered text. https://github.com/stackrox/stackrox/blob/misha/refine-4.8-changelog/CHANGELOG.md#482

ROX-30685: Update changelog for 4.8.3

---

central/cve/common/csv/handler.go
central/cve/csv/handler.go
central/cve/image/csv/handler.go

This adds image V2 to the CSV export handlers when the new image data model is enabled.
change me!

ROX-30459: Add ImageV2 to CSV Export Handlers

---

tests/e2e/lib.sh
ui/apps/platform/cypress/integration/clusters/clusterDeletion.test.js
ui/apps/platform/cypress/integration/clusters/clusters.test.js
ui/apps/platform/cypress/integration/clusters/clustersCertificateExpiration.test.js
ui/apps/platform/cypress/integration/clusters/clustersHealthStatus.test.js
ui/apps/platform/cypress/integration/clusters/clustersManager.test.js
ui/apps/platform/cypress/integration/clusters/redirectFromDashboard.test.js

What I should have done in the first place.
nightly tests pass, please

ROX-30672: Add skip to clusters integration tests until rewrite

---

pkg/signatures/cosign_sig_verifier_test.go

Skip the test until the test data is fixed.
change me!

ROX-30757: skip broken certificate signature test

---

ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/Overview/VirtualMachineCvesOverviewPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/VirtualMachine/VirtualMachinePage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/VirtualMachine/VirtualMachinePageDetails.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/VirtualMachine/VirtualMachinePageHeader.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/VirtualMachine/VirtualMachinePageVulnerabilities.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/VirtualMachineCvesPage.tsx
ui/apps/platform/src/Containers/Vulnerabilities/types.ts
ui/apps/platform/src/Containers/Vulnerabilities/utils/searchUtils.tsx

This PR adds a virtual machine details page with a tabbed layout for displaying VM information and managing CVEs.
Key Changes:
- Create `VirtualMachinePage` component with header, breadcrumb navigation, and tab structure
- Add `VirtualMachinePageHeader` displaying metadata labels (`GuestOS`, `location`, `agent`, `scan time`, `created date`)
- Implement placeholder Vulnerabilities and Details tab sections with conditional descriptive text
- Add routing configuration for `:virtualMachineId` parameter in `VirtualMachineCvesPage`
- Update `searchUtils` to support `VirtualMachine` entity type in `baseUrlForCveMap`
- Add a test navigation button to the overview page for testing the details page
- Use mock data structure matching real VM metadata fields for development

ROX-30632: Add virtual machine details page with tabbed layout

---

sensor/kubernetes/fake/deployment.go
sensor/kubernetes/fake/fake.go
sensor/kubernetes/fake/flows.go
sensor/kubernetes/fake/flows_test.go
sensor/kubernetes/fake/labels.go
sensor/kubernetes/fake/networkpolicy.go
sensor/kubernetes/fake/pools.go
sensor/kubernetes/fake/service.go

Refactored the fake workload package to eliminate global variables and implement dependency injection for better testability and maintainability.
**Key Changes:**
- **Removed all global state**: Moved `labelsPool`, `processPool`, `ipPool`, `externalIpPool`, `containerPool`, `endpointPool`, and `registeredHostConnections` from global variables into `WorkloadManager` instance fields
- **Added dependency injection**: Extended `WorkloadManagerConfig` with builder pattern (`With*` methods) to configure pools during construction
- **Improved code organization**: Extracted pool data structures and utility functions from `flows.go` to new `pools.go` file, reducing `flows.go` from 370→215 lines
- **Fixed coupling bug**: Corrected `pool.remove()` method that was incorrectly accessing other global …

ROX-30732: Do not use globals in fake workloads

---

image/templates/helm/stackrox-central/internal/defaults.yaml.htpl

This updates the resource requirements and guidelines for Scanner V4 based on the [the latest image scan perf tests](https://docs.google.com/document/d/1wOcpuXKTx4_0kYPmFw4-ZQaxFIY-qYQ8hxBg0iPACOM).
I noticed that some of the values were not aligned with [the latest recommendations in the docs](https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes/4.8/html/installing/acs-default-requirements#default-requirements-central-services-scanner-v4_acs-default-requirements). Raise your voice if you think these values should be kept the same, or there is some other rationale for making them different from the proposed values.
Updates to the docs: https://github.com/openshift/openshift-docs/pull/98791
I am unaware of any automated test that needs to be updated. I …

ROX-30469: Update V4 resource requirements

---

go.mod
go.sum

Addresses https://issues.redhat.com/browse/ROX-29652 now that we're on recent Go and the change is upstream.
No changes to functionality.
CI is enough.

chore(deps): drop obsolete helm-mapkubeapis fork

---

central/cve/common/csv/handler.go
central/cve/common/csv/handler_test.go
central/graphql/resolvers/image_vulnerabilities.go
central/graphql/resolvers/images.go
central/views/common/queries.go
central/views/deployments/view_impl.go
central/views/imagecomponentflat/view_impl.go
central/views/imagecve/view_impl.go
central/views/imagecve/view_test.go
central/views/imagecveflat/view_impl.go
pkg/search/options.go
qa-tests-backend/src/test/groovy/CSVTest.groovy

While reviewing #16578 I realized that these were missed for the Image CVE data model.  So the investigation began to put those in for the new CVE data model as while this area may be kind of sort of deprecated it is not officially deprecated like many things that are marked deprecated but aren't.
As these were being put back in, it seemed like a good opportunity to revisit the CSV groovy test and get that working.  That pointed out that some of the queries and the casing there of didn't jive with some of our work arounds for views because we couldn't count on the field equality matching.   So updates were made in the views to account for this to ensure the casing of the query fields matters not.
Fixed and turned on the CSV test (removed the component one because getting that id is …

ROX-30859, ROX-29220: Updates to fix CSV test and code

---

sensor/utils/utils.go

The `"rhacs.redhat.com/tls"` label is already defined [here](https://github.com/stackrox/stackrox/blob/d9e32164d0f6bddc5501b5a0cc37ff5f9c9bf8c4/pkg/labels/common.go#L16), use that definition instead of hardcoding.

chore(sensor): Replace hard-coded TLS secret label

---

CHANGELOG.md
operator/internal/central/extensions/reconcile_tls.go
sensor/kubernetes/certrefresh/env.go

This PR enables CA rotation for both Central and Secured Clusters, only when installed using the Operator.
Documentation is being tracked with [ROX-30901](https://issues.redhat.com/browse/ROX-30901).
Feature was manually tested in https://github.com/stackrox/stackrox/pull/15349 which has additional changes so that the CA rotation steps take place after 5 respectively 10 minutes instead of 3 and 4 years.

ROX-20262: Enable CA rotation in Operator-managed Central and Sensor

---

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/ViewBasedReportsTab.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/ViewBasedReportsTable.tsx
ui/apps/platform/src/services/ReportsService.ts

Refactored vulnerability reporting components to improve code reusability and implemented proper download functionality for view-based reports.
Key Changes:
- Extracted duplicate report download logic into the reusable `downloadReportByJobId` utility function in ReportsService
- Replaced the inline download implementation in the `ReportJobs` component with a centralized download function
- Implemented download functionality for the view-based reports table using the new utility
- Removed TODO comment for view-based reports polling (functionality was already implemented)
No visual changes

ROX-30784: Add View-based Report Download API

---

central/imagev2/datastore/singleton.go
central/risk/manager/manager.go
central/risk/manager/manager_test.go
central/risk/manager/mocks/manager.go
central/risk/manager/singleton.go
central/risk/multipliers/image/component_count.go
central/risk/multipliers/image/component_count_test.go
central/risk/multipliers/image/image_age.go
central/risk/multipliers/image/image_age_test.go
central/risk/multipliers/image/multiplier.go
central/risk/multipliers/image/risky_component.go
central/risk/multipliers/image/risky_component_test.go
central/risk/multipliers/image/vulnerabilities.go
central/risk/multipliers/image/vulnerabilities_test.go
central/risk/multipliers/test_utils.go
central/risk/scorer/image/scorer.go
central/risk/scorer/image/scorer_test.go
central/risk/scorer/test_utils.go
central/sensor/service/pipeline/nodeindex/three_pipelines_test.go
central/sensor/service/pipeline/nodeinventory/two_pipelines_test.go

This PR adds functions for calculating and upserting risk scores for V2 images. it is mostly a copy of existing risk score calculation with minor tweaks.
Added unit tests and verified CI

ROX-30786: Add risk management and calculation for V2 images

---

.github/workflows/notify-milestone-change.yml

https://issues.redhat.com/browse/ROX-25528
* adds workflow dispatch for easier testing
* fixes the Slack notification by escaping of quotes in PR titles and Jira summaries ("Notify on milestone change cannot handle quotes in issue title" is the summary for ROX-25528)
Tested in stackrox/test-gh-actions
* quotes in PR title and Jira summary: https://github.com/stackrox/test-gh-actions/actions/runs/17556317758 (PR: https://github.com/stackrox/test-gh-actions/pull/211, Jira: https://issues.redhat.com/browse/ROX-25435)
* manual dispatch with quote in PR title and Jira summary: https://github.com/stackrox/test-gh-actions/actions/runs/17760495213 (input: `ROX-25435: Fix the "authentication" bug in login system`)

ROX-25528: Handle quotes in PR title and Jira summary in notify GHA

---

central/hash/datastore/datastore.go
central/hash/datastore/datastore_test_constructors.go
central/hash/datastore/singleton.go
central/hash/manager/manager.go

Backport https://github.com/stackrox/stackrox/commit/810dbde215c4e6bd83d2311c5f9a6375e167f98c from https://github.com/stackrox/stackrox/pull/16374.
change me!

ROX-30498: truncate hashes if off (#16374)

---

central/declarativeconfig/README.md
pkg/declarativeconfig/README.md

Add some information on the declarative configuration framework for access control and integrations.
PR stack:
- #15937
- #15938 
- #15939
- #16070 
- #16170 
Documentation only
This documents the steps taken in the previous PRs in the stack.

ROX-29999: add README for declarative configuration

---

central/metrics/custom/runner.go
pkg/sac/context.go
pkg/sac/context_test.go

When a goroutine is scheduled on a service request, the identity and scope checker need to be transfered to a new context, that will not be cancelled with the request context.
This PR adds a method to copy the SAC checker core. The identity transfer has been implemented previously.
CI.

fix: copy context checker core

---

.openshift-ci/ci_tests.py

Increases test timeout for IBM ppc64le and s390x jobs to prevent premature termination of e2e test step. See https://github.com/stackrox/stackrox/pull/13259#issuecomment-3162733648
Tested with Openshift CI.

fix(ci): Increase TEST_TIMEOUT for ppc64le/s390x

---

central/metrics/custom/image_vulnerabilities/tracker.go

Removing a leftover from when the SAC was not supported.
CI, manual tests.
With a scope limited to only "backend" namespace:
```console
sh$ curl https://localhost:8000/metrics -H "Authorization: Bearer $PROM_TOKEN" -ks
rox_central_image_vuln_namespace_severity{Cluster="production",Namespace="backend",Severity="CRITICAL_VULNERABILITY_SEVERITY"} 21
rox_central_image_vuln_namespace_severity{Cluster="production",Namespace="backend",Severity="IMPORTANT_VULNERABILITY_SEVERITY"} 39
rox_central_image_vuln_namespace_severity{Cluster="production",Namespace="backend",Severity="MODERATE_VULNERABILITY_SEVERITY"} 19
rox_central_policy_violation_namespace_severity{Cluster="production",Namespace="backend",Severity="CRITICAL_SEVERITY"} 1
rox_central_policy_violation_namespace_severity{Cluster="production", …
```

fix(metrics): remove the hardcoded scope checker

---

central/processindicator/datastore/bench_test.go

Benchmark test for search was done after searcher removal which did not exist in 4.7.  So the test needs to use the searchers.
change me!

fix(bench): benchmark test fix

---

central/convert/internaltostorage/virtual_machine.go
central/convert/internaltostorage/virtual_machine_test.go

Type conversion to prepare for central pipeline from sensor.
PR stack:
- #16646
- #16692 
- #16758
- #16726 
- #16727 
Manual Unit test run
CI

feat(vm4vm): Conversion from sensor wire format to storage VM

---

image/postgres/konflux.Dockerfile
image/rhel/konflux.Dockerfile
image/roxctl/konflux.Dockerfile
operator/konflux.Dockerfile
operator/konflux.bundle.Dockerfile
scanner/image/db/konflux.Dockerfile
scanner/image/scanner/konflux.Dockerfile

Inducing PR that MintMaker did not open.
No change.
CI.

chore(deps): update all dependencies

---

central/metrics/custom/runner.go
central/metrics/custom/runner_test.go
central/metrics/custom/singleton.go

This PR simplifies handling of the growing number of metric trackers.
CI

refactor: custom metrics runner to loop over trackers

---

ui/apps/platform/eslint.config.js
ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsTable.tsx
ui/apps/platform/src/Containers/Audit/ListeningEndpoints/hooks/useDeploymentListeningEndpoints.tsx

Toward Q3 AI goal: help AI to help us.
Select a folder that will not cause merge conflicts with feature work in progress.
1. Edit eslint.config.js file to comment out folder in `ignores` array.
2. Edit files to fix errors.
3. Edit estlint.config.js file to delete out folder in `ignores` array.
2. `npm run lint:fast-dev` in ui/apps/platform folder.

ROX-30972: Use import type in Containers Audit

---

ui/apps/platform/eslint.config.js
ui/apps/platform/src/Containers/ExceptionConfiguration/VulnerabilitiesConfiguration.tsx
ui/apps/platform/src/Containers/ExceptionConfiguration/useVulnerabilitiesExceptionConfig.ts

Toward Q3 AI goal: help AI to help us.
Select a folder that will not cause merge conflicts with feature work in progress.
1. Edit eslint.config.js file to comment out folder in `ignores` array.
2. Edit files to fix errors.
3. Edit estlint.config.js file to delete out folder in `ignores` array.
2. `npm run lint:fast-dev` in ui/apps/platform folder.

ROX-30978: Use import type in Containers ExceptionConfiguration

---

qa-tests-backend/src/test/groovy/Enforcement.groovy

Sometimes the enforcement kicks in very fast when the test is still creating the deployments in the setup phase. In this case, the enforcement kills the pods even before the deployment creation method gets a chance to load them in memory. This is why the assert `d.pods.size() > 0` fails sometimes. This can be verified by the test logs which suggest that a pod was created but was deleted soon after.
```
01:59:03 | DEBUG | Enforcement               | Kubernetes                | Waiting for kill-enforcement-only to start
01:59:03 | DEBUG | Enforcement               | Kubernetes                | Status of kill-enforcement-only's pods:
01:59:03 | DEBUG | Enforcement               | Kubernetes                | 	- kill-enforcement-only-84f687f767-xtr97
Container status: …
```

ROX-30593: Fix Enforcement test (Test Kill Enforcement)

---

.github/actions/job-preamble/action.yaml

Result of 
```bash
git checkout master .github/actions/job-preamble/action.yaml
```
because 4.7.7 build keeps failing: https://github.com/stackrox/stackrox/actions/runs/18002579497/job/51216631059
My master was at 54a5e426480fe328fbfd52e37913b330ba6b51ab.
I then got a failure, because the job record functions have changed between 4.7 and master, so I reverted that part of the workflow: https://github.com/stackrox/stackrox/pull/17027/commits/d056974b55f98fab753ab728b84dfc9da369ba04
Here are the most relevant commits:
* https://github.com/stackrox/stackrox/commit/de05a68c421d91f0b0de721dd11021e31f46492c
* https://github.com/stackrox/stackrox/commit/cfa556130ebf878cd7d8ee4be3fc1d87c7ca0bed
Build with `ci-build-race-condition-debug` label and all other GHA workflows are passing.

fix(gha): backport changes for job-preamble

---

central/metrics/custom/tracker/tracker_base.go
central/metrics/custom/tracker/tracker_base_test.go
central/metrics/custom_registry.go
central/metrics/custom_registry_test.go

The unused registries are not freed, which may lead to a memory leak.
This PR introduces a cleanup procedure to delete registries not being accessed for 2 days.
CI
Current dependencies on/for this PR:
* [master](../tree/master)
* **PR #15783**
* **PR #15784**
* **PR #15807**
* **PR #15796**
* **PR #15797**
* **PR #15809**
* **PR #15487**
* **PR #16176** 👈
* **PR #15782**

ROX-28151: custom registry cleanup

---

scanner/cmd/scannerctl/fixtures/indexReport.json

The map based proto schema proposed in https://github.com/stackrox/stackrox/pull/16944 is not yet available, so the proto conversion fails currently. This PR reverts the fixture back to the master proto schema.
Ran `go run ./scanner/cmd/scannerctl vm --insecure-skip-tls-verify --matcher-address=localhost:8443` against a recent master version of matcher.

fix(scannerctl): index report fixture in scannerctl

---

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/ViewBasedReportJobDetails.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/ViewBasedReportsTab.tsx
ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/ViewBasedReportsTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/CreateReportDropdown.tsx
ui/apps/platform/src/Containers/Vulnerabilities/utils/vulnerabilityUtils.test.ts
ui/apps/platform/src/Containers/Vulnerabilities/utils/vulnerabilityUtils.ts
ui/apps/platform/src/services/ReportsService.ts
ui/apps/platform/src/services/ReportsService.types.ts
ui/apps/platform/src/utils/arrayUtils.ts
ui/apps/platform/src/utils/searchUtils.ts

Refactored view-based vulnerability reports UI to remove the expiration column and improve the report job details display.
Key Changes:
- Removed hardcoded expiration column from reports table
- Replaced hardcoded CVE severity and discovery time with real data
- Added utility function to format CVE discovery time filters into readable text
- Updated report data model to use 'name' instead of 'requestName'
- Fixed query structure and sort field references
https://github.com/user-attachments/assets/c40aed9c-468d-4709-bff6-4fa808b37e3f

ROX-30857: Remove expiration column and improve report job details

---

central/reports/service/v2/convert.go
central/reports/service/v2/service_impl.go
central/reports/validation/validate.go
generated/api/v2/report_service.pb.go
generated/api/v2/report_service.swagger.json
generated/api/v2/report_service_vtproto.pb.go
proto/api/v2/report_service.proto

This PR fixes report snapshot to return area of concern in GET response
change me!
change me!

ROX-31029: Fixed report snapshot to return area of concern

---

central/metrics/custom/image_vulnerabilities/tracker_test.go
central/metrics/custom/runner.go
central/metrics/custom/tracker/tracker_base.go
central/metrics/custom/tracker/tracker_base_test.go
central/metrics/custom_registry.go
central/metrics/custom_registry_test.go

In case of an abuse from users, central may create too many in-memory Prometheus registries — one per user identity. The scope of this PR is to set a maximum number of such registries, and reject new requests to the `<API>/metrics` endpoint for new identities.
CI
Current dependencies on/for this PR:
* [master](../tree/master)
* **PR #16772**
* **PR #16176**
* **PR #16773** 👈

ROX-28151: limit the number of registries

---

central/metrics/custom/node_vulnerabilities/labels.go
central/metrics/custom/node_vulnerabilities/tracker.go
central/metrics/custom/runner.go
central/metrics/custom/singleton.go
generated/api/v1/config_service.swagger.json
generated/storage/config.pb.go
generated/storage/config_vtproto.pb.go
proto/storage/config.proto
proto/storage/proto.lock

Node vulnerability metrics, exposed on the API port.
Manual test:
```
rox_central_node_vuln_ns_severity{Cluster="production",Component="rhcos",Node="mp-09-22-universe-blo-jrcbs-master-0",Severity="IMPORTANT_VULNERABILITY_SEVERITY"} 28
rox_central_node_vuln_ns_severity{Cluster="production",Component="rhcos",Node="mp-09-22-universe-blo-jrcbs-master-0",Severity="LOW_VULNERABILITY_SEVERITY"} 2
rox_central_node_vuln_ns_severity{Cluster="production",Component="rhcos",Node="mp-09-22-universe-blo-jrcbs-master-0",Severity="MODERATE_VULNERABILITY_SEVERITY"} 17
rox_central_node_vuln_ns_severity{Cluster="production",Component="rhcos",Node="mp-09-22-universe-blo-jrcbs-master-1",Severity="IMPORTANT_VULNERABILITY_SEVERITY"} 28
...
```

ROX-28326: node vulnerabilities as Prometheus metrics

---

central/image/service/http_handler.go
pkg/apiparams/sbom.go
roxctl/image/sbom/sbom.go
roxctl/maincommand/command_tree_debug.yaml
roxctl/maincommand/command_tree_release.yaml

Implements SBOM generation via ad hoc delegate scans.
- Adds `cluster` and `namespace` fields to the `getSBOM` http handler (`/api/v1/images/sbom`) to support delegated scans.
- Adds `--cluster` and `--namespace` flags to the `roxctl image sbom` command to support delegated scans.
PR stack:
- `master`
- https://github.com/stackrox/stackrox/pull/16527
- https://github.com/stackrox/stackrox/pull/16398
- https://github.com/stackrox/stackrox/pull/16526
- 👉  https://github.com/stackrox/stackrox/pull/16884
- ~~added unit tests~~
- ~~added e2e tests~~
- ~~added regression tests~~
- ~~added compatibility tests~~
Deploy stackrox (Central Services):
```
❯ export MAIN_IMAGE_TAG=4.9.x-866-g0212d6b01b
❯ ./deploy/deploy.sh
...
```
Deploy stackrox (Secured Cluster):
```
❯ export …
```

ROX-27920: Re-introduce cluster and namespace flag for SBOM flow

---

central/metrics/custom/image_vulnerabilities/labels.go
central/metrics/custom/image_vulnerabilities/tracker.go
central/metrics/custom/policy_violations/tracker.go

- removed CvssV2 and CvssV3 labels
- added EPSS Probability and Percentile labels
- improved error handling
- minor refactoring
CI

ROX-28326: change image vulnerability labels

---

ui/apps/platform/src/Containers/Vulnerabilities/components/GenerateSbomModal.tsx

Removes the `TechPreview` label from the SBOM generation modal header. Should only be merged after https://github.com/stackrox/stackrox/pull/16884 and https://github.com/stackrox/stackrox/pull/16999.
- ~~added unit tests~~
- ~~added e2e tests~~
- ~~added regression tests~~
- ~~added compatibility tests~~
- ~~modified existing tests~~

chore(ui): remove tech preview label from SBOM modal

---

ui/apps/platform/src/Containers/Policies/Wizard/Step2/PolicyBehaviorForm.tsx
ui/apps/platform/src/Containers/Policies/policies.utils.test.ts
ui/apps/platform/src/Containers/Policies/policies.utils.ts

Update Lifecycle info text according to the requirements.
👀

ROX-30880: Update text in lifecycle intro blob

---

.github/workflows/build.yaml
operator/Dockerfile
operator/Makefile
scripts/ci/lib.sh

Reverts stackrox/stackrox#16915 as the change is breaking all Stackrox builds.

fix(build): Revert "ROX-31023: arm64 support for operator images"

---

central/processbaseline/evaluator/bench_test.go

Currently the db object is created once for all subtests. This results in growing dataset with every run making it impossible to set `count` greater than 1 as it will increase data for every subtests making benchmark slower with every next run causing high deviation in results and making them harder to compare. This PR moves db creation into a subtest where it will be used and teardown after that subtest. 
Spotted on:
- https://github.com/stackrox/stackrox/pull/16987#issuecomment-3351160583
```
go test -tags sql_integration -run=NO -bench=BenchmarkEvaluateBaselinesAndPersistResult  ./central/processbaseline/evaluator/. -count 6 -benchmem -benchtime 3s -timeout 1h
```

fix(processbaseline): evaluator bench test

---

central/reports/service/v2/service_impl.go
central/reports/service/v2/service_impl_test.go

Add view based report feature flag to report endpoints in case we need to disable the APIs
change me!

add feature flag check for view based report api

---

ui/apps/platform/src/Components/CompoundSearchFilter/attributes/virtualMachine.ts
ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/Overview/VirtualMachinesCvesTable.tsx
ui/apps/platform/src/Containers/Vulnerabilities/searchFilterConfig.ts
ui/apps/platform/src/services/SearchService.ts

Adds Filtering and Pagination to the Virtual Machines Table
Notes:
- We originally planned to do filtering and pagination on the front end, but performance concerns made us reconsider
- With virtual machines added to the data store, we should get cluster and namespace filtering by default and we hope to add virtual machine filtering.
change me!

ROX-30526: Virtual Machines Filtering and Pagination

---

central/reports/service/v2/convert.go
central/reports/service/v2/download.go

This PR fixes view based report path in download API and convert logic for storage proto to api proto
I tested this PR by manually requesting report jobs - view based and config based and downloading csv reports
change me!

Fix view based report path in api response

---

.golangci.yml
central/administration/events/datastore/internal/writer/writer_impl.go
central/compliance/data/repository_test.go
central/declarativeconfig/manager_impl.go
central/declarativeconfig/watch_handler.go
central/declarativeconfig/watch_handler_test.go
central/detection/service/service_impl.go
central/networkgraph/service/service_impl.go
central/policy/handlers/handler_test.go
go.mod
pkg/declarativeconfig/access_scope.go
pkg/declarativeconfig/auth_machine_to_machine.go
pkg/declarativeconfig/permission_set.go
pkg/gjson/modifiers.go
pkg/printers/sarif.go
pkg/protoassert/assert.go
pkg/registrymirror/store.go
pkg/set/common.go
pkg/sliceutils/sort.go
roxctl/declarativeconfig/create/access_scope.go
roxctl/declarativeconfig/create/auth_provider.go
roxctl/declarativeconfig/create/notifier.go
roxctl/declarativeconfig/create/permission_set.go
sensor/common/clusterentities/store_container_id.go
sensor/common/clusterentities/store_endpoints_test.go
sensor/common/clusterentities/store_ips_test.go
sensor/common/clusterentities/testing_test.go
sensor/upgrader/preflight/access.go

https://golangci-lint.run/docs/linters/configuration/#exptostd

chore(lint): enable exptostd

---

sensor/common/networkflow/updatecomputer/transition_based.go

Clarify situation with 'deduperActionUpdateProcess' for connections.
Renames `getDeduperAction` into `getConnectionDeduperAction` to make clear that this function is used only in connection enrichment.
Remove `case TransitionTypeOpen2Open` returning `deduperActionUpdateProcess` as it does not apply for connections.
The correct deduper action for Open->Open transition is `deduperActionNoop`.
This change does not change behavior. 
Unit tests are sufficient to validate that - those were run locally and on CI.

ROX-30941: Correct 'getDeduperAction' details

---

central/declarativeconfig/manager_impl.go
pkg/logging/logging.go

Do not compute log message when logging level is not debug.
Fixes:
- https://github.com/stackrox/stackrox/pull/17051#discussion_r2405292735

chore(declarativeconfig): do not log files names
