- ui/apps/platform/src/Containers/Integrations/IntegrationTilesPage/IntegrationTilesPage.js
Can test one or more feature flags with `const { isFeatureFlagEnabled } = useFeatureFlags();`
* feature flag for signatureIntegrations source is specified **explicily** within the component
* feature flag for tile type is specified **indirectly** via integrationsList descriptors
Temporarily add `featureFlagDependency` to **StackRox Scanner**
Without feature flag does not render **StackRox Scanner** tile nor **Signature Integrations** section
With feature flag does render **StackRox Scanner** tile and **Signature Integrations** section
> Replace getFeatureFlags with useFeatureFlags in IntegrationTilesPage

- central/networkgraph/flow/datastore/internal/store/postgres/store.go
- deploy/common/k8sbased.sh
- image/templates/sensor/kubernetes/sensor.sh
- scale/launch_workload.sh
- scale/workloads/xlarge.yaml
- sensor/kubernetes/fake/fake.go
- sensor/kubernetes/fake/namespace.go
- sensor/kubernetes/fake/workload.go
> Scale: Increase namespace configuration and allow for multiple copies of scale framework

- CHANGELOG.md
- ui/apps/platform/src/Containers/VulnMgmt/Reports/Form/NotifierSelection.tsx
- ui/apps/platform/src/Containers/VulnMgmt/Reports/Form/ResourceScopeSelection.tsx
- ui/apps/platform/src/Containers/VulnMgmt/Reports/VulnMgmtReportForm.tsx
- ui/apps/platform/src/Containers/VulnMgmt/Reports/VulnMgmtReportTablePage.tsx
Manual testing of the following scenarios
1. Admin user (can see Create, Create Resource Scope, and Create Email Notifier buttons)
2. Vulnerability Report Creator (can only see Create button)
3. Default Creator perms + Notifier create perms (can see Create and Create Email Notifier buttons)
4. Default Creator perms + Scope create perms (can see Create and Create Resource Scope buttons)
5. Custom role with no READ Image (no buttons)
6. Custom role with no READ notifier (no buttons)
7. Custom role with no READ Role (no buttons)
8. Custom role with no WRITE Vulnerability Reports (no buttons)
> ROX-9945: Fix permission checks for Vulnerability Report creation in UI

- central/graphql/resolvers/components_v2.go
- central/graphql/resolvers/vulnerabilities_v2.go
> ROX-9201: Fix sorting by CVE and Impact Score on Image sub-page

- README.md
Per title. (This is a copy of #1152) 
n/a
> Update clone instructions

- sensor/kubernetes/fake/deployment.go
- sensor/kubernetes/fake/process.go
Remove "bad" processes from the good process list
CI
> Clean up processes to reduce unexpected runtime alerts

- Makefile
> Ensure GOPATH is set before trying to install dev tools

- .circleci/config.yml
- qa-tests-backend/src/test/groovy/LocalQaPropsTest.groovy
https://issues.redhat.com/browse/ROX-9993 — Test case failure in _LocalQaTestProps_
* Updated the expected value to the actual value observed empirically in nightly testing (correctness)
* Disabled the case the case since it isn't actually useful
* Default CircleCI PR tests
> ROX-9993 fix test case

- tools/rocksdbdump/main.go
Added bucket `signature_integrations` to rocksdbdump.
- Ci
> Add signature_integrations bucket.

- qa-tests-backend/src/main/groovy/services/SignatureIntegrationService.groovy
Prepare QA-tests for image signature by creating a service for creating signature integrations required for verifying signatures.
> Create service for SignatureIntegration for usage within QA-tests.

- qa-tests-backend/src/main/groovy/orchestratormanager/OpenShift.groovy
Yesterdays fix (#1192) was full of woe. This fix is a better match with more debug.
CI:
> CI: OSD: Fix the job name match

- pkg/sac/allow_fixed_scopes_checker_core.go
- pkg/sac/tests/allow_fixed_scopes_checker_core_test.go
- pkg/sac/tests/test_scope_checker_core_test.go
- pkg/sac/tests/testutils.go
Effective access scope extraction for AllowedFixedScopesCheckerCore
Unit tests added
> ROX-9536 Implement effective access scope extraction for AllowFixedScopesCheckerCore

- central/sac/authorizer/builtin_scoped_authorizer.go
- central/sac/authorizer/builtin_scoped_authorizer_test.go
Implement effective access scope extraction for the built-in scoped-access control entities.
This will be useful for SAC implementation with the database re-design
Added unit-tests
> ROX-9537 Implement effective access scope extraction for built-in scope checker

- ui/apps/platform/package.json
- ui/packages/ui-components/package.json
- ui/yarn.lock
https://github.com/microsoft/TypeScript/releases/tag/v4.6.3
This release includes fixes for
* an incremental parsing bug caused by faulty error recovery logic
* improved results from the TypeScript API's preProcessFile function
* `yarn build` in ui
* `yarn start` in ui
> ui-devDependencies-typescript-4.6.3

- ui/apps/platform/package.json
- ui/packages/tailwind-config/package.json
- ui/packages/ui-components/package.json
- ui/yarn.lock
https://github.com/prettier/prettier/blob/main/CHANGELOG.md#262
* Update `meriyah` to fix several bugs when parsing valid code
* `yarn lint` in ui
> Update prettier 2.6.2 devDependencies in ui

- pkg/sac/query_helper.go
- pkg/sac/query_helper_test.go
~~- [ ] Unit test and regression tests added~~ Adapt existing tests
~~- [ ] Documented user facing changes (create PR based on [stackrox/openshift-docs](https://github.com/stackrox/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~
Adapted CI tests
> ROX-10022: Ensure Scope query filters trigger echo back of the scoping fields in search results

- qa-tests-backend/src/main/groovy/objects/Deployment.groovy
- qa-tests-backend/src/main/groovy/sampleScripts/reproAdmissionControllerTestFailure.groovy
- qa-tests-backend/src/main/groovy/util/SplunkUtil.groovy
- qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
- qa-tests-backend/src/test/groovy/IntegrationsSplunkViolationsTest.groovy
- qa-tests-backend/src/test/groovy/PaginationTest.groovy
Avoid this one case of rate limiting (ROX-10016) and warn about others.
CI. Run with all and check logs for other images.
> ROX-10016: CI: Avoid rate limiting

- central/secret/search/searcher_impl.go
- pkg/sac/for_resource_helpers.go
- pkg/sac/search_helper.go
~~- [ ] Documented user facing changes (create PR based on [stackrox/openshift-docs](https://github.com/stackrox/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~
Pulled and ran integration tests written in https://github.com/stackrox/stackrox/pull/942
> ROX-10025: Implement scoped search for secrets

- ui/apps/platform/package.json
- ui/yarn.lock
https://github.com/jquense/yup/blob/master/CHANGELOG.md#100-beta4-2022-04-10
* boolean: calling optional made it non-optional
> Update yup 1.0.0-beta.4 dependencies in ui

- ui/apps/platform/src/Containers/VulnMgmt/Reports/Form/EmailNotifierFormModal.tsx
- ui/apps/platform/src/Containers/VulnMgmt/Reports/Form/ResourceScopeFormModal.tsx
Follow-up fixes discovered during testing of #1255 
```
/main/vulnerability-management/reports?action=create
Modal: Specify at least one of: title, aria-label, aria-labelledby.
at Modal
at ResourceScopeFormModal
at ResourceScopeSelection
Modal: When using hasNoBodyWrapper or setting a custom header, ensure you assign an accessible name to the the modal container with aria-label or aria-labelledby.
at Modal
at ResourceScopeFormModal
at ResourceScopeSelection
Modal: Specify at least one of: title, aria-label, aria-labelledby.
at Modal
at EmailNotifierFormModal
at NotifierSelection
Modal: When using hasNoBodyWrapper or setting a custom header, ensure you assign an accessible name to the the modal container with aria-label or aria-labelledby.
at Modal
at EmailNotifierFormModal
at …
```
> Fix accessibility errors on report form modals

- central/cve/fetcher/istio.go
- central/cve/matcher/matcher.go
> Fix panic in Istio CVE attribution

- central/alert/datastore/internal/store/postgres/store.go
- central/cluster/store/cluster/postgres/store.go
- central/namespace/store/postgres/store.go
- central/pod/store/postgres/store.go
- central/processbaseline/store/postgres/store.go
- central/processindicator/store/postgres/store.go
- central/rbac/k8srole/internal/store/postgres/store.go
- central/rbac/k8srolebinding/internal/store/postgres/store.go
- central/risk/datastore/internal/store/postgres/store.go
- central/secret/internal/store/postgres/store.go
- central/serviceaccount/internal/store/postgres/store.go
- tools/generate-helpers/pg-table-bindings/list.go
- tools/generate-helpers/pg-table-bindings/list_test.go
- tools/generate-helpers/pg-table-bindings/main.go
- tools/generate-helpers/pg-table-bindings/store.go.tpl
Add a function that check if object is in scope. This will be used in directly scoped resources on upsert/delete operations to check if they are allowed.
CI
> ROX-9737: Add function that checks if object is in scope

- central/policy/service/validator_test.go
After merging #1218 the tests introduced in #1221 stopped working.
> Fix feature flag in test

- central/apitoken/datastore/internal/store/postgres/store.go
- central/policy/store/postgres/store.go
- central/reportconfigurations/store/postgres/store.go
- central/role/store/permissionset/postgres/store.go
- central/role/store/role/postgres/store.go
- central/role/store/simpleaccessscope/postgres/store.go
- central/signatureintegration/store/postgres/store.go
- central/watchedimage/datastore/internal/store/postgres/store.go
- tools/generate-helpers/pg-table-bindings/store.go.tpl
To make code cleaner let's extract target resource to a variable.
CI
> Extract resource to variable in pg store

- central/cve/fetcher/istio.go
Use the correct CVE definition when postgres is enabled
Trivial
> Use GetCve for cluster cves when using postgres

- .github/dependabot.yaml
Add labels to run on different configurations.
Refs: https://github.com/stackrox/stackrox/pull/1223
> Add eks and kops for dependabot e2e labels

- ui/apps/platform/src/Components/PatternFly/ConfirmationModal/ConfirmationModal.css
- ui/apps/platform/src/Components/PatternFly/ConfirmationModal/ConfirmationModal.tsx
- ui/apps/platform/src/Components/PatternFly/ConfirmationModal/index.ts
- ui/apps/platform/src/Containers/Policies/PatternFly/Modal/EnableDisableNotificationModal.tsx
- ui/apps/platform/src/Containers/Policies/PatternFly/Table/PoliciesTable.tsx
- ui/apps/platform/src/Containers/Policies/PatternFly/Table/PoliciesTablePage.tsx
- ui/apps/platform/src/hooks/patternfly/useToasts.tsx
As the title states above. The wording and functionality should all be the same as the classic Policies UI. You should be able to spin a 68 demo up via infra or you can use mine at https://ls0411boilingflamegrease.demo.stackrox.com/ to compare.
Single notifier integrated:
Enabling:
Disabling:
Multiple notifiers integrated:
disabling just slack:
disabling both:
screenshots.
instructions and make sure they are …
> ROX-9985: Adding enable/disable notifications bulk action to policies table

- .openshift-ci-migration/binary_build_commands.sh
- .openshift-ci-migration/lib.sh
- .openshift-ci-migration/migrate.sh
- .openshift-ci/build/Dockerfile.build-main
- .openshift-ci/build/Dockerfile.main
- .openshift-ci/build/Dockerfile.pre-build-cli
- .openshift-ci/build/Dockerfile.pre-build-go-binaries
- .openshift-ci/build/Dockerfile.pre-build-ui
- .openshift-ci/dispatch.sh
- central/policy/service/service_impl.go
- scripts/ci/lib.sh
- scripts/lib.sh
This is a minimal PR to provide scaffolding for a build process in OSCI. At present nothing is built. Once the companion [PR](https://github.com/openshift/release/pull/27782) in OSCI is merged the build can be completed. It anticipates 3 pre steps, a bundler, and the final image 🤞.
CI is sufficient - a minor change in scripts/lib.sh needs exercise.
> OSCI: Build scaffolding

- central/deployment/datastore/datastore_impl.go
- central/deployment/datastore/datastore_impl_test.go
- central/deployment/datastore/internal/search/searcher_impl.go
- central/deployment/store/cache/cache.go
- central/deployment/store/cache/cache_test.go
- central/deployment/store/dackbox/bench_test.go
- central/deployment/store/dackbox/store_impl.go
- central/deployment/store/dackbox/store_impl_test.go
- central/deployment/store/mocks/store.go
- central/deployment/store/store.go
Standardize and add contexts to the deployment store prior to adding the postgres store
CI should be sufficient as nothing should really change
> Add context and rename deployment store functions

- tools/generate-helpers/pg-table-bindings/store.go.tpl
In store.go.tpl in every function we define scope checker. This PR introduces template that simplify this process.
CI
> Use template to generate checker

- central/secret/datastore/datastore_sac_test.go
- qa-tests-backend/src/test/groovy/SACTest.groovy
~~- [ ] Documented user facing changes (create PR based on [stackrox/openshift-docs](https://github.com/stackrox/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~
Activated tests from PR 942
> ROX-10025: Scoped access control for resource Secret - enable integration SAC search tests

- ui/apps/platform/src/Containers/Integrations/utils/integrationUtils.ts
- ui/apps/platform/src/Containers/Integrations/utils/integrationsList.ts
- ui/apps/platform/src/types/integration.ts
Increase type safety for future editing
1. Edit and rename src/Containers/Integrations/utils/integrationsList.js
* Define `IntegrationDescriptor` type with separate source types
* Delete leftover properties: `disabled` and `typeLabel`
2. Edit src/Containers/Integrations/utils/integrationUtils.ts
* Move `IntegrationSource` and `IntegrationType` to types file to prevent circular dependency with integrationsList
3. Add src/types/integration.ts
* Separate string union for types by source
* Comment out 4 strings pending investigation
1. Investigate 4 strings which are keys in tableColumnDescriptor but not in integrationsList:
```ts
export type IntegrationType =
| 'oidc'
| 'auth0'
| 'saml'
| 'iap'
```
2. Write frontend proto files
* https://github.com/stackrox/stackrox/blob/master/proto/storage/ …
> Rewrite integrationsList file in TypeScript

- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
> ROX-7902: disable syslog notification integration tests due to flakiness

- operator/Makefile
Test-only change.
Relying on CI.
> ROX-8550 bump scorecard wait time to 5 minutes

- .circleci/config.yml
- pkg/features/list.go
- ui/apps/platform/src/utils/featureFlags.ts
(see title)
* Exploratory testing that pages with other feature flags still work
* CI still passes
> ROX-10296: Add feature flag for ROX_NEW_POLICY_CATEGORIES

- central/imagecomponentedge/datastore/datastore_impl.go
- central/imagecomponentedge/datastore/singleton.go
- central/imagecomponentedge/search/searcher_impl.go
- central/imagecomponentedge/search/searcher_impl_v2.go
- central/imagecomponentedge/store/dackbox/store_impl.go
- central/imagecomponentedge/store/mocks/store.go
- central/imagecomponentedge/store/store.go
- ~Documented user facing changes ~
> [ROX-10607] Align image-component relation datastore for postgres

- roxctl/sensor/util/central_env.go
> Fix typo Valutes -> Values

- pkg/scanners/clairify/convert_test.go
I should have probably added this test before, but I forgot oops
CI
> Add node note conversion test

- tools/generate-helpers/pg-table-bindings/main.go
Currenlty we are printing just error and this information is not helpful without the file.
This PR prints a sinnippet around the line where the error occuerd.
**Before:**
```
Error: store_test.go:169:57: missing ',' before newline in composite literal (and 1 more errors)
```
**After:**
```go
Generating for storage.Alert
There is an error in following snippet: missing ',' before newline in composite literal
return map[string]context.Context {
withAllAccess: sac.WithAllAccess(context.Background())
withNoAccess: sac.WithNoAccess(context.Background())
Error: store_test.go:169:57: missing ',' before newline in composite literal (and 1 more errors)
```
CI
> Print file on go error for gogen

- CHANGELOG.md
No Testing or CI results inspection required as this pull request just updates change log.
> [ROX-10666] : Add deprecation notice for FROM option in Disallowed docker file line policy criteria

- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/vulnerabilities_v2.go
In order to define what functions will need to be supported in the migration and prevent the usage of unsupported functions being added to the resolver in the future, we will define a new struct to capture the intended API for image vulnerabilities. This required a quick refactor of the vulnerabilitiesV2 code to resolve some compilation errors.
> ROX-10201: Define more restrictive API for image vulnerability graphql resolver

- scale/workloads/np-load.yaml
- sensor/kubernetes/fake/deployment.go
- sensor/kubernetes/fake/fake.go
- sensor/kubernetes/fake/networkpolicy.go
- sensor/kubernetes/fake/workload.go
- sensor/kubernetes/listener/resources/networkpolicy.go
Create a fake workload to tests updates on `NetworkPolicies`.
* Execute `./scale/launch_workload.sh np-load` and see that we are receiving `NetworkPolicy` updates.
> ROX-10013 - NetworkPolicy Workload

- ui/apps/platform/package.json
- ui/packages/ui-components/package.json
- ui/yarn.lock
https://github.com/microsoft/TypeScript/releases/tag/v4.6.4
This release includes a bug fix for text formatting on certain ranges, which was impacting Visual Studio users.
> Update TypeScript 4.6.4 devDependencies in ui

- central/globaldb/postgres.go
> Fix postgres object counts

- CHANGELOG.md
Updating CHANGELOG.md
Just a CHANGELOG.md update.
> Update CHANGELOG.md in prep for 70.0 release

- central/authprovider/datastore/internal/store/postgres/store.go
Fix CI step `check-generated-srcs` which [is currently failing on main.](https://app.circleci.com/pipelines/github/stackrox/stackrox/11183/workflows/f3d138ad-0d1f-41fe-8fc9-217c9f76cbba/jobs/516633)
- see CI
> Re-generate code to fix CI.

- .circleci/config.yml
- release/scripts/vuln_check.sh
It looks like quay get back to life. This PR reverts couple of PRs that were added to mitigate issues with quay.io.
CI
> Enable vuln scan on nightlies

- qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
- qa-tests-backend/src/test/groovy/CSVTest.groovy
- qa-tests-backend/src/test/groovy/CVETest.groovy
- qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
- qa-tests-backend/src/test/groovy/DeploymentTest.groovy
- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
- qa-tests-backend/src/test/groovy/K8sRbacTest.groovy
- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
- qa-tests-backend/src/test/groovy/PolicyFieldsTest.groovy
- qa-tests-backend/src/test/groovy/SummaryTest.groovy
- qa-tests-backend/src/test/groovy/VulnMgmtTest.groovy
Couple of tests are constantly failing on postgres. This PR ignores them so PG test should be green for every next commit.
CI
> Skip E2E tests on postgres

- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
> Fix network flow test by handling new default namespace label in 1.21

- central/authprovider/datastore/internal/store/postgres/store.go
- central/notifier/datastore/internal/store/postgres/store.go
- central/postgres/schema/authproviders.go
- central/postgres/schema/notifiers.go
- central/postgres/schema/permissionsets.go
- central/postgres/schema/signatureintegrations.go
- central/postgres/schema/simpleaccessscopes.go
- central/role/store/permissionset/postgres/store.go
- central/role/store/simpleaccessscope/postgres/store.go
- central/signatureintegration/store/postgres/store.go
- pkg/postgres/walker/schema.go
Unique fields need to be top leveled to be included
screenshots.
> Include fields that are marked with unique

- central/processindicator/datastore/datastore_sac_test.go
- pkg/fixtures/indicator.go
Added integration tests for Process Indicators DataStore + Search.
- CI
> ROX-10785: Add integration tests for ProcessIndicators store.

- qa-tests-backend/src/test/groovy/GlobalSearch.groovy
Postgres surfaced an issue with the global search. Therefore, Assert on correct condition when running on postgres.
CI
> Update GlobalSearch E2E Test

- central/processindicator/datastore/datastore_sac_test.go
- pkg/fixtures/indicator.go
Address minor review comments from #1589 .
> Additional review comments for ProcessIndicator integration tests.

- pkg/sac/scope_checker_or.go
Address review comments added post-merge within #1492 .
- CI unit tests
> Address post-merge review comments for or scope checker.

- .github/pull_request_template.md
- .gitmodules
We do not want to use the fork anymore as we changed the processes and have more time to do a proper review in the official repo for docs.
- CI only
> Use docs from the openshift repo

- image/postgres/Dockerfile
Fix package [conflicts](https://app.circleci.com/pipelines/github/stackrox/stackrox/11585/workflows/88c2755f-4996-409c-9fe5-ddca8794e38d/jobs/537348) with `--nobest`. 
> fix central-db-image build

- central/reprocessor/reprocessor.go
- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
> Enable ImageScanningTest E2E Test

- qa-tests-backend/src/test/groovy/RiskTest.groovy
> Fix typo in test

- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
> Enable ImageManagementTest

- central/image/datastore/internal/store/postgres/store.go
- qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
- qa-tests-backend/src/test/groovy/PolicyFieldsTest.groovy
> Enable Policy E2E Tests on postgres

- scripts/release-tools/clusters.sh
Added an option to start a demo qa GKE cluster to clusters.sh
See above
> ROX-10931: Automate creation of GKE demo clusters for RCs [skip ci]

- .gitmodules
Updated docs submodule.
See above
> update docs content 3.70.0

- qa-tests-backend/src/main/groovy/services/ImageService.groovy
- qa-tests-backend/src/test/groovy/Services.groovy
Use logger in test services.
This is part of https://github.com/stackrox/stackrox/pull/1705
CI
> Add logger in qa-test services

- central/graphql/resolvers/common_vulnerabilities.go
- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/node_vulnerabilities.go
Abstract out common vulnerability fields from more specifically created types
> ROX-10771: create common vulnerability struct

- qa-tests-backend/src/test/groovy/DeploymentEventGraphQLTest.groovy
- qa-tests-backend/src/test/groovy/DeploymentTest.groovy
- qa-tests-backend/src/test/groovy/RuntimePolicyTest.groovy
- qa-tests-backend/src/test/groovy/RuntimeViolationLifecycleTest.groovy
RE: https://app.circleci.com/pipelines/github/stackrox/stackrox/12159/workflows/aad2e287-6ab4-4500-b1d2-4be5a9290539/jobs/567349/tests
> CI: more rate limit avoidance

- qa-tests-backend/codenarc-rules.groovy
- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
- qa-tests-backend/src/test/groovy/CSVTest.groovy
- qa-tests-backend/src/test/groovy/ComplianceTest.groovy
- qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy
Prevent errors print stacktrace and use logger instead.
This is part of https://github.com/stackrox/stackrox/pull/1705
CI
> Do not print stack trace in qa test

- .gitignore
- qa-tests-backend/.idea/codeStyles/Project.xml
- qa-tests-backend/.idea/codeStyles/codeStyleConfig.xml
- qa-tests-backend/build.gradle
- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
- qa-tests-backend/src/test/groovy/ReconciliationTest.groovy
Please see descriptions in individual commits.
Imports style discussion here https://srox.slack.com/archives/CELUQKESC/p1652894687367059
- ~~[ ] Unit test and regression tests added~~ - this **is** a change for tests.
- ~~[ ] Evaluated and added CHANGELOG entry if required~~ - not required.
- ~~[ ] Determined and documented upgrade steps~~ - no upgrade needed.
- ~~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~ - no user-facing changes here.
> ROX-11005, ROX-11006: Fix race-condition-tests, add Groovy style

- central/risk/datastore/internal/search/searcher_impl.go
Add PostgresSearchHelper to Risk's `searcher` conditionally if the feature flag for postgres is enabled.
- Integration tests will be added within a follow-up PR in the scope of [ROX-10787](https://issues.redhat.com/browse/ROX-10787)
> ROX-10788: Add PostgresSearchHelper to risk searcher.

- .gitmodules
> Jv/update docs content 3.68.2

- .gitmodules
Update docs/content submodule for 3.69.2.
See above.
> Jv/update docs content 3.69.2 second try

- operator/Makefile
> ROX-10935: Switch to a kuttl build which logs more details of unexpected resources.

- pkg/helm/charts/tests/centralservices/flavor/testdata/helmtest/development/development.test.yaml
- pkg/helm/charts/tests/securedclusterservices/flavor/testdata/helmtest/development/development.test.yaml
- pkg/images/defaults/flavor.go
- tests/roxctl/bats-tests/helpers.bash
- tests/roxctl/bats-tests/local/central-generate-development-postgres.bats
- tests/roxctl/bats-tests/local/central-generate-development.bats
- tests/roxctl/bats-tests/local/central-generate-interactive-flavors-postgres.bats
- tests/roxctl/bats-tests/local/central-generate-interactive-flavors.bats
- tests/roxctl/bats-tests/local/roxctl-helm-output-central-development.bats
- tests/roxctl/bats-tests/local/roxctl-helm-output-secured-cluster-services-development.bats
Simple change in development flavor
Ran flavor_test.go
> ROX-10081: update development build image flavor from docker to quay

- central/image/datastore/datastore_impl_test.go
Occasionally, `TestImageDataStore` will flake (see [here](https://app.circleci.com/pipelines/github/stackrox/stackrox/12491/workflows/726ec04c-122e-45f6-9fc9-767cd18774e8/jobs/584039)).
The issue seems to stem from the bleve index path that is created within a temporary directory.
Instead of relying on the directory and the index to be persisted, use `bleve.MemOnlyIndex()` within tests (as is used within other datastore tests, i.e. `k8srole, k8srolebinding, processindicator, secrets...`).
Additionally, refactored some of the test suite to use `Require` instead of `FailNow`, `Require` for no error to avoid potential nil-pointer panics within tests.
- see CI.
> Fix flaky unit tests within ImageDataStore.

- qa-tests-backend/src/main/groovy/services/GraphQLService.groovy
- qa-tests-backend/src/test/groovy/DeploymentEventGraphQLTest.groovy
- qa-tests-backend/src/test/groovy/GraphQLResourcePaginationTest.groovy
- qa-tests-backend/src/test/groovy/IntegrationsSplunkViolationsTest.groovy
- qa-tests-backend/src/test/groovy/K8sRbacTest.groovy
- qa-tests-backend/src/test/groovy/VulnScanWithGraphQLTest.groovy
Skip e2e tests that are failing on master branch.
CI
> Skip failing PG e2e tests

- ui/apps/platform/README.md
* Feature flags: follow up on #1577
* API seems like the next most useful explanation
> Explain feature flags in CI, types, and services in README for Platform UI

- generated/internalapi/central/cluster_metrics.pb.go
- proto/internalapi/central/cluster_metrics.proto
Add comments to cluster metrics proto message.
screenshots.
> Add comments to cluster metrics proto message

- scripts/ci/gke.sh
We periodically hit timeouts when creating GKE clusters. This tends to happen during periods of high CI usage. The logic that tries to delete the cluster and try another zone typically fails. This PR increases the overall timeout for the create and the time spent polling when a timeout occurs. It also randomizes the zone order as zone limits of 50 clusters have also been observed.
> RS-537: CI: Extend GKE timeouts and shuffle

- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/resolver.go
- central/graphql/schema/test/schema_test.go
Create a test to check whether the GraphQL schema is formatted correctly. If it's not a nice message is provided
> GraphQL Schema test

- tools/local-sensor/main.go
`local-sensor` was parsing duration flag as `string`. `flag.Duration` already parses the param as a duration (e.g. `1m`, `10s`, `4h`...)
1. This command should run the scenario without stopping
```
go run ./tools/local-sensor -output results.json -verbose
```
2. This command should run the scenario for 10s then stop:
```
go run ./tools/local-sensor -output results.json -verbose -duration 10s
```
> Local sensor: use flag.Duration instead of parsing it as a string

- tools/rocksdbdump/main.go
> Add node_to_cve bucket to known unhandled bucket list

- .gitmodules
Updated docs/content 
See above
> Jv/update docs content 3.70.1

- migrator/main.go
- migrator/postgreshelper/load.go
- pkg/postgres/schema/all.go
- tools/roxvet/analyzers/validateimports/analyzer.go
This is the fix for the apply schema not working in case of bolt version does not exist.
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))
CI and manual check the log
> Apply schemas after upgrade

- .circleci/config.yml
These are now running and required in OpenShift CI.
CI is sufficient"
> CI: Remove *-unit tests

- .golangci.yml
- roxctl/helm/derivelocalvalues/derivelocalvalues.go
After refactor we need to ignore io in linter.
CI
> Ignore io package after refactoring

- central/networkpolicies/datastore/internal/store/postgres/index.go
> Fix master build by adding correct generated srcs

- central/activecomponent/updater/updater_impl.go
- central/processindicator/datastore/datastore.go
- central/processindicator/datastore/datastore_impl_test.go
SAC didn't exist here before, but now it does so we need to support this functionality
Will run and make sure I don't see these errors
> Fix SAC errors in Postgres now that SAC is in the store

- .circleci/config.yml
> ROX-11193, ROX-11305: CI: Fix EKS & OSD password leaks

- central/sensor/service/pipeline/reconciliation/reconciliation.go
`GetNumbObjectsDeleted` -> `GetNumObjectsDeleted`
None
> fix GetNumObjectsDeleted typo

- pkg/search/queryutils.go
> Make ApplyFnToAllBaseQueries handle boolean queries

- .circleci/config.yml
Reverts stackrox/stackrox#1945
> Revert "OSCI: handle non PR builds"

- central/graphql/resolvers/cluster_vulnerabilities.go
- central/graphql/resolvers/clusters.go
- central/graphql/resolvers/components_v2.go
- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/image_components.go
- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/images.go
- central/graphql/resolvers/namespaces.go
- central/graphql/resolvers/vulnerabilities_v2.go
ImageComponent resolvers and some tweaks to cluster sub resolver usage
> ROX-10205, ROX-10774, ROX-10776: Add a graphQL resolver that returns image components only

- central/detection/service/service_impl_test.go
- central/role/resources/list.go
- pkg/sac/tests/testutils.go
> Cleanup unused vars / funcs

- central/logimbue/store/postgres/store_test.go
> Regen LogImbue to pick up new changes

- central/compliance/datastore/datastore_impl.go
- central/compliance/datastore/internal/store/mocks/store.go
- central/compliance/datastore/internal/store/rocksdb/rocksdb_store.go
- central/compliance/datastore/internal/store/rocksdb/rocksdb_store_test.go
- central/compliance/datastore/internal/store/store.go
- central/compliance/datastore/test/datastore_test.go
Simple PR broken out to just handle the context alignment
CI and unit tests should still pass
> Align compliance stores with contexts

- central/cluster/store/clusterhealth/postgres/store.go
- central/cve/datastore/cluster/internal/store/postgres/store.go
- central/cve/image/datastore/internal/store/postgres/store.go
- central/cve/node/datastore/internal/store/postgres/store.go
- central/imagecomponent/datastore/internal/store/postgres/store.go
- central/networkgraph/entity/datastore/internal/store/postgres/store.go
- central/networkpolicies/datastore/internal/undodeploymentstore/postgres/store.go
- central/networkpolicies/datastore/internal/undostore/postgres/store.go
- central/nodecomponent/datastore/store/postgres/store.go
- pkg/search/postgres/common.go
- tools/generate-helpers/pg-table-bindings/multitest/postgres/store.go
- tools/generate-helpers/pg-table-bindings/store.go.tpl
- tools/generate-helpers/pg-table-bindings/test/postgres/store.go
- tools/generate-helpers/pg-table-bindings/testgraphtables/testchild1/store.go
- tools/generate-helpers/pg-table-bindings/testgraphtables/testchild2/store.go
- tools/generate-helpers/pg-table-bindings/testgraphtables/testg2grandchild1/store.go
- tools/generate-helpers/pg-table-bindings/testgraphtables/testg3grandchild1/store.go
- tools/generate-helpers/pg-table-bindings/testgraphtables/testggrandchild1/store.go
- tools/generate-helpers/pg-table-bindings/testgraphtables/testgrandchild1/store.go
- tools/generate-helpers/pg-table-bindings/testgraphtables/testgrandparent/store.go
- tools/generate-helpers/pg-table-bindings/testgraphtables/testparent1/store.go
- tools/generate-helpers/pg-table-bindings/testgraphtables/testparent2/store.go
- tools/generate-helpers/pg-table-bindings/testgraphtables/testparent3/store.go
Generate SAC query filter for delete operations for indirectly scoped resources.
CI - more test will be added in a separated PR
> ROX-11159: SAC filter on read for indirectly scoped res

- central/compliance/datastore/internal/store/postgres/strings/store.go
> Regen compliance Postgres stores

- CHANGELOG.md
Changelog for slimming domain down. This will make compliance significantly more scalable as the domain can be extremely large
just changelog
> Add a changelog entry for slimming Compliance domain

- central/graphql/resolvers/clusters.go
- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/image_components.go
- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/images.go
- central/graphql/resolvers/namespaces.go
- central/graphql/resolvers/plotted_image_vulnerabilities.go
- central/graphql/resolvers/plotted_node_vulnerabilities.go
PlottedImageVulnerabilities implementation to match the PlottedNodeVulnerabilities. Used in dashboards.
> ROX-10813: plotted image vulnerabilities

- central/compliance/common.go
- central/compliance/datastore/internal/store/postgres/store.go
- central/compliance/datastore/internal/store/strings.go
- central/compliance/datastore/singleton.go
Work in progress PR for porting compliance over to Postgres. This will initially be a naive port
Just trying to build it
> ROX-9640: Port Compliance over to Postgres

- pkg/postgres/walker/schema.go
- pkg/postgres/walker/walker.go
- pkg/search/derived_options.go
- pkg/search/general_query_parser.go
- pkg/search/options.go
- pkg/search/postgres/common.go
- pkg/search/postgres/graph_queries_test.go
- pkg/search/postgres/joins.go
- pkg/search/postgres/query/common.go
- pkg/search/queryutils.go
- pkg/search/queryutils_test.go
- pkg/search/walker.go
Support ordering by counts, and refactor derived fields so it's not as manual as it was with DackBox.
Unit tests
> Derived fields part 1: support counts

- central/graphql/resolvers/clusters.go
Manual testing to check nothing breaks in UI
> [ROX-11249] : Remove plottedVulns sub resolver from cluster

- central/graphql/resolvers/vulnerability_requests_test.go
- central/image/service/service.go
- central/image/service/service_impl.go
- central/image/service/singleton.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go
- central/vulnerabilityrequest/manager/requestmgr/singleton.go
> Remove unused instances of cve datastore

- sensor/debugger/k8s/fake.go
After the refactoring of the replaying methods to use reflection I forgot to send the proper parameter to deletion events.
Testing performed with local-sensor:
* Record the events (including remove events)
* Replay those events with local-sensor
```
go run tools/local-sensor/main.go -record
go run tools/local-sensor/main.go -replay -delay=0s
```
> ROX-11427 fix remove events

- central/globaldb/dackbox/initialize.go
> Exclude more buckets from dackbox init

- ui/apps/platform/src/Containers/Dashboard/PatternFly/Widgets/ViolationsByPolicyCategory.tsx
Adds 'Cluster' and 'Namespace ID' parameters to links from the Policy Violations by Category widget, based on the values selected by the user in the dropdowns at the top of the page.
The search options API does not return "Namespace ID" as a valid search parameter for the Violations page, which causes the value to not be displayed in the search input field. It _does_ display "Namespace ID" parameters in the browsers URL bar, and the initial search does apply these options in the backend query. This isn't great UX and the Namespace IDs are cleared from the URL if any change is made by the users in the UI.
Visit the main dashboard and set Cluster and Namespace filter values.
Click a label link in the chart and ensure that parameters are visible in the URL and search input on the Violations …
> Add cluster and namespace parameters to outbound widget links

- central/policy/service/service_impl.go
In the dry-run service, we were not waiting for a goroutine to finish processing before returning. This made it possible that the dry-run response was still being appended to even while the response was being serialized, which can cause undefined results (including a panic). Fix that by using a signal to explicitly synchronize.
See https://issues.redhat.com/browse/ROX-11461 for the stacktrace.
- ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~ …
> ROX-11461 Fix race condition in dry-run service

- scripts/ci/jobs/push-images.sh
- scripts/ci/lib.sh
Per title. This was skipped in the initial OSCI build port.
Tested on release-0.1.x.
> Add matching scanner/collector tag support to OSCI

- scripts/ci/bats/lib_release_version_test.bats
- scripts/ci/jobs/release-mgmt.sh
- scripts/ci/lib.sh
- scripts/lib.sh
Per title.
Tested on `release-0.1.x` branch.
> OSCI: Add release slack notice

- scripts/ci/compare-debug-metrics.sh
Straightforward, just want these to be in the output
postgres scale tests
> Add more metrics to the scale comparison

- central/cluster/datastore/singleton.go
- central/cve/service/service.go
- central/cve/service/service_impl.go
- central/cve/service/singleton.go
- central/deployment/datastore/singleton.go
- central/namespace/datastore/singleton.go
- central/reprocessor/reprocessor.go
-  ~Evaluated and added CHANGELOG entry if required~
CI
> Move more dackbox db inits behind feature flag

- pkg/search/postgres/common.go
- pkg/search/postgres/common_test.go
> Optimize var replacement

- qa-tests-backend/src/test/groovy/SACTest.groovy
Fixes todo made in 160779e27018b646257537626192b8e05a054bbc
CI
> Use denyall access scope in SAC test

- .github/workflows/cut-rc.yml
- .github/workflows/start-release.yml
- .github/workflows/variables.yml
```
sed -i "s/github.event.inputs/inputs/g" .github/workflows/*.yml
```
> Rename github.event.inputs to just inputs, which is the same

- central/compliance/datastore/internal/store/postgres/store.go
- pkg/postgres/walker/walker.go
- pkg/search/postgres/common.go
- pkg/search/postgres/index_test.go
- pkg/search/postgres/query/test/index_test.go
- pkg/search/query_builder.go
- qa-tests-backend/src/test/groovy/IntegrationsSplunkViolationsTest.groovy
This should fix the Splunk TA checks
Unit tests, plus e2e for splunk
> ROX-11405: Add functionality to Postgres for search after

- qa-tests-backend/src/test/groovy/ComplianceTest.groovy
This is required, but why did this test pass before
CI
> Take MachineConfig results into account for aggregations

- .github/workflows/scripts/patch-changelog.sh
- .github/workflows/start-release.yml
- .github/workflows/variables.yml
Stricter regular expression for allowed release versions.
> Minor fixes in upstream release workflows

- qa-tests-backend/src/test/groovy/ComplianceTest.groovy
- qa-tests-backend/src/test/groovy/GraphQLResourcePaginationTest.groovy
- qa-tests-backend/src/test/groovy/K8sRbacTest.groovy
- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
- qa-tests-backend/src/test/groovy/PolicyConfigurationTest.groovy
Some tests should be able to run after recent changes in postgres implementation and removal of auth plugin.
https://github.com/stackrox/stackrox/pull/2181
CI
> Unskip pg e2e tests

- central/reprocessor/reprocessor.go
In case the reprocessing loop takes longer than the ticker (i.e. in environments with a high scale), we shouldn't run two reprocessing runs in parallel, as this would slow the system down further.
Instead, check before triggering the reprocess whether a reprocessing run is currently in progress.
> Ensure no parallel reprocessing runs are triggered

- .circleci/config.yml
- .openshift-ci/dispatch.sh
- scripts/ci/jobs/local-roxctl-tests.sh
Per title. Requires: https://github.com/openshift/release/pull/29840
CI is sufficient: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/2212/pull-ci-stackrox-stackrox-master-local-roxctl-tests/1540494194081009664
> OSCI: onboard local-roxctl-tests

- tools/generate-helpers/pg-table-bindings/testgraphtables/testshortcircuit/store_test.go
> Fix semantic merge conflict with short circuit store

- release/scripts/scan-images-with-roxctl.sh
- scripts/ci/jobs/release-mgmt.sh
Scan images with rox on merge CI.
Tested in release-0.1.x. https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-release-0.1.x-push-and-release/1541979313547513856
> CI: Scan images with rox

- central/activecomponent/datastore/datastore_impl.go
- central/activecomponent/datastore/internal/store/dackbox/store_impl.go
- central/activecomponent/datastore/internal/store/dackbox/store_impl_test.go
- central/activecomponent/datastore/internal/store/mocks/store.go
- central/activecomponent/datastore/internal/store/store.go
- central/activecomponent/datastore/search/searcher_impl.go
Simple PR to add the necessary contexts and align the naming. This will allow the final Postgres PR to be much cleaner
CI
> Add contexts and align naming for ActiveComponent store

- pkg/features/list.go
- ui/apps/platform/cypress/constants/DashboardPage.js
- ui/apps/platform/cypress/helpers/main.js
- ui/apps/platform/cypress/integration/dashboard.test.js
- ui/apps/platform/src/Containers/MainPage/Body.tsx
Enables the new dashboard as the default.
> Enable feature flag for security metrics dashboard phase one

- .github/workflows/cut-rc.yml
- .github/workflows/scripts/check-jira-issues.sh
- .github/workflows/scripts/cherry-pick.sh
- .github/workflows/scripts/patch-changelog.sh
- .github/workflows/start-release.yml
* New job that prints the arguments with which the workflow has been started;
* Fix for the dry-run input parameter handling;
* Workflow-wide `GITHUB_TOKEN` variable to reduce noise.
Manual testing in `stackrox/test-gh-actions` repository.
> Cleanup and some communications improvements

- central/cve/datastore/singleton.go
- central/globaldb/dackbox/initialize.go
- central/globaldb/rocksdb.go
> Consolidate calls to globaldb

- ui/apps/platform/src/Containers/Dashboard/PatternFly/DashboardPage.tsx
- ui/apps/platform/src/Containers/Dashboard/PatternFly/Widgets/AgingImagesChart.tsx
- ui/apps/platform/src/Containers/Dashboard/PatternFly/Widgets/DeploymentsAtMostRiskTable.tsx
- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/routePaths.js
Fixes a couple of layout breakages that occur in systems with a lot of data. Also swaps widgets 4 and 5 to be consistent with the mocks.
Before:
After:
> Fix dashboard layout breakages at scale

- central/image/datastore/datastore_impl_postgres_test.go
- central/image/datastore/store/common/v2/split.go
- central/image/datastore/store/mocks/store.go
- central/image/datastore/store/postgres/store.go
- central/image/datastore/store/store.go
- central/node/datastore/dackbox/datastore/datastore.go
- central/node/datastore/dackbox/datastore/datastore_impl.go
- central/node/datastore/internal/store/common/v2/merge.go
- central/node/datastore/internal/store/postgres/store.go
Breaking up #2206 and moving out all the refactor in this PR.
> Minor Image store refactor

- central/policycategory/store/postgres/store.go
- pkg/search/sortfields/fields_map.go
- tools/generate-helpers/pg-table-bindings/list.go
> Minor fixes to policy category sort fields and sac

- .openshift-ci/build/build-central-db-bundle.sh
- .openshift-ci/build/build-main-and-bundle.sh
- .openshift-ci/dispatch.sh
- scripts/ci/lib.sh
This PR makes permanent some CI state logging which will )hopefully) make it easier to reason about changes to CI in different environments (bin, images, tests) and states (presubmit, postsubmit, periodics).
> CI: improve state debug

- qa-tests-backend/src/main/groovy/services/ProcessService.groovy
- qa-tests-backend/src/test/groovy/ProcessVisualizationTest.groovy
Following a bug found in collector, this new test covers the case where collector is not reporting process arguments correctly. 
Tested locally on docker desktop.
> Adds test to ProcessVisualizationTest for process arguments

- scripts/ci/gate-jobs-config.json
- scripts/ci/jobs/gke_postgres_qa_e2e_tests.py
- tests/e2e/lib.sh
> CI: Onboard postgres-e2e to OSCI

- ui/apps/platform/src/types/group.proto.ts
Prerequisite to rewrite GroupsService in TypeScript.
Compare to https://github.com/stackrox/stackrox/blob/master/proto/storage/group.proto
* Increase type safety with compile-time checks.
* Simplify maintenance of consistent backend and frontend response types.
> Write frontend group proto for UI

- central/compliance/standards/metadata/metadata.go
- central/complianceoperator/manager/manager.go
> ROX-9994: Add CIS OCP numbers to CO rule name

- central/cve/image/datastore/datastore.go
- central/cve/image/datastore/datastore_impl.go
- central/cve/image/datastore/datastore_impl_test.go
- central/cve/image/datastore/singleton.go
- central/cve/node/datastore/datastore.go
- central/cve/node/datastore/datastore_impl.go
- central/cve/node/datastore/datastore_impl_test.go
- central/cve/node/datastore/singleton.go
- central/cve/suppress/reprocessor_postgres_test.go
- central/image/datastore/datastore.go
- central/image/datastore/datastore_impl.go
- central/image/datastore/singleton.go
- central/image/datastore/store/postgres/store.go
- central/node/datastore/dackbox/datastore/datastore.go
- central/node/datastore/dackbox/datastore/singleton.go
- central/node/datastore/internal/store/postgres/store.go
> Enforce lock on Image and Node ops

- scripts/ci/lib.sh
set the exit code before overwrite.
> CI: Fix slack notice

- .github/workflows/create-cluster.yml
- .github/workflows/cut-rc.yml
- .github/workflows/scripts/create-cluster.sh
- .github/workflows/start-release.yml
* Allow for triggering `create-cluster` workflow manually;
* Allow for not creating cluster on Cut RC manual run;
* Fix `CHANGELOG.md` version patch on master;
* Extracted `create-cluster.sh` script;
* Always create next milestone on Cut RC. This need to be worked further to prevent side effects of milestones closed after release is published.
TODO
> ROX-11711: various fixes on Cut RC

- central/policy/datastore/datastore_impl.go
- central/policycategory/datastore/datastore_impl.go
- central/policycategory/datastore/datastore_impl_test.go
> Honor isDefault while creating, renaming and deleting policy categories

- pkg/search/options.go
Add remaining count derived fields now that namespace graph search is supported.
- ~Documented user-facing changes~
> Add remaining count derived fields

- scripts/ci/jobs/push-images.sh
> CI: Remove .x from RCs/releases notifier link

- scripts/ci/lib.sh
> CI: fix notifier for merge test failures

- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/vulnerabilities_v2.go
> GraphQL counter helper function fix

- central/graphql/resolvers/image_vulnerabilities.go
- central/vulnerabilityrequest/manager/querymgr/query_manager.go
`.id`, which was cve name in rocksdb -> `.cve` in postgres
> Pass correct value to vuln req mgr from graphQL

- qa-tests-backend/src/test/groovy/SummaryTest.groovy
> Enable summary e2e

- central/graphql/resolvers/components.go
- central/graphql/resolvers/components_v2.go
- central/graphql/resolvers/images.go
- central/graphql/resolvers/plotted_image_vulnerabilities.go
- central/graphql/resolvers/vulnerabilities.go
- central/graphql/resolvers/vulnerabilities_v2.go
> GraphQL Guard on Legacy Datastore Invocations

- .circleci/config.yml
Per title. 
EKS to verify Circle CI run.
> ROX-11476: Remove license key from QA tests

- qa-tests-backend/src/test/groovy/GlobalSearch.groovy
Enable the test now that namespace graph searching is supported.
> Enable Global e2e

- central/cluster/datastore/internal/search/searcher_impl_v2.go
- central/clustercveedge/search/searcher_impl_v2.go
- central/componentcveedge/search/searcher_impl_v2.go
- central/cve/cluster/datastore/search/searcher.go
- central/cve/image/datastore/search/searcher.go
- central/cve/node/datastore/internal/search/searcher.go
- central/deployment/datastore/internal/search/searcher_impl_v2.go
- central/image/datastore/search/searcher_impl_v2.go
- central/imagecomponent/search/searcher_impl_v2.go
- central/imagecomponentedge/search/searcher_impl_v2.go
- central/imagecveedge/search/searcher_impl_v2.go
- central/namespace/datastore/datastore.go
- central/node/datastore/internal/search/searcher_impl_v2.go
- central/nodecomponent/datastore/search/searcher.go
- central/nodecomponentcveedge/datastore/search/searcher.go
- central/nodecomponentedge/search/searcher.go
The goal here is to make sure that the dackbox object search applies scoped access control (data filtering).
This Pull request is a pre-factoring request. Tests will be added per target object type as part of https://github.com/stackrox/stackrox/pull/2375 and other pull requests.
> Prefactor: wire dackbox postgres sac search

- ui/apps/platform/cypress/helpers/policiesPatternFly.js
- ui/apps/platform/cypress/integration/policies/policiesTable.test.js
> should have row action to disable policy that has enabled status and then enable it again
> Timed out retrying after 4000ms: Expected to find element: `td[data-label="Status"]:contains("Enabled")`, but never found it.
This problem was caused by my confusion a few months ago, similar to problem recently fixed in #2376
Timing problems are likely if a test gets a DOM element, and then makes a derived assertion, even with `intercept` for request and `wait` for response.
In this case, the table re-renders after the test got a DOM element because of policies request. The test waited on PATCH request, but not GET request.
Although `changePolicyStatusInTable` function does wait for both requests, even more important it gets the expected status with a retryable assertion.
1. Edit …
> Replace wrap with retryable selectors in policies integration tests

- central/graphql/resolvers/clusters.go
- central/graphql/resolvers/components_v2.go
- central/graphql/resolvers/components_v2_test.go
- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/image_components.go
- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/images.go
- central/graphql/resolvers/namespaces.go
- central/graphql/resolvers/nodes.go
- central/graphql/resolvers/plotted_image_vulnerabilities.go
- central/graphql/resolvers/plotted_node_vulnerabilities.go
ImageComponent GraphQL Postgres support.
Some changes to the way plottedvulns gets called to streamline the style.
> ROX-11289: GraphQL Image Component Resolver Postgres Support

- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesFilterInput.tsx
- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesFilterSelect.tsx
- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesList.tsx
- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesListSection.tsx
- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesPage.tsx
- ui/apps/platform/src/types/policy.proto.ts
As title suggests -- also adding default category select dropdown as well. Should function as expected and look like below:
screenshots.
> ROX-11317, ROX-11316: Adding filter select and default category functionality to Policy Categories

- .circleci/config.yml
- operator/Makefile
- operator/README.md
- operator/hack/common.sh
- operator/hack/olm-operator-install.sh
- operator/hack/operator.envsubst.yaml
- operator/pkg/reconciler/env.go
- operator/pkg/reconciler/reconciler_factory.go
- operator/tests/common/image-pull-secrets.yaml
See descriptions in individual commits.
Note: this doesn't address ROX-10967 fully. More commits would be needed, but this fixes some issues we see already.
- ~~[ ] Unit test and regression tests added~~ - not for this change. Relying on existing tests.
The following are not included as this change is internal, not user-facing:
- ~~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~
> ROX-10967: Fix quay.io/rhacs-eng operator & /stackrox-io images

- sensor/tests/replay/replay_test.go
Activate the sensor replay tests in CI.
Check CI runs.
> Activate replay tests in CI

- .circleci/config.yml
Per title. It is in OpenShift CI now.
> ROX-11703: remove race-condition-debug flavor

- central/policycategory/datastore/singleton.go
> Fixing count of default categories added by default

- central/graphql/resolvers/cluster_vulnerabilities.go
- central/graphql/resolvers/gen/main.go
- central/graphql/resolvers/generated.go
- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/loaders/cluster_cves.go
- central/graphql/resolvers/loaders/cluster_cves_test.go
- central/graphql/resolvers/resolver.go
- central/graphql/resolvers/vulnerabilities_v2.go
> ROX-11259: Cluster Vulnerability Postgres Support

- tools/rocksdbdump/main.go
> Fix rocksdb dump issue in test, register policy categories bucket

- central/clustercveedge/datastore/store/postgres/full_store.go
- central/clustercveedge/datastore/store/postgres/gen.go
- central/cve/cluster/datastore/datastore_impl.go
- central/cve/cluster/datastore/index/index.go
- central/cve/cluster/datastore/store/postgres/full_store.go
- central/cve/cluster/datastore/store/postgres/gen.go
- central/cve/converter/v2/parts.go
- central/cve/fetcher/manager_impl_postgres_test.go
- central/cve/fetcher/orchestrator.go
- central/cve/image/datastore/store/postgres/gen.go
- central/cve/node/datastore/internal/store/postgres/gen.go
- pkg/postgres/schema/cluster_cve_edges.go
- pkg/postgres/schema/cluster_cves.go
- pkg/postgres/schema/image_cves.go
- pkg/postgres/schema/node_cves.go
> Add cluster cve tests

- scripts/ci/lib.sh
`oc image mirror` can [flake](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-merge-push-and-release/1542540425221378048). So `retry()`.
> ROX-11591: Retry oc image mirror flakes

- pkg/features/list.go
> [ROX-11837] : Enable ROX_DECOMMISSIONED_CLUSTER_RETENTION feature flag

- ui/apps/platform/src/Containers/Policies/Table/PoliciesTablePage.tsx
Fixes lint failures
`yarn lint`
> Delete unused UI imports

- central/cve/converter/utils/convert_utils.go
- central/cve/image/datastore/singleton.go
- central/image/datastore/datastore_impl_postgres_test.go
- central/image/datastore/keyfence/singleton.go
- central/image/datastore/singleton.go
- central/image/datastore/store/postgres/store.go
- pkg/fixtures/image.go
> [ROX-11908] Cleanup orphaned image dependencies

- central/node/datastore/dackbox/datastore/datastore_impl_postgres_test.go
- pkg/search/postgres/common.go
> Add temporary fix for search duplicates issue

- ui/apps/platform/cypress/constants/apiEndpoints.js
- ui/apps/platform/cypress/helpers/integrations.js
- ui/apps/platform/cypress/integration/integrations/signatureIntegrations.test.js
- ui/apps/platform/src/Containers/Integrations/IntegrationTilesPage/IntegrationTilesPage.js
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx
- ui/apps/platform/src/types/featureFlag.ts
Ivan, when it fits your priorities, can you please make corresponding changes in backend code:
* delete `ROX_VERIFY_IMAGE_SIGNATURE` feature flag
* update occurrences of `ImageSignatureVerification` in code
* integrations/signatureIntegrations.test.js
> Delete ROX_VERIFY_IMAGE_SIGNATURE feature flag in UI

- .github/labeler.yml
> CI: Run all qa tests when collector or scanner are changed

- CHANGELOG.md
Added sections to the release changelog. This improves the readability of the changelog and also automatically restricts the contents of the changelog. Added sections only for deprecations, removed features, and technical changes.
> Add sub-sections to changelog

- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/node_vulnerabilities.go
- central/graphql/resolvers/vulnerabilities_v2.go
- [] Investigated and inspected CI test results
> [ROX-11949] : Add operating system to NodeVulnerability and ImageVulnerability graphQL schema

- deploy/common/k8sbased.sh
- scale/dev/cluster.sh
- scale/dev/config.json
- scale/dev/launch_central.sh
- scale/dev/launch_sensor.sh
- scale/dev/port-forward.sh
- scale/dev/run-many.sh
- scale/workloads/10-sensors.yaml
Need to tweak clusters.sh to be bigger, but generally speaking this is how to run the multiple scale test
Running scale tests with it
> Add scripts for running multiple Sensors with scale workloads

- pkg/signatures/public_key_fetcher_test.go
> Remove failing unit test

- ui/apps/platform/src/Containers/Dashboard/PatternFly/Widgets/ViolationsByPolicyCategory.tsx
This reverses the previous design decision to have legend items in this widget run from Critical -> Low. They now are consistent with other widgets on the page and run Low -> Critical.
Load the new dashboard and scroll to the widget, the legend should start with "Low" as the leftmost item and progress to "Critical" on the right. "Low" and "Medium" should be disabled by default.
Toggle the Low and Medium on, and toggle the High and Critical off and verify that the changes are correctly reflected in the graph.
Refresh the page and ensure that persisted options are still correctly selected:
> Un-reverse order of legend in Violations by policy category widget.

- central/graphql/resolvers/components.go
- central/graphql/resolvers/components_v1.go
- central/graphql/resolvers/image_components.go
- central/graphql/resolvers/images.go
> LayerIndex resolver for image component

- central/graphql/resolvers/cluster_vulnerabilities.go
- central/graphql/resolvers/vulnerabilities.go
- central/graphql/resolvers/vulnerabilities_v1.go
- central/graphql/resolvers/vulnerabilities_v2.go
This is new support. We never had a clusters column on cluster/platform cves page.
> [ROX-11912] Add support for clusters and cluster count for cluster vulnerabilities

- ui/apps/platform/src/Containers/VulnMgmt/Entity/Cluster/VulnMgmtEntityCluster.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Component/VulnMgmtEntityImageComponent.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Component/VulnMgmtEntityNodeComponent.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Deployment/VulnMgmtDeploymentOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Deployment/VulnMgmtEntityDeployment.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Image/VulnMgmtEntityImage.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Image/VulnMgmtImageOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Namespace/VulnMgmtEntityNamespace.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Namespace/VulnMgmtNamespaceOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Node/VulnMgmtEntityNode.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Node/VulnMgmtNodeOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/RelatedEntitiesSideList.js
- ui/apps/platform/src/Containers/VulnMgmt/VulnMgmt.fragments.js
- ui/apps/platform/src/constants/workflowPages.constants.js
Fixes for incorrectly scoped and missing counts in the tile sidebar of single entity views in Vuln Management.
Exploratory testing
> Fix scoping of counts in tile sidebar for VM updates

- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
Be less tied to GCRs current state.
> CI: Allow a range of CVE count from GCR

- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesFilterSelect.tsx
- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesList.tsx
- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesListSection.tsx
- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesPage.tsx
- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategorySidePanel.tsx
- ui/apps/platform/src/services/PolicyCategoriesService.ts
- ui/apps/platform/src/types/policy.proto.ts
As title suggests -- the height of the side panel form needs to be polished (was running into issues because the form is apparently a grid)
Opening/closing of the side panel should work as expected.
screenshots.
> ROX-11318: Adding side panel to policy categories page

- ui/apps/platform/src/Containers/VulnMgmt/List/Images/WatchedImagesDialog.tsx
> ROX-12002: Making repository optional in a watched image path

- scripts/ci/jobs/push-images.sh
> CI: The nightly result URL has changed

- ui/apps/platform/src/Containers/Dashboard/PatternFly/Widgets/ViolationsByPolicyCategory.tsx
Adds missing filters to links in the Violations by category chart. Previously these links only filtered by category, this allows the severity and lifecycle filters to be passed in the links as well, better matching the data displayed in the chart.
Set some severities to hidden and select a lifecycle other than "All".
Click one of the chart bars or category names to link to the Violations page and verify that the correct severity and lifecycle filters are applied to the violations search.
Return to the home page and set all severities to visible, and select a lifecycle of "All".
Click one of the chart bars or category names to link to the Violations page and verify that redundant severity and lifecycle filters are _not_ applied.
> Add lifecycle and severity filters to Violations by category widget links

- central/image/service/service_impl.go
- central/main.go
- central/reprocessor/reprocessor.go
- central/role/resources/list.go
- pkg/booleanpolicy/augmentedobjs/construct.go
- pkg/booleanpolicy/default_policies_test.go
- pkg/booleanpolicy/field_metadata.go
- pkg/features/list.go
- pkg/images/enricher/enricher_impl.go
- sensor/common/scan/scan.go
- sensor/common/scan/scan_test.go
Remove the feature flag for ImageSignatures, as the feature was released in 3.70 and we don't need it anymore.
> Remove ImageSignature feature flag.

- scripts/ci/jobs/push-images.sh
Link is broken after https://github.com/openshift/release/pull/30803 is merged
CI is sufficient. The night will tell.
> CI Improvement: Fix prow nightly link in Slack

- central/activecomponent/updater/updater_impl.go
Currently, executables are being sent to Sensor and to roxctl in cases where the image was already scanned, but it is getting scanned another time. Namely if we're scanning by name this will occur with some frequency
screenshots.
> Clear executables in cached case to ensure they aren't propagated to roxctl or Sensor

- central/cve/cluster/datastore/datastore_impl.go
- central/cve/cluster/datastore/store/mocks/store.go
- central/cve/cluster/datastore/store/postgres/full_store.go
- central/cve/cluster/datastore/store/store.go
- central/cve/fetcher/manager_impl_postgres_test.go
- central/image/datastore/datastore_impl_postgres_test.go
> Ensure that only orphaned cluster cves are cleaned up during reconciliation

- scripts/ci/jobs/osd-aws-qa-e2e-tests.sh
- scripts/ci/jobs/osd-gcp-qa-e2e-tests.sh
To make the OpenShift CI onboard process easier.
n/a
> ROX-11697: Add stubs for OSD tests

- ui/apps/platform/cypress/fixtures/auth/mypermissionsMinimalAccess.json
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/ResourceDescription.tsx
- ui/apps/platform/src/hooks/usePermissions.ts
- ui/apps/platform/src/reducers/roles.js
- ui/apps/platform/src/types/roleResources.ts
Remove AuthPlugin resource from UI code.
Extracted from #2507.
Automated testing.
> ROX-11524: (Part 1/4) Remove AuthPlugin resource from UI

- qa-tests-backend/src/test/groovy/ComplianceTest.groovy
- ui/apps/platform/cypress/fixtures/auth/mypermissionsMinimalAccess.json
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/ResourceDescription.tsx
- ui/apps/platform/src/hooks/usePermissions.ts
- ui/apps/platform/src/reducers/roles.js
- ui/apps/platform/src/types/roleResources.ts
Extracted from https://github.com/stackrox/stackrox/pull/2507.
Automated testing.
> ROX-11524: (Part 2/4) Remove auth plugin resource from QA test

- central/cluster/datastore/datastore.go
- central/cluster/datastore/datastore_impl.go
- central/cluster/datastore/datastore_impl_postgres_test.go
- central/cluster/datastore/datastore_impl_test.go
- central/cluster/datastore/singleton.go
- central/cve/cluster/datastore/datastore.go
- central/cve/fetcher/manager_impl_postgres_test.go
- central/pruning/pruning_test.go
- ~Documented user facing changes ~
Unit Test:
> Prune cluster cves when cluster is removed

- .openshift-ci/clusters.py
- .openshift-ci/dispatch.sh
- qa-tests-backend/src/main/groovy/util/Env.groovy
- scripts/ci/jobs/osd-gcp-qa-e2e-tests.sh
- scripts/ci/jobs/osd_gcp_qa_e2e_tests.py
- scripts/ci/lib.sh
- tests/e2e/lib.sh
Per title.
CI is sufficient - [passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/2632/pull-ci-stackrox-stackrox-master-osd-gcp-qa-e2e-tests/1555612320137220096) all qa tests.
> ROX-11697: Add OSD GCP e2e tests

- proto/storage/active_component.proto
- proto/storage/alert.proto
- proto/storage/cluster.proto
- proto/storage/container_runtime.proto
- proto/storage/cve.proto
- proto/storage/deployment.proto
- proto/storage/external_backup.proto
- proto/storage/http_endpoint.proto
- proto/storage/image.proto
- proto/storage/image_integration.proto
- proto/storage/kube_event.proto
- proto/storage/namespace_metadata.proto
- proto/storage/network_baseline.proto
- proto/storage/network_flow.proto
- proto/storage/network_policy.proto
- proto/storage/node.proto
- proto/storage/notifier.proto
- proto/storage/policy.proto
- proto/storage/process_baseline.proto
- proto/storage/rbac.proto
- proto/storage/report_configuration.proto
- proto/storage/risk.proto
- proto/storage/service_account.proto
- proto/storage/taints.proto
- proto/storage/user.proto
- proto/storage/vuln_requests.proto
- proto/storage/vulnerability.proto
Just move all moretags to common format using ' instead of " and \"
Trivial
> Migrate proto tags to common format

- scripts/ci/jobs/osd-aws-qa-e2e-tests.sh
- scripts/ci/jobs/osd_aws_qa_e2e_tests.py
Per title.
CI is sufficient. Failures are unrelated flakes.
/test osd-aws-qa-e2e-tests
> ROX-11698: Add OSD AWS e2e tests

- central/cve/cluster/csv/handler.go
- central/cve/image/csv/handler.go
- central/main.go
- Added new routes for ImageCVE and ClusterCVE csv export.
- Added new handlers
Manual testing to check if new endpoints work correctly
instructions and make sure they are …
> [ROX-11951 + ROX-11953] : Add csv export endpoints for image CVE and cluster CVE data

- qa-tests-backend/src/test/groovy/CVETest.groovy
> Re-enable CVE end-to-end test "Verify IsFixable for entities when scoped by CVE is still correct" in postgres mode

- ui/apps/platform/cypress/helpers/vulnmanagement/entities.js
- ui/apps/platform/src/Components/ExportButton.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Cluster/VulnMgmtEntityCluster.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/ClustersWithMostOrchestratorIstioVulnerabilities.js
Final cleanup with Postgres ON for the CLUSTERS WITH MOST ORCHESTRATOR & ISTIO VULNERABILITIES widget on the VM dashboard
Verified that CI passes with feature flags OFF, too.
Manual testing
> Fix CVE counts in Clusters with Most CVEs widget for updated Vuln Mgmt

- ui/apps/platform/cypress/constants/VulnManagementPage.js
- ui/apps/platform/cypress/integration/vulnmanagement/entitypages.test.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Cve/VulnMgmtCveOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Policy/VulnMgmtEntityPolicy.js
- ui/apps/platform/src/utils/URLParser.ts
Things are going to change / I can feel it
from the song "Loser" by Beck
* Ran tests locally
* Waiting for CI
> ROX-12171-Fix CVE type UI e2e tests

- central/activecomponent/updater/updater_impl.go
Currently, if there is an error then we will never prune again. It should be safe to always retry
Will run on scale run and memory should not increase
> Always GetAndPrune in avm update function

- central/graphql/resolvers/node_components.go
- ui/apps/platform/src/Containers/VulnMgmt/widgets/TopRiskiestEntities.js
> Change nodeComponentLastScanned to lastScanned in node_components graphQL

- ui/apps/platform/src/Containers/VulnMgmt/Entity/Image/VulnMgmtEntityImage.js
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/CVESummaryLink.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/DeferredCVEs/DeferredCVEsTable.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/FalsePositiveCVEs/FalsePositiveCVEsTable.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ObservedCVEs/ObservedCVEsTable.tsx
- ui/apps/platform/src/Containers/VulnMgmt/VulnMgmt.fragments.js
Of the fixing of Postgres bugs, there is no end
Manual testing 
- CVE links in Observed, Deferred, and False Positive tables no longer crash
- Components show up in Dockerfile display again
> Fix Observed, Deferred, False Positive CVE links, and Dockerfile

- pkg/features/list.go
- sensor/kubernetes/listener/listener.go
Disable the feature flag now that the feature is released and in production.
UI follow up at https://github.com/stackrox/stackrox/pull/2442
- ~[ ] Documented user-facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~
Crossed out what does not apply.
- UT & CI
> Remove ECRAutoIntegration feature flag

- ui/apps/platform/src/Containers/VulnMgmt/List/Cves/ListCVEs.utils.js
BE team is fixing API to provide this data again, but this PR will show it again when it's available.
Before
After
> ROX-12225: Restore Fixed In column for CVE lists scoped under components

- central/graphql/resolvers/images.go
- central/node/datastore/internal/store/common/v2/split.go
- central/ranking/singleton.go
- central/risk/datastore/datastore.go
- central/risk/datastore/datastore_impl.go
- migrator/migrations/n_35_to_n_36_postgres_nodes/common/v2/split.go
Add a new ranker for node components otherwise, node and image component priorities are set in the same sequence. Also, added missed operating system and fixed race in graphQL
Manual
> [ROX-12242] New risk ranker for node components

- image/templates/helm/stackrox-secured-cluster/README.md.htpl
~~- [ ] Investigated and inspected CI test results~~
No testable changes
> Correct image names in Helm README.md.htpl

- scale/dev/cluster.sh
- scale/dev/launch_central.sh
Changes are clear
screenshots.
> Minor clean up to dev scale scripts

- scripts/ci/jobs/openshift_beta_operator_e2e_tests.py
- scripts/ci/jobs/openshift_newest_operator_e2e_tests.py
- scripts/ci/jobs/openshift_oldest_operator_e2e_tests.py
- scripts/ci/jobs/openshift_penultimate_operator_e2e_tests.py
To be used by the jobs defined in https://github.com/openshift/release/pull/31489
This will be tested in the aforementioned PR.
> ROX-11900: symlinks for more operator e2e test jobs

- qa-tests-backend/src/main/groovy/services/CVEService.groovy
- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
> Re-enable image management e2e tests in postgres mode

- operator/README.md
~~- [ ] Investigated and inspected CI test results~~
Documentation changes only
I tested locally the steps from the README.md that I changed.
> Replace docker.io with quay.io in operator readme

- central/clustercveedge/datastore/store/postgres/gen.go
- central/componentcveedge/datastore/store/postgres/gen.go
- central/imagecomponentedge/datastore/internal/store/postgres/gen.go
- central/imagecveedge/datastore/postgres/gen.go
- central/nodecomponentcveedge/datastore/store/postgres/gen.go
- central/nodecomponentedge/store/postgres/gen.go
- tools/generate-helpers/pg-table-bindings/main.go
Rename `--join-table` to `--read-only-store`.
CI
> Rename postgres generator flag

- scripts/ci/jobs/gke_version_compatibility_tests.py
In order to add a new prow step, we first need to have a stub for its step in this repository. After this step is here, we can add a config for it in [openshift/release](https://github.com/openshift/release).
None
> ROX-11770: Add prow step stub for version compatibility test

- scripts/ci/jobs/openshift_newest_qa_e2e_tests.py
Preparing ground for change job name as [mentioned in a past PR](https://github.com/openshift/release/pull/31489#pullrequestreview-1078355016).
This will be tested by a rehearse job in [an upcoming PR](https://github.com/openshift/release/pull/31587).
> Symlink for new openshift-4-qa test job name.

- go.mod
Ran `go mod tidy` to update the `go mod` file.
> Fix go.mod file

- qa-tests-backend/src/test/groovy/ComplianceTest.groovy
Followup to #2786
Relying on CI.
> Replace some test name references

- .github/workflows/cut-rc.yml
- .github/workflows/scripts/check-jira-issues.sh
- .github/workflows/scripts/patch-changelog.sh
Formatting and improved dry-run experience.
Locally and in `test-gh-actions` repository.
> Upstream release automation: minor fixes

- pkg/nodes/converter/convert_utils.go
- pkg/nodes/converter/convert_utils_test.go
> [ROX-12311] Copy node fixed by into new vuln

- pkg/sac/mocks/scope_checker.go
- pkg/sac/scope_checker.go
- pkg/sac/scope_checker_or.go
- pkg/sac/tests/scope_checker_or_test.go
> Remove TryAnyAllowed

- pkg/sac/mocks/scope_checker.go
- pkg/sac/scope_checker.go
- pkg/sac/scope_checker_or.go
- pkg/sac/tests/scope_checker_or_test.go
> Remove TryAllAllowed

- image/rhel/Dockerfile.envsubst
Add jemalloc to main dockerfile in order to prep for having RocksDB utilize it
Long running testing already performed
> Add jemalloc to main Dockerfile

- .openshift-ci/Dockerfile.build_root
This expands current instructions and hopefully will help others avoid pitfalls I fell into recently when working on https://github.com/stackrox/stackrox/pull/2762
None: not a functional change
> Expand the doc on how to test a new version of the CI build image

- central/compliance/datastore/sac_filter.go
- central/networkpolicies/datastore/datastore_impl.go
- central/node/datastore/dackbox/globaldatastore/datastore.go
- pkg/sac/mocks/scope_checker.go
- pkg/sac/scope_checker.go
- pkg/sac/scope_checker_or.go
- pkg/sac/scope_key.go
- pkg/sac/search_helper.go
- pkg/sac/tests/allow_fixed_scopes_checker_core_test.go
- pkg/sac/tests/scope_checker_or_test.go
There is no need to try with only built in authorizer and no error scope checker.
CI
> Remove TryAllowed from scope checker

- central/graphql/resolvers/policies.go
- central/graphql/resolvers/violations.go
Use the count function and exact matches for IDs
Trivial
> Optimize violation count in policies resolver

- .dockerignore
- scripts/ci/lib.sh
> RS-509: Remove outdated comments

- central/graphql/resolvers/clusters.go
- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/k8sroles.go
- central/graphql/resolvers/loaders/deployments.go
- central/graphql/resolvers/namespaces.go
- central/graphql/resolvers/pods.go
- central/graphql/resolvers/policies.go
- central/graphql/resolvers/secrets.go
- central/graphql/resolvers/service_accounts.go
- central/graphql/resolvers/violations.go
- central/pod/datastore/datastore.go
- central/pod/datastore/datastore_impl.go
- central/pod/datastore/mocks/datastore.go
> Use Count function in all GraphQL resolvers instead of search and length

- central/main.go
> ROX-12293: Disable DB backup and restore for managed central

- .github/workflows/start-release.yml
A new step in "Start Release" automation.
Locally and in `test-gh-actions` repository:
https://github.com/stackrox/test-gh-actions/actions/runs/2912915223
> ROX-12015: Configure OSCI branch for stackrox upstream build

- ui/apps/platform/src/Components/workflow/TableCountLinks/TableCountLinks.tsx
- ui/apps/platform/src/Containers/VulnMgmt/Entity/TableWidgetFixableCves.js
- ui/apps/platform/src/Containers/VulnMgmt/fixableVulnTypeContext.js
- ui/apps/platform/src/constants/entityTypes.ts
- ui/apps/platform/src/utils/queryService.js
- ui/apps/platform/src/utils/queryService.test.js
* Primary goal: show correct Entities column data in fixable CVEs table in Image Component Overview (and verified that other Entities columns still work, with and without feature flag ON)
* Piggybacking simplified queries for split CVE and split COMPONENT types, after brainstorming with Mandar 
Example on Image Component Overview, fixable CVEs table with correct entities
Image CVE query
Node CVE query
Cluster CVE query
Image Component query
Node Component query
> ROX-12339: Untangle entities column in fixable CVEs tables (with updated queries)

- central/compliance/manager/manager_impl.go
- central/networkpolicies/service/service_impl.go
- pkg/sac/mocks/scope_checker.go
- pkg/sac/scope_checker.go
- pkg/sac/scope_checker_or.go
- pkg/sac/tests/scope_checker_or_test.go
Since builting authenticator does not return error we don't need it in AllAllowed method.
CI
> Simplify AllAllowed

- pkg/sac/filter.go
- pkg/sac/for_resource_helpers.go
- pkg/sac/mocks/scope_checker.go
- pkg/sac/scope_checker.go
- pkg/sac/scope_checker_or.go
- pkg/sac/scope_key.go
- pkg/sac/search_helper.go
- pkg/sac/tests/allow_fixed_scopes_checker_core_test.go
- pkg/sac/tests/scope_checker_or_test.go
- pkg/search/filtered/sac_filter.go
Deprecate Allowed and create IsAllowed instead to simiplify the code as we don't need to return error after removal of auth plugin.
CI
> Create IsAllowed and deprecate Allowed

- qa-tests-backend/src/main/groovy/orchestratormanager/OpenShift.groovy
- scripts/ci/jobs/aro_qa_e2e_tests.py
- scripts/ci/jobs/gke_version_compatibility_tests.py
- scripts/ci/jobs/openshift_4_operator_e2e_tests.py
- scripts/ci/jobs/rosa_qa_e2e_tests.py
Per title + some reformat.
n/a
/test openshift-newest-qa-e2e-tests
> ROX-11699-ROX-11700: Prow stubs for ARO and ROSA jobs

- ui/apps/platform/src/Containers/Clusters/ClustersSidePanel.tsx
Change wording for Operator-managed Cluster warning
> ROX-12395: update operator managed cluster warning copy

- CHANGELOG.md
- ui/apps/platform/src/Containers/VulnMgmt/List/Cves/VulnMgmtListCves.js
- ui/apps/platform/src/services/VulnerabilitiesService.js
Pulled required FE changes from #2849.
See
> [ROX-12403][FE] Send cve names to suppress/unsupress API

- ui/apps/platform/src/Containers/MainPage/CredentialExpiryBanner.tsx
> Network Graph Search should filter to show only the deployments from the stackrox namespace and deployments connected to them
> Timed out retrying after 4000ms: Expected to find element: `h1:contains("Network Graph")`, but never found it.
at visitNetworkGraph
at visitNetworkGraphWithNamespaceFilter
cypress/integration/networkGraph/networkGraph.test.js
Here is the same test in local deployment after change to prevent unneeded credentialexpiry requests:
* 1564230427168739328 from master build for #2946 on 2022-08-29
For comparison, here is a picture related to this item under **Residue** in #2873
> Investigate double pair of credentialexpiry requests.
The test failed because of timeout before the container even made its requests. The /v1/clusters request is from network sagas, not the …
> Prevent unneeded credentialexpiry requests

- central/graphql/resolvers/node_components_test.go
- central/graphql/resolvers/node_vulnerabilities_test.go
- central/graphql/resolvers/test_utils.go
> [Rox-12234] : NodeComponent GraphQL endpoint tests

- sensor/debugger/k8s/fake.go
Manage the `SYNC_RESOURCE` action in `local-sensor`
```
go run tools/local-sensor/main.go -record
```
```
go run tools/local-sensor/main.go -replay -delay=0s
```
> Manage SYNC_RESOURCE action in local-sensor

- .openshift-ci/build/build-main-and-bundle.sh
- Makefile
- deploy/common/k8sbased.sh
- dev-tools/roxctl.sh
- image/rhel/Dockerfile.envsubst
- image/roxctl/Dockerfile
- image/templates/README.md
- make/env.mk
- operator/Dockerfile
- qa-tests-backend/local-test-example/step1-setup-macos.sh
- scripts/ci/lib.sh
- scripts/ci/roxctl-publish/prepare.sh
- scripts/go-tool.sh
- tests/roxctl/bats-tests/helpers.bash
- tests/upgrade/run.sh
- ui/apps/platform/src/Containers/MainPage/Header/CLIDownloadMenu.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step2/DownloadCLIDropdown.tsx
- ui/apps/platform/src/services/CLIService.js
This reverts commit 8773303de209234ae5988ada7793c865d96d44f0.
> Revert "Support multi-arch binaries (#2820)"

- deploy/common/k8sbased.sh
```
deployment.apps/central created
service/central created
/home/gavin/go/src/github.com/stackrox/stackrox/deploy/common/k8sbased.sh: line 344: [[: command not found
Deploying Scanner...
serviceaccount/scanner created
```
A space is required after [[
Re: #2675
> Fix deploy error

- .openshift-ci/build/build-main-and-bundle.sh
- Makefile
- deploy/common/k8sbased.sh
- dev-tools/roxctl.sh
- image/rhel/Dockerfile.envsubst
- image/roxctl/Dockerfile
- image/templates/README.md
- make/env.mk
- operator/Dockerfile
- qa-tests-backend/local-test-example/step1-setup-macos.sh
- scripts/ci/lib.sh
- scripts/ci/roxctl-publish/prepare.sh
- scripts/go-tool.sh
- tests/roxctl/bats-tests/helpers.bash
- tests/upgrade/run.sh
- ui/apps/platform/src/Containers/MainPage/Header/CLIDownloadMenu.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step2/DownloadCLIDropdown.tsx
- ui/apps/platform/src/services/CLIService.js
This reverts #2945 and reinstates #2820.
/cc @misberner
> Support multi-arch binaries

- .github/workflows/start-release.yml
1. Environment variables refactoring;
2. Removed presubmit and scheduled jobs files removal, as they're required for the openshift/release tests to pass;
3. Removed usage of the roxbot personal token.
Dry-run in `test-gh-actions` repo: https://github.com/stackrox/test-gh-actions/actions/runs/2969852831
> Upstream automation: polishing OSCI configuration automation

- central/config/datastore/singleton.go
- central/deployment/datastore/datastore.go
- central/deployment/service/service_impl_test.go
- central/deployment/store/postgres/full_store.go
- central/globaldb/postgres.go
- central/installation/store/singleton.go
- central/main.go
- central/networkgraph/entity/datastore/datastore_impl.go
- central/pod/datastore/datastore.go
- central/pruning/pruning_test.go
- central/reprocessor/reprocessor_test.go
- central/search/service/service_impl_test.go
- central/sensorupgradeconfig/datastore/singleton.go
- central/version/ensure_test.go
- central/version/store/store.go
- central/version/store/store_impl_test.go
In some places we still have context.TODO.
This PR rmeoves it and replaces with somtehing more suitable.
CI
> ROX-9663 Replace context.TODO

- scripts/ci/jobs/aro_qa_e2e_tests.py
- scripts/ci/jobs/rosa_qa_e2e_tests.py
Per title.
/test aro-qa-e2e-tests <- passes
/test rosa-qa-e2e-tests <- fails due to a known quota issue
> ROX-11699, ROX-11700: Onboard ARO and ROSA

- ui/apps/platform/src/Components/IconWidget.js
- ui/apps/platform/src/queries/node.js
A two-for-one special, the same deletion in a GraphQL query fixes these two separate bugs in Jira.
Bonus: I fixed the overflow of long names in the classic-style Container Runtime widget on Compliance > Node sidepanel. 
Before
After
> ROX-12383, ROX-12426: Remove vuln stuff from Config Mgmt and Compliance node GraphQL query

- qa-tests-backend/gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/7.5.1/release-notes.html
CI
> Bump gradle to 7.5

- CHANGELOG.md
> Changelog for substring string search

- .github/workflows/scripts/check-jira-issues.sh
- scripts/release-tools/jira.sh
* look for finished issues with open PRs;
* include uncategorized issues;
* ignore epics and feature requests.
Local testing.
> Improve JQL queries for spotting unfinished issues

- CHANGELOG.md
Not needed for Changelog update
> [ROX-12496] : Add deprecation notice for csv export endpoint and provide info about new endpoints to use

- .gitmodules
> Update docs to 3.72

- central/role/resources/list.go
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/ResourceDescription.tsx
> Clarify what new resources are for

- ui/apps/platform/src/Containers/VulnMgmt/Dashboard/VulnMgmtDashboardPage.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/ClustersWithMostClusterVulnerabilities.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/MostCommonVulnerabilities.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/MostCommonVulnerabiltiesInDeployment.js
1. another perf optimization: imageCount is called twice https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/VulnMgmt/widgets/MostCommonVulnerabilities.js#L37
1. and here: https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/VulnMgmt/widgets/MostCommonVulnerabiltiesInDeployment.js#L41
Manual testing (the widgets still work)
> ROX-12510: Optimize VM widget queries

- CHANGELOG.md
screenshots.
instructions and make sure they are …
> [ROX-12531] : Update changeling to add requirement to provide CVE Type filter to CSV export queries 

- scripts/ci/lib.sh
These changes are required to support [a change to CI](https://github.com/openshift/release/pull/32043/files) (that had to be reverted) to improve performance for required tests.
Tested with: https://github.com/stackrox/stackrox/pull/3014
Run times are much improved:
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-stackrox-stackrox-ci-perf-hacks-style-checks
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-stackrox-stackrox-ci-perf-hacks-go-unit-tests
> CI: Improve perf for reqd tests

- central/graphql/resolvers/cluster_vulnerabilities.go
- central/graphql/resolvers/cluster_vulnerabilities_test.go
- central/graphql/resolvers/image_vulnerabilities_test.go
- central/graphql/resolvers/test_utils.go
> ROX-12232: Add e2e tests on Cluster Vulnerability Resolver

- central/alert/datastore/datastore_impl.go
- central/alert/datastore/datastore_test.go
- central/alert/datastore/internal/search/searcher_impl.go
- central/alert/service/service_impl.go
- central/cluster/datastore/datastore_impl.go
- central/compliance/data/repository.go
- central/compliance/manager/manager_impl.go
- central/detection/alertmanager/alert_manager_impl.go
- central/detection/alertmanager/filter_options.go
- central/graphql/resolvers/clusters.go
- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/namespaces.go
- central/graphql/resolvers/violations.go
- central/graphql/resolvers/vulnerabilities_v1.go
- central/graphql/resolvers/vulnerabilities_v2.go
- central/image/datastore/datastore_impl.go
- central/namespace/resolver.go
- central/node/datastore/dackbox/datastore/datastore_impl.go
- central/pruning/pruning.go
- central/reports/common/query_builder.go
- central/reports/common/query_builder_test.go
- central/reports/service/singleton.go
- central/risk/getters/alert_mock.go
- central/risk/multipliers/deployment/violations.go
Revert a revert commit, with fix
CI + Checked the central for suspicious entries.
Tested following workflows that pertain to the change:
- Listing alerts
- Searching alerts by cluster id, violation state, lifecycle stage.
- Resolving alert
- Listing namespaces
- Searching namespaces
> Revert "Revert "Change AddStrings queries to AddExactMatches where possible

- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
- qa-tests-backend/src/main/groovy/orchestratormanager/OpenShift.groovy
- qa-tests-backend/src/main/groovy/orchestratormanager/OrchestratorMain.groovy
- qa-tests-backend/src/test/groovy/Enforcement.groovy
In next version of fabric8 the `inNamespace(null)` will cause NPE.
CI
> Handle null namespace in Kubernetes client

- central/deployment/datastore/datastore.go
- central/graphql/resolvers/image_components_test.go
- central/graphql/resolvers/image_vulnerabilities_test.go
- central/graphql/resolvers/test_utils.go
> ROX-12233: e2e tests on image component resolver

- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/policies.go
- central/graphql/resolvers/violations.go
> [Perf][GraphQL] Use count instead of search

- scripts/ci/lib.sh
Follow up to #3073 to fix the debug message.
> CI: debug PR details failure

- qa-tests-backend/src/test/groovy/DeploymentEventGraphQLTest.groovy
Currently we use plain loop with assertions in it's body. So when condition is not satisfied we never retry.
This PR replaces for-loop with retry and return unecessary returns.
CI
> Use retry in DeploymentEventGraphQLTest

- central/deployment/datastore/datastore_impl.go
- central/reprocessor/reprocessor.go
- central/risk/manager/manager.go
- central/risk/scorer/deployment/scorer.go
- pkg/debug/verbose_log.go
- pkg/debug/verbose_log_test.go
This PR add couple of debug log statements to narrow down issue with missing deployment.
We cannot reproduce it so we hope we get more logs if it fails on nightly or other PR.
Refs: https://github.com/stackrox/stackrox/pull/2661
CI
Refs:  ROX-12096
> Add debug logs

- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/policies.go
- central/graphql/resolvers/violations.go
> Revert policy graphQL changes that have affected CI healthiness

- central/graphql/resolvers/subjects.go
- central/rbac/service/list_subjects.go
> ROX-12246: Config Management -> Users and Groups list not loading when using postgres

- scripts/ci/lib.sh
A change to the OpenShift CI environment (missing OPENSHIFT_BUILD_COMMIT) caused the slack notice to #test-failures to stop. This PR uses PULL_BASE_SHA instead and adds a fallback notice so future problems will be noticed.
Manual testing to #slack-test to ensure it works as [expected](https://srox.slack.com/archives/C740BUV25/p1663278095303109) and with a [failure](https://srox.slack.com/archives/C740BUV25/p1663278270152289).
> CI: Handle missing var name for slack notice

- central/policy/service/service_impl.go
- pkg/sac/context.go
Copy over the context scope
Will add a test
> ROX-12670,ROX-12671: Fix Postgres dry-run by propagating proper context

- ui/apps/platform/package.json
- ui/yarn.lock
Keep up with minor updates whenever the changes seem relevant.
1. https://docs.cypress.io/guides/references/changelog#10-8-0
* Several minor changes were made to reduce Cypress's memory footprint in the browser in an attempt to improve test times and reduce the likelihood of crashing the launched browser under test.
2. https://docs.cypress.io/guides/references/changelog#10-7-0
Skipped this update, because the changes did not seem relevant.
> Update cypress 10.8.0 devDependencies in ui

- central/splunk/compliance_test.go
> Fix merge conflict by using new domain objects

- EXPECTED_GO_VERSION
- operator/Dockerfile
- operator/Makefile
- scripts/ci/jobs/check-generated.sh
This follows up on this discussion https://github.com/stackrox/stackrox/pull/3126#discussion_r974928788
Not customer visible therefore other items don't apply.
* Relying on CI
> ROX-12709: Build operator using apollo-ci

- central/deployment/service/service_impl.go
- central/image/service/service_impl.go
- central/secret/service/service_impl.go
- central/vulnerabilityrequest/service/service_impl.go
> Use protobuf getter for pagination

- pkg/search/postgres/query/array_query.go
- pkg/search/postgres/query/common.go
- pkg/search/postgres/query/map_query.go
- pkg/search/postgres/query/query_functions.go
- pkg/search/postgres/query/string_query.go
- pkg/search/postgres/query/test/index_test.go
Need to run the initial query in order to get the proper scoping and where clauses for existence queries. Have some thoughts on some refactors, but shouldn't do them now
CI and large unit test
> ROX-12568: Fix array and enum autocomplete

- .golangci.yml
- qa-tests-backend/local-test-example/step1-setup-macos.sh
- tools/roxvet/analyzers/validateimports/analyzer.go
Bump go version for static check.
> go 1.18 follow up

- qa-tests-backend/src/test/groovy/GroupsTest.groovy
> Fix group tests

- central/sac/authorizer/builtin_scoped_authorizer_test.go
- go.mod
- go.sum
> Remove last occurrence of default-authz-plugin

- tools/generate-helpers/pg-table-bindings/schema.go.tpl
Edditing long lines in go template is quite hard and even harder to review.
This PR split long lines into shorter easier to review chunks.
CI
> Split long lines

- go.mod
- go.sum
- pkg/clair/convert.go
> Update Scanner dependency

- pkg/postgres/pgutils/retry.go
- pkg/search/postgres/common.go
The generic functions are just retries around functions with a defined number of variables returned
CI
> Update retry function names to be generic

- central/config/store/postgres/store.go
- central/installation/store/postgres/store.go
- central/sensorupgradeconfig/datastore/internal/store/postgres/store.go
- migrator/migrations/n_21_to_n_22_postgres_configs/postgres/postgres_plugin.go
- migrator/migrations/n_24_to_n_25_postgres_installation_infos/postgres/postgres_plugin.go
- migrator/migrations/n_48_to_n_49_postgres_sensor_upgrade_configs/postgres/postgres_plugin.go
- pkg/search/postgres/common.go
- tools/generate-helpers/pg-table-bindings/singleton.go.tpl
Same PR as the regular stores for upserts, but with singleton stores this time
CI
> Add retries to Postgres singleton stores

- pkg/postgres/schema/alerts.go
- pkg/postgres/schema/compliance_run_metadata.go
- pkg/postgres/schema/compliance_run_results.go
- pkg/postgres/schema/deployments.go
- pkg/postgres/schema/image_integrations.go
- pkg/postgres/schema/k8s_roles.go
- pkg/postgres/schema/namespaces.go
- pkg/postgres/schema/network_baselines.go
- pkg/postgres/schema/networkpolicies.go
- pkg/postgres/schema/nodes.go
- pkg/postgres/schema/pods.go
- pkg/postgres/schema/process_baseline_results.go
- pkg/postgres/schema/process_baselines.go
- pkg/postgres/schema/process_indicators.go
- pkg/postgres/schema/risks.go
- pkg/postgres/schema/role_bindings.go
- pkg/postgres/schema/secrets.go
- pkg/postgres/schema/service_accounts.go
- tools/generate-helpers/pg-table-bindings/funcs.go
- tools/generate-helpers/pg-table-bindings/list.go
- tools/generate-helpers/pg-table-bindings/main.go
- tools/generate-helpers/pg-table-bindings/schema.go.tpl
To speed up SAC filtering this PR adds hash indexes on Cluster and Namespaces.
CI
> ROX-12875: Add indexes for SAC filters

- tools/local-sensor/main.go
> Fix local-sensor style

- deploy/common/k8sbased.sh
> ROX-12894: Lower requested resources on central-db pod in local postgres

- ui/apps/platform/src/Containers/VulnMgmt/Dashboard/CvesMenu.js
> ROX-12932: Hide NaN in new Cluster Counts dropdown links while loading

- pkg/features/list.go
This PR adds a new feature-flag. The flag is unused yet, but will be used in the context of epic [ROX-10818](https://issues.redhat.com/browse/ROX-10818)
- CI is sufficient
> ROX-12837: Add Feature flag for the Full Node Scanning

- ui/apps/platform/cypress/integration/clusters/clusters.test.js
Enable tests to see if improvements to helper function have solved timing problems.
Ran tests with local deployment
> ROX-12937: Remove skip from cluster certificate expiration and health integration tests

- qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
Delete images from db before test starts so that the DefaultPolicies test picks up fresh scans.
> [ROX-1162] : Delete images before test to clear previous scans

- scripts/ci/get-slack-user-id.sh
- scripts/ci/lib.sh
The idea is to increase attention to breaking tests in `master` and prevent situations when broken tests get introduced without authors realizing it until pinged by colleagues. I've done this myself a few times and know that these situations are real.
Nothing else matters:
Played with it in `#slack-test` channel, e.g. https://srox.slack.com/archives/C740BUV25/p1665001811144699
Hope that it just works in `master`.
> Tag team member member in Slack on CI failure in `master` branch

- scripts/ci/lib.sh
This follows up on <https://github.com/stackrox/stackrox/pull/3317>. The idea is to put more comprehensive instructions for colleagues.
And nothing else matters:
* Checked in `#slack-test` - https://srox.slack.com/archives/C740BUV25/p1665054904226349
> Inform colleagues what to do on messages in `#test-failures`

- central/reports/common/report_formatter.go
- central/reports/scheduler/schedule.go
> Move imageComponents and imageVulnerabilities usage behind postgres flag in vuln reporting

- image/templates/README.md
Add meta templating documentation for feature flags and ignore file
/
> Add meta templating documentation for feature flags and ignore file

- qa-tests-backend/src/test/groovy/VulnScanWithGraphQLTest.groovy
Let's run GraphQL tests with other BATs.
CI
> Mark GraphQL tests as BAT

- central/debug/service/service.go
- roxctl/help/help.properties
> Clarify the difference between debug dump and diagnostic bundle

- ui/apps/platform/cypress/integration/networkGraph/network.test.js
Especially because order in which test files run came up recently.
> Move network integration test file into subfolder

- .github/dependabot.yaml
https://github.com/stackrox/stackrox/pull/3349#issuecomment-1271135428
> Remove not existing label from dependabot PRs

- ui/apps/platform/src/Containers/Policies/Wizard/Step4/PolicyScopeForm.tsx
To address https://github.com/stackrox/stackrox/issues/2952
~~- [ ] Documented user-facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~
> Replace createText with "Images starting with ..."

- ui/apps/platform/package.json
- ui/packages/ui-components/package.json
- ui/yarn.lock
Patch release fixes some false positive syntax errors.
https://github.com/microsoft/TypeScript/releases/tag/v4.8.4
> Update TypeScript 4.8.4 devDependencies in ui

- scripts/ci/jobs/gke_postgres_ui_e2e_tests.py
Add configuration to run ui e2e tests on postgres.
https://github.com/openshift/release/pull/32986
> ROX-13025: Run UI E2E tests on postgres

- migrator/migrations/m_108_to_m_109_compliance_run_schedules/migration.go
> ROX-12759: Fix variable name for clarity in a migration

- .github/workflows/cut-rc.yml
- .github/workflows/scripts/create-cluster.sh
These changes are to make sure the changes from https://github.com/stackrox/infra/pull/706 will be compatible with the rest of stackrox's CI.
CI via [stackrox/test-gh-actions](https://github.com/stackrox/test-gh-actions): 
- Test PR: https://github.com/stackrox/test-gh-actions/pull/49 
- Test run: https://github.com/stackrox/test-gh-actions/actions/runs/3225066721
> RS-544 Fix compatability with new infractl json output

- go.mod
- go.sum
> Bump cosign to v1.13.0

- pkg/postgres/pgtest/conn/conn.go
Some colorful logs will prevent junit log processing. Hence the fix.
screenshots.
In addition to reviewing your code, reviewers …
> ROX-13080: Remove unnecessary logs in unit test

- central/graphql/resolvers/cluster_vulnerabilities.go
- central/graphql/resolvers/clusters.go
- central/graphql/resolvers/components_v2.go
- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/image_components.go
- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/images.go
- central/graphql/resolvers/namespaces.go
- central/graphql/resolvers/node_components.go
- central/graphql/resolvers/node_vulnerabilities.go
- central/graphql/resolvers/nodes.go
- central/graphql/resolvers/plotted_image_vulnerabilities.go
- central/graphql/resolvers/plotted_node_vulnerabilities.go
> ROX-12760: Use passed context if nested resolver context is null

- CHANGELOG.md
- central/cve/cluster/csv/handler.go
- central/cve/csv/handler.go
- central/cve/image/csv/handler.go
- central/cve/node/csv/handler.go
- pkg/search/parser.go
- qa-tests-backend/src/test/groovy/CSVTest.groovy
Manually tested the CVE CSV endpoint with different CVE Types and compared with the results of calling the type specific endpoints.
In addition to reviewing your code, reviewers **must** also review your …
> [ROX-12565] : Update legacy CVE csv export handler to call CVE type specific handler

- tools/local-sensor/main.go
Enable metrics in `local-sensor`
Configure the `ROX_METRICS_PORT` variable and start a prometheus instance that gathers metrics from it:
```
export ROX_METRICS_PORT=:9090
```
Start `local-sensor` with the `-with-metrics` flag:
```
go run tools/local-sensor/main.go -replay -replay-in=trace.jsonl -delay=0s -central-out=/dev/null -with-metrics
```
You should be able to see …
> ROX-11323 Enable metrics in local-sensor

- central/resourcecollection/datastore/store/postgres/gen.go
- central/resourcecollection/datastore/store/postgres/store_test.go
- tools/generate-helpers/pg-table-bindings/main.go
- tools/generate-helpers/pg-table-bindings/store_test.go.tpl
> ROX-13079: fix for postgres deletion tests

- .github/dependabot.yaml
- .github/labeler.yml
> CI: remove obsolete labels from dependabot and labeler

- central/node/datastore/store/postgres/store.go
> Use gogo Un/Marshal for node store

- central/cve/cluster/datastore/store/postgres/full_store.go
- central/version/postgres/store.go
> Use gogo Un/Marshal for version and cve store

- scripts/ci/lib.sh
Cherry pick of https://github.com/stackrox/stackrox/pull/2484. See that PR for more details
> Fix: Change cd into a pair of pushd and popd (#2484)

- scripts/release-tools/setup-central-access.sh
Follow up of #3370.
No testable changes 
> ROX-10890: add script for access central in long-running automation

- .github/workflows/add-new-pr-to-oss-triaging.yml
- .github/workflows/build.yaml
- .github/workflows/lint.yml
Add `actionlint` linter for GitHub workflows.
PR checks.
> Add `actionlint` linter

- operator/tests/central/basic/70-injected-cabundle.yaml
- operator/tests/securedcluster/basic-sc/40-injected-cabundle.yaml
It seems these files were added in https://github.com/stackrox/stackrox/pull/174 by mistake.
They are not actually useful, because there is no assertion to check their effect.
Relying on CI.
> ROX-8392: Remove unused files.

- .github/workflows/add-new-pr-to-oss-triaging.yml
- .github/workflows/build.yaml
- .github/workflows/cut-rc.yml
- .github/workflows/finish-release.yml
- .github/workflows/lint.yml
- .github/workflows/start-release.yml
* stackrox/test-gh-actions#63
* stackrox/test-gh-actions#62
* stackrox/test-gh-actions#61
* stackrox/test-gh-actions#60
* stackrox/test-gh-actions#59
* stackrox/test-gh-actions#58
Tested in stackrox/test-gh-actions.
> Sync GitHub workflows with `test-gh-actions`

- tools/local-sensor/scripts/README.md
- tools/local-sensor/scripts/local-sensor.sh
This PR adds a script ease the performance tests reproducibility using `local-sensor`. 
The above list does not apply to these changes.
```
./tool/local-sensor/scripts/local-sensor.sh -b -g --with-workload workload.yaml -t
```
> ROX-11323 Add local-sensor.sh script and README.md

- release/scripts/vuln_check.sh
> Fix error message in vuln_check.sh script

- .openshift-ci/ci_tests.py
Some times UI e2e tests are going over the limit and more tests are being added all the time!
> CI: Bump UI e2e test timeout

- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/cidr/CidrBlockSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/external/ExternalEntitiesSideBar.tsx
- ui/apps/platform/src/routePaths.js
Quick scaffolding of selecting graph nodes and triggering sidebar with URL change
Only node clicks trigger for now (will add deep-link refresh functionality later)
Deployment
Namespace
CIDR Block
External Entities
> ROX-13134: Make sidebar conditional on URL params

- tools/local-sensor/scripts/README.md
Adds a link to sensor's recorded metrics in `local-sensor.sh`'s `README.md`
N/A
> ROX-11323 Add link to sensor's recorded metrics

- tests/options_test.go
> ROX-13263: Refactor tests to reusue code

- central/resourcecollection/service/service_impl.go
- central/resourcecollection/service/service_impl_test.go
- generated/api/v1/resource_collection_service.pb.go
- generated/api/v1/resource_collection_service.pb.gw.go
- generated/api/v1/resource_collection_service.swagger.json
- proto/api/v1/resource_collection_service.proto
Added REST endpoint for creating a new collection.
Unit tests added.
> [ROX-12622] : Add create collection service

- central/certgen/central_scanner.go
- central/certgen/service.go
- pkg/mtls/crypto.go
Create an endpoint to generate central db certificates.
We are going to use these certificates to generate roxctl yaml bundle for central db provisioning for upgrade
CI and Manual test.
> ROX-13204: Create endpoint to generate central db certificates

- scripts/ci/jobs/gke_postgres_nongroovy_e2e_tests.py
Add configuration to run nongroovy tests on postgres
Refs: https://github.com/stackrox/stackrox/pull/3369
> ROX-13368: Run nongroovy tests on postgres

- central/resourcecollection/service/service_impl.go
- generated/api/v1/resource_collection_service.pb.go
- generated/api/v1/resource_collection_service.pb.gw.go
- generated/api/v1/resource_collection_service.swagger.json
- proto/api/v1/resource_collection_service.proto
> ROX-12623: ListCollections rest endpoint

- central/resourcecollection/datastore/datastore.go
- central/resourcecollection/datastore/datastore_impl.go
- central/resourcecollection/datastore/datastore_impl_test.go
- central/resourcecollection/datastore/mocks/datastore.go
Implement Collection Update workflow and add unit tests to cover the expected functionality.
Added unit tests.
> ROX-12614: Collection Update Workflow

- central/notifiers/splunk/splunk.go
Currently, each request sent to a Splunk endpoint results in its own transport being created, with no timeout settings. That means the connection, once used, will sit around idle until the server decides to close it; if a new request goes out before that happens, the idle connection is not reused. I am not sure if we have ever seen any issues that might have been due to this, but it seems bad enough to fix it proactively anyway.
- CI
> Avoid creating a new HTTP client and transport for each Splunk request

- operator/pkg/central/values/translation/translation.go
> ROX-12934: Add a comment from review thread.

- go.mod
- go.sum
Update dependency: NP-Guard to v1.4.1 to address a known bug.
- CI only
> Update NP-Guard to v1.4.1

- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.css
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
This PR adds the flows table with a basic expandable table. This is an iterative addition. You can find all the subtasks here: https://issues.redhat.com/browse/ROX-12904
> ROX-13169: Adding flows table

- CHANGELOG.md
- central/imageintegration/store/defaults.go
- pkg/env/sensor.go
- pkg/scanners/clairify/clairify.go
Add `.svc` endpoint to be respected by `NO_PROXY` env configuration.
- CI
- Deploy stack rox with global proxy
> ROX-13034: fix gRPC scanner

- central/graphql/resolvers/cluster_vulnerabilities.go
- central/graphql/resolvers/clusters.go
- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/image_components.go
- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/images.go
- central/graphql/resolvers/namespaces.go
- central/graphql/resolvers/node_components.go
- central/graphql/resolvers/node_vulnerabilities.go
- central/graphql/resolvers/nodes.go
> ROX-13231: use passed context when non-postgres

- central/main.go
- central/resourcecollection/datastore/datastore.go
- central/resourcecollection/datastore/datastore_impl.go
- central/resourcecollection/datastore/datastore_impl_test.go
- central/resourcecollection/datastore/singleton.go
- central/resourcecollection/service/singleton.go
> ROX-13259: graphInit called during init time

- .openshift-ci/base_qa_e2e_test.py
- .openshift-ci/ci_tests.py
- .openshift-ci/compatibility_test.py
- qa-tests-backend/src/test/groovy/AutocompleteTest.groovy
- scripts/ci/jobs/gke_version_compatibility_tests.py
> ROX-12319: implement smoke test step with groovy test filter

- central/graphql/resolvers/clusters.go
- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/image_components.go
- central/graphql/resolvers/images.go
- central/graphql/resolvers/namespaces.go
- central/graphql/resolvers/node_components.go
- central/graphql/resolvers/nodes.go
> ROX-13452: don't always clobber scoped ctx when non-postgres

- central/resourcecollection/datastore/datastore.go
- central/resourcecollection/datastore/datastore_impl.go
- central/resourcecollection/datastore/datastore_impl_test.go
- central/resourcecollection/datastore/mocks/datastore.go
> ROX-13261: DryRunUpdate on collection datastore

- central/alert/datastore/datastore_sac_test.go
- central/alerttest/alert.go
- central/cluster/datastore/datastore_sac_test.go
- central/deployment/datastore/datastore_impl_postgres_test.go
- central/deployment/datastoretest/datastore_sac_test.go
- central/networkbaseline/datastore/datastore_impl_test.go
- central/node/datastore/dackbox/datastore/datastore_impl_postgres_test.go
- central/node/datastore/dackbox/datastore/datastore_sac_test.go
- central/node/globaldatastore/datastore_sac_test.go
- central/notifiers/common_test.go
- central/notifiers/format_test.go
- central/postgres/pruning_test.go
- central/processbaseline/datastore/datastore_impl_test.go
- central/processindicator/datastore/datastore_impl_test.go
- central/search/service/service_impl_test.go
- central/serviceaccount/datastore/datastore_impl_test.go
- pkg/fixtures/alert.go
- pkg/fixtures/deployment.go
- pkg/fixtures/fixtureconsts/fixture_consts.go
- pkg/fixtures/network_baseline.go
- pkg/fixtures/node.go
- pkg/fixtures/service_account.go
- pkg/sac/testconsts/sac_consts.go
- pkg/search/query_builder.go
This PR focuses on the test constants and test changes needed to move the string constants in testing to be valid UUIDs.  This one builds upon the work done in https://github.com/stackrox/stackrox/pull/3681.
The work for this one is focused on updating tests to handle UUIDs.  So the changes are the tests.
> Dashrews/ROX-13082 UUID test updates PR 3 of 4

- central/resourcecollection/datastore/datastore.go
- central/resourcecollection/datastore/datastore_impl.go
- central/resourcecollection/datastore/datastore_impl_test.go
- central/resourcecollection/service/service_impl.go
- central/resourcecollection/service/service_impl_test.go
- generated/api/v1/resource_collection_service.pb.go
- generated/api/v1/resource_collection_service.pb.gw.go
- generated/api/v1/resource_collection_service.swagger.json
- proto/api/v1/resource_collection_service.proto
> [ROX-12625 + ROX-13032] : Add GetCollectionCount and UpdateCollection endpoints and  services

- central/resourcecollection/datastore/datastore.go
- central/resourcecollection/datastore/datastore_impl.go
- central/resourcecollection/datastore/datastore_impl_test.go
- central/resourcecollection/datastore/mocks/datastore.go
> ROX-12617: Collection to search query converter

- migrator/main.go
Add logs to show the current image and rollback information, which are helpful in debugging.
screenshots.
In addition to reviewing …
> Add more info in migration log

- migrator/migrations/m_109_to_m_110_networkpolicy_guidance_2/migration.go
The package for the migration in #3597 was incorrect. Maybe that's related to the issue during release testing. 
> Use correct package for migration

- CHANGELOG.md
After much discussion, the core team has agreed that this is best to help us iterate on the products and the documentation more rapidly.
_Parturient montes, nascetur ridiculus mus_
-Horace, _Ars Poetica_
Not applicable
> Update changelog to announce removal of in-product docs

- central/notifiers/jira/jira.go
> Add more context to jira notifier logs

- Makefile
- migrator/migrations/n_05_to_n_06_postgres_active_components/migration_test.go
- migrator/migrations/n_30_to_n_31_postgres_network_flows/migration_test.go
- migrator/migrations/n_35_to_n_36_postgres_nodes/migration_test.go
The goal of this change is to extend the postgres coverage to the initial data migration code.
Postgres test logs should be checked for the presence of n_xx_to_n_yy_zzz tests.
> Test data migration code in postgres tests

- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx
This PR adds a search filter to filter by entity name. It isn't hooked up to actually filter real data yet, but will soon. This is an iterative addition. All related subtasks can be found here: https://issues.redhat.com/browse/ROX-12904
> ROX-13167: Adding search filter by entity

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkGraphIcons.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceDeployments.tsx
- ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/utils/networkGraphUtils.ts
This PR uses real data for the namespace deployments
> ROX-13495: using real data for namespace deployments

- CHANGELOG.md
- image/templates/helm/stackrox-secured-cluster/templates/collector.yaml
Cherry-pick https://github.com/stackrox/stackrox/pull/3850
> Revert fine-grained host paths for compliance mounts

- sensor/kubernetes/eventpipeline/component/component.go
- sensor/kubernetes/eventpipeline/component/mocks/component.go
- sensor/kubernetes/eventpipeline/pipeline.go
- sensor/kubernetes/eventpipeline/pipeline_impl.go
- sensor/kubernetes/eventpipeline/resolver/resolver.go
- sensor/kubernetes/eventpipeline/resolver/resolver_impl.go
- sensor/kubernetes/listener/listener.go
- sensor/kubernetes/listener/listener_impl.go
- sensor/kubernetes/listener/resource_event_handler.go
- sensor/kubernetes/listener/resource_event_handler_impl.go
- sensor/kubernetes/listener/resource_event_handler_impl_test.go
Base implementation of the `Resolver` component.
* CI and Manual testing
> ROX-13355 Resolver component

- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
Followup to https://github.com/stackrox/stackrox/pull/3798
Relying on CI.
> Add a proper TODO.

- ui/apps/platform/package.json
- ui/apps/platform/src/utils/chartUtils.ts
- ui/apps/platform/src/utils/type.utils.ts
- ui/yarn.lock
Release notes: https://www.patternfly.org/v4/developer-resources/release-notes#2022.15-release-notes-2022-11-17
Jest tests
Cypress tests
Manual smoke tests using different pages in the application.
> Update to PatternFly 2022.15

- release/scripts/scan-images-with-roxctl.sh
Wee need to scan `central-db` image.
> Scan central-db image with roxctl

- central/globaldb/v2backuprestore/manager/restore_process.go
- central/main.go
- migrator/clone/clone_test.go
- migrator/clone/db_clone_manager_impl.go
- migrator/clone/mock_central.go
- migrator/clone/postgres/db_clone_manager.go
- migrator/clone/postgres/db_clone_manager_impl.go
- migrator/clone/postgres/db_clone_manager_impl_test.go
- migrator/clone/rocksdb/db_clone_manager.go
- migrator/clone/rocksdb/db_clone_manager_impl.go
- pkg/postgres/pgadmin/admin_utils.go
- tests/upgrade/postgres_run.sh
Updates so that a backup taken using Rocks DB can be restored but to a Postgres database.
Added UT test, updated the clone tests and added this case to the upgrade tests.
> Dashrews/ROX-13205 allow a Rocks DB backup to be restored to Postgres

- migrator/migrations/cvehelper/convert_utils.go
- migrator/migrations/cvehelper/id.go
These codes are not in use but starts to diverge from central. So, I am doing a clean up.
screenshots.
In addition to reviewing your …
> Remove ununsed codes in cvehelper

- README.md
Make the command easier to be reused for Helm upgrades as well by using `--install` option.
- Execute the command
> Use `helm upgrade --install` for easier re-use

- central/cluster/datastore/datastore.go
- central/clustercveedge/datastore/store/postgres/full_store.go
- central/cve/cluster/datastore/store/postgres/full_store.go
- central/deployment/datastore/datastore.go
- central/deployment/store/postgres/full_store.go
- central/graphql/resolvers/cluster_vulnerabilities_postgres_test.go
- central/graphql/resolvers/image_components_postgres_test.go
- central/graphql/resolvers/image_scan_benchmark_test.go
- central/graphql/resolvers/image_vulnerabilities_test.go
- central/graphql/resolvers/node_components_postgres_test.go
- central/graphql/resolvers/node_vulnerabilities_postgres_test.go
- central/graphql/resolvers/test_setup_utils.go
- central/graphql/resolvers/test_utils.go
- central/graphql/resolvers/testutils.go
- central/node/datastore/dackbox/globaldatastore/datastore.go
- central/node/datastore/store/postgres/store.go
- central/node/globaldatastore/datastore_sac_test.go
- central/node/globaldatastore/singleton.go
- central/nodecomponentcveedge/datastore/datastore.go
- central/nodecomponentcveedge/datastore/datastore_sac_test.go
- central/nodecomponentcveedge/datastore/singleton.go
- central/pruning/pruning_test.go
Make it easier to setup graphQL tests and unify the setup code. Refer to `image_scan_test.go` and `image_scan_benchmark_test.go` which I had added that already uses the setup code.
CI
> [ROX-13712] Add utility code for graphQL test setup

- ui/apps/platform/cypress/integration/auth.test.js
Prerequisite to investigate failures for logout test because of request timeout.
Remove confusion:
* Mock empty responses (to add insult to injury, for an obsolete subset of page-specific requests) cause exceptions on the page which are unrelated to the test.
* Mock empty response for POST /api/logimbue to suppress the exceptions is the straw that breaks the tester’s back.
> Visit System Configuration instead of Dashboard in auth integration tests

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkGraphIcons.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/ClusterSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NamespaceSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NetworkBreadcrumbs.tsx
- ui/apps/platform/src/Containers/NetworkGraph/utils/getScopeHierarchy.ts
- ui/apps/platform/src/hooks/useFetchClusterNamespaces.ts
- ui/apps/platform/src/hooks/useFetchClusters.ts
- ui/apps/platform/src/services/NetworkService.js
This is a good stopping place to check the URL flow.
Because the breadcrumb style is not in PatternFly yet, I have left the basic select input in, so that we can test the flow
Manual testing
> ROX-13013: Add query string search parsing to PF Network Graph

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/cidr/CidrBlockSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkGraphIcons.tsx
This PR is an iterative step to creating the CIDR Block side panel. I decided to include three of the subtasks in this PR to minimize PRs. You can find all the subtasks for the CIDR Block side panel work here: https://issues.redhat.com/browse/ROX-13672
> ROX-13673 + ROX-13674 + ROX-13675: Create cidr block side panel layout

- central/resourcecollection/service/service_impl.go
- tests/common_test.go
- tests/resourcecollection_test.go
Add E2E tests for collections, mainly testing the logical matching of deployments.
Fix the service endpoint requirements for creation and update of collections (*at least* one selector rule or embedded obj).
Haha
> ROX-12626: Collections E2E Tests

- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
Changes made during the CI flake maple session.
> Maple: comments and changes from the CI flake session

- tests/e2e/run-e2e-tests-README.md
- tests/e2e/run-e2e-tests.sh
Per title. Docs only change. 
n/a
n/a
> ROX-9115: Docs for e2e test runner

- tests/resourcecollection_test.go
Captured in title.
New tests added
> ROX-13686: regex matching and filter query in collections e2e

- .github/workflows/build.yaml
cci-export will not work properly in GHA. This PR replaces is with proper way to propagate env variables between steps.
CI
https://github.com/stackrox/stackrox/pull/2916#discussion_r1040868165
> Fix cci-export usage in GHA

- central/cve/fetcher/orchestrator.go
- central/cve/matcher/matcher.go
Some style and performance improvements for Istio scanning
> Minor style and performace improvements

- qa-tests-backend/src/test/groovy/GroupsTest.groovy
The test was not deleting the groups it created.
> CI: Fix GroupsTest

- .github/actions/cache-go-dependencies/action.yaml
- .github/actions/cache-gradle-dependencies/action.yaml
- .github/actions/cache-ui-dependencies/action.yaml
- .github/workflows/style.yaml
- .golangci.yml
Add `make style` to github actions workflow
CI
> ROX-13805: Add check-style to GHA

- tests/e2e/run-e2e-tests.sh
Per title. Defaults to postgres. Emulates `CI_JOB_NAME` to work with `./qa-tests-backend`.
Manual testing.
> ROX-9115: E2e test runner: Choose which DB to use

- ui/apps/platform/.eslintrc.js
As discussed in team meeting.
Lint warnings might crowd out errors in editor **Problems** pane.
```text
ui/apps/platform/cypress/integration/clusters/clusters.test.js
529:37  warning  Unexpected unnamed function  func-names
ui/apps/platform/cypress/integration/vulnmanagement/dashboard.test.js
89:80  warning  Unexpected unnamed function  func-names
97:79  warning  Unexpected unnamed function  func-names
105:93  warning  Unexpected unnamed function  func-names
165:55  warning  Unexpected unnamed function  func-names
181:56  warning  Unexpected unnamed function  func-names
```
Although the idiom to skip `describe` blocks has a function name:
```js
before(function beforeHook() {
if (!hasFeatureFlag('ROX_POSTGRES_DATASTORE')) {
this.skip();
}
});
```
It seems fluent JavaScript to replace arrow …
> Turn off func-names lint rule for ui integration tests

- qa-tests-backend/Makefile
- qa-tests-backend/src/test/groovy/VulnMgmtSACTest.groovy
- qa-tests-backend/src/test/groovy/groups/groups.groovy
Run vulnmgmtsactest first so it does not need to scan all used images in order to work correctly. This will ensure we have clean context for this test.
CI
> Run vulnmgmtsactest first

- operator/bundle_helpers/patch-csv.py
This just adds the ability to set `spec.skips` in the operator CSV ([docs here](https://docs.openshift.com/container-platform/4.11/operators/understanding/olm/olm-workflow.html#olm-upgrades-skipping_olm-workflow)). The actual setting should be configured per-release **downstream**.
Merging this is **not** urgent but I decided to implement it anyway and try e.g. when releasing 3.73.2 (still put 3.73.0 in skips). We should try it out some day to see what effect it has and whether it's usable way to discourage bad operator versions.
None of these matters:
Tested manually the following way:
1. Modify `operator/Makefile` target this way
```diff
.PHONY: bundle-post-process
bundle-post-process: operator-sdk ## Post-process CSV file to include correct operator versions, etc. …
```
> ROX-13946: Add ability to set `spec.skips` in the operator CSV

- qa-tests-backend/src/test/groovy/VulnMgmtSACTest.groovy
Looks like there is no property `tewakesortedVulnsdArray`.
This PR fixes this and also add types and use Set instead of ordered list.
> Fix vuln test

- scripts/ci/lib.sh
Reverts stackrox/stackrox#4184 and updates to 0.0.2 to have threshold
> Revert "Do not create issues for CI failures"

- .github/workflows/update_collector_and_scanner.yaml
Update `SCANNER_VERSION` reviewers
CI
> update SCANNER_VERSION reviewers

- ui/apps/platform/src/Containers/Collections/CollectionResults.tsx
Small refactor to use hook to handle infinite loading queries from https://github.com/stackrox/stackrox/pull/4197.
Repeat manual testing steps from:
https://github.com/stackrox/stackrox/pull/4001
https://github.com/stackrox/stackrox/pull/4110
https://github.com/stackrox/stackrox/pull/4115
> Update collection results to use `usePaginatedQuery` hook

- pkg/telemetry/phonehome/hash.go
- pkg/telemetry/phonehome/hash_test.go
Make use of a handier function from sha256 package.
Default `admin` user ID hash:
```sh
$ print -n "2a3e1829-8f84-40c1-a761-006f07a59666:4df1b98c-24ed-4073-a9ad-356aec6bb62d:admin" | sha256sum | xxd -r -p | base64 
+5GOIqkMuJMFDqJcMKvAGvbSRtCUjqdCB+UeU1hOqQA=
```
Generated event:
```json
{
"context": {
"Client ID": "2a3e1829-8f84-40c1-a761-006f07a59666",
"Client Name": "Central",
"library": {
}
},
"groupId": "2a3e1829-8f84-40c1-a761-006f07a59666",
"messageId": "10027051-ef14-4072-8120-13ad4d0869fe",
"originalTimestamp": "2022-12-13T17:55:39.711646136Z",
"receivedAt": "2022-12-13T17:56:40.399Z",
"sentAt": "2022-12-13T17:56:39.712Z",
"timestamp": "2022-12-13T17:55:40.398Z",
"traits": null,
"type": "group",
"userId": …
```
> Minor refactoring to user hashing function

- .github/workflows/build.yaml
The build switch to GHA needs to include the nightlies branch.
n/a we'll see how it fares in the next nightly CI.
> CI: Build images for nightlies

- pkg/booleanpolicy/evaluator/evaluator_test.go
The current test failed after three years when it was written, which we now hit :-).
- see CI.
> ROX-14129,ROX-14130,ROX-14131,ROX-14132: Fix failing boolean policy test.

- pkg/booleanpolicy/evaluator/evaluator_test.go
Addressing a nitpick from PR #4253 that wasn't addressed in the original PR.
> Boolean policy test follow-up

- sensor/debugger/k8s/fake.go
Simply log the event that we are processing if `waitOnMode` fails.
N/A
> Log expected event in replay tests

- central/cluster/datastore/datastore_impl.go
> [ROX-14191] Pull IDs instead of full objects during cluster datastore init

- proto/storage/proto.lock
- tools/linters/go.mod
- tools/linters/go.sum
There is no reason to use replace to custom fork as it points to a commit that is in official repo.
This PR will remove replace and update to latest version.
> Use lastest protolock

- pkg/telemetry/phonehome/client_config.go
- pkg/telemetry/phonehome/interceptor.go
> Use RWMutex for the list of API interceptors

- sensor/kubernetes/listener/resources/deployment_store.go
Done in pair to fix an issue in the sensor pipeline. 
- None, this is behind a feature flag for now.
> Quickfix: Add lock in build deployment dependencies

- qa-tests-backend/build.gradle
> Fix gradlew test not found issue

- ui/apps/platform/src/Containers/Collections/RuleSelector/ByLabelSelector.tsx
> Collection selector rework cleanup

- sensor/debugger/k8s/fake.go
- sensor/tests/replay/replay_test.go
The replay tests do not need to check the event that was sent to central to create the next resource; they just need to signal that the resource was processed. This can be achieved by just signaling whenever the dispatcher is done with the processing.
Some further simplification of the code might be good, but in order to not block dependent PRs I'll tackle those in a follow-up PR. …
> Replay tests do not wait on specific events

- ui/apps/platform/cypress/constants/DashboardPage.js
- ui/apps/platform/cypress/helpers/main.js
Yesterday I stumbled onto this overlooked task.
> Remove DashboardPage file from constants folder for integration tests

- central/graphql/resolvers/resolver.go
- central/graphql/resolvers/search.go
- central/graphql/resolvers/search_test.go
- central/node/globaldatastore/datastore.go
- central/search/service/service.go
- central/search/service/service_impl.go
- central/search/service/service_impl_test.go
This PR replaces global node datastore in search. 
Part 1: #4309 
> Consolidate node datastores: part 2

- central/pruning/pruning.go
- central/pruning/pruning_test.go
- central/pruning/singleton.go
Replace global node store from pruner
Part 1: #4309
Part 2: #4315
Part 3: #4334
CI
> Consolidate node datastores: part 4

- operator/Dockerfile
Refs: 
- https://github.com/stackrox/stackrox/pull/164
- https://github.com/stackrox/stackrox/pull/4277#discussion_r1061368867
> Use GOPROXY fallback in operator builds

- .github/workflows/unit-tests.yaml
> ROX-13912: Migrate UI unit tests

- ui/apps/platform/src/Containers/NetworkGraph/components/StyleNode.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/topology.type.ts
> ROX-12908: adding external entities/cidr block svg to network graph

- ui/apps/platform/src/Components/DescriptionListItem.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/LegendContent.tsx
> ROX-12902: adding legend to network graph

- go.mod
- go.sum
- pkg/telemetry/phonehome/segment/segment.go
The new version fixes some important problems.
CI, local tests.
> Bump segmentio/analytics-go module version.

- ui/apps/platform/src/Containers/NetworkGraph/api/useFetchNetworkBaselines.ts
- ui/apps/platform/src/Containers/NetworkGraph/api/useModifyBaselineStatuses.ts
- ui/apps/platform/src/Containers/NetworkGraph/common/AdvancedFlowsFilter/AdvancedFlowsFilter.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/AdvancedFlowsFilter/advancedFlowsFilterUtils.test.ts
- ui/apps/platform/src/Containers/NetworkGraph/common/AdvancedFlowsFilter/advancedFlowsFilterUtils.ts
- ui/apps/platform/src/Containers/NetworkGraph/common/AdvancedFlowsFilter/types.ts
- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsBulkActions.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTable.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaselines.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/flow.type.ts
- ui/apps/platform/src/Containers/NetworkGraph/types/topology.type.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.ts
> ROX-14346: Allowing ability to add to baseline and mark as anomalous

- tests/active_vuln_test.go
Change active vuln test to use new image vuln interface.
Run active vuln test.
> ROX-14074: Enable active vuln test for postgres

- qa-tests-backend/src/main/groovy/util/Env.groovy
- qa-tests-backend/src/test/groovy/AuditScrubbingTest.groovy
- qa-tests-backend/src/test/groovy/CertExpiryTest.groovy
- qa-tests-backend/src/test/groovy/CertRotationTest.groovy
- qa-tests-backend/src/test/groovy/IntegrationsSplunkViolationsTest.groovy
- qa-tests-backend/src/test/groovy/TLSChallengeTest.groovy
- qa-tests-backend/src/test/groovy/UpgradesTest.groovy
This PR intends to submit a POC to handle power & z architecture specific changes in the groovy test code using an environment variable.
> POC to handle P/Z changes using REMOTE_CLUSTER_ARCH env variable

- central/reportconfigurations/datastore/datastore.go
- central/reportconfigurations/datastore/datastore_impl_postgres_test.go
- central/reportconfigurations/datastore/datastore_impl_test.go
- central/reportconfigurations/datastore/singleton.go
Use the correct indexer when running with postgres.
CI
> [ROX-14238] Use correct indexer when running with postgres

- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
- qa-tests-backend/src/test/groovy/NetworkSimulator.groovy
This PR intends to skip few qa sub-tests that are not applicable OR not required to be executed on power & z architectures.
> Skip few qa sub-tests not applicable for P/Z

- pkg/telemetry/phonehome/client_config.go
- pkg/telemetry/phonehome/segment/segment.go
- pkg/telemetry/phonehome/segment/segment_test.go
Minor refactorings:
1. Coming from this comment: https://github.com/stackrox/stackrox/pull/4278#pullrequestreview-1237574804
2. Add logging for failed asynchornous operations
CI, Unit tests.
> Minor refactoring in the telemetry framework

- .github/workflows/cut-rc.yml
- .github/workflows/finish-release.yml
- .github/workflows/scripts/patch-changelog.sh
- .github/workflows/start-release.yml
- .github/workflows/variables.yml
Includes the following changes:
d255a85 ROX-13535: Remove and don't update docs submodule (stackrox/test-gh-actions#83)
1e5cd4f Assert version format (stackrox/test-gh-actions#75)
551f024 ROX-14048: Add workflow to verify release is done (stackrox/test-gh-actions#82)
d8b178b Update the finish release Slack message (stackrox/test-gh-actions#79)
Tested in the stackrox/test-gh-actions repo.
> Copy GH workflows from test-gh-actions repository

- scripts/ci/get-slack-user-id.sh
For proper CI test-failure tagging in slack
> Add dcaravel to slack user ID list

- pkg/telemetry/phonehome/doc.go
- pkg/telemetry/phonehome/telemeter.go
`/pkg/telemetry/phonehome` package documentation.
Read through the vscode generated package hint.
> Telemetry framework documentation

- central/telemetry/centralclient/interceptors.go
Minor refactoring. This is mostly to show how to build chains of interceptors.
Unit tests and live tests.
> Telemetry refactoring: extract adding default properties

- CHANGELOG.md
- pkg/buildinfo/buildinfo.go
- pkg/buildinfo/internal/timestamp/timestamp.go
- pkg/version/version.go
BuildTimestampt and BuildDate will be removed in future release.
> ROX-14400: Deprecate BuildDate

- scripts/ci/get-slack-user-id.sh
So I can get properly tagged in test failures.
> Add Kyle Lape to slack user ID list

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/topology.type.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/modelUtils.tsx
adding a custom comparator for React.memo and a simple comparator value in the data model (`updateCount`) to use instead of deep comparing models
> Network Graph PF edge performance improvement

- Makefile
- scripts/ci/collect-service-logs.sh
- tests/e2e/bats/check_for_stackrox_OOMs.bats
- tests/e2e/bats/fixtures/test-pod-with-oomkilled_object.json
- tests/e2e/bats/fixtures/test-pod-without-oomkilled_object.json
- tests/e2e/lib.sh
These changes report whether or not pods were OOMKilled during e2e tests by saving addition json artifacts of all the pods that were on the cluster and checking the exit status of those pods
bats test that's included
> ROX-11931: Detect OOM kills in e2e tests

- central/resourcecollection/datastore/datastore_impl.go
- central/resourcecollection/service/service_impl.go
Made the deletion error more human readable on a failed deletion.
Added default sort option of Collection Name for the collections List endpoint.
Added default sort option of Deployment Name for the deployment matching feature of various endpoints.
Manually verified the error message via FE
> ROX-14061, ROX-14277: collection deletion error message, default sorting options

- central/graphql/resolvers/cluster_vulnerabilities_postgres_test.go
- central/graphql/resolvers/image_components_postgres_test.go
- central/graphql/resolvers/image_scan_benchmark_test.go
- central/graphql/resolvers/image_scan_test.go
- central/graphql/resolvers/image_vulnerabilities_test.go
- central/graphql/resolvers/node_components_postgres_test.go
- central/graphql/resolvers/node_vulnerabilities_postgres_test.go
- central/graphql/resolvers/test_setup_utils.go
- central/reports/common/report_formatter.go
- central/reports/scheduler/schedule.go
- central/reports/scheduler/vuln_report_collections_test.go
- pkg/graphql/testutils/test_setup_utils.go
Refactored to ease testing, added test data generation framework and added unit tests
This PR adds tests
> [ROX-13891] : Unit test vuln reports with collections

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/CIDRForm.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/CIDRFormModal.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/CIDRFormRow.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/DefaultCIDRToggle.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/cidrFormUtils.tsx
all the functionality should still be the same and work as expected
* adding a new CIDR block
* deleting a CIDR block
* editing an existing CIDR block
* the form should clear on closing/reopening the modal
* form should show name/address validation on inputs
* <img width="570" alt="image" src="https://user-images.githubusercontent.com/10412893/214773343-279605c6-bfb0-4c6b-a870-115bae3a8998.png">
* error messages should appear as such on duplicate name/id/address
* <img width="571" alt="image" src="https://user-images.githubusercontent.com/10412893/214773406-e460abb6-dcdc-4a40-8106-5cb13cfa12ae.png">
* success message should appear and auto close the modal 
* <img width="549" alt="image" src="https://user-images.githubusercontent.com/10412893/214773503-66becf50-dacd-4acd-ab58-119b0164a983.p …
> ROX-12914: Network Graph PF CIDR block form

- scripts/ci/collect-infrastructure-logs.sh
> ROX-14290: attempt to gather audit logs on OpenShift

- compliance/collection/nodeinventorizer/nodeinventory.go
We apparently missed the Content Sets when converting between Scanner and Stackrox protos what resulted in always empty content sets and 0 vulnerabilities when scanning.
This PR should fix that and provide a bit more visibility on the matter in the logs.
```
nodeinventory.go:39: Info: Node inventory has been built with 501 packages and 4 content sets
```
> Fix passing RHCOS content sets

- CHANGELOG.md
Add notes about 4.0 release, Postgres, and the deprecations that will occur regarding RocksDB in 4.1
N/A
> Add major upcoming changes to the 74 release notes

- ui/apps/platform/src/Containers/AppPageTitle.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/LeftNavItem.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/routePaths.js
Putting this out there as a simple solution
Manual
How it looks when not the active section
How it looks when it is the active section
> ROX-14468: Make new Network Graph a Tech Preview in nav

- central/networkgraph/flow/datastore/internal/store/postgres/store.go
Was running into statement_timeouts that were crashing Central. Should evaluate how we can do this better, but this will avoid crashes
Removes the crash
> ROX-14606: Fix issue with statement timeout crashes on pruning

- ui/apps/platform/src/Components/DeploymentPortConfig.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphContainer.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/api/useFetchNetworkBaselines.ts
- ui/apps/platform/src/Containers/NetworkGraph/api/useFetchNetworkFlows.ts
- ui/apps/platform/src/Containers/NetworkGraph/common/AdvancedFlowsFilter/AdvancedFlowsFilter.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/DefaultCIDRToggle.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/LegendContent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx
- ui/apps/platform/src/Containers/NetworkGraph/hooks/useNetworkPolicySimulator.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/modelUtils.tsx
- ui/apps/platform/src/hooks/useFetchNetworkPolicies.ts
so it turns out it was the `ColaGroup` layout all along 😭  
i changed it to `ColaNoForce` and it seems to be working fine. 
i also added some clean up around `useEffect` bc the console was upset we were trying to set the state of unmounted components
it should look/feel/behave the same (even better!) than before 🥲
> ROX-13431: Network Graph PF edge performance fix

- ui/apps/platform/src/hooks/useFetchReport.ts
A feature flag was removed https://github.com/stackrox/stackrox/pull/4592 at about the same time I added a new instance of the old flag in one of my PRs https://github.com/stackrox/stackrox/pull/4555
CI
> Fix feature flag semantic merge conflict

- pkg/features/list.go
> enable Clair v4 image integration

- central/resourcecollection/service/service_impl.go
See Title.
Added a new unit test on the service implementation
> Trim Whitespace on Collections Endpoints Names

- tests/active_vuln_test.go
- tests/container_instances_test.go
- tests/excluded_scopes_test.go
- tests/feature_flag_test.go
- tests/networkpolicy_test.go
- tests/pods_test.go
"No testable changes". Feel free to …
> ROX-14641: Reenable disabled non-groovy Rocksdb test

- pkg/booleanpolicy/evaluator/evaluator_test.go
Cherrypicks: 
- #4255 4194560
- #4253 30b24dc
> fix-booleanpolicy-test

- central/reportconfigurations/datastore/datastore.go
- central/reportconfigurations/datastore/datastore_impl.go
- central/reportconfigurations/datastore/mocks/datastore.go
- central/resourcecollection/service/service.go
- central/resourcecollection/service/service_impl.go
- central/resourcecollection/service/service_impl_test.go
- central/resourcecollection/service/singleton.go
Same as title
Unit tests added
> [ROX-14220] : DeleteCollection service should error out if collection is used by a reportConfiguration

- qa-tests-backend/src/main/groovy/services/CollectionsService.groovy
- qa-tests-backend/src/main/groovy/services/VulnReportService.groovy
- qa-tests-backend/src/main/groovy/util/MailServer.groovy
- qa-tests-backend/src/test/groovy/VulnReportingTest.groovy
Take 2 on the PR.
screenshots.
> ROX-12632: Add vulnerability report with collections E2E test 

- qa-tests-backend/src/main/groovy/services/CollectionsService.groovy
- qa-tests-backend/src/main/groovy/services/VulnReportService.groovy
- qa-tests-backend/src/test/groovy/VulnReportingTest.groovy
If it fails to clean up for any reason, there could be a name conflict
screenshots.
> Collections E2E: Don't delete collection before report & use unique names

- central/resourcecollection/datastore/datastore_impl.go
- ui/apps/platform/src/Containers/Collections/CollectionForm.tsx
- ui/apps/platform/src/Containers/Collections/errorUtils.ts
See title.
Deployed and checked that message appears as expected.
> Collection Regex Error Message

- pkg/features/list.go
> ROX-14754: Turn on PatternFly Network Graph by default

- pkg/features/list.go
Follow up #2689
Click **Search** on top nav and then
* Click **CLI** button to see menu
* Click **Help** button to see menu
* Click **User** button to see menu
* See left nav (above) until you click collapse button (below)
* Verify that classic modal tests are skipped
> ROX-13710: Enable ROX_SEARCH_PAGE_UI to replace search modal with page

- ui/apps/platform/src/Containers/NetworkGraph/cidr/CidrBlockSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaselines.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx
- ui/apps/platform/src/Containers/NetworkGraph/external/ExternalGroupSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/externalEntities/ExternalEntitiesSideBar.tsx
This PR fixes the following bugs in order of commits. To check each individual change more effectively, you can go commit by commit to check the code changes. Here are the fixes:
Layout fixes to optimize spacing
7c35e-550d-485c-a89b-7bef62b447c0.png">
Hide anomalous traffic label when the num of traffic is 0
Use triangle icon for the anomalous internal traffic label in deployment details
> Network Graph Bug Fixes

- ui/apps/platform/cypress/helpers/networkGraph.js
- ui/apps/platform/cypress/integration/networkGraph/connections.test.js
- ui/apps/platform/cypress/integration/networkGraph/externalEntities.test.js
- ui/apps/platform/cypress/integration/networkGraph/network.test.js
- ui/apps/platform/cypress/integration/networkGraph/networkFlows.test.js
- ui/apps/platform/cypress/integration/networkGraph/networkGraph.test.js
- ui/apps/platform/cypress/integration/networkGraph/tooltip.test.js
> ROX-14771: Unbreak old Network Graph test

- ui/apps/platform/src/Containers/MainPage/AnnouncementBanner.tsx
Update copy on the announcement banner text
> ROX-14642: update announcement banner text

- central/alert/service/service_impl.go
- central/alert/service/service_test.go
- scale/mocksensor/main.go
Automated + manual on cluster. Scale tests TBD.
> ROX-13916: Using Search and highlighted fields in the v1/alerts/summary/counts API for better scaled performance and to avoid OOM

- central/policy/datastore/datastore_impl.go
> Log actual error

- go.mod
- go.sum
> Using most updated scanner

- central/graphql/resolvers/loaders/images_test.go
See title
Tested locally by running with postgres enabled and disabled to ensure the test passes
> ROX-14963: TestImageLoader to support postgres

- operator/pkg/central/reconciler/reconciler.go
Add pause reconcile constant for operator
- CI
> Add pause reconcile constant for operator

- central/graphql/resolvers/loaders/images_test.go
See title.
Tested locally and verified coverage on the function.
> ROX-14963: TestImageLoader FullImageWithID coverage

- qa-tests-backend/src/main/groovy/services/GraphQLService.groovy
- qa-tests-backend/src/test/groovy/VulnMgmtTest.groovy
Unable to repro this locally and it has only happened twice, so print out the actual error from the response for next time.
screenshots.
> ROX-13929: Add log to debug VM GraphQL test error

- central/imagecomponent/search/searcher_impl_test.go
> Skip TestImageComponentDataStore when on Postgres

- central/splunk/violations_query_test.go
- central/splunk/violations_test.go
Test should use postgres if postgres flag is enabled
this is a test
> ROX-14962: Fix test to work when postgres is enabled: central/splunk/violations_test

- CHANGELOG.md
- central/role/resources/list.go
- pkg/buildinfo/buildinfo.go
- pkg/buildinfo/internal/timestamp/timestamp.go
- pkg/version/version.go
- ui/apps/platform/src/constants/accessControl.ts
Manual cherry-pick of https://github.com/stackrox/stackrox/pull/4763.
The automated cherry-pick had merge conflicts in CHANGELOG.md, see https://github.com/stackrox/stackrox/actions/runs/4132199227
n/a
Markdown change, no testing required.
> Cherry-pick of PR-4763 for 3.74.0-rc.2

- central/cluster/datastore/telemetry.go
- central/telemetry/centralclient/instance_config.go
- pkg/telemetry/phonehome/doc.go
- pkg/telemetry/phonehome/segment/segment.go
- pkg/telemetry/phonehome/segment/segment_test.go
- pkg/telemetry/phonehome/telemeter/telemeter.go
- pkg/telemetry/phonehome/telemeter/telemeter_test.go
Documentation update.
Read through.
> Telemetry: phonehome `doc.go` update

- .github/workflows/unit-tests.yaml
Run integration unit tests in GHA.
CI
> Run integration unit tests

- pkg/concurrency/retry_ticker_test.go
Skip failing tests for investigation. 
CI
> Skip flaky ticker tests

- .github/workflows/style.yaml
- pkg/search/postgres/querytype_string.go
- scripts/ci/lib.sh
Run checks that on OSCI were run in grouped statics checks.
CI
> ROX-14924: Run misc style checks

- image/templates/CHANGING_CHARTS.md
> Clarify that second section is not for every SecuredCluster chart change.

- scripts/ci/jobs/openshift_penult_operator_e2e_tests.py
Handle the shortened name for merge CI.
n/a
n/a
> Setup link for "penult" operator e2e tests / 3.73

- scripts/ci/jobs/openshift_penult_operator_e2e_tests.py
Mirrors https://github.com/stackrox/stackrox/pull/4819 in `release-3.72`.
Not doing any of these. At all.
None.
> Setup link for "penult" operator e2e tests / 3.74

- scripts/ci/jobs/openshift_penult_operator_e2e_tests.py
Mirrors https://github.com/stackrox/stackrox/pull/4819 in `release-3.72`.
Won't do any of these. At all.
None.
> Setup link for "penult" operator e2e tests / 3.72

- pkg/features/list.go
- tests/e2e/lib.sh
- ui/apps/platform/src/types/featureFlag.ts
> Add feature flag for Vuln Mgmt Workload CVEs

- deploy/common/k8sbased.sh
- pkg/renderer/helm_values.go
- roxctl/central/generate/generate.go
We need to generate the central db and central db certs in roxctl which is used in the k8s based install
oldest openshift and ui tests
> Fix inability to deploy with helm due to missing certificates

- central/imageintegration/datastore/datastore_impl_test.go
> ROX-14964: Fix test to work when postgres is enabled: TestImageIntegrationDataStore

- image/templates/helm/stackrox-central/templates/01-central-02-db-psps.yaml
- roxctl/central/generate/generate.go
Central DB needs to map config maps
Compatibility test
> Fix Central DB PSP to fix compatibility tests

- central/user/datastore/internal/store/store.go
Seems that this comment became outdated years ago - size restriction was lifted here: https://github.com/stackrox/rox/pull/2798/files
> Update user store documentation.

- central/resourcecollection/service/service_impl.go
> Collection Fail to Delete In Use Collection by Report Config Error Msg

- ui/apps/platform/src/Containers/NetworkGraph/types/flow.type.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.test.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.ts
This PR adds a few tests for flow util functions for the Network Graph. I'll some more in later PRs
Run `npm test` in the `/apps/platform` directory to run tests
> feat: adding tests for network graph util functions

- tests/options_test.go
The empty case is the same as all categories
e2e should pass
> Fix e2e options map test

- ui/apps/platform/cypress/integration/clusters/clustersHealthStatus.test.js
- ui/apps/platform/src/Containers/Clusters/cluster.helpers.test.js
- ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx
The thing speaks for itself (but I added tests, too).
Cluster list with OpenShift
Cluster detail with OpenShift
Still there on GKE
> ROX-14399: Update wording when cluster metadata not available

- qa-tests-backend/src/main/groovy/services/ServiceAccountService.groovy
> Fix service account removal test by using scoped query

- sensor/admission-control/manager/k8s_object.go
- sensor/kubernetes/listener/resource_event_handler.go
- sensor/kubernetes/listener/resources/convert.go
For patch on 3.73
(cherry picked from commit e775e71935e30183b63ec27b5a014823bcbfe904)
screenshots.
> ROX-14973: Support CronJobs in a backwards compatible way (#4853)

- pkg/search/postgres/common.go
Ignore context cancelled errors which are from the client cancelling the request
UI tests
> Ignore context cancelled errors in logging

- .github/workflows/lint.yml
- .github/workflows/scripts/cherry-pick.sh
- .github/workflows/scripts/patch-changelog.sh
- .github/workflows/start-release.yml
- scripts/style/shellcheck_skip.txt
Mirroring changes from 
* https://github.com/stackrox/test-gh-actions/pull/87
* https://github.com/stackrox/test-gh-actions/pull/86
Both things have been tested there.
See linked PRs above. 
Additionally, success of the `lint` workflow is expected.
> ROX-14904, ROX-14661: fix OSCI config PR and improve cherry-picking in Release GHA workflows

- central/detection/alertmanager/alert_manager_impl.go
- central/detection/alertmanager/alert_manager_impl_test.go
cherrypick b9c0cf86ef40f7a73da554e4837fd11ff3d63a8a into 3.73
Unit
> Do not panic when unexpected process violations are received (#4930)

- qa-tests-backend/src/test/groovy/ProcessesListeningOnPortsTest.groovy
> Jv disable process listening on ports e2e tests

- ui/apps/platform/src/Components/Pagination/PaginationInput/PaginationInput.js
- ui/apps/platform/src/Components/PatternFly/FormMessage.tsx
- ui/apps/platform/src/Containers/Network/SidePanel/NetworkDeploymentOverlay/Flows/BaselineSettings/useFetchNetworkBaselines.ts
- ui/apps/platform/src/Containers/SystemHealth/PatternFly/Components/IntegrationsHealth.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ImpactedEntities/ImpactedEntities.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ImpactedEntities/ImpactedEntitiesModal.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/vulnerabilityRequests.graphql.ts
- ui/apps/platform/src/hooks/useURLParameter.test.tsx
This PR fixes a few of the lint warnings from our Lint Bash today
Lint Bash Doc: https://docs.google.com/document/d/1mz8a7Lp058HUIpMgw6FUETvaKVPyegE0bgY4YBDsAFs/edit#heading=h.u0xqdtd6qrsb
> fix: lint warning fixes

- qa-tests-backend/src/test/groovy/ProcessesListeningOnPortsTest.groovy
> Jv disable processes listening on ports e2e test 2

- ui/apps/platform/cypress/helpers/networkGraph.js
- ui/apps/platform/cypress/integration/collections/deploymentMatching.test.js
- ui/apps/platform/cypress/integration/compliance/complianceDashboard.test.js
- ui/apps/platform/cypress/integration/configmanagement/ConfigurationManagement.helpers.js
- ui/apps/platform/cypress/integration/configmanagement/deployments.test.js
- ui/apps/platform/cypress/integration/configmanagement/images.test.js
- ui/apps/platform/cypress/integration/configmanagement/namespaces.test.js
- ui/apps/platform/cypress/integration/configmanagement/nodes.test.js
- ui/apps/platform/cypress/integration/configmanagement/secrets.test.js
- ui/apps/platform/cypress/integration/networkGraph/networkGraph.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/entitypages.test.js
Baseline run to reproduce expected failures.
> Improve integration tests that initially failed on OpenShift

- central/main.go
- central/telemetry/centralclient/instance_config.go
Fix by changing the pass by value to pass by reference.
Manual testing where 'roxctl' events appeared on Segment.
> ROX-15283: Telemetry interceptors won't work

- Makefile
- qa-tests-backend/src/main/groovy/orchestratormanager/OpenShift.groovy
- qa-tests-backend/src/main/groovy/util/Env.groovy
- qa-tests-backend/src/test/groovy/AttemptedAlertsTest.groovy
- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
- qa-tests-backend/src/test/groovy/GlobalSearch.groovy
- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
- qa-tests-backend/src/test/groovy/ImageSignatureVerificationTest.groovy
- qa-tests-backend/src/test/groovy/PolicyConfigurationTest.groovy
- qa-tests-backend/src/test/groovy/VulnMgmtSACTest.groovy
- qa-tests-backend/src/test/groovy/VulnScanWithGraphQLTest.groovy
- scripts/ci/lib.sh
- scripts/ci/logcheck/restart-ok-patterns.json
- tests/e2e/lib.sh
- tests/e2e/run-e2e-tests.sh
Per title. Changes are commented inline.
> cleanup: job name and other CI vars

- ui/apps/platform/src/hooks/useFetchClusters.ts
- ui/apps/platform/src/hooks/useTableSelection.ts
> Fix a few linter issues

- central/role/datastore/datastore_test.go
This is follow-up for https://github.com/stackrox/stackrox/pull/4988 - adding new tests to prevent similar bug.
1. Unit tests added
> Add role datastore unit tests that check if updated value has changed

- central/image/datastore/store/postgres/store.go
- central/node/datastore/store/postgres/store.go
> Acquire DB connection transaction inside lock

- qa-tests-backend/src/test/groovy/SummaryTest.groovy
> ROX-15161: Add log to debug SummaryTest failure in compatibility tests

- ui/apps/platform/src/Containers/NetworkGraph/components/EdgeStateSelect.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/TimeWindowSelector.tsx
Does what the title suggests. See https://issues.redhat.com/browse/ROX-15252
https://user-images.githubusercontent.com/4805485/221672192-d6a11c05-93ac-493d-bac5-c26f1061f560.mov
> ROX-15252: Fix active/extraneous dropdown behavior

- .github/workflows/check-image-vulnerabilities.yml
- .github/workflows/lint.yml
- .github/workflows/scripts/check-image-vulnerabilities.py
Tested here https://github.com/stackrox/test-gh-actions/actions/runs/4252618039.
Output for 3.74.0-rc.4:
> ROX-15294: implement check-image-vulnerabilities workflow to use during upstream release

- .github/dependabot.yaml
Update GHA with @dependabot.
CI
> Update GHA with dependabot

- ui/apps/platform/package.json
- ui/yarn.lock
Update every other minor version seems like a good pace recently.
https://docs.cypress.io/guides/references/changelog#12-7-0
* Fixed an issue where cookies were being duplicated with the same hostname, but a prepended dot. Fixed an issue where cookies may not be expiring correctly.
* Fixed an issue where cookies weren't being synced when the application was stable.
* Fixed an issue where using `cy.intercept`'s `req.continue()` with a non-function parameter would not provide an appropriate error message.
> Update cypress 12.7.0 devDependencies in ui

- central/graphql/resolvers/image_cve_core.go
- central/graphql/resolvers/image_cve_core_test.go
- central/views/imagecve/image_cve.go
- central/views/imagecve/mocks/types.go
- central/views/imagecve/types.go
- central/views/imagecve/view_impl.go
- central/views/imagecve/view_test.go
GraphQL resolver for workload cve count. 
Refer to [API contract](https://docs.google.com/document/d/1c1I9m8cwhdRm3NUwo0D_TxYwAAuIsA-4UMt0VabZg6I/edit#heading=h.wjq0yqnqu4hl) for mocks.
Unit
> [VM2.0][ROX-15261] GraphQL resolver for count unique cves

- central/sensor/service/connection/connection_impl.go
- central/sensor/service/pipeline/all/pipeline.go
Events from Sensor should be safe, would have prevented a previous panic in a handler
Will purposefully cause panics in some handlers to check
> Make the processing of sensor events safe

- ui/apps/platform/src/Containers/NetworkGraph/components/StyleFakeGroup.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/StyleGroup.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/StyleNode.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/stylesComponentFactory.tsx
there should be no lint errors in `Containers/NetworkGraph` and `Containers/Policies`
> UI lint errors fix

- qa-tests-backend/src/main/groovy/objects/Notifiers.groovy
- qa-tests-backend/src/main/groovy/services/NotifierService.groovy
- scripts/ci/lib.sh
- scripts/ci/publish-helm-charts.sh
Updates the descriptions of slack channels used in test.
> CI: Update slack channels

- central/detection/lifecycle/manager_impl.go
- central/processindicator/datastore/datastore_impl.go
The double counting of this function segment makes it very hard to use the segments to show aggregate time taken
Pretty straightforward
> Fix baseline stats and avoid unnecessary copies on Postgres

- pkg/declarativeconfig/transform/auth_provider.go
- pkg/declarativeconfig/transform/auth_provider_test.go
Empty minimum role name = no default group.
> Declarative config: do not create default group if minimum role name is empty

- central/graphql/resolvers/image_cve_core.go
- central/graphql/resolvers/image_cve_core_test.go
- central/views/imagecve/mocks/types.go
- central/views/imagecve/types.go
- central/views/imagecve/view_impl.go
- central/views/imagecve/view_test.go
- central/views/read_options.go
- GraphQL to fetch image cve core for single cve (name). 
- Support to skip fields in select statements. This will enable avoiding pulling unnecessary data. 
screenshots.
> [VM2.0][ROX-13872] Add graphQL to get result by cve

- central/telemetry/centralclient/instance_config.go
Added two Track events.
```json
{
"anonymousId": "062c26b6-85d7-4ee8-b690-1e21e94657f3",
"context": {
"device": {
"id": "062c26b6-85d7-4ee8-b690-1e21e94657f3",
"type": "Central Server"
},
"library": {
}
},
"event": "Telemetry Disabled",
"messageId": "e6b60a12-68f2-48ac-939d-206021e18c1b",
"originalTimestamp": "2023-03-03T14:45:18.813492105Z",
"receivedAt": "2023-03-03T14:45:54.995Z",
"sentAt": "2023-03-03T14:45:54.311Z",
"timestamp": "2023-03-03T14:45:19.497Z",
"type": "track",
"writeKey": "..."
}
```
> ROX-15459: Track telemetry opt-in and opt-out

- central/namespace/datastore/datastore.go
The build index function builds and idMap that is only used in dackbox SAC. No need to do this on Postgres
No impact except slightly faster start up :)
> Remove unnecessary namespace walk when Postgres is enabled

- central/resourcecollection/datastore/datastore_impl.go
Ensure that Collections includes metrics function calls.
Not necessary.
> ROX-14458: Collections Metrics

- pkg/search/postgres/common.go
- pkg/search/postgres/common_test.go
- pkg/search/postgres/testutils.go
- pkg/search/scoped/context.go
> [ROX-15811] Support scope context evaluation within select query parser

- tests/performance/README.md
Just updating docs to cover some setup issues I encountered along the way.
all n/a
n/a
> Performance Testing Documentation Clarity

- central/globaldb/close.go
Close Postgres on Central shutdown
Will try with sigterms once built
> ROX-15802: Close Postgres on termination

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
TS compile error in unmodified component occurred because CI must have only checked changed files in [earlier PR](https://github.com/stackrox/stackrox/pull/5120).
This unblocks master, until the actual fix can be implemented.
CI only
> Add quick fix to TS error in VM2.0

- central/graphql/resolvers/images_test.go
- central/reports/scheduler/vuln_report_collections_test.go
Added unit tests for image graphQL. Coverage is scoped to the image list page as seen [here](https://docs.google.com/document/d/1c1I9m8cwhdRm3NUwo0D_TxYwAAuIsA-4UMt0VabZg6I/edit#heading=h.wjq0yqnqu4hl).
> Unit tests for image graphQL

- central/processbaseline/datastore/datastore.go
- central/processbaseline/datastore/datastore_impl_test.go
- central/processbaseline/datastore/singleton.go
- central/processbaseline/service/service_impl_test.go
- central/processbaseline/store/postgres/cache.go
- central/processbaseline/store/postgres/store_cache_test.go
- scripts/ci/jobs/gke_postgres_scale_tests.py
This is the first option to add cache to process baseline with simple cache.
screenshots. …
> Add simple cache to process baseline postgres store

- ui/apps/platform/src/Containers/Policies/Wizard/Step2/PolicyBehaviorForm.tsx
Low-hanging fruit to help with this concern:
> Clearly indicate when combinations of policy criteria don't make sense or a policy is invalid because of the criteria selection and why?
Multiple stakeholders (UI, UX, docs, API) to proofread
> ROX-15851: Clarify onscreen hint for runtime policies

- ui/apps/platform/src/Containers/Policies/Wizard/Step2/PolicyBehaviorForm.tsx
Addressing docs team concerns from previous PR
> ROX-15581: Follow up for Clarifying onscreen hints about policy lifecycles

- scripts/ci/lib.sh
- https://github.com/stackrox/junit2jira/pull/8
> ROX-14757: Use job name if multiple suites fails

- scripts/ci/jobs/aks_qa_e2e_tests.py
Per title. This will be tested via future OSCI PR(s).
> ROX-8306: Add an AKS test hook for OSCI

- tests/roxctl/bats-tests/helpers.bash
We have couple of context timeout exceeded errors. Let's increase timeout to see if this help. If not maybe we should retry tests on failure.
CI
> ROX-15326: Increase bundle generation timeout

- scripts/ci/jobs/powervs-qa-e2e-tests.sh
Per title. This is just a stub to exec while tests are being developed. CC @Siddhesh-Ghadi
n/a
> CI: stub for powervs e2e tests

- ui/apps/platform/src/Containers/VulnMgmt/VulnMgmt.constants.ts
A Red Hat tester noticed this issue.
I think this change may also indirectly fix an issue that Piotr noticed as well, https://issues.redhat.com/browse/ROX-15948
Look, ranked by priority
> ROX-16050: Add sort fields for top riskiest node and image components widget

- qa-tests-backend/src/test/groovy/DeploymentTest.groovy
Explicitly scan images to make sure the scan data is populated.
n/a
> [ROX-14919] Scan images that are being tested

- ui/apps/platform/src/Containers/NetworkGraph/components/EmptyUnscopedState.tsx
UX request for changes to initial empty state of the new Network Graph
Manual testing
> ROX-15430: Update empty state of new Network Graph

- pkg/images/enricher/enricher_impl.go
- pkg/images/enricher/enricher_impl_test.go
Reverts stackrox/stackrox#5248
> Revert "[ROX-15808] : Fix for watched images not getting scanned more than once"

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css
- ui/apps/platform/src/Containers/NetworkGraph/components/StyleGroup.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/topology.type.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/modelUtils.tsx
This PR changes the background label color to white for the derived namespaces
> ROX-16014: Change the label background color to white for derived namespaces

- deploy/k8s/deploy.sh
Re-enables re-sync in deploy.sh
* CI
> Revert (#4721 and #4882) re-enable re-sync in deploy.sh

- .github/workflows/build.yaml
Reverts stackrox/stackrox#5321
> Revert "Fix GitHub actions to allow for external contributions"

- qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
> Increase waitForViolation timeout in DefaultPoliciesTest

- scripts/ci/gke.sh
- scripts/ci/lib.sh
Handle GH variables in GKE deploy to allow using it in workflows.
- https://github.com/stackrox/jenkins-plugin/pull/234
> ROX-1137: Add support for GHA in GKE deployment

- .openshift-ci/ci_tests.py
> Increase upgrade test timeout

- ui/apps/platform/cypress/constants/NetworkPage.js
- ui/apps/platform/cypress/helpers/networkGraphPF.js
- ui/apps/platform/cypress/integration/networkGraphPF/networkDeploymentSidebar.test.js
- ui/apps/platform/cypress/integration/networkGraphPF/networkGraph.selectors.js
- ui/apps/platform/cypress/integration/networkGraphPF/networkGraphPF.test.js
- ui/apps/platform/cypress/support/e2e.js
- ui/apps/platform/src/Components/DeploymentContainerConfig.tsx
- ui/apps/platform/src/Containers/NetworkGraph/Topology.css
- ui/apps/platform/src/Containers/NetworkGraph/components/DeploymentSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/LegendContent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/SimulationFrame.tsx
- ui/apps/platform/src/Containers/NetworkGraph/utils/modelUtils.tsx
1. Some refactoring of the first tests
2. Adding test for the deployment sidepanel
I added some data-testid's to make the tests more robust.
1. Ran locally
2. Inspect CI results
> Expand PatternFly Network Graph e2e tests, deployment details

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/CveStatusTabNavigation.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/EntityTypeToggleGroup.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/FilterChips.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadTableToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
also cleaning up some styling/URL param logic to use utils
selecting each entity in the toggle group should update the URL; selection should default to CVE.
screenshots.
> ROX-15026: Adding EntityTypeToggleGroup component

- operator/apis/platform/v1alpha1/central_types.go
- operator/pkg/central/extensions/reconcile_admin_password_test.go
- operator/pkg/central/extensions/reconcile_pvc.go
- operator/pkg/central/extensions/reconcile_pvc_test.go
- operator/pkg/central/values/translation/translation_test.go
- operator/pkg/securedcluster/values/translation/translation_test.go
- operator/pkg/values/translation/translation.go
- roxctl/sensor/generate/generate.go
- sensor/admission-control/manager/evaluate_deploytime.go
- sensor/admission-control/manager/evaluate_runtime.go
- tests/resourcecollection_test.go
Just updating the pointer.* calls to non-deprecated ones
> Use non-deprecated pointer utils

- sensor/debugger/central/communicate_server.go
- sensor/tests/resource/imagescan/imagescan_test.go
- sensor/tests/resource/imagescan/yaml/pod.yaml
This PR provides a test that captures the issue found in the new re-sync pipeline related to `UpdateImages` not being properly handled when scanner updates image components or wasn't up when a deployment is initially processed. 
The issue is fixed by #5365, however, we didn't have any automated tests failed before. This new test will make sure the issue is fixed and also serve as regression in case the code changes.
Just the added tests
> ROX-16208: Sensor UpdateImage integration test

- .github/workflows/cut-rc.yml
- .github/workflows/scripts/create-release.sh
Cherry-picking https://github.com/stackrox/stackrox/pull/3877/files. 
No testing required, already done in cherry-picked commit.
> fix: create-release for release-3.73 branch

- central/telemetry/centralclient/instance_config.go
- pkg/env/telemetry.go
- pkg/renderer/helm_values.go
- roxctl/central/generate/generate.go
- roxctl/helm/derivelocalvalues/derivelocalvalues.go
- tests/e2e/bats/fixtures/test-pod-with-oomkilled_object.json
- ui/apps/platform/cypress/fixtures/network/centralDeployment.json
> ROX-16234: Remove unused `ROX_INIT_TELEMETRY_ENABLED`

- ui/apps/platform/cypress/helpers/networkGraphPF.js
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
Experience enhancement
* Tested locally (screenshot or one-second screen recording is not worth the effort)
* Inspect CI
> Preselect cluster in NG 2.0 if only one cluster

- ui/apps/platform/src/Containers/VulnMgmt/widgets/CvesByCvssScore.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/FrequentlyViolatedPolicies.js
Fixes two GraphQL errors:
1. View All link for CVEs by CVSS Score widget pointed to the wrong type of CVE, when running in a Postgres environment. (This is what the Jira ticket describes.)
2. While troubleshooting this issue, someone notices that the Frequently Violated Policies widget on the VM Dashboard had some extra whitespace characters in its query string. Even though not technically related, since I was double-checking GraphQL issues, I fixed this, too.
* Manual testing
* CI
> ROX-16270: Fix View All link on Node single page

- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
- qa-tests-backend/src/test/groovy/RoutesTest.groovy
Enhance the routes e2e tests.
* Run the tests manually against an ocp cluster
* CI
> ROX-15148 Add more e2e tests for routes

- image/templates/helm/stackrox-central/values-public.yaml.example.htpl
Specify the exact format of the string
docs
> Add extra information for the connection string format

- tests/performance/groups/vulnerabilityManagementDashboard.js
Test updates to reflect changes made in #5461
> ROX-16272: update FE tests to reflect query change

- CHANGELOG.md
> ROX-16302: Deprecation notice for service account api endpoint change

- sensor/common/store/mocks/types.go
- sensor/common/store/types.go
- sensor/kubernetes/eventpipeline/resolver/resolver_impl.go
- sensor/kubernetes/listener/resources/convert.go
- sensor/kubernetes/listener/resources/deployment_store.go
- sensor/kubernetes/listener/resources/deployment_store_test.go
Adds a flag that will check if deployments are fully built. 
> Add isComplete flag to wrapper

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css
- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkGraphIcons.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/topology.type.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/modelUtils.tsx
This PR adds badged labels for Deployments, Namespaces, and CIDR Blocks
> ROX-15409: Add badged labels for entity types

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css
This PR adjusts the minimum width so the left/right scrolling behavior doesn't show up
https://user-images.githubusercontent.com/4805485/229623624-e1f271ac-ed88-4206-a529-86cb3b382447.mov
> ROX-15410: fix minimum width of network graph side panel

- qa-tests-backend/scripts/run-part-1.sh
> CI: No longer exit on first failure in nightlies

- .openshift-ci/post_tests.py
With the switch to Spock 2.0 this directory changed name. It contains a useful summary of test results,
> CI: Update spock reports dir

- CHANGELOG.md
automation didn't do it for some reason.
screenshots.
> Dashrews/changelog 4.0.0

- .openshift-ci/dispatch.sh
- .openshift-ci/pre_tests.py
- scripts/ci/gcp.sh
- scripts/ci/lib.sh
- scripts/ci/metrics.sh
- scripts/ci/store-artifacts.sh
- tools/allowed-large-files
This is an initial pass to create some job history for CI. 
What is saved by this PR is just basic info: name, git info, outcome, run time and basic cluster under test info. One could expand with other attributes once this PR passes and dot the test code with e.g. `update_job_record something_of_value ...` and the like. If there are *any* bits of data that you would like to see added in this PR and the value is ready available, let me know and I will add it. Docs for adding columns etc t.b.d.
Corresponds to jobs run at [c85d566](https://prow.ci.openshift.org/pr-history/?org=stackrox&repo=stackrox&pr=5599).
```
$ bq query --use_legacy_sql=false 'select * from stackrox-ci.ci_metrics.stackrox_jobs'
+---------------------+----------------------------------+-------------------+--------+-------- …
```
> CI: Store basic job metrics

- deploy/common/deploy.sh
- deploy/common/k8sbased.sh
This reverts commit 359beb495d25b15f202e5bf35a78937ca14fd224.
screenshots.
> Revert "Allow for using tokens to deploy sensors in deploy.sh (#4417)"

- scripts/ci/gke.sh
- scripts/ci/lib.sh
- scripts/ci/store-artifacts.sh
Also style this and other pages like Prow.
None of these are needed:
> Make GCloud artifacts page show up in Prow directly

- central/processlisteningonport/datastore/datastore_impl.go
- central/sensor/service/pipeline/processlisteningonport/pipeline.go
> Jv change plop warn to debug

- central/resourcecollection/service/service_impl.go
Update the Collections Get endpoint to have a more descriptive error message when failing to find a requested collection.
Testing done through CI.
> Clean up Collections error message on a not found request

- scripts/ci/lib.sh
- tests/e2e/bats/check_for_stackrox_OOMs.bats
- tests/e2e/lib.sh
Per title, to remove the 'crowding' from the top level artifacts dir.
> CI: put test junits in a separate dir

- central/graphql/resolvers/image_cve_core.go
- central/graphql/resolvers/image_cve_core_test.go
- central/views/imagecve/view_impl.go
- central/views/imagecve/view_test.go
> Add filter query support to imageCVE graphQL resolver

- sensor/kubernetes/listener/resources/deployments.go
If re-sync is enabled we might run into a data race between the deployment and service dispatchers. This occurs whenever a deploymentWrap gets inserted in the store in the deployment dispatcher and at the same time a service affecting the same deployment gets created/updated. Since the deployment dispatcher does some modifications to the deploymentWrap after inserting it in the store, this can cause a data race between the two dispatchers. To solve this we simply insert the deploymentWrap in the store after applying all the modifications. …
> ROX-15351 fix data race between the deployment and service dispatchers

- sensor/common/networkflow/manager/manager_impl.go
Orphaned listening endpoints in sensor that have no associated container are not currently being removed. This fixes that problem.
> Jv remove rotten endpoints

- operator/main.go
- operator/pkg/central/reconciler/reconciler.go
- operator/pkg/central/reconciler/reconciler_test.go
Adds an optional environment variable to the operator to enable selective reconciliation based on a label selector
> ROX-16369 Enable operator selective reconciliation

- .github/labeler.yml
Add label for CI related PRs
N/A
> Add area/ci label for CI prs

- CHANGELOG.md
- central/role/datastore/datastore_impl_test.go
- central/role/datastore/permissionset_ids.go
- central/role/datastore/singleton.go
- central/role/default.go
Add a default role that makes it easier to perform vulnerability management activities.
> Add a default role for vulnerability management

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/SeverityCountLabels.tsx
- ui/apps/platform/src/constants/visuals/colors.ts
Adding the dimmed color for counts of zero and adding colors for the other counts.
> CVE severity label counts polish

- central/role/datastore/singleton.go
> Add workflow administration to default vulnerability manager role

- qa-tests-backend/src/test/groovy/GroupsTest.groovy
Roles were added, but not deleted after test is executed.
> Cleanup roles used in GroupsTest.groovy

- CHANGELOG.md
> Jv rox 16533 changelog for processes listening on ports

- central/graphql/resolvers/image_components.go
- central/graphql/resolvers/image_components_postgres_test.go
- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/test_setup_utils.go
- central/graphql/resolvers/test_utils.go
- central/imagecomponentedge/datastore/datastore_test_constructors.go
Ran unit tests with VM 2.0 feature enabled and disabled.
> Add unit tests for image component graphQL

- qa-tests-backend/src/test/groovy/NetworkBaselineTest.groovy
Please see commit messages.
None of these will be done:
Will check the test output in CI makes sense.
> ROX-14975: Improve `NetworkBaselineTest` diagnostic on flakes

- .github/workflows/cut-rc.yml
Cherry-picking 
* https://github.com/stackrox/stackrox/commit/fcd30367a1b07c44d9091289fb0f6d9baf693aea
* https://github.com/stackrox/stackrox/commit/d28fae81ec3d595dd2cd34fa2fd34eb4b1317c4e
Proof run: https://github.com/stackrox/stackrox/actions/runs/4734636516
> cherry-pick cut-rc: update demo flavors (3.74.x)

- .github/workflows/cut-rc.yml
Cherry-picking 
* https://github.com/stackrox/stackrox/commit/fcd30367a1b07c44d9091289fb0f6d9baf693aea
* https://github.com/stackrox/stackrox/commit/d28fae81ec3d595dd2cd34fa2fd34eb4b1317c4e
Proof run: https://github.com/stackrox/stackrox/actions/runs/4734636516
> cherry-pick cut-rc: update demo flavors (3.73.x)

- sensor/common/detector/enricher.go
If `runImageScanAsync` gets called at the same time for images with the same id (digest) but different names, then `forceEnrichImgeWithSignatures` will be set to `true` forcing a re-scan. This could lead to data races in `runScan` if more than one goroutine gets to call `scanAndSet` at the same time.
* Solution was manually tested using the tests in #5691
* CI also passed in …
> ROX-16038 fix data race in the enricher

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/SingleEntityVulnerabilitiesTable.tsx
As titled.
Visit the Image single page - CVSS scores and version numbers should be present and sortable for rows in the table.
> Add CVSS to workload cve image single page

- ui/apps/platform/package.json
- ui/apps/platform/src/Containers/MainPage/AcsFeedbackModal.tsx
- ui/apps/platform/src/Containers/MainPage/Header/HelpMenu.tsx
- ui/apps/platform/src/Containers/MainPage/MainPage.tsx
- ui/apps/platform/src/css/trumps.css
- ui/apps/platform/src/images/feedback_illo.svg
- ui/apps/platform/src/reducers/feedback.ts
- ui/apps/platform/src/reducers/index.js
- ui/yarn.lock
This change adds the ability to open a modal where the user can share feedback through Red Hat's Qualtrics account.
The modal can be opened in one of two ways (hence my use of Redux to avoid prop-drilling)
1. Through a new item in the Help (?) menu
2. Through a floating button in the lower right of the window
The feedback modal is using a beta PatternFly extension component, https://github.com/patternfly/react-user-feedback, which generalizes the current feedback system in console.redhat.com. The customization options for that component are currently quite limited.
Because other Red Hat products can't use console.redhat.com's custom backend, and the ACS backend team doesn't have bandwidth to write our own, we are using a separate form page Red Hat has available for other apps to get …
> ROX-15828: Add share feedback modal

- ui/apps/platform/cypress/constants/SystemHealth.js
- ui/apps/platform/cypress/integration/systemHealth/bundle.test.js
- ui/apps/platform/src/Containers/SystemHealth/Components/DeclarativeConfigurationHealthCard.tsx
- ui/apps/platform/src/Containers/SystemHealth/Components/DeclarativeConfigurationHeathCard.tsx
- ui/apps/platform/src/Containers/SystemHealth/Components/IntegrationHealthWidgetVisual.tsx
- ui/apps/platform/src/Containers/SystemHealth/DashboardPage.js
- ui/apps/platform/src/services/IntegrationHealthService.js
1. Minimize risk to add **Declarative configuration** to System Health page.
2. Reuse some initial work on classic to PatternFly conversion from Van. In contrast to the original plan, make incremental changes in place.
3. Update some subset of classic components to PatternFly:
* Diagnostic Bundle dialog box: high priority and use what Van already did.
* Integrations cards: medium priority and medium effort.
* Vulnerability Definitions: low priority although low effort.
* Cluster Health: instead of development work, an iterating redesign discussion with Mansur is the priority during 4.1 sprints.
1. Rewrite frontend service file in TypeScript.
2. Factor out common components for updated integration cards.
3. Move useful files and delete unused files from PatternFly subfolder.
4. Update …
> Add declarative configuration card to System Health page

- qa-tests-backend/src/test/groovy/ImageSignatureVerificationTest.groovy
- https://github.com/stackrox/stackrox/pull/4738
CI
> ROX-16396: Wait for namespace deletion in test cleanup

- .github/actions/junit2jira/action.yaml
- .github/workflows/unit-tests.yaml
This PR add junit2jira action that will report failures found in junit XML files to Jira.
https://github.com/stackrox/stackrox/actions/runs/4699075635/jobs/8332123252#step:9:36
> ROX-14331: Enable junit2jira in GHA

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
> ROX-7878: Fix flake "Verify generated network policies"

- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
- qa-tests-backend/src/test/groovy/Enforcement.groovy
To make debugging easier let's add a line with information about number of pods for deployment.
CI
> ROX-16290: Add debug log for deployment update

- ui/apps/platform/package.json
- ui/yarn.lock
This PR updates the version of @patternfly/react-topology. Nicole advised us to update the version, open a PR so that CI can run and check for the new test/build failures, and then give a quick manual check of topology in ACS to make sure we don't see any new run time failures or visual/interaction regressions
Please try checking the UI yourself
> refactoring: updating react topology library version

- scripts/ci/openshift.sh
Per title. It is hard to figure out these failures without some debug for comparison.
> ROX-16740: Get debug for OCP cluster scaling failures

- ui/apps/platform/src/Components/CVEStackedPill/CVEStackedPill.js
"We are all individuals."
Before
After
> ROX-16718: Improve text contrast in image scan message tooltip

- scale/workloads/10-sensors.yaml
Trivial change, just ups the number of flows we're receiving
Running this as part of the scale tests
> Increase flows for 10-sensors scale workload

- scripts/ci/jobs/ocp_ui_e2e_tests.py
- ui/apps/platform/cypress/integration/compliance/complianceDashboard.test.js
- ui/apps/platform/cypress/integration/compliance/complianceList.test.js
- ui/apps/platform/cypress/integration/configmanagement/ciscontrols.test.js
- ui/apps/platform/cypress/integration/configmanagement/dashboard.test.js
- ui/apps/platform/cypress/integration/configmanagement/nodes.test.js
- ui/apps/platform/cypress/integration/integrations/imageIntegrations.test.js
Per title. A few test suites and tests were disabled in order to get to pass in these environments. This PR will allow enablement in nightly CI and merge runs.
> ROX-15290: Enable UI E2e for OCP 4.10 and 4.12

- central/featureflags/service/service_impl.go
- pkg/env/local_notifiers.go
- pkg/env/secured_cluster_notifiers.go
- tests/feature_flag_test.go
> ROX-16749: Local Notifiers Env Variable

- pkg/grpc/logger.go
Silence preface logs due to haproxy probes
Run in environment where this error occurs
> ROX-15236: Silence http logs containing preface

- ui/apps/platform/cypress/constants/SystemHealth.js
- ui/apps/platform/cypress/constants/apiEndpoints.js
- ui/apps/platform/cypress/helpers/systemHealth.js
- ui/apps/platform/cypress/integration/systemHealth/integrations.test.js
- ui/apps/platform/src/Containers/SystemHealth/Components/DeclarativeConfigurationHealthCard.tsx
Tests to cover https://github.com/stackrox/stackrox/pull/5773
> Declarative configuration card UI tests

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CveStatusTabNavigation.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/EntityTypeToggleGroup.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/TableEntityToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/sortUtils.tsx
* adding dynamic filter to First Discovered column
* refactoring to be able to reset sort options on entity type toggle group click
* adding `TableEntityToolbar` component to hold the toolbar elements instead of copy/pasting (in order to reset the sort state on entity toggle, we needed to pull the toolbar components down)
everything else should work as expected
"No testable changes". Feel free to attach …
> Workload CVEs overview page fixes pt 1

- ui/apps/platform/cypress/integration/networkGraphPF/networkGraphPF.test.js
This PR fixes a Network Graph e2e test failure in nightlies
> ROX-16827: Fix network graph test

- ui/apps/platform/package.json
- ui/apps/platform/src/Containers/MainPage/AcsFeedbackModal.tsx
- ui/yarn.lock
Improves some internals and build processes, no outward changes that we currently use.
Keeping up with the head of the extension's development, because it is not officially stable, and we are one of its earliest consumers.
Manual testing and CI
> Upgrade react-user-feedback extension to 1.0.9

- scripts/ci/lib.sh
Reverts stackrox/stackrox#5742
> Revert "Revert "Upgrade junit2jira (#5672)""

- central/graphql/resolvers/image_cve_core.go
- central/views/imagecve/db_response.go
- central/views/imagecve/mocks/types.go
- central/views/imagecve/types.go
- central/views/imagecve/view_impl.go
- central/views/imagecve/view_test.go
- pkg/metrics/resolver_string.go
- pkg/metrics/resolvers.go
> [ROX-16719][ROX-16802][ROX-13858] Get all distro tuples for CVE

- central/notifier/processor/notifier_set_test.go
> ROX-16743: Fix style check

- central/notifier/service/service_impl.go
Central side changes for Test Notifier workflow for secured cluster notifiers.  Unit tests not possible for test, we will rely on e2e when enabled in CI (after secured cluster side changes come in post refactors)
None, CI only.  Env var to be turned on in CI once secured cluster side changes come through.
> ROX-16755: Central side changes for Test Notifier workflow for secured cluster notifiers

- ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx
- ui/apps/platform/src/Containers/AccessControl/AuthProviders/authProviders.utils.ts
> ROX-15773: Disable minimum access role selection if defined declaratively

- CHANGELOG.md
- image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml
- image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl
- image/templates/helm/stackrox-secured-cluster/templates/admission-controller.yaml
- image/templates/helm/stackrox-secured-cluster/values-public.yaml.example
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/admission-control.test.yaml
Add Helm parameter for admission controller parameters.
- Added CI test
> ROX-16959 - Add admission controller replicas Helm parameter

- sensor/admission-control/resources/namespaces/namespace.go
> Check for namespace existence before returning annotations

- sensor/common/compliance/node_inventory_handler_impl.go
- sensor/common/component.go
- sensor/common/sensor/sensor.go
Add offline mode message. This is a foundation PR just to unblock working on individual components as well as entering in offline-mode when gRPC breaks.
> ROX-17038: Offline mode

- ui/apps/platform/src/Components/CVEStackedPill/CVEStackedPill.js
- ui/apps/platform/src/Components/KeyValuePairs.js
- ui/apps/platform/src/Components/Metadata/Metadata.js
- ui/apps/platform/src/Components/Table.js
- ui/apps/platform/src/Components/TableV2.js
- ui/apps/platform/src/Containers/MainPage/Notifications.tsx
- ui/apps/platform/src/Containers/Network/SidePanel/NetworkDeploymentOverlay/DeploymentDetails/ContainerConfigurations.tsx
- ui/apps/platform/src/Containers/Risk/ContainerConfigurations.js
- ui/apps/platform/src/Containers/VulnMgmt/List/Cves/CveToPolicyShortForm.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/TopRiskiestEntities.js
- ui/apps/platform/src/utils/vulnerabilityUtils.js
Follow up #5977
1. Difficult to distinguish font-700 for keys from font-600 for values in key-value pairs.
2. No need to specify font-600 for table data cells.
Find in Files `font-600`
|         | Results | Files |
| :---    |    ---: |  ---: |
| before  |      95 |    52 |
| deleted |      30 |    11 |
| after   |      65 |    41 |
1. Visit /main/compliance/clusters
* dark theme
* light theme
2. Visit /main/vulnerability-management/clusters
* dark theme
* light theme
3. Visit /main/configmanagement/clusters
* dark theme
* light theme
4. Visit /main/risk
* dark theme
* light theme
1. Visit /main/configmanagement/clusters and click a cluster
* dark theme
* light theme
2. Visit /main/vulnerability-management/clusters and click a cluster
* dark theme
* light theme
1. Visit /main/network, …
> Delete occurrences of Tailwind font-600 class from values and table data cells

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
> Disable Verify connections from external sources in Openshift

- scripts/ci/lib.sh
Per title. @janisz I used v0.0.8 as I wasn't sure about the extra 0 in the v0.0.07, typo? or?...
CI is sufficient. Should see lots of test results in BQ.
> CI: Store test metrics

- image/templates/helm/stackrox-secured-cluster/internal/defaults/40-resources.yaml
- image/templates/helm/stackrox-secured-cluster/values-public.yaml.example
> ROX-17019: Reduce node-scanning container memory limit to 500 Mi

- central/networkpolicies/datastore/datastore_impl.go
- central/networkpolicies/datastore/datastore_impl_test.go
- central/networkpolicies/datastore/internal/store/bolt/store_impl.go
- central/networkpolicies/datastore/internal/store/mocks/store.go
- central/networkpolicies/datastore/internal/store/store.go
- scale/workloads/10-sensors.yaml
> Use search for network policies instead of walks (#6079)

- .github/workflows/build.yaml
- .openshift-ci/Dockerfile.build_root
- .openshift-ci/build/Dockerfile.build-central-db-bundle
- .openshift-ci/build/Dockerfile.build-main-and-bundle
- .openshift-ci/build/Dockerfile.build-operator-artifacts
- BUILD_IMAGE_VERSION
- Makefile
- docs/Dockerfile
- scale/signatures/deploy.yaml
> Bump builder/tester images to 0.3.50.3 with fixed go, node, java versions

- go.mod
- go.sum
Isolating a change form #6050 to test it using e2e tests (for some reasons e2e tests do not start for PRs open by external contributors).
- CI
> Bump openshift/api dependency for #6050

- roxctl/common/flags/endpoint.go
> Fix flag description

- ui/apps/platform/cypress/helpers/networkGraphPF.js
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/services/NetworkService.js
This PR fixes an issue with consistent data between scoping. For more details see this Jira for the actual issue https://issues.redhat.com/browse/ROX-14668. 
This PR builds on top of the changes from the backend found in this PR https://github.com/stackrox/stackrox/pull/5306. 
https://user-images.githubusercontent.com/4805485/236892213-2735bd0a-0eb8-4524-ba4f-518d8a4dd635.mov
> ROX-16742: consistent network policy graph between scoping

- .github/CODEOWNERS
> Scanner team owns SCANNER_VERSION

- operator/README.md
I had trouble deploying the operator via OLM using the given instructions, so I've updated them here in an attempt to fill in the gaps where I got stuck along the way.
Looks like the diff is way more confusing than I feel like it needs to be, sorry.
Changes:
* Renamed "Launch the Operator with OLM and Index" to "Installing operator via OLM"
* Added a prerequisites section
* Explained how to run the `olm-operator-install.sh` script if desired
I developed the updated instructions while working with the commands locally.  I suggest reviewers do the same if they want to verify correctness!
> Clarify instructions to install operator via OLM

- ui/apps/platform/src/Containers/AccessControl/AuthProviders/ConfigurationFormFields.tsx
- ui/apps/platform/src/Containers/AccessControl/AuthProviders/authProviders.utils.ts
Would help some of our customers if we have this option in the UI, not only in API.
> ROX-17226: Add option to disable offline_access to UI

- ui/apps/platform/cypress/integration/configmanagement/ConfigurationManagement.helpers.js
Counterpart to #6095
Thanks to Van for sending links to recent test failures.
> Configuration Management Policies should have same number in deployments table as in count widget of side panel
> Timed out retrying after 4000ms: Expected to find element: `[data-testid="side-panel"] [data-testid="panel-header"]:contains("118 deployments")`, but never found it.
118 in assertion but 119 in DOM
Especially on OpenShift, count of deployments can change:
* from table link or entity link
* to panel header in list page
| helper function                      | results | files |
| :---                                 |    ---: |  ---: |
| pageEntityCountMatchesTableRows      |      35 |    12 |
| sidePanelEntityCountMatchesTableRows |      35 |    12 |
| entityListCountMatchesTableLinkCount |      15 …
> ROX-17297: Remove specific counts from assertions for Configuration Management integration tests

- central/notifiers/all/all.go
- central/notifiers/metadatagetter/datastore_impl.go
- central/notifiers/metadatagetter/datastore_impl_test.go
- central/notifiers/syslog/syslog.go
- pkg/features/list.go
- pkg/notifiers/metadata_getter.go
- pkg/notifiers/mocks/metadata_getter.go
- pkg/notifiers/syslog/syslog.go
- pkg/notifiers/syslog/syslog_test.go
- tests/e2e/lib.sh
Send namespace name and namespace labels as part of the syslog alert notification if a new feature flag is enabled. 
Manual and unit
> ROX-17200, ROX-17201: Send namespace and namespace labels for syslog alert notifications

- .gitattributes
Mark `go.sum` as generated as in fact it's generated and we have a check to validate it's fine so no need for human review.
- https://github.com/stackrox/stackrox/commit/fc9f9748152bc38a0afa447971562627523bc48c
> Mark go.sum as generated

- pkg/features/list.go
> ROX-17202: Enable Syslog Namespace labels by default

- image/templates/helm/stackrox-secured-cluster/README.md.htpl
- image/templates/helm/stackrox-secured-cluster/values-public.yaml.example
- operator/apis/platform/v1alpha1/securedcluster_types.go
- operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml
- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml
- operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
- roxctl/sensor/generate/generate.go
- ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx
Explicitely mention everywhere, where it could be used for configuring, that CORE_BPF is in Tech Preview.
> Mention CORE_BPF status

- roxctl/analyze/analyze.go
- roxctl/analyze/netpol/netpol.go
Updates to command description of `roxctl analyze netpol`
> [ROX-16898] analyze netpol cmd: update description

- scripts/ci/collect-infrastructure-logs.sh
- scripts/ci/logcheck/blocklist-patterns
For reviewers: I'm interested in your opinion on https://github.com/stackrox/stackrox/pull/5007#discussion_r1210337780
- ~~[ ] Unit test and regression tests added~~ - not testing regexes in hopes that I did all things right and manual validation was sufficient.
These aren't done because aren't needed:
- Manual testing in https://github.com/stackrox/stackrox/pull/6215.
- Green CI here.
> ROX-15340: Add patterns of v1beta1 CronJob and other apis to log checking

- CHANGELOG.md
The timeline can be found [here](https://docs.google.com/spreadsheets/d/19W-y00GJCc8ob1JJc_CMDHXVmnNn5Tq6Y05_daUAyws/edit#gid=1897088338)
> [ROX-17504] Add deprecation notice for legacy workload CVEs

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
This is a potential fix for the page crash that Shubha encountered during the bug bash. Twice during the testing, she encountered a crash when navigating to the deployment page via the image resources tab. The only error information we could pull from the crash was `cannot read property metadata of undefined`. We have not yet been able to reproduce this behavior.
This is a best effort preventative fix against the behavior described above. Starting at the top most component of the `DeploymentPage`, there is only a single location where an object with a `metadata` property is attempted to be read from. This is in the embedded table, when we are associating vulnerability data with an image's docker layers (`image->metadata->v2->layers`). This table expects a non-nullable type of `image`, but …
> Add additional safety check when mapping image vulnerabilities to image metadata

- ui/apps/platform/package.json
- ui/packages/ui-components/package.json
- ui/yarn.lock
Quarterly update has no breaking changes for ui code.
* https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#easier-implicit-returns-for-undefined-returning-functions
* https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#unrelated-types-for-getters-and-setters
* https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#decoupled-type-checking-between-jsx-elements-and-jsx-tag-types
> Update TypeScript 5.1.3 devDependencies in ui

- ui/apps/platform/cypress/constants/SystemHealth.js
- ui/apps/platform/cypress/integration/integrations/integrations.helpers.js
- ui/apps/platform/cypress/integration/systemHealth/integrations.test.js
- ui/apps/platform/src/Containers/SystemHealth/Components/BackupIntegrationHealthWidget.tsx
- ui/apps/platform/src/Containers/SystemHealth/Components/ImageIntegrationHealthWidget.tsx
- ui/apps/platform/src/Containers/SystemHealth/Components/IntegrationHealthWidgetVisual.tsx
- ui/apps/platform/src/Containers/SystemHealth/Components/IntegrationsHealth.tsx
- ui/apps/platform/src/Containers/SystemHealth/Components/NotifierIntegrationHealthWidget.tsx
- ui/apps/platform/src/Containers/SystemHealth/DashboardPage.js
Also, UI is more aligned with declarative config health card + error messages added.
TBD: fix UI tests
> Migrate integration health UI to use PatternFly

- CHANGELOG.md
Update changelog for PVC retirement
screenshots. …
> ROX-13206: Update change log for PVC retirement

- .github/workflows/check-pr-title.yaml
Check if PR title matches a "good PR title" regex, and if it fits 70 characters.
See the check runs of this PR.
> ROX-0: Check PR title format

- qa-tests-backend/src/test/groovy/GlobalSearch.groovy
> ROX-17508: Fix exception in GlobalSearch.groovy

- .github/properties
- scripts/ci/lib.sh
- scripts/ci/publish-helm-charts.sh
Cherry-pick #6349 .
No testable changes.
> 4.0: ROX-16356: Release automation: switch slack notification channels (#6349)

- pkg/features/list.go
> ROX-17649: Enable ROX_DISABLE_COMPLIANCE_STANDARDS feature flag

- central/search/service/service_impl_test.go
- central/telemetry/gatherers/gatherer_test.go
Fixes CI lint that I didn't catch. Not sure how that test didn't fail
CI
> fix(ci): Fix CI lint

- .github/workflows/update_collector_periodic.yaml
https://github.com/stackrox/stackrox/pull/6107 added a check on the PR name style.
> fix(roxbot): dress the collector bump automatic PR

- .github/workflows/update_scanner_periodic.yaml
We now need to adhere to a particular title format
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~
No
> chore(ci): update periodic Scanner bump PR title

- ui/apps/platform/cypress/integration/integrations/notifiers.test.js
- ui/apps/platform/package.json
- ui/yarn.lock
Was going to update several libraries' minor / patch versions, but ran into situation where some library cause a TS compiler incompatibility, so just doing Yup in this round.
I ran the ui-e2e tests for pages with forms locally.
> chore(ui): Update Yup library for June 2023

- tests/yamls/multi-container-pod.yaml
> Fix e2e tests by pinning debian
