stackrox/stackrox

ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopesList.tsx, ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProvidersList.tsx, ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSetsList.tsx, ui/apps/platform/src/Containers/AccessControl/Roles/RolesList.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsTable.tsx
* Follow current PatternFly example:
https://www.patternfly.org/components/table#actions
* Increase our ability to reuse knowledge and skills to update tables easily.
* Simplify lint rules for consistency.
main.js 0 = 4637804 - 4637804
total 4 = 11749510 - 11749506
files 0 = 180 - 180
1. Visit /main//access-control/roles and add a user role
* Before changes, with `actions` prop at 1440px.
* After changes, with `isActionCell` prop and `ActionsColumn` child element as 1440px.
* After changes, with `isActionCell` prop and `ActionsColumn` child element at 760px.
2. …
=> chore(ui): Replace Td actions with Td isActionCell and ActionsColumn

pkg/metrics/tls.go, pkg/mtls/certwatch/certwatch.go, pkg/mtls/certwatch/options.go
The monitoring TLS certs are generated by the OpenShift CA operator. They do not contain the cluster root certs, and therefore verification fails. The verification was first introduced for our own stackrox certs, which do contain the root cert. To avoid customer confusion, let's disable the verification, which is expected to fail for monitoring certs.
Example log message that should be avoided:
```
pkg/mtls/certwatch: 2024/10/30 08:51:23.002130 certwatch.go:68: Warn: This server does not trust its own certificate! If you see certificate trust issues in your clients (e.g. sensors), please ensure that your certificate PEM file includes the entire certificate chain.Watch dir: "/run/secrets/stackrox.io/monitoring-tls"
```
change me!
=> chore: don't verify monitoring tls certs

ui/apps/platform/src/hooks/useAnalytics.test.ts, ui/apps/platform/src/hooks/useAnalytics.ts
Removes hostname information and installation-specific search values from analytics metadata when page views and events are tracked.
The changes are summarized as follows:
1. The `referrer` field is replaced with an empty string unconditionally
2. The `search` field has values replaced if (a) The top level key is either `s` or `s2` (b) The filter level key _does not_ match a defined allow-list.
3. The `url` field has the hostname replaced with the text `redacted.host` and the search portion of the URL replaced as described in (2) above.
Unit tests were added to validate the behavior of the new functions.
Test the redacted properties when a PageView event is sent:
Test the redacted properties when a user-initiated event is sent:
=> ROX-26415: Remove install-specific URL data in telemetry

central/views/imagecve/db_response.go, central/views/imagecve/view_test.go, pkg/pointers/pointer.go
When we added the NVDCVSS field we saw that without a migration we failed to read data into the primitive objects particularly figuring out the max of a float.  Those fields should be pointers such that we can read the data from postgres without the need to artificially set the value to 0.  We can handle that logic in the code with the getters.
This is not a problem for count fields because a count cannot return null, just 0.
Updated the tests which prove this on when we skip the various cvss flags as those would return nil as the column isn't present and the Getters translate the nil.
Also created a cluster and manually set cvss to NULL in the database and verified that it returned 0 instead of a null.  Doing that on an old version crashed central.
=> ROX-26710: vm nulls of primitive query fields

.tekton/main-pipeline.yaml
As a workaround for https://issues.redhat.com/browse/KFLUXBUGS-1508
No contributions to automated tests.
There's a chance Konflux EC won't be happy with the image, I'd request policy exception as part of the same task ROX-26889
=> ROX-26889: Build `main` source image without Cachi2 artifact

ui/apps/platform/cypress/fixtures/vulnerabilities/workloadCves/multipleCvesForImage.json, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveListExceptionFlow.test.js
Re-enables integration tests for deferring multiple CVEs as part of a single request. This change mocks the request for CVEs belonging to a single image because:
- We cannot rely on an image always having more than one CVE
- The full e2e behavior is not dependent on the CVEs that are part of an exception request being present in the system
CI
=> ROX-26706: Mock CVE response for image in multi-cve deferral test

ui/apps/platform/src/hooks/useAnalytics.ts
Great catch - better to keep this in line with the standard.
Adds the `.invalid` TLD in order to prevent potentially route-able hosts from being included in telemetry data.
Manual network tab verification.
=> chore(ui): Update redacted host name to be under .invalid TLD

ui/Makefile
Silences the `npm-audit` output when running `make deps` from the UI level. In replacement, this also adds an explicit `npm audit --omit=dev || true` in order to output vulnerabilities in production level packages for UI code.
This will focus on dependency vulnerabilities that are most likely to affect the product and should be a good target to keep clean from findings before they are reported in security-labelled Jira tickets.
`make clean && make deps` from ui/ folder and see presence of detected issues. Detected issues should not fail the command/build.
=> ROX-25751: Update npm-ci audit to show vulns in prod deps only

ui/apps/platform/package-lock.json
Removes transitive nested dependencies on d3-color 3.0.1 and relies on the version compatible top-level 3.1.0.
Smoke testing of pages that rely on d3-color.
=> chore(ui): Remove d3-color 3.0.1 and depend on 3.1.0

qa-tests-backend/src/test/groovy/SummaryTest.groovy
`getSTaticPodCount` already filters the static pods the way sensor does it. Filtering for pod names that start with `static` is no always right as sensor only adds that prefix to kube-proxy pods that have a non-tracked owner.
=> fix(test): Fix the way the statics pods are counted in TopNav

roxctl/netpol/generate/generate.go, roxctl/netpol/generate/generate_test.go, tests/roxctl/bats-tests/local/roxctl-netpol-generate-development.bats, tests/roxctl/bats-tests/local/roxctl-netpol-generate-release.bats
This change is only relevant for the `roxctl netpol generate` command.
Previously, the `--dnsport` flag only allowed an integer as its argument.
This prevented users from specifying a named port as the default DNS port.
With the proposed change, users will be able to specify both strings and integers as the argument of `--dnsport`.
If the argument can be safely converted to an integer, it will be interpreted as such. Otherwise, it is interpreted as string.
Validity checks were modified accordingly.
Unit tests (for bad path) and e2e tests (for good path) should cover this small change.
=> ROX-25007: Allow named port to be set with the --dnsport flag

qa-tests-backend/scripts/run-compatibility.sh, tests/e2e/run-compatibility.sh
For version tags that include a minor version each time that version is bumped up failing compatibility tests create new JIRA tickets. The goal of this PR is to avoid that by cutting off the minor tags and replacing them with `z`. I'm doing this for both the `gke-version-compatibility-tests` and `gke-nongroovy-compatibility-tests` which still share some code duplication (to be addressed later).
While at it I would also like to remove the test summary which creates an additional JIRA ticket for each failing version tuple (extra noise)
I'm going to run the tests and see how CI stores the results and how the logs look.
=> ROX-22770: Improve CI JIRA automation for compatibility tests

pkg/utils/ignore_error.go, sensor/tests/helper/helper.go, sensor/tests/resource/role/role_test.go, sensor/tests/resource/service/service_test.go
Sensor integration tests create k8s resources to test sensor's behavior. This resources are deleted after the test execution most of the times with defered calls to remove functions. If the resource creation fails the remove functions will be nil. The defered calls to these remove functions need to check whether the remove function is nil or not, otherwise the test will panic.
This PR introduces three changes:
1. Modifies the `IgnoreError` function to check whether the passed function is nil or not.
2. Changes the use of `t.Fatal` in some functions of the integration tests helper to avoid the subtest calling FailNow and therefore failing the parent tests.
3. The defered calls to remove functions should be done after `require.NoError`. If `err != nil` the resource was not created so it's …
=> ROX-24767: Ignore function call if the function is nil

.tekton/main-pipeline.yaml
Per ticket.
Nope.
Successful main build.
=> ROX-26900: Re-add Cachi2 artifact to main's build-source task

central/networkgraph/config/datastore/singleton.go, central/sensor/service/pipeline/deploymentevents/validate_input.go, central/serviceaccount/service/singleton.go, central/telemetry/gatherers/singleton.go, config-controller/api/v1alpha1/policy_types.go, pkg/registries/factory.go, sensor/kubernetes/listener/resources/networkpolicy_store.go, tools/import_validate.py
The blank line detection algorithm was entering a fail state when a blank line is introduced inside the first party imports.
If so, either `fix_blanks` or `golangci-lint` will fail, depending on what last ran, `quickstyle` or the IDE import optimizer.
This PR rectifies this by introducing an updated mechanism to better detect these fail states.
I recommend to review this PR by commits. The first commit introduced the linter fix, the second commit updated files to satisfy the new linter requirements.
To reproduce locally, introduce a newline into any first party import block **on any other branch than this PR**.
Example: [sensor/kubernetes/main.go](https://github.com/stackrox/stackrox/blob/03b81c90e74f49877e84a159f4c114593b307852/sensor/kubernetes/main.go#L4-L5) between lines 4 and 5.
- …
=> ROX-26885: fix blank line detection for imports

pkg/grpc/marshaler_test.go, pkg/grpc/server.go, pkg/grpc/server_ratelimit_test.go, pkg/grpc/server_test.go, pkg/grpc/testutils.go
Adds more logging to the `Stop` function of the gRPC Server in `pkg/grpc`. It also adds a function to print the state of the ports if the unit tests panic due to `syscall.EADDRINUSE`.
This should help debugging the flake [ROX-22816](https://issues.redhat.com/browse/ROX-22816). These changes should be reverted once the problem is solved.
```golang
func (a *APIServerSuite) Test_ForcePanic() {
api1 := NewAPI(defaultConf())
api2 := NewAPI(defaultConf())
a.Assert().NoError(api1.Start().Wait())
a.Assert().NoError(api2.Start().Wait())
}
```
=> feat(debug): Add more logging in the gRPC server package

tests/e2e/run-ui-e2e.sh
We are currently facing an issue with loading JUnit iframe in prow because of a long URL. This change should fix that.
This is related to the ticket: https://issues.redhat.com/browse/ROX-26907
**Notes for reviewers**
- UI Team: can we copy reports only from `ui/test-results/reports/cypress/integration` - or do we still need to include `cypress/integration`?
- no changes on tests
```
<...> test1.txt
<...> rep1
<...> test1.txt
<...> test1.txt
<...> sub-rep
<...> test.txt
<...> rep
<...> sub-rep
<...> test.txt
```
=> chore(ci): Fix JUnit iframe in prow

ui/apps/platform/eslint.config.js, ui/apps/platform/package-lock.json, ui/apps/platform/package.json
https://www.npmjs.com/package/@eslint/json
> This plugin requires ESLint v9.6.0 or higher and you must be using the new configuration system.
Upgraded to ESLint 9.13.0 in #13164
https://eslint.org/blog/2024/10/eslint-json-markdown-support/#json-linting-with-%40eslint%2Fjson
> JSON linting is accomplished using the `@eslint/json` plugin, which is an officially supported language plugin.
> The plugin provides parsing for JSON, JSONC (JSON with comments), and JSON5.
Recommended rules:
* `no-duplicate-keys`
> Disallow duplicate keys in JSON objects
* `no-empty-keys`
> Disallow empty keys in JSON objects
> note: package-lock.json uses empty keys intentionally
1. `npm run lint` in ui/apps/platform to see that 2 .json files contain comments
1. After `npm install`, restart Visual Studio Code, and …
=> chore(ui): Add ESLint plugin for json files in ui

image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml, image/templates/helm/stackrox-secured-cluster/templates/admission-controller.yaml, image/templates/helm/stackrox-secured-cluster/values-public.yaml.example, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/admission-control.test.yaml
Adds support for custom namespace selectors.
Added unit test for current config and custom configuration.
=> feat(helm): support override admission control namespace selector

pkg/centralsensor/caps_list.go, sensor/kubernetes/certrefresh/certificates/certificates.go, sensor/kubernetes/certrefresh/certificates/certificates_test.go, sensor/kubernetes/certrefresh/certrepo/service_certificates_repository.go, sensor/kubernetes/certrefresh/localscanner/certificate_requester.go, sensor/kubernetes/certrefresh/localscanner_tls_issuer.go, sensor/kubernetes/certrefresh/securedcluster/certificate_requester.go, sensor/kubernetes/certrefresh/securedcluster/certificate_requester_test.go, sensor/kubernetes/certrefresh/securedcluster_tls_issuer.go, sensor/kubernetes/certrefresh/securedcluster_tls_issuer_test.go, sensor/kubernetes/certrefresh/tls_issuer_common.go, sensor/kubernetes/sensor/sensor.go
This PR adds Sensor-side handling for the gRPC endpoint implemented here: 
* https://github.com/stackrox/stackrox/pull/12740
It was preceded by several refactor PRs:
* https://github.com/stackrox/stackrox/pull/12825
* https://github.com/stackrox/stackrox/pull/13023
* https://github.com/stackrox/stackrox/pull/13000
* https://github.com/stackrox/stackrox/pull/13260
The new Sensor component (`SecuredClusterTLSIssuer`) checks for Secured Cluster TLS certificates at startup. If they’re missing or nearing expiration, it automatically requests new ones.
Additionally, it also schedules a certificate refresh when the certificates are at ~50%, so there is little risk that the certificates will become stale if Sensor never restarts in the last months of certificate validity.
The added components …
=> ROX-25948: Secured Clusters certificate refresher

ui/apps/platform/cypress/helpers/dndSimulatorDataTransfer.js, ui/apps/platform/eslint.config.js, ui/apps/platform/src/Components/CompoundSearchFilter/types.ts, ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx, ui/apps/platform/src/Containers/AccessControl/PermissionSets/ResourceDescription.tsx, ui/apps/platform/src/Containers/Clusters/ClusterPage.tsx, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesTable.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx, ui/apps/platform/src/Containers/Compliance/List/Table.js, ui/apps/platform/src/Containers/Compliance/widgets/VerticalBarChart.js, ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigActionDropdown.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ScanConfigActionsColumn.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/ViewScanConfigDetail.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ScanConfigClustersTable.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/AcscsEmailIntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ExternalBackupIntegrations/S3CompatibleIntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/MicrosoftSentinelForm.tsx, ui/apps/platform/src/Containers/MainPage/Header/OrchestratorComponentsToggle.tsx, ui/apps/platform/src/Containers/MainPage/Header/UserMenu.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/DefaultFakeGroup.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/ExternalGroupSideBar.tsx, ui/apps/platform/src/Containers/Risk/RiskDetails.js, ui/apps/platform/src/Containers/SystemHealth/DiagnosticBundle/DiagnosticBundleForm.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/ExceptionRequestModal/ExceptionScopeField.tsx, ui/apps/platform/src/hooks/useRestMutation.test.ts, ui/apps/platform/src/utils/responseErrorUtils.ts
Follow up upgrades in #13164
Especially delete comments that are copy-paste of integration forms by contributors from other teams to reduce potential confusion.
Find in Files `eslint-disable` after deletions
* ui/apps/platform/cypress folder has 2 results in 2 files
* ui/apps/platform/src folder has 210 results in 154 files
1. `npm run lint`
=> chore(ui): Delete unused ESLint disable directives

.github/workflows/scanner-mapping-update.yaml, scanner/image/scanner/download-mappings.sh
Future proofing: follow redirects for Red Hat security data, and also ensure the files are not empty.
no
Ported this over into the Scanner CI image and modified the first URL to point to `https://access.redhat.com/security/data/metrics/repository-to-cpe.json` and removed the `L` flag. Found the following:
```
Downloading https://access.redhat.com/security/data/metrics/repository-to-cpe.json > repomapping/repository-to-cpe.json
repomapping/repository-to-cpe.json is empty
```
Re-added the L flag and got:
```
Downloading https://access.redhat.com/security/data/metrics/repository-to-cpe.json > repomapping/repository-to-cpe.json
Downloading https://security.access.redhat.com/data/metrics/container-name-repos-map.json > repomapping/container-name-repos-map.json
Done
total 2.4M
-rw-r--r--. 1 …
```
=> ROX-26929: handle security data redirects and empty files

.github/workflows/scanner-mapping-update.yaml, scanner/config.yaml.sample, scanner/config/config.go, scanner/image/scanner/download-mappings.sh, scanner/updater/rhel/doc.go, scanner/updater/rhel/updaterset.go
Cherry-pick changed Red Hat security data URL. This will fix issues where `curl` does not follow redirects.
no
cherry-pick
=> chore(scanner): update Red Hat sec data location (#12564)

ui/yarn.lock
Upgrades `cross-spawn` to `7.0.5` in `4.5`
```
yarn list output before:
├─ cross-spawn@7.0.3
├─ execa@1.0.0
│  └─ cross-spawn@6.0.5
└─ npm-run-all@4.1.5
└─ cross-spawn@6.0.5
```
```
yarn list output after:
└─ cross-spawn@7.0.5
```
The following are steps I took:
1. `yarn upgrade cross-spawn@7.0.5`
2. Modifying the `yarn.lock` to add `, cross-spawn@^7.0.0, cross-spawn@^7.0.2, cross-spawn@^7.0.3` to the `cross-spawn@7.0.5` block
3. Removing the `cross-spawn@^6.0.0, cross-spawn@^6.0.5: block`
4. Modifying the mentions of `cross-spawn "^6.0.0"` in the `execa@^1.0.0` block and `cross-spawn "^6.0.5"` in the `npm-run-all@^4.1.5` block to `cross-spawn@7.0.5`
5. `yarn install` (just to make sure everything is good)
Verify CI run
=> fix(ui): Upgrade cross-spawn to 7.0.5

sensor/common/clusterentities/metrics/metrics.go, sensor/common/clusterentities/store.go, sensor/common/clusterentities/store_test.go
When sensor transitions from offline to online it [calls Stop on the listener](https://github.com/stackrox/stackrox/blob/e8a3a75590d7c33236fbf7242abb4470cf149578/sensor/kubernetes/eventpipeline/pipeline_impl.go#L131), whereas [the listener wipes all in-memory stores](https://github.com/stackrox/stackrox/blob/9d21f921131b849948d0dc8cf0000732033e16cc/sensor/kubernetes/listener/listener_impl.go#L97). This may lead into problems where connection observed during offline will not be enriched in the following scenario:
- Collector reports a flow and Sensor stores it in memory
- enricher will wait for the tick (30s currently)
- before the tick occurs, we go offline
- next, we go online - this wipes all in-memory stores
- enricher tick finally happens
- more than [2 …
=> ROX-25990: Add history for containerIDs in Sensor

ui/apps/platform/cypress/integration/networkGraph/networkGraph.test.js
Fixes a logical inconsistency that is a possible source of test flakes in the 4.6 release CI. See comments here https://redhat-internal.slack.com/archives/CMH5M8MHN/p1731713048648539. This is potentially related to https://github.com/stackrox/stackrox/pull/12752 just by virtue of being the most recent change in this section, but it does not explain why these tests have not been failing until the past week.
Details of the fix inline.
CI
=> fix(ui): Update NG test assertion for accuracy

.github/actions/junit2jira/action.yaml, scripts/ci/lib.sh
Bump junit2jira to `v0.0.22` - that includes a fix for self-linking Jira tickets.
- no test modifications
Will check CI execution
=> chore(CI): Bump junit2jira to v0.0.22

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approvedFalsePositivesTable.test.ts
Fixes a test flake in the Exception Management tests that currently will occur 100% of the time on November 11, and almost only on November 11.
Why?
The failing test has a section where it intercepts the Name of an Exception Request, finds the row in the table, and then clicks on the table cell containing a link to the Exception Request detail page. Once on the page, the test checks to ensure the `h1` tag contains the same text as the Name of the request.
A request name is automatically generated as follows:
1. Two characters based on the requestors user name followed by a dash
2. The date of the request in YYMMDD format followed by a dash
3. A digit representing the number of requests that exist in the system, which is `9` in the case of these CI runs.
The problem comes from the MMDD …
=> ROX-26944: UI e2e test fix for November 11 bug

ui/apps/platform/cypress/fixtures/vulnerabilities/workloadCves/getImageCVEList.json, ui/apps/platform/cypress/integration/exceptionConfiguration/vulnerabilitiesExceptionConfig.test.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
**Easier to review with "Hide whitespace" enabled**
Mocks the CVE list when visiting the Workload CVE page during integration tests in order to avoid flakes when Scanner has not completed a single image scan at the point that the Exception Configuration test suite runs. The functionality under test does not depend on true e2e CVE responses.
Local Cypress run.
CI.
=> ROX-21658: Mock CVE response in exception config test

ui/apps/platform/package-lock.json
As titled, bumps the version used by react-router v5. This removes the immediate cve finding reported by `npm audit`. The `path-to-regexp` dependency will be dropped altogether once the migration to react-router v6 is complete. 
Smoke test navigating throughout pages in the application.
Changes from 1.7.0 - 1.9.0 are limited to minor regexp support enhancements:
https://github.com/pillarjs/path-to-regexp/releases/tag/v0.1.8
https://github.com/pillarjs/path-to-regexp/releases/tag/v0.1.9
=> chore(ui): Update path-to-regexp ui dependency

sensor/upgrader/preflight/access.go
In one place in the like, we use `_`  instead of `-`. But at least we direct the users to the correct page. The users would need to scroll to the section at the bottom. With this fix, they will be redirected to the correct section.
- I clicked the link
=> fix(link): URL to upgrader troubleshooting docs

qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
The test in question was reenabled when some additional logic was added to prevent port 0 from being chosen, however, this is a deeper UDP issue that we are not yet able to fully solve. Until we have time to look into it, there's no point on having this flaky test around.
A single line is being restore from #12332, don't think validation outside CI is needed.
=> chore(tests): disable flaky network flow test

ui/apps/platform/src/Containers/Policies/PolicyPage.tsx
Prevents a cloned EXTERNAL policy from being marked as EXTERNAL when saved. Since a cloned policy only exists locally in central, without a external sync source, it should be marked INTERNAL instead.
=> ROX-27008: Prevent cloned policies from being marked as external

central/blob/datastore/datastore_test.go, central/complianceoperator/v2/report/datastore/datastore.go, central/postgres/compliance_report_pruning_test.go, central/postgres/pruning.go, central/pruning/pruning.go, central/reports/common/blob.go
Prune compliance reports and blobs using the same criteria as VM.
Finished reports (delivered, generated, or failed) outside of the retention window will be deleted unless:
- The report is the last report (the report is the only report of that type for that given scan configuration).
- The report is not finished (the report is not in the delivered, generated, or failed state).
- The report has a blob (if there is a blob for a given report, we do not delete the report).
- The report is inside the retention window (the report has not expired).
Blobs are pruned if:
- The blob is outside of the retention window (the report has expired).
- The blob is bigger than the allowed space left (report-size > total-allowed-space - used-space).
=> ROX-27007: Prune compliance reports and blobs

central/complianceoperator/v2/report/manager/manager_impl.go, central/complianceoperator/v2/report/manager/manager_test.go, central/complianceoperator/v2/scanconfigurations/service/service_impl.go, central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go
On demand reports are owned by the requester and not by the owner of the scan configuration with which they are associated.
=> ROX-27061: On demand reports are owned by the requester

ui/apps/platform/cypress/helpers/request.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/hooks/useHasGenerateSBOMAbility.ts
As titled. Only adds the button, does not add functionality.
Visit an image single page either without the `ROX_SBOM_GENERATION` feature flag enabled, or without "READ_WRITE" access to "Image":
Visit with both, but without Scanner V4 enabled:
Hovering or tab-navigating to the button displays a tooltip explaining why the button is disabled:
Visit with both and with Scanner V4 enabled. No tooltip is rendered on the button.
=> ROX-26866: Add button to trigger SBOM generation on Image page

.github/workflows/scanner-versioned-definitions-update.yaml
This Thanksgiving, NVD has been serving up 503s instead of turkey. Let's switch to the legacy JSON feeds so everyone can enjoy their holidays.
no
I ran it manually earlier: https://github.com/stackrox/stackrox/actions/runs/12040515984
=> chore: switch to NVD feeds

qa-tests-backend/src/test/groovy/ReconciliationTest.groovy
Alert showed up but after the test had failed. Increasing timeout should fix it.
Test failed at 13:37:40
```
13:37:40 | ERROR | ReconciliationTest        | Helpers                   | An exception occurred in test
org.spockframework.runtime.ConditionNotSatisfiedError: Condition not satisfied:
violations.size() == 1
|          |      |
[]         0      false 
```
But alert showed up at 13:38:21
```
central_active=# select policy_name, deployment_name, time from alerts where policy_name = 'Secure Shell (ssh) Port Exposed';
policy_name           | deployment_name |            time            
---------------------------------+-----------------+----------------------------
Secure Shell (ssh) Port Exposed | testing123      | 2024-08-01 13:38:21.955239
(1 row) 
```
CI is enough
=> ROX-25576: Try fixing ReconciliationTest by increasing timeout

.github/workflows/scanner-versioned-definitions-update.yaml
Followup of https://github.com/stackrox/stackrox/pull/13437. I thought that would do the trick, but I was wrong. Getting this in now to ensure people can enjoy the holiday.
no
no
=> chore(scanner): use nvd feeds

central/externalbackups/plugins/gcs/gcs.go, central/externalbackups/plugins/s3/s3.go, central/externalbackups/plugins/s3compatible/s3compatible.go
In ROX-26945 we observed a test flake where we hit the timeout.
```
GCS backup: creating test object "153cdf82-0569-4df0-9359-cb2eb7bf5b22/stackrox-backup-test-2024-11-11-02-45-35"
in bucket "stackrox-ci-qa-backup-tests": closing GCS writer: context deadline exceeded
```
This PR increases the test timeout from 5 to 9 seconds, which will hopefully make such flakes less likely. Note that we should stay under the 10 second timeout that is enforced by the UI.
I also refactored the contexts to pass them down from a higher level function.
change me!
=> ROX-26945: increase backup test timeouts

.github/renovate.json5
Please review this change per commits. I provided commit message in each.
No automated testing.
Ran `renovate-config-validator` and it said all's ok.
=> chore: Improve Renovate behavior

ui/apps/platform/cypress/helpers/tableHelpers.ts, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js, ui/apps/platform/src/Containers/MainPage/Banners/Banners.tsx, ui/apps/platform/src/Containers/SystemHealth/DashboardPage.js, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageOverviewTable.tsx, ui/apps/platform/src/hooks/useIsScannerV4Enabled.ts
As titled, adds the "Generate SBOM" menu item to images on the Workload CVE overview page.
Visit without the ROX_SBOM_GENERATION feature flag enabled, or without "READ_WRITE" access to "Image":
Visit with both, but without Scanner V4 enabled. In this case, the menu option is disabled and a description tells why.
Visit with both and with Scanner V4 enabled.
=> ROX-26867: Add Generate SBOM menu item to image list page

ui/apps/platform/src/utils/pdfUtils.js
Sanitize the column values so HTML doesn't get accidentally rendered when creating PDFs.
N/A
No automated tests needed.
=> fix(ui): Sanitize column values when rendering PDFs

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.ts, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/GenerateSbomModal.tsx
Adds the "Generate SBOM" modal and displays it via the Workload CVE Image list and Image single pages.
View the Generate SBOM modal via the Workload CVE Image list menu item or the Image CVE single page button:
The "Generate SBOM" button is not functional as this does not currently connect to an API request. Simulated API states below.
Loading:
Success (this will trigger the native browser download):
Error:
Open the modal via the Image single page:
Verify a11y:
=> ROX-26868: Add SBOM generation modal

ui/apps/platform/cypress/integration/violations/violations.test.js
The test is constantly failing since: **2024-11-27**
Jira: https://issues.redhat.com/browse/ROX-27198
The first fail is with the following commit: https://github.com/stackrox/stackrox/commit/8ddf9e3be8eb56356444443874baffbdbb79ab01
Link to Prow: https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-master-merge-gke-ui-e2e-tests?buildId=1861949054968139776
I'll let CI check it.
=> chore(CI): Disable failing UI test for Violations

central/compliance/checks/common/rbac.go, central/compliance/checks/nist80053/check_ac_14/check.go, central/rbac/service/get_subject.go, central/sensor/service/pipeline/rolebindings/pipeline_test.go, pkg/k8srbac/evaluator_impl.go, pkg/k8srbac/subjects.go, pkg/k8srbac/subjects_test.go, qa-tests-backend/src/test/groovy/K8sRbacTest.groovy
We have failing tests on GKE. The difference comes from non-namespaced subjects.
With GKE - Kubernetes version`v1.31.2-gke.1384000`, we have two role bindings. One is normal (namespace) role binding, and the other is cluster (non-namespace) role binding.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: konnectivity-server-leases
namespace: kube-system
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: leases-writer
subjects:
- apiGroup: rbac.authorization.k8s.io
kind: User
name: system:konnectivity-server
namespace: kube-system
```
and
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: system:konnectivity-server
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: system:auth-delegator
subjects:
- …
```
=> ROX-27053: Fix subjects handling for user and group kind

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/GenerateSbomModal.tsx, ui/apps/platform/src/hooks/useAnalytics.ts
As titled.
Generate an SBOM and view the event payload being sent via the Network tab.
=> ROX-27187: Add telemetry for UI initiated SBOM generation

ui/apps/platform/public/index.html, ui/apps/platform/src/Components/GroupedTabs.js, ui/apps/platform/src/Components/PageHeader/PageHeader.js, ui/apps/platform/src/Components/animations/SidePanelAnimatedArea.tsx, ui/apps/platform/src/Containers/Clusters/Components/HelmIndicator.tsx, ui/apps/platform/src/Containers/Clusters/Components/OperatorIndicator.tsx, ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx, ui/apps/platform/src/Containers/ConfigManagement/Entity/Page.js, ui/apps/platform/src/Containers/ConfigManagement/List/Page.js, ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/Containers/MainPage/Header/ThemeToggleButton.tsx, ui/apps/platform/src/Containers/NetworkGraph/common/NetworkPolicies.tsx, ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesYAML.tsx, ui/apps/platform/src/Containers/ThemeProvider.js, ui/apps/platform/src/Containers/VulnMgmt/Entity/RelatedEntitiesSideList.tsx, ui/apps/platform/src/Containers/VulnMgmt/Entity/TileList.tsx, ui/apps/platform/src/Containers/VulnMgmt/Entity/WorkflowEntityPage.js, ui/apps/platform/src/Containers/VulnMgmt/Entity/WorkflowEntityPageLayout.js, ui/apps/platform/src/Containers/VulnMgmt/EntityBreadCrumbs.tsx, ui/apps/platform/src/Containers/VulnMgmt/List/WorkflowListPageLayout.js, ui/apps/platform/src/index.tsx
On one side of the coin, some classic colors are used only for dark theme that was turned off on 2023-06-10 in #6432
On other side of the coin, accessibility guidelines are easier to reinforce via rules with as much PatternFly as possible, and even then, rarely  `className` or `color` props and usually semantic color with `variant` prop:
* 1.4.1 Use of color
* 1.4.3 Contrast (Minimum)
Find in Files
* `useTheme()` has 18 results in 18 files.
* `isDarkMode` has 76 results in 22 files.
* `bg-base-0` has 7 results in 6 files before changes, but none after changes.
* `bg-primary-100` has 8 results in 7 files before changes, but 6 results in 6 files after changes.
* `bg-primary-300` has 3 results in 2 files before changes, but 2 results in 1 file after changes.
1. Delete `isDarkMode` …
=> ROX-27186: Delete conditional code for classic dark theme

pkg/logging/logging_test.go
A sync should be called on a logger before testing to ensure the data is flushed and rotation is triggered.
Unit test.
=> fix: flaky log rotation test

qa-tests-backend/src/test/groovy/K8sRbacTest.groovy
During the CI improvements meeting, we identified that this test is constantly failing for OSD on AWS.
This PR will disable this test until it is fixed.
**For reviewer**
- it is important that test is skipped for `osd-aws-qa-e2e-tests`
- but it runs for other `*-qa-e2e-tests`
I will let the CI pipeline validate the changes.
It's important that the `osd-aws` test is triggered.
=> ROX-25270: Disable K8sRbacTest that fails for OSD on AWS

ui/apps/platform/package-lock.json, ui/apps/platform/package.json
Cypress has either minor or patch update about every other week.
This is our first update during 4.7 effort.
https://docs.cypress.io/app/references/changelog#13-16-0
* Fixed an issue where some JS assets were not properly getting sourcemaps included with the vite dev server if they had a cache busting query parameter in the URL. Fixed some scenarios to ensure that the sourcemaps that were included by the vite dev server were inlined.
https://docs.cypress.io/app/references/changelog#13-15-2
* Fixed an issue where the Cypress runner could hang in `after` or `afterEach` hooks that run Cypress commands after a page load timeout error occurs.
* Updated `mobx` from 5.15.4 to 6.13.5 and `mobx-react` from 6.1.8 to 9.1.1.
* Updated `@cypress/request` from 3.0.4 to 3.0.6. …
=> chore(e2e): Update cypress 13.16.1 devDependencies in ui

ui/apps/platform/cypress/fixtures/vulnerabilities/workloadCves/imageWithMultipleCves.json, ui/apps/platform/cypress/fixtures/vulnerabilities/workloadCves/multipleCvesForImage.json, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveListExceptionFlow.test.js
Days since apollo-client's normalized cache has caused* an obscure and time consuming issue that was difficult to track down: ~45~ **0**
This fixes a test flake in Workload CVE deferral flows where a table row element was not accessible when used with a chained `.find()` Cypress call. I believe the source of this issue is [this PR](https://github.com/stackrox/stackrox/pull/13231) that I merged less than a month ago. That PR mocks the CVE list response for an image for this test suite. This produces the familiar Cypress error:
```
Timed out retrying after 4000ms: `cy.find()` failed because the page updated as a result of 
this command, but you tried to continue the command chain. 
The subject is no longer attached to the DOM, and Cypress cannot requery 
the page after commands such as …
```
=> fix(ui): Fix e2e test flake due to apollo cache misses

migrator/postgreshelper/utils_test.go, pkg/postgres/pgadmin/admin_utils_test.go
Removing the check to see if the connection was terminated.  I am doing that for 2 reasons:
1. That check is racy because the underlying pool could have reconnected to the new test prior to the call to `Ping` in the test.
2. The check is pointless.  If the connection was not dropped the preceding calls to `CreateDB` would fail.
CI is sufficient as it is purely a test fix.
=> ROX-26570: fix postgres test race

central/views/imagecve/db_response.go, central/views/imagecve/view_test.go, central/views/nodecve/db_response.go, pkg/search/postgres/select.go, pkg/search/postgres/select_query_test.go
The search framework sometimes adds columns used in order by and group by clauses to the select part of the query. This is necessary to make a valid query as per SQL spec. For the destination struct used to consume results of such queries, we currently need to guess what extra columns will be added by the search framework and create fields for them in destination struct. In the imageResponse example below, the users of the struct are only interested in the ImageID values and use the other fields just for sorting the IDs. 
```
type imageResponse struct {	
ImageID string `db:"image_sha"`
// Following are supported sort options.	
ImageFullName   string     `db:"image"`	
OperatingSystem string     `db:"image_os"`	
ScanTime        *time.Time `db:"image_scan_time"`
}
```
This can be avoided by …
=> ROX-27042: Allow selecting columns not present in destination struct

qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
Despite bumping the timeout values in #13446, we have seen another deadline exceeded error in CI runs. This PR adds a retry on the test level, similar to what we do for the notifier tests.
CI
=> ROX-27226: add retry to backup qa tests

Makefile, tools/local-sensor/scripts/local-sensor.sh
Local-sensor is used in Sensor integration tests in CI. It would be useful to make it print debug logs by default, so that an analysis of potential flakes is faster.
Nothing - running existing tests should be enough
On CI:
- See [the logs from the run of ` gke-sensor-integration-tests` in CI](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/13533/pull-ci-stackrox-stackrox-master-gke-sensor-integration-tests/1866039770749079552)
- [Direct link to the raw integration test output](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/stackrox_stackrox/13533/pull-ci-stackrox-stackrox-master-gke-sensor-integration-tests/1866039770749079552/artifacts/gke-sensor-integration-tests/stackrox-stackrox-e2e-test/build-log.tx …
=> ROX-27268: Run local-sensor in CI with debug logs by default

CHANGELOG.md, Makefile, image/rhel/Dockerfile, image/rhel/README.md, image/rhel/konflux.Dockerfile, image/templates/helm/shared/templates/02-scanner-06-deployment.yaml.htpl, image/templates/helm/shared/templates/02-scanner-v4-07-db-deployment.yaml, image/templates/helm/shared/templates/02-scanner-v4-07-indexer-deployment.yaml, image/templates/helm/shared/templates/_certrefresh.tpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, image/templates/helm/stackrox-secured-cluster/templates/admission-controller.yaml, image/templates/helm/stackrox-secured-cluster/templates/collector.yaml.htpl, image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl, sensor/init-tls-certs/main.go, sensor/init-tls-certs/main_test.go, tools/roxvet/analyzers/validateimports/analyzer.go
This PR introduces an init container that picks between new and legacy TLS service certificates, and provides them to the Secured Cluster deployments.
Starting with ACS 4.7, Secured Clusters will have a different naming scheme for the secrets that store TLS certificates for the services, and the previous secrets can still exist. `{service}-tls` is now `tls-cert-{service}`, e.g. `sensor-tls` is the legacy secret and `tls-cert-sensor` is the new secret.
The new secrets are created in two cases:
1. after registering a Secured Cluster using a [CRS](https://issues.redhat.com/browse/ROX-26088) token
2. when Secured Cluster certificates are refreshed (applies to both (a) CRS and (b) init bundle registered clusters)
Because of case (2b) above, there will be clusters that have both the legacy and …
=> ROX-26055: TLS certs loader init container

pkg/net/addr.go, pkg/net/endpoint.go, sensor/common/networkflow/manager/manager_impl.go, sensor/common/networkflow/manager/manager_impl_test.go, sensor/common/networkflow/manager/testing_test.go
This PR refactors part of the code but does not change the behavior.
⚠️ ⚠️⚠️All of the description below applies when the logging in Sensor is set to debug mode!
When Sensor made the decision to show something on the network graph as internal- or external entities, we produced  log lines that were roughly like this:
```
Debug: Marking incoming connection to container kube-system/fluentbit-gke from 10.68.153.85:2021 as 'Internal Entities' in the network graph.
Debug: Marking outgoing connection from container gmp-system/prometheus to 10.68.153.85:10250 as 'Internal Entities' in the network graph.
Debug: Marking outgoing connection from container kube-system/konnectivity-agent-metrics-collector to 255.255.255.255:443 as 'External Entities' in the network graph.
```
The point was to help the …
=> ROX-27233: Log reason for not showing a NetworkGraph entity

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
Another attempt at fixing this CI flake. Two attempts have been merged and yet this issue persists. It has not been reproducible other than in a single digit percentage of CI runs.
This fix simply reworks the helper to not use the `cy.wrap().find()` call chain which is throwing the error, instead using `cy.get()` on the target element directly.
Local Cypress runs:
Awaiting CI
=> ROX-27301: Rewrite Cypress test helper to remove use of `find`

central/compliance/handlers/csv.go, pkg/protocompat/time.go, pkg/protocompat/time_test.go, roxctl/central/crs/list.go, roxctl/central/initbundles/list.go, roxctl/central/initbundles/list_test.go
This PR fixes the issue with time formatting in `central init-bundles list` table output.
Made changes:
- refactor `ConvertTimestampToCSVString` to be more generic `ConvertTimestampToString`
- use `time.RFC3339Nano` as default format (behaviour should be the same to older protobuf framework)
- tweak `roxctl/central/crs/list.go` - to use `ConvertTimestampToString` which should be a bit safer with `nil`
- added tests for tabular output to capture future regressions
Test only with added unit tests.
**EDIT:** I have built `roxctl` locally and tested it. It looks good.
=> ROX-27343: Fix roxctl init-bundles list output time format

qa-tests-backend/src/test/groovy/SACTest.groovy
The test is failing `~5 times a week` since `2024-10-23`. This PR is disabling one of the test cases.
I'll let CI run and check that the disabled case is not executed anymore.
=> ROX-26729: Disable SAC Verify Search test for searchImagesToken

qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
This PR disabled `DefaultPoliciesTest` -> `Verify that built-in services don't trigger unexpected alerts` on `aks` platform.
The test has been constantly failing since `2024-12-09`. At that point, `aks` received an update to K8S API `v1.30`
I'll let CI validate it.
It is important to trigger tests on `aks`.
=> ROX-27302: Disable one of DefaultPoliciesTest tests on AKS

ui/apps/platform/cypress/helpers/tableHelpers.ts, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.ts
This adds test cases to cover the scenario of a customer issue where the CVE count on the Image Detail page fluctuated when applying sorts and pagination. This was observed on a screenshare call but we have not been able to reproduce locally.
This test runs a variety of similar scenarios in order to attempt to catch this in many CI runs. (Additionally, it doesn't hurt to have more coverage here.)
change me!
=> ROX-27344: Add test to verify consistent image CVE counts

central/image/service/http_handler.go, central/image/service/http_handler_test.go, central/main.go, pkg/env/image_scan.go
This PR adds
-  http handler to get sboms
- call enricher using request params to generate image metadata and index report
- [X ] added unit tests
Manually tested the chnages by making api call to handler using postman
=> ROX-24540: Add custom route to get sbom

pkg/scannerv4/mappers/mappers.go, pkg/scannerv4/mappers/mappers_test.go
Sort vulnerability values per package by their severity, and scores on ties. The main goal is to reduce flapping of results in Central if multiple CVEs with the same name are returned for the same package, as Central will pick up the first one per package.
Motivation for this comes from the RHSA flapping issue observed in `4.6.0`. This is not a fix, but reduces the blast radius significantly as flapping will only occur if different severity exist in different images, or different packages in the same image, rather than every time a RHSA is associated with multilpe CVEs.
```
podman run -e POSTGRESQL_USER=$(whoami) -e POSTGRESQL_DATABASE=scanner -e POSTGRESQL_PASSWORD=$(cat /proc/self/loginuid) -p 5432:5432 registry.redhat.io/rhel8/postgresql-13
```
Then update `database:`  entries (both …
=> fix(scanner): Order vulns per package by severity

image/templates/helm/stackrox-central/config/centraldb/postgresql.conf.default
It turns out tabs in the configuration are causing an annoying inconvenience. The yaml renderer output for files with tabs ends up being a mess of all lines merged together with the new line character in between. This makes manual configuration harder, and since the tabs are not essential, get rid of them.
Not validated yet.
=> ROX-25643: Remove tabs from postgresql conf

central/globaldb/v2backuprestore/manager/manager.go
To debug a restore which has generated an error additional logs were necessary. roxctl does not print all errors. 
For example, I've run into an error, that external databases are not supported for imports, but did not received an error message nor Central printed the according error in its logs.
=> chore: Add logging to backup restore in Central

central/scanner/handler_test.go, pkg/grpc/marshaler_test.go, pkg/grpc/server_ratelimit_test.go, pkg/grpc/server_test.go, pkg/metrics/server_test.go, pkg/testutils/http.go, tests/http_to_https_test.go
**UPDATE - 2024-12-13**
- port range is changed from 10k to 30k - comment is provided in the code for more info
- all client closes should be safe
- check for free port is extended to check on IPv4 and IPv6 - we don't know from within the `GetFreePort` function how it will be used by the caller. To ensure we don't have a miss, we are checking on both IPv-s
- `getFreePort` from metrics tests is removed and replaced with implementation in `testutils.GetFreeTestPort`
**Original Description**
There are two problems that this PR is trying to address:
- we have extensive reusing of the same port across multiple tests
- we are not closing connections cleanly in our tests
After some investigation, the conclusion is that the `FIN_WAIT` state is piled because of the not properly closed connection …
=> ROX-22816: Fix issues with port bind in unit tests

ui/apps/platform/src/Containers/MainPage/AsyncComponent.tsx, ui/apps/platform/src/Containers/MainPage/Body.tsx
Adds the ability to pass props or wrap top level page components in preparation for the Workload CVE/Platform CVE split.
Smoke test of Workload CVE page and other app pages.
CI
=> ROX-27272: Pass props/context to Workload CVE page component

.github/workflows/scanner-offline-bundle-update.yaml, .github/workflows/scanner-versioned-definitions-update.yaml
A step like this:
```
- name: Create matrix
id: output-matrix
run: |
EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
echo "matrix<<$EOF" >> "$GITHUB_OUTPUT"
.github/workflows/scripts/scanner-offline-bundle-matrix.sh | tee -a "$GITHUB_OUTPUT"
echo "$EOF" >> "$GITHUB_OUTPUT"
```
Does not fail even if `scanner-offline-bundle-matrix.sh` fails. I believe it's because GH actions' default bash flags does not contain `pipefail`, and `tee` is OK if stdin is empty. The matrix job will fail expecting a valid JSON, [see example](https://github.com/stackrox/stackrox/actions/runs/12272953984/job/34242763300).
Testing with `pr-update-scanner-vulns`.
Testing with `pr-update-scanner-vulns`.
=> fix(scanner): Add pipefail to matrix steps

qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
This test is racy.  The test is running on a live environment that is reaching a state.  It tries to get all the violations and then subsequently call counts of alerts.  Then it tries to verify the counts match the number of violations.  That is racy on a running environment.  More violations could be processed between the calls resulting in numbers that differ.  If we desire such a test it should live in the datastore or searcher tests.  Not an e2e test on a running environment where the number of results can change between calls.
CI
=> ROX-18725: flaky policy test

central/sensor/service/connection/connection_impl.go, central/sensor/service/pipeline/nodeindex/pipeline.go, central/sensor/service/pipeline/nodeinventory/pipeline.go, central/sensor/service/pipeline/nodeinventory/pipeline_test.go, central/sensor/service/pipeline/utils.go, pkg/metrics/op_string.go, pkg/metrics/operations.go, sensor/common/compliance/node_inventory_handler_impl.go
For NodeInventories and NodeIndexes (NodeReports) sent from Sensor to Central, Central will no longer require the `ResourceAction_UNSET_ACTION_RESOURCE` to be used. Instead, it will accept all but `ResourceAction_REMOVE_RESOURCE`.
See ticket description for details about backwards-compatibility.
This shows that:
- UNSET actions still work in Central
- UNSET action is no longer changed to CREATE  in metrics   
```
rox_central_resource_processed_count{Operation="Add",Resource="Alert"} 8
rox_central_resource_processed_count{Operation="Add",Resource="Deployment"} 7
rox_central_resource_processed_count{Operation="Add",Resource="Pod"} 24
rox_central_resource_processed_count{Operation="Add",Resource="ProcessIndicator"} 4676
rox_central_resource_processed_count{Operation="Remove",Resource="Alert"} …
```
=> ROX-27415: Abandon UNSET action for NodeInventory and NodeIndex

ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCveViewContext.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useWorkloadCveViewContext.ts
Adds a React.Context at the top level of the WorkloadCvePage that will be used to customize values specific to either "User" workloads or "Platform" workloads.
This context will be provided at the route level and passed via props to the context provider.
Initial test - verify that the passed page title continues to display correctly to the WorkloadCvePage:
=> ROX-27390: Add Context to Workload CVEs page for view customization

central/sensor/service/connection/sensorevents.go
If Central receives NodeInventory and NodeIndex (IndexReport) messages in parallel for the same node...
...the message that arrives later will get deduped. 
This is bad for many reasons:
- No ACK can be sent back to Compliance and it will retry forever
- Switching from v2 to v4 node scanning without restarting Central may never work.
This change puts all Node, NodeInventory, and IndexReport into single worker queue. This shall prevent race condition if multiple events of those three kinds arrive very close to each other. The code in the pipelines is not bullet-proof regarding tight race conditions (that was a decision when working on Node scanning v2), because making it so, would require adding more complexity to it. Those situations can be prevented by using single worker for those type …
=> ROX-27414: Prevent deduping Node Index in Central

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx
Instead of a hard coded "Workload CVEs", reads the page title and breadcrumb navigation link string from the page context.
Navigate through Workload CVE pages and ensure the page title and breadcrumb link continue to read "Workload CVEs".
=> ROX-27391: Update Workload CVE page title with dynamic string

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/CVEsTable.tsx
Discussed with Mansur via chat.
Omit **score** although it is not strictly redundant with **Scoring System** in CVSS and EPSS.
1. Vulnerabilities has table column headings:
* **CVSS** as majority
* **CVSS score** as minority of one (see Analysis)
2. To include **score** consistently would increase column width, especially:
* NVD CVSS
* Top CVSS
CVEsTable.tsx file renders **CVSS score** on cluster page.
* One side of coin:
Because there are multiple CVEsTable.tsx file, fewer (only one) pages are affected than I first thought.
* Other side of coin:
Google doc of PatternFly table column headings has only one occurrence.
Does not affect integration tests.
Replace **CVSS score** with **CVSS**.
Thankfully the table does not have managed columns.
Lint rule reports inconsistent text of …
=> ROX-27422: Replace CVSS score with CVSS for cluster in Platform CVEs

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx
Found unusual `className="pf-v5-u-p-md"` prop while searching for something else.
It has no effect on layout.
Even if it did, it seems superseded by `ExpandableRowContent` element that provides its layout.
Delete it!
main.js 0 = 4614730 - 4614730
total -50 = 11562726 - 11562776
files 0 = 178 - 178
1. Visit /main/workload-cves click a vulnerability, and then expand an image row.
* See same layout before and after change.
2. Click **Deployments** and then expand a deployment row.
* See same layout before and after change.
=> chore(ui): Delete unneeded padding in component subtables

central/complianceoperator/v2/report/manager/manager_impl.go, central/complianceoperator/v2/report/manager/manager_test.go
If there's an a running scan watcher that has on demand reports associated with it, we need to remove the scan config id on error. Otherwise we won't be able to request more on demand reports for that scan config without restarting central.
They way I reproduce this problem:
- Deploy ACS with LOGLEVEL=debug
- Create a scan schedule without notifiers
- Wait for the Scan to finish (checking central logs). Once it's finished if they are not notifiers configured they will be no snapshots created.
- Wait until CO send an extra update for the scan (after is finished). This will trigger an unnecessary scan watcher because no snapshots were created.
- Request a download.
- Observe the request for download is in the `Waiting` state.
- After a while the watcher should timeout but the request never …
=> fix(report): Remove scanConfig from runningReportConfigs on error

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approvedDeferralsTable.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approvedFalsePositivesTable.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/deniedRequestsTable.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/general.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/pendingRequestsTable.test.ts, ui/apps/platform/src/Components/CompoundSearchFilter/attributes/vulnerabilityRequests.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/searchFilterConfig.ts, ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx
Updates the Exception Management pages to use the new advanced filters bar and creating consistency with search on the rest of the VM pages.
Additionally this paves the way to:
- Delete the old search bar components
- Delete the ROX_ADVANCED_FILTERS feature flag and any dead code it creates
Note that this does not fix the following issues, some of which may require work on the BE as well:
1. Exception based searches do not return autocomplete results (error due to "VULN_REQUEST" not being implemented)
2. CVE and Image autocomplete requests do not seem to be able to scope to "Request State"
3. Substring search matches do not work, all search values must be a string prefix
4. Image name search does not work at all, search results are never filtered
Visit the tabs under Exception Management …
=> chore(ui): Switch to advanced filter bar for exception mgmt

central/hash/manager/deduper.go, central/hash/manager/deduper_test.go
This is a _necessary_ change to fix the issue of NodeIndex messages being deduped, but it may not be the _sufficient_ one. 
The _sufficient_ set of fixes should include also:
- https://github.com/stackrox/stackrox/pull/13605
- https://github.com/stackrox/stackrox/pull/13606
- https://github.com/stackrox/stackrox/pull/13640
See the ticket ROX-27414 for more background information.
Before that change the Central metrics were like this:
```
rox_central_resource_processed_count{Operation="Unset",Resource="NodeIndex"} 11
rox_central_resource_processed_count{Operation="Unset",Resource="NodeInventory"} 160
```
note that this metric counts the number of objects that reach the dedicated pipeline - here `nodeindex/pipeline.go`.
With that change the metric looks like
``` …
```
=> ROX-27414: Do not dedupe NodeIndex and NodeInvetory in Central

tests/e2e/lib.sh, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageResources.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageResources.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
Constructs a base search filter value to be used throughout queries in Workload CVE pages.
When the feature flag is off, this has no effect.
When the feature flag is on, `Platform component:true/false` will be passed to all queries in the Workload CVE section.
Note that this isn't _strictly_ required for all queries. e.g. The CVEs listed for an image will not change based on this parameter. The base search query was included in these queries just for the sake of consistency.
With a top level context of `view="user-workload"`, results will be filtered to remove platform components. Screenshots below are of staging.
Image list:
Deployment list:
CVE Single page:
Namespace view:
Autocomplete results:
With a manual override of `view="platform-workload"`, results will be inverted:
Image list: …
=> ROX-27393: Update Workload CVE pages to accept a base search filter

sensor/common/networkflow/manager/manager_impl.go, sensor/common/networkflow/metrics/metrics.go
This is a follow-up to PR #13463 ([this comment](https://github.com/stackrox/stackrox/pull/13463#discussion_r1870917867)) applying the suggestion that the code of `handleContainerNotFound` can be further optimized by reorganizing the if-clauses and returns to avoid unnecessary code nesting.
No fixes or other changes here - just reshuffling the code.
- CI must be sufficient
=> refactor: Optimize returns in `handleContainerNotFound`

central/alert/service/service_impl.go, central/processbaseline/service/service_impl.go, qa-tests-backend/src/test/groovy/Enforcement.groovy, qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy, sensor/common/detector/baseline/baseline.go
We received a flake for baseline process tests because the baseline was locked, but not synced before we've executed the violating exec into a Pod.
- Added a sleep to wait for propagation of the baseline to Sensor
- Added log statements to debug baseline sync flakes easier
If this doesn't fix the flake we must implement an API which can block until the baseline is synced. Related ticket: https://issues.redhat.com/browse/ROX-27486
=> ROX-18278: Fix baseline test flake

ui/apps/platform/src/Containers/VulnMgmt/Entity/Image/VulnMgmtImageOverview.js, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/DeploymentResourceTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCveViewContext.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameLink.tsx, ui/apps/platform/src/Containers/Vulnerabilities/utils/searchUtils.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/utils/searchUtils.tsx
Allows dynamically configuring the base URL when linking to Workload CVE pages in order to support "user" and "platform" views of this page.
Existing CI tests.
Manual testing of links in the following locations:
- Overview page CVE link
- Overview page Image link
- Overview page Deployment link
- Overview page Namespace view button
- Namespace view deployment link
- CVE page Image link
- CVE page Deployment link
- CVE page Image link in nested Deployment table
- CVE page breadcrumb link
- Image page CVE link
- Image page Deployment link via Resources tab
- Image page breadcrumb link
- Deployment page CVE link
- Deployment page Image link in nested CVE table
- Deployment page Image link via Resources tab
- Deployment page breadcrumb link
- Exception Management CVE link (hard coded to …
=> ROX-27392: workload CVE dynamic base url

ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx, ui/apps/platform/src/Containers/Clusters/ClusterDeployment.tsx, ui/apps/platform/src/Containers/SystemHealth/UsageStatistics/ShowAdministrationUsage.tsx, ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerConfiguration.tsx, ui/apps/platform/src/Containers/Violations/Details/Deployment/PortConfiguration.tsx, ui/apps/platform/src/Containers/Violations/Details/Deployment/SecurityContext.tsx, ui/apps/platform/src/messages/vulnMgmt.messages.ts
Outside of policyCriteriaDescriptors which are replaced in #13642
Quote in string is an edge case (especially for fixer) in first draft of lint rule in #13364
Also, IBM Style recommends typographical quote marks.
Although that was for double quote, start with single quote (especially because full stack developers use template literal).
Temporary lint rule reported:
* 2 occurrences of **contraction**
The integrated scanner can't find the OS
Ironically, the original text had correct punctuation, but a recent change apparently retyped the entire sentence :(
* 6 occurrences of **possession**, for example
because the alert's deployment no longer exists
https://www.patternfly.org/ux-writing/writing-for-all-audiences/#writing-for-all-abilities
> Use common contractions (for example, "it’s” and …
=> chore(ui): Replace apostrophe for contraction or possession

.github/workflows/build.yaml
For release builds we need to disable GHA builds which push into `quay.io/rhacs-eng/` and use Konflux for that instead.
This change allows more easily conditionally disable GHA builds by suppressing `RHACS_BRANDING` from the matrix in the `define-job-matrix` job.
Extracted from https://github.com/stackrox/stackrox/pull/13422 and refined.
No change to automated tests.
- Looked at the Build workflow and checked that it seems to work as before.
- Added extra labels on this PR to give a chance for anything build-related to blow up.
=> ROX-26026: Matrixize more jobs in `.github/workflow/build.yaml`

central/main.go, pkg/logging/logging_test.go
Lubmerjack logger, the log rotation wrapper we use, removes the old log files asynchronously.
The test was flaking because it didn't wait for this to happen.
This PR adds a retry loop with a sleep to ensure the file is deleted by the lumberjack goroutine.
```console
sh$ go test -count=1000 -run ^Test_withRotatingCore
PASS
ok  	github.com/stackrox/rox/pkg/logging	68.894s
```
=> ROX-27300: fix a flake in the `pkg/logger` unit test

govulncheck-allowlist.json
CI flagged GO-2024-3105, GO-2024-3106, and GO-2024-3107, which does affect upstream binaries. Ignore it for now, as there is nothing we can do without bumping our upstream version of Go (from 1.22.5 to 1.22.7 or 1.23.1).
Downstream is unaffected, as it's using 1.22.9.
No
Added `scan-go-binaries` to this PR. I expect this to come back clean.
=> chore(govulncheck): ignore GO-2024-3105,GO-2024-3106,GO-2024-3107

tests/e2e/lib.sh
Looking at the logs of a failed nightly build, I found the following:
> INFO: Fri Jan  3 02:13:00 UTC 2025: Will wait for collectors to reach a ready state in namespace stackrox
daemon set "collector" successfully rolled out
Checking readiness of collector-2mzp4
collector-2mzp4 is deemed ready
Checking readiness of collector-2nz4r
collector-2nz4r is deemed ready
Checking readiness of collector-5trq8
collector-5trq8 is deemed ready
Checking readiness of collector-788b5
collector-788b5 is deemed ready
Checking readiness of collector-7w46c
collector-7w46c is deemed ready
Checking readiness of collector-dlljx
collector-dlljx is deemed ready
Checking readiness of collector-gl5gp
collector-gl5gp is deemed ready
Checking readiness of collector-tjk65
collector-tjk65 is deemed ready
Checking …
=> fix(ci): resolve accidental fail-early when collector is not ready yet

.github/workflows/scanner-build.yaml, scripts/ci/lib.sh
Similar to https://github.com/stackrox/stackrox/pull/13694 the goal here is to make it possible to disable pushes to `quay.io/rhacs-eng/` for release builds (which will be driven by Konflux).
Unlike https://github.com/stackrox/stackrox/pull/13694 where the `.github/workflows/build.yaml` workflow is defined through branding, the `.github/workflows/scanner-build.yaml` doesn't have a notion of branding and so I felt introducing one would be too artificial given that the Scanner V4 doesn't have any conditional on the branding. Therefore, I introduce the "registry" `quay.io/stackrox-io`/`quay.io/rhacs-eng` as the matrix parameter.
This change can be reviewed by commits or in its eventual state.
Request for reviewers: an extra dimension for `build-and-push-scanner` and `push-scanner-manifests` …
=> ROX-26026: Introduce `registry` to Scanner build matrix 

govulncheck-allowlist.json
https://github.com/stackrox/stackrox/pull/13708 found this vulnerability in the AWS SDK. Running govulncheck, it was found this repository is unaffected (does not use any affected functions), so this PR adds it to the ignore list.
no
Added `scan-go-binaries` label to this PR. Expect to not see this vuln mentioned in the report.
=> chore(govulncheck): ignore GO-2022-0635

scanner/Makefile, scanner/cmd/scanner/main.go
Properly set the `version` variable by passing the proper `-ldflag` to `go build`.
Before it was setting `-ldflags` twice when building scanner, the second flag overwrote the first, leading to empty `version=""` in the scanner binary, but not affecting the vulnerability version.
Added a `-version` to print the version, for convenience.
Run before the fix:
```
$ ./bin/scanner 2>/dev/null| grep 'version":"' 
{"level":"info","host":"...":"main","version":"","build_flavor":"development","time":"2025-01-07T13:20:59-08:00","message":"starting scanner"}
pkg/metrics: 2025/01/07 13:20:59.882686 throttle.go:90: Info: gathering CPU throttle metrics from sys/fs/cgroup/cpu.stat
^C
$
```
After:
```
./bin/scanner 2>/dev/null -version …
```
=> fix(scanner): Fix -ldflags in scanner's Makefile

ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerConfiguration.tsx, ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerConfigurationDescriptionList.tsx, ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerImage.tsx, ui/apps/platform/src/Containers/Violations/Details/Deployment/DeploymentOverview.tsx, ui/apps/platform/src/types/deployment.proto.ts
Updates links on the Violations detail pane for deployments to point to the appropriate User or Platform component page when the platform component workload cve split is enabled.
Visit a Violation for a deployment in user-space and test the deployment and image links on the Details->Deployment tab.
Repeat for a Violation on a platform component deployment.
=> ROX-27276: violations platform components links

central/clusterinit/backend/backend.go, central/clusterinit/backend/backend_impl.go, central/clusterinit/backend/backend_test.go
See ROX-27212 for details.
Unit tests.
=> ROX-27212: Add a "version" identifier for CRS for future proofness

go.mod, go.sum
Backport https://github.com/stackrox/stackrox/commit/6e6095c19abee2e6213a501a5f1caa7b453e7812 from https://github.com/stackrox/stackrox/pull/13222.
=> chore(deps): bump github.com/golang-jwt/jwt/v4 from 4.5.0 to 4.5.1

.openshift-ci/begin.sh, .openshift-ci/ci_tests.py, scripts/ci/jobs/gke_scanner_v4_install_tests.py, scripts/ci/jobs/ocp_scanner_v4_install_tests.py, tests/e2e/run-scanner-v4-install.bats, tests/e2e/run-scanner-v4-install.sh
The current Scanner V4 installation tests are simply called `scanner-v4-tests`, which has brought some confusion among the team. As the team works towards creating Scanner V4 CI tests, we believe it'd make more sense to change the name of these tests to "install tests".
This is accompanied by https://github.com/openshift/release/pull/56006.
OpenShift CI is a pain to test, so may just test it live...
The OpenShift CI tests know which script to run based on the job's name. In the accompanying PR, you can see the job names changes to include "install". For example, `gke-scanner-v4-tests` --> `gke-scanner-v4-install-tests`. This is eventually converted to `gke_scanner_v4_install_tests.py` in `.openshift-ci/dispatch.sh`, which now exists due to this PR.
=> chore(ci): rename scanner-v4-tests to scanner-v4-install-tests

.tekton/basic-component-pipeline.yaml, .tekton/main-pipeline.yaml, .tekton/operator-bundle-pipeline.yaml, .tekton/scanner-v4-pipeline.yaml
There are build failures in buildah task updates.
> Failed to resolve pipeline result reference for "scanner-db-on-push-7ls5b" with error %!w(*fmt.wrapError=&{invalid pipeline result "JAVA_COMMUNITY_DEPENDENCIES": "JAVA_COMMUNITY_DEPENDENCIES" is not a named result returned by pipeline task "build-container-amd64" 0xc16b452d00}) 
E.g. see https://github.com/stackrox/scanner/pull/1745/checks?check_run_id=35291959937
That's because the corresponding java things were removed from the new version of the tasks.
- https://github.com/konflux-ci/build-definitions/blob/main/task/buildah-oci-ta/0.3/MIGRATION.md
- https://github.com/konflux-ci/build-definitions/blob/main/task/buildah-remote-oci-ta/0.3/MIGRATION.md
Here I searched for "java" (case insensitive) in the `.tekton/` directory and removed …
=> chore: Kill `Java` mentions from Konflux pipelines

.tekton/central-db-build.yaml, .tekton/main-build.yaml, .tekton/operator-build.yaml, .tekton/operator-bundle-build.yaml, .tekton/roxctl-build.yaml, .tekton/scanner-v4-build.yaml, .tekton/scanner-v4-db-build.yaml
Context: https://issues.redhat.com/browse/ROX-24530
1. Finding [central-db image built on Konflux](https://console.redhat.com/application-pipeline/ns/rh-acs-tenant/pipelinerun/central-db-on-push-kslg7): `quay.io/rhacs-eng/central-db:4.7.x-385-g4ddf2f0459-fast`
2. `docker create --name expiration-check quay.io/rhacs-eng/central-db:4.7.x-385-g4ddf2f0459-fast`
3. `docker inspect expiration-check | jq -r '.[0].Config.Labels["quay.expires-after"]'` -> `13w`
=> ROX-24530: let Konflux images expire after 13w

central/views/imagecve/view_test.go, pkg/search/postgres/common.go, pkg/search/postgres/common_test.go, pkg/search/postgres/joins.go, pkg/search/postgres/joins_test.go, pkg/search/postgres/select.go
This PR adds support for left join for search queries. The `RawQuery` syntax exposed in APIs supports `-` as a null check character. For single table queries (no joins) with `Field : -` already translate to `select * from table where field is NULL` but this was not supported when the field is in a table that is related to the root table via a joins because that would require left joins. After this PR queries with `Field : -` will translate to `select * from table1 left join table2 on table1.key1=table2.key2 where table2.field is NULL`.
Note that this PR does not add left join support to select queries. That will be done in a followup task. Current implementation will satisfy the requirement of showing inactive images with non-platform workloads.
change me!
=> ROX-27200: Support left join in searches

.tekton/operator-bundle-pipeline.yaml, scripts/ci/jobs/check-konflux-pipelines.sh
Follow-up from https://github.com/stackrox/stackrox/pull/13577.
I renamed the `wait-for-collector-image` task to keep it in sync with the component name. 
Discussion point: `RELATED_IMAGE_COLLECTOR_FULL` - should it be renamed to `RELATED_IMAGE_COLLECTOR`?
* Running the check script locally with invalid changes to the operator-bundle-pipeline, e.g. commenting out `wait-for-...-image`. Also https://github.com/stackrox/stackrox/actions/runs/12671318977/job/35312817486?pr=13748#step:10:39. 
* `operator-bundle-on-push` pipeline starts, so I assume that the renaming was successful.
=> ROX-23316: check: confirm all components are part of snapshot

CHANGELOG.md, central/sensor/service/pipeline/networkflowupdate/flow_store_updater_impl_test.go, pkg/features/list.go
Reverses existing ROX_EXTERNAL_IPS feature flag, which controls storage of discovered network entities, making it enabled by default.
This means that control over the feature is moved to Collector (via runtime configuration) but storage can be disabled at Central level if required.
~- [ ] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed~
~- [ ] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag~
~- [ ] added unit tests~
~- [ ] modified existing tests~
Trivial change, existing testing should be enough.
=> ROX-27596: enables storage of external ips by default

ui/apps/platform/src/Containers/VulnMgmt/Entity/Image/VulnMgmtImageOverview.js, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/DeploymentFilterLink.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx
1. Fixes the broken link in VM 1.0 Dashboard to point to User Workloads (this does not have an answer for if the image belongs to a platform component at this point...)
2. Fixes the deployments link in the Namespace view to keep the user within the correct page
1. Visit VM 1.0 Dashboard -> Image Single
2. Ensure the NS view deployments link is relative to the top level VM page
=> chore(ui): Add link fixes for NS view and VM dashboard image page

central/image/service/http_handler.go, central/image/service/http_handler_test.go, ui/apps/platform/src/Components/ReportJob/ReportJobsTable.tsx, ui/apps/platform/src/Components/ReportJob/utils.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/GenerateSbomModal.tsx, ui/apps/platform/src/services/DownloadService.js, ui/apps/platform/src/services/ImageSbomService.ts, ui/apps/platform/src/utils/fileUtils.ts
A few minor changes to SBOM Generation:
1. Update the API to allow the UI to pass `imageName` instead of `image_name` as the parameter
2. Add a `TechPreview` label to the modal header
3. Move away from the DownloadService's `saveFile` function due to incorrect assumptions on the response data that do not hold for the SBOM API
Go to VM -> open the Generate SBOM modal:
Submit the request and see that the request is submitted, but fails with an error. The UI correctly parses and displays the error. (In this case, Scanner V4 is not installed correctly even though it is enabled).
Compare to an older central build, that errors due to not providing `image_name` as the parameter.
=> feat(ui): Minor tweaks to SBOM API and UI

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageScanningIncompleteLabelLayout.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/GenerateSbomModal.tsx
If image or scan notes are present, disable SBOM Generation in the UI.
Visit an image with displayed scan notes and attempt to generate SBOM:
Successfully scanned images are unaffected:
=> ROX-27279: Disable SBOM Generation UI when image has scan notes

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
Adds an additional parameter `'-'` to requests on the User workloads page so that the results are a union of entities with "Platform component:false" and "Platform component:NULL". This results in inactive images, such as watched images, being visible in the list.
Add an image to the watch list that is **not** part of an existing deployment.
Before this change, the image will not be included in the User workloads images list:
After this change, the images list will be updated to include any images that are not part of an existing deployment (e.g. watched images):
=> ROX-27604: Add support for inactive images in User Workloads view

pkg/testutils/certs.go
Apple made the decision to declare any cert which a lifetime of over 398 days as invalid. `IssueSelfSignedCert` creates certs which last 5 years, so this change now switches it to 365 days.
CI
=> ROX-27653: IssueSelfSignedCert expiry 365 days

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx
Backend proto: https://github.com/stackrox/stackrox/pull/13713
Follow the pattern for **NVD CVSS** in #13019 
Nice to see (again) that lint rules display temporary errors while my changes are incomplete.
When response has EPSS data:
1. Add properties to `gql` definitions.
1. Add `formatEpssProbability` function in table.utils.ts file.
2. Add optional prop for label in CvePageHeader.tsx file (because both ImageCvePage.tsx and NodeCvePage.tsx files render the element).
Before deploy, enable feature flag in ui folder:
```sh
export ROX_EPSS_SCORE=true
npm run deploy
```
main.js 0 = 4616720 - 4616720
total 1217 = 11614104 - 11612887
* `ls …
=> ROX-26877: Add EPSS column without GraphQL data

pkg/features/list.go
Enables the Platform CVE split feature flag.
There are many items still TODO, but all minor enough that I think making this available sooner than later is a good idea before the release.
Upcoming:
- Finalization for left navigation link naming
- Splitting links on the Exception Management CVE tables
- Fixing links in global search
TODO: Verify default behavior in build.
=> chore: Enable platform CVE split feature flag

pkg/k8scfgwatch/cfg_watcher_test.go
In the test, we start a config map watcher that listens on k8s events in a go routine. If we cancel the context before we create the config map, we except to see no changes. That's what we assert in the test. In test flake [ROX-27418](https://issues.redhat.com/browse/ROX-27418) it seems that the go routine was delayed, such that the sleep time in the main test code was not sufficient and the config map was created before the context was canceled. To make such an event less likely, I bumped the sleep to 300 ms.
CI
=> ROX-27418: bump sleep time

qa-tests-backend/src/test/groovy/SACTest.groovy
Disable flaky test for autocomplete image search variation in SACTest. [ROX-27478](https://issues.redhat.com/browse/ROX-27478)
This test has been flaky since 2024-12-19. Around that time, we have disabled ROX-26729. It could be that they are related.
Let CI run and check that test is not included anymore.
=> chore(CI): Disable test option for autocomplete search image

central/notifiers/generic/generic.go, central/notifiers/generic/generic_test.go
ACSCS uses Vector to send audit logs to cloudwatch. Vector service on production has error logs about not able to parse JSON.
Regression after the [protobuf upgrade](https://github.com/stackrox/stackrox/pull/10951). Vector [doesn't support multiline strings](https://github.com/vectordotdev/vector/issues/4952) in requests, and we changed the format with the upgrade:
Before:
```
new(jsonpb.Marshaler).MarshalToString(message)
```
Now:
```
msgStr := protojson.Format(message)
```
From the doc:
```
// Format formats the message as a multiline string.
// This function is only intended for human consumption and ignores errors.
// Do not depend on the output being stable. Its output will change across
// different builds of your program, even when using the same version of the
// protobuf module. …
```
=> ROX-27688: Use single-line JSON in generic notifier

central/image/service/http_handler.go, central/image/service/http_handler_test.go, pkg/apiparams/policy.go, roxctl/image/image.go, roxctl/image/sbom/sbom.go, roxctl/image/sbom/sbom_test.go, roxctl/image/scan/scan.go
Adds the `roxctl image sbom` command to support the SBOM generation effort. The parameters largely mirror those of `roxctl image scan`.
Unit tests + manual tests shown below.
Setup:
```
$ export ROX_ENDPOINT=...
$ export ROX_API_TOKEN=...
$ make cli_darwin-arm64
$ alias roxctl=bin/darwin_arm64/roxctl
```
Help info:
```
$ roxctl image -h | grep -i sbom
sbom        Generate an SBOM from an image scan.
```
```
$ roxctl image sbom -h
Generate an SPDX 2.3 SBOM from an image scan. You must have write permissions for the `Image` resource.
Usage:
bin/darwin_arm64/roxctl image sbom [flags]
Flags:
--cluster string   Cluster name or ID to delegate image scan to
-f, --force            Bypass Central's cache for the image and force a new pull from the Scanner (default false)
-i, --image string …
```
=> ROX-27147: SBOM roxctl support

central/image/service/http_handler.go, central/image/service/http_handler_test.go, central/main.go, pkg/images/enricher/enricher.go, pkg/images/enricher/enricher_impl.go, pkg/images/enricher/enricher_impl_test.go, pkg/scanners/scannerv4/scannerv4.go, pkg/scanners/types/mocks/types.go, pkg/scanners/types/types.go, pkg/scannerv4/client/client.go, pkg/scannerv4/client/mocks/client.go
This PR adds image enrichment in get sbom method in http handler to generate index report and image metadata.
Tested this change manually by calling sbom http endpoint
=> ROX-24541: Enrich image to get sbom 

roxctl/central/login/login.go, roxctl/central/login/login_test.go, roxctl/central/m2m/exchange/exchange.go, roxctl/central/m2m/exchange/exchange_test.go, roxctl/common/client.go, roxctl/common/client_options.go, roxctl/common/client_options_test.go, roxctl/common/environment/auth_config.go, roxctl/common/environment/auth_config_test.go, roxctl/common/environment/environment-impl.go, roxctl/common/environment/environment.go, roxctl/common/environment/mocks/environment.go, roxctl/image/sbom/sbom.go, roxctl/image/sbom/sbom_test.go
Stacked on top of: 
- https://github.com/stackrox/stackrox/pull/13706
This PR modifies the [roxctl HTTP client abstraction](https://github.com/stackrox/stackrox/blob/1ae035a0c21d156e9689c7e429eae2e35c4d63ca/roxctl/common/environment/environment.go#L20) to allow for it to be configured - to an extent mimicking the [GRPCConnection equivalent](https://github.com/stackrox/stackrox/blob/9ad6937ece0b12b180466bb4d899af8e2af95f31/roxctl/common/environment/environment.go#L22).
The motivation for this change was so that errors can be surfaced via the new `roxctl image sbom` and behavior (retries, delays, backoffs, etc.) made configurable to align with `roxctl image scan` (which uses the GRPC client)
The new configuration allows for: 
- HTTP API errors to be surfaced (currently suppressed)
- …
=> ROX-27147: Roxctl SBOM HTTP API errors and http client config

image/templates/helm/stackrox-secured-cluster/templates/NOTES.txt.htpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, image/templates/helm/stackrox-secured-cluster/templates/cluster-registration-secret.yaml, operator/internal/securedcluster/values/translation/base-values.yaml, operator/internal/securedcluster/values/translation/translation.go, operator/tests/common/crs-assert.yaml, operator/tests/common/crs-fetch.yaml, operator/tests/securedcluster/sc-basic/007-assert-crs.yaml, operator/tests/securedcluster/sc-basic/007-assert-init-bundle.yaml, operator/tests/securedcluster/sc-basic/007-fetch-bundle.yaml, operator/tests/securedcluster/sc-basic/007-fetch-crs.yaml, pkg/crs/crs.go
**IMPORTANT: Only review commits beginning with 2c951aef36e38116427f4654b63d0c764cd4efd7, the commits before that are hopefully soon to be found in master.**
Adds CRS support to the operator:
* The function `checkRequiredTLSSecrets` has been extended to be CRS-aware.
* For testing:
- Modify the `sc-basic` test to use CRS instead of init-bundles.
- (upgrader test needs to keep using init-bundles of course)
CI and manual testing:
* set up OpenShift cluster, configure as current context.
* make -C operator install run
new shell:
* set up openshift cluster, configure as current context.
* NS=stackrox
* kubectl create ns $NS
* kubens $NS
* ./deploy/common/pull-secret.sh quay-ips quay.io | kubectl -n $NS apply -f -
* kubectl apply -f central-cr.yaml
```
apiVersion: platform.stackrox.io/v1alpha1 …
```
=> ROX-25945: CRS Support for Operator

.github/workflows/scanner-build.yaml
This PR fixes problem with scanner images that fails due to:
```
ERROR: failed to solve: registry.access.redhat.com/ubi8-minimal:latest: failed to resolve source metadata for registry.access.redhat.com/ubi8-minimal:latest: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.access.redhat.com/v2/ubi8-minimal/manifests/sha256:cf095e5668919ba1b4ace3888107684ad9d587b1830d3eb56973e6a54f456e67: 502 Bad Gateway
```
This is related to:
- #10209
- https://github.com/stackrox/stackrox/pull/8844
---
CI
https://github.com/stackrox/stackrox/actions/runs/12807954997/job/35709990370?pr=13841#step:13:1
=> fix(CI): retry scanner images builds

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/cancelRequestFlow.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/hooks/useRequestCVEsDetails.ts
Divides the CVE table in Exception Management into two tabs, with each tab contextual to either user workloads or platform components.
Create a Vulnerability Exception and visit the detail page. By default, the "user workloads" tab is selected. CVEs in this section should show counts for images specific to user workloads and the link in the table should navigate to the correct VM section.
Switch to the "platform components" tab and ensure the displayed CVEs match the counts for only platform components, and link to the correct VM section.
=> ROX-27647: Split exception management CVE table into tabs

sensor/common/clusterentities/debug.go
The cluster entities debugger was panicking in the `json.Marshal` when `track` was called at the same time. This is PR fixes this issue by copying the `trace` map instead of adding it to the debug map.
- Start local-sensor with fake-workloads and the entity store debug server enabled.
- Query the server multiple times. Eventually sensor will panic. After this changes sensor should not panic.
=> fix(debug): Copy trace map to avoid concurrency races

.github/workflows/unit-tests.yaml
This PR removes coverage upload for UI tests. This tests do not create coverage report and wrong file is considered as a coverage (`compliance.coverage.utils.tsx`) resulting in errors in codecov UI.
> Unusable report due to issues such as source code unavailability, path mismatch, empty report, or incorrect data format. Please visit our
```
Found 1 possible coverage files:  
ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx
```
Refs: 
- https://github.com/stackrox/stackrox/pull/8997 
CI
=> chore(CI): skip coverage uplaod for UI tests

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts, ui/apps/platform/src/Containers/Vulnerabilities/components/CvePageHeader.cy.jsx, ui/apps/platform/src/Containers/Vulnerabilities/components/CvePageHeader.tsx
1. Edit DeploymentVulnerabilitiesTable.tsx file.
* Add placeholder `const epssProbability = undefined;` assignment statement.
* Delete `!` operator that was leftover from temporary changes for testing.
* Replace **Not available** text with `formatEpssProbabilityAsPercent(epssProbability)` function call.
2. Edit ImageVulnerabilitiesTable.tsx file.
* Ditto step 1 except leftover
3. Edit WorkloadCVEOverviewTable.tsx file.
* Ditto step 1 except leftover
4. Edit table.utils.ts file to add `formatEpssProbabilityAsPercent` function.
* It renders fraction with 5 decimal places as percent with 3 decimal places.
* It renders **Not available** especially for `undefined` from optional chaining.
5. Edit CvePageHeader.tsx file.
* Add `numLabels` for clearer conditional logic.
* Add initial conditional …
=> ROX-27741: Add formatEpssProbabilityAsPercent function

qa-tests-backend/src/test/groovy/SACTest.groovy
TBD
Will let CI run (a few retests).
Retest results can be found here: https://prow.ci.openshift.org/pr-history/?org=stackrox&repo=stackrox&pr=13860 - it looks good.
=> ROX-27478: Add retry for Autocomplete SACTest

qa-tests-backend/src/test/groovy/CloudSourcesTest.groovy
In the cloud sources qa-test we rely on OCM to respond in time. We observed a flake where the OCM call timed out for all retry attempts. Unfortunately there is not much we can do to avoid flakes when OCM is unresponsive. Here I simply bump the total retry time from 100s to 300s.
CI
=> ROX-27736: bump retry times

ui/apps/platform/cypress/integration/clusters/redirectFromDashboard.test.js
With the addition of CRS, it is no longer guaranteed that an init-bundle will be preset in CI during startup. This changes the rendering of the button in the `should redirect from Dashboard when no secured clusters have been added` cloud service test.
Since the behavior under test is to verify the correct redirection from the main dashboard to the clusters page, and less so on which button is displayed, I removed this assertion for stability.
See https://issues.redhat.com/browse/ROX-27711
Possible follow up - if we think it is important to test the behavior of which button appears on this page, we should add tests that mock the responses and assert on the UI behavior.
CI
=> ROX-27711: Remove empty cluster page button text assertion

image/templates/helm/stackrox-central/config/centraldb/postgresql.conf.default
Since #13357 is going to be delayed we are going to make a couple of the updates to default settings now so they are simpler to adjust in the future and so we can have a more accurate detailed document for the users to follow when updating Postgres configuration settings due to updates to resource configurations.
Added the `hash_mem_multiplier` as that may have some use for us to adjust for some queries that spend a lot of time on hash joins.
Added the `autovacuum_max_workers` to make it easier to take advantage of more resources and to help ensure the database is staying in an optimal state by cleaning up dead tuples.
Reverted the `max_connections` to the Postgres default.  Central is the ONLY thing that connects to this database.  As such the default connections should be sufficient and …
=> ROX-27697: update postgres defaults

ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/ExternalEntitiesSideBar.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/ExternalFlowsTable.tsx
The external entities side panel needs to show both "External IPs" and "Workloads with external flows"
axe devTools: ✅ 
linter: ✅ 
External IPs:
Workloads with external flows:
=> ROX-27530: Update external entities side panel

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageResources.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageResources.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/utils/sortUtils.tsx
~Do not merge - we are reverting the back end change that supports this functionality and will revisit in the future.~
**This has been retested against the new backend changes.**
Adds the ability to sort by CVE severity count on the Workload CVE images tab.
Additionally splits out the default sort options for Image/Deployment resource tables, as it is not correct that those tables use the same counterpart as the overview tables.
Visit Workload CVEs and click the Images tab - CVEs by severity should be the default sort and should correctly sort by multi severity. (_Note that this requires an image >= ~`4.6.x-722-gc5c4dce480`~ The most recent tests were done with image `4.7.x-492-g33369d5c7d`_)
Sort descending:
Test sort with applied filter, e.g. "Fixable:true":
=> ROX-26574: Sort images table by cve severity count

image/rhel/konflux.Dockerfile, operator/konflux.Dockerfile
Only the flavor change.
No change.
It's not possible to test the functioning of this yet.
We'll get to it later.
=> ROX-27230: Set image flavor for Konflux builds to `rhacs`

pkg/search/postgres/common_test.go, pkg/search/postgres/query/enum_query.go, pkg/search/postgres/query/enum_query_test.go, pkg/search/postgres/select_query_test.go
This PR removes unnecessary `()` around enum selects and replaces multiple `OR` with `IN`.
CI
=> fix(PG): optimize enum queries

pkg/sac/query_helper.go
Since `AddExactMatches` handles multiple values we can simplify our SAC generation code by providing slice of names/ids to exact matches instead of creating a query for every of them.
CI
=> chore(PG): cleanup SAC filter generator

qa-tests-backend/src/test/groovy/SACTest.groovy
Ticket ROX-26015 highlight flakiness of SACTest `Verify that SAC has the same effect as query restriction for network flows`.
The test performs two calls to the NetworkGraph service to retrieve the network graph since a fixed point in time, one with a user token having restricted scope, and one with a query restricting the results to the same expected domain as the restricted access scope.
It could happen that between these two calls, some network activity result in additional flows being reported by the second call.
There are potentially two ways of reducing the flakiness of this tests:
- Fix both ends of the time period where the network activity is compared (see PR #13887 )
- Retry the network graph calls hoping that the network activity stabilizes and no new network flow appears …
=> ROX-26015: retry network graph SACTest

qa-tests-backend/src/test/groovy/SACTest.groovy
If the source of flakiness of the test is information propagation delay, then retrying should fix the problem. 
CI run on the pull request
=> ROX-25182: Add retries to alert count SACTest

pkg/search/postgres/common.go, pkg/search/postgres/common_test.go, pkg/search/postgres/query/enum_query.go, pkg/search/postgres/query/enum_query_test.go, pkg/search/postgres/select_query_test.go
This PR aims to generate SQL queries that leverage use of `IN` operator that presents better performance when searching. It will also produce smaller statements (with fewer repetitions).
CI
=> feat(PG): optimize queries with IN operator

central/cloudsources/datastore/telemetry.go, central/cloudsources/datastore/telemetry_postgres_test.go
Make sure to count non-existing cloud source types as zero in telemetry. Otherwise we'll get undefined values, which does not look as nice in the telemetry charts.
change me!
=> fix(telemetry): zero value for cloud source telemetry

tests/upgrade/lib.sh
This PR bumps scanner memory limit. We see a lot of OOMKills in upgrade tests.
Ticket: https://issues.redhat.com/browse/ROX-27168
=> ROX-27168: Bump scanner memory limits in upgrade tests

qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
ROX-27302 - Whitelist Alpine apk policy in e2e test case
This test failed after an AKS upgrade. A default component in AKS contained apk. This issue is out of our control, to avoid CI failures we mark this test as whitelisted for default policies.
=> ROX-27302: Whitelist Alpine apk policy in e2e test case

image/rhel/konflux.Dockerfile, image/roxctl/konflux.Dockerfile, make/env.mk, operator/konflux.Dockerfile, scanner/image/scanner/konflux.Dockerfile
Enables the `strictfipsruntime` build flag for Konflux builds.
For more info about the `strictfipsruntime` flag, see [this doc](https://docs.google.com/document/d/1CTpSwITQfOgoOTlPITZNJZy0ltYz60hxkmWsLemCqw0/edit?tab=t.0) (there might be a better resource but this is the one David and I found), and for our general research regarding the linked ticket, see [this doc](https://docs.google.com/document/d/1KcjlevcMF4DLi-KROru7tuUUIb4wSk5e6bnXpU8HZxA/edit?tab=t.0).
Related scanner v2 PR: https://github.com/stackrox/scanner/pull/1709
Verified the build works via Konflux CI and verified the `check-payload` results of the following images:
=> ROX-24283: enable strictfipsruntime in Konflux builds

central/image/datastore/store/postgres/store.go, central/node/datastore/store/postgres/store.go, central/reports/common/query_builder.go, central/views/common/sac.go, pkg/sac/query_helper.go, pkg/sac/query_helper_test.go, pkg/sac/query_testutils.go, pkg/search/postgres/sac.go
Verbose SAC filters are a leftover from the early phase of the Postgres SAC implementation.
Following the removal of the last calls to the verbose variant of the SAC filter helper functions, the non-verbose variants are being renamed to `BuildXXXLevelSACQueryFilter`.
Internal function renaming. The existing CI validation should be enough.
=> chore(cleanup): rename SAC filter generators

qa-tests-backend/src/test/groovy/ImageSignatureVerificationTest.groovy, qa-tests-backend/src/test/groovy/Services.groovy
Assertion on no violations is tricky. We can have multiple states during test execution:
1. policy not evaluated -> no violations
2. policy evaluated -> no violations
3. policy evaluated -> no active violations (can happen only after false-positive alerts, they get resolved quickly)
Changes in this PR are trying to ensure that:
- policy is evaluated - by waiting for **pullable** image state and checking on violations multiple times to avoid getting intermediary state
- false-positive alerts are resolved - by waiting on no active violations
=> ROX-25897: Adjust test to check for no active violations

ui/apps/platform/cypress/integration/integrations/notifiers.test.js, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/SlackIntegrationForm.tsx
A user wanted to use the Slack integration with the Mattermost service, which has a Slack-compatible, according to its docs
https://docs.mattermost.com/about/integrations.html#webhooks
However, our UI has a front-end validation that will not let you submit the Slack integration form, unless the URL is a valid URL with the segment "/services/" in the middle, which is Slack's URL format, but not Mattermost URL format.
This change removes any regex format validation from that field, and only leaves the check that requires that field to not be empty.
(In this case, we could probably require a standard URL, but for some other integrations, we have had customers who used Kubernetes services names, which can be as short as single words–better to be as permissive as possible.)
- I updated the UI …
=> ROX-27829: Remove regex validation from Slack URL field in form

qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
Adds groovy tests that validate scanner is properly detecting component + versions in images that have layers in common.
_**Will not be merged until SCANNER_VERSION updated to include a version with the lineage fix.**_ `ImageScanningTest` is expected to fail in the meantime.
In addition to the tests themselves - manually executed these tests against two clusters, one with the lineage fix and one without - the new test failed for the cluster without the fix, and succeeded in the cluster with the fix. 
```sh
./gradlew test --tests=ImageScanningTest.*"Verify Image Scan Results"*
```
=> ROX-27617: Add image lineage groovy test

tests/delegated_scanning_test.go
This PR should fix one flaky behavior of `TestDelegatedScanning/TestMirrorScans/Scan_ad-hoc_image_from_mirror_via_ImageContentSourcePolicy` test.
Explanation of problem is explain in the ticket.
=> ROX-26663: Retry scans on failed fetch layer errors

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AdvisoryLinkOrText.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx
Prerequisite for future demo with realistic data (by temporary code changes).
Similar steps as for **EPSS probability** in #13789 plus #13892
1. Add AdvisoryLinkOrText.tsx file.
2. Add conditional rendering for **Advisory** table column.
* DeploymentComponentVulnerabilitiesTable.tsx file
* ImageComponentVulnerabilitiesTable.tsx file
When response has `advisory` property:
1. Add property to `gql` definitions.
2. Investigate function for front-end sorting.
3. If needed, add **Advisories** column with count for images but not deployments.
Before local deployment, enable feature flag in ui folder:
```sh
export ROX_CVE_ADVISORY_SEPARATION=true
npm run deploy
```
However, I used staging demo instead (see below).
2. `npm run build` in ui/apps/platform and …
=> ROX-27066: Render Advisory column without GraphQL data

tests/e2e/lib.sh
We have seen flaky tests due to unstable network connectivity even after three successful pings to Central. These flakes are especially annoying, because they don't relate to the failing test itself.
To make network problems less likely, I doubled the number of successful Central pings that are required before starting the tests.
green CI
=> ROX-26617: wait longer for network stability

sensor/kubernetes/certrefresh/certrepo/service_certificates_repository.go, sensor/kubernetes/certrefresh/certrepo/service_certificates_repository_test.go
Secrets created by `ServiceCertificatesRepoSecrets` are using the wrong annotations for secrets that it creates. These secrets are created by:
* CRS secured cluster registration
* secured cluster cert refresh
* local scanner cert refresh
Deployed locally with `./deploy/k8s/deploy-local.sh`
```bash
❯ kubectl -n stackrox get secrets tls-cert-sensor -o yaml
apiVersion: v1
data:
...
kind: Secret
metadata:
annotations:
owner: stackrox
creationTimestamp: "2025-01-29T13:04:39Z"
labels:
app.kubernetes.io/created-by: sensor
app.kubernetes.io/managed-by: sensor
app.kubernetes.io/name: stackrox
name: tls-cert-sensor
namespace: stackrox
...
```
Before this change, the annotations were identical to the labels.
=> fix(sensor): use correct annotations for Sensor TLS secrets

ui/apps/platform/src/Components/CompoundSearchFilter/attributes/epssProbability.test.ts, ui/apps/platform/src/Components/CompoundSearchFilter/attributes/epssProbability.ts, ui/apps/platform/src/Components/CompoundSearchFilter/attributes/imageCVE.ts, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/ConditionText.css, ui/apps/platform/src/Components/CompoundSearchFilter/components/ConditionText.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/types.ts, ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.test.ts, ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
See improved layout of condition selection in testing step 1
~Any advice about responsive shrink of condition `Select` element is welcome.~
~I will fix the layout before merge, for sure.~
1. Edit src/Components/CompoundSearchFilter/types.ts file.
* Add `featureFlagDependency?: FeatureFlagEnvVar[]` property.
* Distinguish `BaseSearchFilterAttribute` type from generic and specific types to remove duplication.
2. Edit src/Components/CompoundSearchFilter/utils/utils.tsx file.
* Add `getSearchFilterConfigWithFeatureFlagDependency` function.
3. Edit src/Components/CompoundSearchFilter/utils/utils.test.ts file.
* Delete incomplete test for function that does not exist.
* Call `getSearchFilterConfigWithFeatureFlagDependency` function in tests whose assertions depend on imageCVE.ts file that now …
=> ROX-27742: Add search filter for EPSS Probability

.tekton/basic-component-pipeline.yaml, .tekton/main-pipeline.yaml, .tekton/operator-build.yaml, .tekton/operator-bundle-pipeline.yaml, .tekton/retag-pipeline.yaml, .tekton/scanner-v4-pipeline.yaml
Using task from https://github.com/stackrox/konflux-tasks/pull/30.
Main image tag becomes the same as operator image tag and so we can eliminate some of the extra tasks and discrepancies.
No change.
=> ROX-22250: Switch to sanitizing version of determine-image-tag

pkg/search/postgres/store.go
Updated `pkg/search/postgres/store.go` `deleteMany` method to stop processing more batches if the error returned is a context cancellation error or a context timeout error.
- Ran pruning test with the context being cancelled before it is even used, and the test exited after one batch failing
- Ran pruning test with the context timeout being set to zero, and the test exited after one batch failing
=> ROX-27782: Make pruning stop after context errors

pkg/contextutil/contextmerge.go, pkg/contextutil/contextmerge_test.go, sensor/common/detector/detector.go, sensor/common/detector/enricher.go, sensor/common/detector/enricher_test.go
In the kuberentes listeners' path to the detector we expire messages if the connection drops. This means the messages will not be sent to Central. In that case we can cancel the request to scan images as the results are not going to be sent regardless.
In the runtime path (process indicators and network flows) we do not cancel the context as we sent messages that arrived while Sensor was disconnected.
=> feat(cancel-scan): Stop scan request if the context is canceled

central/scannerdefinitions/handler/updater_test.go, image/rhel/fetch-stackrox-data.sh
Two separate issues addressed in this PR:
1. A space in the external-networks filename was breaking image builds (must have been OK with the prev CDN) ([ex](https://github.com/stackrox/stackrox/actions/runs/13062430374/job/36448796656))
2. The new CDN doesn't like 'future dates' in the `If-Modified-Since` header which was breaking the scanner definitions tests ([ex](https://github.com/stackrox/stackrox/actions/runs/13062430376/job/36448267008))
**Space in filename breakage**
```
$ curl --fail https://definitions.stackrox.io/external-networks/latest_prefix
external-networks/2025-01-30 10-38-49__645bb476-def6-11ef-9e85-7c1e520c377e
$ latest_prefix="$(curl --fail https://definitions.stackrox.io/external-networks/latest_prefix)"
$ curl --fail …
```
=> fix(ci): due to diff CDN behavior

ui/apps/platform/src/Containers/MainPage/MainPage.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/HorizontalSubnav.css, ui/apps/platform/src/Containers/MainPage/Navigation/HorizontalSubnav.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/NavigationSidebar.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/utils.ts
Adds a horizontal subnav component to the UI, and moves left navigation links for VM to the subnav when the feature flag is enabled.
Currently, which set of links is shown at the top of the page in the subnav is dependent on the current route. The decision is made like this:
1. A key/value object contains a mapping of top level page names to an array of links to be shown for that page
2. If the current page address matches **any** link in the array, the entire array is used as the nav to be shown
This works right now, but is susceptible to some potential issues in the future:
1. It is not possible to show the subnav if the current page address does not match a child item
2. It is not possible to have a link to a _different_ top level page in the subnav without the potential for conflicts …
=> ROX-27822: Add horizontal subnav support and impl for VM

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/utils/sortUtils.tsx
Query fails when I sort by **EPSS Probability** without `SortAggregate` options.
Only on Workload CVEs page, not on image CVEs nor deployment CVEs pages.
Thank you, **Charmik** for quick response that it needs same option as **CVSS**:
```ts
export const aggregateByCVSS: SortAggregate = {
aggregateFunc: 'max',
};
```
main.js 0 = 4617317 - 4617317
total 38 = 11592006 - 11591968
files 0 = 178 - 178
Similar testing steps as in #13789
Even if I run UI with staging demo, which has **Scanner V4**, I need to temporarily edit code to invert conditional rendering, …
=> ROX-27894: Add SortAggregate options for EPSS probability

.github/CODEOWNERS
This hasn't been updated in a while and now seemed like a good time to do so. The main purpose is to ensure the team is aware of any (attempted) changes related to any part of the codebase which we own.
no
I didn't
=> chore(CODEOWNERS): update Scanner team ownership

central/delegatedregistryconfig/datastore/telemetry.go, central/delegatedregistryconfig/datastore/telemetry_postgres_test.go
Fix telemetry collection such that when no delegated config is found, the default/zero values are still collected.
Fix for edge case missed in #13959.
see test
=> ROX-25373: default values if no config is found

sensor/kubernetes/clusterhealth/updater_test.go
`TestExpiredMessages` can be a little bit flaky because races may occur between `Notify` and the ticker in `run`. This PR changes the test to use a fake ticker that can be controlled in the test execution.
=> ROX-27904: Use fake ticker in test

ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/HorizontalSubnav.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/NavigationSidebar.tsx, ui/apps/platform/src/Containers/Risk/ContainerConfigurations.js, ui/apps/platform/src/Containers/Risk/KeyValuePairs.js, ui/apps/platform/src/Containers/Search/SearchTable.tsx, ui/apps/platform/src/Containers/Search/searchCategories.ts, ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerConfiguration.tsx, ui/apps/platform/src/Containers/Violations/Details/Deployment/DeploymentOverview.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx, ui/apps/platform/src/routePaths.ts
Updates routing and URLs to handle the split in Workload CVEs, as well as to support the future concept of VM views.
**New routes for User Workloads and Platform, sans "results" path segment**
- /main/vulnerabilities/user-workloads
- /main/vulnerabilities/platform
**New routes for specific system defined views (thanks Mark!)**
- /main/vulnerabilities/all-images
- /main/vulnerabilities/inactive-images
**Currently unused, but future looking route definition for user-defined views**
- /main/vulnerabilities/results/:viewTemplate/:viewId
**Backwards compatible redirect from existing "/workload-cves" links and saved bookmarks to "all-images" view**
With feature flag off, verify that CI passes and all links/routes work as expected compared to `master`.
With feature flag on, verify links to all …
=> ROX-27823: Update routing for VM result views

ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/HorizontalSubnav.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/NavigationSidebar.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ObservedCveModeSelect.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/string.utils.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx, ui/apps/platform/src/routePaths.ts
Moves the existing dropdown functionality of "Images with vulns" and "Images without vulns" into a top level navigation view.
With feature flag disabled, the dropdown is present and works as expected:
With the feature flag enabled, the default views all show the "with CVEs" representation:
Clicking the "Images w/o CVEs" link in the navigation shows only images and deployments without detected CVEs:
=> ROX-27825: Replace images w/o vulns dropdown with view

image/rhel/konflux.Dockerfile
See https://redhat-internal.slack.com/archives/C7ERNFL0M/p1738574728275579
Mark reports that his local builds are in fact powered by 20. GHA builds also use 20.
Unfortunately, there's no 22 in the catalog for ubi8 base (see [here](https://catalog.redhat.com/search?gs&q=ubi8/nodejs&searchType=containers)), therefore setting the builder stage to 20.
No change.
I'm only going to check that UI _build_ completes successfully. I'm not going to test the UI functioning as part of this change.
Per the investigation in the Slack thread, UI is already built and tested with 20 on GHA.
=> build: Switch Konflux UI builds from NodeJS 18 to 20

ui/apps/platform/src/Components/FilteredWorkflowViewSelector/useFilteredWorkflowViewURLState.ts, ui/apps/platform/src/Containers/MainPage/Navigation/HorizontalSubnav.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/NavigationItem.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/NavigationSidebar.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/utils.ts, ui/apps/platform/src/Containers/Violations/Details/ViolationDetailsPage.tsx, ui/apps/platform/src/Containers/Violations/ViolationsBreadcrumbs.tsx, ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx, ui/apps/platform/src/Containers/Violations/violationTableColumnDescriptors.tsx, ui/apps/platform/src/routePaths.ts
Replaces the FilteredWorkflowView dropdown on the Violations page with the horizontal subnav to match the pattern in VM.
**Notes**
This approach retains the URL parameter instead of switching to a path parameter for the following reasons:
- UX does not anticipate a divergence of workflows in the Violations section comparable to what is happening with VM
- This avoids the need to handle backwards compatibility with existing Violation links, and to search and update all internal links in ACS
- This avoids the need to deal with the conflict between the current `/violations/:alertId` URL and potential `/violations/user-workloads` URLs
Relying on URL parameters however does require some additions to the navigation code, which I will comment on inline.
Visit the Violations page and see the …
=> ROX-27828: Replace Violations dropdown with nav

central/telemetry/centralclient/interceptors.go, central/telemetry/centralclient/interceptors_test.go, pkg/telemetry/phonehome/campaign.go, pkg/telemetry/phonehome/campaign_test.go
When specifying a criterion for telemetry API Call interception, the resulting event is filled with properties from headers mentioned in all other criteria.
The backend tracks a request if it fulfills at least one campaign criterion, and it stops evaluating once the first matching criterion is found. In the case where a request fulfills multiple criterion, it should have added matching headers from all fulfilled criteria, but instead it adds headers from all.
The backend has to evaluate every criterion in the campaign and add headers only from matching criteria.
Unit tests.
=> ROX-27902: telemetry campaign headers problem

pkg/grpc/server_test.go
This PR reverts changes made in #14009.
The critical part is replacing of: `a.T().Cleanup(func() { api.Stop() })` with `a.Require().True(api.Stop())`. Before, we didn't consider the state of `Close` execution to be relevant for the test state. This PR is putting that behavior back.
We need additional investigation to understand why `Stop` is failing.
Let CI pipeline run
=> ROX-27931: Revert require on api Stop call

ui/apps/platform/src/Containers/MainPage/Navigation/HorizontalSubnav.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/NavigationSidebar.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCveViewContext.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
Updates page titles, descriptions, tooltips, and navigation wording for VM after alignment with UX and PM teams.
Open the VM sidebar item and navigation dropdown. "Platform CVEs" has been renamed to the more appropriate "Kubernetes components" and moved within the horizontal nav dropdown.
User workload based pages now have a tooltip next to the main page title explaining more about what the current view entails:
Page descriptions for each of the Observed/Deferred/False positive tabs have been updated:
The "Images without CVEs" view removes the violation state tabs and has alternative text above the table.
=> ROX-27826: Update description and tooltips for VM results page

qa-tests-backend/src/test/groovy/AuditScrubbingTest.groovy
In AuditScrubbingTest we do retries for 30s until we find a value but we do not handle exceptions (in this case network error). This PR replaces simple waiting with retry that handle exceptions.
Fixes:
- https://issues.redhat.com/browse/ROX-27937
- https://issues.redhat.com/browse/ROX-27938
CI
=> ROX-27937: retry on error

ui/apps/platform/src/Components/FilteredWorkflowViewSelector/types.ts, ui/apps/platform/src/Components/FilteredWorkflowViewSelector/useFilteredWorkflowViewURLState.ts, ui/apps/platform/src/Containers/Dashboard/SummaryCounts.tsx, ui/apps/platform/src/Containers/Dashboard/Widgets/PolicyViolationTiles.tsx, ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicyCategoryChart.tsx, ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicySeverity.tsx, ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerConfiguration.tsx, ui/apps/platform/src/Containers/Violations/Details/Deployment/DeploymentOverview.tsx, ui/apps/platform/src/Containers/Violations/ViolationNotFoundPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/hooks/useRequestCVEsDetails.ts
Updates links throughout ACS to support split views for Violations and VM:
1. Reverts the "User workload"/"Platform" CVE split in exception management. With the addition of the "All images" view, the tabs are no longer necessary and complicate the UI.
2. Updates all* links to Violations to specify the "full view" when the user/platform context is unknown.
3. Updates all links to VM where the context _is_ known to fall back to `/workload-cves` when the feature flag is off.
*The global search links to violations will require more work in a follow up due to complications with how the declarative links are rendered.
Visit an exception management request page and see the original single table of CVEs. Clicking on a CVE link routes you to the "All images" view.
From the dashboard, click the …
=> fix(UI): Update links to support split of Platform CVEs

ui/apps/platform/cypress/integration/systemHealth/bundle.test.js, ui/apps/platform/src/services/DownloadService.js
During the SBOM changes, the call to remove quotes from incoming filenames was lost. This resulted in the filename for diagnostic bundles as well as other downloads being surrounded by `_` characters. This is degraded UX as the OS does not correctly detect the file as .zip and requires a rename or other additional steps to extract the contents.
Updated tests to assert on expected download filename.
View recent downloads - see presence of filename wrapped in underscores previously, with recent downloads having the correct filename.
=> ROX-27936: Fixes lost handling of quotes in filename payload

central/image/service/http_handler.go, central/image/service/http_handler_test.go, pkg/apiparams/policy.go, pkg/apiparams/sbom.go, roxctl/image/sbom/sbom.go
If SBOM generation results in a successful image scan ensures that the image scan is saved.
Also ensures that the HTTP error code when generating an SBOM is derived from the error and not always `500` (for example, if the image name is empty the error should be `400` due to `errox.InvalidArgs` being wrapped [here](https://github.com/stackrox/stackrox/blob/5161acdc393b056c0b35ae1ecfece141d38a15e6/pkg/images/enricher/util.go#L16))
Unit tests + manual test.
<details>
<summary>Image Name missing 400</summary>
**Before Fix:**
Notice HTTP `500` is returned 
```
$ cat payload.json 
{
"imageName": "",
"force": false,
"cluster": ""
}
$ curl -ksS -H "Authorization: Bearer $ROX_API_TOKEN" -X POST "https://$ROX_ENDPOINT/api/v1/images/sbom" -i -d @payload.json
HTTP/2 500 
vary: Accept-Encoding …
```
=> ROX-27772: SBOM fix scan time update edge case

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/infoForTh.tsx, ui/apps/platform/src/Containers/Vulnerabilities/utils/sortUtils.tsx
~Although ready for review, DO NOT MERGE until actual text is available.~
Thank you, **Shubha**, for clear and concise text: Likelihood of exploitability
One other change after initial review. axe DevTools reported 5 accessibility issues because of `Popover` element.
* On one side of coin: `PopoverBodyContent` element fixed them, as elsewhere.
* On other side of coin: `info` prop of `Th` element renders in a way that loses `aria-labelledby` attribute, which causes a different issue (explained by comment in code). Too bad, so sad. See pictures in **Manual testing** below.
Field represententatives recommended that we preclude concern or confusion by customers about the meaning of Exploit Prediction Scoring System.
1. Vulnerabilities tables have tooltips for some column headings.
There is no …
=> ROX-27743: Add info popover for EPSS probability column

pkg/grpc/server.go, pkg/grpc/server_test.go
This PR reverts changes made in #14009 and #14123.
We are getting back to old logic where the execution state of `stopper` was ignored.
Let CI pipeline run
=> ROX-27931: Revert stopper state propagation

central/reports/scheduler/v2/reportgenerator/csv_gen.go
Currently when user selects both EPSS Probability and NVD CVSS optional columns in report, EPSS header is misaligned with NVD column. This PR fixes this bug.
Tested vuln report manually with both columns selected
change me!
=> ROX-27950: Fix rep header

CHANGELOG.md
Adds info related to SBOM generation to the changelog
N/A
👁️ 📖
=> ROX-27606: add SBOM gen to changelog

ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/ExternalFlows.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/ExternalIpsTable.tsx
This PR adds the ExternalIPsTable, that Brad made, to the External Flows table under the Deployment Side Panel. The table will show the grouped external IPs. 
Next step will be to add routing so clicking on the link will take you to the right place.
=> ROX-27745: Adding external ips table to deployment side panel

central/networkgraph/aggregator/aggregator_impl.go, pkg/features/list.go
It is redundant. Behavior now is as if the flag has been set to false. External IP information is available via other APIs. Aggregation prevents overloading the graph with many nodes.
No new tests added. The behavior is unchanged.
=> ROX-27971: removes ROX_NETWORK_GRAPH_EXTERNAL_IPS feature flag

central/globaldb/telemetry.go, central/main.go
Database size is an important factor for making decisions about strategies for upgrade, HA, etc. Make it available via telemetry. This data is currently exposed only for ACSCS, let it flow via telemetry as well.
Manual test on an infra cluster with the test API key.
=> ROX-27438: Add db size to telemetry

central/complianceoperator/v2/integration/datastore/datastore_impl_test.go, central/image/datastore/store/postgres/store.go, migrator/migrations/m_202_to_m_203_vuln_requests_for_suppressed_cves/migration_test.go, pkg/postgres/pgutils/scan.go, pkg/search/postgres/common.go
This is minor change that replaces custom implementation with one delivered by pgx.
The main difference is that `CollectRows` closes `rows` and return empty slice instead of `nil`.
CI
=> ROX-27973: use pgx.CollectRows

central/telemetry/centralclient/instance_config_test.go, pkg/env/telemetry.go, pkg/telemetry/phonehome/gatherer.go, pkg/telemetry/phonehome/gatherer_test.go, pkg/telemetry/phonehome/runtime_config.go, pkg/telemetry/phonehome/runtime_config_test.go
Race spot in this unit test CI run:
https://github.com/stackrox/stackrox/actions/runs/13154335828?pr=13963
The problem is in the concurrent access to `g.ctx`.
```
telemetry/centralclient: 2025/02/05 09:49:34.910912 instance_config.go:128: Info: Telemetry collection is disabled
==================
WARNING: DATA RACE
Write at 0x00c000c901b0 by goroutine 130:
github.com/stackrox/rox/pkg/telemetry/phonehome.(*gatherer).reset()
/__w/stackrox/stackrox/pkg/telemetry/phonehome/gatherer.go:56 +0xf8
github.com/stackrox/rox/pkg/telemetry/phonehome.(*gatherer).Start()
/__w/stackrox/stackrox/pkg/telemetry/phonehome/gatherer.go:112 +0xe4
github.com/stackrox/rox/central/telemetry/centralclient.Enable()
/__w/stackrox/stackrox/central/telemetry/centralclient/instance_config.go:209 +0x5ce …
```
=> fix(telemetery): mutex refactoring

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts
Thanks to **David Vail** for seeing that RHSA-2023:7198 has **EPSS probability** of 0.090% in Workload CVEs table but sorts as if about 80%
Thanks to **Surabhi** for digging deep and to **Charmik** for collaborating to conclude that central sorts according to `aggregateFunc: 'max'` but UI displays the first item in `distroTuples` array.
Correct my false assumption in `getCveBaseInfoFromDistroTuples` function:
```js
// Assume that epss property has same value for each of multiple items.
```
Instead of first item, find item that has max value.
To minimize changes, `cveBaseInfo` is the return value.
1. Although ImageVulnerabilitiesTable and DeploymentVulnerabilitiesTable have only one `epss` property per row, the particular value might not be the max.
**Shubha** is deciding whether it might …
=> ROX-27967: Select max epssProbability from distroTuples

CHANGELOG.md, central/sensor/service/pipeline/nodeindex/pipeline.go, central/sensor/service/pipeline/nodeindex/pipeline_test.go, central/sensor/service/pipeline/nodeindex/three_pipelines_test.go, central/sensor/service/pipeline/nodeinventory/pipeline.go, compliance/compliance.go, pkg/env/node_index.go, pkg/features/list.go, sensor/common/sensor/sensor.go
This PR changes the `ROX_NODE_INDEX_ENABLED` from a `BooleanSetting` to a feature-flag, so that it can be exposed over the Cental API to the UI. The UI consumes it as in: https://github.com/stackrox/stackrox/pull/14130
Moreover, I flip the feature flag to enable V4 node scanning* and update the changelog.
*) We are not disabling V2 node scanning yet, they will both run in parallel. The Centrals with Scanner V4 will prefer the V4 scans automatically, whereas the Centrals with StackRox Scanner (V2) will continue working without any changes.
- CI should cover any potential issues regarding the change of a setting to a FF
- I tested the change manually as a part of #14130
=> ROX-27719: Enable FF for RHCOS node scanning with scanner V4 

pkg/protoconv/resources/resources.go
Note that on images that are clearly not pullable, we can save the call to Scanner (over Central) and speed up the processing in Sensor - see https://github.com/stackrox/stackrox/blob/d20bca1e92582829ade0146772f232fb5a0b84ed/sensor/common/detector/enricher.go#L269
In a recent incident, we saw in the Central logs that the images including the error string in the name are sent to Central and a scann attempt it made with scanner. This is not necessary and only wastes resources.
Example central log:
```
image/service: 2025/01/16 14:15:51.851516 service_impl.go:366: Error: Enriching image {"image": "  is an invalid image", "image_id": "", "error": "image enrichment error: error getting metadata for image:   is an invalid image error: invalid arguments: no registry is indicated for image \"  is …
```
=> fix(sensor): Avoid unnecessary image scan attempts

ui/apps/platform/src/services/ImageSbomService.ts
The network request code for SBOM generation erroneously asserted a type of `arraybuffer` for the response data, which was not needed as the response was a JSON type. This caused the `response.data.message` property to be missing in the error message parsing, since `response.data` was not an object type.
The fix was to remove this asserted response type and simply construct a `Blob` from the returned JSON in the success case.
Test a successful SBOM generation and ensure the file is readable:
Simulate a server error with an invalid payload and ensure the error is propagated to the UI:
=> fix(ui): Fix SBOM error message display

.github/labeler.yml
After missing the label on #13350, this might be useful to avoid such mistakes in the future
=> chore(ci): Adds autolabeller config for konflux dockerfile changes

ui/apps/platform/src/Containers/Clusters/Components/ClusterStatus.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterUsingHelmChart.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterUsingOperator.tsx, ui/apps/platform/src/Containers/SystemHealth/CertificateHealth/CertificateCard.tsx, ui/apps/platform/src/Containers/SystemHealth/DiagnosticBundle/GenerateDiagnosticBundle.tsx, ui/apps/platform/src/utils/versioning.test.ts, ui/apps/platform/src/utils/versioning.ts
> OpenShift docs are moving and will soon only be available at docs.redhat.com, the home of all Red Hat product documentation.
Find in Files `getVersionedDocs(` has 15 results in 12 files (excluding definition and tests)
Separate changes according to release in which link was last changed, in case we back patch.
2024-02-29 https://github.com/stackrox/stackrox/pull/10180
2024-01-23 https://github.com/stackrox/stackrox/pull/9506
2024-02-05 https://github.com/stackrox/stackrox/pull/9707
2024-02-12 https://github.com/stackrox/stackrox/pull/9856
Therefore, 4.5 and 4.6 will follow in separate contributions.
1. Update doc page addresses.
* Omit `.html` extension.
* Rename folders if needed.
2. Update `getVersionedDocs` function.
* Replace base address.
* Update conditional logic for absence of …
=> ROX-27916: Update getVersionedDocs and docs links last changed in 4.4

ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviders.tsx
> OpenShift docs are moving and will soon only be available at docs.redhat.com, the home of all Red Hat product documentation.
Find in Files `getVersionedDocs(` has 15 results in 12 files (excluding definition and tests)
Separate changes according to release in which link was last changed, in case we back patch.
2024-07-09 https://github.com/stackrox/stackrox/pull/11895
2024-06-10 https://github.com/stackrox/stackrox/pull/11439
Therefore, 4.4 preceded and 4.6 will follow in separate contributions.
1. Update doc page addresses.
* Omit `.html` extension.
* Rename folders if needed.
1. https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviders.tsx
2024-06-10 https://github.com/stackrox/stackrox/pull/11439
* Replace …
=> ROX-27985: Update docs links last changed in 4.5

CHANGELOG.md, ui/apps/platform/src/Components/ScannerV4IntegrationBanner.tsx, ui/apps/platform/src/Containers/Clusters/Components/CredentialExpiration.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ExternalBackupIntegrations/GcsIntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ExternalBackupIntegrations/S3IntegrationForm.tsx
> OpenShift docs are moving and will soon only be available at docs.redhat.com, the home of all Red Hat product documentation.
Find in Files `getVersionedDocs(` has 15 results in 12 files (excluding definition and tests)
Separate changes according to release in which link was last changed, in case we back patch.
2024-10-30 https://github.com/stackrox/stackrox/pull/13166
2024-09-05 https://github.com/stackrox/stackrox/pull/12558
2024-09-24 https://github.com/stackrox/stackrox/pull/12775
Therefore, 4.4 and 4.5 preceded in separate contributions.
1. Update doc page addresses.
* Omit `.html` extension.
* Rename folders if needed.
1. https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Components/ScannerV4IntegrationBanner.tsx
2025-09-05 …
=> ROX-27986: Update docs links last changed in 4.6

qa-tests-backend/scripts/run-compatibility.sh, tests/e2e/lib.sh, tests/e2e/run-compatibility.sh
Updating the Junix prefix for go compatibility tests with the central and sensor versions used
I've run the tests and confirmed that they are being renamed to include the Central and Sensor versions as expected
=> ROX-27879: Improve go compatibility jira issues

central/networkgraph/service/service_impl.go, central/networkgraph/service/service_impl_postgres_test.go
While flows and entities are sorted before they're processed into metadata, the use of a map for processing led to indeterminate sorting of returned entities which makes pagination functionally useless. This change further sorts the map by key before constructing the response. 
Updated the postgres tests so they take order into account, and will fail if the order of entities is wrong.
=> fix(networkgraph): Fixes sorting of entity metadata

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
Without CVE/advisory separaration in 4.7, **EPSS probability** for RHSA/RHBA/RHEA might differ between WorkloadCVEOverviewTable and the other tables:
* DeploymentVulnerabilitiesTable
* ImageVulnerabilitiesTable
Scanner team reports that even with mitigations, customers might notice differences depending on which CVE are associated with an advisory in a context.
Keep **EPSS probability** where it matters most:
* WorkloadCVEOverviewTable
* CvePageHeader
Omit **EPSS probability** for 4.7 release and then undo omission when CVE/advisory separation is available for 4.8 release.
1. On one side of coint, `isEpssProbabilityColumnEnabled` is easy to change for table columns.
2. On other side of coin, search filter config is not quite so easy.
2. `npm run …
=> ROX-27988: Omit EPSS columns for image and deployment in 4.7 release

ui/apps/platform/src/Containers/Vulnerabilities/utils/textUtils.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/utils/textUtils.ts
Updates the link text to outgoing CVE database links to be dependent on the content of the URL, instead of inferring the link location from the provided `distro` field. This does not impact prioritization, etc. of the links.
Spot check of CVE links on a couple of CVE pages:
Unit test validation to ensure expected functionality and that invalid/unexpected URLs are handled without error.
=> ROX-27284: Update accuracy of CVE link text

scripts/ci/lib.sh
We wait for image prefetcher metrics endpoint to show up.
From time to time this never happens, due to failed load balancer provisioning outside of our control: wrong permissions, lack of quota, etc. (See ticket).
In these cases, it's useful to see a description of the k8s service in question right away, than have to dig through the logs to triage a CI failure correctly.
Also drop the duplicate "ERROR" while at it.
```
INFO: Tue Feb 11 09:37:22 UTC 2025: Waiting for service/qa-e2e-metrics to obtain endpoint ...
INFO: Tue Feb 11 09:37:32 UTC 2025: Waiting for service/qa-e2e-metrics to obtain endpoint ...
INFO: Tue Feb 11 09:37:42 UTC 2025: Something is wrong with the service/qa-e2e-metrics service. See the following 'describe' output.
Name:                     qa-e2e-metrics
Namespace: …
```
=> ROX-28011: describe problematic service before dying

ui/apps/platform/src/Containers/NetworkGraph/common/IPMatchFilter.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/EntityDetails.tsx, ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.ts
Includes 2 change requests:
- Swap direction on entity details flows: direction should be relative to the deployment, not the external entity.
- Remove "not" filtering for 4.7
- Remove "add to baseline" column in entity details table
Example of external ip being the source and central being the destination
Removal of "Not" filtering
Removal of "Add to baseline"
=> chore(ui): Network graph 4.7 changes

ui/apps/platform/src/Containers/Clusters/Components/ClusterSummary.js, ui/apps/platform/src/Containers/Clusters/Components/CredentialExpiration.tsx
should look as it did before 
with expiry text (modified in UI/the date should not display like that irl)
=> ROX-27179: Moving Auto-refresh enabled text below expiry 

ui/apps/platform/cypress/constants/apiEndpoints.js, ui/apps/platform/cypress/helpers/systemHealth.js, ui/apps/platform/cypress/integration/systemHealth/certificateHealthCards.test.js, ui/apps/platform/src/Containers/MainPage/Banners/Banners.tsx, ui/apps/platform/src/Containers/SystemHealth/CertificateHealth/CertificateCard.tsx, ui/apps/platform/src/Containers/SystemHealth/DashboardPage.js, ui/apps/platform/src/services/CertGenerationService.ts, ui/apps/platform/src/types/credentialExpiryService.proto.ts, ui/apps/platform/src/utils/credentialExpiry.ts
This change add UI elements to show the health, and if necessary imminent expiration of the Central-DB certificate.
This change is necessary because several orgs were alerts by their instance of the need to renew the other certificates, for Central and Scanner, but were not aware that they also needed to renew the certificate for the on-prem Central DB Postgres instance.
- New card, which is always present on the System Health page, that shows the status of the central-db certificate and the relative and absolute time until expiry
- - Green if expiry is more than 14 days away
- - Yellow if expiry is less than 14 days, but more than 3 days away
- - Red if expiry is less than 3 days away
- Yellow banner at top of all pages, present only if expiry is less than 14 days, but more than 3 days …
=> ROX-27866: Add UI for central-db cert expiry notices

ui/apps/platform/eslint-plugins/pluginGeneric.js, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/AzureIntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/MicrosoftSentinelForm.tsx
1. Until docs dot openshift dot com site is removed, contributors might get links from it instead of docs dot redhat dot com site, which has become destination of links.
2. Even after previous site is removed, contributors might get link from a doc **preview** which has `.html` extension that customer-facing site does not use.
Reduce chance of problems:
* Forbid leading `/` in **relative** path.
* Forbid `.html` in path.
To understand AST of function call and argument, I used the following site:
https://typescript-eslint.io/play/#ts=5.7.3&showAST=es&fileType=.tsx
Restart Visual Studio Code editor, and then make temporary changes to provoke the expected errors.
Although despite what I though were my best efforts, the code still had both errors, …
=> ROX-28017: Add getVersionedDocs-subPath lint rule in pluginGeneric

image/templates/helm/stackrox-secured-cluster/templates/collector.yaml.htpl, image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl
Attempt removing usage of `ROX_NODE_INDEX_ENABLED` in `.yaml` templates instead of disabling the new feature flag.
After some discussion it's seems now that `ROX_NODE_INDEX_ENABLED` being disabled in collector was a relic from the previous release since the feature had not gone GA yet. There should be no unexpected behavior by removing it from the template and defaulting the feature flag to enabled
Discussed the implications of doing this, [Slack Thread](https://redhat-internal.slack.com/archives/C073B14UE10/p1739366358737919?thread_ts=1739294931.668939&cid=C073B14UE10) and there should not be any problems.
Running /test gke-scanner-v4-install-tests to see if those pass, will merge when they do.
=> ROX-27719:  Scanner v4 env conflict

scanner/decisions/0014-epss-score.md, scanner/decisions/0016-epss-rhsa.md
We opted to not pursue finding the EPSS score for each RHSA's related CVE, as it was non-trivial. This just adds an ADR to reflect the updated decision.
no
no
I didn't
=> chore(scanner): update EPSS ADR for RHSAs

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.ts, ui/apps/platform/src/Containers/MainPage/Navigation/HorizontalSubnav.css, ui/apps/platform/src/Containers/MainPage/Navigation/HorizontalSubnav.tsx
1. Adds the left border to the dropdown navigation in the horizontal nav bar, for visual consistency
2. Retains the title of the current page in the dropdown toggle, when the active page is one of the child items
3. Shows the `isSelected` checkmark state of the current nav item
Before, no divider before dropdown (subtle)
After
Selecting an item from the dropdown changes the dropdown text to reflect the current page, instead of unconditionally displaying "More views". When selected, an item also shows that it is current with the `isSelected` checkmark state.
=> fix(ui): Use current page as horizontal nav title

CHANGELOG.md, central/networkgraph/aggregator/aggregator_impl.go, pkg/features/list.go
External IPs may not ship in 4.7, so this reinstates feature flags to restore backend functionality to 4.6.
=> fix(networkgraph): Reinstates external IPs feature flags

ui/apps/platform/src/Containers/Vulnerabilities/components/GenerateSbomModal.tsx
Minor text change noting that delegated scans are not supported during SBOM generation.
In the future, we should be able to detect this via the image response data and disable the option to generate an SBOM.
=> chore(ui): Add note about SBOM support for delegated scans

config-controller/internal/controller/policy_controller.go, config-controller/pkg/client/client.go, tests/policy_as_code_test.go
Extended the timeout on waiting for a policy to be created to allow for policy creation to take a few seconds
(Also fixed a random typo)
Ran the TestCreateCR test, as well as the entire Policy as Code suite and they passed
=> ROX-27441: Fix Policy As Code CI Flakes

ui/apps/platform/src/Containers/MainPage/Navigation/HorizontalSubnav.tsx, ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCveViewContext.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
Minor cleanup items for the CVE split, one commit per one change:
1. Use a `Popover` instead of `Tooltip` for page help text
2. Minor *final* wording changes in page descriptions
3. Hide irrelevant entity tabs in Workload CVEs ("CVE" tab in the "Without CVEs" view, "Deployment" tab in the Inactive images view)
4. Revert VM breadcrumb to simply "CVE" instead of custom text for each possible view
Popovers:
Inactive images - no deployment button
Image w/o CVEs - no CVEs button
Verify all other views contain all three buttons.
Visit a CVE detail page and see the basic "CVEs" breadcrumb at the top:
=> fix(ui): Minor visual tweaks to Platform CVE split

pkg/registries/types/types.go, sensor/common/registry/registry_store.go, sensor/common/registry/registry_store_test.go, sensor/common/scan/scan.go
As part of our dog fooding efforts, we realized that we partially did not understand the scan errors. These are customer visible because they are surfaced in the administration events. We figured if we had problems, some customers might have similar problems. See also https://github.com/stackrox/stackrox/pull/13928, which fixes a problem with incorrect URL constructions in some cases.
This is an attempt to make scan request error messages slightly more contextual. These errors can quickly become hard to read because the errors of every registry attempt are concatenated.
I introduce two small changes which I think make the error message a bit easier to understand:
* more verbose integration type to easier identify (global) pull secret based integrations.
* separation by pull sources to …
=> chore: improve scan error message

sensor/kubernetes/main.go, sensor/kubernetes/sensor/options.go, sensor/kubernetes/sensor/sensor.go
If ACS is installed using the CRS method, the fake-workloads will not work due to `Fetching Sensor's Ownership` and `Fetching Deployment Identification` logics. This is because the fake-workloads mock the kubernetes client and that mocked client does not contain `sensor's deployment`, nor the `kube-system` and `stackrox` namespaces.
There are two ways I can see of fixing this issue:
1. Inject a real (meaning connects to the cluster's API) k8s client to the `fetcher` logics so we can retrieve this information. 
2. Fake these resources (`sensor's deployment`, `kube-system` namespace, etc) in the fake k8s client. 
I opted for (1) as it seems simpler but this breaks `local-sensor`'s ability to run completely offline. I do think we should implement (2) later if possible.
=> fix(fake-workloads): Inject real k8s client to identify sensor

tests/roxctl/bats-tests/cluster/scanner-upload-db.bats
We have some instability in bats tests when a larger zip file is downloaded. I have added a few modifications to the curl call to see if that will improve its stability.
Also curl logs should be better now to actually see the failure reason.
=> ROX-27199: Tweak download scanner-vuln-updates curl

.github/workflows/performance-tests.yml
Currently, every PR runs wait on images from the `Performance tests` workflow. We want jobs from this workflow to run only when the label is set on PR.
X
=> chore(ci): Adjust CI performance tests rules

tests/upgrade/postgres_run.sh
https://spaces.redhat.com/display/StackRox/Upstream+Release+Automation#UpstreamReleaseAutomation-update-upgrade-testUpdateUpgradeTest
CI
=> chore(upgrade): Bump 4.4 previous version in upgrade test to 4.4.8

tests/upgrade/postgres_run.sh
https://spaces.redhat.com/display/StackRox/Upstream+Release+Automation#UpstreamReleaseAutomation-update-upgrade-testUpdateUpgradeTest
CI
=> chore(upgrade): Bump 4.5 previous version in upgrade test to 4.5.6

.github/workflows/scripts/patch-changelog.sh, CHANGELOG.md
This has been bothering me for so long. Finally took the time to fix it.
no
Ocular inspection
=> chore(ci): fix spelling of CHANGELOG update

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/hooks/useIsFirstRender.ts
The test flakes for ROX-26843 happen when a test asserts that the filters for a GraphQL request match "Severity: Critical, Important", but instead the test received "Severity: Critical, Important, Moderate, Low". This page does in fact always sent the latter, followed by the former, due to the default filters being applied and a second request being sent to the server.
The tests _do_ account for the double request, but every couple weeks or so there is a failure as if a request was "missed".
I have not figured out exactly why this happens, but a better fix is to simply not request the CVE list twice when the user visits the page. This change does so by tracking the first render of the WorkloadCvesPage (default filters only apply on the first render) and substituting the default filters in …
=> ROX-26843: Applies default filters before the first request is sent

central/platform/reprocessor/reprocessor_impl.go, central/platform/reprocessor/reprocessor_impl_test.go
This PR removes the `needsReprocessing*` functions as they are redundant. These functions were previously used to determine if reprocessing was necessary by running a query to check for relevant entries. However, the same query is executed again in the reprocessing loop to fetch and process the data. This results in two identical queries—one for checking and another for fetching. Since the reprocessing loop already verifies whether the query returns any data, we can rely on that check and eliminate the `needsReprocessing*` functions to avoid unnecessary duplication.
CI
=> ROX-27974: remove needs reprocesing check

.github/workflows/unit-tests.yaml
Add possibility to run go-postgres test step with multiple PostgreSQL versions.
=> ROX-20769: Run go-postgres with multiple versions

pkg/postgres/pgutils/utils.go
Currently migrations are applied as a mix of GORM and raw SQL. For the latter it's convenient to respect DryRun mode, which could be used for tooling around migrations, e.g. to take a frozen snapshot to use as a base for tern.
Manually verified the result withing a tool to take snapshots.
=> ROX-28128: Respect DryRun mode when applying migrations

scripts/release-tools/kube-burner-configs/cluster-density/deployment.yml
Currently the process spawning rate is 10, which is roughly 10 processes per second per worker. Normally we got 8 cores on release cluster nodes, meaning that it produces 80 processes/s for a single Collector. If there are less nodes that berserkers, some of them land on the same machine making load even higher.
This leads to situations, when the load is just too high to get any meaningful results, making the whole setup unstable and imbalanced. As a workaround for now, reduce spawning rate, to produce milder load.
change me!
Not validated yet.
=> chore(load-generators): Reduce process load

ui/apps/platform/src/Containers/MainPage/Navigation/NavigationSidebar.tsx
I discovered this problem when I was translating it into Chinese:
These two fields should be written in reverse.
=> fix(ui): Update NavigationSidebar.tsx

ui/apps/platform/src/Containers/Integrations/utils/integrationsList.ts, ui/apps/platform/src/types/featureFlag.ts
This feature flag has been enabled since 2024-06-06 in #11389
https://github.com/stackrox/stackrox/tree/master/ui/apps/platform#delete-a-feature-flag-from-frontend-code
By the way, the notifier has conditional rendering by central capabilities:
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Integrations/IntegrationTiles/NotifierIntegrationsSection.tsx#L33-L35
=> ROX-28160: Delete ROX_ACSCS_EMAIL_NOTIFIER feature flag from ui code

pkg/containers/detection.go, pkg/containers/detection_test.go, pkg/docker/detection.go, roxctl/central/generate/generate.go
The `OutputZip()` function in roxctl does not actually always output a zip file to stdout, even though it says that it does. However making it always do this could now pose a problem for existing docker setups using the logic of `roxctl central generate k8s pvc` where is puts the output into an output path iff `ROX_ROXCTL_IN_MAIN_IMAGE` is unset. 
But the output path is populated by default so checking if that's unset does not work. I propose fixing this problem by checking if we are running inside a docker container, and always outputting the zip to `STDOUT` if we are not. That way the behavior of `roxctl central generate k8s pvc` matches its description.
Alternative idea: Change the description of `roxctl central generate k8s pvc` and explain that it only prints the output to STDOUT if …
=> ROX-20811: Roxctl central generate pvc bug

CHANGELOG.md, sensor/admission-control/manager/evaluate_deploytime.go, sensor/admission-control/manager/images.go, sensor/admission-control/manager/responses.go, sensor/admission-control/resources/deployment.go
There exist 3 ways of scaling a deployment in k8s/Openshift:
1. Update the deployment spec for the `replicas` property.
2. Use `kubectl scale` or `oc scale` on the deployment.
3. Use the `v1/autoscaling scale` subresource (Openshift console uses this)
The admission controller has existing support to run policy detection and enforcement on 1. and 2. above. However, it was missing support for the `scale` subresource. This PR adds that support.
While I was at it, I also fixed a small product branding miss in the output messages/response of the admission controller when the request is denied.
Testing on an Openshift cluster with admission controller enabled for 3 scenarios:
1. Use Openshift console to scale a deployment that violates the enforced latest tag policy. Operation is disallowed. …
=> ROX-13493: Add admission controller support for Scale subresource

tests/e2e/lib.sh
Accept empty CI_JOB_NAME environment variable for local execution of tests.
I have noticed that I cannot execute the scaner V4 tests locally due to an uninitialized `CI_JOB_NAME` environemnt variable.
This should be an easy fix.
=> fix: Accept empty CI_JOB_NAME environment variable in e2e test lib

pkg/search/postgres/common.go, pkg/search/postgres/select_query_test.go
This PR updates the search framework to include NULLS LAST in the ORDER BY clause, ensuring that null values appear last when sorting by EPSS scores.
-->
change me!
change me!
=> ROX-27970: Add fix to return nulls last in sorted list

pkg/search/postgres/common.go, pkg/search/postgres/common_test.go, pkg/search/postgres/joins.go, pkg/search/postgres/select.go
Updates to bypass the the custom image cve and component join logic when using the new data model.  That directed join logic is no longer valid with the new model and should be completely bypassed.
Updated the unit test.  Ran it with the `ROX_FLATTEN_CVE_DATA` set `true` and with the flag set to `false`.  Further testing will occur as additional changes are implemented to get the data out of the system to support the various workflows.
=> ROX-28196: CVE data model search framework updates

deploy/common/env.sh, deploy/common/k8sbased.sh
Use dedicated priority class for collector pods.
We have two worker nodes -- A & B -- and most StackRox workloads have been -- for some reason -- scheduled on node A. Later in the deployment flow, when the collector DaemonSet was about to be deployed, there were no resources left for deploying a collector pod on node A. Hence the deployment and consequently the scanner V4 install test suite failed.
Use pod priority classes and configure the collector pods to be of higher priority class allowing preemption of lower-prio class pods to free up resources on full nodes.
I have enabled using prio classes by default in our deployment scripts.  But it can be disabled explicitly.
=> ROX-27727: Use dedicated priority class for collector pods

qa-tests-backend/codenarc-rules.groovy, qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy, qa-tests-backend/src/main/groovy/orchestratormanager/OpenShift.groovy, qa-tests-backend/src/main/groovy/orchestratormanager/OrchestratorMain.groovy, qa-tests-backend/src/main/groovy/util/Env.groovy
This PR adds types to Kubernetes.grooovy to make it easier to reason what will be returned from the method.
The goal was to enable `@CompileStatic` on Kubernetes.groovy. It was done partially as I don't know why some methods crashes the compiler (`Execution failed for task ':compileGroovy'. > java.lang.StackOverflowError (no error message)`) I annotated problematic methods with `@CompileDynamic`. I annotated other classes with `@CompileStatic` as well as this make it easier to enable `@CompileStatic` on Kubernetes.
I need to disabled `codenarc` rule as we have `create*` methods that returns `void`. We can fix it in the future but I tried to have minimal PR.
CI
=> chore(qa): add types to Kubernetes helpers

central/docs/api_custom_routes/.gitignore, central/docs/api_custom_routes/README.md, central/docs/api_custom_routes/image_service_swagger.yaml, pkg/apiparams/sbom.go
Adds a manually crafted OpenAPI / Swagger spec to the repo for the SBOM generation API that is/was used for building the associated docs - which are not generated automatically (currently).
This location may be temporary until when/if a broader strategy is defined (captured in ROX-28173)
N/A
Via the https://editor.swagger.io/ (validates formatting, etc.), generating ascii docs using [openapi-generator-cli](https://hub.docker.com/r/openapitools/openapi-generator-cli), and further cleaning up with [rhacs-api-docs-gen](https://github.com/gaurav-nelson/rhacs-api-docs-gen)
```
swagger_dir=~/Downloads/swag
cd $swagger_dir
docker run --rm -v "$swagger_dir:/local" openapitools/openapi-generator-cli generate -i /local/swagger.yaml -g asciidoc -o /local/out/asciidoc
cd …
```
=> ROX-27607: create swagger doc for SBOM custom route

qa-tests-backend/src/test/groovy/CertExpiryTest.groovy
Scanner integration registration can take another while after scanner pod is up and healthy.
Retry 5x with 5 second delay.
Details in the ticket.
=> ROX-28141: fix race with scanner integration registration

go.mod, go.sum, operator/api/v1alpha1/overlay_types.go, operator/bundle/manifests/platform.stackrox.io_centrals.yaml, operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml, operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/crd/bases/platform.stackrox.io_centrals.yaml, operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml, operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml, operator/internal/overlays/postrenderer.go
Solves https://issues.redhat.com/browse/ROX-27333
- actual support was added in https://github.com/stackrox/k8s-overlay-patch/pull/25
- this just adds the field to our types and adjusts some docs
Docs will be added in scope of related https://issues.redhat.com/browse/ROX-27332
This is not visible in the form view. The help text in the YAML view looks reasonable:
Tested manually with roughly:
```
$ cd operator
$ make install run
$ kubectl apply -n stackrox -f operator/tests/common/central-cr.yaml
$ oc get cm -n stackrox -o jsonpath='{.data.postgresql\.conf}' central-db-config|grep max_connections
max_connections = 100
$ kubectl edit -n stackrox centrals.platform.stackrox.io stackrox-central-services
$ oc get cm -n stackrox -o jsonpath='{.data.postgresql\.conf}' central-db-config|grep …
```
=> feat(operator): support verbatim overlay values

pkg/env/scannerv4.go, pkg/features/list.go, pkg/scannerv4/mappers/mappers.go, pkg/scannerv4/mappers/mappers_test.go
For readability purposes, I figured it's easier to keep all Scanner V4 feature flags together. This PR also converts `ROX_SCANNER_V4_PARTIAL_NODE_JS_SUPPORT` into a changeable feature flag. It seems more like a feature rather than a configuration for using a feature, so it may make more sense here.
These changes are all invisible to users.
I didn't
=> chore(scanner): group Scanner V4 feature flags together

scripts/ci/lib.sh
Enables images prefetching for scanner V4 installation tests, nothing else.
This is part of a bunch of changes to the scanner V4 installation test suite to make it less flaky.
=> tests: Enable image prefetching for Scanner V4 Install Tests

pkg/concurrency/retry_ticker.go, pkg/concurrency/retry_ticker_test.go, sensor/kubernetes/certrefresh/localscanner_tls_issuer.go, sensor/kubernetes/certrefresh/localscanner_tls_issuer_test.go, sensor/kubernetes/certrefresh/securedcluster_tls_issuer.go, sensor/kubernetes/certrefresh/securedcluster_tls_issuer_test.go, sensor/kubernetes/certrefresh/tls_issuer_common.go, sensor/kubernetes/certrefresh/tls_issuer_common_test.go
This PR adds explicit handling for Sensor offline mode in the TLS issuer components. As these components cannot do anything useful in offline mode, the certificate refresh logic is now only active when Sensor is online.
(note: the TLS issuer was already resilient to Sensor being offline due to its retry mechanism)
Main changes:
* start the certificate refresher only when the component is both started *and* online
* changed behavior of Start / Stop so that they can be called in the wrong order (e.g. calling Start several times in a row is now fine)
* Perform the Central capability check when Sensor enters online mode
* integration tests that cycle through online and offline modes
* unit test for Central capability check
* some testing code clean-up
Manual smoke test that shows that the …
=> ROX-27394: Sensor offline mode support in TLS issuer

tests/e2e/run-scanner-v4-install.bats
For test stability, replace remaining occurrences of plain `kubectl` with `ORCH_CMD`, which points to the retrying `kubectl` wrapper.
=> test: (scanner-v4-install) Use ORCH_CMD instead of kubectl

central/reprocessor/reprocessor.go, central/reprocessor/reprocessor_unit_test.go
We need to fetch the image again to make sure all fields are populated. `GetImage` will internally call a `Merge` function which will use the CVEEdges table to enrich fields like `FirstImageOccurrence` and `FirstSystemOccurrence`.
- Deploy ACS
- Deploy a nginx
- Create a System Policy with the `Days since CVE was first discovered in image` criteria set to `0`
- ☝️ This should generate violations for the nginx deployment
- To speed up the test set `ROX_REPROCESSING_INTERVAL` to 10 minutes in central
- Observe the violations do not get resolved after the reprocessor is triggered
=> ROX-21497: Re-fech image if the scan was updated

tests/e2e/run-scanner-v4-install.bats
The current behaviour wrt handling of old roxctl's was bogus: if a user passed a path containing an existing old copy of roxctl to prevent re-downloading and thus speed up the test suite invocation, at the end this (pre-existing!) roxctl version was deleted. To keep things simple I have removed the deletion entirely. Alternative would have been to keep track of whether is has been downloaded or not but I doubt this would be worth the effort. This file is downloaded into a tmp directory and thus it should not persist for particularly long on host systems (host system being either CI or a local dev workstation).
This also fixes a bug in the test suite where an access to `EARLIER_ROXCTL_PATH` could happen during `teardown_file()` if, for some reason, `setup_file()` threw an error before that …
=> test: (scanner-v4-install) Simplify handling of old roxctl version

roxctl/central/generate/generate.go
Fixing the behavior of `roxctl central generate k8s pvc` in https://issues.redhat.com/browse/ROX-20811 lead to unexpected consequences of our `deploy` script dumping the zip file into STDOUT like this:
```INFO:   Generating deployment bundle...
INFO:   Deployment bundle does not include PodSecurityPolicies (PSPs).
INFO:   This is incompatible with pre-v1.25 Kubernetes installations having the PodSecurityPolicy Admission Controller plugin enabled.
INFO:   Use --enable-pod-security-policies if PodSecurityPolicies are required for your Kubernetes environment.
PK^C^D^T^@^H^@^@^@<B1>]ZZ^@^@^@^@^@^@^@^@^@^@^@^@^]^@   ^@helm/chart/templates/_psp.tplUT^E^@^A<CE><F0<F0><BE>g{{/*
srox.autoSensePodSecurityPolicies $
*/}}
{{ define "srox.autoSensePodSecurityPolicies" }}
{{ $ := index . 0 }}
{{ …
```
=> ROX-28249: Disable new roxctl zip output

CHANGELOG.md
ROX-26763 was missing a changelog entry.
I plan to backport this PR to release-4.7
=> ROX-26763: add changelog entry (zombie process errors)

image/postgres/scripts/docker-entrypoint.sh, scanner/image/db/scripts/docker-entrypoint.sh
Sometimes I like to look at the upstream script https://github.com/docker-library/postgres/blob/master/15/bookworm/docker-entrypoint.sh and ensure we inherit the latest changes. This is what this PR is all about. It takes in all the latest changes while keeping our own StackRox changes.
I do not plan on merging this until 4.7 development is over.
no
If it runs, it runs.
Note: most of the changes to `image/postgres/scripts/docker-entrypoint.sh` were already present in `scanner/image/db/scripts/docker-entrypoint.sh` because the latter was last updated more recently. For a set of differences between the two files after this is merged:
```
$ diff -du image/postgres/scripts/docker-entrypoint.sh scanner/image/db/scripts/docker-entrypoint.sh
--- image/postgres/scripts/docker-entrypoint.sh …
```
=> chore(postgres): inherit latest upstream changes

tests/e2e/run-scanner-v4-install.bats, tests/e2e/run-scanner-v4-install.sh, tests/scripts/setup-certs.sh
The core idea here is that:
1. Support a runtime mode for [printing logs to fd 3](https://bats-core.readthedocs.io/en/stable/writing-tests.html#file-descriptor-3-read-this-if-bats-hangs).
2. Using fd redirection magic we provide a post-processor for stdout and stderr, which causes all messages emitted our deployment machinery to be properly prefixed, including a test step identifier.
We make sure to spawn the post-processor in a dedicated sub-shell to have the fd management explicit. Otherwise some Bash optimization (?) would kick in on this code
```
exec \
1> >(bash -c "post_process_output '$label'" > "/dev/fd/$outfd") \
2>&1
```
which would then start the post-processor as part of the **current** shell, even though it is running in the background(?!). During my tests this turned out to …
=> test: (scanner-v4-install) Use pretty real-time logging

sensor/kubernetes/certrefresh/securedcluster_tls_issuer.go, sensor/kubernetes/certrefresh/securedcluster_tls_issuer_test.go
https://github.com/stackrox/stackrox/pull/13596 introduced a segmentation fault, when calling deactivate() on a TLS issuer that is not started.
Added a unit test that is crashing without the change.
=> ROX-28258: Fix segfault when calling deactivate on stopped TLS issuer

ui/apps/platform/cypress/integration/violations/Violations.helpers.js, ui/apps/platform/cypress/integration/violations/violations.test.js, ui/apps/platform/src/Containers/Violations/ViolationsTablePage.tsx, ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
Uses some recent patterns to re-enable an old, skipped + flagged Violations test that checks sorting by severity.
1. Simplify `interactAndWait` calls
2. Remove Cypress `wait` commands
3. Add attribute to table body to hook onto for a request "complete" notifier*
* This would be better handled with a proper polling state/UI implemented in TBodyUnified, but it works for now as the _only_ method of detecting that the request has finished via user-visible DOM properties.
Local Cypress run:
=> ROX-14054: Re-enable violations sort by severity test

ui/apps/platform/src/Containers/ComplianceEnhanced/searchFilterConfig.ts, ui/apps/platform/src/Containers/Vulnerabilities/searchFilterConfig.ts
Found during planning for potential future `Advisory ID` search filter config.
Two changes to add another search filter config:
1. Add module-scope assignment.
2. And then corresponding variable in `export { … };` statement.
All references are one or more via `import { … }` statement, never all of them.
One change to add another search filter config: 
1. Add `export const whateverElseSearchConfig` assignment statement.
main.js 0 = 4646307 - 4646307
total 0 = 11566078 - 11566078 so neutral after webpack
files 0 = 177 - 177
1. Visit …
=> chore(ui): Reduce effort to add search filter config in ui

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts
Prerequisite for future demo with realistic data (by temporary code changes).
Tentative decision by cross-team to omit **Advisories** column for deployment, for which image becomes and extra level of aggregation:
* to preclude potential scale problem
* to reduce backend effort
* maybe not as intuitive nor useful for customers?
From frontend viewpoint, it that decision changed, then apply same changes to DeploymentVulnerabilitiesTable.tsx file.
1. Edit table.utils.ts file.
* Add `formatTotalAdvisories` function.
2. Edit ImageVulnerabilitiesTable.tsx file.
* Add conditional rendering for **Advisories** table column.
3. Edit ImagePageVulnerabilities.tsx file.
* Add `totalAdvisories` to `filterManagedColumns` function call.
Forgot this at first, although in the back of my mind, something …
=> ROX-28037: Render Advisories column without GraphQL data

go.mod, go.sum
Fixes: https://osv.dev/vulnerability/GHSA-6wxm-mpqj-6jpf 
Backports: 
- https://github.com/stackrox/stackrox/pull/14017
=> chore(deps): bump glog to 1.2.4

qa-tests-backend/src/test/groovy/CSVTest.groovy, qa-tests-backend/src/test/groovy/DeploymentTest.groovy, qa-tests-backend/src/test/groovy/Services.groovy
This will (hopefully) fix some CI flakes that occur with the Groovy `DeploymentTest`. The issue may have been caused by the fact that the test does not wait for scanner to actually complete the scan of the image, just that scanner was able to successfully initiate a scan, this should hopefully rectify that by making it wait for vulnerabilities to be found before it proceeds out of the test setup.
Re-ran the groovy tests a few times, `DeploymentTest` seems to be passing, though it wasn't a common CI failure before. At the very least, this change doesn't seem to have made the flakes any worse or created any new ones.
=> ROX-27626: DeploymentTest CI Flakes

tests/e2e/run-scanner-v4-install.bats
This change allows for some simple time profiling introspection to learn which test steps take within the test suite take particularly long.
I don't know yet where to put this, but here's a small Python script (portable through Nix), which creates bar plots from a run log:
```python
#! /usr/bin/env nix-shell
#! nix-shell -i python3 -p python3 python3Packages.matplotlib python3Packages.pandas python3Packages.seaborn
import json
import pandas
import matplotlib.pyplot as plt
import seaborn
import re
from itertools import chain
import sys
TIMING_DATA_PATTERN = re.compile(r"INFO: .*: .*TIMING_DATA: (.*)")
def extract_timing(line):
if match := TIMING_DATA_PATTERN.match(line):
return [json.loads(match.group(1))]
return []
def load_data(input_stream):
return …
```
=> test: Emit time profiling data in scanner-v4-install test suite

go.mod, go.sum
Fixes [`CVE-2025-22868`](https://access.redhat.com/security/cve/cve-2025-22868)
- https://github.com/golang/go/issues/71490
CI
=> chore(deps): bump oauth2 fork

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx
Apparently some URLs were changed in the docs 4.7 and many links are 404 now. This fixes the link for Node scanning with scanner V4.
Currently, the link is generated as ([click](https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes/4.7/html/operating/manage-vulnerabilities/scan-rhcos-node-host#understanding-node-cves-scanner-v4_scan-rhcos-node-host)):
```
https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes/4.7/html/operating/manage-vulnerabilities/scan-rhcos-node-host#understanding-node-cves-scanner-v4_scan-rhcos-node-host
```
whereas the working link (for 4.6 and 4.7) is ([click](https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes/4.6/html/operating/managing-vulnerabilities#unde …
=> ROX-27943: Fix link to the docs

.github/workflows/batch-load-test-metrics.yml, .github/workflows/build.yaml, .github/workflows/ci-failures-report.yml, .github/workflows/lint.yml, .github/workflows/scanner-build.yaml, .github/workflows/scanner-db-integration-tests.yaml, .github/workflows/scanner-versioned-definitions-update.yaml, .github/workflows/style.yaml, .github/workflows/unit-tests.yaml, scale/signatures/deploy.yaml, tests/e2e/run-e2e-tests.sh
PR #14259 has introduced new version of stackrox-test image, but only for go-postgres tests. Switch everything else as well.
=> ROX-20769: Update everything to stackrox-test-0.4.6

central/cve/converter/utils/convert_utils_v2.go, central/image/datastore/singleton.go, central/image/datastore/store/common/metrics.go, central/image/datastore/store/common/v2/metrics.go, central/image/datastore/store/postgres/store_test.go, central/image/datastore/store/v2/postgres/store.go, central/image/datastore/store/v2/postgres/store_test.go
Updates to the image store to populate the data for the updated model.  This is absolutely based off the existing image store.  The CVE and Components are tied to the image.  Thus there is a lot of logic to make sure things are updated correctly and that all the updates are done under a transaction.  I did however write https://issues.redhat.com/browse/ROX-28222 to look at refactoring this so that all the logic isn't buried in a bespoke store and perhaps bubble the logic up to the datastore later if we have time.
Updated and expanded unit test.  Executed clusters locally with the feature flag enabled to ensure the data is getting populated as expected as data is scanned.
=> ROX-27402: CVE data model image store pr 5

central/auth/m2m/kube_service_account.go, go.mod, pkg/auth/authproviders/iap/backend_impl.go, pkg/auth/authproviders/validate_test.go, pkg/auth/tokens/claims.go, pkg/auth/tokens/issuer_factory.go, pkg/auth/tokens/options.go, pkg/cloudproviders/gcp/identity_token.go, pkg/grpc/authn/extractor.go, pkg/grpc/authn/extractor_test.go, pkg/jwt/facade.go, pkg/jwt/keys.go, pkg/jwt/parser.go, pkg/jwt/tokens.go, sensor/common/certdistribution/service_impl.go, sensor/kubernetes/sensor/deployment_identification.go
Currently we have both v3 and v4 in our dependencies. This will fix this.
> Version 3, in this repo, is still receiving security fixes but not functionality updates.
https://github.com/go-jose/go-jose?tab=readme-ov-file#versions
Refs: 
- https://github.com/stackrox/stackrox/pull/10480
- https://github.com/sigstore/sigstore/pull/2000 – once it will be merged and released we will drop v3 requirement
CI
=> chore(deps): upgrade go-jose to v4

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AdvisoryLinkOrText.tsx
Thank you **Shubha** for observing during demo that **No advisory** has potential problems:
* **Not applicable** is more accurate for non Red Hat images.
* **No advisory** even for Red Hat images means no Red Hat advisory, but could be misunderstand as no advisory from any source (for example, GitHub Security Advisory).
Therefore:
* Retain empty string in API response and report CSV file.
* Replace with hyphen as the conventional absence value in UI, which has 48 results in 33 files.
Time will tell whether we also replace **No advisories** for the count.
=> ROX-28322: Render hyphen for no advisory

ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx
Changes the Policy field "Exposed port" from a number to a text type. This allows adding range characters, which
are supported by the backend and allowed for other similar policy fields. At long last...
Fixes https://github.com/stackrox/stackrox/issues/12932
=> ROX-27875: Change "Exposed port" from number to text input type

tests/e2e/run-scanner-v4-install.bats
Previously the test simple checked "is there a deployment by the name so and so?", which makes sense, for example, after having deployed the stack initially and checking if this ACS deployment also includes specific Kubernetes deployments or not.
But currently we are also using the same function after we are disabling a component (scanner V4) through a CR and we want to make confirm that this change yields a deletion of the existing deployments. Currently we are waiting for either 30 seconds or two minutes (in the operator case) and expect this to be sufficient. But I have seen CI failures due to this *not* being sufficient. It is likely that the deletion of the respective Kubernetes deployments has been initiated but not completed.
The easy (and not so nice) "solution" would be to just …
=> test: Improved logic for detecting deletion of deployments

.github/workflows/fixxxer.yaml
[Work around](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs) for the [problem](https://github.com/orgs/community/discussions/25702) of GH disallowing triggering of workflows on pushes done using the default `GITHUB_TOKEN`.
In theory only the change on `github-push-action` call is needed, but I had seen reports where people saw this action reusing the credentials left in place by the checkout action, so let's keep it safe.
No easy way to test if this works 100% correctly without merging first 😢 
Let's YOLO it in and check. Nobody will suffer if it does not from the start.
=> fix: use different token for fixxxer

roxctl/central/generate/generate.go, roxctl/central/generate/k8s.go, roxctl/common/flags/annotations.go
It's a somewhat ugly solution, but it seems that the best way to not break existing behavior while also making `roxctl central generate...` output zip files is to add another flag.
Currently we have an `--output-dir` flag which specifies which file to write the bundle to, this defaults to `central-bundle`. The usage of this flag is overridden iff `ROX_ROXCTL_IN_MAIN_IMAGE` is set to `false`, in which case the output happens in `STDOUT`. However in ROX-28249 it's pointed out that the default should be a zip output into `STDOUT`, not a file, according to decoumentation.
I've added a flag that is true iff `output-dir` is set *manually* only. Otherwise the default value would make it so we won't have zip outputs even when we don't set it. This should also make the deploy script not break …
=> ROX-28249: Fix roxctl usage in deploy script and scanner tests

tests/delegated_scanning_test.go
Addresses Delegated Scanning Test failures caused by Central incorrectly reporting an active connection to a cluster. When a delegated scan is attempted, if Central reports there is `no connection` to the cluster, the scan will be retried.
Also adds to the test output logs for the actual error returned from the Central API.
CI
=> ROX-26663: dele scan tests flake: no connection

scanner/indexer/indexer.go, scanner/internal/httputil/doc.go, scanner/internal/httputil/transport.go, scanner/internal/httputil/transport_mux.go, scanner/internal/httputil/transport_test.go, scanner/matcher/matcher.go
This completes what https://github.com/stackrox/stackrox/pull/10680 originally hoped to complete. The original solution did ensure Scanner V4 Indexer could reach registries with untrusted certificates; however, it did not account for Claircore being unable to handle it.
Scanner V4 Indexer uses a single instance of a `libindex.Libindex` which is initialized upon startup. The issue is that this struct requires an `http.Client` upon initialization. Before this change, this client was completely unaware of the possibility of an insecure registry, so it did not skip TLS verification, even though Scanner V4 Indexer did skip it in steps prior to passing the request down to Claircore.
This change updates the client we give to `libindex.Libindex` to one which can handle insecure registries as well …
=> ROX-28192: skip TLS verification for insecure registries

config-controller/internal/controller/policy_controller.go
This adds an event filter to the Policy Controller, which should make it not trigger reconciliations when the status of the CR is updated, only when the spec of the CR is updated.
Confirmed that creating/updating a policy only triggers one reconciliation per event, and confirmed that changes were reflected in central.
```
➜  manifests kubectl apply -f test-sp.yaml 
securitypolicy.config.stackrox.io/test-security-policy created
➜  manifests kubectl logs config-controller-865c9c6c67-64zh6 
pkg/client: 2025/03/06 20:14:40.455359 client.go:229: Error: Failed to exchange token: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 34.118.224.60:443: connect: connection refused"Failed to initialize client. Will continue to retry...
pkg/client: …
```
=> ROX-28381: Add Event Filter to Policy Controller

sensor/common/registry/registry_store.go
Adds a log for when Sensor's registry store is cleared. This store holds the delegated registry config which is used to determine if images should be indexed by Sensor or sent to Central.
This log will help troubleshoot future CI failures like [this one](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-nightlies-ocp-4-18-nongroovy-e2e-tests/1896356824681025536) in which a scan should have been handled by Sensor but was instead sent to Central.
```
image "icsp.invalid/rhacs-eng/qa@sha256:68b418b74715000e41a894428bd787442945592486a08d4cbea89a9b4fa03302" not flagged as cluster local which is expected for any delegated scans, most likely the scan was NOT delegated, check Central/Sensor logs to confirm}
```
The decision on whether or not to scan an image …
=> ROX-26663: add log when registry store cleared

deploy/charts/monitoring/dashboards/stackrox-core-dashboard.json
This PR is tweaking CPU panels in Grafana `Core Dashboard`.
Main reason for changes are:
- we use percentage and the calculated value is a percentage of 1 vCPU. That can be misleading, because there could be an assumption that the percentage is based on the CPU limit
- when using percent for Y-axis, it's capped to 100% and CPU utilization with 1+ Cores is not visible
- we use `1m` time range for `rate` function. Better solution is to use `$__rate_interval`, a global Grafana variable that will be properly set by Grafana based on selected time range
Made changes:
- remove percentage calculation (`*100`)
- use variable rate range provided by Grafana (`$__rate_interval `)
- removed `Percent` for Y-axis, because it's not representing percentage anymore and added `[Cores]`
- changed line …
=> chore(release): Tweak CPU usage for Core Grafana dashboard

tests/roxctl/bats-tests/cluster/scanner-upload-db.bats
We simply have problems with downloads. Test does not run for long, `~30sec` to download and upload zip. This also tests full flow and validates that central works properly with generated vulnerability definitions.
This PR is trying to improve the curl call to be stable.
=> ROX-28102: Set curl to retry on any error

.devcontainer/devcontainer.json, .github/workflows/batch-load-test-metrics.yml, .github/workflows/build.yaml, .github/workflows/ci-failures-report.yml, .github/workflows/fixxxer.yaml, .github/workflows/lint.yml, .github/workflows/scanner-build.yaml, .github/workflows/scanner-db-integration-tests.yaml, .github/workflows/scanner-versioned-definitions-update.yaml, .github/workflows/style.yaml, .github/workflows/unit-tests.yaml, .openshift-ci/Dockerfile.build_root, .openshift-ci/dev-requirements.txt, BUILD_IMAGE_VERSION, go.mod, operator/bundle_helpers/requirements-gha.txt, scale/signatures/deploy.yaml, tests/e2e/run-e2e-tests.sh
This PR bumps Go version in builder/test images to allow upgrading cosign:
- https://github.com/stackrox/stackrox/pull/14430
CI
=> chore(deps): bump Go to 1.23.6

pkg/gjson/row.go, pkg/gjson/row_test.go, pkg/printers/csv.go, pkg/printers/table.go, roxctl/common/printer/tabularprinter_factory.go, roxctl/maincommand/command_tree_debug.yaml, roxctl/maincommand/command_tree_release.yaml
Adds an option --required-headers that marks the provided headers as required for the table that roxctl prints. If the entry for that header is empty, the whole row is not printed.
Added a test case to gjson printers, might add more tests tomorrow.
=> ROX-8844: Allow conditionally leaving out empty rows

pkg/env/max_parallel_scans.go, sensor/common/scan/scan.go, sensor/common/scan/scan_test.go
Currently, delegated scans share a rate limiter/semaphore with sensor reprocessing and sensor-observed workloads. This can lead to issues when running scans (e.g., via CI/CD) if the sensor is simultaneously reprocessing or has been restarted.
To mitigate this, we are considering modifying the Sensor to allow a separate pool for ad-hoc roxctl requests by creating a distinct semaphore. This would ensure that a certain number of these requests can be processed independently, reducing contention with sensor reprocessing.
1. Create a new OCP cluster
2. Deploy ACS with deploy script
3. `kubectl set env -n=stackrox deploy/sensor ROX_LOCAL_IMAGE_SCANNING_ENABLED=true`
4. remove and restart sensor pod `kubectl delete pod -lapp=sensor -n stackrox`
5. `./roxctl image scan --force …
=> ROX-19276: set adhoc roxctl scan semaphore

central/sensor/service/pipeline/networkflowupdate/factory.go, central/sensor/service/pipeline/networkflowupdate/flow_store_updater.go, central/sensor/service/pipeline/networkflowupdate/flow_store_updater_impl.go, central/sensor/service/pipeline/networkflowupdate/flow_store_updater_impl_test.go, pkg/networkgraph/entity.go
We used to store 'discovered' entities at the global scope, which makes it easy to determine which clusters are accessed by an entity.
However, when considering pruning, we hit a scalability concern: for every entity, we have to verify if there is no flow using it. This search spans all the flows, which is a large set.
The proposal is to insert 'discovered' entities in every cluster they are detected. This duplicates the information, but splits the pruning cost.
Generate an entity ID scoped to the cluster an entity is discovered in. This will store a new copy every time the entity is discovered in a different cluster.
I deployed the produced image and inspected the entities inserted in the database. They all have a Cluster-scoped identifier. Also, those "discovered" entities are properly …
=> ROX-27722: Store 'discovered' entities for each cluster

tests/upgrade/postgres_run.sh
Bump update test version to released 4.5.7.
I'll let the CI pipeline run verify it.
=> chore(upgrade): Bump 4.5 previous version in upgrade test to 4.5.7

.github/workflows/scanner-versioned-definitions-update.yaml
Our `Scanner versioned vulnerabilities update` GitHub Action has been failing pretty consistently since last Friday (example: https://github.com/stackrox/stackrox/actions/runs/13780455617). The changes from https://github.com/stackrox/stackrox/pull/14545 moved the storage cleanup out of this workflow and into a shared, locally referenced action (i.e., after checkout). However, in this workflow, we checkout a particular git reference that isn't the HEAD of the default branch. These changes will first checkout the default branch, run the job preamble, then checkout the specific ref we need to perform the rest of the workflow.
N/A
Tested with the pr-update-scanner-vulns label; however, these changes won't be fully validated until this PR is merged.
=> fix(ci): checkout master before running preamble

govulncheck-allowlist.json
These vulns have been fixed since updating to go1.23.2. We are now on go1.23.6, so these are definitely resolved.
no
CI
=> chore(govulncheck): remove fixed stdlib vulns

tests/upgrade/postgres_run.sh
Bump update test version to released 4.6.3.
I'll let the CI pipeline run verify it.
=> chore(upgrade): Bump 4.6 previous version in upgrade test to 4.6.3

.github/workflows/ci-failures-report.yml, scripts/ci/metrics.sh
Since we have more and more flaky unit test let's add them to our weekly news. 
Because all of unit tests leaves in our repo we can replace common prefix with `./`
https://github.com/stackrox/stackrox/actions/runs/13816471195/job/38650854104
=> chore(CI): notify about top flaky unit tests

pkg/features/list.go, tests/e2e/lib.sh, ui/apps/platform/src/types/featureFlag.ts
This PR adds a feature flag for the work related to allowing the generation of vulnerability reports using filter views.
Used the same process as other feature flags
=> ROX-28477: Add feature flag for vulnerability ad hoc reports

ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesTable.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx, ui/apps/platform/src/services/DelegatedRegistryConfigService.ts
Prerequisite to clean up delegated scanning interactions.
The drag-and-drop interaction was abandoned.
* `DelegatedRegistry` type has extra frontend-only `uuid` property.
* Page component has extra code to add it to response data.
* The value is random.
David Caravello explains:
> If a path is duplicated, the back-end will ignore subsequent registry entries regardless if they have a different cluster ID or not.
> The back-end logic looks for the ‘first path’ matching the image being scanned (prefix match), once a match is found the the loop exits.
Because even `path` and `clusterId` combined is not a unique key, fall back to simple (although less than ideal) item index as key (with eslint ignore comment).
David Caravello explains:
> Once the config is setup it generally isn’t touched …
=> ROX-28324: Delete frontend-only uuid property from delegated scanning

ui/apps/platform/cypress/integration/clusters/delegatedScanning.test.js, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesList.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesTable.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedScanningSettings.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/ToggleDelegatedScanning.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx
Changes are careful not to cause merge conflict with #14493
**Cancel** button of delegated image scanning page has no effect.
This page does not follow patterns for forms:
1. Table like access control.
* **Edit** row action goes to page in edit mode, and then **Cancel** or successful **Save** goes back (to table).
* Row link goes to page in view mode, **Edit** page action renders as form, and then **Cancel** or successful **Save** goes back (to page in view mode).
2. System Configuration page.
* **Edit** button renders page in edit mode, and then **Cancel** or successful **Save** renders page in view mode.
Apply (half of) the pattern from System Configuration.
1. Initial visit to the page in view mode.
2. Add conditional rendering for **Edit** button at upper right.
3. Instead of …
=> ROX-26504: Add explicit Edit button to delegated image scanning

.github/workflows/unit-tests.yaml
To prevent cancellation of running jobs if other job in same matrix fails let's disable fail fast.
> [`jobs.<job_id>.strategy.fail-fast` applies to the entire matrix. If `jobs.<job_id>.strategy.fail-fast` is set to true or its expression evaluates to true, GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails. This property defaults to true.](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions)
CI
=> chore(CI): do not fail connected Go tests

central/sensor/service/connection/manager_impl.go
After the `sensorConnection.Run` method the connection gets never terminated. This leads to the issue that if the connection was not terminated by a error triggered in one of the sensorConnections methods it is never Terminated.
Some goroutines rely on the connection being in a running state or being properly terminated otherwise they'd block the registration of new clusters by holding onto the lock on the connection map forever.
This is suspected to be root cause of [ROX-27567](https://issues.redhat.com/browse/ROX-27656)
Context: https://redhat-internal.slack.com/archives/C08HDHC0QP8/p1741950653179639
This simple change seems to be hard to test (at least for me), because we'd have to supply a load of mocked objects to construct a case where the HandleConnection method would run into …
=> ROX-27567: terminate sensor connection after Run returns

central/alert/datastore/internal/store/postgres/bench_test.go, pkg/search/postgres/common.go, pkg/search/postgres/store.go
This PR adds a function that do not do batching in RunCursorQueryForSchemaFn and instead call callback once row is scanned. This PR also uses this function in generic store and deprecate `RunCursorQueryForSchema`
CI
=> feat(PG): create RunCursorQueryForSchemaFn

central/image/datastore/store/v2/postgres/store.go
We have 3 duplications that were solved by `pgutils.ScanRows` let's use it instead.
CI
=> ROX-28567: use ScanRows in image v2

ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx
My bad when I replaced `cpuLimit` function call with object literal on 2024-09-20 in #12631
Affects 4.6 and 4.7 release versions.
1. Improve unit tests.
3. `npm run build` in ui/apps/platform
4. `npm run start` in ui/apps/platform
1. Visit /main/policy-management/policies/?action=create and advance to **Rules** step.
2. Drag **Container CPU Limit** from **Container configuration** to rule.
3. Advance to **Review** step.
Before changes, with stray double quote character.
POST /v1/policies/dryrunjob has 400 Bad Request status.
Payload has `fieldName: "Container CPU Limit\""`
> Policy is invalid
> policy invalid error: error validating lifecycle stage error: policy configuration is invalid for deploy time: policy validation error: validation of section …
=> ROX-28495: Fix typo in Container CPU Limit policy field name

image/templates/helm/shared/templates/02-scanner-06-deployment.yaml.htpl, image/templates/helm/shared/templates/02-scanner-v4-07-indexer-deployment.yaml
This PR fixes an issue that arose in https://github.com/stackrox/stackrox/pull/13568, which inadvertently changed the way legacy certs are mounted in the `scanner` and `scanner-v4-indexer` deployments of Secured Clusters, from:
```
- name: certs-legacy
secret:
secretName: scanner-tls
optional: true
```
to:
```
- name: certs-legacy
secret:
secretName: scanner-tls
items:
- key: scanner-cert.pem
path: cert.pem
- key: scanner-key.pem
path: key.pem
- key: ca.pem
path: ca.pem
defaultMode: 420
optional: true
```
However the original version was correct, because the keys of the `scanner-tls` secret are `cert.pem`, `key.pem`, and `ca.pem`. 
This causes local scanner in 4.7.0 to not start when only the legacy certificates are present (which is the case if Central is older than 4.6.0). …
=> ROX-28352: Fix scanner-tls secret keys in deployment template

CHANGELOG.md, deploy/common/k8sbased.sh, roxctl/central/cert/cert.go, roxctl/common/tls.go, tests/e2e/lib.sh, tests/e2e/run-scanner-v4-install.bats, tests/e2e/run.sh, tests/upgrade/lib.sh, tests/upgrade/postgres_run.sh
1. Convert warning to error, as promised a long time ago.
2. Prevent retries on such an error.
```console
me@work$ bin/linux_amd64/roxctl -e localhost:8443 -p admin central whoami
ERROR:	The remote endpoint failed TLS validation. Please do one of the following:
1. Obtain a valid certificate for your Central instance/Load Balancer.
3. Use the --ca option to specify a custom CA certificate (PEM format). This Certificate can be obtained by
running "roxctl central cert".
4. Update all your roxctl usages to pass the --insecure-skip-tls-verify option, in order to
suppress this warning and retain the old behavior of not validating TLS certificates in
the future (NOT RECOMMENDED).
ERROR:	connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for …
```
=> ROX-24500: Certificate validation error in `roxctl` is an error

central/administration/events/datastore/telemetry.go, central/administration/events/datastore/telemetry_administration_events_test.go, central/administration/events/datastore/types.go, central/administration/events/testutils/testutils.go, central/main.go, pkg/administration/events/domain.go, pkg/administration/events/hints.go
Telemetry collection for administrative events, collecting total number of events and number of events by level.
Added tests, will run on CI.
=> ROX-28294: Collect telemetry for number of admin events

central/alert/datastore/internal/store/postgres/bench_test.go, pkg/search/postgres/common.go
It looks like using pgx.ForEachRow has some benefits over our current implementation. It handles memory better although it has almost the same runtime.
```
pkg: github.com/stackrox/rox/central/alert/datastore/internal/store/postgres
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
Many/walk_1_alerts-8      109.3m ± 2%   107.3m ± 2%  -1.83% (p=0.035 n=10)
Many/walk_2_alerts-8      109.2m ± 2%   107.6m ± 2%  -1.51% (p=0.011 n=10)
Many/walk_4_alerts-8      108.3m ± 2%   107.2m ± 1%       ~ (p=0.143 n=10)
Many/walk_8_alerts-8      109.2m ± 2%   108.0m ± 0%  -1.06% (p=0.023 n=10)
Many/walk_16_alerts-8     108.9m ± 2%   107.9m ± 5%       ~ (p=0.631 n=10)
Many/walk_32_alerts-8     109.6m ± 2%   108.3m ± 1%       ~ (p=0.280 n=10) …
```
=> fix(pg): use pgx.ForEachRows in walker

ui/apps/platform/package-lock.json, ui/apps/platform/package.json, ui/apps/platform/src/index.tsx
This PR will load the `monaco-editor` resources from a local dependency rather than through a CDN. 
A customer noticed that the CodeEditor displayed a "Loading..." text. It occurred because it didn't fetch resources for the `monaco-editor` using a CDN. The customer had a closed system. The following change will prevent it from fetching anything externally. 
References: 
https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#use-monaco-editor-as-an-npm-package
Before:
After:
=> ROX-28200: Load monaco-editor locally instead of CDN

scripts/retry-kubectl.sh
Include 'unable to handle the request' in error regex list for retries.
This is an attempt to reduce CI flakiness.
See https://issues.redhat.com/browse/ROX-28587.
Verified locally by pointing `$KUBECTL` to a fake script:
```
#!/usr/bin/env bash
sleep 1
echo >&2 'Error from server (InternalError): an error on the server ("Internal Server Error: \"/api/v1/namespaces/stackrox/persistentvolumeclaims?fieldManager=kubectl-client-side-apply&fieldValidation=Strict\": the server is currently unable to handle the request") has prevented the request from succeeding (post persistentvolumeclaims)'
exit 1
```
=> ROX-28587: Retry kubectl on "unable to handle the request" error

qa-tests-backend/src/main/groovy/services/BaseService.groovy
This PR sets two grpc connection setting keep alive and idle connection. The values are used arbitrary with not in depth testing as we do not use Groovy tests for benchmarking so there should not be any problem with making a connection per request. Since our most popular method of retrying accepts seconds as interval time it's ok to set keep alive every second. As some tests adds longer sleep time (e.g. to wait for sensor/collector or image scan) we can shutdown this connection after 1 minute. 
See:
- https://github.com/grpc/grpc-java/issues/7851#issuecomment-780025689
- https://stackoverflow.com/a/57930958
---
CI
=> fix(qa): add keepalive and idle connection timeout

pkg/postgres/pgutils/scan.go
Fix r instead of rows and godoc.
CI
=> fix(pg): ScanStrings should call row not rows

ui/apps/platform/cypress.config.js
Allows Cypress to retry a failed test during run mode one (1) time, in an attempt to avoid recurring, but rare, flakes that UI e2e tests cannot easily recover from. Analysis of CI problems for these tests can be found [here](https://docs.google.com/document/d/1RzEi_FzPKYask0FfeFSg3g1h6UetztNQtXMmAKrL_AI/edit?tab=t.0#heading=h.66y4kqbj468a). 
With a locally modified test suite to ensure the first instance of the test fails:
```
npm run cypress-spec violations/filteredWorkflowViews.test.ts && echo "Pass"
```
```
2025-03-21T17:57:21.318Z running test suite: filteredWorkflowViews.test.ts
Violations - Filtered Workflow Views
(Attempt 1 of 2) should filter the violations table when the "Applications view" is selected
✓ should filter the violations table when the "Applications view" is selected …
```
=> chore(ui): Enable one retry for Cypress tests

ui/apps/platform/package-lock.json
Needs to go into next 4.6 and 4.7 patch releases.
This is a patch version for a dev dependency used by `webpack-dev-server`. To test, install the latest version and run a local development server, smoke testing pages in the app.
=> ROX-26692: Updates http-proxy-middleware to latest

sensor/kubernetes/fake/flows.go, sensor/kubernetes/fake/flows_test.go
Adds external IPs to fake workload generation. We need to be able to test the external IPs feature using the existing scale tests, in which Sensor creates fake data that it itself consumes. This will enable us to find bugs that might cause crashes, scalability issues, and leaks. This will be part of the long running cluster. It will also be run with K6 load testing, though at the current moment the API endpoints relevant to external IPs is not called by K6 load testing. That change can be made later.
No code that runs in production is modified, so no testing is needed. The fake workload generation currently does not have any testing.
Scale testing was run using …
=> ROX-28479: Add external IPs to fake workload generation

ui/apps/platform/src/routePaths.ts
A user role that should see only **Dashboard** and **Violations**, also sees **Configuration Management**. Adding injury to insult, no data because RBAC errors.
I reduced RBAC resource requirements for routes in #7909
For **Configuration Management** widgets, I specified one resource per widget:
1. `PolicyViolationsBySeverity` widget: `'Alert'`
2. `ComplianceByControls` widget: `'Compliance'`
3. `UsersWithMostClusterAdminRoles` widget: `'K8sSubject'`
4. `SecretsMostUsedAcrossDeployments` widget: `'Secret'`
Here are complete resources for the queries:
1. `PolicyViolationsBySeverity` query `policyViolationsBySeverity` requires `['Alert', 'WorkflowAdministration']`
2. `ComplianceByControls` query `complianceByControls` requires `['Compliance']`
3. `UsersWithMostClusterAdminRoles` query …
=> ROX-28598: Hide Configuration Management if only Alert resource

ui/apps/platform/package-lock.json, ui/apps/platform/package.json
This applies https://github.com/stackrox/stackrox/pull/14244 to `release-4.7` branch to allow downstream builds pass with Hermeto instead of Cachito.
This change is to be followed up by a Hermeto switch for 4.7 in <https://gitlab.cee.redhat.com/stackrox/rhacs-midstream/-/merge_requests/4081>.
Related Slack discussions:
1. https://redhat-internal.slack.com/archives/C7ERNFL0M/p1737985051478809
2. https://redhat-internal.slack.com/archives/C01R0E7CVMX/p1741716667956819
3. https://redhat-internal.slack.com/archives/C02AD1GUA0Y/p1741736650355549
No change in tests.
Relying on CI here with UI tests.
Verified in https://gitlab.cee.redhat.com/stackrox/rhacs-midstream/-/merge_requests/4081 that builds work fine with Hermeto "on".
=> ROX-27838: Override npm peer depenency conflicts / 4.7

ui/apps/platform/package-lock.json, ui/apps/platform/package.json
This applies https://github.com/stackrox/stackrox/pull/14244 to `release-4.6` branch to allow downstream builds pass with Hermeto instead of Cachito.
This change is to be followed up by a Hermeto switch for 4.6 in <https://gitlab.cee.redhat.com/stackrox/rhacs-midstream/-/merge_requests/4082>.
Related Slack discussions:
1. https://redhat-internal.slack.com/archives/C7ERNFL0M/p1737985051478809
2. https://redhat-internal.slack.com/archives/C01R0E7CVMX/p1741716667956819
3. https://redhat-internal.slack.com/archives/C02AD1GUA0Y/p1741736650355549
No change.
- CI with its tests.
- Downstream build in <https://gitlab.cee.redhat.com/stackrox/rhacs-midstream/-/merge_requests/4082>.
=> ROX-27838: Override npm peer depenency conflicts / 4.6

pkg/search/postgres/common.go, pkg/search/postgres/store.go
With following code I've tested how cursor size affects the `Walk`ing time. We can significantly increase the throughput by increasing from 25 to 1000 without putting too much pressure on the database. Of course the bigger the window is the less time we spend in db queries round trips. 
```go
package postgres
import (
"context"
"fmt"
"testing"
"github.com/stackrox/rox/generated/storage"
"github.com/stackrox/rox/pkg/postgres/pgtest"
"github.com/stackrox/rox/pkg/sac"
"github.com/stackrox/rox/pkg/search/postgres"
"github.com/stackrox/rox/pkg/testutils"
"github.com/stretchr/testify/assert"
)
func BenchmarkMany(b *testing.B) {
var alerts []*storage.Alert
const alertsNum = 10000
for i := 0; i < alertsNum; i++ {
alert := &storage.Alert{}
err := testutils.FullInit(alert, …
```
=> feat(pg): increase cursor batch size

ui/apps/platform/src/Containers/ConfigManagement/Dashboard/Header/Header.js, ui/apps/platform/src/Containers/ConfigManagement/Dashboard/Page.js
Dashboard counts and widgets make requests that are doomed to fail if user roles have limited resources.
I reduced RBAC resource requirements for routes in #7909
For **Configuration Management** widgets, I specified one resource per widget:
1. `PolicyViolationsBySeverity` widget: `'Alert'`
2. `ComplianceByControls` widget: `'Compliance'`
3. `UsersWithMostClusterAdminRoles` widget: `'K8sSubject'`
4. `SecretsMostUsedAcrossDeployments` widget: `'Secret'`
Here are complete resources for counts queries in header:
1. `PoliciesTile` query `numPolicies` requires `['WorkflowAdministration']`
2. `CISControlsTile` query `numCISControls` requires `['Compliance']`
Here are complete resources for data queries of widgets:
1. `PolicyViolationsBySeverity` query `policyViolationsBySeverity` requires …
=> ROX-28599: Conditionally render on Configuration Management dashboard

ui/apps/platform/eslint-plugins/pluginGeneric.js
React Router 6 upgrade required code change (because of stricter type checking) in case `Button` element does not have `href` prop when it does have `component={LinkShim}` prop.
**Brad** and I agreed:
* Keep code change based on what TypeScript static inference understands.
* Add lint rule to enforce assumption that `Button` element with `component={LinkShim}` prop has `href` prop.
Use typescript-eslint playground to understand `attribute.value?.expression?.name === 'LinkShim'` condition corresponds to `component={LinkShim}` prop.
https://typescript-eslint.io/play/#ts=5.8.2&showAST=es&fileType=.tsx
Temporarily edit a `Button` element with `component={LinkShim}` to omit `href` prop.
By the way, you need to restart Visual Studio code after you edit lint rules.
1. `npm run lint` in …
=> ROX-28707: Add Button-LinkShim-href lint rule

scripts/ci/lib.sh
We do not create a separated issues if there are more than 5 failed tests. This lead to creation of umbrella issues that collect different failures. Let's increase limit to 10 to get more granular results in jira.
CI
=> ROX-27255: increase junit2jira threshold

sensor/kubernetes/certrefresh/securedcluster_tls_issuer.go, sensor/kubernetes/certrefresh/securedcluster_tls_issuer_test.go
The Secured Cluster TLS issuer allows only one request to Central at a time. In order to do this, it was using an atomic bool `requestOngoing`  to stop other simultaneous requests, and `ongoingRequestID` (guarded by `ongoingRequestIDMutex`) to make sure that received responses belong to the current request.
However, this approach allowed a race condition to take place when there are requests happening in quick succession, and the online / offline mode of Sensor changes. The situation was the following, as reproduced occasionally by the `TestSensorOnlineOfflineModes` test:
* request (1) is triggered
* sensor goes into offline mode, and cancels request (1)
* before request (1) manages to reset `requestOngoing`, a response arrives and it is stored in `responseFromCentral`
* request (2) is …
=> ROX-28390: Fix race condition in TLS issuer

CHANGELOG.md, pkg/booleanpolicy/default_policies_test.go, pkg/booleanpolicy/field_metadata.go, pkg/booleanpolicy/fieldnames/list.go, pkg/booleanpolicy/violationmessages/printer.go, ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx
Adding a new policy criteria "Days since CVE was published".  This allows customers to build a policy to allow teams a grace period from the CVE published date to fix vulnerabilities in images, or get violations if the grace period has elapsed.
@kcarmichael08  This criteria will need to be documented.
Manually created a policy on the cluster.
=> ROX-28716: Added "Days Since CVE Was Published" policy criterion

ui/apps/platform/package-lock.json, ui/apps/platform/package.json, ui/apps/platform/src/Containers/Clusters/Components/HelmValueWarning.tsx, ui/apps/platform/src/react-app-env.d.ts
TypeScript updates a minor version every quarter.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-8/
https://devblogs.microsoft.com/typescript/announcing-typescript-5-8/#granular-checks-for-branches-in-return-expressions
In TypeScript 5.8, the type system special-cases conditional expressions directly inside return statements. Each branch of the conditional is checked against the declared return type of the containing functions (if one exists)
https://devblogs.microsoft.com/typescript/announcing-typescript-5-8/#the---erasablesyntaxonly-option
Recently, Node.js 23.6 unflagged experimental support for running TypeScript files directly; however, only certain constructs are supported under this mode. Node.js has unflagged a mode called `--experimental-strip-types` which …
=> ROX-28733: Upgrade TypeScript 5.8.2

pkg/signatures/cosign_sig_verifier.go, pkg/signatures/cosign_sig_verifier_test.go
Consider a setup where images are signed by two different keys
```
$ cosign sign --key key-1.key quay.io/stehessel/nginx:t1
$ cosign sign --key key-2.key quay.io/stehessel/nginx:t1
```
As a result, the image `quay.io/rhn_support_rissingh/tastest:t1` now contains two signatures `sig-1` and `sig-2`. Create an ACS signature integration with both `key-1` and `key-2`.
There is now a mismatch between the cosign cli behavior and ACS behavior:
* ACS verifies keys with OR and signatures with AND. In other words, it verifies successfully if (`key-1` has signed `sig-1` AND `sig-2`) OR (`key-2` has signed `sig-1` AND `sig-2`).
* cosign verifies keys with OR and signatures with OR. In other words, it verifies successfully if (`key-1` has signed `sig-1` OR `sig-2`) OR (`key-2` has signed `sig-1` OR …
=> ROX-28699: fix verification of multiple cosign signatures

roxctl/central/generate/generate.go, roxctl/central/generate/generate_test.go, roxctl/central/generate/k8s.go, roxctl/central/generate/volumes.go, roxctl/common/flags/annotations.go
When executing `roxctl central generate...` the expected behavior is that a zip file will be pushed into STDOUT so that it can be piped into a file. However this should explicitly NOT happen if `--output-dir` is set. I thought I had fixed this previously by querying for `flags.OutputDirManuallySet = c.PersistentFlags().Changed("output-dir")` during cobra command creation, but this `flags.OutputDirManuallySet` will always be false.
The reason for that as I understand it is that I was setting this during the creation of the cobra command before any parameters such as `--output-dir` were even parsed. The solution then is to check `PersistentFlags().Changed("output-dir")` during execution of the cobra command. This requires passing of the flags to `OutputZip` which I was previously trying to …
=> ROX-28679: Roxctl central generate ignoring --output-dir in OutputZip

roxctl/common/client.go, roxctl/common/tls.go
e2e tests TBD
**Before**:
```console
sh$ bin/linux_amd64/roxctl central debug dump -e 34.75.173.232:443 --output-dir /tmp/
INFO:	Retrieving debug metrics. This may take a couple of minutes...
INFO:	trying to verify cert for SERIALNUMBER=1056504657214105579,CN=CENTRAL_SERVICE: Central,OU=CENTRAL_SERVICE, signed by SERIALNUMBER=5991849816631250472,CN=StackRox Certificate Authority (CA false)
ERROR:	The remote endpoint failed TLS validation.
Do one of the following:
1. Obtain a valid certificate for your Central instance/Load Balancer.
2. Use the --ca option to specify a custom CA certificate (PEM format).
This certificate can be obtained by running "roxctl central cert".
3. Use the --insecure-skip-tls-verify option to suppress this error
and not validate TLS certificates …
```
=> chore(roxctl): Do not retry on permission denied error

ui/apps/platform/cypress/integration/clusters/delegatedScanning.test.js, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesList.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedScanningSettings.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/ToggleDelegatedScanning.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx
While content changes for clarity and correctness simmer in mental slow cooker:
* Replace inconsistent text and capitalization.
* Replace unusual markup with usual PatternFly form markup.
Because of indentation changes, it might help if you ignore white space.
1. Edit delegatedScanning.test.js file.
* Change text as in components below.
2. Edit ClustersTablePanel.tsx file.
* Replace **Delegated scanning** with **Delegated image scanning** in button link for consistency with page heading.
3. Edit DelegatedRegistriesList.tsx file.
* Delete obsolete `updateRegistriesOrder` prop that I might have missed in earlier prerequisite contribution.
* Replace `Card` with `FormGroup` element.
* Delete `EmptyState` markup and move **No registries specified.** above **Add registry** button link.
* Delete …
=> ROX-28715: Improve consistency of delegated image scanning

scripts/retry-kubectl.sh
My kubectl today failed with an error message "TLS handshake timeout" -- let's add it to the list of regexes for `retry-kubctl.sh` so that it will automatically retry in case it hits such an error.
=> test: Add error message to list of errors for kubectl retries

tests/upgrade/postgres_run.sh
After the `4.5.8`, `4.6.4`, and `4.7.1` releases, we should bump upgrade test versions.
Let CI pipeline check it!
=> ROX-28656: Update upgrade test versions

ui/apps/platform/config-overrides.js, ui/apps/platform/package.json, ui/package.json, ui/yarn.lock
See https://github.com/stackrox/stackrox/pull/14817 - this is a manual backport to 4.5.
One additional change: we needed an override for `cross-spawn` due to build errors. The only breaking change between 6.x and 7.x was dropping support for version of Node < **8** (we are currently on Node 20).
See linked PR.
=> ROX-28758: Update redoc

roxctl/central/initbundles/fetch_ca.go, tests/roxctl/bats-tests/cluster/central-init-bundles.bats
This PR fixes a bug: when we wrote ca to a file at the end we delete the file. Instead we should delete the file only when we could not write to it but after we created it. This was introduced in:
- https://github.com/stackrox/stackrox/commit/bf1809b75373953ac7d0228e41dcf58bb256cb43#diff-4a33bdfced9de1c5d2ab61ceb745355aded4d2c25013f9418648c2b2e5a12ef4R36
---
CI
=> ROX-26884: do not delete ca file

migrator/migrations/m_168_to_m_169_postgres_remove_clustercve_permission/permissionsetpostgresstore/postgres_plugin.go, migrator/migrations/m_169_to_m_170_collections_sac_resource_migration/permissionsetpostgresstore/postgres_plugin.go, migrator/migrations/m_170_to_m_171_create_policy_categories_and_edges/policycategoryedgepostgresstore/store.go, migrator/migrations/m_170_to_m_171_create_policy_categories_and_edges/policycategorypostgresstore/store.go, migrator/migrations/m_170_to_m_171_create_policy_categories_and_edges/policypostgresstore/store.go, migrator/migrations/m_171_to_m_172_move_scope_to_collection_in_report_configurations/collectionPostgresStore/postgres_plugin.go, migrator/migrations/m_171_to_m_172_move_scope_to_collection_in_report_configurations/reportConfigurationPostgresStore/postgres_plugin.go, migrator/migrations/m_173_to_m_174_group_unique_constraint/stores/previous/postgres_plugin.go, migrator/migrations/m_173_to_m_174_group_unique_constraint/stores/updated/postgres_plugin.go, migrator/migrations/m_174_to_m_175_enable_search_on_api_tokens/newapitokenpostgresstore/postgres_plugin.go, migrator/migrations/m_174_to_m_175_enable_search_on_api_tokens/oldapitokenpostgresstore/postgres_plugin.go, migrator/migrations/m_176_to_m_177_network_baselines_cidr/networkbaselinestore/postgres_plugin.go, migrator/migrations/m_176_to_m_177_network_baselines_cidr/networkentitystore/postgres_plugin.go, migrator/migrations/m_177_to_m_178_group_permissions/permissionsetpostgresstore/postgres_plugin.go, migrator/migrations/m_178_to_m_179_embedded_collections_search_label/reportconfigstore/postgres_plugin.go, migrator/migrations/m_178_to_m_179_embedded_collections_search_label/test/postgres_plugin.go, migrator/migrations/m_179_to_m_180_openshift_policy_exclusions/postgres/store.go, migrator/migrations/m_181_to_m_182_group_role_permission_with_access_one/permissionsetstore/store.go, migrator/migrations/m_182_to_m_183_remove_default_scope_manager_role/apitokenstore/postgres_plugin.go, migrator/migrations/m_182_to_m_183_remove_default_scope_manager_role/groupstore/postgres_plugin.go, migrator/migrations/m_182_to_m_183_remove_default_scope_manager_role/permissionsetstore/postgres_plugin.go, migrator/migrations/m_182_to_m_183_remove_default_scope_manager_role/rolestore/postgres_plugin.go, migrator/migrations/m_183_to_m_184_move_declarative_config_health/declarativeconfig/store/postgres_plugin.go, migrator/migrations/m_183_to_m_184_move_declarative_config_health/integrationhealth/store/postgres_plugin.go, migrator/migrations/m_184_to_m_185_remove_policy_vulnerability_report_resources/permissionsetstore/postgres_plugin.go, migrator/migrations/m_185_to_m_186_more_policy_migrations/policypostgresstore/postgres_plugin.go, migrator/migrations/policymigrationhelper/categorypostgresstorefortest/postgres_policy_category_plugin.go, migrator/migrations/policymigrationhelper/policypostgresstorefortest/postgres_policy_plugin.go, pkg/search/postgres/common.go
In this PR we replace `RunCursorQueryForSchema` with `RunCursorQueryForSchemaFn` in walk. This results in much simpler code in `store.go` and allow removal of `RunCursorQueryForSchema` as it's not longer used.
CI
=> fix(migrator): use RunCursorQueryForSchemaFn in Walk

ui/yarn.lock
Since 4.5 still uses `yarn`, this could not be automatically backported from the [equivalent PR](https://github.com/stackrox/stackrox/pull/14716) targeting the `master` branch.
See testing steps in https://github.com/stackrox/stackrox/pull/14716
=> ROX-26692: Update http-proxy-middleware

roxctl/image/scan/cve.go, roxctl/image/scan/cve_test.go
We can use enum instead of string that will help us with sorting and also keep the type.
- https://github.com/stackrox/stackrox/pull/14803
---
CI
=> ROX-8333: use enum instead of string

tests/delegated_scanning_test.go
Adds a retry when 502 (Bad Gateway) is returned from quay in the delegated scanning e2e 'ad hoc' tests.
CI
=> ROX-26663: CI fix - retry delegated scan on 502 Bad Gateway

central/auth/datastore/datastore_impl.go, central/auth/datastore/datastore_impl_test.go
The kube SA token m2m auth config that exists now is added for policy as code and hard codes a role mapping to the config-controller service account.  This effectively locks out any other user from using the m2m config for any other purpose.  This change tries to allow users to configure the Kube SA token m2m auth config while the required role mapping for policy-as-code remains intact.
=> ROX-25912: Make Kube SA token m2m auth config dynamic

ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/ClusterRegistrationSecretDescription.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/ClusterRegistrationSecretForm.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/ClusterRegistrationSecretForm.utils.ts, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/ClusterRegistrationSecretPage.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/ClusterRegistrationSecretsHeader.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/ClusterRegistrationSecretsPage.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/ClusterRegistrationSecretsRoute.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/ClusterRegistrationSecretsTable.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/RevokeClusterRegistrationSecretModal.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/SecureClusterPage.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/SecureClusterUsingHelmChart.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/SecureClusterUsingOperator.tsx, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleForm.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/AuthenticationTokensSection.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/ClusterRegistrationSecretsTile.tsx, ui/apps/platform/src/Containers/Integrations/utils/integrationsList.ts, ui/apps/platform/src/Containers/Integrations/utils/tableColumnDescriptor.ts, ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/hooks/useAnalytics.ts, ui/apps/platform/src/routePaths.ts, ui/apps/platform/src/services/ClustersService.ts, ui/apps/platform/src/types/integration.ts
This is an attempt to implement basic support for Cluster registration secrets (CRS) in the UI by copying and modifying the implementation for init-bundles.
Notes:
* I did not copy over the code dealing with "impacted clusters", because revoking CRSs does not impact any cluster (a CRS is *only* used for establishing initial trust, they are not used after that and can be safely revoked).
* For CRS there is no distinction between "Operator format" (a Kubernetes manifest) and "Helm format" (which is YAML, but not a Kubernetes manifest).
* This PR cannot be merged in isolation, there are three PRs which need to be merged first: [backend CRS integration](https://github.com/stackrox/stackrox/pull/13239), [Helm chart integration](https://github.com/stackrox/stackrox/pull/12713) and finally …
=> ROX-26973: CRS Support in ACS UI

CHANGELOG.md, ui/apps/platform/cypress/integration/compliance/Compliance.selectors.js, ui/apps/platform/cypress/integration/compliance/complianceList.test.js, ui/apps/platform/src/queries/table.js
Changing aggregation unit in Compliance tables to use controls instead of checks to match the widgets. choosing `CONTROL` over `CHECK` since we don't show check level of detail anyways in the UI. the ticket specified only for clusters but i found this to be an issue across namespaces/deployments/nodes, so i made the changes in those queries as well.
clicking on the old compliance dashboard lists (clusters, namespaces, deployments, nodes) and subsequently clicking a row should show the standard percentage match the table data & the widgets in the side panel
cluster:
namespace:
deployment:
node:
change me!
=> ROX-27885: Align data in old Compliance across tables and widgets

ui/apps/platform/src/Containers/Compliance/widgets/ControlRelatedResourceList.js, ui/apps/platform/src/Containers/Compliance/widgets/ResourceCount.js, ui/apps/platform/src/queries/image.js, ui/apps/platform/src/queries/policy.js, ui/apps/platform/src/queries/role.js, ui/apps/platform/src/queries/secret.js, ui/apps/platform/src/queries/serviceAccount.js, ui/apps/platform/src/queries/subject.js, ui/apps/platform/src/utils/queryMap.js
Prerequisite to understand what is used where, so we can remove unneeded data from queries to solve problems with role-based access control.
Because this is the third time that I misinterpreted Find in Files to mean that this component is not used, replace `ControlRelatedEntityList` with `ControlRelatedResourceList` so internal name of component is consistent:
* with its file name
* with its default import name
1. Verify that the following entity types are obsolete from before postgres:
* `COMPONENT`
* `CVE`
main.js 0 = 4701584 - 4701584
total -1954 = 11703517 - 11705471
files 0 = 179 - 179
3. `npm …
=> ROX-28795: Delete unreachable code in classic compliance

scripts/ci/jobs/check-generated.sh
Fix errexit logic by spawning test functions in a sub shell which has `set -e` activated.
In the `check-generated.sh` script we use the following pattern:
```
set -euo pipefail
foo() {
echo "doing something"
false # Failure
echo "continuing as if everything is ok"
}
foo || echo "error handling..."
```
This won't work, it will print
```
doing something
continuing as if everything is ok
```
This is so because the `... || error handling` construct causes the `set -e` to be deactivated in the shell function. In this PR I am transforming this code to
```
set -euo pipefail
export SHELLOPTS
foo() {
echo "doing something"
false # Failure
echo "continuing as if everything is ok"
}
export -f foo
bash -c foo || echo "error handling..."
```
This works as expected and will allow us to do the error …
=> test: Fix errexit logic by spawning test functions in a sub shell

roxctl/central/initbundles/fetch_ca.go, tests/roxctl/bats-tests/cluster/central-init-bundles.bats
This PR fixes bug introduced in #14800 where output file was in a directory that does not exist.
Refs:
- #14844 
CI
=> ROX-28788: fix bats test

CHANGELOG.md, compliance/cmd/compliance/main.go, compliance/node/index/indexer.go, compliance/node/index/indexer_test.go, pkg/env/node_index.go, pkg/env/sensor.go, sensor/common/sensor/sensor.go
The value of `ROX_NODE_INDEX_MAPPING_URL` must point to Sensor's https endpoint for obtaining repo to CPE mapping for node indexing. This env var was defaulting to `sensor.stackrox.svc` which worked only when Sensor was installed in the stackrox namespace. For other namespaces, we should have change the Sensor host part in Helm charts, but apparently that has never been done.
In this PR I leave out the Sensor host address from this var and keep only the URL-path. The entire address is now concatenated from  `ROX_ADVERTISED_ENDPOINT` (which contains a correct address) and the new var `ROX_NODE_INDEX_MAPPING_URL_PATH` that defaults to `/scanner/definitions?file=repo2cpe`.
```
{"level":"error","version":"1.2","component":"rhel/internal/common/Updater.Get","error":"Get …
```
=> ROX-28698: Fix wrong default value of node index mapping URL

pkg/postgres/walker/schema.go, tools/generate-helpers/pg-table-bindings/main.go, tools/generate-helpers/pg-table-bindings/singleton.go.tpl, tools/generate-helpers/pg-table-bindings/store.go.tpl, tools/generate-helpers/pg-table-bindings/store_test.go.tpl
This PR removes support for multiple primary keys in generated stores as we don't have such stores. It removes unused template functions and adds a check to prevent multiple primary keys to be used in the future.
CI
=> fix(pg): cleanup store generators

qa-tests-backend/build.gradle
The dependency was added in https://github.com/stackrox/stackrox/commit/037d4d4966e19f9cdf702c915208971bc0880935
but then the use was removed in 5e307f31d054403121609b508e6c9c697ffd96c0
but the dependency was left and it's time to remove it.
CI
=> chore(deps): remove unused docker-java dependency

ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx, ui/apps/platform/src/Containers/Compliance/complianceRBAC.ts
Practice pattern for classic dashboard widgets, althouth manual testing steps suggest that role-based access control is inconsistent between scans themselves and queries for scanned data. Therefore, render according to stricter scan requirements.
By the way, **Scan environment** button has `READ_WRITE_ACCESS` level for `Compliance` resource only:
* even though that is not sufficient for classic scans
* in case it might be sufficient to display results from Compliance Operator
For similar scenario, **Passing standards across clusters** does **not** have `Cluster` as additional resource requirements beyond `Compliance` for route.
1. Remove unneeded data from queries for side panels.
2. Conditionally render secondary data on side panels and single pages.
3. Conditionally render routes …
=> ROX-28778: Conditionally render classic compliance dashboard

CHANGELOG.md, central/sensor/service/connection/connection_impl.go, central/sensor/service/connection/connection_test.go, generated/internalapi/central/image.pb.go, generated/internalapi/central/image_vtproto.pb.go, proto/internalapi/central/image.proto, sensor/common/delegatedregistry/delegated_registry_handler.go, sensor/common/registry/registry_store.go, sensor/common/registry/registry_store_test.go
A race condition was mistakenly disabling delegated scanning (and likely erasing image integrations) when Sensor was reconnecting to Central. The behavior may have starting occurring in https://github.com/stackrox/stackrox/pull/9009.
To fix: the delegated scanning config and image integrations sent from Central are no longer cleared as part of the `registry_store`'s `Cleanup()` method. It seems these store `Cleanup` methods were meant for data derived from k8s informers/listeners, not data sent from Central.
Since the delegated scanning config is always replaced in full, there is no need to clear it.
Image integrations may be deleted via Central while Sensor is disconnected, a new `refresh` flag was added to the `ImageIntegrations MsgToSensor` that will cause Sensor to erase existing …
=> ROX-28574: Fix race condition breaking delegated scanning

central/auth/store/store.go, central/policy/store/store.go
`storeWrapper` decorates the store with `Begin` method. It's implementation is OK but we can remove duplicated code by including store into the struct instead of using a field. This allow use to use store interface and extend it with necessary method without implementing all store methods.
CI
=> chore(pg): cleanup storeWrapper

tests/e2e/run-scanner-v4-install.bats
The scanner-v4-install tests contain a log of output which is due to the teardown cleanup between test steps (including collecting service logs, etc.).
So, currently when analysing test failures I usually look for the "not ok" message from Bats and then right above that there is usually a very long "tear-down" block. I scroll up until I reach the beginning of this block and there is the actual cause for the test failure to be found.
It would be much nicer if one could just look for a simple string, e.g. `FAILED:` and this would be exactly the place where something went sideways.
This PR does that, it adds this marker log line which allows for quick identifying of the problematic test steps.
I decided to use `FAILED:`, because this is also what the Go unit tests output on specific test …
=> test: Add "FAILED:" marker in test output

ui/apps/platform/src/Containers/MainPage/Navigation/NavigationSidebar.tsx, ui/apps/platform/src/Containers/MainPage/Navigation/utils.ts
Fix for an issue where some navigation links wouldn't remain active when inside nested routes.
=> fix(ui): Fix for navigation links active state

.openshift-ci/get_compatibility_test_tuples.py, qa-tests-backend/src/test/groovy/SummaryTest.groovy
- Cherry picks #14770
- Reverts #14744
```
INFO:root:Running compatibility tests for central-v4.6.4-6-g36e5c7c9cd, sensor-v400.6.4 with function QaE2eTestCompatibility
INFO:root:Running compatibility tests for central-v4.6.4-6-g36e5c7c9cd, sensor-v400.5.8 with function QaE2eTestCompatibility
INFO:root:Running compatibility tests for central-v400.6.4, sensor-v4.6.4-6-g36e5c7c9cd with function QaE2eTestCompatibility
INFO:root:Running compatibility tests for central-v400.5.8, sensor-v4.6.4-6-g36e5c7c9cd with function QaE2eTestCompatibility
INFO:root:Running compatibility tests for central-v4.6.4-6-g36e5c7c9cd, sensor-v74.9.0 with function QaE2eTestCompatibility
```
```
INFO:root:Running compatibility tests for central-v4.6.4-6-g36e5c7c9cd, sensor-v400.6.4 with function …
```
=> ROX-28680: Re-enable top nav tests

central/graphql/resolvers/image_components_v2_postgres_test.go, central/graphql/resolvers/images.go, pkg/search/scoped/context.go, pkg/search/scoped/postgres/searcher.go, pkg/search/scoped/postgres/searcher_test.go
With the flattened data model we needed to either pass a specific field in the scope OR to pass an array of IDs with the scope.  After looking into it, adjusting the scope to have a way to take an array of IDs seemed far simpler and less intrusive. 
Updated unit test.  Much further testing will happen further down this PR stack as this is used.
=> ROX-28320: add IDs option to context scope

ui/apps/platform/cypress/integration/compliance/Compliance.helpers.js, ui/apps/platform/src/Containers/Compliance/Entity/Cluster.js, ui/apps/platform/src/Containers/Compliance/Entity/Deployment.js, ui/apps/platform/src/Containers/Compliance/Entity/Namespace.js, ui/apps/platform/src/queries/cluster.js, ui/apps/platform/src/queries/deployment.js, ui/apps/platform/src/queries/namespace.js
Delete data that is either:
* left over from intended but abandoned reuse of query with Configuration Management
* irrelevant information for compliance persona
Add conditional rendering in Cluster.js file:
* `ResourceCount` elements for side panel
* `resourceTabs` array for single page
1. Investigate over-fetching in `EntityCompliance` element.
2. RBAC for queries is still spooky. With `Cluster` and `Node` resources, cluster single page did not render **Nodes** resource tab because `results: []` until I clicked **Scan environment** again.
1. Visit /main/compliance/clusters and then click a link to open side panel.
Before changes, with `Cluster` resource, see presence of errors for unused data.
After changes, with `Cluster` resource, see:
* presence of error because other entities in …
=> ROX-28832: Remove unneeded data from classic compliance queries

ui/apps/platform/cypress/integration/clusters/delegatedScanning.test.js, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesTable.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedScanningSettings.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/cluster.ts
This is a separate task for incorrect text (which corresponds to small change) that I separated from the original bug which paired it with unclear text (which needs more time in mental slow cooker, and then review).
Reported and patiently explained by **David Caravello**
**Destination cluster** list is incorrect:
1. **None** with `value` of empty string, but it corresponds to **Default cluster to delegate to**
2. **cluster (default)** with `value` of cluster id, but it corresponds to an explicit cluster, even if it is default at this moment
1. **Default cluster (whatever)** with `value` of empty string corresponds to **Default cluster to delegate to** and **whatever** is either:
* **None** if no default cluster
* cluster name (or **Not available** if valid clusters does not include id)
2. …
=> ROX-28779: Fix incorrect cluster items in delegated image scanning

central/cloudsources/datastore/datastore.go, central/cloudsources/datastore/datastore_impl.go, central/cloudsources/datastore/datastore_impl_postgres_test.go, central/cloudsources/datastore/internal/store/mocks/store.go, central/cloudsources/datastore/internal/store/postgres/gen.go, central/cloudsources/datastore/internal/store/postgres/store.go, central/cloudsources/datastore/internal/store/postgres/store_test.go, central/cloudsources/datastore/internal/store/store.go, central/cloudsources/manager/manager.go
---
- #14784
- #14781 :point_left: 
- #14779
- #14778
- #14763
- #14759
- #14758
- #14757
- #14747
- #14742
---
CI
=> ROX-28697: use Walk instead of GetAll in cloud sources

central/networkgraph/aggregator/aggregator_impl.go, central/networkgraph/aggregator/aggregator_test.go, central/networkgraph/entity/datastore/datastore_impl_test.go, central/networkgraph/service/service_impl.go, central/networkgraph/service/service_impl_postgres_test.go, central/networkgraph/service/service_impl_test.go, pkg/networkgraph/testutils/utils.go, pkg/networkgraph/tree/multitree_test.go, pkg/networkgraph/tree/radix_test.go, pkg/networkgraph/tree/wrapper_test.go
The "Verify connections to external sources" test in https://github.com/stackrox/stackrox/pull/13098, was failing due to multiple duplicate connections to the internet, with different timestamps. This PR fixes that issue. 
There was existing code for removing duplicate connections to external entities with different timestamps. However, it was not working in this case.
The bug was in this part of the code
```
flowProps.SrcEntity = anonymizeDiscoveredEntity(flowProps.SrcEntity)
flowProps.DstEntity = anonymizeDiscoveredEntity(flowProps.DstEntity)
srcEntity, dstEntity = flowProps.SrcEntity, flowProps.DstEntity
// If both endpoints are not known external sources, skip processing.
if !networkgraph.IsKnownExternalSrc(srcEntity) && !networkgraph.IsKnownExternalSrc(dstEntity) {
ret = append(ret, …
```
=> ROX-28742: Fix deduplication of connections for external IPs

ui/apps/platform/package.json
Tired of having to spend the time to make two whole additional clicks when running e2e tests via a browser locally? Tired of having to wait a couple of seconds for Chrome to open? Fear not, now `npm run cypress-open` understands your intentions and does it for you (AI not included).
This change will automatically assume that `npm run cypress-open` is being used for e2e tests, which it always is, and assumes you want to run tests in Chrome, which we almost always do.
You can override these options via the CLI if needed: `npm run cypress-open -- --config defaultBrowser=firefox`.
`cypress-open` locally and see the window automatically transition to the test suite view.
=> chore(ui): Use e2e and Chrome browser as default local Cypress options

ui/apps/platform/cypress/helpers/file.ts, ui/apps/platform/cypress/integration/clusters/cluster-registration-secrets/ClusterRegistrationSecrets.helpers.ts, ui/apps/platform/cypress/integration/clusters/cluster-registration-secrets/ClusterRegistrationSecrets.test.ts
Although the overall UX for CRS is going to chanage in how we present the feature, the core functionality will remain mostly the same. This test will give us a regression benchmark as further changes are made.
Local Cypress run, CI
=> ROX-28793: Add Cypress e2e test for cluster reg secrets

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ClusterDetailsTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/searchFilterConfig.ts
Fix for compliance filter chips not displaying for cluster filters.
=> fix(ui): Fix compliance filter chips

image/rhel/Dockerfile
lz4 and bzip2 were added to support rocksdb since we do not use it anymore we can remove them.
- https://github.com/stackrox/rox/pull/5611
---
CI
=> chore(deps): remove lz4 and bzip2

.github/workflows/build.yaml, .github/workflows/style.yaml
This follows up on https://github.com/stackrox/stackrox/pull/13502 in the light that some parts of the approach block the release as evidenced in <https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1743438459477049?thread_ts=1742820121.886399&cid=C05TS9N0S7L>.
There's also a discussion in https://github.com/stackrox/stackrox/pull/14825/files#r2022395918 (for the context).
This change can be reviewed by commits which I provided with descriptions.
The future plans are:
- Change branch protection in `master` to respect the new place of the jobs.
- Backport this to 4.6 and 4.7.
- Make the jobs required in release-* branches so that there won't be a similar situation when someone could update pointers without checking the builds.
No change.
Just looking at CI.
=> ROX-28879: Update ScannerV2&Collector Konflux image checks

qa-tests-backend/src/main/groovy/services/NotifierService.groovy, qa-tests-backend/src/main/groovy/util/Helpers.groovy, qa-tests-backend/src/main/groovy/util/Retry.groovy, qa-tests-backend/src/test/groovy/RetryTest.groovy
This PR creates `@Retry` annotation that wraps annotated method with `Helpers.evaluateWithRetry`.
This is done to help retrying on grpc after set of failures to configure it on grpc level. Eventually most of the service methods will be annotated.
- https://github.com/stackrox/stackrox/pull/11821
https://github.com/stackrox/stackrox/blob/d22867428080ff0928788095ec7e634b43b863f0/qa-tests-backend/src/main/groovy/services/BaseService.groovy#L131-L137
Unfortunately there is no easy to use auto retry annotation. I found:
1. https://aspects.jcabi.com/annotation-retryonfailure.html – requires magic to enable aspects in gradle and spock tests
2. https://resilience4j.readme.io/docs/retry – too complex, good for services not for tests
3. https://github.com/spring-projects/spring-retry – too complex …
=> ROX-28100: retry grpc call

ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Risk/RiskPage.jsx, ui/apps/platform/src/Containers/Risk/RiskTablePanel.jsx, ui/apps/platform/src/services/searchOptionsToQuery.ts, ui/apps/platform/src/utils/searchUtils.test.ts, ui/apps/platform/src/utils/searchUtils.ts
Fixes a very rare test flake due to a double-request when visiting the risk page with pre-existing filters in the URL. The fix is more important to address the latter, and less important for fixing the rare flake.
The double request occurs when visiting Risk with search parameters in the URL. Prior to this change, search filters would be filtered to only include keys that were returned in part of the `searchOptions` array. This causes a request with no filters to be sent since the initial `searchOptions` array is empty, followed by a second request once the `searchOptions` are returned from the server. In the typical case of visiting the risk page directly with no filters, this is not a problem as the filtered search object is empty in both cases.
An alternative to this would be to block …
=> ROX-23975: Remove filtering of search options on risk page

central/networkbaseline/manager/manager_impl.go, central/networkbaseline/manager/manager_impl_test.go
When constructing a network baseline, we want to ignore IP information and instead focus on the port/protocol that is exposed to better reflect the behaviour of alerts and network policy generation.
Without these changes, IP information appears in the network baseline, which implies that the deployment is only allowed to talk to that IP. In practice, it can talk to any external IP on the same port/protocol.
~- [ ] CHANGELOG is updated **OR** update is not needed~
~- [ ] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed~
~- [ ] added unit tests~
The added test case covers the anonymization, and …
=> ROX-28028: anonymise external IPs in network baselines

central/policy/datastore/datastore_impl.go, central/policy/datastore/datastore_impl_test.go, central/processindicator/search/searcher_impl_test.go, pkg/postgres/pgtest/postgres.go, pkg/scanners/clairify/convert_test.go
It's long time since we switch to postgres and it's time to cleanup. 
`SkipIfPostgresEnabled` was introduced to skip tests that will not work on postgres and run them when the feature flag is disable. Over the time it evolved to skip test always (as feature flag was always on, and eventually removed). This PR removes this functions and fixes tests or remove them when the new postgres test was added. 
- #4719
- https://github.com/stackrox/stackrox/pull/6526#discussion_r1230780085
- #11953 
---
CI
=> chore(tests): remove SkipIfPostgresEnabled

ui/apps/platform/eslint-plugins/pluginPatternFly.js
Especially when PatternFly is a major version ahead, reduce the risk to have inconsistent version number when we adapt examples.
For example:
https://github.com/stackrox/stackrox/pull/14951#discussion_r2039370285
https://github.com/stackrox/stackrox/pull/14951/commits/7d1b79ab1519271ff5214ec61d9a462da5903b0c
Find in Files for `pf-(\d+)-` with RegExp: 2067 results in 458 files
Especially for template literal ;)
typescript-eslint playground: https://typescript-eslint.io/play/#ts=5.8.2&showAST=es&fileType=.tsx
1. Investigate whether `files` glob in lint config for product files should match src/react-app-env.d.ts file.
2. Lint .css files?
https://eslint.org/blog/2025/02/eslint-css-support/
1. `npm run lint` in ui/apps/platform folder
=> ROX-28946: Add lint rule for version of PatternFly variable or class

ui/apps/platform/cypress/integration/clusters/cluster-registration-secrets/ClusterRegistrationSecrets.test.ts, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx
Adds a button to the Clusters page that links to the CRS table.
Visit cluster page:
Click the button:
Test that the multitude of buttons does not break layout on small screens:
=> ROX-28876: Add button to Clusters page to manage CRS

central/networkgraph/aggregator/aggregator.go, central/networkgraph/aggregator/aggregator_impl.go, central/networkgraph/aggregator/aggregator_test.go, central/networkgraph/service/service_impl.go, central/networkgraph/service/service_impl_postgres_test.go
There are still cases when duplicate connections with different timestamps appear in the network graph. This results when there is a flow with a connection to `INTERNET` and then the non-anonymized version is added. When anonymizing and deduplicating external connections the connection to `INTERNET` will be skipped and the deduplication will not be done.
This ensures that all connections will be deduplicated, by doing the deduplication in an aggregator which only skips connections when they are invalid, whereas the existing aggregators skip connections that are not of interest to the aggregator. This may be more memory and CPU intensive, but guarantees that there are no duplicate connections.
Ran the e2e test here https://github.com/stackrox/stackrox/pull/13098
A new unit test also …
=> fix(Aggregator): Fix network flow deduplication again

ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/ClusterRegistrationSecretTechPreviewAlert.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/ClusterRegistrationSecretsPage.tsx, ui/apps/platform/src/Containers/Clusters/ClusterRegistrationSecrets/SecureClusterPage.tsx
Adds a Tech Preview banner to the CRS table page and "Secure a cluster" page.
Visit the CRS table and instructions pages:
=> ROX-28877: Add Tech Preview alerts in CRS pages

ui/apps/platform/cypress/integration/vulnerabilities/VulnerabilityReporting/VulnerabilityReporting.helpers.js, ui/apps/platform/cypress/integration/vulnerabilities/VulnerabilityReporting/vulnerabilityReportingNav.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CloneVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CreateVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/EditVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReportingPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/ConfigReportsTab.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/OnDemandReportsTab.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportingLayout.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/pathsForVulnerabilityReporting.ts, ui/apps/platform/src/routePaths.ts
This PR adds the "Report configurations" and "On-demand reports" tabs. Essentially, the core code to render the content for Report configurations in `VulnReportsPage` was moved to `ConfigReportsTab`. `VulnReportsPage` was removed and a new file called "VulnReportingLayout" is used to display the page header, tabs, and content. There is a new `OnDemandReportsTab` component too. For now, it'll be empty. We'll add the content for that section in future PRs. The routing was also adjusted.
Manual checking
=> ROX-28473: Add tabs within VM Reporting

ui/apps/platform/eslint-plugins/pluginPatternFly.js, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/HeaderLoadingSkeleton.tsx
Reduce the risk to have inconsistent (absence of) version number when we adapt examples.
Follow up recommendation in https://github.com/stackrox/stackrox/pull/14964#pullrequestreview-2760897263
src/Containers/ComplianceEnhanced/Coverage/CheckDetailsHeader.tsx
78:23  error  PatternFly utility class pf-u-w-50 lacks version number
src/Containers/Vulnerabilities/NodeCves/Node/NodePageHeader.tsx
47:48  error  PatternFly utility class pf-u-mb-sm lacks version number
src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageDetails.tsx
52:68  error  PatternFly utility class pf-v5-u-py-md pf-u-px-xl lacks version number
src/Containers/Vulnerabilities/components/HeaderLoadingSkeleton.tsx
17:23  error  PatternFly utility class pf-u-w-50 lacks version number
1. `npm run lint` in …
=> ROX-29007: Add lint rule for version of PatternFly utility class

central/image/datastore/datastore_impl.go, central/image/datastore/search/searcher_impl_v2.go, central/image/datastore/store/mocks/store.go, central/image/datastore/store/postgres/store.go, central/image/datastore/store/postgres/store_test.go, central/image/datastore/store/store.go, central/image/datastore/store/v2/postgres/store.go, central/image/datastore/store/v2/postgres/store_test.go
In Image store we return missing indices that are not used anywhere. This leads to a situation where we compute result that is ignored. Let's remove it.
```
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
ImageGetMany/GetImagesBatch-8         87.98m ± 2%   86.91m ± 2%       ~ (p=0.052 n=20)
ImageGetMany/GetManyImageMetadata-8   981.3µ ± 1%   967.8µ ± 2%  -1.37% (p=0.006 n=20)
geomean                               9.292m        9.171m       -1.29%
│   old.txt    │               new.txt               │
│     B/op     │     B/op      vs base               │
ImageGetMany/GetImagesBatch-8         7.472Mi ± 0%   7.464Mi ± 0%  -0.10% (p=0.000 n=20)
ImageGetMany/GetManyImageMetadata-8   544.0Ki ± 0%   539.1Ki ± 0%  -0.91% (p=0.000 n=20) …
```
=> ROX-28953: GetByIDs in image

central/imageintegration/store/defaults.go
When viewing the Scanner V4 integration in the UI the indexer/matcher endpoints are blank (defaults will be used).
The UI shows the endpoints as stored in Central DB.  This change will add the default endpoints to the Scanner V4 integration stored in the DB when it is first created.
Note this will have NO effect on Scanner V4 integrations that had been previously created or if the endpoint is cleared in the future.
No tests modified or added.
Enabled scanner v4 on fresh install, and saw endpoints populated, and verified scans were working.
Cleared an endpoint and confirmed scans were still working with the implied default
Also set a non-default value, confirmed scans broke, and restarted central to confirm the non-default value persisted.
=> ROX-28419: Persist indexer/matcher endpoints to DB

sensor/common/scan/scan.go
The duplicate log line was mistakenly kept after a refactor - the line removed was not accurate where it was positioned.
Good location:
https://github.com/stackrox/stackrox/blob/701c3c07a18df8d75aeef6edd8e04c389a26728f/sensor/common/scan/scan.go#L206-L211
Bad location
https://github.com/stackrox/stackrox/blob/701c3c07a18df8d75aeef6edd8e04c389a26728f/sensor/common/scan/scan.go#L248-L253
Existing tests are OK
CI
=> chore: Delegated scanning remove duplicate log

sensor/common/image/interfaces.go, sensor/common/image/mocks/interfaces.go, sensor/common/registry/registry_store.go, sensor/common/registry/registry_store_test.go, sensor/common/scan/scan.go, sensor/common/scan/scan_test.go
The goal of this PR is to provide a stop gap solution to avoid incorrect registry resolution for pull secrets of the form
```
{
"auths": {
"quay.io": {
"auth": "xxx"
},
"quay.io/rhacs-eng": {
"auth": "yyy"
}
}
}
```
Sensor in the status quo would choose only one of the above records and constructs wrong docker API endpoints such as `quay.io/rhacs-eng/v2/<repository>/<image>`. As a result, scan requests will fail randomly based on which secret is chosen.
This PR introduces two main changes:
1. Create underlying registries with just the host endpoint, i.e. only consider the `quay.io` part of `quay.io/rhacs-eng`.
2. Consider all registry entries in the global pull secret regardless of path.
In the above example, we now create two image integrations `quay.io` and `quay.io/rhacs-eng` - …
=> ROX-27814: match all registries with the same hostname

image/postgres/Dockerfile, image/postgres/scripts/init-entrypoint.sh
Experimental trigger for major version upgrade.
change me!
=> ROX-20769: Use pg_upgrade in init-entrypoint

image/templates/helm/shared/config-templates/scanner-v4-db/postgresql.conf.default
This updates the postgresql.conf to add more logs to Scanner V4 DB. These values are based on Central DB's.
no
Installed this version of StackRox onto a cluster and found more DB logs were present:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
Waiting for child process 9 to exit
2025-04-24 16:35:30.097 UTC [10] LOG:  starting PostgreSQL 15.12 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-23), 64-bit
2025-04-24 16:35:30.097 UTC [10] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-04-24 16:35:30.097 UTC [10] LOG:  listening on IPv6 address "::", port 5432
2025-04-24 16:35:30.134 UTC [10] LOG:  listening on Unix socket "/run/postgresql/.s.PGSQL.5432"
2025-04-24 16:35:30.219 UTC [10] LOG:  listening on Unix …
```
=> chore(scanner): more Scanner V4 DB logging

scanner/e2etests/testdata/image_tests.json
This update differences in functional tests since Scanner V4 was launched. They (mostly) are related to expeted changes due to:
- RHSA mapping
- Updates to NVD scoring and mapping
- NVD not publishing V2 metrics
- Some diff I am considering the test was wrong (related to layers)
I am leaving behind failures that I am not confident they are issues with the test cases:
1. FixedBy fields being erased for some RHSAs
2. Description string deleting empty spaces.
3. Vulnerabilities not found, or packages.
Running this locally, I get:
```
--- FAIL: TestImage (97.12s)
--- PASS: TestImage/ubuntu:16.04/ubuntu:16.04 (2.47s)
--- FAIL: TestImage/ubuntu:14.04/quay.io/rhacs-eng/qa:apache-server-scannerci (5.91s)
--- PASS: TestImage/ubuntu:14.04/quay.io/rhacs-eng/qa:sandbox-scannerremovejar (2.47s)
--- …
```
=> ROX-28744: Update known/safe differences in functional tests

tests/upgrade/postgres_run.sh
In upgrade tests, we are bumping central versions, but sensor keeps running on the oldest version. The problem is that sensor 4.1 still restarts if a connection is broken.
This change enables sensor flag that stops sensor from restarting, and it should fix the problem encountered in the test failure.
**UPDATE**
I didn't find a good way to identify if workload is properly created. There are a few indicators that we can use as confirmation, but still not 100% sure.
- Logs in GKE are showing that sensor is connected and not restarting for 13-14 mins. After that, we start bouncing central bouncing, and we can see sensor restarts.
- Log in central in "final" step:
```
sensor/service/pipeline/reconciliation: 2025/04/24 19:14:43.957927 perform.go:24: Info: Deleting 284 deployments as a part of …
```
=> ROX-28934: Avoid sensor restarts on central upgrade

central/vulnmgmt/vulnerabilityrequest/datastore/datastore_impl.go, central/vulnmgmt/vulnerabilityrequest/datastore/datastore_impl_postgres_test.go, central/vulnmgmt/vulnerabilityrequest/datastore/internal/searcher/searcher_impl.go, central/vulnmgmt/vulnerabilityrequest/datastore/internal/store/postgres/gen.go, central/vulnmgmt/vulnerabilityrequest/datastore/internal/store/postgres/store.go, pkg/postgres/schema/vulnerability_requests.go, pkg/sac/resources/list.go
This change is a first step in the direction of removing the concept of Permission Checker in the postgres stores and schemas.
An internal resource is added to control store access for VulnerabilityRequest objects. The more complex access control checks are performed at datastore level, and access to the store is injected in the context by the datastore logic when applicable.
PR stack:
- #14382
- #14384 
Refactor PR. The associated testing was added upfront in #14382 
CI should cover the change.
=> chore(sac): Create resource for Vulnerability Request store access

tests/e2e/run-scanner-v4-install.bats, tools/allowed-large-files
See [ROX-28693](https://issues.redhat.com/browse/ROX-28693), which contains an extensive description of this change.
tl,dr: This PR provides a new and much more direct way to trigger Helm-based deployments of our charts. One test has been rewritten to use these new deployment functions.
Note that this PR only touches existing testing code.
Running the test suite manually against remote clusters.
CI.
=> ROX-28693: Direct Helm deployment method in scanner-v4-tests

image/postgres/Dockerfile, image/postgres/download.sh, image/postgres/konflux.Dockerfile, image/rhel/download.sh, image/rhel/konflux.Dockerfile, tests/upgrade/postgres_run.sh
Use PostgreSQL 15 for central-db. Benefit from https://github.com/stackrox/stackrox/pull/14447 to handle upgrade scenarios.
=> ROX-20769: Use PG15 to run CI

ui/apps/platform/cypress/integration/configmanagement/deployments.test.js, ui/apps/platform/src/Containers/ConfigManagement/Entity/Deployment/DeploymentFindings.tsx, ui/apps/platform/src/Containers/ConfigManagement/Entity/widgets/FailedPoliciesAcrossDeployment.tsx, ui/apps/platform/src/Containers/Workflow/widgets/ViolationsAcrossThisDeployment.jsx
Fixes a missing `deploymentID` parameter in an API query, which was inadvertently dropped during a React Router refactor.
---
The component was originally a JavaScript file using `prop-types`, which were removed during the refactor in favor of extracting `deploymentID` from the `useParams()` hook. Since the runtime prop validation was eliminated, and the change was consistent with the scope of the router refactor, it would not have been flagged automatically—only manual testing or data validation would have caught it.
Although the component was later converted to TypeScript, this alone did not catch the issue. The function responsible for executing the query still accepted an untyped (`any`) argument, and the GraphQL query did not use generic types, so `deploymentID: undefined` was not …
=> ROX-28878: Fix incorrect violations count in ConfigMgmt

ui/apps/platform/src/configureApolloClient.js
As titled.
Manual testing with a very small value to verify that this setting takes effect.
=> ROX-28954: Increase gql client timeout from 60s -> 180s

.golangci.yml, config-controller/pkg/client/client.go, roxctl/sensor/generate/generate.go, roxctl/sensor/generate/openshift.go, roxctl/sensor/generatecerts/gen_certs.go, roxctl/sensor/getbundle/get_bundle.go, roxctl/sensor/util/get_bundle.go, roxctl/sensor/util/resolve_id_or_name.go
We have enabled wrapchedk in roxctl by disabling it everywhere else but our config is not 100% correct. It disables `sensor` and that catches `roxctl/sensor` too. This PR fixes wrapping in this package.
https://github.com/stackrox/stackrox/blob/23b101484b9ef4666bc20ba24ddf7ea1629eea83/.golangci.yml#L164-L167
See:
- https://github.com/stackrox/stackrox/pull/15045
CI
=> chore(roxctl): wrap sensor errors

qa-tests-backend/src/test/groovy/ExternalNetworkSourcesTest.groovy
My refactor #14538 seem to have caused this test to fail more regularly (before it was only flaking). I would like to investigate this before we decide to revert the big PR.
I haven't
=> ROX-24313: Disable test "Verify two flows co-exist if ..." 

deploy/common/k8sbased.sh, qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy, qa-tests-backend/src/main/groovy/services/NetworkGraphService.groovy, qa-tests-backend/src/main/groovy/util/CollectorUtil.groovy, qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy, tests/e2e/lib.sh
Modifies the existing "Verify connections to external sources" to check what happens when the external IPs feature goes from being disabled to enabled to disabled. The existing test creates a pod which repeatedly connects to google.com, which is obviously external to the cluster, and checks that the edge appears in the network graph. The test now creates the collector-config ConfigMap. It initially does so with external IPs being disabled. It then performs the existing check for the edge. Each time the configuration is set, it waits to confirm that collector has the correct configuration, before proceeding. External IPs is then enabled and after waiting for confirmation that the configuration has been updated and enough time has been given for the network graph to be updated, the edge is …
=> ROX-26347: e2e tests for collector runtime config

roxctl/image/scan/scan.go
This has come up a few times over the years, so I want to add this to make it clear it may not be removed until a replacement is found. See https://issues.redhat.com/browse/ROX-29120 for more information.
no
I didn't
=> chore(roxctl): ensure --format json is not removed until replaced

tests/e2e/lib.sh, ui/apps/platform/src/Containers/Clusters/ClustersTable.tsx, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Clusters/Components/ClusterNameWithTypeIcon.tsx, ui/apps/platform/src/Containers/Clusters/Components/HelmIndicator.tsx, ui/apps/platform/src/Containers/Clusters/Components/OperatorIndicator.tsx, ui/apps/platform/src/Containers/Clusters/clustersTableColumnDescriptors.jsx
Implements the initial migration of the clusters table to use PatternFly components and `TbodyUnified`
Note: Status, Sensor upgrade status, and Credential expiration columns will all be updated in a later PR
Default view:
Expandable sections:
=> ROX-26178: Initial clusters page table migration

ui/apps/platform/src/Containers/Integrations/utils/tableColumnDescriptor.ts, ui/apps/platform/src/services/MachineAccessService.ts
For the PaC GA release, the M2M config for the Kube service account is now visible in the UI because it is now configurable. But because the "kube service account" type was added for the config-controller (before it was visible in the UI), it was not added to the UI. So the new M2M config type needs to be added.
Built and deployed the UI locally and observed the new name successfully displayed.  The M2M config is added during Central bootstrap, so there is no additional setup needed to observe this specific M2M config.
=> ROX-29139: Add name for KUBE_SERVICE_ACCOUNT M2M config type

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
Prerequisite to turn on ROX_CVE_ADVISORY_SEPARATION feature flag.
1. `npm run lint` in ui/apps/platform folder
2. `npm run build` in ui/apps/platform folder
=> ROX-29147: Comment out totalAdvisories that was removed from MVP

central/scannerdefinitions/handler/handler_test.go, central/scannerdefinitions/handler/updater_test.go
Sometimes we'd get test flakes due to these tests. Unit tests really should not depend on external services, so this PR replaces the live definitions.stackrox.io with a local server which serves some dummy data. It'd be great to use the real service we use in the product, but that should be done elsewhere (not in unit tests).
This also fixes the usage of `*httptest.ResponseRecorder`. We aren't supposed to use `Code` and `Headers()`, directly, so this switches the usages to the preferred methods.
This just updates CI tests, so CI is sufficient
=> ROX-28325: stop reaching out to external data in unit tests

go.mod, go.sum
Use Claircore v1.5.37. This updates the package scanner versions for language package scanners to ensure we re-index to ignore RPM-installed language packages. This also optimizes the check for RPM-installed files.
no
CI
=> chore(deps): Bump claircore to v1.5.37

operator/Makefile
Looks like this logic never worked, because the passed image name was fully qualified with the registry and org name, and the script expected a bare image name (without any slashes).
As a result, the replaced version was 4.6, fine for the currently released 4.7 operators, but wrong for the to-be-released 4.8.
This change:
* fixes this by trimming everything up to the last slash in the image name
* fixes the undefined variable error that was there all the time in the dead branch
* also adds a `replaced-version` target that I plan to use in https://github.com/stackrox/stackrox/pull/10288 or its replacement, and which is why I noticed this in the first place.
Ran `make -C operator bundle-post-process replaced-version` which now yields `4.7.0` as expected.
=> fix: "replaced operator version" logic

operator/internal/central/carotation/rotation.go, operator/internal/central/carotation/rotation_test.go, operator/internal/central/extensions/reconcile_tls.go, operator/internal/central/extensions/reconcile_tls_test.go, operator/internal/utils/testutils/cert.go, pkg/certgen/ca.go, pkg/certgen/ca_test.go, pkg/mtls/crypto.go
Implements support for CA certification rotation in the Operator, based on [this design](https://docs.google.com/document/d/1I1r3bg3nwt96Q0dWs_mYdl5Wl4_xxVNz3NnB4UbHOCk/edit?usp=sharing).
The current implementation proposes 3 possible states of the CA:
1. only the primary CA is available (first 3 years of validity)
2. a secondary CA is created after 3 years, which is initially used to sign only Secured Cluster certificates (the idea being that a Sensor using exclusively the old (primary) CA doesn't know yet the new CA, and wouldn't be able to authenticate Central if the secondary CA was used also for Central at this point)
3. the secondary CA is promoted to primary CA after 4 years, and it's used to sign both Central and Secured Cluster certificates
(after 5 years the original CA is …
=> ROX-27962: CA rotation mechanism in Operator

.github/workflows/scanner-versioned-definitions-update.yaml, scanner/updater/manual/vulns.yaml
The Tomcat JAR does not contain a pom.properties file, so we cannot construct a quality `groupID:artifactID` pairing. Until we can reach out to Maven, we'll have to keep this entry around.
no
Deployed this version of StackRox to a cluster and let Scanner V4 DB get populated.
You'll find the following:
```
name      |                  package_name                  |            fixed_in_version            
----------------+------------------------------------------------+----------------------------------------
CVE-2022-22963 | spring-cloud-function-context                  | introduced=0&fixed=3.1.7
CVE-2022-22963 | spring-cloud-function-context                  | introduced=3.2.0&fixed=3.2.3
CVE-2022-22965 | spring-beans                                   | …
```
=> chore(scanner): manual entry for CVE-2025-24813

central/alert/datastore/bench_postgres_test.go, central/alert/datastore/datastore.go, central/alert/datastore/datastore_impl.go, central/alert/datastore/datastore_test.go, central/alert/datastore/internal/search/searcher_impl.go, central/alert/datastore/internal/store/mocks/store.go, central/alert/datastore/internal/store/store.go, central/alert/datastore/mocks/datastore.go, central/platform/reprocessor/reprocessor_impl.go, central/platform/reprocessor/reprocessor_impl_test.go
This PR uses a feature created in #15010  to improve alerts service performance and present how to use `GetByQueryFn` in other places.
```
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
AlertDatabaseOps/searchWithRawListAlert-8   9.708m ± 1%   9.448m ± 1%  -2.68% (p=0.000 n=20)
│   old.txt    │               new.txt               │
│     B/op     │     B/op      vs base               │
AlertDatabaseOps/searchWithRawListAlert-8   8.334Mi ± 0%   8.327Mi ± 0%  -0.09% (p=0.000 n=20)
│   old.txt   │              new.txt               │
│  allocs/op  │  allocs/op   vs base               │
AlertDatabaseOps/searchWithRawListAlert-8   109.2k ± 0%   109.2k ± 0%  +0.00% (p=0.000 n=20)
```
More bench tests are in:
- …
=> ROX-28941: Use GetByQueryFn in alerts

ui/apps/platform/src/Containers/Policies/Wizard/Step1/MitreTacticSelect.tsx, ui/apps/platform/src/Containers/Policies/Wizard/Step1/MitreTechniqueSelect.tsx, ui/apps/platform/src/Containers/Policies/Wizard/Step1/PolicyCategoriesSelectField.tsx, ui/apps/platform/src/Containers/Policies/Wizard/Step4/PolicyScopeCard.tsx, ui/apps/platform/src/Containers/Policies/Wizard/Step4/PolicyScopeForm.tsx
Adds `maxHeight` to policy wizard dropdowns to prevent menus from flowing off the page.
Adds inline filters to policy exclusion cluster and deployment dropdowns so that results can be filtered instead of endlessly scrolling.
Via the policy wizard.
Policy category dropdown:
MITRE tactic dropdown:
MITRE technique dropdown:
Cluster exclusion dropdown:
Deployment exclusion dropdown:
Exclude images dropdown:
=> ROX-29012: Add filters and max height to policy dropdowns

image/rhel/konflux.Dockerfile
Switches from UBI8 to UBI9 for the intermediate UI build stage _only_, reverting back to UBI8 as the base for the final image artifact.
This is a prerequisite for an [upcoming change](https://github.com/stackrox/stackrox/pull/13281) to the UI build system that uses binary components that require a version of GLIBC not available on UBI8.
An equivalent change is available in MR 4250 in the rhacs-midstream repo as well.
CI
Manual testing of image created by Konflux (TBD)
=> ROX-28786: Switch to UBI9 for UI build stage in konflux

ui/apps/platform/src/Containers/Compliance/widgets/EntityCompliance.jsx
Two separate problems that made the data in the list table and the side-panel get out of sync.
1. Mismatched granularity between table and side-panel – we want control level
- The list shows results **per control**.
- The side-panel was showing results **per check**.
2. Loose matching in the `where` clause of the graphql request
- The backend does prefix matching on names, so a search on `apiserver` would return results for `apiserver` and `apiserver-another` 
- `getAggregatedResults` call only filtered on the `${entityType}` name and `CLUSTER` name,  identically‑named resources in other namespaces were still getting included.
Before:
```
{
"groupBy": ["STANDARD", "DEPLOYMENT"],
"unit": "CHECK",
"where": "DEPLOYMENT:apiserver+CLUSTER:staging-secured-cluster"
}
```
After:
```
{
"groupBy": …
```
=> ROX-29058: Inconsistent compliance results between table & side panel

qa-tests-backend/src/main/groovy/services/GroupService.groovy
Currently we log exceptions but this leads to a wrong test configuration causing failures in different places. Instead let's retry network calls and do not catch exception if it occurs to fail fast.
CI
=> ROX-29165: @Retry in groups service

central/networkgraph/flow/datastore/internal/store/postgres/store.go, central/networkgraph/flow/datastore/internal/store/postgres/tests/store_test.go, pkg/env/external_ips.go, pkg/networkgraph/testutils/utils.go, pkg/utils/batch_process.go, pkg/utils/batch_process_test.go
Note that this PR is built upon here https://github.com/stackrox/stackrox/pull/15008
With the addition of the External-IPs feature, we now receive and store 'discovered' external entities into the network_entities table. As all the preexisting entities, 'discovered' entities are references as src or dst from network flows.
Up to now, all network entities stored in the database were static (or almost, since custom CIDR-blocks can be added/removed via API, and default entities are either enabled or disabled. But they were not discovered from the network). So we need a way to prune the database to ensure that the number of 'discovered' entities does not grow infinitely.
This PR adds a second stage of pruning after the flow pruning.
We are deleting all 'discovered' external entities for which …
=> ROX-26854: external entities garbage collection

central/cve/converter/utils/convert_utils_v2.go, central/graphql/resolvers/generated.go, central/graphql/resolvers/image_vulnerabilities.go, central/image/datastore/store/postgres/store_test.go, central/image/datastore/store/v2/postgres/store_test.go, generated/api/v1/image_service.swagger.json, generated/api/v1/node_service.swagger.json, generated/api/v1/vuln_mgmt_service.swagger.json, generated/internalapi/scanner/v4/vulnerability_report.pb.go, generated/internalapi/scanner/v4/vulnerability_report_vtproto.pb.go, generated/storage/cve.pb.go, generated/storage/cve_vtproto.pb.go, generated/storage/vulnerability.pb.go, generated/storage/vulnerability_vtproto.pb.go, pkg/scanners/scannerv4/convert.go, pkg/scannerv4/mappers/mappers.go, pkg/scannerv4/mappers/mappers_test.go, proto/internalapi/scanner/v4/vulnerability_report.proto, proto/storage/cve.proto, proto/storage/proto.lock, proto/storage/vulnerability.proto
Red Hat Scanner Certification requires a link to the Red Hat Advisory, so this PR adds the link to the advisory output.
CI
=> ROX-29073: include advisory link

CHANGELOG.md, pkg/features/list.go, pkg/scanners/scannerv4/convert.go, pkg/scannerv4/mappers/mappers.go, pkg/scannerv4/mappers/mappers_test.go
Red Hat vulnerability data may be split into two categories: rpm data and non-rpm data. The non-rpm data may also be known as "container-first" content because this data associates a vulnerability to an entire container image (instead of a specific package inside the image), and the fix would require the use of an updated image (opposed to an updated package).
Scanner V4 does, in fact, read this container-first data, and we clearly show container-first vulnerabilities. Users would see this by seeing the name of the container image (or even base container images) as the affected component.
The problem: when Red Hat declares an image is unaffected by some non-RPM-related vulnerability. For example: let's say there is some Go vulnerability which may potentially affect Red Hat Advanced …
=> ROX-27443: ignore non-Red Hat vulnerabilities in Red Hat layers

ui/apps/platform/src/Containers/SystemConfig/Details/PlatformComponentsConfigDetails.tsx, ui/apps/platform/src/Containers/SystemConfig/Details/components/CustomPlatformComponentsCard.tsx, ui/apps/platform/src/Containers/SystemConfig/Details/components/RedHatLayeredProductsCard.tsx
This PR adds the ability to click on "View more" to show a modal that displays the full rule (or rules for custom components). Some things, not in this PR, that will come in subsequent PRs:
1. Editing the Platform Components Configuration
The "View more" button shows the full Red Hat layered products rule
The "View more" button shows the full custom component rules
Showing multiple custom component rules
Scrolling multiple custom component rules
Tabbing to show that the scrollable area is highlighted. Pressing the "down" key will scroll down
TBD
=> ROX-29230: Clicking 'View more' should show full rule(s)

config-controller/api/v1alpha1/policy_types.go, config-controller/config/crd/bases/config.stackrox.io_securitypolicies.yaml, image/templates/helm/stackrox-central/internal/config.stackrox.io_securitypolicies.yaml
Trying to fix these issues identified by the new CRD upgrade test:
```
ERROR: "NoFieldRemoval": crd/securitypolicies.config.stackrox.io version/v1alpha1 field/^.spec.criteriaLocked may not be removed
ERROR: "NoFieldRemoval": crd/securitypolicies.config.stackrox.io version/v1alpha1 field/^.spec.isDefault may not be removed
ERROR: "NoFieldRemoval": crd/securitypolicies.config.stackrox.io version/v1alpha1 field/^.spec.mitreVectorsLocked may not be removed
ERROR: "NoFieldRemoval": crd/securitypolicies.config.stackrox.io version/v1alpha1 field/^.status.accepted may not be removed
ERROR: "NoFieldRemoval": crd/securitypolicies.config.stackrox.io version/v1alpha1 field/^.status.message may not be removed
ERROR: "NoNewRequiredFields": crd/securitypolicies.config.stackrox.io version/v1alpha1 …
```
=> ROX-29215: Fix SecurityPolicy CRD upgrade regressions

README.md
This improves the manual helm installation section as follows:
- The `--install` and `--create-namespace` flags were added to the commands for deploying on clusters with limited resources, so that those also work when ran in a fresh cluster.
- The sections for central and secured cluster services were aligned, when it comes to structure, helm command flags, and instructions.
- Other minor cosmetic fixes.
I have verified that the results are unchanged when compared with the previous commands, for both central and secured cluster services.
I also checked that the commands for installing in limited-resources clusters work both standalone and when ran after the default installation commands.
=> doc: Align commands and descriptions in manual helm install section

central/networkbaseline/manager/manager.go, central/networkbaseline/manager/manager_impl.go, central/networkbaseline/manager/manager_impl_test.go, central/networkbaseline/manager/mocks/manager.go, central/networkbaseline/service/service_impl.go, central/networkbaseline/service/service_impl_sql_test.go, central/networkbaseline/service/service_impl_test.go, central/networkbaseline/testutils/utils.go, generated/api/v1/network_baseline_service.pb.go, generated/api/v1/network_baseline_service.pb.gw.go, generated/api/v1/network_baseline_service.swagger.json, generated/api/v1/network_baseline_service_grpc.pb.go, generated/api/v1/network_baseline_service_vtproto.pb.go, generated/api/v1/network_policy_service.swagger.json, proto/api/v1/network_baseline_service.proto
This extension to the network baseline API is to support the possible high-volume of external IP flows. The existing mechanism expects the caller to know about all of the flows up front, and will return status for only those flows, but the UI will not have this information for external IPs.
The new API endpoint will lookup the external flows and calculate the status all in the backend, returning a paginated list of anomalous and baseline peers back to the UI.
This is directly in support of https://issues.redhat.com/browse/ROX-28881 
~- [ ] modified existing tests~
Locally I've spun this up on an openshift 4 cluster, using Berserker to generate external traffic, manually querying the endpoint with …
=> feat(networkbaseline): external network baselines API

tests/upgrade/postgres_run.sh
Per upstream release instructions: https://spaces.redhat.com/display/StackRox/Upstream+Release+Automation#UpstreamReleaseAutomation-update-upgrade-testUpdateUpgradeTest
CI
=> chore(upgrade): Bump 4.7 previous version in upgrade test to 4.7.3

pkg/deduperkey/key.go, pkg/deduperkey/key_test.go
When analyzing customer logs, I noticed the following message:
```
pkg/deduperkey: 2025/05/13 08:30:40.888036 key.go:87: Warn: Deduper state has malformed entry: ComplianceOperatorSuiteV2:87dd96f6-0ddb-49d2-81c5-5829cd7de0ce->9529564071028443379: map type: invalid type: ComplianceOperatorSuiteV2
```
- I haven't, not sure if CI is enough, but that is a trivial change
=> fix(deduper): Add missing deduper type

pkg/networkgraph/networkbaseline/peer.go, sensor/common/detector/detector.go, sensor/common/detector/networkbaseline/network_baseline.go, sensor/common/detector/networkbaseline/network_baseline_test.go
With discovered external entities, Sensor was failing to detect network baseline violations because the discovered entity did not exist in Sensor's external src store at the time of detection:
1. Sensor updates its external entities store with entities from Central
2. A flow to a new discovered entity is received from Collector
3. Sensor looks up the entity ID and finds that it does not exist
4. Detection fails
5. Some time later, Central updates Sensor's external entities with the new discovered entity.
The changes here make it so that discovered entities are detected based on the live network flow rather than via the store, at stage (4) above.
Further changes in this PR anonymize discovered entities for the purposes of baseline anomaly detection by converting them to the Internet …
=> fix(violations): network baseline violations with ext IPs

qa-tests-backend/src/test/groovy/ExternalNetworkSourcesTest.groovy
This PR tries to fix tests by using different CIDR for each test case. This is due to an error that happens when Central updates external Networks in sensor that passes this data to collector and then the network is reported back to central causing problems when we try to manually upsert it again. Using different CIDRs for each test should solve this issue.
=> ROX-24313: use different CIDR for every test case

qa-tests-backend/src/main/groovy/services/AlertService.groovy
In ROX-29304, an `UNAVAILABLE` response gRPC code from the alert service caused a flake in the image signature integration tests. Hence, add the `Retry` annotation to the alert service to make sure we retry in such cases.
```
waitForViolation(deployment.name, policyName)
|                |          |     |
|                |          |     BOYPKI-Wildcard+Tekton
|                |          with-signature-unverifiable
|                <objects.Deployment@11c4b34d name=with-signature-unverifiable namespace=qa-signature-tests image=quay.io/rhacs-eng/qa-signatures:centos9-multiarch@sha256:743cf31b5c29c227aa1371eddd9f9313b2a0487f39ccfc03ec5c89a692c4a0c7 labels=[name:with-signature-unverifiable, app:image-with-unverifiable-signature-test] ports=[:] targetport=null volumes=[] volumeMounts=[] …
```
=> ROX-29304: add retry to alert service

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx
The CVE list GraphQL query is shared between the VM landing page and the Exception Management details page. It included a call to imageCVECount() that was only needed on the Exception Management page.
On the VM landing page, a separate query already handles the CVE/image/deployment counts for the entity buttons, and only re-fetches when its specific variables change. However, the shared query was also re-fetching imageCVECount() unnecessarily on unrelated changes (e.g. pagination), adding to performance issues.
This PR removes the unnecessary imageCVECount() call to improve performance.
Visit the Workload CVE list page and see that the table and counts load correctly:
Ditto with the exception management detail page:
=> fix(ui): Remove duplicate CVE count query from VM list page

central/networkbaseline/manager/manager_impl.go, central/networkbaseline/manager/manager_impl_bench_test.go, central/networkbaseline/manager/manager_impl_test.go, central/networkbaseline/manager/singleton.go, central/networkbaseline/service/service_impl_sql_test.go
Ensures network flows within baselines are correctly enriched with entity descriptions by leveraging the network tree manager. This fixes an issue where flow's Discovered flag is not populated, causing failures in anonymizing external flows in the baseline.
Mostly via the additional tests, but also using berserker to generate initial external network flows before triggering a baseline creation
=> fix(networkbaseline): Populate flow entity info using network tree

.github/CODEOWNERS
So that we're tagged for review on changes there.
No change.
Should just work, or not.
=> ROX-26148: Announce `./rpms.*` files ownership

ui/apps/platform/src/Containers/MainPage/Header/CLIDownloadMenu.tsx
Two for one change:
1. Remove one of the two deprecated instances of `<ApplicationLauncher>` in preparation for PF 6
2. Fix the issue with the CLI download dropdown that does not give an indication to the user that a download has started
1. Replace `react-toastify` notification implementation with PatternFly alerts
Open the CLI dropdown from the top masthead. The presentation of this list should be unchanged:
Clicking an item closes the dropdown and presents a toast using the pre-wired toast notification system:
=> ROX-27598: Replace deprecated CLI menu component

CHANGELOG.md, pkg/features/list.go
Set the feature to only use Red Hat data in Red Hat layer to disabled for now.
no
CI
=> chore(scanner): unset flag to only use Red Hat data

central/complianceoperator/v2/report/manager/format/formatter.go, central/complianceoperator/v2/report/manager/format/formatter_test.go, central/complianceoperator/v2/report/manager/generator/mocks/report_gen.go, central/complianceoperator/v2/report/manager/generator/report_gen.go, central/complianceoperator/v2/report/manager/generator/report_gen_impl.go, central/complianceoperator/v2/report/manager/generator/report_gen_impl_test.go
Given a map of failed clusters. The CSV formatter will generate a file per failed cluster with the reason for the failure.
- depends on #15201
- The entire functionality is tested in #15232
=> ROX-27490: Generate failed cluster report

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/hooks/useInvalidateVulnerabilityQueries.ts
Review with ignore whitespace setting.
GraphQL queries for deployment and image component vulnerabilities support `advisory` property **only if** backend `'ROX_FLATTEN_CVE_DATA'` feature flag is enabled.
Three levels of GraphQL queries and 2 pairs of components that request the data.
Bottom up for **deployment** components:
`deploymentComponentVulnerabilitiesFragment` in DeploymentComponentVulnerabilitiesTable.tsx file
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx#L29-L46
first `deploymentsForCveFragment` in AffectedDeploymentsTable.tsx file
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsT …
=> ROX-29313: Add conditional query to flatten CVE data

ui/apps/platform/cypress/integration/clusters/clustersCertificateExpiration.test.js, ui/apps/platform/cypress/integration/clusters/clustersHealthStatus.test.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js, ui/apps/platform/src/Components/CompoundSearchFilter/components/ConditionDate.tsx, ui/apps/platform/src/Containers/Clusters/cluster.helpers.test.js, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.test.ts, ui/apps/platform/src/utils/dateUtils.test.ts, ui/apps/platform/src/utils/dateUtils.ts
Fixes detection of user locales by explicitly checking `navigator.languages` instead of using `undefined` and relying on auto-detection. I have found sources online that state that the resolution of locale when using `undefined` does not always select the first option, leading to unexpected results. Unfortunately I have not found any primary sources in the spec or implementation that confirms this, but I can confirm with the following behavior when setting my browser to use `en-GB` as the default language.
```
navigator.languages
// ['en-GB', 'en']
let fmt = Intl.DateTimeFormat(undefined)
fmt.resolvedOptions().locale
// 'en-US'
```
This behavior results in US formatting still being used for other English locales, such as GB and AU.
In addition, for extra clarity in the case where …
=> fix(ui): Improve detection of specific locale for date formats

image/templates/helm/shared/config-templates/scanner-v4-db/postgresql.conf.default
Scanner V4 DB has a small number of very large tables, so having more autovacuum workers with a small amount of memory allocated for each will not be as useful as having a smaller number of workers with more memory allocated for each.
This change reduces the number of workers from the default, 3, to 2 and doubles the memory allocated to each worker (and separates it from the `maintenance_work_mem` config). Note: This means the max amount of memory used by autovacuum workers is 512MB, which is within the 1GB limit. See https://www.postgresql.org/docs/15/runtime-config-resource.html for more information.
no
We have experimented with changing these settings in a large environment, and they seem to be ok. The main thing we learned is that we have a few very large tables and the rest are …
=> chore(scanner): update autovacuum configs

scanner/updater/manual/vulns.yaml
Follow up from on https://github.com/stackrox/stackrox/pull/15161.
No.
@RTann helped validate this.
=> chore(scanner): one more CVE-2025-24813 entry

tests/e2e/run-scanner-v4-install.bats
This PR adapts the install test suite slightly to the recently merged scanner V4 defaulting changes: It removes the setting for opting-into scanner V4, thus relying on the default to kick in. So, effectively this now tests that scanner V4 is installed by default.
Just CI.
=> test: scanner v4 secured cluster CR tests

central/networkbaseline/manager/manager_impl.go, central/networkbaseline/manager/manager_impl_test.go, pkg/networkgraph/networkbaseline/peer.go
Final missed anonymization location, when the baseline is updated via the UI. e.g. a customer wants an entity to be added/removed from the baseline.
Provided unit test should be enough.
=> fix(networkbaseline): anonymize external entities in baseline update

deploy/charts/monitoring/templates/networkpolicy.yaml, scripts/release-tools/kube-burner-configs/berserker-load/config.yml, scripts/release-tools/kube-burner-configs/no-load-only-elasticsearch/config.yml, tests/performance/scale/config/metrics-full.yml
See the companion PR here https://github.com/stackrox/actions/pull/60
This PR changes the main config file used by kube-burner such that it sends results to OpenSearch/Elasticsearch.
The PR changes the network policy for the monitoring pod, such that is allows for ingress to port 9090. This is needed so that the Prometheus metrics can be obtained from the pod.
It also creates a kube-burner config file with no load but settings for sending results to OpenSearch/Easticsearch.
This just changes some config files so that kube-burner can send metrics to OpenSearch. This does not have an impact on production.
Testing was done here …
=> ROX-28665: Save metrics from long running clusters

scanner/datastore/postgres/distributions.go, scanner/datastore/postgres/distributions_test.go
RHEL 10 uses different CPEs from previous versions. It lists the Major.Minor version instead of just the Major version.
This change updates the regex we use to determine which OSes we support, so we can capture RHEL 10.
CI + installed `4.8.x-750-g5bc923da93` in a cluster and ran `roxctl -e <central endpoint> image scan -i registry.access.redhat.com/ubi10:latest` (same again for `registry.access.redhat.com/ubi10:10.0-1745487123`). Found not only did we get results, but also the note indicating we do not support the OS is not present
=> ROX-29320: support RHEL 10 CPEs

ui/apps/platform/src/Components/Pagination/NextPaginationButton/NextPaginationButton.test.jsx, ui/apps/platform/src/Components/Pagination/PaginationInput/PaginationInput.test.jsx, ui/apps/platform/src/Components/Pagination/PrevPaginationButton/PrevPaginationButton.test.jsx, ui/apps/platform/src/Containers/Collections/CollectionForm.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ApiTokenIntegrationForm/ApiTokenIntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/utils/integrationUtils.ts, ui/apps/platform/src/Containers/MainPage/Header/HelpMenu.tsx, ui/apps/platform/src/Containers/Policies/Detail/PolicyDetail.tsx, ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SeverityCountLabels.css
Instead of omitting the "Save as CR" option from the policy menu when a selected policy is a default policy, instead we keep the option in the menu, disabled, with a brief description why. This is consistent with how we handle the policy delete action, and can help prevent confusion for users who see that the option is missing from the menu with no indication why.
Open a default policy row menu:
Open a non-default policy row menu:
Open the top menu on a default policy page:
Open the top menu on a non-default policy page:
=> ROX-29093: Show disabled save as CR option when default policy

image/templates/helm/shared/templates/02-scanner-v4-07-indexer-deployment.yaml, image/templates/helm/shared/templates/02-scanner-v4-07-matcher-deployment.yaml, image/templates/helm/stackrox-central/internal/config-shape.yaml, image/templates/helm/stackrox-central/internal/defaults.yaml.htpl, image/templates/helm/stackrox-central/internal/expandables.yaml, image/templates/helm/stackrox-central/templates/_init.tpl.htpl, pkg/env/central_endpoint.go, pkg/env/sensor.go, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml, scanner/internal/httputil/transport_mux.go, scanner/internal/httputil/transport_mux_test.go
Not everyone uses `central.<namespace>.svc` nor `sensor.<namespace>.svc` as the Central and Sensor endpoints. Scanner V4 did not consider other possibilities, so it did not properly use mTLS between itself and Central (and Sensor) in these situations.
This PR allows users to customize the Central and Sensor endpoints via `ROX_CENTRAL_ENDPOINT` and `ROX_SENSOR_ENDPOINT` in Scanner V4 Indexer and Scanner V4 Matcher. These environment variables already exist and have been in-use elsewhere, but now Scanner V4 is adopting them.
CI
=> ROX-28690: stop hardcoding Central and Sensor endpoints

sensor/common/sensor/central_sender_impl.go
We want to know if broken message would break the connection by not being able to be marshaled when sending from Sensor to Central. This PR prints the message to the logs for easier investigation. Otherwise, one would need to convince the customer to apply a specially-built debug image to find the root cause of the problem.
- Trivial change, no need for validation
- Used it with 4.6 and a customer resolving a true issue https://github.com/stackrox/stackrox/pull/15308
=> ROX-29232: Log messages that crash grpc stream

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/searchFilterConfig.ts
Follow up with changes that I forgot in #15317
Vulnerabilities Exception Management:
https://github.com/stackrox/stackrox/commit/99c8b7ce745c73e1096eae23c7e6353c293e9fdf#diff-8dbd18bd8635ab21e0396fb96bf259c6ff033f36041f571b6481f27841f8fe7bL14-L16
1. Edit ApprovedDeferrals.tsx, ApprovedFalsePositives.tsx, DeniedRequests.tsx, and PendingRequests.tsx files.
* Call `convertToFlatVulnRequestSearchFilterConfig` function.
2. Edit searchFilterConfig.ts file.
* Add `convertToFlatVulnRequestSearchFilterConfig` function.
1. Although search filter is below tabs, they share the same filter settings (bravo) therefore the same configuration (and comment by bot about boilerplate).
* Therefore, it could make sense to lift configuration up to ExceptionRequestsPage.tsx file.
* Of course, if we followed …
=> ROX-29392: Add conditional search categories to ExceptionManagement

roxctl/common/client.go, roxctl/common/client_options.go, roxctl/common/client_options_test.go, roxctl/image/sbom/sbom.go
I noticed that `DefaultRetryPolicy` does not propagate any errors - hence we did not retry in cases where we should have. This is likely what caused the CI flake ROX-28991.
The code now relies on the `retry` return value to decide if we should retry. I also switched to `ErrorPropagatedRetryPolicy`, such that we can actually log a warning after each attempt. I removed the `ReturnRespBodyOnError` flag and set it to always true. This makes sure that the final error message contains Central specific error messages.
```
$ roxctl sensor generate openshift --output-dir=sensor-bundle --name remote3201 --insecure-skip-tls-verify=true
WARN:	unexpected HTTP status 500 Internal Server Error
WARN:	unexpected HTTP status 500 Internal Server Error
WARN:	unexpected HTTP status 500 Internal Server Error …
```
=> ROX-28991: fix roxctl sensor http retry

pkg/features/list.go
Be prepared to merge when cross-team say the time is right.
CI
=> ROX-28039: Enable ROX_CVE_ADVISORY_SEPARATION feature flag

README.md
The section about deploying StackRox in k8s providers contained the following
sentence:
> While the password file is stored in plaintext on your local filesystem, the
Kubernetes Secret StackRox uses is encrypted, and you will not be able to
alter the secret at runtime. If you lose the password, you will have to
redeploy central.
The initial "while" could be interpreted as duration, equivalent to: "as
long as the password is stored in plain text, the secret is encrypted".
This is incorrect: the initial "while" is meant to highlight that even
if the plain text password file can be edited at any time, that change
won't be picked up by Central and redeployment will be needed.
This commit removes that word altogether and rewords the sentence to
prevent confusion.
=> doc: Clarify note about changing admin cred secret at runtime

ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/FlowTable.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/ExternalFlows.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/ExternalIpsTable.tsx, ui/apps/platform/src/Containers/NetworkGraph/hooks/useNetworkBaselineStatus.ts, ui/apps/platform/src/hooks/useURLPagination.ts
Add pagination to the "External Flows" in the deployment-level Network Graph side panel.
**Why:**
- Large clusters may easily dump hundred of external flows into one table.
**Challenges:**
1. Two independent pagers
- The side panel shows anomalous and baseline flows side-by-side, so each table now owns its own `?anomalousPage=` / `?baselinePage=` and matching `PerPage` keys.
- `useURLPagination(perPage, keyPrefix)` now supports an optional `keyPrefix`, same pattern as `useURLParameter`.
2. Pagination clean up
- When the user closes the side panel or clicks a different node we `setPage(1)` and `setPerPage(10)`, clearing out any stray `?anomalousPage` / `?baselinePage` params.
=> ROX-29031: Add pagination to external flows tables

sensor/common/detector/enricher.go
Adds the image ID to various sensor scan logs to assist troubleshooting.
No tests added
CI / manual
```
$ k set image deploy/sensor sensor=quay.io/rhacs-eng/main:4.8.x-749-gd200c515ca
$ k apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
name: nginx-a
spec:
containers:
- name: main
image: nginx:1.27.5-bookworm
restartPolicy: Always
EOF
```
```
common/detector: 2025/05/20 15:15:04.639524 enricher.go:175: Debug: Sending scan to central for image "docker.io/library/nginx:1.27.5-bookworm" (ID "")
common/detector: 2025/05/20 15:15:09.514598 enricher.go:190: Debug: Successful image scan for image "docker.io/library/nginx:1.27.5-bookworm" (ID ""): 150 components returned by scanner
common/detector: 2025/05/20 15:15:11.314442 enricher.go:175: Debug: Sending scan to central for image …
```
=> ROX-29427: Add image id to sensor scan logs

ui/apps/platform/src/Containers/NetworkGraph/components/FlowBulkDropdown.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/FlowTable.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/ExternalFlows.tsx
Enable status updates for external flows (baseline ↔ anomalous) in Network Graph
Bulk-action improvement:
- Per-table dropdown: each table (baseline, anomalous) now has its own Bulk actions dropdown, so actions are always relevant to that list.
- Selection badge: the dropdown shows the "count" of selected flows, including those picked on other pages.
=> ROX-29032: Add ability to switch external flow status

central/networkbaseline/manager/manager_impl_test.go
Fixes https://issues.redhat.com/browse/ROX-29380
The race is not in the tested code, but in the mock set up of the tree manager. Moving the offending mock setup outside the concurrent code solves the issue.
=> fix(tests): moves GetDefaultNetworkTree mock out of concurrent setup

central/processlisteningonport/datastore/datastore_impl.go, central/processlisteningonport/service/service_impl.go, central/processlisteningonport/service/service_impl_test.go, generated/api/v1/process_listening_on_port_service.pb.go, generated/api/v1/process_listening_on_port_service.pb.gw.go, generated/api/v1/process_listening_on_port_service.swagger.json, generated/api/v1/process_listening_on_port_service_vtproto.pb.go, pkg/fixtures/fixtureconsts/fixture_consts.go, pkg/fixtures/process_listening_on_port.go, proto/api/v1/process_listening_on_port_service.proto, qa-tests-backend/src/main/groovy/services/ProcessesListeningOnPortsService.groovy, qa-tests-backend/src/test/groovy/ProcessesListeningOnPortsTest.groovy
Adds pagination to the processes listening on ports service. Currently if a deployment has a large number of listening endpoints they are all returned, regardless of how many there are. This can mean a slow response from the API endpoint and can cause the UI to freeze up. This does not do pagination for the UI. That will be done at a later time.
The service endpoint also now returns the number of listening endpoints in addition to the listening endpoint themselves. This is because users will want to know how many listening endpoints there are when the service doesn't return all of them.
The pagination is done in central rather than by the query, because central does some filtering so using `LIMIT` in the query does not guarantee the number of listening endpoints in the response.
E2e tests …
=> ROX-20499: Pagination for the listening endpoints API

ui/apps/platform/src/Containers/SystemConfig/Details/PlatformComponentsConfigDetails.tsx, ui/apps/platform/src/Containers/SystemConfig/Details/SystemConfigDetails.tsx, ui/apps/platform/src/Containers/SystemConfig/Details/components/RedHatLayeredProductsCard.tsx, ui/apps/platform/src/Containers/SystemConfig/Form/SystemConfigForm.tsx, ui/apps/platform/src/Containers/SystemConfig/SystemConfigPage.tsx, ui/apps/platform/src/Containers/SystemConfig/configUtils.ts, ui/apps/platform/src/types/config.proto.ts
This PR refactors a few things in preparation for the changes in the System Config Form. Some changes that were made:
1.  **General changes**
1. Falling back to displaying `None` when the regex is not present.
2. Hiding the `View more` button if there is nothing to show.
3. **PlatformComponentsConfigDetails**
1. We now accept a prop for the `platformComponentsConfig` instead of the hardcoded value.
2. We are utilizing a `getPlatformComponentsConfigRules` function to extract the rules in a more structured way to be used in both the details view and the form.
4. **SystemConfigDetails**
1. We will move the feature flag hook up the parent and pass `isCustomizingPlatformComponentsEnabled` as a prop.
5. **SystemConfigForm**
1. Fixing a Typescript issue related to having …
=> ROX-29418: Refactoring system config pt.1

sensor/kubernetes/listener/resources/convert.go, sensor/kubernetes/listener/resources/convert_test.go
Images are marked `not pullable` in various scenarios, one of which is when a container is not yet 'ready' which is often inaccurate and leads to log spam and confusion. This PR reduces the log spam and at the same time attempts to make the `not pullable` designation slightly more accurate.
When a deployment is first observed, an image scan is triggered if the podspec image is a valid reference - afterwards when the associated pods are created that same image may be marked as `not pullable` if the `status.containerStatuses[].imageID` field is not populated (which will happen if the container is not ready). Since an attempt was already made to scan the image when the deployment was first observed it should also be OK to attempt to scan the image when the pod is being created.
CI + manual …
=> ROX-29417: reduce not pullable spam

central/image/service/service_impl.go, central/image/service/service_impl_test.go, sensor/common/detector/enricher.go
The observed 'names' for an image are used to determine if a cached scan should be used (amongst other things). When these names are 'lost' cache misses will occur and potentially lead to excessive registry traffic (observed in the wild).
This PR enhances both Central's and Sensor's handling of image names to ensure names are not lost, increasing chances of cache hits.
Unit tests + manual testing
<details>
<summary>Setup Commands</summary>
To deploy nginx-a:
```
$ k apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
name: nginx-a
spec:
containers:
- name: main
image: nginx:1.27.5-bookworm
restartPolicy: Always
EOF
```
To deploy nginx-b
```
$ k apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
name: nginx-b
spec:
containers:
- name: main
image: nginx:1.27.5
restartPolicy: Never …
```
=> ROX-19095: Ensure image names are not lost

.github/workflows/build.yaml, .github/workflows/scanner-build.yaml, .tekton/basic-component-pipeline.yaml, .tekton/main-pipeline.yaml, .tekton/operator-bundle-pipeline.yaml, .tekton/retag-pipeline.yaml, .tekton/scanner-v4-pipeline.yaml, scripts/ci/should-konflux-replace-gha-build.bats, scripts/ci/should-konflux-replace-gha-build.hold, scripts/ci/should-konflux-replace-gha-build.sh
For release builds, for `quay.io/rhacs-eng` images.
Paired with https://github.com/stackrox/konflux-tasks/pull/55
No change.
See https://github.com/stackrox/konflux-tasks/pull/55
=> ROX-27716: Enable Konflux builds to replace GHA

central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl.go, pkg/features/list.go
There were two ways of naming the receiver var in this file:
- `func (ds *datastoreImpl)`
- `func (d *datastoreImpl)`
as the first one was more popular, I changed all occurrences of the second one to get rid of the IDE style warning.
- in CI we trust
=> chore(refactor): Unify receiver var name in compliance datastore

scripts/retry-kubectl.sh
Running `make -C operator deploy-via-olm`, I started getting this error:
```
2025-05-26T15:20:43Z Creating namespace...
./hack/../../operator/hack/retry-kubectl.sh: line 48: unexpected EOF while looking for matching `"'
```
This was because on mac os /bin/bash is a legacy version (v3.2).
Ran `make -C operator deploy-via-olm` on my machine. CI should cover the rest.
=> fix: use bash from env in retry-kubectl.sh

central/cloudsources/datastore/singleton.go, central/main.go
Optimize central startup time to get the API endpoint up and running sooner. Refactoring the startup of the services to a go routine.
Note: I intend to merge the PR only after 4.8 is cut to get improved soak times.
CI perf tests
Manual scaled cluster with 10 fake sensors running 10-sensors workflow and randomly restarting central - for over 3-4 hours. No crashes observed.
=> ROX-29036: Optimize central API endpoint bringup

tests/upgrade/postgres_run.sh
Per upstream release instructions: https://spaces.redhat.com/display/StackRox/Upstream+Release+Automation#UpstreamReleaseAutomation-update-upgrade-testUpdateUpgradeTest
CI
=> chore(upgrade): Bump 4.6 previous version in upgrade test to 4.6.6

.github/workflows/unit-tests.yaml, Makefile
This PR runs sensor integration tests on GHA with kind cluster. This will replace PROW job that do the same but on GKE cluster.
=> tests: run sensor integration tests on GHA

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigOptions.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/useFormikScanConfig.tsx
The scan config name is used as a foreign key in the results table. Changing the name would cause scan results to lose association with the scan config.
Backend change to block scan config name change is added in: https://github.com/stackrox/stackrox/pull/15333
=> ROX-28348: Disable changing of scan config name

central/pruning/pruning.go
For inactive images retention value of 0, the expectation is that the inactive images will never be pruned. However there is a bug in pruning logic which causes the inactive images to get instantly pruned every hour when the retention value is 0. This could lead to frequent resetting of the firstDiscovered and firstImageOccurrence times of the CVEs in images that are only temporarily inactive.
Manual test- pending
=> ROX-29453: Inactive image retention setting 0 should never prune images

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx
1. Thank you, **David Vail** for finding inconsistent `colspan="5"` attribute of `td` element when presence of **Advisory** column increases total to 6.
Therefore layer has less than available width.
2. When I expanded the wrong `td` element, I also found inconsistent `colspan` attribute for component table itself.
* Images: `colspan={7}` attribute is out-of-date and too small.
* Deployments: `colspan={6}` attribute is up-to-date, becamebut incorrect when I substituted inline value with computed value, because `colspan={8}` attribute of `TbodyUnified` for filtered empty state is incorrect. Maybe copy-paste from images?
Follow conditional `colSpan` pattern from elsewhere.
Temporarily edit code to …
=> ROX-29492: Compute conditional colSpan according to Advisory column

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
It might help to ignore whitespace for review.
Thank you:
* **Ross Tannenbaum** for finding this problem.
* **David Vail** for suggesting the cause.
Component vulnerabilities tables render `PartialCVEDataAlert` element if either `summary` or `imageMetadata` are absent.
Other tables render `PartialCVEDataAlert` if `summary` is absent.
This seems like copy-paste-edit from one condition to two conditions.
1. Render `summary` conditionally, else nothing.
2. Render `WhateverComponentVulnerabilitiesTable` conditionally else `PartialCVEDataAlert` element.
That is, in the context, omit secondary `summary` silently if absent, and render **Partial CVE data** only if primary `imageMetadata` is absent.
Image: …
=> ROX-29493: Render component vulnerabilities table if imageMetadata

deploy/deploy.sh
IntelliJ seems to have trouble following/GOTOing scripts that are called without `.` or `source`.
- ~~[ ] the change is production ready: the change is [GA](https://github.com/stackrox/stackrox/blob/master/PR_GA.md), or otherwise the functionality is gated by a [feature flag](https://github.com/stackrox/stackrox/blob/master/pkg/features/README.md)~~
N/A
Before:
In IntelliJ (or an IntelliJ-based IDE such as GoLand), right click > Go To > Declaration or Usages returns an error `Cannot find declaration to go to`.
After:
IntelliJ jumps to the correct file.
=> fix: source deploy scripts

central/complianceoperator/v2/checkresults/datastore/datastore.go, central/complianceoperator/v2/checkresults/datastore/datastore_impl.go, central/complianceoperator/v2/checkresults/datastore/datastore_impl_test.go, central/complianceoperator/v2/checkresults/datastore/mocks/datastore.go, central/complianceoperator/v2/compliancemanager/manager_impl.go, central/complianceoperator/v2/compliancemanager/manager_impl_test.go, central/complianceoperator/v2/compliancemanager/singleton.go
This PR is adding cleanup of scan results when scan config (schedule) is changed and clusters or profiles are removed from that schedule.
Additional changes:
- protection for changing scan config is added (we are using scan config name as a foreign key in the results table)
- smaller refactoring of tests is done because several test data creation functions could be replaced with one with additional parameters
=> ROX-28348: Cleanup results on scan config update

image/postgres/Dockerfile
The central-db image build target silently pulls an amd64 base image for all architectures (the current image isn't multi-arch), the end result being that 
non-x86 versions of the central-db image are not runnable on their respective architectures. These images are not directly tested.
```
docker run -it --entrypoint /bin/bash quay.io/rhacs-eng/central-db:latest-arm64 -c "readelf -h /usr/bin/postgres" | grep Machine
Machine: Advanced Micro Devices X86-64
docker run -it --entrypoint /bin/bash quay.io/rhacs-eng/central-db:latest-s390x -c "readelf -h /usr/bin/postgres" | grep Machine
Machine:  Advanced Micro Devices X86-64
```
Images built by CI now have the correct layer for amd64 and arm64
```
$ docker run -it --entrypoint /bin/bash …
```
=> fix(multiarch): use centos9 for central-db image

central/complianceoperator/v2/pipelines/complianceoperatorinfo/pipeline.go, central/complianceoperator/v2/pipelines/complianceoperatorinfo/pipeline_test.go
We are getting empty versions for clusters where compliance is not installed (or there is no integration).
For example: GKE cluster
This PR is changing the logic for checking the supported compliance operator version. It will ignore compliance operator information if the compliance operator is not installed.
=> ROX-28348: Skip compliance operator version check for empty versions

operator/api/v1alpha1/central_defaults.go, operator/api/v1alpha1/central_types.go, operator/api/v1alpha1/securedcluster_defaults.go, operator/internal/central/values/translation/translation_test.go, operator/internal/securedcluster/scanner/auto_sense.go, operator/internal/securedcluster/scanner/defaults.go, operator/internal/securedcluster/values/translation/translation.go, operator/internal/securedcluster/values/translation/translation_test.go
Literal `"Default"` values (e.g. injected by the previous version of the CRD) need to be treated in a sane manner in our new defaulting setting, ideally causing little or no surprises for the user. My proposal: Treat them the same as "not specified".
Manual tests conducted:
```
make -C operator olm-install
make -C operator deploy-previous-via-olm
kubectl -n stackrox-operator patch --type=merge catalogsources.operators.coreos.com stackrox-operator-test-index -p "{\"spec\":{\"image\": \"$(kubectl -n stackrox-operator get catalogsources.operators.coreos.com stackrox-operator-test-index -o jsonpath='{.spec.image}' | sed -e 's/stackrox-io/rhacs-eng/;')\"}}"
kubectl create ns stackrox
kubens stackrox
./deploy/common/pull-secret.sh stackrox quay.io | kubectl -n stackrox apply -f -
kubectl apply …
```
=> ROX-29199: Treat "Default" vals in CRs the same as not-specified

ui/apps/platform/package-lock.json, ui/apps/platform/package.json
As titled. This needs an override as the <2.x version dependency comes from a transitive dependency of `react-scripts`, which will not be getting updates.
The breaking changes from 1.x to 2.x are:
- The main export is now a default export.
- The module now throws regular Errors on invalid selectors instead of SyntaxErrors.
Manual testing of UI and verification the SVGs in Network Graph, old VM are loaded correctly into the UI.
CI.
=> chore(ui): Update nth-check dependency

central/complianceoperator/v2/scanconfigurations/service/convert.go, central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go
The Blob store uses a different access scope than Compliance. We need to use the correct context to Search in the Blob store.
Problem:
1. Create a user with the following permissions:
- Cluster Read
- Compliance Read/Write
- Integration Read
2. Create a Schedule with that user
3. Generate a Download
4. Observe in the logs/db that the download is generated correctly
5. Observe that cannot be downloaded through the UI and we see error messages in the logs in the convert function
After these changes the steps (4) and (5) should be fixed and we should be able to download the report from the UI.
- Follow-up on #15513
=> fix(access): Use proper access in the convert functions

central/delegatedregistryconfig/delegator/delegator.go, central/delegatedregistryconfig/delegator/delegator_test.go, central/detection/service/service_impl.go, central/image/service/service_impl.go, generated/api/v1/detection_service.pb.go, generated/api/v1/detection_service.swagger.json, generated/api/v1/detection_service_vtproto.pb.go, generated/api/v1/image_service.pb.go, generated/api/v1/image_service.swagger.json, generated/api/v1/image_service_vtproto.pb.go, pkg/delegatedregistry/delegator.go, pkg/delegatedregistry/mocks/delegator.go, pkg/images/enricher/enricher.go, pkg/images/enricher/enricher_impl.go, pkg/images/enricher/enricher_impl_test.go, proto/api/v1/detection_service.proto, proto/api/v1/image_service.proto, roxctl/image/check/check.go, roxctl/image/scan/scan.go, roxctl/maincommand/command_tree_debug.yaml, roxctl/maincommand/command_tree_release.yaml
Add a `--namespace` flag to `roxctl image scan` and `roxctl image check`. The idea behind this change is to give users the ability to let Sensor read context information from a namespace in the delegated cluster. Specifically, this allows Sensor to use a namespace scoped pull secret to access the image container registry. Consequently, we can integrate with image registries via short-lived credentials created by external secrets operator.
Setting up external secrets 
```
apiVersion: v1
kind: Namespace
metadata:
name: quay-keyless
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: quay
namespace: quay-keyless
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: QuayAccessToken
metadata:
name: quay-token
namespace: quay-keyless
spec:
url: quay.io
robotAccount: keyless+test …
```
=> ROX-24719: add --namespace flag for roxctl image scan/check

operator/internal/common/defaulting/secured_cluster_scanner_v4_enabling.go
Currently some of the log messages for the Scanner V4 defaulting look like this:
```
2025-06-03T09:21:37Z    INFO    controllers.SecuredCluster.extension-feature-defaults.defaulting-flow-scanner-V4.scanner-v4-defaulting   using componentPolicy set in CR {"componentPolicy": "Disabled"}
```
There is a superfluous level of nesting in the logger name. This PR removes the final nesting layer `scanner-v4-defaulting`, which doesn't add any value.
No changes required.
Production ready.
No tests added or modified.
Just CI.
=> fix: Remove nested logger name

ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/ExternalIpsContainer.tsx, ui/apps/platform/src/hooks/useAnalytics.ts
The main goal is to track whether users are interacting with External IPs and infer if the collector feature flag is enabled.
Note:
- Once side panel routing is added to the Network Graph, these tracking events can be removed. At that point, we’ll look for a more reliable way to detect if the collector feature flag `externalIps` is active.
Verified in segment:
**External IPs:**
1. Empty table with no filters
2. Empty table due to filters
3. Table with data
**External Flows:**
1. External toggle clicked:
2. Internal toggle clicked:
=> ROX-29415: Add External IPs analytics

ui/apps/platform/src/global/initializeAnalytics.js, ui/apps/platform/src/hooks/useAnalytics.ts
Goals:
1. Eliminate the initial `analytics.page()` event that bypassed our redaction logic when analytics is initialized
- This was also causing duplicate `page` events on initial app load, since we already trigger our own `page` event when `Body` mounts
2. Ensure `sidePanel` query parameters are redacted since they may contain sensitive data
**Duplicate Page Events (Before):**
When first visiting the app, both of the following `analytics.page()` events were triggered, one from the default segment snippet and one from our `Body` component:
After Fix: Once the default `analytics.page()` call was removed, only our intended page event (2nd) is sent.
**Redacted `sidePanel`**
=> chore(ui): Remove initial telemetry page event, redact sidePanel

ui/apps/platform/src/Containers/NetworkGraph/deployment/ExternalFlows.tsx
Adds a confirmation modal to status updates in Network Graph External Flows.
Because flow status is determined by the combination of direction, port, and protocol (**not** by individual flows) we want to clarify for users what updates will be applied and that related flows will also be affected.
Error state:
=> ROX-29574: Add external flows confirmation modal

central/views/images/view_impl.go
The image view chooses distinct image SHAs for a given query. However, if the sort option in the query is a field that is not part of image schema, it is added to the distinct clause by search framework. This could result in duplicate images being returned from the view.
Manual testing
=> ROX-29596: Fix duplicate images returned when expanding CVEs with different severities in different images

pkg/cloudproviders/aws/metadata.go, pkg/providers/metadata.go
ACS attempts to get metadata from cloud providers' internal metadata services. This is used to set metadata fields in the cluster status. These calls are expected to fail in various scenarios (access to internal metadata endpoint is blocked, unknown cloud provider, bare metal deployment, ...). Therefore, failing metadata calls do not necessarily indicate a problem.
Unfortunately we frequently see users getting confused by these logs (recent example is https://issues.redhat.com/browse/ROX-29550), which may provide a red herring during debugging. Hence, let's remove redundant logs and reduce severity to `debug`.
change me!
=> fix: change metadata log severity to debug

central/image/service/service_impl.go, central/image/service/service_impl_test.go
When scans are delegated/handled by Sensor the image is [flagged as cluster local](https://github.com/stackrox/stackrox/blob/8aa699b3a1fb1998e8750432a22cbbb76f30957c/central/image/service/service_impl.go#L591)
Cluster local images will [not be reprocessed by Central](https://github.com/stackrox/stackrox/blob/e09eea9d3eb55bae5bd3b7625a03ad2f698e423a/central/reprocessor/reprocessor.go#L324) (Sensor handles the reprocessing instead) - images can get stuck in a state where they are never reprocessed.
This can occur, for example, when delegated scanning is enabled and then subsequently disabled - or `roxctl` scans are executed with the `--cluster` flag for active images while delegated scanning is disabled.
This PR adds a reset / 'self-heal' capability - when Sensor requests a scan from …
=> ROX-18779: Reprocess formerly cluster local images

central/networkgraph/flow/datastore/internal/store/postgres/cluster_impl.go, central/networkgraph/flow/datastore/internal/store/postgres/store.go, central/networkgraph/flow/datastore/internal/store/postgres/tests/store_test.go, central/networkgraph/flow/datastore/internal/store/testcommon/flow.go
This PR is a duplicate of https://github.com/stackrox/stackrox/pull/15445. The difference is that this is based on master, whereas the other PR is based on a another PR.
The "discovered" entities pruner is located in the FlowStore component to benefit from an interesting optimization : we use the result of the procedure deleting flows to get a list of the entities 'potentially' orphaned. The verification that an entity is no longer in use (orphaned) is then executed on a much smaller set.
Unfortunately, the EntityStore keeps a "in-memory" copy of all the entities : this is done by the Network-Trees.
The [initial implementation](https://github.com/stackrox/stackrox/pull/14769) of the discovered-entities pruner forgot to delete the entities in the Network-Trees after they are deleted from …
=> ROX-29400: prune also in network trees

central/complianceoperator/v2/report/manager/manager_impl.go, central/complianceoperator/v2/report/manager/metrics.go, central/complianceoperator/v2/report/manager/watcher/metrics.go, central/complianceoperator/v2/report/manager/watcher/scanwatcher.go, pkg/env/compliance_operator.go, sensor/kubernetes/complianceoperator/handler_impl.go, sensor/kubernetes/complianceoperator/metrics.go
This PR adds the following metrics:
1. Number of scans running in parallel. The goal was to capture the temporal aspects, so we divide the time into time-windows, and count what was the max number of scan watchers active in a given time window. Default window is 15 minutes.
2. How long a scan would take - i.e., what is the lifetime of a scan watcher in Central. This maybe skewed if Central frequently restarts, but that should be rare.
3. What kind of CO-related messages Central sends to Sensor.
I validated the metrics on a cluster.
```
rox_sensor_complianceoperator_apply_scan_config_commands_from_central_total{operation="*central.ApplyComplianceScanConfigRequest_ScheduledScan_"} 3
rox_sensor_complianceoperator_commands_from_central_total{operation="*central.ComplianceRequest_ApplyScanConfi …
```
=> ROX-29548: Add Prometheus metrics for Compliance Operator reporting

pkg/env/scannerv4.go, pkg/features/list.go, scanner/indexer/indexer.go
Adds a configurable feature to allow Scanner V4 indexer to reach out to a configurable URL to get additional information about JAR dependencies via the Maven search API during indexing.
This particular feature is meant to be a temporary workaround until we have a more permanent fix, e.g., resolving [CLAIRDEV-93](https://issues.redhat.com/browse/CLAIRDEV-93).
N/A. This feature is meant to be a temporary workaround and will be documented in a KCS.
- ~~[ ] added unit tests~~
- ~~[ ] added e2e tests~~
- ~~[ ] added regression tests~~
- ~~[ ] added compatibility tests~~
- ~~[ ] modified existing tests~~
Container image under test: `quay.io/rhacs-eng/qa:tomcat-9.0.59`
Deploy stackrox:
```
❯ export MAIN_IMAGE_TAG=4.8.x-875-g1a6f5ce768 # or w/e the latest PR tag is
❯ ./deploy/deploy.sh
```
Get …
=> ROX-22663: Add configurable Maven search

migrator/clone/clone_test.go
Some tests in the migrator were not actually running on release tags—they returned early instead of executing, which made them appear to pass. This PR explicitly skips those tests to accurately reflect that they are not being run.
=> tests: properly skip test on release

.tekton/basic-component-pipeline.yaml, .tekton/main-pipeline.yaml, .tekton/operator-bundle-pipeline.yaml, .tekton/retag-pipeline.yaml, .tekton/scanner-v4-pipeline.yaml
From https://github.com/stackrox/konflux-tasks/pull/66.
No change.
Only CI here.
=> ROX-29602: Use updated `determine-image-tag` task

ui/apps/platform/src/Containers/Vulnerabilities/searchFilterConfig.ts
Deployment:Status (Active/Inactive) was an available search filter in VM pages, but is not relevant to VM entities. This filters is used specifically for filtering on Policy Violations.
This filter likely came along for the ride when it was added to the global deployment filters for work on the Violations page. 
Does it make more sense to include all filters per-category on pages, or explicitly opt-in to every filter as it is added? I am leaning towards the latter, as the worst case there is we miss a new filter, which should be caught with manual testing. In the former case, we risk unintentionally adding a new filter to sections that appears broken.
Check that the "Status" filter no longer exists in VM:
=> fix(ui): Remove 'Inactive Deployment' filter from VM pages

go.mod, go.sum, operator/internal/central/reconciler/reconciler.go, operator/internal/common/extensions/mapkubeapis.go, operator/internal/securedcluster/reconciler/reconciler.go
Fixes https://issues.redhat.com/browse/ROX-19315 i.e. operator getting stuck if an API disappears from under a stackrox installation.
This is a PoC which uses a [slightly hacked](https://github.com/porridge/helm-mapkubeapis/pull/1) mapkubeapis plugin. This change is already merged upstream and released in https://github.com/helm/helm-mapkubeapis/releases/tag/v0.6.1 but this version requires go 1.24. Dropping the fork is tracked separately.
1. Applied an [istio CRD](https://github.com/istio/istio/blob/release-1.16/manifests/charts/base/crds/crd-all.gen.yaml).
2. ran the operator from `master`
3. removed the CRD
4. triggered another reconcile, operator got stuck
5. stopped it and ran it from this branch:
```
2025-02-20T12:39:47+01:00	INFO	controllers.SecuredCluster	API not present, marking …
```
=> feat(operator): handle istio API disappearance

scripts/ci/sensor-wait.sh
See https://issues.redhat.com/browse/ROX-29308.
According to the CI failure logs linked in the ticket:
```
INFO: Fri May 30 23:18:51 UTC 2025: [upgrade-to-HEAD-sensor] Sensor deployed. Waiting for sensor to be up
INFO: Fri May 30 23:18:51 UTC 2025: [upgrade-to-HEAD-sensor] Waiting for sensor to start in namespace stackrox-sensor
INFO: Fri May 30 23:18:51 UTC 2025: [upgrade-to-HEAD-sensor] Sensor replicas: 1
INFO: Fri May 30 23:18:51 UTC 2025: [upgrade-to-HEAD-sensor] Sensor readyReplicas: null
INFO: Fri May 30 23:19:31 UTC 2025: [upgrade-to-HEAD-sensor] Unable to connect to the server: dial tcp: lookup api.rox-ci-38203904.ocp.ci.rox.systems on 172.30.0.10:53: read udp 10.128.73.106:41695->172.30.0.10:53: i/o timeout
INFO: Fri May 30 23:19:31 UTC 2025: [post-test-tear-down] FAILED: Test …
```
=> ROX-29308: Use retrying kubectl wrapper in sensor-wait script

operator/EXTENDING_CRDS.md
Explain how the new defaulting extension works and how to add new defaulting flows.
Only changes to internal docs.
Only docs.
None.
None.
=> ROX-29465: Add dev docs for operator defaulting extension

.github/workflows/performance-tests.yml, scale/dev/launch_sensor.sh
Initial investigation showed that sensors were properly scheduled and working, but after some additional testing, it turned out that this is not true. It appears that the sensors are not running, which is why the workload is not being created.
**Further findings**
It looks like the specific node becomes unstable, and sensors scheduled on that node never reach the `running` state. It's not clear what causes node instability. After additional testing, the most stable solution option is to deploy central without scanner V4 and set sensor memory request higher.
=> ROX-29641: Fix k6 tests

ui/apps/platform/cypress/integration/vulnerabilities/VulnerabilityReporting/reportForm.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CloneVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CreateVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/EditVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/ReportFormWizard.tsx
Combines the nearly identical form wizards for create, clone, and edit in VM reporting for ease of testing and migrating to the non-deprecated PF Wizard component.
Existing e2e tests for the report wizard and config creation.
Manual smoke test of edit and clone functionality.
=> chore(ui): Refactor VM report forms to use a shared wizard

pkg/signatures/cosign_sig_verifier.go, pkg/signatures/cosign_sig_verifier_test.go
OCP images are signed by [Red Hat Release Key 3](https://security.access.redhat.com/data/63405576.txt), however they show as unverified.
Steps to reproduce:
- Add signature integration for  [Red Hat Release Key 3](https://security.access.redhat.com/data/63405576.txt) without transparency log verification.
- Scan any OCP image (note that a Red Hat pull secret is needed)
- Verification fails.
The problem is that the "docker-reference" field of the signature payload contains the full image reference, including its digest:
```json
{
"critical": {
"identity": {
"docker-reference": "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c896b5d4b05343dfe94c0f75c9232a2a68044d0fa7a21b5f51ed796d23f1fcc5"
},
"image": {
"docker-manifest-digest": …
```
=> ROX-29716: Fix signature verification for OCP images

ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/Containers/SystemHealth/Components/IntegrationHealthWidgetVisual.tsx, ui/apps/platform/src/Containers/SystemHealth/SystemHealthPage.tsx
Prerequisite changes for future `'pluginGeneric/export-default-react'` lint rule.
Find in Files results can mislead if component name is inconsistent with file name.
1. Rename DashboardPage.jsx as SystemHealthPage.tsx and rewrite in TypeScript.
2. Rename `IntegrationHealthWidget` component according to file name.
3. `npm run build` in ui/apps/platform folder.
=> ROX-29656: Fix inconsistent names in System Health

image/templates/helm/shared/templates/_scanner-v4_defaulting.tpl, image/templates/helm/stackrox-central/.helmtplignore.htpl, image/templates/helm/stackrox-central/templates/00-stackrox-helm-configmap.yaml, image/templates/helm/stackrox-central/templates/_init.tpl.htpl, image/templates/helm/stackrox-central/templates/_stackrox_helm.tpl, image/templates/helm/stackrox-secured-cluster/.helmtplignore.htpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, image/templates/helm/stackrox-secured-cluster/templates/_scanner-defaulting.tpl, image/templates/helm/stackrox-secured-cluster/templates/_stackrox_helm.tpl, image/templates/helm/stackrox-secured-cluster/templates/stackrox-helm-configmap.yaml, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml, pkg/renderer/render_new.go, tests/e2e/run-scanner-v4-install.bats
[PR to be reviewed commit-by-commit.]
**Hot fix for broken Scanner V4 defaulting logic in Helm charts.**
It is unfortunate that it has been overlooked that the `helm upgrade` scenario does *not* work as expected in the current `master` & `release-4.8` branches.
Nevertheless, this is a **release blocker** -- this PR contains a less-trivial change for our both of our Helm charts.
Context: [Slack thread](https://redhat-internal.slack.com/archives/C073B31JVDY/p1749831795950259).
I will describe the problem that has been reported by @dcaravel in my own words:
The upgrade logic in both Helm charts is broken according to common-sense expectations by users of the Helm charts. Assume:
1. Users installs central-services (resp. secured-cluster-services), relying on Scanner V4 defaults -> Scanner V4 …
=> fix: Helm: Keep scanner-v4 enabled except for upgrades from 4.7

ui/apps/platform/cypress/helpers/wizard.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CloneVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CreateVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/EditVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/ReportFormWizard.tsx
As titled. No functional changes, only a change in the underlying component.
Going to step 2 of the wizard, adding a delivery destination, and then removing the delivery destination locks the form in an "invalid" state and makes navigation impossible without reloading.
CI tests created exactly for this moment.
Manual smoke test of wizard in create/edit/clone modes.
=> chore(ui): Replace deprecated Wizard component in VM reporting

ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigWizardFooter.tsx
Part one refactor to aid in review of deprecated wizard component replacement. This change inlines the local components for the ScanConfigWizardFooter.
Since the helper function parameters were inferred to be `any`, this also converts the second argument of `proceedToNextStepIfValid` to a string, since all calling code expects that type.
CI
=> chore(ui): Inline ScanConfigWizard local subcomponents

tests/e2e/run-scanner-v4-install.bats
As titled, `s/_/-/`.
Viewing output in release-4.8 workflow failure.
` INFO: Tue Jun 17 13:09:17 UTC 2025: [setup-file] ERROR:	unknown flag: --image_defaults `
Locally with `roxctl helm output secured-cluster-services --help` to validate flag naming.
=> fix: Fix image-defaults flag in scanner install test

central/serviceaccount/internal/store/store.go, central/serviceaccount/search/searcher_impl.go
Searching raw services results, used 2 passes to get the data.  First it would make a query to get the IDs and then it would take the IDs to get the data.  This is a left over concept from our dackbox indexer and old key value store.  Now that we have Postgres we can simply get the data we do not and in most cases should not get the IDs first as that is a waste of a trip to the database.  This solves that by converting that function to use the new `GetByQueryFn` utilities to simply get the objects from the query.
CI should be sufficient here as functionality is exactly the same.
=> ROX-29753: service account search to get results in one query

pkg/features/list.go
This PR introduces a new feature flag (ROX_RED_HAT_IMAGES_SIGNED_POLICY) to be able to deliver parts of [ROX-29160](https://issues.redhat.com/browse/ROX-29160) gradually without interfering with StackRox normal operation.
I followed the same process as with other flags.
=> ROX-29160: Add feature flag ROX_RED_HAT_IMAGES_SIGNED_POLICY

central/graphql/resolvers/service_accounts.go, central/serviceaccount/service/service_impl.go
The pagination portion of the query was not pulled into the query.  This issue is as old as time, present at least since 2019 based on historical PRs.
Spun up a cluster and ran curl commands against the endpoint.
Before
```
dashrews-mac:stackrox dashrews$ curl --insecure "https://localhost:8000/v1/serviceaccounts?pagination.limit=2" -u admin: | json_pp
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  115k  100  115k    0     0  82921      0  0:00:01  0:00:01 --:--:-- 82930
{
"saAndRoles" : [
{
"clusterRoles" : [
{
"annotations" : {
"rbac.authorization.kubernetes.io/autoupdate" : "true"
},
"clusterId" : "ac1ee931-ddcb-4bcc-a6b4-ac2da559c0e3",
"clusterName" : "remote",
"clusterRole" : true,
"createdAt" : …
```
=> ROX-29776: service account service drops pagination

ui/apps/platform/package-lock.json, ui/apps/platform/package.json
Only one `import` statement:
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Vulnerabilities/hooks/useInvalidateVulnerabilityQueries.ts#L2
By the way, both `graphql` and `@apollo/client` have several alpha releases for next major version.
1. `npm run build` in ui/apps/platform
2. CI
=> ROX-29756: Update graphql 16.11.0 in dependencies

ui/apps/platform/README.md
Delete mention of `eslint.experimental.useFlatConfig` because no longer needed.
1. ESLint plugin version update from a year ago 2024-06-19
https://github.com/Microsoft/vscode-eslint?tab=readme-ov-file#version-305---pre-release
> There is a new eslint.useFlatConfig setting which is honored by ESLint version 8.57.0 and above.
> 9.0.0 <= ESLint version < 10.x: settings is honored and defaults to `true`.
> The experimental settings `eslint.experimental.useFlatConfig` is deprecated and should only be used for ESLint versions >= 8.21 < 8.57.0.
2. ESLint 9 upgrade on 2024-11-07 in #13164
1. See ESLint plugin version 3.0.10 in **Extensions** pane.
2. Quit Visual Studio Code.
3. Delete line from ui/.vscode/setting.json file.
4. Start Visual Studio Code and intentionally make a temporary change …
=> chore(ui): Update vscode settings in ui/apps/platform/README.md

ui/apps/platform/package-lock.json, ui/apps/platform/package.json
https://github.com/jquense/yup/blob/master/CHANGELOG.md#161-2024-12-17
* lazy validation errors thrown in builders should resolve async like other validations
https://github.com/jquense/yup/blob/master/CHANGELOG.md#160-2024-12-16
* expose `LazySchema`
1. `npm run build` in ui/apps/platform
2. CI
=> ROX-29750: Update yup 1.6.1 in dependencies

central/main.go, pkg/grpc/endpoints.go, pkg/grpc/endpoints_test.go, pkg/grpc/metrics/prom.go, pkg/grpc/server.go, pkg/tlsutils/alpn_demux.go, sensor/common/sensor/sensor.go
Let's have more insight on the application-level protocols used in the connections if ALP is used for demuxing the listeners. Note that this happens only in Sensor and Central as only them share a port between http and grpc listeners.
Note that this metric breaks with the pattern, where the name of the subsystem is part of metric name. Instead, the subsystem is a label. So this: 
```
rox_central_endpoint_tls_handshakes_with_negotiated_alp_total
``` 
becomes now
```
rox_endpoint_tls_handshakes_with_negotiated_alp_total{subsystem="central"}
```
This change was introduced to not duplicate metrics in the code only because the subsystem is different.
Tested on a cluster.
- Central. In this example:
- Sensor (IP 1.192) is calling over `pure-grpc` and `""` (two connections in parallel)
- IP 2.2 …
=> ROX-29600: Add metric for ALPN results

qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
This PR is adding a collection of additional data on DeclarativeConfigTest test failures.
For additional information, please check the Jira ticket and the pinned comment.
We will collect:
- ConfigMap - to debug if the config map is not properly applied
- mounted files - to debug if data from the config map is properly mounted to the container
=> ROX-28996: Log additional info on DeclarativeConfigTest fail

ui/apps/platform/cypress/integration/vulnerabilities/VulnerabilityReporting/reportForm.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/VulnerabilityReporting/reportsTable.test.js, ui/apps/platform/src/Components/TabNav/TabNavSubHeader.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/Wizard/ScanConfigWizardForm.tsx, ui/apps/platform/src/Containers/Policies/Wizard/PolicyWizard.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CloneVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CreateVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/EditVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/ReportFormWizard.tsx
Rebase and resolve slight merge conflict after #15789
1. Outside viewpoint:
* inconsistency among wizards
* inconsistency compared to non-wizard form pages
* inconsistency with PatternFly guidelines
2. Inside viewpoint:
* confusion during developtment which precedents
* umcertainty during review which patterns
* extra props and conditional rendering
1. Compliance scan schedule wizard
* **Review** step
* **Save** button
2. Policy wizard
* **Review** step
* **Save** button
3. Vulnerability reporting wizard
* **Review and create** step for clone and create versus **Review and save** step for edit
* **Create** button for clone and create versus **Save** button for edit
Bonus `navAriaLabel`
1. Compliance scan schedule wizard
* **Scan configuration creation steps**
2. Policy wizard
* **clone …
=> ROX-29761: Make wizard Review step and button consistent

.github/workflows/scanner-versioned-definitions-update.yaml
Since https://github.com/stackrox/stackrox/pull/15634 was merged, we've observed failures in the `Scanner versioned vulnerabilities update` workflow, specifically the `build-and-run v1` job. Example: https://github.com/stackrox/stackrox/actions/runs/15973303950/job/45049313708#logs.
These changes attempt to mitigate these errors by freeing more disk space. I suspect we'll hit a warning about not being able to free the requested amount of space, but it shouldn't cause an error.
N/A
Tested the general flow with the `pr-update-scanner-vulns` label, but we won't know if these changes work for the v1 jobs until this PR is merged.
=> fix: free more disk space for definitions update

ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.constants.ts, ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx, ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphContainer.tsx, ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx, ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphURLStateContext.tsx, ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/EdgeStateSelect.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/FlowTable.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/NetworkBreadcrumbs.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/NetworkSearch.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/ExternalFlows.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/EntityDetails.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/ExternalEntitiesSideBar.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/ExternalIpsContainer.tsx, ui/apps/platform/src/Containers/NetworkGraph/external/ExternalIpsTable.tsx, ui/apps/platform/src/Containers/NetworkGraph/hooks/useScopeHierarchy.ts, ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceSideBar.tsx, ui/apps/platform/src/Containers/NetworkGraph/simulation/DeploymentScopeModal.tsx, ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesGenerationScope.tsx, ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesYAML.tsx, ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx, ui/apps/platform/src/Containers/NetworkGraph/simulation/SimulateNetworkPolicyButton.tsx, ui/apps/platform/src/hooks/useAnalytics.ts, ui/apps/platform/src/hooks/useURLPagination.test.tsx, ui/apps/platform/src/hooks/useURLPagination.ts, ui/apps/platform/src/hooks/useURLSearch.ts
Adds more comprehensive URL state to Network Graph.
Previously, only cluster, namespace, deployment, and selected node were reflected in the URL.
This PR expands URL state to include:
- `sidePanelTabState` (e.g. `DETAILS`, `FLOWS`)
- `sidePanelToggleState` (e.g. `INTERNAL_FLOWS`, `EXTERNAL_FLOWS`)
- `EDGE_STATE` (`active` / `inactive`)
- `TIME_WINDOW`
- Pagination state (including anomalous/baseline for 2 table pagination)
- Search filters for both the main graph and side panel
Introduced `NetworkGraphURLStateContext`.
This helps avoid prop drilling and hopefully makes URL state easier to reuse and maintain.
An attempt to make preserving existing search filters in the URL easier when routing using `navigate()`
Verified that pages retain their exact state after page refreshes, including:
- …
=> ROX-29629: Network Graph URL State

ui/apps/platform/package-lock.json, ui/apps/platform/package.json
Follow up replacement of `jest` with `vitest` in #13281
Remember to update some packages in `overrides` if needed.
* For contribution: `npm install` to update package-lock.json file according to changes in package.json file.
> removed 167 packages
* For team: `npm ci` to delete and recreate ui/apps/platform/node_modules folder.
2. `npm run lint` in ui/apps/platform
3. `npm run test` in ui/apps/platform
=> ROX-29886: Delete jest-related devDependencies

central/metrics/central.go, central/metrics/central_test.go, central/metrics/init.go, central/reprocessor/reprocessor.go, central/reprocessor/reprocessor_test.go, central/reprocessor/reprocessor_unit_test.go, central/sensor/service/connection/connection_impl.go, pkg/env/reprocessing_interval.go, pkg/maputil/syncmap.go, pkg/maputil/syncmap_test.go
Adds a timeout to the `UpdatedImage` and `ReprocessDeployments` messages sent from Central to Sensor during reprocessing. 
When the timeout triggers, no more messages will be sent by the reprocessor to that failing Sensor until the next reprocessing cycle.  Messages will resume on the next reprocessing cycle. A metric is added to count the number of skipped messages when in this state.
The timeout chosen (`1m`) was an arbitrary guess - please share if you have data / opinions on what this value should be.
(also removed some dead code)
The motivation for this change was due to observed reprocessing not happening in user environments. In one case the cause was a single sensor (out of 100's) not reading from the gRPC bi-directional stream causing grpc's [flow control …
=> ROX-29755: Recover reprocessing when Sensor's are 'stuck'

.golangci.yml, go.mod, operator/tools/controller-gen/go.mod, operator/tools/envtest/go.mod, operator/tools/kustomize/go.mod, operator/tools/kuttl/go.mod, operator/tools/operator-sdk/go.mod, scanner/hack/quay/go.mod, tests/performance/scale/go.mod, tools/check-workflow-run/go.mod, tools/linters/go.mod, tools/test/go.mod
This is the last PR in series and bumps go in go.mod to allow using all features of go 1.24
- https://github.com/openshift/release/pull/65929
- https://github.com/stackrox/stackrox/pull/15668
=> ROX-29650: bump go to 1.24

pkg/env/integersetting.go, pkg/env/integersetting_test.go
Inspired by discussion in https://github.com/stackrox/stackrox/pull/15176#discussion_r2152078824
When specifying an Integer Setting (read from an env variable), we could add optional validation with its allowed minimum and maximum value. If the boundaries are not held, then the default value would be used. If the default is not within the boundaries, then we could panic to loudly indicate programmer error.
- Unit tests
=> feat(env): Add validation for Integer Setting

tests/e2e/run-scanner-v4-install.bats
The Scanner V4 install test suite currently has buggy support for output sequencing. This PR aims to fix it.
Background:
The test suite does some child-process trickery to post-process output of spawned child process by adding certain logging prefixes to make it clear to which test-case the output belongs.
Of course this opens the doors to issues related to interleaving of messages which are actually supposed to appear in a certain order.
The test suite currently does call `wait` in some places to enforce this ordering, but it is not sufficient. We are currently only calling `wait` as part of the `_end()` function, but this function is not always executed! For example, if a test case is terminated due to a failing command, then executions jumps directly to the `teardown` command, with no …
=> fix(tests): Proper output sequencing on scanner V4 test case teardown

.github/workflows/build.yaml, .github/workflows/style.yaml
By default we free only 24GB and this is not enought to build as observed in https://github.com/stackrox/stackrox/actions/runs/16038722150/job/45256004567
=> fix(CI): free more space for build

.github/CODEOWNERS, .github/dependabot.yaml
The current format is deprecated and reviers are removed and we should use CODEOWNERS instead.
https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
=> chore(dependabot): use CODEOWNERS instead of reviewers

central/authprovider/registry/singleton.go, central/authprovider/service/service_impl_postgres_test.go, central/declarativeconfig/updater/group_updater.go, central/declarativeconfig/updater/role_updater_test.go, central/group/datastore/datastore.go, central/group/datastore/datastore_impl.go, central/group/datastore/datastore_impl_postgres_test.go, central/group/datastore/datastore_impl_test.go, central/group/datastore/mocks/datastore.go, central/group/datastore/singleton.go, central/group/service/service_impl.go, central/group/service/service_test.go
The build was failing with an import cycle error:
```
imports github.com/stackrox/rox/central/auth/userpass
imports github.com/stackrox/rox/central/role/mapper
imports github.com/stackrox/rox/central/group/datastore
imports github.com/stackrox/rox/central/authprovider/registry
imports github.com/stackrox/rox/central/role/mapper: import cycle not allowed
```
The circular dependency was:
1. `central/group/datastore` → `central/authprovider/registry`
2. `central/authprovider/registry` → `central/role/mapper`
3. `central/role/mapper` → `central/group/datastore`
The group datastore needed access to the auth provider registry to validate that referenced auth providers exist when creating/updating groups. This validation happens in the `verifyReferencedRoleAndProvider` method.
Implemented a …
=> fix: untangle

operator/tests/upgrade/upgrade/005-assert.yaml, operator/tests/upgrade/upgrade/005-errors.yaml, operator/tests/upgrade/upgrade/010-assert.yaml, operator/tests/upgrade/upgrade/010-errors.yaml, operator/tests/upgrade/upgrade/030-assert-central.yaml, operator/tests/upgrade/upgrade/030-errors.yaml, operator/tests/upgrade/upgrade/031-assert-secured-cluster.yaml, operator/tests/upgrade/upgrade/031-errors.yaml, operator/tests/upgrade/upgrade/035-assert.yaml, operator/tests/upgrade/upgrade/035-central-cr-with-scanner-v4.yaml
Until recently the 'previous' version, which was installed as part of the upgrade tests, was installing a version which did not pull in scanner V4 by default. The upgrade test in its current form is based on this expected behaviour.
Now, 4.8.x has become the 'previous' version and that version installs scanner V4 by default, hence the test expectations need to be adjusted.
Just test fixes, nothing user-facing.
Just CI.
=> fix(test): Operator e2e upgrade test

central/image/service/service_impl.go, central/image/service/service_impl_test.go, sensor/common/detector/enricher.go
(cherry picked from commit 04b850cdfb5a8c340e6d468c26a2a0598144a3eb)
Backports #15353 to 4.7.x
=> ROX-19095: Ensure image names are not lost (#15353)

ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/NodeUpdateSection.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/AnomalousFlows.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/AnomalousTraffic.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaseline.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx, ui/apps/platform/src/Containers/NetworkGraph/deployment/InternalFlows.tsx
**Hide space** for review to reduce changed lines because of indentation.
Read requests have 403 **Forbidden** status:
* Node updates at upper right
* **Details** tab of deployment side panel
* **Flows** tab of deployment side panel
Write requests have 403 **Forbidden** status:
* Bulk or row actions on **Flows** and **Baseline** tabs
Rendering of empty tab in deployment side panel:
* Link from label in **Details** tab to **Network Policies** tab
* After excellent improvement by **Brad** to include tab in page address query string, link shared by sender who has permission **Flows**, **Baseline**, or **Network policies** tabs, but recipient does not
Some hooks make requests have been added to `InternalFlows` and `ExternalFlows` compoents for External IPs effort, since I added conditional …
=> ROX-29570: Give same RBAC to Flows as Baseline in Network Graph

.tekton/basic-component-pipeline.yaml, .tekton/images-mirror-set.yaml, .tekton/main-pipeline.yaml, .tekton/operator-bundle-pipeline.yaml, .tekton/retag-pipeline.yaml, .tekton/scanner-v4-pipeline.yaml, image/postgres/konflux.Dockerfile, image/rhel/konflux.Dockerfile, image/roxctl/konflux.Dockerfile, operator/konflux.bundle.Dockerfile, rpms.lock.yaml, scanner/image/db/konflux.Dockerfile, scanner/image/scanner/konflux.Dockerfile
Obtained via:
```bash
git cherry-pick fcdb758c a4bbd6a1 7e88dc34 153cfccd 9e7e1d1d a2a1a18c 2cd250c7
```
change me!
=> ROX-29603: Konflux Backporting for 4.8

ui/apps/platform/package-lock.json, ui/apps/platform/package.json
Humble dependency is 15 months outdated.
Find in Files `mobx` in package-lock.json file has 2 relevant results:
* `"node_modules/@patternfly/react-topology"` has `dependencies`
```
"mobx": "^6.9.0",
"mobx-react": "^7.6.0",
```
* `"node_modules/redoc"` has `dependencies` and `peerDependencies`
```
"mobx-react": "^9.1.1",
"mobx": "^6.0.4",
```
In package.json file:
* Update `"mobx": "^6.9.0",` because relevant for both packages.
* Leave `"mobx-react": "^7.6.0",` because that is latest y stream for `react-topology` requirement.
Most changes reduce memory requirement. Every little bit helps, pardon pun.
https://github.com/mobxjs/mobx/releases/tag/mobx%406.13.6
> Improve observableset memory footprint and performance
https://github.com/mobxjs/mobx/releases/tag/mobx%406.13.1
> Shrink Atom and …
=> ROX-29902: Update mobx in dependencies

.golangci.yml, roxctl/central/backup/backup.go, roxctl/central/cert/cert.go, roxctl/central/crs/generate.go, roxctl/central/crs/list.go, roxctl/central/crs/revoke.go, roxctl/central/db/restore/common.go, roxctl/central/db/restore/v1.go, roxctl/central/db/restore/v2.go, roxctl/central/db/restore/v2_cancel.go, roxctl/central/db/restore/v2_restorer.go, roxctl/central/db/transfer/transfer.go, roxctl/central/debug/authz_trace.go, roxctl/central/debug/debug.go, roxctl/central/debug/download_diagnostics.go, roxctl/central/generate/generate.go, roxctl/central/generate/interactive.go, roxctl/central/generate/validate.go, roxctl/central/initbundles/fetch_ca.go, roxctl/central/initbundles/generate.go, roxctl/central/initbundles/list.go, roxctl/central/initbundles/revoke.go, roxctl/central/login/login.go, roxctl/central/userpki/create/create.go, roxctl/central/userpki/delete/delete.go, roxctl/central/userpki/list/list.go, roxctl/central/whoami/whoami.go, roxctl/scanner/downloaddb/downloaddb.go
Wrap unwrapped errors in roxctl package with proper context messages to improve debugging and error traceability. Error messages use gerund form (e.g. 'establishing connection') instead of 'failed to' pattern.
This addresses 50+ wrapcheck violations and significantly improves error context for debugging roxctl operations.
Follows the same pattern as https://github.com/stackrox/stackrox/pull/15045
Assisted-by: Claude (Anthropic AI assistant)
=> chore(roxctl): wrap errors with context messages

tests/e2e/run-scanner-v4-install.bats
**This PR intends to fix the scanner-v4-install-tests on master.**
4.8.0 introduced different defaults for Scanner V4, which now cause CI failures in the scanner-v4-install-tests suite. One of these changes is expected behavior, which requires adjustments to the expectations of a test case which does Helm upgrade tests (-> commit 442cf85bd1530625cc08f34f846591323d0a01f0). A different change is actually a bug in 4.8.0, which causes the value of the `ROX_SCANNER_V4` environment variables to be wrongly set to `true` for sensor deployment bundles (-> commit a007167f16d56cbd245265a7a99586579908665f).
While analyzing the latter issue I figured out that the test logic for the upgrade test involving sensor bundles is actually broken in that it wrongly uses Helm charts under the hood instead of a …
=> ROX-29711: Fix scanner-v4-install-tests suite

pkg/networkgraph/tree/radix.go, pkg/networkgraph/tree/radix_test.go, pkg/networkgraph/tree/types.go, pkg/networkgraph/tree/wrapper.go
Recently the following crash was reported.
```
goroutine 52206 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:26 +0x5e
github.com/stackrox/rox/pkg/grpc/metrics.(*grpcMetricsImpl).convertPanicToError(0xc0083c0e00?, {0x9a12ce0?, 0xfc72210?})
github.com/stackrox/rox/pkg/grpc/metrics/grpc_metrics_impl.go:73 +0x3c
github.com/stackrox/rox/pkg/grpc/metrics.(*grpcMetricsImpl).UnaryMonitoringInterceptor.func1()
github.com/stackrox/rox/pkg/grpc/metrics/grpc_metrics_impl.go:85 +0x9b
panic({0x9a12ce0?, 0xfc72210?})
runtime/panic.go:792 +0x132
github.com/stackrox/rox/pkg/networkgraph/tree.(*nRadixTree).findCIDRNoLock(0xc0083c12b0?, 0x10?)
github.com/stackrox/rox/pkg/networkgraph/tree/radix.go:401 +0x79
github.com/stackrox/rox/pkg/networkgraph/tree.(*nRadixTree).getMatchingSupernetForCIDRNoLock …
```
=> ROX-30003: Fix findCIDRNoLock

pkg/env/external_ips.go
Makes it so that external entities are pruned by default even when external entities is disabled.
=> fix(central): Prune external ips by default 4.8 backport

.openshift-ci/ci_tests.py, deploy/common/k8sbased.sh, qa-tests-backend/src/main/groovy/util/Env.groovy, qa-tests-backend/src/test/groovy/CertRotationTest.groovy, qa-tests-backend/src/test/groovy/ClusterInitBundleTest.groovy, qa-tests-backend/src/test/groovy/ClustersTest.groovy, qa-tests-backend/src/test/groovy/ImageManagementTest.groovy, scripts/ci/gke.sh, scripts/ci/jobs/gke_external_pg_17_qa_e2e_tests.py, scripts/ci/logcheck/restart-ok-patterns.json, scripts/grab-data-from-central.sh, tests/byodb/lib.sh, tests/byodb/run.sh, tests/byodb/simple-postgres.yaml
In order to better state our support position of Postgres versions we need an e2e test that uses an external database.  In the interest of keeping things simple, this test creates a simple Postgres database in the cluster similar to our `central-db`.  But it is not our `central-db`; it uses different images and the connection from central states this is an external database.  So this satisfies the requirement of using an external (to central) database.  This was the path taken mostly to simplify the approach.  We can easily create another test and just pass set the `POSTGRES_VERSION` env var to pull a different postgres version.   Consideration was given to setting up a gcp database, but there would be a lot of work in figuring out the commands and secrets to do such within the framework …
=> ROX-29816: byodb postgres 17 e2e test

pkg/networkgraph/tree/radix.go, pkg/networkgraph/tree/radix_test.go, pkg/networkgraph/tree/types.go
This is a backport of https://github.com/stackrox/stackrox/pull/15949
Recently the following crash was reported.
```
goroutine 52206 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:26 +0x5e
github.com/stackrox/rox/pkg/grpc/metrics.(*grpcMetricsImpl).convertPanicToError(0xc0083c0e00?, {0x9a12ce0?, 0xfc72210?})
github.com/stackrox/rox/pkg/grpc/metrics/grpc_metrics_impl.go:73 +0x3c
github.com/stackrox/rox/pkg/grpc/metrics.(*grpcMetricsImpl).UnaryMonitoringInterceptor.func1()
github.com/stackrox/rox/pkg/grpc/metrics/grpc_metrics_impl.go:85 +0x9b
panic({0x9a12ce0?, 0xfc72210?})
runtime/panic.go:792 +0x132
github.com/stackrox/rox/pkg/networkgraph/tree.(*nRadixTree).findCIDRNoLock(0xc0083c12b0?, 0x10?)
github.com/stackrox/rox/pkg/networkgraph/tree/radix.go:401 +0x79 …
```
=> ROX-30003: Fix find cidr no lock backport 4.8

central/complianceoperator/v2/integration/service/service_impl.go, central/complianceoperator/v2/integration/service/service_impl_test.go
This PR is adding sensor connection status to cluster status during scan config creation.
=> ROX-29794: Sensor status to scan config cluster status

CHANGELOG.md, central/auth/m2m/mocks/set.go, central/auth/m2m/set.go, central/jwt/jwt.go, central/jwt/jwt_test.go
This PR implements an implicit JWT token exchange to allow for authorizing requests from clients, which do not support full m2m flow. E.g., Prometheus server, OpenShift console.
The idea is to identify the issuer of the token before validation, and if it is not a rox token, try to exchange the token using m2m, and then process the request using the exchanged token.
This change adds some _overhead in the token processing_, as it has to be parsed one more time to extract the issuer. Possible optimization would be to parse the token once, and pass the parsed JWT instead of the raw token string. This may be addressed in a separate PR, as such refactoring doesn't seem to be trivial.
Other optimization opportunities (to check if not already implemented):
- cache the issuer certificates;
- cache …
=> ROX-30087: implicit m2m token exchange

ui/apps/platform/src/hooks/patternfly/useFormModal.ts, ui/apps/platform/src/hooks/patternfly/useToasts.tsx, ui/apps/platform/src/hooks/useAlert.test.ts, ui/apps/platform/src/hooks/useAnalytics.ts, ui/apps/platform/src/hooks/useAuthStatus.ts, ui/apps/platform/src/hooks/useCentralCapabilities.ts, ui/apps/platform/src/hooks/useClipboardCopy.ts, ui/apps/platform/src/hooks/useEffectAfterFirstRender.ts, ui/apps/platform/src/hooks/useFeatureFlags.ts, ui/apps/platform/src/hooks/useFetchClusterNamespacesForPermissions.ts, ui/apps/platform/src/hooks/useFetchClustersForPermissions.ts, ui/apps/platform/src/hooks/useFetchDeployment.ts, ui/apps/platform/src/hooks/useFetchDeploymentCount.ts, ui/apps/platform/src/hooks/useFetchNamespaceDeployments.ts, ui/apps/platform/src/hooks/useFetchNetworkPolicies.ts, ui/apps/platform/src/hooks/useIsRouteEnabled.ts, ui/apps/platform/src/hooks/useLocalStorage.ts, ui/apps/platform/src/hooks/useMetadata.ts, ui/apps/platform/src/hooks/usePageAction.ts, ui/apps/platform/src/hooks/usePermissions.ts, ui/apps/platform/src/hooks/useRestQuery.ts, ui/apps/platform/src/hooks/useTableSort.ts, ui/apps/platform/src/hooks/useURLPagination.ts, ui/apps/platform/src/hooks/useURLParameter.ts, ui/apps/platform/src/hooks/useURLSearch.ts, ui/apps/platform/src/hooks/useURLSort.tsx, ui/apps/platform/src/hooks/useURLStringUnion.ts, ui/apps/platform/src/hooks/useWidgetConfig.ts
First batch in a folder less likely to have merge conflicts with unmerged work in progress.
https://typescript-eslint.io/rules/consistent-type-imports/
> TypeScript allows specifying a `type` keyword on imports to indicate that the export exists only in the type system, not at runtime.
> This allows transpilers to drop imports without knowing the types of the dependencies.
Temporarily add `'@typescript-eslint/consistent-type-imports': 'error'` to configuration for product files, grep and sort file names.
1. Add opt-in and opt-out configuration options after we merge opt-out configuration options for limited lint rules in #16022
=> ROX-30218: Use consistent-type-imports for hooks

ui/apps/platform/eslint.config.js
https://typescript-eslint.io/rules/consistent-type-exports
> TypeScript allows specifying a `type` keyword on exports to indicate that the export exists only in the type system, not at runtime.
> This allows transpilers to drop exports without knowing the types of the dependencies.
No errors, because team already uses `export type` idiom.
However, close the door to errors by part-time contributors.
Easy warm up before we start to enable rule for `import type` idiom (thatks to **David Vail** for introducing it) in batches via opt-in and opt-out for folders.
https://typescript-eslint.io/rules/consistent-type-imports
TypeScript allows specifying a `type` keyword on imports to indicate that the export exists only in the type system, not at runtime.
> This allows transpilers to drop imports …
=> ROX-30143: Enable typescript-eslint consistent-type-exports rule

CHANGELOG.md, roxctl/sensor/generate/generate.go, roxctl/sensor/generate/k8s.go, roxctl/sensor/generate/openshift.go
The following roxctl options related to admission controller configuration have been marked for deprecation:
- --admission-controller-enforce-on-creates
- --admission-controller-enforce-on-updates
- --admission-controller-listen-on-creates
- --admission-controller-listen-on-updates
- --admission-controller-listen-on-events
- --admission-controller-timeout
The incorrect defaults for these options (with the exception of -admission-controller-timeout - separate JIRA and discussion ongoing for this) have been fixed to ensure:
1. A user can generate a sensor bundle with the admission controller OOTB without specifying additional options.
2. Validating webhooks for policy evaluation and enforcement, are configured by default for both - if a user would like to enforce policies, all they need to …
=> ROX-30170, ROX-30100: roxctl options deprecation, fix defaults

scripts/ci/lib.sh
`${github.sha}` on PR will not return a real commit. Instead it returns artificial commit that will come from merge to the base branch. This results that our jobs in bigquery has different commit shas in PRWO and github. This PR should fix that issue.
Tested:
```sql 
SELECT name, ci_system  FROM `acs-san-stackroxci.ci_metrics.stackrox_jobs` 
WHERE commit_sha = "e00e491720755e91f72898391320588f7ca0a2a9"
```
| name                                                               | ci_system |
|--------------------------------------------------------------------|-----------|
| openshift-ci-unit-tests                                            | gha       |
| style-check                                                        | gha       |
| build-and-push-main …
=> fix(CI): fix invalid github sha

ui/apps/platform/cypress/integration/clusters/clustersHealthStatus.test.js, ui/apps/platform/src/Containers/Clusters/ClustersTable.tsx, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Clusters/Components/ClusterSummary.jsx, ui/apps/platform/src/Containers/Clusters/Components/SensorUpgrade.tsx, ui/apps/platform/src/Containers/Clusters/Components/SensorUpgradeLegacy.tsx, ui/apps/platform/src/Containers/Clusters/Components/SensorUpgradePanel.tsx, ui/apps/platform/src/Containers/Clusters/cluster.helpers.test.js, ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx, ui/apps/platform/src/Containers/Clusters/clustersTableColumnDescriptors.jsx
Introduces a Sensor Upgrade panel with version details, status details, and upgrade actions.
- Wrapped the table in `InnerScrollContainer` so it doesn’t overflow on smaller screens.
- Minor tweaks to headers:
- Renamed to “Cluster status” (lowercase “status” for consistency).
- Set `width={20}` on the sensor upgrade column to stabilize layout.
- Added a panel component with a description list showing:
- Status
- Reasoning
- Actions
- Sensor & Central versions
- `SensorUpgradeLegacy`: retains original tooltip table + inline action for legacy views and details page.
- `SensorUpgrade`: display-only, no action, no tooltip.
- `UpgradeState.displayValue` is now required (instead of optional).
- Caveat: Legacy views now show both `displayValue` and `actionText` for upgrade/downgrade states. …
=> ROX-26179: Update clusters sensor status

pkg/tlsutils/dial_context.go, tests/endpoints_test.go
Small test stability improvement, very similar to https://github.com/stackrox/stackrox/pull/15844.
Tracking JIRA: https://issues.redhat.com/browse/ROX-29311
Just test changes, nothing user-facing.
Just CI.
=> ROX-29311: Use retrying dial TLS wrapper functions

central/complianceoperator/v2/compliancemanager/manager_impl.go, central/complianceoperator/v2/compliancemanager/manager_impl_test.go, ui/apps/platform/src/Containers/ComplianceEnhanced/Schedules/components/ScanConfigClustersTable.tsx
Current problem (way to reproduce can be found in the ticket):
- if manual scan trigger "fails" (i.e. sensor not connected)
- we will save the state of failure with he scan config
- it can be cleared only by scan config update
- user will not get an error message returned from "trigger" API call
Anothe problem:
- broken scan config state on secured cluster does not represent unhealthy cluster
- cluster can be healthy and work properly for other scan configs
- representation in UI is confusing in misleading
A proposal for this issue:
- errors that occur during manual scan trigger will be collected for each cluster and returned to UI to be displayed to the user
- cluster scan config state - will not be updated if manual trigger scan fails
- in UI we will show "Scan schedule status". Cluster …
=> ROX-29792: Clarify cluster status for scan config

.github/pull_request_template.md
Before this, each section was H3-level (starting with `###`) that made it difficult to add any structure to the PR description, as one needed to use H4 and H5 section headers, which were small and not well visible.
Example: see the H5 sections used at the bottom of the description of https://github.com/stackrox/stackrox/pull/15076 - do you see how small the text "Enrichment of Endpoints" is?
If there is no reason for starting with H3, let's start with ~H1 (one `#`)~ H2 (two `##`) to allow devs using H3 in the description and H4 in the testing sections.
Example: this PR.
I know, this change maybe controversial (intel vs. AMD, pepsi vs. cola), but felt strong urge to open this PR and check the sentiment about it.
Applied the new template to this PR. You are looking at it right now.
=> chore(PR): Make top section of PR template H2 instead of H3

ui/apps/platform/src/constants/accessControl.ts, ui/apps/platform/src/constants/enforcementActions.ts, ui/apps/platform/src/constants/entityTypes.ts, ui/apps/platform/src/constants/networkFlow.ts, ui/apps/platform/src/constants/reportConstants.ts, ui/apps/platform/src/constants/severityColors.ts, ui/apps/platform/src/constants/vulnerabilities.ts, ui/apps/platform/src/messages/common.ts
Batch 4 in a folder less likely to have merge conflicts with unmerged work in progress.
https://typescript-eslint.io/rules/consistent-type-imports/
> TypeScript allows specifying a `type` keyword on imports to indicate that the export exists only in the type system, not at runtime.
> This allows transpilers to drop imports without knowing the types of the dependencies.
Temporarily add `'@typescript-eslint/consistent-type-imports': 'error'` to configuration for product files, grep and sort file names.
1. Add opt-in and opt-out configuration options after we merge opt-out configuration options for limited lint rules in #16022
=> ROX-30268: Use consistent-type-imports for constants and messages

roxctl/common/client.go, roxctl/common/connection.go, roxctl/common/connection_test.go, roxctl/common/environment/environment-impl.go, roxctl/common/tls.go
Refactor and fix the gRPC retries and connection error handling in roxctl:
- removed the "insecure verifier", which was a leftover from the old code where we would print a warning on TLS verification errors.
- string comparison for gRPC `code.Unavailable` errors, to avoid retries for certificate validation errors.
- removed the now unused logging parameter.
The refactored code now properly ignores TLS errors when `--insecure-skip-tls-verify` is passed.
This change is driven by the CI failures where roxctl is confused with the server name set in the environment.
CI.
*Manual tests*
No server name error with `--insecure-skip-tls-verify`:
```console
sh$ bin/linux_amd64/roxctl central whoami -s "bad-name" --use-current-k8s-context -p admin-password --insecure-skip-tls-verify
UserID:
admin
``` …
=> ROX-28673: refactor roxctl tlsconfigopts

tests/upgrade/postgres_run.sh
Bump upgrade test release version
=> ROX-30109: Bump upgrade test version for 4.8.1

central/image/datastore/datastore.go, central/image/datastore/datastore_impl.go, central/image/datastore/image_risk_view.go, central/image/datastore/store/mocks/store.go, central/image/datastore/store/postgres/store.go, central/image/datastore/store/store.go, central/image/datastore/store/v2/postgres/store.go, central/image/views/image_risk_view.go, central/imagecomponent/datastore/datastore.go, central/imagecomponent/datastore/datastore_impl.go, central/imagecomponent/store/mocks/store.go, central/imagecomponent/store/store.go, central/imagecomponent/v2/datastore/datastore.go, central/imagecomponent/v2/datastore/datastore_impl.go, central/node/datastore/datastore.go, central/node/datastore/datastore_impl.go, central/nodecomponent/datastore/datastore.go, central/nodecomponent/datastore/datastore_impl.go
initializing rankers at startup can lead to unnecessarily elongated startup times.  Move that to processing in a separate go func.
Additionally the rankers are initialized by a search to pull in ALL the records into a slice and then a second call to get the details.  This can be accomplished with the use of `Walk` or `GetByQueryFn` in a single pass to the database in a way that is much more friendly to memory.
The scope here creeped a little upon testing.  When testing it was obvious that the image rankers were the issue.  The Walk of the image would get the image serialized object and then go get the components one by one and then go get the CVEs one by one.  All we really need is the image ID and the Risk Score such that we can seed the Rankers.  So I'm using our view construct to …
=> ROX-30307: move ranker initialization out of band

ui/apps/platform/README.md, ui/apps/platform/package.json, ui/apps/platform/scripts/start-ocp-console.sh, ui/apps/platform/src/ConsolePlugin/PluginProvider.tsx, ui/apps/platform/src/ConsolePlugin/SecurityVulnerabilitiesPage/Index.tsx, ui/apps/platform/src/ConsolePlugin/consoleFetchAxiosAdapter.ts, ui/apps/platform/webpack.ocp-plugin.config.js
Adds the ability to configure the following:
1. Whether or not the local console instance injects OpenShift auth headers
2. The endpoint of `central` where API requests should be proxied to
3. An optional ACS auth token that should be added to all API requests
This change will allow us to develop the dynamic plugin frontend with or without a working ACS-side implementation of authn, and against a central instance of our choosing. See more in the provided README docs.
In addition, in order to prevent request failures for POST requests, we need to use the console API's `consoleFetch` implementation to ensure the correct headers are set. Since we already use axios directly throughout, a wrapper around `consoleFetch` was added as an axios adapter to avoid changing application code.
Load the …
=> ROX-29844: Add configuration of base URL in plugin requests

qa-tests-backend/src/test/groovy/ClusterInitBundleTest.groovy
As discussed on https://issues.redhat.com/browse/ROX-29419, this change removes the failing test, because:
1. The same functionality is already covered elsewhere.
2. This particular test doesn't play nice with the (nowadays) automated cert rotation, which has direct impact on the need to specify "impacted clusters" during revokation.
Nothing needed, just a test deletion.
Just *removed* a test for functionality, which is already covered by different tests.
Just CI.
=> ROX-29419: Remove test for revoking init bundle with impacted clusters

ui/apps/platform/webpack.ocp-plugin.config.js
Updates the extension points to correctly add the navigation items for the Security Vulnerabilities Page.
Visit the console and see the "Security" section added to the left nav.
Expanding the Security section and selecting Vulnerabilities from the list correctly navigates to the vuln page:
=> ROX-30356: Add extensions for console Sec Vulns page

ui/apps/platform/src/ConsolePlugin/WorkloadSecurityTab/Index.tsx, ui/apps/platform/webpack.ocp-plugin.config.js
Adds console extension point for the Security tab on OCP Workload pages.
Visit the detail page for the different workloads and navigate to the Security tab:
=> ROX-30357: Add Security tab for Workload pages

ui/apps/platform/src/ConsolePlugin/AdministrationNamespaceSecurityTab/Index.tsx, ui/apps/platform/webpack.ocp-plugin.config.js
Adds an ACS extension point on the console Administration->Namespace page.
👀
=> ROX-30360: Add extension point for admin ns security tab

.github/workflows/scanner-versioned-definitions-update.yaml, scanner/cmd/updater/main.go
Parse the `make tag` of the current checkout to determine when to pass `--split` to the `updater export` command. As of today, builds <= 4.8.x require `--split` that was removed in master.
~Waiting for bundle to be generated based on the `pr-updat-scanner-vulns` tag, then will see...~
Unfortunately, I can't run the build-and-run workflow without publishing the data to production at the moment. Adding a step for dispatch running this and uploading the results to a dev bucket would be a good way to test this. But since we don't have that right now, I can only test the path using triggered by the `pr-update-scanner-vulns`.
=> ROX-30415: Use split opt when applicable

CHANGELOG.md, image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl, image/templates/helm/stackrox-secured-cluster/templates/NOTES.txt.htpl, image/templates/helm/stackrox-secured-cluster/templates/_admission-controller-config.tpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, pkg/helm/charts/tests/securedclusterservices/feature-flags/feature_flags_test.go, pkg/helm/charts/tests/securedclusterservices/feature-flags/testdata/helmtest/admission-controller-config/admission-control.test.yaml, pkg/helm/charts/tests/securedclusterservices/feature-flags/testdata/helmtest/suite.yaml, pkg/helm/charts/tests/securedclusterservices/helmtest_test.go, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/admission-control.test.yaml
See https://issues.redhat.com/browse/ROX-30278. This PR only contains the first set of changes for the referenced ticket.
The options
```
admissionControl:
listenOnCreates: # bool
listenOnUpdates: # bool
listenOnEvents:  # bool
```
shall not be supported any longer. More precisely, since we don’t want to break backwards compatibility and in accordance with the design doc, they shall be “upgraded to true” under the hood. But to make this not entirely silent, we shall
emit a warning message, if these were changed by the user. One exception being that OpenShift 3 doesn't support the `listenOnEvents: true` setting -- in that case it will remain being disabled.
```
$ ROX_ADMISSION_CONTROLLER_CONFIG=true roxctl helm output secured-cluster-services --remove --debug
$ helm template -n stackrox …
```
=> ROX-30278: secured-cluster chart: Make listenOn* settings static

ui/apps/platform/eslint.config.js, ui/apps/platform/package.json, ui/apps/platform/src/Containers/Compliance/Entity/Cluster.jsx, ui/apps/platform/src/Containers/Compliance/Entity/Control.jsx, ui/apps/platform/src/Containers/Compliance/Entity/Deployment.jsx, ui/apps/platform/src/Containers/Compliance/Entity/Namespace.jsx, ui/apps/platform/src/Containers/Compliance/Entity/Node.jsx, ui/apps/platform/src/Containers/Compliance/List/List.jsx, ui/apps/platform/src/Containers/Compliance/List/SidePanel.jsx
1. **Saif** reminded the team that lint takes minutes.
2. **David** reminded the team that 2 rules take 90% of that and graciously provided the timing command (see below).
See #16274
For the 2 slowest rules:
* Visual Studio Code checks open changed files.
* One side of coin: they are needed. Other side of coin: new errors are unlikely.
https://eslint.org/docs/latest/use/command-line-interface#--rule
> This option specifies the rules to be used.
In this case, specify 2 rules **not** to be used.
1. Edit ui/apps/platform/package.json file: add a new `"lint:fast-dev"` command off 2 slowest rules for fast lint during development and let full slow lint in CI report errors.
* `import/no-cycle`
* `import/namespace`
2. Edit ui/apps/platform/eslint.config.js file: move `import/namespace` rule to …
=> ROX-30443: Turn off 2 slowest rules for lint:fast-dev command

ui/apps/platform/src/ConsolePlugin/PluginContent.tsx, ui/apps/platform/src/ConsolePlugin/PluginProvider.tsx, ui/apps/platform/src/ConsolePlugin/SecurityVulnerabilitiesPage/Index.tsx, ui/apps/platform/src/ConsolePlugin/UserPermissionProvider.tsx, ui/apps/platform/webpack.ocp-plugin.config.js
Adds a context implementation for the OCP plugin in order to allow usage of the `usePermissions()` hook, and components that rely on that hook. The context implementation utilizes a [plugin SDK extension point ](https://github.com/openshift/console/blob/main/frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md#consolecontext-provider)so that context data is shared across multiple plugin entry points. This should prevent duplicate requests of things like permissions during a single session. (TODO - Need to make a note to verify this when additional entry points are added.)
Load the plugin and verify that the `mypermissions` request is made and that the permissions are correctly passed to the components. If the request was not wired up correctly, none of the summary …
=> ROX-30334: Adds context for OCP plugin user permissions

ui/apps/platform/src/Components/CheckboxTable.jsx, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Clusters/searchFilterConfig.ts
The Clusters page should align with current UX by including a subheading and margins around the table.
=> ROX-26177: Clusters page layout updates

image/templates/helm/stackrox-secured-cluster/templates/_defaults.tpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
This PR will make be directly useful for the ongoing effort to upgrade certain admission controller config defaults: See https://github.com/stackrox/stackrox/blob/02a683016e9fd1f31eda40185aff61d90bf2e228/image/templates/helm/stackrox-secured-cluster/templates/_admission-controller-config.tpl#L4. This is part of a templating macro, where messages are emitted to the user, explaining that a certain option is not user-configurable anymore. The message shall also mention what the new effective default of the respective field is going to be. At the moment we were able to get away with hard-coding:
```
{{- $formatMsg := "[...] The effective value is 'true'" -}}
```
But of course this is
* too unflexible (e.g., we will need a similar message for the `timeout` field).
* this also introduces a …
=> ROX-30278: Prefactoring: separate collecting of defaults from applying

CHANGELOG.md, image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl, image/templates/helm/stackrox-secured-cluster/templates/_admission-controller-config.tpl, pkg/helm/charts/tests/securedclusterservices/feature-flags/testdata/helmtest/admission-controller-config/admission-control.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/admission-control.test.yaml
Next step, implementing this snippet:
> The setting
> 
> ```admissionControl:
>   dynamic:
>     scanInline: # bool
> ```
> 
> shall not be configurable by the user anymore. During rendering the setting admissionControl.dynamic.scanInline=true shall be effective. Furthermore, if set by the user, emit a warning message.
from the design doc.
* Unit tests.
* Manually, see below:
```
$ ROX_ADMISSION_CONTROLLER_CONFIG=true roxctl helm output secured-cluster-services --remove --debug
WARN:   No output directory specified, using default directory "./stackrox-secured-cluster-services-chart"
WARN:   Removed output directory ./stackrox-secured-cluster-services-chart
INFO:   Written Helm chart secured-cluster-services to directory "./stackrox-secured-cluster-services-chart"
$ helm template -n …
```
=> ROX-30278: secured-cluster Helm: static scanInline field

CHANGELOG.md, image/templates/helm/stackrox-secured-cluster/templates/_admission-controller-config.tpl, pkg/helm/charts/tests/securedclusterservices/feature-flags/testdata/helmtest/admission-controller-config/admission-control.test.yaml
Implements next snippet of the requirements:
> The option
> 
> ```
> admissionControl:
>   dynamic:
>     timeout: # natural number
> ```
> 
> will not be user-configurable anymore. If set by the user, a warning shall be emitted. It is set to 10 seconds.
```
ROX_ADMISSION_CONTROLLER_CONFIG=true roxctl helm output secured-cluster-services --remove --debug
helm template -n stackrox stackrox-secured-cluster-services ./stackrox-secured-cluster-services-chart --set clusterName=foo \
-f ~/go/src/github.com/stackrox/stackrox/tests/roxctl/bats-tests/test-data/helm-output-secured-cluster-services/cluster-init-bundle.yaml \
--set admissionControl.dynamic.timeout=7 \ 
| yq eval-all 'select(.kind == "Secret" and .metadata.name == "helm-cluster-config")' - \
| yq '.stringData["config.yaml"]'
```
=> ROX-30278: secured-cluster Helm: static timeout field

ui/apps/platform/src/ConsolePlugin/CveDetailPage/Index.tsx, ui/apps/platform/webpack.ocp-plugin.config.js
Adds route and component for ImageCve single page in the console.
=> ROX-30422: Add route for CVE detail page

roxctl/common/tls.go
#15173 introduced a bug, where the x509 certificate pool would not include the system certificates.
This PR fixes that accidental behaviour change.
CI
1. :ok: Accessing central with a self-signed cert with `--ca` argument.
2. :ok: Accessing central via a route with system trusted certificate, without `--ca` argument.
3. :ok: Accessing central via a route with system trusted certificate, with `--ca` argument.
4. :ok: `FROM scratch` image, accessing central via port-forward with a self-signed certificate:
```console
sh$ podman run ... roxctl:4.9.x-425-g3e122993e2 -e https://localhost:8000 central whoami -s central.stackrox --ca /tls/central-ca.pem
UserID:
admin
User name:
Roles:
- Admin
```
5. :red_circle: `FROM scratch`, Accessing central via a route with system trusted certificate, …
=> fix(roxctl): base on the system pool

sensor/common/networkflow/manager/manager_impl.go, sensor/common/networkflow/metrics/metrics.go
This PR was a part of a stack, so it misses the PR template.
The PR includes the following:
- Adds gauge metrics for the size of collections used in the enrichment, so that we can always see how long is a given slice/map
- Fixes the log-rate-limiter issue (missed that in #15076)
- Applies one tiny performance optimization when copying maps to a slice - this has been proposed by Cursor and benchmarked by me.
- Unit tests
- Deploying on a cluster and looking at the metrics
- Using #16151 in Grafana to look at the metrics
=> ROX-29060: Add gauge metrics for collections used in enrichment

scripts/ci/gke.sh
This PR updates the GKE region to be geographically closer to the region where our PROW jobs are currently deployed, in order to reduce intermittent network issues. While the ideal setup would run GKE tests from `build02` (GCP-hosted), that requires changes to the PROW configuration. As a more immediate improvement, we're aligning GKE closer to the AWS-based PROW instance in `us-east-1`.
See:
- https://github.com/openshift/release/blob/a156c2b5993702463f56d17667aa23680bc13aaa/clusters/build-clusters/build02/README.md#regenerate-install-configyaml
- https://github.com/stackrox/stackrox/commit/15bc00b9fa50eda0f1606ba51a66831bc9fbf966#diff-1bfdbd7784f6a5763f7bd15c227aacf9c35b457b91e308c9ce97a931b1569715R10
=> fix(CI): use GKE region closer to PROW

central/metadata/service/service.go, central/metadata/service/service_impl.go, central/metadata/service/service_impl_test.go, central/securedclustercertgen/certificates.go, central/securedclustercertgen/certificates_test.go, central/sensor/service/connection/connection_impl.go, central/sensor/service/service_impl.go, central/sensor/service/service_impl_test.go, central/tlsconfig/manager_impl.go, generated/api/v1/metadata_service.pb.go, generated/api/v1/metadata_service.swagger.json, generated/api/v1/metadata_service_vtproto.pb.go, generated/storage/service_identity.pb.go, generated/storage/service_identity_vtproto.pb.go, pkg/centralsensor/caps_list.go, pkg/grpc/authn/service/extractor.go, pkg/grpc/authn/servicecerttoken/extractor.go, pkg/mtls/crypto.go, pkg/mtls/env.go, pkg/mtls/verifier/verify.go, proto/api/v1/metadata_service.proto, proto/storage/proto.lock, proto/storage/service_identity.proto
This PR follows-up https://github.com/stackrox/stackrox/pull/15074 which added a CA rotation mechanism to the ACS Operator, based on [this design](https://docs.google.com/document/d/1I1r3bg3nwt96Q0dWs_mYdl5Wl4_xxVNz3NnB4UbHOCk/edit?usp=sharing). 
CA rotation will enable zero-downtime CA certificate refresh by allowing Central and Sensor to simultaneously trust certificates signed by both the current (primary) and new (secondary) CA during the transition period.
This PR introduces the following changes:
* Adds the ability of Central to load both the primary and secondary CA, and use both when authenticating clients
* Extends the TLSChallenge endpoint so that if there are two CAs in use, Central will include both certificate chains in the `TrustInfo` message, and sign it with both …
=> ROX-27963: Support for CA rotation in Central

central/deployment/datastore/datastore.go, central/deployment/datastore/datastore_impl.go, central/deployment/datastore/datastore_impl_test.go, central/image/datastore/datastore_impl.go
Deployment rankers should not be initialized in the critical path of central startup which brings up the deployment service.
Also, given deployment store is a high cardinality store, using Walk with query instead of the dual Search and GetByID for each deployment is optimized data access pattern. This change should improve startup times and central memory needed.
Also in the image datastore, modified the query construction to use the query builder pattern for better readability.
Deployed PR image, and click around on UI, deployment listing, risk scores, dashboard etc. all worked fine.
=> ROX-30413: Optimize deployment ranking

ui/apps/platform/src/ConsolePlugin/AdministrationNamespaceSecurityTab/AdministrationNamespaceSecurityTab.tsx, ui/apps/platform/src/ConsolePlugin/CveDetailPage/CveDetailPage.tsx, ui/apps/platform/src/ConsolePlugin/ImageDetailPage/ImageDetailPage.tsx, ui/apps/platform/src/ConsolePlugin/ProjectSecurityTab/ProjectSecurityTab.tsx, ui/apps/platform/src/ConsolePlugin/SecurityVulnerabilitiesPage/SecurityVulnerabilitiesPage.tsx, ui/apps/platform/src/ConsolePlugin/WorkloadSecurityTab/WorkloadSecurityTab.tsx, ui/apps/platform/webpack.ocp-plugin.config.js
In the spirit of the recent discussion regarding many `CVETable.tsx` components, lets rename the already long list of `Index.tsx` files for plugin entry points to avoid similar pain.
Smoke test running plugin dev environment.
=> chore(ui): Rename top level plugin modules

scripts/ci/metrics.sh
Currently we pass empty string as a PR number but then it cannot be used as integer resulting in failure on saving job that was run on master. This PR should fix that by using `NULL` instead of empty string.
https://github.com/stackrox/stackrox/blob/651b9189b315ce13a4d5a1d1819e37a686016eea/scripts/ci/metrics.sh#L136
```sql
INSERT INTO acs-san-stackroxci.ci_metrics.stackrox_jobs 
(stopped_at, id, name, repo, branch, pr_number, commit_sha, ci_system, outcome, started_at, test_target, cut_product_version, cut_k8s_version, cut_os_image, cut_kernel_version, cut_container_runtime_version) '
VALUES 
(TIMESTAMP_SECONDS(1754929480), @id, @name, @repo, @branch, @pr_number, @commit_sha, @ci_system, @outcome, TIMESTAMP_SECONDS(@started_at), @test_target, @cut_product_version, @cut_k8s_version, …
```
=> fix(CI): set PR number to NULL if not defined

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/namespaceView.test.js
Different DOM assertion failure after fix in #16347
Workload CVE Namespace View should display the correct search filter chips on the main list page when clicking the deployment link in the table
> Timed out retrying after 8000ms: Expected to find element: `undefined`, but never found it.
cypress/integration/vulnerabilities/workloadCves/namespaceView.test.js:28:15
```js
cy.wrap($row.find('td[data-label="Deployments"] a')).click();
```
This feels familiar. Hypothesis is that cy.get(…).then(($row) => { … })` gets row too soon:
* after React rendered **Namespace** and **Cluster** columns
* before React renders **Deployments** link
1. Replace `find` with `get` method which waits until element exists in the DOM.
2. Replace `find` and `text` methods with:
* `invoke('text').then((namespace) => { …
=> ROX-30503: Replace find, text, and wrap methods in namespaceView test

CHANGELOG.md, roxctl/sensor/generate/generate.go
Self explanatory, see PR title. This is to ensure the Helm rendering is the single place for defaulting the time out value.
@pedrottimark @kcarmichael08  Keeping you in the loop.
CI only.
=> ROX-24956: Set default adm controller timeout value to 0 in roxctl

central/cluster/datastore/datastore_impl.go, central/cluster/datastore/datastore_impl_postgres_test.go
When a cluster is removed, the corresponding health status is not.  This PR addresses that.
(I suspect but didn't confirm this is due to the removal of a FK when processing migrations way back when the RocksDB -> Postgres conversion was on going.)
Added a unit test.  Also set up a cluster and verified this now works.  Before this fix it behaved as [ROX-18298](https://issues.redhat.com/browse/ROX-18298) stated.  See results below:
```
central_active=# select id from clusters;
id                  
--------------------------------------
d4104718-6e6e-44c9-8940-27af71509a26
(1 row)
central_active=# select * from cluster_health_statuses;
id                  | sensorhealthstatus | collectorhealthstatus | overallhealthstatus | admissioncontrolhealthstatus | scannerhealthstatus | …
```
=> ROX-18298: cleanup cluster health on delete

tests/upgrade/postgres_run.sh
As per patch release process: https://spaces.redhat.com/spaces/StackRox/pages/284431271/Upstream+Release+Automation#UpstreamReleaseAutomation-update-upgrade-testUpdateUpgradeTest
=> chore: bump upgrade test 4.8.1 -> 4.8.2

.openshift-ci/dispatch.sh, tests/e2e/lib.sh, ui/apps/platform/cypress.config.js, ui/apps/platform/cypress/helpers/ocpAuth.ts, ui/apps/platform/cypress/integration-ocp/smoke.test.ts, ui/apps/platform/scripts/cypress-ocp.sh
The smoke test passes on OCP4.19 with these changes (https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/stackrox_stackrox/16415/pull-ci-stackrox-stackrox-master-ocp-4-19-ui-e2e-tests/1957866898653712384/artifacts/ui-e2e-tests/stackrox-stackrox-e2e-test/build-log.txt):
```
2025-08-19T19:36:15.932Z running test suite: smoke.test.ts
Basic connectivity to the OCP plugin
✓ should open the OCP web console (16435ms)
1 passing (16s)
```
The smoke test fails on ocp4.18 because of some text/intro changes (https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/16415/pull-ci-stackrox-stackrox-master-ocp-4-18-ui-e2e-tests/1957866898611769344):
```
2025-08-19T19:49:08.425Z running test suite: smoke.test.ts
Basic connectivity to …
```
=> ROX-29840: access ocp console

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.ts, ui/apps/platform/src/Components/ColumnManagementButton.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/WorkloadCVEOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/CVESelectionTd.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/CVESelectionTh.tsx, ui/apps/platform/src/hooks/useManagedColumns.ts
Expands the usage of column management to allow cleaner conditional rendering of table columns in Vuln Management.
This will help us to use these tables in the OCP dynamic plugin, which has different column requirements, without requiring us to do any of the following:
- Duplicate Table code
- Abstract our current patterns to use column descriptors instead of direct rendering (massive refactor)
- Add additional boolean flag props to handle condition columns
In addition to avoiding the previous items there are a couple of side benefits to this approach:
- Existing boolean props and permission checks can be removed or de-duplicated, and moved to the parent component
- All table columns are now explicit in the config and can simplify the ugly calculation of `colSpan` in every table
- …
=> ROX-30362: Extend column mgmt for general conditional columns

qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
Ubuntu recently opted to ignore CVE-2016-20013 https://git.launchpad.net/ubuntu-cve-tracker/commit/active/CVE-2016-20013?id=f2b1cfd3260adb8c188b0ca0ce1ec17bb85bfcf0. This will cause CI to fail once we update to a version of Scanner v2 which knows about this change. This PR is meant to replace it with a different CVE so we can update Scanner v2 without worrying about breaking CI for others
CI
=> fix(ci): replace CVE-2016-20013 with CVE-2024-28085

.github/labeler.yml
This PR enables Sourcery AI reviews on paths owned by @stackrox/sensor-ecosystem
=> chore(ai): enable AI for sensor & ecosystem

image/templates/helm/stackrox-secured-cluster/internal/cluster-config.yaml.tpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/admission-control.test.yaml
The `failurePolicy` configuration setting of the `secured-cluster-services` Helm chart needs to be propagated to Central.
Just automatic tests so far.
e2e test pending.
=> fix: Propagate Admission Controller failure Policy to Central

pkg/helm/charts/tests/securedclusterservices/feature-flags/feature_flags_test.go, pkg/helm/charts/tests/securedclusterservices/feature-flags/testdata/helmtest/admission-controller-config-disabled/admission-control.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/admission-control.test.yaml, pkg/helm/config/testdata/helm-chart-configurations/simple.yaml
Execute certain tests which specifically test the current Helm chart behaviour (i.e. ROX_ADMISSION_CONTROLLER_CONFIG=false) into a dedicated test suite which explicitly switches off this feature flag, thereby making these tests pass irregardless of the current defaulting setting of the feature flag.
No doc changes needed, this is just about restructuring tests.
Just via unit tests -- the change only affects unit tests.
=> test: CI Preparations for enabling new Admission Controller Config

sensor/kubernetes/listener/resource_event_handler_impl.go, sensor/kubernetes/listener/resource_event_handler_impl_test.go
If the message is `nil` the `eventHandler` will panic [here](https://github.com/stackrox/stackrox/blob/cfa0d8a2f699440efb4e1f389b1e6d418417768c/sensor/kubernetes/listener/resource_event_handler_impl.go#L112). Some dispatchers could send `nil` messages like the [profile dispatcher](https://github.com/stackrox/stackrox/blob/cfa0d8a2f699440efb4e1f389b1e6d418417768c/sensor/kubernetes/complianceoperator/dispatchers/complianceoperatorprofiles.go#L32-L41).
The `eventHandler` should handle `nil` messages.
=> fix(nil-handling): Handle nil message in the eventHandlers

pkg/features/list.go
While working with https://github.com/stackrox/stackrox/pull/15763, discussions revealed that it is not a good idea to hide default policies behind feature flags [1]. After flag usages were removed from open PRs [2][3], the flag itself can be removed.
[1] https://redhat-internal.slack.com/archives/C01DQH7UP8C/p1753527317603749?thread_ts=1751477193.410369&cid=C01DQH7UP8C
[2] https://github.com/stackrox/stackrox/pull/15761/commits/14ebb647a62e0ea63dac468a2f620f68f2d7ff04
[3] https://github.com/stackrox/stackrox/pull/15763/commits/73361e79e66cea6ea1d0ce63ad80781a02b3e9b9
I grepped the repo to verify nothing uses the flag I'm removing, and ensured tests pass.
=> ROX-29160: Remove feature flag ROX_RED_HAT_IMAGES_SIGNED_POLICY

.tekton/operator-bundle-pipeline.yaml
Manual backport of https://github.com/stackrox/stackrox/pull/16497 to `release-4.6`
No change.
Performed in https://github.com/stackrox/stackrox/pull/16497.
=> ROX-29969: Remove bundle tag from Snapshot / 4.6

.tekton/operator-bundle-pipeline.yaml
Manual backport of https://github.com/stackrox/stackrox/pull/16497 to `release-4.8`
No change.
Performed in https://github.com/stackrox/stackrox/pull/16497.
=> ROX-29969: Remove bundle tag from Snapshot / 4.8

ui/apps/platform/cypress/integration/clusters/Clusters.selectors.js, ui/apps/platform/cypress/integration/clusters/clustersHealthStatus.test.js, ui/apps/platform/cypress/integration/clusters/clustersManager.test.js, ui/apps/platform/src/Containers/Clusters/ClusterEditFormLegacy.tsx, ui/apps/platform/src/Containers/Clusters/ClusterPage.tsx, ui/apps/platform/src/Containers/Clusters/ClusterStatusGrid.tsx, ui/apps/platform/src/Containers/Clusters/ClusterSummaryLabelsConfiguration.tsx, ui/apps/platform/src/Containers/Clusters/Components/ClusterSummaryLegacy.jsx, ui/apps/platform/src/Containers/Clusters/Components/HelmValueWarning.tsx, ui/apps/platform/src/Containers/Clusters/DynamicConfigurationForm.tsx, ui/apps/platform/src/Containers/Clusters/DynamicConfigurationSectionLegacy.jsx, ui/apps/platform/src/Containers/Clusters/StaticConfigurationForm.tsx, ui/apps/platform/src/Containers/Clusters/StaticConfigurationSectionLegacy.jsx, ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx, ui/apps/platform/src/types/cluster.proto.ts
Dear reviewer:
* Hide space because some files have indentation changes.
* You have my apology in advance that it is hard to compare the 4 pairs of corresponding files.
Align admission controller options in UI with changes for 4.9 release:
* Helm charts
* Operator
* `roxctl`
For almost all customers, **UI is view only** because they configure in the above places.
Admission controller configuration:
* Delete obsolete options
* Replace existing options
* Add new option
1. Move **Cluster labels** preceding configuration forms.
Potential future improvement might provide a separate button for changes to cluster labels, especially if they affect Central but not Sensor.
2. Convert static and dynamic configuration from classic to PatternFly forms.
3. Delete obsolete options.
Static configuration: …
=> ROX-30130: Update classic form to PatternFly for Cluster config

ui/apps/platform/src/Containers/Vulnerabilities/components/CvePageHeader.tsx
1. Fix spacing mistake that I made with fragment in #13892
2. Add `// Ross CISA KEV` comment for conditional rendering of `KnownExploitLabel` element
Sneak peek of future label and tooltip:
2. `npm run lint:fast-dev` in ui/apps/platform folder.
3. `npm run start` in ui/apps/platform folder with staging demo as central.
1. Visit /main/vulnerabilities/user-workloads/cves/CVE-2024-38475
Before changes, compare:
* presence of space following **EPSS probability** label
* absence of space between **First discovered in system** and **Published** labels
After changes, see:
* **Known exploit** label
* presence of space between **First discovered in system** and **Published** labels
=> ROX-30664: Fix space and comment KnownExploitLabel in CvePageHeader

tests/external_backup_test.go
This PR skips nongroovy tests that uses backup service as it's not implemented when using external DB.
https://github.com/stackrox/stackrox/blob/2fbfc8a949f8c67eb9714a07fefaa217992950c2/central/main.go#L467-L470
- https://github.com/stackrox/stackrox/pull/16533
=> ROX-30629: skip S3 tests on external PG 

central/administration/events/handler/handler.go, central/complianceoperator/v2/report/manager/manager_impl.go, pkg/administration/events/stream.go, pkg/administration/events/stream/stream.go, pkg/queue/queue.go, pkg/queue/queue_test.go, sensor/common/detector/detector.go, sensor/common/detector/queue/queue.go, sensor/common/detector/queue/queue_test.go, sensor/kubernetes/certrefresh/securedcluster_tls_issuer.go
This PR adds iterator to queue and uses it instead `PullBlocking` in `for` loops. This change should make code easier to follow.
=> chore(queue): add iterator

sensor/common/networkflow/manager/enrichment_test.go, sensor/common/networkflow/manager/manager_enrich_test.go, sensor/common/networkflow/manager/manager_impl.go, sensor/common/networkflow/manager/manager_impl_test.go, sensor/common/networkflow/manager/manager_sending_test.go, sensor/common/networkflow/manager/purger_test.go, sensor/common/networkflow/manager/testing_test.go, sensor/common/networkflow/metrics/metrics.go, sensor/common/networkflow/updatecomputer/interface.go, sensor/common/networkflow/updatecomputer/legacy.go, sensor/common/networkflow/updatecomputer/update_computer_test.go, sensor/kubernetes/sensor/sensor.go
🐑 Shepherd of this stack is @lvalerom and @rhybrillou (when back)
This PR extracts the calculation logic for sending updates to Central. A new `updateComputer` package is introduced that is responsible for determining what should be sent to central and what skipped. In this PR, there is only one implementation of the `updateComputer` called `Legacy`. The `Legacy` implements the update calculation behavior without any changes to the logic.
Some metrics and dedicated tests are added for the new `updateComputer` package.
- CI should be enough
=> ROX-30390: Extract Update Computer

roxctl/common/connection.go, roxctl/common/connection_test.go
This PR aims to fix following error by adding retry when DeadlineExceeded occurs:
```prolog
[FAIL] Invalid password in ROX_ADMIN_PASSWORD causes failure even though valid password specified with --password
Captured output was:
ERROR:	getting auth status: rpc error: code = DeadlineExceeded desc = context deadline exceeded
[FAIL] Invalid password in ROX_ADMIN_PASSWORD causes failure even though valid token file specified with --token-file
Captured output was:
ERROR:	getting auth status: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
=> ROX-3024: roxctl grpc retry on deadline exceeded

tests/e2e/run-compliance-e2e.sh
This PR aims to fix wrong junit reports paths resulting in not applying junit2jira nor prow UI to compliance test results.
- https://github.com/stackrox/stackrox/pull/6829 
CI
Log from junit2jira
```
INFO: Fri Aug 29 10:35:59 UTC 2025: Will use junit2jira to create CSV for BigQuery input
warning: tag '4.9' is externally known as '4.9.x'
time="Aug 29 10:36:00" level=info msg="Found 3 failed tests"
time="Aug 29 10:36:00" level=info msg="Issue not found. Creating new issue..." ID="?" summary="github.com/stackrox/rox/tests / TestComplianceV2UpdateScanConfigurations FAILED"
time="Aug 29 10:36:00" level=info msg="Issue not found. Creating new issue..." ID="?" summary="github.com/stackrox/rox/tests / TestComplianceV2ComplianceObjectMetadata FAILED"
time="Aug 29 10:36:00" level=info msg="Issue …
```
=> ROX-30690: configure junit output for compliance tests

image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml
I accidentally added the new `enforce` field in `admissionControl.dynamic`, but it should actually be in `admissionControl`.
=> fix: Fix YAML path of new enforce field in Helm config-shape

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/hooks/useManagedColumns.ts
Moves the column overrides out of the CVE, Image, and Deployment table containers and into the parent. This will allow us to pass a different set of overrides to the same components in both the standalone and plugin versions.
Manual smoke test. Existing e2e tests that exercise column management in Workload CVE Overview.
=> refactor(ui): Lift Workload CVE column overrides up to parent

central/reports/common/query_builder_view_based.go, central/reports/common/utils.go, central/reports/scheduler/v2/reportgenerator/report_gen_impl.go, central/reports/scheduler/v2/reportgenerator/report_gen_view_based_test.go, central/reports/scheduler/v2/reportgenerator/testutils.go, central/reports/service/v2/service_impl_test.go, central/reports/validation/validate.go, generated/api/v1/report_configuration_service.swagger.json, generated/api/v2/report_service.pb.go, generated/api/v2/report_service.swagger.json, generated/api/v2/report_service_vtproto.pb.go, generated/storage/report_configuration.pb.go, generated/storage/report_configuration_vtproto.pb.go, proto/api/v2/report_service.proto, proto/storage/proto.lock, proto/storage/report_configuration.proto
This PR adds a query builder for ondemand  reports. query builder uses filters in report snapshot to generate  access scope query and cve attribute query .query builder object is used by report generator to get data using select framework. 
Removed fields ImageType, include_nvd_cvss, include_epss from ViewBasedVulnerabilityReportFilters since we will show all columns by default and image type filter is not available in UI
Add  SimpleAccessScope.Rules to ViewBasedVulnerabilityReportFilters
Removed  extra fields from like image type, include nvd cvss etc from ViewBasedVulnerabilityReportFilters since for the first cut of this feature we only use query string(with search filters) to query data
- [X ] added unit tests
change me!
=> ROX-30375: Added changes to parse query string for ondemand reports

CHANGELOG.md, operator/api/v1alpha1/securedcluster_types.go, operator/api/v1alpha1/zz_generated.deepcopy.go, operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml, operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml, operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml, operator/hack/helm-cluster-config-assert.sh, operator/hack/operator.envsubst.yaml, operator/internal/common/defaulting/test_helpers/helpers.go, operator/internal/securedcluster/extensions/reconcile_defaulting.go, operator/internal/securedcluster/extensions/reconcile_defaulting_test.go, operator/internal/securedcluster/values/defaults/admission_controller.go, operator/internal/securedcluster/values/defaults/defaults.go, operator/internal/securedcluster/values/defaults/defaults_test.go, operator/internal/securedcluster/values/translation/translation.go, operator/internal/securedcluster/values/translation/translation_test.go, operator/tests/common/secured-cluster-cr.yaml, operator/tests/common/verify-dynamic-admission-controller-config.yaml, operator/tests/securedcluster/sc-basic/011-verify-dynamic-admission-controller-config.yaml, operator/tests/upgrade/upgrade/010-assert-central-cr-with-pre-4-9-admission-controller-config.yaml, operator/tests/upgrade/upgrade/010-assert.yaml, operator/tests/upgrade/upgrade/011-verify-pre-4-9-dynamic-admission-controller-config.yaml
1. The options
```
admissionControl:
listenOnCreates: # bool
listenOnUpdates: # bool
listenOnEvents:  # bool
```
are deprecated. Setting them has no effect as they are ignored (one exception, see second point). The Helm chart will treat them as enabled.
2. The field
```
admissionControl:
enforce: # bool
```
has been added. Defaults to `true` on fresh installations. On upgrades, this setting will default to `true` if and only if at least one of the previous options `listenOnCreates`, `listenOnUpdates` is enabled.
3. The field
```
admissionControl:
contactImageScanners: # string
```
is deprecated. It is not picked up by the translator. The Helm chart will make sure to enable inline scanning without any way to opt-out.
4. For the field
```
admissionControl:
bypass: …
```
=> ROX-30279: Operator changes for new Admission Controller Config

sensor/common/networkflow/manager/manager_impl.go, sensor/common/networkflow/metrics/metrics.go
This PR isolates the metric changes form the next PR in the stack. In particular:
- Create metric doubles (counter and gauge) as they are useful for different scenarios (counters help when investigating debug bundle data, gauges are great for grafana)
- Add more labels to selected metrics
- Decouple metrics recording from implementation details in selected functions
- I used those metrics upper in the stack to visualize and follow behaviors of netFlowManager
- CI should be enough to check whether we correctly set the number of labels (it would panic otherwise)
=> ROX-30390: Refactor netFlowManager metrics

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/ViewBasedReportJobDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/ReportParametersDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.ts
Prerequisite for Ross to add optional column for CISA KEV.
1. Follow up on suggestion during sneak peek at sprint demos to simplify checkbox text.
The less the delta to add an optional column, the better.
I had already omitted **Include** from `ReportParameterDetails` in #15467
2. Add `// Ross CISA KEV` comments because several files need consistent changes.
1. Inform docs team about change, because it affects:
https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes/4.8/html/operating/managing-vulnerabilities#vulnerability-management20-creating-report_vulnerability-reporting
2. Ask team about apparent inconsistency between optional columns for view-based and existing vulnerability reports.
2. `npm run …
=> ROX-30733: Omit include in optional columns and add CISA KEV comments

.tekton/main-pipeline.yaml
I spotted that `arm64` builds of `main` run for about an hour as opposed to 30-40 minutes for all other arches (examples: [one](https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs-4-8/pipelineruns/main-on-push-m92nd), [two](https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs-4-8/pipelineruns/main-on-push-z4859), [three](https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs/pipelineruns/main-on-push-ffbs6)).
This isn't due to queuing because the queue is in front of the PipelineRun, not in front of buildah* tasks.
Knowing from [docs](https://konflux.pages.redhat.com/docs/users/getting-started/multi-platform-builds.html#cpu-optimized) we can select …
=> build: Speed up `main` Konflux builds on arm64

tests/e2e/run-scanner-v4-install.bats
See ROX-30725 for explanation.
None needed.
No change to production code, only test code.
Locally executing the test suite file and observing the computed value.
+ CI.
=> ROX-30725: Take z-part into account for computing earlier version

central/securedclustercertgen/certificates.go, central/securedclustercertgen/certificates_test.go, central/sensor/service/connection/connection_impl.go, central/sensor/service/service_impl.go, generated/internalapi/central/secured_cluster_cert_refresh.pb.go, generated/internalapi/central/secured_cluster_cert_refresh_vtproto.pb.go, proto/internalapi/central/secured_cluster_cert_refresh.proto, sensor/kubernetes/certrefresh/securedcluster_tls_issuer.go, sensor/kubernetes/certrefresh/securedcluster_tls_issuer_test.go
CA rotation will initially be fully supported only by Operator-based installations. This is a recent development, due to difficulties with updating the `ca_bundle` of the `ValidatingWebhookConfiguration` when using Helm (we'd need an equivalent of https://github.com/stackrox/stackrox/pull/15706 for Helm). 
Helm-installed Secured Clusters will have partial support, in the sense that they will be able to connect to a Central that uses a new CA (as long as the one trusted by Sensor is still valid), but won't be able to automatically switch to it.
Because of the above, we need to change the certificate issuing logic, which currently is the following:
* if Sensor supports CA rotation, issue certificates signed by the latest CA
* otherwise issue certificates signed by the primary CA
This does …
=> ROX-30770: CA rotation fallback for Helm-installed Sensors

pkg/signatures/cosign_sig_verifier.go, pkg/signatures/cosign_sig_verifier_test.go
The problem is that `image.GetNames()` returns `[]*ImageName`, and when this is passed to `append(image.GetNames(), image.GetName())`, if multiple goroutines are working with the same image object, they could be sharing the underlying slice backing array.
The fix is avoiding an `append` call to shared slices - instead, `append` is only called on the unique slice, which is a local copy.
change me!
=> fix: data race in signature verification

ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx, ui/apps/platform/src/ConsolePlugin/Components/VulnerabilitiesOverviewContainer.tsx, ui/apps/platform/src/ConsolePlugin/PluginProvider.tsx, ui/apps/platform/src/ConsolePlugin/SecurityVulnerabilitiesPage/SecurityVulnerabilitiesPage.tsx, ui/apps/platform/src/ConsolePlugin/constants.ts, ui/apps/platform/src/ConsolePlugin/hooks/useDefaultWorkloadCveViewContext.ts, ui/apps/platform/src/utils/searchUtils.test.ts, ui/apps/platform/src/utils/searchUtils.ts, ui/apps/platform/webpack.ocp-plugin.config.js
Implements the main Security->Vulnerabilities page in the console for the OCP plugin.
Since this main dashboard view will be used in multiple locations, this change also adds:
1. A default Workload CVE context to be used throughout plugin pages
2. A wrapper component for the main vulnerabilities view that handles common dependencies across all of these pages e.g. pagination hooks, callbacks
1. e2e tests will follow in a separate PR to keep the size of this one manageable.
2. Visually, there is clearly too much space between the header components:
This will not be address at this point, as PatternFly 6 reduces the default padding of these components. Any attempt to achieve identical spacing to other console pages may be counter-productive before we upgrade to PF6.
3. This PR also includes …
=> ROX-30701: Implement SecurityVulnerabilitiesPage

CHANGELOG.md, roxctl/sensor/generate/generate.go, roxctl/sensor/generate/k8s.go, roxctl/sensor/generate/openshift.go
According to the design doc the now-deprecated admission controller flags shall not only be deprecated, but they shall also be without any effect, to ensure a good admission controller configuration.
No automated tests added or modified.
```
$ roxctl -e $API_ENDPOINT sensor generate k8s --name sensor-a --admission-controller-enforce-on-creates=false --admission-controller-enforce-on-updates=false --admission-controller-listen-on-creates=false --admission-controller-listen-on-updates=false --admission-controller-listen-on-events=false --admission-controller-timeout=5
Flag --admission-controller-enforce-on-creates has been deprecated, The --admission-controller-enforce-on-creates flag will be removed in future versions of roxctl. It will be ignored from version 4.9 onwards. …
```
=> ROX-30727: Let roxctl ignore deprecated admission controller flags

sensor/kubernetes/certrefresh/env.go, sensor/kubernetes/certrefresh/securedcluster_tls_issuer.go
Allow enabling CA rotation in Sensor independently for Operator and Helm installations. This is needed because Helm support will come at a later time.
Relates to [ROX-27964](http://issues.redhat.com/browse/ROX-27964)
Manually tested on the https://github.com/stackrox/stackrox/pull/15349 branch, where the CA is rotated after 10 minutes.
Steps taken:
- install Central and Secured Cluster
- wait until CA is rotated
- delete a random TLS secret on Sensor to force an update (e.g. `tls-cert-scanner`)
- check that the new TLS certificates are signed by the appropriate CA (new CA when using the Operator, old CA when using Helm)
=> ROX-27964: separate feature flag for CA rotation by install method

ui/Makefile, ui/apps/platform/README.md, ui/apps/platform/cypress.config.js, ui/apps/platform/cypress/helpers/ocpAuth.ts, ui/apps/platform/cypress/integration-ocp/smoke.test.ts, ui/apps/platform/package.json, ui/apps/platform/scripts/cypress-ocp.sh, ui/apps/platform/scripts/cypress.sh, ui/package.json
This is a re-commit of *only the UI changes* that were reverted in https://github.com/stackrox/stackrox/pull/16698.
The original full change set in the PR breaks `ocp-qa-e2e-tests` test runs due to the CI changes causing an cluster name change. More context here: https://redhat-internal.slack.com/archives/CELUQKESC/p1757098564825109
Since the plugin e2e test already are unable to run in CI, this re-adds the UI only changes so that tests can continue to be developed and run *locally* until we are ready to re-implement the changes in CI.
Manually run `/test ocp-4-19-qa-e2e-tests` on this PR and ensure the job succeeds.
=> test(ui): Add UI script changes to allow plugin e2e tests

central/clusters/deployer.go, tests/e2e/run-scanner-v4-install.bats
Make sure that we don't inject `ROX_SCANNER_V4=true` into sensor deployment bundles.
No doc changes needed.
Deploy Central.
```
roxctl -e $API_ENDPOINT--insecure-skip-tls-verify sensor generate k8s --name sc6
INFO:   Deployment bundle does not include PodSecurityPolicies (PSPs).
INFO:   This is incompatible with pre-v1.25 Kubernetes installations having the PodSecurityPolicy Admission Controller plugin enabled.
INFO:   Use --enable-pod-security-policies if PodSecurityPolicies are required for your Kubernetes environment.
INFO:   Successfully wrote sensor folder "sensor-sc6"
```
```
❯ cat sensor-sc6/sensor.yaml | yq e  '. | select(.metadata.name == "sensor" and .kind == "Deployment")' -o=json | jq -r '.spec.template.spec.containers[0].env[] | select(.name | startswith("ROX_")) | …
```
=> ROX-30724,ROX-30397: Don't set ROX_SCANNER_V4 in manifest bundle env

pkg/postgres/schema/configs.go, pkg/postgres/schema/delegated_registry_configs.go, pkg/postgres/schema/installation_infos.go, pkg/postgres/schema/notification_schedules.go, pkg/postgres/schema/notifier_enc_configs.go, pkg/postgres/schema/sensor_upgrade_configs.go, pkg/postgres/schema/system_infos.go, pkg/postgres/schema/versions.go, tools/generate-helpers/pg-table-bindings/main.go, tools/generate-helpers/pg-table-bindings/schema.go.tpl
The cloud service when trying to use logical replication discovered that we have 8 tables with no replication identity and thus they cannot be replicated.  
```
| configs
| delegated_registry_configs
| installation_infos
| notification_schedules
| notifier_enc_configs
| sensor_upgrade_configs
| system_infos
| versions
```
Since these tables do not have a primary key they have no replication identity and thus cannot be replicated.  All these tables are `singletons` which in our data framework lingo means they only ever have at most 1 row.  So changing the replication identity of these tables to be `FULL` should resolve this issue.  Any further singletons created will automatically gather this as long as the code gen tools are utilized correctly.
Before:
```
stackrox=> SELECT
relname,
CASE …
```
=> ROX-30748: full identity singletons

ui/apps/platform/cypress/helpers/main.js, ui/apps/platform/cypress/helpers/nav.ts, ui/apps/platform/cypress/helpers/ocpAuth.ts, ui/apps/platform/cypress/helpers/ocpConsole.ts, ui/apps/platform/cypress/helpers/tableHelpers.ts, ui/apps/platform/cypress/helpers/visit.js, ui/apps/platform/cypress/integration-ocp/security/vulnerabilities.test.ts, ui/apps/platform/cypress/selectors/pf6.ts, ui/apps/platform/scripts/cypress-ocp.sh, ui/apps/platform/src/ConsolePlugin/Components/VulnerabilitiesOverviewContainer.tsx, ui/apps/platform/src/ConsolePlugin/ProjectSecurityTab/ProjectSecurityTab.tsx
Much like https://github.com/stackrox/stackrox/pull/16714, adds the Vuln Overview to the Home -> Projects -> Security tab.
Navigate to Home -> Projects -> Security and validate the correct data is shown:
=> ROX-30705: Adds implementation of project security tab

ui/apps/platform/src/Containers/Clusters/ClusterSummaryGrid.tsx, ui/apps/platform/src/Containers/Clusters/Components/ClusterMetadata.tsx, ui/apps/platform/src/Containers/Clusters/DynamicConfigurationForm.tsx
Hide space (because of indentation changes) for review.
1. Thank you, **Khushboo** for finding lack of conditional rendering for `status: null` property in clusters response.
2. Investigation of conditional rendering also found copy-pasto of **ClusterSummary** instead of **Kubernetes version** in `ClusterMetadata` element.
How did I forget to study and conditional rendering in `ClusterTable` component?
1. Study conditional rendering in `ClusterTable` component, and then apply it in `ClusterSummaryGrid` component.
2. Fix copy-pasto.
3. Add `| null` to prop declaration of `DynamicConfigurationForm` component.
See absence of errors, because already had optional chaining.
Although it would be parallel to do similarly in `StaticConfigurationForm` element, to make sure we do not miss optional …
=> ROX-30827: Add conditional rendering for status in ClusterSummaryGrid

ui/apps/platform/src/Components/SelectSingle/SelectSingle.tsx, ui/apps/platform/src/Containers/Clusters/DynamicConfigurationForm.tsx, ui/apps/platform/src/Containers/Clusters/StaticConfigurationForm.tsx
Thank you, **David Vail** for careful testing!
1. Clickable area in `SelectOption` has less than width of option.
2. Width of `Select` is too wide.
Find in Files `<SelectSingle` has 33 results in 24 files including:
* 3 in DynamicConfigurationForm.tsx file
* 4 in StaticConfigurationForm.tsx file
We limited width of `TextInput` via `isWidthLimited` prop of `Form` element in #16501
In SelectSingle.tsx file, `MenuToggle` has `className="pf-v5-u-w-100"` prop.
1. As discussed with team in Slack thread, replace `className` with `isFullWidth` prop of `MenuToggle` element add it to `SelectSingle` component.
https://www.patternfly.org/components/menus/select#menutoggle
2. To unblock the solution for this feature, `isFullWidth` prop is optional with `true` as default value to preserve existing …
=> ROX-30883: Limit width of Select elements in cluster form

ui/apps/platform/eslint-plugins/pluginPatternFly.js, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageDetailBadges.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameLink.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageScanningIncompleteLabel.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/SignatureCountLabel.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/VerifiedSignatureLabel.tsx
Although for consistency with CISA KEV, omit from feature epic to prevent distraction.
Manual testing of multiple labels for CISA KEV discovered a similar cell layout.
* Width of **Image** column determines whether layout of labels is horizontal, or vertical, or both.
* Although there has been a pattern for part-time contributors to follow, even better that labels row become a consistent pattern.
* `ImageNameLink` component has extra layout responsibility for layout.
1. Find in Files `<ImageNameLink` has 4 results in 4 files
* 3 have no children
* 1 has children: ImageOverviewTable.tsx file
2. Purpose of `Label` wrapped in `Button` wrapped in `Popover` element seems like indication that there is a click interaction.
3. `VerifiedSignatureLabel` encapsulates the condition whether or not to …
=> ROX-30682: Generalize ImageOverviewTable for multiple labels

.tekton/basic-component-pipeline.yaml, .tekton/main-pipeline.yaml, .tekton/scanner-v4-pipeline.yaml
Manual backport of https://github.com/stackrox/stackrox/pull/16851 through cherry-pick.
No change.
Only CI.
=> ROX-30898: Assign index image tag differently / 4.8

.tekton/basic-component-pipeline.yaml, .tekton/main-pipeline.yaml, .tekton/scanner-v4-pipeline.yaml
Manual backport of https://github.com/stackrox/stackrox/pull/16851 through cherry-pick.
No change.
Only CI.
=> ROX-30898: Assign index image tag differently / 4.7

.tekton/basic-component-pipeline.yaml, .tekton/main-pipeline.yaml, .tekton/scanner-v4-pipeline.yaml
Manual backport of https://github.com/stackrox/stackrox/pull/16851 through cherry-pick.
No change.
Only CI.
=> ROX-30898: Assign index image tag differently / 4.6

.github/renovate.json5
As we [start seeing](https://redhat-internal.slack.com/archives/CELUQKESC/p1758093948724879?thread_ts=1758016415.279099&cid=CELUQKESC) MintMaker getting alive again in StackRox, I remembered about this docs page https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#how-to-limit-the-number-of-prsmrs
We want to see all PRs in the StackRox repo since we have no automerge here and so I decided to bump the limits.
You can find out defaults and descriptions in docs:
- https://docs.renovatebot.com/configuration-options/#prhourlylimit
- https://docs.renovatebot.com/configuration-options/#prconcurrentlimit
- https://docs.renovatebot.com/configuration-options/#branchconcurrentlimit
Please also keep in mind the default from MintMaker config:
- …
=> chore: Bump Renovate PR limits

tests/performance/scale/config/metrics-acs-base.yml, tests/performance/scale/config/metrics-acs.yml, tests/performance/scale/config/metrics-full.yml
The current CPU metric is using the formula: `cores * 100` - which is wrong and misleading.
This PR is adding new metrics to collect mili-cores.
Plan for switching is:
1. add new metric
2. wait for a reasonable time to collect data (1-2 months)
3. switch to new metric in dashboards/scripts
4. fix the old metric to represent mCores
5. wait for a reasonable time to collect data (1-2 months)
6. switch to the old fixed metric in dashboards/scripts
7. remove the new metric
**Note:**
Changes related to `captureStart: true` and introduced in another PR, but not all files have been fixed. Since I'm using a script to merge files, this is a product of that.
I didn't test changes.
=> chore(perf): Add new metrics for CPU in mCores

qa-tests-backend/src/test/groovy/BaseSpecification.groovy
This PR add a check for healthy cluster at the end of test spec. This is done to ensure the test left cluster in healthy state so it will not interfere with other tests,
=> chore(qa): wait for cluster healthy

ui/apps/platform/cypress/integration-ocp/security/cveDetail.test.ts, ui/apps/platform/cypress/integration-ocp/security/imageDetail.test.ts, ui/apps/platform/src/ConsolePlugin/ImageDetailPage/ImageDetailPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/DeploymentResourceTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageResources.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageRoute.tsx
Adds the implementation of the Image detail page in the OCP console along with related e2e tests. As part of this change, we also need to allow customization of the Resources -> Deployment table (although we do not need to expose this customization to the user).
As always, "Hide whitespace" makes this a little easier to review.
New Cypress e2e tests check the basics of the page and navigation across pages. The new tests also check that the "Namespace" column is hidden in the resources table when not viewing "All projects".
=> ROX-30703: Adds implementation for plugin Image detail page

deploy/charts/monitoring/dashboards/enrichment-connections.json, deploy/charts/monitoring/dashboards/enrichment-endpoints.json
The diff should be readable. I mainly wanted to correct the legend that  shows now `open` and `closed` instead of `closedTS=true` - this was applied to few places.
- Visually in grafana
=> ROX-30390: Adjust grafana dashboards to recent changes

ui/apps/platform/src/Containers/Clusters/Components/SensorUpgradePanel.tsx, ui/apps/platform/src/Containers/Clusters/cluster.helpers.test.js, ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx
Over-communicate relationship between solution and problem to reduce the probability that we revisit this issue again within the next year.
Slack comment in team public channel from **Michael Hess**:
> A colleague of ours recently tried out ACS CS with an older Secured Cluster to simulate a possible on-prem to cloud migration for their customer.
> While doing so, they noticed that the secured cluster page is giving them a warning.
> They raised the question why they were seeing a warning about the Operator controlling upgrades. I somewhat agree, as to the best of my understanding this setup is best practice (operator governs auto upgrades) so the warning is misleading.
> I am also wondering if the warning is actually triggered by secured cluster being Operator controlled, or if it is due …
=> ROX-30947: Distinguish warning from information for sensor upgrade

operator/internal/common/confighash/pod_template_annotation.go, operator/tests/common/config-hash-assert.yaml
This PR checks that all the pods that belong to Stackrox have the correct config-hash annotation.
This makes sure that this test will fail if new workload types are added to ACS in the future, and we forget to add the config-hash to their pod template annotations.
CI will test the happy flow.
Tested the error flow manually by executing the script with a wrong hash:
```
ERROR: Pods with missing or mismatched app.stackrox.io/config-hash:
admission-control-785d8f5f87-56n9k	admission-control-785d8f5f87-7vmx9	admission-control-785d8f5f87-9zhsw	central-55945d9fbd-j5sgw	central-db-76fcbf56b-f5fw4	collector-dj27m	collector-l6q4s	collector-mlm5j	collector-s4mbp	collector-sxhh5	collector-vzbds	config-controller-79cbbbf9b5-5tzhj	scanner-65f998b879-hnq2j	scanner-65f998b879-zwh6h …
```
=> ROX-30875: Verify pod config-hash annotation in Operator Kuttl tests

qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
Backport of https://github.com/stackrox/stackrox/pull/16634
Only CI.
=> fix(ci): Bump Glibc CVE for ImageScanningTest to pass

central/convert/storagetov2/vuln_exception_service_test.go, central/convert/v2tostorage/vuln_exception_service.go, central/convert/v2tostorage/vuln_exception_service_test.go, central/vulnmgmt/vulnerabilityrequest/utils/util.go
The indefinite deferrals used to rely on `ExpiresOn` timestamp in storage.VulnerabilityRequest being set to nil. This `ExpiresOn` field is a part of one of field in proto.
```
oneof expiry {
// Indicates that this request expires when the associated vulnerability is fixed.
bool expires_when_fixed = 1; // @gotags: search:"Request Expires When Fixed"
// Indicates the timestamp when this request expires.
google.protobuf.Timestamp expires_on = 2; // @gotags: search:"Request Expiry Time"
}
```
We upgraded the tool used to generate marshalling and unmarshalling code sometime in 4.7. Because of this change, if the value of a field inside one of wrapper is nil, then the marshaller defaults its value to the type's zero value. In this case, if `ExpiresOn` is nil, then marshaller will set it to zero …
=> ROX-29388: Fix indefinite deferrals getting expired when storing them in db

ui/apps/platform/eslint-plugins/pluginGeneric.js, ui/apps/platform/src/services/ReportsService.ts
Double down on consistent use of `import type` statement to step forward instead of sideways.
Require `import type` to follow corresponding `import` statement (if it exists).
Use typescript-eslint playground:
https://typescript-eslint.io/play/#ts=5.9.2&showAST=es&fileType=.tsx
2. `npm run lint:fast-dev` in ui/apps/platform folder.
> src/services/ReportsService.ts
> 3:1  error  Move import type to follow corresponding import statement  generic/import-type-order
=> ROX-30988: Add import-type-order rule to pluginGeneric

ui/apps/platform/eslint-plugins/pluginLimited.js, ui/apps/platform/eslint.config.js, ui/apps/platform/src/ConsolePlugin/PluginProvider.tsx, ui/apps/platform/src/constants/accessControl.ts, ui/apps/platform/src/hooks/useTabs.test.jsx, ui/apps/platform/src/index.tsx, ui/apps/platform/src/init/installRaven.js, ui/apps/platform/src/reducers/cloudSources.js, ui/apps/platform/src/reducers/machineAccessConfigs.js, ui/apps/platform/src/reducers/roles.js, ui/apps/platform/src/services/AccessScopesService.ts, ui/apps/platform/src/services/AdministrationUsageService.ts, ui/apps/platform/src/services/AuthService/AuthService.ts, ui/apps/platform/src/services/DeclarativeConfigHealthService.ts, ui/apps/platform/src/services/IntegrationHealthService.ts, ui/apps/platform/src/services/ReportsService.ts, ui/apps/platform/src/services/ReportsService.types.ts, ui/apps/platform/src/services/SystemConfigService.ts
Toward Q3 AI goal: help AI to help us.
Prerequisite so `import` statements from other containers can have consistent order:
* follow package dependencies
* precede relative path within container
Mental slow cooker decided what to do about false positives, therefore we can fix these errors at same time as `import type` and React qualified name.
1. Add `'no-relative-path-to-src-in-import'` to pluginLimited.js file with `ignores` array:
* Components
* ConsolePlugins
* Containers subfolders
Decide what to do about ConsolePlugins or Containers subfolders that do have relative paths to subfolders like:
* Components
* hooks
1. Distinguish path in folder from path in package dependency.
Investigate options of lint rules in `eslint-plugin-import` package. …
=> ROX-30991: Replace relative path to subfolder of src in some import

ui/apps/platform/src/Containers/Policies/Wizard/Step5/PolicyEnforcementForm.tsx
Policy enforcement when using Runtime -> Audit Log is an invalid option, so we disable the ability to enable enforcement when this lifecycle/event source combination is selected.
Before this change:
=> ROX-30968: Enforcement is disabled for audit log policies

operator/internal/central/carotation/rotation.go, operator/internal/central/carotation/rotation_test.go, operator/internal/central/extensions/reconcile_tls.go, operator/internal/central/extensions/reconcile_tls_ca_rotation_test.go, operator/internal/central/extensions/reconcile_tls_test.go
This PR fixes a bug where the Operator would enter an irreconcilable state during CA rotation, after an upgrade from a previous version of ACS that does not support CA rotation, and has a CA older than 4 years:
* Initial central-tls secrets validation determined AddSecondary CA rotation action is needed (typically done after 3 years)
* Post-generation validation now sees that PromoteSecondary CA rotation action is needed
* Which causes "CA rotation action needed" error in post-generation validation
To fix this scenario, this PR introduces a new CA rotation action, AddSecondaryAndPromote, which performs both actions (AddSecondary and PromoteSecondary) in a single step.
This is an alternative to the fix proposed in https://github.com/stackrox/stackrox/pull/16992
Manual testing on [this …
=> ROX-31011: fix CA rotation failure after version upgrade

scale/workloads/10-sensors.yaml, scale/workloads/active-vulnmgmt.yaml, scale/workloads/default.yaml, scale/workloads/high-alert.yaml, scale/workloads/long-running.yaml, scale/workloads/np-load.yaml, scale/workloads/okr-single-load.yaml, scale/workloads/rbac.yaml, scale/workloads/sample.yaml, scale/workloads/scale-test.yaml, scale/workloads/small.yaml, scale/workloads/vulnmgmt.yaml, scale/workloads/xlarge.yaml, sensor/kubernetes/fake/fake.go, sensor/kubernetes/fake/flows.go, sensor/kubernetes/fake/flows_test.go, sensor/kubernetes/fake/workload.go
Introduced configurable port reuse probability to limit unrealistic endpoint sharing behavior in fake workload generation.
**Key Changes:**
- **Added `OriginatorCache`**: Implements probabilistic endpoint-to-originator caching with configurable reuse probability
- **Added `openPortReuseProbability` field**: Configurable parameter (default 0.05) controlling how often different processes reuse the same IP:port without closing endpoints
- **Updated all workload configurations**: Set realistic 5% port reuse probability across all test scenarios
- **Enhanced network endpoint generation**: Uses consistent originator caching instead of random assignment
**Why**: Previous behavior (100% port reuse in releases ≤4.8) was unrealistic and caused memory pressure in Sensor's enrichment pipeline. …
=> ROX-30860: Limit parallel port use by processes 

.tekton/operator-bundle-pipeline.yaml, scripts/ci/jobs/check-konflux-setup.sh
To make Conforma happy.
See https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1758739440034849
I had a feeling that I missed something in https://github.com/stackrox/stackrox/pull/16959 and this is it. CI did not trigger a failure in our `check-konflux-setup.sh` because `collector-slim` was excluded there.
No change.
=> ROX-30945: Include collector-slim in our custom snapshot

make/protogen.mk
With PR: https://github.com/stackrox/stackrox/pull/16237 - support for podman is added.
There is a situation that is not well handled on systems with both commands available. Make will prioritize podman over docker. As mentioned in this comment: https://github.com/stackrox/stackrox/pull/16237#discussion_r2371085469
That comment was rejected because the expectations that make command, which triggers this target, is not often executed. There is one case that was neglected. If someone wants to build docker image locally, they require docs files, because they are copied into the image.
This PR is adding new changes.
- if both commands are there: docker will be used
- if podman is there and no docker: podman will be used
- if none of them can be found: docker will be used
- if calling command …
=> chore(tweak): Make docker command priority in protogen

.github/actions/job-preamble/action.yaml
Cherry-pick of https://github.com/stackrox/stackrox/pull/17027 to `release-4.6` in order to fix RCE builds.
No change.
Only by looking at CI status.
=> fix(gha): backport changes for job-preamble

generated/internalapi/scanner/v4/indexer_service.pb.go, generated/internalapi/scanner/v4/indexer_service_grpc.pb.go, generated/internalapi/scanner/v4/indexer_service_vtproto.pb.go, pkg/features/list.go, pkg/scanners/scannerv4/scannerv4.go, pkg/scanners/types/components.go, pkg/scannerv4/client/client.go, pkg/scannerv4/client/mocks/client.go, proto/internalapi/scanner/v4/indexer_service.proto, scanner/datastore/postgres/external_index_report.go, scanner/datastore/postgres/external_index_report_test.go, scanner/datastore/postgres/external_index_store.go, scanner/datastore/postgres/indexer_metadata_store.go, scanner/datastore/postgres/manifest_metadata.go, scanner/datastore/postgres/migrations/indexer/02-external-index-report.sql, scanner/datastore/postgres/migrations/migrations.go, scanner/datastore/postgres/mocks/indexer_metadata_store.go, scanner/datastore/postgres/reindex_gc.go, scanner/indexer/indexer.go, scanner/indexer/indexer_test.go, scanner/indexer/manifest/manager.go, scanner/indexer/mocks/indexer.go, scanner/services/common.go, scanner/services/indexer.go, scanner/services/matcher.go
- Adds a new Scanner V4 gRPC API, `StoreIndexReport`, to store index reports from other scanners. This API will initially be used to store index reports from delegated scans, supporting the generation of SBOMs from those index reports.
- Adds a new table to the Indexer's `external_index_report` that will house the delegated scan index reports, along with some metadata to make decisions on whether to overwrite the data on conflict and garbage collect the data.
- Adds a feature flag, `ROX_SCANNER_V4_STORE_EXTERNAL_INDEX_REPORTS` (subject to change based on reviews), to toggle storing external index reports from delegated scans to Central's Scanner V4 Indexer. It's on by default, and can be toggled off to disable storing external index reports. Not that disabling `ROX_SBOM_GENERATION` will …
=> ROX-27149: Store Index Report API

ui/apps/platform/src/Containers/Policies/policies.utils.test.ts, ui/apps/platform/src/Containers/Policies/policies.utils.ts
Fixes a long standing issue (3.72!) where splitting of policy criteria values for "Disallowed Dockerfile line" with a key of `ENV` and a value that contains `=`, as well as "Environment Variable" where the value contains `=`, mangles the output value. I believe this causes this criteria to function incorrectly as well, but I would need to test it.
Modified exiting unit tests for the ENV case and added criteria for the "Environment variable" case.
Manual testing with the following criteria:
Before:
After:
=> ROX-13221: Fixes splitting of policy criteria values that contain '='

tests/performance/scale/config/orion-acs-cluster-density-v2.yml
This PR is adding Orion configuration to check regression on ACS cluster-density-v2 job.
I validated configuration manually:
```
export ES_SERVER=https://<username>:<password>@<elasticsearch>
export es_metadata_index='perf_scale_ci*'
export es_benchmark_index='ripsaw-kube-burner*'
```
I made a Docker image from: https://github.com/cloud-bulldozer/orion - and ran it with `tail -f /dev/null`.
After that, I could `exec` and copy files into the container.
```
orion --config orion-acs-cluster-density-v2.yml --hunter-analyze  --input-vars='{"version": "4.19"}'  --lookback=30d
```
=> ROX-30848: Add Orion config for ACS cluster-density-v2 job

central/metrics/custom/runner.go, central/metrics/custom/tracker/tracker_base.go, central/metrics/custom/tracker/tracker_base_test.go, central/metrics/custom_registry.go
Track the event of the metrics configuration with provided related central identity properties.
Segment:
```json
{
"anonymousId": "252d4cd4-9f59-499b-9b24-9ce485d4291f",
"context": {
"app": {
"build": "development",
"version": "4.9.x-95-g586a4a7736"
},
"device": {
"id": "252d4cd4-9f59-499b-9b24-9ce485d4291f",
"type": "Central Server",
"version": "4.9.x-95-g586a4a7736"
},
"library": {
},
"traits": {
"Total custom Prometheus registries": 1
},
"userAgent": "Rox Central/4.9.x-95-g586a4a7736 (linux; amd64)"
},
"event": "Served custom Prometheus metrics",
"messageId": "prom_registries-302d377998730586",
"originalTimestamp": "2025-07-28T14:31:52.381788392Z",
"receivedAt": "2025-07-28T14:31:52.474Z",
"sentAt": …
```
=> ROX-28151: Phonehome telemetry for custom Prometheus metrics

generated/internalapi/scanner/v4/indexer_service.pb.go, generated/internalapi/scanner/v4/indexer_service_vtproto.pb.go, pkg/scanners/scannerv4/scannerv4.go, pkg/scannerv4/client/client.go, proto/internalapi/scanner/v4/indexer_service.proto, scanner/datastore/postgres/external_index_report.go, scanner/datastore/postgres/external_index_store.go, scanner/indexer/indexer.go, scanner/indexer/indexer_test.go, scanner/indexer/mocks/indexer.go, scanner/indexer/remote.go, scanner/services/common.go, scanner/services/indexer.go, scanner/services/indexer_test.go, scanner/services/matcher.go, scanner/services/matcher_test.go
- Modifies the `Indexer.GetIndexReport` gRPC request to include a new field, `includeExternalReports`, which includes getting external index reports from the Scanner V4 Indexer. This is plumbed through the entire system, including the common Scanner V4 client; however, it's only used in the `GetSBOM()` abstraction.
- Adds a new method to `ExternalIndexStore`, `GetIndexReport()`, which returns the external index report from a provided `hashID`.
- Implemented `ExternalIndexStore.GetIndexReport()` for `externalIndexStore`.
PR stack:
- `master`
- https://github.com/stackrox/stackrox/pull/16527
- https://github.com/stackrox/stackrox/pull/16398
- 👉 https://github.com/stackrox/stackrox/pull/16526
-  https://github.com/stackrox/stackrox/pull/16884
- ~~added unit tests~~
- ~~added e2e tests~~
- …
=> ROX-27150: Pull external index reports

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/useNodeSummaryData.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/VirtualMachine/VirtualMachinePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/aggregateUtils.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/BySeveritySummaryCard.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/CvesByStatusSummaryCard.tsx
Adds Virtual Machine CVEs Summary Cards
Summary cards added for the following:
* CVEs by severity
* CVEs by status (fixable/non-fixable)
Additional Notes:
* Lifted `CvesByStatusSummaryCard` out of the `WorkloadCves` container and into the generic `Vulnerabilities/components` directory.
* Hidden statuses – Currently we could show all severities/statuses counts even when filtered, however I'm under the assumption that once filtering is implemented on the backend we will lose that capability.
---
---
---
=> ROX-31034: Virtual Machine CVEs Summary Cards

ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/Overview/VirtualMachineCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/Overview/VirtualMachinesCvesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/VirtualMachine/VirtualMachinePageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/VirtualMachineCvesPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VirtualMachineCves/aggregateUtils.ts, ui/apps/platform/src/Containers/Vulnerabilities/utils/searchUtils.tsx
Updates the following:
* Hooks up link between virtual machines page and single virtual machine page
* Updates the single virtual machine route to be more consistent with other sections in vulnerabilities. Changed from `/vulnerabilities/virtual-machine-cves/:id` to `/vulnerabilities/virtual-machine-cves/virtualmachines/:id`.
* Severity count on the virtual machines list table is now based on `EmbeddedVulnerability.severity` as opposed to `EmbeddedVulnerability.cvssv3.severity`. 
* Title and dev preview label wrapper changed from `Split` to `Flex`. It seems that split uses flexbox under the hood with align items set to stretch causes the dev preview label to fill up the containers height (not respecting `isCompact`)
=> chore(ui): Update virtual machine route and severity counts

go.mod, go.sum, operator/tests/central/central-misc/064-assert-after-unset-expose-monitoring.yaml, operator/tests/common/central-cr-assert.yaml, operator/tests/common/central-cr-without-scanner-v4-assert.yaml, operator/tests/common/monitoring-auth-reader-assert.yaml, operator/tests/common/secured-cluster-cr-assert-no-scanner-v4.yaml, operator/tests/common/secured-cluster-cr-assert.yaml, operator/tests/common/upgrade-assert.envsubst.yaml, operator/tests/securedcluster/sc-basic/020-assert.yaml, operator/tests/upgrade/upgrade/010-assert-central-cr-with-pre-4-9-admission-controller-config.yaml
TODO:
The pause-reconcile support is upstream as of March 2025 (https://github.com/operator-framework/helm-operator-plugins/pull/426). It includes the `Paused` condition in `status`.
So we need to teach our tests to tolerate it before we rebase our helm-operator fork.
The problem is https://github.com/kudobuilder/kuttl/issues/76 but it is possible to work it around by using the recently added CEL support. Here I'm changing only the places which are exposed to a status of a CR reconciled by any "old" version of the ACS operator, because the regular CEL-free way is more readable and any failures are also reported in a nicer way.
CI
=> ROX-12637: make kuttl tests tolerate pause reconcile status condition

tests/upgrade/postgres_run.sh
Bumping the patch version per release [instructions](https://spaces.redhat.com/spaces/StackRox/pages/690979844/Upstream+Konflux+Release#Upstream%2BKonfluxRelease-update-upgrade-testUpdateUpgradeTest).
Nothing new.
Looking to see green upgrade test.
=> ROX-30945: Bump 4.6.9 -> 4.6.10 patch version

sensor/tests/helper/helper.go, sensor/tests/resource/networkpolicy/networkpolicy_test.go
Add check that no empty alert results are sent during network policy evaluation in network policy tests.
=> chore(CI): Check no empty alert results in network policy tests

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentOverviewTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/utils/sortUtils.tsx
As titled, adds sorting to the Deployment Overview list "CVEs by severity" column.
Visit the Deployment Tab in Vuln Management and sort by the CVE severity column:
=> ROX-30504: Allow sorting by CVE severity across affected deployments

tests/upgrade/postgres_run.sh
Following release instructions https://spaces.redhat.com/spaces/StackRox/pages/690979844/Upstream+Konflux+Release#Upstream%2BKonfluxRelease-update-upgrade-testUpdateUpgradeTest
No updates
Upgrade test CI is sufficient.
=> ROX-30945: bump 4.7 version in upgrade tests

central/pod/datastore/datastore_impl_real_test.go, central/processbaseline/baselineutils.go, central/processbaseline/evaluator/evaluator.go, central/processbaseline/evaluator/evaluator_impl.go, central/processbaseline/evaluator/evaluator_integration_test.go, central/processbaseline/evaluator/evaluator_test.go, central/processbaseline/evaluator/mocks/evaluator.go, central/processindicator/datastore/bench_test.go, central/processindicator/datastore/datastore.go, central/processindicator/datastore/datastore_impl.go, central/processindicator/datastore/datastore_impl_test.go, central/processindicator/datastore/mocks/datastore.go, central/processindicator/datastore/singleton.go, central/processindicator/views/risk_evaluation_view.go, central/processlisteningonport/datastore/datastore_impl_test.go, central/processlisteningonport/service/service_impl_test.go, central/risk/multipliers/deployment/process_baseline_violations.go, central/risk/multipliers/deployment/process_baseline_violations_test.go, pkg/processbaseline/processbaseline.go
Stripping the data pulled from the database.  Using our "view" like mechanism to run `Select` queries to only retrieve the 6 or so fields that are required for re-evaluation.  Notice the explain plans below that show the width of each row returned is cut in half which will save memory on both central and central-db as well as traffic between the two.  Also the benchmark results below can be compared to those in #16932 .  The speed is very slightly slower, but the memory allocations are cut in half with this PR.
```
go test -tags sql_integration -bench=. -benchmem -run=^$
goos: darwin
goarch: arm64
pkg: github.com/stackrox/rox/central/processbaseline/evaluator
cpu: Apple M3 Pro
BenchmarkEvaluateBaselinesAndPersistResult/100_processes_2_containers-12         	    3396	    317166 ns/op …
```
=> ROX-30963: Only query indicator fields needed for evalution

migrator/migrations/m_212_to_m_213_add_container_start_column_to_indicators/migration_impl.go, migrator/runner/runner.go
Instead of pulling all indicators by cluster, pull them by cluster and signal time is null.  This way if a migration restarts we won't have to reprocess what we already updated.
The query generated is `select process_indicators.serialized from process_indicators where (process_indicators.ClusterId = $1 and process_indicators.ContainerStartTime is null)`
Using my large snapshot on an external database, killing the migration part way through and verifying in the logs that the cluster in progress at time of bounce processes fewer rows 2nd time around.
Start the migration.  Restarted the pod where the log stops.
```
Migrator: 2025/10/01 14:50:08.357910 log.go:18: Info: Found DB at version 212, which is less than what we expect (213). Running migrations... …
```
=> ROX-31114: improve indicator migration

ui/apps/platform/src/ConsolePlugin/WorkloadSecurityTab/WorkloadSecurityTab.tsx, ui/apps/platform/src/ConsolePlugin/hooks/useWorkloadId.ts
Adds the Deployment detail view to Workload pages in the OCP console.
The OCP Workload pages reference a workload by **workload name** and **namespace name**. Since ACS APIs expect a workload "id", we need to query ACS for a list of workloads matching the workload and namespace name in the URL and extract the ID from the response.
Due to the OCP console not providing any information about the cluster, and even if it did, ACS uses a separate model for cluster name/id on the backend, these queries are unable to restrict the data to a specific cluster when hitting central directly. **For this to work in production, we must have backend support to restrict to a single cluster.**
Visit the Deployments list in the console and select an individual deployment. From there, navigate to the Security …
=> ROX-30704: Add implementation for Workload Security tab

ui/apps/platform/src/Containers/Policies/Wizard/Step2/PolicyBehaviorForm.tsx
As titled - final update of this text.
👀 
Docs link fails locally, but when replaced with 4.8 navigates to https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes/4.8/html/operating/managing-security-policies#con-policy-lifecycle_about-security-policies
=> chore(ui): Update policy lifecycle descriptions

.tekton/central-db-build.yaml, .tekton/main-build.yaml, .tekton/operator-build.yaml, .tekton/operator-bundle-build.yaml, .tekton/roxctl-build.yaml, .tekton/scanner-v4-build.yaml, .tekton/scanner-v4-db-build.yaml
From the Slack thread <https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1758784462802249>, my observations and trials in this PR it's clear that OOMs happen in `/root/.cache/hermeto/go/go1.21.0/bin/go mod download -json` command that's executed by Hermeto to prefetch Go dependencies.
The thread is inconclusive about the root cause of the error. On one hand, I'm sure little has changed on our side, especially in `release-4.6` branch. On the other, what exactly happens in `go mod download` and what to do to prevent it requesting lots of memory quickly is left without the answers.
I used https://github.com/stackrox/stackrox/pull/17053 to trigger multiple runs and validate the change is stable.
`build-source-image` tends to fail too. It's not news but the one started doing that more …
=> ROX-31079: Reduce OOM kills in Konflux pipelines

central/processbaseline/evaluator/bench_test.go, central/processbaseline/evaluator/evaluator_impl.go, central/processbaseline/evaluator/evaluator_integration_test.go, central/processbaseline/evaluator/evaluator_test.go, central/processindicator/datastore/datastore.go, central/processindicator/datastore/datastore_impl.go, central/processindicator/datastore/mocks/datastore.go, pkg/search/postgres/select.go
The current `GetProcessIndicatorsRiskView` calls are inefficient for our use case, since we need to loop through the returned process indicators. Switching to a callback-based approach allows us to process items one by one, avoiding the need to load all objects into a slice. This reduces memory usage and lowers GC pressure.
```bash
go test -tags sql_integration -run=NO -bench=BenchmarkEvaluateBaselinesAndPersistResult  ./central/processbaseline/evaluator/. -count 6 -benchmem -benchtime 3s 
```
```
│ master-2.txt │               new.txt               │
│    sec/op    │    sec/op     vs base               │
EvaluateBaselinesAndPersistResult/100_processes_2_containers-8                  1.781m ± 32%   1.720m ± 55%        ~ (p=0.240 n=6) …
```
=> fix(risk): improve reprocess deployment risk

central/detection/lifecycle/manager_impl.go, central/pod/datastore/datastore_impl_real_test.go, central/processindicator/datastore/datastore.go, central/processindicator/datastore/datastore_impl.go, central/processindicator/datastore/mocks/datastore.go, central/processindicator/store/mocks/store.go, central/processindicator/store/store.go, central/processlisteningonport/datastore/datastore_impl_test.go
This PR changes the logic of `buildIndicatorFilter` to fetch only indicators for deployments instead and not filtering it in code. This should reduce amount of data returned by DB and reduce operations performed in walk function.
=> fix: buildIndicatorFilter query for deployments

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/ViewBasedReportJobDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/AdvancedFiltersToolbar.tsx, ui/apps/platform/src/Containers/Vulnerabilities/filterChipDescriptor.ts, ui/apps/platform/src/Containers/Vulnerabilities/filterChipDescriptors.ts, ui/apps/platform/src/Containers/Vulnerabilities/searchFilterConfig.ts
Centralized filter chip descriptors to ensure consistent display between compound search filters and view-based report filters.
**Key Changes**:
- Created `filterChipDescriptor.ts` to centralize filter chip display configuration
- Added render function to display fixable status as `"Fixable"/"Not fixable"` instead of `"true"/"false"`
- Created `viewBasedReportSearchFilterConfigs` array for report-available filters
- Updated `ViewBasedReportJobDetails` to use centralized descriptors for consistent formatting
- Refactored `AdvancedFiltersToolbar` to reuse shared descriptors instead of inline definitions
=> ROX-31118: Consistent filter chip display in Vuln Reporting

.github/CODEOWNERS, .golangci.yml, compliance/node/index/indexer.go, compliance/node/index/indexer_test.go, compliance/virtualmachines/agent/README.md, compliance/virtualmachines/agent/cmd/cmd.go, compliance/virtualmachines/agent/common/config.go, compliance/virtualmachines/agent/config/config.go, compliance/virtualmachines/agent/index/index.go, compliance/virtualmachines/agent/main.go, compliance/virtualmachines/agent/vsock/client.go, compliance/virtualmachines/agent/vsock/client_test.go
Add a standalone virtual machine agent. The agent is meant to be run by users on a kube-virt virtual machine. It then gathers index reports, and sends the index reports to the collector relay (see #16929).
To index RHEL packages, we require at least claircore `1.5.40`, which requires other changes (see https://github.com/stackrox/stackrox/pull/16944). This PR is therefore rebased onto the claircore bump.
`client_test.go` and `README` were generated with the help of claude.
I've tested that the agent produces expected `IndexReports` and sends them to the relay (https://github.com/stackrox/stackrox/pull/16929) via vsock. I set up the environment as follows:
* OpenShift ROSA cluster with one metal node.
* Enable vsock in kube-virt and on the virtualmachine (`"devices.autoattachVSOCK": …
=> ROX-29575: add virtual machine agent
