- ui/apps/platform/src/Containers/NetworkGraph/common/AdvancedFlowsFilter/AdvancedFlowsFilter.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/ClusterSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/DeploymentSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/DisplayOptionsSelect.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NamespaceSelector.tsx
An `aria-label` attribute is prerequisite for integration tests.
All of the `Select` elements have default `aria-label="Options menu"` attribute.
Although the doc page is not especially clear about which of the various props for which of the various types of `Select` element, `aria-label="Select a cluster"` did not work.
https://www.patternfly.org/v4/components/select#select
By reading PatternFly Select.tsx file, verifying the change, and also finding the corresponding props in collections:
1. AdvancedFlowsFilter.tsx
* Outer element **residue** needs label from someone who knows more than me
* Inner element `toggleAriaLabel="Select ports"`
2. ClusterSelector.tsx `toggleAriaLabel="Select a cluster"`
3. DeploymentSelector.tsx `toggleAriaLabel="Select deployments"`
4. …
> Specify toggleAriaLabel prop for Select elements in Network Graph

- .github/actions/cache-go-dependencies/action.yaml
Avoid deprecated constructs in GHA
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Don't use deprecated GHA output

- operator/pkg/central/extensions/common.go
- operator/pkg/central/extensions/reconcile_pvc.go
- operator/pkg/central/extensions/reconcile_pvc_test.go
- operator/tests/central/basic/10-assert.yaml
Each instance of the `ReconcilePVCExtension` should only care about the PVC resources which match its target (where matching is in broad sense, for backwards compatibility reasons). This was mostly true, except for the `handleDelete()` case, which lead to unintended removal of owner references from **all owned** PVCs.
See [more detailed description in the ticket](https://issues.redhat.com/browse/ROX-14335?focusedCommentId=21590623&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21590623).
This changes:
- `handleDelete()` to ignore PVCs that are not for the current target,
- adds a unit test and a kuttl test for this case
- improves logging a bit
- fixes some typos
This definitely requires some user-facing communication, since some repair actions would be …
> ROX-14335: PVC extension should not touch PVCs that are not its target

- ui/apps/platform/src/Containers/Network/Header/TimeWindowSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/TimeWindowSelector.tsx
- ui/apps/platform/src/constants/timeWindows.ts
This includes two related items:
1. Adding and wiring up a PF version of the Time Window dropdown to the new Network Graph toolbar
2. Adding the Last Updated time to the right side of the toolbar, as per the new mock, https://docs.google.com/presentation/d/1DdKZ0PoLk6yDyV9vFM4Q-HpB0N_lXwJ53G-CYAc56Sc/edit#slide=id.g1669bc43c7d_13_62 
Default time window
Changing to a new value
> ROX-14372: Add PF version of time window dropdown

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTable.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTableHeaderText.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaselines.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaselinesSimulated.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/SimulateBaselinesButton.tsx
- ui/apps/platform/src/Containers/NetworkGraph/hooks/useSimulation.ts
- ui/apps/platform/src/Containers/NetworkGraph/simulation/SimulationFrame.tsx
- ui/apps/platform/src/Containers/NetworkGraph/utils/getSimulation.ts
This PR starts off the addition of the baseline simulation in the network graph. I've divided the work further so we can merge things in iteratively
> ROX-14347: Adding baseline simulation to new network graph

- operator/tests/common/upgrade-assert.envsubst.yaml
- operator/tests/upgrade/upgrade/20-upgrade-operator.yaml
Followup to #4508 that tests the manual remediation instructions.
In a separate PR at least for now, since this can be iterated on as a followup from the fix.
Actually the remediation commands are a no-op, because 3.74.x was still not tagged, and thus the "previous version" is still considered to be 3.72 which does not have the bug. But this will change as soon as the 3.74.x tag is created.
The last two checkboxes are being discussed in the ticket.
Ran the script manually and inspected output.
Otherwise CI plus the check mentioned above should be sufficient.
> ROX-14335: Remediate bug and verify in operator upgrade test

- deploy/common/k8sbased.sh
- qa-tests-backend/scripts/lib.sh
- qa-tests-backend/scripts/run-compatibility.sh
- qa-tests-backend/scripts/run-part-1.sh
- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
- scripts/ci/clair/deploy.sh
- tests/e2e/lib.sh
We've had CI Failures like [this](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-nightlies-osd-gcp-qa-e2e-tests/1615576493528715264), because the bundle installation method tries to install a PodSecurityPolicy for central by default if the env variable `POD_SECURITY_POLICIES` is not set or set to `true`. PodSecurityPolicy was removed from Kubernetes 1.25 and upwards, which is why the test setup is failing.
This PR changes the deploy scripts to query the Kubernetes server version and set `POD_SECURITY_POLICIES` to false if it detects a version >= 1.25.
- ~[ ] Documented user facing changes (create PR …
> ROX-14427: set PSPs for CI to false for k8s version 1.25 and higher

- operator/Makefile
- operator/README.md
- operator/bundle.Dockerfile
- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/bundle/metadata/annotations.yaml
- operator/bundle/tests/scorecard/config.yaml
- operator/config/default/kustomization.yaml
- operator/config/default/manager_auth_proxy_patch.yaml
- operator/config/scorecard-versioned/kustomization.yaml
Upgrade Operator SDK from 1.20.1 to 1.24.1 and apply necessary migrations according to [Upgrade SDK Version](https://sdk.operatorframework.io/docs/upgrading-sdk-version/)
This includes:
- replace `go-get-tool` with `go install`
- download `kustomize` binaries directly
- bump `kube-rbac-proxy`
- e.t.c.
**Note1: Upgrading to 1.25 and 1.26 is blocked by 1.19 golang version**
**Note2: controller-gen version is still ahead. controller-gen will be update to v0.10.0 only in 1.26 SDK version**
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into …
> ROX-13689: Bump operator SDK to 1.24.1 version

- central/policycategoryedge/store/postgres/store.go
- tools/generate-helpers/pg-table-bindings/list.go
When running `make go-generated-srcs`, I encountered an error:
```
make go-generated-srcs
...
central/policycategoryedge/search/searcher_impl.go
central/policycategoryedge/search/mocks/searcher.go
central/policycategoryedge/store/store.go
central/policycategoryedge/store/postgres/gen.go
pg-table-bindings-wrapper --get-all-func --type=storage.PolicyCategoryEdge --table=policy_category_edges --search-category POLICY_CATEGORY_EDGE --references=policies:storage.Policy,policy_categories:storage.PolicyCategory --search-scope POLICY_CATEGORY_EDGE,POLICY_CATEGORIES
2023-01-25 14:20:44 Generating for storage.PolicyCategoryEdge
Error: template: store.go:74:19: executing "store.go" at <.Obj.IsGloballyScoped>: error calling IsGloballyScoped: unknown resource: PolicyCategoryEdge. Please add the …
```
> Fix make go-generated-srcs

- CHANGELOG.md
- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
This reverts commit 821a3041f909ebc58fe30215f3bf3f97006310df (https://github.com/stackrox/stackrox/pull/4366) because we're not making the channel change in 3.74.
See https://srox.slack.com/archives/C3W3U0RGW/p1674581968487489
Won't do the following as this is "just" a revert:
* Nothing except of CI.
> ROX-14280: Revert "Describe the `stable` operator channel"

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphContainer.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/topology.type.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/modelUtils.tsx
as it states in the title --
* refactored the data filtering/modifying to be in its own layer (`NetworkGraphContainer`)
* also separated out `TopologyComponent` into its own file and simplified it so that it simply renders whatever the model it is given
* this greatly improves performance of toggling display options when a side panel is open (you should not notice any performance issues)
* display options should persist between selecting a node on the graph and also between edge states
> Network Graph PF edge perf improvement and refactor

- ui/apps/platform/src/Containers/NetworkGraph/api/useFetchSimulatedBaselines.ts
- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTable.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaselinesSimulated.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/flow.type.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.ts
- ui/apps/platform/src/types/networkPolicyService.ts
This PR adds functionality to get simulated baselines. Baselines that are added are marked as green and have a +. Baselines that are removed are marked as red and have a -. I also added filters.
> ROX-14514: Add functionality to get simulated baselines

- central/graphql/resolvers/node_scan_benchmark_test.go
- central/graphql/resolvers/node_scan_test.go
Some test helper function names were changed by a different PR. It caused unit tests to fail after PR [#2926](https://github.com/stackrox/stackrox/pull/2926) merged. Changes in this PR should fix the tests.
> Fix incorrect call to a changed function in tests

- tests/admctrl_configmap_test.go
Per title. TestAdmissionControllerConfigMap is broken.
> ROX-14495: Skip broken test

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphContainer.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/api/useFetchNetworkFlows.ts
- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTable.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.ts
This PR shows the extraneous flows in the flows table when we switch the view using the selector. The extraneous egress/ingress flows will show up in the table as the last row
https://user-images.githubusercontent.com/4805485/214653717-9debc9c8-3890-4c3c-bc9d-29a3b9033287.mov
> ROX-14555: Show extraneous flows and allowed ingress/egress flows

- .github/workflows/build.yaml
- .github/workflows/style.yaml
- .github/workflows/unit-tests.yaml
- .openshift-ci/Dockerfile.build_root
- .openshift-ci/build/Dockerfile.build-central-db-bundle
- .openshift-ci/build/Dockerfile.build-main-and-bundle
- .openshift-ci/build/Dockerfile.build-operator-artifacts
- BUILD_IMAGE_VERSION
- scale/signatures/deploy.yaml
- tests/e2e/run-e2e-tests.sh
The goal is to pick up a new `oc`. It also happens to pick up newer `git` - a fix for its new checks was merged in #4459 
The custom-built ARM image mentioned in the `Makefile` is not bumped. See https://issues.redhat.com/browse/ROX-12064
CI should suffice.
> ROX-14352: Bump CI images to latest version.

- pkg/declarativeconfig/uuid.go
- pkg/declarativeconfig/uuid_test.go
This PR is a pre-factor for the declarative configuration project.
For declarative configuration, we allow users to specify resources in a declarative manner by providing YAML configuration via config map / secret mounts within central.
The YAML-based configuration will not be using any UUIDs, but instead will be uniquely identified by their name.
To support this, we need to make sure we map those names internally to UUIDs, since datastores typically work with UUIDs as unique identifiers, as well as make sure that we will be able to create the UUIDs deterministic, since the same _named declarative configuration_ should only create _a single set of resources_.
For this, we re-use the `uuid.NewV5FromNonUUID`, which under hood are `v5 UUIDs`, which are meant for generating UUIDs from names …
> ROX-14229: Deterministic UUIDs for declarative config resources

- .openshift-ci/clusters.py
- scripts/ci/gke.sh
Cluster create is timing out. e.g.:
```
Creating cluster rox-ci-nongroovy-test-161829777865441689 in us-central1-c...
INFO: Wed Jan 25 17:51:57 UTC 2023: gcloud command timed out. Checking to see if cluster is still creating
INFO: Wed Jan 25 17:52:24 UTC 2023: Waiting for cluster rox-ci-nongroovy-test-161829777865441689 in us-central1-c to move to running state (wait 1 of 60)
INFO: Wed Jan 25 17:52:45 UTC 2023: Waiting for cluster rox-ci-nongroovy-test-161829777865441689 in us-central1-c to move to running state (wait 2 of 60)
INFO: Wed Jan 25 17:53:06 UTC 2023: Waiting for cluster rox-ci-nongroovy-test-161829777865441689 in us-central1-c to move to running state (wait 3 of 60)
INFO: Wed Jan 25 17:53:28 UTC 2023: Waiting for cluster rox-ci-nongroovy-test-161829777865441689 in …
```
> CI: Bump GKE timeout

- ui/apps/platform/src/Containers/Collections/CollectionForm.css
- ui/apps/platform/src/Containers/Collections/CollectionForm.tsx
Two minor UI tweaks:
1. Fixes the misaligned "expandable section icon" in production builds
2. Ensures the Save/Cancel button section of the collection form is always pinned at the bottom of the page
Icon before:
Icon after:
Button toolbar before:
Button toolbar after:
> Collections UI minor fixes

- pkg/declarativeconfig/role.go
- pkg/declarativeconfig/role_test.go
Go struct which will be used for YAML -> Go struct transformation of declarative Role.
1. Unit test added
> ROX-14137: Role declarative config struct

- ui/apps/platform/src/index.tsx
Hat-tip to Mark for tracking down this solution to the multiple-MobX error in the browser console.
Without this code, error
With this code, no error
> Fix error message about multiple mobx instances

- qa-tests-backend/src/main/groovy/services/CollectionsService.groovy
- qa-tests-backend/src/main/groovy/services/VulnReportService.groovy
- qa-tests-backend/src/main/groovy/util/MailServer.groovy
- qa-tests-backend/src/test/groovy/VulnReportingTest.groovy
- tests/e2e/lib.sh
Adds a simple E2E test that tests that vuln reports generates a report given a collection and sends an email with it the report attached as a CVE. For now it just verifies the email was sent and has an attachment to keep the BAT tests simple and fast. Another test (or more) can be added later that'll run only in the nightlies which would actually parse the CSV.
this is a test
In addition to reviewing your code, reviewers …
> ROX-12632: Add vulnerability report with collections E2E test

- pkg/declarativeconfig/permission_set.go
- pkg/declarativeconfig/permission_set_test.go
This solution is based on re-using existing proto enums within new Go structs.
Alternatives:
1. Introduce a new struct replacing `storage.Access`proto enum within this Go struct + conversion function
2. Convert from YAML to JSON first, then to proto
screenshots.
> ROX-14137: Permission Set declarative config Go struct

- operator/tests/central/basic/40-assert.yaml
- operator/tests/central/basic/50-assert.yaml
- operator/tests/central/basic/61-assert.yaml
- operator/tests/central/basic/62-assert.yaml
- operator/tests/central/basic/76-assert.yaml
- operator/tests/central/basic/80-assert.yaml
- operator/tests/central/basic/81-assert.yaml
Operator test [recently](https://github.com/stackrox/stackrox/commit/82a3731cef4f7a499b94902a9d263090039f1e86) started failing on the step that enables telemetry. @theencee noticed this on [his PR](https://github.com/stackrox/stackrox/commit/c78a8d60490ec11dc192be9e8da5e58638babfdf) and was kind to look into the cause and ping me.
I suspect the issue is actually in an earlier step which ignores the error, and the telemetry step is the first in line which does assert the central pod health and therefore fails. However the failure is not very informative, because we do not collect pod logs in that step.
So this change:
1. asserts deployment health in step 76 (`switch-central-db-to-internal`, which is the one I suspect to be the culprit)
2. collect pod logs in every step which asserts …
> Improve operator basic central test.

- Makefile
Recent `git` does not like the repository to be owned by a different user.
To solve this
- pass --user to `docker run`
- make sure the go cache volume source directory is created as the current user before running docker
I think I even managed to find a simple way to fix permissions of existing/newly created volumes. This is especially important on macs, where the volume does not map to an actual directory on disk and cannot be solved by an `rm -rf`.
Ran `make clean; rmdir linux-gocache; make sensor-build-dockerized; make image` successfully.
> ROX-14352: Run dockerized builds as current user, rather than root, to please git.

- central/role/mapper/store_based_mapper_impl.go
- central/role/mapper/store_based_mapper_impl_test.go
- central/role/mapper/telemetry.go
Try to `GetUser` before adding it to the tenant group. This should avoid sending duplicates of `Group` messages to segment.
Local testing by restarting the sensor.
> ROX-14339: Telemetry: Try to get user before adding it to the tenant group

- central/declarativeconfig/manager.go
- central/declarativeconfig/manager_impl.go
- central/declarativeconfig/singleton.go
- central/declarativeconfig/watch_handler.go
- central/main.go
This PR is a pre-factor for future PRs for the declarative config feature.
It will create a coarse structure of a manager that starts a watch on a specific directory.
Additionally, the watch will be conditionally started in the main routine _iff_ the feature flag is enabled.
In future PRs, the manager implementation will be expanded to also cover the reading file contents from the directory, marshalling these YAMLs to structs, transforming the structs to proto messages, and reconciling the proto messages within the stores.
> ROX-14428: Create stub manager for declarative configuration

- ui/apps/platform/src/Containers/NetworkGraph/components/DeploymentSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NamespaceSelector.tsx
This fixes a workflow considered a blocker.
Look ma, open menus!
https://user-images.githubusercontent.com/715729/214975381-794b3c16-04ac-4cd5-8d82-f401df004751.mov
> ROX-14583: Make NS and Deployment dropdowns stay open

- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkPolicies.tsx
- ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/topology.type.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/modelUtils.tsx
This PR shows the network policies for deployments and namespaces
> ROX-14563: Show network policies data in the deployments side panel

- ui/apps/platform/src/Containers/NetworkGraph/api/useFetchBaselineNetworkPolicy.ts
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaselines.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
This PR adds the "Download baseline as network policy button" as discussed in this conversation https://srox.slack.com/archives/C02PA0VVB46/p1674764670668319
This will download the network policy YAML instead of going into the simulation mode. Since UX needs time to discuss that flow, this is our temporary solution.
https://user-images.githubusercontent.com/4805485/215165800-0a67e705-712b-485d-bd21-9fb699ebe46e.mov
> ROX-14568: Add download baseline as network policy button

- central/cluster/datastore/telemetry.go
- central/main.go
- central/role/mapper/telemetry.go
- pkg/telemetry/phonehome/client_config.go
- pkg/telemetry/phonehome/gatherer.go
- pkg/telemetry/phonehome/gatherer_test.go
- pkg/telemetry/phonehome/interceptor.go
- pkg/telemetry/phonehome/interceptor_test.go
- pkg/telemetry/phonehome/mocks/telemeter.go
- pkg/telemetry/phonehome/segment/segment.go
- pkg/telemetry/phonehome/segment/segment_test.go
- pkg/telemetry/phonehome/telemeter.go
* Add `*UserAs` methods to `Telemeter` interface, to alter UserID and/or set device context for a particular call. This way a central could Identify a secured cluster from its name.
```json
{
"context": {
"Client ID": "6393af03-28ac-4f5f-bf35-b0d10be9f99f",
"Client Name": "Central",
"library": {
}
},
"messageId": "97377717-545e-4a41-bbe4-01d29a536c43",
"originalTimestamp": "2023-01-23T17:51:39.924036459Z",
"receivedAt": "2023-01-23T17:52:40.666Z",
"sentAt": "2023-01-23T17:52:39.745Z",
"timestamp": "2023-01-23T17:51:40.844Z",
"traits": {
"Auth Providers": null,
"Central version": "3.73.x-505-g211a07a034-dirty",
"Chart version": "73.0.505-g211a07a034-dirty",
"Kind": "Central",
"Kubernetes version": "v1.25.3",
"Orchestrator": …
```
> ROX-14487: Improvements of Group and Identify messages

- ui/apps/platform/cypress/integration/collections/deploymentMatching.test.js
- ui/apps/platform/src/Containers/Collections/CollectionResults.tsx
Simplifies the selector assertions for deployment matching tests that were causing test flakes.
Additionally, this removes a couple of pieces of the code that were redundant in the collection results sidebar.
Verify CI results.
> Re-enable collections e2e test for deployment matching

- central/telemetry/centralclient/instance_config.go
- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- operator/tests/central/basic/80-assert.yaml
- operator/tests/central/basic/81-assert.yaml
- pkg/env/openshift.go
- pkg/helm/charts/tests/centralservices/testdata/helmtest/central.test.yaml
Set the `ROX_OPENSHIFT_API` environment variable to the central deployment for Openshift installations, so that the telemetry code could identify Openshift as the platform on which the central is running:
https://github.com/stackrox/stackrox/blob/8f9fe014022f45953861e70ef55e4bcbc6c741dd/pkg/env/openshift.go#L5-L6
https://github.com/stackrox/stackrox/blob/8f9fe014022f45953861e70ef55e4bcbc6c741dd/central/telemetry/centralclient/instance_config.go#L49-L51
```
$ kubectl describe deployment central
...
Environment:                                                                                                  
ROX_NAMESPACE:            (v1:metadata.namespace)
ROX_OFFLINE_MODE:        false …
```
> ROX-14101: Detect central installed on Openshift

- ui/apps/platform/src/Containers/Collections/CollectionForm.tsx
Adds client side validation for leading and trailing spaces in collection names, as well as in label based rules.
Test that entering a leading or trailing space in the collection name displays an inline error, and disables the form submit button.
Test that entering a leading or trailing space in a label rule displays an invalid field, and disables the form submit button.
> Disallow leading and trailing spaces in collection names

- ui/apps/platform/cypress/integration/collections/deploymentMatching.test.js
- ui/apps/platform/src/Components/PatternFly/BacklogListSelector.tsx
- ui/apps/platform/src/Containers/Collections/CollectionAttacher.tsx
- ui/apps/platform/src/Containers/Collections/hooks/useEmbeddedCollections.ts
A logic error in when the embedded collection data was filtered was leading to cases where the client side form state would be invalid.
If the user took the following steps:
1. Attached a collection
2. Filtered the available collection list in a way that the first collection was not visible
3. Attached a second collection, and cleared the search filter
This would result in both of the collections being displayed in the "attached" section of the UI, but the underlying form data would only contain the second collection, which impacted dry-run requests as well as saving the collection.
The fix was to move the search filtering from the `useEmbeddedCollections` hook that fetches the data to the component that displayed the data via a filtering callback.
- Cover this case in e2e tests
If any of …
> Fix inconsistent data state after using embedded collection filter

- ui/apps/platform/src/Components/DeploymentPortConfig.tsx
This PR fixes the following issue in the new network graph:
* When I click on a specific deployment, details popup on the right. I scrolled down and found Port configurations. I see two boxes I can expand, but when collapsed, they seem blank
> fix: network graph bug - port configuration text fix

- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
This PR shows the network policy rules for a deployment
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~
> ROX-13418: Use real data for network policy rules section

- ui/apps/platform/src/Components/Menu.tsx
- ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.js
Implementation for Version 1 from this Jira comment,
https://issues.redhat.com/browse/ROX-13325?focusedCommentId=21420775&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21420775
Link used for docs from this comment,
https://issues.redhat.com/browse/ROX-13325?focusedCommentId=21608282&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21608282
Note: I tried re-styling the PF toggle to look more like the classic StackRox buttons, but that gave it more of an "uncanny valley" look than it helped, so I left the default PatternFly style for everything.
(I tried to use the Menu PatternFly component, as having better semantics and functionality, but it turned out to have limitations, including not being able to open a link in a new …
> ROX-14240: Implement dropdown for Add Cluster options

- central/debug/service/db_diagnostics.go
- central/debug/service/db_diagnostics_test.go
- central/debug/service/service.go
- pkg/env/central_diagnostics.go
Added some information for central-db to the diagnostic bundle.  This will be populated if we are pulling the diagnostics for central and of course in Postgres mode.  Meaning this will not be pulled for ACSCS, which makes sense as we should know what that configuration is.  The new file in the bundle will be `central-db.json`.  Example contents:
```
{
"Database": "PostgresDB",
"DatabaseClientVersion": "pg_dump (PostgreSQL) 13.9",
"DatabaseServerVersion": "13.9",
"DatabaseExtensions": [
{
"ExtensionName": "plpgsql",
"ExtensionVersion": "1.0"
},
{
"ExtensionName": "pg_stat_statements",
"ExtensionVersion": "1.8"
}
],
"DatabaseConnectString": "host=central-db.stackrox.svc port=5432 user=postgres sslmode=verify-full sslrootcert=/run/secrets/stackrox.io/certs/ca.pem statement_timeout=60000 …
```
> Dashrews/ROX-14169 add central-db configuration information to diagnostic bundle

- ui/apps/platform/src/Containers/VulnMgmt/Reports/Form/CollectionSelection.tsx
Bug discovered by Van during team testing.
Go to VM reporting and configure a report. Before saving click into the typeahead area of the collections dropdown and then click back out. It is not necessary to enter a search filter, but that also will reproduce the issue. Saving the report gives an error:
```
Failure
Collection <collection_name> not found. Error: %!s(<nil>): not found
```
This error is from the BE due to the FE sending the collection **name** and not the collection id as the `scopeId` parameter.
PatternFly's `<Select>` component has an `onSelect` callback prop that fires when the value of the dropdown is changed. However this callback also fires when all of the following are true:
- the user is toggling the dropdown closed
- the `isInputValuePersisted` prop is set to true
- …
> Fix collection dropdown in VM reporting to always use id as scopeId parameter

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#12-4-1
* Upgraded ua-parser-js from 0.7.24 to 0.7.33 to address security vulnerability where crafting a very-very-long user-agent string with specific pattern, an attacker can turn the script to get stuck processing for a very long time which results in a denial of service (DoS) condition.
> Update cypress 12.4.1 devDependencies in ui

- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/cidr/CidrBlockSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTable.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaselines.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaselinesSimulated.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/external/ExternalGroupSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/externalEntities/ExternalEntitiesSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceDeployments.tsx
- ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceSideBar.tsx
This PR fixes two issues:
1. We want to show a yellow indicator when there is an anomalous flow that is not external and a red indicator when it is external
2. We want to be able to click on the table entity names to simulate clicking that entity node
https://user-images.githubusercontent.com/4805485/215576170-126cf14b-5ba9-40f8-b439-d4001dd4cf9a.mov
> Network Graph Bug Fixes for Monday

- central/cve/cluster/datastoretest/datastore_sac_test.go
It seems a data race was detected in some dackbox SAC tests.
The resolution here is to alter the tests to ensure the data is indexed before its cleanup is attempted.
The change at hand here is a fix of the existing tests. No functional code change, so no new test.
> ROX-14579: Ensure ClusterCVE SAC tests wait for indexing of injected data before test cleanup

- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ClairIntegrationForm.tsx
Specify margin-bottom to separate from **Integration name** with same spacing as form elements.
> ROX-13684: Add deprecation warning to Clair v2 integration form

- .gitmodules
Update docs branch to 3.73.2 https://github.com/openshift/openshift-docs/commit/d2bac2dd59c40862fff7fafc340ebe2070ffdbd5
It should be done by cut rc step but it was recently removed and I can't use older version as it has issues with tags. 
> ERROR: Expected docs/content submodule to point to branch rhacs-docs-3.73.2, got: rhacs-docs-3.73.1
> Update docs to 3.73.2

- ui/apps/platform/src/Containers/VulnMgmt/Reports/VulnMgmtReportForm.tsx
This fixes a bug where a vm report is unable to be changed from "monthly" to "weekly" due to multiple mutually-exclusive fields being set on the JSON request object at the same time. The backend proto only supports one of the fields, and will default to using `daysOfMonth` if both it and `daysOfWeek` are set. If this happens when the intervalType is "WEEKLY", the BE will throw an error.
Create a VM report config and save it with a "Monthly" interval, setting any value for the days.
Reload this config in edit mode and update the interval to "Weekly", verifying that it saves correctly.
> Fix VM reporting to allow changing between weekly and monthly intervals

- pkg/declarativeconfig/access_scope.go
- pkg/declarativeconfig/access_scope_test.go
Go struct which will be used for YAML -> Go struct transformation of declarative Access Scope.
Unit test added
> ROX-14137: access scope YAML format for declarative config

- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
adding unselect (close sidebar) function to same node click to mitigate confusion on how to unselect a node & for consistency between the visuals (highlighted node) on the graph vs the side panel state.
everything should still work the same otherwise
> Network graph: Patternfly -- adding unselect on same node click

- ui/apps/platform/src/Containers/NetworkGraph/utils/modelUtils.tsx
as the title states -- now it should actually match up w the policy tab in the deployment side panel
> Network graph: PF - tightening policy status badge logic

- CHANGELOG.md
- central/debug/service/service.go
- central/graphql/resolvers/resolver.go
- central/reportconfigurations/service/service_impl.go
- central/reports/service/service_impl.go
- central/role/datastore/datastore_impl.go
- central/role/datastore/datastore_test.go
- central/role/datastore/permissionset_ids.go
- central/role/datastore/singleton.go
- central/role/datastore/telemetry.go
- central/role/default.go
- central/role/resources/list.go
- central/role/service/service_impl.go
- tools/generate-helpers/pg-table-bindings/list.go
- ui/apps/platform/src/Containers/AccessControl/AccessControl.tsx
As part of the effort to simplify the permission management in the product, the `Role` resource will be grouped with the `Access` one.
This change announces the grouping and flags the code portions to alter in order to make this change happen.
Mostly comment addition in the code.
> Prepare Role resource grouping with Access

- image/templates/helm/stackrox-central/config/centraldb/postgresql.conf.default
There are background processes, things like parallel workers, and potentially psql. Central will generate 1-90 conns, but this will help ensure that we don't hit strange overheads without much more additional expected overhead on Postgres
``` 
3309562 | postgres 2023-01-30 18:16:28.881186+00 | 2023-01-30 18:16:28.878071+00 | 2023-01-30 18:16:28.878805+00 | 2023-01-30 18:16:28.886326+00 | active  | 157587413 | select distinct(deployments.Id::text), deployments | parallel worker
```
Straightforward and found this issue while testing scale
> Increase default max conns to 200 to better support background processes

- ui/apps/platform/cypress/integration/vulnmanagement/reporting/reportingForm.test.js
Fixes broken VM reporting config e2e test on master by making sure to delete the report config _before_ the collection during cleanup.
As a bonus, I've added a check in the test that a collection cannot be deleted when in use by a report config.
Local Cypress testing
Awaiting CI results
> ROX-14659 Update Cypress collection test to delete report config before collection

- central/image/datastore/store/postgres/store.go
- central/node/datastore/store/postgres/store.go
The issue not reproducible manually. Remove the dev build panic that I had added to the surface unexpected case and instead log to make CI less noisy until I determine the root cause of the issue.
> Remove the dev panic; continue logging

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css
- ui/apps/platform/src/Containers/NetworkGraph/components/NamespaceSelector.tsx
From all-hands bug bash:
> If a cluster is empty (no namespaces) there should be something to let the user realize that. Currently Namespaces will simply not have any dropdown which may feel like it’s stuck or something.
> Consider feedback text appearing in the “Namespaces” selection, or some other form of feedback
Decision: show ‘No namespaces’ when the dropdown is disabled so it is obvious why disabled
When no cluster selected, unsullied state
Cluster with no namespaces is selected -> Namespace dropdown shows why it is disabled
Switch to a cluster with namespaces -> back to normal
Bonus: restore grayed background for disabled checkboxes
(which had been whited out by Tailwind reset)
> Indicate when select cluster has no namespaces

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
The bug report said this happened only when changing to a cluster that had no namespaces; however, it actually happens on any namespace change.
Manual testing
> Clear the models when cluster selection changes

- ui/apps/platform/src/css/trumps.css
Fix unintended side effect of #2611
stagingdb with `list-style: decimal;`
local with `list-style: decimal;`
local with `list-style: none;`
> ROX-14670: Remove shadow number on Policy Wizard steps

- ui/apps/platform/src/Containers/Policies/policies.utils.ts
Trim in `getServerPolicy` function which is called:
* Before POST /v1/dryrunjub request in Review Policy step.
* Before POST or PUT /v1/policies request on click Save button.
1. Possibly add frontend validation for `name` length and allowed characters.
2. Policy criteria `value` deserves extra special care to make sure it does not regress.
3. Policy scope `key` and `value` of label deserve extra special care to make sure it does not regress.
1. Temporary console.log to compare client and server policy.
2. See presence or absence of spaces:
* in payload of POST /v1/policies/dryrunjob request at Step 5
* in response of GET /v1/policies/id after save
> ROX-13754: Trim fields in Policy Wizard form before dryrun and save

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx
Res ipsa loquitur
1. There is a minimum width to the resizeable side panel before the layout and content within it start to look broken.
2. The sidepanel space is fairly limited. To optimize readability, it would be valuable to minimize the space used by the kabob menu as much as possible so that other columns do not become squished / truncated. 
3. The header used in the Details section is the wrong size and inconsistent with the Flows and baseline panelsl. It should use the pf-u-font-size-lg class
No smaller than this
Also, extra whitespace around kebab minimized, while still allowing some padding for accessible click target
Smaller subhead font size
> Set min width for new network drawer

- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
Update the DockerHub images to Quay.io images, as these tests may be failing due to DockerHub rate-limiting. The purpose of these tests is to ensure the "scan time" is not "null", so it really is not important which images are used.
CI
> ROX-14619: fix metadata retrieval errors in scan time test

- pkg/env/sensor.go
- sensor/kubernetes/eventpipeline/pipeline.go
- sensor/kubernetes/eventpipeline/resolver/resolver.go
- sensor/kubernetes/eventpipeline/resolver/resolver_test.go
- sensor/kubernetes/sensor/options.go
- sensor/kubernetes/sensor/sensor.go
This PR moves the `eventPipeline`'s queue sizes initialization to the `CreateOptions`.
* The CI should be enough
> ROX-13413 move the eventPipeline's queue size initialization to CreateOptions

- ui/apps/platform/src/Containers/MainPage/Header/CLIDownloadMenu.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step2/DownloadCLIDropdown.tsx
Simply used find feature to locate where Windows x86_64 was mentioned and added similar items for other two arches.
`roxctl` binaries already exist in the image:
```bash
$ docker run --rm -it --entrypoint=/bin/bash quay.io/stackrox-io/main:3.73.x-565-gd8d7f7074b
bash-4.4$ ls assets/downloads/cli/
roxctl-darwin-amd64  roxctl-linux  roxctl-linux-amd64  roxctl-linux-ppc64le  roxctl-linux-s390x  roxctl-windows-amd64.exe
```
Won't do these:
works and files are reported as having correct arch
also works and files have proper arch
> ROX-13423: Add UI download items for roxctl for IBM P and Z

- ui/apps/platform/src/Containers/PolicyCategories/CreatePolicyCategoryModal.tsx
- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesPage.tsx
- ui/apps/platform/src/Containers/PolicyCategories/PolicyCategorySidePanel.tsx
- ui/apps/platform/src/css/trumps.css
Fix a recent regression and mitigate confusion from interactive behavior which was by design.
1. When you click a system-default category in the list, nothing happens. Although this is by design, it needs disabled appearance in contrast to customer-defined categories.
2. After you click a customer-defined category, it opens in the side panel.
* The **Save** button is disabled **until** you make a change.
* Although it becomes enabled **if** you make a change, it is an implicit **edit** mode.
3. Immediately after you create a customer-defined category, it opens in the side panel. Because of disabled **Save** button in problem 2, it looks like creation of the category via a modal has not yet occurred.
1. System-default categories had visual distinction from customer-defined categories via …
> ROX-14647-14671: Reduce confusion about policy categories

- sensor/kubernetes/eventpipeline/component/message.go
The `MergeResourceEvents` has a bug where some values could get overridden  incorrectly.
* CI
> Fix bug where values got overridden incorrectly

- ui/apps/platform/src/Components/PatternFly/SeverityLabelsList.tsx
- ui/apps/platform/src/Containers/Collections/CollectionForm.tsx
- ui/apps/platform/src/Containers/Collections/RuleSelector/ByLabelSelector.tsx
- ui/apps/platform/src/Containers/Collections/RuleSelector/ByNameSelector.tsx
- ui/apps/platform/src/Containers/Collections/RuleSelector/RuleSelector.css
Note: this is a low risk nice-to-have for 3.74 release, but also relatively low priority.
Adds inline error message to collection form fields that give more information on why the field is in an error state. This wraps existing TextInputs with FormGroups in order to take advantage of the inline error messages provided by the `helperTextInvalid` prop.
Also includes another minor UI fix for the VM report page. The severity labels were all set to red, this updates them to be the correct colors used elsewhere in the app.
On the collection form, add a "by name" rule and leave the value empty:
Enter a value, and then add another rule line. The second line should be the one containing the error. The error should also apply if the field is set to …
> ROX-14657 Add inline errors for collection form fields

- ui/apps/platform/src/Containers/Collections/CollectionForm.tsx
- ui/apps/platform/src/Containers/Collections/errorUtils.ts
Updates the FE check to match the new BE error message.
Additionally adds `<` and `>` as supported characters for collection names, as requested by @charmik-redhat due to these characters existing in migrated access scopes.
> Update front end check for regex rule message

- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/constants/useCaseTypes.js
- ui/apps/platform/src/messages/useCase.js
- ui/apps/platform/src/routePaths.js
* adding proper page titles to NG 2.0
* going to a namespace in the NG and hitting refresh should not show `undefined` momentarily in the page title
* going to the NG and refreshing the page (on an unselected state) should not show `[object Object]` in the page title
* clicking on `External to cluster` group node in the NG should now show `https://localhost:3000/main/network-graph/external/External%20to%20cluster?s[Cluster]=production&s[Namespace][0]=stackrox`
> Network graph: PF - External to cluster url and page title fixes

- ui/apps/platform/src/Containers/VulnMgmt/Entity/TableWidgetFixableCves.js
- ui/apps/platform/src/Containers/VulnMgmt/VulnMgmtComponents/FixableCveExportButton.js
- ui/apps/platform/src/services/VulnerabilitiesService.js
Earlier work to vary the CSV export of CVEs by type for Postgres missed passing down the type to the export functionality fo the Fixable CVE tables in the Findings sections of individual entities.
1. One change passes that CVE type down when Postgres is enabled.
2. Another change adds a fallback when Postgres is not enabled, so that the best approximate CVE_Type filter is added for an individual entity when exporting. (Note, the non-Postgres API does not support multiple filter values, so Cluster export will just get image CVEs. Asking for an API improvement for a datastore that will be removed in 9 weeks is not worth the effort.)
Manually testing on:
1. Postgres (stagingdb)
2. Non-Postgres (staging)
> FOX-14426: Fix CVE exports in Findings sections

- ui/apps/platform/src/Containers/MainPage/AnnouncementBanner.tsx
- ui/apps/platform/src/Containers/MainPage/MainPage.tsx
This adds a dismissible announcement banner to indicate 4.0.0 will be our next version and Postgres will be used. The dismissible aspect will be kept in local storage.
Manual testing performed
Alternative dismiss button
> ROX-14642: Add dismissible postgres announcement banner

- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
the current experience causes the layout to be merged oddly on edge state change:
Before:
* active state:
* <img width="1214" alt="image" src="https://user-images.githubusercontent.com/10412893/216143154-8ed08b3b-388c-41f6-9d29-7a3f383fca07.png">
* changing to extraneous state:
* <img width="1215" alt="image" src="https://user-images.githubusercontent.com/10412893/216143251-b3b8b272-9644-4104-97c1-607449ef7531.png">
After:
* active state:
* <img width="1217" alt="image" src="https://user-images.githubusercontent.com/10412893/216143366-a757709f-ed8a-449b-ba08-e36c7f4cec97.png">
* changing to extraneous state:
* <img width="1215" alt="image" src="https://user-images.githubusercontent.com/10412893/216143439-bebf5ff4-015a-4f88-9e97-e61e39f458a2.png">
everything else should work as expected …
> Network graph: PF - adding reset graph callback for smooth edge state change

- qa-tests-backend/scripts/run-part-1.sh
- qa-tests-backend/src/main/groovy/objects/ImageIntegration.groovy
- scripts/ci/clairv4/clairv4-kubernetes.yaml
Use Quay image instead of GCR, but also disable the test, as the images cannot be pulled at this time
CI
> Disable Clair v4 automated tests and move Clair to Quay

- .github/workflows/release-ci.yaml
- .github/workflows/tagged-ci.yaml
- scripts/ci/jobs/push-images.sh
- scripts/ci/lib.sh
We currently slack a notice that builds have started for RCs, releases and nightlies. This PR aims to move that task out of openshift/release. This will enable the removal of the stackrox branded builds from the openshift/release config.
- https://srox.slack.com/archives/C740BUV25/p1675274772169069
- https://github.com/stackrox/stackrox/actions/runs/4067323894/jobs/7004533567
> ROX-14632: migrate slack notice

- central/main.go
- central/telemetry/centralclient/instance_config.go
- pkg/grpc/authn/tokenbased/extractor.go
This PR makes central add the token-auth admin user ID to the tenant group in addition to the basic-auth ID.
Local testing.
> ROX-14655: Add token-based admin user ID to the tenant Group

- qa-tests-backend/src/test/groovy/VulnReportingTest.groovy
It might take some time for email to show up so add retries. 
Also add logs when cleaning up because it seems the cleanup might be failing at times
this is the test
> Add retry to vuln report E2E test when fetching email

- central/cluster/datastore/datastore_impl.go
- central/cluster/datastore/telemetry.go
Make the "Secured Cluster Registered" come from the API user who requested the cluster.
Adding a secured cluster with the local `admin` user (i.e. `sso:4df1b98c-24ed-4073-a9ad-356aec6bb62d:admin`), and central ID=`3b23fcfc-70a2-4064-9f67-20611b1457b0`:
```sh
$ print -n "3b23fcfc-70a2-4064-9f67-20611b1457b0:4df1b98c-24ed-4073-a9ad-356aec6bb62d:sso:4df1b98c-24ed-4073-a9ad-356aec6bb62d:admin" | sha256sum | xxd -r -p | base64
dn7LN2rq3t5svLVxI4j9pakjOKWoqQoapsxbqBJm6GY=
```
the following event has been tracked tracked:
```json
{
"context": {
"device": {
"id": "3b23fcfc-70a2-4064-9f67-20611b1457b0",
"type": "Central"
},
"library": {
}
},
"event": "Secured Cluster Registered",
"messageId": "40ad76ec-ea3f-4ae2-856f-7055445a9335", …
```
> Telemetry: Assign API user to the Secured Cluster Registered event

- central/featureflags/service/service_impl.go
- tests/feature_flag_test.go
Feature flag API apparently shows all values, even disabled values in the API response
screenshots.
> Always show value of the ROX_POSTGRES_DATASTORE flag in feature flag API

- central/policy/datastore/datastore_impl.go
- central/policy/datastore/datastore_impl_postgres_test.go
The Configuration Management Dashboard -> Policy Violations by severity widget stopped working with the introduction of categories. This is because the graphql API for that widget uses the `SearchRawPolicies` method in the policy datastore which had not accounted for populating policies with categories using the new way in the postgres world. Fixed it to do exactly that.
Manual, on infra cluster.
> ROX-14783: Fix SearchRawPolicies to populate policy categories from new store when postgres is enabled

- pkg/declarativeconfig/auth_provider.go
- pkg/declarativeconfig/auth_provider_test.go
Auth provider struct which will be used to transform from YAML declarative config to Go struct.
Unit test added
> ROX-14137: auth provider declarative config

- image/templates/helm/stackrox-secured-cluster/templates/collector.yaml
The prom metrics server is started, even when monitoring is not explicitly exposed.
Therefore, we get port clashes in that case as well.
This PR disables the Compliance port completely if monitoring is not enabled, and sets it to a non-standard port if enabled, eliminating all clashes.
screenshots.
> Disable Prom metrics if monitoring is not set

- pkg/concurrency/poller_test.go
See the output in the related ticket https://issues.redhat.com/browse/ROX-14477
The case seems to be a very simple example of the data race. Despite that, I wasn't able to reproduce the original failure locally. Maybe the runner machine had some special condition.
The implementation of the `Poller` (struct under test) seems legit, at least I wasn't able to spot anything obviously broken.
None of the following is needed:
* Will merge if CI passes.
* Ran it successfully locally with `GOTAGS=release RACE=true scripts/go-test.sh -v -count=1000 -run TestPollWithTimeout ./pkg/concurrency`. However, as I mentioned above, even the original failure did not get reproduced this way.
> ROX-14477: Fix data race in `poller_test.go`

- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
Fixes the `openshift-penultimate-qa-e2e-tests` by reverting one cherry-pick from https://github.com/stackrox/stackrox/commit/b5b80a3e97568a74af68c03ecee3b184e11c8824. 
Failed test: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-release-3.73-merge-openshift-penultimate-qa-e2e-tests/1621467481371578368. 
> fix ImageScanningTest (no matching image registries found)

- .openshift-ci/ci_tests.py
- operator/README.md
- operator/tests/TROUBLESHOOTING_E2E_TESTS.md
@theencee please let me know if this would have helped in your case.
Not perfect, but that's all I could prepare today before PTO. Will improve this in a followup PR with a better example now that https://github.com/stackrox/stackrox/pull/4568 enables log fetching in more steps.
CI should be sufficient to make sure I didn't break the Python file. Otherwise this is just a doc.
> First stab at kuttl troubleshooting guide.

- pkg/declarativeconfig/access_scope.go
- pkg/declarativeconfig/auth_provider.go
- pkg/declarativeconfig/configuration.go
- pkg/declarativeconfig/permission_set.go
- pkg/declarativeconfig/role.go
This PR is a prefactor for [ROX-14148](https://issues.redhat.com/browse/ROX-14148), which shall add the transformation logic for each specific declarative configuration type.
We introduce a new interface `Configuration`, which will be used to abstract all different types of declarative configuration such as `Access Scope, AuthProvider, Permission Set, Role`.
For now, the interface exposes only a single method, which is `Type()` to return a string enum which specifies the type of the declarative configuration.
This will later on be used to differentiate between the configurations when transforming them.
Later on, this interface will most likely also be extended to support a `Validate()` method, validating the contents of the YAMLs.
- no …
> ROX-14148: Prefactor Configuration interface for declarative configurations

- .github/workflows/start-release.yml
The workflow created an `rc.0` milestone: https://github.com/stackrox/stackrox/actions/runs/4084959446
Start Release should rather create `next-milestone`, as `milestone` will be 0, as there should be no `-rc.` in the version provided for a release.
https://github.com/stackrox/stackrox/actions/runs/4101883067
> ROX-14902: Fix rc.0 milestone

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#12-5-0
* Improved memory consumption in `run` mode by removing reporter logs for successful tests.
* Upgraded `underscore.string` from 3.3.5 to 3.3.6 to reference rebuilt assets after security patch to fix regular expression DDOS exploit.
https://docs.cypress.io/guides/references/changelog#12-5-1
* Fixed a regression introduced in Cypress 12.5.0 where the `runnable` was not included in the `test:after:run` event.
* Upgraded `simple-git` from 3.15.0 to 3.16.0 to address security vulnerability where Remote Code Execution (RCE) via the clone(), pull(), push() and listRemote() methods was possible due to improper input sanitization.
> Update cypress 12.5.1 devDependencies in ui

- central/cluster/datastore/telemetry.go
- central/role/mapper/telemetry.go
- central/telemetry/centralclient/instance_config.go
- pkg/telemetry/phonehome/client_config.go
- pkg/telemetry/phonehome/gatherer.go
- pkg/telemetry/phonehome/gatherer_test.go
- pkg/telemetry/phonehome/interceptor.go
- pkg/telemetry/phonehome/interceptor_test.go
- pkg/telemetry/phonehome/segment/segment.go
- pkg/telemetry/phonehome/telemeter.go
- pkg/telemetry/phonehome/telemeter/mocks/telemeter.go
- pkg/telemetry/phonehome/telemeter/telemeter.go
- pkg/telemetry/phonehome/telemeter/telemeter_test.go
A suggestion for a refactoring:
* `Telemeter.With` overrides the User ID for which the following call is addressed;
* `Telemeter.As` overrides the device context to impersonate the device which sends the messages.
Unit tests.
> Refactoring: shared Telemeter interface package

- ui/apps/platform/src/Containers/MainPage/AnnouncementBanner.tsx
One more round of word-smithing
Updated message when using an environment running RocksDB
Allowing text wrapping on small screen widths, to account for longer message
No longer a message, after message is dismissed and page is refreshed (this screenshot is just to verify that there was no regression)
No message when using an environment running Postgres
> ROX-14777: Update Postgres coming soon message

- deploy/common/k8sbased.sh
- operator/tests/e2e/central-cr.envsubst.yaml
- qa-tests-backend/src/test/groovy/K8sRbacTest.groovy
- scripts/ci/jobs/openshift_oldest_qa_e2e_tests.py
- scripts/ci/jobs/openshift_penultimate_qa_e2e_tests.py
- tests/e2e/lib.sh
This PR:
- Skips K8sRbacTest under openshift where it is flaky (ROX-14666).
- Increases the node count for openshift e2e clusters by 1.
- This is required for the `openshift-penultimate-qa-e2e-tests` test because the operator now installs `central-db` by default.
- Removes the operator `central.db.isEnabled` setting as that is now obsolete.
CI is sufficient - with 3 openshift e2e flavors.
> CI: Fix openshift e2e

- deploy/common/k8sbased.sh
Prior to this change, we wouldn't propagate the env var variables so Postgres was running on standard storage class when on GKE. This will allow it to run with SSD to do comparisons
```
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
central-db            Bound    pvc-b29f98d3-26fd-4ee1-9276-9f0188e78490   100Gi      RWO            faster         17s
stackrox-db           Bound    pvc-efbcabe9-85e5-4494-b154-ca127a410ecb   100Gi      RWO            faster         17s
```
Ran it locally
> Propagate storage class options to Central-DB

- deploy/common/k8sbased.sh
- deploy/k8s/sensor.sh
- sensor/kubernetes/sensor/sensor.go
Disable re-sync when deploying ACS using `deploy/k8s` scripts.
> ROX-14780: Disable re-sync when deploying ACS with deploy.sh

- .github/workflows/verify-release.yml
Failed (Username and password required): https://github.com/stackrox/stackrox/actions/runs/4104924661
"Successful" (expected failure): https://github.com/stackrox/stackrox/actions/runs/4104983573
> fix GHA: set correct quay.io credentials for verify-release workflow

- Makefile
- make/protogen.mk
Podman runs containers as the current user, and uses the user namespace by default.
This PR removes user substitution (`--user ...`) for podman users, but keeps it for docker users.
`make image`
> Run 'podman run' in user namespace

- image/templates/README.md
- image/templates/helm/stackrox-central/values-public.yaml.example.htpl
- image/templates/helm/stackrox-central/values.yaml.htpl
- image/templates/helm/stackrox-secured-cluster/internal/defaults/50-images.yaml.htpl
@BradLugo got confused seeing `registry: stackrox.io` in the generated Helm values.
While that confusion is fair, Helm values files are meant to be examples illustrating usage rather than the set of currently selected values. I myself would prefer helm value files to give **actual** defaults, but this can easily make this change XL-sized.
Instead, I simply get rid of `stackrox.io` mentions where they may be confusing.
Context thread
https://srox.slack.com/archives/CELUQKESC/p1675462004575229?thread_ts=1675459102.811779&cid=CELUQKESC
None of these needed:
* Manually:
```bash
$ make cli
$ rm -rf stackrox-central-services-chart
$ rm -rf stackrox-secured-cluster-services-chart
$ roxctl helm output central-services --image-defaults=rhacs
$ grep -F '#image:' -B1 -A4 …
```
> Reduce the number of confusing instances of `stackrox.io` in charts

- central/declarativeconfig/manager_impl.go
- central/declarativeconfig/transform/transformer.go
- pkg/declarativeconfig/transform/transformer.go
This PR is a prefactor for [ROX-14148](https://issues.redhat.com/browse/ROX-14148) and adds an abstraction for transforming a declarative configuration to its associated proto message(s).
The previously introduced `ConfigurationType` will be re-used to distinguish which transformer to use.
For now, the default transformer created and used within the declarative configuration manager will not have any transformer implementations associated with it, those will be added at in follow-up PRs in the context of [ROX-14148](https://issues.redhat.com/browse/ROX-14148).
- no testing requried.
> ROX-14148: Prefactor Transformer abstraqction for declarative configuration.

- qa-tests-backend/src/test/groovy/RiskTest.groovy
This was the proposed solution, with the assumption being that the namespace failing deletion is causing failures and could be avoided by ensuring that the namespace is empty at the time the deletion is attempted.
As this is a flake, reproduction will be difficult. This change will be done and then monitored for any persistent issues. Further solutions will be explored in the case that this does not solve the issue at hand.
> ROX-14175: Wait for deployments to be deleted before trying to delete namespace in RiskTests

- tests/e2e/lib.sh
`openshift-*-qa-e2e-tests` have `CGO_CHECKS` enabled. This caused an invalid env var setting.
> ROX-14944: CI: Fix openshift e2e nightly tests

- image/templates/helm/stackrox-central/templates/01-central-12-central-db.yaml
Central-DB should have a readiness probe that signifies to the service that it is available
All tests should run as normal
> Add readiness probe to central-db

- .github/workflows/build.yaml
- .github/workflows/style.yaml
- .github/workflows/unit-tests.yaml
- .openshift-ci/Dockerfile.build_root
- .openshift-ci/build/Dockerfile.build-central-db-bundle
- .openshift-ci/build/Dockerfile.build-main-and-bundle
- .openshift-ci/build/Dockerfile.build-operator-artifacts
- BUILD_IMAGE_VERSION
- central/processlisteningonport/store/store.go
- scale/signatures/deploy.yaml
- tests/e2e/run-e2e-tests.sh
Reverts stackrox/stackrox#4658 which added a `-dirty` tag to operator builds.
https://srox.slack.com/archives/CELUQKESC/p1675807797443359
> Revert "Bump apollo-ci image to 0.3.56"

- CHANGELOG.md
- central/role/resources/list.go
- pkg/buildinfo/buildinfo.go
- pkg/buildinfo/internal/timestamp/timestamp.go
- pkg/version/version.go
- ui/apps/platform/src/constants/accessControl.ts
Following the name change of the future releases, references to these was updated in Changelog, UI and code comments.
- Open the Changelog and check for references to future releases by their versions.
- Deploy an instance, open the UI on Access Control, view an existing permission set, create another one, and check the permission deprecation releases.
> Change future release references from 3.75 and 3.76 to 4.0 and 4.1

- central/networkgraph/entity/datastore/datastore_impl_test.go
It is best to review this change by individual commits because there's bigg-ish prefactoring, but the actual fix is small.
I think the problem is with the test, rather than with the main code (which I did not dig enough).
I wasn't able to reproduce the test failure locally but I hope that my fix (explained below) should be able to address the issue.
In other words, my approach is to do the best effort, merge the change, close the ticket and wait the ticket to re-appear again on any subsequent test failures in case I wasn't able to resolve the root cause.
The related ticket has three failures:
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-merge-go-unit-tests-release/1617573217029853184
```
=== RUN   TestNetworkEntityDataStore
=== RUN …
```
> ROX-14490: Fix data race in `TestNetworkEntityDataStore`

- operator/tests/common/delete-central-errors-cluster.envsubst.yaml
- operator/tests/common/delete-securedcluster-errors.yaml
PSPs are not a thing any more in more recent k8s versions.
Unfortunately when `kuttl` is told to [check that a resource of an unknown type is not present, it fails](https://github.com/kudobuilder/kuttl/issues/317).
Keeping this check working on older versions of kubernetes (that still have this type) is probably not worth the effort. So we simply stop checking them.
- Counting on CI.
- Ran the test suite against an infra openshift 4.12.1 cluster.
> ROX-14427: Drop PodSecurityPolicy from errors files.

- pkg/renderer/kubernetes.go
- pkg/renderer/render_test.go
- roxctl/central/generate/k8s.go
- tests/roxctl/bats-tests/helpers.bash
- tests/roxctl/bats-tests/local/central-generate-development.bats
- tests/roxctl/bats-tests/local/expect/flavor-interactive-dummy.expect.tcl
- tests/roxctl/bats-tests/local/expect/flavor-interactive-postgres.expect.tcl
- tests/roxctl/bats-tests/local/expect/flavor-interactive.expect.tcl
This PR fixes an issue when trying to generate kubectl files for central and using the default values.
Specifically, the declarative configuration default values are the culprit.
Leaving the values as:
```
Enter list of config maps to add as declarative configuration mounts in central (default: "[]"):
Enter list of secrets to add as declarative configuration mounts in central (default: "[]"):
```
will lead to the following created mounts:
```
name: []
mountPath: /run/stackrox.io/declarative-configuration/[]
readOnly: true
name: []
mountPath: /run/stackrox.io/declarative-configuration/[]
readOnly: true
name: []
mountPath: /run/stackrox.io/declarative-configuration/[]
readOnly: true
name: []
mountPath: /run/stackrox.io/declarative-configuration/[]
readOnly: true
```
These are invalid names, …
> ROX-14953: Fix invalid kubectl files within roxctl generate

- qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
Changed the image that was getting scanned to generate debug logs to investigate test failure.
Not needed
> [ROX-11612] : Use correct struts image to scan for debug logging

- operator/pkg/central/values/translation/translation.go
- operator/pkg/central/values/translation/translation_test.go
- operator/tests/central/basic/10-assert.yaml
- operator/tests/central/basic/40-assert.yaml
- operator/tests/central/basic/40-reconcile.yaml
- operator/tests/central/basic/75-errors.yaml
- operator/tests/central/basic/76-assert.yaml
- operator/tests/central/basic/76-switch-back-to-internal-central-db.yaml
- operator/tests/central/basic/76-switch-back-zzz-deletes.yaml
This was resulting in is db isEnabled being false
The operator e2e tests should pass
> Default to empty DB Spec if unset in CR and update Kuttl tests

- ui/apps/platform/src/Containers/NetworkGraph/utils/networkGraphUtils.test.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/networkGraphUtils.ts
This PR fixes an issue with the deployment details tab showing the wrong info for the number of external flows for this deployment
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~
> ROX-14987: Fix wrong info for anomalous external flows count

- qa-tests-backend/src/main/groovy/objects/Notifiers.groovy
- qa-tests-backend/src/main/groovy/util/SyslogServer.groovy
- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
Added a e2e syslog test that verifies deploys syslog server, creates notifier and verifies connection between syslog and central.
Checklist
[ ] Unit test and regression tests added
[ ] Evaluated and added CHANGELOG entry if required
[ ] Determined and documented upgrade steps
[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))
Testing Performed:
Verified the test passes locally for syslog notifier.
> Added syslog notifier test to verify syslog connection

- tests/roxctl/bats-tests/local/expect/flavor-interactive-dummy.expect.tcl
- tests/roxctl/bats-tests/local/expect/flavor-interactive-postgres.expect.tcl
- tests/roxctl/bats-tests/local/expect/flavor-interactive.expect.tcl
Handle the change to prompt order after Go 1.18->1.19. This PR also makes the prompt match more strict as I noticed that some expect calls would silently timeout. As to wether the new order is correct is up for discussion.
> roxctl interactive mode: handle order change after Go update

- operator/tests/TROUBLESHOOTING_E2E_TESTS.md
As promiesd in #4570 here is an example that contains pod log outputs (from [this run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/4690/pull-ci-stackrox-stackrox-master-openshift-newest-operator-e2e-tests/1622769663010148352)).
Also some minor editorial improvements.
Doc-only change.
Took a look at the rendered markdown.
> Improvements for the operator e2e test troubleshooting guide.

- central/cluster/datastore/telemetry.go
- pkg/telemetry/phonehome/segment/segment.go
- pkg/telemetry/phonehome/segment/segment_test.go
- pkg/telemetry/phonehome/telemeter/telemeter.go
- pkg/telemetry/phonehome/telemeter/telemeter_test.go
This PR adds support for Amplitude API feature: `groups` field of Track events.
* `groups` is a mapping of group names to group IDs, e.g.
```json
"groups": { "Tenant": ["tenant-id1", "tenant-id2"] }
```
Considerations:
* Segment supports `groups` property mapping from a random context object. The PR suggests `context.groups`;
* Neither Segment nor Amplitude support `group_properties`.
The mapping configuration for the Amplitude destination on Segment side is set up like this:
Unit tests, local testing.
"Secured Cluster Initialized" event supplied with the Tenant group on Segment:
```json
{
"context": {
"device": {
"id": "97fc111c-f1bc-418f-85ef-0fa2d15aa973",
"type": "Secured Cluster"
},
"groups": {
"Tenant": [
"fa7bb897-a17c-4de6-a035-759a05598a77"
]
},
"library": {
"name": …
```
> Telemetry: `WithGroups` option

- ui/apps/platform/src/Containers/VulnMgmt/List/Cves/CveBulkActionDialogue.js
- ui/apps/platform/src/Containers/VulnMgmt/List/Cves/CveToPolicyShortForm.js
- ui/apps/platform/src/Containers/VulnMgmt/List/Cves/VulnMgmtListCves.js
- ui/apps/platform/src/utils/vulnerabilityUtils.js
The main purpose of this change is to fix a gap when migrating to Postgres, where CVEs could no longer be added to a policy from the CVE list pages.
In addition, it cleans up some "drift" in functionality, and some bugs that show this hasn't been a much-used feature.
- It filters out default policies from the list of existing VM policies that CVEs could be added to, because at some point subsequent to this default policies became read-only.
- It fixes a bug where existing non-default (i.e., customer-created) polices could not be selected, because of the way the VM data flow "locks" the JS objects that are passed by reference into this dialog. (The solution is to use a utility function to deep clone the an existing policy object selected as a target. The clone does not have the "locked" …
> ROX-14797: Fix bulk Add CVEs to Policy for Postgres

- central/cluster/datastore/telemetry.go
- central/telemetry/centralclient/instance_config.go
- pkg/telemetry/phonehome/segment/segment.go
- pkg/telemetry/phonehome/segment/segment_test.go
- pkg/telemetry/phonehome/telemeter/telemeter.go
- pkg/telemetry/phonehome/telemeter/telemeter_test.go
Set `anonymousId` instead of `userId` for messages without an explicitly assigned user. This allows for distinguishing backends from API users by querying `userId == 'none'`.
```json
{
"anonymousId": "fa7bb897-a17c-4de6-a035-759a05598a77",
"context": {
"device": {
"id": "fa7bb897-a17c-4de6-a035-759a05598a77",
"type": "Central"
},
"library": {
}
},
"event": "Updated Central Identity",
"messageId": "b62fbd3a-c64f-41f8-8dbe-e0f7a08b867c",
"originalTimestamp": "2023-02-03T15:18:46.173249011Z",
"receivedAt": "2023-02-03T15:19:46.653Z",
"sentAt": "2023-02-03T15:19:45.978Z",
"timestamp": "2023-02-03T15:18:46.848Z",
"type": "track",
"writeKey": "..."
}
```
> Telemetry: set anonymousId for events where user is not provided

- scripts/ci/lib.sh
0.0.4 fixes problem with long logs that are not accepted by jira as it has limited number of chars in task description.
CI
> Bump junit2jira to 0.0.4

- pkg/declarativeconfig/transform/access_scope.go
- pkg/declarativeconfig/transform/access_scope_test.go
- pkg/declarativeconfig/transform/transformer.go
This PR adds logic to transform a declarative configuration, specifically the `Access Scope` one, to its related proto message.
Within the transformation logic, the proto fields will be filled as well as a deterministic UUID based on the name of the access scope will be created.
For now, within the transformation logic, no validation of the transformed proto message is done (e.g. about conformity, name uniqueness etc.). These additional checks may be added at a latter point in a follow-up.
- added unit tests.
> ROX-14148: Add transforming of declarative config to proto for Access Scopes

- scripts/ci/jobs/ocp_ui_e2e_tests.py
- scripts/ci/jobs/openshift_penultimate_qa_e2e_tests.py
- tests/e2e/run-ui-e2e.sh
This will allow UI e2e tests to run in an OSCI OCP 4.12 cluster via `/test ocp-ui-e2e-tests`. At present they will not pass and that is a separate WIP. 
Companion to https://github.com/openshift/release/pull/36201
> Add an OCP option for UI e2e tests

- pkg/auth/authproviders/oidc/backend_factory_impl.go
- pkg/auth/authproviders/oidc/backend_impl.go
- pkg/auth/authproviders/oidc/backend_impl_test.go
- pkg/auth/authproviders/saml/backend_impl.go
- pkg/declarativeconfig/auth_provider.go
- pkg/declarativeconfig/transform/auth_provider.go
- pkg/declarativeconfig/transform/auth_provider_test.go
- pkg/declarativeconfig/transform/permission_set_test.go
- pkg/declarativeconfig/transform/transformer.go
This PR adds logic to transform a decalartive configuration, specifically the `Auth provider`, to its related proto message.
The `Auth Provider` declarative configuration is unique in the sense that it specifies the `Auth Provider` as well as the `Groups` proto messages.
The `Auth Provider` transformation logic had a few caveats:
- The `config` for each auth provider is a `map[string]string`, however based on the type, different keys should be populated. Some refactorings were required to share the config keys between the transformation logic and the specific auth provider backend.
- The UUID is created deterministically from the name of the auth provider. This will need to be reused in the login URL for the auth provider.
- The `Groups` which are associated with the auth provider will …
> ROX-14148: Add transforming of declarative config to proto for Auth providers & groups

- operator/apis/platform/v1alpha1/central_types.go
The function `CentralDBEnabledPtr()` is still used by `acs-fleet-manager` and should have not been removed, as long as the field `IsEnabled` still exists and must be set to `Enabled` in ACSCS.
~~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~
CI should be sufficient, this just restores a function deleted in this PR https://github.com/stackrox/stackrox/pull/4372
> Restore CentralDBEnabledPtr

- .github/CODEOWNERS
Being in CODEOWNERs means getting review emails for PRs that are WIP. I'd rather not. If other members of the stackrox/ci group like the spam I can remove myself from the group.
- n/a
- n/a
> CI: Less spam

- central/telemetry/centralclient/instance_config.go
- pkg/grpc/authn/tokenbased/extractor.go
- pkg/telemetry/phonehome/hash.go
- pkg/telemetry/phonehome/hash_test.go
We have 2 points of user identity extractions:
1. when a user logs in for the first time, the central will add the user to the tenant group;
2. when the user calls central, the central may issue an event, with the user ID.
There's apparently a problem in that those two cases produce different user IDs:
1. uses the actual user ID, like `admin` or `test@stackrox.com`;
2. uses the token-based ID, like `sso:3dadd0b0-1649-426e-81d5-cde3fce5e181:test@stackrox.com`.
As the two IDs do not match, the actual events get no assigned tenant group. This explains why we miss the 'Secured Cluster Registered' event in the funnel.
This PR make the hash function to trim the prefix generated by the tokenbased id extractor, so that 
user IDs extracted from tokens of the requests to central would match the …
> ROX-14979: Trim `sso:provider-id:` prefix from user ID

- scripts/ci/jobs/openshift_penult_operator_e2e_tests.py
Setup link for "penult" operator e2e tests in order to be able to run them on merges.
The problem is that OSCI does not like the test name `merge-openshift-penultimate-operator-e2e-tests` as being too long, therefore shortened it to `merge-openshift-penult-operator-e2e-tests` in order to make OSCI happy.
See https://github.com/openshift/release/pull/36268
Won't do these:
None.
```
$ pwd
/home/misha/go/src/github.com/stackrox/stackrox/scripts/ci/jobs
$ ls -l openshift_*_operator_e2e_tests.py
-rwxrwxr-x 1 misha misha 497 Okt 31 15:36 openshift_4_operator_e2e_tests.py
lrwxrwxrwx 1 misha misha  33 Okt 31 15:36 openshift_beta_operator_e2e_tests.py -> openshift_4_operator_e2e_tests.py
lrwxrwxrwx 1 misha misha  33 Okt 31 15:36 openshift_newest_operator_e2e_tests.py -> …
```
> Setup link for "penult" operator e2e tests

- ui/apps/platform/src/Components/TablePagination.js
After a lot of dead-ends, I finally tracked down this bug.
Immediate cause: 
- The `stateStack` property of the "workflowState" is what we use to capture the infinite possible levels of the Vulnerability section.
- Now that the CVE type has been split into 3 separate types for Postgres, we still use the same template option for all CVEs, but varying the rendering options based on the new CVE type.
- Since the whole render tree from the root template was no longer changing when going directly from one CVE type to another, the Pagination component was not getting re-created.
- Surprise! the part of the pagination component where you can type any page number to go directly to that page of the results, besides being wrapped in a "debounce" function to prevent a flurry of API calls when …
> ROX-13379: Fix bug when typing new page number among CVE types

- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
Verify syslog notifier is intermittently failing in CI with connection error. Added retry in assert test syslog section to give some time for syslog service to come up after deployment. 
Ran test few times locally to make sure there are no failures.
> ROX-14996 - Add retry in verify syslog test

- .github/workflows/unit-tests.yaml
Migrate local roxctl tests from OSCI to GHA. As it requires builded CLI let's run it in build phase so we can access builded binaries.
CI
> ROX-15045: run local roxctl tests on GHA

- Makefile
This should help with `stringer` problems. At least it does solve it for my local problems.
Locally I've been seeing
```
central/graphql/resolvers/active_state.go
stringer -type=ActiveStateEnum
stringer: internal error: package "context" without types was imported from "github.com/stackrox/rox/central/graphql/resolvers"
central/graphql/resolvers/active_state.go:10: running "stringer": exit status 1
```
After some googling, that seems to happen because older `stringer` gets picked up. The obvious hunch is that `stringer` installed via `go-tool` is not visible during Go code generation.
Context: https://srox.slack.com/archives/CELUQKESC/p1674834470778089
None of these:
* No problems locally after the fix.
* `grouped-static-checks` and `Style / check-generated-files` should remain green.
> Include `.gotools` in the `$PATH` for go code generation

- image/postgres/scripts/docker-entrypoint.sh
- image/templates/helm/stackrox-central/templates/01-central-12-central-db.yaml
Default to fast shutdown, which kills all in flight txns and rolls them back. This will allow for faster shutdown and less likely sigkills in the middle of termination
Ran the equivalent in a chaos test for several days
> Update Central DB signal handling to default to fast shutdown

- make/protogen.mk
Previously, if one did not fetch the dependencies since the scanner dep was bumped you'd get a cryptic error such as:
```
[mowsiany@mowsiany operator]$ make generate
make -C .. proto-generated-srcs
make[1]: Entering directory '/home/mowsiany/go/src/github.com/stackrox/stackrox'
+ Checking if github.com/grpc-ecosystem/grpc-gateway is up-to-date
+ Checking if github.com/gogo/protobuf is up-to-date
+ /home/mowsiany/go/src/github.com/stackrox/stackrox/generated/api/integrations/splunk_service.pb.go
Missing value for flag: -I
make[1]: *** [make/protogen.mk:191: /home/mowsiany/go/src/github.com/stackrox/stackrox/generated/api/integrations/splunk_service.pb.go] Error 1
make[1]: Leaving directory '/home/mowsiany/go/src/github.com/stackrox/stackrox'
make: *** [Makefile:197: parent-proto-generate] …
```
> ROX-13813: fail in a visible way when scanner protos cannot be found

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NodeUpdateSection.tsx
This implements the "nodes-were-added-click-to-update" functionality of the old Network Graph, on the new Network Graph.
There were no mocks for how this should look in the new format. On the old graph, there was a floating rectangle near the upper-right corner of the graph, with the timestamp when the graph was last updated. If the number of nodes available for the graph changed, a count of the difference of nodes was added below the timestamp, and the whole thing became a clickable area to force a graph update.
On the new graph layout, the mocks show the timestamp in the far right of the lowest toolbar. There is no mock for the 
Steps to test
(shown in the screen recording attached below)
1. I selected the Production cluster, and the backend and default namespaces, on staging.
2. I …
> ROX-14582: Wire up network graph polling

- central/networkpolicies/service/service_impl.go
- pkg/protoconv/networkpolicy/conversion_test.go
- pkg/protoconv/networkpolicy/k8s.go
- pkg/protoconv/networkpolicy/rox.go
Kubernetes added a 'status' field for NetworkPolicies in 1.24. See: [v1.24 Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#api-change-3)
Using the `NewSerializerWithOptions` from `k8s.io/apimachinery/pkg/runtime/serializer/json` with a `v1.NetworkPolicy` will return the `status` field even if the status is empty. This is because the type `Status` is defined as a value instead of a pointer so it always gets serialized in json.
The problem is: Old cluster using kubernetes < 1.24 will fail to apply NetworkPolicies generated this way. See: [ROX-14775](https://issues.redhat.com/browse/ROX-14775)
Since the `status` field is not handled by ACS, we can delete the field manually if present.
Note: This might not be necessary in the future since the …
> ROX-14775 Delete the status field if present when encoding NeworkPolicies to YAML

- ui/apps/platform/src/Components/PatternFly/ResourceIcon/ResourceIcon.css
- ui/apps/platform/src/Components/PatternFly/ResourceIcon/ResourceIcon.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/MostRecentViolations.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicySeverity.test.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicySeverity.tsx
- ui/apps/platform/src/css/acs.css
- ui/apps/platform/src/types/alert.proto.ts
Correctly handles the response type for the `alerts` graphql queries in the dashboard widget.
The query was incorrectly types as a `DeploymentAlert` when the true response type is `Alert`, which could be a `DeploymentAlert`, `ImageAlert`, or `ResourceAlert`, each of which has different `null` fields. This caused the dashboard to crash when the most recent alert was from a `ResourceAlert` type, which I believe only occurs when the user creates a custom policy for k8s audit logs and sets the severity to critical.
This may be easier to review with "Hide whitespace" on.
Load the widget with violations of a custom policy tracking the `configmap` type.
Load the widget with violations of a custom policy tracking the `secrets` type.
Load the …
> ROX-15103 Correctly handle different alert types on dashboard widget

- qa-tests-backend/src/main/groovy/services/ServiceAccountService.groovy
- qa-tests-backend/src/test/groovy/K8sRbacTest.groovy
On Postgres on Openshift, listing all service accounts can be very slow. We have a different ticket for this: ROX-14666
CI
> Fix service account test by using a specific query instead of a list

- sensor/admission-control/manager/k8s_object.go
- sensor/kubernetes/listener/resource_event_handler.go
- sensor/kubernetes/listener/resources/convert.go
This uses k8s discovery API to determine if v1/batch CronJob exists. If it does then use the informer for that, if not, then fall back to v1beta1. This does however mean that without more involved changes, that we cannot move forward from k8s client-go 1.24 which is the last version with v1beta1 for cron jobs (there isn't risk of this happening automatically as an API upgrade will cause a compilation error)
CI should test the v1 flow, but we'll have to manually test 3.11 and <4.6
> ROX-14973: Support CronJobs in a backwards compatible way

- ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicyCategoryChart.tsx
Just a little tidying up
Used a scale cluster as backend
Before
After this change, at scale
Even with this change, smaller scales still behave as before
> ROX-15095: Adjust Violations chart axis for large counts

- ui/apps/platform/src/Components/PatternFly/ResourceIcon/ResourceIcon.css
- ui/apps/platform/src/Components/PatternFly/ResourceIcon/ResourceIcon.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/MostRecentViolations.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicySeverity.test.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicySeverity.tsx
- ui/apps/platform/src/css/acs.css
- ui/apps/platform/src/types/alert.proto.ts
Cherry pick of https://github.com/stackrox/stackrox/commit/a069261608ec227efa7b3cdc96a2bae8baf61a61 from  https://github.com/stackrox/stackrox/pull/4872 with merge conflicts resolved for the 3.73.3 patch release.
Repeat testing steps of https://github.com/stackrox/stackrox/pull/4852 with simulated network requests for:
- Alerts with a valid `deployment` field object
- Alerts with `deployments: null` and `resource.resourceType: 'SECRETS'`
- Alerts with `deployments: null` and `resource.resourceType: 'CONFIGMAPS'`
- Alerts with `deployments: null` and `resource.resourceType: 'UNKNOWN'`
- Alerts with both `deployments: null` and `resource:null` (should not happen, but the UI falls back to the "unknown" alert type
> Correctly handle different alert types on dashboard widget

- .openshift-ci/post_tests.py
- scripts/ci/collect-infrastructure-logs.sh
This timed out too early in [a PR](https://github.com/stackrox/stackrox/pull/4775#issuecomment-1427831543) for me on a cluster where `oc adm` is non-functional.
- Bump the outer timeout by 2 minutes
- Shrink the must-gather timeout by 3 minutes
- Print some timestamped messages to figure out how long `must-gather` actually takes (edit: seems like below 20s)
Relying on CI.
> Tune collect-infrastructure-logs.sh timeout.

- ui/apps/platform/src/Containers/SystemConfig/Form/SystemConfigForm.tsx
- ui/apps/platform/src/reducers/publicConfig.ts
- ui/apps/platform/src/utils/fetchingReduxRoutines.ts
First draft of a pattern for reducers in TypeScript.
Ironically, so much effort on action **creator function** types did nothing for actions in reducers :(
Also to support optional `params` which is only in globalSearch that will be deleted in #4855
`PrefixedAction<'whatever/WHATEVER', Response>` type has better type safety than the following classic function calls:
* `createFetchingActionTypes('whatever/WHATEVER')`
* `createFetchingActions(types.WHATEVER)`
If reducer has `switch` instead of `if` statements, then TypeScript reports errors for incorrect property access:
* `type`
* `response`
* `error`
Note that the change in SystemConfigForm reported a problem because of assumption that response is non-null. Bravo!
Notice an ancient copy-pasto: `'notifiers/FETCH_PUBLIC_CONFIG'`
1. Initial …
> Define PrefixedAction type for reducers in TypeScript

- deploy/k8s/deploy.sh
- deploy/k8s/sensor.sh
Resync was disabled by mistake in the `deploy/openshift` scripts. #4721 set `ROX_RESYNC_DISABLED="true"` in `deploy/k8s/sensor.sh`. The problem is: `deploy/openshift/sensor.sh` is a link to `deploy/k8s/sensor.sh` so by disabling the resync in `k8s/sensor.sh` it was also being disabled in `openshift/sensor.sh`
This PR should disable resync only for `deploy/k8s`.
This should also fix the the test failure `RoutesTest / Verify that routes are detected correctly` (See [ROX-14004](https://issues.redhat.com/browse/ROX-14004))
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-do …
> Disable resync only in vanilla k8s

- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/routePaths.js
Adds left hand navigation item for new Vulnerabilities section as well as routes to match the Workload CVE pages:
- Workload CVE Overview
- CVE Single page
- Image Single page
- Deployment Single page
The navigation with the feature flag enabled:
The navigation with the feature flag disabled:
Navigating to any of the Vulnerabilities subpages returns a 404 page, with or without the feature flag. (Route handlers are not implemented in this PR.)
> ROX-15009 Add navigation item for 'Vulnerabilities' (VM 2.0) section

- operator/tests/central/basic/81-assert.yaml
- pkg/search/postgres/common.go
We should pass the contexts correctly. Just looked at all the of logs and don't have one related to pg context timeouts
Check of logs from runs
> Pass contexts instead of copying them to honor context cancellations

- image/templates/helm/stackrox-central/internal/config-shape.yaml
- image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
- image/templates/helm/stackrox-central/templates/01-central-00-db-serviceaccount.yaml
- image/templates/helm/stackrox-central/templates/01-central-02-db-psps.yaml
- image/templates/helm/stackrox-central/templates/01-central-02-db-security.yaml
- image/templates/helm/stackrox-central/templates/01-central-08-db-configmap.yaml
- image/templates/helm/stackrox-central/templates/01-central-08-external-db-configmap.yaml
- image/templates/helm/stackrox-central/templates/01-central-10-db-networkpolicy.yaml
- image/templates/helm/stackrox-central/templates/01-central-11-db-pvc.yaml
- image/templates/helm/stackrox-central/templates/01-central-12-central-db.yaml
- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- image/templates/helm/stackrox-central/templates/_central_setup.tpl
- image/templates/helm/stackrox-central/values-public.yaml.example.htpl
- image/templates/helm/stackrox-central/values.yaml.htpl
- operator/pkg/central/values/translation/translation.go
- operator/pkg/central/values/translation/translation_test.go
- operator/tests/central/basic/80-assert.yaml
- operator/tests/central/basic/81-assert.yaml
- pkg/search/postgres/common.go
Remove the option to disable Central DB in the helm charts
CI should do it
> ROX-15040: Remove Central DB enabled option

- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesDeploymentSinglePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesImageSinglePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesSinglePage.tsx
Adds route handling and almost empty page shells for the four main pages of the Workload CVEs section.
With feature flag enabled
Visit the main Workload CVEs page via the sidebar link or by direct entry of the URL:
Visit the cve, image, and deployment single pages via direct entry of the URL:
Visiting a workload cve route that is not the base URL, or a valid entity with an `id` part of the path results in a 404 page:
With feature flag **disabled** - manually verify that all of the above URLs return the standard 404 page.
> ROX-15017 Add routing and stubbed page components for Workload CVEs

- operator/tests/common/delete-central-errors-cluster.envsubst.yaml
- operator/tests/common/delete-securedcluster-errors.yaml
Cherry-picking an operator test fix to the release branch. 
> Cherry-pick Operator test fix: Drop PodSecurityPolicy from errors files. (#4774)

- roxctl/central/db/restore/v2.go
- roxctl/central/db/restore/v2_test.go
This PR fixes a panic that occurs when no file is given within the positional args for `roxctl central db restore`.
The following has changed within the PR:
- Instead of using custom validation of the positional argument, use `cobra.ExactArgs()` instead.
- Mark the previously only _commented_ deprecated `--file` flag as _actually_ deprecated.
- Within the `validate()` step, ensure that its also validated that the file exists.
- see added unit tests.
> ROX-10999: Fix panic in roxctl central db restore when no file is given

- central/cluster/datastore/telemetry.go
- central/main.go
- central/role/mapper/telemetry.go
- central/telemetry/centralclient/instance_config.go
- pkg/telemetry/phonehome/client_config.go
- pkg/telemetry/phonehome/gatherer.go
- pkg/telemetry/phonehome/interceptor.go
- pkg/telemetry/phonehome/interceptor_test.go
- pkg/telemetry/phonehome/segment/segment.go
- pkg/telemetry/phonehome/telemeter.go
- pkg/telemetry/phonehome/telemeter/mocks/telemeter.go
- pkg/telemetry/phonehome/telemeter/telemeter.go
* added `WithGroups` to all Track calls so that the events are attached to the Tenant;
* made `Group` method read `WithGroups` option for the group ID;
* renamed `groupName` to `groupType` following Amplitude convention, to reduce naming confusion;
* added `groupType` property to the telemetry client configuration;
* modified `Gatherer.Start` method to accept the options for the underlying telemetry calls.
> Telemetry: Always add WithGroups to Track calls

- central/metrics/central.go
- central/metrics/init.go
- central/processlisteningonport/datastore/datastore_impl.go
Add counter to monitor orphaned PLOP objects. A PLOP object not referencing a ProcessIndicator is not a valid situation and has to be monitored.
Local testing to make sure the metric is present in the output.
> ROX-14377 Orphaned PLOP metric.

- ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx
While answering a question about which specific value to use for a group mapping for OpenShift auth provider (`userid` vs `name`), I realized we currently do not expose the `Test login` functionality for the auth provider.
This is typically useful to test the values received from the IdP and adjust the groups mapping based on that.
Now, the test login has been enabled for the OpenShift auth provider.
If any of these …
> ROX-10744: Add test login to OpenShift auth provider

- qa-tests-backend/Makefile
- qa-tests-backend/src/test/groovy/VulnMgmtSACTest.groovy
Query for additional scanner information when getting Image Vulnerabilities while running in Postgres on the VulnMgmtSACTest. When GraphQL gets queried in the tests, it logs at `Info` level the request and the response. With this change when this flake happens again we will be able to determine which scanner the vulnerability is getting populated by simply by looking back a couple of lines in the build logs of the failing tests.
Fix for the `make proto-generated-sources` rule in the qa-tests-backend Makefile. I wasn't able to get make wildcards work, but using find to expand the files in proto will allow us to detect if proto files have been deleted as well rather than just changed. If we want to narrow it down in scope at some point in the future we can use `-type f` to narrow to files …
> ROX-14025: VulnMgmtSACTest flake additional logging

- qa-tests-backend/src/main/groovy/services/BaseService.groovy
To prevent QA test failures due to network errors (like below), enable retries.
> io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
CI
> ROX-15061: Enable retry on grpc client

- sensor/tests/resource/helper.go
- sensor/tests/resource/networkpolicy/networkpolicy_test.go
- sensor/tests/resource/pod/pod_test.go
- sensor/tests/resource/role/role_test.go
- sensor/tests/resource/service/service_test.go
Refactor the helper functions used in the `sensor-integration-test`
* Enables the helper functions to create resources based on structs.
* Adds the `testRun` struct to hold all the information regarding a test run.
* Adds a `RetryCallback` that will be called (if set) when the creation of a resource fails.
**Note to the reviewers**: Consider reviewing the PR commit by commit. …
> sensor integration test helper refactor

- central/detection/alertmanager/alert_manager_impl.go
- central/detection/alertmanager/alert_manager_impl_test.go
This PR logs error instead of panicking when an unexpected runtime process alert is encountered by Central.
Unit
> [ROX-15198] Do not panic when unexpected process violations are received

- scripts/ci/lib.sh
- scripts/ci/logcheck/blocklist-patterns
- scripts/ci/logcheck/check.sh
- tests/e2e/bats/check_for_stackrox_OOMs.bats
- tests/e2e/lib.sh
Failures from the script that checks pod logs for suspicious entries are hidden in CI output. This PR creates a JUnit record for them.
- how it looks now (testing with a check for stackrox in logs :raised_eyebrow:): https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/4917/pull-ci-stackrox-stackrox-master-gke-nongroovy-e2e-tests/1626659698134487040
> ROX-15086: Junitify pod log checks

- central/declarativeconfig/manager.go
- central/declarativeconfig/manager_impl.go
- central/declarativeconfig/mocks/watch_handler.go
- central/declarativeconfig/singleton.go
- central/declarativeconfig/watch_handler.go
- central/declarativeconfig/watch_handler_test.go
- central/main.go
- pkg/env/declarative_config.go
This PR adds the reconciliation loop for declarative configurations.
After the contents of the declarative configuration mounts will be watched by multiple watch handlers (introduced within [ROX-14147](https://issues.redhat.com/browse/ROX-14147), the next step is to start with the reconciliation of the transformed proto messages.
This includes the following:
- Creating a "complete" view of all transformed proto messages, keyed by their respective watch handler directory.
- Creating a loop that will continously iterate over the transformed proto messages and allow for upserting proto messages as well as deleting proto messages.
Besides these two points, the following was done as well:
- Instead of specifying the watch handler intervals as well as the reconciliation loop interval as …
> ROX-15164: Reconciliation loop for declarative configuration

- qa-tests-backend/src/test/groovy/ProcessesListeningOnPortsTest.groovy
The processes listening on ports test should only run for gke-postgres-qa-e2e-tests
> Jv plop e2e test only for gke postgres qa e2e tests

- central/role/datastore/datastore_test.go
This test was not working with Postgres.  Updated it such that it will execute Postgres backed stores.
this is only a test
> Dashrews/ROX-14966 Update role datastore test to work with postgres

- ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx
- ui/apps/platform/src/types/cluster.proto.ts
1. Import type from frontend proto file.
2. Replace property dot with `in` operator, which TypeScript prefers for case analysis in this situation.
3. Add missing type intersection in frontend proto file.
* clusters/clustersHealthStatus.test.js
> Fix lint warning about no explicit any in clusters ProviderMetadata type

- central/views/imagecve/image_cve.go
- central/views/imagecve/singleton.go
- central/views/imagecve/types.go
- central/views/imagecve/view_impl.go
- central/views/imagecve/view_test.go
This PR adds the concept similar to SQL views to work with the cve data irrespective of the underlying data model. The model also uses real snapshots of image scans in the unit tests, the first of its kind. This will eventually be used in VM2.0 graphQL.
**Background:**
We store CVEs distro-specific. As in, one cve can have multiple records in DB. By having the abstraction similar to SQL view saves us from changing the data model yet again and having yet another table that captures core cve data like universal CVE identifier (not ACS CVE identifier), summary, published date, etc. 
Unit
> [VM2.0] Image CVE view

- ui/apps/platform/src/Containers/VulnMgmt/Entity/Cluster/VulnMgmtClusterOverview.js
Remove the policies table from clusters in vulnerability management.
The table on its own doesn't provide as much context as the violations page. The same information can be found on the violations page, which the field team confirmed can be confusing to customers.
> ROX-14019: remove policies table from clusters in vuln mgmt

- ui/apps/platform/src/Containers/Dashboard/Widgets/DeploymentsAtMostRiskTable.tsx
- ui/apps/platform/src/Containers/Risk/RiskSidePanelContent.js
This PR changes links from the old Network Graph to the new Network Graph. The following are areas where I found links to the Network Graph:
1. The "Deployments at most risk" widget in the Dashboard section
2. Under the "Risk Indicators" tab in the Risk section
If there are any other areas I might have missed, let me know 
https://user-images.githubusercontent.com/4805485/220225102-402cef2f-ba27-46e5-a32d-5fe8dbac27fc.mov
https://user-images.githubusercontent.com/4805485/220225130-371b5ba5-8226-4295-83f2-1f5f58cfb01a.mov
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift- …
> ROX-15138: Change the links from NWG 1.0 to NWG 2.0

- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.test.ts
This PR adds a few more tests for flow util functions for the Network Graph
Run `npm test` in the `/apps/platform` directory to run tests
> feat: adding tests for network graph util functions (part 2)

- ui/apps/platform/cypress/integration/networkGraph/network.test.js
- ui/apps/platform/cypress/integration/risk/risk.test.js
- ui/apps/platform/src/Containers/Dashboard/Widgets/DeploymentsAtMostRiskTable.tsx
- ui/apps/platform/src/Containers/NetworkGraph/utils/networkGraphURLUtils.test.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/networkGraphURLUtils.ts
- ui/apps/platform/src/Containers/Risk/RiskSidePanelContent.js
This is a follow-up PR to https://github.com/stackrox/stackrox/pull/4955 in order to create a util function that can generate a link to a specific deployment. This util function should make it easier in regards to the following:
1. Having a util function to generate a link to a specific deployment prevents us from repeatedly (and manually) creating links in different parts of the app
2. If the URL architecture of network graph changes, we only need to make changes in this file rather than all the places where the links are used …
> feat: creating a util function to generate links to a specific deployment in network graph

- .golangci.yml
- Makefile
Currently modules could be changed by linter. This PR disable this and require modules to be downloaded before.
> If set we pass it to "go list -mod={option}". From "go help modules":
> If invoked with -mod=readonly, the go command is disallowed from the implicit
> automatic updating of go.mod described above. Instead, it fails when any changes
>  to go.mod are needed. This setting is most useful to check that go.mod does
> not need updates, such as in a continuous integration and testing system.
> If invoked with -mod=vendor, the go command assumes that the vendor
> directory holds the correct copies of dependencies and ignores
> the dependency descriptions in go.mod.
https://golangci-lint.run/usage/configuration/
CI
> Do not change modules on lint

- sensor/kubernetes/listener/resource_event_handler.go
Sync roles prior to role bindings due to dependencies on role id. I saw this when doing some other deduping work and saw that bindings were breaking the deduping logic
Master vs this PR events locally:
```
sensor_event_queue Operation=Add Type=Role (old: 91.00, new 91.00): change: 0.0000%
sensor_event_queue Operation=Add Type=Binding (old: 136.00, new 78.00): change: -42.6471%
```
```
postgres_table_size table=role_bindings                                          78
```
Should see fewer role bindings events
> Sync roles in Sensor prior to role bindings

- central/role/datastore/datastore_impl.go
- central/role/datastore/datastore_test.go
The bug introduced within https://github.com/stackrox/stackrox/pull/4762 made it impossible to update roles via `datastore_impl#UpdateRole` - it was always reusing old value instead of new one.
This is a quick fix to correct the bug. Planning follow up PR to add similar test cases for access scopes and permission sets
1. Unit test added
> Update value during UpdateRole call instead of reusing the same one

- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
> ROX-13915: Move docker.io images used in ImageManagementTest to quayio/rhacs-eng to prevent rate limiting

- ui/apps/platform/src/Containers/VulnMgmt/Entity/Deployment/VulnMgmtDeploymentOverview.js
Remove the policies table from deployment in vulnerability management.
The table on its own doesn't provide as much context as the violations page. The same information can be found on the violations page, which the field team confirmed can be confusing to customers.
> ROX-14018: Remove policy table from deployment in vuln mgmt

- ui/apps/platform/src/Containers/VulnMgmt/Entity/Namespace/VulnMgmtNamespaceOverview.js
Remove the policies table from namespace in vulnerability management.
The table on its own doesn't provide as much context as the violations page. The same information can be found on the violations page, which the field team confirmed can be confusing to customers.
> ROX-14020: Remove policy table from namespace in vuln mgmt

- compliance/collection/main.go
In the current state, compliance calls the `Communicate` function every time it wants to send something. This will orphan the gRPC stub created in `manageReceivedStream`, thus making sensor unable to send any messages to compliance.
This PR aims to solve this problem by reusing the same gRPC stub for receiving and sending messages from/to sensor (tracked in [ROX-15100](https://issues.redhat.com/browse/ROX-15100)).
See: 
* [ROX-13383](https://issues.redhat.com/browse/ROX-13383) …
> Refactor compliance connection to sensor

- sensor/kubernetes/listener/resource_event_handler.go
Informers have a SetTransformFunc that mutates an object before it hits the cache. Generically, we can set the managed fields entries to nil
screenshots.
> Removed ManagedFields at the informer level to save on memory

- central/detection/lifecycle/manager_impl.go
- central/metrics/central.go
- central/metrics/init.go
Adds a metric that tracks how many indicators have yet to be flushed. This is not available in sensor_event_queue because of the batching
Will run this on GKE once it builds and should prometheus metric
> Add queue length metric for process indicators

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/CveStatusTabNavigation.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/EntityTypeToggleGroup.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadTableToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
following the description in the ticket (https://issues.redhat.com/browse/ROX-15020)
just adding scaffolding and url state management for the tabs for now
> ROX-15020: Adding Workload CVE Overview page scaffolding

- ui/apps/platform/cypress/integration/vulnmanagement/entitypages.test.js
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/TableModal.tsx
- ui/apps/platform/src/hooks/useTableSelection.ts
Due to defining a default function within the React custom hook, the reference keeps changing and triggers the useEffect, resulting in an infinite loop. Defining the function outside of the hook fixes this issue. The TableModal.tsx file has a similar problem with a passed-in function. However, this issue can be fixed by using the useCallback hook.
Manually tested violations and policy management tables
> ROX-15341: Fix for default function prop causing useEffect loop

- .github/workflows/build.yaml
Disable Go dependency caching for operator due to `no space left on device` problems: https://redhat-internal.slack.com/archives/C04KE8ES1MG/p1677507508664539
Also do a forced docker system prune before building to make everything nice and clean...
screenshots.
> fix: don't cache operator go dependencies

- central/alert/datastore/bench_postgres_test.go
- central/alert/datastore/bench_test.go
- central/alert/datastore/datastore.go
- central/alert/datastore/datastore_impl.go
- central/alert/datastore/mocks/datastore.go
- central/pruning/pruning_test.go
Increase alert parallelism due to mutex profile showing lots of slowness
Will run in a scaled cluster
> Increase alert parallelism and cleanup unused functions

- tests/roxctl/bats-tests/cluster/deployment-bundles-psps.bats
- tests/roxctl/bats-tests/local/deployment-bundles-psps.bats
- tests/roxctl/slim-collector.sh
Judging from the failure described in the ticket, 16 bit `$RANDOM` can repeat in a single CI run. Try and make this less likely.
CI should be sufficient. I'll trigger optional jobs since I'm not sure in what cases this is used.
> ROX-14945: make random names more random

- roxctl/image/scan/cve.go
- roxctl/image/scan/cve_test.go
- roxctl/image/scan/scan.go
- roxctl/image/scan/scan_test.go
- roxctl/image/scan/testdata/color_testComponents.json
- roxctl/image/scan/testdata/color_testComponents.txt
- roxctl/image/scan/testdata/testComponents.json
- roxctl/image/scan/testdata/testComponents.txt
The API of `image scan` will return the number of _unique_ CVEs found within the scanned image.
Currently, the "new" output formats `json,table` output the list of _all_ CVEs found, counting duplicates as well.
This caused confusion when comparing the API response to the output of roxctl.
To avoid this confusion, the following has been done:
- count the _unique_ number of CVEs found within the image scan and report this within `json,table` output for roxctl.
- within the warning message, add "unique vulnerabilities" to the output to make things more clear.
Note:
Within the same feedback from customers, there also was initial confusion regarding the number of components: the API responds with the _total_ number of components, whilst roxctl shows the number of vulnerable components. …
> ROX-15277: Report unique CVEs in image scan output

- qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
Grabbed a nginx image (nginx:1.22-alpine) and tagged it as qa:latest. This prevents rate limiting or slow down from docker.io from impacting these tests
this is a test
> ROX-13351: Use an image tagged as latest in quay.io/rhacs-eng for DefaultPoliciesTest

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/hooks/useNetworkPolicySimulator.ts
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkSimulatorActions.tsx
This PR removes the "Apply network policy" option as suggested by Boaz. See https://issues.redhat.com/browse/ROX-15345
> ROX-15345: remove 'Apply network policy' option from UI

- ui/apps/platform/src/Containers/NetworkGraph/components/DeploymentSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NamespaceSelector.tsx
This PR adds a "clear selections" option for network graph namespace and deployment selectors
https://user-images.githubusercontent.com/4805485/221949799-fa0ee7ec-606e-4581-9d78-bcf7678b1743.mov
> ROX-15313: Add clear selections option for network graph namespace and deployment selectors

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/DefaultFilterModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
* The button at the top right corner of the page should be a button
* The button badge should reflect the number of filters set globally
* Clicking on the button should open the Default filters modal
* The modal should look like the above and populate as empty at first
* Clicking the checkboxes and cancelling should not update local storage
* Clicking the checkboxes and hitting the 'Apply filters' button should save the filters to local storage
* Opening the modal on refresh should load the filters saved from local storage
Implementation notes: 
* I saved the empty state to be ```preferences: {
defaultFilters: {
Severity: [],
Fixable: [],
},
},``` because those fields will always exist (vs possibly being empty) and thus it didn't make much sense to omit them in the empty state and end up …
> ROX-15024: Workload CVEs Overview - Default filters modal

- sensor/common/centralclient/client.go
With the introduction of ACSCS, one common environment setup we have seen is a proxy between sensor and central, since central will now not be deployed within the customers environment anymore.
During the initial setup of the secured cluster, sensor will reach out to central to a) retrieve metadata of central via the `/v1/metadata` service and b) retrieve the certificates. Afterwards, the gRPC connection will be established between central and sensor.
Now, when a egress proxy shall be used by sensor to establish communication with central, the following occurs:
```log
common/centralclient: 2023/02/28 18:05:34.041615 grpc_connection.go:79: Info: Check Central status failed: receiving Central metadata: calling https://central-url:443/v1/metadata: Get "https://central-url:443/v1/metadata": …
```
> ROX-15279: Ensure central client respects proxy

- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
Test flakes when an image pull does not complete within the 30x3 retries counter (Timer) are regular enough: https://issues.redhat.com/issues/?jql=labels%20%3D%20CI_Failure_Timeout_Pull. Debug shows that often the pull completes soon after the test fails.
This PR extends the retry counter to 60 retries with a the same 3 second wait between tries. Note: This is still within the 800 second global test timeout. (A somewhat imperfect solution but a flake reducer nonetheless and there is no "image pull is progressing albeit slowly" API call that I could find).
`all-test` + a few flavors. Bumping timeouts can have knock on effects.
> ROX-14222: CI: Increase retries for pod readiness

- .github/actions/cache-go-dependencies/action.yaml
- .github/workflows/style.yaml
This pull request aims to improve the caching process for golangci-lint by separating it from the Go cache. Additionally, the keys used to access the Go cache have been modified to prioritize cache entries from the same job, even if they were created later. Previously, unrelated jobs were occasionally downloading unnecessary cache data, which resulted in "no disk space" errors. By implementing this new approach, we expect to make better use of cached entries since there are infrequent instances where the entire cache needs to be invalidated for the same job. 
- https://github.com/golangci/golangci-lint/discussions/1920
CI
> Optimise usage of Go cache in GHA

- ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSetForm.tsx
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSets.tsx
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSetsList.tsx
- ui/apps/platform/src/Containers/AccessControl/TraitsOriginLabel.tsx
- ui/apps/platform/src/Containers/AccessControl/traits.ts
- ui/apps/platform/src/constants/accessControl.ts
- ui/apps/platform/src/services/AuthService/AuthService.ts
- ui/apps/platform/src/services/RolesService.ts
- ui/apps/platform/src/types/traits.proto.ts
Display origin(System, User or Declarative) in the permission set list view.
> ROX-14702: Display origin in permission sets UI

- central/globaldb/metrics/metrics.go
- central/globalindex/metrics.go
- central/metrics/init.go
- pkg/dackbox/indexer/metrics.go
Declutter prometheus
CI will tell me if I tried to double register something
> Don't register some Bolt and RocksDB metrics when Postgres is enabled

- qa-tests-backend/src/main/groovy/util/Helpers.groovy
The contents of [`default-policies-test-struts-app.json`](https://github.com/stackrox/stackrox/blob/ebcfa1d0dde8813aef1d4e94cda4676565d45f3c/qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy#L152) were being truncated during CI runs - reducing troubleshooting confidence.
The cause of the truncation was the associated Groovy/Java FileWriter's internal buffer was not being flushed. Calling `.close()` on the FileWriter will force a flush of the internal buffer.
This was noticed while investigating `ROX-11612`
Testing locally by creating a Groovy / Spock framework testing sandbox.
A test data file was created via `seq 1 500000 > lotta.txt`
A modified version of the `Helper.collectImageScanForDebug()` was created to reproduce the …
> ROX-11612 - fix image scan debug file truncation

- sensor/common/admissioncontroller/alert_handler.go
- sensor/common/admissioncontroller/message_forwarder.go
- sensor/common/compliance/auditlog_manager_impl.go
- sensor/common/compliance/command_handler_impl.go
- sensor/common/compliance/mocks/auditlog_manager.go
- sensor/common/compliance/node_inventory_handler.go
- sensor/common/compliance/node_inventory_handler_impl.go
- sensor/common/compliance/node_inventory_handler_test.go
- sensor/common/component.go
- sensor/common/config/handler.go
- sensor/common/detector/detector.go
- sensor/common/detector/mocks/detector.go
- sensor/common/enforcer/enforcer.go
- sensor/common/externalsrcs/handler.go
- sensor/common/networkflow/manager/manager_impl.go
- sensor/common/reprocessor/handler.go
- sensor/common/sensor/sensor.go
- sensor/common/signal/signal_service.go
- sensor/kubernetes/admissioncontroller/config_map_persister.go
- sensor/kubernetes/clusterhealth/updater.go
- sensor/kubernetes/clustermetrics/cluster_metrics.go
- sensor/kubernetes/clusterstatus/updater.go
- sensor/kubernetes/eventpipeline/pipeline_impl.go
- sensor/kubernetes/localscanner/tls_issuer.go
- sensor/kubernetes/networkpolicies/command_handler.go
- sensor/kubernetes/telemetry/command_handler.go
- sensor/kubernetes/upgrade/command_handler_impl.go
The idea is to have a mechanism to notify `SensorComponents` when the connection with central is established.
I'm thinking of making the `NotifyReady` function more generic and have something like `Notify(msg)` so we can reuse this for other types of notifications and not just notifying when the connection with central is ready.
Note to reviewers: Consider reviewing the PR by commit. The second and forth are the most interesting 🙂 
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-do …
> ROX-15101 nack to compliance if central connection is not ready

- central/authprovider/service/service_impl.go
- pkg/auth/authproviders/registry_httphandler.go
- pkg/auth/permissions/utils/role.go
- pkg/auth/user/util.go
- pkg/auth/user/util_test.go
Log user identities so that we can later collect them via CloudWatch and thus detect unauthorized access.
We log `ExchangeToken` results as well as it is used in basic auth in the UI(and potentially can be used with other auth providers)
Example of log record:
```
Warn: User successfully logged in with user attributes {"userID": "", "serviceID": "{\"id\":\"a\",\"initBundleId\":\"b\"}", "expires": "2023-02-27T19:22:16.405955Z", "username": "UserID", "friendlyName": "Madonna Slytherin", "roleNames": ["Admin", "Analyst"], "permissions": "{\"id\":\"a\",\"initBundleId\":\"b\"}", "authProvider": {"Id":"","Name":"authProviderName","Type":""}}
```
P.S. The reason to convert `serviceId` and `permissions` to JSON string is to improve readability of these fields. Compare to raw proto formatting:
``` …
```
> ROX-14521: Log user identities which successfully logged in

- sensor/kubernetes/clustermetrics/cluster_metrics_test.go
The test timeout was hit in CI run https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-merge-go-unit-tests-release/1626246342575656960 as detailed in ROX-15157. I could not reproduce the issue, I therefore increased the test timeout to make an accidental hit less likely.
I also noticed that expected and actual result in the assertions were swapped.
> ROX-15157: increase clustermetrics test timeout

- ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopeFormWrapper.tsx
- ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopes.tsx
- ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopesList.tsx
- ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx
- ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProvidersList.tsx
- ui/apps/platform/src/Containers/AccessControl/AuthProviders/RuleGroups.tsx
- ui/apps/platform/src/Containers/AccessControl/Roles/RoleForm.tsx
- ui/apps/platform/src/Containers/AccessControl/Roles/Roles.tsx
- ui/apps/platform/src/Containers/AccessControl/Roles/RolesList.tsx
- ui/apps/platform/src/Containers/AccessControl/traits.ts
- ui/apps/platform/src/constants/accessControl.ts
- ui/apps/platform/src/services/AccessScopesService.ts
- ui/apps/platform/src/services/AuthService/AuthService.ts
- ui/apps/platform/src/services/RolesService.ts
Following up steps and pattern of changes made here https://github.com/stackrox/stackrox/pull/4894, in this PR I add origin field for other resources in the UI: roles, access scopes, auth providers and groups.
As groups are tightly bound to auth provider and are only rendered on the auth provider page, we do not display groups' origin anywhere in the UI. The assumption is that groups and corresponding auth provider always will be of the same type - either both imperative or declarative. The only change made for groups is that groups with `Declarative` origin are impossible to modify or delete within the UI.
For every other resource next changes are introduced:
* `Origin` field is displayed when listing all resources of a certain type
*  Based on `Origin` field resources might be disabled …
> ROX-14702: Display origin for access scopes, roles, auth providers and groups

- central/graphql/resolvers/k8sroles.go
- central/graphql/resolvers/service_accounts.go
Don't double paginate the Service Account and Role endpoints in GraphQL.
Deployed and manually verified that data is correctly returned.
> ROX-15395: Service Account and Role pagination fix

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
This PR fixes an issue where the network graph wouldn't update properly. The following issues should be resolved:
1. When you first go to the network graph, you should see the graph and not an empty screen
2. When selecting namespaces/deployments, the graph should now show the graph updating to reflect the data to be presented
3. Modifying the deployments search filter should update the graph as well
4. Clicking on the "node updates" button should update the graph
https://user-images.githubusercontent.com/4805485/222231937-ca476bed-e4de-4159-b764-f20fd929f18e.mov …
> ROX-15267: Fixing updating issue with network graph

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
This PR hides the filters, time window selector, edge state selectors until a cluster and namespace is selected
> ROX-15406: Do not show filter tool bar when there is no cluster/namespace is selected

- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
- qa-tests-backend/src/main/groovy/util/ChaosMonkey.groovy
- qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
- sensor/admission-control/manager/evaluate_deploytime.go
These are the parts of #4775 which are generally useful for troubleshooting `AdmissionControllerTest` (and potentially other tests too), even if we do not decide to re-enable `ChaosMonkey`, but do not include the `@CompileStatic` changes which are in separate PR #5024 due to their size.
See individual commits' descriptions for more info on each change.
> ROX-7026: `AdmissionControllerTest` troubleshooting improvements

- central/authprovider/datastore/datastore_impl.go
- central/group/datastore/datastore_impl.go
- central/role/datastore/datastore_impl.go
Follow up on https://issues.redhat.com/browse/ROX-14182. Let's also ensure that you can't turn imperative resource into declarative and vice versa.
Unit tests run
> Declarative configuration: forbid overriding resource origin

- pkg/declarativeconfig/auth_provider.go
- pkg/declarativeconfig/auth_provider_test.go
During the testing of the creation of declarative configurations we found out that we currently, by mistake, provide the scheme for the `UIEndpoint / ExtraUIEndpoints` fields.
When doing that, the auth provider will be come unusable, as these fields are meant to be filled in the form of <host>:<port> _without_ the scheme.
Adjusted the comments within the struct as well as the test cases, were we used invalid values for the `UIEndpoint, ExtraUIEndpoints, Mode` fields.
- documentation change without requiring additional tests.
> Ensure the UIEndpoint for declarative auth providers is given without scheme

- central/declarativeconfig/manager_impl.go
We mistakenly only started watches for the "root" directory of declarative configuration (`/run/stackrox.io/declarative-configuration`) instead of watching each specific entry within the directory.
This lead to not receiving any updates within directory.
- manual tests were performed to verify that updates are working properly (see [this PR's description](https://github.com/stackrox/stackrox/pull/5018))
> Fix dir to watch in declarative configuration.

- central/graphql/resolvers/image_cve_core.go
- central/graphql/resolvers/resource_count_by_severity.go
- central/views/imagecve/image_cve.go
- central/views/imagecve/mocks/types.go
- central/views/imagecve/types.go
- central/views/imagecve/view_impl.go
- central/views/imagecve/view_test.go
- Added a generic resource count by severity resolver
- Added `affectedImagesBySeverity` field to cve list resolver
> [VM2.0][ROX-13854] GraphQL resolver for resource count by cve severity

- CHANGELOG.md
API only field, no UI for it, reason/context/history for its existence unknown.
Eyeball only
> ROX-15774: Deprecation changelog entry for expiration field in Excluxion proto

- central/metrics/central.go
- central/metrics/init.go
- central/sensor/service/connection/connection_impl.go
- central/sensor/service/pipeline/all/pipeline.go
Follow up to the safe code
```
pipeline_panics resource=AlertResults                                            24
pipeline_panics resource=Binding                                                 164
pipeline_panics resource=ClusterHealthInfo                                       6
pipeline_panics resource=ClusterStatusUpdate                                     4
pipeline_panics resource=Deployment                                              32
pipeline_panics resource=ImageIntegration                                        2
pipeline_panics resource=Namespace                                               20
pipeline_panics resource=NetworkPolicy                                           22
pipeline_panics resource=Node …
```
> ROX-15399: Add metrics for panics in pipelines

- central/graphql/resolvers/node_vulnerabilities_postgres_test.go
- central/graphql/resolvers/search_test.go
- central/graphql/resolvers/test_setup_utils.go
- central/rbac/service/list_subjects.go
- central/rbac/service/list_subjects_test.go
- pkg/fixtures/role_bindings.go
Subject's search options were updated [#3682](https://github.com/stackrox/stackrox/pull/3682) to include K8sRoleBindings fields as well. However, subject searcher did not allow matching those extra fields and because of this, autocomplete for subjects did not work on role bindings fields. This PR fixes subject searcher to allow matching K8sRoleBinding fields.
Note: This fix is tied to postgres schema for RoleBindings and will only work correctly on postgres. On rocksDB, the search results for role bindings fields will still come out empty. …
> [ROX-13659] : Allow subject searcher to search by roleBinding fields

- central/main.go
- central/telemetry/centralclient/instance_config.go
- pkg/telemetry/phonehome/client_config.go
- pkg/telemetry/phonehome/interceptor.go
This PR adds a functionality to enable or disable (i.e. to use or not to use) a configured central telemetry client.
A telemetry client is configured (`Config.Enabled() == true`) when a storage key is provided via the environment variable.
On top of that, central may decide to not use the configured client if the user tells it so. If there's no key provided, central can not enable the collection.
Following PRs will add an API to trigger the client enablement, and use of a storage to persist the setting.
The envisaged solution is described in more details here: https://docs.engineering.redhat.com/display/StackRox/Opt-out
See #4977 for the API test scenario.
> ROX-15102: Prefactoring, add Enable and Disable functions

- central/cluster/datastore/telemetry.go
Exposing cluster status properties in the secured cluster identity.
Tested manually with local secured cluster so far with disabled provider checks, as the values were empty, as there's no cloud provider.
Example event seen on Segment, notice the `Orchestrator Version` trait:
```json
{
"anonymousId": "1677cf97-e8b2-4ec6-96fd-71427cc40b16",
"context": {
"device": {
"id": "1677cf97-e8b2-4ec6-96fd-71427cc40b16",
"type": "Secured Cluster Server"
},
"groups": {
"Tenant": [
"062c26b6-85d7-4ee8-b690-1e21e94657f3"
]
},
"library": {
},
"traits": {
"Admission Controller": true,
"CPU Capacity": 8,
"Cluster Type": "KUBERNETES_CLUSTER",
"Collection Method": "EBPF",
"Collector Image": "quay.io/stackrox-io/collector",
"Main Image": …
```
> ROX-15419: Secured cluster provider details telemetry

- pkg/telemetry/phonehome/segment/segment.go
- pkg/telemetry/phonehome/segment/segment_test.go
Amplitude, apparently, requires User ID for proper event attribution, and so the idea of missing user ID for backend initiated events didn't work.
This PR modifies the Platform field for events initiated by backends (i.e. if there's no User ID) by adding ` Server` to it (that will be, e.g., "Central Server" for periodic central events), so that we can identify such "users" and events on Amplitude.
```json
{
"anonymousId": "062c26b6-85d7-4ee8-b690-1e21e94657f3",
"context": {
"device": {
"id": "062c26b6-85d7-4ee8-b690-1e21e94657f3",
"type": "Central Server"
},
"library": {
}
},
"event": "Telemetry Disabled",
"messageId": "e6b60a12-68f2-48ac-939d-206021e18c1b",
"originalTimestamp": "2023-03-03T14:45:18.813492105Z",
"receivedAt": …
```
> Telemetry: add "Server" suffix to the Platform for backends

- pkg/telemetry/phonehome/client_config.go
- pkg/telemetry/phonehome/segment/segment.go
This change allows for setting the max batch size parameter for Segment client. We'll set it to 1 in Fleet Manager, so that Group and Track events go in different batches, as otherwise they're more likely to be processed in the wrong order by Segment.
This setting was suggested in the [Segment support ticket 500793](https://segment.zendesk.com/hc/en-us/requests/500793).
This is an internal Segment SDK setting.
> Telemetry: add BatchSize configuration parameter

- central/cluster/datastore/telemetry.go
- pkg/telemetry/phonehome/gatherer.go
- pkg/telemetry/phonehome/gatherer_test.go
- pkg/telemetry/phonehome/segment/segment.go
- pkg/telemetry/phonehome/segment/segment_test.go
- pkg/telemetry/phonehome/telemeter/telemeter.go
* New `WithTraits` option, that allows for passing User properties to events;
* Removed `Identify` calls in favor of `Track(... WithTraits)`.
This change ensures the user properties are updated on Amplitude even when passing through Segment.
An according mapping has been setup in the Amplitude destination to take the Segment event `traits` from `context` and put to `user_properties` Amplitude event field.
Example of an event with traits seen on Segment:
```json
{
"anonymousId": "1677cf97-e8b2-4ec6-96fd-71427cc40b16",
"context": {
"device": {
"id": "1677cf97-e8b2-4ec6-96fd-71427cc40b16",
"type": "Secured Cluster"
},
"groups": {
"Tenant": [
"062c26b6-85d7-4ee8-b690-1e21e94657f3"
]
},
"library": { …
```
> Telemetry: Use Track instead of Identify

- pkg/search/postgres/common.go
Moved the returning of rows.Err() to scanRows to simply make the code a little cleaner.
CI is sufficient for this minor change.
> Dahshrews/minor cleanup in searcher for returning rows.Err()

- central/integrationhealth/datastore/datastore_impl.go
- central/integrationhealth/reporter/health_reporter_impl.go
\+ fail on lack of permissions in upsert/remove integration health operations
Minor improvements to integration health reporter + integration health datastore include:
* replacement of unrestricted access context with context with `Integration`write access
* actively failing on lack of permissions in upsert/delete operations in integration health datastore(thanks @dhaus67 for looking into it first)
The reasons for the last change:
* `UpsertIntegrationHealth` is not called from the UI - all errors will be logged within `health_reporter_impl.go`; if not logged there is no way to notice a lack of permissions
* `RemoveIntegrationHealth` is called when user removes notifier/image integration/backup via UI or API. The reason we assume it is safe to change this behaviour is because:
1.  Deletion …
> Reduce permissions of integration health reporter

- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkPolicies.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceSideBar.tsx
This PR adds an option to show all network policies like in Network Graph 1.0
> ROX-15260: Add option to show all network policies

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphContainer.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
This PR fixes an issue where clicking on a multi-network cidr block node would not show the side panel. The issue happened because the `id` had a `/` in it that confused our URL state. The fix includes encoding/decoding the id
> ROX-15385: Clicking on multi-network cidr block nodes should show the side panel

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphContainer.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css
- ui/apps/platform/src/Containers/NetworkGraph/components/StyleNode.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/topology.type.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.test.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/modelUtils.tsx
This PR adds styling to the nodes to fade out unconnected nodes when a specific node is selected
> ROX-15411: De-emphasizing the unconnected nodes

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/BySeveritySummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/CvesByStatusSummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesImageSinglePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useCveStatusTabParameter.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
Implements the CVE status tab section of the image single page and bare-bones summary cards.
- Implement correct icons and styling for summary cards
- Integrate query with URL search parameters applied by the filter bar
- Integrate summary card "hidden" rendering with URL search parameters
Error state:
Loading state (the blue speck is a spinner):
Rendering at various sizes when the request completes successfully:
> Add status tabs and summary card shells to images single page.

- image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
- image/templates/helm/stackrox-central/values-public.yaml.example.htpl
- image/templates/helm/stackrox-central/values.yaml.htpl
Push the statement_timeout to be 20m as now the timeouts are done via contexts with a default query timeout of 60s and a default cursor timeout of 10m
Should have no impact
> ROX-15332: Change statement_timeout to be 20m

- compliance/collection/intervals/intervals.go
- compliance/collection/intervals/intervals_test.go
- compliance/collection/main.go
- pkg/env/node_scan.go
Use randomized interval durations to determine the initial time to perform first node scanning and subsequent rescanning. Allow these intervals to be configurable through environment variables.
- The initial interval is configurable by a maximum value, uniformly randomized from zero to maximum.
- Rescanning intervals are configurable by "percentage-deviated" random numbers: a base number or average is selected, and a percentage of uniform deviation from that is used. Example: Base 4h. Deviation: 10%. Random interval min to max: 3h36m to 4h24m.
The motivation is to reduce the chances of concurrent scanning and distribute the load on the filesystem I/O, network I/O, Sensor, and Central memory.
Manual deployment and the following logs were …
> ROX-12969: Randomize node scanning intervals

- .github/dependabot.yaml
- .github/workflows/auto-merge.yml
Currently @dependabot PRs are handled by @stackrox/ui-dep-updaters  and @stackrox/backend-dep-updaters this is fine but many times updates are small and could be automatically merged. 
This PR adds automation that will approve and post `@dependabot squash and merge` comment. PR will be merged if all checks pass (not only required ones).
Example: https://github.com/mdn/content/pull/25142#pullrequestreview-1328710625
Tested it on kube-linter
- https://github.com/stackrox/kube-linter/pull/508
> Auto-merge dependabot PRs when all checks pass

- deploy/common/k8sbased.sh
Looks like this was missed in https://github.com/stackrox/stackrox/pull/3230
CI should be sufficient. Let me figure out how to run this on recent k8s...
/test help
> ROX-15812: Propagate `$POD_SECURITY_POLICIES` to `roxctl` when installing sensor.

- sensor/kubernetes/enforcer/cronjob/suspend.go
- sensor/kubernetes/enforcer/zero_replica.go
- sensor/kubernetes/listener/resource_event_handler.go
- sensor/utils/utils.go
- tools/roxvet/analyzers/validateimports/analyzer.go
RHACS falsely claimed that it enforced policies on CronJobs by setting "replicas to 0". However with cron one can only suspend the `CronJob`. Added support to enforce deploy time policies on `CronJob`.
Manually, on GKE and Openshift 4.6 by following steps to reproduce in the JIRA (thanks @msugakov !)
```common/enforcer: 2023/02/20 22:01:55.964640 enforcer.go:135: Info: enforcement successful. action enforcement: SCALE_TO_ZERO_ENFORCEMENTSCALE_TO_ZERO_ENFORCEMENT
deployment: <
deployment_id: "06c8224d-9271-49ad-bc82-25d664d9fda5"
deployment_name: "hello"
deployment_type: "CronJob"
namespace: "boo-test"
alert_id: "dc23ac02-10f3-4807-b8a9-ae30bd3fe934"
policy_name: "Boo Test policy"
>
```
``` …
```
> ROX-15113: Add support to suspend a CrobJob while enforcing a deploy time policy

- sensor/tests/resource/helper.go
We need to defer the call to the `removeNamespace` function to after the namespace is created without error, otherwise `removeNamespace` will be `nil` and the tests will panic in the deferred call.
TODO
> ROX-15823 Fix deferred call in the sensor integration tests

- central/processindicator/datastore/datastore_sac_test.go
- central/processindicator/search/searcher_impl.go
- central/processindicator/search/searcher_impl_test.go
- central/processindicator/store/mocks/store.go
- central/processindicator/store/store.go
Process indicators getting is very expensive. This at least consolidates a couple of these queries, but there is still more to be done to reduce the number of times we're querying
```
13464.446300000001 |  25307 |      35 | 1875541589 | 22945144 | select process_indicators.Id::text as Process_ID from process_indicators where process_indicators.DeploymentId = $1
3308.4725166666667 |   3213 |       9 | 1906889509 | 23272478 | select "process_indicators".serialized from process_indicators where process_indicators.Id = ANY($1::uuid[])
```
CI
> Use GetByQuery in process indicator searcher

- CHANGELOG.md
- roxctl/scanner/generate/generate.go
The PR announces the deprecation of the `--offline-mode` flag within the `roxctl scanner generate` command, as the default behavior for scanner is to retrieve updates via Central anyways.
Created [ROX-15868](https://issues.redhat.com/browse/ROX-15868) as a follow-up to remove the flag within the 4.2.0 release, 2 release after announcing that the flag is deprecated.
> ROX-10242: Remove the offline-mode flag for scanner generate

- .github/workflows/cut-rc.yml
- scripts/ci/lib.sh
- scripts/ci/publish-helm-charts.sh
* Make check for open Jira issues in ongoing release optional. This was helpful during 3.74.0 release, when there were known open issues for documentation while cutting release candidates
* `mark_collector_release` is now idempotent. Previously, when re-running the automation, it would push the same lines multiple times into the RELEASED_VERSIONS file. Later it could fail because the PR already existed. fyi @Molter73 
* `push_helm_charts` does not request review from the obsolete `release-artifact-publishers` group anymore. Reviewing and merging the Helm charts is task of the upstream release engineer and mentioned in the release tracker, therefore the Slack message is not required anymore as well.
> ROX-15158, ROX-15360, ROX-15361: make jira issue check optional, collector released versions idempotent & fix publish-helm-charts

- image/postgres/create-bundle.sh
- image/rhel/create-bundle.sh
From time to time our image build fails due to issues with downloading RPMs with curl. This PR will retry on this failures.
- https://github.com/stackrox/stackrox/actions/runs/4383282481/jobs/7673465480#step:18:107
- https://github.com/stackrox/stackrox/actions/runs/4380270156/jobs/7667224910#step:18:107
- https://github.com/stackrox/stackrox/actions/runs/4353467533/jobs/7607685345#step:18:108
- https://github.com/stackrox/stackrox/actions/runs/4356129018/jobs/7613917425#step:16:108
CI
> Retry curl in create bundle

- qa-tests-backend/src/test/groovy/ImageSignatureVerificationTest.groovy
This PR moves the images used within the image signature tests to quay.io, instead of reyling on other public registries such as `gcr.io, docker.io`.
When the tests were originally written, quay.io did not yet support the cosign OCI metadata type, and hence public images were used.
Now, these images have been moved to the `quay.io/rhacs-eng/qa-signatures` repo, and new cosign signatures have been publish for these images.
The private keys + passphrases of the signatures have been added to BitWarden.
- see CI (tests should still pass).
> ROX-15852: Move images in ImageSignatureTests to quay.io

- .github/dependabot.yaml
We disablet labeler for @dependabot PRs but we can easily add at least some labels 
- https://github.com/stackrox/stackrox/pull/581 
> Label dependabot PRs

- ui/apps/platform/src/reducers/apitokens.js
- ui/apps/platform/src/reducers/clusterInitBundles.js
- ui/apps/platform/src/reducers/integrations.js
- ui/apps/platform/src/sagas/apiTokenSagas.js
- ui/apps/platform/src/sagas/clusterInitBundleSagas.js
Another warm up exercise after returning from week away from code. The following analysis from November 2022.
Found while researching minimum unneeded code in #3759
One more step toward deleting sagas for integrations.
Find dispatch of actions:
* fetchAPITokens: useFetchIntegrations dispatches action
* generateAPIToken: 0 results for `request` action
* revokeAPITokens: IntegrationsListPage dispatches action
* startTokenGenerationWizard: 0 results
* closeTokenGenerationWizard: 0 results
Find reference to selectors:
* getAPITokens: useIntegrations and IntegrationTilesPage
* tokenGenerationWizardOpen: 0 results
* getCurrentGeneratedToken: 0 results
* getCurrentGeneratedTokenMetadata: 0 results
Find dispatch of actions:
* fetchClusterInitBundles: useFetchIntegrations and IntegrationsListPage …
> Delete unneeded actions and selectors in apitokens clusterInitBundles integrations

- central/alert/datastore/datastore_impl.go
- central/alert/datastore/internal/search/searcher_impl.go
- central/alert/datastore/internal/store/mocks/store.go
- central/alert/datastore/internal/store/store.go
- central/graphql/resolvers/deploymentevents.go
- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/namespaces.go
- central/graphql/resolvers/policies.go
- central/graphql/resolvers/violations.go
- central/graphql/resolvers/vul_mgmt_widgets.go
- pkg/search/paginated/options.go
Couple changes needed to be made to allow this to happen, mostly around the searcher wrappers and also moving sorting into the service layer where it is expected. 
CI + Scale test
> Enable alerts to use GetByQuery instead of Search and GetMany

- ui/apps/platform/src/Containers/AccessControl/AccessScopes/EffectiveAccessScopeTable.tsx
See pictures under Testing Performed
Friendly reviewers, what are pro and con of `id` pattern that replaces space (or punctuation) with underscore? It is a pattern that I found clear and effective for a tech doc team to relate file name from page title and `h1` text of Help topics.
Although we use camelCase in code, it feels awkward here:
| Label text | id with underscore | id as camelCase |
| :--- | :--- | :--- |
| Cluster name | `id="Cluster_name"` | `id="clusterName"` |
| Namespace name | `id="Namespace_name"` | `id="namespaceName"` |
1. Investigate react-hooks/exhaustive-deps warning in AccessScopeForm
1. Visit /main/access-control/access-scopes and then click **Create access scope**
2. Click scan in axe DevTools panel
* Form elements must have labels
```html
<input …
```
> Provide labels for cluster and namespace filter input elements

- central/processindicator/datastore/datastore.go
- central/processindicator/datastore/datastore_impl_test.go
- pkg/env/process_pruning.go
This optimization is very expensive and based on some analysis, it is not particularly useful in many environments. Default it to off, but have a way to turn it back on if needed
CI
> Default periodic process pruning via heuristics to false

- central/certgen/service.go
- central/clusterinit/backend/access/access.go
- central/clusterinit/backend/backend_test.go
- central/clusters/identity.go
- central/integrationhealth/service/service_impl.go
- central/main.go
- central/role/datastore/singleton.go
- central/role/resources/list.go
- central/serviceidentities/datastore/datastore_impl.go
- central/serviceidentities/datastore/datastore_impl_test.go
- central/serviceidentities/internal/store/postgres/store.go
- central/serviceidentities/service/service_impl.go
- tools/generate-helpers/pg-table-bindings/list.go
The set resources used for access control is being simplified. A number of resources has been deprecated.
The goal here is to get rid of the deprecated resources, both in the database and in the codebase (UI, QA, central, DB).
This PR focuses on the `ScannerBundle`, `ScannerDefinitions` and `ServiceIdentity` resources in central.
> ROX-12750: Resource grouping - central part for ServiceIdentity, ScannerBundle and ScannerDefinitions

- ui/apps/platform/cypress/helpers/features.js
- ui/apps/platform/cypress/integration/vulnmanagement/clusterCves.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/clusters.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/deployments.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/entitypages.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/imageComponents.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/images.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/namespaces.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/nodeComponents.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/nodeCves.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/policies.test.js
- ui/apps/platform/scripts/cypress.sh
* Cluster/Platform might not have any CVEs let alone fixable CVEs.
* Node might not have any CVEs let alone fixable CVEs.
* Image might not have fixable CVEs: passed here but had failed in #4817
1. Edit cypress/helpers/features.js
* Delete unused default export.
* Add `hasOrchestratorFlavor` function.
2. Edit cypress/integration/vulnmanagement/clusterCves.test.js for 3 / 4 tests:
* should sort the CVSS Score column
* should display vulnerability descriptions
* should display links for clusters
3. Edit cypress/integration/vulnmanagement/clusters.test.js for 3 / 9 tests:
* should display links for fixable image CVEs
* should display links for all node CVEs
* should display links for all cluster CVEs
4. Edit cypress/integration/vulnmanagement/deployments.test.js for 1 / 5 tests:
* should …
> ROX-15886: Skip UI e2e tests that are not relevant for OpenShift

- CHANGELOG.md
- central/compliance/manager/manager_impl.go
- central/compliance/manager/service/service_impl.go
- central/compliance/manager/test/manager_test.go
- central/graphql/resolvers/compliance_management.go
- central/graphql/resolvers/resolver.go
- central/main.go
- central/probeupload/manager/manager_impl.go
- central/probeupload/service/service_impl.go
- central/role/resources/list.go
- central/sac/authorizer/builtin_scoped_authorizer_test.go
- central/sensorupgrade/service/service_impl.go
- central/sensorupgradeconfig/datastore/datastore_impl.go
- central/sensorupgradeconfig/datastore/datastore_test.go
- central/sensorupgradeconfig/datastore/internal/store/postgres/store.go
- tools/generate-helpers/pg-table-bindings/list.go
The set resources used for access control is being simplified. A number of resources has been deprecated.
The goal here is to get rid of the deprecated resources, both in the database and in the codebase (UI, QA, central, DB).
This PR focuses on the AllComments, ComplianceRuns, ProbeUpload and SensorUpgradeConfig resources in central.
~~- [ ] Determined and documented upgrade steps
CI should be sufficient
> ROX-12750: Resource grouping - central part for AllComments, ComplianceRuns, ProbeUpload and SensorUpgradeConfig

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadTableToolbar.tsx
Follow up to quick fix https://github.com/stackrox/stackrox/pull/5170.
Workload CVE single pages do not use default filters, so we set the value to a constant empty `DefaultFilters` object. @alwayshooin you'll want to rebase on top of this once merged since the quick fix causes a useEffect render loop (just for us, only has an impact when rendering Workload CVE pages).
screenshots.
instructions and make sure they are …
> Sets default filters to empty for images single page

- ui/apps/platform/src/Components/PatternFly/SeverityIcons.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/BySeveritySummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/CvesByStatusSummaryCard.tsx
- ui/apps/platform/src/constants/visuals/colors.ts
Adds new colored icons for vuln severities/statuses and implements them in the summary card for the image single page.
View summary card with all data available and no data hidden:
View summary cards with severity results for Important/Moderate, zero results for Critical, and Low being manually disabled. Status card has "Fixable" manually disabled.
> Add CVE severity and status icons to image page summary cards

- scripts/ci/lib.sh
This is missing in the prow "Cluster Versions" summary and it would be useful to have it there. Note: having both kubectl version and oc version introduces some redundancy but I am ok with that.
> CI: Add oc version

- qa-tests-backend/src/test/groovy/ImageSignatureVerificationTest.groovy
Currently, sporadically, the image signature verification tests fail due to timeout issues when fetching the metadata of the image:
```log
image/service: 2023/03/13 15:57:04.735695 service_impl.go:285: Error: error enriching image \"quay.io/rhacs-eng/qa-signatures@sha256:5bc15c838843506f6aaa6fa8d03b8d83f15b936a0362d6732afa0f45135fcf54\": image enrichment error: error getting metadata for image: 
quay.io/rhacs-eng/qa-signatures@sha256:5bc15c838843506f6aaa6fa8d03b8d83f15b936a0362d6732afa0f45135fcf54 errors: [getting metadata from registry: \"core quay\": Failed to get the manifest digest : Head 
\"https://quay.io/v2/rhacs-eng/qa-signatures/manifests/sha256:5bc15c838843506f6aaa6fa8d03b8d83f15b936a0362d6732afa0f45135fcf54\": context deadline exceeded (Client.Timeout exceeded while awaiting …
```
> ROX-15911: Reassess policies in retry for ImageSignatureVerificationTests

- image/templates/helm/stackrox-central/values-private.yaml.example
Found this entry of dbPassword is not in use as of now. It seems to be a leftover from previous solution.
So remove it from public facing doc.
Went through git search for dbPassword and all existing usage is for scanner.
> Remove an unused duplicate db password in public value example

- central/alert/datastore/datastore_impl.go
- central/graphql/resolvers/deploymentevents.go
- central/graphql/resolvers/deployments.go
- central/graphql/resolvers/namespaces.go
- central/graphql/resolvers/policies.go
- central/graphql/resolvers/violations.go
- central/graphql/resolvers/vul_mgmt_widgets.go
- pkg/search/paginated/options.go
Always return a fresh copy of the sort option which can be modified in many places
Hopefully run race tests
> Don't reuse violation time sort option pointer

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#12-8-0
* Added the ability to control whether a request is logged to the command log via `cy.intercept()` by passing `log: false` or `log: true`.
This can be used to override Cypress's default behavior of logging all XHRs and fetches
* It is now possible to control the number of connection attempts to the browser using the `CYPRESS_CONNECT_RETRY_THRESHOLD` Environment Variable.
* Upgraded `mocha-junit-reporter` from `2.1.0` to `2.2.0` to be able to use new placeholders such as `[suiteFilename]` or `[suiteName]` when defining the test report name.
1. Is `mocha-junit-reporter` redundant in ui devDependencies?
2. Are the placeholders useful?
1. `yarn cypress install` in ui/apps/platform
2. `yarn cypress-open` in ui/apps/platform
> Update cypress 12.8.0 devDependencies in ui

- ui/apps/platform/src/Containers/AccessControl/AccessControl.tsx
- ui/apps/platform/src/Containers/AccessControl/accessControlPaths.ts
- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/routePaths.js
- ui/apps/platform/src/utils/URLParser.ts
Besser spät als nie: residue from #5199
Delete before descriptive route configuration.
1. Edit src/Containers/AccessControl/AccessControl.tsx
* Import paths from routePaths.js file.
2. Edit src/Containers/AccessControl/accessControlPaths.ts
* Rename `accessControlBasePathV2` as `accessControlBasePath`
* Delete re-export of renamed paths.
3. Edit src/Containers/MainPage/Body.tsx
* Rename `accessControlPathV2` as `accessControlPath`
4. Edit src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
* Rename `accessControlBasePathV2` as `accessControlBasePath`
5. Edit src/routePaths.js
* Delete obsolete path variable.
* Rename 2 path variables.
```js
export const accessControlPath = `${mainPath}/access`;
export const accessControlBasePathV2 = `${mainPath}/access-control`;
export const …
```
> Delete obsolete accessControlPath in UI

- tests/feature_flag_test.go
Feature flag test broke when I added active vuln mgmt to the flags returned to the UI
Test should pass? Not sure how to get it to run actually
> Fix feature_flag test by accounting for active vuln mgmt

- central/networkbaseline/manager/manager_impl.go
- central/networkbaseline/manager/manager_impl_test.go
- central/networkbaseline/service/service_impl.go
- pkg/networkgraph/networkbaseline/peer.go
Network Baseline info does not show CIDR blocks when the peer is an external source. This PR aims to add that information to the baseline entry, which can be consumed by the FE.
A: It **does** need a migration. I'm working on it on a separate PR that has to be merged before the release. I'm splitting in different PRs because (1) this PR already unblocks the FE for new installations; (2) not having a migration won't crash central, it just won't show the CIDR block for existing baselines (existing behavior); (3) the migration code could be reviewed by people that have more knowledge on the Postgres migration. 
**Update:** here's the PR with the migration: #5252
For more context on the issue, check [this decision doc](https://docs.google.com/document/d/1Tw3mf6dbd_-fwlKwP55xUK7OWVr4fePp8XkzvV2 …
> ROX-14674: Fix duplicate baselines

- operator/Makefile
The `make deploy` target in operators Makefile is always deploying the same image `quay.io/stackrox-io/stackrox-operator:0.0.1`, although it tries to set the image with the `kustomize` CLI tool. It turned out that the `make bundle` stage already replaces the image assumed by the kustomize command executed in `make deploy`. By change the image string asumed by the `make deploy` target it is working properly.
- ~[ ] Unit test and regression tests added~ only dev tooling affected
- ~[ ] Evaluated and added CHANGELOG entry if required~ 
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs- …
> ROX-10901: Fix kustomize image command in operator make deploy target

- README.md
- deploy/central.sh
- deploy/deploy-local.sh
- deploy/deploy.sh
- deploy/detect.sh
- deploy/sensor.sh
- scripts/style/shellcheck_skip.txt
I have used deploy/k8s/deploy.sh a million times on an OpenShift cluster. Add a new script that detects if it's k8s or openshift and then use the right script
Ran on Openshift and GKE
> Detect in deploy scripts if openshift or k8s is used

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/SingleEntityVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesImageSinglePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useImageVulnerabilities.ts
- ui/apps/platform/src/hooks/useSet.test.ts
- ui/apps/platform/src/hooks/useSet.ts
Adds the expandable section to image single page table rows. This section contains another table with details on all image components that are affected by this CVE.
- Figure out why `fixedIn` and `location` fields always return empty strings (BE bug?)
- Figure out why `layerIndex` is always null (BE bug?)
- Reset the expanded/collapsed state on all rows when the table is sorted or paginated (depends on https://github.com/stackrox/stackrox/pull/5258) 
Load an image single page and see that expandable arrows are now present.
Expand a row by clicking on the expand arrow on the left side of the table.
Collapse the row by clicking the arrow again.
Verify that multiple rows can be expanded at the same time.
Verify that a row with multiple …
> Add expandable section for image vulnerability components table

- ui/apps/platform/cypress/integration/risk/risk.test.js
- ui/apps/platform/src/Components/EntityList/EntityList.js
- ui/apps/platform/src/Components/SearchInput/SearchInput.js
- ui/apps/platform/src/Components/URLSearchInput.js
- ui/apps/platform/src/Components/URLSearchInputWithAutocomplete.js
- ui/apps/platform/src/Containers/Clusters/ClustersPage.js
- ui/apps/platform/src/Containers/Compliance/ComplianceSearchInput.js
- ui/apps/platform/src/Containers/Compliance/Entity/Standard.js
- ui/apps/platform/src/Containers/Compliance/List/List.js
- ui/apps/platform/src/Containers/Compliance/List/Page.js
- ui/apps/platform/src/Containers/ConfigManagement/List/List.js
- ui/apps/platform/src/Containers/ConfigManagement/List/ListFrontendPaginated.js
- ui/apps/platform/src/Containers/Network/Header/NetworkSearch.js
- ui/apps/platform/src/Containers/Network/SidePanel/Details/NetworkFlows/NetworkFlowsSearch.js
- ui/apps/platform/src/Containers/Network/SidePanel/NetworkDeploymentOverlay/BaselineSimulation/BaselineSimulationSearch.js
- ui/apps/platform/src/Containers/Network/SidePanel/NetworkDeploymentOverlay/Flows/NetworkBaselines/NetworkBaselinesSearch.js
- ui/apps/platform/src/Containers/NetworkGraph/components/NetworkSearch.tsx
- ui/apps/platform/src/Containers/Risk/RiskPageHeader.js
Solve critical issue from axe DevTools:
> Form elements must have labels
> Element has no placeholder attribute
Indeed, although React Select (or maybe more accurate to say, our use of it) renders a placeholder, `input` element does not have a `placeholder` attribute.
For interest, although not practicality, I verified that React Select 5 might have solved the problem with the `placeholder` prop:
> Placeholder text is now announced.
1. Render `placeholder` prop as `aria-label` attribute in and component that renders an element from ReactSelect, like `SearchInput` component.
2. Pass `placeholder` prop through all levels of application select components.
3. Replace generic default placeholder with specific placeholder that follows the majority **Filter whatevers** grammar pattern, because …
> ROX-16029: Provide aria-label from placeholder for classic search input elements in UI

- ui/apps/platform/cypress/constants/NetworkPage.js
- ui/apps/platform/cypress/helpers/networkGraphPF.js
- ui/apps/platform/cypress/integration/networkGraphPF/networkGraphPF.test.js
- ui/apps/platform/cypress/support/e2e.js
- ui/apps/platform/src/Containers/NetworkGraph/components/ClusterSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NamespaceSelector.tsx
This adds the first basic e2e tests for the new PatternFly Network Graph
1. Navigate to the new graph from the left nav
2. Navigate directly via the URL
3. Select the first cluster in the list and the "stackrox" namespace, and verify that NS group and label are on the graph.
Note: I did not attempt to change the paradigm of the tests from the existing Network Graph test (reusing old selectors and constants where possible). Likewise, I did not try to make the new selectors reusable yet, until we get more tests written.
* Inspect CI results
* Ran test locally
> ROX-13658: Add first basic e2e tests for PF Network Graph

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/BySeveritySummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/CvesByStatusSummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/SingleEntityVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useImageVulnerabilities.ts
- ui/apps/platform/src/hooks/useURLSort.ts
Adds server side sorting and pagination to the image single page table.
- Add appropriate sorting for all fields on the BE is complete and documented in the collab doc
Visit an image single page and verify that a single page worth's of data has loaded. The default sorting of the table should be by Severity, descending.
Use the pagination forward/back buttons to verify that pages of data are changed correctly.
Update the number of items per page and verify that the number of items is changed correctly.
Test that sorting by CVE, Severity, and CVE Status work correctly.
Verify that the CVEs by severity and CVEs by status cards have a total count matching that displayed at the top of the table.
> Add pagination and sorting to image single table

- ui/apps/platform/package.json
- ui/packages/ui-components/package.json
- ui/yarn.lock
https://github.com/microsoft/TypeScript/releases/tag/v5.0.2
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/
> 5.0 is not a disruptive release, and everything you know is still applicable. While TypeScript 5.0 includes correctness changes and some deprecations for infrequently-used options, we believe most developers will have an upgrade experience similar to previous releases.
Selected items:
1. https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters
> In TypeScript 5.0, you can now add a `const` modifier to a type parameter declaration to cause `const`-like inference to be the default.
> A better definition of this function should use `readonly string[]`
The second quote sounded more useful on skim reading.
2. …
> Upgrade TypeScript 5.0.2 devDependencies in ui

- central/group/datastore/datastore.go
- central/group/datastore/datastore_impl.go
- central/group/datastore/datastore_impl_test.go
- central/group/datastore/mocks/datastore.go
- central/group/service/service_impl.go
- central/role/datastore/datastore.go
- central/role/datastore/datastore_impl.go
- central/role/datastore/datastore_test.go
- central/role/datastore/datastore_test_constructors.go
- central/role/datastore/singleton.go
Previously, it was possible to delete role that were referenced by groups in auth providers (potentially also the minimum access role), leading to breaking auth provider's behavior when deleting such a role.
Now, before deleting a role, it will be first checked whether this role is referenced by any groups. If that's the case, an error will be returned indicating the number of groups that reference the role.
Note that this required a minor refactoring in the group datastore: instead of having the filter in `GetFiltered` filter on `storage.GroupProperties`, the filter now works on `storage.Group` (which it should have in the first place).
- see CI (added unit tests, adjusted existing ones).
> ROX-10998: Verify role references in groups before deletion

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
Tuning for test flake in `Verify cluster updates can block flow connections from showing` (`NetworkFlowTest.groovy`)
screenshots.
> ROX-14974: Tune waitForEdgeUpdate time

- pkg/images/enricher/enricher_impl.go
- pkg/images/enricher/enricher_impl_test.go
In `pkg/images/enricher/enricher_impl.go`, func `EnrichImage` gets called for enriching watched images with option `IgnoreExistingImages`. When this option is set, we should not look for existing image in database to populate the image scan. However, we were not checking for that option in `updateImageFromDatabase` . Due to this, watched images were rescanned only when their SHA changed instead of getting rescanned every 4 hours. The fix is to check for `IgnoreExistingImages` in `updateImageFromDatabase` and return without doing db lookup if the option is set. This will force fresh scan, signature and signature verification of image every 4 hours.
- ~[ ] Documented user facing changes …
> [ROX-15808] : Fix for watched images not getting scanned more than once

- ui/apps/platform/cypress/integration/configmanagement/dashboard.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/entitypages.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/policies.test.js
5 tests fail because of assumption that there are fixable vulnerabilities with severity at least important.
Follow up to understand the problem:
* Is there a backend problem?
* Do tests make assumptions about system state that has been true, but is not always guaranteed to be true?
Thanks to Dave Vail:
> Policy failures for deployments that exist before ACS is installed are not detected after installation. (At least for build/deploy policies “Apache Struts: CVE-2017-5638” and “Fixable Severity of at least Important”).
> Note that running the image after installing ACS will correctly fail the policy, as will disabling/enabling the policy.
I just verified disabling/enabling the policy.
> Deploying ACS on a new GKE cluster installs version v3.23.5 of calico-node which has no vulnerabilities …
> Skip failing ui-e2e tests temporarily

- central/main.go
- compliance/collection/main.go
- pkg/metrics/http_server.go
- pkg/metrics/http_server_test.go
- sensor/kubernetes/main.go
- tools/local-sensor/main.go
uptime_seconds metric
```
uptime_seconds                                                                   4850
```
From QA tests
> Add an uptime metric to default prometheus server

- central/authprovider/datastore/datastore_impl.go
- central/authprovider/datastore/datastore_impl_test.go
- central/declarativeconfig/manager_impl.go
- central/declarativeconfig/updater/updater.go
- central/group/datastore/datastore_impl.go
- central/group/datastore/datastore_impl_test.go
- central/role/datastore/datastore.go
- central/role/datastore/datastore_impl.go
- central/role/datastore/datastore_impl_test.go
- central/role/datastore/mocks/datastore.go
- pkg/auth/authproviders/registry_httphandler_test.go
- pkg/auth/authproviders/store.go
This PR is a prefactor for adding deletion to the declarative configuration reconciliation.
Each datastore that will be used during the reconciliation will be updated to implement a `Get...Filtered` function.
This will allow us later do to the following:
- Filter out all resources that are declarative via their `GetTraits().GetOrigin()`
- Filter out all resources that should exist declaratively via their respective IDs.
Note that the group datastore already provides such functionality, thus it was skipped within this prefactor.
- see added unit tests on each datastore.
> ROX-14694: Prefactor datastores used in declarative config to include filter functions

- ui/apps/platform/src/Containers/MainPage/MainPage.tsx
Add public config as another prerequisite from initial requests for conditional rendering that affects all authenticated routes.
I had debated it for header and footer, but now that it affects **analytics**, wait until information is in Redux store to prevent edge cases.
1. GET /v1/featureflags
2. GET /v1/config/public
3. GET /v1/telemetry/config to be determined if this is also a prerequisite to render routes
4. GET /v1/mypermissions
**Brad**: As the implementation of analytics matures with opt-in-out option (what a delightful pun) we need to determine whether frontend **always** makes telemetry config request.
If it **always** makes the request:
1. MainPage might need to wait until availability of analytics is known via response or failure of GET /v1/telemetry/config request.
2. …
> Wait for isLoadingPublicConfig in MainPage

- ui/apps/platform/cypress/constants/TablePagination.js
- ui/apps/platform/cypress/selectors/pagination.js
- ui/apps/platform/src/Components/Pagination/NextPaginationButton/NextPaginationButton.js
- ui/apps/platform/src/Components/Pagination/NextPaginationButton/NextPaginationButton.test.js
- ui/apps/platform/src/Components/Pagination/PrevPaginationButton/PrevPaginationButton.js
- ui/apps/platform/src/Components/Pagination/PrevPaginationButton/PrevPaginationButton.test.js
- ui/apps/platform/src/Components/TablePagination.js
Solve critical issue from axe DevTools:
> Button must have discernable text
Pagination buttons need `aria-label` attribute.
1. Add `aria-label` prop that follows the precedent of PatternFly Pagination element.
* Go to previous page
* Go to next page
2. Use `aria-label` instead of `data-testid` for integration tests.
1. Classic pagination also has color contrast issue.
2. Maybe a moot point that there seems like redundant pagination for classic StackRox:
* src/Components/Pagination/PrevPaginationButton/PrevPaginationButton.js
* src/Components/Pagination/NextPaginationButton/NextPaginationButton.js
* src/Components/TablePagination.js
3. Ditto for integration tests:
* cypress/constants/TablePagination.js
* cypress/selectors/pagination.js
1. axe DevTools
2. `yarn test` in ui/apps/platform
> Provide aria-label for classic Pagination buttons

- sensor/kubernetes/listener/resources/route.go
- sensor/kubernetes/listener/resources/service_store.go
The route handler sends related deploymentReferences to the resolver.
* ~Depends on: #5250~
* Manual tests in an OCP cluster
* e2e tests running in CI
* e2e tests will be enhanced in #5250
> ROX-14436 route handler sends deploymentReference to the resolver

- ui/apps/platform/src/Containers/NetworkGraph/components/LegendContent.tsx
This PR adds the `filtered namespace` and `derived namespace` items to the network graph legend
> ROX-15963: Adding new items to network graph legend

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css
This PR changes the background label color to purple for the `External to cluster` group
> ROX-16015: Change the label background color to purple for the 'External to cluster' group

- pkg/cloudproviders/aws/metadata.go
If we cannot reach the AWS metadata server, we should just assume the cloud provider is not AWS. That is [what we used to do](https://github.com/stackrox/stackrox/commit/2f9cedecd9c31d024f990bed89d63fbc0bc6492e#diff-871049363fb616b0ce9f980b95e7030b5adb464e0341e686460237c0dcd22661R21). #5201 decided to return this as an error, but it should not be an error because it's possible this is not an AWS environment. This PR reverts the returned error. …
> assume cloud provider is not AWS if metadata service unreachable

- qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
The "Verify CVE snoozing applies to images scanned by admission controller us.gcr.io/stackrox-ci/nginx:1.10.1" was failing because the policy creation itself was failing - because the policy category being used does not exist.
Changed to use a pre existing category for the new policy, and asserting on the policy create being successful, before running the actual testcase  scenario.
A bunch of other inline scan related tests were failing because of possible timing issues with the scan. Added a force scan for the image in question in the setup stage to avoid the scan related timing issues.
CI failure, hence CI only.
> ROX-13190,ROX-14595,ROX-15073,ROX-15311: Admission controller e2e test fixes

- .github/workflows/build.yaml
Currently, external contributors won't be able to provide mergable PRs that fulfill all required steps within GitHub actions, due to us currently requiring to push the container image within the build step.
Since external contributors (or, to be more specific, PRs from forks) do not have access to CI secrets, they currently are failing the push step, specifically the docker login part.
Instead of requiring the build step for external contributors to include the push part, I've skipped this for them (for "internal" PRs, i.e. originating from the same repository, the images will still be pushed).
This has the following consequences:
- the workflow will succeed and the PR can be merged.
- all subsequent E2E tests triggered from this PR will fail, due to the image not being available. If the …
> Fix GitHub actions to allow for external contributions

- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaseline.tsx
Current description is misleading:
"Trigger violations for network policies not in the baseline"
It should be replaced by:
"Trigger violations for traffic not in the baseline. This offers soak time for finalizing your network policies, where ACS can alert you on unexpected traffic, while that traffic is not blocked by a network policy"
A picture is worth 1,000 words
> ROX-15449: Enhance description for Alert on Baseline toggle

- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
While doing manual scale testing, I happened to find 2 issues:
1. Very long deployment names crowd the Close (X) in the PatternFly sidebar layout, so I added a max-width to the deployment name in the title, so that long names wrap.
2. If an error occurs while retrieving deployment details--as happened during the scale test, when a deployment was deleted in the background--the page crashed. I coerced the error to a string, and moved down the position of the error message, so that the Close (X) is still visible.
1. Long deployment name wrapping
2. Error message with Close button, instead of page crash
> Fix issues with Deployment Sidebar in Network Graph 2.0

- sensor/kubernetes/fake/deployment.go
- sensor/kubernetes/fake/flows.go
Adds container endpoints to the fake sensor data. These endpoints also have information about the fake processes that "launched" them. The purpose of this is to do load testing of processes listening on ports.
Load testing results and how they were done can be found here https://docs.google.com/document/d/1Es96w-jqYXxxmWDt8Sekm5VN8iMLDqBIkoPmDHwOvH8/edit#
How to see entries in process_listening_on_ports table
Started load similar to https://docs.engineering.redhat.com/display/StackRox/Long-running+cluster with the largest change being that the cluster was not set to run for a long time
Got the postgres password with 
kubectl -n stackrox get secret central-db-password -o yaml
Login to postgres
ks exec -it central-db-<pod-name> -- psql
Use password obtained above
Use the correct database
\c …
> ROX-14912 load testing for processes listening on ports

- ui/apps/platform/src/Containers/Clusters/ClustersPage.js
- ui/apps/platform/src/Containers/SystemConfig/Form/SystemConfigForm.tsx
- ui/apps/platform/src/index.tsx
If a user is opted in to telemetry but later opts out, we can stop emitting events to Segment using the public config flag setup in redux `publicConfig.telemetry.enabled` ([see here](https://github.com/stackrox/stackrox/pull/5247)). However, in this scenario, Segment will still be set up on the page. To completely remove the Segment code at that point, we can reload the page. The new public config telemetry value will prevent Segment from being initialized after the page is refreshed.
With the flag enabled, you can verify segment is initialized in various ways:
* check segments debugger and look for events
* see if `window.analytics` exists
* look for segment/amplitude script tags
Disabling telemetry in the system config should result in …
> Force reload the page to clear out segment code when opted out

- pkg/scanners/clairify/clairify.go
When deploying Central to OCP-4.12 and multiple Secured Clusters (OCP 4.8 - 4.11) using Helm without modifying the default resource attribution and with 2 scanner instances, we got Scanner going up to >10s fairly at 1m at p99:
I want to accommodate those spikes since we don't currently retry Node Inventory, and customers might need to wait up to 4hs, by default, if a timeout like that occurs.
CI.
> Bump node scan timeouts to 1 minute

- operator/hack/common.sh
- operator/hack/operator.envsubst.yaml
Remove code that sets environment variables that are no longer meaningful for the operator since release 3.72.
Operator tests are passing and logs show that `rhacs-eng` images are being used, which is all that matters.
> ROX-11808: Stop setting obsolete env variables.

- pkg/search/parser.go
- pkg/search/parser_test.go
- pkg/search/postgres/query/string_query.go
- pkg/search/postgres/query/string_query_test.go
Trimming values and building new string query do not handle empty strings correctly.
The first one is missing out to extract it out of double quotes due to the length condition (an empty string is `""`, which is exactly the same lenght as 2 * `"`, where the `"` is EqualityPrefixSuffix). This leads to an empty string being represented as `\"\"` along the way, producing incorrect search results.
The second one assumes that an empty string is something incorrect, although it's totally fine to search for values equal empty string.
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs)) …
> Fix handling empty string matches

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesImageSinglePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useImageDetails.ts
Apparently when I pulled the query and types into a custom hook, I never actually pulled the hook body in and just exported an empty, unused function...
Manual testing of image page load.
> Pull image details hook body into hook file

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/DynamicIcon.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/SingleEntityVulnerabilitiesTable.tsx
Adds the dynamic column icon to workload cve table columns that can be impacted by applied data filters.
Includes the "Bolt" icon itself, as well as wrapper components for the most common usages as a label or column header.
Note: The icon in the mocks is titled "Bolt" in font-awesome v6, but the font-awesome v5 bolt that PatternFly uses is slightly different.
The icon and "Filtered view" badge should not be visible when no filters are applied on the page.
When a filter is applied, the "filtered view" badge and bolt column header icons should be displayed.
> Add dynamic column icon to workload cve images table

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/SingleEntityVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesImageSinglePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useImageDetails.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useImageVulnerabilities.ts
- ui/apps/platform/src/configureApolloClient.js
This reverts a previous change in how the queries were structured and moves the images->metadata->v1->layers part of the resolver back to the `imageVulnerabilities` query that is used for the table data. The original change was put in place to avoid an extra request being sent that was due to part of the graphql cache being overwritten, which fixed the extra request but not the overwritten data.
The problem was due to a handful of things:
- The `ImageMetadata` type does not have a unique id, so it cannot be normalized by Apollo's cache
- Since it can't be normalized, it is embedded directly on the `Image` type when a request returns
- When merging items in the cache, Apollo does not recursively merge them, so every returned value of `image->metadata` was replacing the entire `metadata` …
> Add gql client merge function for image metadata field

- .github/workflows/build.yaml
Reverts stackrox/stackrox#5349
The previous PR had two issues:
- the `build-push` action failed as the docker buildx was not setup. Instead of using the `context.with`, I've resorted to using just `if` on the step.
- the `push` event when i.e. merging to master didn't trigger builds, since the `event.pull_request` was not set.
Additionally, also moved to `!github.event.pull_request.head.repo.fork` to indicate that the PR is not coming from a fork, since it seemed more readable.
As a sample, this now does the following on a fork with GitHub actions enabled:
- It will detect that the PR is running on a fork, hence the build jobs will be skipped: https://github.com/dhaus67/stackrox/actions/runs/4502247753/jobs/7924325522
- When merging, the push event will be detected, and the jobs will run …
> Revert "Revert "Fix GitHub actions to allow for external contributions""

- central/declarativeconfig/manager_impl.go
- central/declarativeconfig/manager_impl_test.go
- pkg/env/declarative_config.go
- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
This PR addresses some improvements mentioned within #5186, specifically regarding the reconciliation.
In short, the following has been improved:
- reconciliation will be skipped if a) no changes to messages compared to the previous run b) the previous upsert did not include an error c) the previous deletion did not include an error.
- if the previous upsert included an error, but no changes are indicated in the reconciled messages, only upserts will be retried, deletions will be skipped.
- if the previous deletion included an error, but no changes are indicated in the reconciled messages, only deletion will be retried, upserts will be skipped.
Regarding the change of the reconciliation:
We will retry reconciliation if no changes are made due to the fact that errors have to reach a …
> Skip reconciliation of declarative config for no changes

- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTable.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentFlows.tsx
This PR separates the table under the `Flows` tab into two sections: `Anomalous` and `Baseline`
> ROX-15441: Add anomalous/baseline sections under flows tab

- ui/apps/platform/src/Containers/NetworkGraph/common/AdvancedFlowsFilter/AdvancedFlowsFilter.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/AdvancedFlowsFilter/types.ts
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentBaseline.tsx
- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.test.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.ts
This PR removes the option of filtering by anomalous/baseline flows in the advanced filters. Since we will be separating the anomalous and baseline flows into separate expandable sections (https://github.com/stackrox/stackrox/pull/5351), the need for these filter options will be less useful
Note: I won't branch this off of https://github.com/stackrox/stackrox/pull/5351 as it'll take much longer to get it merged
> ROX-16134: Remove the selection of anomalous/baseline flows from the advanced filters

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphContainer.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTableHeaderText.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/EdgeStateSelect.tsx
This PR replaces the term "extraneous" in the UI. For now, we will change it in the select dropdown and in the table header. We should eventually replace the term within our code as well
> ROX-15850: replace the term 'extraneous'

- central/declarativeconfig/watch_handler.go
- central/declarativeconfig/watch_handler_test.go
There has been an instance where the watch handler test for declarative config has been flaky: https://github.com/stackrox/stackrox/actions/runs/4503411483
Looking at the test in question, it seems like we are missing a call to the `UpdateDeclarativeConfigContents`.
Locally, it was reproducible when running the tests multiple times, i.e. with `-test.count 500`.
The culprit seems to be the low interval we use. Using a more relaxed interval (100ms instead of 10ms) seemed to have fixed the flakiness, at the very least from the first glance locally.
Furthermore did a small QoL change: instead of printing the errors with `%+v` which included too much information, resorted back to `%v`.
- unit tests.
> Fix flaky watch handler test

- deploy/common/k8sbased.sh
- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
- tests/e2e/lib.sh
Currently, release builds are failing after #5266 . The reason is the change for declarative config within the deploy scripts.
We currently only verify whether the feature flag is passed, but not whether the build is a release build, since the command will not be available for the release build irrespective of the feature flag being set or not.
We conditionally only set `ROX_DECLARATIVE_CONFIGURATION` to true if `BUILD_TAG == ""`.
screenshots.
In addition to reviewing your code, reviewers **must** …
> Fix declarative config tests for release builds

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
- ui/apps/platform/src/hooks/useURLSort.ts
Adds an optional callback option to the `useURLSort` hook so that we can reset the current table page when a column is sorted.
Visit the image page and increment the page of the data table.
Sort a column and ensure the table page returns to 1.
> Reset current page for images table when a column is sorted

- ui/apps/platform/src/Components/ContainerArgumentsInfo.tsx
- ui/apps/platform/src/Components/ContainerCommandInfo.tsx
- ui/apps/platform/src/Components/ContainerImageInfo.tsx
- ui/apps/platform/src/Components/ContainerResouresInfo.tsx
- ui/apps/platform/src/Components/ContainerSecretsInfo.tsx
- ui/apps/platform/src/Components/ContainerVolumesInfo.tsx
- ui/apps/platform/src/Components/DeploymentContainerConfig.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.css
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx
- ui/apps/platform/src/css/trumps.css
This adds the container information to the Deployment details tab of the Network Graph 2.0 sidebar.
Container name and Resources
Volumes
Secrets
Arguments and Commands
> ROX-16129: Add container info to NG 2.0 deployment details

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphContainer.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css
- ui/apps/platform/src/Containers/NetworkGraph/components/StyleGroup.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/topology.type.ts
This PR fixes an issue when selecting a namespace or external group node. The group nodes were not faded out correctly
> ROX-16159: Fix styling issues when selecting a namespace or external group

- pkg/scanners/clairify/convert.go
- pkg/scanners/clairify/convert_test.go
If the field `Features` exists and is populated, it should include all the required components in the scanned inventory, and using the metadata to populate components is redundant and unnecessary. It is only relevant if performing non-host-level node scanning.
UTs and manual testing. Cluster `jvdm-argilo`, screenshot:
> ROX-16158: Don't populate components from node metadata if Features are provided

- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
Fixes the initialization error here: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-nightlies-gke-qa-e2e-tests/1640223063058419712
> Fix declarative config test annotation

- ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopesList.tsx
- ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProvidersList.tsx
- ui/apps/platform/src/Containers/AccessControl/AuthProviders/RuleGroups.tsx
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSetsList.tsx
- ui/apps/platform/src/Containers/AccessControl/Roles/RolesList.tsx
- ui/apps/platform/src/Containers/AccessControl/TraitsOriginLabel.tsx
- ui/apps/platform/src/Containers/AccessControl/traits.ts
* Show origin as simple text instead of the label in list view
*  show origin for groups + info icon with explanation for unmodifiable groups
> Adjust UI for Origin field in access control resources

- image/templates/common/port-forward.sh
Bind to `0.0.0.0` to allow calling local proxy from containers.
CI
> bind to 0.0.0.0 on port-forward

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useImageVulnerabilities.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
- ui/apps/platform/src/types/cve.proto.ts
- ui/apps/platform/src/utils/searchUtils.test.js
- ui/apps/platform/src/utils/searchUtils.ts
Integrates the WorkloadTableToolbar search filter with the images single page table.
Apply a severity filter and see it reflected in the URL, summary cards, and table:
Apply another severity filter and a fixable filter and see them reflected in the URL, summary cards, and table:
Apply entity filters and see them reflected in the URL (none of the data is impacted by these filters in my environment)
Verify that the entity filters are correctly sent as part of the query:
> Integrate workload cve image single page table with search filter

- central/alert/datastore/bench_postgres_test.go
- central/alert/datastore/datastore.go
- central/alert/datastore/datastore_impl.go
- central/alert/datastore/datastore_sac_test.go
- central/alert/datastore/mocks/datastore.go
- central/alert/service/service_impl.go
- central/alert/service/service_test.go
- central/risk/getters/alert.go
- central/risk/getters/alert_mock.go
- central/risk/multipliers/deployment/violations.go
- central/risk/multipliers/deployment/violations_test.go
- central/risk/scorer/deployment/scorer.go
- central/risk/scorer/deployment/scorer_test.go
```
percent | exec_min | max_time | mean_time |  calls   |   rows   |                                                                query                                                                
---------+----------+----------+-----------+----------+----------+-------------------------------------------------------------------------------------------------------------------------------------
5 |      129 |      386 |         1 | 14833342 | 61640777 | select "alerts".serialized from alerts where (alerts.Deployment_Id = $1 and (alerts.State = $2)) order by alerts.Time desc LIMIT $3
```
Can remove the sort for this query which is due to risk
```
central_active=# explain analyze select serialized from alerts where state = 0 and deployment_id = '4790c16b-af89-4fae-9809-10e06de4f84e' …
```
> Remove ListAlert function from datastore that used v1.ListAlertRequest

- qa-tests-backend/src/test/groovy/VulnMgmtSACTest.groovy
Remove the scanner data added in #4856 since no repro has occurred. Increase the retries on each of the tests in the suite to allow for additional timing if necessary.
If failure persists we should consider a rescan of the images.
> ROX-15936: up retry count on image vuln role scoping tests

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCveSummaryCards.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageSingleVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/BySeveritySummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/EnvironmentalImpact.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/TopCvssScoreBreakdown.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
- ui/apps/platform/src/configureApolloClient.js
This adds summary cards to the ImageCVE single page.
Load a CVE page:
Apply search filters and observe that the total number of images in the ""Environmental impact" card as well as the labels in the "By severity" card are updated. *Note that the actual values here are _wrong_, since the BE query support is not fully merged yet*
Query error state:
Loading state:
Small screen views:
> Add ImageCVE page summary cards

- qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
- qa-tests-backend/src/test/groovy/AttemptedAlertsTest.groovy
- qa-tests-backend/src/test/groovy/AuditLogAlertsTest.groovy
- qa-tests-backend/src/test/groovy/BuiltinPoliciesTest.groovy
- qa-tests-backend/src/test/groovy/ComplianceTest.groovy
- qa-tests-backend/src/test/groovy/DeploymentEventGraphQLTest.groovy
- qa-tests-backend/src/test/groovy/DeploymentTest.groovy
- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
- qa-tests-backend/src/test/groovy/K8sEventDetectionTest.groovy
- qa-tests-backend/src/test/groovy/PolicyConfigurationTest.groovy
- qa-tests-backend/src/test/groovy/VulnMgmtWorkflowTest.groovy
This PR intends to add multi-arch support for the groovy tests.
> Use multi-arch test images & few changes

- go.mod
- go.sum
- pkg/gjson/modifiers.go
- pkg/gjson/modifiers_test.go
- pkg/gjson/utils.go
- pkg/printers/sarif.go
- pkg/printers/sarif_test.go
- pkg/printers/testdata/sarif_report.json
- roxctl/common/printer/objectprinter_factory.go
- roxctl/common/printer/sarifprinter_factory.go
- roxctl/common/printer/sarifprinter_factory_test.go
- roxctl/deployment/check/check.go
- roxctl/image/check/check.go
- roxctl/image/scan/scan.go
This PR adds the SARIF output format to roxctl.
The [SARIF output format](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html) is a standard for analysis tools to share their results. Most notably, its required by GitHub to support publishing code scanning results ([more info can be found here](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning)).
The following are noteworthy changes within this PR:
- a new custom modifier for gjson has been added: `@text`, which creates a single text from a JSON object. This is used to create a multiline help message within the SARIF report consisting of multiple values (e.g. a component's CVE, name, version, fixed version).
- a new printer that is capable of printing SARIF …
> ROX-15462: Add sarif output format to roxctl

- .github/workflows/build.yaml
`push` option for `build-push` action is `false` by default. This means we need to set it to true in order to build and push images.
CI
> Push rcd and mock-grpc on build

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#12-9-0
* Fixed an issue where `cy.intercept()` added an additional `content-length` header to spied requests that did not set a `content-length` header on the original request.
> Update cypress 12.9.0 devDependencies in ui

- central/telemetry/centralclient/instance_config.go
Telemetry configuration must take into account the `ROX_OFFLINE_MODE` setting. This PR makes the central to skip telemetry initialization when this setting is set to true.
```sh
$ kubectl get deploy/central -o json | jq ".spec.template.spec.containers[0].env[3,9]"
{
"name": "ROX_OFFLINE_MODE",
"value": "true"
}
{
"name": "ROX_TELEMETRY_STORAGE_KEY_V1",
"value": "abc"
}
$ kubectl logs deploy/central | grep tele
telemetry/centralclient: 2023/03/29 08:53:00.909162 instance_config.go:107: Info: Phonehome telemetry collection disabled.
```
> ROX-16231: Respect the ROX_OFFLINE_MODE setting

- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
- qa-tests-backend/src/test/groovy/VulnReportingTest.groovy
This PR intends to skip few of the groovy tests related to slack notifications on P/Z.
> Skip slack notification related tests on P/Z

- CHANGELOG.md
- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
This reverts https://github.com/stackrox/stackrox/pull/4534 which is itself a revert of https://github.com/stackrox/stackrox/pull/4366
The change was reviewed and approved in https://github.com/stackrox/stackrox/pull/4366 so I will be happy with just a rubber-stamp approval to be able to merge.
These not done or not needed:
* Was tested in https://github.com/stackrox/stackrox/pull/4366. Here - only CI.
> ROX-14280: Describe the `stable` operator channel

- qa-tests-backend/src/test/groovy/CSVTest.groovy
This PR intends to make CSVtest multi-arch compliant using MA images for test execution
> Make CSVTest multi-arch compliant

- qa-tests-backend/src/test/groovy/ProcessesListeningOnPortsTest.groovy
- sensor/common/networkflow/manager/manager_impl.go
- sensor/common/networkflow/manager/manager_impl_test.go
An e2e test where a processes which is listening on a port is killed and there is an assert to check that the listening endpoint no longer appears in the API. Also adds unit tests. These tests revealed some bugs which were fixed by https://github.com/stackrox/stackrox/pull/5358
The above PR was merged into this one.
Deploy stackrox locally or connect to a cluster running stackrox
```
cd qa-tests-backend
export ROX_POSTGRES_DATASTORE=true
```
That directory should have a file, qa-test-settings.properties with the following contents
```
export REGISTRY_USERNAME=*********@redhat.com
export REGISTRY_PASSWORD="*******************"
```
If this the first time you are running the tests or you made some changes to the tests or generated files you might or might not need to run the following
``` …
```
> Jv rox 16074 process listening on ports e2e test to check for closed ports

- .github/workflows/cut-rc.yml
Cherry-pick of https://github.com/stackrox/test-gh-actions/pull/92
... otherwise jobs depending on `check-jira` are also skipped. 
Failed job: https://github.com/stackrox/stackrox/actions/runs/4551026838
Working as expected (failure because release-0.0 branch does not exist)
* with checking jira issues: https://github.com/stackrox/test-gh-actions/actions/runs/4551134738/jobs/8024859527
* without: https://github.com/stackrox/test-gh-actions/actions/runs/4551134903/jobs/8024865314
You can also see the difference when checking the output or by clicking on the [Check Jira tickets for release](https://github.com/stackrox/test-gh-actions/actions/runs/4551134903/jobs/8024865314#logs) box. 
Tested in …
> move jira conditional check to step instead of job level

- central/clusters/zip/render_test.go
- compliance/collection/main.go
- image/templates/helm/stackrox-secured-cluster/templates/collector.yaml
- pkg/env/node_scan.go
As per https://github.com/stackrox/stackrox/pull/5422, we are not creating the node-inventory container on clusters that are not Openshift 4. Compliance is able to handle the unavailability of this container, but it will result in errors in the logs. In order to avoid polluting the logs, we can instruct compliance to not attempt to call the node-inventory when we know that it is not there.
The approach from this PR is to keep the `nodeInventoryClient` uninitialized on clusters other that Openshift 4. This results in skipping the `manageNodeScanLoop` that would normally do the call to node-inventory.
```
main: 2023/03/30 14:35:35.223335 main.go:264: Info: Compliance will not call the node-inventory container, because this is not Openshift …
```
> ROX-16169: Compliance shall be calling node inventory only on Openshift 4

- .github/workflows/build.yaml
From time to time if `style` fails the cache is not populated. This results with not generating image due to following error:
> ossls audit --export image/THIRD_PARTY_NOTICES
Processing JS deps directories: [ui/node_modules ui/apps/platform/node_modules ui/packages/ui-components/node_modules ui/packages/tailwind-config/node_modules] 
ossls: failed to locate js dependencies in dirs [ui/node_modules ui/apps/platform/node_modules ui/packages/ui-components/node_modules ui/packages/tailwind-config/node_modules]: failed to walk ui/node_modules: lstat ui/node_modules: no such file or directory
This PR explicitly downloads UI dependencies to not rely on cache. 
Refs:
- https://github.com/stackrox/stackrox/actions/runs/4539789916/jobs/8000175814?pr=5411 …
> Fetch UI deps to generate OSS notice

- ui/apps/platform/src/Components/TablePagination.js
Solve serious issue from axe DevTools on classic pages which have paginated tables
Light mode contrast ratio is less than 4.5
| class | hex | ratio |
| ---: | ---: | ---: |
| `text-base-500` | `#a1a1a1` | 2.58 |
| `text-base-600` | `#6e6e6e` | 5.09 |
Dark mode contrast ratio is sufficient but see below
1. Inherit color and font-weight from ancestor page style.
* Delete `text-base-500 font-500` from `div` element.
2. Specify color for elements that have PatternFly style rules:
* Replace `text-base-900` with `text-base-600` for `input` element.
* Add `text-base-600` for first `button` element, especially to prevent inconsistency from seeming to imply enabled versus disabled state. Even worse, absence of class caused the button to (seem to) …
> Provide sufficient color contrast in classic pagination

- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
As was requested in https://issues.redhat.com/browse/ROX-14483
Note that Daniel Messer suggested
`"['OpenShift Platform Plus', 'Red Hat Advanced Cluster Security']"`
whereas the examples in the official documentation combine single- and double- quotes differently.
See https://docs.openshift.com/container-platform/4.10/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs
Example given there:
`'["3Scale Commercial License", "Red Hat Managed Integration"]'`
Choosing between two formats I decided for the latter provided that's the style already used for
`operators.openshift.io/infrastructure-features` attribute.
- ~[ ] Evaluated and added CHANGELOG entry if required~ - theoretically, we can enter this in the changelog but I'm not sure what this …
> ROX-14483: Add operator subscription annotation

- deploy/common/deploy.sh
Disable re-sync when deploying using deploy scripts. It should work for both k8s and OpenShift.
Many for the last 6 months
> Disable re-sync for deploy.sh

- ui/apps/platform/src/Components/PatternFly/FixabilityIcons.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCveSummaryCards.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/AffectedImages.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/BySeveritySummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/SingleEntityVulnerabilitiesTable.tsx
This adds the Images data table on the ImageCVE single page.
It also makes a couple of semi-related tweaks on the same page:
- Abstract out the fixability icons to avoid copy/pasting
- Rename the "Environmental impact" summary card
There are many TODOs throughout this section that need to be broken out into subtasks. Most of them are either verifying with the BE team that field usage is correct, or filling in details that will not cause a large structural change.
Load an ImageCVE page. The default entity tab should be "Images" instead of "Deployments". (TBD for the UI component, but is implemented in the logic.)
Request loading state:
Request error state:
Request complete state:
Test that the table does not load when the `entityTab` …
> Add images table for CVE single page

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/CveStatusTabNavigation.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/EntityTypeToggleGroup.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCvePage.tsx
Integrates the EntityTypeToggleGroup component.
I did find an issue unrelated to this change that needs to be fixed as a [follow up](https://github.com/stackrox/stackrox/pull/5458):
The image and deployment queries are only run when their tab is active, by design, to avoid the unnecessary overhead of loading data for both tabs. However, this means that the image/deployment counts are not updated when their tab is not active i.e. when filters change. I'll likely need to restructure these queries a bit.
Load the ImageCVE page, and see that the default URL parameter is "Image", and the "Image" tab is selected. The "CVE" tab should not render and the total image count should be visible.
Clicking the Deployments tab hides the images tab and …
> Integrate ImageCVE page with EntityTypeToggleGroup

- ui/apps/platform/src/Components/DeploymentContainerConfig.tsx
- ui/apps/platform/src/Components/SecurityContext.tsx
- ui/apps/platform/src/utils/securityContextUtils.test.js
- ui/apps/platform/src/utils/securityContextUtils.ts
Revised requirements:
1. Because the only security context currently available in the Deployment API is at the container level, this ticket will focus on adding security context in each container section of the Deployment Details.
2. In the NG 1.0 implmentation, we limited the Security Context we showed to only Add Capabilities, Drop Capabilities, and Privileged. We will not impose that limit in this implementation–if a security context setting is not empty/null, we will show it.
3. We will not show security context settings that are empty/null.
4. If none of the security context settings are set, we will simply display "No security context
Manual testing
Examples (from the three containers within the StackRox `collector` pod
collector container:
compliance container (a different set of …
> ROX-15448: Add security context to containers displayed in details of NG 2.0

- ui/apps/platform/cypress/constants/NetworkPage.js
- ui/apps/platform/cypress/integration/risk/risk.test.js
- ui/apps/platform/src/Components/URLSearchInputWithAutocomplete.js
Solve serious issue from axe DevTools on classic and PatternFly pages which have search filter
Contrast ratio of `text-base-500` is less than 4.5
| mode | foreground | background | ratio |
| :--- | ---: | ---: | ---: |
| light | `#a1a1a1` | `#ffffff` | 2.58 |
| dark | `#6e6e6e` | `#3b3b3b` | 4.33 |
Because axe DevTools does not require the same color contrast for placeholder text as for ordinary text, replace `span` with `input` element that has `placeholder` and `readonly` attributes.
Also verified on Safari 16.3 and Firefox Developer Edition 110.0b8
**Light** mode insufficient contrast with `span` element
**Light** mode with `input` element
**Dark** mode insufficient contrast with `span` element
**Dark** mode with `input` element
We could …
> Provide sufficient color contrast for placeholder in search filter

- ui/apps/platform/src/Containers/Integrations/IntegrationTilesPage/IntegrationTile.tsx
Solve minor issue from axe DevTools on Integrations page:
> Alternative image alternative is not repeated as text
https://dequeuniversity.com/rules/axe/4.6/image-redundant-alt?application=AxeChrome
For example, given the icon markup `<img alt="Home Page"/>`, the adjacent text also says "Home Page".
In such a scenario, a screen reader will announce this content to the user as "Home Page Home Page". The redundancy is unnecessary and potentially confusing.
In this scenario, the icon image's `alt` attribute value is better left empty by setting `alt=""`.
Hard to say why axe DevTools reports the problem for only 14 of the images.
1. Replace `alt={label}` with `alt=""` prop.
2. Replace deprecated `isHoverable` with `isSelectableRaised` prop
https://www.patternfly.org/v4/components/card#card
> …
> Remove redundancy from alt attribute in integration tile images

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadTableToolbar.tsx
- ui/apps/platform/src/hooks/useURLParameter.ts
- ui/apps/platform/src/hooks/useURLSearch.ts
- ui/apps/platform/src/hooks/useURLStringUnion.ts
The `useURLSearch` and `useURLStringUnion` hooks that wrap `useURLParameter` for specific use cases did not expose the optional `history` argument, which defaults to the `push` action. This was causing multiple history writes when the URL was syncing with local storage that broke back navigation.
This exposes the history option on those two hooks so that we can `replace` history when syncing state in `useEffect` hooks, and use the default of `push` when the URL change is the result of a user action.
- Visit Workload CVE main page and apply default filters
- Visit any number of other pages in the app
- Visit Workload CVE main page and apply local filters
After doing this, navigating backwards should result in one history …
> Allow 'replace' instead of 'push' to URL history when synchronizing values.

- image/postgres/scripts/docker-entrypoint.sh
Add flock to the DB initialization to avoid multiple instances using the mount at the same time. RWO volumes can have multiple pods on the same node utilize a mount point. This has lead to potential overlap of postgres processes that lead to corruption as they are both accessing the data at the same time (one is shutting down and the other is starting up). Reference https://github.com/kubernetes/kubernetes/issues/29855#issuecomment-384099479. This may also just occur on GCP
No corruption so far on runs with flock
> Add flock to DB initialization

- ui/apps/platform/cypress/integration/systemConfig/systemConfig.selectors.js
- ui/apps/platform/cypress/integration/systemConfig/systemConfig.test.js
- ui/apps/platform/src/Components/ColorPicker.js
- ui/apps/platform/src/Containers/SystemConfig/Details/PublicConfigBannerDetails.tsx
- ui/apps/platform/src/Containers/SystemConfig/Form/SystemConfigForm.tsx
Solve critical issue from axe DevTools on System Configuration page:
> Buttons must have discernable text
1. Make `id` prop required.
2. Replace `data-testid` with `aria-label` prop.
3. Update selectors for integration tests.
1. Reduce redundancy between details and form.
* For example, PatternFly read-only text input form element for data retention details?
Without `aria-label` attribute
With `aria-label` attribute
1. `yarn start` in ui folder
2. `yarn cypress-open` in ui/apps/platform folder
* systemConfig/systemConfig.test.js
> Provide aria-label for ColorPicker button in System Configuration

- ui/apps/platform/src/Containers/Violations/violationTableColumnDescriptors.tsx
Solve serious issue from axe DevTools in Search results table:
Aha, 16 results but only 9 issues because axe DevTools does not analyze the table rows that are scrolled out of view?
Contrast ratio of `pf-u-color-400` is less than 4.5
Contrast ratios for foreground colors on `#ffffff` background color:
| class | color | ratio |
| ---: | ---: | ---: |
| `pf-u-color-100` | `#151515` | 18.26 |
| `pf-u-color-200` | `#6a6e73` |  5.13 |
| `pf-u-color-300` | `#3c3f42` | 10.59 |
| `pf-u-color-400` | `#8a8d90` |  3.33 |
https://webaim.org/resources/contrastchecker/
Thanks to Dave Vail for investigating and recommending `pf-u-color-200` utility class.
1. Investigate **Table header text should not be empty** issue.
Visit /main/violations
Insufficient …
> Improve color contrast in Violations table

- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
This PR intends to make ImageManagementTest multi-arch compliant using MA images for test execution
> Make ImageManagementTest multi-arch compliant

- ui/apps/platform/src/Containers/Search/NotApplicable.tsx
- ui/apps/platform/src/Containers/Search/SearchTable.tsx
Solve serious issue from axe DevTools in Search results table:
Contrast ratio of `pf-u-color-400` is less than 4.5
Contrast ratios for foreground colors on `#ffffff` background color:
| class | color | ratio |
| ---: | ---: | ---: |
| `pf-u-color-100` | `#151515` | 18.26 |
| `pf-u-color-200` | `#6a6e73` |  5.13 |
| `pf-u-color-300` | `#3c3f42` | 10.59 |
| `pf-u-color-400` | `#8a8d90` |  3.33 |
https://webaim.org/resources/contrastchecker/
Thanks to Dave Vail for investigating and recommending `pf-u-color-200` utility class.
1. Improve color contrast for blue **Namespace: stackrox** in search filter.
2. Investigate **Elements must use only allowed ARIA attributes** issues.
Visit /main/search?s[Namespace]=stackrox
Insufficient color contrast …
> Improve color contrast in Search results table

- ui/apps/platform/cypress/helpers/networkGraphPF.js
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css
- ui/apps/platform/src/Containers/NetworkGraph/components/DeploymentSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NamespaceSelector.tsx
- ui/apps/platform/src/utils/removeNullValues.ts
This PR makes the search bar sticky in the namespace/deployment selectors. Because this is not naturally possible to do with the `Select` component, we had to make use of the `customContent` prop to display a `Menu` the same way it functions as it does today
Note: We can refactor the selectors to be more reusable (possibly making an `EntitySelector` component), but in order to keep the PR light, and considering future edge cases, we won't do that right now
https://user-images.githubusercontent.com/4805485/228352245-b2c08378-3b35-4a4e-84a2-2c2274412fc6.mov
> ROX-15402: Change to a sticky search bar in the breadcrumb

- ui/apps/platform/cypress/constants/RiskPage.js
- ui/apps/platform/cypress/constants/VulnManagementPage.js
- ui/apps/platform/cypress/helpers/vulnmanagement/entities.js
- ui/apps/platform/cypress/integration/clusters/clusters.test.js
- ui/apps/platform/cypress/integration/compliance/complianceList.test.js
- ui/apps/platform/cypress/integration/configmanagement/ConfigurationManagement.helpers.js
- ui/apps/platform/cypress/integration/networkGraph/tooltip.test.js
- ui/apps/platform/cypress/integration/risk/risk.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/entitypages.test.js
- ui/apps/platform/cypress/selectors/panel.js
- ui/apps/platform/src/Components/Button/Button.js
- ui/apps/platform/src/Components/CloseButton.js
- ui/apps/platform/src/Components/CollapsibleSection/CollapsibleSection.js
- ui/apps/platform/src/Containers/ConfigManagement/SidePanel/SidePanel.js
- ui/apps/platform/src/Containers/Workflow/WorkflowSidePanel.js
1. Solve critical issue from axe DevTools on pages that have classic side panels:
> Buttons must have discernable text
2. Solve serious issue from axe DevTools on pages that have classic side panels:
> Links must have discernable text
1. src/Components/CloseButton.js
```html
<button type="button" class="flex p-3 text-center text-sm items-center " data-testid="cancel" id="panel-close-button">
```
2. src/Components/CollapsibleSection.js
```html
<button type="button" class="" data-testid="collapsible-btn">
```
3. src/Containers/ConfigManagement/SidePanel.js and src/Containers/Workflow/WorkflowSidePanel.js
```html
<a data-testid="external-link" class="border-base-400 border-l h-full p-4" href="/main/configmanagement/cluster/fdf2741d-f5c9-4214-8355-b467d02b8a9c">
```
1. Delete `id` and replace …
> Provide aria-label for buttons and links in classic side panels

- ui/apps/platform/src/Containers/SystemConfig/Details/PublicConfigTelemetryDetails.tsx
- ui/apps/platform/src/Containers/SystemConfig/Details/SystemConfigDetails.tsx
- ui/apps/platform/src/Containers/SystemConfig/Form/SystemConfigForm.tsx
- ui/apps/platform/src/reducers/telemetryConfig.js
Enable telemetry by default by allowing null/undefined to equate to true
Running fresh deployment results in telemetry defaulting to enabled
> ROX-16322: Telemetry should be enabled by default

- qa-tests-backend/src/test/groovy/CSVTest.groovy
`@Unroll` adds test args to the test name which makes that difficult to use in issue tracking. IIRC adding a parameter to the name string will skip the default behavior. Tests will tell
> CI: Label CSVTest

- CHANGELOG.md
- central/reprocessor/reprocessor_unit_test.go
- central/sensor/service/pipeline/all/factory.go
- central/sensor/service/pipeline/nodes/pipeline_test.go
- compliance/collection/main.go
- pkg/env/node_scan.go
- pkg/features/list.go
- pkg/nodes/enricher/enricher_impl.go
- sensor/common/compliance/service_impl.go
- sensor/kubernetes/sensor/sensor.go
This PR changes the RHCOS NodeScanning feature flag to an env variable, that is *enabled* by default.
We keep the env variable in order to have a possibility to disable the feature in case something unexpected would happen.
Moreover, we remove the no longer used FakeNodeScanner from this repo (it still needs to be removed from the scanner repo).
⚠️ We need a similar PR for the Scanner repo ⚠️ 
> ROX-13935: Enable RHCOS FF & add a failsafe switch

- central/sensor/service/pipeline/nodeinventory/pipeline.go
- compliance/collection/intervals/intervals.go
- compliance/collection/main.go
- sensor/common/compliance/node_inventory_handler_impl.go
This PR rephrases log messages concerning RHCOS, so that they are:
- not polluting the logs too much
- more informative
⚠️ We need a similar PR for the Scanner repo ⚠️ 👉 https://github.com/stackrox/scanner/pull/1146
> ROX-14358: Ensure RHCOS logging is informative

- ui/apps/platform/src/Containers/AccessControl/AccessScopes/LabelSelectorCard.tsx
- ui/apps/platform/src/Containers/AccessControl/Roles/AccessScopesTable.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTable.tsx
- ui/apps/platform/src/Containers/Policies/Modal/EnableDisableNotificationModal.tsx
- ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.tsx
- ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
- ui/apps/platform/src/Containers/VulnMgmt/Reports/VulnMgmtReportTablePanel.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/AffectedComponents/AffectedComponentsModal.tsx
Solve minor issue from axe DevTools in Search results table:
> Table header text should not be empty
PatternFly examples follow the accessibility work-around to render `Td` instead of `Th` element.
Join them if you cannot beat them: an attempt to render **Actions** required additional utility classes in both the table **head** and table **data** cells.
Delete extra `Th` element that does not correspond to a column in `EnableDisableNotificationModal` component.
1. Replace `any` in `VulnMgmtReportTablePanel` component.
1. Visit /main/violations
* with PatternFly `Th` element that renders as HTML `th` element.
* with PatternFly `Td` element that renders as HTML `td` element
> Replace Th which has empty text with Td

- qa-tests-backend/src/test/groovy/CSVTest.groovy
This change broke OCP QA e2e tests ([before](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-ocp-4-12-merge-qa-e2e-tests/1641417276299153408)/[after](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-ocp-4-12-merge-qa-e2e-tests/1641425328695939072)).
Probably best to revert at this point until we can figure out root cause.
Reverts stackrox/stackrox#5468
> Revert "Make CSVTest multi-arch compliant"

- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- pkg/renderer/helm_values.go
- roxctl/central/generate/generate.go
- roxctl/central/generate/generate_test.go
- roxctl/central/generate/volumes.go
- roxctl/helm/derivelocalvalues/derivelocalvalues.go
* Make the `--enable-telemetry` option of the `roxctl central generate` command to update the helm values with the data taken from the respective environment variables.
* A few minor improvements in the code around.
Tested with local `roxctl`:
```sh
$ export ROX_TELEMETRY_STORAGE_KEY_V1=abc
$ ./bin/linux_amd64/roxctl central generate k8s pvc --enable-telemetry=true
...
INFO:	StackRox Kubernetes Security Platform collects and transmits anonymous usage and system configuration information. If you want to OPT OUT from this, re-generate the deployment bundle with the '--enable-telemetry=false' flag.
...
$ rg -B4 abc central-bundle
central-bundle/helm/values-public.yaml
18-  telemetry:
19-    enabled: true
20-    storage:
21-      endpoint: …
```
> ROX-16233: Read environment variables for the telemetry configuration

- central/processlisteningonport/datastore/datastore_impl_test.go
- central/processlisteningonport/store/postgres/full_store.go
In the following scenario we could end up with a situation where for a brief period of time the only information reported for a listening endpoint is the port, protocol, and deployment Id. Central receives a listening endpoint and matching process indicator. The process indicator is deleted before the message that the port is closed reaches central. In such cases the port is almost certainly closed and should not be reported by the API.
> Jv dont show listening endpoints with no process info

- ui/apps/platform/src/Containers/NetworkGraph/common/FlowsTable.tsx
This PR updates the anomalous traffic icon to be a triangle for consistency
> ROX-15429: Change anomalous traffic icon to triangle

- image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
- image/templates/helm/stackrox-central/values-public.yaml.example.htpl
- image/templates/helm/stackrox-central/values.yaml.htpl
We ran into an issue that had statement timeouts for some Postgres queries, this would decrease the likelihood of those happening on 74. This is mitigated via contexts in 4.0.
Trivial
> Extend statement timeout to 10m

- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkGraphIcons.tsx
This PR fixes an issue I introduced in a [previous merge](https://github.com/stackrox/stackrox/pull/5539) where the deployment badge text was incorrect
> feat: deployment badge text was incorrect

- sensor/kubernetes/eventpipeline/pipeline_impl.go
- sensor/kubernetes/eventpipeline/pipeline_test.go
For testing purposes we want to resolve the dependencies again in the resolver instead of just flushing the already built deployment to the detector when a `ReprocessDeployments` message is received.
This should be reverted after [ROX-14310](https://issues.redhat.com/browse/ROX-14310)
* CI
> ROX-16279: Set skipResolving to false when a ReprocessDeployments is requested

- central/clusters/zip/generate_certs.go
- central/metadata/service/service_impl.go
- central/tlsconfig/manager_impl.go
- central/tlsconfig/manager_impl_test.go
- central/tlsconfig/tlsconfig.go
- central/tlsconfig/tlsconfig_test.go
Errors around malformed `defaultTLSCertificate` are not super helpful. This PR aims at providing better error messages for the customer when such errors occur. 
The previous implementation used 2-3 different methods with duplicated logic to load and verify the default TLS certificate. This basically uses a single access point for handling that.
> ROX-14479 Improve error reporting when handling the defaultTLSCertificate

- README.md
- operator/bundle_helpers/patch-csv.py
- scripts/get-previous-y-stream.bats
- scripts/get-previous-y-stream.sh
Please see the mentioned ticket and commit messages for the context.
One thing I'm not 100% sure about is whether to keep the script as external shell one or move the logic inside of `patch-csv.py` (or next to it).
Advantages of keeping a separate script:
- It is unit-tested and tests are ran in CI, we don't have unit tests in CI for Python.
- It can be used in other places (e.g. version-compatibility tests, but I'm yet to run them).
Advantages of integrating in `patch-csv.py`:
- Less moving parts like spawning external process from Python.
These aren't needed:
* CI here should be green (enough green).
* Testing with `4.0.0-rc.1` tag under https://github.com/stackrox/stackrox/pull/5530
> ROX-14960: Fix detection of previous Y-Stream release

- qa-tests-backend/src/test/groovy/ProcessesListeningOnPortsTest.groovy
- tests/e2e/lib.sh
PLOP feature seems to be disabled by default in nightlies. Ignore e2e tests if that's the case.
CI run should be sufficient.
> Disable PLOP E2E tests if the feature is off

- pkg/env/sensor.go
- sensor/common/metrics/init.go
- sensor/common/metrics/metrics.go
- sensor/kubernetes/eventpipeline/output/output_impl.go
- sensor/kubernetes/eventpipeline/resolver/resolver_impl.go
- sensor/kubernetes/sensor/options.go
Adds to metrics `resolverChannelSize` and `outputChannelSize` to track the size of the `eventPipeline` channels.
> ROX-14570: add metrics to track the size of the eventPipeline channels

- central/postgres/pruning.go
- central/postgres/pruning_test.go
- central/pruning/pruning.go
- central/pruning/pruning_test.go
Use sql instead of cursors. There are 3 million alerts in this database and it times out on cursor timeout. In this cluster there are also 0 matches. Test will be written before merging
Will run in the cluster
> Use SQL to optimize orphaned alert pruning workflow

- pkg/search/autocomplete_query_parser.go
- pkg/search/autocomplete_query_parser_test.go
- pkg/search/general_query_parser.go
- pkg/search/general_query_parser_test.go
- pkg/search/parser.go
- pkg/search/parser_test.go
Plus `+` is used to indicate a conjunction (`AND`) between match field queries and comma `,` is used to indicate a disjunction (`OR`). But they can also be a part of search value for a field. To allow that if a plus or comma is enclosed in quotes, it should be ignored.
Unit tests
> [ROX-16268] : Query parser should skip plus and comma if within double quotes

- .openshift-ci/clusters.py
- .openshift-ci/dispatch.sh
- scripts/ci/gke.sh
When a CI job is canceled (e.g. a new commit is pushed to a PR) the GKE clusters are not always torn down. This is due to the default job exit handler killing the GKE teardown script before it has a chance to complete. Even if that behavior was modified i.e. to not kill the script, there is still a lot of (possibly) extraneous tasks in the teardown path before the required gcloud command is executed. And time in the canceled job interrupt handler is limited.
So this PR changes cancelation handling to teardown the cluster without cleanup and give it some time to execute before exiting.
This is still a pretty fragile piece of code forwarding signals, sleep, etc. A more Openshift CI aware approach as an extra step in the `stackrox-e2e` step-registry task may be worth looking at as a longer …
> ROX-16325: CI: tear down the GKE cluster on job cancelation

- image/embed_charts.go
- pkg/renderer/kubernetes_helm.go
Removes the panic when creating generating Secured Cluster manifests with SHA. Instead this should surface the error to the caller.
> ROX-16212: Remove panic from failed charts

- pkg/declarativeconfig/access_scope.go
- pkg/declarativeconfig/access_scope_test.go
- pkg/declarativeconfig/auth_provider_test.go
- pkg/declarativeconfig/permission_set.go
- pkg/declarativeconfig/permission_set_test.go
- pkg/declarativeconfig/role_test.go
- pkg/declarativeconfig/transform/access_scope.go
- pkg/declarativeconfig/transform/access_scope_test.go
- pkg/declarativeconfig/transform/role.go
- pkg/declarativeconfig/transform/role_test.go
- roxctl/declarativeconfig/create/access_scope.go
- roxctl/declarativeconfig/create/access_scope_test.go
- roxctl/declarativeconfig/create/auth_provider.go
- roxctl/declarativeconfig/create/auth_provider_test.go
- roxctl/declarativeconfig/create/create.go
- roxctl/declarativeconfig/create/permission_set.go
- roxctl/declarativeconfig/create/permission_set_test.go
- roxctl/declarativeconfig/create/role.go
- roxctl/declarativeconfig/create/role_test.go
- roxctl/declarativeconfig/declarativeconfig.go
- roxctl/maincommand/command.go
This PR is the first PR in a series of PRs to add roxctl commands to support users with the usage of declarative configurations.
The first command introduced is the `create` command.
The use-case for the `create` command is to offer users with the possibility to generate the YAML format of the declarative configuration via a CLI, instead of manually constructing it themselves (similar to how one can generate a deployment YAML via `kubectl create deployment --replicas=1 --image 
nginx:latest --dry-run-client -o yaml`).
The `create` command exposes subcommands for each resource supported in declarative configuration (`role, auth provider, access scope, permission set`) and each command will a) construct the declarative configuration struct from the flag values b) attempt to transform the …
> ROX-14150: Add create command for declarative configs

- pkg/printers/sarif_test.go
Within the SARIF printer test, the version of roxctl will be included in the output.
During the assertion of the output against the expected output, the version will be replaced with an empty string. We previously only replaced 3.x versions (due to two different version fields being populated), but now we shall include this to cover 4.x as well.
- CI should pass again.
> Fix SARIF printer tests

- CHANGELOG.md
Based on Chris' presentation we just sat through at the NA F2F, no customer is happy with the PDF export, because all it is, is a "screenshot" of the current page of the UI. They think it will be the CSV emailed report, just "printed" to PDF.
Since this is removing functionality, we need to add a deprecation notice to Changelog and Release Notes for 4.0, so that we can remove it in 4.2.
In the deprecation notice, please add language to the effect of "Use vuln reporting feature instead" - because I believe customers are not aware of/using that feature to get them the info they are looking for.
n/a
n/a
> ROX-16390: Add deprecation for PDF exports in VM1.0 UI

- deploy/common/k8sbased.sh
- tests/e2e/lib.sh
This is a fix for #5492 which incorrectly only disabled re-sync for helm installations. 
CI run
> Patch Sensor for manifests and operator installations

- pkg/env/processes_listening_on_port.go
- pkg/features/list.go
- sensor/common/networkflow/manager/manager_impl.go
It should enable the feature to be disabled at runtime whereas Features are burned into their default value for Release builds.
> Control ProcessesListeningOnPort with a BooleanSetting instead of a Feature

- pkg/declarativeconfig/transform/access_scope.go
- pkg/declarativeconfig/transform/access_scope_test.go
We moved some validation within the `transform` method, specifically whether the label selectors contained within the access scope are valid.
This leads to the access scope not being created, and the integration health status not being created. This is undesired, as we want to specifically have an integration health status for it.
Hence, reverting the changes made to the `transform` now, but will make sure in a follow-up that the `roxctl declarative-config create access-scope` command will validate the access scope's label selectors.
- CI should be passing again, specifically `DeclarativeConfigTest`.
> ROX-16391: Fix declarative config E2E tests

- ui/apps/platform/src/Containers/VulnMgmt/Dashboard/VulnMgmtDashboardPage.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/TopRiskiestEntities.js
Setting "Filter CVEs" toggle to "Fixable" was not filtering these entities by non-fixable CVEs. 
This is because the frontend does not pass the query with the fixable flag to the backend.
Verified that the `Fixable:true`, if on, or nothing, if off, was being added to the query fired by the TopRiskiestEntities widget component.
When all was selected (and no flag filter sent)
When Fixable selected, and flag filter is sent, there is a difference in how the backend calculates the list (subtle)
> ROX-15219: Add fixable flag to Top Riskiest <thing> widget query

- ui/apps/platform/package.json
- ui/apps/platform/src/Components/workflow/TableCountLinks/TableCountLinks.tsx
- ui/apps/platform/src/Containers/Collections/types.ts
- ui/apps/platform/src/Containers/Dashboard/SummaryCounts.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/AgingImagesChart.tsx
- ui/apps/platform/src/Containers/Network/Header/TimeWindowSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useImageVulnerabilities.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
- ui/apps/platform/src/types/cve.proto.ts
- ui/apps/platform/src/types/policy.proto.ts
- ui/packages/tailwind-config/package.json
- ui/packages/ui-components/package.json
- ui/yarn.lock
Patch update now to limit number of code changes for major upgrade soon.
1. https://github.com/prettier/prettier/blob/main/CHANGELOG.md#285
* TypeScript 5.0 introduces two new syntactic features:
`const` modifiers for type parameters
`export type *` declarations
* Add parentheses for (array of) `TypeofTypeAnnotation` to improve readability.
17 changes in 11 files
* src/Components/workflow/TableCountLinks/TableCountLinks.tsx
* src/Containers/Collections/types.ts
* src/Containers/Dashboard/SummaryCounts.tsx
* src/Containers/Dashboard/Widgets/AgingImagesChart.tsx
* src/Containers/Network/Header/TimeWindowSelector.tsx
* src/Containers/NetworkGraph/NetworkGraphPage.tsx
* src/Containers/NetworkGraph/TopologyComponent.tsx
* src/Containers/Vulnerabilities/WorkloadCves/hooks/useImageVulnerabilities …
> Update prettier 2.8.7 devDependencies in ui

- ui/apps/platform/src/app.tw.css
Solve serious issue from axe DevTools in workflow tables when side panel is open:
Contrast ratio less than 4.5 in light mode for `text-tertiary-700` foreground and `bg-tertiary-200` background colors.
| mode | foreground | background | ratio |
| :--- | :--- | :--- | ---: |
| dark  | `#d1e6fa` | `#2c4258` | 8.09 |
| light | `#417ab4` | `#ebf5ff` | 4.07 |
Follow example of PatternFly toggle group in which selected items have ordinary color on light blue background color.
https://www.patternfly.org/v4/components/toggle-group/design-guidelines
Contrast ratio more than 4.5 in light mode for default `text-base-600` foreground and `bg-tertiary-200` background colors.
| mode | foreground | background | ratio |
| :--- | :--- | :--- | ---: |
| dark  | …
> Improve color contrast for active row in classic tables

- ui/apps/platform/package.json
- ui/packages/ui-components/package.json
- ui/yarn.lock
https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=milestone%3A%22TypeScript+5.0.4%22+is%3Aclosed+
* Disable JSX recovery hack when in unary expression context
https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=milestone%3A%22TypeScript+5.0.3%22+is%3Aclosed+
* Assertion function & Type guards for Record types broken on 5.0
* unused type guard result erroneously changing inferred type of variable
> Update TypeScript 5.0.4 devDependencies in ui

- central/graphql/resolvers/image_components.go
Look at the full scope tree and not just the parent to evaluate image component's layer index.
> Look at the scope tree to evaluate layer index

- central/image/datastore/store/postgres/store.go
`copyFromImageCVEEdges` in image postgres store was failing to insert new ImageCVEEdges into postgres when the edges on batchSize boundaries in the input edges were pre-existing edges.
e2e test ImageScanningTest should not fail
> [ROX-16068] : Fix ImageCVEEdges not getting inserted sometimes

- ui/apps/platform/src/Containers/VulnMgmt/List/Cves/CveBulkActionDialogue.js
If no custom policies have been created, adding a CVE to a policy in vulnerability management will cause the page to error out due to an infinite loop in the `CveBulkActionDialogue` component.
Action:
Results before:
Results after:
> Bulk action cve to policy breaks without custom policies

- scripts/ci/lib.sh
- scripts/ci/publish-helm-charts.sh
Cherry-picking relevant changes for fixing Helm charts and Collector version update PRs in release-3.74 branches from https://github.com/stackrox/stackrox/pull/5039. 
These have failed in the 3.73.4 release and we can avoid manual work for the release engineer if this PR lands on the release branch before the 3.74.2 release.  
n/a
> cherry-pick #5039: fix Helm / Collector version publishing steps for 3.74

- scripts/ci/publish-helm-charts.sh
Cherry-picks changes to Helm chart publishing from https://github.com/stackrox/stackrox/pull/5039.
This is a partial cherry-pick, because the other changes from that PR are incompatible with OSCI, which this release is using for the Release CI.
n/a
> Cherry-picking for ROX-15361: fix helm charts publishing

- scripts/ci/jobs/ocp_operator_e2e_tests.py
- scripts/ci/jobs/ocp_qa_e2e_tests.py
- scripts/ci/jobs/ocp_ui_e2e_tests.py
All openshift e2e tests now have ocp in their job names. This PR creates jobs in the target repo (this) to reflect that. TEST_SUITE will then be updated in a subsequent PR in openshift/release to use (and test) these jobs. And then another PR in this repo will remove the openshift-4 ones.
n/a
n/a
> CI: Add OCP jobs

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/DeploymentPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImagePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImagePageResources.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/BySeveritySummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/SingleEntityVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
A handful of cleanup items I noticed that don't have tickets, one change for each commit so reviewing is likely easier to do commit-by-commit.
1. Update naming of main page components from `WorkloadCveEntitySinglePage` to just `EntityPage`.
2. Switch existing tables to use the "compact" variant and fix the border display in the embedded table.
3. Add PageTitles (oops) to entity single pages.
4. Change all usage of "faded" text colors in the UI to `color-200` which is the only noticeably lighter text color offered by PatternFly that passes accessibility color tests on a plain white background.
Manual testing of navigation, page titles, and table rendering.
> Minor general workload CVE fixes

- ui/apps/platform/package.json
- ui/apps/platform/src/app.tw.css
- ui/yarn.lock
Left over after delete `react-slick` in #3065
Find in files only references to **slick** or **carousel** are in app.tw.css file
1. Delete dependency and then `yarn` in ui
2. `yarn build` in ui to see expected error because of reference in app.tw.css
3. Delete reference
4. `yarn build` in ui and then
* `wc build/static/css/main.*.css` in ui
branch - master: -9415 = 4855447 - 4864862
* `wc build/static/css/*.chunk.css` in ui
branch - master: 0 = 1069736 - 1069736
5. `yarn start` in ui and then visit pages that have links in left navigation
> Delete slick-carousel package and styles from UI

- sensor/tests/replay/replay_test.go
- sensor/tests/resource/imagescan/imagescan_test.go
- sensor/tests/resource/networkpolicy/networkpolicy_test.go
- sensor/tests/resource/pod/pod_test.go
- sensor/tests/resource/role/role_test.go
- sensor/tests/resource/service/service_test.go
Disabled re-sync in `sensor-integration-tests`.
* CI
* Manual test `sensor-integration-tests`
> Set re-sync disabled in sensor-integration-tests

- .openshift-ci/post_tests.py
- qa-tests-backend/Makefile
- qa-tests-backend/src/main/groovy/util/Helpers.groovy
- qa-tests-backend/src/test/groovy/ProcessVisualizationTest.groovy
- scripts/ci/collect-service-logs.sh
- scripts/ci/create-webhookserver.sh
- tests/e2e/lib.sh
- tests/e2e/run.sh
This PR includes a number of fixes to get AKS working again.
Also:
- Adds support for a ci-fail-fast label.
- Adds `kube-system` to the namespaces gathered on failure.
- Includes daemonsets in the objects gathered on failure.
- Skips ProcessVisualizationTest / Verify process visualization on kube-proxy for AKS (ROX-16461).
- Log and restart the webhook port-forward.
- Fix nongroovy-e2e tests in release mode.
> CI: Fixes for AKS

- ui/apps/platform/src/Components/KeyValuePairs.js
- ui/apps/platform/src/Components/TimelineGraph/Minimap/BrushableOverlay.js
- ui/apps/platform/src/Containers/Network/SidePanel/Creator/Tiles/GenerateNetworkPoliciesSection.tsx
- ui/apps/platform/src/Containers/Network/SidePanel/Creator/Tiles/UploadNetworkPolicySection.tsx
- ui/apps/platform/src/Containers/Network/SidePanel/NetworkDeploymentOverlay/DeploymentDetails/ContainerConfigurations.tsx
- ui/apps/platform/src/Containers/Risk/ContainerConfigurations.js
- ui/apps/platform/src/constants/visuals/colors.ts
Prerequisite to solve insufficient color contrast accessibility issues by mapping from classic to PatternFly theme.
PatternFly color palette does not have magenta.
https://www.patternfly.org/v4/guidelines/colors#color-palette
1. Redundantly distinguishes value from key by accent color in addition to either font style or weight:
* src/Components/KeyValuePairs.js
* src/Containers/Network/SidePanel/NetworkDeploymentOverlay/DeploymentDetails/ContainerConfigurations.tsx
* src/Containers/Risk/ContainerConfigurations.js
Distinction between secondary and accent is hard in light theme and even harder in dark theme (see pictures).
2. Double style inconsistency accent versus primary above, and both are heading text that look like buttons or links. Too bad, so sad that icon apparently has inherent …
> Delete occurrences of theme accent color

- operator/apis/platform/v1alpha1/central_types.go
- operator/bundle/manifests/platform.stackrox.io_centrals.yaml
- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/config/crd/bases/platform.stackrox.io_centrals.yaml
- operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
- Specifying the connection string is tech preview in 4.0
- If a user specifies the DB password, then this is not currently picked up by Central DB pod and it uses the autogenerated one so tell users not to specify it
https://issues.redhat.com/browse/ROX-16488
Just docs, but will look at it in the UI view
> Add Tech Preview designation to Operator for connection string

- pkg/env/sensor.go
- pkg/env/setting.go
- pkg/env/setting_test.go
This PR strips the prefix `http://` or `https://` from the `ROX_CENTRAL_ENDPOINT` variable to avoid Sensor crashing (as in the ticket).
Using UI to generate init bundle is already immune to providing `http[s]://` as prefix.
> ROX-11780: Strip http[s] from CENTRAL_ENDPOINT

- pkg/centralsensor/init_cert.go
Many customers and colleagues report seeing this panic message as a bug: `Panic: Invalid dynamic cluster ID value "": no concrete cluster ID was specified in conjunction with wildcard ID "00000000-0000-0000-0000-000000000000"
panic: Invalid dynamic cluster ID value "": no concrete cluster ID was specified in conjunction with wildcard ID "00000000-0000-0000-0000-000000000000"`. This is usually (always?) caused by Central being restarted without persisting its data between the restarts. Adding additional information to the log message helps understand why we see this panic.
> ROX-15278: Improve panic log message when central is recreated without persistence

- .github/workflows/cut-rc.yml
With the last Infra release, 
* QA Demo requires to set the `central-db-image` parameter if you want to use Postgres
* Openshift 4 Demo flavor can generate Helm charts for arbitrary versions, therefore we can remove the patching steps and set the desired version directly. We'll also not wait for the cluster to be created and instead hint the user to wait and check in given time.
Tested manually. If this works as expected on the next RC cut, I will cherry-pick the commit to master.
> ROX-16435: update cut-rc to use updated QA Demo & Openshift 4 Demo flavors

- README.md
- scripts/quick-helm-install.sh
Reduce central-db resources in Helm installation scripts with `--small` variant so that Central does not come overprovisioned as by default (4 cpu & 8Gb) and follows what we set in `deploy.sh`-based deployments (see https://github.com/stackrox/stackrox/blob/3269be7471c24aa387b7c988b81f475754e64571/deploy/common/local-dev-values.yaml).
Also updated a bit README around Helm-based installation.
Rendered README: https://github.com/stackrox/stackrox/blob/misha/update-central-db-resources-in-scripts/README.md#deploying-stackrox
These aren't needed:
Tested `scripts/quick-helm-install.sh --small` as part of https://github.com/stackrox/stackrox/pull/5692.
> Reduce central-db resources in Helm installation scripts

- CHANGELOG.md
- pkg/version/chart_version_test.go
- pkg/version/version.go
- pkg/version/version_test.go
Old Helm charts were versioned like this:
```
Main Version -> Helm Chart Version
3.0.58.2 -> 58.2.0
3.74.1 -> 74.1.0
```
This creates a problem with the major version bump from 3.74.z to 4.0.0 because under such scheme
```
Main Version -> Helm Chart Version
4.0.0 -> 0.0.0
4.1.0 -> 1.0.0
4.2.0 -> 2.0.0
```
which, according to [SemVer used in Helm](https://helm.sh/docs/topics/charts/#charts-and-versioning), is considered to be older versions than 3.74.z rendered to (I also verified this manually).
It seems weird why the release number was put into Helm Major version. Unfortunately, @mtesseract is on the leave to answer. I made extensive search in Confluence, in the Internet and also [asked](https://redhat-internal.slack.com/archives/C02HTD51SMD/p1680778117629319) @SimonBaeumer in Slack but …
> ROX-14917: Switch Helm versioning to respect Main major version

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCveSummaryCards.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
Restructures the queries a bit so that the counts for `images` and `deployments` are always kept up to date, regardless of the user's current entity tab. The query that requests the full table data will still only request data for the active tab.
Load the ImageCVE page and see that the counts for both Images and Deployments are up to date.
Change to the Deployments tab, and apply a deployment filter. The counts for both images and deployments should update to match the filter, but the only request that is sent is the `SummaryData` request. The images request is not sent because "Deployments" is the active tab.
> Separate image count query from data loading query in image cve page

- ui/apps/platform/cypress/helpers/networkGraph.js
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NetworkGraphNavItems.tsx
- ui/apps/platform/src/Containers/Network/Page.js
- ui/apps/platform/src/routePaths.js
Jira: https://issues.redhat.com/browse/ROX-16466
This PR makes a change to the left nav bar:
1. The old network graph nav item will now say "Network Graph (1.0 deprecated)"
2. The new network graph nav item will now say "Network Graph (2.0)"
3. The deprecation banner in the old network graph is now feature flagged
> ROX-16466: Remove preview from NWG 2.0 and mark 1.0 as deprecated

- .github/workflows/cut-rc.yml
* The image needs to be fully specified, not just image tag
* key and value need to be separated by `=`, not `:`
Added to milestone, so also be fixed on release branch.
Fixed based on manual cluster provisioning "gke-demo-4-0-0-rc-4-manual".
> fix: typos in referencing central-db-image for QA Demo cluster in cut-rc workflow

- qa-tests-backend/src/test/groovy/GroupsTest.groovy
This is first PR in series of PRs to introduce e2e test for behaviour implemented in https://issues.redhat.com/browse/ROX-14700. 
This particular PR focuses on creating/updating groups with invalid role or auth provider references.
1. Run new tests locally
2. + CI should be sufficient
> ROX-16531: Test group create/update with invalid references

- ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx
- ui/apps/platform/src/Containers/ConfigManagement/Entity/widgets/ScopedPermissions.js
- ui/apps/platform/src/constants/visuals/colors.ts
- ui/apps/platform/src/utils/vulnerabilityUtils.js
Prerequisite to solve insufficient color contrast accessibility issues by mapping from classic to PatternFly theme.
PatternFly color palette does have purple, but there are few occurrences of this color, none of which have an intuitive semantic meaning.
https://www.patternfly.org/v4/guidelines/colors#color-palette
1. Edit src/Containers/Clusters/cluster.helpers.tsx
* Replace secondary with base for status of Unavailable clusters.
2. Edit src/Containers/ConfigManagement/Entity/widgets/ScopedPermissions.js
* Replace random selection from `['primary', 'secondary', 'tertiary']` with `primary` color.
3. Edit src/constants/visuals/colors.ts
* Delete `'secondary'` from `colorTypes` array.
4. Edit src/utils/vulnerabilityUtils.js
* Replace `type="secondary"` with `type="base"` in `LabelChip` …
> Delete occurrences of theme secondary color

- ui/apps/platform/src/Containers/NetworkGraph/components/DeploymentSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NamespaceSelector.tsx
This PR includes some UX improvements:
1. When clearing the selections using the network graph namespace/deployment selectors, we don't want to close the dropdown
2. When no namespaces are selected in the namespace selector, disable the "clear selections" button
3. When no deployments are selected in the deployment selector, disable the "clear selections" button
4. When filtering deployments in the deployment selector, if no deployment matches under a namespace, hide that whole grouping in the display. If no deployments match across namespaces, then show a "No deployments found" text
https://user-images.githubusercontent.com/4805485/232595321-dc7a07ea-3b78-4c14-a80a-ad5d7e7b3ad1.mov
> fix: UX improvements for clear selections and display for filtered deployments

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#12-10-0
* Removed unintentional debug logs.
* Upgraded `commander` from `^5.1.0` to `^6.2.1`.
* Upgraded `minimist` from `1.2.6` to `1.2.8` to address CVE-2021-44906 NVD security vulnerability.
> Update cypress 12.10.0 devDependencies in ui

- scripts/ci/lib.sh
This reverts commit 6f5d9f26e8af3423f5b55b365c25d2aa045c37ea.
Undefined vars cause the junit2jira block to exit.
> Revert "Upgrade junit2jira (#5672)"

- image/templates/sensor/kubernetes/sensor.sh
- image/templates/sensor/openshift/sensor.sh
When we generate installation bundle for sensor, there are cases when we cannot detect wether the user has disabled PSPs or not. So we generate a sensor installation script including PSPs, even if the target cluster does not support it.
This introduce a last "fail-safe" mechanism, to ignore the PSPs in a sensor installation bundle if the target k8s cluster does not support it. The ideal situation would be to not generate them altogether. But in the case that these PSPs manifests are generated, at least the installation script will not fail if the cluster cannot install them. 
I've tested that the sensor.sh script detects when the PSPs are available or not in a cluster, and will install them conditionally.
> ROX-16552 Add basic autosense for PSPs in generated sensor.sh scripts.

- ui/apps/platform/cypress/integration/configmanagement/dashboard.test.js
Tests of Policy Violations by Severity widget fail intermittently.
Dave Vail found that vulnerabilities (and therefore policy failures) change as image versions change.
The objective of the test is to compare counts from a link. Which severity of policy violations is not significant.
* `'should show the same number of high severity policies in the "Policy Violations By Severity" widget as it does in the Policies list'`
* `'should show the same number of low severity policies in the "Policy Violations By Severity" widget as it does in the Policies list'`
* `'should show the same number of policies without violations in the "Policy Violations By Severity" widget as it does in the Policies list'`
Merge the 3 tests to compare the count of policies for the first link in the bullet list of the …
> Test count of policies independent of severity in Configuration Management

- ui/apps/platform/src/Components/PatternFly/IconText/IconText.tsx
- ui/apps/platform/src/Containers/ConfigManagement/List/Clusters.js
- ui/apps/platform/src/Containers/ConfigManagement/List/Nodes.js
- ui/apps/platform/src/Containers/ConfigManagement/List/Roles.js
- ui/apps/platform/src/Containers/ConfigManagement/List/utilities/NoEntitiesIconText.tsx
Color text causes accessibility problems like insufficient contrast or assumption of perfect color vision.
Compare `LabelChip` element versus plain text for either of the following
* No whatevers: Clusters, Deployments, Namespaces, Nodes, Roles
* 0 whatevers: Images
| List            | element | text | total |
| :---            |    ---: | ---: |  ---: |
| CISControls     |       0 |    0 |     0 |
| Clusters        |       4 |    0 |     4 |
| Deployments     |       0 |    2 |     2 |
| Images          |       0 |    1 |     1 |
| Namespaces      |       0 |    4 |     4 |
| Nodes           |       1 |    0 |     1 |
| Policies        |       0 |    0 |     0 |
| Roles           |       2 |    3 |     5 |
| Secrets         |       0 |    2 |     2 |
| ServiceAccounts |       0 |    3 | …
> Replace LabelChip with NoEntitiesIconText in Configuration Management

- qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
The `waitForViolation` timeout for `DefaultPoliciesTest > Verify policy * is triggered` was recently increased to 300 seconds. (#5372). This is reasonable as there is evidence that the Apache Struts policy for example can take > 2 minutes to trigger ([1](https://search.ci.openshift.org/?search=Apache+Struts%3A+CVE-2017-5638+triggered+after+waiting+%5Cd%7B2%2C3%7D+seconds&maxAge=336h&context=1&type=build-log&name=stackrox.*ocp.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)). However if the policy violation is not triggered within that 300 second timeout the JUnit global 800 second timeout invariably kicks off ([2](https://search.ci.openshift.org/?search=Failed+to+trigger+Apache+Struts%3A+CVE-2017-5638+after+waiting&maxAge=336h&context=1&type=build-log&name=stackrox.*ocp.*&exclud …
> CI: Extend global timeout for DefaultPoliciesTest

- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
This is the second PR in a series of PRs to introduce e2e test for behaviour implemented in [issues.redhat.com/browse/ROX-14700](https://issues.redhat.com/browse/ROX-14700).
This particular PR focuses on how declarative configuration logic handles deletion of dependent resources.
1. New tests added
2. CI is sufficient
> ROX-16531: Add orphaned resources tests to DeclarativeConfigTest.groovy

- image/templates/helm/stackrox-central/templates/01-central-08-external-db-configmap.yaml
We are missing client_encoding in the connection string definition
screenshots.
> ROX-16607: Explicitly specify connection string encoding

- image/postgres/scripts/docker-entrypoint.sh
Explicitly set the server encoding to avoid mismatch issues
CI
> Explcitly set Postgres server encoding to UTF8

- Makefile
- qa-tests-backend/src/main/groovy/util/SyslogServer.groovy
- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
In this PR syslog notifier test is changed to use syslog server image with rest endpoint. Additional test steps are added to verify that syslog receives alert notification message from central.
Testing Performed
Test is run in CI to verify that it passes
> Modified syslog test to use syslog server with rest endpoint

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
Quick fix for page crashes on the deployments tab when filters/sorting/pages are changed due to `data` becoming `undefined`.
Load the workload CVE overview page, go to the deployments tab, and filter/sort/paginate.
> Add generic type for deployment gql query response

- sensor/tests/resource/helper.go
- sensor/tests/resource/role/role_test.go
- sensor/tests/resource/role/yaml/nginx-cluster-binding.yaml
- sensor/tests/resource/role/yaml/nginx-cluster-role.yaml
Enhance the `sensor-integration-tests` with `ClusterRoles`.
* Running the integration tests manually.
* CI
> Add cluster role integration tests

- pkg/env/booleansetting.go
- pkg/env/roxctl.go
- roxctl/common/flags/endpoint.go
- roxctl/common/flags/env_flag.go
- roxctl/common/flags/env_flag_test.go
- roxctl/common/flags/no_color.go
Some roxctl command line flags already have associated environment variables. Others don't.
The goal of this change is to harmonize the way roxctl commands can be configured by adding environment variables as additional configuration source for some of the command line flags.
CI should be sufficient to ensure the basic functions are not broken.
Manual tests will be performed to check roxctl commands also behave as expected if configured through environment variables.
Test `ROX_NO_COLOR`:
Various manual tests:
```bash
ybrillou@ybrillou-mac stackrox % ROX_ENDPOINT="https://localhost:8000" ROX_PLAINTEXT=false ROX_INSECURE_CLIENT=true roxctl central whoami
WARN:	The remote endpoint failed TLS …
```
> ROX-15145: Add environment variables as alternative information source for roxctl global command line flags

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CveStatusTabNavigation.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/SeverityCountLabels.tsx
- ui/apps/platform/src/constants/visuals/colors.ts
As the title states, adding the CVE list to the Overview page. Everything should function as expected, although there are a few things tbd on PM that i have left in the comments.
also fixed the severity colors again on the severity labels
TODO:
* get clarity on score version for CVSS column
* get clarity on denominator for affected images column
* update summary once BE is ready
* add empty results page to tables
> ROX-15028: Adding CVE list to Workload CVEs Overview page

- image/templates/helm/stackrox-secured-cluster/README.md.htpl
- image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml
- image/templates/helm/stackrox-secured-cluster/internal/defaults/40-resources.yaml
- image/templates/helm/stackrox-secured-cluster/internal/expandables.yaml
- image/templates/helm/stackrox-secured-cluster/templates/collector.yaml
- image/templates/helm/stackrox-secured-cluster/values-public.yaml.example
Renaming a Helm setting as discussed in https://redhat-internal.slack.com/archives/C04213W844U/p1681745465572349
> ROX-16554: Rename Helm setting nodeInventoryResources to nodeScanningResources

- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ArtifactRegistryIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ArtifactoryIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/AwsSecurityHubIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/AzureIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/DockerIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/EcrIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/EmailIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/GcsIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/GenericWebhookIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/GoogleCloudSccIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/GoogleIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/IbmIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/JiraIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/NexusIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/QuayIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/RhelIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/S3IntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/SplunkIntegrationForm.tsx
This change makes the "update token / update password" etc checkbox on all integration forms that have saved credentials no longer be checked by default when opening the form to edit an existing integration. (This was causing confusion with customers not being able to Test existing integrations, unless they unchecked the box--and they got stuck because the flow is not obvious.)
Rather than change the default value of the `updatePassword` property, which is our API's way of noting new creds will be in the request, and which is required to be `true` on create, I leverage the already-existing condition which clears out the "******" value that comes back on edit. I added changing the `updatePassword` field to `false` in those situations.
I manually tested each form with credentials. …
> ROX-16648: Change default to not update creds on integration form edit

- qa-tests-backend/src/main/groovy/orchestratormanager/OpenShift.groovy
- qa-tests-backend/src/main/groovy/services/GraphQLService.groovy
- qa-tests-backend/src/main/groovy/services/ImageIntegrationService.groovy
- qa-tests-backend/src/main/groovy/services/RoleService.groovy
- qa-tests-backend/src/main/groovy/util/Helpers.groovy
- qa-tests-backend/src/test/groovy/AuditLogAlertsTest.groovy
- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
- qa-tests-backend/src/test/groovy/GroupsTest.groovy
- qa-tests-backend/src/test/groovy/SACTest.groovy
- scripts/ci/lib.sh
Some of what is logged is not useful. See https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/branch-ci-stackrox-stackrox-nightlies-gke-qa-e2e-tests/1648553247369072640/artifacts/gke-qa-e2e-tests/stackrox-e2e/build-log.txt for the log used to drive this PR.
Changes following issues in the log & commit order:
- Don't try to delete the test role if it does not exist. Avoids the initial stack dump starting `io.grpc.StatusRuntimeException: NOT_FOUND: failed to retrieve role "Test Automation Role - 6672": not found`
- Don't try to create Stackrox Scanner if it already exists. Avoids repeated `io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Validation error: integration with name "Stackrox Scanner" already exists: invalid arguments`. 
- GraphQL responses are very …
> CI: Clean up logs

- pkg/centralsensor/caps_list.go
Adds a new capability to the list of sensor capabilities. The capability is called ListeningEndpointsCap. This is contrary to the ticket and name of the branch. The name processes listening on ports is somewhat in flux and is likely to end up being listening endpoints instead. The service, API endpoint, and table were all changed to listening_endpoint and the name of the capability is consistent with that. Nothing is currently being done with the capability.
> Jv rox 16471 add processes listening on ports as a sensor capability

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/SingleEntityVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/EmptyTableResults.tsx
Adds an empty state in the table when a request completes successfully, but the applied filters cause zero results to be returned.
Overview images:
Overview deployments:
CVE Single images:
CVE Single deployments:
Image single:
> Add empty state for Workload CVE tables when filters return zero results

- ui/apps/platform/src/Containers/NetworkGraph/components/EdgeStateSelect.tsx
https://issues.redhat.com/browse/ROX-16604
This PR makes a few changes to the edge select component to make terminology more clear and consistent
> ROX-16604: NWG 2.0 menu should say active flows, not active traffic

- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
- qa-tests-backend/src/main/groovy/orchestratormanager/OrchestratorMain.groovy
- qa-tests-backend/src/main/groovy/util/Helpers.groovy
- qa-tests-backend/src/test/groovy/NodeInventoryTest.groovy
We expected the nodes to be scanned immediately (what is not the case), thus the test was super-flaky.
In this PR, the flakiness should be addressed by:
- Changing the collector config to start scanning immediately on the fly
- Add retries to the assertion regarding the number of components
> ROX-16639: Fix RHCOS test flake

- ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/PolicyViolationsBySeverity.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/TopRiskyEntitiesByVulnerabilities.js
- ui/apps/platform/src/constants/visuals/colors.ts
1. Color text causes accessibility problems like assumption of perfect color vision.
2. Inconsistent colors for severity throughout UI.
1. src/Containers/ConfigManagement/Dashboard/widgets/PolicyViolationsBySeverity.js
* This use of `Sunburst` element is similar to `CvesByCvssScore` component.
2. src/Containers/VulnMgmt/widgets/TopRiskyEntitiesByVulnerabilities.js
* This is the only use of `Scatterplot` element.
1. Except for **policy** colors, labels, and severities, instead of vulnerability, changes are similar to src/Containers/VulnMgmt/widgets/CvesByCvssScore.js in #5811
2. Encapsulate `legendData` within component.
In ui/apps/platform folder:
1. `export CYPRESS_ROX_POSTGRES_DATASTORE=true`
2. `yarn cypress-open`
* configmanagement/dashboard.test.js
* vulnmanagement/dashboard.test.js …
> Replace uses of severityColorMap from severityColors with accessible alternatives

- scripts/ci/metrics.sh
If the job record is not created, METRICS_JOB_ID will be undefined and undefined vars still cause an exception despite the `_finalize_job_record || { echo "ignored" }` approach. 
Re: https://github.com/openshift/release/pull/38750#issuecomment-1523099715
> CI: Handle missing job record better

- ui/apps/platform/src/Containers/Compliance/widgets/ComplianceByStandard.js
- ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/ComplianceByControls.js
- ui/apps/platform/src/constants/visuals/colors.ts
1. Classic colors have less contrast generally than PatternFly colors. Even for PatternFly severity colors, there is work-in-progress to improve contrast specifically for color vision.
2. Inconsistent colors for severity and corresponding concepts throughout UI.
Similar to `PolicyViolationsBySeverity` component in #5825
Especially because `ComplianceByStandard` is to the right of the former on Configuration Management dashboard.
Notice how the comparison in classic light mode emphasized how the subtle classic color looks like disabled?
1. Use consistent classic color for links.
2. Use plain text for descriptions.
3. Associate compliance colors with corresponding severity colors.
* Light edge around legend in dark theme is not new. The better the rest of the page looks, the worse it looks …
> Replace classic colors in Compliance Sunburst with PatternFly colors

- CHANGELOG.md
Add chagnelog entry for "Rename Helm setting nodeInventoryResources to nodeScanningResources" as it was forgotten in https://github.com/stackrox/stackrox/pull/5781 
- nothing
> ROX-16554: Add changelog entry

- central/networkgraph/service/service.go
- central/networkgraph/service/service_impl.go
- central/networkpolicies/service/service.go
- central/networkpolicies/service/service_impl.go
- central/networkpolicies/service/service_impl_test.go
- central/role/sachelper/access.go
- central/role/sachelper/cluster.go
- central/role/sachelper/extract.go
- central/role/sachelper/namespace.go
- central/role/sachelper/pagination.go
- central/role/sachelper/resource_filter.go
- central/role/sachelper/sachelper.go
- central/role/sachelper/scope.go
- central/role/service/service.go
- central/role/service/service_impl.go
- central/role/service/service_impl_test.go
Testing the NetworkGraph 2.0 page, I found out that the network policy lookup requires the `Cluster` permission in order to check if the cluster for which information is requested does exist. Requiring the `Cluster` permission for existence check could lead to data leaks or at least exposure of sensitive data not needed for network graph and policy management.
The change at hand alters the cluster validation flow for network graph and network policy to the verification that the target cluster is in the requester scope for either `NetworkGraph` or `NetworkPolicy` depending on the flow performing the existence check.
The change 
you did not do …
> ROX-14324: Use requester scope and target resource to validate cluster existence for NetworkGraph and NetworkPolicy

- sensor/common/detector/enricher_test.go
Update: Adding regression tests for the data race described below. The fix was introduced in #5627.
Opening this PR to discuss how to solve a data race we discovered in the enricher (see [ROX-16038](https://issues.redhat.com/browse/ROX-16038))
Our understanding of the code is that we force a scan of an image with the same id (digest) but different name. This leads to the race condition reproducible by the test added in this PR. I don't know if this `forceEnrichImageWithSignatures` is 100% necessary, but if it is, we need to rework the logic to make sure we fix this race.
cc @dhaus67 since he was the last one modifying this logic.
cc @fredrb 
- ~[ ] Documented user facing changes (create …
> ROX-16038 Regression tests for the data race in the enricher

- ui/apps/platform/src/Containers/Policies/Wizard/PolicyWizard.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step2/PolicyBehaviorForm.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaForm.tsx
- ui/apps/platform/src/css/trumps.css
1. Retrieved the count of current violations for policy being edited, at the Wizard level.
2. Save flag if violations exist
3. Pass down to PolicyBehaviorForm and PolicyCriteriaForm
4. Disable Lifecycle inputs and show message on PolicyBehaviorForm, and on PolicyCriteriaForm.
Created a non-default policy and triggered violations.
> ROX-16659: Prevent policy lifecycle and criteria change when active alerts exist

- go.mod
This PR is not required as we have replace statement for runc but looks like some scanning tools do not recognize it.
https://github.com/stackrox/stackrox/blob/303752244696f8ba7c7c1180a40bbd55c8c54c62/go.mod#L419
Fixes:
- https://github.com/stackrox/stackrox/security/dependabot/158
- https://github.com/stackrox/stackrox/security/dependabot/159
- https://github.com/stackrox/stackrox/security/dependabot/160
CI
> Bump runc version

- ui/apps/platform/package.json
- ui/apps/platform/src/hooks/useWidgetConfig.test.tsx
- ui/apps/platform/src/services/AuthService/AccessTokenManager.test.js
- ui/apps/platform/src/services/AuthService/addTokenRefreshInterceptors.test.js
- ui/apps/platform/src/utils/networkGraphUtils.test.js
- ui/packages/ui-components/package.json
- ui/yarn.lock
First step to upgrade eslint-related devDependencies.
Auto-fix 21 `jest/no-alias-methods` errors from attempted eslint-plugin-jest 27.2.1 attempted upgrade because they are backward compatible, but wait on that upgrade, because it indirectly causes hundreds of typescript-eslint errors that await future investigation.
```text
dependencies:
"@typescript-eslint/utils" "^5.10.0"
```
1. `yarn lint`
* ui folder
* ui/apps/platform folder
* ui/packages/ui-components folder
2. `yarn lint:fix` in ui/apps/platform folder
3. `yarn test` and then press a
* ui/apps/platform folder
* ui/packages/ui-components folder
> Update eslint-plugin-jest-dom-4.0.3 devDependencies in ui

- CHANGELOG.md
- central/role/datastore/permissionset_ids.go
- central/role/datastore/singleton.go
- central/role/default.go
Adds a new permission set and the associated default role.
These provide minimum permissions to display the Network Graph pages
> ROX-14324: Add default role and permission set to display network graph

- .github/actions/cache-ui-dependencies/action.yaml
* `npm-v2` is too generic, it could happen that a lock file with different contents is taken as input
* we also deleted a cache that we believe was corrupted as it didn't build properly
* build failure: https://github.com/stackrox/stackrox/actions/runs/4859026771/jobs/8661140006
* successful build: https://github.com/stackrox/stackrox/actions/runs/4859509864/jobs/8662358093?pr=5876
> fix GHA: remove too generic UI cache

- go.mod
- go.sum
- tests/roxctl/bats-tests/local/roxctl-netpol-generate-development.bats
- tests/roxctl/bats-tests/local/roxctl-netpol-generate-release.bats
Upgrading package version and modifying expected error messages in the tests accordingly.
No user facing changes
> Upgrade NP-Guard's cluster-topology-analyzer to 1.7.0

- .github/workflows/build.yaml
- ui/apps/platform/src/Components/PatternFly/ConfirmationModal/ConfirmationModal.css
- ui/apps/platform/src/Components/PatternFly/ConfirmationModal/ConfirmationModal.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsListPage.tsx
- ui/apps/platform/src/Containers/Policies/PolicyPage.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step2/PolicyBehaviorForm.tsx
- ui/apps/platform/src/Containers/Policies/policies.utils.ts
- ui/apps/platform/src/css/trumps.css
This is the 2nd stage in a group of three tasks to improve the UX around lifecycles and criteria in the Policy Wizard.
1. ROX-16659: Prevent policy lifecycle and criteria change when active alerts exist
2. **ROX-16650: Warn when editing lifecycle stage that existing criteria will reset, when no active alerts _(this PR)_**
3. ROX-16651	Prevent users from selecting combinations of criteria that don't adhere with the selected lifecycle stages (requires code design review before implementation)
As preliminary work, I moved the code that calculates the new values for Lifecycle based on user input into a pure function. For a new Policy, the input handle calls this newly-extracted function to get its values and uses those to update the form object.
Because of the way our Policy Wizard / …
> ROX-16650: Warn when editing lifecycle stage that existing criteria will reset

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts
Adds the main data table for the deployment single page.
Visit a deployment single page and view the main table:
Loading state:
Error state:
Viewing the embedded table with multiple related images:
> Add data tables for deployment single page

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
There have been cases where UDP port 0 is reported in the network graph. This occurs in the connection between collector and kube-dns when the kernel module probe is used. Kernel module probes are in the process of being removed, but we need to ensure that this problem does not occur with other types of probes in the future. More information can be found here https://issues.redhat.com/browse/ROX-16722
Deploy using your favorite method. Set the collection method to KERNEL_MODULE.
cd qa-tests-backend
export ROX_POSTGRES_DATASTORE=true
Follow other steps needed to run e2e tests locally
./gradlew test --tests=NetworkFlowTest
The following is observed
NetworkFlowTest > Verify ports are greater than 0 FAILED
Condition not satisfied:
property.port > 0
|        |    |
|        0    false …
> Jv rox 16819 e2e test for udp port 0 issue

- ui/package.json
Prerequisite for TypeScript 5.1 upgrade about May 30
https://github.com/microsoft/TypeScript/issues/53031
https://devblogs.microsoft.com/typescript/announcing-typescript-5-1-beta/#es2020-and-node-js-14-17-as-minimum-runtime-requirements
> TypeScript 5.1 now ships JavaScript functionality that was introduced in ECMAScript 2020. As a result, at minimum TypeScript must be run in a reasonably modern runtime. For most users, this means TypeScript now only runs on Node.js 14.17 and later.
CI for ui-e2e-tests currently runs Node.js 16.17.1 and UI team runs 16.y.z so this is for good citizenship in open source community.
2. `yarn lint`
* in ui/apps/platform
* in ui/packages/tailwind-config
* in ui/packages/ui-components
> Increase minimum version of node to 14.17.0 in ui

- scripts/ci/bats/lib_junit.bats
- scripts/ci/lib.sh
- tests/e2e/bats/check_for_stackrox_OOMs.bats
https://github.com/stackrox/stackrox/pull/4917 caused the prow JUnit panel to spin and not render results for gke-version-compatibility-tests [e.g.](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-nightlies-gke-version-compatibility-tests/1653265032659603456). I'm guessing that this is because in their current form,  the `save_junit_...()` methods can create multiple JUnit XML files with the same testsuite/class and testname. 
This PR creates a record of JUnit results for the same JUnit class and uses that to create multiple test case entries as or if needed. A simple line by line record for results was used because editing XML is too hard for me (in bash at least).
Note: this may not fix the original problem but I think its a better approach and may …
> CI: Fix spinning JUnit

- sensor/kubernetes/listener/resources/secrets.go
Secrets are not deduped correctly on openshift
Ran this image, and looked at the metrics. When we bounce sensor pod then central metrics show that no more secrets are processed
> Update secret event

- pkg/auth/user/util.go
- pkg/auth/user/util_test.go
In https://issues.redhat.com/browse/ROX-14521, we added access log as part of Central logs. Considering we don't show access scope in access log, `permissions` field does not provide much useful formation. To avoid on-call engineers confusion, let's remove `permissions` and leave only `roleNames` as a way to determine what level of access user actually had.
> Remove aggregated permissions from access log

- pkg/renderer/kubernetes_helm.go
- pkg/renderer/kubernetes_helm_test.go
Cert rotation seems to be breaking if cluster image tag is a SHA reference. 
This PR aims to "stop the bleeding" and bring Cert Rotation back to a healthy state. The underlying issue will eventually be fixed by decoupling the secret rendering from full sensor bundle rendering or by implementing support for SHAs in manifest installations.  
See comments and commit messages for more context.
**Cluster "remote" has digest reference:**
**Generating manifest bundles still fails with error:**
```
message: unable to get required cluster information: pre-rendering sensor chart: instantiating sensor chart template: instantiating file internal/defaults/50-images.yaml: instantiating template file internal/defaults/50-images.yaml: template: …
```
> ROX-16212: Fix cert rotation broken on some installations

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageHeader.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePageHeader.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ComponentLocationTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DatePhraseTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/FilterAutocomplete.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/FilterResourceDropdown.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageDetailBadges.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx
One commit -> one minor update
1. Add the "images by severity" column to the ImageCVE page deployment tab table
2. Add tooltips to all dates in all tables
3. Add tooltip/icon to component vuln table when "source" is equal to "OS"
4. Add the image `tag` to the name in all table cells
5. Update pagination to default to 20 for all tables (PF component defaults are 10, 20, 50, 100)
6. Restrict the filter toolbar dropdown to only appropriate resources based on the page context
Visit the ImageCve page and click the deployment tab to view the images by severity column:
Visit any table with dates and hover over the value in the date column:
Open an embedded component table when the vulnerability is a language-level vuln:
When it is an OS vuln: …
> Minor UX details for Workload CVEs

- ui/apps/platform/src/Containers/VulnMgmt/Reports/Components/ScheduleText.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageHeader.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePageHeader.tsx
- ui/apps/platform/src/types/report.proto.ts
- ui/apps/platform/src/utils/dateUtils.ts
Adds types to our date utils, which previsouly inferred `any` for all functions.
Type level change only.
> Add type annotations to date utils file

- .github/actions/cache-ui-dependencies/action.yaml
- ui/Makefile
Triggered by https://github.com/stackrox/stackrox/pull/5865 merge failing `pre-build-ui`: https://github.com/stackrox/stackrox/actions/runs/4891147510/jobs/8731299737#step:9:37
Related thread https://redhat-internal.slack.com/archives/CELUQKESC/p1683284029430709
The problem with the former approach is that `node_modules` contents must be very specific to what's requested by `yarn.lock` and `package.json` files. Any unwanted dependencies that came from GHA cache will be there and can interfere.
In the new approach, we exclude `node_modules` from saving and restoring through GHA cache and do that only to yarn cache (verified that the location reported by `yarn cache dir` is `/usr/local/share/.cache/yarn/v6`). Further, when we run `yarn install`, `yarn` should look for packages in that cache …
> Exclude `node_modules` from UI caching

- central/notifier/processor/mocks/processor.go
- central/notifier/processor/processor.go
- central/notifier/processor/processor_impl.go
- central/notifier/processor/processor_impl_test.go
Short circuit notification processing in Central for secured cluster notifiers, when feature is turned on.
Added unit test.
Unit test only
> ROX-16748: Short circuit notification processing in Central for secured cluster notifiers, when feature is turned on.

- .github/actions/cache-gradle-dependencies/action.yaml
- .github/actions/cache-ui-dependencies/action.yaml
GitHub does not like v2 action and says its node is obsolete.
[link](https://github.com/stackrox/stackrox/actions/runs/4893751877)
None of these:
* CI is green.
> Update GHA cache action from v2 to v3

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/TopCvssScoreBreakdown.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/CvssTd.tsx
As titled.
Visit a CVE single page, and view that the CVSS is present in the top level of the table.
> Add missing CVSS to ImageCVE page Images table

- ui/apps/platform/cypress/constants/VulnManagementPage.js
- ui/apps/platform/cypress/helpers/visit.js
- ui/apps/platform/cypress/helpers/vulnmanagement/entities.js
- ui/apps/platform/cypress/integration/vulnmanagement/clusters.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/componentsNonPostgress.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/deployments.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/deploymentsNonPostgress.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/imageComponents.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/images.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/namespaces.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/namespacesNonPostgress.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/nodeComponents.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/policies.test.js
This conditional testing pattern is safe only if all conditional rendering scenarios are likely to occur. It is risky for edge cases that rarely occur.
Intermittant test failures if links do not exist for fixable vulnerabilies or failing deployments:
> Timed out retrying after 4000ms: Expected to find content: '/^\d+ Fixable$/' within the element: <div.rt-td.w-1/8.p-2.flex.items-center.font-600.text-base-600.text-left.border-r-0.leading-normal> and with the selector: 'a' but never did.
> Timed out retrying after 4000ms: Expected to find content: '/^\d+ failing deployments?$/' within the element: <div.rt-td.w-1/8.p-2.flex.items-center.font-600.text-base-600.text-left.border-r-0.leading-normal> and with the selector: 'a' but never did.
Tests make an **invalid assumption** that images, …
> Provide conditional integration testing for Vulnerability Management links

- image/templates/helm/stackrox-central/config/centraldb/postgresql.conf.default
Looks like we are leaving some performance on the table:
Previously effective_cache_size and maintenance_work_mem were set to 6GB and 1GB, but were dropped in the consolidation of the postgresql.conf
90 conns * 10MB overhead estimated + 90 conns(ish) + parallel workers can spawn more * 40MB (work_mem) + 3 (autovacuum_max_workers ) * 512MB (maintenance_work_mem) + shared_buffers(2GB) ~= 8GB. Default resource requests are 4 CPU and 8 GB. Limits are 8 CPU and 16 GB so even here we may be leaving some performance on the table, but keeping it as close to requests as possible to avoid eviction / ooms
4 GB effective_cache_size is just a hint to the planner. This one is pretty difficult to set in kubernetes because it's not clear how much cache is available, but 4GB is the default anyways
If any …
> Specify memory parameters in postgresql.conf

- central/main.go
- central/notifier/processor/mocks/processor.go
- central/notifier/processor/notifier_set.go
- central/notifier/processor/notifier_set_test.go
- central/notifier/processor/processor.go
- central/notifier/processor/processor_impl.go
- central/notifier/service/service.go
- central/notifier/service/service_impl.go
- central/notifier/service/service_impl_test.go
- central/notifier/service/singleton.go
- central/sensor/service/connection/connection_impl.go
- central/sensor/service/connection/manager.go
- central/sensor/service/connection/manager_impl.go
- central/sensor/service/connection/mocks/manager.go
- pkg/centralsensor/caps_list.go
Central side changes to send NotifierSync messages when CRUD operations on notifiers are performed in Central, and initial sync to sensor, iff ROX_SECURED_CLUSTER_NOTIFICATIONS is true
Added sensor capability for secured cluster notifications.
Note: Secured cluster side processing will come in following PRs
Manual testing TBD, once sensor and admission controller changes come in, in following PRs
> ROX-16753: Central side changes to send NotifierSync to sensor

- central/declarativeconfig/manager_impl.go
- central/declarativeconfig/manager_impl_test.go
- pkg/declarativeconfig/configuration.go
- pkg/declarativeconfig/configuration_test.go
This PR refines the current errors emitted by the configuration unmarshal of declarative config.
Previously, this was a multierror with little value:
```
unable to unmarshal the configuration: 4 errors occurred:
* yaml: unmarshal errors:
line 1: field cool not found in type declarativeconfig.AuthProvider
line 2: field value not found in type declarativeconfig.AuthProvider
* yaml: unmarshal errors:
line 1: field cool not found in type 
declarativeconfig.AccessScope
line 2: field value not found in type declarativeconfig.AccessScope
* yaml: unmarshal errors:
line 1: field cool not found in type declarativeconfig.PermissionSet
line 2: field value not found in type declarativeconfig.PermissionSet
* yaml: unmarshal errors:
line 1: field cool not found in type declarativeconfig.Role
line 2: …
```
> Refine declarative config errors

- central/cluster/datastore/telemetry.go
Secured cluster telemetry data contains of a wrongly formatted "Provider" property.
The PR fixes the formatting and also adds the "Provider Verified" property, which is also a part of generic provider metadata.
New secured cluster properties as seen on Segment:
```json
"traits": {
"Admission Controller": false,
"CPU Capacity": 12,
"Cluster Type": "KUBERNETES_CLUSTER",
"Collection Method": "EBPF",
"Collector Image": "quay.io/stackrox-io/collector",
"Main Image": "quay.io/stackrox-io/main",
"Managed By": "MANAGER_TYPE_UNKNOWN",
"Orchestrator Version": "v1.25.6",
"Priority": 1,
"Provider": "Azure",
"Provider Region": "eastus",
"Provider Verified": true,
"Provider Zone": "",
"Slim Collector": true,
"Total Nodes": 3
}
```
> ROX-16850: Fix secured cluster provider name

- .golangci.yml
> Minor: remove forgotten dash from `.golangci.yml`

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageResources.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/ImageResourceTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/DeploymentResourceTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageResources.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
Enables the "Resource" tabs for images and deployments, and points links from the tables on the main page to them.
From the workload cve overview page, view the image table and click one of the "# deployments" links in the table.
Error state:
From the workload cve overview page, view the deployment table and click one of the "# images" links in the table.
> Add image/deployment resource tables for Workload CVEs

- qa-tests-backend/src/test/groovy/DeploymentTest.groovy
- qa-tests-backend/src/test/groovy/RuntimePolicyTest.groovy
- qa-tests-backend/src/test/groovy/RuntimeViolationLifecycleTest.groovy
Backport https://github.com/stackrox/stackrox/pull/5802 to release 3.73 to avoid flakes with release CI.
> ROX-16693: RuntimePolicyTest allow apt failure (backport 3.73)

- qa-tests-backend/src/test/groovy/DeploymentTest.groovy
- qa-tests-backend/src/test/groovy/RuntimePolicyTest.groovy
- qa-tests-backend/src/test/groovy/RuntimeViolationLifecycleTest.groovy
Backport  #5802 to release 3.74.
> ROX-16693 RuntimePolicyTest allow apt failure (backport 3.74)

- .github/workflows/cut-rc.yml
- .github/workflows/start-release.yml
* creates OSCI configuration in upstream release flow for new releases from the `release-x.y` templates instead of the master configuration. The templates were created in https://github.com/openshift/release/commit/11e4e5088f49d864e8d9e13a0e34727c4ec5c371. 
I will not backport changes from this PR to release branches for 3.x and 4.0, as neither will run `start-release` code to produce new OSCI configuration)
Tested in https://github.com/stackrox/test-gh-actions/pull/95, produced https://github.com/openshift/release/pull/39103 (file names fixed in https://github.com/stackrox/test-gh-actions/pull/95/commits/e34e3b43babf0d4e51c16cb4ad5de591c6a5ea35)
> ROX-14908 (GHA): create OSCI configuration for new releases from template instead of master configuration

- qa-tests-backend/scripts/run-part-1.sh
This follows up on https://github.com/openshift/release/pull/38678#discussion_r1179631178 discussion.
- This eliminates `QA_TEST_TARGET` environment variable.
- Rehearse tests will run as full tests after the change. I hope that's not a big impact in terms of costs and waiting time, but more confidence. Although, I can restore the rule to do BAT there.
- This also fixes the problem that postsubmit postgres-qa-e2e-tests were running as BAT. E.g. [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-merge-gke-postgres-qa-e2e-tests/1653499367778160640):
```
INFO: Tue May  2 21:13:04 UTC 2023: QA Automation Platform Part 1
INFO: Tue May  2 21:13:04 UTC 2023: An unexpected context. Defaulting to BAT tests only...
```
The next step for me would be …
> Change rules to run BAT QA tests only in PR context without the label

- ui/apps/platform/src/Containers/ConfigManagement/Entity/widgets/ScopedPermissions.js
1. Color text causes accessibility problems like assumption of perfect color vision.
2. Color theme classes from template literal like `bg-${colorClass}-200 text-${colorClass}-700` and `border-${colorClass}-300` prevents Tailwind optimization to purge unused classes.
Plain text seems like an alternative, because semantics of colors does not fit create/update and delete.
1. Render verbs as plain text.
This is the caboose of the Tailwind template literal train, along with #5923
1. Black text in classic dark theme might be solved by PatternFly dark theme.
2. Now that accessible alternatives have replaced template literals, how many complete string classes remain for the most used levels of text and background colors?
|         text class | results | files |
|               ---: |    ---: | …
> Replace text color in ScopedPermissions

- Makefile
Updates the manually built arm image to 1.20.3
Local builds
> Update ARM build image to Go 1.20.3

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
Enable Network Flow test.
Test might still be flaking, but to get a new ticket with prow logs, I propose that we enable this test now and monitor it in nightly/master CI runs. 
Ran in CI 5 times. Step failed for other reasons than because of enabled test.
> ROX-7047: Network Flow test 

- central/audit/audit.go
- central/graphql/resolvers/compliance_management.go
- central/graphql/resolvers/utils.go
- central/graphql/resolvers/vulnerability_requests.go
- central/main.go
- pkg/audit/audit.go
- pkg/grpc/routes/routes.go
- pkg/grpc/server.go
- pkg/httputil/status_tracking_writer.go
- pkg/sac/observe/interceptors.go
This PR is adding audit logs for custom routes that are modifying the status of the ACS stack.
The following changes are made:
- HTTP Interceptor handler is added to auditor
- several custom routes are marked to have enabled audit
- helper function for status code error is moved into `StatusTrackingWriter` - so that it can be reused
- audit log for GraphQL mutation `complianceTriggerRuns` is added
**EDIT: After review**
- removed not used `log` variable from `central/audit/audit.go`
- removed internal `sendAuditMessage` function and promoted `SendAdhocAuditMessage` to `SendAuditMessage`, because it was the same function
- moved `Resolver.processWithAuditLog` to `central/graphql/resolvers/utils.go`, because it's now used in vulnerability_requests and compliance_management.
For additional …
> ROX-16737: Add audit logs for custom routes

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.css
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/FixedByVersionTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/SeverityCountLabels.tsx
*Note that this is easier to review with "Hide whitespace" enabled*
Fixes the table layouts to avoid overly small columns by doing the following:
- Setting all table headers to `noWrap`, which ensures each column will never be smaller than the length of its text
- Setting `noWrap` on table cells that look bad when wrapping, and do not have unbounded length (most of the cells containing icons)
- Allowing tables to grow larger than their container, and when they do, adding a horizontal scrollbar consistent with other pages in the app
Table with ample space:
Reduced space:
Cramped/horizontal scroll:
> Update WorkloadCVE table layouts to fit columns and avoid wrapping.

- .github/CODEOWNERS
- .github/workflows/update_scanner_periodic.yaml
Scanner is migrating into this repo, so this PR adds a few CODEOWNERS entries for the team
Nah
> Add CODEOWNERS entries for Scanner

- central/auth/userpass/auth.go
- central/centralhealth/service/service_impl.go
- central/clusterinit/service/service_impl.go
- central/main.go
- central/role/accessscope_ids.go
- central/role/datastore/datastore_impl_test.go
- central/role/datastore/singleton.go
- central/role/default.go
- central/role/default_test.go
- central/role/mapper/always_admin_mapper_impl.go
- pkg/declarativeconfig/transform/role.go
- pkg/declarativeconfig/transform/role_test.go
- pkg/defaults/accesscontrol/access_scope.go
- pkg/defaults/accesscontrol/permission_set.go
- pkg/defaults/accesscontrol/role.go
This PR allows roles created via declarative configuration to reference default resources (specifically permission sets and access scopes), which previously wasn't possible.
The change required refactoring of the existing role package which defined the default resources.
Specficially, the following was done:
- a new `accesscontrol` package was created under `pkg/defaults`.
- the consts for roles and access scopes have been moved there. As a result, all current role imports have been moved to `accesscontrol` within central.
- the transformer for roles has been adjusted to first check if the referenced permission set or role is a default one before attempting to create a UUID out of the name.
One caveat is within this PR:
This currently only works for postgres. In non-postgres environments, …
> ROX-16893: Allow references to default resources in declarative roles

- pkg/defaults/accesscontrol/access_scope.go
During the refactoring of the default roles / access scopes / permission sets, there was a typo in the `Deny All` access scope: `Deny all`. This lead to failing UI E2E tests, this PR fixes the typo.
- see CI passing (this time also with UI E2E tests)
> Fix Deny All typo

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#12-12-0
* Fixed an issue in Electron where devtools gets out of sync with the DOM occasionally.
* Upgraded `plist` from `3.0.5` to `3.0.6` to address CVE-2022-26260 NVD security vulnerability
* Upgraded `engine.io` from `6.2.1` to `6.4.2` to address CVE-2023-31125 NVD security vulnerability.
> Update cypress 12.12.0 devDependencies in ui

- .github/workflows/scripts/prepare-upgrade-test.sh
- .github/workflows/upgrade-test.yml
With central-db part of deployment, the GKE cluster provisioned for the upgrade tests is too small.
Making it bigger with this PR in line with the demo cluster from cut-rc workflow.
Successful run: https://github.com/stackrox/stackrox/actions/runs/4979408086. 
Successful workflow run: https://github.com/stackrox/stackrox/actions/runs/4979408086.
> fix GHA: bump upgrade test cluster resources

- central/networkpolicies/service/service_impl.go
- central/notifier/processor/mocks/processor.go
- central/notifier/processor/processor.go
- central/notifier/processor/processor_impl.go
- central/notifier/processor/processor_impl_test.go
- central/notifier/service/service_impl.go
- central/notifiers/cscc/cscc.go
- pkg/notifiers/awssh/notifier.go
- pkg/notifiers/email/email.go
- pkg/notifiers/generic/generic.go
- pkg/notifiers/jira/jira.go
- pkg/notifiers/mocks/alert_notifier.go
- pkg/notifiers/mocks/audit_notifier.go
- pkg/notifiers/mocks/notifier.go
- pkg/notifiers/mocks/report_notifier.go
- pkg/notifiers/mocks/resolvable_alert_notifier.go
- pkg/notifiers/notifier.go
- pkg/notifiers/pagerduty/pagerduty.go
- pkg/notifiers/slack/slack.go
- pkg/notifiers/splunk/splunk.go
- pkg/notifiers/sumologic/sumologic.go
- pkg/notifiers/syslog/syslog.go
- pkg/notifiers/teams/teams.go
Central side changes to send network policy yamls via secured clusters notifiers
CI only, manual testing once secured cluster side changes come in.
> ROX-16756: Central side changes to send network policy yamls via secured clusters notifiers

- qa-tests-backend/src/test/groovy/SACTest.groovy
Looks like we should use `intersect` instead of cardinality as it's important what is in the set.
CI
> ROX-16692: Use intersect instead of cardinality

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
Per title. This test is failing in some cluster flavors and creating a significant amount of noise. 
> ROX-16849: Disable port > 0 test

- pkg/env/sensor.go
- sensor/kubernetes/listener/resources/service_store.go
The function `getRoutesForServices` does not lock before reading from the service store. This is a potential data race if another goroutine tries to access the service store. This function is only called [here](https://github.com/stackrox/stackrox/blob/74476b76b39dfe2e9cdaeecc3e9eaf262097389f/sensor/kubernetes/listener/resources/service.go#L192), so it only affects the re-sync path (to be removed soon).
If any of these don't …
> Fix data race in service store

- qa-tests-backend/build.gradle
A number of recent merge test failures are because tests are taking > 3 hours. This PR bumps the overall test timeout to 3.5 hours. 
> CI: Increase overall QA e2e test timeout

- ui/apps/platform/src/Components/PatternFly/IconText/ImageActiveIconText.tsx
- ui/apps/platform/src/Components/PatternFly/IconText/NotApplicableIconText.tsx
- ui/apps/platform/src/Components/PatternFly/IconText/PolicyDisabledIconText.tsx
- ui/apps/platform/src/Components/PatternFly/IconText/PolicyStatusIconText.tsx
- ui/apps/platform/src/Components/PatternFly/IconText/VulnerabilityFixableIconText.tsx
Follow up after first draft in #5696
Thanks to Mansur for guiding the discussion by Design and Product.
| entity        | text        | icon                  | color         |
| :---          | :---        | :---                  | :---          |
| policy        | Enabled     | CheckIcon             | normal black  |
| policy        | Disabled    | MinusIcon             | normal black  |
| vulnerability | Fixable     | WrenchIcon            | normal black  |
| vulnerability | Not fixable | MinusIcon             | normal black  |
| policy        | Pass        | CircleCheckIcon       | success green |
| policy        | Fail        | ExclamationCircleIcon | danger red    |
Bonus improvements for consistency:
* ImageActiveIconText renders CheckIcon and MinusIcon like policy Enabled/Disabled …
> Improve icons for Enabled Fixable Pass in UI

- ui/apps/platform/src/Components/DetailsOverlay/DetailsOverlay.tsx
- ui/apps/platform/src/Components/NumberedGrid/NumberedGrid.js
- ui/apps/platform/src/Components/NumberedList/NumberedList.js
- ui/apps/platform/src/Components/SubHeader/SubHeader.js
- ui/apps/platform/src/Components/TableGroup.js
- ui/apps/platform/src/Components/TableHeader.js
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionsTable.tsx
- ui/apps/platform/src/Containers/BreadCrumbs/EntityBreadCrumb.js
- ui/apps/platform/src/Containers/Clusters/Components/FormFieldRequired.js
- ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/SecretsMostUsedAcrossDeployments.js
- ui/apps/platform/src/Containers/ConfigManagement/Entity/Policy/Policy.js
- ui/apps/platform/src/Containers/ConfigManagement/SidePanel/BreadCrumbs.js
- ui/apps/platform/src/Containers/Dashboard/SummaryCounts.tsx
- ui/apps/platform/src/Containers/Images/VulnsTable.js
- ui/apps/platform/src/Containers/Login/TestLoginResultsPage.js
- ui/apps/platform/src/Containers/Network/SidePanel/NetworkDeploymentOverlay/DeploymentDetails/ContainerConfigurations.tsx
- ui/apps/platform/src/Containers/Network/SidePanel/NetworkDeploymentOverlay/DeploymentDetails/SecurityContext.tsx
- ui/apps/platform/src/Containers/Network/SidePanel/NetworkDeploymentOverlay/Flows/NetworkBaselines/NetworkBaselinesTable/GroupedStatusTableCell.tsx
- ui/apps/platform/src/Containers/Risk/ContainerConfigurations.js
- ui/apps/platform/src/Containers/Risk/Process/BinaryCollapsible.js
- ui/apps/platform/src/Containers/Risk/Process/DiscoveryCardHeader.js
- ui/apps/platform/src/Containers/Risk/SecurityContext.js
- ui/apps/platform/src/Containers/SystemHealth/Components/ClusterHealth.tsx
- ui/apps/platform/src/Containers/SystemHealth/Components/IntegrationsHealth.tsx
- ui/apps/platform/src/constants/form.constants.ts
Follow up #5977
1. PatternFly does not include an italic file for RedHatText font.
2. PatternFly typography guidelines do not even mention italic font style.
https://www.patternfly.org/v4/guidelines/typography
3. PatternFly does not provide a utility class for italic font style.
You must specify a `style` prop: `style={{ fontStyle: 'italic' }}`
4. Microsoft style guide recommends against italic formatting for **instructions in UI**. It is reasonable to infer that it recommends against italic formatting in **UI itself**.
https://learn.microsoft.com/en-us/style-guide/procedures-instructions/formatting-text-in-instructions#in-the-ui-and-general-content
> Instructions can also appear in the UI itself and in content other than documentation, such as blogs and marketing. In this content, avoid …
> Delete occurrences of Tailwind italic class

- ui/apps/platform/cypress/constants/PoliciesPage.js
- ui/apps/platform/cypress/integration/policies/exportPolicy.test.js
- ui/apps/platform/cypress/integration/policies/policiesTable.test.js
- ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.tsx
UX recommendation for calling out default policies is to add a column, specifying System or User.
Changes are:
1. Add a column labeled "Origin" after the Status column, in which default policies are designated System, and any user-created policies are designated User. (Bonus: I made this column sortable.)
2. Remove the "Description" column
3. Make the table rows expandable, and now show the Description in the expanded row when a row is expanded. (Uses the same code pattern as is used in the new VM 2.0 CVEs table to reveal the CVE description.)
Updated Cypress tests for the Policies table.
Also, manual testing
Policies table before changes:
After changes:
Origin column sorted ascending:
Origin column sorted descending:
With Description added in expanded row:
> ROX-16248: Add column for policy origin

- qa-tests-backend/src/main/groovy/util/NetworkGraphUtil.groovy
This PR intends to fix timeout issue on P/Z with `Verify two flows co-exist if larger network entity added first` test which is part of `ExternalNetworkSourcesTest`.
This PR intends to fix [ROX-16938](https://issues.redhat.com/browse/ROX-16938)
> Increase NETWORK_FLOW_UPDATE_CADENCE_IN_SECONDS for few ARCH's

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
Apparently the network graph and the network policies are not in sync. We try to fix that by waiting at the beginning of the test to make sure that they have enough time to observe the same conditions.
- CI - run 3 times (with pass) - `gke-qa-e2e-tests`
> ROX-16924: Fix flake in 'Verify generated network policies' 

- .github/workflows/unit-tests.yaml
go-junit-reporter mark cancelled tests as failed leading to incorrect tasks in jira. This PR skips issues reporting if workflow was cancelled. 
- https://github.com/orgs/community/discussions/26303#discussioncomment-3251302
> ROX-16999: Do not run junit2jira on cancelled jobs

- scripts/k8s/prometheus-local-port-forward.sh
This utility script can be used if a developer needs access to their `/metrics` endpoint.
This script mainly follows the same approach as `local-port-forward.sh` with a few tweaks:
* https://github.com/stackrox/stackrox/blob/0a0be38de8110e06347f4df43ff5af67c82d9d64/scripts/k8s/local-port-forward.sh#L7-L7 line is removed as killing parallel port-forwards can delete port-forward to ACS API port
* Verification that the port is ready is done using `/metrics` endpoint
* Default ports are adjusted to `9090`
* Displayed link is adjusted to `http://localhost:${LOCAL_PORT}/metrics`
1. Executed the script
> Script for port-forwarding to Prometheus metrics endpoint

- ui/apps/platform/cypress/integration/policies/policyWizardStep3.test.js
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/BooleanPolicyLogicSection.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaForm.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx
- ui/apps/platform/src/Containers/Policies/policies.utils.ts
- ui/apps/platform/src/utils/arrayUtils.test.ts
- ui/apps/platform/src/utils/arrayUtils.ts
This PR contains two related additions:
1. Add the Lifecycle Stages that are allowed for each policy criterion to that criterion's descriptor in `ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx`, based on the newly-updated policy documentation in this spreadsheet, https://docs.google.com/spreadsheets/d/17TSHuhtbktVrHvbqfgChc8m7RxNyfILNGFYWZ4PTYdU/edit#gid=63129838 
2. Use those allowed Lifecycle Stages to filter the criteria available in Step 3 of the Policy edit wizard. There was already a chain of conditionals for which criteria to show (based on various checks). This just adds one final filter to that chain, by a policy-specific utility function which in turn calls a potentially-reusable new array filtering function.
Example of the filter logic:
* A …
> R)X-16651: Filter policy criteria available based on Lifecycle Stages

- central/networkpolicies/datastore/datastore_impl.go
- central/networkpolicies/datastore/datastore_impl_test.go
- central/networkpolicies/datastore/internal/store/bolt/store_impl.go
- central/networkpolicies/datastore/internal/store/mocks/store.go
- central/networkpolicies/datastore/internal/store/store.go
- scale/workloads/10-sensors.yaml
Getting many network policies currently uses walk for historical reasons. This is incredibly slow especially if the "query" is scoped. This will be significantly faster.
*Note*: Because this commit will be cherry-picked, I have not tried to optimize the Count function, which will need the indexer to properly work and requires substantial changes. A jira will be created for this
Before this PR:
imageintegration/datastore: 2023/05/18 17:38:16.092213 singleton.go:58: Info: Completed deletion of 'sourced' image integrations
Got deleted at 11:45 so was running for a good hour and no new logs
On this PR:
```
central_active=# select count(*) from network_baselines;
count 
-------
24981
(1 row)
central_active=# select count(*) from …
```
> Use search for network policies instead of walks

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/SeverityCountLabels.tsx
Updating `SeverityCountLabels` component to reflect when severities are hidden via filter. The data should reflect properly even when the table is not filtered by severity.
CVE -> Deployment table (unfiltered)
CVE -> Deployment table (filtered)
Overview page -> CVEs (unfiltered)
Overview page -> CVEs (filtered)
Overview page -> Images (unfiltered)
Overview page -> Images (filtered)
Overview page -> Deployments (unfiltered)
Overview page -> Deployments (filtered)
> Workflow CVEs: Updating severity count labels

- ui/apps/platform/cypress/helpers/vulnmanagement/entities.js
Problem was overlooked on GKE but occurs often on OpenShift.
Vulnerability Management Clusters should display links for deployments: should display links for deployments
> Timed out retrying after 4000ms: Expected to find element: `h2:contains("Related entities") ~ div ul li a[data-testid="DEPLOYMENT-tile-link"]:has('[data-testid="tileLinkSuperText"]:contains("120")'):has('[data-testid="tile-link-value"]:contains("DEPLOYMENTS")')`, but never found it.
cypress/helpers/vulnmanagement/entities.js
cypress/integration/vulnmanagement/clusters.test.js
Selector has 120 from deployments link in clusters table, but related entities link had 121 in side panel.
Thanks to Van for identifying the root of the problem:
Count of deployments changed between steps 1 and 3:
1. clusters page renders …
> ROX-17001: Simplify unreliable selector in Vulnerability Management integration tests

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
Updates regex to not match leftover splunk namespace when generating network policies. 
> ROX-15893: Fix "Verify network policy generator" Network Flow flake

- sensor/common/centralclient/grpc_connection.go
- sensor/common/sensor/sensor.go
- sensor/debugger/central/grpc_client.go
This PR adds a simple backoff strategy for when the gRPC connection breaks. 
I tested locally with local sensor support (#6024) connecting to a real Central instance. More information on the `Testing Performed`.
There are still many things that might fail with this (sensor does not reconcile or send `SYNC` event on reconnect), which will be tackled in the remaining of the epic ([ROX-9776](https://issues.redhat.com/browse/ROX-9776)). 
1. Deployed ACS on an infra cluster
2. Scaled sensor down to `0` replicas
3. Port-forwarded central API to `localhost:8000`
4. Ran local-sensor pointing to real Central
```
$ ROX_PREVENT_SENSOR_RESTART_ON_DISCONNECT="true" LOGLEVEL="debug" go run ./tools/local-sensor/main.go -connect-central "localhost:8000"
```
5. After connection was alive and steady, …
> ROX-17039: Sensor retries gRPC connection when failed

- tests/backup_test.go
Non-groovy test fail in backup test frequently due to timeout. This PR increate the timeout.
screenshots.
> Add timeout to backup test

- generated/api/v1/authprovider_service.pb.go
- generated/api/v1/debug_service.pb.go
- generated/internalapi/central/sensor_events.pb.go
- generated/storage/cluster.pb.go
- generated/storage/group.pb.go
- generated/storage/labels.pb.go
- generated/storage/network_policy.pb.go
- generated/storage/node.pb.go
- generated/storage/notifier.pb.go
- generated/storage/rbac.pb.go
- generated/storage/secret.pb.go
- generated/storage/service_account.pb.go
- generated/storage/test.pb.go
- generated/test/test.pb.go
Failed job: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-release-3.74-merge-grouped-static-checks/1660897599969824768
I did: `make proto-generated-srcs`
Successful job: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/6124/pull-ci-stackrox-stackrox-release-3.74-grouped-static-checks/1660905949495300096. 
Let's ignore pending E2E tests.
I will ask the responsible team to look at the `local-roxctl-tests` failure.
> 3.74: fix grouped-static-tests: make proto-generated-srcs

- tests/roxctl/bats-tests/local/expect/flavor-interactive-dummy.expect.tcl
- tests/roxctl/bats-tests/local/expect/flavor-interactive-postgres.expect.tcl
- tests/roxctl/bats-tests/local/expect/flavor-interactive.expect.tcl
Failed job: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-release-3.74-merge-local-roxctl-tests/1660897601647546368
Cherry-picked https://github.com/stackrox/stackrox/pull/4795
Successful run: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/6125/pull-ci-stackrox-stackrox-release-3.74-local-roxctl-tests/1660921326233194496.
> 3.74: fix local roxctl tests

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/sortUtils.test.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/sortUtils.tsx
As titled.
Visit the overview page CVE list and see that summaries and score versions are available.
With multiple score versions, all versions will be displayed in the parens (simulated).
> Add CVE summary and score versions to workload cve list

- scripts/ci/lib.sh
Per title. There is CSV data with a column like:
```
"Verify k8s exec detection into [k8seventnginx2, k8seventprivnginx2] with addl groups [field_name: ""Privileged Container""
values {
value: ""true""
}
]"
```
Ran a manual load of previously failed data.
> CI: Allow quoted newlines in results

- central/graphql/resolvers/image_cve_core.go
- central/views/imagecve/db_response.go
- central/views/imagecve/mocks/types.go
- central/views/imagecve/types.go
- central/views/imagecve/view_impl.go
- central/views/imagecve/view_test.go
- pkg/search/postgres/common.go
I added a workaround specifically for an issue in vulnerability management 2.0 for fixable query search on following pages:
- CVE Single -> Image List and Deployment List
- Image List
- Deployment List
**The actual fix is much more expansive as described in [ROX-17252](https://issues.redhat.com/browse/ROX-17252).**
For images having both fixable and non-fixable cves, query `cve:x+fixable:false` returns an image containing `cve:x` and has some non-fixable cves instead of the images where `cve:x` is not fixable.
Consider the following image-cve map:
```
img  |  cve  | fixedby | isfixable 
------+-------+---------+-----------
sha1 | cve-1 | 1.1     | t
sha1 | cve-2 | 1.5     | t
sha2 | cve-1 | 1.1     | t
sha2 | cve-2 |         | f
```
case 1: For query `Fixable:true`, images `sha1` and …
> [ROX-17254] Workaround for vulnerability management 2.0 due to the fanned BFS search issue 

- pkg/declarativeconfig/transform/auth_provider.go
- pkg/declarativeconfig/transform/auth_provider_test.go
- pkg/declarativeconfig/transform/notifier.go
- pkg/declarativeconfig/transform/notifier_test.go
- pkg/declarativeconfig/transform/transformer.go
Add transformer from declarative config notifier to proto notifier. Supports Generic Webhook and Splunk notifiers.
1. Added unit tests
> ROX-16867: Add notifier transformer

- tests/roxctl/bats-tests/local/expect/flavor-interactive-dummy.expect.tcl
- tests/roxctl/bats-tests/local/expect/flavor-interactive.expect.tcl
Cherry-picking #4795. 
Relevant test: `local-roxctl-tests`
Successful run: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/6150/pull-ci-stackrox-stackrox-release-3.73-local-roxctl-tests/1661299169681215488
All other CI failures may be ignored, they will be fixed separately.
> 3.73: roxctl interactive mode: handle order change after Go update (#4795)

- ui/apps/platform/src/Containers/Integrations/CreateIntegrationPage.tsx
- ui/apps/platform/src/Containers/Integrations/EditIntegrationPage.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationDetailsPage.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationPage.tsx
Integration type can be deduced from breadcrumbs. This change makes UI more similar to Access Control detail pages.
> Show integration name instead of integration type as the page header

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageHeader.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
Better handles that case where a deployment is not found, likely due to an invalid ID in the URL. Instead of crashing the page this will display a 404.
Visit the deployment page with a known bad id in the URL:
> Display 404 instead of error in cases of invalid deployment id

- ui/apps/platform/src/Containers/Integrations/IntegrationDetailsPage.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/IntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationPage.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsTable.tsx
- ui/apps/platform/src/Containers/Integrations/utils/integrationUtils.ts
- ui/apps/platform/src/Containers/Integrations/utils/tableColumnDescriptor.ts
- ui/apps/platform/src/services/NotifierIntegrationsService.ts
- ui/apps/platform/src/types/notifier.proto.ts
- Display origin(User or Declarative) in the Splunk/Generic Webhook notifier list view.
- Display origin in details page for Splunk/Generic Webhook notifiers.
- Disable editing/deleting declaratively created Splunk/Generic Webhook notifiers from UI.
> ROX-16871: adjust UI for declarative notifiers

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts
Apollo's normalized cache to the rescue again...
This deletes or aliases `id` fields in graphql queries for `imageComponents` and `imageVulnerabilities` that are nested in deeper queries. This was causing duplicate data to appear in tables when multiple child objects were returned with the same ID.
Example: CVE-2013-1965 impacts two components in the below image, with with cve being fixable in one, but not fixable in the other. Due to Apollo's caching, only one instance of the `imageVulnerability` is stored in the cache and displayed in the table, leading to the `CVE Fixed In` field being incorrectly identical in both rows.
After this change, since the `id` field is aliased to something else, the data is embedded directly in the parent …
> Delete ID fields in Workload CVE gql queries to avoid cache normalization

- .gitmodules
Update docs for 3.73.5 - automation failed because branch did not exist.
Failed build: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-release-3.73-merge-push-and-release/1661385121825034240. 
> update docs 3.73.5

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/riskAcceptanceFlow.test.js
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CveStatusTabNavigation.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
Correctly scopes data according to the Observed/Deferred/False positive state of CVEs according to the selected tab.
Note that the CVE single page is unscoped - it will list all images/deployments containing the CVE regardless of the status of the CVE in that particular entity. This is a known edge case that will be addressed post MVP.
**Note: It has been decided to move this functionality to post-MVP and a follow up PR will disable the CveStatusTabs. This is left in since we will still want the logic once the functionality is re-enabled **
From the main overview page, check the total number of CVEs. In this system all CVEs are observed. CVE-2004-0971 will be marked as **Deferred** and CVE-2009-5155 will be marked as **False positive**. …
> Scope workload CVE queries to correct VulnerabilityState

- ui/apps/platform/cypress/constants/NetworkPage.js
- ui/apps/platform/src/Components/DashboardMenu/DashboardMenu.js
- ui/apps/platform/src/Components/Menu.tsx
- ui/apps/platform/src/Components/RadioButtonGroup/RadioButtonGroup.tsx
- ui/apps/platform/src/Components/TileContent/TileContent.tsx
- ui/apps/platform/src/Components/visuals/SunburstDetailSection.js
- ui/apps/platform/src/Components/workflow/EntitiesMenu/EntitiesMenu.js
- ui/apps/platform/src/Containers/Network/Graph/Overlays/Filters.tsx
- ui/apps/platform/src/Containers/Network/Graph/Overlays/NamespaceEdgeFilter.tsx
- ui/apps/platform/src/app.tw.css
- ui/apps/platform/src/css/trumps.css
- ui/apps/platform/src/index.tsx
Follow up #6053
Thanks to Dave for suggesting:
> Is there a reason we need to keep Open Sans Condensed for the buttons instead of moving to a Red Hat font variant? Or is that something we want to change as a follow up?
1. Small font size `text-sm` or even `text-xs` for buttons is not needed if the text does have `uppercase` style.
2. Heavier font weight `font-600` for buttons and sometimes lighter color `text-base-500` is not needed ditto.
3. Rarely used `font-condensed` is not needed ditto.
4. Insufficient color contrast for primary color and background-color is solved by normal text color and bold font weight `font-700` with `bg-primary-200` for classic RadioButtonGroup that is similar to PatternFly toggle.
Find in Files `font-condensed` 6 results in 5 files
1. src/Components/Menu.js
2. …
> Delete occurrences of Tailwind font-condensed and part 2 for uppercase

- tests/e2e/bats/check_for_stackrox_OOMs.bats
- tests/e2e/lib.sh
In this way OOM checks failures for each app will go to a app specific JIRA which is easier to manage than a new JIRA for each OOM instance.
Tested with a previously spotted OOM:
```
$ rm -rf ttt/*; (ARTIFACT_DIR=ttt; source ~/go/src/github.com/stackrox/stackrox/tests/e2e/lib.sh; check_for_stackrox_OOMs part-1/k8s-service-logs)
INFO: Wed May 24 14:40:36 PDT 2023: Checking part-1/k8s-service-logs/stackrox/pods/admission-control-784d6fdbf-57g2q_object.json for OOMKilled
INFO: Wed May 24 14:40:36 PDT 2023: Checking part-1/k8s-service-logs/stackrox/pods/admission-control-784d6fdbf-gvll2_object.json for OOMKilled
INFO: Wed May 24 14:40:37 PDT 2023: Checking part-1/k8s-service-logs/stackrox/pods/admission-control-784d6fdbf-rpbjz_object.json for OOMKilled
INFO: Wed May 24 14:40:37 PDT 2023: …
```
> CI: Combine OOM checks for junit2jira

- ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx
- ui/apps/platform/src/Containers/Compliance/Dashboard/ManageStandardsModal.tsx
- ui/apps/platform/src/Containers/Compliance/widgets/ComplianceByStandards.tsx
- ui/apps/platform/src/services/ComplianceService.ts
Unblock end-to-end backend-to-frontend testing to discover any problems with filtering of GraphQL responses.
1. ComplianceDashboardPage
* Add `isFetchingStandards` and `errorMessageForStandards` to component state.
* Replace `fetchComplianceStandards` with `fetchComplianceStandardsSortedByName` as temporary solution for inconsistent sorting of standards in GET /v1/compliance/standards response.
* Add `client.resetStore()` on successful save. Forgot to write under manual testing that the change causes the 10 or more GraphQL queries for compliance dashboard page. If I remember correctly, sunburst widgets were filtered.
* Replace temporary condition for `disabled` prop of **Manage standards** button.
2. ManageStandardsModal
* Rewrite filter condition.
* Rewrite TODO comment about edge case …
> ROX-17283: Filter compliance information according to hideScanResults property

- CHANGELOG.md
- central/debug/service/service.go
- central/declarativeconfig/manager_impl.go
- central/graphql/resolvers/access_scopes.go
- central/graphql/resolvers/permission_sets.go
- central/graphql/resolvers/resolver.go
- central/graphql/resolvers/roles.go
- central/group/datastore/datastore_impl.go
- central/reportconfigurations/service/common/authorizer.go
- central/reports/service/service_impl.go
- central/role/datastore/datastore_impl.go
- central/role/datastore/datastore_impl_test.go
- central/role/datastore/singleton.go
- central/role/datastore/telemetry.go
- central/role/resources/list.go
- central/role/service/service_impl.go
- central/role/store/permissionset/postgres/store.go
- central/role/store/role/postgres/store.go
- central/role/store/simpleaccessscope/postgres/store.go
- qa-tests-backend/src/test/groovy/ComplianceTest.groovy
- tools/generate-helpers/pg-table-bindings/list.go
This change is part of a series with the goal of making the configuration of user access control easier, and of limiting the risk of features not working because of missing permissions.
The goal is to bring the `Role` permission under the umbrella of the `Access` one.
CI should be sufficient
> ROX-14398: Group Role permission with Access one

- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
Changing tests to restart pods with kill via shell sh -c kill 1 instead of kill 1. Due to the central images not containing kill binary in PATH. This error was seen when testing central with test case TLSChallengeTest on s390x and power. This change will use the built in shell command for kill, if no binary is found.
Remake of pr https://github.com/stackrox/stackrox/pull/5534
> Swap to running Kill from shell for restartPodByLabelWithExecKill

- central/compliance/datastore/internal/store/postgres/compliance_config/store_test.go
- ui/apps/platform/cypress/fixtures/auth/declarativePermissionSet.json
- ui/apps/platform/cypress/fixtures/auth/mypermissionsMinimalAccess.json
- ui/apps/platform/cypress/fixtures/auth/mypermissionsNoAccess.json
- ui/apps/platform/src/Containers/AccessControl/AccessControl.tsx
- ui/apps/platform/src/Containers/AccessControl/AccessControlNoPermission.tsx
- ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopeFormWrapper.tsx
- ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopes.tsx
- ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopesList.tsx
- ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviders.tsx
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSetForm.tsx
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSets.tsx
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/PermissionSetsList.tsx
- ui/apps/platform/src/Containers/AccessControl/PermissionSets/ResourceDescription.tsx
- ui/apps/platform/src/Containers/AccessControl/Roles/RoleForm.tsx
- ui/apps/platform/src/Containers/AccessControl/Roles/Roles.tsx
- ui/apps/platform/src/Containers/AccessControl/Roles/RolesList.tsx
- ui/apps/platform/src/Containers/VulnMgmt/Reports/VulnMgmtReportForm.tsx
- ui/apps/platform/src/Containers/VulnMgmt/Reports/VulnMgmtReportTablePage.tsx
- ui/apps/platform/src/constants/accessControl.ts
- ui/apps/platform/src/types/roleResources.ts
This change is part of a series with the goal of making the configuration of user access control easier, and of limiting the risk of features not working because of missing permissions.
The goal is to bring the `Role` permission under the umbrella of the `Access` one.
This part focuses on the UI changes.
CI should be sufficient
> ROX-14398: Group Role resource with Access - UI part

- qa-tests-backend/codenarc-rules.groovy
- qa-tests-backend/src/main/groovy/objects/Notifiers.groovy
- qa-tests-backend/src/main/groovy/services/PolicyService.groovy
- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
- qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
- qa-tests-backend/src/test/groovy/ImageSignatureVerificationTest.groovy
- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
- qa-tests-backend/src/test/groovy/ProcessesListeningOnPortsTest.groovy
Enable codenarc rule that was disabled during bump of gradle:
- https://github.com/stackrox/stackrox/pull/4924
CI style
`make -c qa-tests style`
> ROX-7771: Re-enable Indentation codenarc rule

- ui/apps/platform/package.json
- ui/yarn.lock
Upgrading to the latest prerelease to make sure it didn’t break. This will be the last upgrade we will do before the ACS 4.1.0 release is cut
Upgrade seems to have worked. 
Besides the change to package.json, it looks like the only line in yarn.lock that changed is the entry for the extension package itself. (No dependency bumps)
I submitted a form, and it went through, So, I think it is successfully smoke-tested.
https://issues.redhat.com/projects/RHPF/issues/RHPF-15?filter=allissues#:~:text=Hat%20Product%20Feedback-,RHPF%2D15,-RH%20Product%20Feedback
> Bump react-user-feedback to latest verions, 1.1.2

- .openshift-ci/pre_tests.py
- scripts/ci/gke.sh
- scripts/ci/lib.sh
- scripts/ci/store-artifacts.sh
The release-3.74 branch is missing some useful info e.g. what OCP version is it running. This PR backports the changes for that.
CI is sufficient. The failures are OK IMO. There was an imaging glitch. I'm running one full gke-qa for sanity.
> release-3.74 : CI: Backport cluster logging

- .github/CODEOWNERS
This PR sets @stackrox/merlin as an owner of `[central|pkg|rox]/declarativeconfig/`
N/A
> Set merlin team ownership on declarative config

- ui/apps/platform/src/Components/RelatedEntityListCount.js
- ui/apps/platform/src/Components/visuals/SunburstDetailSection.js
- ui/apps/platform/src/Containers/BreadCrumbs/EntityBreadCrumb.js
- ui/apps/platform/src/Containers/BreadCrumbs/EntityBreadCrumbs.js
- ui/apps/platform/src/Containers/Compliance/widgets/ComplianceByStandard.js
- ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/ComplianceByControls.js
- ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/PolicyViolationsBySeverity.js
- ui/apps/platform/src/Containers/ConfigManagement/SidePanel/BreadCrumbs.js
- ui/apps/platform/src/Containers/ConfigManagement/SidePanel/SidePanel.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Policy/VulnMgmtPolicyOverview.js
- ui/apps/platform/src/app.tw.css
Remove inconsistencies that I have noticed during manual testing for integration test failures. In some cases search for source of one problem lead to related problems.
* Classic contrast between bold font-700 and normal font-600 was sometimes too subtle to see.
* PatternFly contrast between bold font-700 and normal font-400 makes obvious some inconsistent unneeded bold formatting. Especially combination of light color with bold weight.
1. Delete rare `font-400` normal font weight that is redundant now.
* RelatedEntityListCount
2. Delete `font-600` almost-bold font weight and `text-base-500` light color for supporting text like count of policies violated.
* SunburstDetailSection also prevent `undefined` in `class` attribute
3. Move `font-700` bold font weight from Vulnerability Management …
> Delete unneeded Tailwind font weight (part 2)

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/TooltipTh.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/sortUtils.tsx
- ui/apps/platform/src/hooks/useURLSort.ts
- ui/apps/platform/src/types/search.ts
- ui/apps/platform/src/types/table.ts
As it states, fixes a variety of sort issues in the feature. Unfortunately, it does not look like the PF table supports multisort yet (I was mistaken, must've been thinking of react-table) :(
This PR fixes:
* Overview -> Images: `The 'Age' column does not sort`
* Overview -> Images:  `The `Scan time` column does not sort`
* Overview -> Images:  `Trying to sort by `Operating system`, `Deployments`, or `Scan time` highlights all three columns`
* Overview -> Images: `Top CVSS, Affected images, and First discovered does not sort`
* `When you clear filters then sort the scan time column, this error appears:` cannot reproduce
* Overview -> Images: `Sorting by deployments columns excludes watched images. I believe we had decided to not sort on the deployments column. The API contract document …
> Workflow CVEs: Sort fixes

- ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx
- ui/apps/platform/src/Containers/Compliance/Dashboard/ManageStandardsError.tsx
- ui/apps/platform/src/Containers/Compliance/Dashboard/ManageStandardsModal.tsx
Handle potential failure of some or all PATCH requests.
1. `Promise.all` rejects as soon as the first promise rejects, but `catch` block does not know when all promises have settled.
2. Even knowing when all promises have settled, how to describe rare edge case that some resolved and others rejected?
3. Even knowing when all promises have settled, how to describe rare edge case that GET /v1/compliance/standards request fails?
Because backend filters the standards in GraphQL requests according to `hideScanResults` property:
1. ComplianceDashboardPage calls `client.resetStore()` to re-request.
2. ManageStandardsModal can encapsulate GET /v1/compliance/standards request each time it opens.
* It makes the request only when needed.
* Users get immediate feedback if prerequisite GET request …
> ROX-17377: Replace Promise.all with Promise.allSettled for PATCH compliance standards

- CHANGELOG.md
- pkg/env/signature.go
- pkg/signatures/factory.go
We've recently had a customer case where the registry of the customer was under a lot of load due to signature fetching. While [this PR](https://github.com/stackrox/stackrox/pull/6158) reduces the amount of calls made to the registry, in case customers are not using the signature verification feature at all, 
we also shouldn't eagerly fetch image signatures.
For that, the PR introduces the environment variable `ROX_DISABLE_SIGNATURE_FETCHING`, which can be set by customers to a) stop fetching image signatures and verification and b) remove all signatures from existing images.
Note that the scope currently is only to have this environment variable on Central, but it may be extended to Sensor as well (within the local scanning cases, as well as the delegated scanning feature that will be …
> Introduce environment variable to skip fetching image signatures

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageHeader.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePageHeader.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/AffectedImages.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/BySeveritySummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/CvesByStatusSummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DockerfileLayerTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DynamicIcon.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageDetailBadges.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameTd.tsx
Lots of Major and Minor fixes for the Workload CVE pages. Each fix is one commit and may be easier to review via the commit tab instead of looking at all of the changed files in aggregate.
Changes:
1. Remove the duplicate command text when showing Dockerfile layers.
2. Update table headers to read "CVE severity" and "CVE status" instead of just "Severity", "Status", or "Fix status"
3. Remove links to the Resource tabs from the main table. These are now plain text.
4. Fix the SHA at the top of the image page to be the image's ID, not the metadata digest.
5. Ensure duplicate distro feed links are not shown on the CVE page by deduping based on operating system.
6. Switch summary cards to "flat" style to get consistent border width.
7. Remove `isCompact` from single page header labels to …
> Adds a handful of smaller fixes for Workload CVE

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/FilterAutocomplete.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx
When sending requests to the autocomplete API for the Workload CVE entity search box, we now pass
1. All currently applied search filters
2. The current value of the user's entered text
3. The ID and resource type of the current page context
This makes the autocomplete dropdown only display entries that are valid according to data that will exist in the table below it.
ImageCVE page:
Suggested images only match items in the table:
Suggested deployments only match items in the table:
Suggested namespaces:
Suggested clusters:
**This does not work, passing any other filter results in an empty array response. The alternative is to not pass filters specifically for "cluster", which will always return all results.**
Suggested data when filtered …
> Pass current filters and current search context to workload cve autocomplete

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageHeader.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePageHeader.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/AffectedImages.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/BySeveritySummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/CvesByStatusSummaryCard.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DockerfileLayerTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DynamicIcon.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/FilterAutocomplete.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/FilterChips.css
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageDetailBadges.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/SeverityCountLabels.tsx
One of the last (??? 🙏 ) rounds of minor fixes for Workload CVEs based on the bug bash.
1. Do not show previous data results in tables if the current request results in an error.
2. Update tooltips for severity icons according to new wording
3. Fix the display of filter toolbar text input placeholders
4. Fix odd wrapping of Select elements in toolbar
5. Update tooltip for the affected images column
1. For the overview page tables, as well as summary cards on the image and cve pages, force a simulated error and ensure data does not show below the error message:
2. View severity icon tooltip wording on the main table
3. Filter toolbar should show context sensitive placeholder message:
4. With no other filters applied, select a CVE status of …
> More minor fixes and tweaks for Workload CVEs

- central/role/validate_test.go
- pkg/accessscope/validate.go
- pkg/accessscope/validate_test.go
POST/PUT of access scope without rules results in a corrupt entry in the database and broken UI(see ticket).
Note: POST/PUT of
```
{
"name": "habibi",
"rules": {}
}
```
will still work as it results in next access scope being added to the database:
```
{
"id": "eb2076f3-d4a8-40d2-91fb-67ba32f0bd7e",
"name": "habibi",
"description": "",
"rules": {
"includedClusters": [],
"includedNamespaces": [],
"clusterLabelSelectors": [],
"namespaceLabelSelectors": []
},
"traits": null
}
```
1. Unit test is added
2. Manual test POST/PUT requests
> ROX-15140: Forbid access scope without rules

- central/declarativeconfig/manager_impl_test.go
- pkg/declarativeconfig/configuration.go
- roxctl/declarativeconfig/create/create.go
- roxctl/declarativeconfig/create/notifier.go
- roxctl/declarativeconfig/create/notifier_test.go
`generic` and `splunk` subcommands to the `declarative-config create notifier` command.
Unit tests, manual CLI tests.
> ROX-16876: `roxctl declarative-config create notifier *` commands

- central/role/datastore/datastore_impl_test.go
Was broken due to  https://github.com/stackrox/stackrox/pull/6226. The reason it was not caught on is that apparently, this test is not on the list of Postgres tests to execute. This PR should address it: https://github.com/stackrox/stackrox/pull/6245
1. Run test manually
> Fix role datastore_impl_test.go

- .github/dependabot.yaml
Configure dependabot to prefix the commits and PRs with, e.g. `chore(ui-npm):`.
> chore: configure dependabot conventional commit-message

- pkg/declarativeconfig/configuration.go
- pkg/declarativeconfig/configuration_test.go
Given a YAML such as:
```yaml
name: hello-world
description: first declaratively created permission set
resources:
- resource: Integration
access: READ_ACCESS
- resource: Administration
access: READ_ACCESS
- resource: Access
access: READ_ACCESS
---
name: hello-world
description: first declaratively created role
permissionSet: hello-world # Referencing the previously created permission set.
accessScope: Unrestricted # Referencing a system resource, the "Unrestricted" access scope.
---
```
`roxctl declarative-config lint` will fail.
The reason is the trailing delimiter within the YAML multiline object. The `decoder.Decode` will actually not return an error, but instead decode a nil object. In that case, we shouldn't add the nil object to our list of unstructured objects, as these will later …
> Fix trailing multiline YAML delimiter for declarative configurations.

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
Adds a banner to the top of all Workload CVE pages.
_This PR is easier to review with "hide whitespace" on_
Visit any and all Workload CVE pages and view the banner at the top of the page. Ensure the banner does not cause content on the bottom of the pages to be cut off.
Click on the link inside the banner and ensure you are taken to the VM 1.0 dashboard:
> Add banner to top of Workload CVE pages

- ui/apps/platform/cypress/helpers/networkGraph.js
- ui/apps/platform/cypress/helpers/vulnmanagement/entities.js
- ui/apps/platform/cypress/integration/vulnmanagement/reporting/reporting.helpers.js
- ui/apps/platform/src/Containers/MainPage/Sidebar/BadgedNavItem.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.css
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NetworkGraphNavItems.tsx
Updates the sidebar navigation to communicate the status of new features in a standard way according to UX mocks from @zhenpesky . This currently only impacts the Workload CVE and Network Graph features.
_Easier to review with "Hide whitespace" turned on_
Load the app and view the left hand navigation, with ROX_VULN_MGMT_WORKLOAD_CVES and ROX_POSTGRES_DATASTORE and ROX_NETWORK_GRAPH_PATTERNFLY enabled. Note that we are not officially deprecating any of the navigation items for VM 1.0 at this point, even if Workload CVEs are beginning their deprecation.
Load the app with ROX_NETWORK_GRAPH_PATTERNFLY disabled. (This is marked deprecated in the nav still, even with the FF off since we have previously released it as a deprecated version. I'm …
> Update navigation to use UX standardized badges

- central/declarativeconfig/manager_impl.go
- central/declarativeconfig/manager_impl_test.go
- central/declarativeconfig/types/accepted_types.go
- central/declarativeconfig/updater/notifier_updater.go
- central/declarativeconfig/updater/updater.go
- central/notifier/datastore/datastore.go
- central/notifier/datastore/datastore_impl.go
- central/notifier/datastore/mocks/datastore.go
- central/notifier/policycleaner/clean_policy.go
- central/notifier/policycleaner/singleton.go
- central/notifier/service/service.go
- central/notifier/service/service_impl.go
- central/notifier/service/singleton.go
- pkg/declarativeconfig/configuration.go
- pkg/declarativeconfig/transform/notifier_test.go
Reconcile declarative notifiers(create/update/delete).
Policies are cleaned from deleted notifiers same as in API to be consistent.
TBD
> ROX-16869: reconcile declarative notifiers

- ui/apps/platform/src/services/MetadataService.ts
Prerequisite for conditional rendering with same source of truth as for conditional behavior on backend.
Follow up #6253
One step forward, although request has status code 501 Not Implemented
* https://github.com/stackrox/stackrox/blob/master/proto/api/v1/metadata_service.proto#L70-L93
* https://github.com/stackrox/stackrox/blob/master/proto/api/v1/metadata_service.proto#L121-L125
API Reference is a hint from Misha to verify frontend camelCase for backend underscore case:
> Add CentralServicesCapabilities to MetadataService

- ui/apps/platform/src/Containers/Compliance/widgets/StandardsAcrossEntity.js
After change to `hideScanResults` properties of standards, Compliance dashboard:
* does filter **Passing standards by cluster** vertical bar chart
* does **not** filter **Passing standards across whatever** horizontal bar charts
Responses of getAggregatedResultsAcrossEntity_ENTITY and getAggregatedResultsByEntity_ENTITY are similar:
* `complianceStandards` array is filtered according to `hideScanResults` property.
* `controls.results` array is not filtered
* `results.results` array is not filtered
Comparison of helper functions in components:
* StandardsByEntity filters with `!standard` here: https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Compliance/widgets/StandardsByEntity.js#L36-L38
* StandardsAcrossEntity without condition here: …
> ROX-17503: Filter according to hideScanResults in StandardsAcrossEntity horizontal bar graphs

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/FilterChips.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
Removes the default filters and local fixability filters until rework can be done on how "fixable" is calculated via the API.
Additionally, CVEs on the ImageCVE page will calculate the value of the "CVE status" column based on whether or not each imageComponent has a non-empty `fixedByVersion` field, instead of by using the top level `isFixable` field returned from the GraphQL query.
Default filters are not accessible from the main page (note that default filters in local storage will be ignored as well):
Local fixability filters are not available in any page:
Check that "Fixable" in the URL is ignored:
Viewing a CVE where all components are "Not fixable" before:
and after:
> Remove default filters and local fixability filters

- ui/apps/platform/src/Containers/MainPage/AcsFeedbackModal.tsx
- ui/apps/platform/src/Containers/MainPage/MainPage.tsx
Text changes:
1. At the top refer to the official name “Help us improve Red Hat Advanced Cluster Security for Kubernetes”. 
-- Can we make the above  “Help us improve StackRox” instead for StackRox ? (but still Red Hat for Cloud ?)
change text for Share Feedback:
2. change text for Share Feedback: "What has your RHACS experience been like so far?"
-- for upstream (opensource), instead use "What has your StackRox experience been like so far?"
Functional change:
* Only show the link to open a support case if running downstream, RHACS branded version
UX change:
* Rotate floating button from bottom edge to right edge (still red, no purple here)
Manual testing
Stackrox version (no REACT_APP_ROX_PRODUCT_BRANDING flag set):
RHACS version (`export REACT_APP_ROX_PRODUCT_BRANDING='RHACS_BRANDING'; …
> ROX-16786: Enhancements to feedback system

- central/authprovider/telemetry/telemetry.go
- central/declarativeconfig/manager.go
- central/declarativeconfig/manager_impl.go
- central/main.go
- central/role/datastore/telemetry.go
- go.mod
Based on [the list of analytic ideas for declarative config](https://docs.google.com/document/d/1L4B-xlyYp9eeHOAJbZVon51wLIjzQf9iCvY95EbftBM/edit?usp=sharing), this PR implements the first set of those, namely:
- providing an overview of all created declarative resources per resource type via their origin.
- providing an overview of the number of mount points (this correlates to secrets / config maps).
This way, we can now see which resources are defined declaratively the most, as well as differentiate properly between user created, system defaults, declaratively created resources in the future.
Manual tests:
1. Setup central instance with telemetry configured.
2. View in Amplitude the central identity data:
4. Create a declarative …
> ROX-16888: Analytics for declarative config feature

- ui/apps/platform/cypress/integration/systemHealth/clusters.test.js
- ui/apps/platform/src/Containers/SystemHealth/CardHeaderIcons.tsx
- ui/apps/platform/src/Containers/SystemHealth/CertificateHealth/CertificateCard.tsx
- ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/ClusterStatusCard.tsx
- ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/ClustersHealth.utils.ts
- ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/ClustersHealthCardHeader.tsx
- ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/ClustersHealthCards.tsx
- ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/CredentialExpirationCard.tsx
- ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/SensorUpgradeCard.tsx
- ui/apps/platform/src/Containers/SystemHealth/DeclarativeConfigurationHealth/DeclarativeConfigurationHealthCard.tsx
- ui/apps/platform/src/Containers/SystemHealth/VulnerabilityDefinitionsHealth/VulnerabilityDefinitionsHealthCard.tsx
- ui/apps/platform/src/types/integrationHealth.proto.ts
Provide consistent pattern, especially so Ivan can adapt DeclarativeConfigurationHealthCard to 3 integration health cards.
1. Align icons at the left of card title
* Spinner while waiting for initial fetch
* MinusIcon if request error
* ExclamationCircleIcon if any unhealthy
* ExclamationTriangleIcon if any degraded
* CheckCircleIcon if none of the above
2. Clusters health phrase at the right of card title
* N unhealthy
* N degraded
* N healthy
* empty string if none of the above (that is, edges cases of no clusters or only Unavailable or Uninitialized clusters)
1. Visit /main/system-health: see that cards fit when all healthy, even before rewrite of integration health from widgets to cards.
* 1920px panel width and height
* …
> Move icons to left of card title in System Health

- ui/apps/platform/src/Containers/Compliance/List/Table.js
Fix incorrect specific fallback in #6053
https://github.com/stackrox/stackrox/blame/master/ui/apps/platform/src/Containers/Compliance/List/Table.js#L298
1. Visit /main/compliance
2. Click **View standard** on a sunburst widget.
> Generalize fallback for any groupBy category that is not a resourceLabel

- deploy/common/k8sbased.sh
- pkg/env/declarative_config.go
- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
- tests/e2e/lib.sh
- tests/roxctl/bats-tests/local/expect/flavor-interactive.expect.tcl
With the release of 4.1, the declarative config feature will be released.
We previously introduced this as environment variable to have the developer preview in 4.0, so now the environment variable will be marked as `true` by default.
Adjusted most of the code to respect this.
Once the feature is stable, we shall remove the environment variable completely.
> ROX-16008: Enable declarative config feature by default

- scripts/ci/logcheck/check-restart-logs.sh
- scripts/ci/logcheck/check-restart-logs_test.bats
- tests/e2e/lib.sh
Per title. By wrapping these failures with a junit report we get jira tracking via junit2jira. The offending log is also copied to the top level of openshift/release Artifacts to make it easier to examine.
- with pod restart due to error during test (e.g. `kubectl -n stackrox exec sensor-69d57d6467-vj9ks -- kill -ABRT 1`)
- without
> ROX-16321: Junitify the check for pod restarts

- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
There currently exist two CI flakes within the declarative config tests.
They both are related with deletion of resources. Hence, we increase the timeout only for waiting for the deletions.
Additionally, lowered the pause seconds from 60 to 10, this should also speed up things when we receive an update earlier (previously, the interval was 60 seconds, hence the value. Since we decreased the interval and logic, we may also decrease the pause seconds now to hopefully speed things up in some 
cases).
While it's unfortunate to increase the timeout yet again for an expensive, long-running test like the declarative config one, there's no real way to speed things up on the backend:
- the interval already has lowered from 60 to 20 seconds. Decreasing the interval further would have performance …
> ROX-16816,ROX-16841: Increase timeouts in declarative config tests for deletion

- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
This PR intends to add multi-arch support for the `IntegrationsTest` QA test.
Changes are verified manually using `./gradlew test --tests=IntegrationsTest`
Part of this PR intends to fix [ROX-17420](https://issues.redhat.com/browse/ROX-17420)
> Make IntegrationsTest multi-arch compliant

- ui/apps/platform/src/Containers/Policies/Wizard/Step2/PolicyBehaviorForm.tsx
Adding descriptions as helper text below the radio buttons for the two types of event source for RUNTIME lifecycle in the Policy behavior form step.
RUNTIME not selected, then no helper text (existing behavior)
RUNTIME selected, and Deployment Event Source selected
RUNTIME selected, and Audit Logs Event Source selected
> ROX-17020: Add descriptions below policy event source options in form

- sensor/common/detector/detector.go
- sensor/common/registry/registry_store.go
To address CI failures, stacktrace from CI failures below, stacktrace does not appear to be accurate to the line that is panic'ing
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x28ee32d]
goroutine 26011 [running]:
github.com/stackrox/rox/sensor/common/registry.(*Store).hasClusterLocalRegistryHost(0x0, {0xc0128d74f0?, 0x30?})
github.com/stackrox/rox/sensor/common/registry/registry_store.go:260 +0xed
github.com/stackrox/rox/sensor/common/registry.(*Store).IsLocal(0x0, 0xc009c64b40)
github.com/stackrox/rox/sensor/common/registry/registry_store.go:213 +0x68
github.com/stackrox/rox/sensor/common/detector.(*cacheValue).scanAndSet(0xc008f30080, {0x401cc98, 0xc00b877158}, {0x4031a78, 0xc000624100}, 0xc00897cc80)
github.com/stackrox/rox/sensor/common/detector/enricher.go:148 …
```
> Fix on-prem reg panic

- ui/apps/platform/src/Containers/MainPage/MainPage.tsx
- ui/apps/platform/src/hooks/useCentralCapabilities.ts
- ui/apps/platform/src/index.tsx
- ui/apps/platform/src/reducers/centralCapabilities.ts
- ui/apps/platform/src/reducers/index.js
- ui/apps/platform/src/services/MetadataService.ts
Central capabilities data will be used to distinguish between managed services and self-managed solutions. Add central capabilities response data to redux and provide a react hook for easy access of data. 
Redux store:
Hook use case:
```typescript
const { isCentralCapabilityAvailable } = useCentralCapabilities();
const isDeclarativeConfigHealthAvailable = isCentralCapabilityAvailable(
'centralCanDisplayDeclarativeConfigHealth'
);
```
> ROX-17539: Add central capabilities to redux

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DefaultFilterModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/sortUtils.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
Fixes mostly related to default filters -- it shouldn't make a difference right now since they have been removed for the release, but the fixes that are in the DefaultFilterModal will persist within the component.
Also fixes table empty state of the CVEs overview page and default sort to be CVSS
> Workload CVEs: Default filter and other fixes

- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
This PR adds notifiers to the E2E tests of declarative configuration.
> ROX-16874: Add notifiers to declarative config E2E tests

- qa-tests-backend/src/main/groovy/util/Env.groovy
- qa-tests-backend/src/test/groovy/CertExpiryTest.groovy
- qa-tests-backend/src/test/groovy/CertRotationTest.groovy
This PR intends to make changes in `CertExpiryTest` and `CertRotationTest` so that the tests are only executed only if both central & secures-cluster are deployed on same cluster. 
These tests executes only when `ONLY_SECURED_CLUSTER` is set to `true`.
To skip the test set `ONLY_SECURED_CLUSTER` to `false`, which is also the default value. 
Part of this PR intends to revert few changes added as part of #4357
> Execute CertExpiryTest & CertRotationTest only if central is deployed

- .github/workflows/scripts/prepare-upgrade-test.sh
We do not need to set the images explicitly during roxctl generate for the upgrade tests.
This will future proof the upgrade tests, because new or removed images won't break stuff.
Tested and reviewed in https://github.com/stackrox/test-gh-actions/pull/96.
> ROX-16502: future-proof upgrade tests with roxctl generate

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageResources.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageResources.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/TableEntityToolbar.tsx
One small change that slipped through - this removes the `isCompact` form of the Pagination component to allow users to directly enter the page number.
All pages use the expanded pagination component:
> Use expanded form of pagination component for workload cve tables

- central/deployment/datastore/datastore_impl_test.go
- central/pod/datastore/datastore_bench_test.go
- central/pod/datastore/datastore_impl_test.go
- central/processindicator/filter/singleton.go
- central/reprocessor/reprocessor_test.go
- pkg/env/integersetting.go
- pkg/env/process_filter_max_paths.go
- pkg/process/filter/filter.go
- pkg/process/filter/filter_test.go
- sensor/common/processfilter/filter.go
- sensor/common/processsignal/pipeline_test.go
For environments that are running random / consistently unique processes, cap the process filter in Central to 5k, but leave Sensor's uncapped to avoid missing process alerts due to caps
Unit tests
> ROX-17547: Set max fan out for unique processes to 5k in Central and max in Sensor

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePageHeader.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
A few more minor fixes I found when testing against stagingdb:
- Re-adds the `vulnerabilityId` field to vulns on the deployment page. Previously this used `cve` as the React key, which isn't unique in a deployment context. We need the `id`, which is cve + operating system.
- Fixes another error with duplicate CVE links on the ImageCVE page. This was de-duping links by OS, but since `rhel` and `centos` use the same link and text it was causing doubles on pages with cves using both images. Now it de-dups on the link text, ensuring that we only get a single instance of each type of link
Manual
> Additional minor fixes for Workload CVEs

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx
This effect was causing the search filter to be cleared when navigating tabs on the workload CVE overview page. Since a new version of this component is rendered each time the tab changes, the effect will always fire once. Previously it merged the default filter state with the URL state, but since we aren't using default filters it seems safe to remove entirely.
Go to a tab on the workload cve overview page and apply a filter.
Change tabs and ensure the filter persists.
> fix(ui): Remove default filter useEffect from workload cve toolbar

- ui/apps/platform/cypress/integration/systemHealth/integrations.test.js
As @pedrottimark said:
```
OCP has an image integration error for Quay.io but GKE has no errors, so that is why CI passed
```
1. Extended CI run TBD
> fix: system health ui tests: backup integrations test

- ui/apps/platform/src/Containers/SystemHealth/DashboardPage.js
ACS CS does not provide customers with the ability to use declarative configurations. Therefore, the system health page should not show the declarative config health status when running in "managed service" mode, i.e. for ACS CS instances.
`CapabilityAvailable`
`CapabilityDisabled`
> ROX-17177: Disable declarative config system health for ACS CS

- qa-tests-backend/src/test/groovy/TLSChallengeTest.groovy
- qa-tests-backend/src/test/groovy/UpgradesTest.groovy
This PR intends to enable executing `TLSChallengeTest` and `UpgradesTest` on P/Z. Also a workaround has been added in UpgradesTest to make it execute on P/Z.
Part of this PR intends to revert few changes added as part of #4357
> fix(qa): Enable executing TLSChallengeTest and UpgradesTest on P/Z

- ui/apps/platform/cypress/integration/accessControl/accessControl.helpers.js
> Access Control Permission sets list link for default Admin goes to form which has label instead of button and disabled input values
> `cy.click()` can only be called on a single element. Your subject contained 2 elements. Pass `{ multiple: true }` if you want to serially click each element.
`:contains` pseudo-selector for **Admin** is ambiguous after **Vulnerability Management Admin** was added in #6140
* Did not fail on branch because no changes in ui folder, therefore ui-e2e-tests did not run.
* Did not fail on merge because of caching?
Replace `:contains` pseudo-selector with `contains` method and RegExp.
* Verify problem and change helper function.
* Run all accessControl tests.
> ROX-17563: Require exact match in Access Control integration tests

- pkg/scanners/clairify/convert.go
This was applied to the normal scan path but not to the grpc scan path
Trivial
> Apply active vuln mgmt env var to grpc call

- ui/apps/platform/cypress/helpers/systemHealth.js
- ui/apps/platform/cypress/helpers/visit.js
- ui/apps/platform/cypress/integration/systemHealth/declarativeConfiguration.test.js
Add a new visit method for mocking central capabilities response data. Demonstrate new method by writing tests for System Health -> Declarative Configuration
> feat(ui): Add central capabilities cypress test helpers

- pkg/logging/logging.go
Within a refactor of the logging interface the `LoggerForModule()` was refactored to use `CurrentModule().Logger()` instead of `currentModule(3).Logger()`.
In itself, `CurrentModule()` will call `currentModule(3)`, however since the caller will now be the logging package itself (specifically `pkg/logging`), `currentModule(3)` will now yield `pkg/logging` instead of the package where `LoggerForModule()` originally was being called from.
Subsequently, if one were to use `currentModule(4)` instead, the package name would be yielded correctly.
Since `CurrentModule()` is already in use in a few places, reverted the refactoring back to use `curerntModule(3).Logger()` instead.
For the location of the log call (i.e. the `logging.go:170` part, the `AddCallerSkip` option of the zap logger was …
> ROX-17480: Use correct module name in logger

- .github/properties
- scripts/ci/lib.sh
- scripts/ci/publish-helm-charts.sh
Splitting notifications and discussions from #forum-acs-eng-release. 
GHA tested in https://github.com/stackrox/test-gh-actions/pull/97. 
- New Slack channel: #acs-release-notifications (ID: C05AZF8T7GW)
Secrets were updated on OSCI Vault + GHA settings by @gavin-stackrox .
> ROX-16356: Release automation: switch slack notification channels

- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
We previously refactored the metadata function and made [the returned error lowercase](https://github.com/stackrox/stackrox/commit/fe9b99ed2dcd9c26e99bc4a089c561be1f70b8fe#diff-fb9aae01acef1decdba85965a284ff9c4388f66ceb350ea68c6e51dfe95a2a2dR210) (which it should have been to begin with), so adjusting the 
test to get rid of the failures.
- see CI passing
> ROX-17622: Fix ImageScanningTest error message

- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentDetails.tsx
UX affordance so user can click on anomalous counts to jump to Flows tab in NG 2.0 sidebar
Manual testing
> ROX-17095: Make anomalous flow counts open Flows tab

- central/main.go
- ui/apps/platform/src/Containers/AccessControl/AccessControl.tsx
Remove the notions of `Administration`, `Compliance`, `DeploymentExtension`, `Integration`, `Image`, and `Cluster` (they were done in 3.73/3.74).
> fix: Remove resource replacement banner text for old previous releases

- operator/pkg/central/common/common.go
- operator/pkg/central/extensions/reconcile_pvc.go
- operator/pkg/central/extensions/reconcile_pvc_test.go
- operator/pkg/central/reconciler/reconciler.go
- operator/pkg/central/values/translation/pvc_checker.go
- operator/pkg/central/values/translation/translation.go
- operator/pkg/central/values/translation/translation_test.go
- operator/tests/central/basic-central/10-assert.yaml
- operator/tests/central/basic-central/10-errors.yaml
- operator/tests/central/basic-central/100-assert.yaml
- operator/tests/central/basic-central/90-assert.yaml
- operator/tests/central/basic-central/90-errors.yaml
- operator/tests/central/basic-central/91-assert.yaml
- operator/tests/upgrade/upgrade/25-errors.yaml
- operator/tests/upgrade/upgrade/25-obsolete-pvc.yaml
This PR is part of Central PVC retirement. The stackrox-db is attached to Central and holding the RocksDB and some persistent data in Central. After we migrate all data from RocksDB to Postgres, we are ready to retire PVC. This is helpful to make ACSCS stateless to be deployed cross-zone. 
Prior to 4.1, we still have some persistent data on RockDB and those files are move to Postgres in 4.1 or beyond through migration. That requires us to still use the PVC in 4.1 during the migration. In addition to that, keeping the pvc will help rollback and restoration process.
For newly installed Central, we do not need to create and mount stackrox PVC.  After migration and after the customer has confirmed that the Central is running in a good shape, they may start to retire PVC. The process requires …
> ROX-16557: Stop creating stackrox-db on installation - operator

- image/templates/helm/stackrox-central/templates/01-central-03-diagnostics-rbac.yaml
- pkg/k8sintrospect/collector.go
* Added error debug message for the case when logs cannot be retrieved;
* Added "get pods/log" permission to the `stackrox-central-diagnostic` role.
Tested with local setup.
Before giving permissions:
```
Error retrieving container logs: unknown (get pods central-756858c7cf-6wgts)
server response object: [{
"metadata": {},
"status": "Failure",
"message": "unknown (get pods central-756858c7cf-6wgts)",
"reason": "Forbidden",
"details": {
"name": "central-756858c7cf-6wgts",
"kind": "pods",
"causes": [
{
"reason": "UnexpectedServerResponse",
"message": "unknown"
}
]
},
"code": 403
}]
```
> ROX-14267: Allow central to `get pods/log`

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/ImageResourceTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/DeploymentResourceTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DatePhraseTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageDetailBadges.tsx
Changes the "Age" badge on the image single page and the "Age" column on the image overview table to read e.g. "3 months" instead of "3 months ago".
Image overview table:
Image single page:
> fix(ui): Correctly handle phrasing for date distance text

- qa-tests-backend/src/test/groovy/GlobalSearch.groovy
This PR intends to add multi-arch support for the `GlobalSearch` QA test.
Changes are verified manually using `./gradlew test --tests=GlobalSearch`
Part of this PR intends to fix [ROX-17644](https://issues.redhat.com/browse/ROX-17644)
> ROX-17644: Make GlobalSearch test multi-arch compliant

- pkg/images/enricher/enricher_impl.go
- pkg/images/utils/utils.go
- pkg/images/utils/utils_test.go
In the past we've added a new field `Names` which contains multiple image names for a single digest. The reasoning behind this was that images may have different fullnames but the same digest (e.g. stored under different repositories, stored in different registries but the same digest).
When either scanning images from sensor or when scanning images from central the image names field will be populated. However, when using scanning workflows like the detection service, it currently will always override the image names to the given image name of the image.
This is not excatly what was intended, hence we will now always ensure we add the unique image names from both the cached image as well as the image to-be-scanned, ensuring no overwrite happens when using a detection service scanning …
> fix(enricher): Ensure image names are used in image enricher

- central/compliance/service/service_impl.go
Changes to get aggregated results and run results API to filter results based on standards
Manually tested APIs
Set hideScanResults for IST_SP_800_53_Rev_4 to true
API response
1. GET v1/compliance/runresults?standardId=NIST_SP_800_53_Rev_4&clusterId=506f3088-28ab-4b8f-a8e9-9bde9ccbbefc
{
"error": "Results are hidden for this stadard",
"code": 13,
"message": "Results are hidden for this stadard",
"details": []
}
2. GET v1/compliance/aggregatedresults
{
"results": [
{
"aggregationKeys": [],
"unit": "CHECK",
"numPassing": 771,
"numFailing": 241,
"numSkipped": 857
}
],
"sources": [
{
"clusterId": "506f3088-28ab-4b8f-a8e9-9bde9ccbbefc",
"standardId": "PCI_DSS_3_2",
"successfulRun": {
"runId": "0b3d25d6-63ee-4c84-bce6-bbbb0fda9092",
"standardId": "PCI_DSS_3_2",
"clusterId": …
> ROX-16980: Added API changes for aggregatedresults

- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkPolicies.tsx
- ui/apps/platform/src/hooks/useFetchNetworkPolicies.ts
Minimum viable fix, based on Saif's groundwork in draft PR #6170 
Name of "All network policies is now there, and policies YAML doesn't re-render and go back to all, if policy IDs in prop object haven't changed.
> ROX-17028: Network policies list inconsistencies

- ui/apps/platform/cypress/integration/compliance/hideScanResults.test.js
> Compliance hideScanResults should hide HIPAA standard: should hide HIPAA standard
Message
> Timed out retrying after 4000ms: Expected to find element: `.widget:has('[data-testid="widget-header"]:contains("Passing standards across clusters")') a:contains("HIPAA")`, but never found it.
> fix(ui): Skip hideScanResults integration tests for openshift

- central/blob/datastore/store/store.go
- central/blob/datastore/store/store_test.go
Add sac check to upsert and delete.
These two operations require both read/write permissions. If a caller holds only one permission, it will lead to inconsistency.
1. If a caller has write permission but no read permission, upsert will lead to leaking large object.
2. If a caller has read permission but no write permission, delete will lead to a blob without large object.
This PR fixes that by augment ctx with extra read permission.
If any of these don't apply, please …
> Add sac check to blob upsert

- qa-tests-backend/src/test/groovy/ComplianceTest.groovy
This PR fixes the ComplianceRuns tests after the `Policy` resource was removed. It now uses the replaced resource `WorkflowAdministration`.
> ROX-17413: Fix ComplianceTest

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#12-14-0
* Upgraded `find-process` from 1.4.1 to 1.4.7 to address Synk security vulnerability.
* Upgraded `firefox-profile` from 4.0.0 to 4.3.2 to address security vulnerabilities within sub-dependencies.
1. `yarn start` in ui
2. `yarn cypress-open` in ui/apps/platform
* compliance/complianceDashboard.test.js
* compliance/hideScanResults.test.js (failed when run before the preceding)
Aha, now I better understand ocp-4-12-ui-e2e-tests failures for #6362
* hideScanResults.test.js **assumes** that environment has already been scanned, but complianceDashboard.test.js is skipped on openshift.
* Therefore, the first test in hideScanResults needs to scan, so that it does not depend on side-effects from another test file.
* In contrast to the …
> chore(e2e): Update cypress 12.14.0 devDependencies in ui

- ui/apps/platform/src/Containers/SystemHealth/CertificateHealth/CertificateCard.tsx
Correct copy paste mistake in #6258
1. Visit /main/system-health and click link to verify that `href` attribute was correct although text was incorrect
> fix(ui): Fix incorrect link text in System Health Certificate cards

- .openshift-ci/ci_tests.py
- scripts/ci/jobs/ocp_sensor_integration.py
- tests/e2e/run.sh
- tests/e2e/sensor.sh
This PR adds dummy test run (one that always passes) required by https://github.com/openshift/release/pull/40182
The proper moving of the tests will happen in the follow-up 👉 The goal of https://issues.redhat.com/browse/ROX-17674 is to move the sensor integration tests away from the nongroovy step as the integration tests are now larger and keep growing. This would allow us (who work on Sensor) to iterate quicker when adding new features and tests in the upcoming epic.
- Running it locally the way the CI will run this, i.e.:
```
QUAY_RHACS_ENG_RO_USERNAME="xxx" \
QUAY_RHACS_ENG_RO_PASSWORD="yyy" \
ORCHESTRATOR_FLAVOR="openshift" \
MAIN_IMAGE_TAG="4.0.x-619-g2c7a6f32b8" \
KUBECONFIG="~/.cluster/kubeconfig" \
./tests/e2e/sensor.sh
```
> ROX-17673: Prepare dummy test target for sensor-integration tests

- ui/apps/platform/src/Containers/MainPage/Header/MastheadToolbar.tsx
- ui/apps/platform/src/Containers/ThemeProvider.js
Request from our UX team. (see Jira)
Until we can fully implement PatternFly themes for dark mode.
Tested by switching to Dark Mode, then unstashing code changes. Setting for Dark Mode remained in local storage, but is now ignored.
With luck, when we re-introduce Dark Mode, and if we use the same local storage flag, users who had saved that preference will get Dark Mode back automatically.
> ROX-16515: Temporarily hide dark mode

- ui/apps/platform/src/Components/InfoList/InfoList.js
- ui/apps/platform/src/Components/LinkListWidget.js
- ui/apps/platform/src/Components/NumberedGrid/NumberedGrid.js
- ui/apps/platform/src/Components/NumberedList/NumberedList.js
- ui/apps/platform/src/Components/TableGroup.js
- ui/apps/platform/src/Containers/Clusters/Components/FormFieldRequired.js
- ui/apps/platform/src/Containers/ConfigManagement/Entity/widgets/Rules.js
- ui/apps/platform/src/Containers/Images/CVETable.js
- ui/apps/platform/src/Containers/Images/VulnsTable.js
- ui/apps/platform/src/Containers/MainPage/Header/OrchestratorComponentsToggle.tsx
- ui/apps/platform/src/Containers/Risk/Process/BinaryCollapsible.js
- ui/apps/platform/src/Containers/Risk/Process/DiscoveryCardHeader.js
- ui/apps/platform/src/Containers/Risk/SecurityContext.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Cve/VulnMgmtCveOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/List/Cves/CveBulkActionDialogue.js
- ui/apps/platform/src/Containers/VulnMgmt/VulnMgmtComponents/FixableCveExportButton.js
As part of ongoing accessibilty effort, delete leftover styles that detract from legibility of Red Hat font with PatternFly colors.
* Classic contrast between bold font-700 and normal font-600 was sometimes too subtle to see.
* PatternFly contrast between bold font-700 and normal font-400 makes obvious some inconsistent unneeded bold formatting.
Find in Files `font-600` reduced by half from 52 results in 31 files to 25 results in 16 files
1. Verify that SimulationFrame will be deleted with classic Network Graph.
2. Verify whether any Redux form fields are obsolete.
3. Verify whether or not src/Containers/VulnMgmt/Entity/Policy folder is obsolete after #6235
4. Return to presentation components for cluster health in a follow up to reduce risk of merge conflicts with recent changes for 4.1 …
> fix(ui): Delete unneeded Tailwind font weight (part 3)

- ui/apps/platform/cypress/integration/collections/collectionsCrudWorkflow.test.js
- ui/apps/platform/cypress/integration/collections/collectionsTable.test.js
- ui/apps/platform/cypress/integration/collections/deploymentMatching.test.js
- ui/apps/platform/cypress/integration/collections/permissions.test.js
- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/hooks/useFetchReport.ts
> deprecating our Postgres feature flag
Find in files `ROX_POSTGRES_DATASTORE`
* cypress: decrease from 43 results in 25 files to 37 results in 21 files
* src: decrease from 60 results in 49 files to 58 results in 48 files
1. Delete skip from integration tests.
2. Delete conditional rendering from body and left navigation.
3. Delete conditional code for upgrade from 3.73 to 3.74 version in reports.
branch - master: -362 = 11794399 - 11794761
1. Visit /main/collections and then click **Create collection**
2. Click **Cancel** and then go back to main dashboard
3. Expand **Platform Configuration** and then click **Collections**
* …
> ROX-17715: Delete non-postgres code in Collections UI

- qa-tests-backend/src/main/groovy/services/NotifierService.groovy
- qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
Makes it easier running locally tests that use `NotifierService` but are not related to slack webhooks - for example, `DeclarativeConfigTest`
> refactor: Stop requiring slack env variables for NotifierService

- central/postgres/pruning.go
- central/postgres/pruning_test.go
- central/pruning/pruning.go
- central/pruning/pruning_test.go
Update pod pruning to use SQL and not walk.
Added some simple tests.  pruning pods isn't as complicated as others as it is either orphaned or it is not.
> ROX-17668: pod pruning no walk

- qa-tests-backend/src/test/groovy/ProcessesListeningOnPortsTest.groovy
This PR intends to add multi-arch support for the `ProcessesListeningOnPortsTest` QA test.
Changes are verified manually using `./gradlew test --tests=ProcessesListeningOnPortsTest
`
This PR intends to fix [ROX-16969](https://issues.redhat.com/browse/ROX-16969)
> ROX-16969: Make ProcessesListeningOnPortsTest multi-arch compliant

- qa-tests-backend/src/test/groovy/NetworkSimulator.groovy
- qa-tests-backend/src/test/groovy/NodeInventoryTest.groovy
- qa-tests-backend/src/test/groovy/TLSChallengeTest.groovy
This PR intends to add multi-arch support for the QA test.
The `NodeInventoryTest`, `TLSChallengeTest` and few sub-tests in `NetworkSimulator` have dependency on central / scanner deployment.
In a P/Z test environment where only secured-cluster is deployed & central + scanner are deployed on X, these tests need to be skipped.
> fix(qa): Skip QA tests on P/Z when central & scanner is on X

- central/authprovider/registry/singleton.go
- central/debug/service/singleton.go
- central/declarativeconfig/singleton.go
- central/declarativeconfig/updater/updater.go
- central/main.go
- central/trace/singleton.go
- pkg/auth/authproviders/registry_impl.go
* Introduce singleton for authz trace sink
* Introduce singleton for auth providers registry
* Remove dependency of declarative config manager singleton on auth providers registry
* Re-introduce singleton for debug service(originally removed as a side-effect of https://github.com/stackrox/rox/pull/9305)
During the implementation of https://issues.redhat.com/browse/ROX-12125, a lot of debug service code can be reused to the point, where it makes sense to reuse debug service instance.
Additionally, considering we use singleton pattern in almost 100% services in `central`, it makes sense to clean up code further by introducing new singletons. Plus, no need to pass parameters to `servicesToRegister` and `declarativeconfig.ManagerSingleton()`. …
> refactor: Re-Introduce singleton for debug service

- ui/apps/platform/cypress/integration/configmanagement/ConfigurationManagement.helpers.js
- ui/apps/platform/cypress/integration/configmanagement/clusters.test.js
- ui/apps/platform/cypress/integration/configmanagement/roles.test.js
- ui/apps/platform/src/Components/BinderTabs/BinderTabs.tsx
- ui/apps/platform/src/Components/GroupedTabs.js
- ui/apps/platform/src/Components/Tabs.js
1. PatternFly guidelines do not even mention uppercase.
2. Extra width of uppercase is a blocker to increase classic normal font size from 12px to 14px, especially for same size as PatternFly in tables and key-value lists.
Find in File `uppercase` decreased from 29 results in 20 files to 23 results in 17 files
Replace uppercase with mixed case and use `bg-primary-200` for active tab similar to PatternFly for `ToggleGroup` element.
1. src/Components/GroupedTabs.js and simplify comlicated styles
* Vulnerability Management: src/Components/workflow/EntityTabs/EntityTabs.js
* Configuration Management: src/Containers/ConfigManagement/Entity/EntityTabs.js
2. src/Components/Tabs.js
* Network Graph: src/Containers/Network/SidePanel/Simulator/SuccessViewTabs.tsx
* Risk: …
> fix(ui): Delete occurrences of Tailwind uppercase part 4

- ui/apps/platform/cypress/integration/accessControl/accessControlPermissionSets.test.js
- ui/apps/platform/src/Containers/AccessControl/Roles/Roles.tsx
- ui/apps/platform/src/services/AccessScopesService.ts
> deprecating our Postgres feature flag
1. Visit /main/access-control/roles
2. Click **Create role**, type **None Unrestricted**, click **None**, and then click **Save**
3. Click **Create role**, type **None Deny All**, click **None**, click **Deny All**, and then click **Save**
* accessControl/accessControlAccessScopes.test.js
* accessControl/accessControlPermissionSets.test.js
* accessControl/accessControlRoles.test.js
> ROX-13585: Delete non-postgres conditional code in Access Control UI

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePageHeader.tsx
Realized from discussions yesterday during planning that links to vendor CVE databases from the Workload CVE page should have an external link icon to let the user know they are being taken to an external site. Making the PR was faster than making a Jira ticket.
Visit any CVE page in the Workload CVE section. All external links in the header should have the PatternFly external link icon.
> feat(ui): Add external link icon to workload cve distro links

- integration-tests/mock-grpc-server/main.go
Currently the mock grpc server used by collector only reports the latest network connection involving a container. With this change all connections involving a container will be reported by that container. The corresponding PR for collector can be found at https://github.com/stackrox/collector/pull/1194
See above
> ROX-17744: Mock grpc server should report multiple connections

- .openshift-ci/pre_tests.py
- scripts/ci/jobs/gke_sensor_integration_tests.py
- scripts/ci/jobs/ocp_sensor_integration_tests.py
Extracted from https://github.com/stackrox/stackrox/pull/6416/ to make the empty/dummy sensor-integration tests pass.
The pre and post tests assume that Stackrox was deployed to the cluster, but the `sensor-integration` tests do not need ACS installation to run. Thus, the CI was failing as it expected particular namespaces to exist.
Required for the rehearsals in https://github.com/openshift/release/pull/40290 to pass.
- CI
> ROX-17673: Remove pre and post tests from sensor-integration target

- central/declarativeconfig/manager_impl.go
> fix: Remove unused constant from declarativeconfig/manager_impl

- scripts/ci/jobs/ocp_core_bpf_qa_e2e_tests.py
- tests/e2e/lib.sh
The default value for the operator based deployment is specified via SecuredCluster CRD and is ebpf. This prevents using core_bpf in E2E tests.
> ROX-16726: Propagate collection method for operator-based deployment

- tests/yamls/multi-container-pod.yaml
Fixed one thing, but broke the roxctl test
gke nongroovy should pass
> ROX-17785: Fix the e2e test breakage by adding back latest tag

- central/compliance/checks/all_test.go
- central/compliance/manager/test/manager_test.go
- central/compliance/standards/registry.go
- central/compliance/standards/registry_singleton.go
- central/compliance/standards/registry_test.go
- central/complianceoperator/manager/manager_test.go
- pkg/search/predicate/basematchers/base_matchers.go
Use our search predicates instead of bleve. Prefix match in predicates should be capitalization agnostic just like search
CI + small unit test
> refactor: Remove bleve from Compliance by using predicates

- deploy/common/deploy.sh
`$(date '+%s')` and `$deadline` are numbers.
> fix: use number comparison in deploy.sh

- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
Investigation didn't give any results - for some reason, auth provider is not guaranteed to be returned at this point in test.
I added retries, and the test seems to pass(I ran it ±100 times).
1. CI is sufficient + tested before within this PR
> ROX-17655: fix declarative config "orpaned resources" test

- ui/apps/platform/src/Containers/Workflow/WorkflowEntityPage.js
- ui/apps/platform/src/utils/queryService.js
- ui/apps/platform/src/utils/queryService.test.js
chore(ui): this is part of removing all references to the Postgres feature flag
Smoke tested and ran ui-e2e tests locally
> ROX-17770: Delete non-postgres code in getFragmentInfo functions

- scripts/ci/lib.sh
Prior to this PR test results were only saved on merge. ~This change relies on a new [junit2csv](https://github.com/stackrox/junit2csv) tool derived from junit2jira. I wanted to avoid accidental creation of JIRAs in a PR context.~ This change relies on `-dry-run` passed to junit2jira to avoid creating JIRAs and to get the CSV required for test results.
Check DB for results.
> ROX-17781: Get test results in PR context

- central/policy/service/service_impl.go
- central/policy/service/validator.go
- central/policy/service/validator_test.go
- pkg/booleanpolicy/default_policies_test.go
- pkg/booleanpolicy/field_metadata.go
- pkg/defaults/policies/policies.go
- pkg/features/list.go
- sensor/common/detector/detector.go
- sensor/kubernetes/listener/resources/networkpolicy.go
- sensor/kubernetes/listener/resources/networkpolicy_test.go
- tests/networkpolicy_test.go
Removing old feature flag for Network Policy system policies. The feature has been enabled for at least three releases already. 
CI should be sufficient
> ROX-17872: Remove ROX_NETPOL_FIELDS feature flag

- scripts/ci/logcheck/restart-ok-patterns.json
The deployment of testing environment is not specifically orchestrated to ensure that Sensor is available when Collector is started. It is then likely that when Collector is ready, Sensor is not yet.
We propose to add a general exception for all tests which accept when Collector restart with a log entry stating that the reason is Sensor unavailability.
> ROX-17623: Accept Collector restarts on Sensor unavailability

- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
The pattern is similar to the one observed here: https://github.com/stackrox/stackrox/pull/6403
1. Health is created
2. Other declarative resources are created
3. Auth provider is not created
Apparently, there's some delay between health of auth provider created and auth provider being created. 
Solving in the same manner as the referenced CI failure
1. CI is sufficient. Optimistically assuming it will be enough and failures will stop
> ROX-17661: fix declarative config "successful creation" test

- scripts/ci/logcheck/allowlist-patterns
The post-e2e-test check which looks for suspicious entries in pod logs is frequently failing due to deprecation warnings about PodSecurityPolicy objects.
However by design, we keep installing PodSecurityPolicy objects as long as the server supports them.
We detect if they are not supported and in that case do not apply them, so these warnings are not useful at this point.
See also ROX-17796 ROX-17766 ROX-17734 for related work.
The original message is `2595:/tmp/postgres-upgrade-test-logs/04_postgres_postgres_rollback/stackrox/pods/sensor-upgrader-5578dbc74-9wpmk-upgrader.log:W0602 14:41:14.496056       1 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+` but the check script uses `grep -vP` (Perl-compatible REs) so I've used a dot in place of …
> ROX-17517: Tolerate PSP messages in "suspicious entries" check

- central/compliance/standards/registry.go
- central/compliance/standards/registry_test.go
Historically, the control's id was fully qualified. This was due to the proto format from the standard.ToProto(). I had a bug where I used control.ToProto() from the internal standard and not the proto from the resolution of standard.ToProto()
UI e2e
> fix(e2e): Fix compliance predicate search for controls

- Makefile
- scripts/ci/jobs/test-binary-build-commands.sh
- scripts/ci/lib.sh
Per title. The openshift/release `test-bin` image build time can be 18 minutes. Removing it completely is an option (https://github.com/stackrox/stackrox/pull/6525) but we may get a reasonable performance boost just by reducing the build to the only roxctl that is required. 
CI is sufficient. It ran faster (and all green!) for the [one CI run](https://prow.ci.openshift.org/pr-history/?org=stackrox&repo=stackrox&pr=6550) for this test 7m20s.
> ROX-17149: Only build what is required for e2e tests

- ui/apps/platform/cypress/helpers/vulnmanagement/entities.js
Adapt pattern from Configuration Management in #6549
Scope limited to be safe for 4.1 release branch as of 2023-06-07
Prevent merge conflicts with **deletions** preceding current line 19 of the file on 2023-06-12 in #6466
Problem was overlooked on GKE but occurs often on OpenShift.
> Vulnerability Management Clusters should display links for deployments
> Timed out retrying after 4000ms: Expected to find element: `[data-testid="side-panel"] [data-testid="panel-header"]:contains(128 deployments)`, but never found it.
cypress/helpers/vulnmanagement/entities.js
cypress/integration/vulnmanagement/clusters.test.js
Selector has 128 from deployments link in clusters table, but deployments table has 127 deployments.
Thanks to Van for identifying the root of the problem:
Count of deployments …
> ROX-17001: Improve verifyTableLink for Vulnerability Management tests

- qa-tests-backend/src/test/groovy/ExternalNetworkSourcesTest.groovy
Multiple external network sources test are failing due to timeouts: [ROX-16727](https://issues.redhat.com/browse/ROX-16727), [ROX-17159](https://issues.redhat.com/browse/ROX-17159) and [ROX-17395](https://issues.redhat.com/browse/ROX-17395). This has also manifested in other aggregated failures in CI jobs ([ROX-17728](https://issues.redhat.com/browse/ROX-17728)). 
We have identified multiple sources of flakiness in this test suite. Here are the key observations:
1. All tests have the same network entity name, this can cause conflicts if previous tests failed to cleanup properly  
2. The deletion request triggers a deletion job, meaning that the actual cleanup takes longer than the request being replied to  
3. If any assertion fails, the tests will retry on the BaseSpec retry loop, taking …
> ROX-16727: Fix ExternalNetworkSourcesTest

- tests/e2e/lib.sh
There are CI Errors for the auto-sensing logic for PSP introduced in #4488.
The checks where failing for EKS because they put other characters in their version strings returned by kubectl.
There are additional consideration to why the approach with major/minor version check is brittle in #4813 comments.
This PR changes the check so that it uses `kubectl api-resources` command instead. This should be a more reliable solution.
- ~~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-do …
> ROX-14946: change PSP auto-sensing in e2e tests

- central/hash/manager/manager.go
- pkg/env/hash_flush_interval.go
ROX_HASH_FLUSH_INTERVAL controls the frequency of flushing the hashes to the database. Unlikely to be used, but a good thing to tune just in case
Trivial
> chore(config): Add ROX_HASH_FLUSH_INTERVAL to control hash flush rate

- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
Currently the quay.io registry integration is created and deleted on a test spec basis. When tests run in parallel this would be problematic for tests that require its presence. This PR changes it to create and delete the integration on a test run basis.
`all-qa-tests`.
> ROX-17499: Create quay registry once

- ui/apps/platform/src/Containers/Login/LoginPage.js
Currently, when executing `roxctl central login` and the central instance doesn't have any auth provider configured besides the default basic auth provider, the authorize roxctl page will contain an error.
This is due to the current login page code assuming that there will be at least one auth provider within the list of available auth providers. However, since we filter out the basic auth provider in roxctl authorize mode, since its not compatible with the flow, this assumption doesn't hold true anymore.
This PR fixes this by a) ensuring that the current code in `LoadingOrForm` respects potential empty auth provider list within the initial values and b) returning an error in roxctl authorize mode in case of an empty auth provider list after filtering out the basic auth provider.
If any …
> ROX-17956: Fix error in roxctl authorize mode

- ui/apps/platform/cypress/integration/integrations/externalBackups.test.js
- ui/apps/platform/cypress/integration/integrations/imageIntegrations.test.js
- ui/apps/platform/cypress/integration/integrations/integrations.helpers.js
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/EcrIntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/S3IntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationForm/IntegrationForm.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationTilesPage/IntegrationTilesPage.js
- ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsListPage.tsx
Hide the Use IAM role option for the ECR integration
@connorgorman  suggests to entirely remove Cloud Backup integrations, both S3 and GCS. (Not just hiding the IAM option from S3 backup.)
Verified that IAM role is still available in ECR integration when the `centralScanningCanUseContainerIamRoleForEcr` capability is available, and that the IAM role is not visible when `centralScanningCanUseContainerIamRoleForEcr` is NOT available.
Verified that the backup integrations section is still visible and usable on the Integrations dashboard when `canUseCloudBackupIntegrations` capability is available, and that the backup integrations section is not visible when `canUseCloudBackupIntegrations` is NOT available. In addition, I also added redirects if someone tries to visible the table or form …
> ROX-16766: Disable IAM Role when necessary

- qa-tests-backend/src/test/groovy/ExternalNetworkSourcesTest.groovy
This is a follow-up from #6570 where we introduced a failure in the tests if the external entity isn't deleted, but there was one case where the entity was deleted both in the tests and the cleanup. Causing the second deletion to fail.
> ROX-17159: ExternalNetworkSourcesTest fix double deletion

- ui/apps/platform/cypress/helpers/vulnmanagement/entities.js
- ui/apps/platform/cypress/integration/vulnmanagement/clusterCves.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/clusters.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/deployments.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/imageComponents.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/imageCves.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/images.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/namespaces.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/nodeComponents.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/nodeCves.test.js
ocp-4-10-ui-e2e-tests 
1. Vulnerability Management Clusters should display links for namespaces
2. Vulnerability Management Clusters should display links for deployments
3. Vulnerability Management Clusters should display links for nodes
4. Vulnerability Management Deployments should display links for images
5. Vulnerability Management Image Components should display links for images
6. Vulnerability Management Image Components should display links for deployments
7. Vulnerability Management Image CVEs should display links for deployments
8. Vulnerability Management Image CVEs should display links for images
9. Vulnerability Management Image CVEs should display links for image-components
10. Vulnerability Management Images should display links for deployments
11. Vulnerability Management …
> ROX-17982: Wait for secondary entities request in verifyTableLink

- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReportingPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
- ui/apps/platform/src/routePaths.js
This PR adds some boilerplate code to start things off for the new vulnerability reporting page. The routes are in place and a simple header, subheader, and button were added to the main page
> ROX-17813: Vulnerability Reporting 2.0 set up

- ui/apps/platform/cypress/integration/configmanagement/ConfigurationManagement.helpers.js
- ui/apps/platform/cypress/integration/configmanagement/ciscontrols.test.js
- ui/apps/platform/cypress/integration/configmanagement/clusters.test.js
- ui/apps/platform/cypress/integration/configmanagement/deployments.test.js
- ui/apps/platform/cypress/integration/configmanagement/images.test.js
- ui/apps/platform/cypress/integration/configmanagement/namespaces.test.js
- ui/apps/platform/cypress/integration/configmanagement/nodes.test.js
- ui/apps/platform/cypress/integration/configmanagement/policies.test.js
- ui/apps/platform/cypress/integration/configmanagement/roles.test.js
- ui/apps/platform/cypress/integration/configmanagement/secrets.test.js
- ui/apps/platform/cypress/integration/configmanagement/serviceaccount.test.js
- ui/apps/platform/cypress/integration/configmanagement/usersandgroups.test.js
Follow up #6187
Original names of helper functions:
1. `entityListCountMatchesTableLinkCount` 14 results in 5 files
2. `sidePanelEntityCountMatchesTableRows` 34 results in 11 files
3. `pageEntityCountMatchesTableRows` 34 results in 11 files
The testing **objective** was and is to verify correct behavior for **links**.
The testing **method** changed:
* from unreliable assertion of **specific value** of count and noun.
* to reliable assertion of **generic RegExp** for count and noun.
Rename helper functions replace obsolete Count and emphasize Link:
1. `verifyTableLinkToSidePanelTable`
2. `verifyWidgetLinkFromSidePanelToTable`
3. `verifyWidgetLinkFromSinglePageToTable`
Rewrite test titles:
1. should go from table link to whatevers table in side panel
2. should go to whatevers table from …
> chore(ui): Rename link functions for Configuration Management tests

- image/templates/helm/shared/internal/scanner-config-shape.yaml
- image/templates/helm/shared/templates/02-scanner-06-deployment.yaml.htpl
- image/templates/helm/stackrox-central/internal/config-shape.yaml
- image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- image/templates/helm/stackrox-central/values-public.yaml.example.htpl
- image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml
- image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl
- image/templates/helm/stackrox-secured-cluster/templates/admission-controller.yaml
- image/templates/helm/stackrox-secured-cluster/templates/collector.yaml
- image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl
- image/templates/helm/stackrox-secured-cluster/values-public.yaml.example
- pkg/helm/charts/tests/centralservices/testdata/helmtest/central.test.yaml
- pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/admission-control.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/sensor.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/tolerations.test.yaml
This merge requests adds support for changing affinities 
Current values were defined as default values for all components.
Central services:
```
$ cd pkg/helm/charts/tests/centralservices
$ go test
PASS
ok      github.com/stackrox/rox/pkg/helm/charts/tests/centralservices   29.403s
```
Secured cluster:
```
$ cd pkg/helm/charts/tests/securedclusterservices
$ go test -v
PASS
ok      github.com/stackrox/rox/pkg/helm/charts/tests/securedclusterservices    5.837s
```
> feat(helm): add support affinities and tolerations

- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
Fixes an edge case causing CI failures.
If an image integration with name `core quay` exists in the cluster under test when the groovy test suite is started, attempts to delete the integration will fail due to an invalid UUID.  This is caused by the `coreImageIntegrationId` var being set to the value `id: <uuid>`, the `id:` prefix will cause UUID parse errors:
```
ImageScanningTest > Image metadata from registry test - #testName > ImageScanningTest.Image metadata from registry test - quay-auto STANDARD_OUT
17:23:23 | INFO  | ImageScanningTest         | Starting testcase
17:23:23 | WARN  | ImageIntegrationService   | Failed to delete integration
io.grpc.StatusRuntimeException: INTERNAL: cannot parse UUID id: "56489001-b712-4301-9a50-c1650c30d88b"
```
If any of these don't apply, please …
> ROX-17742: Fix CI `cannot parse UUID id` error

- ui/apps/platform/src/Components/Pagination/PaginationInput/PaginationInput.js
- ui/apps/platform/src/Components/ReactSelect/ReactSelect.js
- ui/apps/platform/src/Components/URLSearchInputWithAutocomplete.js
- ui/apps/platform/src/Components/forms/ReduxPasswordField.js
- ui/apps/platform/src/Components/forms/ReduxTextField.js
- ui/apps/platform/src/Containers/Clusters/Components/AdmissionControl/AdmissionControlStatusTotals.tsx
- ui/apps/platform/src/Containers/Clusters/Components/Collector/CollectorStatusTotals.tsx
- ui/apps/platform/src/Containers/Clusters/Components/Scanner/ScannerStatusTotals.tsx
- ui/apps/platform/src/Containers/Clusters/Components/SensorUpgrade.tsx
- ui/apps/platform/src/constants/form.constants.ts
As part of ongoing accessibilty effort, delete leftover styles that detract from legibility of Red Hat font with PatternFly colors.
* Classic contrast between bold font-700 and normal font-600 was sometimes too subtle to see.
* PatternFly contrast between bold font-700 and normal font-400 makes obvious some inconsistent unneeded bold formatting.
Find in Files `font-600` reduced from 25 results in 16 files to 8 results in 6 files that are soon to be deleted: 5 files for Network Graph 1.0 and 1 file for Vulnerability Management Policy.
1. Remove `font-600` if normal font weight is appropriate:
* src/Components/Pagination/PaginationInput/PaginationInput.js
* src/Components/ReactSelect/ReactSelect.js
* src/Components/URLSearchInputWithAutocomplete.js
* …
> fix(ui): Delete unneeded Tailwind font weight (part 4)

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#12-15-0
1. Added support for running Cypress tests with Chrome's new `--headless=new` flag. Chrome versions 112 and above will now be run in the `headless` mode that matches the headed browser implementation.
CI uses Electron 106 (headless). Investigate whether this feature is relevant.
2. The `videoCompression` configuration option now accepts both a boolean or a Constant Rate Factor (CRF) number between `1` and `51`. The videoCompression default value is still `32` CRF and when `videoCompression` is set to `true` the default of 32 CRF will be used.
Investigate whether this feature is relevant for EPIPE failures on CI during video compression.
3. Removed `cypress/mocha-teamcity-reporter` as this package was no longer being referenced. …
> chore(e2e): Update cypress 12.15.0 devDependencies in ui

- central/declarativeconfig/health/datastore/datastore_impl_test.go
After introducing the change to only allow modifications with contexts that are able to modify declarative configurations, the tests were failing. This wasn't noticed because they didn't run on master.
```
=== RUN   TestDeclarativeConfigHealthDatastore
=== PAUSE TestDeclarativeConfigHealthDatastore
=== CONT  TestDeclarativeConfigHealthDatastore
--- PASS: TestDeclarativeConfigHealthDatastore (11.98s)
=== RUN   TestDeclarativeConfigHealthDatastore/TestGetDeclarativeConfigs
--- PASS: TestDeclarativeConfigHealthDatastore/TestGetDeclarativeConfigs (3.59s)
=== RUN   TestDeclarativeConfigHealthDatastore/TestRemoveConfigHealth
--- PASS: TestDeclarativeConfigHealthDatastore/TestRemoveConfigHealth (4.22s)
=== RUN …
```
> fix(declarative-config): Fix declarative config store tests

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
This fixes a couple of issues causing the problem described in the ticket. The current logic makes it so that the Network Graph cannot update whenever the "# updates available" button is visible. Clicking on the button will correctly apply the updates and makes the filters usable again for 30 seconds, until the next time the epoch polling causes the button to reappear.
There were two issues causing this behavior:
1. A check in the update function that skipped the update if the current epoch `!== 0`. This was likely put in place to avoid automatically updating the graph when there was a change to the nodes, but unintentionally skipped _all_ updates to the graph when a node update was available.
2. The UI set the current epoch to the value returned from the `/v1/networkgraph/cluster` …
> ROX-17938: Fix handling of NG epoch updates in UI

- Makefile
- central/declarativeconfig/health/datastore/datastore_impl_test.go
- central/imageintegration/datastore/datastore_impl_test.go
- central/networkgraph/entity/datastore/datastore_impl_test.go
- central/views/imagecve/view_test.go
See change, this should automatically pick up all sql_integration build tags
postgres tests stage
> fix(e2e): Add all Postgres tests automatically to postgres-unit-tests

- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
- Change the test start time variable so that it is more clearly test spec related.
- Move RestAssured config to globalSetup().
> ROX-17499: Two minor changes

- qa-tests-backend/src/test/groovy/AuditLogAlertsTest.groovy
- qa-tests-backend/src/test/groovy/PolicyFieldsTest.groovy
As seen with other tests (e.g. [PolicyFieldsTest](https://github.com/stackrox/stackrox/blob/f7527862e93c9c126862f8a2d28ad8c154ddef71/qa-tests-backend/src/test/groovy/PolicyFieldsTest.groovy#L250)), policy violations can be slow to appear under OCP and particularly after policies are created or changed. This PR gives the test more time to find the violation.
CI is sufficient - with OCP.
> ROX-18030: AuditLogAlertsTest: Wait longer for violations to appear

- qa-tests-backend/src/main/groovy/util/ApplicationHealth.groovy
- qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
The "AdmissionControllerTest > Verify admission controller performs image scans if Sensor is Unavailable" test can fail because while it waits for admission-control pods to be ready it does not wait for them to be healthy and ready to work. This change uses the ApplicationHealth package to ensure admission-control is ready to work before trying to deploy an image that it should refuse.
E.g. in a failing test the admission-control pod is not logging readiness until about `15:50:37` but the test tries to create at `15:50:33`:
```
AdmissionControllerTest > Verify admission controller performs image scans if Sensor is Unavailable STANDARD_OUT
15:50:07 | INFO  | AdmissionControllerTest   | Starting testcase
15:50:12 | INFO  | Kubernetes                | Scaled the deployment sensor to 0 …
```
> ROX-17994: AdmissionControllerTest: Wait for pods to be ready to work

- central/splunk/violations_test.go
This test is flaky since the postgres unit test selection was fixed. If it persists, disable it
CI
> fix(test): skip flaky Splunk test with Postgres

- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
Per title. It is probably harmless that this occurs for each test specification but there is no need. Moving the setup (namespace, PSP and SA creation) to globalSetup() also makes it thread safe.
> ROX-17499: Setup orchestrator once

- ui/apps/platform/cypress/helpers/main.js
- ui/apps/platform/cypress/helpers/vulnmanagement/entities.js
- ui/apps/platform/src/Containers/Dashboard/Widgets/ImagesAtMostRisk.test.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/ImagesAtMostRisk.tsx
Removal of the backend implementation of the non-pg part of this query was causing errors in https://github.com/stackrox/stackrox/pull/6303 so looks like I get to join in the fun.
UI unit tests
> ROX-17886: Remove pre-pg query from ImagesAtMostRisk widget

- central/hash/manager/deduper.go
- central/hash/manager/deduper_test.go
Attempted alerts had their hashes stored in the database, but they should be treated like runtime alerts
Ran master and created thousands of attempted alerts, then upgraded to this PR and saw the total number of hashes drop down to the original level
> ROX-18044: Skip deduping of attempted alerts

- .github/workflows/scripts/prepare-upgrade-test.sh
Prepare upgrade tests uses (previous) roxctl binary to generate Helm charts. 
Roxctl has an option to disable PSP generation.  
See https://github.com/stackrox/stackrox/actions/runs/5376028827
> fix(GHA): disable psps in upgrade tests with roxctl flag

- tests/roxctl/slim-collector.sh
There was an existing flake within the tests for the sensor bundle creation.
Within the tests, curl is used to reach out to central to retrieve the cluster ID. Occasionally, the call failed due to timeouts etc.
Added retries for the curl command to ensure such flakes should be reduced to a minimum.
> ROX-17388: Retry curls in roxctl tests

- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
Per title. This helps prepare for groovy tests to run concurrently. The test failure is from a flake unrelated to this change.
CI is sufficient - and ensures that the changes are benign at this point i.e. before tests actually run in parallel. Experimentation in https://github.com/gavin-stackrox/spock-example/blob/abd5082887c1f7687875b35c5e80ddeb86e3d60a/src/test/groovy/stackrox/BaseSpecification.groovy#L57 show using `synchonized()` in this manner works as desired.
> ROX-17497: Make globalSetup() thread safe

- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/utils/URLParser.ts
1. Find in Files `networkBasePath` 1 result in 1 file
* routePaths: delete with network reducers and sagas
2. Find in Files `networkPath` 9 results in 5 files
* Body: delete now
* integrationSagas: delete with network reducers and sagas
* networkSagas: delete with network reducers and sagas
* routePaths: delete with network reducers and sagas
* URLParser: delete now
TL;DR Decrease 666K in static js implies webpack understands deletion of async import.
Time will tell how much (if any) additional decrease from careful deletion:
* css style
* js code
* media images, and so on
* dependencies
* `wc build/static/css/*.css`
branch - master total: -4223 = 5796730 - 5800953
branch - master main.css: 0 = 4974847 - 4974847
* `ls -al build/static/css/*.css | …
> ROX-18011: Delete Network Graph 1.0 route

- ui/apps/platform/cypress/integration/clusters/Clusters.helpers.js
- ui/apps/platform/cypress/integration/clusters/delegateScanning.test.js
- ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/ToggleDelegatedScanning.tsx
- ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx
- ui/apps/platform/src/services/DelegatedRegistryConfigService.ts
- ui/apps/platform/src/types/dedicatedRegistryConfig.proto.ts
This implements the basic transition between mock
https://www.sketch.com/s/a7c5e8bd-524f-4396-b273-a8ccc33b3a77/a/WdY75g0
and mock
https://www.sketch.com/s/a7c5e8bd-524f-4396-b273-a8ccc33b3a77/a/nQVa89a
Off
On
CI test expanded to cover this interaction
> ROX-18023: Add delegate image scanning toggle

- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
Previously this was done on a per spec basis but that will not be feasible with concurrent tests. This PR changes the record and compare to a per run basis.
> ROX-17499: Check resource leaks over the entire test run

- pkg/booleanpolicy/default_policies_test.go
- pkg/booleanpolicy/field_metadata.go
- pkg/booleanpolicy/querybuilders/special_cases.go
Add Caps needs us to match all values specified in the criteria, not just a string exact match.
Automated unit test cases
> ROX-18073: Fix bug in AddCaps implementation

- Makefile
- README.md
Add a `SKIP_CLI_BUILD` flag similar to `SKIP_UI_BUILD` to improve build times when one is not interested in roxctl changes.
> ROX-17722: add SKIP_CLI_BUILD in Makefile

- central/networkgraph/entity/datastore/datastore_impl_test.go
This reenables the network entity tests; however, I needed to expand the SAC scopes because the datastore does reads which now have implicit scopes via Postgres. It's not possible for a user to have just write access currently so I think we can expand the READ_WRITE access to truly mean RW instead of just W in another PR
Unit test
> ROX-18024: Reenable network entity tests

- qa-tests-backend/src/main/groovy/common/Constants.groovy
- qa-tests-backend/src/test/groovy/AuditLogAlertsTest.groovy
Failures from the `AuditLogAlertsTest > Verify Audit Log Event Source Policies Trigger: *` test continue to show up on merge PR runs despite an increase of the wait for violation timeout from 60s to 100s. This PR increases the timeout to 900s to help get more data on instances that require a longer timeout. [Repeat runs](https://prow.ci.openshift.org/pr-history/?org=stackrox&repo=stackrox&pr=6649) had no recorded test run time greater then **6s** despite running with parameters similar to a merge run.
> ROX-18030: AuditLogAlertsTest: Extend timeout to flush out outliers
