.github/workflows/cut-rc.yml, .github/workflows/finish-release.yml, .github/workflows/start-release.yml, .github/workflows/upgrade-test.yml
Tested in https://github.com/stackrox/test-gh-actions/pull/98.
See above, not applicable.
=> ROX-14261: add accessibility text to upstream release Slack messages

central/deployment/datastore/search_comparison_test.go
I already updated the other test (`BenchmarkSearchAllDeployments`) mentioned on the JIRA through one of the dackbox PR.
=> [ROX-17705] Update TestDeploymentSearchResults to run on postgres

central/image/service/service_impl.go
Some time ago, [we tailored unavailability metrics to a set gRPC statuses](https://github.com/stackrox/rhacs-observability-resources). This PR updates Central to use `ABORTED` instead of `UNAVAILABLE` to [throttle Sensor](https://github.com/stackrox/stackrox/blob/13964fdb33e687fb9c6ed271e940648c0d938e8a/sensor/common/detector/enricher.go#L126). This should keep availability metrics clean when Scanner concurrency reaches its limit in Central.
`ABORTED` is never generated by the gRPC implementation or server.
TODO: Local run, reduce Central limit, observe correct status code.
=> ROX-17093: Use ABORTED status for throttling scanner calls

tools/generate-helpers/pg-table-bindings/funcs.go, tools/generate-helpers/pg-table-bindings/store.go.tpl
Extract PG filter generation.
CI – generated files were not changed
=> ROX-17926: Extract common code into sub template

.github/workflows/build.yaml
Per title. The script was removed in a recent PR (#6550)
n/a - will check after merge
n/a
=> fix(ci): install roxctl via make

central/reportconfigurations/service/common/authorizer.go, pkg/grpc/server.go
=> Add routing for v2 APIs and authorizers for v2.ReportConfigurationService grpc endpoints

.github/workflows/unit-tests.yaml
Re-quote a shell command to satisfy shellcheck linter.
=> fix: workaround a shellcheck error in `unit-tests.yaml`

central/nodecomponentcveedge/datastore/datastore_sac_test.go, central/nodecomponentedge/datastore/datastore_sac_test.go
Extract common code and run tests in parallel as they all are read only. 
CI
=> refactor(pg): run *edge tests in parallel

ui/apps/platform/src/Containers/MainPage/Body.tsx
> deprecating our Postgres feature flag
Separate from Vulnerability Management 1.0
=> ROX-17765: Delete non-postgres conditional code in Body UI

ui/apps/platform/cypress/integration/clusters/Clusters.helpers.js, ui/apps/platform/cypress/integration/clusters/delegateScanning.test.js, ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx, ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/routePaths.js
This PR
* sets up the route
* adds the skeleton of the page (only the breadcrumb, title, subhead, and placeholder for the first item on the page)
* adds the first ui-e2e test for this page
Newborn page
CI test
=> ROX-17174: Create Delegate Image Scanning page

central/views/imagecve/view_test.go
=> ROX-18025: Unskip ImageCVEView test

.github/workflows/scripts/prepare-upgrade-test.sh
Cherry-pick fix from #6673 .
Tested in original PR.
=> fix(GHA): 3.74.x cherry-pick fix(GHA): disable psps in upgrade tests with roxctl flag

.github/workflows/scripts/prepare-upgrade-test.sh
Cherry-picked #6673. 
Tested in original PR.
=> fix(GHA): 4.1.x disable psps in upgrade tests with roxctl flag (#6673)

.github/workflows/scripts/prepare-upgrade-test.sh
Cherry-picking #6673 .
Tested in original PR.
=> fix(GHA): 4.0.x disable psps in upgrade tests with roxctl flag (#6673)

deploy/common/k8sbased.sh, image/embed_charts.go, image/templates/sensor/kubernetes/sensor.sh, image/templates/sensor/openshift/sensor.sh, sensor/upgrader/bundle/context.go, sensor/upgrader/bundle/instantiator.go, sensor/upgrader/bundle/instantiator_test.go, sensor/upgrader/common/filter.go, sensor/upgrader/upgradectx/context.go
Cherry pick #6490 #6426 #5729 #6463 into `release-3.74 `
CI
=> PSP fixes cherry-pick in `release-3.74`

central/vulnerabilityrequest/manager/requestmgr/manager_impl_create_req_test.go, central/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go, central/vulnerabilityrequest/utils/util.go
See title
~[ ] Unit test and regression tests added
[ ] Evaluated and added CHANGELOG entry if required
[ ] Determined and documented upgrade steps
[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~
This is a test
=> ROX-17696: Update TestVulnRequestManager to run on postgres

CHANGELOG.md
=> ROX-18073: Adding a changelog for the add caps fix

scripts/ci/lib.sh
Reduce noise in slack and jira.
=> ROX-17280: Skip notifications for release-4.0

central/graphql/resolvers/service_accounts_test.go, central/graphql/resolvers/vulnerability_requests_test.go, central/vulnerabilityrequest/manager/querymgr/query_manager_impl_test.go
`TestVulnRequestsResolver` and `TestVulnReqQueryManager`
~[ ] Unit test and regression tests added
[ ] Evaluated and added CHANGELOG entry if required
[ ] Determined and documented upgrade steps
[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~
This is a test
=> ROX-17695, ROX-17697: Update more VM deferral tests to run on postgres

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveSingle.test.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/SeverityCountLabels.tsx
Additional Cypress tests for Workload CVEs **Image single** page.
CI e2e tests
=> test(ui): Add Cypress tests for workload cve image single page

pkg/search/postgres/select_query_test.go
Verify scanning nullable ts field.
Unit
=> Unit test scanning nullable timestamp field

central/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go
=> fix(test): Skip TestVulnRequestManager until fixed

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/CreateVulnReport/CreateVulnReportPage.tsx
Simple PR to add breadcrumbs to the report creation page
=> ROX-17828: Adding breadcrumbs to report creation page

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/CreateVulnReport/CreateVulnReportPage.tsx
Simple PR to add a basic wizard with 3 steps: `Configure report parameters`, `Configure delivery destinations (Optional)`, and `Review and create`. Each step will be fleshed out more in future PRs. We will also add form validation as well
=> ROX-17830: Show report creation wizard flow with 3 steps

operator/apis/platform/v1alpha1/central_types.go, operator/bundle/manifests/platform.stackrox.io_centrals.yaml, operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/crd/bases/platform.stackrox.io_centrals.yaml, operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
The default in the CRD is superfluous
=> ROX-17712: Remove the scannerComponent enabled default

pkg/helm/charts/tests/centralservices/base_suite_test.go, pkg/helm/charts/tests/centralservices/testdata/all-values-explicit.yaml, pkg/helm/charts/tests/centralservices/testdata/autogenerate-all.yaml, pkg/helm/charts/tests/securedclusterservices/base_suite_test.go, pkg/helm/charts/tests/securedclusterservices/testdata/all-values-explicit.yaml
=> refactor(operator): extract yamls to files

central/metadata/service/service_impl.go, sensor/common/centralclient/client.go, sensor/common/centralclient/client_test.go, sensor/common/centralclient/grpc_connection.go
This reverts commit b727ea465402ed25aabdb8a4fe0a6e4ae862fb30.
=> ROX-18173: Revert "ROX-18173: Authenticate 'v1/metadata' (#6718)"

central/graphql/resolvers/image_cve_core.go, central/views/imagecve/db_response.go, central/views/imagecve/mocks/types.go, central/views/imagecve/types.go, central/views/imagecve/view_test.go, pkg/search/postgres/select_query_test.go
=> ROX-18193: Read nullable timestamp field into pointer

pkg/metrics/server_test.go
https://issues.redhat.com/browse/ROX-18300 reports a test flake where the server refused the connection. Since the server is started in a go routine, it might happen that it is not ready in time for the get request. Wrapping the get request and assert in a `assert.Eventually` should reduce the probability for this happening.
=> ROX-18300: wrap assert in Eventually

pkg/env/process_pruning.go
turn on process pruning by default for 4.0.X.
screenshots.
=> turn on process pruning

ui/apps/platform/src/Containers/Integrations/utils/integrationsList.ts, ui/apps/platform/src/types/featureFlag.ts
Ross, I did not change the 2 backend occurrences:
* feature flag: https://github.com/stackrox/stackrox/blob/master/pkg/features/list.go#L27-L28
* reference in tests: https://github.com/stackrox/stackrox/blob/master/qa-tests-backend/scripts/lib.sh#L30
=> chore(ui): Delete ROX_CLAIR_V4_SCANNING in ui

central/ui/mux.go
Don't allow anyone to iframe it
screenshots.
=> ROX-11227: Add X-Frame-Options header to UI request

go.mod, go.sum
=> ROX-17712: Upgrade helm operator

sensor/common/compliance/auditlog_manager.go, sensor/common/compliance/auditlog_manager_impl.go, sensor/common/compliance/auditlog_manager_test.go
=> ROX-17323: Introduce Offline awareness to Audit Log Manager

go.mod, go.sum, scanner/go.mod
https://github.com/stackrox/docker-registry-client/pull/14
- ~[] Investigated and inspected CI test results~
CI
=> chore(deps): bump docker-registry-client

operator/apis/platform/v1alpha1/central_types.go, operator/pkg/central/extensions/reconcile_pvc.go
When deploying a Central CR with an empty spec the operators runs into a nil-pointer exception.
screenshots.
=> fix(operator): nil-pointer exception with empty Central CR

central/complianceoperator/v2/profiles/store/postgres/store.go, central/complianceoperator/v2/rules/store/postgres/store.go
Had to regenerate as generator changes slipped in between my last rebase and the merge.
screenshots.
In addition to reviewing your …
=> chore(regenerate): compliance profile protos stores regenerate

CHANGELOG.md
=> ROX-18173: Mention authenticated endpoints in CHANGELOG

central/cluster/service/service_impl.go, central/detection/service/service_impl.go, central/image/service/service_impl.go, central/imageintegration/service/service_impl.go, central/main.go, central/metadata/service/service_impl.go, central/resourcecollection/service/service_impl.go, pkg/grpc/authz/or/or.go
=> refactor(authn): Rename `SensorOrAuthorizer` for brevity

sensor/kubernetes/complianceoperator/updater.go, sensor/kubernetes/complianceoperator/updater_test.go
=> Collect compliance operator status on startup

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/CreateVulnReport/CreateVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/LastRunState.test.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/LastRunState.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/LastRunStatusState.test.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/LastRunStatusState.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useCreateReport.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useFetchReports.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/errorUtils.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/types.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.ts, ui/apps/platform/src/services/ReportsService.ts, ui/apps/platform/src/services/ReportsService.types.ts
This PR will fetch data using the following APIs: `/v2/reports/configurations`, `/v2/reports/status/:id`, and `/v2/reports/last-status/:id` and then merge the data to be displayed in the reports table
https://github.com/stackrox/stackrox/assets/4805485/1ef1c0db-727c-4dfd-8351-d7229e93bd30
=> ROX-18422: Populating the reports table

central/sensor/service/pipeline/all/factory.go, pkg/features/list.go, sensor/kubernetes/client/client.go, sensor/kubernetes/listener/resource_event_handler.go, tests/e2e/bats/fixtures/test-pod-without-oomkilled_object.json
=> Remove legacy compliance integration feature flag

scanner/cmd/scanner/main.go, scanner/go.mod, scanner/go.sum
=> Gracefully stop GRPC and update overwrites

tests/yamls/multi-container-pod.yaml
try to fix the non-groovy tests.
screenshots.
=> chore(test): 4 0 fix nongroovy

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx, ui/apps/platform/src/services/ReportsService.ts
This PR allows the user to delete a report using the table row actions
https://github.com/stackrox/stackrox/assets/4805485/cb243f89-7983-47a7-a69d-a167b38d8900
=> ROX-17818: Show table row actions + ROX-17825: Allow deleting report

central/alert/datastore/internal/store/postgres/store_test.go, central/cluster/store/cluster/postgres/store_test.go, central/compliance/datastore/internal/store/postgres/metadata/store_test.go, central/compliance/datastore/internal/store/postgres/results/store_test.go, central/deployment/store/postgres/store_test.go, central/namespace/store/postgres/store_test.go, central/networkbaseline/store/postgres/store_test.go, central/networkpolicies/datastore/internal/store/postgres/store_test.go, central/pod/store/postgres/store_test.go, central/processbaseline/store/postgres/store_test.go, central/processbaselineresults/datastore/internal/store/postgres/store_test.go, central/processindicator/store/postgres/store_test.go, central/rbac/k8srole/internal/store/postgres/store_test.go, central/rbac/k8srolebinding/internal/store/postgres/store_test.go, central/risk/datastore/internal/store/postgres/store_test.go, central/secret/internal/store/postgres/store_test.go, central/serviceaccount/internal/store/postgres/store_test.go, tools/generate-helpers/pg-table-bindings/store_test.go.tpl
=> refactor: Use common test cases for generated SAC store tests: GetMany

sensor/common/signal/signal_service.go
=> chore(cleanup): Remove nondescript log line

ui/apps/platform/src/Containers/ComplianceEnhanced/CompliancePage.tsx, ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx, ui/apps/platform/src/routePaths.js
Incorporate routing for Compliance 2.0 and include a link to it in the sidebar navigation.
Feature flag off:
Feature flag on:
=> ROX-18111: Setup Compliance 2.0 routing

.golangci.yml, scanner/cmd/scanner/main.go, scanner/config/config.go, scanner/indexer/indexer.go, scanner/indexer/service.go, scanner/matcher/matcher.go, scanner/matcher/service.go
Scanner was not adhering to golangci-line rules, so this PR fixes that.
CI
=> ci(scanner): make golangci-lint happy

central/alert/datastore/internal/store/postgres/store_test.go, central/cluster/store/cluster/postgres/store_test.go, central/compliance/datastore/internal/store/postgres/metadata/store_test.go, central/compliance/datastore/internal/store/postgres/results/store_test.go, central/deployment/store/postgres/store_test.go, central/namespace/store/postgres/store_test.go, central/networkbaseline/store/postgres/store_test.go, central/networkpolicies/datastore/internal/store/postgres/store_test.go, central/pod/store/postgres/store_test.go, central/processbaseline/store/postgres/store_test.go, central/processbaselineresults/datastore/internal/store/postgres/store_test.go, central/processindicator/store/postgres/store_test.go, central/rbac/k8srole/internal/store/postgres/store_test.go, central/rbac/k8srolebinding/internal/store/postgres/store_test.go, central/risk/datastore/internal/store/postgres/store_test.go, central/secret/internal/store/postgres/store_test.go, central/serviceaccount/internal/store/postgres/store_test.go, tools/generate-helpers/pg-table-bindings/store_test.go.tpl
=> refactor: Use common test cases for generated SAC store tests: Count

ui/apps/platform/cypress/integration/compliance/complianceDashboard.test.js, ui/apps/platform/cypress/integration/compliance/complianceList.test.js
Minimize differences in test coverage between gke and ocp.
=> chore(e2e): Unskip openshift in compliance tests

central/alert/datastore/internal/store/postgres/store_test.go, central/cluster/store/cluster/postgres/store_test.go, central/compliance/datastore/internal/store/postgres/metadata/store_test.go, central/compliance/datastore/internal/store/postgres/results/store_test.go, central/deployment/store/postgres/store_test.go, central/namespace/store/postgres/store_test.go, central/networkbaseline/store/postgres/store_test.go, central/networkpolicies/datastore/internal/store/postgres/store_test.go, central/pod/store/postgres/store_test.go, central/processbaseline/store/postgres/store_test.go, central/processbaselineresults/datastore/internal/store/postgres/store_test.go, central/processindicator/store/postgres/store_test.go, central/rbac/k8srole/internal/store/postgres/store_test.go, central/rbac/k8srolebinding/internal/store/postgres/store_test.go, central/risk/datastore/internal/store/postgres/store_test.go, central/secret/internal/store/postgres/store_test.go, central/serviceaccount/internal/store/postgres/store_test.go, tools/generate-helpers/pg-table-bindings/store_test.go.tpl
=> refactor: Use common test cases for generated SAC store tests: Walk

central/complianceoperator/v2/checkresults/store/postgres/store.go, central/complianceoperator/v2/scans/store/postgres/store.go
Parallel work on new stores and store code generation did collide. Files need to be re-generated
screenshots.
=> fix: regenerate files

central/alert/datastore/internal/store/postgres/store_test.go, central/cluster/store/cluster/postgres/store_test.go, central/compliance/datastore/internal/store/postgres/metadata/store_test.go, central/compliance/datastore/internal/store/postgres/results/store_test.go, central/complianceoperator/v2/checkresults/store/postgres/store.go, central/complianceoperator/v2/scans/store/postgres/store.go, central/deployment/store/postgres/store_test.go, central/namespace/store/postgres/store_test.go, central/networkbaseline/store/postgres/store_test.go, central/networkpolicies/datastore/internal/store/postgres/store_test.go, central/pod/store/postgres/store_test.go, central/processbaseline/store/postgres/store_test.go, central/processbaselineresults/datastore/internal/store/postgres/store_test.go, central/processindicator/store/postgres/store_test.go, central/rbac/k8srole/internal/store/postgres/store_test.go, central/rbac/k8srolebinding/internal/store/postgres/store_test.go, central/risk/datastore/internal/store/postgres/store_test.go, central/secret/internal/store/postgres/store_test.go, central/serviceaccount/internal/store/postgres/store_test.go, tools/generate-helpers/pg-table-bindings/store_test.go.tpl
=> refactor: Use common test cases for generated SAC store tests: GetIDs

central/alert/datastore/internal/store/postgres/store_test.go, central/cluster/store/cluster/postgres/store_test.go, central/compliance/datastore/internal/store/postgres/metadata/store_test.go, central/compliance/datastore/internal/store/postgres/results/store_test.go, central/deployment/store/postgres/store_test.go, central/namespace/store/postgres/store_test.go, central/networkbaseline/store/postgres/store_test.go, central/networkpolicies/datastore/internal/store/postgres/store_test.go, central/pod/store/postgres/store_test.go, central/processbaseline/store/postgres/store_test.go, central/processbaselineresults/datastore/internal/store/postgres/store_test.go, central/processindicator/store/postgres/store_test.go, central/rbac/k8srole/internal/store/postgres/store_test.go, central/rbac/k8srolebinding/internal/store/postgres/store_test.go, central/risk/datastore/internal/store/postgres/store_test.go, central/secret/internal/store/postgres/store_test.go, central/serviceaccount/internal/store/postgres/store_test.go, tools/generate-helpers/pg-table-bindings/store_test.go.tpl
=> refactor: Use common test cases for generated SAC store tests: Exists

central/alert/datastore/internal/store/postgres/store_test.go, central/cluster/store/cluster/postgres/store_test.go, central/compliance/datastore/internal/store/postgres/metadata/store_test.go, central/compliance/datastore/internal/store/postgres/results/store_test.go, central/deployment/store/postgres/store_test.go, central/namespace/store/postgres/store_test.go, central/networkbaseline/store/postgres/store_test.go, central/networkpolicies/datastore/internal/store/postgres/store_test.go, central/pod/store/postgres/store_test.go, central/processbaseline/store/postgres/store_test.go, central/processbaselineresults/datastore/internal/store/postgres/store_test.go, central/processindicator/store/postgres/store_test.go, central/rbac/k8srole/internal/store/postgres/store_test.go, central/rbac/k8srolebinding/internal/store/postgres/store_test.go, central/risk/datastore/internal/store/postgres/store_test.go, central/secret/internal/store/postgres/store_test.go, central/serviceaccount/internal/store/postgres/store_test.go, tools/generate-helpers/pg-table-bindings/store_test.go.tpl
=> refactor: Use common test cases for generated SAC store tests: Get

central/alert/datastore/internal/store/postgres/store_test.go, central/cluster/store/cluster/postgres/store_test.go, central/compliance/datastore/internal/store/postgres/metadata/store_test.go, central/compliance/datastore/internal/store/postgres/results/store_test.go, central/deployment/store/postgres/store_test.go, central/namespace/store/postgres/store_test.go, central/networkbaseline/store/postgres/store_test.go, central/networkpolicies/datastore/internal/store/postgres/store_test.go, central/pod/store/postgres/store_test.go, central/processbaseline/store/postgres/store_test.go, central/processbaselineresults/datastore/internal/store/postgres/store_test.go, central/processindicator/store/postgres/store_test.go, central/rbac/k8srole/internal/store/postgres/store_test.go, central/rbac/k8srolebinding/internal/store/postgres/store_test.go, central/risk/datastore/internal/store/postgres/store_test.go, central/secret/internal/store/postgres/store_test.go, central/serviceaccount/internal/store/postgres/store_test.go, tools/generate-helpers/pg-table-bindings/store_test.go.tpl
=> refactor: Use common test cases for generated SAC store tests: Delete*

central/image/datastore/store/postgres/store.go
More optimizations of reprocessing to come, but this is a small one
CI
=> chore(optimization): Avoid rewriting image layers unnecessarily

central/alert/datastore/internal/store/postgres/store_test.go, central/cluster/store/cluster/postgres/store_test.go, central/compliance/datastore/internal/store/postgres/metadata/store_test.go, central/compliance/datastore/internal/store/postgres/results/store_test.go, central/deployment/store/postgres/store_test.go, central/namespace/store/postgres/store_test.go, central/networkbaseline/store/postgres/store_test.go, central/networkpolicies/datastore/internal/store/postgres/store_test.go, central/pod/store/postgres/store_test.go, central/processbaseline/store/postgres/store_test.go, central/processbaselineresults/datastore/internal/store/postgres/store_test.go, central/processindicator/store/postgres/store_test.go, central/rbac/k8srole/internal/store/postgres/store_test.go, central/rbac/k8srolebinding/internal/store/postgres/store_test.go, central/risk/datastore/internal/store/postgres/store_test.go, central/secret/internal/store/postgres/store_test.go, central/serviceaccount/internal/store/postgres/store_test.go, tools/generate-helpers/pg-table-bindings/store_test.go.tpl
=> refactor: Use common test cases for generated SAC store tests: cleanup

scanner/services/converters.go, scanner/services/converters_test.go
fix Style checks on master
screenshots.
=> fix: comply with goimports rules

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CloneVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
This PR adds the clone flow for the reporting feature
https://github.com/stackrox/stackrox/assets/4805485/94367847-4635-405a-9129-681eec84816f
=> ROX-17824: Add clone flow for reports

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/DeliveryDestinationsDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/ReportParametersDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/ScheduleDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportReviewForm.tsx
This PR shows the configuration details of a report in the details page
=> ROX-17857: Show configuration details

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/NotifierSelection.tsx
This automatically sets the default distribution list when selecting a notifier in the reports form
https://github.com/stackrox/stackrox/assets/4805485/6baf6434-ae86-4fdf-8fdb-bcb4f720ae8a
=> ROX-18726: Add default distribution list when selecting notifier

go.mod
=> chore(fix): Drop go.mod to 1.19

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/RunHistory.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useFetchReportHistory.ts, ui/apps/platform/src/services/ReportsService.ts, ui/apps/platform/src/services/ReportsService.types.ts
This PR adds the run history for a report configuration
=> ROX-17858: Show run history in report details

.github/CODEOWNERS
Looks like @stackrox/merlin owns this part of codebase.
N/A
=> chore(perf): assign tests/performance to merlin

sensor/kubernetes/clustermetrics/cluster_metrics.go
This executes the cluster metrics pipeline initially before starting the ticker. Without this change, Central only receives the first message after the 5 minute ticker has elapsed for the first time. That is a bit annoying when testing the metrics and perhaps also misleading when interpreting the metrics (looks like a 5 minute disconnect).
Tested that the first message now appears directly after Sensor -> Central communication has been established.
=> ROX-18274: add initital run to cluster metrics pipeline

qa-tests-backend/src/test/groovy/ProcessesListeningOnPortsTest.groovy
This PR makes some changes to `ProcessesListeningOnPortsTest.groovy` to support parallel execution (i.e. a unique namespace for the test) as well as some minor test flow and orchestrator call use refactoring. With this change there are now 2 concurrent tests in Groovy e2e tests, DeclarativeCongfigTest & ProcessesListeningOnPortsTest.
It also changes logging to undo the prior attempt to get a normalized thread description and replaces it with a test specification context logline to help correlate logs to test. Dealing with test output in a concurrent test world in a viable manner is still something of a work in progress, but at least for this change the output looks good to me. 
CI++
- fails as [expected](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/68 …
=> ROX-18195: Add ProcessesListeningOnPortsTest to the parallel set

.openshift-ci/post_tests.py
Due to #6974, groovy tests artifacts are stored to openshift-ci artifacts. This causes gke-version-compatibility-tests to fail because this job runs multiple `final_posts` and the destination dir already exists in artifacts. This PR gives the destination dir a unique suffix.
`version-compatibility-tests` should be updated to only execute `final_posts` once however the unique destination is a useful change and how GCS storage handled this job previously.
/test gke-version-compatibility-tests
=> fix(ci): handle multiple report artifacts

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useRunReport.ts, ui/apps/platform/src/services/ReportsService.ts, ui/apps/platform/src/services/ReportsService.types.ts
This PR allows the user to `Send report now` and `Generate download`. There seems to be a backend bug right now, so you will likely not see the status change when you refresh or you might see an error at the top
=> ROX-17819: Allow sending a report now and generating a download

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useFetchReports.ts, ui/apps/platform/src/services/ReportsService.ts
This PR adds filtering by report name and pagination to the reports table
=> ROX-17816: Add filtering and pagination to reports table

scripts/ci/pull-retag-push.sh
Remove the images that were retagged to save on disk space
CI
=> fix(build): Decrease disk usage after retag

central/reportconfigurations/service/common/authorizer.go
Forgot to update the authorizer path
screenshots.
=> fix(bug): Fix authorizer with new service name

scanner/image/db/scripts/docker-entrypoint.sh
See https://github.com/stackrox/stackrox/pull/4841 and https://github.com/stackrox/stackrox/pull/5477
Nah
=> chore(scanner): fast shutdown scanner-db

scanner/Makefile
=> chore(scanner): initialize tag once in Makefile

go.mod, go.sum
Update helmtest to most recent commit (after Kubernetes deps have been made compatible via https://github.com/stackrox/helmtest/pull/47). This is done in preparation of adding PrometheusRule CR, which required a CRD update in helmtest (see https://github.com/stackrox/helmtest/pull/45).
screenshots.
=> fix(deps): update `helmtest`

ui/apps/platform/cypress/helpers/visit.js, ui/apps/platform/cypress/integration/accessControl/accessControl.helpers.js, ui/apps/platform/cypress/integration/accessControl/accessControlAccessScopes.test.js, ui/apps/platform/cypress/integration/accessControl/accessControlAuthProviders.test.js, ui/apps/platform/cypress/integration/accessControl/accessControlPermissionSets.test.js, ui/apps/platform/cypress/integration/accessControl/accessControlRoles.test.js, ui/apps/platform/cypress/integration/collections/permissions.test.js, ui/apps/platform/cypress/integration/credentialExpiry/credentialExpiry.test.js, ui/apps/platform/cypress/integration/systemConfig/systemConfig.test.js, ui/apps/platform/src/Components/NotFoundMessage/NotFoundMessage.tsx, ui/apps/platform/src/Components/PageNotFound.tsx, ui/apps/platform/src/Containers/Clusters/ClustersPage.js, ui/apps/platform/src/Containers/Clusters/ClustersSidePanel.tsx, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.js, ui/apps/platform/src/Containers/Clusters/clustersTableColumnDescriptors.js, ui/apps/platform/src/Containers/Dashboard/DashboardPage.tsx, ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.tsx, ui/apps/platform/src/Containers/Policies/Table/PoliciesTablePage.tsx, ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesPage.tsx, ui/apps/platform/src/Containers/Risk/RiskSidePanelContent.js, ui/apps/platform/src/Containers/SystemHealth/DashboardPage.js, ui/apps/platform/src/routePaths.ts
1. Replace implicit **and** relationship for `resourceAccessRequirements` with predicates functions:
* `everyResource` for **and** relationship
* `someResource` for **or** relationship
2. Add conditional rendering in main Dashboard
* `ViolationsByPolicySeverity` only if has read access for Alert
* `ImagesAtMostRisk` only if has read access for Image
* `DeploymentsAtMostRisk` only if has read access for Deployment
* `AgingImages` only if has read access for Image
* `ViolationsByPolicyCategory` only if has read access for Alert
* `ComplianceLevelsByStandard` only if has read access for Compliance
3. Add conditional rendering in Risk
* **View Deployment in Network Graph** on if has requirements for `networkPath`
* **Process Discovery** only if read access for Alert
4. Add conditional …
=> ROX-18686: Add missing resourceAccessRequirements in routePaths

CHANGELOG.md
Add changelog entry with monitoring
CI
=> ROX-18793: Add changelog entry with monitoring

deploy/common/k8sbased.sh
Set the OpenShift version for sensor deployment if `ROX_OPENSHIFT_VERSION` is set.
screenshots.
=> fix(deploy): set OpenShift version if ROX_OPENSHIFT_VERSION

central/reports/common/report_formatter.go, central/reports/scheduler/v2/reportgenerator/consts.go, central/reports/scheduler/v2/reportgenerator/report_gen_impl_test.go
This  PR adds csvv column to vuln report. 
Added unit test
=> ROX-16564: Added cvss score in vuln report CSV

.github/workflows/start-release.yml
=> ROX-17507: Automatically find start-release git SHA (#101)

.github/workflows/cut-rc.yml
Transferring changes from 
- https://github.com/stackrox/test-gh-actions/pull/100
- https://github.com/stackrox/test-gh-actions/pull/108
=> fix(gha): Increase timeout waiting for Quay images for RCs to 60m

ui/apps/platform/src/types/featureFlag.ts
Previously ignored by the `ROX_CENTRAL_EVENTS` feature flag introduction, this makes things right again.
N/A
=> fix(ui): sort feature flags alphabetically

.github/workflows/finish-release.yml
Porting of https://github.com/stackrox/test-gh-actions/pull/110.
Tested in `test-gh-actions`.
=> ROX-13192: let finish-release bump infra demo versions

ui/apps/platform/cypress/integration/configmanagement/dashboard.test.js, ui/apps/platform/src/Containers/ConfigManagement/Dashboard/Page.js, ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/ComplianceByControls.js, ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/PolicyViolationsBySeverity.js, ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/SecretsMostUsedAcrossDeployments.js, ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/UsersWithMostClusterAdminRoles.js, ui/apps/platform/src/Containers/ConfigManagement/Entity/Policy/Policy.js
1. ComplianceByControls
* **Scan** button requires READ_WRITE_ACCESS for Compliance resource.
2. Policy
* **Edit policy** button would require READ_WRITE_ACCESS for WorkflowAdministration resource, but is a view link.
* However, policies route requires Integration, which Configuration Management does not require.
1. ComplianceByControls
* Conditionally render `ScanButton` element. Delete obsolete `isConfigMangement` prop.
* Bonus: Delete unneeded `button` elements in view links and replace title case with sentence case.
2. Policy
* Move helper component inline and **Edit Policy** with **View policy**.
* Conditionally render button-link only if all resources for policies route.
* Replace obsolete policies path!
1. Investigate conditional rendering for `ComplianceByControls` if …
=> ROX-18886: Add conditional RBAC in Configuration Management

central/reports/service/v2/service_impl.go
=> Fill pagination for parsed report history queries

pkg/defaults/policies/files/drop_all_capabilities.json
=> ROX-17979: Minor fixes to default drop all policy wording

Makefile
=> refactor(build): Do not explicitly pass CGO_ENABLED=0 to builds

central/compliance/aggregation/aggregation_test.go
This PR replaces mock implementation with real `standards.Repository`. This will allow testing production code and benchmarks will have more meaning as skipping repository implementation results in false assumptions that there nearly 0 allocations.
CI
=> refactor(test): use real standards.Repository implementation

.github/workflows/style.yaml
This PR checks for trailing spaces in changed code on every PR.
example: https://github.com/stackrox/stackrox/actions/runs/5811320940/job/15754281771?pr=7230
CI (see example)
=> chore(lint): trailing whitespaces

ui/apps/platform/src/Containers/SystemConfig/Details/PrivateConfigDataRetentionDetails.tsx, ui/apps/platform/src/Containers/SystemConfig/Form/SystemConfigForm.tsx, ui/apps/platform/src/types/config.proto.ts
Add vulnerability report history retention to system config
=> ROX-17868: System config vuln report history retention

CHANGELOG.md
See title
~[ ] Investigated and inspected CI test results~
n/a
=> docs(deprecate): Deprecate the CIS Docker v1.2.0 standard

central/reports/scheduler/vuln_report_collections_test.go, central/resourcecollection/datastore/datastore.go, central/resourcecollection/datastore/datastore_bench_postgres_test.go, central/resourcecollection/datastore/datastore_impl.go, central/resourcecollection/datastore/datastore_impl_postgres_test.go, central/resourcecollection/datastore/mocks/datastore.go, central/resourcecollection/service/service_impl.go, central/resourcecollection/service/service_impl_test.go
=> Refactor collection datastore to make its usage in tests easier

central/resourcecollection/service/service_impl.go, central/resourcecollection/service/service_impl_test.go
- ~Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))
Unit
=> Ensure that collections referenced by report configurations cannot be deleted

central/reports/service/v2/convert.go, central/reports/service/v2/convert_test.go, central/reports/service/v2/service_impl_test.go, central/reports/validation/validate.go, generated/api/v2/report_service.pb.go, pkg/fixtures/report_configuration.go, proto/api/v2/report_service.proto
=> [ROX-19129] : Change daysOfWeek to (0-6) range from (1-7) range in report service and add more validations

proto/api/v1/role_service.proto
=> fix(api): Graduate permission sets and access scopes

ui/apps/platform/src/Components/PatternFly/CheckboxSelect.tsx, ui/apps/platform/src/Components/PatternFly/DayPickerDropdown.tsx, ui/apps/platform/src/Components/PatternFly/FormLabelGroup.tsx, ui/apps/platform/src/Components/PatternFly/RepeatScheduleDropdown.tsx, ui/apps/platform/src/Components/SelectSingle/SelectSingle.tsx, ui/apps/platform/src/Containers/VulnMgmt/Reports/VulnMgmtReportForm.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CloneVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CreateVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/EditVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/ReportFormWizardFooter.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/ScheduleDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/DeliveryDestinationsForm.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/NotifierSelection.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.ts, ui/apps/platform/src/services/ReportsService.types.ts
This PR adds validation for VM Reporting 2.0 form fields
https://github.com/stackrox/stackrox/assets/4805485/ebdb4fa9-bf90-4e5d-be77-1aac649c57e3
https://github.com/stackrox/stackrox/assets/4805485/649ed43a-f67f-4a5d-af7e-8246bc76139d
https://github.com/stackrox/stackrox/assets/4805485/13040a2c-4601-4780-8a9f-9fb15a13df1e
https://github.com/stackrox/stackrox/assets/4805485/484dfa2f-32b7-46d3-9dfe-90fd4f0b93e9
ui-e2e failure is a flake; failed to set up infrastructure in one flavor of the test suite ("Error: context deadline exceeded")
=> ROX-17831: Adding formik and validation

ui/apps/platform/src/Containers/SystemConfig/Details/PrivateConfigDataRetentionDetails.tsx, ui/apps/platform/src/Containers/SystemConfig/Form/SystemConfigForm.tsx, ui/apps/platform/src/Containers/SystemConfig/SystemConfig.utils.ts, ui/apps/platform/src/types/config.proto.ts
Add a section for vulnerability reporting download retention to system config
Details:
Edit:
Validation:
=> ROX-17687: Vuln report download retention

central/reports/common/report_formatter.go, central/reports/scheduler/v2/reportgenerator/consts.go
Fixed alignment of column name with actual column 
Test change manually
=> Fix rep column

qa-tests-backend/src/main/groovy/services/PolicyService.groovy, qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy
Per title. This PR creates a test namespace for the tests deployments and creates a clone of the one policy used so that it only apply to that namespace.
Ran a 50x cycle of testParallelBAT with no failures: 
[out17.txt](https://github.com/stackrox/stackrox/files/12361497/out17.txt)
=> ROX-18995: Add ProcessBaselinesTest to the parallel test set

central/sensor/service/pipeline/nodeinventory/pipeline_test.go
This PR adds more unit tests to the node inventory pipeline. 
Tests that combine two pipelines (node & node inventory) will be added in a followup.
=> ROX-13802: RHCOS - testing Central pipelines

ui/apps/platform/src/Components/ExportButton.js, ui/apps/platform/src/Containers/VulnMgmt/Dashboard/VulnMgmtDashboardPage.js, ui/apps/platform/src/Containers/VulnMgmt/Entity/WorkflowEntityPageLayout.js, ui/apps/platform/src/Containers/VulnMgmt/List/WorkflowListPageLayout.js
Changes required for this removal:
1. Remove export button entirely from VM 1.0 dashboard (PDF was only option there)
2. Remove `pdfID` prop from <ExportButton> instance on `WorkflowListPageLayout` and `WorkflowEntityPageLayout`
3. Only render <ExportButton> on those two layouts if entityType is IMAGE_CVE, NODE_CVE, or CLUSTER_CVE. These are the only.
4. Hide export button trigger when there are no export options available. (This fixes a current bug on some VM 1.0 pages.)
- Observe any CI 
- Manual testing
VM 1.0 Dashboard
List pages
CVE type pages: still have Export button with CSV option only now
Single pages
Other sections still have Export button with PDF option
=> ROX-16394: Remove PDF export option from VM 1.0

ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/SyslogIntegrationForm.tsx
=> fix(typo): Fix placeholder typo in syslog form

pkg/env/vuln_reporting.go
=> Enable ROX_VULN_MGMT_REPORTING_ENHANCEMENTS feature flag by default

scripts/lib.sh, tests/e2e/lib.sh
1. Take a backup
2. Get the current config
3. Update the config
4. Restore
5. Check that the config is the same as before the restore
upgrade tests
=> fix(test): Validate restore overwrote previous changes

.github/pull_request_template.md
~~A suggestion here is to shift focus from "testing", that can be misunderstood, to have authors prove they checked how their thing actually works. That can be done through doing manual actions and observing results, creating and running automated tests, or something else. At this point, the suggestion is to promote the activity of validating the change and tackling _automated_ testing can be done later.~~
Let me try differently.
I have a feeling that "testing" is currently undervalued and in the context of PRs misunderstood as "just let CI run".
The problems of "just letting CI run" is that (a) it requires author to create automated tests, (b) it requires test tests actually cover significant parts of the change (ideally all).
The problem with (a) is that I see many PRs that go out …
=> docs: Update testing guideline in PR template

ui/apps/platform/src/Containers/MainPage/Header/MastheadToolbar.tsx, ui/apps/platform/src/hooks/useIsRouteEnabled.ts, ui/apps/platform/src/routePaths.ts
1. GET /v1/search request requires several resources
* Inferred from https://github.com/stackrox/stackrox/blob/master/central/search/service/service_impl.go#L66-L82
* Confirmed from `category` values in `counts` property of response
1. Add resources to `resourceAccessRequirements` in routePaths.ts file.
2. Conditionally render **Search** button/link only if search route is enabled.
3. Add `useIsRouteEnabled` hook.
1. Conditional render links in search results as **Not available** if user role does not have (additional) resource requirements for route.
* For example, risk require DeploymentExtension in addition to Deployment resource.
2. Replace route **paths** with route description **keys** from string enumeration type for better developer experience in a future follow up after necessary …
=> ROX-19121: Add conditional RBAC for global search

central/reports/service/v2/service_impl_test.go, central/reports/validation/validate.go
=> [ROX-19187] : Validate if image types are selected in report config

release/scripts/scan-images-with-roxctl.sh
=> fix(ci): allow roxctl image check to be disabled (4.0)

ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/SyslogIntegrationForm.css, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/SyslogIntegrationForm.tsx, ui/apps/platform/src/types/notifier.proto.ts
For Nakul's addition of an option to fix a backend bug.
This PR is into the branch with the backend changes, to allow for integrated testing
Visual testing for now, since this PR is into the branch with the backend changes, to allow for integrated testing
=> ROX-18572: Add CEF format options to Syslog form

scripts/release-tools/kube-burner-configs/cluster-density/config.yml, scripts/release-tools/kube-burner-configs/cluster-density/configmap.yml, scripts/release-tools/kube-burner-configs/cluster-density/deployment.yml, scripts/release-tools/kube-burner-configs/cluster-density/service.yml, scripts/release-tools/kube-burner-configs/kube-burner-cr.yml, scripts/release-tools/kube-burner-configs/secret_template.yml
=> ROX-17741: long running cluster should include collector kube burner configs (#116)

scanner/decisions/0002-local-scanning-with-scanner-v4.md
=> chore(scanner): anchor links in ADR 2

.github/dependabot.yaml
=> ci(scanner): add dependabot for scanner

qa-tests-backend/src/test/groovy/IntegrationsSplunkViolationsTest.groovy
This has failed for weeks
Straightforward
=> fix(test): Disable Splunk until it is debugged

.github/workflows/create-clusters.yml
=> Jv rox 17741 long running cluster should include collector 2 (#115)

sensor/common/sensor/central_receiver_impl.go, sensor/common/sensor/central_sender_impl.go
This will help with future debugging when sensor frequently disconnects, we can more easily asses what triggered it. 
There's no real validation until we get logs from users cluster. 
What can be validated here is: check the info messages that show up in sensor logs once prow finishes running E2E tests. 
=> ROX-18698: Add more logs when sensor is disconnecting

.github/go-coding-style.md
This PR contributes to the style guide in md format, so you can test it by reading the text.
=> ROX-0000: Go Coding Style - provide example for naked returns

CHANGELOG.md
This change announces a change of behaviour for some product endpoints.
This is a Changelog only modification.
CI should be enough as only the Changelog is impacted. …
=> chore(changelog): Announce endpoint hardening

ui/apps/platform/cypress/integration/clusters/delegatedScanning.test.js, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesTable.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedScanningSettings.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/ToggleDelegatedScanning.tsx, ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx, ui/apps/platform/src/services/DelegatedRegistryConfigService.ts
- Selection among NONE | ALL | SPECIFIC doesn't work well with checkbox + 2 radio buttons
- Default cluster is not required
- None should also be an option for cluster in each table row
- Updated ui-e2e tests
- Manual testing
=> ROX-19193: Update incorrect form behavior for delegated scanning

central/declarativeconfig/watch_handler.go
This PR contains two small fixes, namely:
- [ROX-18630](https://issues.redhat.com/browse/ROX-18630): this rare flake occurred when the test file was created, but nothing was written yet to it. Hence, it lead to an empty byte array being sent to `UpdateDeclarativeConfigContents`. This has been fixed by explicitly ignoring empty files.
- [ROX-18794](https://issues.redhat.com/browse/ROX-18794): this fixes the error logs for trying to read files / directories starting with `..`. Within a secret / config map mount, the `..data` and `..<date>` directories should be ignored. Contrary to the issues description, we cannot skip symlinks since the keys within config maps / secrets that are represented as single files are symlinks themselves.
As a minor change, the existing warning that a directory …
=> ROX-18630, ROX-18794: Improve declarative config watch handler

.github/workflows/update-vulnerabilties.yaml
fix action lint error in updater workflow
=> ROX-19128: fix action lint error

ui/apps/platform/src/Containers/SystemHealth/UsageStatistics/ShowProductUsage.tsx
Improve product usage UI description to explain in detail how it works.
1. CI is sufficient - change is cosmetic
=> fix: Product usage UI description

ui/apps/platform/src/Containers/SystemHealth/UsageStatistics/ProductUsageForm.tsx
Fix wording to correct English phrase.
1. CI is sufficient - change is cosmetic
=> fix: product usage UI Nodes -> Node

scanner/decisions/0003-scanner-image-names.md
=> chore(scanner): scanner image name ADR

.github/workflows/cut-rc.yml
=> Jv pass variables to create clusters (#118)

image/rhel/Dockerfile, image/rhel/static-bin/admission-control, image/rhel/static-bin/compliance, image/rhel/static-bin/kubernetes-sensor, image/rhel/static-bin/sensor-upgrader
These symlinks are needed downstream
Will run this downstream
=> fix(Dockerfile): Add back needed symlinks

image/postgres/Dockerfile, image/rhel/Dockerfile, operator/Dockerfile, qa-tests-backend/test-images/vulns/drools-image/Dockerfile, scanner/image/db/Dockerfile, scanner/image/scanner/Dockerfile
Inspired by https://github.com/stackrox/stackrox/pull/6653
See separate commit descriptions.
- ~~[ ] Unit test and regression tests added~~ - not for this change.
- ~~[ ] Evaluated and added CHANGELOG entry if required~~ - in doubt about this. The changes are to the upstream images, i.e. affect open source users. Not sure how to formulate what's changing for them.
Won't do these as they don't apply:
* Only CI - checking that builds succeed and e2e tests are ok overall.
=> chore: Update UBI Images to 8.latest and *dnf args consistency

.github/workflows/scripts/patch-changelog.sh
Manually port changes from https://github.com/stackrox/test-gh-actions/pull/117
- Just by looking at the code
=> chore(release-automation): Fix changelog PR title

.github/workflows/build-scanner.yml, deploy/common/deploy.sh, scanner/Makefile, scripts/ci/lib.sh
Check the CI logs and check quay.io
=> ROX-16834: Push Scanner images

.github/actions/junit2jira/action.yaml, scripts/ci/lib.sh
v0.0.11 includes a feature to link issues reported in a single run.
CI
responsible for the change after it gets merged which includes reverting, fixing, etc. Make sure you validate the change
ASAP after it gets merged or explain in PR when the validation will be performed.  
Explain here why you skipped testing in case you did so.
Have you created automated tests for your change? Explain here which validation activities you …
=> chore: update junit2jira

ui/apps/platform/src/hooks/useTimeout.test.ts
Prerequisite to upgrade, but wait for the actual upgrade until we have fixed errors from other packages, which result from transitive dependencies.
2. `yarn test` in ui
=> chore(ui): Fix jest no-alias-methods lint errors

central/reports/service/v2/config_separation_test.go, central/reports/service/v2/service_impl.go, central/reports/service/v2/service_impl_test.go
This PR adds a check to prevent deletion of report config if there is a job of the report in preparing/waiting state.
There is another check that prevents editing report is there is a job of the report config requested by owner in waiting/preparing state
It is acceptable to skip testing in cases when CI is …
=> ROX-15972: Fix del rep

.github/CODEOWNERS
Res ipsa loquitur.
Does not apply
Can only be tested after merge, when I PR which touches the ui/ directory is submitted.
=> chore(cleanup): Add ui team as codeowners for ui/ directory

qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
This PR attempts to fix two CI flakes for declarative config tests.
The first one ([ROX-18264](https://issues.redhat.com/browse/ROX-18264)) occurrs when the first test `Check successful creation update and deletion of declarative resources` fails.
Sometimes the previously created declarative configurations aren't cleaned up in time. Hence, the `cleanup` of the test now waits until the declarative configs are deleted and no integration health exists for them.
The second one ([ROX-18263](https://issues.redhat.com/browse/ROX-18263)) occurrs when creating declarative configurations: it seems that the `Role` resource consistently fails being created.
Testing things manually (i.e. running this test multiple times locally) didn't lead to the same behavior.
If there would be an issue _creating_ …
=> ROX-18263, ROX-18264: Fix declarative config E2E tests

central/compliance/handlers/csv.go, central/cve/cluster/csv/handler.go, central/cve/csv/handler.go, central/cve/image/csv/handler.go, central/cve/node/csv/handler.go, central/risk/handlers/timeline/csv.go, pkg/csv/http_writer.go, pkg/csv/utils.go, pkg/csv/writer.go
- Moved code around, existing coverage should suffice
CI run.
=> refactor(csv): One function to write CSV headers.

.github/go-coding-style.md
=> chore(doc): Add concurrency section

roxctl/README.md
This PR is a first step in introducing a few guidelines / common knowledge about structuring commands, writing commands, as well as maintaining commands.
While this currently doesn't cover _everything_, it serves as a starting point for additional things being covered in the future.
~~- [ ] Investigated and inspected CI test results~~
- N/A.
=> chore(roxctl): roxctl guidelines

roxctl/central/whoami/whoami.go, roxctl/central/whoami/whoami_test.go
This PR improves and fixes the `roxctl central whoami` command.
The first issue is that the command currently lists _all_ roles available via the role service API.
This is misleading, since _all_ roles are listed and not the ones associated with the current user. Additionally, in case the user doesn't have `READ Access`, the command will fail.
The second part is cleaning up the output of the command: `\t` has been added to keep consistency with the user ID / user name fields. Additionally, now the roles _associated_ with the user are being printed.
- see the adjusted unit tests.
Additionally, a manual test with a demo instance:
1. Create an API token with the `Continuous Integration` role.
2. Use the API token with roxctl:
``` …
```
=> fix(roxctl): improve whoami command

image/templates/CHANGING_CHARTS.md, tests/e2e/run-e2e-tests.sh
Add Helm breaking changes documentation.
=> feat(doc): Add Helm breaking changes documentation

central/auth/service/service_impl.go, central/auth/service/service_impl_test.go, central/development/service/service_impl.go, central/development/service/service_impl_test.go, central/role/service/service_impl.go, central/role/service/service_impl_test.go, pkg/grpc/authn/basic/identity_test_constructors.go, pkg/grpc/authz/idcheck/authorizer.go, pkg/grpc/authz/or/or.go, qa-tests-backend/src/test/groovy/ReconciliationTest.groovy
In order to reduce the attack surface of the product, additional endpoints require authentication.
It is also acceptable to skip testing for changes that are too taxing to test before merging. In …
=> ROX-19140: require authentication for some public endpoints

.github/workflows/verify-release.yml
Auto-generated PR to update the upstream GHA automation with [3dbb8445abe9d5037e78adb04458d26f69653c33](https://github.com/stackrox/test-gh-actions/commit/3dbb8445abe9d5037e78adb04458d26f69653c33).
=> chore(deps): bump docker/login-action from 2 to 3 (#129)

image/rhel/download.sh
Ensure we log errors when failures happen with curl to investigate what's going on.
PR has been created because of [this CI failure here](https://github.com/stackrox/stackrox/actions/runs/6192903599/job/16813919085#step:22:492).
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown …
=> fix(ci): ensure errors are logged for curl

.github/workflows/scanner-update-NVD-data.yaml
We need to start NVD data fetching workflow
=> fix(scanner): Removed branch restriction

scanner/decisions/0004-scannerv4-read-vulneralbilities.md
A detailed explanation of how NVD CVSS data updating pipeline works
=> ROX-19004: NVD CVSS data updating pipeline ADR

central/reports/scheduler/schedule.go, central/reports/scheduler/v2/reportgenerator/report_gen_impl.go, central/reports/scheduler/v2/reportgenerator/singleton.go, pkg/notifiers/email/email.go, pkg/notifiers/mocks/report_notifier.go, pkg/notifiers/report_notifier.go
=> ROX-19484:Added changes for custom body/subject for report email

scripts/ci/lib.sh
I messed up with notifications. This PR reverts recent changes in slack notifications. I'll enable it once I fix it.
Reverts:
- stackrox/stackrox#7783
- https://github.com/stackrox/stackrox/pull/7732
=> revert: Generate slack message with jira link

ui/apps/platform/README.md
Follow up after doing the steps in #7828
=> chore(ui): Write instructions how to add a route

.github/CODEOWNERS
Long overdue
~[ ] Investigated and inspected CI test results~
N/A
=> chore(codeowners): Combine data shepherds and core workflows teams

operator/main.go
Makes this more similar to the `if` a dozen or so lines above.
Requested in a different PR review.
=> refactor: Flip a condition for readability.

.github/workflows/performance-tests.yml, tests/performance/tests/testK6Integration.js
This PR enhances the output formatting of the K6 performance tests in CI by
- uploading raw data and summarized reports to GCS
- adding a JUnit summary to the job summary
- adding a PR comment with the text summary and links to the test artifacts: https://github.com/stackrox/stackrox/pull/7890/#issuecomment-1735343202. 
The workflow is tied to the PR label "ci-performance-tests". 
Adding that label to a PR or adding commits to a PR that already has this label will trigger the performance tests.
A proof run: https://github.com/stackrox/stackrox/actions/runs/6325227451
=> feat(hackathon): CI: Enhance K6 output formatting

.github/workflows/performance-tests.yml, tests/performance/scripts/opensearch-upload/opensearch-json-import.py, tests/performance/scripts/opensearch-upload/requirements.txt, tests/performance/tests/testK6Integration.js
=> feat(hackathon): Upload performance tests to Opensearch

.github/workflows/performance-tests.yml
=> feat(hackathon): debug performance tags

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/DeleteModal.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/hooks/useDeleteModal.ts
This PR adds the ability to bulk delete reports
Note: Pending tests
https://github.com/stackrox/stackrox/assets/4805485/4baa0c6a-6752-4ad9-9e28-a41525c00b9a
=> ROX-17815: Bulk report deletion

qa-tests-backend/scripts/run-custom-pz.sh
Enables few more QA tests to be executed on P/Z OCP clusters.
=> feat(qa): Add more QA tests to be executed on P/Z

ui/apps/platform/cypress/fixtures/auth/roles.json, ui/apps/platform/cypress/helpers/inviteUsers.js, ui/apps/platform/cypress/integration/accessControl/accessControlAuthProviders.test.js, ui/apps/platform/cypress/integration/userinfo.test.js, ui/apps/platform/src/Containers/MainPage/InviteUsersForm.tsx, ui/apps/platform/src/Containers/MainPage/InviteUsersModal.tsx, ui/apps/platform/src/utils/textUtils.test.js, ui/apps/platform/src/utils/textUtils.ts
This is the second of a series of PRs to add an "Invite users" function to the app.
1. Add an `Emails` textarea, which accepts one or more valid emails, separated by commas (Validation includes splitting the emails into an array, trimming leading and trailing whitespace, and doing basic regex validation on each individual email.)
2. Add a single Select menu, with all the available Auth Providers as options. (If only 1 auth provider is available, it is pre-selected. If more than one Auth Provider is available, and one of them is name "Red Hat SSO" or "OpenShift" then that one is preselected.)
3. Add a single Role menu, with all the available Roles as options, except that that the Admin and None roles are filtered out of the options.
- Show a warning if no auth providers are available
- …
=> ROX-19834: Add Invite Users form

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/EmailTemplatePreview.tsx
=> feat(UI): Add report config name to preview

CHANGELOG.md
Functional changes have been implemented in previous PRs (see stack), this PR just updates the changelog accordingly.
**Previous PRs:**
- https://github.com/stackrox/jenkins-plugin/pull/268
- https://github.com/stackrox/stackrox/pull/7758
- https://github.com/stackrox/stackrox/pull/7738
- https://github.com/stackrox/stackrox/pull/7650
This PR only updates the changelog
N/A - only a changelog update
=> ROX-19685: Update changelog - roxctl OCP internal registry

ui/apps/platform/src/Containers/VulnMgmt/VulnMgmt.constants.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts, ui/apps/platform/src/routePaths.ts
As titled. The UI currently only does a positive check for `watchStatus === 'WATCHED'`, so the case where GraphQL returns `'UNKNOWN'` is already covered (no change in the UI). This only updates the UI types to be accurate with the BE types.
The only place `watchStatus` is queried in plain JS files is [here](https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/VulnMgmt/VulnMgmt.fragments.js#L474), and then used [here](https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/VulnMgmt/List/Images/VulnMgmtListImages.js#L150), also only checking for a value of 'WATCHED'.
Use this space to explain **how you validated** that **your change functions exactly how you expect …
=> feat(ui): Update UI to support 'UNKNOWN' watchstatus

.dockerignore, .tekton/roxctl-pull-request.yaml, .tekton/roxctl-push.yaml, image/roxctl/Dockerfile, pkg/tlscheck/tlscheck.go, status.sh
=> build roxctl rhtap

migrator/postgres/gorm/config.go
#7960 added a subsequent migration to the same table utilizing the convenience of gorm to walk the table.  On the second migration we could not iterate over the rows after the second DDL change.  The resulting error was:
```
ERROR: cached plan must not change result type (SQLSTATE 0A000)
```
Gorm uses PGX underneath and by default PGX uses statement cache.  When we use gorm to walk through the data with `db.Rows()` that is translated to `select * from TABLE;`.  Upon the DDL change when we use `db.Rows()` again, the `select *` is cached.  But the cached statement returns the old type and not the new one.  Thus we get the error.  
To prevent this for gorm migrations, this change turns off statement caching for the migrators gorm connection.  Migrator only.  So any performance hit should be …
=> fix(gorm): turn off gorm migration statement cache

pkg/cryptoutils/crypto_codec.go
=> style: Fix style check in cryptoutils

.github/actions/cache-go-dependencies/action.yaml, pkg/grpc/server.go
Backport to release-4.1 branch.
=> ROX-18291: backport to release-4.1

ui/apps/platform/src/messages/common.ts
See title
responsible for the change after it gets merged which includes reverting, …
=> chore(cleanup): Unused const with stackrox support numbers

scanner/config/config.go
The config file was never closed before. Now it is.
I didn't
=> fix(scanner): config file leak

migrator/migrations/m_190_to_m_191_plop_add_closed_time_column/migration_impl.go, migrator/migrations/m_190_to_m_191_plop_add_closed_time_column/migration_test.go
PLOP migration in PR #7747 broke operator upgrade tests.  See https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-merge-gke-operator-e2e-tests
Migrations are stacked on top of each other.  So simply reverting #7747 would cause numerous issues to inflight migrations so I'm basically skipping it while a fix is being worked. …
=> chore(migration): turn off plop migration

scanner/config/config.go
Add a missing defer for a change introduced in 7d0e7f13b8 fix(scanner): config file leak (#8000)
None.
=> fix(scanner): Add missing defer

image/roxctl/Dockerfile.rhtap
=> use brew registry for builder

qa-tests-backend/README.md
Add the spin cycle runs to the qa-test README as discussed in our demo meeting.
=> chore(docs): how to run qa-test spin cycle

.github/actions/job-preamble/action.yaml, .github/workflows/build.yaml, .github/workflows/style.yaml, .github/workflows/unit-tests.yaml
Backport of https://github.com/stackrox/stackrox/pull/7985 to `release-4.1` branch.
=> chore(backport): ci disk free

.github/actions/cache-go-dependencies/action.yaml
backport of https://github.com/stackrox/stackrox/pull/8036
=> fix(ci): release 4.0/remove problematic go cache hit

central/notifier/service/service.go, central/notifier/service/service_impl.go, central/notifier/service/singleton.go, central/notifiers/cscc/cscc.go, central/notifiers/email/email.go, central/notifiers/jira/jira.go, central/notifiers/slack/slack.go, central/notifiers/syslog/syslog.go, central/notifiers/teams/teams.go, central/notifiers/utils/encryption.go, pkg/cryptoutils/cryptocodec/crypto_codec.go, pkg/cryptoutils/cryptocodec/crypto_codec_test.go, pkg/notifiers/awssh/notifier.go, pkg/notifiers/generic/generic.go, pkg/notifiers/pagerduty/pagerduty.go, pkg/notifiers/splunk/splunk.go, pkg/notifiers/sumologic/sumologic.go, pkg/notifiers/types.go
=> ROX-19880: Secure notifiers on create and update

qa-tests-backend/src/main/groovy/objects/Deployment.groovy, qa-tests-backend/src/test/groovy/BaseSpecification.groovy, qa-tests-backend/src/test/groovy/PolicyConfigurationTest.groovy, qa-tests-backend/src/test/groovy/ProcessVisualizationReplicaTest.groovy, qa-tests-backend/src/test/groovy/ProcessVisualizationTest.groovy, qa-tests-backend/src/test/groovy/RoutesTest.groovy
This PR intends to add codes changes to make QA test multi-arch compliant
=> fix(qa): Multi-arch changes for QA tests

central/reprocessor/reprocessor.go, pkg/env/reprocessing_interval.go
Allow risk reprocessing interval to be configurable to allow for use in 4.2. 4.3 will increase the default interval
It is also acceptable to skip testing for changes that are too taxing to test …
=> fix(perf): Add risk reprocessing interval env var

sensor/common/metrics/init.go
=> feat(metrics): Register metrics in Sensor

qa-tests-backend/Makefile, qa-tests-backend/build.gradle, qa-tests-backend/scripts/run-custom-pz.sh
This PR adds a new target for JUnit tag `PZDebug` which can be leveraged to run any desirable test/tests in CI.
Tested locally and in CI/CD.
=> feat(CI): Add a JUnit tag for ppc64le/s390x to run desirable tests

image/postgres/Dockerfile, image/rhel/Dockerfile, integration-tests/mock-grpc-server/image/Dockerfile, scanner/image/db/Dockerfile, scanner/image/scanner/Dockerfile
This is the more correct location for community contact.
CI
=> ROX-19843: Use https://stackrox.io/ for image maintainer label

CHANGELOG.md
Changelog for upcoming changes related to vulnerability management feature.
n/a
=> chore(docs): Vulnerability Management changelogs

qa-tests-backend/scripts/run-custom-pz.sh, qa-tests-backend/src/test/groovy/ComplianceTest.groovy, qa-tests-backend/src/test/groovy/IntegrationsTest.groovy, qa-tests-backend/src/test/groovy/NetworkSimulator.groovy
Enabled the SlackNotifier test that were previously skipped on P/Z.
=> ROX-16943: Enable tests on P/Z to verify slack notifier functionality

qa-tests-backend/scripts/run-custom-pz.sh, qa-tests-backend/src/test/groovy/BuiltinPoliciesTest.groovy, qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy, qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
This PR intends to fix the issue where `Wget in Image` violations were not getting triggered on P/Z. The new image used is built as per changes in #6012
=> fix(qa): WGET violations issue fixes for P/Z

central/image/datastore/store/common/v2/merge.go, central/node/datastore/store/common/v2/merge.go
If the elements of the array are nil, and we try to marshal them then they will panic. This ensures that we do not panic, but does not solve the underlying nil-ness
Straightforward logic change
=> ROX-20132: Protect against marshal panic by removing nil elements 

central/notifier/processor/singleton.go, central/notifier/service/service_impl.go, central/notifiers/utils/encryption.go
Central startup changes to process notifiers.
Manual testing on a cluster, with env var turned on, and pre created notifiers in the db.
=> ROX-19878: Augment central startup for notifiers

scripts/ci/lib.sh
This PR updates junit2jira and changes the order of jobs to generate slack attachments with junit2jira and then publish on slack.
It turned out that there were two issues with previous implementation:
1. Generated attachments were invalid 
2. curl errors were skipped 
Refs:
- https://github.com/stackrox/stackrox/pull/8093
- https://github.com/stackrox/stackrox/pull/7805
- stackrox/stackrox#7783
- https://github.com/stackrox/stackrox/pull/7732
- https://github.com/stackrox/junit2jira/pull/20
Changed script to run test on PR and added a failing test. Message with jira ID could be found here:
https://redhat-internal.slack.com/archives/CLUNQEEMA/p1697116850386609
In addition to reviewing code here, reviewers **must** also review testing and …
=> ROX-16364: use junit2jira for slack attachments

pkg/administration/events/hints.go
Follow-up from a review by Kerry ([ref here](https://github.com/stackrox/stackrox/pull/7941#pullrequestreview-1674648706))
This should bring the hints for the feature more in-line with existing style guides.
N/A.
=> chore(admin-events): make hints adhere to doc style guides

central/config/service/service.go
Add config validation behind feature flag
=> Add config validation behind feature flag

qa-tests-backend/src/test/groovy/AuditScrubbingTest.groovy, qa-tests-backend/src/test/groovy/BuiltinPoliciesTest.groovy, qa-tests-backend/src/test/groovy/ClientCertAuthTest.groovy, qa-tests-backend/src/test/groovy/ComplianceTest.groovy, qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy, qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy, qa-tests-backend/src/test/groovy/Enforcement.groovy, qa-tests-backend/src/test/groovy/ImageManagementTest.groovy, qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy, qa-tests-backend/src/test/groovy/PolicyConfigurationTest.groovy, qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy, qa-tests-backend/src/test/groovy/ProcessVisualizationReplicaTest.groovy, qa-tests-backend/src/test/groovy/ProcessVisualizationTest.groovy, qa-tests-backend/src/test/groovy/RiskTest.groovy, qa-tests-backend/src/test/groovy/RoutesTest.groovy, qa-tests-backend/src/test/groovy/SACTest.groovy
Adds `PZ` tag to the following tests
```
AuditScrubbingTest
BuiltInPoliciesTest
ClientCertAuthTest
ComplianceTest
DeclarativeConfigTest
DefaultPoliciesTest
Enforcement
ImageManagementTest
NetworkFlowTest
PolicyConfigurationTest
ProcessBaselinesTest
ProcessVisualizationReplicaTest
RiskTest
RoutesTest
SACTest
```
In CI
=> feat(qa): Enable more tests to run on ppc64le/s390x

ui/apps/platform/src/Containers/Compliance/widgets/ComplianceByStandard.js
The dashboard is aggregating based on controls, but the sunburst was aggregating on checks which causes a discrepancy.
This example illustrates why:
Control 1:
Cluster scope and is overall passing - it is a singular check
Control 2:
Deployment Scope and is overall failing
9 Deployments are evaluated and 3 are passing and 6 are failing
Aggregation runs:
By CHECK the math of percent passing is as follows: [1 (control 1 check) +  3 (control 2 checks)] / (10 total checks) = 40% passing
By Control the math of percent passing is as follows: [1 (control 1) / (2 total controls)] = 50% passing
After this fix:
UI check plus went through the output data and was able to determine where the numbers were coming from …
=> ROX-19762: Align sunburst percentages with dashboard percentages

pkg/grpc/endpoints.go, pkg/grpc/server.go
As part of the mitigation for [cve-2023-44487](https://access.redhat.com/security/cve/cve-2023-44487), some projects have decided to reduce MaxConcurrentStreams to 100 (this is the minimum recommended value in the HTTP/2 standard - default is 250).
This PR applies this change to Stackrox gRPC and HTTP2 servers. …
=> ROX-20122: set gRPC & http2 max concurrent streams to 100

go.mod, go.sum
Bump go-grpc to 1.58.3, which fixes [CVE-2023-44487](https://github.com/advisories/GHSA-qppj-fm5r-hxr3) for the gRPC server.
It is also acceptable to skip testing for changes that are too taxing to …
=> ROX-20122: bump go-gprc to 1.58.3

scripts/ci/gcp.sh
Per title. This var was removed from OSCI vault and dependency in https://github.com/stackrox/jenkins-plugin/pull/279
=> chore(ci): remove unused var

central/notifier/processor/singleton.go, central/notifiers/email/email.go, pkg/cryptoutils/cryptocodec/crypto_codec.go, pkg/notifiers/email/email.go, pkg/notifiers/email/email_integration_test.go
=> task: Updates to email notifier for creds

central/convert/storagetov2/vuln_exception_service.go, central/convert/v2tostorage/vuln_exception_service.go, central/main.go, central/vulnerabilityrequest/service/v2/service.go, central/vulnerabilityrequest/service/v2/service_impl.go, central/vulnerabilityrequest/service/v2/service_impl_test.go, central/vulnerabilityrequest/service/v2/singleton.go, pkg/errox/errors.go, pkg/errox/grpc/mapping.go
The service implementation for a few v2 vulnerability exception APIs. The functionality of APIs covered in this PR has not changed. The remaining APIs will be addressed in a follow-up.
Unit test
=> ROX-20246: Implement v2 vuln exception service - part 1

central/image/datastore/store/postgres/store.go, central/node/datastore/store/postgres/store.go
=> ROX-20134: Close transactions

sensor/kubernetes/listener/resources/hash_reconciliation.go, sensor/kubernetes/listener/resources/hash_reconciliation_test.go, sensor/kubernetes/listener/resources/node_store.go, sensor/kubernetes/listener/resources/store_provider.go
This PR adds the implementation for ReconcileDelete for the Node Store.
As this code is currently not called by our production code, I rely on the added unit tests in `hash_reconciliation_test.go`.
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand …
=> ROX-20072: Implement Node Store Reconciliation

qa-tests-backend/src/test/groovy/ImageSignatureVerificationTest.groovy
Swap image to new signed multiarch images
=> ROX-16944: ImageSignatureVerificationTest update to multiarch images

scripts/ci/lib.sh
Periodics does not have a `.refs.base_link` in `$JOB_SPEC`. In theory we could use `.extra_refs` but then we do not have a commit. This PR provides a workaround for this. When base_link is null we will generate link to a commit obtained from git.
It is acceptable to skip testing in cases when CI is sufficient, …
=> fix(test): missing GH link in jira issues

central/notifiers/email/email.go, central/notifiers/email/email_integration_test.go, central/notifiers/generic/generic.go, central/notifiers/jira/jira.go, central/notifiers/jira/jira_fake_test.go, central/notifiers/jira/jira_integration_test.go
Updating jira and generic notifier for creds
CI only
=> feat(be): Updating jira and generic notifier for creds

central/main.go
This was missed in the original renaming of `product/usage` to `administration/usage`.
Produced CSV:
```csv
Timestamp,Nodes,CPU Units
2023-10-18T20:12:20Z,3,12
2023-10-18T21:12:20Z,3,12
2023-10-18T22:12:20Z,3,12
2023-10-18T23:12:20Z,3,12
2023-10-19T00:12:20Z,3,12
2023-10-19T01:12:20Z,3,12
```
=> fix(admin-usage): fix handler path

sensor/kubernetes/listener/resources/hash_reconciliation.go, sensor/kubernetes/listener/resources/hash_reconciliation_test.go, sensor/kubernetes/listener/resources/rbac/namespaced_binding.go, sensor/kubernetes/listener/resources/rbac/store_impl.go, sensor/kubernetes/listener/resources/rbac/store_impl_test.go, sensor/kubernetes/listener/resources/store_provider.go
=> ROX-20289: RBAC store reconcile

central/notifiers/cscc/cscc.go, central/notifiers/cscc/cscc_test.go
=> feat(be): Updating cscc notifier for creds

pkg/registrymirror/mocks/store.go, pkg/registrymirror/store.go
Since Central does not track any of the resources in this store, we do not need to reconcile this store.
This just removed unused code.
performed …
=> ROX-20076: The registry Mirror store does not need to reconcile

central/notifiers/awssh/notifier.go, central/notifiers/email/email.go
=> feat(be): Updates to AWSSecurityHub notifier for creds

central/notifiers/jira/jira.go, central/notifiers/pagerduty/pagerduty.go, central/notifiers/pagerduty/pagerduty_test.go
=> feat(be): Update pagerduty notifier for creds

qa-tests-backend/src/test/groovy/VulnReportingTest.groovy
=> fix(test): Disabled v1 reporting test

qa-tests-backend/src/test/groovy/VulnReportingTest.groovy
=> fix(test): Force ignore v1 reporting test

central/complianceoperator/v2/checkresults/datastore/datastore_impl_test.go, central/complianceoperator/v2/checkresults/store/postgres/gen.go, central/complianceoperator/v2/checkresults/store/postgres/store.go, central/complianceoperator/v2/checkresults/store/postgres/store_test.go, central/complianceoperator/v2/integration/store/postgres/gen.go, central/complianceoperator/v2/integration/store/postgres/store.go, central/complianceoperator/v2/integration/store/postgres/store_test.go, central/complianceoperator/v2/profiles/store/postgres/gen.go, central/complianceoperator/v2/profiles/store/postgres/store.go, central/complianceoperator/v2/profiles/store/postgres/store_test.go, central/complianceoperator/v2/scanconfigurations/store/postgres/gen.go, central/complianceoperator/v2/scanconfigurations/store/postgres/store.go, central/complianceoperator/v2/scanconfigurations/store/postgres/store_test.go, central/complianceoperator/v2/scans/store/postgres/gen.go, central/complianceoperator/v2/scans/store/postgres/store.go, central/complianceoperator/v2/scans/store/postgres/store_test.go
The use of the GetAll function is unsafe because it consumes lots of memory.  Additionally, the only reason these files had it is because wherever I copied the gen.go line from had it.  The function isn't used here and isn't needed.
CI should be plenty sufficient
Use this space to explain **how you validated** that **your change functions exactly how you …
=> chore(gen):  compliance remove get all tag

operator/main.go
Some other projects mainly Kubernetes claim that the [golang fix](https://github.com/golang/net/commit/b225e7ca6dde1ef5a5ae5ce922861bda011cfabd) for CVE-2023-44487 only fixes part of the problem and still leave room for DoS attacks.
https://github.com/kubernetes/kubernetes/pull/121120
https://github.com/kubernetes/kubernetes/issues/121197
https://github.com/golang/go/issues/63417#issuecomment-1758858612
Current remediation advice for (Red Hat) operators is to disable HTTP2 for webhooks and metrics server, if they use TLS.
This PR forces HTTP1.1 for the operator webhook server. Metrics server configuration remains untouched, since we're not using TLS.
- ~~[ ] Determined and documented …
=> fix: force HTTP1.1 for operator webhooks to remidiate CVE-2023-44487

.github/CODEOWNERS
Making maple suggested review for any changes in Kubernetes listeners. 
=> chore(codeowner): add maple to changes in sensor listeners

central/vulnerabilityrequest/manager/requestmgr/manager_impl_cache_test.go, central/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go, pkg/fixtures/vulnerability_request.go
=> chore: simplify and enable more vuln exception tests

ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionManagementPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestsPage.tsx, ui/apps/platform/src/routePaths.ts
This PR adds a route and page for `Exception Management`
=> ROX-19821: Adding exception management page to UI

scripts/release-tools/kube-burner-configs/cluster-density/config.yml, scripts/release-tools/kube-burner-configs/cluster-density/configmap.yml, scripts/release-tools/kube-burner-configs/cluster-density/deployment.yml, scripts/release-tools/kube-burner-configs/cluster-density/service.yml, scripts/release-tools/kube-burner-configs/kube-burner-cr.yml, scripts/release-tools/kube-burner-configs/secret_template.yml
Backport of #7528. This should help us when we run the Create clusters action to create long running clusters. …
=> ROX-17741: long running cluster should include collector kube burner

central/debug/service/diagnostics.go
This PR simplifies code responsible for waiting for all goroutines to finish by combining dedicated goroutine into for loop waiting on channel. 
CI (we have a diagnostic bundle e2e test)
=> refactor: combine gorutine into for loop

ui/packages/ui-components/package.json
Prerequisite to upgrade these devDependencies in apps/platform for React 18.
* See no changes in yarn.lock file.
3. `yarn test` in ui/packages/ui-components
* See `echo test`
=> chore(ui): Delete test-library devDependencies from ui-components

.openshift-ci/get_latest_helm_chart_versions.py, scripts/ci/jobs/gke_version_compatibility_tests.py
Add a support exception to compatibility tests for latest central with sensor 3.74.x. Add functionality to find the latest patch for a given version. 
Checked CI logs and artifacts. The images below show that the support exception version is being tested as expected.
=> ROX-18223: version compatibility support exception handling

central/notifiers/splunk/splunk.go, central/notifiers/splunk/splunk_test.go
=> feat(be): Updates to splunk notifier for creds

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionManagementPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx, ui/apps/platform/src/services/VulnerabilityExceptionService.ts, ui/apps/platform/src/utils/dateUtils.ts
This PR adds the basic table for Pending Approvals. I separated out the table cells into separate components so we may build the tables for the other tabs in a similar fashion (leaving out any table cells or adding any additional table cells, depending on which table we're looking at)
=> ROX-19424: Adding pending approvals table

pkg/grpc/server.go
Fix gRPC tests. Follow-up from #8120.
=> fix(test): fix data race on gRPC stop

.tekton/roxctl-pull-request.yaml, .tekton/roxctl-push.yaml, image/roxctl/rhtap.Dockerfile
```
$ docker run --platform linux/amd64 quay.io/redhat-user-workloads/rh-acs-tenant/acs/roxctl:on-pr-05a03fdf3ff61085f33e0f0a4de7d6abe1768066 version
4.2.x-350-g05a03fdf3f
```
=> ROX-20233: use updated git-clone task with tag fetching

.github/CODEOWNERS
This adds all packages under administration to the Merlin team's code ownership.
The administration packages include:
- usage
- events
N/A
=> chore(CODEOWNERS): add administration to Merlin team.

CHANGELOG.md
=> docs: Deprecate host and platform vulnerability exception management

migrator/migrations/m_192_to_m_193_report_config_migrations/migration_impl.go, migrator/migrations/m_192_to_m_193_report_config_migrations/migration_test.go
=> ci: Fix golangci lint checks

pkg/features/list.go, qa-tests-backend/src/test/groovy/ReconciliationTest.groovy, sensor/common/reconciliation/component.go, sensor/common/sensor/central_communication_impl.go, sensor/debugger/central/communicate_server.go, sensor/tests/connection/connection_test.go
Enable feature for 4.3.
Tested in all previous PRs
=> ROX-20417: Enable client reconciliation feature flag

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.test.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx
Another PR to fix a few more issues and misunderstandings with the expiry
=> fix(ui): Issues with expiry

.openshift-ci/get_latest_helm_chart_versions.py
Fixing syntax error (typo) in compatibility tests.
=> feat(test): fix syntax error in compatibility tests

.github/workflows/cut-rc.yml
Auto-generated PR to update the upstream GHA automation with [43ab5f2bd340495c8a47210800d8e84462dea0c2](https://github.com/stackrox/test-gh-actions/commit/43ab5f2bd340495c8a47210800d8e84462dea0c2).
=> fix(GHA): skip jira check needs to be done on step level (#133)

ui/apps/platform/src/Containers/VulnMgmt/List/Cves/VulnMgmtListCves.js
The UI side of https://github.com/stackrox/stackrox/pull/8128. Hides the legacy global snooze buttons in VM 1.0 when UNIFIED_DEFERRALS is enabled.
Easier to review with "Hide whitespace" enabled.
With the flag enabled.
Toolbar buttons for Image CVEs are not present. Table row actions for CVE snooze are not present:
Buttons and actions *are* still available for Node and Platform CVEs:
With the flag disabled, the buttons and actions are once again available for image CVEs:
=> ROX-20168: Hide image cve snooze UI when 2.0 deferral is enabled

.github/workflows/unit-tests.yaml, Makefile, central/alert/datastore/bench_postgres_test.go, central/compliance/data/repository_bench_test.go, central/compliance/manager/run_bench_test.go, central/pod/datastore/datastore_bench_test.go, pkg/networkgraph/tree/wrapper_bench_test.go, tests/performance/README.md
Smoke test benchmark tests (only 1 iteration) to validate that everything is working. This change will not bring any valuable performance data  just check if tests are working correctly.
Refs:
- https://github.com/jstemmer/go-junit-report/issues/174
https://github.com/stackrox/stackrox/actions/runs/6656653147/job/18089682341?pr=8352#step:8:27
=> fix: run benchmark tests in CI

operator/main.go
Adapts https://github.com/stackrox/stackrox/pull/8279/ to the `release-3.74` branch, which uses `controller-runtime v0.12` instead of `0.16`
Cherry-picks https://github.com/stackrox/stackrox/pull/8394
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change only. …
=> ROX-20391: disable http/2 webhook in operator - CVE-2023-44487

migrator/README.md
Update migrator readme with a gorm note.
provided convince any reviewer or any external reader that you did enough to validate your …
=> chore(readme): migrator readme

central/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go
=> chore: enable reobserve vulnerabilities unit test

pkg/features/list.go, qa-tests-backend/src/test/groovy/ReconciliationTest.groovy, sensor/common/reconciliation/component.go, sensor/common/sensor/central_communication_impl.go, sensor/debugger/central/communicate_server.go, sensor/tests/connection/connection_test.go
=> fix(reconciliation): Revert client reconciliation

migrator/migrations/m_194_to_m_195_vuln_request_global_scope/migration_impl.go
=> chore: correct logging

.github/workflows/unit-tests.yaml
There is a bug in junit report generator that results in marking passing tests as failed
- https://github.com/jstemmer/go-junit-report/issues/174
It is also acceptable to skip testing for changes …
=> chore: skip junit report creation for bench tests

operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/default/manager_auth_proxy_patch.yaml
Cherry-picks https://github.com/stackrox/stackrox/pull/8407 into `release-4.2` …
=> ROX-20542: disable http/2 in operator kube-rbac-proxy

.tekton/roxctl-pull-request.yaml, .tekton/roxctl-push.yaml
My review on top of https://github.com/stackrox/stackrox/pull/7982.
It is best to review this PR by commits because I tried making them self-describing and isolated. Reviewing the entire thing may look too much.
=> ROX-19956: adjust pipeline for roxctl@rhtap

.github/workflows/check-image-vulnerabilities.yml, .github/workflows/create-clusters.yml, .github/workflows/cut-rc.yml, .github/workflows/finish-release.yml, .github/workflows/start-release.yml, .github/workflows/upgrade-test.yml, .github/workflows/variables.yml, .github/workflows/verify-release.yml
Auto-generated PR to update the upstream GHA automation with [b675efb45eb4075324d5f6f1515587b8d89bd4b5](https://github.com/stackrox/test-gh-actions/commit/b675efb45eb4075324d5f6f1515587b8d89bd4b5).
=> ROX-19521: add release prefix to release workflow names (#139)

.github/workflows/finish-release.yml
Auto-generated PR to update the upstream GHA automation with [c839ea882fb53fc44e380d52dd4f9faa36fe8da7](https://github.com/stackrox/test-gh-actions/commit/c839ea882fb53fc44e380d52dd4f9faa36fe8da7).
=> ROX-19864: skip infra demo version bump if not newer (#140)

.github/workflows/start-release.yml
Auto-generated PR to update the upstream GHA automation with [04431e09656edd5b3554f204700e53eb438a2cf8](https://github.com/stackrox/test-gh-actions/commit/04431e09656edd5b3554f204700e53eb438a2cf8).
=> ROX-20503: Create CHANGELOG PR in start-release as roxbot (#141)

central/debug/service/service.go, scale/profiler/pprof.sh, scripts/secured-cluster-diagnostics.sh
To avoid confusion, give the pprof files a better extension.
CI run
=> chore: Replace `.tar.gz.` with `.pb.gz` for pprof files

pkg/images/enricher/enricher_impl.go, pkg/images/enricher/enricher_impl_test.go
Previously, there was a divergence between how the cached, existing image's values were enriched during scans. For delegated scanning, it wouldn't include the merged version of iamge scans, for non-delegated scans it would include them.
This would lead to a difference in behavior based on the scan "method" used. Culprit was the current call of `updateImageFromDatabase` vs `fetchFromDatabase`:
`fetchFromDatabase` retains image names only for `UseImageNamesRefetchCachedValues`, whereas `updateImageFromDatabase` does so for all enrichment options.
- see added unit tests.
performed one does not seem sufficient. As a reviewer, you …
=> fix(enricher): retain image names for delegated scans

CHANGELOG.md
Simple changelog
responsible for the change after it gets merged which includes …
=> fix(changelog): Add changelog entry for Docker deprecation

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionManagementPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.css, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/mockUtils.ts
This PR adds the request details page with the following:
1. Breadcrumbs
2. Header with subtext
3. Overview section with request information
=> ROX-19386: Request details page

deploy/common/deploy.sh
`deploy/common/deploy.sh` should be able to handle the core_bpf collection method correctly. 
The change only impacts how the core_bpf collection method is handled in CI and when running ACS locally.
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code …
=> Jv fix core bpf collection method option

ui/apps/platform/cypress/integration/exceptionConfiguration/ExceptionConfig.helpers.js, ui/apps/platform/cypress/integration/exceptionConfiguration/ExceptionConfig.selectors.js, ui/apps/platform/cypress/integration/exceptionConfiguration/vulnerabilitiesExceptionConfig.test.js, ui/apps/platform/src/Containers/ExceptionConfiguration/VulnerabilitiesConfiguration.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExpiryField.tsx, ui/apps/platform/src/services/ExceptionConfigService.ts
As titled.
Note: we may want to hold off merging this until the API stabilizes, as tests may fail once the "Indefinite" option is added to the API.
CI
=> ROX-19344: Add e2e tests for vuln deferral configuration

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
This PR adds the CVE tables section to the request details page. I'm using fake data for the CVE table for now. Since the request data gives us a `string[]` for the CVEs, we'll need to do an API call to get the data and display it in the table. We can reuse the API fetching logic used in `CVEsTableContainer`:
```
const { error, loading, data, previousData } = useQuery(cveListQuery, {
variables: {
query: getVulnStateScopedQueryString(querySearchFilter, vulnerabilityState),
pagination: {
offset: (page - 1) * perPage,
limit: perPage,
sortOption,
},
},
});
```
But I'll do that in a separate PR
=> ROX-19387: Add CVEs table in the request details page

sensor/tests/helper/helper.go, sensor/tests/resource/pod/pod_test.go
Two tests seem to be flaky here, but they don't happen frequently. This PR aims to fix one and add more logs to the other. 
=> ROX-18569: Fix pod integration tests flake

image/rhel/Dockerfile
In local development, the only thing that most likely changes is either the ui or the binaries. This allows for better caching
CI
=> refactor(dockerfile): Reorganize Dockerfile for better caching

.tekton/central-db-pull-request.yaml, .tekton/central-db-push.yaml
=> ROX-20749: update PR pipeline

central/notifier/service/service_impl.go
- `upgradeNotifierConfig` in `notifier/service/service_impl.go` adds source type key map to the splunk type notifier.
-  So any notifier type specific validations should happen after  `upgradeNotifierConfig` is called on the service. Otherwise, splunk type notifiers will fail validation.
- In PR #8507, extra notifier type specific validations were added to the notifier service to validate credentials before they are cleaned up. Since these validations ran before the call to `upgradeNotifierConfig`, they failed in e2e tests.
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshi …
=> fix(ci): Fix IntegrationsTest on CI

tools/generate-helpers/pg-table-bindings/store.go.tpl
We do not support multiple primary keys in generated stores. This PR removes code responsible for handling this. 
generated files has no changes 
=> fix(pg): remove unused code from store template

.github/dependabot.yaml
This PR will make dependabot to update k8s.io deps together so they all will have the same version number. …
=> chore(deps): dependabot update k8s.io together

pkg/metrics/op_string.go, pkg/metrics/operations.go, pkg/search/postgres/store.go
Adds timing metric for walk functions that was missing
responsible for the change …
=> fix(metrics): Add metric for Walk

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SearchOptionsDropdown.tsx, ui/apps/platform/src/services/VulnerabilityExceptionService.ts
This PR uses real data to display the pending requests' data in the Exception Management section.
https://github.com/stackrox/stackrox/assets/4805485/298bad7b-72d0-4a39-9919-e07734824fe7
https://github.com/stackrox/stackrox/assets/4805485/c4c214cb-32de-49a1-9dea-53d246754e58
=> ROX-20696: Use real data for pending requests

sensor/common/compliance/auditlog_manager_impl.go
Dedupe audit log status info by cluster as these can be backed up when there are a lot of resource alerts being generated
```
sensor_event_duration Action=UNSET_ACTION_RESOURCE Type=AuditLogStatusInfo       (4908173/1571320) 3.124
sensor_event_queue Operation=Add Type=AuditLogStatusInfo                         1571323
sensor_event_queue Operation=Dedupe Type=AuditLogStatusInfo                      3234755
sensor_event_queue Operation=Remove Type=AuditLogStatusInfo                      1571322
``` …
=> fix(perf): Dedupe audit logs for the same cluster

central/scannerdefinitions/handler/handler.go, central/scannerdefinitions/handler/handler_test.go, central/scannerdefinitions/handler/singleton.go
Noticed this was unused, so I removed it.
if it builds, it builds
=> chore(scannerdefinitions): remove unused argument

scanner/Makefile
Merged https://github.com/stackrox/stackrox/pull/8614 without realizing these variables are now unused and may be removed.
CI
=> chore(scanner): remove unused variables

ui/apps/platform/src/hooks/useLocalStorage.test.ts
=> fix(ui): UI unit test fix for semantic merge conflict

sensor/common/networkflow/manager/manager_impl.go
Increment the external flow counter in sensor once per active connection to external source. Currently this counter is incremented for every active host connection with an ext src for each enrichment tick in sensor.
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code …
=> fix(sensor): external flow counter

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
This PR uses real data to display the denied requests' data in the Exception Management section. You should be able to filter and sort the same way described in https://github.com/stackrox/stackrox/pull/8577
=> ROX-20695: Use real data for denied requests

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestForm.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestModal.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/utils.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/PendingExceptionLabelLayout.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
One commit == one fix
1. Some queries in Workload CVEs were missing the exception count filters, leading to a "Pending Update" badge when there was an approved exception but _without_ a requested update.
2. Links from the "Pending exception" badges were updated to go to the correct exception management URL
3. The deferral exception form would be put in an invalid state if it was submitted without selecting an expiry.
1. Repeat the testing steps in https://github.com/stackrox/stackrox/pull/8550. Additionally, approve a deferral and _do not_ request an update on that deferral. Verify that no badge is present for the image or deployment lists on the deferral tab for the deferred CVE. 
2. Request an exception for a CVE, then click the badge …
=> fix(ui): Fix assorted workload CVE bugs

.github/workflows/update-vulnerabilties.yaml, scanner/cmd/updater/main.go, scanner/updater/export.go, scanner/updater/version/RELEASE_VERSION
Transitioning to update data for one supported version at a time
Download from one data source at a time
Enable retrying for timed-out job
https://github.com/stackrox/stackrox/actions/runs/6744987233
https://github.com/stackrox/stackrox/actions/runs/6740135608
https://github.com/stackrox/stackrox/actions/runs/6739894041
https://github.com/stackrox/stackrox/actions/runs/6738818970
https://github.com/stackrox/stackrox/actions/runs/6738174050
=> ROX-20103: Optimizing Memory Consumption in the Vulnerability Workflow

.github/workflows/update-vulnerabilties.yaml
Fix the cron schedule and enable testing branch
=> ROX-20103: Fix cron and add scanner branch for testing

ui/apps/platform/src/Containers/Vulnerabilities/hooks/useInvalidateVulnerabilityQueries.ts
Title
Local `yarn lint` and CI
=> fix(ui): Fix semantic merge conflict for UI lint

.openshift-ci/begin.sh, .openshift-ci/end.sh, scripts/ci/lib.sh
These are initial stubs which will ultimately fulfill the requirements of ROX-20914.
CI is sufficient. These will be called from https://github.com/openshift/release/pull/45729 post merge.
=> feat(CI): add begin/end hooks

.github/workflows/build.yaml
Scan go binaries with govulncheck
- https://go.dev/blog/vuln
- https://github.com/stackrox/stackrox/pull/6345
Output: https://github.com/stackrox/stackrox/actions/runs/6903986369?pr=8653#summary-18784048069
CI
=> fix(ci): scan go binaries

sensor/common/centralclient/client_test.go
Skip failing test on master.
CI
=> ROX-20931: skip failing test

.github/workflows/unit-tests.yaml
By a mistake wrong job was removed. …
=> fix: do not run junit2jira on bench

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/utils.ts
When the "Only <image-name>:<tag>" option is selected for a deferral where the image does not have a "tag", formik validation will fail and prevent the form from being submitted. This is because the `yup.string().required()` definition does not allow for empty strings.
The fix is to relax the validation requirements, and then at the point where the request is formatted ensure that `tag` is a valid string value.
This should resolve the last remaining Workload CVE test flake in CI.
Find an image without a tag, and open the deferral form. Fill out the form and select "Only <image-name>:" as the option. With all form fields completed, the submit button should be enabled:
=> fix(ui): Fix form validation when tag is an empty string

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx
This is a two part fix:
1) Deletes a `useEffect` that I believe was a safety check that was put in when you could still delete a collection that was in use by a VM 2.0 report. This is no longer possible as the backend now prevents it.
2) Unconditionally fetches the details for the selected collection ID when editing. This shows the correct collection name in the dropdown instead of displaying the UUID when the selected collection has not been fetched for the current paginated list.
As a follow up we need to work with UX to determine the best way to handle these types of dropdowns, where the number of displayed items is customer determined and could be a very large quantity.
Create a report, and click "View more" in the collection dropdown …
=> ROX-20941: Fix missing scope when editing vm report

go.mod, go.sum, pkg/compliance/checks/nist800-190/check421/check_test.go, pkg/migrations/migration_version.go, pkg/protoconv/time.go, pkg/registries/docker/metadata_v1.go
We are using docker in couple of places. This brings this huge dependency just for small amount of it's functionality (e.g. atomic file write or image spec definition). This PR removes docker (although it's still imported indirectly) and replaces it with open containers spec or code or removes where it was not needed at all.
CI
=> chore(deps): remove docker dependency

.github/workflows/update_collector_periodic.yaml, .github/workflows/update_scanner_periodic.yaml
=> chore(CI): ROX-20643: update robot for periodics

.github/workflows/build-scanner.yml, scanner/Makefile, scanner/image/db/Dockerfile
See https://github.com/stackrox/stackrox/pull/7504 for CentralDB's related changes.
If it builds, it builds
=> feat(scanner): support Scanner on s390x

pkg/features/list.go
Adds a FF for Prevent Sensor Restarts V3.
N/A
=> ROX-21068: Add FF for v3

.github/CODEOWNERS, .github/workflows/scanner-build.yml, .github/workflows/scanner-mapping-update.yaml, .github/workflows/scanner-nvd-update.yaml, .github/workflows/scanner-vuln-update.yaml
This makes it clearer which jobs are related to Scanner v4
CI I guess?
=> chore(ci): unify scanner ci under same prefix

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js, ui/apps/platform/eslint.config.js, ui/apps/platform/src/Components/NumberedGrid/NumberedGrid.js, ui/apps/platform/src/Components/visuals/Sunburst.js, ui/apps/platform/src/Containers/ConfigManagement/Entity/Secret.js, ui/apps/platform/src/Containers/ConfigManagement/List/Images.js, ui/apps/platform/src/Containers/Policies/Wizard/Step2/PolicyBehaviorForm.tsx, ui/apps/platform/src/Containers/Risk/SecurityContext.js, ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/ClustersHealthCards.tsx, ui/apps/platform/src/Containers/VulnMgmt/List/Components/VulnMgmtListComponents.js, ui/apps/platform/src/Containers/VulnMgmt/List/Cves/VulnMgmtListCves.js, ui/apps/platform/src/Containers/VulnMgmt/List/ImageComponents/VulnMgmtListImageComponents.js, ui/apps/platform/src/Containers/VulnMgmt/List/NodeComponents/VulnMgmtListNodeComponents.js, ui/apps/platform/src/global/initializeAnalytics.js, ui/apps/platform/src/sagas/metadataSagas.js, ui/apps/platform/src/utils/logError.js
We deferred eslint-comments recommended rules to limit the number of changes in #8629
Here is the recommended configuration:
https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/master/lib/configs/recommended.js
Here is documentation for the recommended rules:
* https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/master/docs/rules/disable-enable-pair.md
> eslint-disable directive-comments disable ESLint rules in all lines preceded by the comment. If you forget eslint-enable directive-comment, you may overlook ESLint warnings unintentionally.
* https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/master/docs/rules/no-aggregating-enable.md
> eslint-enable directive-comments can enable rules which are disabled by different eslint-disable …
=> chore(ui): Fix errors and enable eslint-comments recommended rules

Makefile
=> chore(style): limit argument list size for roxvet

.github/workflows/auto-merge.yml, .github/workflows/build.yaml
Switches to rhacs-bot for remaining CI and release workflows. Secrets enabled as necessary.
Will test in stackrox/test-gh-actions.
=> chore(CI): ROX-20643: update github robot II

pkg/registries/docker/metadata_v1.go
Fix for comment on backport: 
- https://github.com/stackrox/stackrox/pull/8755/files/2adc41a3e689208ef713d030b14083c679a48031#r1406556920
It is also acceptable to skip testing for changes that are …
=> fix(docker): use author instead of createdby

ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedDashboard.test.js, ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedScanConfigs.test.js
Adding tests for work done over the past week
Ran the tests locally
=> chore(tests): Add scan config form step 1 tests

pkg/features/list.go
Per the title
Already on by default in CI and ephemeral dev deployments; this change will allow it to "bake" in all dev environments for weeks before release.
Automated e2e tests already exist for this change.
=> ROX-21013: Turn on policy criteria modal feature flag

tests/e2e/lib.sh
Enable the STS cloud credentials feature flag in CI runs.
CI
=> ROX-20783: enable STS cloud credentials feature flag in CI

tools/local-sensor/main.go
If the the FF `SensorReconciliationOnReconnect` is enabled, the fake connection in local-sensor needs to send a `DeduperState` on startup. …
=> fix(local-sensor): Send the DeduperState in local-sensor

.github/workflows/build.yaml, scripts/ci/lib.sh
Docker interactions with quay.io and registry.access.redhat.com can be flaky. Pepper them with 5 retries (with backoff). 
- https://github.com/stackrox/stackrox/actions/runs/7047231619/job/19181738533#step:10:466
- https://github.com/stackrox/stackrox/actions/runs/7047438542/job/19181339078#step:10:9
- https://github.com/stackrox/stackrox/actions/runs/7048193941/job/19184691408
- https://github.com/stackrox/stackrox/actions/runs/7048199495/job/19184707722
...
CI
=> fix(CI): retry docker interactions

qa-tests-backend/src/main/groovy/util/Helpers.groovy, qa-tests-backend/src/test/groovy/RiskTest.groovy
The risk score may change during the test while new entries populated and the priority depends on current deployments in the system. We want to make sure they are equal eventurally.
1. wait for both processes available before test for same deployment
2. retry a few times checking risk.
3. retry a few times for priority
4. add debug information for debugging ROX-17512 further 
Use this space to explain …
=> ROX-17308, ROX-17512: wait for risk and priority in test

go.mod, go.sum, pkg/mocks/github.com/aws/aws-sdk-go/service/securityhub/securityhubiface/mocks/mocks.go
=> chore(update): Update aws-sdk-go

pkg/registries/docker/metadata_v1.go
This PR brings the "old" behaviour so instead of `now()` we will use `0` timestamp.
https://github.com/stackrox/stackrox/pull/8755/files/2adc41a3e689208ef713d030b14083c679a48031#r1408252161
It is …
=> fix(docker): use 0 timestamp instead of now

central/graphql/resolvers/image_cve_core.go
`DistroTuples` graphQL resolver in `ImageCVECore`  redirects to VM 1.0 graphQL resolver for `ImageVulnerabilities`. Now `ImageVulnerabilities` resolver filters out snoozed CVEs when no explicit filter by `CVESuppressed` is provided. When ImageVulnerabilities resolver is called by `DistroTuples`, its intent is to get those details of a single CVE that cannot be obtained via SQF. For example description, link, etc.  So, the auto removal of snoozed CVEs is unintentional here. Hence, we should add an explicit filter with `CVESuppressed == true OR false` when calling `ImageVulnerabilities` from `DistroTuples` resolver.
- ~[ ] Documented user …
=> ROX-20943: Fix missing details for snoozed CVEs in Workload CVEs

pkg/registries/docker/metadata_v1.go
=> fix(docker): use 0 timestamp instead of now 

operator/pkg/central/extensions/reconcile_pvc.go
Add documentation to the PVC extension.
responsible for the change after it gets …
=> chore(docs): add operator pvc extension documentation

central/metrics/init.go
Metrics was created but forgot to be initialized.
=> feat(metrics): Add sensor connected metric

sensor/kubernetes/listener/resources/networkpolicy.go, sensor/kubernetes/listener/resources/service_store.go
After #8823 there were some functions that were no longer used and needed to be removed.
=> fix(style): remove unused functions

central/externalbackups/datastore/telemetry.go, central/externalbackups/plugins/gcs/gcs.go, central/externalbackups/plugins/s3/s3.go, central/externalbackups/plugins/types/types.go, central/main.go, pkg/externalbackups/types.go
Add telemetry for external backup integrations. Follow up to #8873.
=> ROX-20808: add telemetry for external backup integrations

ui/apps/platform/src/Containers/Policies/policies.utils.ts
Related to changes in #8796
Hard to say why TypeScript did not report this with the others
1 .`yarn build` in ui
=> fix(ui): Add type assertion in postFormatImageSigningPolicyGroup

.github/workflows/unit-tests.yaml
This PR configures publishing coverage information to codecov.io
Example report for this branch: 
- https://app.codecov.io/github/stackrox/stackrox/tree/codecov-integration
- https://github.com/stackrox/stackrox/pull/8936#issuecomment-1843324773
Next step will be to configure codecove to post updates on PR or slack about coverage changes and enable code coverage generation for ui and optionally integration tests
Refs: 
- https://github.com/stackrox/stackrox/pull/6539
- https://github.com/stackrox/stackrox/commit/e301f4963f038ff37a1c944cfe01347b21b3b7ec – we used to have coveralls
See example ⬆️  …
=> chore(ci): add codecove integration

go.mod, go.sum
=> chore(deps): bump github.com/go-jose/go-jose/v3 from 3.0.0 to 3.0.1 

ui/Makefile
This PR runs UI tests with coverage on CI and skips one level of directory structure as it is obsolete. 
Example: https://app.codecov.io/github/stackrox/stackrox/tree/collect_coverage_for_ui/ui%2Fapps%2Fplatform%2Fsrc
CI
=> chore(ci): collect coverage for UI unittests

.github/workflows/unit-tests.yaml
Introduced in #8936 change breaks junit-jira integration as junit report is in different location.
Before: https://github.com/stackrox/stackrox/actions/runs/7129295329/attempts/1#summary-19413069203 
After: https://github.com/stackrox/stackrox/actions/runs/7130610243/attempts/1#summary-19417383288
CI
=> fix(ci): junit report for UI tests

generated/api/v2/compliance_integration_service.swagger.json, generated/api/v2/compliance_profile_service.swagger.json, generated/api/v2/compliance_results_service.swagger.json, generated/api/v2/compliance_scan_configuration_service.swagger.json, make/protogen.mk
Show the docs in the v2 drop down
=> fix(docs): Show Compliance V2 API docs

Makefile
This PR fix a few places and allow CGO_ENABLED setting honored in building.
This is needed in m1 building local image
provided convince any reviewer or any external reader that …
=> fix(arm64): Fix CGO_ENABLED setting

pkg/features/list.go
=> fix(ff): Make compliance FF changeable on release builds

scanner/e2etests/testdata/image_tests.json, scanner/e2etests/testdata/image_tests.orig.json
Fix the test in scanning package:
"Name": "jackson-databind",
"VersionFormat": "JavaSourceType",
"Version": "2.9.10.4"
=> fixed e2e test version

qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
=> ROX-19615: Try to increase timeout of Network Flow test

ui/apps/platform/cypress/fixtures/auth/updateMinimumAccessRole.json, ui/apps/platform/src/Containers/MainPage/InviteUsers/InviteUsersModal.tsx, ui/apps/platform/src/sagas/groupSagas.js, ui/apps/platform/src/services/GroupsService.ts, ui/apps/platform/src/types/group.proto.ts
=> ROX-11600: Migrate GroupsService.js to Typescript

codecov.yml
Make check pass if the coverage drop is 1%
responsible for the change after it gets …
=> chore(ci): increases codecov threshold

tests/e2e/lib.sh
For CI purposes, we'll always need to install the Compliance Operator in the cluster before the integration tests run, but locally that might not be the case.
When developers have local clusters they're running integration tests against, they might have CO installed already from a previous integration test run.
This commit makes it easier for contributors to rerun complinace integration tests by detecting if the CO CSV is present, and using it instead of attempting to reinstall it.
Compliance operator integration testing should still install the compliance operator. You can also verify this change manually by running the integration tests locally twice, and observe it doesn't fail because the compliance operator is already installed on the cluster. …
=> ROX-21409: Detect CO installs during integration tests

.openshift-ci/begin.sh, scripts/ci/jobs/gke_perf_scale_tests.py, scripts/ci/jobs/ocp_perf_scale_tests.py
Per title.
Jobs run via `/test`. Clusters are configured appropriately. Nothing is done with them.
=> feat(CI): stubs for perf scale jobs

qa-tests-backend/codenarc-rules.groovy, qa-tests-backend/src/main/groovy/objects/Node.groovy, qa-tests-backend/src/main/groovy/objects/Notifiers.groovy, qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy, qa-tests-backend/src/main/groovy/orchestratormanager/OrchestratorMain.groovy, qa-tests-backend/src/test/groovy/AdmissionControllerNoImageScanTest.groovy, qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy, qa-tests-backend/src/test/groovy/AttemptedAlertsTest.groovy, qa-tests-backend/src/test/groovy/BaseSpecification.groovy, qa-tests-backend/src/test/groovy/ComplianceTest.groovy, qa-tests-backend/src/test/groovy/ImageScanningTest.groovy, qa-tests-backend/src/test/groovy/IntegrationHealthTest.groovy, qa-tests-backend/src/test/groovy/IntegrationsSplunkViolationsTest.groovy, qa-tests-backend/src/test/groovy/IntegrationsTest.groovy, qa-tests-backend/src/test/groovy/K8sEventDetectionTest.groovy, qa-tests-backend/src/test/groovy/K8sRbacTest.groovy, qa-tests-backend/src/test/groovy/ProcessVisualizationTest.groovy, qa-tests-backend/src/test/groovy/ReconciliationTest.groovy
This PR enables useful codenarc rules. This allow us to keep more healthy code as catching NPE or having an empty method is a code smell. Also preventing nested loops should make our code more readable as in many places that were fixed in this PR nested loop could be replaced with one of groovy collection operator such as `find`, `any`, `every`.
CI
=> chore(qa): enable codenarc rules

ui/apps/platform/src/Containers/ComplianceEnhanced/ScanConfigs/Table/ScanConfigsTablePage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ScanConfigs/Wizard/ReviewConfig.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ScanConfigs/Wizard/ScanConfigWizardFooter.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ScanConfigs/Wizard/ScanConfigWizardForm.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ScanConfigs/compliance.scanConfigs.utils.ts, ui/apps/platform/src/services/ComplianceEnhancedService.ts
This code introduces the review and submission step of the compliance configuration wizard. Key points:
1. Purpose of the Step: Reviewing and submitting compliance configurations.
2. Formik: Due to the structure of the form in the configuration step, the scan schedule values are stored in a format in Formik that differs from the format required in the submission payload.
3. Utility File (`compliance.scanConfigs.utils.ts`): Used to bridge the format discrepancy. The file, as of now, is responsible for:
- Converting Formik values to a scan configuration payload: It transforms the values managed by Formik into the format expected by the api.
- Formatting a `Schedule` into a readable string: This function is used in both the `ReviewConfig` step and on the `ScanConfigsTablePage`.
If any of …
=> ROX-20666: Compliance config wizard review step

go.mod
Remove defunct comment and move indirect dependencies into the proper section.
Nah
=> chore(deps): minor cleanup

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/deploymentSingle.test.js, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/SummaryCards/BySeveritySummaryCard.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
As titled.
Tests focus on items that:
- integrate multiple components on the page
- cannot easily be tested with component tests alone
- are independent from the data, or lack thereof, returned via the API
CI
=> ROX-17144: Add integration tests for Workload CVE deploy page

pkg/cloudproviders/gcp/utils/util.go
Add back scc proxy that got lost in #9002.
CI
=> ROX-21188: add back proxy for scc

pkg/search/postgres/store_test.go
This PR is there to ensure that we have base smoke tests for all functions of the generic postgres store.
Added unit tests
=> test: Explicitly test the generic store

image/templates/helm/stackrox-secured-cluster/templates/collector-scc.yaml
Add label auto-upgrade label to StackRox SCCs to be included in the upgrader.
This fixes a flake in the nightly CI builds.
Discussed in https://redhat-internal.slack.com/archives/C04QLSHAGN4/p1702458026258789
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment …
=> ROX-21365: Fix upgrade test and add auto-upgrade labels to SCCs

ui/apps/platform/src/Containers/VulnMgmt/List/Cves/VulnMgmtListCves.js
=> fix(ui): Fix semantic merge conflict with no-undef-init lint rule

ui/apps/platform/src/Containers/Clusters/clustersTableColumnDescriptors.js
As title suggests. I didn't bother adding tests because this table needs to be converted to PF at some point anyways/revamped.
=> ROX-21376: Adding no sort option to columns in cluster table

.github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-pr-vuln-update.yaml, .github/workflows/scanner-release-vuln-update.yaml
Upload vulnerabilities based on the master branch as well as PR which set the `pr-update-scanner-vulns` label for development purposes.
I set the PR label, and vulns are uploaded
performed testing and …
=> chore(scanner): create dev vuln updater

scripts/ci/jobs/ocp_scanner_v4_tests.py
Just adding test stub for scanner v4 tests on OCP.
Will be filled with actual test later, but allows integrating new test step into
openshift/release repository right now without CI failures.
It is …
=> ROX-21562: Add test stub for scanner v4 tests on OCP

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.helpers.js, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.selectors.js, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/pendingRequestsTable.test.js, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
This is an initial test for the Pending Requests flow in Exception Management. You can check the subtasks for this Jira to see all the tests we will be adding https://issues.redhat.com/browse/ROX-20946.
=> test(ui): Adding table related tests for pending requests flow

scanner/cmd/scannerctl/main.go
When testing, sometimes we only care about the index report. This adds `--index-only` to `scannerctl` so we can just test the indexing step without the matcher.
Run scanner and then use `scannerctl scan --index-only <image>` …
=> chore(scanner): add --index-only flag to scannerctl scan

scripts/ci/metrics.sh
Per title
verified with:
```
bq query --use_legacy_sql=false  'SELECT
COUNT(*) AS `#`,
IF(LENGTH(Classname) > 20, CONCAT(RPAD(Classname, 20), "..."), Classname) AS `Suite`,
IF(LENGTH(Name) > 40, CONCAT(RPAD(Name, 40), "..."), Name) AS `Case`
FROM
`acs-san-stackroxci.ci_metrics.stackrox_tests__extended_view`
WHERE
CONTAINS_SUBSTR(ShortName, "qa")
AND Status = "failed"
AND NOT IsPullRequest
AND CONTAINS_SUBSTR(JobName, "master")
AND NOT CONTAINS_SUBSTR(JobName, "ibmcloudz")
AND NOT CONTAINS_SUBSTR(JobName, "powervs")
AND DATE(Timestamp) >= DATE_SUB(DATE_TRUNC(CURRENT_DATE(), WEEK(MONDAY)), INTERVAL 1 WEEK)
GROUP BY
Classname,
Name
ORDER BY
COUNT(*) DESC
LIMIT
10'
W0103 15:47:29.839733 140432069846848 bigquery_client.py:731] There is no apilog flag so non-critical logging is disabled. …
```
=> fix(CI): exclude PZ from weekly report

central/notifiers/awssh/notifier.go, central/notifiers/email/email.go, central/notifiers/generic/generic.go, central/notifiers/jira/jira.go, central/notifiers/pagerduty/pagerduty.go, central/notifiers/splunk/splunk.go
=> ROX-21370: Remove the check for empty creds in notifiers

.github/workflows/scanner-nvd-update.yaml, .github/workflows/scripts/scanner-update-nvd.py
We need to return when the start date is future dates, otherwise NVD throws errors
=> Fix start date is future dates error

image/templates/helm/shared/config-templates/scanner-v4/indexer-config.yaml.tpl, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml
Hi! Here is how you could include a conditional for central-services / secured-cluster-services in the config.
=> Conditional for indexer config

pkg/telemetry/phonehome/gatherer.go, pkg/telemetry/phonehome/gatherer_test.go
Periodic telemetry gatherer to issue a Heartbeat event in case there were no changes in properties. Otherwise keep issuing the Updated Identity event.
CI, unit tests.
Event seen on Segment:
```json
{
"anonymousId": "29313a3b-1d24-4779-97f6-d9252d96e9c0",
"context": {
"device": {
"id": "29313a3b-1d24-4779-97f6-d9252d96e9c0",
"type": "Central Server"
},
"groups": {
"Tenant": [
"29313a3b-1d24-4779-97f6-d9252d96e9c0"
]
},
"library": {
}
},
"event": "Central Heartbeat",
"messageId": "0539e939-90f3-4459-85b3-ae4cb1e075a1",
"originalTimestamp": "2024-01-04T12:01:29.359251753Z",
"receivedAt": "2024-01-04T12:11:29.509Z",
"sentAt": "2024-01-04T12:11:29.326Z",
"timestamp": …
```
=> ROX-21573: Telemetry heartbeat event

qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
The test flakes a lot and is not trivial to do any quick fixing.
As in the code
- Check CI that the test is skipped
=> ROX-19615: Disable "Verify connections from external sources"

ui/apps/platform/eslint.config.js, ui/apps/platform/src/Containers/Collections/RuleSelector/RuleSelector.cy.jsx, ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicySeverity.cy.jsx
As titled.
local `yarn lint`
CI
=> chore(ui): Enable eslint for cypress component tests

scanner/updater/rhel/fetch_test.go, scanner/updater/rhel/parse_test.go, scanner/updater/rhel/rhel.go, scanner/updater/rhel/updaterset.go
Noticed these updated when I ran `go fmt ./scanner/...`
CI
=> chore(scanner): fix style in RHEL updater

go.mod, go.sum
This will remove a ton of error logs about invalid values in baggage
no
=> chore(deps): Bump zlog to 1.1.8

image/templates/helm/stackrox-central/values.yaml.htpl
=> fix(docs): [99papercuts] Fix typo in sentence

image/templates/helm/stackrox-secured-cluster/internal/defaults/50-images.yaml.htpl
Without explicitly rendering these values as YAML strings, it is easily possible to make the Helm chart rendering fail due to invalid YAMLs:
Use the following setting:
```
image:
main:
tag: ""
```
And the `helm install` invocation will fail with:
```
Error: INSTALLATION FAILED: execution error at (stackrox-secured-cluster-services/templates/upgrader-serviceaccount.yaml:1:4): 
FATAL ERROR:
Section 7 in defaults file internal/defaults/50-images.yaml contains invalid YAML
helm.go:84: [debug] execution error at (stackrox-secured-cluster-services/templates/upgrader-serviceaccount.yaml:1:4): 
FATAL ERROR:
Section 7 in defaults file internal/defaults/50-images.yaml contains invalid YAML
INSTALLATION FAILED
main.newInstallCmd.func2
helm.sh/helm/v3/cmd/helm/install.go:154 …
```
=> chore(helm-charts): Quote Image refs to make rendering less fragile

govulncheck-allowlist.json
Extend the govulncheck exception …
=> fix(test): Extend govulncheck expiration

operator/hack/common.sh
=> ROX-20049: Bump retry subscription

scanner/image/db/download.sh
Bump the version of postgres used in v4 scanner to version 15 for s390x only (p & x already on version 15).  Successful local build on s390x.
=> chore(scanner): use postgres 15 for s390x

operator/hack/build-index-image.sh, operator/hack/get-github-release.sh
ROX-15885: Add retry to get-github-release calls
- CI
- Local build
=> ROX-15885: Add retry to get-github-release calls

sensor/kubernetes/eventpipeline/resolver/resolver_impl.go, sensor/kubernetes/listener/resources/endpoints.go
Remove unused code.
- Ci should be happy.
=> chore(cleanup): Remove unused code in the endpointManager

central/imageintegration/datastore/singleton.go, central/imageintegration/datastore/singleton_test.go, central/risk/manager/manager.go, central/risk/manager/manager_test.go, deploy/common/k8sbased.sh, image/templates/helm/stackrox-central/.helmtplignore.htpl, image/templates/helm/stackrox-central/internal/defaults.yaml.htpl, image/templates/helm/stackrox-central/internal/expandables.yaml.htpl, image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl, image/templates/helm/stackrox-central/templates/NOTES.txt.htpl, image/templates/helm/stackrox-central/templates/_init.tpl.htpl, image/templates/helm/stackrox-secured-cluster/.helmtplignore.htpl, image/templates/helm/stackrox-secured-cluster/internal/defaults/50-images.yaml.htpl, image/templates/helm/stackrox-secured-cluster/internal/defaults/70-scanner-v4.yaml.htpl, image/templates/helm/stackrox-secured-cluster/internal/expandables.yaml.htpl, image/templates/helm/stackrox-secured-cluster/templates/NOTES.txt.htpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl, pkg/features/list.go, pkg/helm/charts/tests/centralservices/helmtest_test.go, pkg/scanners/factory.go, sensor/common/scannerclient/singleton.go, tests/e2e/lib.sh, tests/e2e/run-scanner-v4.bats
=> ROX-21624: Rename Scanner v4 Feature Flags

Makefile
=> chore(Makefile): Fix Makefile

central/notifiers/email/email.go, central/notifiers/generic/generic.go
Manually tested using unauthenticated email notifier …
=> ROX-21370: Skip decrypting creds in unauthenticated notifiers (part 2)

central/notifiers/awssh/notifier.go, central/notifiers/email/email.go, central/notifiers/generic/generic.go, central/notifiers/jira/jira.go, central/notifiers/pagerduty/pagerduty.go, central/notifiers/splunk/splunk.go
(cherry picked from commit a47ef92125135ebb7741f085e5b82a1388e4d098) 
This is PR #9204 after resolving the merge conflicts (automated cherry-picking was impossible)
=> ROX-21370: Remove the check for empty creds in notifiers (#9204)

central/main.go, pkg/grpc/authz/idcheck/id_check.go, pkg/grpc/authz/or/or.go
=> fix(scanner): allow scanner v4 access to scannerdefinitions endpoint

operator/Dockerfile
Use `ubi8-micro:latest` as base image for the 3.74 branch instead of `8.7` which is not maintained anymore and has vulns. Downstream is also using `latest`.
It is also acceptable to skip testing for …
=> Update stackrox-operator base image for 3.74 releases

.github/dependabot.yaml
Actions like `upload/download` needs to be updated together. This PR will group updates in a single PR.
Refs:
- https://github.com/stackrox/stackrox/pull/9176
It is also acceptable to skip testing …
=> fix(dependabot): group actions update

operator/pkg/central/extensions/reconcile_tls.go, operator/pkg/central/extensions/reconcile_tls_test.go, operator/pkg/common/extensions/reconcile_scanner_v4_db_password.go
Fixing the build on master branch after merge of #8787:
https://github.com/stackrox/stackrox/actions/runs/7501998836/job/20423769992
It is also acceptable to skip testing for changes that are too …
=> fix: conflicting merge for scanner v4 secrets in operator

pkg/search/postgres/store_cache.go
fix(panic): Lock store cache on read in Delete and DeleteMany
Will run with race condition
=> fix(panic): Lock store cache on read in Delete and DeleteMany

pkg/registries/ecr/transport.go, pkg/registries/google/transport.go
This is a performance improvement for the "read path" - i.e. when the token is valid and simply read and applied in the transport. We want this to happen concurrently without multiple requests blocking each other. What we pay is that we may refresh the token multiple times, and that we cannot guarantee that the token is the same when it is checked and when it is used (TOC-TOU).
tested on test cluster
=> ROX-20788: optimize transport for concurrent reads

ui/apps/platform/src/constants/accessControl.ts
`WorkflowAdministration` replaces `Policy` resource - that should be reflected in minimum permission set.
1. Manual test TBD
=> ROX-21025: Update minimum permission set recommendation

image/templates/common/port-forward.sh, scale/dev/port-forward.sh
First part of the larger PR https://github.com/stackrox/stackrox/pull/9314.
In an unrelated PR these scripts should be merged as they overlap almost completely.
It is also acceptable to skip testing …
=> ROX-21668: Custom namespaces in port-forward scripts

central/scannerdefinitions/handler/handler.go, central/scannerdefinitions/handler/handler_test.go, central/scannerdefinitions/handler/updater_test.go, image/templates/helm/shared/config-templates/scanner-v4/indexer-config.yaml.tpl
Central must update compressed NVD data bundle and serve the bundle to the new Scanner
curl --insecure -u admin:{PWD} https://localhost:8000/api/extensions/scannerdefinitions?file=cvss > data.tar.gz
curl --insecure -u {PWD} https://localhost:8000/api/extensions/scannerdefinitions?file=name2cpe > name2cpe.json
curl --insecure -u admin:{PWD} https://localhost:8000/api/extensions/scannerdefinitions?file=repo2cpe > repo2cpe.json
=> ROX-20805: CVSS API in Central

ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ClairIntegrationForm.tsx
see title
responsible for the change after it gets merged which includes reverting, …
=> fix: Extend the CoreOS Clair v2 integration deprecation date

central/localscanner/certificates.go, central/localscanner/certificates_test.go
=> feat(scanv4-certs): Implement Cert Issuing for local Scanner v4

tests/e2e/lib.sh
Before this change the following chunk of messages was several multiple times, depending on the specific test:
```
out: error: the server doesn't have a resource type "psp"
out: error: the server doesn't have a resource type "psp"
out: error: the server doesn't have a resource type "SecurityContextConstraints
out: Error from server (NotFound): error when deleting "scripts/ci/psp/psp.yaml": clusterroles.rbac.authorization.k8s.io "stackrox-default-psp" not found
out: Error from server (NotFound): error when deleting "scripts/ci/psp/psp.yaml": rolebindings.rbac.authorization.k8s.io "stackrox-default-psp" not found
out: resource mapping not found for name: "stackrox-default" namespace: "" from "scripts/ci/psp/psp.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
out: …
```
=> chore(ci): Prevent noisy error messages during resource teardown

operator/apis/platform/v1alpha1/securedcluster_types.go, operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml, operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml, operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
The difference is subtle, but "conversion" sounds more generic rather than internal-looking "translation".
Docs change only.
=> ROX-18375: Improve ForceCollection docs

.github/workflows/unit-tests.yaml, scripts/ci/bats/lib_get_repo_full_name.bats, scripts/ci/bats/lib_is_in_PR_context.bats, scripts/ci/bats/lib_pr_has_label.bats, scripts/ci/logcheck/check-restart-logs_test.bats, scripts/ci/store-artifacts.bats
Run shell tests on every commit. …
=> fix(ci): run shell tests in CI

pkg/clientconn/client.go, pkg/grpc/server.go, sensor/common/centralclient/grpc_connection.go
Bring in the changes from here https://github.com/stackrox/stackrox/pull/7930#issuecomment-1896434425
this increases the maximum size of gRPC messages that can be received.
It is also acceptable to …
=> Jv set grpc max size

deploy/common/deploy.sh, deploy/common/k8sbased.sh, scripts/ci/cleanup-deployment.sh, scripts/ci/sensor-wait.sh, scripts/k8s/get-lb-ip.sh, scripts/k8s/kill-pod.sh, scripts/style/shellcheck_skip.txt
This is the third part of the larger PR https://github.com/stackrox/stackrox/pull/9314.
Context can be found over there.
This PR contains the changes to our CI scripts, making the namespace parameterizable.
I am waiting for CI.
The commit:
```
commit 5f85cd8de347d96a46b0d8971e70fc54bfb1f2dd
Author: Moritz Clasmeier <mclasmeier@redhat.com>
Date:   Thu Jan 18 21:28:04 2024 +0100
Addendum to last PR: renaming variables namespace -> central_namespace, as discussed during PR review
```
should probably be reviewed separately, as this is not about extending the CI scripts, it is -- as the commit message says -- an addendum to the last PR which I owe to @tommartensen. :-)
=> ROX-21668: Parameterizable namespace in CI scripts

go.mod, go.sum, roxctl/netpol/connectivity/map/cta.go, roxctl/netpol/generate/generate.go, roxctl/netpol/generate/generate_test.go
=> ROX-20271: Upgrade cluster-topology-analyzer to v2

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/ClustersCoverageTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Components/CoverageTableViewToggleGroup.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/CoveragesPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/compliance.coverage.utils.ts, ui/apps/platform/src/Containers/ComplianceEnhanced/MockData/complianceResultsServiceMocks.js, ui/apps/platform/src/Containers/ComplianceEnhanced/Status/Dashboard/ScanResultsOverviewTable.tsx, ui/apps/platform/src/css/trumps.css, ui/apps/platform/src/services/ComplianceEnhancedService.ts
This creates the results page for viewing cluster compliance.
* Operator status and build date are not included in the api response as of now, but we plan on getting that info for MVP
Currently we have only tested one cluster
=> ROX-18119: Create coverage cluster results

central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl.go
Had a comment that we squashed an error that could prove to be valuable.  Simply addressing that here.
provided convince any reviewer …
=> chore(unsquash):  compliance wrap error

scanner/indexer/indexer.go, scanner/indexer/indexer_test.go, scanner/matcher/matcher.go
=> chore(scanner): clean resources when done or upon error

pkg/telemetry/phonehome/doc.go
=> docs: a note with a Confluence link in `phonehome/go.doc`

image/templates/helm/stackrox-central/templates/NOTES.txt.htpl, image/templates/helm/stackrox-secured-cluster/templates/NOTES.txt.htpl
Converging on Scanner V4. I prefer v4, but I think I've noticed other people prefer V4. Honestly not a big deal as long as it's consistent
lolno
=> chore(scanner): consistent naming scheme in Helm notes

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.helpers.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approveRequestFlow.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/denyRequestFlow.test.ts
This PR adds a test for the approve request workflow
1. `should be able to approve a request if approval permissions are granted`
=> test(ui): Adding tests for the approve request workflow

scanner/indexer/indexer.go
```yaml
http_listen_addr: 127.0.0.1:9443
grpc_listen_addr: 127.0.0.1:8443
indexer:
enable: true
database:
conn_string: "host=/var/run/postgresql"
password_file: ""
get_layer_timeout: 1m
repository_to_cpe_file: "repository-to-cpe.json"
name_to_repos_file: "container-name-repos-map.json"
repository_to_cpe_url: "http://localhost:8000/repository-to-cpe.json"
name_to_repos_url: "http://localhost:8000/container-name-repos-map.json"
matcher:
enable: false
database:
conn_string: "host=/var/run/postgresql"
password_file: ""
mtls:
certs_dir: "certs/scanner-v4"
log_level: debug
```
```sh
⮩ python -m http.server                                                  [~/wt/github.com/stackrox/stackrox/health/scanner]
Serving HTTP on 0.0.0.0 port 8000 …
```
=> chore(scanner): Improve indexer config readability

tests/e2e/lib.sh, tests/e2e/run-scanner-v4.bats
While working on the multi-namespace tests for Scanner V4 I had to fix a couple of issues along the way. This is the second chunk, which contains some improvements for the resource teardown. In particular:
1. `validatingwebhookconfigurations` are also deleted
2. global and namespaced resources are deleted separately.
It is acceptable to assume trust and keep this section light, e.g. as a bullet-point …
=> test(scanv4): Slice 1: (Prefactoring) Teardown improvements

govulncheck-allowlist.json
=> fix(exception): Allow another month for govulncheck

tests/e2e/run-scanner-v4.bats
While working on the multi-namespace tests for Scanner V4 I had to fix a couple of issues along the way. This is the third slice, which contains support within the scanner v4 installation tests for patching down deployed resources. This is important, because deploying the complete stack including scanner V2 & V4 in two separate namespaces plus all other components requires a lot of resources. In the worst case workloads cannot be scheduled because they don't fit on the nodes in the best case we are just waiting a lot of computing power just for testing installation scenarios.
Feel free to attach JSON snippets, curl …
=> test(scan4): Slice 2: (Prefactoring) Support patching down resources

.github/workflows/scanner-build.yaml
=> ROX-21746: build arm64 Scanner v4 images

central/imageintegration/datastore/telemetry.go, central/imageintegration/store/defaults.go, central/main.go, pkg/registries/artifactory/artifactory.go, pkg/registries/artifactregistry/registry.go, pkg/registries/azure/azure.go, pkg/registries/docker/docker.go, pkg/registries/ecr/ecr.go, pkg/registries/google/google.go, pkg/registries/ibm/ibm.go, pkg/registries/nexus/nexus.go, pkg/registries/nexus/nexus_integration_test.go, pkg/registries/quay/quay.go, pkg/registries/rhel/rhel.go, pkg/registries/types/types.go, sensor/common/registry/registry_store.go, sensor/common/registry/registry_store_test.go, sensor/common/scan/scan.go, sensor/kubernetes/listener/resources/deployments.go, sensor/kubernetes/listener/resources/secrets.go
Add telemetry for image integrations:
* Total count
* Count by integration type
* Count by STS enabled integrations
I also refactored the image integration names by introducing constants for all registry names.
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment …
=> ROX-20808: add telemetry for image registries

image/templates/helm/shared/templates/02-scanner-v4-02-db-password-secret.yaml
See https://github.com/stackrox/stackrox/pull/7910, it's the same issue.
Manual testing with old Helm version (3.8.0).
We might consider adding tests using an old Helm version, but this is not part of this quick fix PR.
=> fix(scanv4): Fix templating error with older Helm versions

scripts/ci/get-slack-user-id.sh
=> chore: Update github user name for mclasmeier

image/templates/helm/shared/templates/02-scanner-v4-05-indexer-network-policy.yaml, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml
=> chore(scanner): limit Central and Matcher ingress to CentralServices

image/templates/helm/stackrox-secured-cluster/feature-flag-values.yaml.htpl
See diff.
responsible for the change after it gets merged which includes reverting, …
=> fix(scanv4): Remove dup feature flag in secured-cluster chart

ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaForm.tsx
As requested by @boazmichaely.
=> ROX-22033: Requested text change for policy criteria

pkg/search/postgres/store_cache.go
Fixes a bug, these functions will be tested in a follow up PR
Tested in follow up
=> fix(bug): Pass query to WalkByQuery in store cache

image/templates/helm/stackrox-central/internal/defaults.yaml.htpl, operator/tests/common/central-cr.yaml
Apparently we have many CI failures related to scanner-v4-matcher OOMing since we've enabled it by default.
https://issues.redhat.com/browse/ROX-22015
This is an attempt to fix this by setting higher default for scanner-v4-matcher memory.
It is acceptable to skip testing in cases when CI is sufficient, or it's a …
=> fix: increase default mem for scanner-v4-matcher to fix CI

image/templates/helm/stackrox-central/internal/defaults.yaml.htpl, image/templates/helm/stackrox-secured-cluster/internal/defaults/70-scanner-v4.yaml.htpl
Based on some scale testing, these are the new resource requests/limits which are required for Scanner v4.
TODO
=> ROX-21332: update Scanner v4 resources

image/templates/helm/stackrox-secured-cluster/internal/defaults/70-scanner-v4.yaml.htpl, operator/tests/common/central-cr.yaml
During manual testing I discovered a bug that the PVC for a local scanner V4 is only created on an initial installation with scannerV4 enabled, but not when enabling scanner V4 afterwards. This was true for the helm and the operator implementation.
Also bump matcher resources for scannerV4 central-cr.yaml defaults, because I saw some OOMs during testing.
It is acceptable to assume trust and keep this …
=> ROX-19058: SC helm also create scannerV4 PVC on upgrades

operator/tests/securedcluster/sc-basic/80-errors-openshift.yaml, operator/tests/upgrade/upgrade/90-errors-securedcluster-openshift.yaml
=> test(operator): add a missed file

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.helpers.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/general.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
This PR fixes the browser title when navigating the exception management sections
=> ROX-21476: Fix title on browser tab for exception management

deploy/common/k8sbased.sh
In the `launch_central` function in `k8sbased.sh` we try to apply manifests for Scanner V4 unconditionally. But it is not guaranteed that these manifests exist in a deployment bundle in all environments. For example, when an old roxctl (which does not have Scanner V4 support built in) is used to generate a central deployment bundle, no Scanner V4 manifests are contained in that bundle.
Therefore, what this PR does is adding an existence check for Scanner V4 manifests before trying to apply them.
@tommartensen I have assigned this to you, because I am (slightly) modifying `k8sbased.sh`. But in case you don't have the resources ATM, please ignore. Thank you.
Use this space to explain **how you validated** that **your …
=> fix(scanv4): Check if bundle contains Scanner V4 manifests

central/image/datastore/fixable_test.go
Add a unit test that tests out a few fixable query scenario. This establishes that some fixable queries fail on postgres datastore.
=> chore(test): Test some fixable query scenarios

central/notifier/processor/singleton.go, central/notifiers/utils/encryption.go, central/notifiers/utils/encryption_test.go
Manually tested by creating notifiers, securing them and checking the db.
Have you created automated tests for your change? Explain here which validation activities you did manually and why …
=> ROX-21843: Hide notifier cred deletion behind delete feature flag

generated/api/v1/db_service.pb.go, generated/api/v1/network_policy_service.pb.go, generated/api/v1/resource_collection_service.pb.go, generated/api/v1/vuln_req_service.pb.go, generated/internalapi/central/cluster_metrics.pb.go, generated/internalapi/central/hello.pb.go, generated/internalapi/central/telemetry.pb.go, generated/internalapi/compliance/compliance_data.pb.go, generated/internalapi/sensor/network_connection_info.pb.go, generated/storage/alert.pb.go, generated/storage/cluster.pb.go, generated/storage/cve.pb.go, generated/storage/deployment.pb.go, generated/storage/image_component.pb.go, generated/storage/kube_event.pb.go, generated/storage/node.pb.go, generated/storage/node_component.pb.go, generated/storage/notifier.pb.go, generated/storage/policy.pb.go, generated/storage/rbac.pb.go, generated/storage/report_configuration.pb.go, generated/storage/resource_collection.pb.go, generated/storage/service_identity.pb.go, generated/storage/test.pb.go, go.mod, go.sum
This PR upgrade the dependency to gogoproto fork we are using to include the latest changes to include trailing comments into generated go files. 
- https://github.com/connorgorman/protobuf/pull/6
CI (in generated files only comments should be added)
=> ROX-22102: upgrade proto fork

go.mod, go.sum
=> chore(deps): Bump ClairCore to 1.5.21

proto/storage/proto.lock
Update storage proto.lock file.
The following commands are used:
```
cd proto/storage
../../.gotools/bin/protolock commit
```
No testing was performed.
=> chore(proto): Update storage proto.lock

qa-tests-backend/src/test/groovy/RbacAuthTest.groovy
We are not using array. Let's keep it simple.
responsible for the change after it …
=> test: cleanup Rbac test resources

central/main.go, ui/apps/platform/src/Containers/AccessControl/AccessControl.tsx, ui/apps/platform/src/constants/accessControl.ts
After the various permission consolidations, it is now time to remove the warnings about the old permissions being replaced by other coarser grain permissions.
This PR leaves the framework elements (except for the UI banner in the access control section) used to communicate resource deprecations and replacements, but removes the references to former and replaced permissions.
It is acceptable to assume …
=> chore: cleanup old resource replacement warnings and information

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/updateRequestFlow.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
This PR allows a user to update a pending exception request 
https://github.com/stackrox/stackrox/assets/4805485/7f9a4161-859a-4ab5-9a7d-5f90fe36fe88
=> ROX-21478: Allow updating a pending request

tests/pods_test.go
=> chore(debug): Add logs to non-groovy TestPod test

.github/workflows/scanner-mapping-update.yaml, central/scannerdefinitions/handler/handler.go, central/scannerdefinitions/handler/updater_test.go
Use defintion.stackrox.io for mapping file _**only**_
To be added
=> ROX-22121: migrate mapping files to prod destination

qa-tests-backend/src/test/groovy/Services.groovy
CI is enough
performed testing …
=> ROX-18429: Increase timeout when checking for deployment deletion

CHANGELOG.md, pkg/features/list.go, sensor/common/networkflow/manager/manager_impl_test.go
Enabled offline v3.
- `[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~
=> ROX-21069: enabled FF for offline v3

scripts/ci/lib.sh
Stop loading all output into memory, emit it bit by bit using tee such that watching CI logs in prow frontend is useful again.
=> test(operator): improve wrapped command output handling

pkg/features/list.go
Open now to give CI plenty of time, but do not merge until after #9707
=> ROX-22197: Turn on ROX_MOVE_INIT_BUNDLES_UI feature flag

tests/e2e/lib.sh
Currently, it only creates a jira ticket, but its hard to debug. Just print the suspicious logs as they come up …
=> chore(debug): Print suspicious log for easier debugging

qa-tests-backend/src/test/groovy/ReconciliationTest.groovy
Add compliance suite to ReconciliationTest.
Unit test.
=> fix(test): Fix ReconciliationTest with compliance suite

.github/workflows/triage-report_periodic.yml
I think it will be good to present updates more often. We can start with Wednesday and Friday.
=> chore: show triage report twice a week

go.mod, go.sum, pkg/auth/authproviders/iap/backend_impl.go, pkg/auth/authproviders/validate_test.go, pkg/auth/tokens/claims.go, pkg/auth/tokens/issuer_factory.go, pkg/auth/tokens/options.go, pkg/cloudproviders/gcp/identity_token.go, pkg/grpc/authn/extractor.go, pkg/grpc/authn/extractor_test.go, pkg/jwt/facade.go, pkg/jwt/keys.go, pkg/jwt/tokens.go, sensor/common/certdistribution/service_impl.go, sensor/kubernetes/sensor/deployment_identification.go
Moves go-jose from the deprecated repo to the supported repo
CI
=> chore(bump): Move square/go-jose to go-jose/go-jose

.github/api_guidelines.md
Continuation of establishing API guidelines. This PR adds a few key guidelines for URLs.
It is also acceptable to skip testing for changes that are too taxing to test before merging. In such case …
=> URL Guidelines

ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedDashboard.test.js, ui/apps/platform/src/Containers/ComplianceEnhanced/ComplianceEnhancedPage.tsx
Follow up replacement of **Compliance Status** with **Cluster Compliance** in #9683
1. Edit cypress/integration/compliance-enhanced/complianceEnhancedDashboard.test.js
* Add `.skip` to `describe` block.
2. Edit src/Containers/ComplianceEnhanced/ComplianceEnhancedPage.tsx
* Replace `complianceEnhancedStatusPath` with `complianceEnhancedClusterComplianceBasePath` in `Redirect` element.
* Also rewrite `Redirect` to prepare for future upgrade to React Router 6
https://reactrouter.com/en/main/upgrading/v5#remove-redirects-inside-switch
* Comment out `Route` element for compliance dashboard.
* Add `Route` for **Compliance | Not Found** following example:
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx#L41-L46
1. …
=> ROX-21882: Hide compliance dashboard for MVP

central/cluster/datastore/datastore.go, central/cluster/datastore/datastore_impl.go, central/cluster/datastore/datastore_test_constructors.go, central/cluster/datastore/singleton.go, central/complianceoperator/v2/compliancemanager/manager.go, central/complianceoperator/v2/compliancemanager/manager_impl.go, central/complianceoperator/v2/compliancemanager/manager_impl_test.go, central/complianceoperator/v2/compliancemanager/singleton.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl_test.go, central/complianceoperator/v2/scanconfigurations/datastore/mocks/datastore.go, central/complianceoperator/v2/scanconfigurations/datastore/singleton.go, central/graphql/resolvers/test_setup_utils.go, central/pruning/pruning_test.go
This PR adds changes to remove cluster from scan config and delete scan status  …
=> ROX-19543 Delete cluster

pkg/cloudsources/paladin/client.go, pkg/cloudsources/paladin/client_test.go, pkg/cloudsources/paladin/testdata/response.json
This PR can be seen as a prefactor which adds the Paladin Cloud API client in perparation to interact with the API to obtain discovered clusters.
- See added unit tests.
=> feat(paladin): add paladin API client

ui/apps/platform/src/Containers/Risk/KeyValuePairs.js, ui/apps/platform/src/Containers/Violations/Details/Deployment/DeploymentOverview.tsx
Ask and it shall be given.
Link from deployment details tab in Violation detail view.
Link from deployment details tab in Risk detail view.
=> ROX-20582: Add link to Deployment from Violation and Risk detail views

.github/workflows/scanner-offline-bundle-update.yaml, .github/workflows/scanner-release-vuln-update.yaml, .github/workflows/scripts/scanner-update-offline-bundle.sh
This is a job to generate scanner V4 offline bundle
Generating V4 offline defs only 
Another job will be created to generate scanner-vulns-[version].zip"
ls offline-bundles_scanner-vulns-4.3 
k8s-istio.zip  manifest.json  scanner-defs.zip	scanner-v4-defs-4.3.zip
=> ROX-21955: Generate v4 offline bundle

image/templates/helm/shared/config-templates/scanner-v4/matcher-config.yaml.tpl, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml, scanner/config/config.go
I just realized this is not necessary, so let's remove it. I also added a test to ensure the link is set properly for CentralServices
CI
=> chore(scanner): no need to configure SecuredCluster vuln endpoint

image/templates/helm/shared/templates/_pvcs.tpl, image/templates/helm/shared/templates/_scanner-v4_volume.tpl, image/templates/helm/stackrox-central/internal/config-shape.yaml, image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, image/templates/helm/stackrox-secured-cluster/templates/collector-pod-security.yaml, pkg/helm/charts/tests/securedclusterservices/flavor/testdata/helmtest/suite.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/suite.yaml
=> feat(scanv4): Use existing PVC for Scanner V4 DB

sensor/common/networkflow/service/service_impl.go, sensor/common/signal/signal_service.go, sensor/common/signal/singleton.go, sensor/debugger/collector/common.go, sensor/debugger/collector/fake_collector.go, sensor/debugger/collector/network_flows_client.go, sensor/debugger/collector/signals_client.go, sensor/kubernetes/sensor/options.go, sensor/kubernetes/sensor/sensor.go, tools/local-sensor/main.go
Template for a fake collector that can be used for testing or debugging sensor.
```golang
fakeCollector.SendFakeSignal(&sensor.SignalStreamMessage{
Msg: &sensor.SignalStreamMessage_Signal{
Signal: &v1.Signal{
Signal: &v1.Signal_ProcessSignal{
ProcessSignal: &storage.ProcessSignal{
ContainerId: talkContainerId,
Name:        "curl",
},
},
},
},
}) …
```
=> feat(fake-collector): Fake collector for testing and debugging

.github/CODEOWNERS
Add files related to `cloudsources` and `discoveredclusters` to Team Merlin's responsibility, additionally extend the scope of the `auth` related packages to cover also Central side (i.e. M2M feature).
N/A.
=> chore(CODEOWNERS): add cloudsources to Merlin team

central/declarativeconfig/updater/notifier_updater.go, central/notifier/processor/singleton.go, pkg/declarativeconfig/context.go, pkg/declarativeconfig/context_test.go
Unit tests added
Manual testing by creating a declarative config notifier and securing it. …
=> ROX-21844: Add context to allow both declarative and imperative origin resources

deploy/common/k8sbased.sh, operator/Makefile, scripts/ci/jobs/ocp_scanner_v4_tests.py, tests/e2e/lib.sh, tests/e2e/run-scanner-v4.bats, tests/e2e/yaml/secured-cluster-cr.envsubst.yaml
This PR adds a multi-namespace, operator-based installation with Scanner V4 enabled.
=> test(scanv4): Add operator-based install scenarios

sensor/tests/resource/service/service_test.go
Uses correct assertion function
Tests passing 
=> ROX-21731: Service integration test flake fix

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/CoveragesPage.tsx
Exporting as csv will not be available in 4.4
=> ROX-18122: Disable export as CSV for compliance

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/cveListExceptionFlow.test.js, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/CveSelections.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestForm.tsx
This PR enables a user to remove CVEs from a vuln request using the modal
https://github.com/stackrox/stackrox/assets/4805485/5e213e6c-3abd-4c75-b9b5-a3287b456ffa
=> ROX-20554: Removing a CVE when updating a request

scanner/Makefile
Downstream builds require that target to copy scripts from the parent directory. …
=> fix(scanner): Add downstream copy-script target to support downstream

ui/apps/platform/cypress/helpers/formHelpers.js, ui/apps/platform/cypress/integration/integrations/integrations.helpers.js, ui/apps/platform/cypress/integration/integrations/paladinCloudIntegrations.test.ts, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/PaladinCloudIntegrationForm.tsx
Adding UI tests for paladin cloud integration form + fixing validation logic
=> ROX-22046: Paladin cloud integration form UI tests

central/complianceoperator/v2/scanconfigurations/service/service_impl.go, central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go
=> Added validator to verify scan config name is dns compatible

ui/apps/platform/cypress/integration/integrations/integrations.helpers.js, ui/apps/platform/cypress/integration/integrations/machineAccessConfigs.test.ts, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/MachineAccessIntegrationForm.tsx
Follow up of https://github.com/stackrox/stackrox/pull/9706
=> ROX-20222: Add M2M configuration UI tests

scripts/ci/jobs/gke_version_compatibility_tests.py
Enable now that 3.74.9 has been released
responsible for the change after it gets …
=> chore(test): Enable 3.74.x compatibility testing

CHANGELOG.md
This change announces a change of behaviour for some product endpoints.
This is a Changelog only modification. …
=> ROX-22480: Changelog entry for future hardening

image/templates/helm/stackrox-secured-cluster/templates/admission-controller.yaml
=> ROX-13960: Set VWC namespaceSelector dynamic

CHANGELOG.md, central/role/service/service_impl.go
All is in the title.
responsible for the change after it gets merged which includes …
=> ROX-19814: require authenticated access to /v1/resources

operator/bundle_helpers/patch-csv.py
This no-op parameter can be removed, because the midstream scripts no longer use it.
We do not need to wait until older releases that use these parameters are no longer supported, because those older releases use the script from their respective release branches.
It is acceptable to skip testing in cases when CI …
=> ROX-22395: Cleanup --replace-rbac-proxy option

ui/apps/platform/cypress/integration/integrations/paladinCloudIntegrations.test.ts
Fixes CI when flag is not enabled yet
responsible for the change after it gets …
=> fix: paladinCloudIntegrations.test.ts use feature flag

ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterUsingHelmChart.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterUsingOperator.tsx
Pending review by docs and Draco teams, make changes from 2 UI team bug bashes.
1. Replace numbered list with bulleted list under **Prerequisites** because they seem independent.
2. Swap bulleted items so second item about OpenShift Container Platform as closer to first item in numbered list about OpenShift Container Platform.
3. Edit ClipboardCopy command
* Add `create` verb that I deleted by mistake when I made the following change.
* Reverse replacement of `rhacs-operator` with `stackrox` (pending review) according to cloud service:
https://github.com/RedHatInsights/acs-ui/blob/main/src/routes/GettingStartedPage/Wizard/InstallWithOperator.js#L103
1. Edit code block
* Replace `rhacs-secured-cluster-services` with `stackrox-secured-cluster-services` based on discovery by Linda and David. …
=> ROX-22562: Make changes after team test of secure a cluster steps

central/cluster/datastore/datastore_impl.go, central/complianceoperator/v2/checkresults/datastore/datastore.go, central/complianceoperator/v2/checkresults/datastore/datastore_impl.go, central/complianceoperator/v2/checkresults/datastore/mocks/datastore.go, central/complianceoperator/v2/pruner/pruner.go, central/complianceoperator/v2/pruner/singleton.go
=> Added changes to delete check result by cluster id

tests/e2e/run-scanner-v4.bats
Verify the `ROX_SCANNER_V4` env var in Sensor (in addition to Central, where it was already done).
=> test(scanv4): verify Scanner V4 env vars in Sensor deployment

go.mod, go.sum
=> chore(deps): bump claircore to 1.5.22

operator/tests/common/central-cr-with-scanner-v4.yaml, tests/e2e/lib.sh, tests/e2e/run-scanner-v4.bats, tests/e2e/yaml/central-cr-with-scanner-v4.envsubst.yaml, tests/e2e/yaml/central-cr.envsubst.yaml, tests/e2e/yaml/secured-cluster-cr-with-scanner-v4.envsubst.yaml, tests/e2e/yaml/secured-cluster-cr.envsubst.yaml
This PR adds the multi-namespace operator upgrade test to the Scanner V4 installation test suite.
Best reviewed commit by commit.
It is also acceptable to skip testing for changes that are too …
=> ROX-22563: Add operator multi-namespace upgrade test

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/ClustersCoverageTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Components/CoverageTableViewToggleGroup.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/CoveragesPage.tsx, ui/apps/platform/src/services/ComplianceEnhancedService.ts
Addresses the following issues related to the overall coverage table
* Remove "Build date" column
* Add "Operator status" column
* Add missing `dataLabel` prop to `<Td>` elements
* Add missing `aria-label` to the `Progress` component
* Update the text displayed when no results are found in the table
* Re-align the `CoverageTableViewToggleGroup` to sit next to pagination, saves vertical space
> * Update the text displayed when no results are found in the table
---
> * Remove "Build date" column
> * Add "Operator status" column
> * Re-align the `CoverageTableViewToggleGroup` to sit next to pagination, saves vertical space
> * Add missing `aria-label` to the `Progress` component
---
> * Add missing `dataLabel` prop to `<Td>` elements
=> ROX-22600: address compliance coverage issues

central/complianceoperator/v2/scanconfigurations/service/convert.go
=> fix(BE): Fix possible race condition when bindings are unavailable

CHANGELOG.md
Briefly mention Scanner V4, referring to the RHACS docs.
I'm not exactly sure how much information we should provide in the ChangeLog. I guess it is better to stay more concise than going into the details (listing features and installation methods)?
It is acceptable to skip testing in cases when CI is …
=> docs(scanv4): Mention Scanner V4 in ChangeLog

CHANGELOG.md, deploy/common/k8sbased.sh, image/templates/helm/stackrox-central/templates/01-central-02-db-psps.yaml, image/templates/helm/stackrox-central/templates/01-central-02-db-security.yaml
The installation for hostpath is not in use and it is not recommended for security reasons. We are going to deprecate it in the next releases.
provided convince any reviewer or any external reader that you did enough to validate your …
=> ROX-21230: Deprecate hostpath notice

CHANGELOG.md
=> ROX-13367: Add WIF support to CHANGELOG

ui/apps/platform/cypress/integration/integrations/paladinCloudIntegrations.test.ts, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/PaladinCloudIntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/hooks/useIntegrationActions.ts, ui/apps/platform/src/utils/responseErrorUtils.ts
Add "Test" button to Paladin Cloud integration, similar to other integrations. We still skip testing integration during create/update operations.
1. Pressed `Test` button 
2. Checked that timeout displays proper error:
3. Checked that if I switch endpoint to `https://stackrox.io`, error from backend is returned
=> ROX-22543: Add test functionality Paladin Cloud

ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/OcmIntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationForm/IntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/CloudSourceIntegrationsSection.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/OcmTile.tsx, ui/apps/platform/src/Containers/Integrations/hooks/useIntegrations.ts, ui/apps/platform/src/Containers/Integrations/utils/integrationsList.ts, ui/apps/platform/src/Containers/Integrations/utils/tableColumnDescriptor.ts, ui/apps/platform/src/services/CloudSourceService.ts, ui/apps/platform/src/types/integration.ts
Similar to https://github.com/stackrox/stackrox/pull/9831, adds an integration form for OCM as a cloud source.
=> ROX-22047: OCM integration form

image/templates/helm/shared/config-templates/scanner-v4/indexer-config.yaml.tpl, image/templates/helm/shared/config-templates/scanner-v4/matcher-config.yaml.tpl
Inject the log level setting from the Helm chart configuration into configuration files for Scanner V4 indexer and matcher.
It is also acceptable to skip testing for changes that are too taxing to …
=> fix(scanv4): Inject log level into configuration files

operator/apis/platform/v1alpha1/central_types.go, operator/apis/platform/v1alpha1/securedcluster_types.go, operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
=> fix: hide monitoring in operator ui if scannerV4 not enabled

CHANGELOG.md
=> ROX-22070: Compliance 2.0 Changelog

image/templates/helm/stackrox-central/values.yaml.htpl
=> docs(scanv4): Add example values to central Helm chart

go.mod, go.sum
This version improves JAR parsing error messages. See https://github.com/quay/claircore/compare/v1.5.23...v1.5.24
By the way, if you're curious how I always know when a new ClairCore version is out: I subscribe to release updates in the ClairCore GitHub repo.
If it builds, it builds …
=> chore(deps): claircore v1.5.24

govulncheck-allowlist.json
=> chore(CI): Allow another month for govulncheck

central/cloudsources/datastore/telemetry.go, central/cloudsources/datastore/telemetry_postgres_test.go, central/main.go
Add telemetry for the number of cloud source integrations as well as the different types.
N/A.
=> chore(cloud-sources): add telemetry for cloud sources

CHANGELOG.md
Add the CHANGELOG entry for machine to machine / machine access configurations.
N/A
=> chore(m2m): add changelog entry

.github/workflows/scanner-mapping-update.yaml, .github/workflows/scanner-offline-bundle-update.yaml, .github/workflows/scripts/scanner-update-offline-bundle.sh, central/scannerdefinitions/handler/handler.go, central/scannerdefinitions/handler/updater_test.go
=> fix(scanner): use v4 namespacing for mapping bucket

ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterUsingOperator.tsx
=> ROX-22668: Cluster init bundle operator content changes

CHANGELOG.md
=> feat(docs): Changelog warning for RocksDB removal

tests/e2e/run-scanner-v4.bats
The previous waiting code used an implicit default timeout of 30s, which might be too short.
Furthermore: add delay to prevent kubectl from becoming confused about vanishing pods when it is actually waiting for them to become ready.
It is acceptable to skip testing in cases when CI is sufficient, or it's a …
=> test(scanv4): Improve waiting for StackRox Operator Pods

deploy/common/k8sbased.sh, operator/tests/common/central-cr-with-scanner-v4.yaml, tests/e2e/run-scanner-v4.bats
=> ROX-22590: Test disabling of Scanner V4

central/authprovider/service/service_impl.go
The /v1/login/authproviders endpoint is a public endpoint. This change aims at documenting the reasons behind its being public in order to ease future investigations of public endpoints and possible hardening.
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment …
=> ROX-20688: Document why /v1/login/authproviders should remain public

central/scanner/handler.go, pkg/apiparams/scanner.go, pkg/images/defaults/flavor.go, pkg/renderer/images.go, pkg/renderer/kubernetes.go, pkg/renderer/templater.go, pkg/renderer/templates/public_values.yaml.tpl, roxctl/central/generate/interactive.go, roxctl/central/generate/k8s.go, roxctl/common/flags/imageFlavor.go, roxctl/scanner/generate/generate.go, tests/roxctl/bats-tests/local/expect/flavor-interactive.expect.tcl
So far we have implemented roxctl (i.e. manifest bundle installation) support for Scanner V4 installation rather half-heartedly: roxctl was able to generate bundles but it was not possible to configure images references (registries, repositories, tags). At first this seemed acceptable because roxctl hasn't been a priority for Scanner V4 installations, but it turned out that it caused quite some annoyances with regard to our own deployment tooling, which still uses deployment bundles here and there.
A closer look at the way images are configured revealed that we better integrate Scanner V4 properly into the `renderer` (in particular the `K8sConfig` structure and the related image override and defaulting mechanisms) and into the `apiparams` package. In the end it was feasible to also expose …
=> fix(scanv4): Proper support in renderer and roxctl

image/templates/helm/stackrox-secured-cluster/README.md.htpl
=> docs(scanv4): Mention Scanner V4 in README

pkg/images/enricher/enricher_impl.go, pkg/images/enricher/enricher_impl_test.go
We have seen the following edge case:
- An image exists for a particular SHA.
- Another image with the same SHA will be added, but a different reference. This may be done by calling `roxctl image scan / roxctl image check`. This will use cached values.
- The image signature verification data, if previously existing for a signature, will not be refetched. However, signature verification data will be affected by the change names.
We now will do the following when updating the to-be-enriched image with an existing image: in case changes to the image names are found, we will reset the signature verification data on the image, forcing a re-verification.
- see CI.
Manual tests: 
1. Create a signature integration in ACS using the below public …
=> fix(enricher): force sig verification when names change

scanner/matcher/matcher.go, scanner/matcher/updater/distribution/updater.go, scanner/matcher/updater/vuln/updater.go
Run the initial distribution updater more eagerly (every 15m) if the vuln DB is not ready. Then do it every 24h. This allows the matcher fleet to get the known distributions as soon as possible. 
It …
=> fix(scanner): Sync distribution updater with vulnerability updater

tests/e2e/run-scanner-v4.sh
=> test(scanv4): Testing junit reports

central/complianceoperator/v2/checkresults/datastore/datastore.go, central/complianceoperator/v2/checkresults/datastore/datastore_impl.go, central/complianceoperator/v2/checkresults/datastore/datastore_impl_benchmark_test.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore.go, pkg/fixtures/compliance_check_result.go
Added a benchmark test and a metric
Primarily this PR is a test.  However I did spin up a cluster to ensure the metrics were recorded.
=> ROX-20429, ROX-20396: compliance results benchmark

scanner/e2etests/testdata/image_tests.json
These tests were out-of-date. See https://github.com/stackrox/scanner/blob/master/e2etests/testcase_test.go for the latest updates
CI
=> fix(scanner): update fixedby in e2e tests

central/apitoken/backend/backend_impl.go, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/ApiTokenIntegrationForm/ApiTokenIntegrationForm.tsx
=> feat: forbid selecting expiration date in past for API token

qa-tests-backend/src/test/groovy/BaseSpecification.groovy, qa-tests-backend/src/test/groovy/ComplianceTest.groovy, qa-tests-backend/src/test/groovy/ImageManagementTest.groovy, qa-tests-backend/src/test/groovy/PolicyConfigurationTest.groovy, qa-tests-backend/src/test/groovy/VulnMgmtWorkflowTest.groovy
Prefer using SHA over tags.
Refs:
- #10106 
- https://github.com/stackrox/stackrox/pull/10096 …
=> chore: use SHA for test image

central/policy/service/service_impl.go
=> ROX-22797: Paginate ListPolicies

central/policy/service/service_impl_test.go
see title. Forgot to include in [original PR](https://github.com/stackrox/stackrox/pull/10203)  …
=> fix(test): Add unit test for policy pagination

pkg/auth/authproviders/oidc/backend_impl.go, pkg/auth/authproviders/oidc/backend_impl_test.go
Currently, we do not handle nonce verification errors strict, i.e. we should always return an error in case of a nonce verification failure instead of silently ignoring it and returning the auth response, if it was possible to create one.
- see CI.
=> fix(oidc): stricter handling of nonce verification error

central/policy/service/service_impl.go, central/policy/service/service_impl_test.go
=> fix(revert): Revert policy pagination

sensor/kubernetes/listener/resources/networkpolicy_store_test.go
Refactors Network Policy store clean up unit tests to be more similar to deployment store tests.
This also fixes a bug in the test where the pod label check wasn't really testing anything. 
Tests pass. 
=> ROX-18198: Network Policy store unit tests

go.mod
Looks like this excludes are no longer needed.
responsible for the change after it …
=> chore(deps): remove unused excludes

go.mod, go.sum
Looks like this replace is no longer required.
responsible for the change after it …
=> chore: remove replace for kyaml

.github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-release-vuln-update.yaml, scanner/updater/version/RELEASE_VERSION
use apollo image for scanner job and fix "tmp" not accessible issue
=> ROX-22871: fix "tmp" not accesible issue

go.mod, go.sum
Pickup the fix for  GO-2024-2611(CVE-2024-24786)
Existing tests
=> chore(deps): Bump protobuf version

.github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-release-vuln-update.yaml
=> fix(Scanner): test volumes in scanner job

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.helpers.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approveRequestFlow.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approvedFalsePositivesTable.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/cancelRequestFlow.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
This includes some tests for the Approved False Positives table in Exception Management. You can check the subtasks for this Jira to see all the tests we will be adding https://issues.redhat.com/browse/ROX-20970.
=> ROX-20970: Tests for Approved False Positives Table

.github/workflows/scanner-build.yaml, scanner/image/db/scripts/download.sh
ROX-22927 fix s390x build issues and re-enable
built successfully on s390x machine.
=> ROX-22927: fix s390x build issues and re-enable

sensor/debugger/k8s/fake.go, tools/local-sensor/main.go
Use a `concurrency.ErrorSignal` instead of an error chan in the `FakeEventsManager`.
performed …
=> ROX-11396: Use error signal instead of error chan

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.helpers.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/deniedRequestsTable.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/denyRequestFlow.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
This includes some tests for the Denied Requests table in Exception Management. You can check the subtasks for this Jira to see all the tests we will be adding https://issues.redhat.com/browse/ROX-20982.
=> ROX-20982: Tests for Denied Requests Table

scripts/ci/metrics.sh
Followup to https://github.com/stackrox/automation-iac/pull/69
I could not find any other uses, can you think of any @gavin-stackrox ?
=> ROX-22862: Use ShortJobName, ShortName is deprecated.

go.mod, go.sum
Cherry pick and resolve the following
chore(deps): bump github.com/go-jose/go-jose/v3 from 3.0.2 to 3.0.3 (#10274)
chore(deps): bump gopkg.in/go-jose/go-jose.v2 from 2.6.1 to 2.6.3 (#10273)
It is …
=> chore(deps): bump github.com/go-jose/go-jose

.github/workflows/scanner-pr-vuln-update.yaml, scanner/mappers/mappers_test.go, scanner/updater/rhel/parser.go
Parsing RHEL vuln names in the updaters rather than using the V4 "mappers". This guarantees backward compatibility with Scanner V2. We don't want to fork away from ClairCore, but this fork is temporary as work to onboard new RH security data sources is in progress.
It is acceptable to skip testing in cases when …
=> fix(scanner): Parse RH vuln names from RH links

ui/apps/platform/src/Components/PatternFly/TableErrorComponent.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/types.ts
This PR adds Deployment labels and annotations in the Deployments single page
=> ROX-22725: Adding deployment labels and annotations

central/cve/cluster/datastore/datastore_impl.go, central/cve/common/utils.go, central/cve/image/datastore/datastore_impl.go, central/cve/node/datastore/datastore_impl.go, tools/roxvet/analyzers/gogoprotofunctions/analyzer.go
The goal is to remove direct calls to the gogo protobuf layer and have all of them happen through an abstraction layer in order to ease the migration to a new protobuf library.
The change is the application through the refactoring tool `eg` of the following template:
```
package refactor
import (
"time"
"github.com/gogo/protobuf/types"
"github.com/stackrox/rox/pkg/protocompat"
)
func before(d *types.Duration) (time.Duration, error) {
return types.DurationFromProto(d)
}
func after(d *types.Duration) (time.Duration, error) {
return protocompat.DurationFromProto(d)
}
```
Feel free to attach JSON snippets, curl …
=> ROX-22101: use gogo DurationFromProto through compatibility layer

tests/e2e/lib.sh, tests/upgrade/legacy_to_postgres_run.sh, tests/upgrade/lib.sh
When Rocks is removed we will not be able to upgrade from Rocks to 4.5.  This is setting the Rocks upgrade test to stop at 4.4.  Later we will add a case where we catch that an error is returned if trying to upgrade from Rocks to 4.5.  Refactored things necessary for rocks out of the `lib.sh` and isolated into `legacy_to_postgres_run.sh` to avoid accidental use of those functions elsewhere.
NOTE:  using `4.4.0-rc.9` to get this PR moving and unblock the rest of the rocks removal.  If 4.4 is released prior to this PR being merged I will update it to 4.4.  Otherwise a subsequent chore PR will be used to move to actual 4.4. 
~- [ ] Documented …
=> ROX-22872:  rocks upgrade cap at 4.4

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DynamicIcon.tsx
=> ROX-19949: Change VM 2.0 lightning icon to a filter icon

operator/main.go, operator/pkg/central/extensions/common.go, operator/pkg/central/extensions/common_test.go, operator/pkg/central/extensions/reconcile_admin_password.go, operator/pkg/central/extensions/reconcile_central_db_password.go, operator/pkg/central/extensions/reconcile_pvc.go, operator/pkg/central/extensions/reconcile_scanner_db_password.go, operator/pkg/central/extensions/reconcile_scanner_v4_db_password.go, operator/pkg/central/extensions/reconcile_tls.go, operator/pkg/central/reconciler/reconciler.go, operator/pkg/common/extensions/reconcile_scanner_db_password.go, operator/pkg/common/extensions/reconcile_scanner_v4_db_password.go, operator/pkg/common/extensions/secret_reconciliator.go, operator/pkg/common/labels/labels.go, operator/pkg/proxy/extension.go, operator/pkg/reconciler/reconciler_factory.go, operator/pkg/securedcluster/extensions/common.go, operator/pkg/securedcluster/extensions/reconcile_scanner_db_password.go, operator/pkg/securedcluster/extensions/reconcile_scanner_v4_db_password.go, operator/pkg/securedcluster/reconciler/reconciler.go, operator/pkg/securedcluster/values/translation/translation.go, operator/pkg/securedcluster/values/translation/translation_test.go, operator/pkg/utils/api.go
Sorry I was not able to review #10302 in time. See the suggestions here. I recommend viewing each commit separately.
The most important is the change from `apiReader` to `direct` in variable names, which stresses the fact that we're using an uncached client, which is the important part - not the fact that we're using the Reader interface.
Apart from this, I think the tradeoff we're making (lower memory usage but raise latency and API server load) is important enough to mention in the changelog file. It would be great to do actual measurements, but that can happen later.
Feel free to attach JSON snippets, curl …
=> chore(operator): Followup improvements.

scanner/e2etests/testdata/image_tests.json
Some of the values were out-of-date, and others were changed due to Scanner v2 and v4 differences. All of these changes are expected and ok.
CI
=> fix(scanner): update e2e test expected values

CHANGELOG.md
=> fix: add operator cache label selector to changelog

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCvesPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodesTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/components/NodeCveFilterToolbar.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadCveFilterToolbar.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/CVESeverityDropdown.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/CVEStatusDropdown.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/FilterDropdowns.css, ui/apps/platform/src/Containers/Vulnerabilities/searchOptions.ts, ui/apps/platform/src/Containers/Vulnerabilities/types.ts
Depends on refactoring in https://github.com/stackrox/stackrox/pull/10355
- Adds the main layout of the Node CVE list page.
- Basic integration of entity tabs, filters, and pagination with URL parameters
Visit Node CVEs from the sidebar and see the rendered page layout. The correct entityTab parameter should be visible in the URL:
Change to the Node entity and ensure the correct entityTab parameter is visible in the URL:
Apply various filters and change the "perPage" setting and ensure the URL tracks these values:
It is also acceptable to skip testing for changes that are too taxing to test before merging. In such case you …
=> ROX-23028: Add page component layout for node cves page

image/postgres/download.sh, image/rhel/download.sh, scanner/image/db/scripts/download.sh
`s390x` builds have been flaky recently: [1](https://github.com/stackrox/stackrox/actions/runs/8332299571), [2](https://github.com/stackrox/stackrox/actions/runs/8332067365), [3](https://github.com/stackrox/stackrox/actions/runs/8331824676). Switch to `dnf` over `yum` as a first step. 
=> chore(CI): use dnf over yum

CHANGELOG.md, image/templates/helm/shared/templates/_helpers.tpl, image/templates/helm/stackrox-central/internal/config-shape.yaml, image/templates/helm/stackrox-central/templates/_init.tpl.htpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, pkg/helm/charts/tests/centralservices/base_suite_test.go, pkg/helm/util/render.go
See https://issues.redhat.com/browse/ROX-23096. Subject says it all.
Why 3.9.0? Because it seems that this is the first version which makes its own version string available to the chart to be rendered as `.Capabilities.HelmVersion.Version` (see https://github.com/helm/helm/releases/tag/v3.9.0).
It is acceptable …
=> ROX-23096: Abort rendering of Helm charts if Helm version is < v3.9.0

go.mod
Assign replacements to @stackrox/scanner 
`go mod tidy` 
=> chore(go.mod): extract replaces owned by scanner

go.mod
Assign replacements to @stackrox/core-workflows  
`go mod tidy` 
=> chore(go.mod): extract core workflows replaces

go.mod
Assign replacements to @stackrox/draco  
`go mod tidy` 
=> chore(go.mod): replaces owned by 🐉

.tekton/scanner-v4-db-pull-request.yaml, .tekton/scanner-v4-db-push.yaml, scanner/image/db/konflux.Dockerfile
responsible for the change after it gets merged which includes reverting, fixing, …
=> ROX-20860: Add Konflux build pipeline for Scanner v4 DB

.github/dependabot.yaml, .github/workflows/retest_periodic.yml, tools/retest/go.mod, tools/retest/go.sum, tools/retest/main.go
This PR creates an action that will run every hour and scan PRs with `auto-merge` label and if there is a failed status then comment with `/retest`. This is a first step into making an action that will run prow tests on PR with given number of times. Currently there is a hard limit of 10 retests.
Run on [`pull_request` event](https://github.com/stackrox/stackrox/actions/runs/8359198489/job/22882040137#step:4:73)
that resulted with following comment
- https://github.com/stackrox/stackrox/pull/10404#issuecomment-2009492469
- https://github.com/stackrox/stackrox/actions/runs/8375351851/job/22932512422?pr=10438
performed one does …
=> chore(test): auto retest prow

go.mod, go.sum
Update protobuf deps. One of the several PRs based on https://github.com/stackrox/stackrox/pull/10441.
This matches the versions in 4.4.0.
CI
=> chore(deps): protobuf 1.31.0 => 1.33.0

scanner/updater/version/RELEASE_VERSION
There is no need to have any of these except for 4.4.0, so let's free up some resources and get rid of false-positive alerts
I didn't
performed testing …
=> chore(scanner): remove unnecessary release versions

image/postgres/download.sh, scripts/check-log-query-data.sh, scripts/check-todos.sh, scripts/ci/collect-collector-metrics.sh, scripts/ci/gke.sh, scripts/ci/lib.sh, scripts/k8s/cleanup.sh, tests/e2e/bats/check_for_errors_in_stackrox_logs.bats, tools/local-sensor/scripts/local-sensor.sh
Using [image with bumped shellcheck version](https://github.com/stackrox/rox-ci-image/pull/201).
```
[stackrox]$ docker run --privileged -u `id -u`:`id -u`  -ti -w `pwd` -v /home:/home quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.66-1-g1594f5d4fe make shell-style
+ shell-style
INFO: Thu Mar 21 10:24:26 UTC 2024: Running shellcheck on all .sh files (excluding scripts/style/shellcheck_skip.txt)
[stackrox]$ 
```
performed one does not seem sufficient. As a reviewer, you must not approve the change until you …
=> ROX-23313: Fix shellcheck 0.10.0 warnings.

qa-tests-backend/scripts/migrate_protos.sh
The `cp` command on my machine does not support the `--no-preserve` option. As the comment above the failing line reports issues with file ownership and writability, two additional steps are introduced to ensure the copied files are owned and writable by the calling user.
It is acceptable to skip testing in …
=> chore(proto): workaround unsupported cp option on mac

.github/workflows/unit-tests.yaml, .openshift-ci/Makefile, .openshift-ci/tests/test_clusters.py
Per title.
[CI](https://github.com/stackrox/stackrox/actions/runs/8384448112/job/22961783626?pr=10486)
=> chore(CI): enable .openshift-ci unit tests in CI

tools/retest/main.go
Let's limit number of retest to 3 …
=> fix(ci): retest max 3 times

operator/tools/kuttl/go.sum, tools/retest/go.mod, tools/retest/go.sum
Fix go modules for latest go 1.21
```bash
find $PWD -type f -name "go.mod" -printf '%h\n' | xargs -IDIR bash -c 'cd DIR && go mod tidy'
```
It is also acceptable to skip testing for changes that are …
=> fix: go mod tidy on 1.21

.github/workflows/scanner-release-vuln-update.yaml
go1.21+ is much stricter about the go mod file, so just `go mod tidy` before building older versions.
CI
=> fix(ci): scanner vuln updates go1.21 updates

CHANGELOG.md
=> chore(docs): Scanner DB PostgreSQL 12 -> 15

.github/workflows/lint.yml, .github/workflows/style.yaml, .openshift-ci/dev-requirements.txt
See:
- https://github.com/stackrox/rox-ci-image/pull/201
- https://github.com/stackrox/stackrox/pull/10471
CI 💪🏻 
=> ROX-23313: Bump lint/style checks image

pkg/booleanpolicy/evaluator/base_evaluators.go, pkg/notifiers/format.go, pkg/protoconv/time.go, pkg/protoconv/time_test.go, pkg/readable/time.go
See title.
PR stack:
- #10525
- #10526 
- #10528
- #10529
- #10530
- #10531
- #10532
- #10533
- #10534
- #10535
- #10536
- #10537  …
=> ROX-22101: gogo move pkg/readable/ProtoTime to protoconv

pkg/sensor/queue/scaler_test.go
=> ROX-22764: fix tests from PR #10308

tests/upgrade/legacy_to_postgres_run.sh
In upgrade test we `make cli` twice for different versions which is not required as we can download binaries and do not build them.
- https://github.com/stackrox/stackrox/pull/10559
test upgrade
=> chore: cleanup upgrade test

pkg/booleanpolicy/evaluator/base_evaluators.go, pkg/booleanpolicy/evaluator/evaluator_test.go, pkg/booleanpolicy/violationmessages/printer/network_baseline.go, pkg/protocompat/time.go
See title.
PR stack:
- #10525
- #10526 
- #10528
- #10529
- #10530
- #10531
- #10532
- #10533
- #10534
- #10535
- #10536
- #10537  …
=> ROX-22101: remove gogo protobuf imports from pkg/booleanpolicy

central/convert/storagetotype/discovered_clusters.go, central/convert/typetostorage/discovered_cluster.go, pkg/booleanpolicy/evaluator/base_evaluators.go, pkg/booleanpolicy/evaluator/evaluator_test.go, pkg/booleanpolicy/violationmessages/printer/network_baseline.go, pkg/cloudsources/discoveredclusters/discovered_cluster.go, pkg/cloudsources/ocm/client.go, pkg/cloudsources/ocm/client_test.go, pkg/cloudsources/paladin/client.go, pkg/cloudsources/paladin/client_test.go, pkg/fixtures/discovered_cluster.go, pkg/protocompat/time.go
See title.
PR stack:
- #10525
- #10526 
- #10528
- #10529
- #10530
- #10531
- #10532
- #10533
- #10534
- #10535
- #10536
- #10537  …
=> ROX-22101: migrate pkg cloudsources away from gogo protobuf

central/compliance/handlers/csv.go, pkg/csv/utils.go, pkg/protocompat/time.go, pkg/protocompat/time_test.go
See title.
PR stack:
- #10525
- #10526 
- #10528
- #10529
- #10530
- #10531
- #10532
- #10533
- #10534
- #10535
- #10536
- #10537  …
=> ROX-22101: move pkg csv away from gogo protobuf

central/compliance/handlers/csv.go, central/networkgraph/aggregator/aggregator_test.go, pkg/csv/utils.go, pkg/networkgraph/testutils/utils.go, pkg/protocompat/time.go, pkg/protocompat/time_test.go
See title.
PR stack:
- #10525
- #10526 
- #10528
- #10529
- #10530
- #10531
- #10532
- #10533
- #10534
- #10535
- #10536
- #10537  …
=> ROX-22101: move pkg networkgraph away from gogo protobuf

pkg/search/postgres/common.go, pkg/search/postgres/store.go, pkg/search/postgres/store_cache.go
See title.
PR stack:
- #10525
- #10526 
- #10528
- #10529
- #10530
- #10531
- #10532
- #10533
- #10534
- #10535
- #10536
- #10537  …
=> ROX-22101: move pkg search postgres away from gogo protobuf

pkg/search/postgres/common.go, pkg/search/postgres/store.go, pkg/search/postgres/store_cache.go, pkg/search/predicate/base_predicates.go, pkg/search/predicate/basematchers/base_matchers.go, pkg/search/predicate/basematchers/timestamp.go, pkg/search/predicate/predicate.go, pkg/search/predicate/timestamp_predicate.go
See title.
PR stack:
- #10525
- #10526 
- #10528
- #10529
- #10530
- #10531
- #10532
- #10533
- #10534
- #10535
- #10536
- #10537  …
=> ROX-22101: move pkg search predicate away from gogo protobuf

central/telemetry/gatherers/central.go, central/telemetry/gatherers/cluster.go, pkg/search/postgres/common.go, pkg/search/postgres/store.go, pkg/search/postgres/store_cache.go, pkg/search/predicate/base_predicates.go, pkg/search/predicate/basematchers/base_matchers.go, pkg/search/predicate/basematchers/timestamp.go, pkg/search/predicate/predicate.go, pkg/search/predicate/timestamp_predicate.go, pkg/telemetry/util.go
See title.
PR stack:
- #10525
- #10526 
- #10528
- #10529
- #10530
- #10531
- #10532
- #10533
- #10534
- #10535
- #10536
- #10537  …
=> ROX-22101: move telemetry away from gogo protobuf

qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
`quay.io` will sometimes return a component list without vulns when scanning an image. See ROX-23406 for failure examples and [corroboration](https://issues.redhat.com/browse/ROX-23406?focusedId=24454754&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24454754). This PR adds a 5x retry with a 60 second pause between tries to attempt to get the expected scan.
CI+:
- ran with an image with no vulns. 
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/10570/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1773751999997677568 …
=> fix(CI): ROX-23406: retry to get vulns from quay.io

scanner/updater/version/RELEASE_VERSION
This will reduce noise
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/op~enshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))
nah
I didn't
=> chore(scanner): delete rc versions

Makefile
Fix arm64 local build.
It is acceptable to assume trust and keep this section …
=> fix: Fix arm64 local build with golang 1.21

govulncheck-allowlist.json
Ignore one which requires version bump
trivial
=> ROX-23485: temporarily ignore

migrator/migrations/m_172_to_m_173_network_flows_partition/stores/previous/store.go, migrator/migrations/m_172_to_m_173_network_flows_partition/stores/updated/store.go, migrator/migrations/m_182_to_m_183_remove_default_scope_manager_role/migration_test.go
=> ROX-22101: remove gogo protobuf imports from migrations

make/protogen.mk
gogo is not longer needed in proto …
=> chore: remove gogo from make

ui/apps/platform/src/Containers/Dashboard/Widgets/AgingImagesChart.tsx
Changes as suggested by Mark here,
https://github.com/stackrox/stackrox/pull/10401#discussion_r1543433615 
Verified that the component looks the same after this change as it did before, and matches the data as seen on staging central.
=> chore(ui): Fix codemod for aging images chart

sensor/common/externalsrcs/handler.go, sensor/common/networkflow/manager/manager_impl.go, sensor/common/networkflow/metrics/metrics.go
- Adds metrics for internal flows
- Fixes bug where internal flows are counted as external flows metric
- Add orientation to flows
- Add namespace label to flow metric
=> ROX-7481: Improve extenral/internal Network Metrics

tools/roxvet/analyzers/validateimports/analyzer.go
Now that the protocompat PRs have been merged, it's time to clean up the exceptions brought in roxvet at the beginning. 
It is also acceptable to skip testing for changes that are too taxing to test …
=> ROX-22101: cleanup roxvet exceptions for gogo protobuf imports

ui/apps/platform/cypress/integration/accessControl/accessControl.helpers.js, ui/apps/platform/cypress/integration/accessControl/accessControlOrigin.test.js, ui/apps/platform/src/Containers/MainPage/InviteUsers/InviteUsersModal.tsx
=> chore(ui): Make all access control e2e tests pass

ui/apps/platform/src/Containers/Vulnerabilities/components/FilterAutocomplete.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SearchOptionsDropdown.tsx, ui/apps/platform/src/hooks/patternfly/useSelectToggle.ts
should resolve dropdown/filter issues in the UI (specifically Workload CVEs and also in Exception Management)
=> fix(ui): Dropdown fix

central/authprovider/datastore/datastore.go, central/declarativeconfig/updater/role_updater.go, central/declarativeconfig/updater/role_updater_test.go, central/declarativeconfig/updater/updater.go, central/group/datastore/datastore.go
Increase test coverage for the role updater in declarative config.
- see CI.
=> chore(dec-config): add tests to role updater

ui/apps/platform/cypress/helpers/formHelpers.js, ui/apps/platform/cypress/helpers/tableHelpers.js, ui/apps/platform/cypress/integration/integrations/apiTokens.test.js, ui/apps/platform/cypress/integration/integrations/integrations.helpers.js, ui/apps/platform/cypress/integration/systemHealth/vulnDefinitions.test.js, ui/apps/platform/src/Containers/Integrations/IntegrationForm/FormLabelGroup.tsx, ui/apps/platform/src/Containers/SystemConfig/Details/PublicConfigBannerDetails.tsx, ui/apps/platform/src/Containers/SystemConfig/Details/PublicConfigLoginDetails.tsx
=> fix(ui): PF5 e2e fixes integrations page

ui/apps/platform/cypress/constants/PoliciesPage.js, ui/apps/platform/cypress/integration/policies/policiesTable.test.js, ui/apps/platform/cypress/integration/policies/policyWizardStep3.test.js
branched off of the integrations test PR (https://github.com/stackrox/stackrox/pull/10653). skipping policy criteria modal tests for now since that code has not/will not ship in its current state
=> fix(ui): PF5 e2e fixes policies

ui/apps/platform/cypress/integration/collections/collectionsCrudWorkflow.test.js, ui/apps/platform/cypress/integration/collections/permissions.test.js, ui/apps/platform/cypress/integration/credentialExpiry/credentialExpiry.test.js, ui/apps/platform/cypress/integration/violations/Violations.selectors.js, ui/apps/platform/cypress/integration/violations/violations.test.js, ui/apps/platform/src/Components/PatternFly/FormLabelGroup.tsx
=> chore(ui): More PF 5 fixes for e2e tests

.github/actions/junit2jira/action.yaml, scripts/ci/lib.sh
https://github.com/stackrox/junit2jira/releases/tag/v0.0.19
responsible for the …
=> chore(deps): update junit2jira to v0.0.19

tests/upgrade/legacy_to_postgres_run.sh
=> fix: follow redirects when downloading roxctl

CHANGELOG.md, pkg/features/list.go, sensor/kubernetes/listener/resources/convert.go
Some merge conflicts for the 4.4.1 release milestone have been incorrectly resolved. This led to some unintended changes sneaking into the release branch. The offending commits are https://github.com/stackrox/stackrox/commit/4f003b05500096d80350c24c478793623b35b169 and https://github.com/stackrox/stackrox/commit/1b256ec9dc2bccebd6a76b3ec8405ccf795b8ee5.
Visual validation of what should have been merged.
=> fix: release 4.4.1 merge conflict resolution

roxctl/central/m2m/exchange/exchange.go, roxctl/central/m2m/exchange/exchange_test.go
Adds the `token-file` command to the m2m exchange command.
This is added cause of a use-case we had in a Tekton task where a scratch image is used and its thus not possible to read out files within scripts, to allow roxctl to read the token from a file path instead.
This also creates parity with the API token file flag we currently have.
- see CI.
=> chore(roxctl): add token-file flag for exchange command

govulncheck-allowlist.json
Remove "until" for these vulnerabilities so future patch releases do not have to deal with this. Also added a new vuln.
trivial
=> ROX-23544: resolve scan-go-binaries failures in 4.4

CHANGELOG.md
=> chore: Clarify introduction of streaming endpoints in CHANGELOG

central/sensor/service/connection/connection_impl.go, sensor/kubernetes/eventpipeline/pipeline_impl.go
=> Jv send runtime configuration to sensor DON'T REVIEW

central/scanner/handler.go, pkg/cloudsources/paladin/client.go, pkg/helm/charts/tests/centralservices/helmtest_test.go, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/collector-image.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/main-image.test.yaml, pkg/set/common.go, pkg/signatures/public_key_fetcher.go, pkg/testutils/matchers.go, roxctl/declarativeconfig/lint/lint.go, roxctl/helm/derivelocalvalues/derivelocalvalues.go, roxctl/image/check/check.go, roxctl/image/scan/scan.go, roxctl/summaries/policy/policy.go
I came across a few typos and decided to fix a couple of others as well.
CI
=> fix: various typos

ui/apps/platform/README.md
Counterpart to add from https://github.com/stackrox/stackrox/pull/9706/files#diff-926a04cede9dd8e863297243b51d305a52f6b11143242fb8d08663ffd1aec6e6R169-R173
=> chore(ui): Add missing step to delete a feature flag for CI in README

central/scannerdefinitions/handler/updater_test.go
Increase and test the new timeout
=> ROX-23561: Extend timeout in updater test

.github/workflows/tagged-ci.yaml, scripts/ci/lib.sh
This is handled by a workflow and the webhook is obsolete.
=> chore(CI): remove nightly slack webhook

pkg/env/notifier_secret_encryption.go
- ~ ] Determined and documented upgrade steps~
CI is enough
Manually create notifiers and upgrade to a version with env var enabled
=> ROX-23682: Enable ROX_CLEANUP_NOTIFIER_CREDS env var

pkg/clientconn/useragent.go, pkg/clientconn/useragent_test.go, pkg/testutils/ci.go, pkg/testutils/ci_test.go
* `IsRunningInCI()` to return true just if `CI` variable is defined, whatever the value;
* Added tests.
=> fix: setting CI tag in User-Agent

.github/workflows/retest_periodic.yml
In https://github.com/stackrox/stackrox/pull/10696 I removed go.mod from tools to be able to run tests in CI. This file was used by setup go action to determine Go version. Let's use `go.mod` instead.
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change only. …
=> fix: retest_periodic.yml

migrator/migrations/m_192_to_m_193_report_config_migrations/migration_impl.go
Report snapshots have a foreign key field ReportConfigID. So all report configurations must be added before the report snapshots. With the current implementation it is possible for snapshots to be added before the related report configs. This leads to the fk violation in the migration. This PR fixes the issue.
Manual testing by creating 23 (exceeding batch size boundary) report configs such that only 13 (does not exceed …
=> ROX-23638: Fix snapshots added before configs in migration

.tekton/main-pull-request.yaml, .tekton/main-push.yaml
Since the task is about to be closed.
These - not:
None.
=> chore: Remove mentions of ROX-20160 from comments

qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy
This PR replace duplicated code with a function
CI
=> chore: cleanup deployment creation in test

.github/actions/junit2jira/action.yaml, qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy, scripts/ci/lib.sh
Updates version of `junit2jira` to match latest: https://github.com/stackrox/junit2jira/releases/tag/v0.0.20
CI
=> chore(deps): update junit2jira to v0.0.20

image/postgres/konflux.Dockerfile, image/rhel/konflux.Dockerfile, image/roxctl/konflux.Dockerfile, operator/konflux.Dockerfile, scanner/image/db/konflux.Dockerfile, scanner/image/scanner/konflux.Dockerfile
Similar change as https://github.com/stackrox/collector/pull/1633
Only CI.
=> chore: Expand RHACS in Konflux Dockerfile labels

ui/apps/platform/cypress/integration/integrations/imageIntegrations.test.js, ui/apps/platform/cypress/integration/risk/deploymentTimeline.test.js, ui/apps/platform/cypress/integration/risk/podTimeline.test.js, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/QuayIntegrationForm.tsx
Changes are the result of discussion in the Jira ticket
1. Added checks for the new labels on those inputs to the ui-e2e-tests
2. Manually observed the changed labels and info box
=> ROX-23589: Clarify Quay integration auth fields

deploy/common/k8sbased.sh, tests/e2e/run-scanner-v4.bats
This PR is *not* anymore about increasing a wait timeout.
Instead we remove our custom (extremely underprovisioned) resource configuration and see how it goes.
Just CI.
Could well happen that this turns out to be somewhat flaky, in that case the plan is to pick a larger machine size.
=> ROX-23267: Standard resource config in Scanner V4 install tests 

ui/apps/platform/cypress/helpers/policies.js, ui/apps/platform/cypress/helpers/visit.js
attempting to make these more robust. followed the suggested options in the error/cypress documentation
=> ROX-23645, ROX-21933: Policy Wizard Step 3 test flakes

ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/cveDetailPage.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeCvesOverviewPage.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/nodeCves/nodeDetailPage.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/platformCves/clusterDetailPage.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/platformCves/cveDetailPage.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/platformCves/platformCvesOverviewPage.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/snoozeWorkflow.test.ts
Test plan implemented as Cypress test suite stubs for e2e/integration tests across Node and Platform CVE pages.
These will be backfilled when BE APIs become available.
None!
Verify that these test stubs do not run and do not cause failures in CI.
=> ROX-23026: Create integration test outline for node/platform cves

README.md, migrator/README.md
Remove some RocksDB stuff
~- [ ] Investigated and inspected CI test results~
provided convince any reviewer or any external reader …
=> ROX-23293: rocksdb readmes

.github/CODEOWNERS
Update Team Merlin's responsibilities to include also the signature related packages.
It is also acceptable to skip testing for changes that are too taxing to test before merging. In such case you …
=> chore(CODEOWNERS): update Merlin's responsibilities

sensor/kubernetes/listener/watcher/crd/crdwatcher_test.go
Remove the random CRD creation to make the test deterministic.
=> fix(test): Remove randomness in the watcher test

central/administration/events/datastore/internal/writer/writer_impl.go, central/cluster/service/service_impl.go, central/declarativeconfig/manager_impl.go, central/declarativeconfig/watch_handler.go, central/declarativeconfig/watch_handler_test.go, central/detection/service/service_impl.go, central/pruning/pruning.go, operator/pkg/proxy/extension.go, pkg/declarativeconfig/access_scope.go, pkg/declarativeconfig/permission_set.go, pkg/gjson/modifiers.go, pkg/maputil/maputil.go, pkg/printers/sarif.go, pkg/registrymirror/store.go, pkg/sliceutils/concat.go, pkg/sliceutils/extra_types.go, pkg/sliceutils/map.go, roxctl/declarativeconfig/create/access_scope.go, roxctl/declarativeconfig/create/auth_provider.go, roxctl/declarativeconfig/create/notifier.go, roxctl/declarativeconfig/create/permission_set.go, scanner/matcher/updater/distribution/updater.go, scanner/services/matcher.go
Took some time to reevaluate the necessity of these functions and did some cleanup
Any replacements are essentially the same implementation, so no …
=> chore: cleanup usage of sliceutils and maputil

central/sensor/service/pipeline/networkflowupdate/pipeline.go, pkg/centralsensor/caps_list.go, sensor/common/networkflow/manager/manager_impl.go
(cherry picked from commit ec23204)
Manual cherry-pick for the release 4.4.2
=> ROX-23540: Central cap to display Internal Entities in the NWG (#10698)

sensor/kubernetes/listener/watcher/complianceoperator/availabilitychecker.go
Add ComplianceRemediation to CRD availability
- CI
=> chore(fix): Add ComplianceRemediation to CRD availability

qa-tests-backend/Makefile, qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
**This is just to trigger CI**
Testing new debug logs.
responsible for the change …
=> ROX-19615: Network Graph Flake

ui/apps/platform/src/Components/KeyValueListModal.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx
This PR adds the annotations column to the namespace view table
=> ROX-23565: Adding annotations to namespace view

.github/workflows/scanner-db-init-dump.yaml
responsible for the change after it gets merged which includes reverting, fixing, …
=> fix(scanner): Fix db init updater call

migrator/migrations/m_192_to_m_193_report_config_migrations/migration_impl.go, pkg/env/notifier_secret_encryption.go
Cherry pick changes for PRs #10736 (commit: [42d2ae8](https://github.com/stackrox/stackrox/commit/42d2ae80af4c11f54e972c3d91cff854235bf127)) and #10757 (commit: [bf70a92](https://github.com/stackrox/stackrox/commit/bf70a929ac66159f91e0a82ae50e129f86a9dbab))
Cherry picked changes. So CI is enough
In addition to reviewing code here, reviewers **must** also review testing and …
=> fix: cherry pick fixes for ROX-23682 and ROX-23638

scanner/decisions/0009-scannerv4-read-manual-vulnerabilities.md
Upgrade the current manual vuln updating process
=> ROX-23591: ADR for improving the current manual vuln updating process

pkg/gjson/slices.go, pkg/printers/sarif.go, pkg/printers/sarif_test.go
(cherry picked from commit cf5e7f5481abb7be08966009f0ee7f49902062e3)
=> fix(sarif): nil array should not have placeholder value (#10928)

.devcontainer/devcontainer.json, .github/workflows/batch-load-test-metrics.yml, .github/workflows/build.yaml, .github/workflows/ci-failures-report.yml, .github/workflows/lint.yml, .github/workflows/scanner-build.yaml, .github/workflows/scanner-db-init-dump.yaml, .github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-release-vuln-update.yaml, .github/workflows/style.yaml, .github/workflows/unit-tests.yaml, .openshift-ci/Dockerfile.build_root, BUILD_IMAGE_VERSION, go.mod, scale/signatures/deploy.yaml, tests/e2e/run-e2e-tests.sh
Bump Go to latest 1.21 version.
Related OSCI PR: https://github.com/openshift/release/pull/51510 (pending because image is being mirrored into the build server registry)
It is also acceptable to …
=> chore: bump Go version to 1.21.9

tests/e2e/run-scale.sh
This should fix scale tests failing in 4.3 branch. 
Checklist above
=> fix(release): pin prometheus-metrics-parser

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/PlatformCvesByStatusSummaryCard.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/PlatformCvesByTypeSummaryCard.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/useClusterSummaryData.ts, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SummaryCardLayout.cy.jsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SummaryCardLayout.tsx
As titled.
Visit a Platform CVE cluster page:
Loading:
Error:
Success:
With a fixability filter:
=> ROX-23075: Add cluster page summary cards

tests/upgrade/postgres_run.sh
=> ROX-23441:  upgrade test collector image tag

central/debug/service/service.go, pkg/postgres/stats/stats.go
This PR adds dead tuple and analyze stats for the database to the diagnostic bundle.  These can sometimes be helpful in performance issues to see if we may want to force an analyze of a certain table or perform a vacuum to clear out dead data.  It just gives us more insight into the health of the database overall.
A likely follow on to this is an API to force an analyze on a table and/or the entire database.
These 2 files are the results of this change to the diagnostic bundle:
[central-db-pg-analyze-stats.json](https://github.com/stackrox/stackrox/files/15201805/central-db-pg-analyze-stats.json)
[central-db-pg-tuples.json](https://github.com/stackrox/stackrox/files/15201806/central-db-pg-tuples.json)
~- [ ] Evaluated and added CHANGELOG entry …
=> ROX-23754: postgres dead tuples and analyze stats

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx
As titled
Requests are currently mocked, so validate that the parameters are being set by changing the "perPage" value in the UI and verifying that the value is tracked in the URL and sent in the request:
=> ROX-23074: Add pagination to cluster page vuln table

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/useAffectedClusters.ts
As titled.
Requests are currently mocked, so validate that the parameters are being set by changing the "perPage" value in the UI and verifying that the value is tracked in the URL and sent in the request:
=> ROX-23065: Adds pagination control to Platform CVE page cluster table

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx
Once again, as titled.
Requests are currently mocked, so validate that the parameters are being set by changing the "perPage" value in the UI and verifying that the value is tracked in the URL and sent in the request:
=> ROX-23048: Add pagination control to node page table

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
Workaround for a Workload CVE issue where CVEs show up twice in Deployment CVE lists. This leads to two problems:
1. It isn't clear to the user why a CVE is displayed twice in the list as both entries appear identical
2. Since multiple entries have the same "CVE" field, when expanding/collapsing a row, all entries with a matching CVE name will expand/collapse
This is due to our usage of the `imageVulnerabilities` resolver on this page, instead of the newer `imageCVEs` resolver used on the list page which de-duplicates CVEs that are the same across multiple operating systems.
The fix for each issue is:
1. Add a new column "OS" that shows the operating system affected by the CVE, which gives some indication as to why there are duplicate rows.
2. Use the CVE `id` field instead of `cve` field …
=> ROX-24037: Add OS column to improve UX when duplicate CVEs

.tekton/basic-component-pipeline.yaml, .tekton/determine-image-tag-task.yaml, .tekton/main-pipeline.yaml, .tekton/scanner-v4-pipeline.yaml, CHANGELOG.md, pkg/features/list.go, pkg/registries/docker/registry_without_digest_call.go, pkg/registries/docker/registry_without_digest_call_test.go, scripts/ci/jobs/aro_qa_e2e_tests.py
=> use a taskref for determine-tag-task

ui/apps/platform/src/Components/CompoundSearchFilter/components/AttributeSelector.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundFilterInputField.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/EntitySelector.tsx
Adds a CompoundSearchFilter component with the initial EntitySelector child component
=> ROX-23504: Adding CompoundSearchFilter component

sensor/tests/complianceoperator/crd_test.go, sensor/tests/helper/helper.go, tests/complianceoperator/crds/compliancecheckresults.yaml, tests/complianceoperator/crds/ns.yaml, tests/complianceoperator/crds/profiles.yaml, tests/complianceoperator/crds/rules.yaml, tests/complianceoperator/crds/scansetting.yaml, tests/complianceoperator/crds/scansettingbindings.yaml, tests/complianceoperator/crds/tailoredprofiles.yaml
Adds an integration tests for the CRD watcher.
=> ROX-2389: Add integration test for CO CRDs detection

central/views/imagecve/view_impl.go
The SQL query to return the data needed for Workload CVEs landing performs 10 different aggregates for each CVE. Now when we paginate the query to only return 20 CVEs per page, those 10 aggregates are computed only for those 20 CVEs. So far so good.  But when we chose to sort by one of those aggregates, we get timeouts. Looking at the query plan, we can see that when asked to sort by one of the aggregates, postgres applies all 10 aggregates on all the rows and then returns top 20 results from that. This takes a lot of time. We just want to sort by one aggregate. So if we can compute that one aggregate for all rows, select the top 20 CVEs and then apply remaining aggregates for those 20 CVEs, it would save a lot of time.
SQL Plan before :
```
Limit  (cost=3346.12..3346.17 rows=20 …
```
=> ROX-19123: Fix workload CVEs performance issue

scripts/ci/metrics.sh
This is a slightly modified (more DRY and with improved naming) piece of #10822 from @janisz with additional support for saving/loading of metrics from the image prefetcher.
None, really, because I don't think I have the permissions to write to that GCS bucket nor bigtable.
=> tests: central and image prefetches metrics

CHANGELOG.md, roxctl/image/scan/cve.go, roxctl/image/scan/cve_test.go, roxctl/image/scan/scan.go, roxctl/image/scan/scan_test.go
Cherry-pick #10936 for the release.
- see CI. 
=> fix: cherry-pick #10936

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx, ui/apps/platform/src/services/ComplianceResultsService.ts
Adds pagination to the Compliance V2 Profile Checks table
=> ROX-24097: Profile checks table pagination

ui/apps/platform/src/Components/CompoundSearchFilter/components/AttributeSelector.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/EntitySelector.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/SimpleSelect.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/types.ts, ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.test.ts, ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.ts, ui/apps/platform/src/Components/SelectSingle/SelectSingle.tsx
This PR includes the following:
1. Creating the `AttributeSelector` component
2. Usage of the PF5 Select Component (will be a one-off for now, but we may consider pulling it up to the components directory and further extending the capabilities)
3. Fixing up Types
4. Creating util functions to encapsulate logic and make things simpler to follow
5. Tests!
=> ROX-23506: Adding attribute selector

migrator/migrations/m_199_to_m_200_policy_updates_for_4_5/migration.go, migrator/migrations/m_199_to_m_200_policy_updates_for_4_5/policies_before_and_after/after/access_central_secret.json, migrator/migrations/m_199_to_m_200_policy_updates_for_4_5/policies_before_and_after/before/access_central_secret.json, pkg/defaults/policies/files/access_central_secret.json
Some years ago the default namespace for the operator deployment has changed. The policy should've been adjusted at that point but was not. i.e the policy was wrong for years. We never had false positive alerts because the policy only matches get operations on that secret. Up to this [change](https://github.com/stackrox/stackrox/pull/10302), the operator only ever sent list requests to fetch secrets (it would never send a direct get for central-htpasswd) . With the change the operator started to also send get requests, which violate the policy because it has not been updated.
Updating the policy to include both service accounts (old and new) names (which reference namespace names) as k8s user names.
Use this space to …
=> ROX-23372: Additional SA name in default policy criteria value

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/DetailsPageHeader.tsx, ui/apps/platform/src/services/ComplianceResultsService.ts, ui/apps/platform/src/services/ComplianceResultsStatsService.ts
This PR adds the check details page's page header:
1. A new service function named `getComplianceProfileCheckStats` was created
2. Moved around common variables between files
3. A new reusable component called `DetailsPageHeader` was created
=> ROX-23999: Adding check details page page header

.tekton/central-db-pull-request.yaml, .tekton/central-db-push.yaml, .tekton/main-pull-request.yaml, .tekton/main-push.yaml, .tekton/operator-pull-request.yaml, .tekton/operator-push.yaml, .tekton/roxctl-pull-request.yaml, .tekton/roxctl-push.yaml, .tekton/scanner-v4-db-pull-request.yaml, .tekton/scanner-v4-db-push.yaml, .tekton/scanner-v4-pull-request.yaml, .tekton/scanner-v4-push.yaml
Historical references:
* https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1713181360407219
* https://docs.google.com/document/d/1c4ssQ6tNBksQXHYjaL_T8KSFpIZIYeRR7l3yUhJn-cE/edit
Just checked that images are there:
```
docker manifest inspect "quay.io/rhacs-eng/main:$(make tag)-fast" >/dev/null && echo "main ok"
docker manifest inspect "quay.io/rhacs-eng/central-db:$(make tag)-fast" >/dev/null && echo "central-db ok"
docker manifest inspect "quay.io/rhacs-eng/stackrox-operator:$(make tag)-fast" >/dev/null && echo "stackrox-operator ok"
docker manifest inspect "quay.io/rhacs-eng/roxctl:$(make tag)-fast" >/dev/null && echo "roxctl ok"
docker manifest inspect "quay.io/rhacs-eng/scanner-v4-db:$(make tag)-fast" >/dev/null && echo "scanner-v4-db ok"
docker manifest …
```
=> ROX-22474: Push Konflux-built containers to quay.io/rhacs-eng

central/scannerdefinitions/handler/handler.go
1. Break the path for V2 and V4 handlers early. Although they still use common methods under the hood, this makes it simpler to navigate and update the code in the future.
2. Separate offline and online handling into different methods, putting the `switch` decision on the updater type in obvious places.
3. Change the updater creation method (`getUpdater()`) to accept a "URL path" to the desired updater file. The updater will check the updater type to derive the actual update URL based on the path. 
We are still doing logic per updater type inside the open methods, both online and offline. I decided to keep it there for now to control the scope of this refactoring.
The purpose of this is to make it simpler to add, remove, or update updater definitions formats, versions, etc.
If any of …
=> refactor(central): defs: Simplify vulnerability definition handling

dev-tools/roxctl.sh
Support fedora for roxctl wrapper
- Run `./dev-tools/roxctl.sh` on fedora
=> chore(scripts): Support md5sum in roxctl wrapper

ui/apps/platform/src/Containers/AccessControl/PermissionSets/ResourceDescription.tsx
Fixes the description for the WorkflowAdministration resource which has replaced the policy and vulnerability reports resources.
N/A 
=> fix(ui): description for WorkflowAdministration resource

ui/apps/platform/cypress.config.js, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/types.ts
This PR adds the `date-picker` option 📅 to the compound search filter 🔍
=> ROX-23510: Adding the date-picker to the compound search filter

.openshift-ci/debug-tips.md
Add OpenShift CI debug tips
- /
=> chore(docs): Add OpenShift CI debug tips

image/templates/helm/stackrox-secured-cluster/README.md.htpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, image/templates/helm/stackrox-secured-cluster/values-public.yaml.example, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/base-config.test.yaml
This is a sub-ticket of [ROX-23467](https://issues.redhat.com/browse/ROX-23467).
This PR:
* improves documentation within the secured-cluster-services Helm chart.
* introduces sanity checks within the Helm templating code to make the feature more robust.
It is acceptable to skip testing in cases when CI is …
=> ROX-23720: Sanity check and doc improvements for clusterLabels

pkg/postgres/pgtest/postgres.go
Add documentation for postgres table usage
- CI
=> chore(docs): Add documentation for postgres table usage

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ObservedCveModeSelect.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
Adds integration tests for the with and without CVE view modes.
Local Cypress runs, CI
=> chore(ui): without cves view e2e tests

CHANGELOG.md, roxctl/central/generate/k8s.go, roxctl/sensor/generate/openshift.go
Let roxctl default to OpenShift 4 for generating sensor and central deployment bundles
It is acceptable to skip testing in cases when CI is …
=> ROX-14990: roxctl default to OpenShift 4

.github/workflows/cut-rc.yml, .github/workflows/finish-release.yml, .github/workflows/start-release.yml
Co-authored-by: Gavin Jefferies <gjefferi@redhat.com>
(cherry picked from commit eb3433f813ae93c19b3e20ca0c607f4df0413c66)
It is acceptable to …
=> chore(ci): switch to rhacs-bot (#143) (#8756)

.github/workflows/build.yaml
See the [diff](./11261/files).
CI
=> fix: `GITHUB_TOKEN` secret name

central/postgres/pruning.go, central/postgres/pruning_test.go, central/processindicator/datastore/datastore.go, central/processindicator/datastore/datastore_impl.go, central/processindicator/datastore/datastore_impl_test.go, central/processindicator/datastore/mocks/datastore.go, central/pruning/pruning.go, central/pruning/pruning_test.go
improve process indicator pruning
(cherry picked from commit 7c8c6a6800d27efd86453fed861c2c87c6ee37f5)
=> ROX-23630: [BACKPORTING] indicator pruning (#11005)

scripts/ci/jobs/gke_operator_e2e_tests.py, scripts/ci/jobs/gke_perf_scale_tests.py, scripts/ci/jobs/gke_upgrade_tests.py, scripts/ci/jobs/ocp_operator_e2e_tests.py, scripts/ci/jobs/ocp_perf_scale_tests.py, scripts/ci/lib.sh
Preparation for use of image-prefetcher in other e2e tests where ORCHESTRATOR is defined.
=> refactor(image-prefetcher): use ORCHESTRATOR var

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsTable.tsx, ui/apps/platform/src/services/ComplianceResultsService.ts
Adds pagination to the Compliance V2 Check Details table
Pagination:
Page 2:
=> ROX-24001: Check details pagination

ui/apps/platform/src/Containers/AccessControl/PermissionSets/ResourceDescription.tsx
[Backport release-4.4] fix(ui): description for WorkflowAdministration resource (#11138)
=> chore: Backport #11138 to release-4.4

ui/apps/platform/src/Containers/VulnMgmt/List/Images/VulnMgmtListImages.js
Removes the watched images UI from VM 1.0 when VM 2.0 is marked as GA. This should be the final step that makes VM 1.0 read-only.
With the feature flag disabled, visit the VM 1.0 image list page. See the "Manage watches" button in the header as well as "Scanning via watch tag" text in the table for images currently being watched.
With the feature flag enabled, both of the above UI elements are removed.
=> chore(ui): disable watched images UI in vm 1.0
