- scanner/go.mod
Bleve was removed in https://github.com/stackrox/stackrox/pull/6524, so we no longer need this replace in Scanner's go.mod
nah
> chore(scanner): remove bleve from go.mod

- .github/workflows/unit-tests.yaml
- compliance/collection/auditlog/auditlog_impl_test.go
These changes (temporarily) fix the permission issues in the go dep caches GitHub actions.
Reverts https://github.com/stackrox/stackrox/pull/6344 and https://github.com/stackrox/stackrox/pull/6601
Relevant Slack threads:
- https://redhat-internal.slack.com/archives/CELUQKESC/p1687878824317229
- https://redhat-internal.slack.com/archives/C0321S70YK1/p1687874219753839
CI
> fix(check-pr): Revert "ROX-14204: enable `TestReaderReturnsErrorIfFileExistsButCannotBeRead` (#6344)"

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/HelpIconTh.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/LastRunState.test.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/LastRunState.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/LastRunStatusState.test.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/LastRunStatusState.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/types.ts
- ui/apps/platform/src/services/ReportsService.ts
- ui/apps/platform/src/types/report.proto.ts
- ui/apps/platform/src/types/reportConfigurationService.proto.ts
This PR adds a simple version of the table to be used to display the reports. I added one report to the table to show an example of what will be displayed. The error icon in the "Last run status" column will display a tooltip with the error message. If, for some reason, no error message is populated then we'll use a generic error message. Also, note that we will be merging the report configuration with the last run report status and the report status to display in the table. I added types for each and a merged type as well
> ROX-17814: Show a simple vulnerability reports table

- pkg/sync/mutex_dev.go
`TryLock` will panic if `acquireTime` isn't set for `mutex_dev`. 
This is a follow-up from #6602. 
- CI
- Tested in #6602
> ROX-11462: implement TryLock on mutex_dev wrapper

- central/main.go
- pkg/grpc/endpoints.go
- pkg/grpc/server.go
- pkg/grpc/server_test.go
- pkg/sync/mutex_dev.go
This is a refactor in `pkg/grpc` to allow calling `.Stop()` on a gRPC server and stopping all TCP listeners underneath (for gRPC and HTTP multiplexers).
With the current code is not possible to start two servers in separate tests. The server is bound to the lifecycle of Go runtime, and it should never stop unless the process exists.
This makes writing unit and integration tests in Sensor (and presumably in Central) much harder. You can't have two tests that start a gRPC server in the same file or package.
This was attempted sometime ago (#2130) but it was dropped in favor of simply running sensor integration tests in separate `go test` commands (see #2202). 
In order to close this technical debt and allow us to write tests starting and stopping the gRPC server multiple times, this PR aims …
> ROX-11462: Allow graceful stop on `pkg/grpc`

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
Fix the `Verify intra-cluster connection via external IP` e2e test by checking the edge with external sources instead the new deployment.
* CI
> ROX-7046: check edge with external sources in NetworkFlowTest

- roxctl/central/debug/dump.go
- roxctl/central/initbundles/constants.go
- roxctl/central/initbundles/fetch_ca.go
- roxctl/central/initbundles/generate.go
- roxctl/central/initbundles/initbundles.go
- roxctl/central/initbundles/list.go
- roxctl/central/initbundles/revoke.go
- roxctl/cluster/cluster.go
- roxctl/collector/supportpackages/upload/command.go
- roxctl/collector/supportpackages/upload/upload.go
- roxctl/common/flags/timeout.go
- roxctl/deployment/deployment.go
- roxctl/helm/derivelocalvalues/command.go
- roxctl/helm/derivelocalvalues/command_test.go
- roxctl/helm/derivelocalvalues/derivelocalvalues.go
- roxctl/scanner/scanner.go
- roxctl/scanner/uploaddb/uploaddb.go
- roxctl/scanner/uploaddb/uploaddb_test.go
- roxctl/sensor/sensor.go
This PR introduces configurable timeouts for all roxctl commands that require it and also adjusted the default timeout from 30 seconds to 1 minute.
The reason for changing the default timeout is due to context deadline exceed flakes seen in CI.
Below is a table that encompasses all changes, showing the previous timeout and notes about changes made:
| Command                           | Previous timeout | Changes made                                                                                               |
| --------------------------------- |:----------------:| ----------------------------------------------------------------------------------------------------------:|
| central backup                    | 1h               | - …
> ROX-11796, ROX-16835, ROX-17416: Fix timeouts for roxctl

- roxctl/scanner/generate/generate.go
After refactoring the timeout, the timeout flag wasn't added to the generate command for scanner.
This fixes that.
- see CI.
> ROX-18145, ROX-18144, ROX-18143, ROX-18142, ROX-18141: Fix scanner generate test

- ui/apps/platform/cypress/integration/clusters/delegateScanning.test.js
- ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesList.tsx
- ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedScanningSettings.tsx
- ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx
- ui/apps/platform/src/types/dedicatedRegistryConfig.proto.ts
This is an incremental change to allow selecting whether all internal registries will use the same default cluster, or whether the user will specify that certain registries will use each their own specific cluster.
Follow-up:
1. Picking the default cluster from a list of available clusters will come in a later PR.
2. Adding and listing specific registries and their specific cluster to use for scanning will come in another later PR.
(Note: I investigated using Formik to manage the state, but because one backend concept, the `enabledFor` property, is split between the checkbox and radio buttons in the design, and the form object isn't that complicated, I elected not to add the extra Formik handling.)
With ALL selected
With SPECIFIC selected
e2e test run locally
> ROX-17738: Allow selecting ALL or SPECIFIC registry setting

- central/cluster/datastore/datastore.go
- central/cluster/datastore/datastore_impl.go
- central/postgres/pruning.go
- central/pruning/pruning.go
- central/pruning/pruning_test.go
Try deflaking the node sac test by running serially
Unit tests. Ran `go test -failfast -tags sql_integration . --count 500` locally in the directory. Was failing consistently and now passes
> fix(test): Fix node datastore sac test by pruning orphaned nodes

- qa-tests-backend/src/test/groovy/AuditLogAlertsTest.groovy
Third time is a charm.
ROX-18030: AuditLogAlertsTest: Extend timeout to flush out outliers (#6649)
ROX-18030: AuditLogAlertsTest: Wait longer for violations to appear (#6639)
> ROX-18030: AuditLogAlertsTest: Wait for the policy to propagate

- ui/apps/platform/package.json
- ui/packages/ui-components/package.json
- ui/yarn.lock
https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=milestone%3A%22TypeScript+5.1.5%22+is%3Aclosed+
Fix a few regressions which would break the build if we hit them:
* stack overflow
* heap out of memory
* compiled code can contain JSX
> chore(ui): Update TypeScript 5.1.5 devDependencies

- pkg/auth/authproviders/openshift/backend_impl.go
- pkg/notifiers/generic/generic.go
ROX-18137.
The `service-ca.crt` is a self-signed CA certificate, which issues internal certificates for services annotated with `service.alpha.openshift.io/serving-cert-secret-name`, like the future vector aggregator:
```
subject=CN = openshift-service-serving-signer@1687766551
issuer=CN = openshift-service-serving-signer@1687766551
```
Deployed test `hop` HTTPS server to the default namespace with an Openshift service signed certificate:
```
Certificate chain
0 s:CN = hop.default.svc
i:CN = openshift-service-serving-signer@1687766551
a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
v:NotBefore: Jun 26 10:43:37 2023 GMT; NotAfter: Jun 25 10:43:38 2025 GMT
1 s:CN = openshift-service-serving-signer@1687766551
i:CN = openshift-service-serving-signer@1687766551
a:PKEY: rsaEncryption, …
```
> ROX-18137: Generic notifiers to trust `serviceaccount/service-ca.crt`

- sensor/tests/resource/pod/pod_test.go
This happens due to this change in the k8s listener PR: https://github.com/stackrox/stackrox/pull/6376#discussion_r1246370815
Failing tests were ignored and the PR was merged prematurely. 😞 
This should fix the failing `Test_PodHierarchy`.
> ROX-18147: Fix pod hierarchy test flake

- README.md
Customers rarely deploy secured-cluster-services to the same namespace as Central. 
To provide a convinient way to copy the Helm command I've added the `centralEndpoint` parameter.
Additionally for re-usability if no Central was installed before the `--create-namespace` flag is provided.
To reuse the command after installation the command uses now `upgrade --install` as an option
- Install secured cluster service with changed command
> fix(readme): Update Helm command to install secured-cluster-services

- central/metadata/service/service_impl.go
- central/metadata/service/service_impl_test.go
- pkg/errox/roxerror.go
In case of absent TLS challenge, the error message currently looks like this:
```
{"error":"base64 decoded challenge token must be 32 bytes long, got : invalid arguments","code":3,"message":"base64 decoded challenge token must be 32 bytes long, got : invalid arguments","details":[]}
```
which is hard to parse, especially if the challenge is empty.
This PR ensures that the challenge appears in quotes to enhance readability. 
CI run with a newly added test; manual check of the returned error message.
> refactor: Update TLSChallenge error messages for clarity

- qa-tests-backend/src/main/groovy/services/BaseService.groovy
- qa-tests-backend/src/test/groovy/AuthServiceTest.groovy
- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
- qa-tests-backend/src/test/groovy/RbacAuthTest.groovy
This PR changes BaseService.groovy, the class that manages the central gRPC channel for test, to use ThreadLocal vars for static state. Which helps prepare for groovy tests to run concurrently.
CI is sufficient - ci-all-qa-tests - this ensures that the changes are benign at this point i.e. before tests actually run in parallel. Experimentation in https://github.com/gavin-stackrox/spock-example/blob/master/src/test/groovy/stackrox/BaseService.groovy confirms it as a reasonable way to provide thread local state.
> ROX-17963: Make service auth thread safe

- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
Per title.
CI and `/test eks-qa-e2e-tests` to check that there are no regressions. In a parallel test environment this would only run concurrently if the test spec features are mult-threaded which is unlikely.
> ROX-17499: Make EKS orchestrator reset thread safe

- qa-tests-backend/src/test/resources/logback-test.xml
When tests are running concurrently it will be useful to know which thread is generating a log message. Note: this is not intended as the final PR to deal with test output in a concurrent test world but merely a necessary first step. Also, if the pattern gets more complicated we should invest in a custom layout: https://logback.qos.ch/manual/layouts.html.
> ROX-17965: Add thread to logs

- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/CreateVulnReport/CreateVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReportingPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/hooks/usePageAction.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/hooks/usePageState.ts
- ui/apps/platform/src/routePaths.js
This PR adds the following things:
- Some extra paths were created for the following states: `create`, `edit` (to be used in the future), and `clone` (to be used in the future)
- Clicking on `Create report` will take you to the page for creating a report
- The route for the page for creating a report will be conditionally added based on permissions
- A very basic page for creating a report was added (like just a page header type of basic)
https://github.com/stackrox/stackrox/assets/4805485/c2f209f7-f785-46ee-9e1e-ac92797c3ea1
> ROX-17827: 'Create report' should start the creation process

- qa-tests-backend/Makefile
- qa-tests-backend/build.gradle
- qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
- qa-tests-backend/src/test/resources/ParallelSpockConfig.groovy
This PR creates a tag to use to denote test specifications that could run in parallel with other tests and picks DeclarativeConfigTest.groovy as the first candidate.
> ROX-17502: Add a slot for parallel testing

- central/metadata/service/service_impl.go
- central/metadata/service/service_impl_test.go
- generated/api/v1/metadata_service.pb.go
- generated/api/v1/metadata_service.swagger.json
- proto/api/v1/metadata_service.proto
Prior to this patch, Metadata service was giving unauthenticated access to all of its endpoints by default. Some endpoints, however, overrode this behavior in their handlers.
This PR refactors authorization in the Metadata endpoint so that it follows the per-service authorizer pattern used in the codebase. The default is changed to "deny" and every service's endpoint is explicitly called out in the authz map. This ensures consistent error messaging and more importantly prevents giving public access to future endpoints in this service by oversight.
- `ci/prow/gke-sensor-integration-tests` is a known flake, https://issues.redhat.com/browse/ROX-18148
CI run;
Manual test verifying calls to the affected endpoints behave the same w.r.t. authentication.
> refactor: Metadata service authorization is explicit

- central/metadata/service/service_impl.go
Originally, `/v1/database/status` was open to the world to allow consumers—primarily ACS UI—to to zero in on the problem with the database before authentication because rendering login screen requires fetching info on auth providers from the database. However, ACS UI does not call this endpoint from the login screen and apparently does not plan to do so in the nearest future.
Given the primary use case is off the table, this PR tightens access for the endpoint to only authenticated users.
Manual test in the last PR of the chain, see https://github.com/stackrox/stackrox/pull/6718.
> ROX-18173: Authenticate 'v1/database/status'

- ui/apps/platform/cypress/integration/audit/listeningEndpoints/ListeningEndpoints.helpers.js
- ui/apps/platform/cypress/integration/audit/listeningEndpoints/listeningEndpointsTable.test.js
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/routePaths.js
Adds a route handler and page stub for the "Listening endpoints" page that will display what processes/ports are exposed on deployments.
The current design is in progress and displays the page under a new top level nav item titled "Audit" with a child item called "Listening endpoints". The URL structure follows the anticipated navigation.
Manually visit the `/audit/listening-endpoints` URL and view the page stub.
> ROX-17950: Add hidden page route for listening endpoints

- central/mitre/service/service_impl.go
Originally, 'v1/mitreattackvectors/*' were open to the world because they have nothing to hide. However, to reduce our surface for DoS attacks, this PR tightens access for the endpoints to only authenticated users.
- `ci/prow/gke-sensor-integration-tests` failure is a known flake: https://issues.redhat.com/browse/ROX-18153 
Manual test in the last PR of the chain, see https://github.com/stackrox/stackrox/pull/6718.
> ROX-18173: Authenticate 'v1/mitreattackvectors/*'

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/CreateVulnReport/CreateVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx
This PR adds a new `ReportParametersForm` component that will eventually keep track of the form fields in the `Configure report parameters` section of the wizard. This simply creates the component and adds the header + subheader. Eventually, we'll make form components for each wizard step. I'm imagining passing the state and setter function for the form values to each form component and we'll keep track of it all in the parent component
> ROX-17835: show header and subheader for report parameters section

- operator/apis/platform/v1alpha1/central_types.go
- operator/apis/platform/v1alpha1/common_types.go
- operator/apis/platform/v1alpha1/securedcluster_types.go
The `+kubebuilder:validation:Default` is not a valid kubebuilder marker
see https://book.kubebuilder.io/reference/markers/crd-validation.html
https://github.com/kubernetes-sigs/controller-tools/blob/47cdd8814d6dce89accf5496f0c369685dcd1894/pkg/crd/markers/validation.go#L38
> ROX-17712: Remove deprecated kubeBuilder markers

- ui/apps/platform/cypress/integration/clusters/delegateScanning.test.js
- ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedScanningSettings.tsx
- ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx
This adds the same type of cluster selector that is used in Network Graph 2.0, to select a cluster that roxctl will use as the default scanner for ad-hoc scans in private registries local to the customer's internal network.
Possible followup:
Consolidate selectors for clusters, namespaces, and deployments into one shared spot for all sections of the app to use.
On initial load, with no cluster selected
Cluster dropdown open
Cluster selected
CI test run locally
> ROX-17739: Input for specifying default adhoc cluster

- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/CreateVulnReport/CreateVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx
This PR adds the `Report scope` (ie. A collection) to scope the clusters/namespaces/deployments the user would like to get a vuln report for. I am reusing the `CollectionSelection` component we use in the old reporting feature
https://github.com/stackrox/stackrox/assets/4805485/074e20df-cbd7-45fd-842b-d66ae41f2ec3
https://github.com/stackrox/stackrox/assets/4805485/3e6b9da8-aecb-456b-afc8-ac5ded1f7c7c
> ROX-17837: Adding a field for report scope

- ui/apps/platform/src/Components/PatternFly/CheckboxSelect.tsx
- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/CreateVulnReport/CreateVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx
- Creates a hook called `useReportFormValues`. This defines the types of form values. It also allows us to reuse the hook between the `CreateVulnReportPage`, `EditVulnReportPage`, and `CloneVulnReportPage`.
- Creates a component called `ReportParametersForm`, which will render the fields used in the wizard's first step. We will pass the state value and state setter for the hook to this component to update the form values. Since we're keeping track of the form value state in the parent component, the values persist between wizard steps.
- Updated the `CheckboxSelect` to allow passing a custom placeholder text.
https://github.com/stackrox/stackrox/assets/4805485/56482cbb-22d4-4445-b1fc-4e01ee8d31df
> ROX-17836: Adding fields for report parameters

- sensor/kubernetes/eventpipeline/output/output.go
- sensor/kubernetes/eventpipeline/output/output_impl.go
- sensor/kubernetes/eventpipeline/resolver/resolver.go
- sensor/kubernetes/eventpipeline/resolver/resolver_impl.go
This is a known issue when we stop sensor. There are some race conditions when we stop some of the components and consequently a component that is still running might try to write in a channel that was already closed in another component. We have plans to organize the start up and stopping of components to address this but in the mean time we make sure to not write in the inner channels in the `outputQueue` and the `Resolver` components.
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rh …
> ROX-17895: Don't write the inner channels if the component is stopped

- pkg/buildinfo/buildinfo.go
- pkg/buildinfo/buildinfo_intest.go
- pkg/buildinfo/buildinfo_notest.go
- pkg/version/version.go
- pkg/version/version_test.go
We want to detect `release && test` builds to disable telemetry for them.
Unit tests.
> fix: detect test builds

- central/metadata/service/service_impl.go
- sensor/common/centralclient/client.go
- sensor/common/centralclient/client_test.go
- sensor/common/centralclient/grpc_connection.go
Originally, `/v1/metadata` was open to the world to serve license information and enable ACS UI to prompt user to enter a license on the login screen. However, licensing has been removed from the product and now we can tighten access for the endpoint to only authenticated users.
Since Sensor needs on a public endpoint to test connection to Central, `/v1/metadata` is replaced by `/v1/ping`.
- CI failure is a known flake: https://issues.redhat.com/browse/ROX-17416
Deployed `4.1.x-259-g9faa2d010e` and checked that:
* `v1/database/status`, `v1/mitreattackvectors/*`, `v1/metadata` require authentication
* `v1/ping` and `v1/tls-challenge` do not
* Sensor's can connect to Central
* UI seems to function normally
> ROX-18173: Authenticate 'v1/metadata'

- sensor/kubernetes/listener/resources/deployment_store.go
- sensor/kubernetes/listener/resources/pod_store.go
- sensor/tests/connection/connection_test.go
- sensor/tests/connection/k8sreconciliation/reconcile_test.go
- sensor/tests/helper/helper.go
- sensor/tests/replay/alerts/replay_alerts_test.go
- sensor/tests/replay/resources/replay_resources_test.go
Deployment objects were not being cloned on `Get()` and `GetAll()`, this caused data races to happen if the deployment resolver would process a deployment that is still in the pipeline (i.e. in the detector).
This PR makes sure that we clone all deployments so the pointer properties are not changed while the deployment object is being read.
The caveat here is that we are introducing a high number of Clones that weren't there before, which can cause significant resource consumption. 
There will be a follow-up investigation to see if they are significantly impacting the performance. 
> ROX-18148: Fix data race

- qa-tests-backend/src/main/groovy/services/BaseService.groovy
#6590 changed the test<->central channel state to use ThreadLocal variables. The intent being that each concurrent test thread would not have to be concerned with other tests altering its central connection. However a side effect of this change is that when threads complete and the ThreadLocal vars are GC'd the gRPC package produces a nasty error message:
```
Jun 30, 2023 9:29:07 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=16, target=localhost:8000} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.< …
```
> ROX-17963: CI: Fix central channel handling

- ui/apps/platform/package.json
- ui/yarn.lock
Verify no occurrences of package imports found before deleting Network Graph 1.0 component and container.
```
"cytoscape": "^3.21.1",
"cytoscape-cose-bilkent": "^4.0.0",
"cytoscape-node-html-label": "^1.2.2",
"cytoscape-popper": "^2.0.0",
"react-cytoscapejs": "^1.2.1",
"react-dropzone": "^11.3.1",
"react-table": "^7.6.2",
```
1. Note that `react-popper` is used in ColorPicker for System Configuration page.
2. Note that policies does not use `react-dropzone` but `react-dnd` instead (but maybe not for much longer :)
3. src/Components/TableV7 does not import `react-table` so has temporary reprieve until follow up to delete orphan code.
4. Out of an abundance of caution, wait on tippy because it is also a dependency in ui-components package.
```
"tippy.js": "^6.3.7",
```
No change because …
> ROX-18209: Delete Network Graph 1.0 dependencies except tippy

- scripts/ci/lib.sh
It is an open question as to how to best handle slack and JIRA notifications on release branches in order to support the release engineer and the process. So this PR removes them 'for now'. I've verified that `PULL_BASE_REF` exists in a pull and merge context in openshift CI.
> ROX-17280: Skip slack & JIRA for release branches

- scripts/ci/lib.sh
It is an open question as to how to best handle slack and JIRA notifications on release branches in order to support the release engineer and the process. So this PR removes them 'for now'.
This PR also brings in #6497 in order to get the `--dry-run` functionality for junit2jira and cherry-pick #6803.
> ROX-17280: Disable notifications for releases

- central/main.go
- compliance/collection/compliance/node_scanner.go
- pkg/metrics/server.go
- pkg/metrics/server_test.go
- pkg/metrics/tls.go
- sensor/kubernetes/main.go
- tools/local-sensor/main.go
Add a TLS configurer interface responsible for updating the TLS config when either the TLS server certs (mounted via secret) or the client CA (read from config map) is rotated.
> ROX-17224: TLS configurer

- image/templates/helm/stackrox-central/templates/NOTES.txt.htpl
- image/templates/helm/stackrox-central/values.yaml.htpl
- pkg/helm/charts/meta.go
- pkg/renderer/render_new.go
The change in helm renderer allows for configuring telemetry in the `values.yaml` as per the [documentation](
https://docs.engineering.redhat.com/display/StackRox/Telemetry+from+Self-Managed+Installations).
Telemetry should be enabled in the `values.yaml` for release versions or when explicitly enabled with `--enable-telemetry=true`, and disabled with key "DISABLED" for non-release versions, unless explicitly enabled.
Local testing with release and non-release versions of roxctl. With and without providing a key. With enabled and disabled telemetry command line option.
```sh
$ ROX_TELEMETRY_STORAGE_KEY_V1=abc ./bin/linux_amd64/roxctl central generate k8s none --output-format helm --enable-telemetry=true
$ cat …
```
> fix: default telemetry settings for helm `values.yaml`

- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- image/templates/helm/stackrox-central/templates/NOTES.txt.htpl
- image/templates/helm/stackrox-central/values.yaml.htpl
- operator/apis/platform/v1alpha1/central_types.go
- operator/bundle/manifests/platform.stackrox.io_centrals.yaml
- operator/config/crd/bases/platform.stackrox.io_centrals.yaml
- operator/pkg/central/values/translation/translation.go
- operator/pkg/central/values/translation/translation_test.go
- operator/tests/common/central-cr.yaml
- pkg/helm/charts/meta.go
- pkg/renderer/render_new.go
Similarly to #6453, make development operator versions to disable telemetry in the central by default, and release operator versions to enable it.
Unit tests.
> ROX-17683: Enable telemetry by default for release operator versions

- deploy/common/ci-values.yaml
- deploy/common/k8sbased.sh
- deploy/common/local-dev-values.yaml
- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- image/templates/helm/stackrox-central/templates/NOTES.txt.htpl
- image/templates/helm/stackrox-central/values.yaml.htpl
- operator/apis/platform/v1alpha1/central_types.go
- operator/bundle/manifests/platform.stackrox.io_centrals.yaml
- operator/config/crd/bases/platform.stackrox.io_centrals.yaml
- operator/pkg/central/values/translation/translation.go
- operator/pkg/central/values/translation/translation_test.go
- operator/tests/common/central-cr.yaml
- pkg/helm/charts/meta.go
- pkg/renderer/render_new.go
- tests/e2e/lib.sh
We want to disable telemetry when running CI tests. It will be automatically disabled for non-release versions (as no key is provided), but it has to be disabled explicitly when testing release versions of central. Otherwise, centrals will download and use the on-prem configuration.
Local deploy with helm and kubectl.
> ROX-17713: Disable telemetry in our ci runs

- central/telemetry/centralclient/instance_config.go
- deploy/common/ci-values.yaml
- deploy/common/k8sbased.sh
- deploy/common/local-dev-values.yaml
- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- image/templates/helm/stackrox-central/templates/NOTES.txt.htpl
- image/templates/helm/stackrox-central/values.yaml.htpl
- operator/apis/platform/v1alpha1/central_types.go
- operator/bundle/manifests/platform.stackrox.io_centrals.yaml
- operator/config/crd/bases/platform.stackrox.io_centrals.yaml
- operator/pkg/central/values/translation/translation.go
- operator/pkg/central/values/translation/translation_test.go
- operator/tests/common/central-cr.yaml
- pkg/buildinfo/buildinfo.go
- pkg/buildinfo/buildinfo_intest.go
- pkg/buildinfo/buildinfo_notest.go
- pkg/env/telemetry.go
- pkg/helm/charts/meta.go
- pkg/renderer/render_new.go
- pkg/version/version.go
- pkg/version/version_test.go
- roxctl/central/generate/generate.go
- roxctl/central/generate/generate_test.go
- roxctl/central/generate/k8s.go
- tests/e2e/lib.sh
Enable telemetry by default (`--enable-telemetry=true`) in `roxctl central generate` for _release version builds_ (of roxctl binary).
The storage key set in the output manifests and Helm values is `DISABLED` unless:
* telemetry is enabled explicitly for dev or by default for release version images;
* AND (a key value is provided via `ROX_TELEMETRY_STORAGE_KEY_V1` environment variable
* OR (the binary is a release version AND the key is empty)).
`isReleaseBuild()` moved to `pkg/version` and renamed to `IsReleaseVersion()`.
Unit tests, CI.
> ROX-17683: Enable telemetry by default in roxctl

- roxctl/generate/netpol/cta.go
- tests/roxctl/bats-tests/local/roxctl-netpol-generate-development.bats
- tests/roxctl/bats-tests/local/roxctl-netpol-generate-release.bats
As specified in [ROX-16828](https://issues.redhat.com/browse/ROX-16828).
> ROX-16828: Add "generated" label to build-time generated netpols

- CHANGELOG.md
- central/telemetry/centralclient/instance_config.go
- central/telemetry/centralclient/instance_config_test.go
- deploy/common/ci-values.yaml
- deploy/common/k8sbased.sh
- deploy/common/local-dev-values.yaml
- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- image/templates/helm/stackrox-central/templates/NOTES.txt.htpl
- image/templates/helm/stackrox-central/values.yaml.htpl
- operator/apis/platform/v1alpha1/central_types.go
- operator/bundle/manifests/platform.stackrox.io_centrals.yaml
- operator/config/crd/bases/platform.stackrox.io_centrals.yaml
- operator/pkg/central/values/translation/translation.go
- operator/pkg/central/values/translation/translation_test.go
- operator/tests/common/central-cr.yaml
- pkg/buildinfo/buildinfo.go
- pkg/buildinfo/buildinfo_intest.go
- pkg/buildinfo/buildinfo_notest.go
- pkg/env/telemetry.go
- pkg/helm/charts/meta.go
- pkg/renderer/render_new.go
- pkg/telemetry/phonehome/client_config.go
- pkg/telemetry/phonehome/client_config_test.go
- pkg/version/version.go
- pkg/version/version_test.go
- roxctl/central/generate/generate.go
- roxctl/central/generate/generate_test.go
- roxctl/central/generate/k8s.go
- tests/e2e/lib.sh
Release version central binary will download a json document from a URL, defined via `ROX_TELEMETRY_CONFIG_URL` (with some hardcoded default value) on startup if there's no telemetry key defined. Development version will download the config if only a key is also defined via environment variable and if the key is equal to the one found in the config.
Example document:
```json
{ "storage_key_v1": "asdfm52347fhvsdkj" }
```
*Update*: until the default endpoint is implemented, we'll use the hardcoded key.
With an HTTP server pod, serving `config.json`, central logs:
```
...
telemetry/centralclient: 2023/06/13 15:08:16.374527 instance_config.go:86: Info: Telemetry configuration has been downloaded from http://10.244.0.18:8000/config.json
... …
```
> ROX-17682, ROX-17684: Download telemetry key

- central/telemetry/centralclient/instance_config.go
- operator/pkg/central/values/translation/translation.go
- operator/pkg/central/values/translation/translation_test.go
- pkg/telemetry/phonehome/key_management.go
- pkg/telemetry/phonehome/key_management_test.go
- roxctl/central/generate/generate.go
- roxctl/central/generate/generate_test.go
Moved the storage key download logic from `central/telemetry/centralclient/instance_config.go` to `pkg/telemetry/phonehome/key_management.go`, update references.
Unit tests.
> refactor: telemetry storage key management

- .github/workflows/repo2cpe-download.yaml
This GitHub workflow is designed to keep the repo2cpe and name2cpe mapping JSON files updated for Claircore's RHEL scanning in the on-prem scanner V4. Since the on-prem scanner V4 does not have direct internet access, it relies on the files being available in Google Cloud Storage. The workflow handles the download of these files using a CI process and then stores them in Google Cloud Storage. Subsequently, the scanner V4 retrieves the files from Google Cloud Storage to perform scanning operations.
By automating this update process through the workflow, the repo2cpe and name2cpe mapping files remain current, ensuring accurate and efficient RHEL scanning within the on-prem scanner environment.
Run CI in GH action
> added download repo2cpe

- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkPolicies.tsx
- ui/apps/platform/src/hooks/useFetchNetworkPolicies.ts
Fixes a UI crash caused by deleting a NetworkPolicy while the Network Graph is open, and then clicking on the impacted deployment.
This fixes the immediate issue, but a better follow up would be to still display the remaining network policies if possible. (A single error for any one policy prevents the users from viewing _any_ other policies for the deployment.)
View the network graph with a deployment containing a network policy in the selected scope.
Select anything other than the deployment (or nothing) in the graph. Delete one of the network policies that impacts the deployment via `kubectl`. (`kubectl -n ui-testing delete networkpolicy/nginx2-http`)
Click the deployment again in the graph. The UI should not crash, and the Network …
> ROX-18200: Handle error object when networkpolicy request fails

- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkPolicies.tsx
- ui/apps/platform/src/hooks/useFetchNetworkPolicies.ts
- ui/apps/platform/src/services/NetworkService.js
Builds on #6798 to allow some data to display in partial error cases.
Perform the testing steps in #6798 to view an error in the sidebar. If some netpol requests succeeded, display both the errors from the failed requests as well as the usable data.
Error state + empty state if every possible request fails:
Error state if there is an error in the `Promise.allSettled` resolver:
Happy path:
> refactor(ui): Allow netpol YAML to display in UI after partial errors

- sensor/common/compliance/node_inventory_handler_impl.go
- sensor/common/compliance/node_inventory_handler_test.go
Small change for clarity: 
When Sensor sends a NACK to Compliance, Compliance will enter a retry loop and resend the inventory until it receives an ACK.
This PR resets the centralReady signal, therefore leading to Sensor sending NACKs to Compliance on receiving Node Inventories.
The branch was deployed on a OS 4.12 cluster with the FF enabled and Node Scan interval set to 1 minute.
Afterwards, `central` replicas were scaled to 0, to observe Sensor loosing connction to Central.
In that case, `NACK`s are sent out to Compliance immediately upon receiving a Node Inventory.
Finally, after scaling central back to 1 replica, Sensor and Compliance return to working function and transmit Node Scans to Central.
> ROX-17321: Sensor offline mode for Compliance Node Scans

- .github/actions/cache-ui-dependencies/action.yaml
Previous implementation could restore a cache with wrong dependencies, as the dependency files don't between current and cached don't have to match. Matching of the dependency file content is implemented as part of the cache key, e.g. for npm-v2-7ebb8fb1894252db88b2b5a6f2f2da6f13eea209fc2727c029caf4de57218c74-pre-build-ui the dependency file "fingerprint" / hash is 7ebb8fb1894252db88b2b5a6f2f2da6f13eea209fc2727c029caf4de57218c74.
> fix GHA: UI cache too generic (4.0 release branch)

- ui/apps/platform/src/services/ProcessListeningOnPortsService.ts
- ui/apps/platform/src/types/processIndicator.proto.ts
Adds the service file for the listening endpoints API.
Manual testing of this endpoint revealed that the `ProcessSignal.time` field in `processIndicator.proto.ts` can actually be null so that has been updated as well, even though it doesn't affect any consuming code.
(My theory is that any string field that represents a `time` on the backend can result in `null` values when data cannot be found, as opposed to an empty string for plain string values.)
Manual endpoint testing.
> ROX-18089: Add UI service definition for listening_endpoints endpoint

- ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedScanningSettings.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphContainer.tsx
- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/ClusterSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NamespaceSelector.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NetworkBreadcrumbs.tsx
- ui/apps/platform/src/Containers/NetworkGraph/components/NetworkSearch.tsx
- ui/apps/platform/src/Containers/NetworkGraph/hooks/useNetworkPolicySimulator.ts
- ui/apps/platform/src/Containers/NetworkGraph/hooks/useScopeHierarchy.ts
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx
- ui/apps/platform/src/Containers/NetworkGraph/types/networkScopeHierarchy.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/hierarchyUtils.test.ts
- ui/apps/platform/src/Containers/NetworkGraph/utils/hierarchyUtils.ts
- ui/apps/platform/src/hooks/useFetchClusterNamespacesForPermissions.ts
- ui/apps/platform/src/hooks/useFetchClustersForPermissions.ts
- ui/apps/platform/src/services/NetworkService.js
- ui/apps/platform/src/services/RolesService.ts
Adds the user's selects Namespace and Deployment scope to simulated network policy generation. This will cause the generated network policies to only be for deployments that are explicitly selected as part of the user's current scope.
Instead of passing the selected namespaces and deployments alongside the `clusterId` throughout this section, a custom read-only hook is used to pass the user's selected scope to individual components. This avoids threading another property through many component levels and removes the previous threading of `clusterId`.
This PR also updates the cluster SAC response type from `Cluster` to `ScopeObject` to avoid potential issues with consuming code relying on `Cluster` properties that do not exist.
_Note: Much of the Network Graph work for the following …
> ROX-18036: Pass full search scope to network graph simulator panel

- .github/workflows/unit-tests.yaml
- Makefile
- go.mod
- go.sum
- operator/Dockerfile
- operator/Makefile
- operator/config/.gitignore
- operator/main.go
- operator/pkg/central/reconciler/reconciler.go
- operator/pkg/common/extensions/mapkubeapis.go
- operator/pkg/securedcluster/reconciler/reconciler.go
- operator/tests/reconcile/mapkubeapis_test.go
- operator/tests/reconcile/reconcile_suite_test.go
This PR adds the new [mapkubeapis](https://github.com/helm/helm-mapkubeapis) extension to the operator. It checks if there're deprecated or removed objects in the release manifests and performs cleanup before the helm upgrade. This is especially useful when PSPs are removed from the cluster (i.e. by upgrading an OCP cluster to 4.12) and the operator is running a version that does not support PSP autosensing (i.e. 3.69.X).
- Added an integration test.
- Tested the OCP upgrade on an infra cluster.
> ROX-17687: Operator PSP recovery

- qa-tests-backend/src/main/groovy/services/ImageService.groovy
- qa-tests-backend/src/main/groovy/util/Helpers.groovy
Sometimes registries have glitches. Retrying a scan call at least once after a bit of a while should reduce the number of CI failures such as:
1. https://issues.redhat.com/browse/ROX-16319
2. https://issues.redhat.com/browse/ROX-17737
And maybe others.
CI
> ROX-17737: Add simple retry to ScanImage

- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsTable.tsx
- ui/apps/platform/src/constants/networkFlow.ts
- ui/apps/platform/src/services/ProcessListeningOnPortsService.ts
- ui/apps/platform/src/types/processIndicator.proto.ts
Adds a plain table structure to the listening endpoints page with sample data.
Load the listening endpoints page:
Minimal non-mobile size:
> ROX-17951: Add basic table display of listening endpoints data

- ui/apps/platform/src/Containers/Collections/CollectionFormModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx
This PR adds a "View" button that allows you to view the selected scope. This is useful when we want to see what exactly are the details for a specific collection before we set it as the report scope
https://github.com/stackrox/stackrox/assets/4805485/8ea1b3af-0512-4fc7-a271-449e12441867
> ROX-17838: Allow viewing a selected report scope

- central/telemetry/centralclient/instance_config.go
See ROX-18281. The change is to add the previously missing Flavor property to the central backend user.
Local deployment, event seen on Segment:
```json
{
...
"traits": {
"Auth Providers": null,
"Central version": "4.1.x-299-g54326a88f4",
"Chart version": "400.1.0-299-g54326a88f4",
"Flavor": "opensource",
"Kubernetes version": "v1.25.3",
"Managed": false,
"Orchestrator": "KUBERNETES_CLUSTER",
...
}
}
```
> ROX-18281: Telemetry - add Flavor to central properties

- operator/apis/platform/v1alpha1/securedcluster_types.go
- operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml
- operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml
Customers who are using the kernel module collection method are unable to upgrade as that option has been removed in 4.1. This adds kernel module as a valid collection method. If someone tries to use kernel module as a collection method, the collection method will be changed to EBPF.
Discussed with @pedrottimark and concluded that the UI test failures are not the result of code changes here and that bringing in the fix to the 4.1 release branch would not be worth it.
Followed the directions [here](https://gitlab.cee.redhat.com/stackrox/downstream-utils/-/blob/main/testing/books/operator-catalog.ipynb) and [here](https://docs.engineering.redhat.com/display/StackRox/Managing+a+Downstream+RHACS+Release+on+Red+Hat+Infrastructure#ManagingaDownstreamRHACSReleaseonRedHatInfrastructure-test-prereq …
> ROX-18208: rhacs operator upgrade failed 4.1

- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
Because installing ACS v4.1.0 breaks OLM for customers that use `KernelModule` collection method, this version should be marked as broken so that it's always skipped by OLM.
See ROX-18208
screenshots.
> ROX-18208: Mark v4.1.0 as skipped version

- central/authprovider/datastore/internal/store/postgres/store.go
- central/complianceoperatorintegration/store/postgres/store.go
- central/externalbackups/internal/store/postgres/store.go
- central/group/datastore/internal/store/postgres/store.go
- central/imageintegration/store/postgres/store.go
- central/logimbue/store/postgres/store.go
- central/notifier/datastore/internal/store/postgres/store.go
- central/policy/store/postgres/store.go
- central/policycategory/store/postgres/store.go
- central/policycategoryedge/store/postgres/store.go
- central/serviceidentities/internal/store/postgres/store.go
- pkg/search/postgres/store.go
- tools/generate-helpers/pg-table-bindings/store.go.tpl
- tools/generate-helpers/pg-table-bindings/test/postgres/store.go
- tools/generate-helpers/pg-table-bindings/testuuidkey/postgres/store.go
> ROX-18155: pg generic store: GetAll

- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.test.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsTable.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/hooks/useDeploymentListeningEndpoints.tsx
Replaces the inline mock data with live data from central to display deployments and their associated listening endpoints. This currently will load data for only the first ten deployments in the system.
**Note that a design is not finalized for this page. This is a basic display to get the necessary data loading code in place while UX finishes design work.**
Load the listening endpoints page at `/audit/listening-endpoints`:
Small screen:
Loading state:
Error state:
> ROX-17953: Use live data for listening endpoints table

- tests/e2e/yaml/compliance-operator/subscription.yaml
The Compliance Operator recently released version 1.0.0 on a new channel called `stable`, which will include all new Compliance Operator releases moving forward (at least up until a breaking change that requires a new channel).
https://docs.openshift.com/container-platform/4.13/security/compliance_operator/compliance-operator-release-notes.html#compliance-operator-release-notes-1-0-0
Previously, the `release-0.1` channel was used to install the latest version of the Compliance Operator, but that was prior to the 1.0.0 release. The latest release on the `release-0.1` channel was 0.1.61.
Does Compliance Operator 1.0.0 have any breaking changes?
No. Even though it's a major version bump, it does not contain any backwards incompatible changes and is essentially the same code as 0.1.61. This …
> ROX-14249: Install the Compliance Operator from `stable` channel

- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.test.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
Adds a "View more" button to allow lazy loading of more deployments with listening endpoints.
Again, the design is not finalized by UX, this PR uses a simple design in order to get the necessary functionality in place.
View the listening endpoints page directly at `/audit/listening-endpoints` and scroll to the bottom. A "View more" button should be present:
Click the button, it should become disabled while more data is loading:
Continue to click the "view more" button until all data has loaded. Once all data has loaded the button will disappear:
> ROX-17952: Add ability to lazy load listening endpoints

- sensor/tests/connection/k8sreconciliation/reconcile_test.go
The `ROX_PREVENT_SENSOR_RESTART_ON_DISCONNECT` feature flag is not enabled in release builds making this test fail constantly in nightlies.
> ROX-18148: skip reconciliation test on release builds

- .openshift-ci/ci_tests.py
- scripts/ci/jobs/ocp_compliance_e2e_tests.py
- scripts/style/shellcheck_skip.txt
- tests/Makefile
- tests/e2e/run-compliance-e2e.sh
Previously, we ran the compliance end-to-end testing with the UI end-to-end testing. While this is good, and we should continue to do it since compliance can impact UI functionality, we can separate the compliance testing out into its own CI job.
This gives us the flexibility to invoke the compliance end-to-end testing on backend-specific changes, instead of only UI related changes.
We should be able to test this change with `ocp-4-13-compliance-e2e-tests` CI, which should install the Compliance Operator and run the nongroovy compliance tests. Once that is passing, we should be good to merge this change.
> ROX-18310: Add separate CI job specifically for Compliance e2e testing

- ui/apps/platform/package.json
- ui/yarn.lock
TL;DR 10% decrease for main.js bundle and 7.5% for total of js bundle files.
Following recent theme of deleting css, media, and js files, reduce size of bundle via modern JavaScript.
1. Thanks to Brad for demo of Lighthouse browser tool that reported that bundles do not use modern JavaScript.
2. Also `yarn build` warns several times:
> Browserslist: caniuse-lite is outdated. Please run:
> npx update-browserslist-db@latest
1. Default browserslist query in package.json file provoked warnings about caniuse-lite outdated because of relative conditions:
```
"browserslist": [
">0.2%",
"not dead",
"not ie <= 11",
"not op_mini all"
]
```
2. For determinate results similar to what yarn.lock does for package.json file, change to specify a specific browser version `"Chrome >= 80"` that has …
> chore(ui): Update browserslist to Chrome 80 in ui

- operator/tests/common/upgrade-assert.envsubst.yaml
- operator/tests/upgrade/upgrade/20-upgrade-operator.yaml
In 4.1 this PVC is gone. This fixes the upgrade test. Details in ticket.
> ROX-18340: Stop asserting stackrox-db PVC in operator upgrade test

- ui/apps/platform/src/Containers/NetworkGraph/hooks/useNetworkPolicySimulator.ts
Passes additional "general" filters that have been applied via the search bar to the network policy simulator API. Due to the fact that these filters also reduce the scope of the graph, they should also be used to reduce the scope of the generated policies.
Generate policies for two namespaces, with no additional filter - policies for deployments in `ui-testing` and `ui-testing2` are generated
Add a general filter ("Deployment Label: app=wordpress") - only the Wordpress deployment has generated policies.
> ROX-18318: Add general filters to network policy simulation API call

- central/splunk/violations_test.go
Panic not using utils.Must which forks a goroutine to panic that cannot be caught
CI
> ROX-18045: Remove Splunk panic handler unit test

- ui/apps/platform/package.json
- ui/apps/platform/src/Containers/Clusters/ClustersSidePanel.tsx
- ui/apps/platform/src/services/ClustersService.ts
- ui/apps/platform/src/services/schemas.js
- ui/yarn.lock
Follow up delete next-to-last occurrences of normalizr in #6782
1. Even more difficult than understanding data flow when containers share data in reducers via sagas, invisible **data transformations outside of containers** because classic network graph needed to access clusters as an object map with id as key.
2. Add external insult to internal injury: normalizr dependenct is no longer maintained.
1. The only `saveCluster` call is in ClustersSidePanel when user clicks **Next** button.
2. Response always included new or updated cluster. Since last year, it also includes `clusterRetentionInfo` property.
1. Simplify service function and its call.
1. I supposed that initial attempt to use `cluster` object in response as source of truth did not work for new cluster, because several fields are …
> chore(ui): Delete normalizr from saveCluster and dependencies in ui

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#12-17-1
* Upgraded `@cypress/request` from 2.88.10 to 2.88.11 to address CVE-2022-24999 security vulnerability.
1. `yarn start` in ui
2. `yarn cypress-open` in ui/apps/platform
* clusters/clusters.test.js
* policies/policiesTable.test.js
* risk/risk.test.js
* violations/violations.test.js
> chore(e2e): Update cypress 12.17.1 devDependencies in ui

- ui/apps/platform/cypress/fixtures/alerts/deploymentForAlertFirstInAlerts.json
- ui/apps/platform/cypress/fixtures/alerts/deploymentWithEmptyContainerConfig.json
- ui/apps/platform/cypress/integration/violations/Violations.helpers.js
- ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerConfiguration.tsx
- ui/apps/platform/src/Containers/Violations/Details/Deployment/DeploymentOverview.tsx
- ui/apps/platform/src/Containers/Violations/Details/DeploymentDetails.tsx
- ui/apps/platform/src/Containers/Violations/Details/Enforcement/Header.tsx
- ui/apps/platform/src/Containers/Violations/Details/EnforcementDetails.tsx
- ui/apps/platform/src/Containers/Violations/Details/ViolationDetailsPage.tsx
- ui/apps/platform/src/services/NetworkService.js
In preparation for ROX-11034, this updates the types in the Violations page's Deployment tab to remove usage of `any` in order to increase type safety and correctness.
Steps:
1. Use the destructured properties on alert in https://github.com/stackrox/stackrox/pull/6873/files#diff-5c53620827639310dcbb0614ba692ae5369b2680042b73d4edde5d2deec81773 instead of checking property access to allow TypeScript to automatically infer the types being passed to the child components as non-null.
2. Add explicit prop types to child components instead of using an implicit `any`.
3. Remove the now unneeded null/undefined checks in child components due to Step 1.
4. Split the `Alert['deployment']` and `Deployment` types from being used interchangeably …
> refactor(ui): Increase type safety of DeploymentDetails tab

- qa-tests-backend/src/test/groovy/NodeInventoryTest.groovy
The problem was that the Collector DS restarted with new env var updated all but one pod. 
⚠️ I was unable to reproduce this locally.
This PR:
- Adds one more repetition of the entire process (setting env var to the DS, waiting for pods to be updated)
- Changes the wait time between checking the node-inventory containers from 6s to 10s. This should give more time for the change to propagate (if that is the reason of this failure).
- CI
- Locally running tests
> ROX-18216: Fix NodeInventory flake

- ui/apps/platform/cypress/helpers/scopeSelectors.js
- ui/apps/platform/src/Containers/NetworkGraph/api/useFetchNetworkBaselines.ts
- ui/apps/platform/src/Containers/NetworkGraph/namespace/NamespaceSideBar.tsx
- ui/apps/platform/src/Containers/NetworkGraph/utils/flowUtils.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts
- ui/apps/platform/src/hooks/usePaginatedQuery.ts
- ui/apps/platform/src/utils/securityContextUtils.ts
Recent work to delete unused dependencies reminded me of an inconsistency that the team had discussed, and then forgotten. I became curious whether rewrite named imports as default imports from lodash subfolder affects either bundle size or yarn.lock file.
1. In ui/apps/platform folder:
```sh
find src \( -name '*.js' -o -name '*.ts' -o -name '*.tsx' \) -exec fgrep -h "'lodash" \{\} >> somewhere/lodash.txt \;
```
2. Find in File `'lodash'` 6 named out of 150 total
* `import { isEmpty } from 'lodash';`
* `import { debounce } from 'lodash';`
* `import { uniq } from 'lodash';`
* `import { uniq } from 'lodash';`
* `import { uniqBy } from 'lodash';`
* `import { sortBy } from 'lodash';`
Although I do not have a preference between named import from `'lodash'` versus default import from …
> chore(ui): Import consistently from lodash

- pkg/env/metrics.go
- pkg/metrics/tls.go
- pkg/metrics/tls_test.go
- pkg/metrics/verifier_test.go
Expose all the client CA settings as env vars.
> ROX-17224: add client CA env vars

- image/templates/helm/stackrox-central/internal/config-shape.yaml
- image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
- image/templates/helm/stackrox-central/templates/99-openshift-monitoring.yaml
- image/templates/helm/stackrox-central/templates/_init.tpl.htpl
- image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml
- image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
- image/templates/helm/stackrox-secured-cluster/templates/openshift-monitoring.yaml
- pkg/helm/charts/tests/centralservices/testdata/all-values-explicit.yaml
- pkg/helm/charts/tests/centralservices/testdata/autogenerate-all.yaml
- pkg/helm/charts/tests/centralservices/testdata/helmtest/openshift-monitoring.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/all-values-explicit.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/openshift-monitoring.test.yaml
This PR renames `enableOpenShiftMonitoring` to `monitoring.openshift.enabled: true` and exposes it in operator.
CI
> refactor(helm): rename openshift monitoring

- image/templates/helm/stackrox-central/templates/99-openshift-monitoring.yaml
- pkg/helm/charts/tests/centralservices/testdata/helmtest/openshift-monitoring.test.yaml
ServiceMonitor only works is namespace has certain label.
As Helm does not control the namespace it installs we cannot simply add 
a label to that namespace. This PR installs ServiceMonitor in openshift-monitoring 
namespace that is guaranteed to exist and have proper labels.
screenshots.
> ROX-17225: install service monitor in monitoring

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveSingle.test.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadTableToolbar.test.js
Since the feature is still behind a feature flag until GA, put the tests behind the same flag.
Local CI runs with `CYPRESS_ROX_VULN_MGMT_WORKLOAD_CVES` enabled and disabled to verify that tests run/don't run correctly.
Tests should be **enabled** in CI.
> chore(ui): Gate Workload CVE e2e tests behind feature flag

- ui/apps/platform/src/Containers/Clusters/ClusterDeployment.js
- ui/apps/platform/src/Containers/Clusters/ClusterLabelsTable.tsx
- ui/apps/platform/src/Containers/Clusters/ClustersSidePanel.tsx
- ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.js
- ui/apps/platform/src/Containers/Clusters/DownloadHelmValues.tsx
1. Visit /main/clusters and then click a row
Minor: Table header text should not be empty `<th class="" aria-label="Action"></th>`
2. Click **Next**
Serious: Elements must meet minimum color contrast ratio
* Element has insufficient color contrast of 4.32 (foreground color: #2c8820, background color: #edffeb, font size: 10.5pt (14px), font weight: normal). Expected contrast ratio of 4.5:1
`<button type="button" class="mr-2 btn btn-success" data-testid="">`
* Element has insufficient color contrast of 2.08 (foreground color: #5fb2f7, background color: #ebf6ff, font size: 9.0pt (12px), font weight: normal). Expected contrast ratio of 4.5:1
`<button type="button" class="download uppercase text-primary-600 p-2 text-center text-sm border border-solid bg-primary-200 border-primary-300 …
> fix(ui): Fix accessibility problems in Clusters

- ui/apps/platform/cypress/fixtures/network/networkPoliciesInNamespace.json
- ui/apps/platform/cypress/integration/violations/Violations.helpers.js
- ui/apps/platform/cypress/integration/violations/Violations.selectors.js
- ui/apps/platform/cypress/integration/violations/violations.test.js
- ui/apps/platform/src/Components/PatternFly/CodeEditorDarkModeControl.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkPolicies.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesYAML.tsx
- ui/apps/platform/src/Containers/Violations/Details/DeploymentDetails.tsx
- ui/apps/platform/src/Containers/Violations/Details/NetworkPolicyModal.tsx
Updates the plain text for network policies in the "Deployment" tab of the Violations detail page to use a list of links instead. Clicking one of the links will open a modal that shows the yaml in the same code editor used in the Network Graph.
View a violation that occurs on a deployment in a namespace with network policies. (Note that the specific deployment itself does not need to have network policies.)
Click on a network policy.
Dark mode:
Test that the copy control and export button work correctly (no screenshots).
Close the modal and open another.
View a deployment in a namespace with no Network Policies:
> ROX-11034: Add ability to view NetPol in modal on Violation/Deploy tab

- qa-tests-backend/src/test/groovy/CSVTest.groovy
This PR intends to add multi-arch support for the `CSVTest` QA test.
Changes are verified manually using `./gradlew test --tests=CSVTest`
This PR intends to fix [ROX-16929](https://issues.redhat.com/browse/ROX-16929)
> ROX-16929: Make CSVTest multi-arch compliant

- tests/e2e/run-e2e-tests-README.md
- tests/e2e/run-e2e-tests.sh
Per title. Also removes the use of gradles cache in the running container as that is not necessarily portable. 
n/a - this script is standalone and not used in any automation.
> CI: Extend e2e runner to support gradle tasks

- tests/e2e/lib.sh
- tests/e2e/run.sh
Currently, a flake exists within the roxctl tests when the `whoami` command is used.
Previously, the timeouts have been adjusted as well as retries have been implemented. 
However, the failure was observed now again.
Looking at the output of the logs:
```log
INFO: Tue Jul 11 05:32:19 UTC 2023: Patch the loadbalancer and netpol resources for endpoints test
service/central-loadbalancer patched
networkpolicy.networking.k8s.io/allow-ext-to-central-ports created
INFO: Tue Jul 11 05:33:30 UTC 2023: Run roxctl tests
Using API_ENDPOINT 34.135.119.201:443
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1238  100  1205  100    33   8368    229 …
```
> ROX-18360: Ensure API after preparing tests

- ui/apps/platform/cypress/integration/violations/Violations.selectors.js
- ui/apps/platform/cypress/integration/violations/violations.test.js
- ui/apps/platform/src/Containers/Violations/Details/Deployment/ContainerConfiguration.tsx
- ui/apps/platform/src/Containers/Violations/Details/Deployment/SecurityContext.tsx
- ui/apps/platform/src/Containers/Violations/Details/DeploymentDetails.tsx
- ui/apps/platform/src/Containers/Violations/Details/Enforcement/Explanation.tsx
- ui/apps/platform/src/Containers/Violations/Details/Enforcement/Header.tsx
- ui/apps/platform/src/Containers/Violations/Details/K8sCard.tsx
- ui/apps/platform/src/Containers/Violations/Details/NetworkFlowCard.tsx
- ui/apps/platform/src/Containers/Violations/Details/ViolationDetailsPage.tsx
- ui/apps/platform/src/Containers/Violations/Modals/ExcludeConfirmation.tsx
- ui/apps/platform/src/Containers/Violations/Modals/ResolveConfirmation.tsx
- ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
- ui/apps/platform/src/Containers/Violations/types/violationTypes.ts
Follow up to #6908, this removes almost all instances of `data-testid` in the Violations detail page in favor of using accessible `aria-label` attributes.
CI
> chore(ui): Cleanup data-testid in Violations container

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/CreateVulnReport/CreateVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useCreateReport.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx
- ui/apps/platform/src/services/ReportsService.ts
- ui/apps/platform/src/setupProxy.js
- ui/apps/platform/src/types/reportConfigurationService.proto.ts
This PR allows the user to actually create a report using the v2 Reports API. Some things to note in this PR:
- I created a function to send an API call to create a report
- I created a hook that manages the data returned, error state, loading state, and function to send an API call
- I have to update `setupProxy` to allow proxying v2 API endpoints
- I tweaked the types for the ReportConfiguration type due to a change in the API
- I updated the `useReportFormValues` hook to export two new functions. One is the `clearFormValues` function which basically changes the state to the default state. We will also export a new function called `setReportFormFieldValue`, which helps with duplicated logic in the `ReportParametersForm` component
- I added a custom footer for the wizard, which was …
> ROX-17849: Allowing creating a vuln report

- qa-tests-backend/src/test/groovy/PolicyConfigurationTest.groovy
This test was failing because `ImageService.getImage` throws an exception when it cannot find an image. This PR turns the loop into a standard withRetry() loop.
CI is sufficient + OCP tests where this fails most often + 50x run against an infra cluster.
> CI: Fix PolicyConfigurationTest

- ui/apps/platform/src/Containers/ConfigManagement/List/Policies.js
Recommended by Mandar and confirmed by ACS UX team on 2023-07-12
Follow up after changes suggested in PatternFly Design Share and reviewed by ACS UX team:
* Replace icons **without** text for enabled state with icon **with** text
* Replace hyphen **without** explanation for status of disabled policies with icon **with** text
Enabled column is redundant because Policy Status has either:
* Disabled is explicit
* Fail implies Enabled
* Pass implies Enabled
UI/UX meeting discussed but did not yet converge on specific improvement for default sort on this page.
1. Visit /main/configmanagement/policies
* 1920px panel width
* 1440px newer laptop width
* 1280px older laptop width
* configmanagement/policies.test.js
> fix(ui): Delete Enabled column in Configuration Management Policies

- ui/apps/platform/src/Containers/Risk/ContainerConfigurations.js
- ui/apps/platform/src/Containers/Risk/DeploymentDetails.js
- ui/apps/platform/src/Containers/Risk/KeyValuePairs.js
- ui/apps/platform/src/Containers/Risk/Process/ProcessBaselineElementList.js
- ui/apps/platform/src/Containers/Risk/RiskDetails.js
- ui/apps/platform/src/Containers/Risk/SecurityContext.js
**Deployment Details** tab
> 4 serious: List element has direct children that are not allowed: `div`
Under **Resources**:
* CPU Request (cores)
* CPU Limit (cores)
* Memory Request (MB)
* Memory Limit (MB)
More under **Secrets** if I select a deployment that has them.
1. src/Components/KeyValuePairs,js is used only in Risk:
* src/Containers/Risk/ContainerConfigurations.js
* src/Containers/Risk/DeploymentDetails.js
* src/Containers/Risk/SecurityContext.js
2. It looks like copy-paste. `ContainerVolumes` renders `li` elements, but `Resources` and `ContainerSecrets` render `div` elements.
3. Found only 3 ocurrences of `tracking-normal` Tailwind class: obsolete and in Risk.
4. No integration tests depend on `data-testid` attributes for KeyValuePairs.
1. Move KeyValueMap.js from src/Components …
> fix(ui): Fix accessibility problems in KeyValuePairs for Risk

- ui/apps/platform/src/Components/Panel.js
- ui/apps/platform/src/Containers/Risk/Process/DiscoveryCardHeader.js
- ui/apps/platform/src/Containers/Risk/Process/ProcessBaselineElementList.js
- ui/apps/platform/src/Containers/Risk/Process/ProcessBaselineList.js
1. 4 serious: Buttons must have discernable text
2. 1 moderate: Heading levels should only increase by one h3 Event Timeline and so on
1. Indeed, buttons lack `aria-label` attribute:
* DiscoveryCardHeader: hard to believe that it does not know if its state is collapsed or expanded!
* ProcessBaselineList
* ProcessBaselineElement
2. `PanelTitle` renders `div` instead of more semantic `h2` element. Therefore there is a gap to the semantic `h3` elements.
1. Add `aria-label` attribute:
* DiscoveryCardHeader: too bad, so sad: generic Expand or Collapse. Also replace conditional and that has `false` class with ternary that has empty string.
2. Renders `h2` element in `PanelHeader` component. Even if affects heading levels in other classic pages, we will adjust them for semantic page structure. …
> fix(ui): Fix accessibility problems in Process Details for Risk

- ui/apps/platform/cypress/integration/configmanagement/dashboard.test.js
- ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/PolicyViolationsBySeverity.js
- ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/SecretsMostUsedAcrossDeployments.js
- ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/UsersWithMostClusterAdminRoles.js
1 and 10 serious issues, respectively
> `ul` and `ol` must only directly contain `li` and so on elements
> `li` elements must be contained in a `ul` or `ol`
SecretsMostUsedAcrossDeployment renders `li` inside `a` element, instead of `a` inside `li` element.
1. Replace invisible block link with visible link for secret name.
2. Delete redundant tooltip for deployment count and certificate status.
3. Adjust margins.
4. While we are at it, replace title case with sentence case for 3 widgets.
A lot of custom alignment to render a unique list when data cries out for a table:
| Secret             |      Status | Cluster | Namespace | Deployments |
| :---               |        ---: | :---    | :--       |        ---: |
| proxy-config       |    no certs | remote  | stackrox  |           2 |
| …
> fix(ui): Fix accessibility issues in Configuration Management Secrets

- ui/apps/platform/src/Components/TextSelect/TextSelect.js
> Form elements must have labels
TextSelect based on React Select renders a dummy `input` element:
* src/Containers/ConfigManagement/Dashboard/widgets/ComplianceByControls.js
* src/Containers/VulnMgmt/widgets/TopRiskiestEntities.js
* src/Containers/VulnMgmt/widgets/TopRiskyEntitiesByVulnerabilities.js
Comment from code:
```js
// Because React Select renders a dummy input element,
// axe DevTools reports a theoretical issue: Form elements must have labels.
// One of its suggestions is to enclose the form element in a label element.
// Thankfully that does not affect the layout.
// However, jsx-a11y rule only accepts label as sibling, not enclosing.
/* eslint-disable jsx-a11y/label-has-associated-control */
return (
<label>
<Select styles={selectStyles} isSearchable={false} {...rest} …
```
> fix(ui): Fix accessibility issue about TextSelect input form label

- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
- tests/e2e/run-e2e-tests.sh
Since @Retry() was removed this test fails more often. One particular culprit is `Image metadata from registry test` when the Azure container registry times out:
```
pkg/images/enricher: 2023/07/07 09:09:58.403784 enricher_impl.go:348: Info: Getting metadata for image stackroxci.azurecr.io/stackroxci/registry-image:0.3
image/service: 2023/07/07 09:10:03.492909 service_impl.go:289: Error: error enriching image "stackroxci.azurecr.io/stackroxci/registry-image:0.3": image enrichment error: error getting metadata for image: stackroxci.azurecr.io/stackroxci/registry-image:0.3 error: getting metadata from registry: "acr": Get "https://eusmanaged51.blob.core.windows.net/1783c77074a44bedb6bc08eb5ab66324-z69mm6zphh//docker/registry/v2/blobs/sha256/e0/e03ee8c409b34496c09c261194dd3d0d825f0a67350d49c8 …
```
> CI: Fix ImageScanningTest flakes

- ui/apps/platform/cypress/integration/vulnmanagement/VulnerabilityManagement.selectors.js
- ui/apps/platform/src/Containers/ConfigManagement/SidePanel/BackButton.js
- ui/apps/platform/src/Containers/ConfigManagement/SidePanel/BreadCrumbs.js
- ui/apps/platform/src/Containers/VulnMgmt/EntityBreadCrumbs.tsx
> Links must have discernable text
1. Replace `data-testid` prop with `aria-label` prop:
* Solve accessibility problem for image link.
* Prefer visible text or accessibility attributes instead of `data-testid` attributes in test selectors.
1. Visit /main/configmanagement/deployments, click a row, and then click a related entities link.
2. Visit /main/vulnerability-management/deployments, click a row, and then click a related entities link.
* vulnmanagement/clusterCVEs.test.js
* vulnmanagement/clusters.test.js
* vulnmanagement/deployments.test.js
* vulnmanagement/imageComponents.test.js
* vulnmanagement/imageCves.test.js
* vulnmanagement/images.test.js
* vulnmanagement/namespaces.test.js
* vulnmanagement/nodeComponents.test.js
* vulnmanagement/nodeCves.test.js
* …
> fix(ui): Fix accessibility problem with side panel BackButton

- ui/apps/platform/cypress/integration/vulnmanagement/clusters.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/deployments.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/imageComponents.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/namespaces.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/nodeComponents.test.js
Because `verifyConditionalCVEs` supports **absence of CVEs** remove `skip` from 6 tests:
* for node CVEs and cluster CVEs in clusters.test.js
* for image CVEs in deployments.test.js
* for image CVEs in imageComponents.test.js
* for image CVEs in namespaces.test.js
* for node CVEs in nodeComponents.test.js
> chore(e2e): Unskip openshift in tests that call verifyConditionalCVEs

- ui/apps/platform/cypress/integration/vulnmanagement/dashboard.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/dashboardToEntityPage.test.js
- ui/apps/platform/src/Components/ViewAllButton/index.ts
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Component/VulnMgmtComponentOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Deployment/VulnMgmtDeploymentOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Image/VulnMgmtImageOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Namespace/VulnMgmtNamespaceOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Node/VulnMgmtNodeOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/ClustersWithMostClusterVulnerabilities.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/CvesByCvssScore.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/MostCommonVulnerabilities.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/MostCommonVulnerabiltiesInDeployment.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/RecentlyDetectedImageVulnerabilities.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/TopRiskiestEntities.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/TopRiskyEntitiesByVulnerabilities.js
- ui/apps/platform/src/Containers/VulnMgmt/widgets/ViewAllButton.tsx
Although several classic pages still have title case, this high profile page has inconsistent case.
1. During update to **View all** text, I noticed that it rendered `HashLink` element to support former links from System Health to anchors in Integrations, but after updates of other containers to PatternFly elements, the only uses of `ViewAllButton` are in Vulnerability Management widgets, therefore:
* Render `Link` element.
* Move to same folder as components that import it, so obvious to delete it whenever we delete them.
1. Vulnerability single page does not render CVE id.
1. Visit /main/vulnerability-management
* See **View all** buttons
* See **Top riskiest images** and so on
* See **Recently detected image vulnerabilitites**
* See **Most common image vulnerabilities**
* See …
> fix(ui): Fix inconsistent case on Vulnerability Management dashboard

- image/templates/sensor/kubernetes/delete-sensor.sh
- image/templates/sensor/openshift/delete-sensor.sh
- scripts/style/shellcheck_skip.txt
Skip PSPs for clusters where PSPs were removed (K8S v1.25 and above)
Manually tested on the following platforms:
1. Vanilla K8S v1.27.3+k3s1
2. Vanilla K8S v1.23.6+k3s1
3. Openshift 4.11.44 (Infra)
4. Openshift 4.13.4 (Infra)
1. Install Central
2. Create a cluster from the UI, download a sensor bundle.
5. Install Secured Cluster with `./sensor.sh`
6. Uninstall with `./delete-sensor.sh`
> ROX-18374: Autodetect PSP in delete-sensor.sh

- ui/apps/platform/package.json
- ui/apps/platform/src/Containers/MainPage/Header/UserMenu.js
Prerequisite to remove ui-components as a dependency.
TL;DR Slight increase: to know, you measure.
main.css: 111 = 4231518 - 4231407
total: 111 = 10248033 - 10247922
0 = 80 - 80 files
1. Visit /main/dashboard
* logout.test.js
* userInfo.test.js
> chore(ui): Replace ui-components Avatar with inline code

- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.test.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsTable.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/hooks/useDeploymentListeningEndpoints.tsx
Replaces the infinite, flat table on the listening endpoints page with a traditionally paginated table and expandable rows.
Deployments with no listening endpoints will be present in the table, but will not be expandable.
This also uses the _# of many_ pagination pattern that was suggested in the past to avoid additional expensive network requests.
- Add column sorting
- Add a search by deployment input
Visit the listening endpoints page:
Test pagination controls:
Test expanding and closing multiple rows:
Page beyond the max number of items (TBD - need to follow up with UX on ideal patterns for this case):
> ROX-18471: Update listening endpoints to use expandable table

- central/networkbaseline/manager/manager_impl.go
- central/networkbaseline/manager/manager_impl_test.go
- pkg/networkgraph/networkbaseline/baseline_info.go
This PR addresses a CI failure that happens due to a change that was made in the baseline creation.
Rather than reverting the change, and always create a baseline when a deployment is created, the proposal here is to search all baselines when deleting a deployment **only if that deployment does not have a baseline.**
The issue observed is that network flows are deleted from the table when the deployment gets deleted, making baseline inconsistent when a deployment is deleted. 
- Given we have two deployments: *server* and *client* which are created at the same time.
- Then *client* makes a request to *server* and shuts down.
- When this happens, ACS will remove the network flow between *client* and *server* from network_flows_v2.
There are two different paths the application could take, …
> ROX-14975: Fix baseline setup

- pkg/k8scfgwatch/cfg_watcher.go
The watch context timeout was intended to deal with connection timeouts during the initial server response, however it also includes the event stream that comes after. This leads to unintended early disconnect of the watcher, which is then re-created. However, connection problems should already be covered by the default transport, which includes timeouts. So the context timeout is not needed here, and just leads to log spam and added load on the k8s API.
Tested on OpenShift cluster.
> fix(k8scfgwatch): remove watch timeout

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadTableToolbar.test.js
This flake seems to gradually be happening more frequently as time goes on, so I'll disable it for now until a proper fix can be worked.
https://issues.redhat.com/browse/ROX-17959
N/A
> test(ui): Temporarily disable flaky workload cve toolbar test

- compliance/collection/compliance/compliance.go
I was able to trigger* a situation where a nodeInventory is not ACK-ed but the cache in Compliance is empty. This will result in Compliance retrying and not getting an ACK until the next scheduled scan happens.
This PR provides a fix where we recognize such situation and schedule the next scan immediately (in 1s).  
*) I am still not sure how to reproduce this reliably. What I did was simply a restart of sensor. I think it may be a time coincidence. 
The root cause seem to be the inability of Compliance to receive the ACK from Sensor AND empty nodeInventory cache in Compliance.
```
collector Collector Version: 3.15.x-65-ga5ab4b809e
collector OS: Red Hat Enterprise Linux CoreOS 413.92.202306141213-0 (Plow)
collector Kernel Version: …
```
> ROX-0000: Fix node inventory resend edge case

- central/complianceoperator/v2/checkresults/store/postgres/store.go
- central/complianceoperator/v2/scans/store/postgres/store.go
The resources have moved from `central/role/resources` to `pkg/sac/resources`, and due to a missed rebase the generated stores for the compliance operator were using the old, non-existing location for resources.
Re-run code gen to re-create the stores to ensure they use the new package location for resources.
> fix(ci): re-generate complianceoperator stores

- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsTable.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/hooks/useDeploymentListeningEndpoints.tsx
As titled again.
Visit the listening endpoints page:
Enter a search value and press enter -or- click the `->` button:
Click the `X` button to clear the search:
Open multiple deployments and view the alignment of the nested tables:
> ROX-18473: Add search input to listening endpoints table.

- central/deployment/datastore/datastore_impl.go
- central/deployment/datastore/datastore_impl_test.go
Cronjobs will lose the digest used once the cronjob has finished, but it's worthwhile to display the last running image instead of saying that it's not running which is may be for most of the time
Will write a unit test and groovy test, but just wanted to get this out here
> ROX-15848: Merge cronjobs to preserve image digests

- central/alert/datastore/internal/store/postgres/store_test.go
- central/cluster/store/cluster/postgres/store_test.go
- central/compliance/datastore/internal/store/postgres/metadata/store_test.go
- central/compliance/datastore/internal/store/postgres/results/store_test.go
- central/complianceoperator/v2/checkresults/store/postgres/store.go
- central/complianceoperator/v2/scans/store/postgres/store.go
- central/deployment/store/postgres/store_test.go
- central/namespace/store/postgres/store_test.go
- central/networkbaseline/store/postgres/store_test.go
- central/networkpolicies/datastore/internal/store/postgres/store_test.go
- central/pod/store/postgres/store_test.go
- central/processbaseline/store/postgres/store_test.go
- central/processbaselineresults/datastore/internal/store/postgres/store_test.go
- central/processindicator/store/postgres/store_test.go
- central/rbac/k8srole/internal/store/postgres/store_test.go
- central/rbac/k8srolebinding/internal/store/postgres/store_test.go
- central/risk/datastore/internal/store/postgres/store_test.go
- central/secret/internal/store/postgres/store_test.go
- central/serviceaccount/internal/store/postgres/store_test.go
- tools/generate-helpers/pg-table-bindings/store_test.go.tpl
The generated store tests do use a specific expected test result each to actually test the behaviour of the store functions against the same permission/scope set.
The point here is to centralize the expected test results in common test cases, and to add a new scope.
CI should be enough
> refactor: Use common test cases for generated SAC store tests: Upsert*

- ui/apps/platform/package.json
- ui/apps/platform/src/Containers/MainPage/Header/CLIDownloadMenu.tsx
- ui/apps/platform/src/app.tw.css
- ui/apps/platform/src/constants/form.constants.ts
- ui/apps/platform/src/css/trumps.css
This is the caboose of the train to delete Network Graph 1.0 code and so on.
Investigate how the follwing style rules relate to PatternFly and Tailwind:
1. `html`
* `line-height: 1.15` is redundant with a PatternFly base.css
2. `body`
* non-standard property that is not in app.tw.css and only in PatternFly for a very specific selector
```css
body {
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
}
```
https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/
> Feel free to use it on light text on dark backgrounds
> but for main portions of text where readability is paramount please leave the default setting alone and let the operating system handle the smoothing.
Therefore, more good than harm to omit global override.
3. various elements
* Tailwind …
> ROX-17716: Delete ui-components and tippy.js from dependencies

- ui/apps/platform/tailwind.config.js
> Tailwind is not purging unused styles because no template paths have been provided.
> The bundle size is significantly larger than recommended.
After having removed partial class names via template literal and removed many obsolete classes, turn on purge option which consists of pattern for any source files which might contain Tailwind classes.
TL;DR Additional 4.5 minutes corresponds to 14 Kb/sec savings: remember when that was a reasonable modem speed?
1. `yarn build` in ui and then compute branch - master for the following
* time 270 = 390 - 120 plus or minus seconds or so
* `wc build/static/css/*.css`
main.css: -3940869 = 801862 - 4742731
total: -3940869 = 1663033 - 5603902
* `ls -al build/static/css/*.css | wc`
0 = 29 - 29 files
2. `yarn start` in ui (did not notice a corresponding …
> chore(ui): Purge unused Tailwind style rules

- central/globaldb/v2backuprestore/restore/postgres.go
The restore database name was central_active_restore instead of central_restore. This means that restore is broken. I will follow up with a PR for a test that ensures restore works
Manually
> fix(restore): Fix Postgres restore database name

- ui/apps/platform/cypress/integration/audit/listeningEndpoints/ListeningEndpoints.helpers.js
- ui/apps/platform/cypress/integration/networkGraphPF/networkGraph.helpers.js
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsTable.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/routePaths.js
Expands the "Network Graph" link into a "Network" section and adds the "Listening Endpoints" page as a sublink of that section.
Load the app and view the sidebar:
Test visiting the network graph and selecting a deployment:
Test visiting the listening endpoints page:
> ROX-18474: Add listening endpoint link to sidebar nav

- ui/apps/platform/src/Containers/MainPage/AsyncComponent.tsx
- ui/apps/platform/src/Containers/MainPage/Body.tsx
Verified that webpack needs to see `import('componentPath')` and so cannot replace component with component path in route configuration.
It seems more likely that change to chunks is from move than from TypeScript.
main.css: 418 = 3757748 - 3757330
total: 1043 = 9901516 - 9900473
1 = 79 - 78 files
Visit pages via left navigation and explore 1 (or 2 for workflow) levels of descendant pages.
> ROX-18642: Move and rewrite AsyncComponent in TypeScript

- ui/apps/platform/src/Containers/Collections/CollectionsTable.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsTable.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/TableModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
Minor issue from axe DevTools on 4 pages:
> Table header text should not be empty
Lighthouse does not report this as an accessibility issue.
Give axe DevTools benefit of the doubt that `Th` element without text, might be a problem for some screen readers even with `aria-label` attribute.
In case the benefit of the doubt is too generous, increase our empathy with customers not to inflict opinions about cloud security.
1. Visit /main/collections to see collections table
2. Visit /main/integrations, and then click a card to see integrations table
3. Visit /main/policy-management/policies, click **Create policy**, on step 3 drag **Image signature**, and then click **Select** and temporarily edit code to render table even though there are no signature …
> chore(ui): Replace empty Th with Td to fix accessibility issues

- sensor/kubernetes/eventpipeline/component/component.go
- sensor/kubernetes/eventpipeline/component/mocks/component.go
- sensor/kubernetes/eventpipeline/pipeline.go
- sensor/kubernetes/eventpipeline/pipeline_impl.go
- sensor/kubernetes/eventpipeline/pipeline_test.go
- sensor/kubernetes/listener/listener.go
- sensor/kubernetes/listener/listener_impl.go
- sensor/kubernetes/listener/resource_event_handler.go
- sensor/kubernetes/listener/resource_event_handler_impl.go
- sensor/kubernetes/listener/resource_event_handler_impl_test.go
- sensor/tests/connection/k8sreconciliation/reconcile_test.go
- sensor/tests/connection/k8sreconciliation/yaml/netpol-block-egress.yaml
- sensor/tests/connection/k8sreconciliation/yaml/nginx.yaml
- sensor/tests/connection/k8sreconciliation/yaml/nginx3.yaml
- sensor/tests/helper/helper.go
This PR relies on a few past PRs to make kubernetes reconciliation work when flipping between offline and online mode.
- #6958: Add context to every messages in the pipeline. This prevents messages to linger in the queue and mess up the reconciliation.
- #6692: Adds interface for cleaning up the in-memory stores. This is called when going into offline mode. This is required because during the reconciliation, we might pick up old deployments that were deleted while sensor wasn't listening to events.
- #6376: Adds offline mode for Kubernetes listeners. This triggers the reconciliation once the listeners are re-created.
> ROX-17157: Fix reconciliation for offline mode for Kubernetes Listener

- Makefile
- image/rhel/.gitignore
- image/rhel/Dockerfile
- image/rhel/create-bundle.sh
Removes the UI copy and third party notices copy from the bundler
CI
> refactor(image): Copy UI and notices directly to Dockerfile

- ui/apps/platform/src/routePaths.ts
Write route descriptions that correspond to conditional rendering in Body element.
After resource simplification, multiple resources imply only **and** never **or** as far as I am aware.
**Limitation**: We cannot have one route render either old component or new component according to feature flag. Even when Linda and I did completely replace classic policies with PatternFly policies, we used a temporary separate route during development.
Will add steps to a section following feature flags
https://github.com/stackrox/stackrox/tree/master/ui/apps/platform#feature-flags
1. Add path variable for new route.
2. Add route description with path as computed key for new route. Because we will stop adding title to `basePathToLabelMap` the net number of steps in routePaths remains the same.
In the …
> ROX-18681: Add routeDescriptionMap and isRouteEnabled to routePaths

- scanner/services/converters.go
- scanner/services/converters_test.go
The conversion functions from Clair to Scanner types related to creating index reports have been included in this patch. The Scanner V4 APIs use protobuf types that require translation from the underlying Clair Core types.
🌳 master
├─ :arrow_up_small: **ROX-18605: Initial conversion functions for Create Indexer Report #7043** :point_left: 
├─── :arrow_up_small: ROX-18605: Implement create index report #7077
├───── :arrow_up_small: ROX-18605: Implement Indexer Get and Has endpoints #7099
- UTs.
> ROX-18605: Initial conversion functions for Create Indexer Report 

- central/sensor/service/connection/connection_impl.go
- central/sensor/service/connection/sensorevents.go
Fix panic in Central when resource is nil
sensor/service/connection: 2023/07/26 18:53:21.480780 sensorevents.go:97: Error: Received event with unknown resource from cluster remote (3eb5fe5a-c30c-40c3-aee2-24cd2c1ec4ab). May be due to Sensor (4.1.x-511-g11a58138f9-dirty) version mismatch with Central (4.1.x-511-g11a58138f9-dirty)
Will add an event and send from Sensor
> ROX-18645: Handle events with missing resource

- sensor/kubernetes/listener/listener.go
- sensor/kubernetes/listener/listener_impl.go
- sensor/kubernetes/listener/resource_event_handler.go
This resulted from a PR that was merged recently: #7032
This might be a workaround for the moment, just to avoid using mutex. But perhaps a better approach would be to recreate the listeners entirely when going into offline mode.
> ROX-0000: Fix mutex taking more than 5s to unlock

- central/internal/server.go
The goal of this PR is to protect cluster-internal port(used to get central diagnostic data in ACSCS) with HTTPS. This is due to the fact that central diagnostic data is sensitive and shouldn't be unencrypted.
We reuse mTLS certificate here as we don't care if caller trusts our certificate or not - we only use it for encryption. 
1. Deployed stackrox locally
2. Adjusted `ROX_MANAGED_CENTRAL` to `true`
3. `port-forward` to Central
4. `curl https://localhost:9095/diagnostics` does not work, while `curl --insecure https://localhost:9095/diagnostics` returns diagnostic data
> fix: Secure cluster-internal port with HTTPS

- ui/apps/platform/src/Containers/MainPage/AsyncComponent.tsx
- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/routePaths.ts
Follow up from #7118
* Also order path variable declarations to minimize merge conflicts when multiple people add routes.
* Move `vulnManagementReportsPath` and `vulnManagementRiskAcceptancePath` above `vulnManagementPath` and add a comment.
* Replace one feature flag with array of feature flags.
Will add steps to a section following feature flags
https://github.com/stackrox/stackrox/tree/master/ui/apps/platform#feature-flags
In src/routePaths.ts file:
1. Add path variable for new route.
2. Add property to `routeDescriptionMap` object.
Because we will stop adding title to `basePathToLabelMap` the net number of steps in routePaths remains the same.
In src/Containers/MainPage/Body.tsx file:
1. Import path variable for new route.
2. Add property to `routeComponentMap` object.
You save a step …
> ROX-18684: Add routeComponentMap and call isRouteEnabled in Body

- CHANGELOG.md
- pkg/env/registry_mirroring.go
Adds an environment variable `ROX_REGISTRY_MIRRORING_ENABLED` that will be used to control enabling / disabling support for registry mirroring capabilities.
Is un-used as of this PR, will be consumed as the stories in ROX-11347 are implemented.
Unit tests and docs will be added as part of stories mentioned in ROX-11347
N/A
> ROX-18247: Add env var for registry mirroring support

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/DeleteReportModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/hooks/useDeleteModal.ts
This PR adds some content to the vuln report details page. You should see the breadcrumbs, the title, and an actions dropdown
> ROX-17856: Adding header, tabs, and actions for report details page

- CHANGELOG.md
- operator/pkg/central/reconciler/reconciler.go
- operator/pkg/proxy/translation.go
- operator/pkg/proxy/translation_test.go
- operator/pkg/securedcluster/reconciler/reconciler.go
If the operator runs with proxy environment (HTTP_PROXY, HTTPS_PROXY, NO_PROXY) variables set for its deployment and the CR also configures the same proxy environment variables in its `customize` field. The operator merges both configuration to an invalid state for env variables like this:
```yaml
spec:
customize:
envVars:
- name: HTTP_PROXY
value: http://10.68.248.34:80
valueFrom:
secretKeyRef:
key: "HTTP_PROXY"
name: central-stackrox-central-services-proxy-env
```
Having a conflict like this lead to a helm releases that can't be applied. In ROX-18477 this lead to an endless reconciliation retry that was responsible for the creation of secrets in the stackrox namespace.
This happens due to a conflict when merging environment variable proxy configuration with CR proxy configuration. This …
> ROX-18477: operator delete valuesFrom in proxy config if values is set

- sensor/common/component.go
- sensor/common/scannerdefinitions/http_handler.go
- sensor/common/scannerdefinitions/http_handler_test.go
- sensor/common/sensor/sensor.go
This PR is part of the effort of making Sensor resilient to Central disconnects.
When the connection with central stops, local scanner might still request scanner definitions from Sensor. In this case, avoid making a call to Central and return an error directly to Scanner.
> ROX-17318: Don't return scanner definitions when in offline mode

- sensor/common/detector/detector.go
- sensor/common/detector/mocks/detector.go
- sensor/common/networkflow/manager/manager_impl.go
- sensor/common/networkflow/manager/manager_impl_test.go
- sensor/common/networkflow/manager/testing_test.go
Add context to the `ExpiringMessage` as well as the detector calls. This allow us to cancel messages that shouldn't be sent upon disconnection with central.
- This is a followup of #6959
> ROX-18608: Add context to NetworFlows offline v1

- ui/apps/platform/src/Components/PatternFly/SeverityIcons.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/ImagesAtMostRiskTable.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/MostRecentViolations.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/PolicyViolationTiles.tsx
- ui/apps/platform/src/constants/visuals/colors.ts
- ui/apps/platform/src/css/acs.css
- ui/apps/platform/src/utils/chartUtils.ts
1. Low severity is gray on main dashboard but blue everywhere else
2. High/important severity is orange-300 on dashboard but orange-200 everywhere else.
3. SecurityIcon for critical and important on dashboard but CriticalRiskIcon and AngleDoubleUpIcon everywhere else. 
Find in Files `severityColors` has 10 results in 5 files
1. src/constants/visuals/colors.ts
```ts
export const severityColors: Record<PolicySeverity, string> = {
LOW_SEVERITY: 'var(--color-severity-low)',
MEDIUM_SEVERITY: 'var(--color-severity-medium)',
HIGH_SEVERITY: 'var(--color-severity-important)',
CRITICAL_SEVERITY: 'var(--color-severity-critical)',
};
```
2. src/Containers/Dashboard/Widgets/ImagesAtMostRiskTable.tsx vulnerability severity
```tsx
<SecurityIcon
className="pf-u-display-inline pf-u-mr-xs" …
```
> fix(ui): Fix inconsistent severity colors and icons on dashboard

- ui/apps/platform/src/Containers/VulnMgmt/Reports/VulnMgmtReports.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ObservedCVEs/PendingApprovalPopover.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/RiskAcceptancePage.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/pathsForRiskAcceptance.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReportingPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/pathsForVulnerabilityReporting.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
- ui/apps/platform/src/routePaths.ts
Follow up comment by Dave https://github.com/stackrox/stackrox/pull/7128#pullrequestreview-1549738696
> Are the paths here and below that were not moved into the alphabetized list ones that are used only for routing inside the Container level? If so, I think it would be helpful noting that in comments that split the two sections so that new top level routes are sure to be added to the list above.
Set an example to **minimize** sub-route paths at global scope: only for inter-container links.
1. Delete obsolete.
2. Add to comments which containers import paths for links.
3. Move sub-route paths into containers.
Forgive the somewhat verbose names, but even after all these years, my eyes sometimes rebel as camelCase for proper nouns like riskAcceptancePaths
4. Write `TODO` comments to verify …
> chore(ui): Delete unused export variables in routePaths

- pkg/grpc/authn/tokenbased/extractor.go
When a modifying operation is performed, [audit log captures user identity](https://github.com/stackrox/stackrox/blob/bcf64d26fa015b91731d2febaa0ae238951f8b23/central/audit/audit.go#L95) associated with the operation. In case anonymous API token is presented, the only identifiable information is [identity's `FriendlyName`](https://github.com/stackrox/stackrox/blob/a6c70b876d86872a0f32ac5f0bef43412866b4c4/pkg/grpc/authn/tokenbased/identity.go#L50-L57), which currently captures associated roles and token expiration.
This PR adds token ID (`jti`) and name to identity's `FriendlyName`. It also ensures expiration is printed in RFC3339 time format instead of debug string.
`FriendlyName` before: `anonymous bearer token with roles Admin,Continous Delivery (expires 2023-07-28 21:55:20.775166 +0200 …
> ROX-16267: Clarify token's provenance

- .github/dependabot.yaml
dependabot's UI PRs are stale. Some of them are year old. We can decrease limit to 1 or even disable it as we do not use it for UI dependencies. 
- https://github.com/stackrox/stackrox/pull/12 opened on 2021
N/A
> chore(dependabot): limit open UI PRs to 1

- central/detection/service/service_impl.go
- central/detection/service/service_impl_test.go
- central/image/service/service_impl.go
- pkg/images/enricher/enricher.go
- pkg/images/enricher/enricher_impl.go
- pkg/images/enricher/enricher_impl_test.go
- pkg/signatures/public_key_verifier.go
Currently when trying to make use of the `image.Names` field (i.e. when having an image with the same digest across either multiple repositories or different tags) then it currently isn't possible to receive valid signatures and signature verification results.
While it is possible to upsert both images within Central's database, it won't be possible to trigger a re-fetching of signatures and signature verification by passing the `--force` flag.
When the `--force` flag is passed, the `Names` field will be overwritten and upserted within Central. This is due to the fact that we do not attempt to fetch the previously existing `Names` due to the `ForceRefetch` option within the enrichment context.
For other consumers of the image enricher such as the reprocessing loop or the "internal scan …
> fix: new fetch option for images enriched via roxctl

- pkg/search/postgres/store.go
`GetAll` is enabled only for certain stores and the option to enable it has following comment:
https://github.com/stackrox/stackrox/blob/286a94051140da4ef181478a61aed7ed11da339f/tools/generate-helpers/pg-table-bindings/main.go#L103-L104
To prevent usage outside of an interface that exposes this method only for [certain stores](https://github.com/search?q=repo%3Astackrox%2Fstackrox+--get-all-func&type=code) we will mark it as deprecated with a comment to prefer using `Walk` that could be more efficient if we need to just do some operation on all values but not need them all at once.
CI
> ROX-18312: Mark GetAll as deprecated in GenericStore

- ui/apps/platform/src/Containers/NetworkGraph/hooks/useNetworkPolicySimulator.ts
- ui/apps/platform/src/Containers/NetworkGraph/simulation/CodeCompareIcon.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/CompareYAMLModal.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesYAML.css
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesYAML.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/SimulateNetworkPolicyButton.tsx
- ui/apps/platform/src/services/NetworkService.js
This adds a button to the network policy simulation that allows the user to view the generated policies side-by-side with the existing network policies.
View the network graph page and enable the simulator. Verify that the "View active YAMLs" tab works correctly, and identically to how it did before this change, showing all existing network policies for deployments in the current scope.
Return to the "Simulate network policies" tab and generate network policies:
Click the "Compare changes" button to view the generated policies side by side with the existing network policies:
Close the modal and change the network graph scope - ensure that the updated policies are reflected in the modal when generated again.
The code editor theme button …
> ROX-18468: Add existing network policies YAML to simulator side panel

- ui/apps/platform/src/Containers/Compliance/Entity/Cluster.js
- ui/apps/platform/src/Containers/Compliance/Entity/Control.js
- ui/apps/platform/src/Containers/Compliance/Entity/Deployment.js
- ui/apps/platform/src/Containers/Compliance/Entity/Namespace.js
- ui/apps/platform/src/Containers/Compliance/Entity/Node.js
- ui/apps/platform/src/Containers/Compliance/Entity/ResourceTabs.js
- ui/apps/platform/src/Containers/Compliance/widgets/ComplianceByStandard.js
- ui/apps/platform/src/Containers/Compliance/widgets/HorizontalBarChart.js
- ui/apps/platform/src/Containers/Compliance/widgets/colorsForCompliance.ts
1. Compliance dashboard with scan results: 2 minor issues
> id value must be unique
```svg
<pattern id="bar-background" patternUnits="userSpaceOnUse" width="6" height="6">
```
2. Compliance entity single page: 1 serious issue
> Element has insufficient color contrast of 2.28 (foreground color: #5fb2f7, background color: #ffffff, font size: 10.5pt (14px), font weight: bold). Expected contrast ratio of 4.5:1
1. HorizontalBarChart defines `pattern` element with same `id` for each instance.
Factor out `getColor` function for consistency with ComplianceByStandard sunburst graph.
2. Replace text color with background color for active tab as in grouped tabs (the corresponding tabs in Configuration Management and Vulnerability …
> fix(ui): Fix accessibility issues for id and active tab in Compliance

- ui/apps/platform/src/routePaths.ts
As titled.
Required permissions are derived from the two endpoints this page hits, [here](https://github.com/stackrox/stackrox/blob/master/central/deployment/service/service_impl.go#L39) for Deployment and [here](https://github.com/stackrox/stackrox/blob/master/central/processlisteningonport/service/service_impl.go#L19) for DeploymentExtension.
Manually set 'DeploymentExtension' to `NO_ACCESS` from a breakpoint in the UI. Do the same with `Deployment`.
- The route returns a 404 page
- The link is not visible in the lefthand navigation
Load the UI with a user that has permissions for both resources:
> ROX-18133: Add permission checks to listening endpoints route

- sensor/common/clusterid/cluster_id.go
- sensor/common/metrics/info.go
- sensor/common/metrics/init.go
- sensor/common/metrics/metrics.go
- sensor/kubernetes/clustermetrics/cluster_metrics.go
Add a rox_central_info metric, which is intended as a metric series sent to OpenShift Telemeter for telemetry purposes. It captures some basic information about the Central installation:
* `sensor_id`: this is the ACS cluster ID. Note that `cluster_id` already has a meaning within OpenShift telemetry as the ID of the OpenShift cluster. The label is renamed to make it unambiguous.
* `central_id`: the ID of the connected Central
* `sensor_version`: ACS version (e.g. 4.2.0)
* `hosting`: self-managed or cloud-service
* `install_method`: manifest, helm or rhacs-operator. Implemented via an env var, which we will need to set up (TODO).
* `secured_nodes`, `secured_vcpu`: sum of all nodes
* `value`: this is always 1 for easier counting in PromQL queries …
> ROX-18274: add `rox_sensor_info` metric

- central/role/sachelper/sachelper.go
- central/role/service/service_impl_test.go
- pkg/sac/allow_fixed_scopes_checker_core.go
- pkg/sac/resources/list.go
**_Summary_**:
The AllowFixedScope checker core has a simplistic behaviour that is not consistent with the built-in scope checker core for cluster scoped resources.
In order to align the behaviour, a first step is taken in order to re-structure the AllowFixedScope checker core to later be able to align the behaviour.
**_Details_**:
Scoped access control basically checks whether the requested is granted access to a given action (accessMode) on a given resource, potentially for a given object. Objects being granted access to are tied to a scope level (global, tied to a cluster or tied to a namespace). Access checks to a given object are performed against an action on a resource, and potentially (depending on the resource scope level) a set of allowed clusters or namespaces in clusters.
The …
> ROX-9981: Refactor AllowFixedScopeCheckerCore

- roxctl/connectivity-map/netpol_test.go
- roxctl/connectivity-map/testdata/minimal/output.json
- roxctl/connectivity-map/testdata/minimal/output.txt
Add check for generated output of netpol generate so we fail in unit tests not only in bats.
Refs:
- https://github.com/stackrox/stackrox/pull/7139
CI
> test(netpol): check netpol generated output

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
Found an issue where if you select a namespace in the network graph, then clear the selection so that only "cluster" is selected, the graph and sidebar will continue to render.
Load the NG
Select a namespace
De-select the namespace
The empty section should not scroll down to show the stale graph visualization.
Previous behavior:
https://github.com/stackrox/stackrox/assets/1292638/372f16c7-c6e3-4f9f-ab87-b66f1da0eaca
> fix(ui): Don't render network graph when no namespace is selected

- sensor/tests/connection/alerts/alert_test.go
- sensor/tests/connection/alerts/data/policies.json
- sensor/tests/connection/alerts/yaml/nginx.yaml
This ticket became a no-op from the production code perspective. The detector is already being cleaned up when the connection is restarted since we do a full policy sync see [here](https://github.com/stackrox/stackrox/blob/6fae80c1358dbc1e9c828accd5d3135e61f2c6ba/sensor/common/detector/detector.go#L226).
> ROX-17643: Detector Cleanup

- sensor/common/sensor/sensor.go
The exponential back-off was not being reset after sensor reconnection with central. This led to sensor always increasing the retry time and never reseting it.
> ROX-0000: reset the exponential back-off on reconnect

- sensor/kubernetes/clusterhealth/updater.go
- sensor/kubernetes/clusterhealth/updater_test.go
Cluster Health now stops the ticker if sensor is offline. Additionally, messages that were in the pipeline before stopping the component are cancelled upon re-connection. This avoids sending an incorrect state of the secured cluster to central on re-connection. This cancellation is a nice to have but not crucial since even if sensor sends an incorrect state it will be updated after 30s.
> ROX-17324: clusterhealth offline v1

- qa-tests-backend/scripts/lib.sh
Per title, the URLs for merge CI logs are incorrect.
CI is sufficient - will check again after merge
> fix(ci): add missing path for merge logs

- central/pruning/pruning.go
- central/pruning/pruning_test.go
- central/pruning/singleton.go
This PR adds pruning task for report history(snapshots). Report history is pruned based on value of report history config. 
Will add another PR for unit tests
Test Done:
Unit tests passed
e2e tests passed
> ROX-18639: Added changes for report history pruning task

- .github/workflows/build.yaml
Per @connorgorman "we can’t build the race condition images for other arches cause cgo will be enabled and we’re relying on the fact it’s cross compiled statically". This PR removes the targets using GHA matrix exclude.
> fix(builds): exclude arm64, ppc64le from -race builds

- operator/tests/central/basic-central/10-assert.yaml
- operator/tests/common/delete-central-errors-cluster.envsubst.yaml
- operator/tests/common/delete-central-errors.yaml
- operator/tests/securedcluster/basic-sc/40-assert.yaml
- operator/tests/securedcluster/basic-sc/40-enable-monitoring.yaml
- operator/tests/securedcluster/basic-sc/41-disable-monitoring.yaml
- operator/tests/securedcluster/basic-sc/41-errors.yaml
* Removed the auth reader assert in the operator e2e tests because they now depend on the dynamically generated namespace name.
* Added `clusterName` to secured cluster CR as it seems to be required.
screenshots.
> fix(operator): fix openshift-monitoring tests

- sensor/common/registry/registry_store.go
- sensor/common/registry/registry_store_test.go
This PR aims to fix a data race in the registry store (see [ci failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-merge-gke-sensor-integration-tests/1686673827150434304))
* ~Should fix~ Partially fixes: [ROX-18767](https://issues.redhat.com/browse/ROX-18767)
> ROX-18767: add lock in Cleanup

- image/templates/helm/stackrox-central/templates/_init.tpl.htpl
Reverts stackrox/stackrox#7209
This broke operator tests, which provide a password via a secret rather than literal value.
> ROX-12724: Revert "Verify external source and password"

- central/networkgraph/service/masker.go
- central/networkgraph/service/service_impl.go
- central/networkgraph/service/service_impl_test.go
The investigation of the CI issue in the ROX-18322 highlighted the fact that namespaces and deployments can show up in different order in the sequence in which these are masked.
In order to ensure that two consecutive calls to `GetNetworkGraph` get the same results regardless of the order in which flows and entities are fetched from database.
New Unit test output against master
```
=== RUN …
```
> ROX-18322: Mask deployments for network graph in a deterministic way

- release/scripts/scan-images-with-roxctl.sh
Per title. When the StackRox CI instance is down it is useful to be able to disable this check.
> fix(ci): allow roxctl image check to be disabled

- central/globaldb/postgres.go
- central/telemetry/gatherers/postgres.go
When connecting to an external postgres we will likely not have access to other databases within that instance and we shouldn't.  We also do not care about the sizes of those databases.  So we only need to grab the size for the specified database in the connection so that growth can be monitored through our metrics.
```
rox_central_postgres_db_size_bytes{database="stackrox"} …
```
> ROX-18824: size stats only for specified db when external

- .github/workflows/build.yaml
Fix the make tag for manifest list pushes
CI + nightly
> fix(build): Add support for tagged builds to manifest push

- scripts/ci/lib.sh
Retags the scanners into multi-arch, this will allow us to retag when other arches exist
screenshots.
> fix(build): Create manifest lists for retagged images

- image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
- image/templates/helm/stackrox-central/templates/_init.tpl.htpl
- image/templates/helm/stackrox-central/values-public.yaml.example.htpl
- image/templates/helm/stackrox-central/values.yaml.htpl
- image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl
- image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
- image/templates/helm/stackrox-secured-cluster/values-public.yaml.example
- pkg/helm/charts/tests/centralservices/testdata/helmtest/central.test.yaml
- pkg/helm/charts/tests/centralservices/testdata/helmtest/injected-cabundle-cm.test.yaml
- pkg/helm/charts/tests/centralservices/testdata/helmtest/openshift-auth.test.yaml
- pkg/helm/charts/tests/centralservices/testdata/helmtest/openshift-autosense.test.yaml
- pkg/helm/charts/tests/centralservices/testdata/helmtest/openshift-monitoring.test.yaml
- pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner.test.yaml
- pkg/helm/charts/tests/centralservices/testdata/helmtest/sccs.test.yaml
- pkg/helm/charts/tests/securedclusterservices/flavor/testdata/helmtest/suite.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/admission-control.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/audit-logs.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/env.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/injected-cabundle-cm.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/legacy-settings.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/openshift-monitoring.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-slim.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/sccs.test.yaml
Enable OpenShift platform monitoring integration via `monitoring.openshift.enabled: true` by default. On OpenShift 3 clusters we default back to `monitoring.openshift.enabled: false`.
Note that changes to the Helm test code such as
```
values:
monitoring:
openshift:
enabled: false
```
are required in some cases because the Prometheus related CRDs are not known to the tests. Because they are not related to the actual test intend, I opted to disable the feature for these tests.
Deployed on OCP test cluster.
> feat(helm): enable OpenShift monitoring by default

- operator/apis/platform/v1alpha1/central_types.go
- operator/apis/platform/v1alpha1/common_types.go
- operator/bundle/manifests/platform.stackrox.io_centrals.yaml
- operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml
- operator/config/crd/bases/platform.stackrox.io_centrals.yaml
- operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml
* Move `GlobalMonitoring` into common types.
* Flip default to `true`.
screenshots.
> feat(operator): enable OpenShift monitoring by default in CRD

- sensor/tests/connection/alerts/alert_test.go
- sensor/tests/connection/connection_test.go
- sensor/tests/connection/k8sreconciliation/reconcile_test.go
- sensor/tests/helper/helper.go
- sensor/tests/resource/imagescan/imagescan_test.go
- sensor/tests/resource/networkpolicy/networkpolicy_test.go
- sensor/tests/resource/pod/pod_test.go
- sensor/tests/resource/role/role_test.go
- sensor/tests/resource/service/service_test.go
Calls to `c.t.FailNow` or `c.t.Fatal` can lead into a situation where we use the incorrect `t` object and the parent test is being failed from a subtest. This is not allowed (see for example https://github.com/golang/go/issues/58129) and may lead to following failures:
```
=== NAME  Test_NetworkPolicy
helper.go:607: timeout reached waiting for violation state (Ingress applied: egress violation): expected violations not found: [Deployments should have at least one egress Network Policy]
=== NAME  Test_NetworkPolicy/Test_Deployment_NetpolViolations/Ingress_applied:_egress_violation
testing.go:1471: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
=== NAME  Test_NetworkPolicy/Test_Deployment_NetpolViolations
testing.go:1471: test executed …
```
> ROX-18844: Fix sensor integration test harness

- scripts/ci/lib.sh
Per title. Scanner images are not produced with 'latest' tags, so there is no need for a manifest for them.
> fix(builds): skip latest manifest for scanner images

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#12-17-3
* Fixed an issue where unnecessary requests were being paused. No longer sends `X-Cypress-Is-XHR-Or-Fetch` header and infers resource type off of the server pre-request object.
1. `yarn start` in ui
2. `yarn cypress-open` in ui/apps/platform
* vulnmanagement/entitypages.test.js
> chore(e2e): Update cypress 12.17.3 devDependencies in ui

- scripts/ci/lib.sh
I thought collector images were produced with `:latest-<arch>` tags but it is not so.
> fix(builds): skip latest manifest for collector images

- image/templates/helm/stackrox-central/templates/_init.tpl.htpl
Warn if external is true for central database but no password or source is provided during Helm chart install.
We still need to allow it because the secrets and configuration may be managed by operator or other sources. 
Helm install manual test.
> ROX-12724: Warn external DB without source or password

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css
As titled. The compact padding was foiled by the addition of the "Feedback" button.
Load the NG and view tables with kebab menus in the sidebar.
Before:
After:
Before:
After:
> ROX-18560: Re-add padding to NG sidebar menu td cells

- central/reports/common/blob.go
- central/reports/service/v2/service_impl.go
- central/reports/service/v2/service_impl_test.go
Report Generator generates blob path as `common.GetReportBlobPath(configID, reportID)` but download report service generated blob path as `common.GetReportBlobPath(reportID, configID)`. This PR makes both ordering consistent.
If any of these don't apply, please …
> Fix blob path id generation in report service to match the path generated by report generator

- operator/hack/build-index-image.sh
Add `skip-tls-verify` flag for opm render to be able to build index image with insecure registry.
I added this flag for development purposes, similar to the `--use-http` flag.
It is needed to pull bundle images from insecure registries, in particular OpenShift internal registries, namely `crc` and infra. This allows you to test local changes on OpenShift clusters without pushing the changes, open a PR and wait for CI to push the images, speeding up development time.
It seems like `opm render` does not use docker daemon and fails to pull the images even if I specify an insecure registry in the docker configuration.
Tested locally
> feat(operator): Add skip-tls-verify flag for opm render

- sensor/common/detector/detector.go
- sensor/common/detector/enricher.go
- sensor/common/detector/mocks/detector.go
- sensor/common/processsignal/pipeline.go
- sensor/common/processsignal/pipeline_test.go
- sensor/common/sensor/central_communication_impl.go
- sensor/kubernetes/eventpipeline/output/output_impl.go
- sensor/kubernetes/eventpipeline/pipeline_impl.go
- sensor/kubernetes/eventpipeline/pipeline_test.go
Rather than having detector have its own context (like we first discussed), this PR proposes a simpler approach. Add `context.Context` to the detector API, allowing the components left of detector in pipeline to provide their context in the messages. 
> ROX-17326: Add context to detector

- operator/config/default/kustomization.yaml
- operator/config/default/manager_webhook_patch.yaml
- operator/config/manifests/kustomization.yaml
When I tried to add another volumeMount to the deployment, it added the webhook mount instead of mine, which was confusing. This change adds a few more comments for future generations explaining why the kustomization is done this way.
Comment changes only, CI is sufficient.
> ROX-18918: Add clarifying comments for the webhook kustomization

- central/policy/datastore/datastore_impl.go
- central/policy/datastore/datastore_impl_test.go
- central/policy/store/boltdb/store.go
Required for bolt cleanup.
screenshots.
> ROX-17689: Move policy error definitions to datastore from bolt store

- scripts/ci/lib.sh
Expose user friendly information about possible flakes that were already reported to jira.
Example: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/7250/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1688887101317189632
Refs: 
- https://github.com/stackrox/junit2jira/pull/16
N/A
> chore(tests): expose flakes in prow 

- qa-tests-backend/scripts/lib.sh
- scripts/ci/gke.sh
- scripts/ci/lib.sh
- scripts/ci/store-artifacts.sh
- tests/e2e/run-scale.sh
It's just a styling change to keep our custom list font smaller. Currently we are using `<h4>` that is `24px` the same size as `.mdl-card__title-text` (aka `JUnit` lens section title)
N/A
> chore(tests): remove header from title

- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesGenerationScope.css
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesGenerationScope.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx
- ui/apps/platform/src/Containers/NetworkGraph/utils/simulatorUtils.ts
Shows the current scope of selected deployments/namespaces/cluster in the network simulator side panel in order to give users a clear idea of what entities will be used to generated the network policies.
Open the network simulator panel, and verify the displayed text against the selected scope and the data in the graph.
One namespace selected:
Two namespaces selected:
Multiple namespaces selected, multiple deployments selected from **one** of those namespaces:
Multiple namespaces selected with deployments selected from each:
The scope view is also visible after policies have been generated:
> ROX-18185: Add scope of netpol generation to simulator side panel

- qa-tests-backend/src/main/groovy/common/Constants.groovy
- qa-tests-backend/src/main/groovy/services/PolicyService.groovy
- qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
- tests/e2e/run-e2e-tests.sh
This change adds ImageScanningTest to the parallel test set. In practice it will run after AdmissionControllerTest because ImageScanningTest requires a READ/WRITE lock on scanning configuration so they will not run together (and A is before I). As more tests are parallelized however these will be able to run concurrently with ImageScanningTest. i.e. no immediate performance benefit is expected from this change.
There are essentially three changes:
- A lock to prevent tests with different scanner requirements affecting each other (documented in the code).
- A separate namespace used for the tests deployments.
- A clone of policies used by the test scoped to the tests namespace.
CI + A standalone cycle of 50 runs. Some flakeage was seen but this is consistent with the test flakiness in …
> ROX-18810: Add ImageScanningTest to the parallel set

- pkg/centralsensor/caps_list.go
- sensor/common/compliance/node_inventory_handler_impl.go
- sensor/common/compliance/node_inventory_handler_test.go
Apparently Sensor `NodenIventoryHandler` was already pretty well tested (coverage 91%). I iterated over the code again and improved few things. The coverage for that file is now at 94.4%.
The original idea to implement that with e2e tests has not been followed, because equivalent unit tests were possible.
> ROX-16861: Test Sensor's RHCOS functions

- ui/apps/platform/src/Containers/NetworkGraph/simulation/DeploymentScopeModal.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesGenerationScope.tsx
Makes the deployment section of the NG simulator sidebar scope clickable.
Clicking on this element opens a modal with a preview of all the deployments in the selected scope.
Select namespace and/or deployments and open the network policy simulator sidebar:
Click the deployment link to open the modal of currently selected deployments:
Sort by deployment or namespace:
> ROX-18467: Show scoped deployments in network policy simulator modal

- pkg/notifiers/jira/jira.go
- pkg/notifiers/jira/jira_fake_test.go
Currently only basic auth is tried. If a user provides an oauth token or JWT in the password field, then auth will fail.
With this change, a user can provide the token in the "password or api token" field (with a dummy username value), and bearer auth will succeed after a failed basic auth attempt.
Deployed the PR image to a cluster and tried to add a Jira integration to issues.redhat.com using my Personal Access Token.  Successfully created this [test issue](https://issues.redhat.com/browse/ROX-18333).
> ROX-17992: Try bearer auth as fallback in jira notifier

- ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx
- ui/apps/platform/src/Containers/Compliance/Entity/Header.js
- ui/apps/platform/src/Containers/Compliance/List/Header.js
Because of links between entities, routePaths specifies all needed resources.
Scan requires READ_WRITE_ACCESS for Compliance resource.
Each component that has conditional rendering takes responsibility to get permissions via hook.
Delete extra levels of flex alignment in Header components.
It looks like deletions more than balanced additions.
main.css: 0 = 3759691 - 3759691
total: -450 = 9931978 - 9932428
0 = 81 - 81 files
1. Visit /main/compliance
* See **Scan environment** and **Manage standards** buttons only if READ_WRITE_ACCESS for Compliance
2. Click a standard link
* See **Scan** button only if …
> ROX-18867: Add conditional RBAC in Compliance 1.0

- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
- ui/apps/platform/src/Containers/Risk/RiskTablePanel.js
- ui/apps/platform/src/services/DeploymentsService.ts
Switches from the indeterminate "1 of many" pagination UX to the traditional paged UX. Initially it wasn't possible to determine how many rows were in the table, but with the updated expandable design we can easily do this.
Bonus fix: fixes the layout of the toolbar in Firefox.
Best reviewed with "Hide whitespace" on.
View the listening endpoints page and test the traditional pagination:
Firefox before:
Firefox after (still not pixel perfect, but no longer broken):
> fix(ui): Add traditional pagination to listening endpoints page

- central/reports/common/report_formatter.go
- central/reports/scheduler/schedule.go
- central/reports/scheduler/v2/reportgenerator/report_gen_impl.go
- central/reports/scheduler/v2/reportgenerator/report_gen_impl_test.go
If the report is empty and it is to be
1. emailed: keep the current logic to not send an attachment
2. downloaded: write the compressed empty report to blob to be downloaded.
- ~ ] Unit test and regression tests added
existing unit tests.
> ROX-18956: Generate empty report to download in case of no cve found

- central/probeupload/manager/manager.go
- pkg/probeupload/server_handler.go
- pkg/probeupload/server_handler_test.go
- sensor/common/component.go
- sensor/common/scannerdefinitions/http_handler.go
- sensor/common/sensor/notifiable.go
- sensor/common/sensor/sensor.go
This PR readds https://github.com/stackrox/stackrox/pull/7178 after adding a fix. 
Please review by commits:
This PR reverts the revert (1st commit) and adds a fix (2nd commit) for the bug where the Central handler was starting in offline mode and never went online.
Additionally, it names one component to make identification of it easier in the logs (3rd commit), and adds regression test  (4th commit) for the issue fixed in the 2nd commit.
> ROX-17319: Handle offline mode for collector driver downloads (fixed)

- pkg/features/list.go
- sensor/tests/connection/connection_test.go
Enables `ROX_PREVENT_SENSOR_RESTART_ON_DISCONNECT` feature flag.
Many since the beginning of the release
> ROX-18747: Enable prevent sensor restart feature flag 

- pkg/env/sensor.go
Changed exponential backoff for gRPC connection to match Kubernetes at 10s initial, 5min max.
Confirmed that the new values match the restart policy of Kubernetes, seen here: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy
> ROX-17647: Use kubernetes timeouts for gRPC

- central/compliance/aggregation/aggregation.go
This PR removes superfluous code and reduces memory use for > 90%.
In `Control` implementation we do heavy operation of creating new object (`ToProto`)
https://github.com/stackrox/stackrox/blob/1bc6e2e294ee09a3cfffa8cfad5d11e4c20acf59/central/compliance/standards/registry.go#L212-L217
This is not necessary as in `GetCategoryByControl` we access the same element (`r.controlsByID[controlID]`) and return it without any modifications.
By removing first check we can significantly reduce number of allocations.
https://github.com/stackrox/stackrox/blob/1bc6e2e294ee09a3cfffa8cfad5d11e4c20acf59/central/compliance/standards/registry.go#L201-L209
```bash
name                 old time/op    new time/op    delta
AggregatedResults-8     175ms ± 1%     153ms ± 2%  -12.22%  (p=0.000 n=10+10)
name …
```
> ROX-17414: remove duplicated existence check

- ui/apps/platform/src/Containers/NetworkGraph/components/CIDRFormModal.tsx
- ui/apps/platform/src/hooks/useTimeout.test.ts
- ui/apps/platform/src/hooks/useTimeout.ts
Adds a `useTimeout` hook that wraps `setTimeout` and automatically cleans up when the parent component unmounts.
Implements the first usage of this hook in the CIDRModal component of the Network Graph.
```typescript
const callback = (message: string) => console.log(string);
const [startTimeout, cancelTimeout] = useTimeout(callback);
// The delay and args are configurable each time the timeout is initialized
startTimeout(1000, "Hello after one second!");
// Setting a new timeout before the previous has fired will clean it up and not execute twice
startTimeout(2000, "Actually lets do two seconds");
// A cancel function is provided to manually cancel the timeout before the hook unmounts
cancelTimeout();
```
In writing tests for https://github.com/stackrox/stackrox/pull/7332 I ran into flakes …
> fix(ui): Add useTimeout hook and apply to CIDR modal

- pkg/search/postgres/index_test.go
- pkg/search/postgres/query/time_query.go
- pkg/search/postgres/query/time_query_test.go
- pkg/search/query_builder.go
This adds support for being able to run queries such that you can select a specific interval of time
Unit tests
> feat(search): Add capability to run time range query

- ui/apps/platform/cypress/integration/vulnmanagement/VulnerabilityManagement.selectors.js
- ui/apps/platform/src/Containers/VulnMgmt/List/Cves/VulnMgmtListCves.js
- ui/apps/platform/src/Containers/VulnMgmt/List/Images/VulnMgmtListImages.js
1. VulnMgmtListCves
* **Add to policy** is relevant only for image CVEs and requires READ_WRITE_ACCESS for WorkflowAdministration
By the way, the interaction in the modal seems awkward and buggy.
* **Defer and approve** requires READ_WRITE_ACCESS for Image, VulnerabilityManagementApprovals, VulnerabilityManagementRequests
* **Reobserve** requires READ_WRITE_ACCESS for Image, VulnerabilityManagementApprovals, VulnerabilityManagementRequests (I assume by analogy, although I did not have enough skill to set up the scenario)
* **View deferred** or **View observed** did not seem to require either Approvals or Requests resources, but Snoozed does have similar problem as Fixed boolean search.
2. VulnMgmtListImages
* **Manage watches** requires READ_WRITE_ACCESS for WatchedImage
1. …
> ROX-18887: Add conditional RBAC in Vulnerability Management 1.0

- qa-tests-backend/src/main/groovy/common/Constants.groovy
- qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
Per title. PR #7289  was a bit premature. Other tests create registry secrets (when they create a per test namespace that duplicates secrets from the `qa` namespace for example). These in turn can create autogenerated registry integrations which can effect ImageScanningTest.
> ROX-18810: Remove ImageScanningTest from the parallel test set

- ui/apps/platform/cypress/integration/networkGraph/networkGraph.helpers.js
- ui/apps/platform/cypress/integration/networkGraph/networkGraph.selectors.js
- ui/apps/platform/cypress/integration/networkGraph/networkGraph.test.js
- ui/apps/platform/src/Containers/NetworkGraph/components/CIDRFormRow.tsx
Adds some basic tests for the Network Graph.
- Tests that changing the Cluster/NS/Deployment scope dropdowns cause the correct stackrox deployments to be visible
- Tests that applying a general filter causes the correct deployments to be visible
- Tests the ability to add and delete CIDR blocks via the modal
This does match up with some of the assertions in the test plan, so I'll make a note in that document that the items are completed when this is merged.
CI
> test(ui): Add e2e test for network graph scope, filtering, cidr blocks

- ui/apps/platform/cypress/integration/listeningEndpoints/listeningEndpointsTable.test.js
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx
- ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsTable.tsx
- ui/apps/platform/src/hooks/useSet.ts
Adds a handful of UX enhancements to the Listening Endpoints table:
1. A new column showing the count of listening endpoints, to aid in understanding why some rows are not expandable
2. Adds a global "expand all" icon to the table header to expand/collapse all rows
3. Deployment names now link to the equivalent Risk page
4. Columns were re-ordered to more closely match the Risk page
5. The "Process name" column in the embedded table was changed to "Exec file path"
6. All rows are now expandable. Rows with no resulting endpoints contain this information in the expanded section.
Load the listening endpoints page and see a column for count:
Use the global expand/collapse icon to manage row expansion state: …
> feat(ui): Display listening endpoint count in table

- deploy/common/k8sbased.sh
Per the failure in https://issues.redhat.com/browse/ROX-19022, deploy.sh may not wait long enough for central rollout readiness. This PR bump the wait a little.
/test aks-qa-e2e-tests
> fix(test): wait longer for central readiness

- scripts/ci/jobs/gke_version_compatibility_tests.py
Switch to e2-standard-8 x 2 for this test (was e2-standard-4 x 3) to avoid unscheduled collectors that have appeared since GKE switched v1.26->1.27.  
- https://search.ci.openshift.org/chart?search=Timed+out+after+10m&maxAge=336h&context=1&type=build-log&name=stackrox.*compat.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
- https://issues.redhat.com/browse/ROX-19023
/test gke-version-compatibility-tests
> fix(test): provide more oomph for compat-test

- ui/apps/platform/src/Containers/Dashboard/DashboardPage.tsx
DashboardPage.tsx renders:
1. `SummaryCounts` element requires READ_ACCESS for all of the following:
* Alert for count of violations
* Cluster for count of clusters
* Deployment for count of deployments
* Image for count on images
* Node for count of nodes
* Secret for count of secrets
2. `ScopeBar` element requires READ_ACCESS for Cluster and Namespace because of `getAllNamespacesByCluster` query
1. Conditionally render `SummaryCounts` element.
2. Conditionally render `ScopeBar` element (pending **Residue** item 2).
1. Even after the above solution, I still see POST /api/graphql?opname=summary_counts for `clusterCount` on MainPage:
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/MainPage/MainPage.tsx#L56-L62
Mixing up failures for requests from …
> ROX-18991: Add conditional RBAC in main dashboard

- .github/workflows/build.yaml
With the current order the `-rcd` gets dropped for the manifest push. The order is correct for the images: https://github.com/stackrox/stackrox/actions/runs/5829094812/job/15808281267#step:26:71
Re: https://issues.redhat.com/browse/ROX-15366?focusedId=22787353&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22787353
```
(export GITHUB_ENV=`mktemp`; \
echo "$GITHUB_ENV"; \
export GITHUB_REF=refs/tags/4.1.x-nightly-20230811; \
source scripts/ci/lib.sh; \
handle_gha_tagged_build; \
set -o allexport; \
source "$GITHUB_ENV"; \
echo "BUILD_TAG=$(make --quiet --no-print-directory tag)-rcd" >> "$GITHUB_ENV"; \
source "$GITHUB_ENV"; \
make tag)
```
```
/tmp/nix-shell.SUcG6R/nix-shell.oj2Y0w/tmp.wXWcvhn2D7
GITHUB_REF: refs/tags/4.1.x-nightly-20230811
This is a tagged …
```
> fix(ci): handle the tag before the `-rcd`

- central/cluster/datastore/datastore_test_constructors.go
- central/detection/buildtime/singleton.go
- central/graphql/resolvers/search_test.go
- central/imageintegration/datastore/singleton.go
- central/policy/datastore/singleton.go
- central/postgres/report_pruning_test.go
- central/pruning/pruning_test.go
- central/rbac/k8srolebinding/datastore/datastore.go
- central/rbac/k8srolebinding/datastore/datastore_sac_test.go
- central/rbac/k8srolebinding/datastore/singleton.go
- central/rbac/utils/cluster_permission_evaluator_test.go
- central/rbac/utils/namespace_permission_evaluator_test.go
- central/reports/config/datastore/datastore.go
- central/reports/config/datastore/datastore_impl_postgres_test.go
- central/reports/config/datastore/datastore_impl_v2_test.go
- central/reports/config/datastore/singleton.go
- central/reports/snapshot/datastore/datastore_impl_test.go
- central/resourcecollection/service/service_impl_test.go
Be more lenient in some panic scenarios and removed a bit of dead code related to panic-able spots
CI, but we won't hit the failure spots
> chore(cleanup): Audit panic usage and be more lenient

- qa-tests-backend/src/test/groovy/NetworkBaselineTest.groovy
The `@timeout` annotation used was from `Spock` framework which couldn't overwrite the JUnit default test timeout of 800s. In order to allow a test to run longer than 800s we need to overwrite JUnit's global timeout variable:
```groovy
@Rule
@SuppressWarnings(["JUnitPublicProperty"])
org.junit.rules.Timeout globalTimeout = new org.junit.rules.Timeout(1600, TimeUnit.SECONDS)
```
> ROX-18892: Fix Network Baseline timeout in JUnit

- go.mod
- go.sum
- roxctl/connectivity-map/cta.go
- tests/roxctl/bats-tests/local/roxctl-connectivity-map-development.bats
- tests/roxctl/bats-tests/local/roxctl-connectivity-map-release.bats
Update  np-guard/netpol-analyzer to v0.4.3 
Includes a few compatibility updates:
- update to `roxctl/connectivity-map/cta.go`
- update to connectivity-map bats tests, since netpol-analyzer v0.4.3 does not necessarily traverses input YAML files by lexical order.
> ROX-17192: Update np-guard/netpol-analyzer to v0.4.3

- image/templates/helm/stackrox-secured-cluster/templates/collector.yaml
The current definition of the Collector _daemonset_ contains a volume to access to the Docker socket. This is not used anymore and could cause security concern.
Let's discard it.
> ROX-18838: discard unused Docker socket mount in Collector container

- image/templates/helm/stackrox-central/templates/01-central-03-diagnostics-rbac.yaml
Since ACSCS central diagnostics are re-enabled in https://issues.redhat.com/browse/ROX-12125, we need corresponding role to collect data via k8s API.
1. CI
> fix: Apply stackrox-central-diagnostics role in ACSCS

- sensor/common/metrics/init.go
- sensor/common/metrics/metrics.go
- sensor/kubernetes/clustermetrics/cluster_metrics.go
This is the follow up for Sensor. Basically we change the single info style metric into two gauge metrics.
New metrics:
* `rox_sensor_secured_nodes`
* `rox_sensor_secured_vcpu`
screenshots.
> feat(metrics): separate info metric into telemetry gauges for Sensor

- central/metrics/telemetry/gauges.go
- pkg/metrics/util.go
- sensor/common/metrics/metrics.go
Add `build` (release / development) and `branding` (stackrox / ACS) labels to `rox_central_info` / `rox_sensor_info`.
see screenshot
> feat(metrics): buildinfo labels

- ui/apps/platform/cypress/helpers/main.js
- ui/apps/platform/cypress/integration/clusters/redirectFromDashboard.test.js
- ui/apps/platform/src/Containers/MainPage/MainPage.tsx
1. For redirect to /main/clusters, CLUSTER_COUNT query requires READ_ACCESS to Cluster resource.
* The count is relevant only if READ_WRITE_ACCESS to Cluster resource.
* Because hook cannot be conditional, it is not possible to omit the request if the answer is not relevant.
1. Replace `useQuery` with `useEffect` and call `getClustersForPermissions` only if READ_WRITE_ACCESS for Cluster resource.
Slight increase probably from `isLoadingClustersCount` because replacement of query with request was probable about even exchange.
main.css: 44 = 3759732 - 3759688
total: 44 = 9949060 - 9949016
0 = 81 - 81 files
1. …
> ROX-19072: Minimize conditional RBAC in MainPage

- image/templates/helm/stackrox-central/templates/99-openshift-monitoring.yaml
- image/templates/helm/stackrox-secured-cluster/templates/openshift-monitoring.yaml
Deploy a recording rule for the Telemeter metric. This is just to remove some unnecessary labels to reduce the load for the Telemeter service.
screenshots.
> ROX-18276: Drop unneeded labels from telemeter metric

- deploy/common/deploy.sh
We have recently added core_bpf as a new collection method for collector as tech preview. It will soon become GA. This PR adds core_bpf as a collection method to deploy/common/deploy.sh. It was noticed that it had not been added previously when the gke-race-condition-qa-e2e-tests failed when run with the core_bpf collection method.
Ran race condition …
> ROX-18829: switch gke ebpf race condition qa e2e tests to core bpf

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/routePaths.ts
1. `DeploymentSelector` requires READ_ACCESS for Deployment resource.
2. Side panel requires READ_ACCESS for DeploymentExtension resource.
3. **Manage CIDR blocks** has asymmetrical requirements
* requires READ_ACCESS for Administration resource to open the modal
* requires READ_WRITE_ACCESS for NetworkGraph to click **Update configuration**
Usually I would require only READ_ACCESS to open and conditionally render **Update** button, but **Manage** verb sets an expection to touch with your hands, not just see with your eyes.
4. **Network policy generator**
* requires READ_ACCESS for Notifier resource, probably for **Share YAML with notifiers**
1. Add resources to `resourceAccessRequirements` in routePaths.ts file.
2. Add conditional rendering in `NetworkGraphPage` component.
1. Investigate …
> ROX-19089: Add conditional RBAC in Network Graph

- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/RiskAcceptancePage.tsx
1. RiskAcceptancePage has conditional rendering of 404 Not Found page that is now generic in Body.
2. Table components have conditional rendering for READ_WRITE_ACCESS to VulnerabilityManagementApprovals or VulnerabilityManagementRequests resources.
1. Delete obsolete conditional rendering.
1. Some of the conditional rendering conflates whether action items:
* are disabled because of current selection or user
* are unavailable because of user role
2. Seen here again, as discovered recently elsewhere:
* `Select` element does not support conditional rendering of `SelectOption` but is not first choice for imperative actions.
* `Dropdown` element better supports conditional push of items into `dropdownItems` array but `BulkActionsDropdown` does not because it emulates child composition.
1. …
> ROX-19088: Remove unneeded conditional RBAC in Risk Acceptance 1.0

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/hooks/useNetworkPolicySimulator.ts
- ui/apps/platform/src/Containers/NetworkGraph/simulation/DeploymentScopeModal.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesGenerationScope.tsx
- ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx
- ui/apps/platform/src/Containers/NetworkGraph/utils/simulatorUtils.ts
- ui/apps/platform/src/hooks/useFetchDeploymentCount.ts
_In my opinion this is easier to review in "split" view._
This removes the need for https://github.com/stackrox/stackrox/pull/7386 by querying for the exact deployments in the current scope, including any applied general filters.
This does so with the following changes:
- [Update](https://github.com/stackrox/stackrox/pull/7407/files#diff-c7830fe92be548741538cd230301a23caeae064b01e17134a727da9e69535da3) the `fetchDeploymentCount` hook used in the main page component so that it accepts a full `SearchFilter` instead of just a cluster id
- Reuse the `fetchDeploymentCount` hook result from the main page component to display the count of deployments in the simulator sidebar
- [Remove the previous calculation](https://github.com/stackrox/stackrox/pull/7407/files#diff-9bfc163f430b25882ec0afc38a02c …
> fix(ui): Fix display of scoped deployments for netpol sim

- central/debug/service/diagnostics.go
- pkg/k8sutil/client_config.go
Since ACSCS central diagnostics are re-enabled in [issues.redhat.com/browse/ROX-12125](https://issues.redhat.com/browse/ROX-12125), we need to allow ACS to connect to k8s API.
To allow that connection, we need to add an exception for the kubernetes API server in ACSCS data plane cluster. This change makes the k8s client use DNS record as a host instead of raw IP, which allows for easier configuration of the ACSCS data plane cluster, see https://github.com/stackrox/acs-fleet-manager/pull/1200
1. Manually tested by downloading diagnostic bundle
> fix: Use DNS in k8s client for ACSCS

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx
Small UX improvement for the collections menu in reporting 2.0. This makes the space in the wizard container expand slightly when the menu is opened.
In either case, this makes the body of the wizard component scrollable, but after this change it is more apparent that the menu has expanded by exposing content.
An alternative implementation that would be simple is to add `direction="up"` to the Select component, but the UX felt a bit out of place. Setting the behavior to flip automatically only works if we set a non-default parent for the dropdown list component. I tested this a bit but found it was fixing the issue at hand while introducing others.
Note that it appears that the interaction between these components is fixed in PF5, so this may not be needed after upgrade:
If any of these …
> ROX-18881: Add extra margin below dropdown in reporting form

- central/compliance/datastore/datastore_impl.go
- central/compliance/datastore/internal/store/postgres/store.go
- central/compliance/datastore/internal/store/postgres/store_test.go
- central/compliance/datastore/test/datastore_test.go
This PR is opssit approach to https://github.com/stackrox/stackrox/pull/7353 where we delete caching code.
This PR implements in memory cache for calculated aggregations.
The code for keeping aggregates was not implemented for postgres and not enabled for SAC (see: https://github.com/stackrox/stackrox/pull/301/files#r806715921). 
To support SAC the cache key is built from compacted scope tree and query params.
Clean cache just after scan:
| URL                                                       | code | type | source             | size  |  time  |
|-----------------------------------------------------------|------|------|--------------------|-------|:------:|
| graphql?opname=getAggregatedResultsAcrossEntity_NODE      | 200  | xhr  | main.97af8cf8.js:2 | 506 B | 665 ms |
| …
> ROX-9134: add cache for compliance aggregations

- central/main.go
- central/reports/common/testutils.go
- central/reports/common/utils.go
- central/reports/config/service/config_separation_test.go
- central/reports/config/service/service_impl.go
- central/reports/config/service/validate.go
- central/reports/manager/manager_impl.go
- central/reports/scheduler/v2/scheduler_impl.go
- central/reports/service/service_impl.go
- central/reports/service/service_impl_test.go
- central/reports/service/singleton.go
- central/reports/service/v2/config_separation_test.go
- central/reports/service/v2/download.go
- central/reports/service/v2/download_test.go
- central/reports/service/v2/service_impl.go
- central/reports/service/v2/service_impl_test.go
- central/reports/validation/validate.go
- v1 reporting APIs will not accept/return report configs that have the `resourceScope` field set.
- v2 reporting APIs will not accept/return report configs that have the `scopeId` field set.
- v1 scheduler will only run jobs for v1 report configs, v2 scheduler will only run jobs for v2 report configs.
Unit tests
instructions and make sure …
> [ROX-19037] : Allow reporting v1 and v2 to coexist

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CloneVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/EditVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/apiUtils.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useFetchReport.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useFetchReports.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useRunReport.ts
Enables "Run report" and "Generate download" menu items on View Report page, adds toasts when actions complete.
Open menu and select "Send report now" from the list:
Open menu and select "Generate download" from the list:
Simulated failure for either of the above cases:
Menu item disabled when no notifiers:
> ROX-18882: Enable actions on report view page

- .github/workflows/style.yaml
Trailing whitespaces are valid markdown, therefore we must exclude markdown files from the linter. See https://www.markdownguide.org/basic-syntax/#line-breaks.
screenshots.
> fix(linter): exclude .md in whitespace linter

- ui/apps/platform/cypress/integration/collections/permissions.test.js
- ui/apps/platform/src/routePaths.ts
1. POST /v1/collections/dryrun silently returns no deployments without READ_ACCESS for Deployment resource.
2. **Collection results** dryrun request has inconsistent resource requirements (see **Manual testing** item 2).
3. Bravo, components already have all conditional rendering for read versus write access. Extra credit for explicit props!
1. Add `'Deployment'` to `resourceAccessRequirements` in routePaths.ts file because anyone who has access to collections needs to view results.
2. I did not add conditional rendering related to dryrun request, because behavior seems like a backend bug: ROX-19116
Aha, `'Deployment',` has 13 characters :)
main.css: 13 = 3759794 - …
> ROX-19112: Add to resourceAccessRequirements for Collections

- CHANGELOG.md
- image/templates/helm/stackrox-secured-cluster/README.md.htpl
- image/templates/helm/stackrox-secured-cluster/values-public.yaml.example
- operator/apis/platform/v1alpha1/securedcluster_types.go
- operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml
- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml
- operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
- roxctl/sensor/generate/generate.go
- ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx
In preparation for CORE_BPF GA, this PR simply removes all Tech Preview labels throughout documentation.
N/A - this is a purely cosmetic change
> ROX-19079: Removes Tech Preview status from CORE_BPF collection method

- sensor/tests/helper/helper.go
- sensor/tests/resource/imagescan/imagescan_test.go
- sensor/tests/resource/networkpolicy/data/policies.json
- sensor/tests/resource/networkpolicy/networkpolicy_test.go
- sensor/tests/resource/networkpolicy/yaml/netpol-allow-443.yaml
- sensor/tests/resource/service/service_test.go
Show an error message that no alert results were found if fake central doesn't have alerts for requested deployment. Right now, this integration test will fail with the assertion message, which is misleading. 
- CI
> ROX-19047: Add more specific error messages to sensor integration test

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CloneVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/EditVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/apiUtils.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useFetchReport.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useFetchReportHistory.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useFetchReports.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useWatchLastSnapshotForReports.ts
Polls the last status report history for report configurations on the list page.
Polls the last status for the report config on the details page. (Used to toggle `isDisabled` state in the menu.)
Polls the list of report jobs on the details page.
- In order to poll only the statuses, I decoupled the request for the configuration from the requests for the job history. This led to some renaming/type changes again from `Report` -> `ReportConfiguration`.
- To avoid entire tables being replaced with a loading spinner when data was updating, or a page was changing, I added a `null` type to the data from the `useFetchReport` and `useFetchReports` hooks as well as retaining the previous state during a re-fetch. This required a bit of a logic change in the components. e.g) …
> ROX-18875: Poll for status updates in vuln reporting tables

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/exampleReportsCSVData.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportReviewForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.ts
1. If the user can visit the collections page, the collection name in the reports table will link to the appropriate page.
2. Incoming Dates are formatted correctly for the report form
3. Add CVSS column to report table preview
4. Sets the current page to `1` when a filter is applied or cleared
1. 
Load VM reporting and see that the collections link is visible and opens the collection modal:
If the user does not have the appropriate access, only the collection name will be displayed instead. (Currently this is only possible if the user has read access to "WorkflowAdministration" but no access to "Deployment".)
2. Edit a report config with a custom date set and ensure the date is correctly displayed in the YYYY-MM-DD format without time …
> ROX-19168,ROX-19167,ROX-19164: VM 2.0 Report fixes

- ui/apps/platform/src/Containers/AccessControl/AuthProviders/RuleGroups.tsx
We shouldn't show `This rule is managed declaratively and can only be edited declaratively.` information message when user resource is in view mode.
Before:
After:
> fix: Show declarative marker near group only when group is declarative

- ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesList.tsx
- ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesTable.tsx
- ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx
- ui/apps/platform/src/services/DelegatedRegistryConfigService.ts
This creates a table of exceptions for registries and the cluster designated to scan them.
This entailed embedding some of the form elements inside a PatternFly drag-and-drop variant Table. 
This proved tricky because the API structure for this list of registry objects does not contain anything that can be used as a stable ID for each array element, in this context.
- I started by combining the path and the clusterId of each row, but then when they were being edited, that changed, and every keypress caused the text input to lose focus
- Next, I violated our lint rule and just used a row index for each row's React key. That fixed the focus problem.
- Then, when I added the drag and drag functionality, based on the PatternFly docs code, I needed IDs in the markup (because the library does …
> ROX-17740: Create table of registry exceptions

- image/templates/helm/stackrox-secured-cluster/templates/openshift-monitoring.yaml
- image/templates/helm/stackrox-secured-cluster/templates/sensor-netpol.yaml
- sensor/upgrader/common/bundle_resources.go
- sensor/upgrader/common/bundle_resources_test.go
Openshift monitoring resources are missing the auto-upgrade label that other Sensor resources have. This seems to break the nightly upgrader tests, see https://issues.redhat.com/browse/ROX-18895.
screenshots.
> fix(sensor): add sensor auto-upgrade labels

- image/templates/helm/stackrox-central/internal/config-shape.yaml
- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- image/templates/helm/stackrox-central/templates/_init.tpl.htpl
- operator/tests/central/basic-central/80-assert.yaml
- operator/tests/central/basic-central/81-assert.yaml
- sensor/common/installmethod/install.go
- sensor/common/metrics/metrics.go
- sensor/kubernetes/sensor/sensor.go
Set the `install_method={rhacs-operator, manifest, helm}` label for the telemetry metrics. The install method is determined based on available fields in the Helm chart:
* `.Operator` -> Helm chart was rendered by the RHACS operator.
* `.KubectlOutput` -> Helm chart was rendered by manifest renderer.
* otherwise it's a plain Helm chart.
In Central, this information is based in via an env variable `ROX_INSTALL_METHOD`. Sensor already knows about it via its `managedBy` property, so we just need to expose it to the telemetry metric.
"No testable changes". Feel free to …
> feat(telemetry): set install method

- image/templates/helm/stackrox-secured-cluster/templates/openshift-monitoring.yaml
- operator/tests/securedcluster/basic-sc/40-assert.yaml
- operator/tests/securedcluster/basic-sc/41-errors.yaml
Looks like the pod monitor was copy/pasted from the old implementation. It does not feature authn/z, and we therefore don't want to expose it by default as part of OpenShift monitoring integration.
It is still accessible via `sensor.exposeMonitoring` if one wants to use the unauthenticated monitoring solution.
screenshots.
> fix(sensor): remove pod monitor

- ui/apps/platform/cypress/integration/violations/Violations.selectors.js
- ui/apps/platform/src/Containers/Violations/Details/Deployment/DeploymentDetails.tsx
- ui/apps/platform/src/Containers/Violations/Details/Deployment/NetworkPoliciesCard.tsx
- ui/apps/platform/src/Containers/Violations/Details/Deployment/SecurityContext.tsx
- ui/apps/platform/src/Containers/Violations/Details/ViolationDetailsPage.tsx
- ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx
1. ViolationsTablePanel
* **Resolve and add to process baseline** requires READ_WRITE_ACCESS for Alert resource.
* **Mark as resolved** requires READ_WRITE_ACCESS for Alert resource.
* **Exclude deployment from policy** requires READ_WRITE_ACCESS for WorkflowAdministration resource.
2. ViolationDetailsPage
* **Violation** and **Enforcement** tabs render information from `alert` object.
* **Deployment** tab requires READ_ACCESS for Deployment resource.
* **Policy** tab requires READ_ACCESS for Policy Management route.
* Because `PolicyDetailContent` element makes additional requests like GET /v1/notifiers which requires READ_ACCESS for Integration resource.
* Even if this context does not require all the resources of the route, breaking encapsulation for Violations to make assumptions …
> ROX-19034: Add conditional RBAC in Violations

- ui/apps/platform/src/Containers/Policies/Detail/ExcludedDeployment.tsx
- ui/apps/platform/src/Containers/Policies/Detail/PolicyDetailContent.tsx
- ui/apps/platform/src/Containers/Policies/Detail/PolicyScopeSection.tsx
- ui/apps/platform/src/Containers/Policies/Detail/Restriction.tsx
- ui/apps/platform/src/Containers/Policies/PoliciesPage.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step4/PolicyScopeCard.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step4/PolicyScopeForm.tsx
- ui/apps/platform/src/Containers/Policies/policies.utils.ts
- ui/apps/platform/src/Containers/SystemHealth/DashboardPage.js
- ui/apps/platform/src/Containers/SystemHealth/DiagnosticBundle/DiagnosticBundleForm.tsx
- ui/apps/platform/src/routePaths.ts
1. View policy
* `PolicyDetailContent` calls `fetchClustersAsArray` for `clusters` prop of `PolicyScopeSection` element, which is conditionally rendered.
* `PolicyScopeSection` provides `clusters` prop to `Restriction` and `ExcludedDeployment` elements.
* `Restriction` conditionally renders cluster name for id.
* `ExcludedDeployment` conditionally renders cluster name for id.
2. Clone, create, or edit policy
* `PolicyScopeForm` calls `fetchClustersAsArray` for `clusters` prop of `PolicyScopeCard` elements, which are conditionally rendered in `map` methods.
* `PolicyScopeCard` renders cluster id and name in options of `Select` element.
1. `DiagnosticBundleForm` calls `fetchClustersAsArray` and renders cluster name in options of `Select` element.
* It is not possible to replace /v1/clusters …
> ROX-19145: Improve RBAC requirements in Policies and System Health

- central/probesources/sources.go
- pkg/kocache/entry.go
- pkg/kocache/kocache.go
- pkg/kocache/kocache_test.go
- pkg/kocache/offlinectrl.go
- pkg/kocache/offlinectrl_test.go
- pkg/kocache/source.go
- pkg/probeupload/server_handler.go
- pkg/probeupload/server_handler_test.go
- sensor/common/sensor/notifiable.go
- sensor/common/sensor/sensor.go
The KoCache object is an active cache. On cache miss, it contacts Central and attempts to download kernel object (ko).
In this PR we make it offline-aware. It means that it still does what it was designed to, but produces more informative error logs when Sensor runs in offline mode (see example below).
Additionally, I refactored the affected code:
- Extract reusable errors into vars and slightly rephrase some error messages
- Remove collisions between var names and pkg names (`entry`)
- Restructured `Options` object, so that defaults are always used by default
- Made internal things unexported
```
// Central goes offline
sensor-8645b495f7-75kxj common/sensor: 2023/08/10 11:31:07.775734 central_communication_impl.go:181: Info: Communication with central ended.
(...)
sensor-8645b495f7-75kxj …
```
> ROX-19018: Make koCache handle Offline mode

- pkg/k8sutil/client_config.go
Use FQDN to prevent unnecessary DNS lookups. See https://github.com/stackrox/acs-fleet-manager/pull/1208 for the corresponding `NO_PROXY` env var definition.
Tested on OpenShift cluster.
> fix(k8sutils): use FQDN for managed Central

- pkg/metrics/tls.go
Use `k8sutils` to construct the client config to make sure we bypass the proxy on cloud-service Centrals.
Tested on OpenShift cluster.
> fix(metrics): use DNS k8sutil client

- ui/apps/platform/src/Components/TechPreviewBanner.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/JobDetails.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobStatus.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReportingPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.test.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx
This PR includes the following fixes:
1. Adds a "Tech preview" label for the Vulnerability Reporting 2.0 feature
2. When expanding a report job, the details should show that the download was deleted if it was (not saying it's prepared)
3. The table row actions should be disabled if you weren't the user who generated the download
4. If a download is ready, you should be able to download by clicking on the "Ready for download"
5. If you aren't allowed to download (not the user who generated the download) you shouldn't be able to click on the "Ready for download"
6. If a download was deleted, we should say "Download deleted"
> ROX-19163: VM Reporting 2.0 fixes

- release/scripts/scan-images-with-roxctl.sh
> fix(ci): allow roxctl image check to be disabled (3.74)

- pkg/env/notifications.go
- pkg/notifications/singleton.go
- pkg/notifications/stream.go
Create an interface to write and consume notifications. The corresponding service and datastore will be created in follow up PRs.
The first use case of the notification stream is adding notifications from log packages in chosen modules.
-
> feat(notifications): notification interface

- scripts/ci/gke.sh
Since the GKE update to k8s 1.27 CI has started to flake due to cluster API unavailability. Google support has not provided a workaround: "Cluster operations such as resizing cannot be excluded from the maintenance exclusions".
All GKE flavors. 16x runs without cluster issues.
> ROX-19109: Use v1.26 to get a more stable GKE clusters

- ui/apps/platform/src/Components/PatternFly/CheckboxSelect.tsx
- ui/apps/platform/src/Components/PatternFly/DayPickerDropdown.tsx
- ui/apps/platform/src/Components/PatternFly/RepeatScheduleDropdown.tsx
- ui/apps/platform/src/Components/SelectSingle/SelectSingle.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CloneVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/EditVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ViewVulnReportPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useWatchLastSnapshotForReports.ts
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/DeliveryDestinationsForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx
This PR fixes the following issues:
* Adding a `menuAppendTo` prop to the `Select` components where we append to the body will resolve the cut off issue with the select options
* When editing or cloning a report, the second step should not include the `(Optional)` text
* The download report name should not append a `-report` to the name
* When the last report status is pending, we should disable the edit and delete options in the `Actions` dropdown
* The `schedule` should be optional regardless of whether we set delivery destinations
> fix(ui): VM Reporting 2.0 last few fixes

- ui/apps/platform/src/Containers/SystemConfig/Details/PrivateConfigDataRetentionDetails.tsx
- ui/apps/platform/src/Containers/SystemConfig/Form/SystemConfigForm.tsx
- ui/apps/platform/src/types/config.proto.ts
Add `downloadableReportRetentionDays` to system config
Additionally, for `downloadableReportRetentionDays` and `historyRetentionDurationDays` a 0 value would mean delete whenever the next garbage collection runs. Since reports can consume lot of storage, we do not want to provide option to never delete.  
> ROX-17867: Prepared downloadable vuln report days

- sensor/common/metrics/metrics.go
The hosting information for Sensor needs to be set up runtime based on information passed by Central. Therefore when first running the metrics registration this information may not yet be available. For this reason, set the hosting label later during runtime when other dynamic labels are set.
Tested on OpenShift cluster.
> fix(sensor): set hosting at later point

- CHANGELOG.md
- central/main.go
This PR changes the permission required to view the API docs, i.e. the `api/docs/swagger` path.
Previously this required `READ Integration`, before the resource migration and simplification this was `READ APIToken`. This dates back to a long time, when the feature was first introduced.
Now, this can pose as a challenge for users interested in APIs (e.g. the report config or CVE / Image related ones) where they do not necessarily have `READ Integration`).
Thus, this PR lowers the access barrier for the API docs, and only requires users to be authenticated.
- N/A, `user.Authenticated()` has been covered previously.
> fix(auth): make api docs require authn only

- pkg/csv/writer.go
Fix UTF-8 BOM write in CSV writer.
When UTF-8 BOM is added to a CSV header, the header may be wrapped in double quotes, with the BOM. The BOM should be put directly to the stream instead.
Bug demonstration: https://play.golang.com/p/8Q34s_jlsD-
Tested in #7403.
> fix: write UTF-8 BOM to the stream before CSV headers

- README.md
- generated/api/v1/cluster_service.swagger.json
- generated/storage/cluster.pb.go
- operator/apis/platform/v1alpha1/securedcluster_types.go
- operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml
- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml
- operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
- operator/pkg/securedcluster/values/translation/translation.go
- operator/pkg/securedcluster/values/translation/translation_test.go
- proto/storage/cluster.proto
Adds the registry override parameter to the SecuredCluster CR, pipes it through to the Helm chart.
- [Not yet - creating PR] Investigated and inspected CI test results
- [Not yet - unsure if required] Evaluated and added CHANGELOG entry if required
- [Not yet - unsure if required] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))
Unit tests.
Tested: Ran a kind cluster, installed CentralCluster and SecuredCluster CRs, ran the Operator locally, confirmed that the value is piped through when set in the SecuredCluster CR (visible in Central UI means value is set in the backend -> …
> ROX-18660: Added SecuredCluster CR param registryOverride

- central/certgen/service.go
- central/main.go
- pkg/grpc/routes/routes.go
Restrict certgen API for managed centrals. A small refactoring has been made in order to reuse the existing helper methods.
Testing performed manually on a local cluster with helm installation method.
1. Generate chart
```
docker run -it --rm -v "$(pwd):/usr/src/stackrox" quay.io/stackrox-io/roxctl:4.1.x-842-g944704de24 helm output central-services --image-defaults opensource --output-dir /usr/src/stackrox/stackrox-central-services-chart --remove
```
2. Install central
```
helm upgrade -i --namespace=stackrox stackrox-central-services ./stackrox-central-services-chart --values ./tmp/helm/values/values-central-dev.yaml --set env.managedServices=true --create-namespace
```
3. Open UI
4. Ensure that certificate download fails
> ROX-15146: Disable certgen API for managed Central

- .github/workflows/build-scanner.yml
- scanner/Makefile
- scanner/image/db/.gitignore
- scanner/image/db/Dockerfile
Build multi-arch Scanner images. This does not push these images to any registry. Building arm64, amd64, and powerpc. Skipping Z at this time
CI. Take a look at the logs for the modified steps
> ci(scanner): build multi-arch Scanner images

- central/reprocessor/reprocessor.go
- central/tlsconfig/tlsconfig.go
- pkg/k8scfgwatch/cfg_watcher.go
- pkg/logging/fields.go
- pkg/metrics/server.go
- pkg/metrics/tls.go
- sensor/upgrader/runner/runner.go
This PR adds structured logs to the reprocessor. The reprocessor will be the first package that will be moved to structured logs to later enable it to send the log entry to the notification service.
The reason for choosing the reprocessor is that it currently does expose probably the most interesting async info for customers: whether there's trouble scanning images or not.
The existing `Errorw/Warnw` were used. We may think about adding `Infow` as well, I personally do not mind adding it in this PR.
As a caveat:
Introduced multiple wrappers for common fields we want to have in structured logs: `image, image_id, cluster_id, node_id`.
Additionally, also refactored existing usages of `zap.Error` to use `logging.Err` instead. Reason for this is that the wrapper (both the one for `zap.Error` …
> ROX-18482: Add structured logs to reprocessor

- scripts/ci/collect-service-logs.sh
Adds init container logs to the CI log dumps.
Intent is to aid in troubleshooting init-container issues (i.e. this one ROX-19213)
Installed ACS v4.1.2 on an OCP 4.13 infra cluster, and did the following:
```sh
$ ./scripts/ci/collect-service-logs.sh stackrox ./dignore-before
$ ./scripts/ci/collect-service-logs.sh stackrox ./dignore-after
$ path=dignore-before
$ find $path -type f | sed "s/$path//g" > files-$path
$ path=dignore-after
$ find $path -type f | sed "s/$path//g" > files-$path
$ diff files-dignore-before files-dignore-after
109a110
> /stackrox/pods/central-db-5cfd969ff-xxmjb-init-db.log
135a137
> /stackrox/pods/scanner-db-6c7494ff46-ldf7f-init-db.log
$ cat files-dignore-before | wc -l
203
$ cat files-dignore-after | wc -l
205
``` …
> chore(ci): Add collection of init container logs in CI

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/DeliveryDestinationsForm.tsx
As titled.
Also adds a `key` prop for notifiers in the form.
Send report:
Generate download:
> feat(ui): Add toasts when running a report from the list page

- tools/roxvet/analyzers/needlessformat/analyzer.go
- tools/roxvet/analyzers/structuredlogs/analyzer.go
- tools/roxvet/roxvet.go
This PR adds an analyzer for roxvet which verifies structured log usage. Currently it simply flags calls of `Warnf/Errorf` to use `Warnw/Errorw` instead.
In the future, we might sophisticate this further, as well as extend the scope of linted packages (for the time being, only the `reprocessor` package is being linted).
Split out of this PR is #7462 which fixes the `Logger` expression for the `needlessformat` anaylzer and all occurrences.
- see CI succeeding.
- run the linter locally via `go vet -vettools ./.gotools/bin/roxvet github.com/stackrox/rox/central/reprocessor`. Introduced changes locally to ensure that the check flags them correctly.
> feat(roxvet): add analyzer for structured logs

- pkg/search/paginated/paginated.go
https://issues.redhat.com/browse/ROX-19082 and https://issues.redhat.com/browse/ROX-18863 are examples of this. Basically we mark the sort option field as to lower but the default sort option is only declared once
Race condition change
> fix(race): Fix race conditions by cloning the sort option

- image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl
- image/templates/helm/stackrox-secured-cluster/values-public.yaml.example
[K8s docs say](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity):
> If omitted or empty, `namespaces` defaults to the namespace of the Pod where the affinity/anti-affinity definition appears.
This is simpler and more robust than hardcoding `stackrox` - which caused the anti-affinity rule to be ignored when admission controller is installed into a custom-named namespace.
CI should be sufficient, but in addition I manually installed ACS in the non-default namespace and validated that the admission controller pods are dispersed despite lack of the `namespaces` field:
```
[mowsiany@mowsiany stackrox]$ kubectl -n $NAMESPACE get pods -o wide -l app=admission-control
NAME                                 READY   STATUS    RESTARTS …
```
> ROX-19220: Remove `namespaces` from anti-affinity.

- deploy/common/k8sbased.sh
- deploy/common/sensor-toxiproxy-patch.json
- go.mod
- go.sum
- sensor/common/chaos/config.go
- sensor/common/chaos/env.go
- sensor/common/chaos/profile/droppedpackets.go
- sensor/common/chaos/profile/none.go
- sensor/common/chaos/profile/periodicdisconnect.go
- sensor/common/chaos/profile/profile.go
- sensor/common/sensor/sensor.go
This PR introduces a chaos testing setup to Sensor. It uses [toxiproxy](github.com/shopify/toxiproxy) as a proxy in between Sensor and Central to introduce bad network conditions.
This is not yet integrated in any automated tests, but you should be able to deploy sensor with toxiproxy by running:
```bash
CHAOS_PROXY="true" ./deploy/k8s/deploy.sh
```
It will patch sensor adding a new container in the same pod that runs `toxiproxy` application. It will also set an environment variable in Sensor `ROX_CHAOS_PROXY_ENABLED` so sensor will do the proxy configurations and add the network conditions. 
So far, I've added two example chaos profiles:
- Periodic disconnects (default): stops the connection for 10 seconds every 5 minutes 
- Random disconnects: 1% of the connection writes should result …
> ROX-18821: Sensor chaos proxy setup

- pkg/auth/authproviders/openshift/backend_impl.go
- pkg/auth/authproviders/openshift/watcher.go
This PR introduces the capability to watch the certificates injected within the openshift connector for the openshift auth provider.
We had reportst that after some certificates have been rotated, the central pod would have to be restarted. Additionally, the injected CA bundle, which _can_ be updated during runtime, also does not get propagated to existing instances of OpenShift auth without a restart.
Hence, added the capability to reload the certpool injected into the openshift connector.
Caveats:
- Decided _not_ to adjust the openshift connector interface to introduce a separate method allowing to reload the cert pool but instead opted into re-creating the openshift connector instead.
- Currently for each connector a two k8scfgwatch handlers will be started. They will then propagate to …
> ROX-16856: watch certs for openshift auth provider

- ui/apps/platform/src/Containers/Search/FilterLinks.tsx
- ui/apps/platform/src/Containers/Search/SearchNavAndTable.tsx
- ui/apps/platform/src/Containers/Search/SearchTable.tsx
- ui/apps/platform/src/Containers/Search/ViewLinks.tsx
- ui/apps/platform/src/Containers/Search/searchCategories.ts
- ui/apps/platform/src/hooks/useIsRouteEnabled.ts
- ui/apps/platform/src/routePaths.ts
1. Add conditional rendering of links according to `routeKey` property added in #7524
* Delete filtering for individual resources from `SearchNavAndTable` because it assumes all are specified as `resourceAccessRequirements` in routePaths.
* Delete `resourceName` property from `searchResultCategoryMap` and write comment.
* Replace direct import of `searchResultCategoryMap` in `SearchTable` with filtered copy from `searchResultCategoryMapFilteredIsRouteEnabled` function call.
* Replace direct import of `searchResultCategoryMap` in `FilterLinks` and `ViewLinks` with prop for filtered copy from `SearchTable` component.
1. Add optional `featureFlagDependency` property for situations in the future like policy categories in the past.
2. Add id to page address for policy categories. It is only in …
> ROX-19201: Add conditional RBAC for global search links

- ui/apps/platform/src/Components/PatternFly/ResourceIcon/ResourceIcon.css
- ui/apps/platform/src/Components/PatternFly/ResourceIcon/ResourceIcon.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/NetworkGraphIcons.tsx
- ui/apps/platform/src/css/acs.css
Thanks to Zhenpeng for selecting colors which have sufficient contrast.
1. Refactor the two separate implementations into one.
**Residue** item 1 aims for decrease in js bundles.
* `wc build/static/css/*.css`
main.css: -447 = 797293 - 797740
total: -2363 = 1637043 - 1639406
* `ls -al build/static/css/*.css | wc -l`
0 = 30 - 30 files
main.css: 0 = 3761815 - 3761815
total: 504 = 9969952 - 9969448
0 = 80 - 80 files
1. Visit /main/network-graph
* See insufficient color contrast for CL resource icon before changes.
* See sufficient color contrast for CL resource icon after changes.
* See **CL** resource icon with …
> fix(ui): Replace resource icon colors which had insufficient contrast

- central/main.go
- central/productusage/datastore/securedunits/datastore_impl.go
- central/productusage/injector/injector.go
- central/productusage/injector/injector_impl.go
- central/productusage/injector/injector_test.go
- central/productusage/store/cache/cache.go
Synchronize update of cache fields, to avoid case when nodes and cpu numbers don't agree.
Unit tests of the service, injector and datastore.
> ROX-17702: sync cache records

- qa-tests-backend/scripts/lib.sh
- scripts/ci/gke.sh
- scripts/ci/store-artifacts.sh
I wanted to make it for a long time.
Won't do these:
- ~~[ ] `GKE Logs Explorer` links are left-clickable~~ - no, they aren't and I could not make them work.
Not creating tests for this change because it's change in tests tooling.
> chore: Set `target="_blank"` on links rendered in OSCI

- roxctl/image/scan/scan.go
- roxctl/image/scan/testdata/color_testComponents.txt
- roxctl/image/scan/testdata/testComponents.txt
The table output summary line previously was missing the number of moderate CVEs.
This is due to us using the wrong key, sadly this has existed for quite some time.
The PR fixes this by using the constants to get the correct string.
- see the adjusted unit tests in CI.
> ROX-15277: Fix table output

- qa-tests-backend/src/main/groovy/objects/ImageIntegration.groovy
- qa-tests-backend/src/main/groovy/services/ImageIntegrationService.groovy
- qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
- qa-tests-backend/src/test/groovy/VulnMgmtSACTest.groovy
- qa-tests-backend/src/test/groovy/VulnMgmtTest.groovy
While implementing https://github.com/stackrox/stackrox/pull/7497 I ran into numerous race failures around the presence and absence of Stackrox Scanner. This PR removes cases where Stackrox Scanner is deleted by some tests and added by others to rely instead on Stackrox Scanner being a default integration.
> fix(ci): normalize stackrox scanner config

- ui/apps/platform/src/Containers/ComplianceEnhanced/Dashboard/ComplianceDashboardPage.tsx
- ui/apps/platform/src/Containers/ComplianceEnhanced/Dashboard/Widgets/ComplianceByProfile.tsx
- ui/apps/platform/src/Containers/ComplianceEnhanced/Dashboard/Widgets/HorizontalBarChart.tsx
- ui/apps/platform/src/Containers/ComplianceEnhanced/Dashboard/types.ts
Create the compliance by profile widget. Should display the percent of compliance by profile. Create a reusable component for both compliance by profile and compliance by cluster to use.
Note: currently uses static data
> ROX-18114: Compliance by profile widget

- qa-tests-backend/src/main/groovy/services/PolicyService.groovy
- qa-tests-backend/src/test/groovy/BaseSpecification.groovy
- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
- qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy
This PR adds `ImageManagementTest.groovy` to the set of tests that run concurrently. This is achieved with a standard pattern: clone and scope policies to a test namespace and create deployments in that same namespace.
50x runs:
- testParallel - [out43.txt](https://github.com/stackrox/stackrox/files/12412001/out43.txt)
- testParallelBAT - [out42.txt](https://github.com/stackrox/stackrox/files/12411998/out42.txt)
> ROX-19183: Add ImageManagementTest to the parallel set

- roxctl/sensor/generate/generate.go
- roxctl/sensor/getbundle/get_bundle.go
`roxctl sensor generate`/`roxctl sensor get-bundle` involve downloading K8s manifests from Central, which has been observed to time out in tests with a `DeadlineExceeded`. See https://issues.redhat.com/browse/ROX-19204 for an example. To reduce the probability of exceeding the deadline, increase the timeout for this command from the global 1m default to 5m.
> fix(roxctl): increase sensor timeouts

- roxctl/common/connection.go
We have consistently observed that `roxctl` calls fail tests due to connectivity issues. The currently configured 3 retries with a maximum backoff of 0.4s might be inadequate. This will not solve all our problems because some of the failures are due to `DeadlineExceeded`, which is not retried at all by gRPC. However, I'm hoping it will reduce the number of `Unavailable` failures. Note that the total retry time is still bounded by the parent context timeout.
> fix(roxctl): increase retry attempts

- image/templates/helm/stackrox-secured-cluster/templates/collector.yaml
**Change**
Set the mount propagation setting to `HostToContainer` for volumes in the collector daemonset on the root directory mount. By default, the k8s/ocp setting is `none,` equivalent to `rprivate` in Linux. Using this mount propagation fixes a customer/OCP issue and is also more correct for ACS, if a host mount is added after the pod is created, with the existing mount propagation, the volume mount will not have access to the new mount.
**Fixes**
Changing the mount propagation allows the pod to receive `unmount` events, which will fix [ROX-9350](https://issues.redhat.com/browse/ROX-9350) and is based on guidance in this ticket, [OCPBUGS-14351](https://issues.redhat.com/browse/OCPBUGS-14351)
Openshift 3.15 will enable this by default for any HostPath volume. For now, other OCP …
> ROX-9350: Enable HostToContainer mount propagation

- .openshift-ci/post_tests.py
- deploy/common/k8sbased.sh
Per title. The recent change to store some artifacts in OSCI storage (versus GCS) did not follow the same semantics as the other post scripts i.e. `run_with_best_effort()`. This change only copies when the source dir exists and changes the overall handling to follow that best effort approach.
This PR stems from failures like [this](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-merge-gke-qa-e2e-tests/1695115680392679424) where the post process gets short circuited by this bug and the full suite of debug logs are not gathered.
> fix(ci): allow missing dir in artifact store

- deploy/common/k8sbased.sh
- qa-tests-backend/scripts/run-compatibility.sh
- scripts/ci/jobs/gke_version_compatibility_tests.py
- scripts/style/shellcheck_skip.txt
- tests/e2e/lib.sh
Add version compatibility tests for a central deployment one version behind the latest release vs latest sensor. Methods vary as follows based on what version is changed:
* Latest Central: Default deployment
* Older Central: Overriding chart directory to stackrox-oss and setting the `--version` flag.
* Latest Sensor: Using `roxctl helm output secured-cluster-services` to create the latest helm chart and overriding the chart directory to the directory of that chart. This is necessary because by default the sensor helm chart is provisioned from the central deployment, but given an older central that helm chart won't be the latest.
* Older Sensor: Overriding chart directory to stackrox-oss and setting the `--version` flag.
The compatibility …
> ROX-16548: test latest sensor vs older central

- ui/apps/platform/src/Containers/Clusters/DelegateScanning/Components/DelegatedRegistriesTable.tsx
- ui/apps/platform/src/Containers/Clusters/DelegateScanning/DelegateScanningPage.tsx
The first character you type in one of the Pathname fields, causes that input to lose focus. Clicking back into it allows you to type as many more characters as you like without losing focus. But if you leave that field (click out, tab out) and then focus it again, then the next character you type also causes it to lose focus.
While trying to add drag and drop to the table (which has been removed for now, due to buggy behavior of the PatternFly component, I had added UUIDs to the table rows. However, I forgot to perpetuate the UUID in the change handler for the path input.
Changes:
- now perpetuate the UUID in the change handler for the path input
- also perpetuate the UUID in the change handler for the row's selected cluster input (provides no obvious benefit in the UX) but keeps the …
> fix(ui): Fix bug in delegated regestries path editing

- operator/hack/common.sh
- operator/hack/operator.envsubst.yaml
Per my research in the related ticket, the only required thing is the presence of `spec.grpcPodConfig.securityContextConfig` attribute on the operator `CatalogSource` resource.
This should make manifests for deploying our upstream-built operator index deployable on OCP 4.14.
Not doing these:
I haven't tested further operands deployment on 4.14. Any issues there (if present) would be separate from this one which blocks the deployment of the operator.
Not creating automated tests because the changed code is part of automated tests itself. …
> ROX-19215: Fix operator index deployment on OCP 4.14

- ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/ClustersHealthCards.tsx
- ui/apps/platform/src/Containers/SystemHealth/DiagnosticBundle/DiagnosticBundleForm.tsx
- ui/apps/platform/src/services/ClustersService.ts
Follow up task: more consistent name for only 2 calls that remain after deletion of 2 in #7481
The original `fetchClusters` function that called normalizr for sagas was deleted in #6782
> ROX-19295: Rename fetchClustersAsArray function

- qa-tests-backend/src/test/groovy/DiagnosticBundleTest.groovy
In https://issues.redhat.com/browse/ROX-19182 we observed the generic test timeout (`800s`) being hit. Upon investigation, I realized that the http client in the test has no timeouts and does not retry on connection issues. Therefore this PR adds:
* connection and read timeouts to indicate the type of issue more clearly.
* a retry handler for retry-able errors.
> fix(qa-tests): add timeout and retry to diag bundle call

- central/metadata/service/service_impl_test.go
Since authn/z for `GetCentralCapabilities()` is handled by middleware and no specific permissions are required, remove mock identity from the test.
CI run
> test: Remove mock identity in TestGetCentralCapabilities

- ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx
- ui/apps/platform/src/Containers/AccessControl/AuthProviders/ConfigurationFormFields.tsx
Even though this checkbox does not change anything, it's still better to disable it so that UI would be consistent.
Manually tested 
> fix: Disable offline_access checkbox when auth provider is declarative

- qa-tests-backend/src/main/groovy/orchestratormanager/Kubernetes.groovy
In https://issues.redhat.com/browse/ROX-18892 I encountered a test flake due to connection failure.
```
Wrapped by: java.io.IOException: Failed to connect to /34.28.36.43:443
at orchestratormanager.Kubernetes.ensureNamespaceExists(Kubernetes.groovy:158) [6 skipped]
```
Based on @gavin-stackrox, the root cause is a GKE `CLUSTER_RESIZE`:
```
$ gcloud --project=stackrox-ci container operations list | grep 1696538173041020928
operation-1693321873247-a322b918-4d74-42b4-b71a-9a396906d157  CREATE_CLUSTER  us-central1-b  rox-ci-qa-e2e-test-1696538173041020928                    DONE     2023-08-29T15:11:13.247538598Z  2023-08-29T15:23:38.082118456Z
operation-1693322622916-bf195eb3-0150-4e20-8d31-6e7434ad02db  UPDATE_CLUSTER  us-central1-b  rox-ci-qa-e2e-test-1696538173041020928 …
```
> ROX-18892: increase k8s-client retries

- .github/workflows/build.yaml
- Makefile
- integration-tests/mock-grpc-server/image/Dockerfile
update mock-grpc-server to support multiple architectures.
Build and pushed to personal quay repo
> ROX-18436: update mock-grpc-server container to be multi-arch

- qa-tests-backend/src/test/groovy/Enforcement.groovy
docker.io is rate limited. We should switch to quay.io where possible.
- https://github.com/stackrox/stackrox/commit/01e52f7ed35acefa36f1d82ba6ad9eacb6250475#diff-9dcde8ab453f7c9b245fc4376c28fd3914a380a7cc995d93c0f29bc1003ed625R369-R370
CI
> ROX-19320: Use quay.io instead of docker

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/DeliveryDestinationsForm.tsx
This fixes an issue where the delivery destination dropdowns would freeze if multiple delivery destinations were added using the same notifier.
Test adding and deleting multiple delivery destinations, including duplicate notifiers throughout. All dropdowns should successfully open and close as expected, and the value of the notifiers should remain consistent when values are deleted.
Performing similar actions against staging causes the UI to break almost immediately.
https://github.com/stackrox/stackrox/assets/1292638/6aa1f0d0-ef31-4ec4-ba37-3e01fd37d608
> fix(ui): Fix dropdown not closing with duplicate notifier

- pkg/protoconv/resources/resources.go
- scripts/ci/logcheck/allowlist-patterns
- sensor/admission-control/manager/k8s_object.go
- sensor/kubernetes/listener/resources/convert.go
This PR adds an ignore-regexp to the log checker to tolerate deprecation warning in form of: `apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+`
We do not have any references to [/oapi/v1.DeploymentConfig](https://docs.openshift.com/container-platform/3.10/rest_api/oapi/v1.AppliedClusterResourceQuota.html) which is gone since OCP 3.10.
We do support [apps.openshift.io/v1/DeploymentConfig ](http://apps.openshift.io/v1) as long as they exist. They were originally planned to be removed in 4.17, but apparently this plan was dropped and the removal date is unknown. For more details see https://issues.redhat.com/browse/OCPSTRAT-118.
Testing this on Mac requires to change all occurrences of `grep` in `scripts/ci/logcheck/check.sh` to `ggrep`
```shell
$ cat …
```
> ROX-19453: Add logchecker exception for deprecated DeploymentConfigs

- .github/api_best_practices.md
This PR is the first in the series of PRs to document general ACS API best practices. This PR exclusively focuses on the naming conventions recommendations.
n/a
> chore(docs): ACS API guidelines - Part 1: Naming convention

- deploy/common/deploy.sh
`prevent.stackrox.com` was introduced long time ago as a test domain name that you would add via `/etc/hosts` to access Central in UI. There is strong evidence that it is ancient history as no one mentioned it since 2019, and all references to it are limited to `setup_auth0`, which itself is becoming obsolete.
> chore: Remove prevent.stackrox.com from deploy.sh

- .github/workflows/cut-rc.yml
Tested in https://github.com/stackrox/test-gh-actions/pull/125
> fix(GHA): cut-rc - github.event.inputs is empty for closed milestones

- image/templates/helm/stackrox-central/templates/99-openshift-monitoring.yaml
- image/templates/helm/stackrox-secured-cluster/templates/openshift-monitoring.yaml
Based on feedback in https://github.com/openshift/cluster-monitoring-operator/pull/2062, change the telemetry metrics in the following ways:
* `rhacs:telemetry:rox_sensor_secured_nodes` and `rhacs:telemetry:rox_sensor_secured_vcpu` -> `rhacs:telemetry:rox_sensor_info`. The reason for this change is that Telemeter already includes the node count and cpu count in their metrics. We keep the info metric for the remaining information.
* remove `branding` label from all recording rules and filter directly for `RHACS` branding.
~~I also realized that `ROX_PRODUCT_BRANDING` is not set consistently in the container environment. Therefore, switch to the image flavor name `ROX_IMAGE_FLAVOR`, which serves essentially the same purpose. We may switch back to `ROX_PRODUCT_BRANDING` at a later time once …
> ROX-18276: adapt telemetry metrics to Telemeter feedback

- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
Dockerhub frequently returns errors like
```
io.grpc.StatusRuntimeException: INTERNAL: image enrichment error: error getting metadata for image: docker.io/docker/kube-compose-controller:v0.4.23 errors: [getting metadata from registry: &#34;Public DockerHub&#34;: failed to get the manifest digest: Head &#34;https://registry-1.docker.io/v2/docker/kube-compose-controller/manifests/v0.4.23&#34;: http: non-successful response (status=401 body=&#34;&#34;), getting metadata from registry: &#34;Autogenerated https://registry-1.docker.io for cluster remote&#34;: failed to get the manifest digest: Head &#34;https://registry-1.docker.io/v2/docker/kube-compose-controller/manifests/v0.4.23&#34;: http: non-successful response (status=401 body=&#34;&#34;)
```
leading to test flakes.
Therefore, switch …
> ROX-18772: use quay registry

- qa-tests-backend/build.gradle
We are using a pretty old gRPC version in the qa tests. Bumping to the latest version, which includes a lot improved features, in particular with regards to retries.
CI
> chore: bump qa-test gRPC version

- pkg/images/enricher/enricher_impl.go
This is just a style change to use less indentation after inverting condition and exiting early.
CI
responsible for the change after it gets merged which includes reverting, fixing, etc. Make sure you validate the change
ASAP after it gets merged or explain in PR when the validation will be performed.  
Explain here why you skipped testing in case you did so.
Have you created automated tests for your change? Explain here …
> fix: invert if to exit early from func

- qa-tests-backend/src/test/groovy/SACTest.groovy
In ROX-19316 the nginx pod did not come up due to the following error:
```
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2023/08/25 15:36:24 [emerg] 1#0: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```
I believe the issue is caused by restrictive file permissions for containers on OpenShift. To prevent this issue, there is an unprivileged version of the nginx image `nginx-unprivileged`. This PR switches the qa SACTest to this unprivileged image.
I initially attempted to introduce `nginx-unprivileged` also for other tests, however not all tests - in particular the process baseline tests …
> ROX-19316: use nginx-unprivileged image

- operator/Makefile
- operator/hack/build-index-image.sh
- operator/tests/scripts/validate-crs.sh
- operator/tools/go.mod
- operator/tools/go.sum
- operator/tools/tools-import.go
* Replace a workaround mentioned in #5821 with proper filtering using `yq`.
* Also use the same `yq` version for another script for consistency and automatic version bumps.
> ROX-19283: Validate only stackrox CRs

- ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx
- ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx
- ui/apps/platform/src/services/ClustersService.ts
- ui/apps/platform/src/utils/searchUtils.ts
Increase type safety before making functional changes to the page.
main.css: -2 = 3761770 - 3761772
total: 1 = 9977225 - 9977224
0 = 80 - 80 files
1. Visit /main/clusters
2. Create an unavailable cluster.
3. Delete the unavailable cluster via toggle all, and then clear check mark in remote cluster.
* clusters/clusterDeletion.test.js
* clusters/clusters.test.js
* clusters/clustersCertificateExpiration.test.js
* clusters/clustersHealthStatus.test.js
* clusters/clustersManager.test.js
* clusters/delegatedScanning.test.js
* clusters/redirectFromDashboard.test.js
> ROX-19526: Rewrite ClustersTablePanel in TypeScript

- ui/apps/platform/src/Containers/Clusters/ClusterDeployment.tsx
- ui/apps/platform/src/Containers/Clusters/ClusterEditForm.tsx
- ui/apps/platform/src/Containers/Clusters/ClustersSidePanel.tsx
- ui/apps/platform/src/Containers/Clusters/clusterTypes.ts
Increase type safety before making functional changes to the page.
1. Replace import from container clusterTypes.ts with src/types/cluster.proto.ts file.
* 23 results in 16 files within Clusters container.
* Separate chore for cluster types and helpers for credential expiration in SystemHealth container.
2. Investigate how to represent request status for `kernelSupportAvailable` property.
main.css: 0 = 3761772 - 3761772
total: -18 = 9977206 - 9977224
0 = 80 - 80 files
1. Visit /main/clusters and create an unavailable cluster.
* clusters/clusterDeletion.test.js
* clusters/clusters.test.js
* …
> ROX-19527: Rewrite ClusterDeployment in TypeScript

- ui/apps/platform/cypress.config.js
- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#13-0-0
Although Test Replay for Cypress Cloud is not relevant for us, it does affect some configuration.
1. Automation performance is now improved by switching away from websockets to direct CDP calls for Chrome and Electron browsers.
2. Edge cases where `cy.intercept` would not properly intercept have been addressed.
3. Node 14 support has been removed and Node 16 support has been deprecated. Node 16 may continue to work with Cypress v13, but will not be supported moving forward to closer coincide with Node 16's end-of-life schedule. It is recommended that users update to at least Node 18.
* CI currently uses 18.16.0
* I am currently using 16.13.0 and tested locally that this upgrade version works.
4. The minimum supported Typescript …
> chore(e2e): Update cypress 13.0.0 devDependencies in ui

- ui/apps/platform/src/Components/PatternFly/RepeatScheduleDropdown.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/DeliveryDestinationsForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/NotifierSelection.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.ts
- ui/apps/platform/src/hooks/useURLPagination.ts
This PR fixes the following issues:
1.  ROX-19311: [[Reports table] Fix overflow issue with table row actions](https://issues.redhat.com/browse/ROX-19311)
2. ROX-18884: [[Report form] Choosing a new notifier overwrites the custom distribution list](https://issues.redhat.com/browse/ROX-18884)
https://github.com/stackrox/stackrox/assets/4805485/f312d01f-0f81-4582-983a-e1c2d5bcf599
3. ROX-19307: [[Report form] Change descriptor](https://issues.redhat.com/browse/ROX-19307)
4. ROX-19308: [[Reports table] Left align collections column](https://issues.redhat.com/browse/ROX-19308)
5. ROX-19309: [[Reports table] Fix help text](https://issues.redhat.com/browse/ROX-19309)
6. ROX-19317: [[Pagination] Issue with per page value](https://issues.redhat.com/browse/ROX-19317) …
> feat(ui): VM Reporting 2.0 GA Major Fixes

- ui/apps/platform/src/Components/SelectSingle/SelectSingle.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/NotifierSelection.tsx
This change includes removing the "Create" buttons for the Collection and Notifier in the VM 2.0 Reports Form and placing them inside the dropdown select as a footer action. See included screenshots
> ROX-19485: Change create button into a dropdown footer

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/watchedImagesFlow.test.js
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
As titled. Opens the watched images modal with a default empty image name value. Also adds some placeholder Cypress tests until the more interesting pieces of code are implemented.
Visit the Workload CVE overview page. The button will be present for all three entity tabs.
Clicking on the button opens the modal.
> ROX-19335: Add manage watched images button

- central/compliance/handlers/csv.go
- central/cve/cluster/csv/handler.go
- central/cve/csv/handler.go
- central/cve/image/csv/handler.go
- central/cve/node/csv/handler.go
- central/risk/handlers/timeline/csv.go
- pkg/csv/http_writer.go
- pkg/csv/http_writer_test.go
- pkg/csv/utils.go
- pkg/csv/utils_test.go
This PR teaches `csv.WriteError()` to deduce the status code from the error class und ensures appropriate HTTP headers are set.
Unit tests and CI run.
> refactor(csv): Rely on `http.Error` in 'pkg/csv'

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
Not yet sure how to fix that flake, as I am still trying to reproduce it... This description will be updated once a solution is found.
1. Was unable to increase the timeout of 800s to 1600s - the solution using `Timeout globalTimeout = new Timeout(1600, TimeUnit.SECONDS)` does not help.
[CI log](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/7600/pull-ci-stackrox-stackrox-master-ocp-4-13-qa-e2e-tests/1696188892962623488)
```
18:28:17 | DEBUG | NetworkFlowTest           | NetworkGraphUtil          | Checking for edge between deployments: sourceId 104a577f-c658-4212-bdfa-b8e2b75bbfbf, targetId 81bb672b-541f-4165-9836-a08be4289b8c
18:28:17 | DEBUG | NetworkFlowTest           | NetworkGraphUtil          | Looking at edges for 1 source node(s)
18:28:18 | …
```
> ROX-19233: Fix verify connections from external sources

- image/templates/helm/stackrox-secured-cluster/.helmtplignore.htpl
- image/templates/sensor/openshift/delete-sensor.sh
- image/templates/sensor/openshift/sensor.sh
Unfortunately I found a bug w/ OpenShift monitoring in the secured cluster manifest download. It applies only when secured clusters are installed via manifest download, and causes the monitoring resources to not be created and applied. As a result, Sensor does not show up in OpenShift monitoring.
Tested manifest download w/ and w/out this change.
> fix: monitoring in manifest download

- ui/apps/platform/src/Containers/VulnMgmt/Entity/Component/VulnMgmtComponentOverview.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/TableWidgetFixableCves.js
1) From VM dashboard, open Node CVEs and then click on a single Node CVE.
2) Click on the 'Open externally' button on the top right corner (left of close button) to open the CVE in its own view.
3) Click components from the related entities.
4) Click any component.
5) Click Nodes under component's related entities.
Result: graphQL error in the API network call response, but no visible effect on UI
The React component update cycle tries to re-render the ComponentOverview component one last time before navigating away from it, but with the new entityType of "NODE". Due to a missing path in the conditional that calculates the dynamic query for TableFixableCves, it tries to make a new query for node CVEs, but with an `imageVulnerabilityCounter`.
Add a check for entityType of "NODE" when …
> ROX-16345: Fix graphQL error navigating from node_compoenent to nodes

- pkg/csv/http_writer.go
- pkg/csv/http_writer_test.go
- pkg/csv/utils.go
- pkg/csv/writer.go
Also relax string eq checks in a test and removed one constant as a side bonus.
CI run
> refactor(csv): Use same constants in both CSV writers

- ui/apps/platform/src/Containers/Integrations/IntegrationTilesPage/IntegrationTile.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationTilesPage/IntegrationTilesPage.tsx
- ui/apps/platform/src/Containers/Integrations/IntegrationTilesPage/IntegrationsSection.tsx
- ui/apps/platform/src/services/IntegrationsService.ts
Increase type safety before making functional changes to the page (see **Residue**).
1. Replace `mapStateToProps` with `useSelector` hook.
2. Replace `PropTypes` with type for structured selector.
3. Simplify `countIntegrations` function.
4. Replace `testId` with `id` prop.
1. Provide conditional rendering for **Cluster Init Bundles** tile according to permissions.
* Encapsulate request to prevent 403 Forbidden status.
* Prepare for link to clusters instead of integrations.
2. Possibly encapsulate requests for counts of other sections to remove dependency on reducers and sagas.
Replace dynamic with static types offsets replace JavaScript with TypeScript conditional code like: `'categories' in integration && integration.categories`
2. `yarn build` in ui and then …
> ROX-19541: Rewrite IntegrationTilesPage in TypeScript

- .github/CODEOWNERS
Trying two things:
- a higher position in the config file
- adding a leading path delimiter
in order to avoid UI team members from getting tagged by operator file changes, which happened earlier today
N/A
> chore(cleanup): Adjust position of ui team codeowners

- ui/apps/platform/src/Containers/Integrations/IntegrationForm/AnnotationKeyLabelIcon.tsx
- ui/apps/platform/src/Containers/SystemConfig/Details/PrivateConfigDataRetentionDetails.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobStatus.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/ReportParametersDetails.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.ts
This PR fixes the following issues:
1. ROX-19305: [[Report jobs] The table flickers](https://issues.redhat.com/browse/ROX-19305)
https://github.com/stackrox/stackrox/assets/4805485/503d8528-f497-4c50-8a58-f91cd522a134
2. ROX-19162: [[UI] Add the report job history retention tool tip](https://issues.redhat.com/browse/ROX-19162)
3. ROX-18906: [[Reports form] Clarify the notifier tooltips](https://issues.redhat.com/browse/ROX-18906)
*Before:*
*After:*
4. ROX-18905: [[Accessibility] ARIA input fields must have an accessible name](https://issues.redhat.com/browse/ROX-18905)
The IDs used in ARIA and labels must be unique. After you click `Create collection`, because collection form also has TextArea element with id=”description”, we will need to make the report description label unique. So the …
> feat(ui): VM Reporting 2.0 GA Fixes Pt 2

- pkg/fixtures/alert.go
- pkg/fixtures/policy.go
- pkg/notifiers/common.go
- pkg/notifiers/format.go
- pkg/notifiers/format_test.go
Email, Slack and Jira notifications aren't sent for events that have `NetworkFlowInfo` set in the `MessageAttributes` oneof. The reason is because it looks like the oneof doesn't play nicely with the email template. 
This change fixes it by just ignoring any `MessageAttributes` that is not `KeyValueAttrs`. Will file a separate ticket to revisit the template just for network flow alerts at a later time (to see if items from `NetworkFlowInfo` should be rendered or not)
Also fixes a bug with the URL for resource alerts 
~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into …
> ROX-11963: Notifications fail for network flow alerts

- ui/apps/platform/cypress/fixtures/alerts/alerts.json
- ui/apps/platform/cypress/integration/violations/violations.test.js
- ui/apps/platform/src/Containers/Violations/Details/ViolationDetailsPage.tsx
- ui/apps/platform/src/Containers/Violations/types/violationTypes.ts
- ui/apps/platform/src/Containers/Violations/violationTableColumnDescriptors.tsx
- ui/apps/platform/src/utils/textUtils.ts
Two primary changes for this PR:
1. Display the new audit log types with the constants converted from snake case (e.g., "network_policy") to start case ("Network Policy")
2. For audit log violations that only have a cluster, but no namespace, display only the cluster name (e.g., instead of "remote/", it should be "remote"
In addition, there are two small related changes in this PR
- I converted `ui/apps/platform/src/utils/textUtils.js` to TypeScript `ui/apps/platform/src/utils/textUtils.ts` before I realized I could leverage a lodash import to do the change here. I let the conversion stand.
- I fixed a small bug where audit log violations showed the policy name instead of the cluster name on the ViolationDetailsPage.
Testing manually against an OpenShift cluster with appropriate policies …
> ROX-19573: Change UI for new audit log options

- pkg/csv/http_writer.go
- pkg/csv/http_writer_test.go
- pkg/csv/utils.go
- pkg/csv/writer.go
HTTP CSV writer currently does not explicitly set the HTTP status code. While _I think_ we can rely on HTTP writer implementation to set the status code to `200` as default, there is no reason to be implicit here.
CI run.
> fix(csv): Ensure HTTP status is set for CSV writers

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/watchedImagesFlow.test.js
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesModal.tsx
- ui/apps/platform/src/hooks/useRestMutation.test.ts
- ui/apps/platform/src/hooks/useRestMutation.ts
Adds the "Watch image" modal form and formik validation to the Workload CVE page.
Adds a general purpose `useRestMutation` hook that is API compatible with the react-query equivalent to avoid boilerplate when making destructive async calls.
Unit tests for new hook.
Visit the workload CVE page and open the modal via header button. The default value in the form is empty. Click into the text input and then click out, the form will present an error and submitting will be disabled.
Close the modal and open the modal via a table row action. The text input should have the value of the image in the row that was selected. Click "Add image to watch list" and watch the form go through the loading state to the success state, showing an inline alert. …
> ROX-19337: Add watch image functionality to workload cve modal

- qa-tests-backend/src/main/groovy/services/ImageService.groovy
- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
- qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
- qa-tests-backend/src/test/groovy/RiskTest.groovy
- qa-tests-backend/src/test/groovy/SACTest.groovy
- qa-tests-backend/src/test/groovy/Services.groovy
We have seen `scanImage` and `detectBuildTime` flaking repeatedly when image registries respond with throttling or `5xx` status codes. See https://issues.redhat.com/browse/ROX-18772 and related tickets for some examples.
Fix retries by doing the following:
* Consolidate use of `scanImage`.
* Fix the retry in `ImageService.scanImage` by increasing the attempts from 1 to 10.
* Add retry to `requestBuildImageScan`.
I believe this should fix many of the CI flakes we've been seeing around `scanImage`.
CI
> ROX-18772: fix scanImage retry

- central/metrics/telemetry/gauges.go
- central/metrics/telemetry/telemetry.go
- image/templates/helm/stackrox-central/templates/99-openshift-monitoring.yaml
- image/templates/helm/stackrox-secured-cluster/templates/openshift-monitoring.yaml
- sensor/common/metrics/init.go
- sensor/common/metrics/metrics.go
Changes to conform to the latest ask by the Telemeter team to approve our telemetry metrics (see https://github.com/openshift/cluster-monitoring-operator/pull/2062).
* Normalize the Central metrics to relational structure via `rox_central_info` where `central_id` is the primary key. In queries the labels must be joined back onto the time series `rhacs:telemetry:rox_central_info * on(central_id) group_left rhacs:telemetry:rox_central_secured_vcpus`.
* Define a base `rox_sensor_info` metric for the sensor telemetry metric.
Tested with upstream image in OCP cluster with OpenShift monitoring. To simulate the downstream image, I manually set `ROX_PRODUCT_BRANDING=RHACS_BRANDING`.
CI `ocp-4-13-ebpf-qa-e2e-tests` failure is unrelated due to collector:
```
pkg/kocache: 2023/09/09 19:11:38.558678 …
```
> ROX-18276: Central info metric

- sensor/common/metrics/init.go
- sensor/common/metrics/metrics.go
#3387 added two dedicated counters for PLOP, but they where not used correctly.
Deployed the built image, port forwarded sensor's prometheus metrics and checked the counters are properly reported.
> fix(plop): use the correct counters

- central/reports/common/report_formatter.go
- central/reports/scheduler/schedule.go
- central/reports/scheduler/v2/reportgenerator/report_gen.go
- central/reports/scheduler/v2/reportgenerator/report_gen_impl.go
- central/reports/scheduler/v2/reportgenerator/singleton.go
This includes report config name in report csv name. 
Manually verified that when user downloads a report , report config is included in csv name
example - RHACS_Vulnerability_Report_Config_Test_07_September_2023.csv for report config called Test
> ROX-19159 Added report config name to report csv name

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#13-1-0
* Updated `plist` from 3.0.6 to 3.1.0 to address CVE-2022-37616 and CVE-2022-39353.
* compliance/hideScanResults.test.js
> chore(e2e): Update cypress 13.1.0 devDependencies in ui

- sensor/common/scannerclient/grpc_client.go
Fixes a broken URL used by sensor to talk to scanner-slim
Testing for current PRs for delegated scanning are breaking, expecting V2 scanner to be used.
```
common/delegatedregistry: 2023/09/12 20:43:21.373178 delegated_registry_handler.go:108: Info: Received scan request: "request_id:\"959df5bc-2017-4896-aac4-56b1073c53ba\" image_name:\"image-registry.openshift-image-registry.svc:5000/dave/dave-is:latest\" namespace:\"dave\" "
common/scannerclient: 2023/09/12 20:43:21.373351 grpc_client.go:133: Info: dialing scanner-v2 client: scanner-v4.stackrox.svc:8443
common/scannerclient: 2023/09/12 20:43:21.373752 grpc_client.go:119: Info: dialing scanner at scanner-v4.stackrox.svc:8443
grpc_internal: 2023/09/12 20:43:21.373792 clientconn.go:318: …
```
> fix(scan): set scanner-slim URL back to original value

- .github/actions/cache-go-dependencies/action.yaml
The operator build for release-4.2 was running out of space. This change removes the job only cache restore key which might be the culprit.
Re: https://redhat-internal.slack.com/archives/C05MSQS5FCJ/p1694559313461909?thread_ts=1694536962.249039&cid=C05MSQS5FCJ
Reproduced the issue: https://github.com/stackrox/stackrox/actions/runs/6165725672
Verified fixed: https://github.com/stackrox/stackrox/actions/runs/6165852925
> fix(CI): operator build out of space

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
Adds a (:eye: Watched image) label to the image cell of the workload cve image table, removing the equivalent text from the deployment column.
_Note that this changes the behavior in two ways from the current tech preview, making it match the behavior of VM 1.0_
1. No additional text or label will be displayed if the image is not watched and is part of zero deployments
2. Images with > 0 deployments that are watched **will** display the "watched image" label
CC @mansursyed - Do the above behavior changes make sense and accurately reflect the mocks? There are before/after screenshots below as well.
Watch some images.
Before:
After:
Clicking on a watched image label will open the modal:
> feat(ui): Add updated 'watched image' label to workload cve table

- scripts/ci/lib.sh
This fixes a bug with the CI where, on PR failure, would first send a Slack message informing the developer of the commit of the failure, _then_ generate the attachment from `junit2jira`. These changes simply swap that order
> fix(ci): Generate slack message, then send it

- CHANGELOG.md
- central/group/datastore/filter/filter.go
- central/group/datastore/filter/filter_test_constructors.go
- central/role/datastore/datastore_test_constructors.go
- central/role/service/service_impl.go
- central/role/service/service_impl_test.go
- central/role/validate_test.go
For a long time now, roles are created with the `Unrestricted` access scope when the parameter is missing.
The goal of the change is to now systematically require a valid access scope ID when creating a new role
Added integrated unit tests for the role creation and update with either correct or empty access scope IDs
```bash
% curl --insecure -XGET -u admin:$(cat deploy/k8s/central-deploy/password) https://localhost:8000/v1/roles/AnalystClone|jq .
{
"name": "AnalystClone",
"description": "",
"permissionSetId": "ffffffff-ffff-fff4-f5ff-fffffffffffe",
"accessScopeId": "ffffffff-ffff-fff4-f5ff-ffffffffffff",
"globalAccess": "NO_ACCESS",
"resourceToAccess": {},
"traits": null
}
% curl --insecure -XPUT -u admin:$(cat …
```
> ROX-9510: Require access scope ID for any role

- central/sensor/service/pipeline/nodeinventory/two_pipelines_test.go
Ensure the following [failure](https://github.com/stackrox/stackrox/actions/runs/6182333631/job/16781865998) does not happen:
```
central/sensor/service/pipeline/nodeinventory/two_pipelines_test.go:224:22: G601: Implicit memory aliasing in for loop. (gosec)
tt.setUpMocks(t, &tt.mocks)
```
- Run `make golangci-lint` locally
- CI
> fix(gosec): G601

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/watchedImagesFlow.test.js
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesTable.tsx
Adds the watched images table to the modal and the ability to unwatch an image.
e2e tests +
Open the watched images modal - by default no images are in the watched table:
Watch an image. Upon success the watched image will be added to the table:
The table on the parent page will also be refreshed to show the image including a "Watched image badge":
Add another:
Remove the images via the modal:
> ROX-19337: Add watched images table to modal

- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/AffectedComponents/AffectedComponentsModal.tsx
Discovered this issue when attempting to reproduce https://github.com/stackrox/stackrox/issues/7464. That issue was filed against 4.1.1 while this fix was tested against a different error in 4.3.0-dev. It is possible that this is the same problem manifesting in a different way due to changes since 4.1.1
The `listType` passed from the AffectedComponentsModal is eventually passed to [`getFragmentInfo`](https://github.com/stackrox/stackrox/blob/4bf9049dea4ef56dd9da2e8464ea0c48068cffd5/ui/apps/platform/src/utils/queryService.js#L290) in utils/queryService.js, which calls [`getFragmentName`](https://github.com/stackrox/stackrox/blob/4bf9049dea4ef56dd9da2e8464ea0c48068cffd5/ui/apps/platform/src/utils/queryService.js#L194) in the same file. None of the expected values in this function match the …
> fix(ui): Swap COMPONENT->IMAGE_COMPONENT in affected components modal

- ui/apps/platform/src/Containers/Policies/Wizard/Step2/PolicyBehaviorForm.tsx
Problem, as reported in GitHub issue #5722:
Layout problems in Safari on the Policy Behavior tab of the Policy Wizard were preventing filling out all the inputs, in particular the Event Source input.
Investigation:
As an early instance of our migration to the Red Hat PatternFly library, we had used two (2) `<Form>` React components for layout purposes only (not behavior), and the interaction of the rendered markup for those two components was breaking the Safari layout.
Solution:
Wrapping all the input markup in the tab with only one `<Form>` React component, and adding some appropriate utility CSS classes to mimic the desired spacing resolves the issue in Safari, without breaking the layout in other browsers.
I tested in various browsers, but in particular Safari and Chrome.
In addition …
> ROX-16600: Fix audit log layout bug in Safari

- ui/apps/platform/package.json
- ui/packages/ui-components/package.json
- ui/yarn.lock
Update to last 5.y.z version before investigating whether upgrade to 6 has any breaking changes.
Unlike some lint config dependencies, eslint can access the plugin even after deleting from ui/packages/ui-components/package.json.
1. `yarn lint` in ui and also in ui/apps/platform
> chore(ui): Update eslint-plugin-testing-library to 5.11.1

- central/vulnerabilityrequest/datastore/datastore.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl_benchmark_test.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl_cache_test.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl_create_req_test.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go
- central/vulnerabilityrequest/manager/requestmgr/singleton.go
- central/vulnerabilityrequest/utils/util.go
- central/vulnerabilityrequest/validator/validate.go
- pkg/testutils/verify_in_test_only.go
**Background:**
We prohibit users from creating vulnerability requests for CVEs in a scope if a existing requests already covers the CVE in that scope. 
**Issue:**
The issue was there existed race between the validation against existing requests and adding new request to database. Thus, the validation could be wrong by the time the request is actually database. 
**Solution:**
This PR ensure that the vulnerability request creation is not racy by allowing only one request to be evaluated at a time.
Unit + benchmark
```
BenchmarkCreate
BenchmarkCreate/create
BenchmarkCreate/create-8         	     250	   4319530 …
```
> chore: Remove vulnerability request creation race

- pkg/retry/retry.go
Use actual exponential backoff when `withExponentialBackoff=true` - currently the backoff function is quadratic instead of exponential. I stumbled upon this inconsistency and thought a PR is quicker than creating a ticket for it. 
CI
> fix: exponential back function in retry

- operator/tests/central/basic-central/80-assert-non-openshift.yaml
- operator/tests/central/basic-central/81-assert-non-openshift.yaml
Rename the env var in places which were apparently missed in https://github.com/stackrox/stackrox/pull/7614 but was not caught because the GKE operator e2e test job was not automatically triggered at that point yet.
CI should be sufficient now that the job is triggered automatically.
> ROX-19312: Rename ROX_NAMESPACE to POD_NAMESPACE in remaining places.

- operator/Makefile
- operator/bundle_helpers/patch-csv.py
- operator/bundle_helpers/requirements.txt
- operator/bundle_helpers/test_patch-csv.py
Context https://redhat-internal.slack.com/archives/C05MSQS5FCJ/p1694025354934279
Before this change, we have 4.2.0 release that has the following combination of attributes in CSV:
* `olm.skipRange: '>= 4.1.0 < 4.2.0'`
* `replaces: rhacs-operator.v4.1.0`
* `skips:  - rhacs-operator.v4.1.0` (de-newlined)
The problem is that all 4.1.1+ patches are truncated from the upgrade graph due to `replaces: rhacs-operator.v4.1.0`, and 4.1.0 can't be installed because it is skipped.
This change will make us have `replaces: rhacs-operator.v4.1.1`, i.e. the next patch in such situation. It's not optimal because currently the latest patch is 4.1.3 and we'd ideally do `replaces: rhacs-operator.v4.1.3`.
However, I don't know of a reliable way to find out patch versions already released that does not involve …
> fix: Fix 4.2.0 stuck operator upgrade when 4.1.0 is skipped

- pkg/scanners/quay/quay.go
We've seen regular timeouts in the scanner qa-tests.
I measured the typical response time of quay.io using our qa-test image scan endpoint
```
GET https://quay.io/api/v1/repository/rhacs-eng/qa/manifest/sha256:451efa58416d38e138afd1e0c5afcfffccf98f4c4ae9e0a7823adb9800a8beda/security?features=true&vulnerabilities=true
```
I queried the above endpoint 1000 times using 16 parallel requests and recorded the response time.
Based on these results, it looks like our 20 second timeout is cutting it a bit close. Therefore I propose increasing the client timeout to 60 seconds.
Note that we have retries in the qa-tests, but other clients don't necessarily retry.
> ROX-19719: increase quay.io client timeout

- ui/apps/platform/package.json
- ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#13-2-0
* Fixed an issue where `enter`, `keyup`, and `space` events were not triggering click events properly in some versions of Firefox.
* Upgraded Electron from `21.0.0` to `25.8.0`, which updates bundled Chromium from `106.0.5249.51` to `114.0.5735.289`. Additionally, the Node version binary has been upgraded from `16.16.0` to `18.15.0`. This does NOT have an impact on the node version you are using with Cypress and is merely an internal update to the repository & shipped binary.
* compliance/hideScanResults.test.js
> chore(e2e): Update cypress 13.2.0 devDependencies in ui

- central/debug/service/diagnostics.go
- central/debug/service/service.go
We have seen repeated timeouts in the qa-tests when requesting a diagnostic bundle (timeout=5min):
```
11:10:36 | INFO  | DiagnosticBundleTest      | DiagnosticBundleTest      | Starting testcase: Test that diagnostic bundle download succeeds with admin access token
11:15:41 | DEBUG | DiagnosticBundleTest      | Helpers                   | Caught exception. Retrying in 10s (attempt 0 of 10): io.restassured.internal.http.ResponseParseException: status code: 200, reason phrase: OK
11:20:56 | DEBUG | DiagnosticBundleTest      | Helpers                   | Caught exception. Retrying in 10s (attempt 1 of 10): io.restassured.internal.http.ResponseParseException: status code: 200, reason phrase: OK
```
There is no apparent cause and it's unclear where in Central the diag bundle request handler …
> ROX-19524: add debug logs to diag bundle

- central/vulnerabilityrequest/manager/requestmgr/manager_impl.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl_cache_test.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl_create_req_test.go
- central/vulnerabilityrequest/utils/util.go
- central/vulnerabilityrequest/utils/util_test.go
When a vulnerability request is approved, other vulnerability requests whose one or more CVEs are covered by the approved requests should be auto-declined.
Unit tests
https://github.com/stackrox/stackrox/assets/9895898/9c61587f-7575-489a-a74f-42a684d9cdbd
https://github.com/stackrox/stackrox/assets/9895898/40304753-0317-42e3-8b40-7a4fb36bcbe1
> ROX-19767: Auto-decline similar scoped vuln requests

- ui/apps/platform/cypress/integration/vulnmanagement/entitypages.test.js
The link from namespace in side panel to its cluster should not push onto the workflow state.
Therefore, this filter test for the old behavior becomes obsolete.
Also, it assumed the cluster has fixable image CVEs, which is often false for nightlies-gke-latest-ui-e2e-tests
> chore(ui): Delete obsolete entitypages integration test

- central/scannerdefinitions/handler/handler.go
- go.mod
- go.sum
- pkg/httputil/error.go
- roxctl/central/debug/download_diagnostics.go
- roxctl/central/debug/download_diagnostics_test.go
- roxctl/common/client.go
- roxctl/scanner/uploaddb/uploaddb_test.go
We've been dealing with issues within roxctl when calling APIs via HTTP. For gRPC, retries have already been added, however for HTTP not yet.
This PR adds retries to the HTTP client shared for each command within the environment by leveraging [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp).
The current retry logic is a maximum of 3 retries, using an exponential backoff with a minimum wait time of 10 second and a maximum wait time of 30 seconds in-between requests. This should help with CI flakes we've seen.
- see CI.
performed one does not seem sufficient. As a reviewer, you must not approve the change until …
> ROX-19613: Retry http calls in roxctl

- CHANGELOG.md
- central/detection/buildtime/detector_impl_test.go
- central/detection/utils.go
- central/detection/utils_test.go
With the introduction of custom categories, the API enforces that custom categories are title-cased.
However, the detection APIs, where categories can be passed to filter policies, enforces all categories to be lower-cased.
This lead to issues with roxctl, where custom categories couldn't be used since the backend would always lower-case them, leading to the categories not being recognized.
This PR fixes this behavior by removing the lower-casing within the backend service.
While this may have impact on users due to a slight change in behavior, the input has been invalid to being with, and lower-casing _must_ be removed to support custom categories.
Left a changelog entry to clarify this.
- see adjusted unit tests.
In addition to …
> ROX-19738: Fix policy categories filter

- central/processlisteningonport/datastore/datastore_impl.go
Changes a noisy log statement to debug.
> refactor: change plop log to debug

- CHANGELOG.md
- central/detection/buildtime/detector_impl_test.go
- central/detection/utils.go
- central/detection/utils_test.go
Reverts stackrox/stackrox#7824
UI E2E tests are failing, which need to be fixed.
Originally, UI e2e tests are not running on normal PRs without UI changes, hence this slipped through.
> fix(ci): revert policy category PR

- ui/apps/platform/src/Containers/DeferralConfiguration/DeferralConfigurationPage.tsx
- ui/apps/platform/src/Containers/MainPage/Body.tsx
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/routePaths.ts
Adds routing and an empty page for vulnerabilities deferral configuration.
Load the main navigation without the `ROX_VULN_MGMT_UNIFIED_CVE_DEFERRAL` flag set. "Deferral configuration" should not appear in the main navigation, and direct navigation via URL should display a not-found page.
Load the main navigation without the `Administration` resource permission. "Deferral configuration" should not appear in the main navigation, and direct navigation via URL should display a not-found page.
Load the main navigation with both of the above:
> ROX-19344: Add deferral configuration page

- ui/apps/platform/cypress/helpers/request.js
- ui/apps/platform/cypress/integration/compliance/Compliance.helpers.js
- ui/apps/platform/cypress/integration/compliance/complianceDashboard.test.js
- ui/apps/platform/cypress/integration/compliance/hideScanResults.test.js
Test flake fix that has been becoming more frequent lately.
Each flake was due to a network timeout waiting for a large number of requests to return. On my local machine, it can take 5-6 seconds for the scan to complete and all requests to finish, so it is not unreasonable that this would take > 10 seconds in CI.
The fix here increases the `requestTimeout` for each test that runs a compliance scan to 20 seconds. This extends the `waitForResponses` helper to allow pass-through of an options object to `cy.wait()`.
CI
Verified the new timeout locally by setting it to `200ms` and verifying that local Cypress runs would fail for these specific tests.
> ROX-14380: Increase Cypress request timeout when scanning compliance

- ui/apps/platform/src/Containers/DeferralConfiguration/DeferralConfigurationPage.tsx
- ui/apps/platform/src/Containers/DeferralConfiguration/VulnerabilitiesConfiguration.tsx
Adds the tab structure (Vulnerabilities tab only) and basic page layout.
Load the deferral config page:
> ROX-19344: Add tabs and vuln deferral config container

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/watchedImagesFlow.test.js
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesTable.tsx
Hides the action cell and "Watch image" option for images that do not have a tag (e.g. digest based images). Currently attempting to watch one of these images always results in an error, so the option has been removed.
Load the images tab and see images without tags and without table actions:
> fix(ui): Remove table row action for images without a tag

- ui/apps/platform/src/Containers/DeferralConfiguration/VulnerabilitiesConfiguration.tsx
Adds the form items and layout for vuln deferral config.
This does not include
- Loading of deferral config
- Formik/validation
- Handling form controls or the Save button
Load the deferral config page and test the layout at different screen sizes.
https://github.com/stackrox/stackrox/assets/1292638/3079c834-4371-4f72-9d87-58e7fb6b5cab
> ROX-19344: Add deferral config form layout

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx
e2e tests for the Workload CVE overview page
1. Tests basic page properties and defaults
2. Test behavior of severity filter across the three entity tables
CI
> test(ui): Add Cypress tests for Workload CVE overview page

- sensor/common/detector/enricher.go
- sensor/common/scan/scan.go
- sensor/common/scan/scan_test.go
Addresses an assumption that the image passed to the local enricher is a valid image - an invalid image was triggering a sensor panic
The enricher was being passed `srcImage.GetName().GetFullName()` = `   is an invalid image`, ultimately causing:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2c41856]
goroutine 14758 [running]:
github.com/stackrox/rox/sensor/common/scan.scanImage({0x41bea48, 0xc01b9226c0}, 0x41ce8a?, {0x0?, 0x0?}, 0x28?)
github.com/stackrox/rox/sensor/common/scan/scan.go:366 +0x36
github.com/stackrox/rox/sensor/common/scan.(*LocalScan).fetchImageAnalysis(0xc004573b20, {0x41bea48, 0xc01b9226c0}, 0xc01e74bce0, {0x0, 0x0}, 0xc02dbf7b30) …
```
> ROX-19825: Sensor panics when invalid image passed to local enricher

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
Should fix a flake (permanent flake?) due to all CVEs reported on the Workload CVE list page only affecting a single image.
The selector to grab this element looked for `"images with"` in the aria-label, which is correctly rendered as `"image with"` when there is only one.
See video screenshot from a failed test run:
Local test run.
Awaiting CI.
> ROX-19824: Fix severity count selector in UI e2e test

- operator/main.go
Add env variables which allows to disable central or secured cluster reconcilers.
It will be used in ACSCS to prevent dogfooding operator from reconciling tenant centrals
local testing with `make install run` …
> ROX-19819: Add flags to disable central and secured cluster reconciler

- central/featureflags/service/service_impl.go
- central/role/service/service_impl.go
Document why the two mentioned endpoints are not authenticated, and the steps to make them authenticated.
Only adding documentation comments. There should be no imapct.
CI is therefore sufficient. …
> ROX-19138: `/v1/resources` and `/v1/featureflags` authentication doc

- central/reports/common/report_formatter.go
- central/reports/scheduler/schedule.go
- central/reports/scheduler/v2/reportgenerator/consts.go
- central/reports/scheduler/v2/reportgenerator/email_formatter.go
- central/reports/scheduler/v2/reportgenerator/email_formatter_test.go
- central/reports/scheduler/v2/reportgenerator/report_gen_impl.go
- central/reports/scheduler/v2/reportgenerator/types.go
- pkg/fixtures/report_snapshot.go
- pkg/notifiers/email/email.go
- pkg/notifiers/report_notifier.go
> ROX-19483: Add default email subject, body and config details to emailed reports

- go.mod
- go.sum
This updates the zap dep, as has already been done on master.
The updated version doesn't print stack traces when structured logs are used, which leads to _very_ verbose logs such as:
```log
reprocessor: 2023/09/25 16:10:42.793474 reprocessor.go:312: Error: Error enriching image {"image": "quay.io/stackrox-io/scanner-db:2.31.x-7-gf65eb03ab0", "error": "image enrichment error: error getting metadata for image: quay.io/stackrox-io/scanner-db:2.31.x-7-gf65eb03ab0 errors: [getting metadata from registry: \"Autogenerated https://quay.io/ for cluster remote\": failed to get the manifest digest: Head \"https://quay.io/v2/stackrox-io/scanner-db/manifests/sha256:abf679f955906b7ee8e2c0c44c1f55744cf874ea4d68c1264e30292dc24b5ce2\": net/http: request canceled while waiting for connection …
```
> fix(dep): update zap dep to avoid verbose logging

- central/detection/buildtime/detector.go
- central/detection/buildtime/detector_impl.go
- central/detection/deploytime/detector_impl.go
- central/detection/lifecycle/manager.go
- central/detection/lifecycle/manager_impl.go
- central/detection/lifecycle/singleton.go
- central/detection/runtime/detector_impl.go
This issue was found during testing / verifying the fix for [ROX-19738](https://issues.redhat.com/browse/ROX-19738): when creating a build-time policy and using the detection service to check for policy violations (e.g. via `roxctl image check`), the behavior currently is as-follows:
- The build time detector's policy set will be filled with the existing policies during [within the initialize function](https://github.com/stackrox/stackrox/blob/master/central/detection/buildtime/singleton.go#L38).
- Afterwards, no modifications are made to the policy set, meaning neither newly added, updated, or removed policies will be taken into account.
- The result of the `DetectBuildTime` request then may contain stale data, either from policies that _may_ have been already removed / updated, or miss …
> fix(detection): update build time policies for detection

- CHANGELOG.md
- central/detection/buildtime/detector_impl_test.go
- central/detection/utils.go
- central/detection/utils_test.go
Reverts stackrox/stackrox#7834
This was initially reverted since a CI failure related to policy categories was found within the `ui-e2e-tests` on main.
This PR ensures that the changes aren't at fault, and after confirming that the changes are good-to-be merged again.
> ROX-19738: Fix policy categories

- image/templates/helm/stackrox-central/templates/_central_endpoints.tpl
Prior to Go 1.18, the `and` function evaluates all expressions instead short-circuiting. This causes a problem when intermediate values are nil. See also https://stackoverflow.com/a/59796677 for an explanation.
Fixes https://github.com/stackrox/stackrox/issues/7905.
```
export OUTPUT_FORMAT=helm
./deploy/k8s/deploy-local.sh
```
with Helm `3.9.0` with and without this patch.
> fix: nil evaluation in central endpoint Helm template

- ui/apps/platform/src/Containers/DeferralConfiguration/useVulnerabilitiesDeferralConfig.ts
- ui/apps/platform/src/services/DeferralConfigService.ts
Adds service calls for vulnerability deferral config and a hook to read/write config data.
Manual testing of the APIs via REST client only.
Functional testing is done in follow up PRs.
> ROX-19344: Add service for vuln deferral config

- ui/apps/platform/package.json
- ui/yarn.lock
For Cypress 13.2.0 and 13.3.0 on CI
```
@stackrox/platform-app: Opening Cypress...
@stackrox/platform-app: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /alabama/.cache/Cypress/13.3.0/Cypress/resources/app/packages/server/lib/modes/addon/addon-native.node)
@stackrox/platform-app: Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /alabama/.cache/Cypress/13.3.0/Cypress/resources/app/packages/server/lib/modes/addon/addon-native
```
Thanks to super searcher Van:
* Test replay issue: https://github.com/cypress-io/cypress/issues/27902
* Cypress opening issue: https://github.com/cypress-io/cypress/issues/27920
Downgrade to Cypress 12
> chore(e2e): Downgrade to cypress 12.17.4 devDependencies in ui

- ui/apps/platform/src/routePaths.ts
TL;DR reduce role-based access control resource requirements for 6 route keys:
* `compliance`
* `configmanagement`
* `'network-graph'` indirectly via `nonGlobalResourceNamesForNetworkGraph`
* `'policy-management'`
* `risk`
* `'vulnerability-management'`
For cherry pick into 4.2.1 release branch, changes are limited to prevent merge conflicts with 3 route keys added in routePaths.ts file **after** 2023-08-24 https://github.com/stackrox/stackrox/pull/7566
* `'administration-events'`
* `'clusters/init-bundles'`
* `'deferral-configuraton'`
Because I missed the forest for the trees while adding conditional rendering within routes to reduce `resourceAccessRequirements` during sprint 4.2C, some routes became unavailable for primary use cases because of lack of resources for secondary use cases, …
> ROX-19860: Reduce RBAC resource requirements for routes

- sensor/common/detector/detector.go
- sensor/common/metrics/metrics.go
Deduping at the detector level is one of the reason why we have to hash deployments so frequently. If we could remove the deduper in detector, we can reduce the hashing load by half. However, we first need to understand if after re-sync we are still hitting the deduper frequently. 
If `detector_deduper_cache_hit` metric is close to `0`, we could safely remove the deduper and cash-in the allocations improvement. 
> feat(metrics): Add dedupe metrics to detector

- ui/apps/platform/src/Containers/VulnMgmt/Entity/Cluster/VulnMgmtEntityCluster.js
- ui/apps/platform/src/Containers/VulnMgmt/Entity/Namespace/VulnMgmtEntityNamespace.js
WorkflowAdministration is a resource requirement for `'vulnerability-management'` sub-routes:
* /main/vulnerability-management/clusters
* /main/vulnerability-management/namespaces
If user role does not have that resource:
> Unable to load data
> not authorized: "READ_ACCESS" for "WorkflowAdministration"
Components include unused policy properties in their query:
* VulnMgmt/Entity/Cluster does not use `policyStatus` nor `policyCount` values.
* VulnMgmt/Entity/Namespace does not use `policyStatus` nor `policyCount` values.
Delete obsolete! It rhymes ;)
main.css: 0 = 3761413 - 3761413
total: -1457 = 10117437 - 10118894
0 = 84 - 84 …
> ROX-19873: Delete policy properties in Vulnerability Management 1.0

- .github/workflows/build.yaml
The build is failing due to space constraints. [e.g.](https://github.com/stackrox/stackrox/actions/runs/6346218781/job/17262716217#step:27:228) 
This change uses `docker system prune` to claw back available space prior to the failing `push_matching_collector_scanner_images()` step which needs to pull images.
- repro: https://github.com/stackrox/stackrox/actions/runs/6355527223/job/17264416299?pr=7935#step:27:221
- fixed: https://github.com/stackrox/stackrox/actions/runs/6355979382/job/17265328071#step:27:1
In CI (links above).
> fix(build): Get space for `-rcd` build

- central/compliance/checks/common/checks.go
- central/compliance/checks/docker/runtime.go
- central/compliance/checks/docker/runtime_test.go
- central/compliance/checks/hipaa_164/check308a1iia/check_test.go
- central/compliance/checks/nist800-190/check412/check.go
- central/compliance/checks/nist800-190/check412/check_test.go
- central/compliance/data/repository.go
- central/compliance/framework/data.go
- central/compliance/framework/mocks/data.go
We were loading all indicators into memory in order to check that at least 1 existed and also if they were SSH processes. Instead, target the loading to only ones that could be SSH processes which should be a large subset of the processes overall.
Should be able to see the reduced memory on high process clusters
> fix(memory): Reduce compliance memory used by process indicators

- pkg/grpc/server.go
We noticed that unauthorized calls to `/v1/metadata` were being recorded as `Unknown` status code in prometheus metrics, even though the corresponding error `errox.NotAuthorized` was being mapped to `403` http status code for the client. The reason this happens is the current order of the unary grpc interceptors, which record metrics *before* the error to status code conversions happens.
before
```
grpc_server_handled_total{grpc_code="Unknown",grpc_method="GetMetadata",grpc_service="v1.MetadataService",grpc_type="unary"} 8
grpc_server_handled_total{grpc_code="Unknown",grpc_method="GetCentralCapabilities",grpc_service="v1.MetadataService",grpc_type="unary"} 2
grpc_server_handled_total{grpc_code="Unknown",grpc_method="GetConfig",grpc_service="v1.TelemetryService",grpc_type="unary"} 2 …
```
> ROX-19887: fix grpc status code in metrics

- .github/workflows/build.yaml
Ported from: #7935
The build is failing due to space constraints. [e.g.](https://github.com/stackrox/stackrox/actions/runs/6346218781/job/17262716217#step:27:228) 
This change uses `docker system prune` to claw back available space prior to the failing `push_matching_collector_scanner_images()` step which needs to pull images.
- repro: https://github.com/stackrox/stackrox/actions/runs/6355527223/job/17264416299?pr=7935#step:27:221
- fixed: https://github.com/stackrox/stackrox/actions/runs/6355979382/job/17265328071#step:27:1
In CI (links above).
> fix(build): Get space for -rcd build

- ui/apps/platform/src/Containers/DeferralConfiguration/VulnerabilitiesConfiguration.tsx
- Adds formik validation to form items
- Connects the "Save" button to update the config
- Adds READ_ACCESS permission checks to disable the form and remove the "Save" button
View the page with a user who has `READ_ACCESS` for `Administration`:
View the page with full access, change and save the configuration:
Test validation of numeric fields:
Test that duplication validation only impacts numeric fields that are enabled:
> ROX-19344: Add validation and persistence to deferral config form

- ui/apps/platform/cypress/integration/vulnmanagement/reporting/reportingForm.test.js
- ui/apps/platform/cypress/integration/vulnmanagement/reporting/reportingTable.test.js
- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReportingPage.tsx
- ui/apps/platform/src/routePaths.ts
This PR uses the `ROX_VULN_MGMT_REPORTING_ENHANCEMENTS` to determine whether or not to show the v1 Reporting view or the v2 Reporting view.
The feature flag is on
The feature flag is off
> chore(ui): Hide/show reporting v1 and v2 based on feature flag

- qa-tests-backend/src/test/groovy/VulnScanWithGraphQLTest.groovy
Updates test image to use the multiarch version
Following changes have been made in the test case for the mulitarch image
- Updated total number of CVE's in image
- Updated CVE in graphQL query from CVE-2017-18190 to CVE-2017-12611
- Updated base image from debian:8 to ubuntu:20.04
> ROX-14127: VulnScanWithGraphQLTest multi-arch image update

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
This PR intends to add multi-arch support for the `NetworkFlowTest` QA test.
Since the P/Z libvirt based clusters don't support external loadbalancer, the `setCreateLoadBalancer()` is set to false.
Changes are verified manually using `./gradlew test --tests=NetworkFlowTest`
> ROX-19920: Make NetworkFlowTest multi-arch compliant

- pkg/clientconn/client.go
- pkg/grpc/server.go
- sensor/common/centralclient/grpc_connection.go
Sensor shares the same variable with sensor for gRPC server max receive size (ROX_GRPC_MAX_MESSAGE_SIZE).
However, this is not considered for gRPC clients. Meaning that central messages will have a hardcoded default threshold of 4MB.
This is important for the work in #7755 since the deduper size can grow and we'd like to fine-tune the maximum receive size in sensor without patching if users are hitting the 4MB threshold. 
**Note to reviewers:** an alternative to having to expose `MaxMsgSizeSetting` from `pkg/grpc` would be to have a new variable config only for the client max size.
Running local-sensor with max receive as `10B` fails on the first received message from Central:
```
$ ROX_GRPC_MAX_MESSAGE_SIZE="10" go run …
```
> ROX-19885: Set gRPC max receive size for client connection

- central/cluster/service/service_impl.go
- central/cluster/service/service_impl_test.go
- central/config/datastore/datastore.go
- central/config/datastore/datastore_test.go
- central/config/datastore/mocks/datastore.go
- central/config/datastore/singleton.go
- central/config/service/service.go
- central/main.go
- central/pruning/pruning.go
- central/pruning/pruning_test.go
The `/v1/config/public` endpoint does not always return the data it should.
In order to ensure the public config is always returned, access to the public and private parts of the config are separated, and the access control is relaxed on the public part.
New unit tests added.
Manual testing
```bash
% curl --insecure -XGET https://localhost:8000/v1/config/public
```
> ROX-19139: Split config read into private and public parts

- image/templates/common/ca-setup.sh
Fix broken file search in `ca-setup.sh`.
Currently the script could not find any file in the directory, even with the correct extensions `.crt` and `.pem`. 
1. Download a Sensor bundle from Central (ACSCS instance)
2. Extract it
3. ./sensor/ca-setup-sensor.sh -d sensor/additional-cas
```
RHACS ./sensor/ca-setup-sensor.sh -d sensor/additional-cas
The following certificates will be used as additional CAs:
- sensor/additional-cas/00-rds-ca-bundle.crt
W1004 11:14:04.253818   48979 helpers.go:663] --dry-run is deprecated and can be replaced with --dry-run=client.
secret/additional-ca-sensor created
secret/additional-ca-sensor labeled
``` 
In addition to reviewing code here, reviewers **must** also review testing and request further testing in …
> ROX-19868: Fix broken file search in ca-setup.sh

- central/administration/events/datastore/datastore.go
- central/administration/events/datastore/datastore_impl_benchmark_test.go
- central/administration/events/datastore/internal/store/mocks/store.go
- central/administration/events/datastore/internal/store/store.go
This PR adds a benchmark to the datastore for administration events, specifically to benchmark the buffered writer's `Upsert` and `Flush` methods.
A follow-up PR will be created to address the issue of slow mutex, this can be seen as a prefactor to allow for performance comparision.
The result of the benchmark ran locally:
```
goos: darwin
goarch: amd64
pkg: github.com/stackrox/rox/central/administration/events/datastore
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkDatastore_Add_and_Flush
BenchmarkDatastore_Add_and_Flush/add_1000_events_to_the_writer_and_flush_it
BenchmarkDatastore_Add_and_Flush/add_1000_events_to_the_writer_and_flush_it-12         	      10	 836921826 ns/op
BenchmarkDatastore_Add_and_Flush/add_5000_events_to_the_writer_and_flush_it …
```
> feat(admin-events): add benchmarks for datastore

- qa-tests-backend/src/test/groovy/PolicyConfigurationTest.groovy
This PR intends to fix failures on P/Z with `PolicyConfigurationTest`. Changes in the test would make it multi-arch compliant.
This PR intends to fix [ROX-16935](https://issues.redhat.com/browse/ROX-16935)
> ROX-16935: Make PolicyConfigurationTest multi-arch compliant

- central/delegatedregistryconfig/delegator/delegator.go
Adds the segment `ScanDelegatorSearchNamespaces` to the existing `function_segment_duration_bucket` metric for capturing how long the namespace access checks take for delegated scans.
This was requested in a [previous PR review](https://github.com/stackrox/stackrox/pull/7650#discussion_r1324288105).
On an OCP infra cluster:
- Installed ACS Central Services and Secured Cluster
- Scanned `nginx` and 3 other images using: `roxctl ... --cluster=remote`
- Set up port-forward to central deployment metrics port: `k port-forward deploy/central 9090`
- Observed new metric was created via output from `localhost:9090`
```
...
rox_central_function_segment_duration_bucket{Segment="ScanDelegatorSearchNamespaces",le="4"} 4 …
```
> ROX-19678: Add metric delegate scan namespace access check

- ui/apps/platform/cypress/integration/administration/events/AdministrationEvents.helpers.js
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEvent.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventDescription.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventHintMessage.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsPage.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsTable.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsToolbar.tsx
- ui/apps/platform/src/services/AdministrationEventsService.ts
Make invisible changes to prepare for next steps in events page and visible changes to finish the event page.
If needed, sprint demos can use edited page addresses in browser history.
1. Events page
* Add hooks for pagination, search, and sort in page address query string. Thank you, David Vail.
* Support pagination in toolbar.
* Add tagline following page heading.
Troubleshoot platform issues by reviewing event logs. Events are purged after 4 days by default.
* Add **N events found** count at left of toolbar.
2. Event page
* Add `Alert` element to display level, hint, message properties.
* Refactor hint and message instead of repeating code from events page.
3. AdministrationService
* Replace `string` with `number` for count and  `string` with `string[]` for filter properties according …
> ROX-19910: Add administration events query string to page address

- central/graphql/resolvers/images.go
- ui/apps/platform/src/Components/CVEStackedPill/CVEStackedPill.js
- ui/apps/platform/src/Containers/VulnMgmt/VulnMgmt.constants.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
- ui/apps/platform/src/routePaths.ts
We should not block access to images if a user is not authorized to look at a watched image. Instead just return unknown.
Will run with a role without watched image and ensure that the ui and everything looks good
> fix(bug): Return unknown when not authorized for watch status

- central/apitoken/expiration/expiration.go
- central/apitoken/expiration/expiration_test.go
- pkg/administration/events/domain.go
- pkg/administration/events/hints.go
- pkg/administration/events/resources/resources.go
- pkg/logging/fields.go
- pkg/logging/log_converter_impl.go
- pkg/logging/log_converter_impl_test.go
This PR enables the creation of administration events for the log messages for API token expirations.
This enables more visiblity for the expiration.
A new resource `API Token` was created with the new domain `Authentication`.
Additionally provided a fix to allow passing both `resource ID` and `resource name` fields via zap.Field. Previously this rendered in an error.
- see the added unit tests. …
> ROX-19773: API token expiration events

- qa-tests-backend/src/test/groovy/SACTest.groovy
Updates SACTest to use multiarch image for nginx-unprivileged-1.25.2
relying on CI
> fix(qa): Update multi-arch image for SACTest

- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsTable.css
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsTable.tsx
Yuck, in such a hurry that I copied title of subsequent pull request into commit message.
Thanks to Daniel Haus for reporting this problem that I overlooked in #7958
**Count** column head aligned left but data aligned right (common convention for numeric values).
Utility class worked when column head contained only text, but `sort` param implicitly wraps text in a `button` element.
1. Delete `className` prop.
2. Replace obsolete style rules with rule that aligns `button` element at right.
Before `yarn deploy` in ui, do the following:
```sh
export ROX_ADMINISTRATION_EVENTS=true
```
1. Visit /main/administration-events
* **Count** aligned left without style rule
* **Count** aligned right with style rule
Before `yarn cypress-open` in ui/apps/platform, do the following:
```sh
export …
```
> ROX-20001: Align administration events Count column head at right

- .github/actions/job-preamble/action.yaml
- .github/workflows/build.yaml
- .github/workflows/style.yaml
- .github/workflows/unit-tests.yaml
GHA jobs often fail due to insufficient disk space. The containerized jobs start with 16G available:
https://github.com/stackrox/stackrox/actions/runs/6422072015/job/17437813543?pr=7985#step:3:9
There is a cache of docker images that are not relevant to stackrox style, unit-test, build needs:
https://github.com/stackrox/stackrox/actions/runs/6422072015/job/17437813543?pr=7985#step:3:11
Which if freed gets 22G available:
https://github.com/stackrox/stackrox/actions/runs/6422072015/job/17437813543?pr=7985#step:3:129
> chore(ci): Free up some space for GHA runners

- .github/workflows/create-clusters.yml
- .github/workflows/cut-rc.yml
Auto-generated PR to update the upstream GHA automation with [643a2c906d31aa0bff39c4bbd886f5cea3868d8d](https://github.com/stackrox/test-gh-actions/commit/643a2c906d31aa0bff39c4bbd886f5cea3868d8d).
> fix(GHA): long running clusters must have shorter names (#132)

- sensor/common/centralclient/grpc_connection.go
- sensor/common/sensor/sensor.go
This PR removes the inner loop of the Sensor - Central connection logic, leaving us with only one loop.
Deployed the change to a cluster, scaled down Central to 0, observed Sensor losing connection.
Afterwards, scaled back Central to 1, observed Sensor reconnecting to Central. …
> ROX-17646: Remove waitUntilCentralIsReady

- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsEmptyState.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsPage.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsTable.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsToolbar.tsx
- ui/apps/platform/src/Containers/Administration/Events/SearchFilterDomain.tsx
- ui/apps/platform/src/Containers/Administration/Events/SearchFilterLevel.tsx
- ui/apps/platform/src/Containers/Administration/Events/SearchFilterResourceType.tsx
- ui/apps/platform/src/services/AdministrationEventsService.ts
Filter events to troubleshoot a particular platform issue.
Thanks again to David Vail for clear examples of search filters in Workload CVEs.
1. Edit AdministrationEventsPage.tsx file:
* Add props from `useURLSearch` hook to `AdministrationEventsToolbar` element.
* Add `searchFilter` prop to `AdministrationEventsTable` element.
2. Edit AdministrationEventsTable.tsx file:
* Delete unneeded fragment.
* Add conditional rendering for empty state.
3. Add AdministrationEventsEmptyState.tsx file:
* Adapt from existing examples.
4. Edit AdministrationEventsToolbar.tsx file:
* Add callback functions which call generic `setSearchFilter` function from `useURLSearch` hook with value from specific `replaceSearchFilterWhatever` functions.
* Call pure `getAdministrationEventsFilter` function that returns …
> ROX-19990: Add administration events search filters and empty state

- pkg/namespaces/constants.go
- sensor/upgrader/common/namespaces.go
- sensor/upgrader/preflight/namespace.go
- sensor/upgrader/preflight/namespace_test.go
- sensor/upgrader/upgradectx/context.go
The sensor upgrader is used when sensor is installed via manifest download, while at a later point central is updated to a newer version. The upgrader will then attempt to upgrade sensor to the same upgraded version. As part of the upgrade process, it currently checks that all resources are created in the stackrox namespace. With `4.2.0`, when integration with OpenShift monitoring is enabled, sensor additionally creates Prometheus resources in system namespaces.
This leads to a failure during the upgrader pre-flight check when upgrading from `4.1.x` to `4.2.0` for OpenShift secured clusters. As a fix for this issue, this PR adds the Prometheus resources to an exception list.
To reproduce the original issue:
* Install central via Helm chart version `4.1.3`.
* Install sensor via manifest …
> ROX-19955: Prometheus resources in sensor upgrader

- operator/tests/central/basic-central/10-assert.yaml
- operator/tests/central/basic-central/61-assert.yaml
- operator/tests/central/basic-central/62-assert.yaml
- operator/tests/common/central-cr-assert.yaml
- operator/tests/common/secured-cluster-cr-assert.yaml
Workaround for recently slow scanner startup while it is being investigated by the scanner team. I just added another 10 minutes to the deadline we already have for lack of a better number.
> ROX-19997: Bump timeout to 25 minutes when we wait for scanner.

- .github/actions/cache-go-dependencies/action.yaml
Backport of https://github.com/stackrox/stackrox/pull/8036
> fix(ci): release 3.74/remove problematic go cache hit

- qa-tests-backend/src/test/groovy/BuiltinPoliciesTest.groovy
This PR intends to add multi-arch support for the `BuiltinPoliciesTest` QA test.
Changes are verified manually using `./gradlew test --tests=BuiltinPoliciesTest`
> ROX-20056: Make BuiltinPoliciesTest multi-arch compliant

- .github/actions/cache-go-dependencies/action.yaml
> fix(ci): only restore go cache by hash on go.sum(s)

- central/debug/service/diagnostics.go
- central/telemetry/gatherers/cluster.go
When the context is canceled, errors that returned from `PullKubernetesInfo`, `PullMetrics` or `PullClusterInfo` might get missed since they are not logged but rather sent via channel to be written to diagnostic bundle. 
> fix: diag bundle - log errors that are missed when context is canceled

- roxctl/declarativeconfig/k8sobject/k8sobject.go
- roxctl/declarativeconfig/k8sobject/k8sobject_test.go
K8s client encodes secrets by itself, we don't need to do base64 encoding in roxctl.
1. Manual TBD
> fix: Remove extra base64 encoding in k8sobject.go

- CHANGELOG.md
- central/sensor/service/connection/connection_impl.go
- central/sensor/service/connection/initsync_manager.go
- central/sensor/service/connection/initsync_manager_test.go
- central/sensor/service/connection/manager_impl.go
- central/sensor/service/connection/sensorevents.go
- pkg/env/rate_limit.go
- pkg/errox/errors.go
- pkg/errox/grpc/mapping.go
This PR introduces an option to limit the number of sensors in init sync mode. This will reduce resource consumption for the Central component in situations when many sensors are doing initial sync (i.e., central update, or other situations where central is restarted)
Behavior is that if limit is reached we will not allow other sensors to connect. A returned error will use code 429 Resource Exhausted.
**Considerations**
1. The current solution uses set. My concern is if we can get into sitatuon where we will have lingering clusters in the set. That can lead to a state where sensors are not able to connect. Should we consider using `expiringcache.Cache` with an expiring time of 2h or so?
2. nitpick: The solution for no limit (0 limit) currently uses special `if` cases. Maybe we can …
> ROX-19561: Add limiter for maximum allowed init sync sensors

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/watchedImagesFlow.test.js
In some flavors of the OCP UI e2e tests, multiple rows with the same image name are returned in the default response when an image is watched. This ensures when selecting those images, that we grab the first one to avoid a Cypress error of attempting to click multiple elements.
Awaiting CI
> ROX-20042: Add 'first' qualifier to watched image row selectors

- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
This PR intends to add multi-arch support for the `ImageManagementTest` QA test.
Changes are verified manually using `./gradlew test --tests=ImageManagementTest`
> ROX-16930: Make ImageManagementTest multi-arch compliant v2

- scripts/ci/gcp.sh
- scripts/ci/gke.sh
- scripts/ci/metrics.sh
- scripts/ci/store-artifacts.bats
- scripts/ci/store-artifacts.sh
- scripts/ci/tools/get-info-about-osci-jobs/get-info-for-shas.sh
- tests/e2e/lib.sh
- tests/e2e/run-scale.sh
This PR changes the GCP login for CI to a RH project. And moves metrics, GKE clusters, artifacts and misc storage buckets to use those in that project created by IaC: https://github.com/stackrox/automation-iac/pull/25.
- All QA
- Plus upgrade and scale tests due to their use of GCS
> ROX-19262: Move CI to RH

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
As titled. For simplicity and consistency with VM 1.0, watched image functionality will be restricted to users with "READ_WRITE_ACCESS" on the "WatchedImage" resource.
"Hide whitespace" for easier reviewing.
Visit the Workload CVE list page, on the "Image" tab, with less than "READ_WRITE" permissions.
Revisit the page with full permissions.
> ROX-19968: Add permission checks for watched images controls

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx
This small change causes the datetime stamp that a report was run to be appended to the report name, when the report ZIP is downloaded.
We also do some rudimentary sanitization of the final filename to avoid file system conflicts.
Example: 
`name`: "Van 2:Electric/Slide"
`reportStatus.completedAt`: "2023-10-10T20:17:15.436832803Z"
filename used: "Van_2_Electric_Slide-2023-10-10T20_17_15.436832803Z.zip"
Manual testing
I created a report name with special characters, generated the report, and then downloaded it.
> ROX-19160: Append date to VM 2.0 Report download names

- sensor/common/deduper/deduper.go
- sensor/common/deduper/key.go
- sensor/common/deduper/key_test.go
This PR adds functions to parse the deduper state. Follow-up PRs will be opened to call this functions and initialize the deduper state.
> ROX-19696: add functions to parse deduper state

- qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
This PR intends to add multi-arch support for the `DefaultPoliciesTest` QA test.
Test images used in respective test are changed to use alternate multi-arch images which support 3 platforms viz. x86_64, ppc64le and s390x.
Changes are verified manually using `./gradlew test --tests=DefaultPoliciesTest`
Part of this PR intends to fix [ROX-16932](https://issues.redhat.com/browse/ROX-16932)
> ROX-16932: Make DefaultPoliciesTest multi-arch compliant

- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsPage.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsToolbar.tsx
- ui/apps/platform/src/Containers/Administration/Events/SearchFilterDomain.tsx
- ui/apps/platform/src/Containers/Administration/Events/SearchFilterLevel.tsx
- ui/apps/platform/src/Containers/Administration/Events/SearchFilterResourceType.tsx
- ui/apps/platform/src/Containers/Administration/Events/UpdatedTimeOrUpdateButton.tsx
- ui/apps/platform/src/services/AdministrationEventsService.ts
- ui/apps/platform/src/utils/dateUtils.ts
Let users decide when to load new events, following the precedent of Network Graph.
Events page implicitly reloads after any user action:
* to change search filters, sorting, or (theoretically in this case) pagination
* to visit an event page and then go back
If all events in polling request are new, then render **Load 10+ new events** (or whatever is the `perPage` amount) because frontend knowledge is limited to current page.
As discussed, frontend knowledge is limited to current request params.
1. Edit AdministrationEventsPage.tsx file.
* Separate `useEffect` for initial request and user-initiated actions from `useEffect` for polling requests.
* Frontend polling interval 60 seconds corresponds to backend reprocessing of events. 
* Count available events compared to set of event id for …
> ROX-20012: Add polling for administration events

- central/reports/scheduler/v2/reportgenerator/consts.go
- central/reports/scheduler/v2/reportgenerator/email_formatter.go
- central/reports/scheduler/v2/reportgenerator/report_gen_impl.go
- central/reports/scheduler/v2/reportgenerator/types.go
- central/reports/service/v2/service_impl_test.go
- central/reports/validation/validate.go
- pkg/branding/brandedtext.go
- pkg/env/vulnerability_management.go
This PR fixes following bugs
- Custom subject not getting sent in report emails
- Increase custom subject and body max lengths to match the settings on UI
- Make the default email body consistent with the UI
Manual testing
performed one does not seem sufficient. …
> ROX-19984: Report emails do not have custom subject and other bugs

- go.mod
- go.sum
Bump the grpc-http1 library to a version which has the fixed version of x/net for CVE-2023-39325 (aka CVE-2023-44487)
No
> build(deps): bump golang.stackrox.io/grpc-http1 from 0.2.11 to 0.2.12

- scripts/release-tools/kube-burner-configs/cluster-density/config.yml
- scripts/release-tools/kube-burner-configs/cluster-density/configmap.yml
- scripts/release-tools/kube-burner-configs/cluster-density/deployment.yml
- scripts/release-tools/kube-burner-configs/cluster-density/service.yml
- scripts/release-tools/kube-burner-configs/kube-burner-cr.yml
- scripts/release-tools/kube-burner-configs/secret_template.yml
…configs (#116) (#7528)
Backport of #7528. This should help us when we run the Create clusters action to create long running clusters.
> ROX-17741: long running cluster should include collector kube burner

- .openshift-ci/clusters.py
- scripts/ci/gke.sh
- scripts/ci/jobs/gke_operator_e2e_tests.py
I suspect slow scanner-db startup (up to 20x the time on OCP/AWS) that causes gke-operator-e2e tests to flake out is caused by poor disk performance. This PR tries to improve it by resizing the disks 10x, since their performance scales linearly with size. More details and calculations in the ticket.
I wanted to conduct some experiments first but [it seems I lack permissions](https://redhat-internal.slack.com/archives/CVANK5K5W/p1697003899544809). However just giving this a go is worth doing anyway and we can observe the impact in CI.
I took a look at the `init-db` init container execution times in the `gke-operator-e2e` job for this PR, and they were:
* 1m53s 
* 2m4s
* 1m54s
* 2m3s
* 1m44s
For an unrelated PR on top of `master` it's:
* 1m58s
* 2m37s
* 2m21s
* 2ms6s
* 1m17s
So not much …
> ROX-20040: Try and improve gke-operator-e2e disk performance

- scripts/release-tools/kube-burner-configs/cluster-density/berserker-configmap-endpoints-zipf.yml
- scripts/release-tools/kube-burner-configs/cluster-density/config.yml
- scripts/release-tools/kube-burner-configs/cluster-density/endpoint-load-deployment.yml
Kube-burner now creates listening endpoints load via berserker. A new deployment is created in which berserker reads a workload file that specifies the endpoints load. The workload used for the endpoints is specified in a confimap.
This just changes some config files for kube-burner, so no testing or user facing documentation is required. 
Go to …
> ROX-19857: long running collector should have listening endpoints load

- scripts/ci/lib.sh
`curl` does not return an error when server return non 200 OK.
This PR adds flags that should make curl reporting this kinds of errors.
Example: https://storage.googleapis.com/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-ocp-4-10-merge-ui-e2e-tests/1704350553095540736/build-log.txt
I've created invalid slack message in `payload.json`.
```bash
cat payload.json | curl -XPOST -d @- -H 'Content-Type: application/json' "$webhook_url"
echo $?                                                                                
cat payload.json | curl -sSfl -XPOST -d @- -H 'Content-Type: application/json' "$webhook_url" 
echo $?                                                                                      
```
In addition to reviewing …
> fix(ci): catch errors on sending to slack

- sensor/kubernetes/listener/resource_event_handler.go
The resync period of 0 was not being applied to routes and deployment configs so they were being resynced every minute. The change in routes was propagating to the deployments they referenced and causing far too many changes to deployments (e.g. what this PR was fixing: https://github.com/stackrox/stackrox/pull/7956) and causing extra stress on Sensor and detection. 
Will run on openshift cluster
> ROX-20181: Apply noResyncPeriod to Openshift resources

- sensor/kubernetes/listener/resources/hash_reconciliation.go
- sensor/kubernetes/listener/resources/hash_reconciliation_test.go
- sensor/kubernetes/listener/resources/serviceaccount_store.go
- sensor/kubernetes/listener/resources/store_provider.go
This PR adds the implementation for ReconcileDelete for the ServiceAccount Store.
As the SAS doesn't expose direct access to IDs, I have added a StringSet which tracks Add/Delete operations and is wiped on Clean.
As this code is currently not called by our production code, I rely on the added unit tests in hash_reconciliation_test.go.
In addition to reviewing code here, reviewers **must** also review testing and request …
> ROX-20057: Implement reconciliation in ServiceAccount Store

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
- ui/apps/platform/src/types/cve.proto.ts
Adds Observed/Deferred/FP Tabs to the Workload CVE list page and scopes queries of the data to the correct status.
Create and approve a deferral and false positive via the VM 1.0 UI.
View the Workload CVE page with feature flag off, filtered to the approved CVEs. This view shows _all_ instances of the CVEs, regardless of exception status.
Turn the feature flag on and view the same page. One CVE is absent (deferred across all affected images), the other CVE has a reduced affected images count.
Deferral tab:
FP tab:
> ROX-19459: Add CVE status tabs to workload CVE list page

- central/globaldb/v2backuprestore/manager/restore_process.go
- central/hash/manager/manager.go
- central/sensor/networkpolicies/controller_impl.go
- central/sensor/service/connection/manager_impl.go
- central/sensor/service/connection/sensorevents.go
- central/sensor/telemetry/controller_impl.go
- pkg/auth/authproviders/provider_impl.go
- pkg/concurrency/lock.go
- pkg/images/enricher/enricher_impl.go
- pkg/registries/docker/docker.go
- sensor/common/detector/deduper.go
- sensor/common/detector/detector.go
- sensor/kubernetes/listener/resources/node_store.go
Based [on a discussion within the style guide](https://github.com/stackrox/stackrox/pull/7282#discussion_r1290644635) regarding improving the usage of `WithLock/RLock` to allow multiple return values.
- see CI.
> chore(concurrency): add return values to WithLock/WithRLock

- ui/apps/platform/cypress/integration/administration/events/eventsTable.test.js
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventDescription.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventHint.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventHintMessage.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventPage.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsEmptyState.tsx
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsTable.css
- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsTable.tsx
- ui/apps/platform/src/services/AdministrationEventsService.ts
Thanks to Mansur for careful and constructive critique earlier this week. Haha, alliteration and rhyme.
1. Edit eventsTable.test.js file
* Update table column head text.
* Update description list type text.
2. Edit AdministrationEventDescription.tsx file.
* Replace **Created at** with **Created** and **Last updated at** with **Last updated**.
3. Add AdministrationEventHint.tsx file.
* Replace lines which have hyphen space prefix with bullet list items.
* Replace empty lines with `br` elements.
4. Edit AdministrationEventHintMessage.tsx file.
* Factor out hint as its own component.
5. Edit AdministrationEventPage.tsx file.
* Add divider between breadcrumbs and page heading.
* Merge page sections to decrease double padding via 24px spacer for `FlexItem` element.
6. Edit …
> ROX-20089: Make changes from design review of administration events

- ui/apps/platform/cypress/integration/configmanagement/dashboard.test.js
Configuration Management Dashboard should go to filtered policies list from link in Policy violations widget
> Timed out retrying after 4000ms: expected '?s[Severity]=CRITICAL_SEVERITY&s[Policy%20Status]=Fail' to include '[Disabled]=False'
This is related to the added policy HTTP/2 DDOS policy which has Critical severity.
1. configmanagement/dashboard.test.js
* `cy.location('search').should('contain', '[Disabled]=False');`
2. PolicyViolationsBySeverity.js
* Links for high medium low have `Disabled: 'False'` but for critical does not :(
* In theory, inconsistency is a bug, but it seems past expiry date to fix.
1. Delete this secondary assertion.
* configmanagement/dashboard.test.js
> fix(e2e): Delete assertion from PolicyViolationsBySeverity test

- migrator/version/version.go
Looks like there is a mistake in error wrap as message makes no sense and parameter is not used. …
> chore(db): Fix error wrap

- operator/tests/run.sh
- scripts/ci/lib.sh
The main operator test e2e run script contains several phases, each wrapped in a command which creates a JUnit report file in case of a failure. However a couple of those steps which use `kuttl` underneath themselves create separate, more fine-grained JUnit report files on *most* failures.
As a result, the junit2jira bot often creates duplicate bug reports - one with precise kuttl step failure information (titled [`central / basic-central FAILED`](https://issues.redhat.com/browse/ROX-20040?focusedId=23244250&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23244250) or [`securedcluster / basic-sc FAILED`](https://issues.redhat.com/browse/ROX-20065), and another one just mentioning the overal phase failure titled [`test-e2e / Run operator E2E tests. …
> ROX-20112: Prevent double-reporting `kuttl` errors.

- image/roxctl/rhtap.Dockerfile
I saw that enterprise contract started failing more after I set empty values on inherited labels.
Therefore, I set `version` to a dummy value.
`url` seems to be set to container page:
```
$ docker inspect registry.redhat.io/advanced-cluster-security/rhacs-main-rhel8:4.2.1 | grep -F '"url"'
"url": "https://access.redhat.com/containers/#/registry.access.redhat.com/rhacs-main-rhel8/images/4.2.1-3",
```
Funny, that the page does not work at the moment. I gave a link to RHACS in the software catalog instead, this is a parent level above images.
I also set `com.redhat.license_terms` to what our containers get during builds:
```
$ docker inspect registry.redhat.io/advanced-cluster-security/rhacs-main-rhel8:4.2.1 | grep -F 'com.redhat.license_terms'
"com.redhat.license_terms": …
```
> chore: Update labels again and set some value to version and url

- go.mod
- go.sum
Use the latest github.com/stackrox/helm-operator which has fixed label selector bug
Follow up for #7695 
```
CENTRAL_LABEL_SELECTOR="foo=bar" MAIN_IMAGE_TAG=4.2.1 make install run
3CENTRAL_LABEL_SELECTOR="foo=baz" MAIN_IMAGE_TAG=4.2.1 make install run
``` …
> ROX-20203: Bump helm operator plugin version

- pkg/grpc/endpoints.go
- pkg/grpc/server.go
Cherry-pick of https://github.com/stackrox/stackrox/pull/8124 into the `release-4.1` branch. …
> ROX-20122: set gRPC & http2 max concurrent streams to 100

- sensor/kubernetes/eventpipeline/output/output.go
- sensor/kubernetes/eventpipeline/output/output_impl.go
- sensor/kubernetes/eventpipeline/pipeline_impl.go
- sensor/kubernetes/eventpipeline/resolver/resolver.go
- sensor/kubernetes/eventpipeline/resolver/resolver_impl.go
- sensor/tests/connection/connection_test.go
Sensor has a race condition when closing channels when `.Stop()` is called in the `eventpipeline`. This PR makes sure that all goroutines are stopped on a signal, and leaves the channels unclosed. This isn't a problem in this case because the references to these structs will not be used anymore, and the [channels will garbage collected](https://groups.google.com/g/golang-nuts/c/pZwdYRGxCIk/m/rGr1D-uTQMEJ). 
Call `.Stop()` on integration test. 
> ROX-18285: Fix data race when calling .Stop() on sensor pipeline

- central/convert/storagetov2/user.go
- central/convert/storagetov2/vuln_exception_service.go
- central/convert/storagetov2/vuln_exception_service_test.go
- central/convert/storagetov2/vulnerability.go
- central/convert/testutils/vuln_exception.go
- central/convert/testutils/vuln_request.go
- central/convert/v2tostorage/user.go
- central/convert/v2tostorage/vuln_exception_service.go
- central/convert/v2tostorage/vuln_exception_service_test.go
- central/convert/v2tostorage/vulnerability.go
Message converters to convert `storage.Vulnerability` to `v2.VulnerabilityException` and vice-versa.
Unit Test
> ROX-20221: Message converters for v2 vulnerability exception service

- CHANGELOG.md
- pkg/env/reprocessing_interval.go
- scripts/ci/jobs/aks_qa_e2e_tests.py
- scripts/ci/jobs/aro_qa_e2e_tests.py
- scripts/ci/jobs/eks_qa_e2e_tests.py
- scripts/ci/jobs/gke_qa_e2e_tests.py
- scripts/ci/jobs/gke_race_condition_qa_e2e_tests.py
- scripts/ci/jobs/ibmcloudz_qa_e2e_tests.py
- scripts/ci/jobs/ocp_qa_e2e_tests.py
- scripts/ci/jobs/ocp_sensor_integration_tests.py
- scripts/ci/jobs/osd_aws_qa_e2e_tests.py
- scripts/ci/jobs/osd_gcp_qa_e2e_tests.py
- scripts/ci/jobs/powervs_qa_e2e_tests.py
- scripts/ci/jobs/rosa_qa_e2e_tests.py
- tests/e2e/lib.sh
There are several circumstances where risk reprocessing can be triggered rapidly:
- Flapping deployment changes
- Random process executions
- Lots of alert changes
This can lead to flapping risk calculations which are fairly expensive. A 10 minute debounce period minimizes the impact of these potential issues. This leads to a fairly reasonable cap for risk. Back of envelope math:
50,000 deployments with a 600 second debounce is a max of 83 risk reprocessings per second
CI (may need to tweak the env var for CI to finish quickly)
performed one does not seem sufficient. As a reviewer, you must not approve the change until you …
> fix(perf): Move risk reprocessing to debounce over a 10 minute period

- qa-tests-backend/src/test/groovy/SummaryTest.groovy
In many clusters, things are being created and deleted by controllers consistently. If we're within 2 objects, we should mark this as fine
e.g. sensor-upgrade gets created or catalog market pods are created on openshift
CI tests
>  ROX-20228: SummaryTest should be more lenient

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/cveListExceptionFlow.test.js
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/CveSelections.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/DeferralForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionScopeField.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/utils.ts
Adds the form within the modal for Workload CVE deferrals. This is only the components and layout for the form; state is not tracked and there is no validation.
Visit Workload CVEs and select the defer CVE option:
Visit exception config and change the values, ensuring that the changes are reflect on follow up visits to the deferral form:
> ROX-19358: Add a modal form for CVE deferral

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/DeferralForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionScopeField.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/utils.ts
- ui/apps/platform/src/services/ExceptionConfigService.ts
As titled. Builds on top of https://github.com/stackrox/stackrox/pull/8160
Load the deferral form and test that the different options can be tracked with formik state:
The date picker defaults to "tomorrow" and only allows selection of dates in the future:
Manually entering a date in the past invalidates the form:
Entering an invalid date string invalidates the form:
Blurring the comment field without entering a value invalidates the form:
> ROX-19358: Add formik validation and state tracking to deferral form

- pkg/grpc/endpoints.go
- pkg/grpc/server.go
Cherry-pick of https://github.com/stackrox/stackrox/pull/8124 into the `release-3.74` branch. …
> ROX-20121: set gRPC & http2 max concurrent streams to 100

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/CveSelections.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/DeferralForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionScopeField.tsx
- ui/apps/platform/src/hooks/useMap.test.ts
- ui/apps/platform/src/hooks/useMap.ts
Updates the CVE selection list to contain links to individual CVE pages as well as CVE descriptions.
The majority of the changes are due to the need to move from using a `Set` to track selected CVEs, to using a `Map`. This is because we also need to retain the CVE summary in state, and there is no way to make a custom comparator for objects contained in a Set. (Reference equality only).
Additionally, in order to better control layout the TabContent has been separated from being a direct child of a `Tab`. It is easier to review this with "Hide whitespace" on.
View the modal when deferring a single CVE:
View the modal when deferring multiple CVEs. The CVE list container should fill the remaining space and scroll:
Click a CVE link to verify …
> ROX-19358: Add CVE selection list to deferral form

- qa-tests-backend/src/main/groovy/common/Constants.groovy
- qa-tests-backend/src/test/groovy/SummaryTest.groovy
Ignore truncated annotations in summary test especially for nodes because the logic for annotation truncation is word oriented so it's not a blind length check. This leads to errors like
```
Test truncation:
'could not apply update: setting node's state to Done failed. Error: error setting node's state to Done: unable to update node "&Node{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []...'
Go truncation:
'could not apply update: setting node's state to Done failed. Error: error setting node's state to Done: unable to update node "&Node{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [][]},Spec:NodeSpec{PodCIDR:,DoNotUseExter...']
```
CI test + manual annotation of node to check …
> ROX-17927: Ignore truncated annotations in SummaryTest

- scanner/.gitignore
- scanner/Makefile
1. Adds a generic target to build everything in `cmd/`; 
2. Update image build to use the above.
| master
| ........ ⏫ **feat(scanner): Add make build #8017** :point_left: 
| ............ ⏫ feat(scanner): Add a client-side interface for Scanner #8019
| ................ ⏫ feat(scanner): Add initial E2E tests for Scanner #8064
| ................ ⏫ fix(sensor): Use Scanner V4 client in local scanning #8066
`make images`
> feat(scanner): Add `make build`

- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
This PR intends to add multi-arch support for the `ImageManagementTest` QA test.
Test code changes & images used in the test are update to enable test execution on 3 platforms viz. `x86_64`, `ppc64le` and `s390x`.
Few of the sub-tests skipped earlier on P/Z, have been re-enabled in this PR.
Changes are verified manually using `./gradlew test --tests=ImageManagementTest`
> ROX-16930: Re-enable skipped ImageManagementTest sub-tests on P/Z

- sensor/common/registry/registry_store.go
- sensor/common/registry/registry_store_test.go
- sensor/kubernetes/listener/resources/hash_reconciliation.go
- sensor/kubernetes/listener/resources/hash_reconciliation_test.go
- sensor/kubernetes/listener/resources/secrets.go
- sensor/kubernetes/listener/resources/store_provider.go
Allow registry stores to keep track of all secrets added and removed in the cluster. This is necessary to do the reconciliation between central and sensor when the connection breaks.
> ROX-20074: Registry store reconciliation

- pkg/env/sensor.go
- sensor/common/sensor/central_communication.go
- sensor/common/sensor/central_communication_impl.go
- sensor/common/sensor/central_communication_test.go
- sensor/common/sensor/sensor.go
We now timeout if the `DeduperState` is not received after a while. Timing-out falls back into the old behavior, so central will do the reconciliation in the next retry.
Depends on:
* #8084 (for the unit tests refactors)
* Deploy ACS and scale sensor to 0
* Use local-sensor with a modify timeout of 10 nanoseconds
* See sensor timing out waiting for the deduper state and then reconnecting with `reconciliation = false`: …
> ROX-19670: add timeout when waiting for the DeduperState

- sensor/kubernetes/listener/resources/hash_reconciliation.go
- sensor/kubernetes/listener/resources/hash_reconciliation_test.go
- sensor/kubernetes/listener/resources/networkpolicy_store.go
- sensor/kubernetes/listener/resources/store_provider.go
This PR adds the implementation for ReconcileDelete for the NetworkPolicy Store.
Central only requires the ID of a NetworkPolicy to delete a given resource ([here](https://github.com/stackrox/stackrox/blob/ef44f9f9ec950fa18c7bee4bd8200d9067b8fe9b/central/sensor/service/pipeline/networkpolicies/pipeline.go#L153C1-L154)).
As this code is currently not called by our production code, I rely on the added unit tests in …
> ROX-20073: Implement Network Policy Store Reconciliation

- sensor/kubernetes/listener/resources/service_store.go
Since Central does not track services or routes, the service store does not need to be reconcile.
There is no need to validate anything. This PR only removes an unused function.  …
> ROX-19669: remove ReconcileDelete from the service store

- pkg/sync/mutex_dev.go
The watchdog is the cause of many CI flakes. A timeout of 10s should stabilize things and if we hit 10s then something is seriously wrong that needs to be debugged
Trivial
> fix(test): Increase mutex watchdog to 10s to increase CI stability

- central/detection/alertmanager/alert_manager_impl_test.go
- central/detection/alertmanager/filter_options.go
- central/detection/lifecycle/manager_impl.go
- central/detection/lifecycle/manager_impl_test.go
Scope the merging for resource requests
```
New PR:
central_active=# select total_exec_time, mean_exec_time, rows, calls, rows/calls as avg, query from pg_stat_statements where query ilike 'select%alerts%' order by calls desc limit 20;
total_exec_time    |    mean_exec_time    | rows  | calls | avg |                                                                                                                         query                                                                       
----------------------+----------------------+-------+-------+-----+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> ROX-20136: Reduce cost of resource alert processing

- CHANGELOG.md
- central/main.go
- pkg/env/rate_limit.go
- pkg/grpc/ratelimit/ratelimit.go
- pkg/grpc/ratelimit/ratelimit_impl.go
- pkg/grpc/ratelimit/ratelimit_impl_test.go
- pkg/grpc/server.go
- pkg/grpc/server_ratelimit_test.go
- pkg/grpc/server_test.go
This PR adds an API rate limiter for HTTP, gRPC, and Stream requests.
The current solution will reject requests if the rate limit is reached.
The following changes are made:
- Added env variable to set rate limit (check CHANGELOG)
- By default, we will not limit requests, and for a negative rate limit, the app will panic
- Add RateLimiter to `grpc` package
- interface has two functions that are not used (relevant to follow-up PR)
- implementation uses a simple token bucket rate limit method (comment for NewRateLimiter)
- gRPC server has tests for HTTP and gRPC interceptors and missing rate limiter
**Benchmark**
Introduced `Limit` function used for rate limit adds ~180 ns/call.
```
BenchmarkNoLimit-12           	 8358933	       142.9 ns/op
BenchmarkWithLimitHit-12      	 6711018 …
```
> ROX-19561: Add API rate limit for gRPC, HTTP and Stream requests

- scripts/release-tools/lib.sh
- scripts/release-tools/setup-central-access.sh
In Bash on macOS, there isn't a built-in readarray command like there is in Bash versions 4.0 and above. 
The input from kubectl+jq is space delimited, therefore we can use `IFS` and `read` to load the values into an array. 
```
$ ./scripts/release-tools/setup-central-access.sh long-fake-load-4.2.2-rc.1
To use the downloaded kubeconfig, run:
export …
```
> ROX-19105: fix release cluster access script for Mac users

- scripts/ci/jobs/aks_qa_e2e_tests.py
- scripts/ci/jobs/aro_qa_e2e_tests.py
- scripts/ci/jobs/eks_qa_e2e_tests.py
- scripts/ci/jobs/gke_qa_e2e_tests.py
- scripts/ci/jobs/gke_race_condition_qa_e2e_tests.py
- scripts/ci/jobs/ibmcloudz_qa_e2e_tests.py
- scripts/ci/jobs/ocp_qa_e2e_tests.py
- scripts/ci/jobs/ocp_sensor_integration_tests.py
- scripts/ci/jobs/osd_aws_qa_e2e_tests.py
- scripts/ci/jobs/osd_gcp_qa_e2e_tests.py
- scripts/ci/jobs/powervs_qa_e2e_tests.py
- scripts/ci/jobs/rosa_qa_e2e_tests.py
- sensor/common/sensor/sensor.go
I believe that this test fails because Sensor doesn't restart anymore so what happens is that it retries too quickly and gets too large of a backoff due to that and then never retries before the test gives us. Therefore, shorten the max amount of time on the Sensor retries for testing purposes:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-merge-gke-qa-e2e-tests/1714777933635129344/artifacts/merge-gke-qa-e2e-tests/stackrox-e2e/artifacts/spec-logs/TLSChallengeTest.log
CI?
performed one does not seem sufficient. As a reviewer, you must not approve the change until …
> ROX-20242: Fix timing of TLS challenge test

- central/clusterinit/backend/backend_impl.go
- central/clusterinit/backend/backend_test.go
Add clusterid context to logs. We are trying to debug something and the logs are too generic
Trivial
> chore(log): Add more context to clusterinit bundle errors

- central/main.go
[##](url) Description
This change disables v1 reporting api based on vuln reporting 2.0 feature flag
Tested with v1 reporting endpoints. Endpoint returns Not found
> Disbale v1 reporting api in 4.3

- ui/apps/platform/src/Containers/SystemHealth/DashboardPage.js
Follow up #7435
To avoid merge conflicts close to 4.2 release, we waited to add conditional rendering.
Both `ShowAdministrationUsage` and `GenerateDiagnosticBundle` encapsulate requests which require READ_ACCESS for Administration resource.
Lift up conditional rendering to include both buttons.
1. Visit /main/system-health
* With READ_ACCESS for Administration resource.
* With NO_ACCESS for Administration resource (temporarily edit code to simulate).
See absence of buttons and also **Vulnerability definitions** card.
* systemHealth/bundle.test.js
* systemHealth/systemHealthGeneral.test.js
> ROX-20316: Add conditional RBAC for ShowAdministrationUsage

- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventHintMessage.tsx
Somehow it escaped my attention until now that message has sans-serif font instead of monospace font that is conventional for code.
For code rendered inside the code block: `CodeBlockCode` element.
https://www.patternfly.org/components/code-block#codeblockcode
1. Visit /main/administration-events
* Without `CodeBlockCode` element, see sans-serif font.
* With `CodeBlockCode` element, see monospace font.
2. Click a link to visit administration event page.
* With `CodeBlockCode` element, see monospace font.
> ROX-20317: Add CodeBlockCode for administration event message

- central/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go
Seems like this test has been disabled for quite some time now. I am enabling a portion of the test which is not excepted to be flaky but let's see. Eventually, the full test will be enabled.
> chore: Enable portion of "TestVulnRequestManager"

- tests/e2e/run-scale.sh
The nightly store did not get the update to the bucket name.
Only stores in nightlies.
> fix(ci): use correct name for nightly comparison bucket

- central/processbaseline/evaluator/evaluator_impl.go
- central/processbaseline/evaluator/evaluator_test.go
When processing only unlocked baselines, there is no chance that a process is anomalous so avoid fetching from the DB.
Scale test results:
```
sensor_event_duration | Action=UNSET_ACTION_RESOURCE Type=ReprocessDeployment | (68797.62/3982) 17.28 | (57946.85/4013) 14.44 | -16.4227%
```
e2e tests should check that risk still performs properly, but scale testing will tell us the most
> fix(perf): Only load processes if there is a locked baseline

- ui/apps/platform/cypress/fixtures/auth/mypermissionsForAnalyst.json
- ui/apps/platform/cypress/helpers/main.js
- ui/apps/platform/cypress/integration/dashboard/dashboardSummaryCounts.test.js
- ui/apps/platform/src/Containers/Dashboard/DashboardPage.tsx
- ui/apps/platform/src/Containers/Dashboard/SummaryCount.tsx
- ui/apps/platform/src/Containers/Dashboard/SummaryCounts.tsx
Follow up #7381
To prevent **There was an error loading system summary counts** in summary counts bar of main dashboard, the initial conditional rendering was all or nothing.
1. Edit DashboardPage.tsx file.
* Replace `&&` with `||` in conditional rendering.
* Add `hasReadAccessForResource` prop to `SummaryCounts` element.
2. Add SummaryCount.tsx file.
3. Edit SummaryCounts.tsx file.
* Based on review question, I refactored with resources as keys and rendered nouns via `tileNouns` object.
* Conditionally include in query only properties for which user role has permission.
* Conditionally render counts.
main.js: 0 = 3910905 - 3910905
total: 126 = 10177590 - 10177464
* …
> ROX-20279: Minimize resource requirements for SummaryCounts

- ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
Follow up #7909
After we reduced resource access requirements for Network Graph:
1. If user role does not have DeploymentExtension resource:
* **Baseline** tab of deployment side panel makes request that has 403 Forbidden status.
GET /v1/networkbaseline/id
2. If user role does not have NetworkPolicy resource:
* For **Network policies** tab, deployment side panel makes request that has 403 Forbidden status.
GET /v1/networkpolicies/id
* Click **Network policy generator** makes request that has 403 Forbidden status.
GET /v1/networkpolicies?clusterId=id&deploymentQuery=Cluster%3Aname%2BNamespace%3Aname
1. DeploymentExtension
* DeploymentSideBar.tsx file renders tabs and DeploymentBaseline.tsx file encapsulates request.
* It selects **Baseline** tab and disables other tabs if baseline …
> ROX-20243: Add conditional RBAC to tab and button for NetworkPolicy

- sensor/common/component.go
- sensor/common/reconciliation/component.go
- sensor/common/sensor/central_communication.go
- sensor/common/sensor/central_communication_impl.go
- sensor/common/sensor/central_communication_test.go
- sensor/common/sensor/central_sender.go
- sensor/common/sensor/central_sender_impl.go
- sensor/common/sensor/sensor.go
- sensor/common/store/mocks/types.go
- sensor/common/store/types.go
- sensor/kubernetes/sensor/sensor.go
This component is responsible for making sure that the deduper state is passed to `hash_reconciler` and that sensor messages are produced and emitted to central. 
> ROX-20291: Sensor reconciler component

- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- pkg/env/notifier_secret_encryption.go
We've used different feature flag names in the helm/operator changes compared to the central changes for the encryption notifier secrets feature.
This PR changes that to use what's defined in helm/operator.
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change …
> ROX-16669: change enc notifier feature flag to match operator

- ui/apps/platform/cypress/integration/administration/events/AdministrationEvents.helpers.js
- ui/apps/platform/cypress/integration/administration/events/eventsTable.test.js
Balancing cost and benefit, add tests for filter now but defer tests for sort by **Last updated** and **Count** until later.
Inspected each test in Cypress console.
* administration/events/eventsTable.test.js
> ROX-20322: Increase test coverage for administration events

- central/main.go
It's only started if the flag is off, so stopping will fail
Manually. Deployed with feature flag on, and killed central. It stopped only v2 service and it terminated in an appropriate amount of time. Deployed with it off, and repeated test. It only stopped v1 service and also terminated in an appropriate amount of time.
In addition to reviewing code here, reviewers **must** also …
> fix(bug): Stop V1 reports service only if flag is off

- operator/hack/common.sh
This `patch` often races with default service account creation. But judging from the comment, it's obsolete altogether.
Let's try just dropping it.
> ROX-20046: Stop patching service account.

- sensor/kubernetes/listener/resources/dispatcher.go
- sensor/kubernetes/listener/resources/hash_reconciliation.go
- sensor/kubernetes/listener/resources/hash_reconciliation_test.go
- sensor/kubernetes/listener/resources/namespace.go
- sensor/kubernetes/listener/resources/namespace_store.go
- sensor/kubernetes/listener/resources/store_provider.go
If sensor is capable of doing the reconciliation, it should be doing namespace reconciliation as well.
* Deploy ACS in a cluster with `ROX_SENSOR_RECONCILIATION=true`
* Create a few namespaces
* You should see the namespaces in the UI
* Scale sensor to zero
* Delete a few namespaces
* Scale sensor to one again
* You should see the deleted namespaces disappear in the UI  …
> ROX-20345: Reconcile namespaces in sensor

- tests/e2e/run-scale.sh
One more case of using the wrong GCP project. Will it be the last?
Commented out `is_nightly_run()` to exercise the store portion of this job.
> fix(CI): fix (and test) gke-scale-tests

- sensor/common/sensor/sensor.go
- sensor/tests/connection/connection_test.go
- sensor/tests/helper/helper.go
Depends on #8120 
This PR is a long overdue follow-up from #6602. Which introduced the possibility of stopping gRPC connections. 
Sensor integration tests were not able to be written in the same file. This PR introduces a change to sensor `Stop()` function that allows a single test to have many sensor runtimes due to properly stopping the listeners. 
Created a second `SensorHello` test just to prove that this works. 
> ROX-20119: Properly stop gRPC in tests

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/CompletedExceptionRequestModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestModal.tsx
- ui/apps/platform/src/services/VulnerabilityExceptionService.ts
Adds the response details to a follow up modal when a deferral request has successfully been submitted.
- The scope `registry` and `remote` are hard coded again in this example until the API supports wildcard/global values.
- The `createdAt` timestamp returning from the API is currently `null`, which is why the date appears incorrect.
- We need to replace the provided link once that page is implemented
Open deferral for Workload CVEs:
Upon success, a new modal is presented with details of the submitted request:
Note that the "Requested" field above is incorrect because the API is currently returning `null`.
> ROX-19367: Add modal for a deferral request success

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExpiryField.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/utils.ts
Updates the `DeferralForm` component to be more generic in order to support both Deferrals and False Positives without a lot of duplicate code. As a bonus, this only makes a request to the exception config endpoint when the request type is a deferral, since it isn't needed for false positives.
1. Extract the exception config request and "Expiry" fields into a new component
2. Conditionally render the ExpiryField component only when the request is a deferral request
3. Pass some text strings in as props instead of hard coding in the form
Repeat testing steps from previous deferral exception form flows in preceding PR.
> chore(ui): Refactor DeferralForm for more general use

- sensor/kubernetes/fake/deployment.go
- sensor/kubernetes/fake/flows.go
Fixes a bug in the scale tests that makes it so that the sizes of the process and listening endpoint pools are not calculated correctly. Currently when these pools hit their maximum capacity and elements are deleted from them the recorded size of the pools are not decreased. This in turn means that new elements cannot be added, even though it should be possible to do so. …
> fix: bug in scale test process and endpoint removal

- sensor/common/store/reconciliation/store.go
- sensor/common/store/reconciliation/store_test.go
- sensor/kubernetes/listener/resources/complianceoperator/dispatchers/complianceoperatorprofiles.go
- sensor/kubernetes/listener/resources/complianceoperator/dispatchers/complianceoperatorresults.go
- sensor/kubernetes/listener/resources/complianceoperator/dispatchers/complianceoperatorrules.go
- sensor/kubernetes/listener/resources/complianceoperator/dispatchers/complianceoperatorscans.go
- sensor/kubernetes/listener/resources/complianceoperator/dispatchers/complianceoperatorscansettingbindings.go
- sensor/kubernetes/listener/resources/complianceoperator/dispatchers/complianceoperatortailoredprofiles.go
- sensor/kubernetes/listener/resources/dispatcher.go
- sensor/kubernetes/listener/resources/hash_reconciliation.go
- sensor/kubernetes/listener/resources/hash_reconciliation_test.go
- sensor/kubernetes/listener/resources/store_provider.go
- sensor/kubernetes/listener/resources/store_provider_test.go
Sensor was not tracking `compliance operator` resources. This PR aims to introduce a new store to track these resources and upon connection with Central, Sensor will do the reconciliation of these resources.
* In an OCP cluster, install the [compliance-operator](https://docs.openshift.com/acs/operating/manage-compliance-operator/compliance-operator-rhacs.html)
* Deploy ACS
* Perform an scan with ACS: Compliance -> Scan …
> ROX-20352: Reconcile ocp resources

- central/sensor/service/connection/connection_impl.go
- central/sensor/telemetry/controller.go
- central/sensor/telemetry/controller_impl.go
Should cancel when `ctx` is done.
> fix: ctx handling in ProcessTelemetryDataResponse

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/utils.ts
- ui/apps/platform/src/services/VulnerabilityExceptionService.ts
As titled.
Select one or more workload CVEs and "Mark as false positive" from the menu.
> ROX-19363: Add false positive CVE modal to workload cves

- ui/apps/platform/src/Containers/Administration/Events/AdministrationEventsToolbar.tsx
Change request from Mansur to separate toolbar filters similar to Workload CVEs:
Although PatternFly guidelines have one `ToolbarGroup` elements for multiple search filter items:
https://www.patternfly.org/components/toolbar/design-guidelines#filter-group
One group per item is a way to separate items visually:
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx#L87-L90
1. Visit /main/administration-events
* Original without spacing between search filter items
* Improved with spacing between search filter items
* administration/events/eventsTable.test.js
> ROX-20394: Separate administration events filters

- ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx
Related to access control because conditional rendering of separator depends whether links have enabled routes.
1. Generalize child items.
* Replace `ChildDescription` and `type: 'child'` with `LinkDescription` type and `type: 'link'` prop.
* Add `SeparatorDescription` type and `type: 'separator'` prop.
2. Filter second-level children.
* Factor out `isChildLinkEnabled` callback function.
* Add `isChildSeparatorRelevant` callback function.
| link                    | featureFlagRequirements              |
| :---                    | :---                                 |
| Workload CVEs           | ROX_VULN_MGMT_WORKLOAD_CVES          |
| Exception Management    | ROX_VULN_MGMT_UNIFIED_CVE_DEFERRAL   |
| Vulnerability Reporting | ROX_VULN_MGMT_REPORTING_ENHANCEMENTS |
1. Visit …
> ROX-20351: Add separator as a type of child in NavigationSidebar

- ui/apps/platform/src/Containers/NetworkGraph/deployment/DeploymentSideBar.tsx
Follow up #7909
After we reduced resource access requirements for Network Graph:
* If user role does not have DeploymentExtension resource:
* **Baseline** tab of deployment side panel makes request that has 403 Forbidden status.
GET /v1/networkbaseline/id
DeploymentExtension
* DeploymentSideBar.tsx file renders tabs and DeploymentBaseline.tsx file encapsulates request.
* It selects **Baseline** tab and disables other tabs if baseline simulation mode is on.
* However, BaselineSimulationButton is an orphan component. So, apparent deadlock in rendering is double theoretical.
Add conditional rendering.
main.js: 0 = 3911320 - 3911320
total: 30 = 10187138 - 10187108
* `ls …
> ROX-20356: Add conditional RBAC for Baseline tab in Network Graph

- CHANGELOG.md
- central/audit/audit.go
- central/audit/audit_test.go
- pkg/env/audit.go
This PR introduces `ROX_AUDIT_LOG_WITHOUT_PERMISSIONS` to conditionally remove resolved permissions for audit log messages to reduced the amount of information exposed within audit log messages.
This isn't recommended in all cases, since it may make investigation harder when wanting to figure out the current permissions for a requester at a specific point. Setting this environment variable will mean
the user has to check the associated role's permission set at the point of the request to get the permissions associated with the role.
The reason we decided to introduce this variable was:
a) on a user request.
b) requiring the user to look up the _exact_ permissions is _anyways_ required, since access scopes are currently not added in the audit log message and are required to get a full …
> ROX-20288: Audit log without permissions

- central/risk/manager/manager.go
Image and component risk factors are not actually used currently so only insert the values if the score has changed, which will reduce the number of writes on the database
Scale test + comparison of QA metrics
Before 
cat stackrox_debug_2023_10_24_06_48_08/metrics-1 | grep postgres_op_duration_count | grep Risk
rox_central_postgres_op_duration_count{Operation="Get",Type="Risk"} 21616
rox_central_postgres_op_duration_count{Operation="Remove",Type="Risk"} 3842
rox_central_postgres_op_duration_count{Operation="Upsert",Type="Risk"} 10811
After:
cat stackrox_debug_2023_10_24_17_43_27/metrics-1 | grep postgres_op_duration_count | grep Risk
rox_central_postgres_op_duration_count{Operation="Get",Type="Risk"} 21136 …
> fix(perf): Dedupe component risk upserts

- central/processlisteningonport/datastore/datastore_impl.go
Previously cases in which central received a message for a closed listening endpoint for which there was no existing open record were logged. However, now that listening endpoints are deleted when pods are deleted, this is a common occurrence and does not need to be logged.
This just removes one logging statement.
This just removes one logging statement.
> fix: remove logging of closed nonexistent plops

- scripts/ci/jobs/gke_upgrade_tests.py
Not sure whether this will be sufficient to overcome all timeouts, but it's certainly necessary for reasonable performance of scanner-db init-db. This is inspired by #8255
See the PR mentioned above for a general overview - I didn't look at this specific test, but I assume the cause is the same.
Overall, CI should be sufficient.
> ROX-20102: Use a disk with a more decent performance.

- pkg/features/list.go
With the release of 4.3, the feature flag should be enabled by default.
N/A
> chore(admin-events): enable feature flag by default

- .github/workflows/repo2cpe-download.yaml
The decision to compress two json files into one is because we want make it easier for central to pull data from google bucket.
After this change, we can avoid loop call in central and potential data lost caused by rate limiting and http request failures
> ROX-19004: Compress Repo Mapping JSON files for Easier Communication

- scripts/ci/gke.sh
It took scanner-db 17 minutes to start on upgrade tests and it has been failing repeatedly. Boost the disk type and size for all instances. The overall price should be fairly low as these disks are not long lived
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment …
> fix(test): Boost disk performance in CI tests

- central/vulnerabilityrequest/utils/util.go
If we want to match all tags, then just skip adding a regex match all tags query.
> chore: remove unnecessary query

- central/debug/service/service.go
- pkg/postgres/stats/stats.go
Adds the 1000 most expensive queries in terms of exec time to the diagnostic and debug bundles. This will allow us to see where postgres is spending time and what we could optimize. The pg stat statement object is just what i think is useful for now but more data may be necessary in the future. I also limited the number of queries to 1k and the size of the query to 1k so approximate max bound should be around 1MB
Get diag and debug and see data in there
> chore(debug): Add pg_stat_statements to debug and diagnostic bundles

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.test.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx
Added some tests for edge cases involving the following functions:
1. `getDeferralExpiryToUse`
2. `getRequestedAction`
Referencing functions made in https://github.com/stackrox/stackrox/pull/8322
> test(ui): Adding tests for expiry-related functions

- central/sac/authorizer/builtin_scoped_authorizer.go
- pkg/cache/objectarraycache/objectarraycache.go
- pkg/cache/shallowobjectarraycache/shallowobjectarraycache.go
Some customers with large setups are facing OOM Kills with Central. One big contributor to the memory allocations are clusters and namespaces.
The changes here aim at limiting the amount of data pulled when enriching the request context for later SAC checks.
This change is impacting any service call that is performed by a user whose identity has a restricted scope. …
> ROX-20439: Cache clusters and namespaces used for SAC checks

- scanner/.gitignore
- scanner/README.md
- scanner/cmd/scannerctl/main.go
- scanner/config.yaml.sample
These changes allow the option for TLS verification for self-signed certs, which complements the changes from https://github.com/stackrox/stackrox/pull/7939.
- Investigated and inspected CI test results (N/A)
- Unit test and regression tests added (N/A?)
- Evaluated and added CHANGELOG entry if required (N/A)
- [Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs)) (N/A)
This is a local development change so many of the items on the checklist are not applicable.
Here's my local config file (some values redacted):
```sh
❯ cat config.yaml
indexer:
database:
conn_string: ...
matcher:
database:
conn_string: ...
mtls:
certs_dir: …
```
> chore(scanner): add scannerctl grpc option flags

- ui/apps/platform/cypress/integration/main/HelpMenu.test.js
Help menu API Reference UI test started failing after merging PR #8305 
CI is enough
performed one does not seem sufficient. As a reviewer, you …
> ci: Fix "Help menu API Reference" UI test

- ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviders.tsx
- ui/apps/platform/src/Containers/MainPage/Header/UserMenu.tsx
- ui/apps/platform/src/Containers/MainPage/InviteUsers/InviteUsersModal.tsx
- ui/apps/platform/src/hooks/useAnalytics.ts
I realized this would be handy data to have as soon as possible
I tested this manually by 
1. Adding the dev telemetry key to a development environment, to turn on analytics tracking for that environment
2. Creating an auth provider
3. Opening the Invite Users modal (1 event)
4. Inviting a user (1 different event)
5. Observed events in Amplitude
> chore(analytics): Add event analytics to Invite Users feature

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesForm.tsx
- ui/apps/platform/src/hooks/useAnalytics.ts
Adds tracking to watched images events.
"Inspired" (stolen) from Van's testing steps:
1. Adding the dev telemetry key to a development environment, to turn on analytics tracking for that environment
2. Creating an auth provider
3. Open the watched image modal from the "Manage watch images" button as well as the table row menu (2 events)
4. Watch a single image (1 event)
5. Observed events in Amplitude
> chore(ui): Add analytics events for watched images

- ui/apps/platform/src/Containers/Clusters/Components/ClusterStatus.tsx
At some point, a change in either the UI or API opened up a situation where the cluster health object is completely undefined when displaying the status of a cluster that was just created through the legacy UI form.
The cluster entry is still created in the database, and the artifacts necessary to install the Secure Cluster Services are still available for download, but the user would only see the download option after refreshing the page.
This change fixes the confusing UX of that situation, by detecting when that cluster health object is undefined and defaulting to displaying a status of UNAVAILABLE, which is technically accurate. 
Misleading "error" state displayed, after a user has clicked "Next" on the UI cluster form to add a cluster entry to the database and generate its artifacts. …
> ROX-20477: Fix confusing warning in legacy cluster creation UI

- sensor/kubernetes/listener/resource_event_handler.go
- sensor/kubernetes/listener/resources/store_provider_test.go
If we stop Sensor while the k8s handlers are being initialize (`handleAllEvents` is still running), we can panic while trying to add a new handler [here](https://github.com/stackrox/stackrox/blob/4a7152b37ccdda2f670247dc19172db4dbaadce2/sensor/kubernetes/listener/resource_event_handler.go#L322). This PR solves this by introducing a new function that check whether the listener was stopped or not before calling `utils.Should`. 
* **Note**: This was only affecting development builds. …
> fix(sensor-startup): Do not panic if listener was stopped by Sensor

- pkg/features/list.go
- sensor/common/store/deployment_dependency.go
- sensor/common/store/mocks/types.go
- sensor/common/store/types.go
- sensor/kubernetes/eventpipeline/resolver/resolver_impl.go
- sensor/kubernetes/eventpipeline/resolver/resolver_test.go
- sensor/kubernetes/listener/resources/convert.go
- sensor/kubernetes/listener/resources/convert_mutating_test.go
- sensor/kubernetes/listener/resources/convert_override_test.go
- sensor/kubernetes/listener/resources/convert_test.go
- sensor/kubernetes/listener/resources/deployment_store.go
- sensor/kubernetes/listener/resources/deployment_store_bench_test.go
- sensor/kubernetes/listener/resources/deployment_store_test.go
- sensor/kubernetes/listener/resources/deployments.go
Rather than deduping entire deployments at the detector level, this proposal is to generated hashes out of the `store.Dependencies` object that is used to enrich the deployment spec into a `storage.Deployment`. If neither the deployment spec nor the 
dependencies changed, there is no reason to process a deployment further. 
**Overview**
On a deploy-time path (i.e. Kubernetes events) the only reasons to process a deployment on an `UPDATE` (send a `SensorEvent_Resource` message to central and check violations) is when either of these two happen:
1. The deployment spec changed
2. Some adjacent resource changed (e.g. RBAC or Route)
Whenever a deployment event is received, we store the spec in deployment store as `built=false`. Meaning that the present deployment is yet to be resolved against …
> ROX-20328: Dedupe deployment dependencies

- .openshift-ci/clusters.py
- operator/tests/central/basic-central/10-central-cr.yaml
- operator/tests/common/central-cr.yaml
- scripts/ci/gke.sh
- scripts/ci/jobs/gke_operator_e2e_tests.py
- scripts/ci/jobs/gke_upgrade_tests.py
Because:
* Turns out the shot in the dark that https://github.com/stackrox/stackrox/pull/8072 was, was not sufficient.
* While this PR was in flight, https://github.com/stackrox/stackrox/pull/8340 changed disks to SSD which have a different performance characteristics (see ticket)
This PR now:
- no longer adjusts disk size since it is pointless with SSDs
- bumps scanner-db CPU from default 200m to 400m, which ~doubles `init-db` speed
- bumps scanner-db memory request from 200MiB at which it might OOM to apparently safe 512MiB
- reverts https://github.com/stackrox/stackrox/pull/8256 that is now unnecessary
- fix disk_gb parameter passing that was missed in  https://github.com/stackrox/stackrox/pull/8072 (causing that PR to be a no-op) and restore default disk size now that it is SSD
More …
> ROX-20065: Improve scanner(-db) performance in operator e2e test.

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.test.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/CompletedExceptionRequestModal.tsx
- ui/apps/platform/src/services/VulnerabilityExceptionService.ts
Updates UI expected response types to match BE type refactor in https://github.com/stackrox/stackrox/pull/8333
Repeat testing steps for submitting a deferral or false positive requests from previous PRs.
> fix(ui): Sync FE and BE types for exception requests

- ui/apps/platform/src/services/NetworkService.js
- ui/apps/platform/src/utils/searchUtils.test.js
- ui/apps/platform/src/utils/searchUtils.ts
When the other namespaces' names start with the same name as a filtered namespace, both the filtered NS chosen and the other similar named NS show up in the Network Graph.
@Maddosaurus  from the Maple team confirmed that the Network Graph API accepts the characters `r/` at the beginning of a search string, which causes the remainder of that string to be treated as a regex.
FE-only solution:
Immediately before sending the namespace and deployment parameters for the network graph calls, iterate over the arrays of namespaces and deployments selected by the user, and map them to new values in the form `r/^{value}%`. This makes them behave as exact-match regexes.
1. Added unit tests for the new function to make all Namespaces and Deployments chosen in the NG selector bar be exact matches
2. …
> ROX-19512: Limit Network Graph scope selectors to exact matches

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionScopeField.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/VulnerabilityStateTabs.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useVulnerabilityState.ts
Splits all sections in Workload CVEs by CVE vulnerability state via tabs.
When viewing a deferred/FP tab, links to other pages do not persist the vulnerability state. e.g. Viewing deferred CVEs, then clicking a CVE name takes you to the _Observed (Workload)_ tab for that single CVE.
Create and approve a deferral and false positive via the VM 1.0 flow:
Verify that CVEs that have an exception for only _some_ images are still visible on the Observed tab:
Verify that CVEs that have an exception for _all_ images are not visible on the Observed tab:
Verify Deferrals:
Verify False Positives:
CVE Single page for a fully deferred CVE:
CVE Single page for a partially FP'd CVE:
Image single page for an image with an approved deferral:
Image single …
> ROX-19401: Add vuln state tabs to workload cve detail pages

- central/vulnerabilityrequest/datastore/datastore.go
- central/vulnerabilityrequest/datastore/datastore_impl.go
- central/vulnerabilityrequest/datastore/datastore_impl_test.go
- central/vulnerabilityrequest/utils/util.go
- central/vulnerabilityrequest/utils/util_test.go
- generated/api/v2/vuln_exception_service.pb.go
- proto/api/v2/vuln_exception_service.proto
- ROX-20493: Prohibit changing a deferral vuln exception to false-positive and vice-versa. The updated function `UpdateRequest` is protected by the feature flag and is used by v2 APIs only.
- ROX-20494: Only allow deleting vulnerability exceptions or updates in pending state.
- ROX-20495: Prohibit updates that do not change exceptions. Updates go through the approval process, so the updates that do not change the original exception can be annoying for admin, so prohibit such updates.
Unit test
> ROX-20493, ROX-20494, ROX-20495: Miscellaneous vulnerability exception validations

- central/cve/image/service/service_impl.go
- qa-tests-backend/src/test/groovy/AdmissionControllerTest.groovy
- qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
The legacy vulnerability snooze APIs are moved behind the feature flag. If the unified deferral feature is enabled, the APIs will not be available for use. The deprecation notice was released in 4.1. The final removal notice will be released in 4.4.
> ROX-19293: Feature flag legacy image vulnerability snooze APIs

- CHANGELOG.md
- ui/apps/platform/cypress/integration/compliance/Compliance.helpers.js
- ui/apps/platform/cypress/integration/compliance/complianceDashboard.test.js
- ui/apps/platform/cypress/integration/compliance/hideScanResults.test.js
- ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx
- ui/apps/platform/src/Containers/Compliance/widgets/ComplianceByStandards.tsx
The removal of these sunburst widgets for the individual compliance standards was announced in the 4.2 release notes.
> - Red Hat will remove the following widgets from the Compliance dashboard in RHACS 4.4:
>   - CIS Docker v1.2.0 Compliance
>   - PCI DSS 3.2.1 Compliance
>   - CIS Kubernetes v1.5 Compliance
>   - NIST SP 800-53 Compliance
>   - NIST SP 800-190 Compliance
>   - HIPAA 164 Compliance
https://docs.openshift.com/acs/4.2/release_notes/42-release-notes.html#notice-for-upcoming-changes
1. Removed the checks for both the rendered components in the UI, and the waits on API calls that are now no longer made, from the ui-e2e-tests
2. Visually verified that the widgets were there before the change, and are no longer there after the change.
(note: I had to add margin to the …
> ROX-18840: Remove sunburst widgets from Compliance dashboard

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/FilterAutocomplete.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/SearchOptionsDropdown.tsx
This PR takes the `FilterAutocomplete` and `FilterResourceDropdown` Components and re-purposes them for the Exception Management section. To not break anything, I decided to create a copy of the Components (renamed to `FilterAutocomplete` and `SearchOptionsDropdown`). The `SearchOptionsDropdown` was made more generic to be reused for other cases. The `FilterAutocomplete` was slightly modified as well to make it easier to reuse. 
Note: I plan to revisit and refactor the two components to incorporate the new ones in an upcoming PR.
> ROX-19420: Adding search filters for pending requests

- operator/tests/upgrade/upgrade/20-upgrade-operator.yaml
When upgrade fails, the message emitted to the JUnit summary file is something along the lines of:
```
command "" exceeded 72 sec timeout, context deadline exceeded
```
Root cause is a `kuttl` [bug](https://github.com/kudobuilder/kuttl/issues/493) where - when creating an error message - only looks at the `command` field of a command object (which in this case is empty) rather than at the `script` field if it's not empty. I will address this bug upstream [separately](https://github.com/kudobuilder/kuttl/pull/494), but here we can work it around by using the `command` field, since there is nothing shell-dependent in this command so it does not need to use `script`.
In addition to reviewing code here, reviewers **must** …
> ROX-17898: Work around useless error message.

- sensor/kubernetes/eventpipeline/pipeline.go
- sensor/kubernetes/listener/listener.go
- sensor/kubernetes/listener/listener_impl.go
- sensor/kubernetes/listener/resources/dispatcher.go
- sensor/kubernetes/listener/resources/hash_reconciliation.go
- sensor/kubernetes/listener/resources/hash_reconciliation_test.go
- sensor/kubernetes/listener/resources/store_provider.go
- sensor/kubernetes/listener/resources/store_provider_test.go
Since #7313 there are stores in sensor's "In-Memory" stores that are not entirely in memory. Registry mirror has information stored in the filesystem.
This shouldn't affect any reconciliation or resync behavior, as the data is in an ephemeral `emptyDir` and it's not backed by an PVC.
> ROX-20535: Rename sensor InMemory stores

- ui/apps/platform/cypress/integration/policies/policyWizardStep3.test.js
- ui/apps/platform/src/Containers/MainPage/InviteUsers/InviteUsersModal.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaModal.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicySection.tsx
This is the first of a series of PRs to add the new, more accessible way of adding policy criteria to a policy.
This PR adds a button to each section card in the Policy Wizard Step 3, after any already-added fields and the current drop area.
Clicking that button opens a modal, where the available policy criteria will be listed. (Not this PR only has a static stub list of criteria as a placeholder.)
I am not hiding the drag-and-drop method of adding criteria yet, because I think the two methods can coexist during development, and having both should make testing more efficient.
1. Created automated e2e tests for the button and modal, when the feature flag is on.
2. Manually verified the interaction
Button visible when feature flag is on
Modal open
Button below existing added policy field
In …
> ROX-20323: Create new policy criteria modal

- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/config/default/manager_auth_proxy_patch.yaml
As per the [Operator Remediation Guidance for CVE-2023-44487 doc](https://docs.google.com/document/d/1F99glzhX2i2Ppe5Qq3M-Po_jSSUiVssqFyWRhVm1X3o/edit?usp=sharing), HTTP/2 should be disabled in the `kube-rbac-proxy` that is part of the operator pod.
In order to do that, we need to:
- update its image tag to v0.15
- pass it the `--http2-disable` parameter
Note that downstream this image is replaced by `openshift4/ose-kube-rbac-proxy`. The [latest v4.13 release](https://catalog.redhat.com/software/containers/openshift4/ose-kube-rbac-proxy/5cdb2634dd19c778293b4d98?architecture=amd64&image=6537aafd6d3a98c9e65fcab7) supports the `--http2-disable` flag as well.
Tested in the ACS CS integration environment (see …
> ROX-20542: disable http/2 in operator kube-rbac-proxy

- scripts/ci/logcheck/check-restart-logs.sh
- tests/e2e/lib.sh
Add pod names in junit restarted pod report. This will result in different tickets for different pods.
Manually run script on payload I found in Jira. It correctly reports pod names
```bash
cat <<EOF  | grep "copied to Artifacts" | cut -d- -f1,3 | sort -u | tr '\n' ' '
Checking for a restart exception in: /tmp/k8s-service-logs/stackrox/pods/collector-2njt5-collector-previous.log
Ignoring this restart due to: collector restart due to sensor connection failure (likely slow start)
Checking for a restart exception in: /tmp/k8s-service-logs/stackrox/pods/collector-2njt5-compliance-previous.log
This restart does not match any ignore patterns
collector-2njt5-compliance-previous.log copied to Artifacts
Checking for a restart exception in: …
```
> ROX-17653: add pods names to pod restart junit

- .github/workflows/unit-tests.yaml
Send slack notification on `go bench` tests failure.
- #8352 
responsible for the …
> chore: slack notification for go bench failure

- .openshift-ci/clusters.py
- scripts/ci/gke.sh
Per title. The existing logic has 3 locations for defaults and is confusing.
Ensure tests with parameter overrides get the correct values:
```
NAME                                     LOCATION       MASTER_VERSION      MASTER_IP       MACHINE_TYPE   NODE_VERSION        NUM_NODES  STATUS
rox-ci-upgrade-test-1717954958445252608  us-central1-b  1.26.9-gke.1507000  35.224.183.162  e2-standard-8  1.26.9-gke.1507000  3          RUNNING
```
> refactor(CI): have a single source of GKE defaults

- .tekton/roxctl-pull-request.yaml
- .tekton/roxctl-push.yaml
The learning of https://github.com/stackrox/stackrox/pull/8440 is that task digests can go out of date even when tags don't change. Here I manually updated digests for all tasks I spotted.
The method was simple: I pulled latest images by tags
```bash
docker pull quay.io/redhat-appstudio-tekton-catalog/task-clamav-scan:0.1
```
and then replaced digests in file with the ones that got printed by `docker pull`.
This does not include `task-prefetch-dependencies` because the one is addressed in <https://github.com/stackrox/stackrox/pull/8440>.
This goes on top of https://github.com/stackrox/stackrox/pull/8324 but can be merged after 8324 is merged.
Won't do any of these since they don't apply:
Looked at CI and at the enterprise contract results. …
> chore: Update RHTAP task digests

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/CVESelectionTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/CVESelectionTh.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/CompletedExceptionRequestModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionRequestForm.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionScopeField.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/utils.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/hooks/useExceptionRequestModal.ts
Adds the deferral and false positive flow to the Workload CVE Image page. As part of this change, common code used here as well as in the main Workload CVE list page has been factored out.
1. Modal state management for the form modal and follow up success modal has been moved into a hook [useExceptionRequestModal.ts](https://github.com/stackrox/stackrox/pull/8390/files#diff-c20d33a8e9c8710bcaea6a008e98ae0572770a859d7b2e07f2d6305b9a15bcea)
2. Common table cells for selection have been moved to [CVESelectionTh](https://github.com/stackrox/stackrox/pull/8390/files#diff-6b64b4b45d04db0adfe210778f92b8055b0f4e114d908e6b76c88ec8f03dcbb3) and [CVESelectionTd](https://github.com/stackrox/stackrox/pull/8390/files#diff-67030b6f5a59fb6d69adc2e967e61349e3e36913fd94f07f34a2ee824928f5ad) components
3. …
> ROX-19394: Add deferral flow to image single page

- ui/apps/platform/cypress/integration/compliance/Compliance.helpers.js
- ui/apps/platform/cypress/integration/compliance/complianceList.test.js
- ui/apps/platform/cypress/integration/configmanagement/dashboard.test.js
- ui/apps/platform/src/Components/ControlDetails.js
- ui/apps/platform/src/Containers/ComplianceEnhanced/Status/Dashboard/Widgets/ComplianceByProfile.tsx
- ui/apps/platform/src/Containers/ConfigManagement/Dashboard/Page.js
- ui/apps/platform/src/Containers/Dashboard/Widgets/ComplianceLevelsByStandard.test.tsx
- ui/apps/platform/src/constants/entityTypes.ts
- ui/apps/platform/src/constants/tableColumns.test.js
- ui/apps/platform/src/messages/standards.js
Removes Docker CIS from the FE after already removing it from the backend
UI e2e
> chore(deprecation): Remove Docker CIS from UI

- central/convert/v2tostorage/vuln_exception_service.go
- central/convert/v2tostorage/vuln_exception_service_test.go
- central/graphql/resolvers/vulnerability_requests_test.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl_create_req_test.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl_reobserve_test.go
- central/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go
- central/vulnerabilityrequest/manager/requestmgr/singleton.go
This PR implements a v1 workflow to revert vulnerability exceptions having expiry based on the fixability of CVEs. In v2, a request can contain one or more CVEs, and the request can be set to expire if:
- past expiry time, or
- all CVEs in the requests are fixable, or
- at least one CVE in the request is fixable
In v1, a request could have only one CVE and the request can be set to expire if:
- past expiry time, or
- the CVE in the request is fixable
For backward compatibility, the legacy field is also set to `at least one` expiry kind because legacy implementation was so. 
Unit Test
> ROX-20610: v2 workflow to revert vulnerability exception

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
This PR adds the basic table for Approved Deferrals. I make use of the components previously created for the Pending Requests section.
Includes: ROX-19429 and ROX-19425
The same vuln request data is used for both of these sections (ie. Approved pending update deferral)
> ROX-19428: Create approved deferrals table

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionDetailsCell.tsx
Adds a link on the Workload CVE list table and Image page CVEs table to the exception management page, filtered by the relevant CVE.
Note that the search is applied to the URL, but implementation of the tables and filtering on the target pages are not complete at this point.
Create and approve at least one deferral and one false positive.
Visit the workload cve list page and view the deferral tab. Click the link and verify that the CVE search filter is applied in the URL.
Repeat this process for the false positive tab.
Repeat this process for the deferral tab on the image page.
Repeat this process for the false positive tab.
> ROX-19375: Add request details link to workload cves tables

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/DeploymentResourceTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameTd.tsx
Changes the component for table links in Workload CVEs from `<Button variant="link" />` to a plain `<Link />`. This makes it so that the link text itself is selectable for copy/paste.
For each of the following tables, verify that any link text within the table is selectable and that the link continues to go to the correct location.
- CVE List
- Image List
- Deployment List
- Image page CVE links
- Deployment page CVE links
- Deployment page nested table Image links
- CVE page Image links
- CVE page Deployment links
- CVE page nested deployment table Image links
e.g.)
> ROX-17720: Swap components to make Workload CVE links selectable

- migrator/migrations/m_195_to_m_196_vuln_request_users/migration_impl.go
- migrator/migrations/m_195_to_m_196_vuln_request_users/migration_test.go
Migrate legacy vuln exception expiry into v2 expiry. In v2, a request can contain one or more CVEs, and the request can be set to expire if:
- past expiry time, or
- all CVEs in the requests are fixable, or
- at least one CVE in the request is fixable
In v1, a request could have only one CVE and the request can be set to expire if:
- past expiry time, or
- the CVE in the request is fixable
The legacy field is migrated to `at least one` expiry kind because legacy implementation was so.
Note: Added the changes to the previous migration pushed earlier this morning through #8464.
Unit
> ROX-20609: Migrate legacy vuln exception expiry into v2 expiry

- central/image/service/service_impl.go
After #5339 has landed, which "fixed" the `IgnoreExistingImages` fetch option in the image enricher, this resulted in the following behavior:
- Watched images were now correctly being re-scanned again.
- However, the `ScanImage` API would now _always_ force a re-enrichment of the image.
This seems like an unwanted consequence, and the initial issue seems to be the following:
The `ScanImage` API already allows "forcing" an update of an existing image's scan via the `force` field within the request. It doesn't make sense to always ignore cached values when such a setting exists on the request.
Furthermore, it lead to an issue with fields such as the image's `Names` field, which were now overwritten completely, due to not using the `UseImageNamesRefetchCachedValues` fetch option when …
> fix(image): use UseCachesIfPossible fetch option for image scan

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.test.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx
This PR adds the basic table for Approved false positives. I make use of the components previously created for the Pending Requests section.
Includes: [ROX-19430](https://issues.redhat.com/browse/ROX-19430) and [ROX-19434](https://issues.redhat.com/browse/ROX-19434)
The same vuln request data is used for both the `Pending requests` section and the `Approved false positives` section (ie. Approved pending update - false positive). I made a few updates to the table cell components as well. You'll notice that the `Requested items` are different in each tab. Since you can technically remove a CVE as part of an update, you'll want to see a difference between the approved request and the updated request
> ROX-19433: Create approved false positives table

- .github/actions/cache-gradle-dependencies/action.yaml
- .github/actions/cache-ui-dependencies/action.yaml
Gradle and UI always download all deps so there is no reason to add job name to cache key.
CI
> chore(cache): do not use job name for UI cache key

- scanner/Makefile
- scanner/README.md
Updates include the following:
* Changes to `make all`
* Previous `make all` did not work, as `scanner-go-build` target no longer exists. It is now just equivalent to `make images`
* Default `GOOS` to `$HOST_OS` so `make build` builds Go binaries to use locally. `make images` will set `GOOS=$(DEFAULT_GOOS)` so the image's go binary is always built for `linux`
* Moved a few targets around
* Only check the expected Go version in CI. The current way caused more headaches than intended. The idea was to ensure developers updated to the latest Go versions, but instead caused developers to have to downgrade Go versions (or locally modify `EXPECTED_GO_VERSION`). Keeping this in CI to ensure our CI images are the correct version.
- ~[ ] Evaluated and …
> chore(scanner): misc. Makefile updates

- make/github.mk
The `$$(i*i)` never worked:
```
curl: (22) The requested URL returned error: ... 
environment: i*i: command not found
Retrying after  seconds...
environment: i*i: command not found
sleep: missing operand
Try 'sleep --help' for more information.
make: *** [make/protogen.mk:81: /home/mowsiany/go/src/github.com/stackrox/stackrox/.proto/.downloads/protoc-22.0-linux-x86_64.zip] Error 1
```
This changes to use double parens, which are the way to do arithmetic in bash.
While at it, it also made quoting consistent (present when necessary, i.e. not within `[[ ]]` which does not perform word splitting).
First, applied this change to [make/github.mk](make/github.mk):
```
--- a/make/protogen.mk
+++ b/make/protogen.mk
@@ -76,9 +76,10 @@ PROTOC_FILE := $(PROTOC_DOWNLOADS_DIR)/$(PROTOC_ZIP)
include …
```
> ROX-14176: fix protoc download retry, add quotes

- tests/e2e/lib.sh
- ui/apps/platform/cypress/integration/compliance-enhanced/ComplianceEnhanced.helpers.js
- ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedDashboard.test.js
- ui/apps/platform/src/Containers/ComplianceEnhanced/Status/Dashboard/ComplianceDashboardPage.tsx
This adds the scaffolding, and the most basic assertions, for ui-e2e-tests for the new Compliance 2.0 section. Only the landing page, `/main/compliance-enhanced/status`, is tested here.
In writing the test, I noticed that we were not setting a page title on the tab when visiting this page. In order to write this basic test, I fixed that oversight.
Caveats:
1. The data on the state is static for now, because the API and Compliance Operator integration are still in development.
2. Because there can be no API calls yet, the route matching/mock data is not included in this PR.
1. Will observe results of this test in CI
2. Ran the test locally, to see it passing.
performed one …
> chore(testing): New scaffolding for Compliance 2.0 ui-e2e-tests

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveSingle.test.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/watchedImagesFlow.test.js
The watched images tests previously would select whatever the first image on the page was for the watched image flow. Recently, this test was failing due to images not being available on gke.gcr.io.
This fix pre-filters the image list to only include images in the central deployment reduce the reliance on 3rd party changes.
Local Cypress CI run.
> fix(ui): Filter images list during watched image tests

- scanner/Makefile
Use `build-deps-t` where `deps` is hardcoded. It was added in #8460 but not used.
Also only run go version commands when needed.
And remove one unnecessary clean target.
Did `make build` and `make images`.
> fix(scanner): Use build-deps-t

- central/graphql/resolvers/image_cve_core.go
- central/graphql/resolvers/image_vulnerabilities.go
- central/graphql/resolvers/image_vulnerabilities_test.go
- central/graphql/resolvers/test_setup_utils.go
- central/graphql/resolvers/vulnerability_requests.go
This PR adds graphql vulnerability sub-resolver for getting an exception count. The sub-resolver does not accept a free-form query but instead, a direct filter `requestStatus: PENDING, APPROVED...`. Upon an authorization error on the sub-field, the Go zero-value is returned for the returned type (This is something we should be doing to all APIs).
Unit Test
> ROX-20612, ROX-20608: graphQL for exception count

- pkg/postgres/pgtest/postgres.go
This PR changes the SQL driver used in tests. Instead of loading lib/pq just for a side effect of loading `postgres` driver we can use `pgx` driver that is already loaded by gorm.
CI
> chore(pg): use pgx driver instead lib/pq

- operator/bundle.Dockerfile
- operator/bundle.Dockerfile.extra
This change is because OCP 4.10 reached EoL and we don't get new operator versions published downstream for it.
Here's info https://docs.engineering.redhat.com/display/SP/Shipping+Operators+to+EOL+OCP+versions
Downstream change as part of the same ticket ROX-20318: https://gitlab.cee.redhat.com/stackrox/rhacs-midstream/-/merge_requests/2182
E2E tests were already adjusted for 4.11 instead of 4.10 in https://issues.redhat.com/browse/ROX-20167.
None of these are needed:
I won't do any manual testing for this change, rather will run OSCI operator tests for higher and lower OCP bounds.
I will not specifically validate that the new value works as expected because the change should be self-evident and I use benefit of relying that this attribute should work as expected.
In addition to reviewing …
> ROX-20318: Move operator lower bound OCP version 4.10 -> 4.11

- operator/hack/common.sh
PR #8214 bumped the upgrade step timeout, which helped a lot with failures like ROX-17348 due to recent OLM versions (on OCP 4.14) taking longer to install.
However, inside the upgrade script ran by the upgrade step there is this additional 5m timeout for CSV upgrade, which apparently should have been bumped too. This change doubles it.
> ROX-20681: Bump CSV install timeout.

- .tekton/roxctl-pull-request.yaml
- .tekton/roxctl-push.yaml
- image/roxctl/rhtap.Dockerfile
- scripts/rhtap/fail-build-if-git-is-dirty.sh
Without hermetic builds.
The problem was due to stale image hash of `quay.io/redhat-appstudio-tekton-catalog/task-prefetch-dependencies:0.1` and insufficient workspace volume.
----
How I validated the change - by comparing pipeline run logs.
A build with prefetching enabled. `prefetch-dependencies` takes 1m40s, `build-container` takes 5m31s.
Interestingly, the build system injects `. /cachi2/cachi2.env &&` into every `RUN` statement in the dockerfile.
I.e. the original
```
RUN mkdir -p image/bin
```
becomes
```
RUN . /cachi2/cachi2.env &&     mkdir -p image/bin
```
That's how, I believe, they make sure all appropriate commands (`go ...`) find cached packages.
A build without prefetching. `prefetch-dependencies` obviously gets skipped. `build-container` takes 5m29s.
No speedup in build and …
> ROX-20482: Enable Go mod prefetching

- image/templates/helm/stackrox-secured-cluster/templates/admission-controller.yaml
Adding deployment scale to the resource list for the VWC
Manual testing on openshift and GKE cluster. Created a deployment with nginx latest, enforced Latest Tag default policy, and scaled it up and down to see that the operation is blocked by the admission controller.
> ROX-20552: Adding deployment scale to the resource list for the VWC

- central/compliance/checks/common/checks.go
- central/compliance/checks/nist800-190/check433/check_test.go
- central/compliance/checks/nist800-190/check442/check_test.go
- central/compliance/checks/pcidss32/check121/check_test.go
- central/compliance/checks/pcidss32/check132/check_test.go
- central/compliance/checks/pcidss32/check134/check_test.go
- central/compliance/data/repository.go
- central/compliance/framework/data.go
- central/compliance/framework/mocks/data.go
- central/networkpolicies/graph/evaluator.go
- central/networkpolicies/graph/evaluator_test.go
- central/networkpolicies/graph/graph_builder.go
- central/networkpolicies/graph/mocks/evaluator.go
GetGraph can be very expensive when network policies are fairly wide in creating the edges. We only care about which network policies match which deployments
Will check compliance before and after and write a unit test
> fix(perf): Add new network graph utilities to lower memory usage

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/watchedImagesFlow.test.js
Disables the watched image tests pending resolution of https://issues.redhat.com/browse/ROX-20728
These tests cannot be fixed as-is reliably because:
1. The only images that are available during the CI run are under the `gke.gcr.io` registry, which rejects requests on the backend for most images during this flow.
2. Images under `quay.io` are not being scanned, or for some other reason are not showing up on the Workload CVE image list
Local + await CI
> test(ui): Disable watched images e2e tests

- central/notifier/service/service_impl.go
- central/notifiers/awssh/notifier.go
- central/notifiers/cscc/cscc.go
- central/notifiers/email/email.go
- central/notifiers/generic/generic.go
- central/notifiers/jira/jira.go
- central/notifiers/pagerduty/pagerduty.go
- central/notifiers/splunk/splunk.go
- central/notifiers/utils/encryption.go
- central/notifiers/validation/validate.go
- pkg/secrets/scrub.go
- pkg/secrets/scrub_test.go
- Cleanup notifiers on startup and during create/update
- Refactor validation so that notifiers are validated before cleanup
Manual Testing
performed …
> ROX-19879: Cleanup notifiers on startup and during CRUD

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.test.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/mockUtils.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/hooks/useSet.ts
- ui/apps/platform/src/services/VulnerabilityExceptionService.ts
This PR adds real data for the Request Details page.
Note: When you click on the CVE link in the bottom table, it will navigate you to the CVE single page in the Workload CVEs section. I pass the appropriate URL query params, but the data won't show yet. Also, seems like the autocomplete filter doesn't really work well with a string that doesn't include the full registry, remote, and tag 😢. We might need to tweak that component a bit
Defer a CVE with a scope that ranges across all images and deployments
https://github.com/stackrox/stackrox/assets/4805485/e57523bd-e5c1-4e52-af9c-24fd97b394ba
Defer a CVE with a scope for one specific image but across all tags
https://github.com/stackrox/stackrox/assets/4805485/d0560232-61a3-49af-bc8f-01acec456a8c
Defer a CVE with a scope for one specific …
> ROX-20699: Using real data for request details page

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/cveListExceptionFlow.test.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveListExceptionFlow.test.js
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
Adds e2e tests for exception workflows in VM 2.0 from the image single page.
Also refactors existing e2e test helpers to use an object parameters instead of many positional parameters.
Local e2e test runs + CI
> test(ui): Add e2e tests for image single page exception flows

- .github/actions/cache-go-dependencies/action.yaml
- .github/workflows/style.yaml
- Makefile
Currently in go cache we keep both modules and build artifacts. This PR splits this cache into two 
1. GOMODCACHE
2. GOBUILDCACHE
This separation will allow us to keep a single go mod cache for every job (this requires downloading always all modules) but as we usually do it anyway it's not a big problem. Having a single cache key will limit amount of used cache space and increase cache lifespan.
Refs:
- https://github.com/stackrox/stackrox/pull/8494
- https://github.com/stackrox/stackrox/pull/8495
CI
performed …
> fix(gha): split go mod and build cache

- sensor/tests/connection/connection_test.go
Testing if Test_SensorReconnects is still flaky
Testing if Test_SensorReconnects is still flaky
> ROX-18197: reenable test sensor reconnects

- central/convert/internaltov1storage/compliance_check_results.go
- central/convert/internaltov2storage/compliance_check_results.go
- central/sensor/service/connection/sensorevents.go
- central/sensor/service/pipeline/complianceoperatorresults/pipeline.go
- central/sensor/service/pipeline/complianceoperatorresults/pipeline_test.go
- tests/e2e/run-compliance-e2e.sh
- tests/e2e/run.sh
Nextgen compliance MVP only pulls over part of the compliance functionality.  So V1 compliance needs to remain fully functional until feature parity is met by nextgen compliance.  So the results need to be stored in both V1 and V2 means to ensure a fully functional experience.  Since the message from sensor to central is changing the pipeline has to handle both old and new version as it is possible that central could be running with the nextgen compliance flag while a sensor may not be.  In such cases, compliance messages from a sensor without the feature flag set or an older sensor will only be processed as V1 compliance.  Additionally V2 messages need to be converted and stored as V1.  The simplest path here would have been to simply have sensor send both V1 and V2 messages.  That felt …
> ROX-20398: process V1 and V2 compliance results when flag on

- CHANGELOG.md
- central/delegatedregistryconfig/delegator/delegator.go
Fixes a bug that mistakenly required `Administration` permission to delegate scans.
Alternatively considered removing the [Administration check](https://github.com/stackrox/stackrox/blob/b614826867f333c00141f9cbd69f7381b84d5493/central/delegatedregistryconfig/datastore/datastore.go#L37-L41) from delegated registry config datastore, because the [service](https://github.com/stackrox/stackrox/blob/b614826867f333c00141f9cbd69f7381b84d5493/central/delegatedregistryconfig/service/service.go#L34) performs the appropriate access check this would have allowed internal components to access the config without modifying the request's context.
Both mechanisms are used throughout ACS (elevating context and removing the check from the datastore). I am OK using either if there is a strong opinion one way …
> ROX-20623: Allow non-admins to delegate scans

- ui/apps/platform/src/Containers/ExceptionConfiguration/ExceptionConfigurationPage.tsx
- ui/apps/platform/src/Containers/ExceptionConfiguration/VulnerabilitiesConfiguration.tsx
This defers rendering of the vulnerability exception config form until after the request has successfully returned the current configuration from the server.
This serves two purposes:
1. Fixes race conditions in tests
2. Prevents rendering the form with invalid placeholder data. The form now will only render with the correct, current data.
Easier to review with "Hide whitespace" on.
Local Cypress run + awaiting CI
> ROX-20804: Defer rendering of vuln exception config form

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedImagesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/PendingExceptionLabelLayout.tsx
Adds a "Pending exception" label to CVEs, Images, and Deployment under "Observed" tabs when the entity has an open exception request that has not yet been approved.
Adds a "Pending update" label to CVEs, Images, and Deployments under "Deferred" (and theoretically "False Positive") tabs when the entity has an approved exception request with a new pending update.
Note: False positive requests currently cannot be updated, but if that is changed the labels will show up under that tab as well.
Defer a CVE via the Workload CVE Image page, only for a single image.
Visit the Workload CVE list page, the CVE shows up with a Pending label on the list page, the relevant image page, deployment page, and for affected images/deployments on that CVE's …
> ROX-19357: Add pending exception label to workload cve tables

- .tekton/roxctl-pull-request.yaml
- .tekton/roxctl-push.yaml
This is to fix failing builds due to insufficient persistent volume quota when multiple build requests run in parallel.
See https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1699473999600919
None of these are needed and will not be done:
Verified needed volume size by injecting a Task that prints free and used space.
The passing build is the confirmation that the setting gives sufficient storage size.
> chore: Decrease RHTAP workspace size for `roxctl` builds

- scanner/Makefile
- scanner/README.md
Downstream images may be built with newer Go versions. Because of this, the `build-go-check-ver` check for the `$(build-deps-t)` is removed. After removing from that target, there isn't much of a reason to keep it around anymore, so I'm just going to remove it, completely.
CI …
> chore(scanner): remove go version check

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
This PR uses real data to display the approved deferrals' data in the Exception Management section. You should be able to filter and sort the same way described in https://github.com/stackrox/stackrox/pull/8577
> ROX-20697: Use real data for approved deferrals

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DefaultFilterModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.css
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
- ui/apps/platform/src/hooks/useLocalStorage.test.ts
- ui/apps/platform/src/hooks/useLocalStorage.ts
- ui/apps/platform/src/utils/type.utils.ts
Reimplements fixability filters and default filters in Workload CVEs when the appropriate feature flag is on.
e2e tests in a follow up to keep the size of this PR manageable.
- A new `useLocalStorage` [hook](ui/apps/platform/src/hooks/useLocalStorage.ts) has been added. This hook requires a third parameter of a type predicate to ensure the raw value pulled from localStorage is always runtime consistent with the value we expect it to be. This helps prevent the need use type assertions (`value as MyType`) in the code, and avoids runtime errors when the value in localStorage is invalid.
- The TypeScript type for the stored default filters was changed so that it is defined as a [yup schema _first_, and then the TS type is inferred](https://github.com/stackrox/stackrox/pull/8514/files#diff-d9e5 …
> ROX-17494: Reimplement fixability filters in workload CVEs

- tests/e2e/lib.sh
- ui/apps/platform/cypress/integration/compliance-enhanced/ComplianceEnhanced.helpers.js
- ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedDashboard.test.js
- ui/apps/platform/src/Containers/ComplianceEnhanced/ScanConfigs/ScanConfigPage.tsx
- ui/apps/platform/src/Containers/ComplianceEnhanced/ScanConfigs/ScanConfigsHeader.tsx
- ui/apps/platform/src/Containers/ComplianceEnhanced/ScanConfigs/Table/ScanConfigsTablePage.tsx
Expand the original base test for Compliance 2.0 to:
1. visit dashboard (aka Status page) from left nav
2. visit dashboard (aka Status page) by direct navigation and check existing page elements
3. visit scan configs (aka Scheduling page) from left nav
4. visit scan configs (aka Scheduling page)  by direct navigation and check existing page elements, and start creation process
Note: I'm also adding the env var to turn on the feature flag in OCP CI environments, because this feature really only works on OCP
Ran tests locally …
> chore(test): Add smoke tests for Compliance 2.0 scan configs

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/cveListExceptionFlow.test.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveListExceptionFlow.test.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
- ui/apps/platform/src/hooks/useLocalStorage.test.ts
Fixes an issue where severity counts were incorrectly hidden on Workload CVE details pages.
Additionally fixes CI failures from the following PRs in an attempt to get CI back on track with a single merge
- https://github.com/stackrox/stackrox/pull/8612
- https://github.com/stackrox/stackrox/pull/8610
Local Cypress runs, awaiting CI
Visiting an image single page no longer displays "Results hidden" for all severities in the card.
> fix(ui): Fix collective workload CVE test issues

- Makefile
controller-gen is not referenced in Makefile. We can remove it as it's installed and pinned in operator Makefile
https://github.com/stackrox/stackrox/blob/b27c7bd4bc1562d2a07fe3f0856641240553ed79/operator/Makefile#L173
CI
> fix: remove unused controller-gen from Makefile

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
This PR uses real data to display the approved false positives data in the Exception Management section. You should be able to filter and sort the same way described in https://github.com/stackrox/stackrox/pull/8577
> ROX-20698: Use real data for approved false positives

- scripts/ci/lib.sh
`/tmp/secrets` is not used. ref: https://github.com/stackrox/stackrox/pull/2540 & https://github.com/openshift/release/pull/30789
> chore(CI): remove unused secrets mount

- scanner/cmd/scanner/main.go
- scanner/config/config.go
- scanner/config/config_test.go
- scanner/indexer/indexer.go
- scanner/indexer/mocks/indexer.go
- scanner/indexer/remote.go
- scanner/mappers/mappers.go
- scanner/mappers/mappers_test.go
- scanner/services/indexer.go
- scanner/services/indexer_test.go
- scanner/services/matcher.go
- scanner/services/matcher_test.go
Approve this PR to:
- Move service/converters to mappers.
- Add RemoteIndexer.
- Move manifest digest creation to indexer.
- Add config flag to enable remote indexer.
These changes will allow the Matcher to use a remote Indexer to retrieve Index Reports when the vulnerability report request does not contain contents, only index report hash id.
Setup Scanner to run locally in different modes.
`matcher-config.yaml`:
```
http_listen_addr: 127.0.0.1:9444
grpc_listen_addr: 127.0.0.1:8444
indexer:
enable: false
database:
conn_string: "host=/var/run/postgresql"
password_file: ""
get_layer_timeout: 1m
matcher:
enable: true
database:
conn_string: "host=/var/run/postgresql"
password_file: ""
indexer_addr: :8443
mtls:
certs_dir: certs/scanner-v4 …
```
> ROX-20732: Matcher can use a remote Indexer

- roxctl/scanner/uploaddb/uploaddb.go
- roxctl/scanner/uploaddb/uploaddb_test.go
Reformats Db to DB and renames `uploadDd` to `uploadDB`
If it builds, it builds
> chore(roxctl): upload-db minor cleanup

- ui/apps/platform/package.json
- ui/yarn.lock
The need to skip tests because of async problems related to testing-library `act` and React 18 caused me to notice how outdated jest and ts-jest have become.
We will take it one major version at a time: 27, 28, 29.
Upgrade beyond 27 requires `resolutions` because of `jest "^27.4.3"` in `dependencies` of react-scripts package.
* https://jestjs.io/blog/2021/05/25/jest-27
* https://github.com/jestjs/jest/blob/main/CHANGELOG.md#2700
* https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md#breaking-changes-4
1. `yarn test` in ui/apps/platform and then type `a`
> chore(ui): Upgrade jest and ts-jest 27  devDependencies

- operator/tests/common/upgrade-assert.envsubst.yaml
- operator/tests/upgrade/upgrade/20-assert.yaml
This step timed out by less than a second due to quay slowness.
By only focusing on the status of CRs, and leaving assertion of operand health to subsequent step 30, we:
- reduce the scope of this step to just the operator reconciliation, greatly increasing its probability of success within the timeout
- increase the quality of the operand health checks, since step 30 has more checks and more collectors
One can think of this as continuation of the changes in https://github.com/stackrox/stackrox/pull/8431 …
> ROX-20766: Do not assert operand health in upgrade step 20

- sensor/common/networkflow/manager/manager_impl.go
Currently, if customers see an edge connecting a container with External Entities on the network graph, then they have no  information about this connection.
With this PR, we are adding a log line to Sensor with information about all external connections that are unknown. It means that we show source and destination of the connection (namespace + container name on one side, and IP address and port on the other side) for all cases when "External Entities" would appear on the graph.
Note that we will not show this log line, if the source/destination is external but belongs to the known CIDR ranges. In that case, we will show the name associated with the CIDR range on the graph and no log entry will be produced.
- I have deployed a cluster and triggered an edge to "External Entities" …
> ROX-20713: Add log with connection details (External Entities in NWG)

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/hooks/useInvalidateVulnerabilityQueries.ts
Adds a hook that instructs the Apollo client to evict the cache of all top level fields related to workload CVEs. _This will only make network calls for queries that are active and depend on these fields._ Inactive queries will only be refetched when their component is rendered again.
This is used to ensure the Workload CVE data cache is up to date with known mutations. In the case of this PR, this occurs when the user submits an exception request in order to correctly render the "Pending exception" labels.
Visit Workload CVEs and then visit a single CVE page. This will populate the apollo cache with the query result for that CVE. Navigate back to the CVE list and defer this CVE.
- The list view in the background will automatically update …
> feat(ui): Add hook to invalidate all workload cve queries

- scanner/e2etests/helmchart/templates/scanner-deployment.yaml
- scanner/image/db/Dockerfile
- scanner/image/scanner/Dockerfile
- scanner/image/scanner/scripts/entrypoint.sh
Scanner image:
* Explicitly copy the scripts we want to prevent unintentional bloat. For example, the `.gitignore` file was copied into the Scanner image, previously
* Put the scripts into `/usr/local/bin` instead of root, as it's the standard location for local binaries in Linux
* Note: Scanner v4 DB already put scripts here
* Remove `chmod +rx /scanner`, as it already has these permissions
Scanner DB image:
* Keep `the owner of /usr/local/bin/docker-entrypoint.sh` as root to prevent potential attackers using the `postgres` user from messing with the file
* Remove `chmod +x /usr/local/bin/docker-entrypoint.sh` since it's already executable
* Move scripts copies into a single layer
- ~[ ] …
> chore(scanner): various image nits

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/cveListExceptionFlow.test.js
- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js
The combination of the following recent changes have made the amount of CVE data available in CI unpredictable:
1. https://issues.redhat.com/browse/ROX-20728 resulting in fewer overall images scanned at runtime
2. https://issues.redhat.com/browse/ROX-17494 resulting in unfixable, low severity, and moderate severity CVEs being filtered from the table
3. The fact that CVEs disappear from the CI when an update fixes the vulnerability (disproportionately affecting the inverse of 2 above - Critical/Important and Fixable CVEs)
This attempts to mitigate at least 2 and 3 by clearing all applied filters at the beginning of the tests. A [new ticket](https://issues.redhat.com/browse/ROX-20910) was created to revisit the overall test strategy here with a focus on reliability.
If any of these don't …
> test(ui): Clear all filters before performing deferral tests

- ui/apps/platform/package.json
- ui/yarn.lock
Left over from pre-PatternFly components for which classes depended on props.
> ROX-20668: Remove classnames from ui dependencies

- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx
Found this while navigating with the console open. The VM reporting list page will rerender infinitely until the report list returns from the API call, or indefinitely if there is a network error on the initial request.
With the console open, verify that the "Maximum update depth exceeded." error is not displayed when visiting VM reporting.
> fix(ui): Fix infinite rerender in vm reporting

- pkg/booleanpolicy/augmentedobjs/construct.go
- pkg/booleanpolicy/matcher_impl.go
- pkg/detection/runtime/detector.go
- sensor/common/detector/detector.go
The runtime path was not being enhanced with the network policies applied to the deployment.
* Deploy ACS
* Create a system policy with the following criteria: 
* Create a deployment nginx.
* Observe that there are violations triggered whenever we create a network flow to that deployment:
* Create a network policy for that deployment.
* Observe that there are no more …
> ROX-20881: enhance with network policies

- ui/apps/platform/eslint.config.js
- ui/apps/platform/src/Components/PageTitle.tsx
- ui/apps/platform/src/Components/workflow/TableCountLinks/TableCountLinks.tsx
- ui/apps/platform/src/Containers/AppPageTitle.tsx
- ui/apps/platform/src/Containers/NetworkGraph/common/AdvancedFlowsFilter/types.ts
- ui/apps/platform/src/routePaths.ts
- ui/apps/platform/src/types/risk.proto.ts
- ui/apps/platform/src/utils/searchUtils.ts
We disabled some rules to limit the number of changes in #8629
1. no-duplicate-type-constituents
* Delete duplicate `'IMAGE_COMPONENT'` from string enumeration.
2. no-redundant-type-constituents
* TableCountLinks: `""` is overriden by string in this union type
Simplify because `(typeof entityTypes)[keyof typeof entityTypes]` means `string`
* AdvancedFlowsFilter/types.ts
* "ingress" | "egress" is overridden by string in this union type
* "L4_PROTOCOL_TCP" | "L4_PROTOCOL_UDP" is overridden by string in this union type
* searchUtils.ts: `unknown` overrides all other types in this union type
Simplify
3. no-unsafe-return
* Add `Record<string, string>` to objects in routePaths.ts file.
* Delete `.toString()` in AppPageTitle.tsx file.
* Add `| undefined` in AppPageTitle.tsx and PageTitle files. …
> chore(ui): Fix errors and enable typescript eslint rules (part 1)

- ui/apps/platform/eslint.config.js
- ui/apps/platform/src/Components/ReactSelect/ReactSelect.js
- ui/apps/platform/src/Components/URLSearchInputWithAutocomplete.js
We disabled some rules to limit the number of changes in #8629
1. react/display-name
* ReactSelect: provide name of class.
* URLSearchInputWithAutocomplete: replace arrow function with named function.
> chore(ui): Fix errors and enable react display-name lint rule

- ui/apps/platform/eslint.config.js
- ui/apps/platform/src/Components/BinderTabs/Binder.test.tsx
- ui/apps/platform/src/Components/Pagination/NextPaginationButton/NextPaginationButton.test.js
- ui/apps/platform/src/Components/Pagination/PrevPaginationButton/PrevPaginationButton.test.js
- ui/apps/platform/src/Components/Select.test.js
- ui/apps/platform/src/Components/TimelineGraph/EventsGraph/ClusteredEventMarker/ClusteredEventMarker.test.tsx
- ui/apps/platform/src/Components/TimelineGraph/EventsGraph/EventMarker/EventMarker.test.js
- ui/apps/platform/src/Containers/Dashboard/ScopeBar.test.tsx
- ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/VulnRequestedAction/VulnRequestedAction.test.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/MyActiveJobStatus.test.tsx
- ui/apps/platform/src/hooks/useTabs.test.js
We disabled some rules to limit the number of changes in #8629
All errors to prefer a different assertion method have automatic fix.
There was one extraneous change from `getAllByRole` to `getByRole` which broke Select.test.js but I undid it to keep only the assertion method change.
1. `yarn lint:fix` in ui/apps/platform
2. `yarn test` in ui/apps/platform
> chore(ui): Fix errors and enable jest-dom recommended lint rules

- pkg/postgres/context.go
- pkg/search/postgres/store.go
DeleteMany currently has strange semantics where it may give you a partial deletion. This moves delete many into a single, all or nothing transaction which is much clearer semantics
Unit tests test the nesting
> fix(store): Put DeleteMany into a transaction

- central/networkgraph/entity/networktree/manager_bench_test.go
This PR fixes bench test by running an operation `b.N` times. 
It also fixes following issue with this test:
> Received unexpected error: network tree for cluster "c1" already exists
```
BenchmarkCreateNetworkTree
BenchmarkCreateNetworkTree/createNetworkTree
BenchmarkCreateNetworkTree/createNetworkTree-8         	     182	   6465295 ns/op
BenchmarkCreateNetworkTree/insertIntoNetworkTree
BenchmarkCreateNetworkTree/insertIntoNetworkTree-8     	      64	  17993408 ns/op
PASS
``` …
> fix: manager bench test

- .github/workflows/build.yaml
We need to run junit2jira especially when previous step was failing. 
CI
> fix: report vulns to jira on push

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx
- ui/apps/platform/src/services/VulnerabilityExceptionService.ts
This PR adds the ability to view comments on the Request Details page. Clicking the comments button/link will open a modal to view comments in a scrollable manner.
> ROX-20886: Add modal for viewing exception request comments

- ui/apps/platform/cypress/integration/policies/policyWizardStep3-dnd.test.js
- ui/apps/platform/cypress/integration/policies/policyWizardStep3.test.js
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaForm.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaModal.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicySection.tsx
This is the final step in implementing the new Policy Field modal to replace the drag-and-drop style of add policy fields to a Policy.
1. Adds the filter text input to the TreeView, which does front-end filtering on the list of available criteria as the user types in the input. (Note: as discussed in the UX-UI meeting, the TreeView's filter bar appears immediate above the tree, with the Expand All button above the whole TreeView component)
2. Disables the modal's primary button until a field has been selected.
3. Filters fields that have already been used in a policy section out of the list in the modal. (This need was revealed when porting one of the e2e tests to check that a field can't be added twice--and I chose it as the simplest solution, because disabling TreeView items is not a …
> ROX-20521: Add frontend filter for policy criteria modal

- ui/apps/platform/src/Containers/MainPage/Body.tsx
Prevent InviteUsersModal from rendering and causing GET request to various Auth-related endpoints, if user does not have appropriate permissions to act on inviting.
Discovered gap when customer who had user Role without even read access to ACCESS got stuck in a logout/login redirect loop.
tbd
> ROX-20927: Scope Invite Users modal to Access write permission

- sensor/tests/resource/pod/pod_test.go
This time the flake is in `DeleteDeployment` test.
IIUC the `nil` check is not sufficient if the alerts were resolved as opposed to never triggered. So if alert results aren't `nil`, they should have 0 elements in the slice. 
If this doesn't solve the issue, I've added additional logs for the next time this fails. 
> ROX-20789: Fix pod hierarchy test flake

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/DeploymentResourceTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/AffectedDeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameTd.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
Links throughout the Workload CVE section will keep the user on the same vulnerability state tab (Observed, Deferred, False Positive).
Create and approve false positive and deferral requests.
Visit the deferred tab on the over view list page. Test that links for CVEs, Images, and Deployments keep you on the Deferred tab across pages:
Check the outgoing links from the CVE single page:
Repeat for outgoing links from the Image and Deployment single pages.
Repeat all of the above for the Observed and False Positive tabs.
> ROX-20848: Maintain vuln state across Workload CVE links

- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl
- operator/tests/central/basic-central/90-assert-openshift.yaml
- operator/tests/common/central-volumes-assert-openshift.yaml
Add [the projected volume for the service account](https://kubernetes.io/docs/concepts/storage/projected-volumes/) for its usage with the upcoming WIF / STS integration.
The projected volume is required to set a custom audience of `openshift` for parity with the CCO operator's expected audience.
Currently, this is only being done when deployed to OpenShift, for non-OpenShift deployments nothing will be changed.
1. Deploy the latest Helm chart / operator on OS cluster
```bash
./deploy/deploy.sh
```
2. Observe in the rendered YAML for both Central and Sensor the projected volume
```yaml
...
- name: central-bound-sa-token
projected:
defaultMode: 420
sources:
- serviceAccountToken:
audience: openshift
expirationSeconds: 3600
path: token
...
- …
```
> ROX-20784: Add projected SA volume

- central/alert/datastore/internal/store/postgres/bench_test.go
- pkg/search/postgres/store.go
As documentation says `Close` will collect data of all queries so in our case there is no need to manually loop over all queries inside the batch. 
Another change in this PR is to make a single batch for all objects updated and not a batch per object especially when we have batching in `UpsertMany`.
> `Close` closes the batch operation. All unread results are read and any callback functions registered with `QueuedQuery.Query`, `QueuedQuery.QueryRow`, or `QueuedQuery.Exec` will be called. If a callback function returns an error or the batch encounters an error subsequent callback functions will not be called.
> `Exec` reads the results from the next query in the batch as if the query has been sent with Conn.Exec. Prefer calling `Exec` on the `QueuedQuery`.
Refs:
- …
> fix(db): batch upsert in a single call

- image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml
- operator/tests/central/basic-central/81-assert-non-openshift.yaml
- operator/tests/central/basic-central/81-assert-openshift.yaml
- pkg/helm/charts/meta.go
- pkg/helm/charts/tests/centralservices/testdata/helmtest/telemetry.test.yaml
- roxctl/helm/output/output.go
* Set telemetry key to `DISABLED`, if `central.telemetry.enabled==false`;
* Configure telemetry in `roxctl helm` output.
`roxctl central generate k8s pvc`, running release version of `roxctl` generates this in `helm/values-public.yaml`:
```yaml
central:
telemetry:
enabled: true
storage:
endpoint: 
key: 
```
and provided `--enabled-telemtry=false`:
```yaml
central:
telemetry:
enabled: false
storage:
endpoint: 
key: DISABLED
```
the rendered helm chart in this case has this variable in the central deployment:
```yaml
- name: ROX_TELEMETRY_STORAGE_KEY_V1
value: "DISABLED"
```
performed one does not seem sufficient. As a …
> fix: configure telemetry in helm output

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/VulnerabilityStateTabs.tsx
Resets the current table page when navigating between deferral state tabs. Previously the page would be maintained, leading to incorrect data displays where the table would show no data.
On the observed tab, cycle a handful of pages forward:
Move to the "Deferred" tab an ensure you are on the first page of results:
Repeat for the Image, ImageCVE, and Deployment detail pages.
> ROX-20834: Reset pagination when changing vuln state tabs

- ui/apps/platform/config-overrides.js
- ui/apps/platform/eslint.config.js
- ui/apps/platform/package.json
- ui/apps/platform/react-app-rewired/jest/cssTransform.js
- ui/apps/platform/react-app-rewired/jest/fileTransform.js
- ui/apps/platform/src/Containers/ConfigManagement/ConfigMgmt.utils.test.js
- ui/apps/platform/src/Containers/VulnMgmt/List/Cves/ListCVEs.utils.test.js
- ui/package.json
- ui/yarn.lock
One more step forward. Reduce from 18 to 15 months outdated.
Jest in time (pardon pun) because first 30 alpha versions have been published.
Upgrade beyond 28 requires `resolutions` because of `jest "^27.4.3"` in `dependencies` of react-scripts package.
* https://jestjs.io/blog/2022/04/25/jest-28
* https://github.com/jestjs/jest/blob/main/CHANGELOG.md#2813
* https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md#2808-2022-08-14
1. Update and then delete types/jest because `"@types/jest" "*"` in types for testing-library jest-dom package, I temporarily updated types/jest and then deleted it (in case it ever becomes unneeded by the other package).
2. Add jest-environment-jsdom to devDependencies because Jest 28 removed it from default installation.
3. Override cssTransform.js and …
> chore(ui): Upgrade jest and ts-jest 28 devDependencies

- central/imageintegration/store/defaults.go
Same as other defaults, support the public registry
scanned public.ecr.aws/aws-observability/aws-for-fluent-bit:latest
> fix(default): Add ECR public registry as default config

- sensor/kubernetes/clusterstatus/updater.go
- sensor/kubernetes/clusterstatus/updater_test.go
If Sensor goes offline the cluster metadata info might not be received by Central. Sensor should re-send the metadata when back online.
> ROX-20692: handle offline status in the cluster status updater

- central/hash/manager/deduper.go
- central/hash/manager/deduper_test.go
- pkg/deduperkey/key.go
- pkg/deduperkey/key_test.go
- pkg/sensor/event/event.go
- sensor/common/deduper/deduper.go
This PR introduces generic functions to manage parsing of key-like strings in `/pkg`. 
This is related to the PR comment: https://github.com/stackrox/stackrox/pull/8430#pullrequestreview-1717551083
New tests can be skipped for this change since it's a minimal refactor. The current test suite will check for regressions.
> ROX-20693: Move common key functions to pkg

- pkg/nodes/enricher/enricher_impl.go
- pkg/nodes/enricher/metrics.go
This PR adds a Prometheus metric to central to track the number of received Node Scan components per node and node scan.
Created an OpenShift 4 cluster, deployed via `deploy.sh` and port-forwarded port 9090 from the monitoring pod to localhost.
I then waited for the first Node Scans to arrive, to check the metric `rox_central_node_scan_num_components` (see [screenshot in this comment](https://github.com/stackrox/stackrox/pull/8686#issuecomment-1819186844))
> chore(scanner): Add size of Node Inventory Components as metric

- central/sensor/service/connection/manager.go
- central/sensor/service/connection/manager_impl.go
- central/sensor/service/connection/manager_test.go
- central/sensor/service/connection/mocks/manager.go
- central/sensor/service/service_impl.go
Follow-up from #8430. 
It fixes a possible issue if the cluster is too large and the number of unchangedIDs is too large to be transmitted on initial ResourcesSynced message. 
In order to test this locally, I've changed my sensor to inject 260k entries to check that central properly falls back to the old reconciliation.
```
--- a/sensor/common/deduper/deduper.go
+++ b/sensor/common/deduper/deduper.go
@@ -113,6 +114,10 @@ func (d *deduper) Send(msg *central.MsgFromSensor) error {
resourcesSynced := event.GetSynced()
if d.appendUnchangedIDs && resourcesSynced != nil {
d.synced = true
+               for i := 0; i < 260_000; i++ {
+                       d.unchangedIDs.Add(fmt.Sprintf("Deployment:%s", uuid.NewV4()))
+               } …
```
> ROX-20878: Fallback reconcile if gRPC ResourceExhausted

- .github/workflows/build.yaml
- Makefile
- tools/linters/go.mod
- tools/linters/go.sum
- tools/linters/tools-import.go
Move from `latest` to pinned version stored in `tools/linters/go.mod` so it will be pinned and updated by @dependabot
- https://github.com/stackrox/stackrox/pull/8653#discussion_r1398832319
CI
> fix(ci): pin govulncheck version

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/TableEntityToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/components/SearchOptionsDropdown.tsx
Adds the ability to filter all Workload CVE tables by "Component" and "Component Source".
Follow up: refactoring of workload cve filters to enforce a single source of truth
Filter by component:
Filter by component source:
On the image single page:
Repeat filtering on the CVE and Deployment single pages
> ROX-20574: Add component filters to workload cves

- scanner/Makefile
Now you can create Scanner with CGO enabled. For example:
```
$ make CGO_ENABLED=1 image/scanner/bin/scanner
+ bin/scanner
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-X github.com/stackrox/rox/scanner/internal/version.Version=4.3.x-253-g4280dc16e2" -o bin/scanner ./cmd/scanner
```
Run `make CGO_ENABLED=1 image/scanner/bin/scanner`. It may not compile on macOS, but that's ok. It's meant for the …
> build(scanner): allow cgo enablement

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.test.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestOverview.tsx
This PR shows a slightly different view for request details when the exception status is `APPROVED_PENDING_UPDATE`. Because this is a mixed state, we want to be able to show the request data as it was approved and the request data that is pending approval
> ROX-20862: Show updated vs. original request data in request details

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/CVESeverityDropdown.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/CVEStatusDropdown.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DefaultFilterModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/TableEntityToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/searchUtils.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/types.ts
- ui/apps/platform/src/Containers/Vulnerabilities/components/FilterAutocomplete.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/components/SearchOptionsDropdown.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/searchOptions.ts
Implements [this TODO](https://github.com/stackrox/stackrox/pull/8721/files#diff-48d45bd63292341708a815735bc19c0a64cf72c76de6934038e2208eeded2b44L11), and uses the new options to provide a single source of truth throughout workload CVE sections. Also makes some minor changes to standardize on ALL_CAPS for existing Workload CVE filters.
Manual testing of all search filters on the list page, image detail page, cve detail page, and deployment detail page.
Additional testing via existing Cypress tests.
> chore(ui): Refactor VM 2.0 search options for single source of truth

- tests/e2e/lib.sh
In [ROX-17934](https://issues.redhat.com/browse/ROX-17934) we have all types of errors found across different CI runs. This make no sense. This PR introduces heuristic to create a jira unit based on last found line. We take the part after last `.log[` and from that we extract last segment after splitting by `:` (a common go error delimiter). After merging this PR we should have more fine grained issues.
Refs:
- https://github.com/stackrox/stackrox/pull/8378
CI and I've run command for different outputs I found in original jira issue.
performed one does not seem sufficient. As a reviewer, you must not approve the change until …
> ROX-17934: split reports for suspicious logs

- sensor/common/installmethod/install.go
Default sensor install method to `manifest`. The install method is used for our Telemeter metrics, where sensors installed via a downloaded yaml manifest bundle currently show up w/ an empty install method. The reason is that such manifest installs may result in `ManagerType_MANAGER_TYPE_UNKOWN`.
> fix: sensor install method fallback to `manifest`

- central/config/service/service.go
The /v1/config/public endpoint is a public endpoint. This change aims at documenting the reasons behind its being public in order to ease future investigations of public endpoints and possible hardening.
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change …
> ROX-20018: Document why /v1/config/public is public

- qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
This test flakes a lot. We track it in ROX-19615
Looking at the run and making sure that the test is skipped.
> chore(flake): Disable Test "Verify connections from external sources"

- .tekton/central-db-pull-request.yaml
- .tekton/roxctl-pull-request.yaml
Was requested by colleagues in https://redhat-internal.slack.com/archives/C0321S70YK1/p1700742096346419
`contains` function is mentioned here https://github.com/google/cel-spec/blob/master/doc/langdef.md#list-of-standard-definitions
None of these needed, none will be done:
Confirmed it works by seeing RHTAP here and not seeing it in https://github.com/stackrox/stackrox/pull/8768.
> ROX-21072: Limit RHTAP PR workflows if branch name contains "rhtap"

- qa-tests-backend/scripts/run-compatibility.sh
Make version strings shorter so test folder names are less verbose and easier to read for users.
The regex works by capturing the first part of an image tag, since image tags can be long or short. Examples:
4.3.x-266-g3e1c64296a --> 4.3.x
400.2.2 --> 400.2.2
74.3.7 --> 74.3.7
It always returns MAJOR.MINOR.PATCH or MAJOR.MINOR.X
I manually tested the regex used. The artifacts in the CI runs also show that the test folder names changed as expected:
> ROX-20277: gke version compatibility limit test description

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx
This PR makes the `Requested update` and `Latest approved` tabs part of the URL. This allows us to go to the correct tab for a request that is approved, but pending an update. We use the query param value of `?context=CURRENT` or `?context=PENDING_UPDATE` to determine which tab to show
Tests will come in a future PR
https://github.com/stackrox/stackrox/assets/4805485/ff4ca335-ef50-41ac-89e3-cb4e15bb9672
> ROX-21014: Make request details tab part of URL

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestApprovalButtonModal.tsx
- ui/apps/platform/src/services/VulnerabilityExceptionService.ts
This PR adds the ability to approve requests. The approve button will show up on the Request Details page on the following conditions:
1. The user has read/write access for `VulnerabilityManagementApprovals`
2. The request is either in the `PENDING` or `APPROVED_PENDING_UPDATE` status
The approve button shows up in the top right section
Clicking on the button will show a modal. The modal will display one form field for inputting an approval rationale. The form has validation. The button will be disabled initially and when no value is inputted for the approval rationale.
If the request was approved, you'll see a success banner at the top of the page showing it was approved. The data on the page will be updated as well.
> ROX-20556: Add flow for approving a vulnerability request

- central/sensor/service/connection/connection_impl.go
- central/sensor/service/connection/connection_test.go
- central/sensor/service/service_impl.go
- pkg/centralsensor/caps_list.go
- pkg/features/list.go
- qa-tests-backend/src/test/groovy/AuditLogAlertsTest.groovy
- sensor/common/sensor/central_communication_impl.go
- sensor/debugger/message/fake.go
Enabling the Feature Flag for sensor client reconciliation after the fix in #8430. 
This PR also fixes the following issue:
- Changes the capability name. This is because 4.3 was shipped with the possibility of skipping reconciliation and send individual deletes. Since we changed the behaviour of feature but kept the same FF and capability name, this cased a conflict in the compatibility test.
Manual tests and automated tests were added in past PRs. See #7755 and #8430
performed testing and you are satisfied with …
> ROX-21023: Enable client reconciliation feature flag

- .golangci.yml
- central/notifiers/email/email_integration_test.go
- central/notifiers/splunk/splunk_test.go
- pkg/registries/ibm/ibm_integration_test.go
- pkg/registries/quay/quay_integration_test.go
- pkg/scanners/quay/quay_integration_test.go
Integration tests are guarded by `integration` tags. To lint them we need to add `integration` tag to linter.
There are some suspicious lines that looks like a real tokens/passwords that should be injected.
CI
> fix(lint): enable linting for integration tests

- CHANGELOG.md
- operator/apis/platform/v1alpha1/central_types.go
- operator/bundle/manifests/platform.stackrox.io_centrals.yaml
- operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml
- operator/config/crd/bases/platform.stackrox.io_centrals.yaml
- operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
Removes the annotations for tech preview for external db
Trivial
> ROX-20898: Remove tech preview for external DB

- ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js
For this particular test, clears the default filters at the start of the test. This prevent inconsistencies after navigation since default filters do not persist when moving from the overview page to the detail pages.
Awaiting CI
> ROX-20928: Clear default filters before navigation in e2e test

- pkg/secretinformer/informer.go
- pkg/secretinformer/informer_test.go
Add a secret informer wrapper for use in watching the cloud credential secrets `awsCloudCredentials`/`gcpCloudCredentials`/`azureCloudCredentials`. These secrets will contain STS configuration for workload identity federation.
CI
> ROX-20783: add secret informer wrapper

- ui/apps/platform/eslint.config.js
- ui/apps/platform/src/hooks/useTabs.test.js
- ui/apps/platform/src/services/AuthService/AccessTokenManager.js
A recent change to an `import` statement caused an error from import/no-duplicates rule when cherry-picked into a patch release branch.
We replaced airbnb import config with import errors config in #8629
There is a loophole because of rules in airbnb import config that are not in import errors config.
It is complicated to understand which files were checked according to which config from classic eslintrc.js file.
Although I do not see where classic eslintrc.js file turned off, from number of errors, it is obvious that we did not enforce the following rules:
* import/no-named-as-default
* import/no-named-as-default-member
1. Add rules to close loophole.
2. Fix errors from import/no-duplicates rule:
* Add disable comment in AccessTokenManager.js file out of an abundance of caution.
* Merge …
> chore(ui): Fix errors and close loophole in import lint rules

- ui/apps/platform/eslint.config.js
- ui/apps/platform/src/Containers/Clusters/ClustersPage.tsx
- ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicyCategoryChart.tsx
- ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
- ui/apps/platform/src/Containers/Policies/Modal/DuplicatePolicyForm.tsx
- ui/apps/platform/src/Containers/Policies/PolicyPage.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/TableModal.tsx
- ui/apps/platform/src/Containers/Policies/policies.utils.ts
- ui/apps/platform/src/Containers/Violations/Details/ViolationDetailsPage.tsx
- ui/apps/platform/src/Containers/VulnMgmt/Reports/Form/NotifierSelection.tsx
- ui/apps/platform/src/hooks/useWidgetConfig.ts
- ui/apps/platform/src/utils/chartUtils.ts
We disabled some rules to limit the number of changes in #8629
1. To expedite turning on this rule, I added disable comments where I am not sure about types:
* `handler` argument in `DuplicatePolicyForm`
* `targetProps?.datum?.xName` in ViolationsByPolicyCategoryChart
2. TypeScript errors related to `ClientPolicy` and `Policy` were confusing.
Although I think some of the type declarations are incorrect, I added `as unknown` idiom which we can find in the future to sort it out.
* `yarn build` displays only the first error.
* `yarn start` displays some errors in its overlay.
* Visual Studio Code displays errors only for open files. The delayed cause and effect between errors felt like dominos falling in slow motion.
3. `yarn start` in …
> chore(ui): Fix errors and turn on no-explicit-any lint rule

- central/notifier/processor/singleton.go
- central/notifiers/awssh/notifier.go
- central/notifiers/cscc/cscc.go
- central/notifiers/email/email.go
- central/notifiers/generic/generic.go
- central/notifiers/jira/jira.go
- central/notifiers/pagerduty/pagerduty.go
- central/notifiers/splunk/splunk.go
Fix to spew out error instead of crashing if notifiers cannot be secured
Eyeball only
> ROX-21183: Spew error instead of crashing if notifiers are not secured

- central/externalbackups/plugins/gcs/gcs.go
Use the STS client manager in GCS backup integrations. If the feature flag is disabled we revert to the previous client based on default credentials. However, we now add the proxy transport by default.
* CI
* manual e2e test w/ both WIF config and static service account credentials.
> ROX-20786: use GCP STS client in GCS backup integration

- .github/workflows/lint.yml
- .github/workflows/style.yaml
- .openshift-ci/.gitignore
- .openshift-ci/.pylintrc
- .openshift-ci/Makefile
- .openshift-ci/README.md
- .openshift-ci/base_qa_e2e_test.py
- .openshift-ci/ci_tests.py
- .openshift-ci/clusters.py
- .openshift-ci/common.py
- .openshift-ci/compatibility_test.py
- .openshift-ci/dev-requirements.txt
- .openshift-ci/get_latest_helm_chart_versions.py
- .openshift-ci/post_tests.py
- .openshift-ci/runners.py
- .openshift-ci/tests/test_clusters.py
- .openshift-ci/tests/test_runners.py
- Makefile
- scripts/ci/jobs/gke_upgrade_tests.py
- scripts/ci/jobs/gke_version_compatibility_tests.py
- scripts/ci/jobs/ibmcloudz_qa_e2e_tests.py
- scripts/ci/jobs/ocp_sensor_integration_tests.py
- scripts/ci/jobs/powervs_qa_e2e_tests.py
When we migrated to openshift-ci with the .openshift-ci Python layer we described tooling for style and lint but did not enforce it resulting in some understandable drift. This PR rectifies that with style (PEP8/pycodestyle) and lint (pylint) checks. And fixes existing style and lint issues.
> chore(CI): Add python dev tooling for openshift-ci

- pkg/kubernetes/annotations.go
Small thing noticed when using tekton is that it will append the hash into an annotation. This forces the storage of the object even if there isn't a change in our representation of it
Trivial
> chore(perf): Ignore tekton last applied hash annotation

- image/templates/helm/shared/config-templates/scanner-v4/matcher-config.yaml.tpl
- image/templates/helm/shared/templates/02-scanner-v4-05-indexer-network-policy.yaml
1. Add the configuration to the Matcher to access IR from the Indexer.
2. Update the network policies to allow these calls.
Calls to Match vulnerabilities in Central will now accept the Index Report content in the API but instead pull the Index Report directly from the Indexer.
```
bin/linux_amd64/roxctl helm output central-services \
--image-defaults=development_build \
--debug \
--debug-path image \
--remove \
--output-dir /home/jvdm/stackrox-infra/minikube/rox-deploy/charts/central-services
```
Then, I verified the helm chart was configured as expected. I did not deploy this, yet.
performed one does not seem sufficient. As …
> fix: Configure Matcher to pull IR from Indexer

- central/postgres/pruning.go
- central/postgres/pruning_test.go
- central/pruning/pruning_test.go
There is a periodic pruning job that deletes listening endpoints that have a deploymentid that does not match any of the ids in the deployments table. However, currently the listening endpoint is only deleted if the PodUid is not null. This was done as a result of a conversation in this PR https://github.com/stackrox/stackrox/pull/8171. It would be better if the check for the existence of a PodUid were removed, so that more stale listening endpoints are removed. …
> fix: Prune listening endpoints by deploymentid even if poduid is null

- pkg/tlsutils/dial_context.go
- pkg/tlsutils/dial_context_test.go
This PR adds functionality to `tlsutils` that will return a custom error message instead of an error returned by the library. An error produced by the library could contain information we do not want to propagate to UI (API caller).
1. Added unit test
2. Tested API call:
Example response:
```
"message": "failed to determine scanner cert expiry error: failed to contact scanner at https://scanner.stackrox.svc:8080: unable to establish a TLS-enabled connection",
```
In …
> ROX-20876: Adjust returned errors from tlsutils

- image/templates/helm/stackrox-central/internal/defaults.yaml.htpl
Through light usage the Scanner V4 PVC was filling up, this PR increases the PV size from `10 GiB` to `50 GiB`
```
2023-11-30 18:00:01.598 UTC [23] FATAL:  the database system is starting up
2023-11-30 18:00:08.156 UTC [16] PANIC:  could not write to file "pg_wal/xlogtemp.16": No space left on device
```
```
sh-4.4$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         128G   17G  112G  13% /
tmpfs            64M     0   64M   0% /dev
tmpfs           6.3G   64M  6.3G   1% /etc/hostname
tmpfs           250M     0  250M   0% /dev/shm
/dev/sda4       128G   17G  112G  13% /etc/hosts
/dev/sdb        9.8G  9.8G  9.9M 100% /var/lib/postgresql/data
tmpfs           4.0G   12K  4.0G   1% /run/secrets/stackrox.io/certs
tmpfs           4.0G   20K  4.0G   1% …
```
> fix(scannerv4): Increase default scanner v4 DB PVC size

- central/compliance/data/factory.go
- central/compliance/data/mocks/factory.go
- central/compliance/data/repository.go
- central/compliance/framework/data.go
- central/compliance/framework/mocks/data.go
- central/compliance/manager/data_promise.go
- central/compliance/manager/manager_impl.go
There are two sets of data promises in the current compliance code, but they are deduped on if they have been instantiated. Once the compliance operator was added, both data promise paths are hit. The one that pulls the data right away and starts running and the other that waits until a scrape comes back. This results in _most_ of the same data going into the data repo twice costing twice the memory. This change dedupes the common data in those promises by wrapping it with a once.
Ran compliance on openshift with the compliance operator prior to this change and logged that the data repo was instantiated twice. Now with logs it is instantiated once.
In addition to reviewing code here, reviewers **must** also review testing and request …
> fix(perf): Reduce memory usage for compliance runs

- central/notifiers/awssh/notifier.go
- central/notifiers/awssh/notifier_test.go
Add STS support to the AWS SH notifier and correctly set up the client during creation.
1. Create a sample AWS SH notifier with STS enabled
```json
{
"id": "",
"name": "sts-security-hub",
"type": "awsSecurityHub",
"uiEndpoint": "https://<central-endpoint>",
"awsSecurityHub": {
"region": "us-east-1",
"credentials": {
"stsEnabled": true
},
"accountId": "<account-id>"
}
}
```
2. Ensure that the test functionality works as expected (i.e. go to `Integrations -> AWS SH -> Click Edit -> Click Test`)
performed testing and …
> ROX-20787: Add STS to AWS SH notifier

- central/main.go
- central/notifier/datastore/telemetry.go
Add telemetry for collecting the total number of notifiers, the different types of notifiers, and WIF / STS enabled notifiers.
This is within the scope of the feature of cloud credentials support (i.e. adding WIF / STS support to certain integrations).
N/A
> chore(notifiers): Add telemetry for notifiers

- pkg/cloudproviders/gcp/storage/factory.go
I tracked down the API response time observed in ROX-21188 - other than the one caused by the `FindDefaultCredentials` call - to the http client in
```
return storage.NewClient(ctx, option.WithHTTPClient(&http.Client{Transport: transport}))
```
It seems the response time increase occurs when using a custom http client on OCP 4.11. The custom http client is used to inject the stackrox proxy configuration. The google SDK presently does not provide a better way to configure a proxy. This PR removes the proxy config until either the problem is better understood and we find a different solution. Also note that proxies configured via the common env vars should still work out of the box.
In the meantime this should unblock CI and prevent the response time jump.
If any of these don't apply, …
> ROX-21188: remove http proxy

- sensor/common/clusterentities/metrics/metrics.go
- sensor/common/clusterentities/store.go
- sensor/kubernetes/listener/resources/deployments.go
- sensor/kubernetes/listener/resources/metrics/metrics.go
- sensor/kubernetes/listener/resources/pod_store.go
The hierarchy was getting removed before processing the event in the deployment dispatcher. This led to a memory leak in the `PodStore` and the `EntityStore` if a deployment was scaled down (or a pod crashes, gets reschedule, etc).
The following is an example of how to reproduce this leak (the metrics in the first commit of this PR are needed):
- Deploy ACS
- Apply the following yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx-deployment
labels:
app: nginx
spec:
replicas: 10
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- name: nginx
image: nginx:1.14.2
ports:
- containerPort: 80
```
- Observe the pods running:
```bash
NAME                               READY   STATUS    RESTARTS   AGE
nginx-deployment-cbdccf466-95p77 …
```
> fix(leak): Remove pod was not working if the pod has owners

- sensor/kubernetes/fake/flows.go
Currently the number of open listening endpoints added by the fake workload generator in sensor is limited to endpointPool.Capacity, which is set to 10000. The main objective of this PR is to be able to add an arbitrarily large number of open listening endpoints to the central database using  the fake workload generator in sensor.
Another issue is that in production, many listening endpoints do not have an associated process indicator in the central database. However, in the fake data generated by sensor listening endpoints are always associated with process indicators. This PR makes it so that half of the listening endpoints generated by the fake load generator added to the central database are not associated with process indicators.
~~- [ ] …
> ROX-20731: Improve scale tests for listening endpoints

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
Disables the cache for the CVE list query on the Workload CVE deployments page. Preventing Apollo from caching this data removes the bug where data is duplicated across every row in the table.
Visit a deployment detail page in Workload CVEs. Severity, status, and affected component should not be the same for every row in the table.
Before:
After:
> ROX-21185: Disable apollo cache for deployment page query

- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCancelButtonModal.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestDenialButtonModal.tsx
- ui/apps/platform/src/services/VulnerabilityExceptionService.ts
This PR adds the ability to cancel requests. The cancel button will show up on the Request Details page on the following conditions:
1. The user is the requester
2. The request is either in the `PENDING` or `APPROVED_PENDING_UPDATE` status
The cancel button shows up in the top right section
Clicking on the button will show a modal. The modal will display an alert that gives a little warning and shows how many CVEs are in the request and how many Images it will affect.
If the request was canceled, you'll be navigated back to the pending requests table. NOTE: This may change depending on UX decision here https://redhat-internal.slack.com/archives/C03JMGWJYMD/p1701372644906699.
> ROX-19385: Add flow for cancelling request

- ui/apps/platform/src/Containers/Policies/Wizard/Step3/policyCriteriaDescriptors.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/policyValidationSchemas.ts
This issue was noticed while testing other aspects of policies.
> If I select Mount Propagation criteria and drag it to the policy section area then I can press Next and continue (but it's an error since I need to have values in there).
>
> However if I select a value from the drop (or even multiple ones), the Next button is disabled.
>
> It's the opposite logic of what should be. Interestingly, if I select a value and then clear it, the Next button is not re-enabled (which is correct).
When the Policies section was migrated to PatternFly, the only front-end validation we were doing to enable the next button was to make sure you had at least one field in each "group" added. When we added the Image Signature field later, we wrote a custom validation function for it, but that seems to have …
> ROX-16831: Fix UI validation for mount propagation policy criterion

- ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaFieldInput.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaFieldSubInput.tsx
- ui/apps/platform/src/Containers/Policies/Wizard/Step3/PolicyCriteriaForm.css
Heavy is the hand that wields the CSS. (or something like that)
This adds a very specific CSS rule to make the option buttons wrap when the option names are long.
It also fixes some select menus for policy criteria options getting cut off, which I noticed while testing every policy field to make sure my new CSS rule didn't break anything. (My first attempt at rule had broken something.)
Before
After
Other buttons in field inputs are not affected (example, the button labelled "Select" here)
Correct select options menus that are no longer being cut off
performed …
> ROX-16830: Fix policy criteria buttons being cut off

- qa-tests-backend/src/test/groovy/TLSChallengeTest.groovy
We've seen timeouts / io.Exceptions within the test cleanup when assessing whether we currently run on OpenShift 3.11.
The main issue is that the Central deployment gets restarted, and we only verify whether the pods are ready. This doesn't necessarily mean that the API server is started and served already, which may take some time.
Added another step of waiting for the metadata service results before attempting to bounce Sensor to ensure the Central API is reachable and avoid any exceptions / timeouts.
- see CI. …
> ROX-20339: Fix TLSChallenge timeout

- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageComponentVulnerabilitiesTable.tsx
- ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ComponentLocationTd.tsx
Adds component source to Workload CVE tables. The "Location" field was also wrapped in `<Truncate>` to prevent forcing the parent table off screen.
Tables with an image context:
Tables without an image context:
Location tooltip:
> ROX-20575: Add source column to embedded vuln tables

- .github/workflows/labeler.yaml
Reverts stackrox/stackrox#8929 as it's failing with 
```
Error: TypeError: Input does not meet YAML 1.2 "Core Schema" specification: sync-labels
Support boolean input list: `true | True | TRUE | false | False | FALSE`
Error: Input does not meet YAML 1.2 "Core Schema" specification: sync-labels
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```
> chore(deps): Revert bump actions/labeler from 4 to 5

- qa-tests-backend/src/test/groovy/K8sRbacTest.groovy
Sensor does not trigger changes on simple rule reordering, but the cluster version operator reorders the rules (investigation pending) so do a naive comparison check for the test
CI test
> fix(test): Fix RBAC test by making it order agnostic

- scripts/ci/jobs/gke_scanner_v4_tests.py
- scripts/ci/logcheck/restart-ok-patterns.json
- tests/e2e/run-scanner-v4.sh
We have recently merged a change containing the first step towards Scanner V4 tests running in CI.
After the required changes to support this the test were merged to the `openshift/release` repo we were able to actually execute the test and fix the remaining issues currently preventing this test from passing. This PR contains the required changes for allowing this test to pass.
Follow-up PRs are planned for adding test cases to the new Scanner V4 test.
This just fixes a new CI test.
> ROX-19053: Wrap up first Scanner V4 Deployment test executing in CI

- qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy
The failure is caused by "deployment not found" and hence adding wait for deployment.
provided convince any reviewer or any external reader that you did enough to validate your …
> ROX-20015: Wait for deployment before getting process baseline

- scanner/Makefile
#8445 moved the location of the postgres config files to conform to current StackRox deployment conventions. Moving these files means we cannot run `make -C scanner e2e-deploy` anymore, though, so this PR updates this `make` target to copy the files from the new location.
`make -C scanner e2e-deploy`. You'll find the files are copied over correctly.
In addition to reviewing code here, reviewers **must** also review testing …
> chore(scanner): copy postgres configs from new location

- image/templates/helm/shared/templates/_image-pull-secrets.tpl
- image/templates/helm/stackrox-central/templates/_init.tpl.htpl
- image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
- pkg/helm/charts/tests/centralservices/testdata/helmtest/image-pull-secrets.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/image-pull-secrets.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-slim.test.yaml
- pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/suite.yaml
No change in functionality.
The goal of this PR is to:
- reduce the implicit coupling between the `srox.configureImagePullSecrets*` functions by merging them
- simplify and reduce the number of test cases for pull image secret related features
This further paves the road to the fix for ROX-9156, which will necessarily introduce another dimension in this space: the existence vs non-existence of certain `Secret` resources.
Similar to #8804 I recommend looking at individual commits, as their messages explain the rationale behind each change.
performed …
> ROX-9156: another round of pre-factoring

- central/image/service/service_impl.go
A race condition existed in delegated scanning, believe this fix addresses the race condition - however we were not able to reproduce the exact `panic` which triggered the investigation.
Deployed `main:4.3.x-nightly-20231207-rcd` nightly and triggered parrallel delegating scans via `roxctl` on fresh start, produced the below trace.  After some time ability to reproduce lessened.
```
delegatedregistryconfig/delegator: 2023/12/07 16:53:33.245292 delegator.go:112: Info: Sent scan request "67591ecb-a274-49f2-9b46-544e83c163fa" to cluster "fb849453-4155-44a5-9868-e4d8e6309a85" for "docker.io/library/nginx:latest" with inferred namespace ""
==================
WARNING: DATA RACE
Read at 0x00c010775320 by goroutine 226555: …
```
> fix(delegator): Clone image built in enricher

- scanner/e2etests/testdata/image_tests.json
- scanner/mappers/mappers.go
- scanner/mappers/mappers_test.go
This patch addresses an issue when parsing the value for the `FixedInVersion` from ClairCore vulnerability reports where the data was not handling certain cases correctly:
1. **Enhanced Parsing of `fixedInVersion` Field**: In `mappers.go`, a new function `fixedInVersion` has been added. This function addresses a parsing issue where `FixedInVersion` values were incorrectly handled when URL-encoded or needed to be extracted from the `Range.Upper` field.
1. **Updated Unit Tests**: New test scenarios in `mappers_test.go` ensure that the `fixedInVersion` function accurately handles different formats of the `FixedInVersion` value. The `image_tests.json` file has been updated to correct an outdated and incorrect description for CVE-2021-41411. …
> fix(scanner): Fix FixedInVersion parsing
