stackrox/stackrox

.github/dependabot.yaml
Limit of 1 is a bit problematic. Currently we have one PR open for operator tools that is failing CI and no new PR could be opened. If we increase this limit than we can have more PRs open at the same time.
Refs: 
- https://github.com/stackrox/stackrox/security/dependabot/204
- https://github.com/stackrox/stackrox/pull/8406
=> fix(ci): increase dependabot limits

image/templates/helm/shared/templates/02-scanner-v4-07-db-deployment.yaml, scanner/Makefile, scanner/e2etests/helmchart/templates/db-deployment.yaml, scanner/image/db/.gitignore, scanner/image/db/Dockerfile, scanner/image/db/scripts/docker-entrypoint.sh, scanner/image/db/scripts/init-entrypoint.sh
Various updates:
* Use the PGDATA environment variable instead of the hardcoded value
* Use the POSTGRES_PASSWORD_FILE environment variable instead of the hardcoded value
* Part of this was also to create a unique init-entrypoint.sh script for Scanner v4 DB to give Scanner v4 DB independence from Central DB. This file also uses an env var instead of of hardcoding `scram-sha-256`
* Remove PGDATA from Dockerfile, as it's not needed
* Add env vars to Scanner v4 test Helm chart, as downstream Scanner v4 DB failed to start without these changes (does not have PGDATA hardcoded into the Dockerfile)
* Other Helm chart updates
Note: I considered changing PGDATA from `/var/lib/postgresql/data/pgdata` to the typical `/var/lib/pgdql/data`, but this had permission issues in the downstream image …
=> chore(scanner): misc Scanner v4 DB updates

qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy
This change increase the time out for process baseline test. The value is in align with what is used in RiskTest.
provided convince any reviewer or any external reader that you …
=> fix(test): Increase time out for process baseline delete test

qa-tests-backend/src/main/groovy/services/NetworkGraphService.groovy
This could help limit the ExternalNetworkSourcesTest failing with `io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 4210009`.
=> fix(e2e-tests): Fix RESOURCE_EXHAUSTED in e2e NWG tests 

ui/apps/platform/config-overrides.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js, ui/apps/platform/eslint.config.js, ui/apps/platform/src/Components/visuals/Sunburst.js, ui/apps/platform/src/global/initializeAnalytics.js
Follow up residue for eslint-config-airbnb-base after #8813
If software quality criteria becomes less strict, then cherry pick of commits into patch release branches might report errors according to earlier configurations and versions of devDependencies.
Usually software quality criteria has become more strict in ESLint, Prettier, and TypeScript, therefore when an upgrade causes many errors, it is possible to fix them **in batches**, because the changes are **not errors**  according to earlier configurations and versions of devDependencies.
However, deleting airbnb config opened a loophole:
* Some rules had been turned on, **but are not now**.
* However, some of them are deprecated because redundant with Prettier.
The following do not require any change:
* Some rules had been turned on, …
=> chore(ui): Fix errors and close loophole in airbnb-base lint rules

ui/apps/platform/src/Containers/ComplianceEnhanced/Status/Dashboard/Widgets/HorizontalBarChart.tsx, ui/apps/platform/src/Containers/Dashboard/Widgets/AgingImagesChart.tsx, ui/apps/platform/src/Containers/Dashboard/Widgets/ComplianceLevelsByStandardChart.tsx, ui/apps/platform/src/Containers/Dashboard/Widgets/ViolationsByPolicyCategoryChart.tsx
The recommendation from the PatternFly team to upgrade to the latest PF-charts library did not make a difference on the broken charts, so I opted to disable animations entirely.
Load the dashboard without interacting with the charts:
Load compliance 2.0 without interacting with the charts:
=> ROX-21219: Disable animations for PF charts

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js
Fixes a recent text change resulting in a 100% failure rate of CVE Exception related e2e tests.
=> test(ui): Update e2e test text selection for workload cves

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx
Fixes a related cache issue on the Workload CVE deployment page. This issue can be reproduced by the following:
- Visit an individual Workload CVE Deployment page
- Perform an action that causes a second request to be sent (change the page, change the perPage, sort a column, etc.)
- The correct data will be displayed in the table
- **Wait between 5 and 30 seconds**
- Another request is sent, which ignores the `fetchPolicy: 'no-cache'` option, updates the cache and displays invalid data.
_I don't know exactly why this occurs, or why this fix is the answer._ I can reliably reproduce the behavior before/after the change, and it reliably only happens on the Deployment single page.
Before this change:
Visit a deployment page:
Set the perPage …
=> fix(ui): Disable cache for nextFetchPolicy on deployment page

sensor/common/sensor/central_communication.go, sensor/common/sensor/central_communication_impl.go, sensor/common/sensor/central_communication_test.go, sensor/common/sensor/sensor.go
Some components might benefit from knowing when the sync with Central has finished (see [this comment]( https://github.com/stackrox/stackrox/pull/8889/files#r1422707054)).
performed testing and …
=> feat(notify-sync): notify components when the sync is done

ui/Makefile
This reverts commit 6d53f574a3d4485a7a4b755de4387dc248e21b2c.
Revert a prior commit that caused UI tests to generate coverage file in CI. Keeps the change to the `apps/platform` directory.
I did not revert https://github.com/stackrox/stackrox/pull/8948 as it seems like that was a fix that is independent of the codecov integration and something we want to keep.
=> chore(ui): Revert "collect coverage for UI unittests"

qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
Give it a range so that changes by a few won't trigger a failure
responsible for …
=> ROX-21380: Update number of components in risk factor test

qa-tests-backend/src/test/groovy/K8sRbacTest.groovy
I've checked the successful runs of this test and it passes in a first try. That's why I've changed the way we wait and reduce number of retries and increase sleep time to not pollute logs but give more time for API to populate data.
It is acceptable to skip testing in cases when CI is sufficient, or it's a …
=> ROX-19855: increase waiting time for role

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageResources.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageResources.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx
Fixes a bug where moving to a page > 1 on the Vulnerabilities tab of an Image/Deployment page and then clicking on the Resources tab would not reset the page number. This led to an empty table in most cases, even when there was valid data.
This is fixed by moving the `useUrlPagination()` call up to the parent component, and passing the result down to each of the Vulnerabilities and Resources tabs. Previously, each of the tabs individually called this hook and made the page reset on tab change inaccessible.
Visit an image detail page, and progress the table to a page beyond the first.
Click the Resources tab and verify that the page is reset to page 1.
Repeat the above procedure on a deployment detail page.
=> ROX-21144: Reset pagination between vulns and resource tabs

operator/pkg/central/reconciler/reconciler.go, operator/pkg/proxy/translation.go, operator/pkg/proxy/translation_test.go, operator/pkg/securedcluster/reconciler/reconciler.go, operator/pkg/securedcluster/values/translation/translation.go, operator/pkg/values/translation/enricher.go, operator/pkg/values/translation/enricher_test.go
This refactors the way proxy-related env vars are being injected into helm values after the translator runs.
Previously this was achieved by having `proxy.InjectProxyEnvVars` take care of invoking the wrapped translator, and then massaging the resulting helm values. A fix for ROX-9156 that is in the works will need to add a similar piece of functionality, in the sense that it will also need to post-process the values. In order to avoid having to construct a matryoshka-style stack of translators with duplicated logic, this change introduces a `WithEnrichment` function which takes care of invoking the translator and then running any number of "enricher" objects that just massage the resulting values.
It also:
- simplifies `getProxyConfigHelmValues` by making impossible for it to return an …
=> refactor(operator.pkg): introduce helm values enrichers.

tests/e2e/lib.sh, tests/e2e/yaml/compliance-operator/catalog-source.yaml, tests/e2e/yaml/compliance-operator/subscription.yaml
Previously, we were installing the complinace operator from downstream sources using a subscription, which is fine, but installing from upstream sources gives us earlier access to upstream features that haven't been released downstream yet.
This is useful for integration work where ACS relies on compliance operator features that aren't available downstream yet. This also gives us early feedback for any compliance operator features or fixes that may break integrations in ACS.
View the compliance integration job logs to make sure the Compliance Operator is being installed from upstream (ghci.io) instead of downstream Red Hat sources.
In addition to reviewing code here, reviewers **must** also review testing and request further testing in …
=> ROX-21409: Install compliance operator from upstream sources

central/signatureintegration/datastore/validate.go, pkg/booleanpolicy/value_regex.go, pkg/signatures/types.go, pkg/signatures/types_test.go
These changes move `signatureIntegrationIDPrefix` to a common location to reuse between `central/signatureintegration/datastore/validate.go` `pkg/booleanpolicy/value_regex.go`
See added unit test.
=> ROX-9716: move signatureIntegrationIDPrefix to common location

sensor/kubernetes/complianceoperator/updater.go, sensor/kubernetes/complianceoperator/updater_test.go
Fix an evaluation condition for compliance CRD, now it returns the correct evaluation.
Unit tests, also deployed and tested the patch on a cluster
* Added mock test for testing following cases in sensor:
* All required CRDs exist, and it should not have any errors
* One required CRD is missing, and it should contains the missing crd kind in the error
* Required Kinds list is empty, and it should return errors
tested on a cluster with the patch:
```
[vincent@node workflow]$ roxcurl /v2/compliance/integrations | json_pp
{
"integrations" : [
{
"clusterId" : "a6a8c1d2-2b6e-4d0b-830e-3acdd2df5e59",
"clusterName" : "remote",
"id" : "329572d4-6178-471f-91f0-e453f0cdbddd",
"namespace" : "openshift-compliance",
"statusErrors" : [],
"version" : "" …
```
=> ROX-21213: Fix Compliance operator status errors regarding CRDs

.github/workflows/backport-pr.yaml
Per title. Adding a release to a PR e.g. `backport release-4.3` will cause the PR to be backported to release branch once merged or after merge if the label is added after merge.
None. Reviewed https://github.com/tibdex/backport, Will fork and reassess if this does not work as expected.
=> chore(release): add a PR backport action

qa-tests-backend/src/test/groovy/ImageScanningTest.groovy, tests/e2e/run-e2e-tests.sh
The current image (struts-app) gets a 520 response from quay. This causes the ImageScanningTest testcase to fail by reaching the 800s global timeout. This causes subsequent tests to fail (ImageIntegration, VulnMgmtTest) as the quay integration is not deleted when the global timeout is reached. A future PR/issue will address fixing that.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-ocp-4-11-merge-qa-e2e-tests/1735366241893224448
Tested locally and CI.
=> fix(CI): use a different image for quay scans

image/templates/helm/stackrox-central/templates/NOTES.txt.htpl
There's no `._rox._namespace` property in the Central helm chart, it exists only in the secured cluster services chart. Therefore, the modified condition doesn't make sense because `._rox._namespace` is not defined.
In older versions of helm (3.7.2) the installation fails with the following error:
```
Error: UPGRADE FAILED: template: stackrox-central-services/templates/NOTES.txt:10:75: executing "stackrox-central-services/templates/NOTES.txt" at <ne .Release.Namespace ._rox._namespace>: error calling ne: incompatible types for comparison
```
```
docker run -it --rm -v "$(pwd):/usr/src/stackrox" quay.io/stackrox-io/roxctl:$(make tag) helm output central-services --image-defaults opensource --output-dir …
```
=> fix(helm): remove helm release namespace note from the central chart

qa-tests-backend/src/main/groovy/services/ComplianceService.groovy, qa-tests-backend/src/main/groovy/services/GraphQLService.groovy
For some reason when HTTP client encourage an error we only log it and return empty response. This makes addresing CI failure problematic as failing assertion might be misleading and the root cause of the problem is in the log. This PR replaces this behaviour with not catching exception at all and allowing it to bubble up to a test so it will be obvious why test failed.
Another change to minimize networking issues negatively impacting our test success rate this PR adds retrying of failed request either for IO exception as well as 501 errors.
CI …
=> ROX-17185: retry gql queries in e2e tests

scripts/run-support-triage-report.sh
It turns out I've used wrong jira filter
1. [Current On-Call Bugs to Triage r2](https://issues.redhat.com/browse/ROX-21444?filter=12388044)
2. [Previous On-Call Untriaged Bugs r2](https://issues.redhat.com/browse/ROX-21382?filter=12388046)
instead of
1. [Add this filter to your favorites Current On-Call Queue to Triage / ROX](https://issues.redhat.com/browse/ROX-21446?filter=12413623)
2. [Untriaged Bugs from Previous On-Call Week / ROX](https://issues.redhat.com/browse/ROX-21381?filter=12413975)
run script locally and check the numbers
```
./scripts/run-support-triage-report.sh
Posting '<!subteam^S04SU9AHJ4C> There are 47 untriaged issues (not including 15 leftovers from previous duty)' to slack
./scripts/run-support-triage-report.sh: …
```
=> fix: use proper jira filters

ui/apps/platform/cypress/integration/integrations/notifiers.test.js
Test is failing on ocp-11 and ocp-13 although not gke after #9068
Temporarily skip over the weekend pending investigation about need to enter data in another field of the form.
=> chore(ui): Skip ui-e2e test for Google Cloud SCC integration

ui/apps/platform/package.json, ui/yarn.lock
https://github.com/prettier/prettier/blob/main/CHANGELOG.md#311
1. https://github.com/prettier/prettier/blob/main/CHANGELOG.md#fix-unstable-and-ugly-formatting-for-comments-in-destructuring-patterns-15708-by-sosukesuzuki
> Fix unstable and ugly formatting for comments in destructuring patterns
This sounds familiar.
2. https://github.com/prettier/prettier/blob/main/CHANGELOG.md#support-import-attributes-15718-by-fisker
> TypeScript 5.3 supports the latest updates to the import attributes proposal.
2. `yarn build` in ui/apps/platform
=> chore(ui): Update prettier 3.1.1 devDependencies in ui

ui/apps/platform/cypress/helpers/fakeGCPServiceAccount.js, ui/apps/platform/cypress/integration/integrations/notifiers.test.js
With #9002 we perform a validation of the service account JSON via the google client on the backend. So far the UI e2e tests have provided an invalid service account JSON (`"type": "service_account"` without valid `"private_key"`). This is fixed by passing a prepared valid but fake service account JSON lifted from https://github.com/google/oauth2l/blob/e2ff2cc6d1b42f9fc26211dc15890772ec62fdd9/integration/fixtures/fake-service-account.json.
CI should pass
=> ROX-21446: fix scc ui e2e test

central/declarativeconfig/manager_impl.go, central/declarativeconfig/watch_handler.go, qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
This PR includes fixes for two flakes within declarative config tests, which are loosely related.
The main issue between both seems to be that the lock wasn't held for the complete critical section, which could lead to rare overwrites.
The locks have been fixed, and the timeout has been slightly increased as well for the E2E test.
- affected unit test run 10000x without failures.
=> ROX-17800,ROX-19883: Fix declarative config test flakes

operator/tests/common/central-cr.yaml, operator/tests/common/image-pull-secrets.yaml, operator/tests/common/secured-cluster-cr.yaml
There are several "magic" secret names that are referred to by our ServiceAccounts. `stackrox` is one of them.
This change to switch to an explicitly named, non-magic secret is in preparation for a ROX-9156 bugfix, which will remove references to non-existing magic secrets and add e2e test steps checking effects of addition and removal of "magic" secrets.
CI is enough.
=> test(operator): use an explicit image pull secret

sensor/kubernetes/eventpipeline/pipeline_impl.go, sensor/kubernetes/eventpipeline/pipeline_test.go
In order to capture runtime events while Sensor is offline, we need to maintain the resource stores populated and the dispatchers running. The context will be cancel for the listeners when Sensor goes offline, this ensures no new messages are queued or sent while Sensor is offline.
In addition to reviewing code here, reviewers **must** also review testing and request further …
=> ROX-21384: Stop listeners 'on reconnect' instead of 'on disconnect'

pkg/grpc/authn/basic/extractor.go, pkg/grpc/authn/extractor.go, pkg/grpc/authn/extractor_test.go, pkg/grpc/authn/interceptor.go, pkg/grpc/authn/service/extractor.go, pkg/grpc/authn/servicecerttoken/extractor.go, pkg/grpc/authn/tokenbased/extractor.go, pkg/grpc/authn/userpki/extractor.go
This PR improved auth interceptor logging. It introduces a new struct that will keep the original error and the message propagated to the API/UI user. With this, we are ensuring the following:
- we are going to log errors with complete information
- we will not expose sensitive information to the API/UI user
Changes made:
- added error struct that keeps root error and additional message
- added logging of error struct that will log the underlying error
- covered the situation that frequent/expected token expired is logged as debug
- changed `basic` extractor to return nil if an error occurred
- tweaked debug log in service token extractor
**Consideration**
If we doubt that logs could still be noisy, we can increase the rate limit period to 1min or 5min instead of 10sec.
- ~[ ] Evaluated …
=> chore(fix): Improve auth interceptor logging

sensor/common/sensor/sensor.go
Do not lock before the select.
=> fix(notify-sync): Do not lock before the select

central/detection/service/service_impl.go, roxctl/deployment/check/check.go, roxctl/deployment/check/check_test.go, roxctl/deployment/check/testdata/deployment2.yaml, roxctl/deployment/check/testdata/testMultipleFilesExpectedYaml.yaml
Take multiple yaml files as input to roxctl deployment check --file instead of only a single one.
In order not to break legacy support I decided to add an additional --files flag with this behavior. Let me know in the comments if it would make more sense to also remove the old --file flag, OR to make the --file flag work in the way the --files flag works now.
On a sidenote I also moved the assignment of random IDs for deployments parsed from yaml from the previous PR https://github.com/stackrox/stackrox/pull/8763 to a different spot where I think it makes more sense.
I manually tested roxctl deployment check --files with multiple input files and some print statements and it looks to be behaving as expected to me.
=> ROX-20905: Handle multiple yaml files

scripts/ci/lib.sh
Slack notification on failures is intended for and only supports merge to the main branch failures. Periodics cause: https://redhat-internal.slack.com/archives/CLUNQEEMA/p1702636813795079 due to missing state.
=> fix(CI): skip slack notifications for scheduled jobs

.github/workflows/build.yaml, scripts/ci/lib.sh, scripts/ci/test_state.sh
After #8958 changed the context where slack messages are generated (from the job dispatch step to job end step) we started to get a slack message for every e2e test that fails when images are not built. This was previously ignored by checking for the images available state breadcrumb. This PR moves the breadcrumb to the shared location so it will be available in the end step.
=> fix(CI): reduce image failure e2e test spam

ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleDescription.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleForm.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlePage.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleWizard.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlesHeader.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlesPage.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlesRoute.tsx
Prerequisite to add cluster init bundle wizard, although discussion continues about its contents.
By the way, there is only an endpoint to fetch bundles, not to fetch a bundle by id:
https://github.com/stackrox/stackrox/blob/master/proto/api/v1/cluster_init_service.proto#L82-L86
1. InitBundlePage: Investigate second argument of service function and add confirmation modal for **Revoke bundle**.
2. InitBundlesRoute: Replace replace resources with Admin role.
3. Write integration tests.
In stackrox/ui folder before `yarn deploy`
```sh
```
1. Visit /main/clusters/init-bundles
2. Click link to /main/clusters/init-bundles/id
=> ROX-21127: Refactor cluster init bundles pages

image/templates/helm/shared/templates/_set_install_method.tpl.htpl, image/templates/helm/stackrox-central/templates/_init.tpl.htpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl
In preparation for a fix for ROX-9156, make install method available in both helm charts, such that it can be used by `srox.configureImagePullSecrets` without restrictions.
=> refactor(helm): Set _rox.env.installMethod in both charts.

pkg/helm/charts/tests/centralservices/testdata/helmtest/image-pull-secrets.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/suite.yaml
In preparation for testing a fix for ROX-9156, make these helper functions treat a null list of secrets the same as an empty one, rather than crash.
=> test(helm): Make some functions null-safe.

ui/apps/platform/src/Containers/Collections/CollectionsFormPage.tsx, ui/apps/platform/src/Containers/VulnMgmt/List/Cves/VulnMgmtListCves.js, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useCreateReport.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/api/useRunReport.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/CollectionSelection.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DefaultFilterModal.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/EntityTypeToggleGroup.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/TableEntityToolbar.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/WorkloadTableToolbar.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/FilterAutocomplete.tsx, ui/apps/platform/src/hooks/useAnalytics.ts, ui/apps/platform/src/utils/type.utils.ts
Adds analytics events as described in https://docs.google.com/document/d/1v0z2OK2B5nWmYHh4pNEoVd4YfIW0gOVomf7qgkvND2I/edit
Set the central env var to the development analytics key.
Manual event testing and verification in the analytics dashboard.
Until I have access to share charts more easily - here is a link to internal Slack thread showing the events in Amplitude along with charts for each event type. https://redhat-internal.slack.com/archives/C03JMGWJYMD/p1702567215510979
=> ROX-19790: Add UI analytics for Workload CVEs

central/complianceoperator/v2/compliancemanager/manager.go, central/complianceoperator/v2/compliancemanager/manager_impl.go, central/complianceoperator/v2/compliancemanager/manager_impl_test.go, central/complianceoperator/v2/compliancemanager/mocks/manager.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl_test.go, central/complianceoperator/v2/scanconfigurations/datastore/mocks/datastore.go, central/complianceoperator/v2/scanconfigurations/service/service_impl.go, central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go, central/sensor/service/connection/connection_impl.go
This PR adds Compliance Scan Config deletion to central.
The central will check if a scan config exist in the datastore and we will remove the scan config from the datastore if they do and send the delete message to all cluster. 
Unit-tests and Deployed and tested on a cluster
* Added Unit test DeleteComplianceScanConfiguration in central service
* Added Unit test DeleteScanConfiguration in central manager
* Added mock test for datastore for deleting scan
* Deployed and tested deleting scan on a real cluster
```
[vincent@node stackrox]$ roxcurl /v2/compliance/scan/configurations
{"configurations":[{"id":"c70743cf-05b5-43ff-a7c6-5a43472c3cc4","scanName":"testscan","scanConfig":{"oneTimeScan":false,"profiles":["rhcos4-high"],"scanSchedule":{ …
```
=> ROX-19540: Central Implement a workflow to delete scan config 

.containerignore, .dockerignore, .gitignore, .snyk
The check is enabled if the `snyk-secret` is present in RHTAP. Right now, I removed it to not interfere with other builds.
A process needs to be established to review the findings eventually. 
Two pipeline runs for this PR:
- [Task log (178 issues found)](https://github.com/stackrox/stackrox/files/13658679/operator-on-pull-req …
=> ROX-20237: Enable Snyk SAST scanner in RHTAP

image/templates/helm/stackrox-central/internal/config-shape.yaml
These config shape entries were missing in the previous PR for central-services. …
=> ROX-19048: Add missing Scanner V4 Customization Config Shape to Chart

Makefile, pkg/logging/rate_limited_logger_test.go
I've noticed a flake in the rate_limited_logger, instead of expecting variadic arguments it expected a slice. 
The assertion changed to a slice to match the variadic function arg of the log call.
Secondly the line number of the log line needed to be updated.
```
rate_limited_logger.go:296: Unexpected call to *mocks.MockLogger.Logf([debug %s%s%s /code/pkg/logging/rate_limited_logger_test.go:213 -  This is a template for debug logs with 2 arguments to convert ]) at /code/pkg/logging/rate_limited_logger.go:296 because: 
expected call at /code/pkg/logging/rate_limited_logger_test.go:211 doesn't match the argument at index 2.
Got: [/code/pkg/logging/rate_limited_logger_test.go:213 -  This is a template for debug logs with 2 arguments to convert ] ([]interface {})
Want: is equal to …
```
=> fix(logger): ROX-21493: fix rate limited logger test

deploy/common/ci-values.yaml, image/templates/helm/shared/templates/_scanner-v4_init.tpl.htpl, pkg/renderer/templates/public_values.yaml.tpl, scripts/ci/jobs/gke_scanner_v4_tests.py, tests/e2e/run-scanner-v4.sh
This PR turns the existing minimal Scanner v4 test into a basic Helm upgrade test.
1. CI.
2. Locally:
Source something like this:
```
export ORCHESTRATOR_FLAVOR=k8s
export OUTPUT_FORMAT="helm"
export ROX_SCANNER_V4_ENABLED="true"
export STORE_METRICS="true"
export ROX_POSTGRES_DATASTORE="true"
export ROX_BASELINE_GENERATION_DURATION="5m"
export CI=false
export CHART_REPOSITORY=/tmp/helm-charts
export QUAY_RHACS_ENG_RO_PASSWORD=...
export QUAY_RHACS_ENG_RO_USERNAME=...
export USE_LOCAL_ROXCTL=true
export CURRENT_MAIN_IMAGE_TAG="4.3.x-450-gf976c9f095"
if [[ -z "$KUBECONFIG" ]]; then
echo "set KUBECONFIG"
fi
if [[ ! -x "$(command -v roxctl)" ]]; then
export PATH="$PWD/bin/darwin_amd64:$PATH"
echo "PATH=$PATH"
fi
```
and then execute `tests/e2e/run-scanner-v4.sh` against an Infra GKE cluster …
=> ROX-19054: Add upgrade logic to Scanner V4 CI test

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ViewVulnReport/ReportJobs.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx
Fixes table action menus that are cut off when opened, due to appearing inside the table container.
This fix appends the DOM element to `document.body`, which ensures the element is positioned above the container, even when it would otherwise overflow.
CVE List:
Images List:
Image single:
Vuln Reporting Jobs:
=> ROX-21473: Fix obstructed table action menus in Workload CVEs

ui/apps/platform/eslint.config.js, ui/apps/platform/src/Components/PatternFly/ErrorBoundary/ErrorBoundaryCodeBlock.tsx, ui/apps/platform/src/Containers/Clusters/ClustersSidePanel.tsx, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Collections/CollectionsTable.tsx, ui/apps/platform/src/Containers/Policies/Modal/EnableDisableNotificationModal.tsx, ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.tsx, ui/apps/platform/src/Containers/SystemHealth/DiagnosticBundle/GenerateDiagnosticBundle.tsx
https://typescript-eslint.io/rules/no-floating-promises/
> Require Promise-like statements to be handled appropriately.
> This rule reports when a Promise is created and not properly handled. Valid ways of handling a Promise-valued statement include:
* awaiting it
* returning it
* Calling its `.then()` with two arguments
* Calling its `.catch()` with one argument
The benefit to prevent new errors outweighs cost of TODO comments:
1. ErrorBoundaryCodeBlock
* Replace TODO comment with `addToast` call.
* Factor out `ToastGroup` as suggested by David with props to compose `AlertGroup` and `useToasts` hook.
2. For delete actions, render error in modal.
2. `yarn build` in ui/apps/platform and then compute branch - master for the following in ui:
* `wc …
=> chore(ui): Fix errors and turn on no-floating promises lint rule

ui/apps/platform/eslint.config.js, ui/apps/platform/src/Containers/Policies/policies.utils.ts
Follow up residue for eslint-config-airbnb after #8813
If software quality criteria becomes less strict, then cherry pick of commits into patch release branches might report errors according to earlier configurations and versions of devDependencies.
Usually software quality criteria has become more strict in ESLint, Prettier, and TypeScript, therefore when an upgrade causes many errors, it is possible to fix them **in batches**, because the changes are **not errors**  according to earlier configurations and versions of devDependencies.
However, deleting airbnb config opened a loophole:
* Some rules had been turned on, **but are not now**.
* However, some of them are deprecated because redundant with Prettier.
The following do not require any change:
* Some rules had been turned on, **and …
=> chore(ui): Fix errors and close loophole in airbnb react lint rules

scanner/updater/rhel/parse_test.go, scanner/updater/rhel/parser.go
We want the scores so we can return them to customers. We encode fox maximum flexibility. This is temporary: Once SAF/VEX is ready, we will adopt that.
UTs.
=> ROX-16811: Encode CVSS scores in the RHEL vuln severity field

pkg/centralsensor/caps_list.go, pkg/features/list.go, sensor/common/deploymentenhancer/component.go
Add the flag ROX_CLUSTER_AWARE_DEPLOYMENT_CHECK to be used in Sensor
=> ROX-21197: Add a feature flag for cluster aware checks

central/cve/fetcher/orchestrator.go, central/reprocessor/reprocessor.go, pkg/backgroundtasks/manager_impl.go, pkg/nodes/enricher/enricher_impl.go, qa-tests-backend/test-images/syslog/syslog.go, sensor/common/compliance/auditlog_manager_impl.go, sensor/debugger/central/communicate_server.go
For all non-assignment operations in critical sections, use `With[R]Lock` instead of locking and undeferred unlocking. This way we avoid blocked mutexes, make the code future proof, and reduce the frequency of the undeferred unlocking pattern.
For educational purposes, maybe we should go even further and rewrite all assignments as well to eliminate undeferred unlocking altogether (and create a linter). So instead of:
```
c.lock.RLock()
pod, ok := c.cache[id]
c.lock.RUnlock()
```
something like
```
pod, ok := concurrency.WithRLock2(&c.lock, func() (pod *storage.Pod, ok bool) {
pod, ok = c.cache[id]; return
})
```
CI run …
=> chore: Fewer manual mutex unlocks

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.selectors.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js
Apply's the following changes to the Workload CVE image single page tests in order to reduce CI flakes:
1. Instead of checking the CVE severity counts in each table row to find an image with vulnerabilities, simply apply a filter of `CVE:*`. This will guarantee the table only contains images with vulns, regardless of the feature flag set in use.
2. Instead of finding what severity CVEs are non-zero for the selected image, just apply `Severity:Critical` and test the invariants that would be true for that case, regardless of whether or not that image has Critical CVEs.
Will close
https://issues.redhat.com/browse/ROX-21438
https://issues.redhat.com/browse/ROX-21439
https://issues.redhat.com/browse/ROX-21440
Local Cypress runs with …
=> test(ui): Make image single page tests more robust

ui/apps/platform/cypress/integration/vulnmanagement/entitypages.test.js
Fix for flake: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-ocp-4-11-merge-ui-e2e-tests/1737565432228876288
This occurs when the test selects a deployment from the table that does not have any associated components. This will be the case if:
1. The deployment has no scanned images
2. The deployment image scanning is in-progress
3. The deployment image scanning is complete, but there are no CVEs
This happens because the test selects the first row from the table. In the case of the flake, this is a deployment with images that have not been scanned:
This test has been updated to select the first row of the table that contains an "Image CVEs" cell with a link that contains the text "CVE", which only occurs when the deployment has a scanned image …
=> fix(ui): Select table row containing scanned CVEs

sensor/common/networkflow/manager/manager_impl_test.go
After #8782 was merged a data race was introduce in some of the networkflow manager tests.
=> fix(data-race): fix network flow manager tests

pkg/env/integersetting.go, sensor/common/clusterentities/entity_status.go, sensor/kubernetes/listener/resources/env.go, sensor/kubernetes/listener/resources/store_provider.go
Enabling the history added in #8782.
This allows to get rid of incorrectly reported 'External Entities' on the network graph for cases where Collector Afterglow reports a connection close after the related deployment (source or destination) has been changed (e.g., IP address change for a service) or deleted.
- Manual upgrade steps are not required as default value (used for cases when the env var is missing) will work well.
I tested this setting in #8782.
=> ROX-20716: Enable history for ClusterEntities Store

central/tlsconfig/tlsconfig.go
Reduce the log level for informational logs within the tls config manager.
The main reason is that they will be output quiet frequently (every 5 minutes) and pollute logs with information that isn't necessarily actionable (especially in the context of ACSCS).
Sample logs:
```log
tlsconfig: 2024/01/02 16:33:34.076450 tlsconfig.go:51: Info: Skipping additional CA directory entry "..2023_12_20_15_06_36.451612458" because it is a directory
tlsconfig: 2024/01/02 16:33:34.076550 tlsconfig.go:73: Info: Skipping additional CA file "/usr/local/share/ca-certificates/..data" because it is a symlink that resolved to a directory
tlsconfig: 2024/01/02 16:33:34.077506 tlsconfig.go:155: Info: Default TLS certificate file "/run/secrets/stackrox.io/default-tls-cert/tls.crt" does not exist. Skipping …
```
=> chore(tlsconfig): reduce log noise

qa-tests-backend/src/test/groovy/CertRotationTest.groovy
Add doc that test is only executed in Manifest based environments
=> fix(e2e): Document test is executed in Manifest based environments

.github/workflows/ci-failures-report.yml, scripts/ci/metrics.sh
Change the default to the main eng channel so that the scheduled job (which has no inputs) goes where we want it to.
- https://github.com/stackrox/stackrox/actions/runs/7391734703
- https://redhat-internal.slack.com/archives/CELUQKESC/p1704239761481789
=> fix(CI): send the scheduled report to the correct channel

central/postgres/pruning.go, central/postgres/report_pruning_test.go
PR fixes sql query to get report snapshots that in the pruning window. 
Manual Testing
1.deploy 4.3 acs
2. create report configs and run scheduled email jobs, on demand email and download.
3. set pruning window to 2 days
4. verify that report snapshots in the pruning window are deleted
=> ROX-21048: Fixed report prunning sql query

scanner/decisions/0006-redhat-cvss-scores.md, scanner/decisions/0007-redhat-cvss-scores.md
Introduce decision to use a forked ClairCore repository, temporarily, so we can get Red Hat CVSS scores.
Related forked repo PR: https://github.com/stackrox/claircore/pull/1
No
=> ROX-20835: Red Hat CVSS score ADR

scripts/ci/jobs/ocp_compliance_e2e_tests.py, tests/Makefile, tests/compliance_operator_v2_test.go, tests/complianceoperator/README.md, tests/e2e/lib.sh, tests/e2e/run-compliance-e2e.sh, tests/e2e/run.sh, tests/e2e/yaml/compliance-operator/nist-moderate.yaml, tests/e2e/yaml/compliance-operator/rhcos4-moderate.yaml
Legacy compliance operator testing relies on the ability to install the
operator from source (specifically, GKE integration testing). While the
OpenShift testing uses installs from subscriptions, we can clean up the install
code from the GKE test path.
This patch does a few things:
1. Uses the new ComplianceAsCode/compliance-operator repository
2. Uses `make deploy-local` as the preferred method for deploying the Compliance Operator from source
3. Adds a new environment variable for installing from source so that we can enable source installs for non-OpenShift testing
4. Adds a new set of compliance e2e tests meant to exercise the v2 compliance integration APIs
Subsequent patches can remove the manifests for Compliance Operator CRDs and
resources, since they're likely outdated.
If any of …
=> ROX-18313: Introduce compliance v2 integration test suite 

qa-tests-backend/scripts/lib.sh
Once https://github.com/openshift/release/pull/47162 merges, this will fix the "Groovy Test Logs" links in the prow UI.
Links work.
=> fix(CI): use the correct link to the groovy log

qa-tests-backend/src/test/groovy/ImageScanningTest.groovy
In its current form, if quay is persistently erroring on the scan API call, the retries + pauses of `expectedDigestImageFromScan() + ImageService.scanImage()` will result in the junit global 800s timout being reached before the test gives up. This results in poor state handling in the Groovy test / Spock framework world. (#9059). One option is to increase the globalTimeout for this test as other tests do. But a max of 800s for an image scan response seems already pretty long. So instead this PR follows the option of reducing the retries and pauses between them.
```
=30*(10*15+2)
=4560 seconds <-- without the time in making the API calls
```
```
=3*(10*15+15)
=495 seconds <-- without the time in making the API calls
``` …
=> refactor(CI): change retry/pause for quay test

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesForm.tsx
Removes validation (and error message) from watched image modal when `onBlur` is triggered. This prevents a form error from being displayed when the user opens the modal and removes an image at the bottom of the list. The error will still be visible if the form is submitted with an empty value.
(This is a two-line change that looks larger due for formatting.)
Watch an image via VM 2.0
Open the modal again via the Manage Watched Images button
Remove an image from the list - no error is shown in the input at the top of the modal
Attempt to submit the form with no value:
Submit the form with a valid value:
=> ROX-21469: Remove error message onBlur from watched images modal

Makefile, scripts/ci/jobs/ui-component-tests.sh, ui/apps/platform/package.json, ui/apps/platform/scripts/cypress-component.sh
Adds job configuration to run Cypress component tests via Prow. This job is currently optional and runs only when invoked explicitly.
Kick off prow CI job manually with `/test ui-component-tests`.
Tests complete successfully and:
JUnit output successfully reported in Prow dashboard
JUnit reports uploaded to GCP
Cypress test videos captured and uploaded to GCP
=> chore(ui): Create config for ui-component CI job

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveSingle.test.js
Fixes an occasional e2e test flake on ocp-4-13 when the test hits a deployment with a long-ish name. The long name causes the `<Truncate>` component to split the text into two lines, and the newline character fails when comparing text on the second page.
Create a deployment with a long-ish name and verify the text is split across newlines. Run Cypress test before and after the change.
=> ROX-21437: Fix test failures due to newline character in deploy name

pkg/scannerv4/client/client.go, scanner/indexer/indexer.go, scanner/indexer/remote.go, scanner/matcher/matcher.go, scanner/services/indexer.go, scanner/services/matcher.go
Improve Scanner v4 logging by adding the related hash_id to various gRPC endpoint logs
See the logs
=> ROX-21495: logging improvements

central/risk/multipliers/deployment/process_baseline_violations.go, pkg/env/process_baseline_risk.go
Process baseline risk is consistently one of the most expensive operations against the database, this provides an environment variable to help alleviate it if it's not required from the user. I'll continue to look into optimizing the codepath
Straightforward change
=> fix(perf): Add toggle to disable process baseline risk

central/compliance/checks/common/checks.go, central/compliance/checks/hipaa_164/check308a1iia/check_test.go, central/compliance/checks/pcidss32/check225/check.go, central/compliance/checks/pcidss32/check225/check_test.go, central/compliance/data/repository.go, central/compliance/framework/data.go, central/compliance/framework/mocks/data.go, central/networkgraph/flow/datastore/internal/store/postgres/store_test.go
Don't load egress flows or any flow that is not terminating at a deployment, which is what is used for the compliance check. The other length check is still reasonable in terms of having a deployment that has received at least 1 ingress flow
Unit test modifications
=> fix(perf): Constrain flows to deployment destinations

scanner/cmd/scannerctl/authn/auth.go, scanner/cmd/scannerctl/main.go, scanner/cmd/scannerctl/scale.go, scanner/cmd/scannerctl/scan.go
Extends `scannerctl` with the ability to run scale tests. At the moment, the scale tests just pull a bunch of images from some specified repository.
Deploy Scanner v4 for yourself and try it out.
I followed the steps from https://github.com/stackrox/stackrox/pull/8869 to create a Helm chart to deploy StackRox with Scanner v4. Be sure to replace the tags for the Scanner …
=> feat(scannerctl): scale test support

central/pruning/pruning.go
Don't run the query evaluation for pods if the query for deployments returns values that exclude the image from pruning
Unit test
=> fix(perf): Optimize image pruning selection

pkg/env/sensor.go, sensor/common/metrics/init.go, sensor/common/metrics/metrics.go, sensor/common/networkflow/manager/manager_impl.go, sensor/common/networkflow/manager/manager_impl_test.go, sensor/common/networkflow/manager/testing_test.go
This PR introduces buffering for Network Flow Updates.
- Buffer will not be read by gRPC component while offline
- Network Flow Manager does not need to control offline-mode anymore, as it always writes data into a buffer
- Buffer size if controlled by environment variable `ROX_SENSOR_NETFLOW_OFFLINE_BUFFER_SIZE`
- If buffer is full, the flow is not appended and current state isn't updated. Therefore next tick will carry over updated flows.
- If buffer is full, the flow updates are still sent to detection.
- New metric `network_flow_buffer_size` gauges how filled the buffer is
1. Deploy ACS
2. Create deployment A
3. Stop connection between sensor and central (you can use chaos proxy or teardown central)
4. Generate flow from deployment A …
=> ROX-21051: Buffer network flow updates

image/templates/helm/stackrox-secured-cluster/README.md.htpl, image/templates/helm/stackrox-secured-cluster/internal/defaults/30-base-config.yaml.htpl, image/templates/helm/stackrox-secured-cluster/values-public.yaml.example, image/templates/helm/stackrox-secured-cluster/values.yaml.htpl, pkg/helm/config/testdata/helm-chart-configurations/simple.yaml, pkg/renderer/kubernetes_helm_test.go
Make core_bpf a default one for Helm charts. Part of https://github.com/stackrox/collector/issues/1470
No need for unit or regression tests.
* Generated charts for central & secured cluster services
```
$ roxctl helm output central-services --image-defaults=development_build --debug
$ roxctl helm output secured-cluster-services --image-defaults=development_build --debug
```
* Deployed using helm
```
$ helm upgrade --install -n stackrox stackrox-central-services --create-namespace  ./stackrox-central-services-chart [...]
$ helm install -n stackrox stackrox-secured-cluster-services ./stackrox-secured-cluster-services-chart [...]
```
* Verified that the resulting cluster has the core_bpf collection method.
=> ROX-18375: [Helm] Set core_bpf a default collection method

central/notifier/datastore/datastore.go, central/notifier/datastore/datastore_impl.go, central/notifier/datastore/internal/store/mocks/store.go, central/notifier/datastore/internal/store/store.go, central/notifier/datastore/mocks/datastore.go, central/notifier/processor/singleton.go, central/notifier/service/service_impl.go, central/notifiers/utils/encryption.go
Updated central startup task to allow rekeying of notifier secrets
Manual testing by encrypting and rekeying email notifier.
responsible for the …
=> ROX-20871: Support notifier rekeying

pkg/metrics/testdata/throttle/cgroup1/sys/fs/cgroup/cpu/cpu.stat, pkg/metrics/testdata/throttle/cgroup2/sys/fs/cgroup/cpu.stat, pkg/metrics/throttle.go, pkg/metrics/throttle_test.go
The current throttle metrics only support `cgroup v1`. `cgroup v2` has a slightly different structure (all stats in a single, flat directory, and the throttled time changed name/semantics).
This change adds support for `cgroup v2` as well as keeping support for `cgroup v1`.
Scanner v4 runs these metrics, so I ran Scanner v4 with debug logs. I no longer see the following log:
```
pkg/metrics: 2023/12/15 17:20:14.171894 …
```
=> fix(metrics): support cgroupv2 CPU metrics

pkg/channelmultiplexer/channelmultiplexer.go, pkg/env/sensor.go, sensor/common/metrics/init.go, sensor/common/metrics/metrics.go, sensor/common/processsignal/enricher.go, sensor/common/processsignal/pipeline.go, sensor/common/processsignal/pipeline_test.go, sensor/kubernetes/sensor/sensor.go
Process Indicator events are now sent to a buffered channel.
- If the FF `ROX_CAPTURE_INTERMEDIATE_EVENTS` is enabled, the events won't be expired. 
- If the buffer is full, the event will be dropped. This is to avoid Sensor OOMing if we are offline.
- Metrics for the buffer size and the number of events dropped have been added.
- The buffer size is configurable with `ROX_SENSOR_PROCESS_INDICATOR_OFFLINE_BUFFER_SIZE`
- …
=> ROX-21054: process indicators offline v3

image/templates/helm/stackrox-central/templates/NOTES.txt.htpl
See https://issues.redhat.com/browse/ROX-21619. This PR:
* removes the bogus `clusterName` and `centralEndpoint` from the post-installation NOTES -- these two got accidentally copied over from the secured-cluster-services Helm chart.
* slightly improve the way the StackRox version is reported.
No testing performed besides CI, as this is just a cosmetic change.
=> ROX-21619: Cosmetic Improvements for Helm Chart post-Install Notes

central/cluster/datastore/datastore_impl.go, ui/apps/platform/src/Containers/Clusters/cluster.helpers.tsx
Make core_bpf a default one when unset in the stored configuration and in the UI. Part of https://github.com/stackrox/collector/issues/1470
No need for unit or regression tests.
Deployed ACS, verified that CORE_BPF is a default collection method suggested in the UI. Modified the database record for one secured cluster to have an unset collection method -- turns out it was transformed to `NO_COLLECTION` and never hits the "defaults" assignment logic, showing that an "unset" value is legacy and used exclusively as a defensive coding measure for corrupted data or ancient versions.
=> ROX-18375: [Central] Set core_bpf a default collection method

pkg/telemetry/phonehome/gatherer.go, pkg/telemetry/phonehome/gatherer_test.go
As the test gathering procedure calls `Stop()`, there was a race condition between cancelling the context and calling `Track()`.
The first is read by the test as a way to wait for the termination, before checking the result, while the `Track()` call could happen after the check.
The PR adds a wait group, which can be used in tests to ensure all gathering goroutines are terminated before checking the outcome.
I added a `time.Sleep(time.Second)` call to the `identify()` function, and so reproduced the race condition problem.
I added `Wait()` calls for the `procs` WaitGroup in the test to ensure the `loop` and `identify` goroutines are terminated before checking the `Track()` calls.
In addition to reviewing code here, reviewers **must** also …
=> fix: ROX-21573, wait for gathering goroutines to terminate in tests

ui/apps/platform/src/Containers/Policies/Detail/PolicyDetail.tsx, ui/apps/platform/src/Containers/Policies/Table/PoliciesTablePage.tsx, ui/apps/platform/src/Containers/PolicyCategories/PolicyCategoriesPage.tsx, ui/apps/platform/src/Containers/Violations/Modals/ExcludeConfirmation.tsx, ui/apps/platform/src/Containers/Violations/ViolationsTablePanel.tsx, ui/apps/platform/src/hooks/patternfly/useToasts.tsx, ui/apps/platform/src/types/alert.proto.ts
Adds error handling to the "Exclude deployment from policy" menu option on the Violations page. Fixes [ROX-21270](https://issues.redhat.com/browse/ROX-21270), where an error was occurring but it was not clear why clicking the action button seemed to have no effect.
On the violations page, exclude deployments via the row menu as well as the bulk dropdown. The happy path should remain the same:
https://github.com/stackrox/stackrox/assets/1292638/5a137fdf-e6ac-463b-bc4a-f0cbf222580a
Test both actions again, this time with a simulated error at the network level:
https://github.com/stackrox/stackrox/assets/1292638/92eb926e-5250-45ee-b503-436df3034eee
=> ROX-21271: Add error handling to violations page exclusions action

pkg/clientconn/client.go
This PR configures the keepalive params of the connection between Compliance (Node scanning) and Sensor, so that the client and server match and we no longer get  `too_many_pings` in the logs.
1. I manually checked if the node scanning feature still works (in the UI).
2. Manual test on OCP:
- Regular deployment with `./deploy/openshift/deploy.sh`
- Setting compliance to spam sensor: `ocs set env daemonsets/collector --containers="compliance" ROX_NODE_SCANNING_INITIAL_BACKOFF="1s" ROX_NODE_SCANNING_MAX_INITIAL_WAIT="1s" ROX_NODE_SCANNING_INTERVAL="1m"`
- Observing Compliance logs for few hours (overnight)
Before (note the version):
```
│ No certificates found in /usr/local/share/ca-certificates …
```
=> ROX-20936: Fix 'too_many_pings' in Compliance

sensor/common/detector/detector.go, sensor/common/metrics/init.go, sensor/common/metrics/metrics.go
Remove entity not found logs in cases where the deployment or external source is not found. This case can happen if Network Flows are processed for entities that no longer exist in the cluster (i.e. pod was deleted). The flows are simply dropped in this case, but in some large environments, the sensor logs were flooded with log lines. 
=> ROX-7401: Change entity not found logs 

qa-tests-backend/scripts/run-compatibility.sh, qa-tests-backend/scripts/run-part-1.sh, qa-tests-backend/scripts/run-part-2.sh, qa-tests-backend/src/test/groovy/GraphQLResourcePaginationTest.groovy, scripts/ci/lib.sh, tests/upgrade/legacy_to_postgres_run.sh, tests/upgrade/lib.sh, tests/upgrade/postgres_run.sh
GraphQLResourcePaginationTest used variable test names which makes it difficult to consider pass/fail rate. e.g. `Verify graphql/sublist pagination deployment Namespace:stackrox+Deployment:central <objects.SortOption@29ae2517 field=Deployment reversed=true> secrets`.
Its a good idea for CI runs of `qa-backend-tests` to start with a clear test results folder. Failure to do so can result in duplicate JUNIT records and metrics. As is currently the case with qa-e2e jobs due to the part-1/part-2 separation.
CI + affected test jobs: …
=> chore(CI): misc JUNIT fixes

image/templates/helm/shared/config-templates/scanner-v4/indexer-config.yaml.tpl, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml
The indexer must get repository mapping data from correct URL:
indexer in security cluster should send request to Senor endpoint
indexer in central cluster should send request to Central endpoint
=> ROX-21569: Add repo mapping URL to indexer config

image/templates/helm/shared/templates/_scanner-v4_init.tpl.htpl
Adds the Scanner V4 component (indexer|matcher) to the helm generated Cert TLS Subject Alternative Names. Also updates the common names to match [`ServiceType`'s](https://github.com/stackrox/stackrox/blob/5cd9f69072c17146661fe63bfda293fa08b10003/proto/storage/service_identity.proto#L21).
On an infra cluster installed scanner v4, and examined the the generated TLS certs for the appropriate SAN's.
Before the change:
```
$ k get secret scanner-v4-indexer-tls -o json | jq -r '.data."cert.pem"' | base64 -d | openssl x509 -text -noout | grep -i "subject alt" -A1
X509v3 Subject Alternative Name: 
DNS:scanner-v4.stackrox, DNS:scanner-v4.stackrox.svc, DNS:scanner-v4.stackrox.svc.cluster.local
$ k get secret scanner-v4-matcher-tls -o json | jq -r …
```
=> fix(scannerv4): Add ScannerV4 Component to TLS Hostname(s)

central/detection/service/service.go, central/detection/service/service_impl.go, central/detection/service/service_impl_test.go, central/detection/service/singleton.go, pkg/booleanpolicy/networkpolicy/networkpolicy.go, pkg/images/enricher/enricher.go, pkg/protoconv/resources/resources.go, pkg/protoconv/resources/resources_test.go
This PR extends the capabilities Central has when `roxctl deployment check` is called.
Now Central is enriching a Deployment with Network Policies that would apply to it, were it deployed.
1. Deploy to any cluster
1. Set up a new API token in Central and export it for roxctl to use
1. Set Central loglevel to debug
1. Use `roxctl` from PR https://github.com/stackrox/stackrox/pull/9110 to check a deployment (see addendum):
- `./roxctl deployment check --cluster remote --namespace stackrox --file ./nginx.yaml`
1. Observe logline in Central with `Determined applied network policies for deployment nginx-deployment: ...` listing empty Network Policies
1. Apply the yaml to the Namespace (mainly creating the Network Policy): 
- `kubectl -n …
=> ROX-21198: Enrich deployments with Network Policies in Central

pkg/centralsensor/init_cert.go
Central no longer uses `STOARAGE=pvc` to enable persistence. The linked KBA still seems valid though.  
Did not. 
=> feat(logs): adjust message on incorrect ClusterID failure

.openshift-ci/compatibility_test.py, scripts/ci/jobs/gke_version_compatibility_tests.py
#9164 has made it a requirement that k8s-logs are saved to a clean dir. But that was not the case for gke-version-compatibility-test. This PR has the test use a dir based on the versions being tested.
=> fix(CI): gke-version-compat-test: use a clean dir for each version

scripts/ci/jobs/ocp_scanner_v4_tests.py
This PR provides an implementation for the following CI tests: `ocp-4-11-scanner-v4-tests` and `ocp-4-14-scanner-v4-tests`
They will run the same tests as the pre-existing `gke-scanner-v4-tests` tests, but on OCP.
The tests were validated by analyzing the logs of `ocp-4-11-scanner-v4-tests` and `ocp-4-14-scanner-v4-tests`.
=> ROX-21562: Enable Scanner v4 Tests on OCP

CHANGELOG.md, pkg/booleanpolicy/field_metadata.go, pkg/detection/runtime/detector_test.go
Allows policies to be written on resource names with a regex
Unit test
=> ROX-20257: Allow regex in specification of resource name

central/compliance/manager/data_promise.go, central/compliance/manager/manager_impl.go
Decouples the trigger call for compliance which is synchronous to be asynchronous to fix a 60s timeout in the compliance UI
Will run a scale test to see that all compliance checks run immediately
=> chore(perf): Make data repo creation async in Compliance

ui/apps/platform/package.json, ui/yarn.lock
turns out we aren't using this at all anymore. 🔥
=> ROX-20669: Remove `react-numeric-input` from package.json 

pkg/grpc/authz/idcheck/id_check.go, scanner/services/indexer.go, scanner/services/indexer_test.go, scanner/services/matcher.go, scanner/services/matcher_test.go
For release builds, only:
* Indexer: Central and Sensor
* Matcher: Central
For dev builds, allow access from anywhere at this time. This is useful when testing Scanner v4, only, without the Central/Sensor interactions (for example: via `kubectl port-forward`). For release builds, use the fine-grained auth rules to prevent anyone/anything (except Central and/or Sensor) from doing anything
Note: the production network policies already enforce these rules, but having the finer-grained auth prevents anyone from using `kubectl port-forward` to reach the Indexer and/or Matcher. …
=> ROX-18526: add fine-grained authorization to Scanner v4 endpoints

pkg/telemetry/phonehome/gatherer.go, pkg/telemetry/phonehome/gatherer_test.go
1. `Stop` is called in the `EXPECT.Track.Do()` chain instead of from the gathering function;
2. Removed `procs WaitGroup`, as (1) ensures `Track` is called before `Stop()`;
3. New tests with custom ticker to invoke gathering procedures ad-hoc.
Added unit tests.
=> refactor: Telemetry gatherer tests with custom ticker

ui/apps/platform/src/Containers/NetworkGraph/NetworkGraph.tsx, ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphContainer.tsx, ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.css, ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx, ui/apps/platform/src/Containers/NetworkGraph/TopologyComponent.tsx
Removes the conditionally rendered `Drawer` component and the second rendering of the simulator sidebar on the Network Graph. This moves the conditional rendering from the top level of `NetworkGraphPage` directly to the child elements of `TopologyComponent`.
For reference, the component hierarchy is:
`NetworkGraphPage` -> `NetworkGraphContainer` -> `NetworkGraph` -> `TopologyComponent`
This also fixes another papercut that impacted this change: removing the page overflow when a system config banner is displayed.
Test opening the simulation sidebar with no namespaces selected:
Test with namespaces selected:
Test that changing cluster/namespace selections re-renders the graph correctly: …
=> chore(ui): Remove duplicate rendering of NG simulator sidebar

central/detection/service/service_impl.go, central/sensor/service/pipeline/enhancements/pipeline.go
This PR adds a fallback behaviour for Central to fall back to the old behaviour if Sensor doesn't have the capability to enhance deployments.
- ~~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~
This behaviour can be switched on and off with the feature flag `ROX_CLUSTER_AWARE_DEPLOYMENT_CHECK`.
The flag is currently off by default, leading to the capability not being added to the list of Sensor caps.
(Find used `nginx.yaml` at the bottom of this PR description)
1. Deploy …
=> ROX-21202: Add fallback to non-enhanced Deployments

operator/apis/platform/v1alpha1/securedcluster_types.go, operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml, operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml, operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
Make core_bpf a default one for the Operator. Values translation is not changed on purpose (it's going to be the target of another PR), only the default value. Part of https://github.com/stackrox/collector/issues/1470
No need for unit or regression tests.
Deployed central services and a secured cluster following instructions in `operator/README.md`, verified that the resulting cluster has core_bpf collection method configured.
=> ROX-18375: [Operator] Set core_bpf a default collection method

pkg/images/enricher/enricher_impl.go, pkg/scanners/set_impl.go
Modifies the image enricher in Central to NOT fallback to the `Stackrox Scanner` if `Scanner V4` is enabled and encounters an error.
With ACS deployed to an infra cluster:
With Scanner V4 broken, executed a `roxctl` scan and observed the scan failure in the `indexer` logs, and a fallback/successful scan via the Stackrox Scanner:
```
$ rctl image scan --image=nginx --force 2>/dev/null | jq '.scan.dataSource'
{
"id": "169b0d3f-8277-4900-bbce-1127077defae",
"name": "Stackrox Scanner"
}
```
Indexer Logs
```
{"level":"info","host":"scanner-v4-indexer-7588f96f9c-rbdnf","resource_type":"containerimage","manifest":"sha512:bdefc1cbe20a36d49235e5374ef77c2ef8570ff9dbad0fa9a16a8548de983bb8cf8dcdf7808d2bdeff34baf1df415d44bf9a5e212d4f9e25bdc9db9e85dffb6 …
```
=> ROX-21670: Skip Stackrox Scanner on Scanner V4 error

scanner/mappers/mappers.go, scanner/mappers/mappers_test.go
`VersionId` is not populated for Alpine: https://github.com/quay/claircore/blob/v1.5.20/alpine/distributionscanner.go#L110
Using `Version` instead, see below:
```
did   | version_id |     version     
--------+------------+-----------------
rhel   | 9          | 9
rhel   | 8          | 8
debian | 12         | 12 (bookworm)
debian | 11         | 11 (bullseye)
ubuntu | 22.04      | 22.04 (Jammy)
alpine |            | 3.18
alpine |            | 3.16
alpine |            | 3.17
alpine |            | 3.11
alpine |            | 3.8
alpine |            | 3.14
debian | 9          | 9 (stretch)
alpine |            | 3.10
alpine |            | 3.9
alpine |            | 3.12
alpine |            | 3.15
ubuntu | 20.04      | 20.04 (Focal)
alpine |            | 3.19
alpine |            | 3.13
alpine | …
```
=> fix(scanner): Set Alpine Version from VersionID

pkg/env/scannerv4.go, pkg/scannerv4/client/client.go, scanner/indexer/remote.go
It is possible a `VulnerabilityReport` is larger than the default 4MiB which the go-gRPC client allows, by default. This PR bumps the default to 64MiB and includes a new environment variable `ROX_SCANNER_V4_GRPC_MAX_RESPONSE_SIZE` to allow users to configure the setting.
I ran into this issue in tests.
performed …
=> ROX-21519: make the Scanner v4 client max response size configurable

scanner/mappers/mappers.go, scanner/mappers/mappers_test.go
1. Pull CVSS scores from OSV updaters presented in `Severity`.
2. Use CVSS enrichments to populate CVSS
TODO I have scanning results with CVSS scores run locally, need to run this in a cluster and post results here.
=> ROX-21616: Use NVD CVSS scores enrichments and OSV CVSS scores

pkg/scanners/scannerv4/convert.go, pkg/scanners/scannerv4/convert_test.go
**NOTE: Original purpose of PR will be implemented in https://github.com/stackrox/stackrox/pull/9345. This PR now just does simple cleanup**
I noticed `VersionId` is not populated for Alpine. See https://github.com/quay/claircore/blob/v1.5.20/alpine/distributionscanner.go#L110
I also checked the Scanner v4 DB and saw the following:
```
did   | version_id |     version     
--------+------------+-----------------
rhel   | 9          | 9
rhel   | 8          | 8
debian | 12         | 12 (bookworm)
debian | 11         | 11 (bullseye)
ubuntu | 22.04      | 22.04 (Jammy)
alpine |            | 3.18
alpine |            | 3.16
alpine |            | 3.17
alpine |            | 3.11
alpine |            | 3.8
alpine |            | 3.14
debian | 9          | 9 (stretch)
alpine |            | 3.10 …
```
=> chore(scanner): cleanup client-side OS conversion

image/templates/helm/shared/templates/_scanner-v4_init.tpl.htpl, image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl
David, I'd suggest something like this? Haven't tested this on a cluster yet, though.
=> fix(scanv4): Skip deploying Scanner v4 components if central is already deployed.

Makefile
fix(Makefile): Redirect kind error output to /dev/null
- Run locally
- CI
=> fix(Makefile): Redirect kind error output to /dev/null

operator/pkg/central/extensions/reconcile_admin_password.go, operator/pkg/central/extensions/reconcile_central_db_password.go, operator/pkg/central/extensions/reconcile_tls.go, operator/pkg/central/extensions/reconcile_tls_test.go, operator/pkg/common/extensions/reconcile_scanner_db_password.go, operator/pkg/common/extensions/secret_reconciliator.go, operator/pkg/common/extensions/secret_reconciliator_test.go
Before, it avoided touching an existing central-tls secret altogether. There was a special boolean arg in secret reconciliator just for that single purpose.
Instead, make use of the parameter for passing existing secret content, added in #9258 to reuse pre-existing CA fields, but otherwise regenerate the leaf cert. Avoid touching JWT key at least for now, since I have not investigated what the impact would be, and this should be the safe path, given the past behaviour.
FTR, a [followup PR](https://github.com/stackrox/stackrox/pull/9305) changes the cert validation to trigger a refresh some time ahead of the expiry date.
CI with the new cases should be enough.
performed one …
=> ROX-21622: Make operator able to replace central TLS leaf cert

sensor/common/deploymentenhancer/component.go, sensor/common/deploymentenhancer/component_test.go
DeploymentEnhancer has an internal queue in which all incoming requests are queued.
This PR introduces changes to handle when the queue is full, ensuring `ProcessMessage` does not block.
Automated tests + manual testing.
Manual testing was conducted by decreasing `deploymentQueueSize` to 1, deploying the image, and running multiple `roxctl deployment check` commands in parallel, looking for the introduced error message in the Sensor logs.
=> ROX-21345: Ensure DeploymentEnhancer message queue never blocks

ui/apps/platform/cypress/integration/integrations/general.test.js, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/ClusterInitBundlesTile.tsx
For **with feature flag** below:
1. Before you `yarn deploy` in ui folder:
```sh
```
2. Before you `yarn cypress-open` in ui/apps/platform folder:
```sh
export CYPRESS_ROX_MOVE_INIT_BUNDLES_UI=true
```
1. Visit /main/integrations and then scroll down
2. Click **Cluster Init Bundle** card
See /main/integrations/authProviders/clusterInitBundle
See absence of requests because of Redux and sagas for integrations route
See GET /v1/cluster-init/init-bundles request
See /main/clusters/init-bundles page
* integrations/clusterInitBundles.test.js
See test pass because it visits the path directly
* integrations/general.test.js
Oops, I forgot about this. Added conditional assertion.
=> ROX-21683: Link from integration tile to cluster init bundles table

ui/apps/platform/src/Containers/Clusters/Components/ManageTokensButton.tsx
Fixed by dropping the 2 commits: Ouch, by mistake this is based on #9348
For **with feature flag** below:
1. Before you `yarn deploy` in ui folder:
```sh
```
1. Visit /main/clusters
See **Manage tokens** button
See link to /main/integrations#token-integrations
See **Manage init bundles** button
See link to /main/clusters/init-bundles
=> ROX-21689: Link from button on clusters page to init bundles

pkg/env/sensor.go
Updates the default value for `ROX_SCANNER_V4_GRPC_ENDPOINT` to match what is expected for the accessing the Scanner V4 indexer.
N/A
=> fix(scan4): Update default Scanner V4 Indexer Endpoint

pkg/registries/ecr/ecr.go, pkg/registries/ecr/ecr_test.go, pkg/registries/ecr/transport.go
This PR is a refactor of the AWS ECR integration. The goal is to get rid of the `refreshDockerClient` functionality, because it performs unprotected concurrent read/writes and may lead to a data race. As an alternative, we introduce a custom AWS transport, which performs the token refresh in a concurrency safe way.
Tested on test cluster (ROSA HCP):
* STS enabled ECR `Test` is successful after Central start.
* STS enabled ECR `Test` is successful after 12h when the first access token expires.
performed testing and …
=> ROX-20788: refactor ECR client

scanner/image/scanner/Dockerfile, scanner/image/scanner/download-mappings.sh
Embed the latest version of the RHEL-related mapping files into each Scanner image. This is required to ensure indexing can occur when Scanner v4 starts up before Central
This adds 2.1MB to the image:
```
$ ls -lh /run/mappings/
total 2.1M
-rw-r--r-- 1 root root 100K Jan 12 20:40 container-name-repos-map.json
-rw-r--r-- 1 root root 2.0M Jan 12 20:40 repository-to-cpe.json
```
Pull the image to find the files in the image
In …
=> ROX-21690: embed initial mapping files

ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlePage.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleWizard.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleWizard.utils.ts, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleWizardStep1.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleWizardStep2.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlesHeader.tsx, ui/apps/platform/src/services/ClustersService.ts
1. Add `history.goBack()` to table after click **Revoke bundle**.
1. Import `downloadBundle` function from utils.
2. Add `validationSchema` especially for name.
3. Add formik state.
4. Factor out step names.
1. Add `TextInput` for **Name**.
2. Add `Radio` for **Platform**.
3. Add `Select` for **Installation**.
1. Add sentence about platform and installation.
1. InitBundlePage: investigate second argument and add confirmation modal.
2. Display icon in `TextInput` whenever name is not valid?
3. InitBundleWizardStep1: investigate whether `Select` needs **append to** idiom.
4. InitBundleWizardStep2: display bundle file name and collaborate with Kerry and Mansur about information.
5. Are there extra unexpected requests?
6. Add confirmation modal for **Revoke bundle**.
Before you `yarn deploy` …
=> ROX-21128: Add InitBundleWizard steps

sensor/common/networkflow/manager/manager_impl.go
The ticker for the enrichment should not be stopped on creation.
- Deploy ACS with the FF enabled
- Create a deployment A
- Stop the connection between sensor and central
- Generate a flow to/from deployment A
- Observe the metric `rox_sensor_network_flow_buffer_size` increases after 30s
- Re-start the connection between sensor and central
- Observe the flow appears in the NG …
=> fix(netflow): Do not stop the ticker in offline v3

operator/apis/platform/v1alpha1/securedcluster_types.go, operator/apis/platform/v1alpha1/zz_generated.deepcopy.go, operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml, operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/crd/bases/platform.stackrox.io_securedclusters.yaml, operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml, operator/pkg/securedcluster/values/translation/translation.go, operator/pkg/securedcluster/values/translation/translation_test.go
Introduce a new values translation in the operator to switch from ebpf collection method to core_bpf. It means at upgrade of an existing secured cluster, configured to use ebpf, it will be modified to use core_bpf.
The translation is happening on every sync, which means by itself it will prevent any attempts to override a secured cluster CR to temporary use ebpf. To still be able to use ebpf if needed, a new boolean configuration option is introduced `spec.perNode.Collector.forceCollection`. If the flag is set, no translation from ebpf to core_bpf would be applied, and ebpf value could be used.
The use case for the new option is temporary workarounds and troubleshooting, thus it doesn't have to be advertised in common scenarios in the documentation.
Part of …
=> ROX-18375: Translate ebpf to core_bpf

ui/apps/platform/cypress/integration/clusters/Clusters.helpers.js, ui/apps/platform/src/Containers/Clusters/AddClusterPrompt.tsx, ui/apps/platform/src/Containers/Clusters/ClustersPage.tsx, ui/apps/platform/src/Containers/Clusters/ClustersSidePanel.tsx, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx
First of 2 refactoring steps as prerequisite to designs for init bundles and unsecured clusters.
New design for **no clusters** page has nothing in common with **clusters table** page, but `ClusterTablePanel` renders `AddClusterPrompt` element with both headers.
Clusters components still have tightly coupled structure left over from original side-by-side table and panel.
Depend on page address is source of truth for page state.
1. ClustersPage
* Replace `setSelectedClusterId` with `history.push(…)` call in descendants.
* Move `PageHeader` element to ClustersTablePanel component.
* Delete `workflowStateContext` because no descendant has `useContext` hook.
* Conditionally render `ClustersSidePanel` element.
2. ClustersTablePanel
* Move `AddClusterPrompt` element up to become alternative to …
=> ROX-21710: Simplify structure of clusters page

central/sensor/service/pipeline/all/factory.go
The pipeline for receiving information about the compliance operator installation was only created if the feature flag was enabled.  The feature flag is no longer used in sensor so there is a scenario where sensor can send the message if it sends it before the central capabilities are sync'ed with sensor.  The pipeline should always exist and simply do nothing if the feature flag is not enabled.
If any of these don't apply, …
=> fix(pipeline): compliance info pipeline

.github/workflows/scanner-build.yml
https://download.postgresql.org/pub/repos/yum/15/redhat/rhel-8-aarch64/ was cleared today for some reason. Just ignored arm64 for now
CI
=> chore(scanner): stop making arm64 builds for now

operator/pkg/central/extensions/reconcile_tls.go, operator/pkg/central/extensions/reconcile_tls_test.go
Refresh the cert after half of its validity period passes. This way there is still plenty of time for:
- the central/central-db/scanner* pods to restart and pick up the new cert, e.g. as a result of an ACS or node upgrade, even before we add auto-reload of certs at runtime to all these components
- a human to intervene before expiry in case this auto-refresh is unsuccessful for whatever reason
This change also updates a few error messages for consistency.
Possible future work:
- change the operator to trigger another reconcile shortly after the earliest refresh time of all encountered certificates. In practice this is not an issue, half of validity period (~6 months) of these certs is a multiple of the forced reconcile period (11 hours), so might not be worth the complexity.
- change all …
=> ROX-21621: Refresh central services leaf certs before they expire.

roxctl/netpol/connectivity/diff/cta.go, roxctl/netpol/connectivity/map/cta.go, roxctl/netpol/connectivity/netpolerrors/errors.go, tests/roxctl/bats-tests/local/roxctl-netpol-connectivity-diff-development.bats, tests/roxctl/bats-tests/local/roxctl-netpol-connectivity-map-development.bats
Updates for `roxctl netpol connectivity` commands error handling and bats tests, for ROX_20271.
Includes:
- few suggested changes for error handling 
- few tests updates (bats tests)
=> ROX-20271: Upgrade NP-Guard to v1: updates

ui/apps/platform/src/Containers/VulnMgmt/List/Cves/VulnMgmtListCves.js, ui/apps/platform/src/hooks/useAnalytics.ts
Updates VM telemetry to not track values for "CVE", "Image", or "Component" in Workload CVE filters, nor track "CVE" when a legacy global snooze is applied.
Apply CVE, Image, and Component filters, and verify that the filter value is not sent via telemetry API calls. _Note that only "category" appears in the properties when viewing the network request._
Repeat for legacy snooze:
=> fix(ui): Update workload cve telemetry to track fewer filter values

image/templates/helm/shared/templates/_metadata.tpl, image/templates/helm/stackrox-secured-cluster/templates/sensor-rbac.yaml, image/templates/helm/stackrox-secured-cluster/templates/upgrader-serviceaccount.yaml
When our Helm charts create *global* resources these resources must be namespace-prefixed to prevent name clashes when deploying into different namespaces in parallel (or sequential when these resources are not properly cleaned up afterwards).
In the context of ACSCS where we deploy multiple centrals on the same cluster we had to make sure that all such global resources in the central chart were correctly handled (prefixed). For the secured-cluster chart we didn't have this requirement and it seems some of the global resources were simply overlooked.
This was noticed in the context of scanner v4 testing.
Just CI.
=> fix(chart): Prefactoring: Fix the naming of global resources in chart

ui/apps/platform/package.json, ui/apps/platform/src/services/ClustersService.ts, ui/apps/platform/src/services/ComplianceEnhancedService.ts, ui/apps/platform/src/services/DeploymentsService.ts, ui/yarn.lock
https://prettier.io/blog/2024/01/12/3.2.0
> faster CLI is slated to be released as version 4.0.
Keep up with minor updates in case future major upgrade has breaking changes.
https://prettier.io/blog/2024/01/12/3.2.0#avoid-introducing-linebreaks-in-template-interpolations-15209httpsgithubcomprettierprettierpull15209-by-bakkothttpsgithubcombakkot
> In a template string avoid adding a linebreak when formatting the expression unless one is already present or it's unavoidable due to e.g. a nested function. Previously a linebreak could be introduced whenever some interpolation in the template was sufficiently "not simple".
> Now it will instead be left alone.
> If a linebreak is already present within the `${...}`, format as normal.
Prettier will add fewer linebreaks in new template literals, …
=> chore(ui): Update prettier 3.2.2 devDependencies in ui

tools/generate-helpers/pg-table-bindings/store.go.tpl
Some excessive template cleanup creeped in #8863 
The goal here is to restore the code generation to a working state.
manual `make go-generated-srcs`
=> fix: restore missing template vars in postgres generator

pkg/env/scannerv4.go, scanner/indexer/indexer.go
Enable NodeJS (npm) indexing support. This is configurable via `ROX_SCANNER_V4_NODE_JS_SUPPORT`, as it is not well tested at this time.
nah
=> feat(scanner): nodejs indexing support

image/templates/helm/stackrox-secured-cluster/internal/defaults/70-scanner-v4.yaml.htpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-slim.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml
Context for this PR is the activation of the local scanner feature within the secured-cluster services Helm chart.
So far the situation is that scanner (v2) is disabled by default within the secured-cluster chart. Setting `scanner.disable: false` activates the local scanner feature and the deployment of scanner (v2).
With the upcoming 4.4 Helm charts we are installing scanner v4 by default as part of the central chart, i.e. the user does not need to explicitly set `scannerV4.disable: false` for scanner v4 to be deployed.
Given these semantics for the central chart and for the sake of coherence and ergonomics it seems reasonable to adjust the secured-cluster chart in such a way that an activated scanner v2 implies scanner v4 being activated as well (unless `scannerV4.disable` has been …
=> feat(scanv4): Enable Scanner v4 when Scanner v2 is enabled

central/detection/service/service_impl.go, pkg/env/deployment_enhancement.go
This PR introduces a configurable timeout for Central to wait for Sensor to answer a Deployment Enhancement Request.
For this, a new environment variable was introduced, `ROX_CENTRAL_DEPLOYMENT_ENHANCE_TIMEOUT`.
Manual testing, by deploying and setting the timeout very low and watching for timeout answers.
- Deploy locally
- Enable feature flag
- `kubectl set env deployment/sensor ROX_CLUSTER_AWARE_DEPLOYMENT_CHECK=true -n stackrox`
- Set short timeout
- `kubectl set env deployment/central ROX_CENTRAL_DEPLOYMENT_ENHANCE_TIMEOUT="10ms" -n stackrox`
- Start enhanced deployment check (see yaml at the bottom of this PR description)
- `bin/linux_amd64/roxctl deployment check --file ~/Downloads/nginx.yaml --cluster remote --namespace stackrox` …
=> ROX-21203: Introduce Central Enhancement Timeout

image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl, operator/apis/platform/v1alpha1/central_types.go, operator/bundle/manifests/platform.stackrox.io_centrals.yaml, operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/crd/bases/platform.stackrox.io_centrals.yaml, operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
The expected location of the key secret has changed (see [here](https://github.com/stackrox/stackrox/blob/master/central/notifiers/utils/encryption.go#L15) ) and this PR adapts the Helm charts.
1. Install 4.3.2:
```bash
kubectl create ns stackrox
deploy/common/pull-secret.sh stackrox quay.io | kubectl -n stackrox apply -f -
helm install -n stackrox stackrox-central-services rhacs/central-services --set central.exposure.route.enabled=true --set central.persistence.none=true --set central.notifierSecretsEncryption.enabled=true
```
2. Create the `central-encryption-key` secret (for 4.3.2) and `central-encryption-key-chain` secret (in preparation for 4.4) with the the following contents:
```yaml
kind: Secret
apiVersion: v1
metadata:
name: …
```
=> ROX-21681: Adapt Helm charts to use central-encryption-key-chain

central/complianceoperator/v2/checkresults/datastore/datastore.go, central/complianceoperator/v2/checkresults/datastore/datastore_impl.go, central/complianceoperator/v2/checkresults/datastore/datastore_impl_test.go, central/complianceoperator/v2/checkresults/datastore/mocks/datastore.go, central/complianceoperator/v2/checkresults/datastore/stats_views.go, central/complianceoperator/v2/checkresults/service/service_impl.go, central/complianceoperator/v2/checkresults/service/service_impl_test.go, central/convert/storagetov2/compliance_results_service.go, central/convert/testutils/compliance_results.go, generated/api/v2/compliance_results_service.pb.go, generated/api/v2/compliance_results_service.pb.gw.go, generated/api/v2/compliance_results_service.swagger.json, proto/api/v2/compliance_results_service.proto
This PR calculates and groups the check result stats by cluster.  So if a cluster had 14 different scan configurations run against it, this would aggregate the counts of all 14 of those results into a single count.  Below is an instance of this with 3 completely different scans executed against the same cluster.  The stats are aggregated.
```
{
"scanStats" : [
{
"checkStats" : [
{
"count" : 406,
"status" : "FAIL"
},
{
"count" : 0,
"status" : "INFO"
},
{
"count" : 288,
"status" : "PASS"
},
{
"count" : 0,
"status" : "ERROR"
},
{
"count" : 35,
"status" : "MANUAL"
},
{
"count" : 0,
"status" : "INCONSISTENT"
},
{
"count" : 0,
"status" : "NOT_APPLICABLE"
}
}
],
"cluster" : {
"clusterId" : "454ef133-efa6-4b83-9762-c82cb9723360",
"clusterName" : "remote"
}
}
]
}
```
~- [ ] Evaluated and added …
=> ROX-21641: compliance result stat cluster

central/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go
Enable the last remaining disabled test to collect logs when it fails. Other tests in the suite were fixed and enabled, which are passing in the CI.
=> rox-18182: enable TestProcessorDoesntExpireOnceStopped

image/templates/helm/shared/config-templates/scanner-v4/indexer-config.yaml.tpl, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml, scanner/config.yaml.sample, scanner/config/config.go, scanner/indexer/indexer.go, scanner/indexer/indexer_test.go
This makes the seed files configurable, so we can still run outside the container image. This also renames `name_to_cpe_url ` to `name_to_repos_url` to be more accurate
CI …
=> chore(scanner): make mapping seed files configurable

pkg/cloudproviders/aws/metadata.go, pkg/cloudproviders/aws/metadata_test.go, pkg/cloudproviders/azure/metadata.go, pkg/cloudproviders/utils/utils.go
Get EKS cluster metadata. Unfortunately there is no reliable way to get the cluster name, so we have to get it on a best effort basis. There are two possible sources:
* EC2 metadata instance tags. This works if access has been enabled for the EC2 instance.
* Node labels. This works if the cluster was created via eksctl.
Tested on EKS cluster.
=> ROX-21521: get EKS cluster metadata

sensor/common/centralclient/client_test.go
This was fixed in master with #8885 but it's not worth backporting that for an end-of-life branch.
=> ROX-21615: Disable broken test in release-4.1 branch

pkg/env/deployment_enhancement.go, sensor/common/deploymentenhancer/component.go
Introducing a configurable queue size for incoming `DeploymentEnhancementRequest` messages to Sensor.
Tuning this variable correctly might be not that easy, as a single enhancement request can contain an arbitrary number of deployments.
- Automated CI tests
- Manual testing
Manual testing was concluded by reducing the queue size to 1 or 0, then looking for `resource exhausted` error messages
=> ROX-21291: Introduce environment var for enhancement queue size

central/compliance/checks/hipaa_164/check306e/check_test.go, central/compliance/checks/hipaa_164/check308a1iia/check_test.go, central/compliance/checks/hipaa_164/check308a1iib/check_test.go, central/compliance/checks/hipaa_164/check308a5iib/check_test.go, central/compliance/checks/nist800-190/check411/check_test.go, central/compliance/checks/nist800-190/check412/check_test.go, central/compliance/checks/nist800-190/check414/check_test.go, central/compliance/checks/nist800-190/check422/check_test.go, central/compliance/checks/nist800-190/check433/check_test.go, central/compliance/checks/nist800-190/check442/check_test.go, central/compliance/checks/nist800-190/check443/check_test.go, central/compliance/checks/nist800-190/check444/check_test.go, central/compliance/checks/nist800-190/check455/check_test.go, central/compliance/checks/pcidss32/check121/check_test.go, central/compliance/checks/pcidss32/check132/check_test.go, central/compliance/checks/pcidss32/check134/check_test.go, central/compliance/checks/pcidss32/check135/check_test.go, central/compliance/checks/pcidss32/check225/check_test.go, central/compliance/checks/pcidss32/check61/check_test.go, central/compliance/framework/domain.go, central/compliance/framework/run_test.go, central/compliance/manager/manager_impl.go, central/compliance/manager/run_bench_test.go, central/compliance/manager/run_test.go
Pods are unused so no need to load them into the domain
Just code removal
=> fix(perf): Remove pods from compliance domain

ui/apps/platform/package.json, ui/yarn.lock
Version 1.2.0 was published almost 8 months ago.
Update with 2 sprints before next release, especially before feature bashes.
https://github.com/jquense/yup/blob/master/CHANGELOG.md#133-2023-12-14
* 1.3.3: `addMethod`: allow Schema without making TypeScript upset
* 1.3.2: pick and omit with excluded edges
* 1.3.1: `ValidationError` extends `Error`
* 1.3.0: Allow schema metadata to be strongly typed
=> chore(ui): Update yup 1.3.3 dependencies in ui

central/compliance/manager/manager_impl.go
Node vulnerabilities are not used in compliance. At scale, it was taking 2-3s per cluster to get the nodes for the domain which are pulled serially. Now, it takes on avg 27 milliseconds per cluster at scale.
Ran scale tests
=> fix(perf): Only fetch node metadata in compliance domain

ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlePage.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlesPage.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlesTable.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/RevokeBundleModal.tsx
Adapt from classic init bundles:
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/DeleteClusterInitBundleConfirmationModal.tsx
1. Investigate why the following did not work. Maybe difference between React 17 and 18?
```tsx
/*
* Cancel button has initial focus so delete requires an intentional action,
* like click button or press tab key, not just press return key.
*/
if (typeof refCancelButton?.current?.focus === 'function') {
refCancelButton.current.focus();
}
```
```sh
```
1. Visit /main/clusters, click **Manage init bundles**, click **Create bundle** and then go back to the bundles page.
2. Click link to bundle page, and then click **Revoke …
=> ROX-21130: Adapt from classic confirmation modal to revoke bundle

tests/compliance_operator_v2_test.go
Increased sleep time in TestComplianceV2CreateGetScanConfiguration to increase wait time to get compliance scan results.
It is also acceptable to skip testing for changes that are too taxing to test …
=> fix(ci): Incresed sleep time for scan config test

central/vulnerabilityrequest/manager/requestmgr/manager_impl.go
The vulnerability exception revert loop seems to be racy. The routine checks if the loop is stopped only before reading the database. However, since it is a separate routine (async), the stop could be triggered after the database has been read.
=> fix: Ensure the loop is stopped

sensor/common/sensor/sensor.go
Sensor did not allow traffic to `/scanner/definitions` from Scanner v4. This change permits traffic from Scanner v2 and indexer, only
no
=> fix(scanner): permit indexer traffic to sensor

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.helpers.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/cancelRequestFlow.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCancelButtonModal.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestDenialButtonModal.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/hooks/useRequestCVEsDetails.ts
This PR adds some tests for the cancel request workflow
1. `should be able to cancel a request if the user is the requester`
2. `should be able to see how many CVEs will be affected by a cancel`
=> test(ui): Adding tests for the cancel request workflow

scripts/ci/lib.sh
Marking the collector release failed for 
- 4.3.4: https://github.com/stackrox/stackrox/actions/runs/7609473566
- 4.2.4: https://github.com/stackrox/stackrox/actions/runs/7587950405
According to step summary no commit was added because:
`Skip RELEASED_VERSIONS file change, already up to date ...`
Closer investigation showed that this matched: 
```
$ grep 4.2.4 RELEASED_VERSIONS
3.14.2 4.0.2  # Rox release 4.0.2 by roxbot at Tue May 30 19:49:04 UTC 2023 
```
... because `grep` treated the dot like any char. 
To avoid this issue, this PR introduces spaces around the tag regex.
The format of the file specifies that the Stackrox version is surrounded by one space before and two spaces after. 
The RELEASED_VERSIONS file shall be updated manually. …
=> ROX-21868: fix update skip condition in mark_collector_release

pkg/features/list.go
While we await different UX
Deploying the PR build image, then checking to ensure the Policy Criteria Modal is no longer available, and the old policy drag and drop fields still work.
1. No policy modal, but drag and drop is back and can be used in creating a policy
2. Policy created with drag and drop criteria works
=> chore(ui): Turn off policy criteria modal for now

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/ScanConfigDetailPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/ScanConfigsPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Table/ScanConfigsTablePage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/ViewScanConfigDetail.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ScanConfigOptions.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/useFormikScanConfig.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/compliance.scanConfigs.utils.ts, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/compliance.scanConfigs.utils.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/components/ScanConfigClustersTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/components/ScanConfigParameters.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/components/ScanConfigProfiles.tsx, ui/apps/platform/src/hooks/useRestQuery.ts, ui/apps/platform/src/routePaths.ts, ui/apps/platform/src/services/ComplianceEnhancedService.ts
This PR implements the read-only view of a single Scan Schedule (`scanConfig` in the API).
Image of the mock from this page:
The [API call](https://stagingdb.demo.stackrox.com/main/apidocs-v2#tag/ComplianceScanConfigurationService/operation/ComplianceScanConfigurationService_GetComplianceScanConfiguration) to get this data have, or need, updates, and for MVP the only thing we can get for the profiles are their names.
Notes:
1. `Name` field has to follow RFC 1123, so this PR also adds helper text to the form in the wizard, and a regex and error message for frontend validation.
2. `Description` leave wasn't being sent in POST request when creating Scan Schedules (scanConfigs), so I added that.
3. `Schedule` is using the helper function from the table.
4. `Last Run`: as you can see in the …
=> ROX-21630: Create scan config details page

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.helpers.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/denyRequestFlow.test.ts
This PR adds some tests for the deny request workflow
1. `should be able to deny a request if approval permissions are granted`
2. `should be able to see how many CVEs will be affected by a denial`
=> test(ui): Adding tests for the deny request workflow

.github/workflows/release-ci.yaml, .github/workflows/scanner-build.yaml, scanner/Makefile
https://github.com/stackrox/stackrox/pull/9272 introduced the need to differentiate between release and dev Scanner, so this PR ensures a release build is made upon release.
See 
```
$ make -C scanner bin/scanner
+ bin/scanner
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags="-X github.com/stackrox/rox/scanner/internal/version.Version=4.3.x-638-g7e4c0238fb" -tags= -o bin/scanner ./cmd/scanner
$ go version -m …
```
=> chore(scanner): differentiate dev and release Scanner v4

CHANGELOG.md, scripts/ci/lib.sh, scripts/ci/publish-helm-charts.sh
Stops generating and publishing stackrox.io based helmcharts.
Going forward, the opensource flavor is published to stackrox/helmcharts.
Used a "dry run" of a release (curtesy of @tommartensen) to produce an [example release-artifacts PR](https://github.com/stackrox/release-artifacts/pull/122).
The interesting artifact is the [helm repo archive](https://github.com/stackrox/release-artifacts/blob/4276a90f8c55a0b07a7112fe0e46b957b5ab8f41/helm-charts/opensource/stackrox-central-services-400.3.0-817-g1588c87071.tgz
) produced. I verified this contains the opensource charts, by looking at the `internal/defaults.yaml`'s image repository and confirming it now points to quay.io.
In addition to reviewing code here, reviewers **must** also review …
=> ROX-21620: publish opensource instead of stackrox.io helm charts

scanner/e2etests/image_test.go, scanner/indexer/indexer.go, scanner/updater/rhel/fetch_test.go, scanner/updater/rhel/parse_test.go, scanner/updater/rhel/updaterset.go
Following up on https://github.com/stackrox/stackrox/pull/9476#pullrequestreview-1839285758:
```
find scanner -name '*.go' | while read f; do grep 'interface{}' $f && sed -i 's/interface{}/any/' $f && go fmt $f; done
```
`make -C scanner build`
=> chore(scanner): Replace interface{} with any

ui/apps/platform/src/Components/PatternFly/IconText/ExternalLink.tsx, ui/apps/platform/src/Containers/Clusters/Components/ClusterStatus.tsx, ui/apps/platform/src/Containers/Collections/CollectionFormModal.tsx, ui/apps/platform/src/Containers/SystemHealth/CertificateHealth/CertificateCard.tsx, ui/apps/platform/src/Containers/SystemHealth/DiagnosticBundle/GenerateDiagnosticBundle.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/CveSelections.tsx
Adapt from `IconText` element:
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Components/PatternFly/IconText/IconText.tsx
Prevent additional duplication in cluster init bundles of similar rendering code elsewhere:
1. https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Clusters/Components/ClusterStatus.tsx#L34-L48
2. https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Collections/CollectionFormModal.tsx#L46-L56
3. https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Collections/CollectionFormModal.tsx#L133-L143
4. https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/SystemHealth/CertificateHealth/CertificateCard.tsx#L132-L150
5. …
=> ROX-21838: Factor out reusable ExternalLink component

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageDetailBadges.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageScanningErrorLabelLayout.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/utils/getImageScanMessage.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/utils/getImageScanMessage.ts
This PR adds the image scan notes popover in the 'Images' tab (within Workload CVEs) and an alert in the 'Images' details page
I was not able to test this out using real data, but I tried to simulate the different states and the messages we would see. Attached screenshots of the messages below
When there are no `notes` or `scanNotes` then we won't display anything
Otherwise, we'll display the label and the proper message in the popover depending on the string values in `notes` and `scanNotes`.
When there are no `notes` or `scanNotes` then we won't display anything
Otherwise, we'll display the proper message in an alert warning depending on the string values in `notes` and `scanNotes`.
=> ROX-21210: Adding image scan notes popover

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/denyRequestFlow.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
This little PR removes the ability to cancel a denied request. Since it's already denied, there is no reason to cancel it
I updated the test to include a check for the `Cancel request` button. Ideally, I should probably check for that in a separate test. I didn't want to go through a whole deferral flow again just to check that, so I tacked it onto the first test. We can also revisit some of these tests to make sure we're doing things optimally. For example, having a test to check for the button that follows right after a previous test that does the denial. Maybe that's worth a discussion. I think there are always pros and cons to doing something like that.
=> ROX-21479: Remove ability to cancel a denied request

central/sensor/service/pipeline/complianceoperatorrulesv2/pipeline.go, qa-tests-backend/src/test/groovy/ReconciliationTest.groovy
unexpected text showed up on upgrade.  Should have returned nil instead of error.
And also Reconciliation map updates in that groovy test.
CI …
=> fix(test): compliance upgrade unexpected

scripts/ci/get-slack-user-id.sh
Per title.
See how @-tagging does not work currently in https://redhat-internal.slack.com/archives/CLUNQEEMA/p1705995812469439
These aren't needed and won't be done:
Visually/manually double-checked that
=> chore: Enable tagging Michael Heß in Slack notifications

image/templates/helm/shared/templates/_scanner-v4_init.tpl.htpl, image/templates/helm/stackrox-central/internal/defaults.yaml.htpl, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml
Actually we only wanted to merge this change: https://github.com/stackrox/stackrox/pull/9529/files#diff-d987dde6c0295b6166f8fc0b16b92ed97f68f96907aad8045fe5aef490a11488R168
So that *by default* Scanner V4 is installed with the central-services Helm chart. This comes as a requirement for the Scanner V4 initiative.
But this change alone caused `helm lint <central-services-chart>` to fail. Explanation for this behaviour can be found in a comment in the diff.
So this PR also modifies the behaviour of the Helm chart so that Helm linting works.
Regarding:
> Updating the user-visible documentation for the Scanner V4 integration is tracked in separate tickets, hence doesn't need to be done here.
> Some upgrade tests exist already, others will be added as part of the remaining work for the Scanner …
=> feat(scanv4): Enable Scanner V4 by default in Central chart

central/debug/service/diagnostics.go, central/debug/service/diagnostics_test.go, central/debug/service/service.go, central/debug/service/zip.go, central/sensor/telemetry/controller_impl.go, central/telemetry/gatherers/cluster.go, go.mod, pkg/concurrency/do.go, pkg/concurrency/do_test.go, pkg/concurrency/error_wait.go, pkg/env/sensor.go, pkg/k8sintrospect/collect.go, pkg/prometheusutil/export.go, sensor/kubernetes/telemetry/command_handler.go, sensor/kubernetes/telemetry/gatherers/cluster.go
We've recently had issues with the diagnostic bundle generation, specifically an issue where the metrics and Kubernetes info requests would run into timeouts due to not responding in-time.
The logs when the timeout occurs look like the following:
```log
debug/service: 2023/12/07 13:12:28.426410 diagnostics.go:63: Warn: Error pulling kubernetes info from sensor {"cluster_name": "remote", "error": "sensor didn't sent any data in last 5m0s"}
debug/service: 2023/12/07 13:17:28.432909 diagnostics.go:90: Warn: Error pulling metrics from sensor {"cluster_name": "remote", "error": "sensor didn't sent any data in last 5m0s"}
```
Alternatively, if Central was running into a client timeout (e.g. `roxctl` timeout) the logs look as follows:
```log
debug/service: 2023/12/07 14:44:00.982499 …
```
=> fix(diag-bundle): fix diag bundle issues

image/templates/helm/stackrox-central/templates/_central_endpoints.tpl
The comment I spot when downloaded the `scanner-tls.yaml` to update scanner certificates.
This PR does not fix the 597 empty lines, preceding the actual content of the file.
below.
Tested go template syntax in go playground. CI.
=> fix: go template comment

roxctl/helm/output/output.go, roxctl/helm/output/output_test.go
Aligning the command line parameter with `roxctl central generate`.
Unit test. Manually in command line.
=> ROX-21677: add `--enable-telemetry` parameter to `roxctl helm output`

ui/apps/platform/cypress/integration/compliance/Compliance.helpers.js, ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx, ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardTile.tsx, ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceScanProgress.tsx, ui/apps/platform/src/Containers/Compliance/Dashboard/useComplianceRunStatuses.ts, ui/apps/platform/src/Containers/Compliance/ScanButton.js, ui/apps/platform/src/css/trumps.css, ui/apps/platform/src/queries/standard.js
Adds a progress indicator to Compliance 1.0 that is displayed when there are scan runs in-progress. Will poll for updates every 10 seconds until all runs are complete.
The testing procedure below uses simulated API calls and a polling interval of 1 second to better demonstrate behavior.
Relies on API changes in https://github.com/stackrox/stackrox/pull/8957
- On load of Compliance 1.0, if there are no runs in progress nothing will be shown
- If runs are in progress, or if a new scan is kicked off, a progress bar will be shown and poll for updates
- If the user navigates away, refreshes, etc, the polling will continue and the progress bar will still be visible
- When the runs complete, the “success” progress bar will remain on the page, …
=> fix(ui): Add progress indicator for async Compliance 1.0 scans

scanner/services/indexer.go
Allows the Scanner V4 Matcher to talk to Indexer.
Should address [failure in CI](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-ocp-4-11-merge-qa-e2e-tests/1750174582217641984) when testing release builds
TBD
=> fix(indexer): Add Matcher to API auth

central/hash/manager/deduper.go, central/hash/manager/mocks/deduper.go, central/sensor/service/connection/sensorevents.go, central/sensor/service/connection/worker_queue.go, pkg/deduperkey/key.go
When an object is being processed and hits an unretryable error, the object is dropped and is not reinserted back into the queue to be processed. However, the received map still has the reference to that object so if the Sensor comes back up and resends an event then it will be deduped by the received map even though the object was never successfully processed. This will remain until Central is bounced and then the received map will be reset because it is simply in-memory. Therefore, on an unretryable failure purge the received map of the reference to the object in order to allow future events to successfully be processed
Use this space to explain **how you validated** that **your change functions exactly how you expect …
=> fix(bug): Ensure future processing when error is unretryable

go.mod, go.sum, roxctl/doc/generate.go, roxctl/maincommand/command.go
This PR introduces a new `docs` command with which doc pages can be generated for all roxctl commands.
The doc page generation works using [spf13/cobra/doc](https://pkg.go.dev/github.com/spf13/cobra/doc) package and the currently supported formats of man, markdown, reST, YAML.
Note that this currently is only used by the doc team as input for extending the docs, and not necessarily used as-is.
For the time being, decided to guard this functionality behind the buildinfo (i.e. disable this for release builds), we may want to switch to an environment variable if desired as well (this way we could theoretically generate the docs later on in the upstream release pipeline as artifacts as well).
N/A …
=> feat(roxctl): generate docs for roxctl

pkg/helm/charts/tests/centralservices/testdata/helmtest/image-pull-secrets.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/image-pull-secrets.test.yaml
Now that we use a helmtest version with support for testing the `lookup` function, add test coverage for extraction of pull secret names from the default service account.
This was a warm-up for a fix to ROX-9156, but useful on its own.
=> test(helm): cover extraction of pull secrets from the default SA

pkg/helm/charts/tests/centralservices/testdata/helmtest/image-pull-secrets-legacy.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/image-pull-secrets-legacy.test.yaml
This creates clones of a couple of helmtest files related to image pull secrets.
Sadly GitHub does not show this, but they are identical:
```
$ diff -u pkg/helm/charts/tests/centralservices/testdata/helmtest/image-pull-secrets-legacy.test.yaml pkg/helm/charts/tests/centralservices/testdata/helmtest/image-pull-secrets.test.yaml
$ diff -u pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/image-pull-secrets-legacy.test.yaml pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/image-pull-secrets.test.yaml
$ 
```
The `-legacy` in the name means they will be testing support for the soon-to-be-legacy use case. I.e. automatically referring to a few image pull secrets whose names are considered special.
These are created in this separet PR purely in order to make the next PR …
=> test(helmtest): Prepare image pull secret tests for upcoming change.

sensor/tests/connection/connection_test.go
- SensorHello2 was created to make sure multiple local sensor instances could be executed in a single sensor integration test
- Preventing sensor restarts feature flag is already enabled by default
=> feat(test): Remove duplicate SensorHello tests and feature flag

ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersEmptyState.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersPage.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersTable.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersToolbar.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/SearchFilterType.tsx, ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/routePaths.ts, ui/apps/platform/src/services/DiscoveredClustersService.ts
Adapt from
https://github.com/stackrox/stackrox/tree/master/ui/apps/platform/src/Containers/Administration/Events
Follow procedure
https://github.com/stackrox/stackrox/tree/master/ui/apps/platform#add-a-route
1. Edit ui/apps/platform/src/routePaths.ts file.
* Add a path **without** params for link from sidebar navigation ~and, if needed, path **with** params for the `Route` element~.
Because table row displays all information about a discovered cluster, no separate page for MVP.
* Add a string to `RouteKey` type.
* Add a property to `routeRequirementsMap` object.
Specify `ROX_CLOUD_SOURCES` feature flag during development of a new route.
Specify `Administration` minimum resource requirements. Because **Discovered clusters** link is on clusters page, `Cluster` is an implicit requirement. …
=> ROX-21943: Add discovered-clusters route in UI

central/convert/internaltov2storage/compliance_operator_profile.go, central/sensor/service/connection/sensorevents.go, central/sensor/service/pipeline/all/factory.go, central/sensor/service/pipeline/complianceoperatorprofiles/pipeline.go, central/sensor/service/pipeline/complianceoperatorprofiles/pipeline_test.go, central/sensor/service/pipeline/complianceoperatorprofilesv2/pipeline.go, central/sensor/service/pipeline/complianceoperatorprofilesv2/pipeline_test.go, pkg/deduperkey/key.go, pkg/metrics/resource_string.go, pkg/metrics/resources.go, qa-tests-backend/src/test/groovy/ReconciliationTest.groovy, sensor/kubernetes/listener/resources/complianceoperator/dispatchers/complianceoperatorprofiles.go
Moving V1 and V2 profiles to use separate pipelines
UT and spinning up a cluster to ensure objects populate as expected. …
=> ROX-21956: compliance profiles use separate pipelines for V1 and V2

.github/workflows/scanner-build.yaml
We were not pushing Scanner v4 manifest indexes (see https://github.com/stackrox/stackrox/actions/runs/7647853880/job/20839784400). This PR fixes that, and it also appends `-prelease` to the image/version tag for prerelease builds.
Added the `ci-build-prerelease` label. Not sure how to test tagging from here, though
In addition to reviewing code here, reviewers **must** also …
=> fix(scanner): nightly and prerelease builds

scanner/datastore/postgres/connect.go, scanner/indexer/indexer.go, scanner/matcher/matcher.go, scripts/ci/logcheck/restart-ok-patterns.json
This makes Scanner v4 Indexer and Matcher startup more robust and give the DB about 5 minutes to startup.
This should hopefully make CI happier, too.
Indexer logs:
```
$ oc logs -f deploy/scanner-v4-indexer
No certificates found in /usr/local/share/ca-certificates
'/etc/pki/injected-ca-trust/tls-ca-bundle.pem' -> '/etc/pki/ca-trust/source/anchors/tls-ca-bundle.pem'
pkg/memlimit: 2024/01/25 23:56:21.047904 …
```
=> chore(scanner): retry DB connection upon startup

operator/tests/common/central-cr-assert.yaml, operator/tests/common/central-cr-pre-scanner-v4-assert.yaml, operator/tests/common/central-cr.yaml, operator/tests/common/delete-central-errors-openshift.yaml, operator/tests/common/delete-central-errors.yaml, operator/tests/upgrade/upgrade/05-assert.yaml, operator/tests/upgrade/upgrade/30-central-cr.yaml
Adding Scanner V4 resource to assertions of kuttl tests.
responsible for the change …
=> ROX-19058: add scannerV4 to kuttl tests for central

ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleWizardStep2.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterPage.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterUsingHelmChart.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterUsingOperator.tsx, ui/apps/platform/src/Containers/MainPage/Body.tsx, ui/apps/platform/src/routePaths.ts
1. Add reusable content components for **Operator** or **Helm chart** installation method.
* `InitBundleWizardStep2` renders either/or depending on selection in wizard step 1.
* `SecureClusterPage` renders either/or via tabs. Add `secure-a-cluster` route for this page.
2. Rename **Install cluster** button as **Secure a cluster** wording from Cloud Sources mocks of clusters page.
* Replace **View instructions** link with **Init bundle installation methods** link to **Secure a cluster with an init bundle** page.
* Replace **New cluster** with **Legacy installation method**.
After we merge this, move forward in parallel:
* Add content of the 2 components to focus the attention of reviewers:
* Kerry: clear wording and consistency with docs.
* Mansur: usability and visual design.
* Simon: …
=> ROX-21129: Add cluster init bundles wizard step 2

roxctl/common/flags/endpoint.go, roxctl/common/flags/endpoint_test.go
When the port is missing we will get an error from `Dial` that is retried so for 60s user gets nothing and at the end configuration error is thrown. This PR adds roxctl validation for host:port
=> fix: roxctl validate endpoint for port

central/complianceoperator/v2/compliancemanager/manager_impl_test.go
Looks like a missed merge conflict caused a reference to an old type to stick around.
provided convince any reviewer or any external …
=> fix(style): compliance fix style

central/scannerdefinitions/handler/handler.go, central/scannerdefinitions/handler/handler_test.go, image/templates/helm/shared/config-templates/scanner-v4/indexer-config.yaml.tpl, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml
The file maps container names to repos, not CPEs. Changing the name to reflect this.
CI
=> chore(scanner): rename name2cpe to name2repos

scanner/cmd/scanner/main.go
Adds `build flavor` to the indexer/matcher startup logs. Since logic (such as auth) is dependant on the type of build, this will help determine if testing a release/development/etc. build.
Inspected logs:
Release build:
```
{"level":"info","host":"scanner-v4-matcher-5849f7cf8c-lcp6f","component":"main","version":"4.3.x-883-geaa3ee1bbe-dirty","build_flavor":"release","time":"2024-01-26T20:27:33Z","message":"starting scanner"}
{"level":"info","host":"scanner-v4-indexer-7d65dbc85-4npts","component":"main","version":"4.3.x-883-geaa3ee1bbe-dirty","build_flavor":"release","time":"2024-01-26T20:27:44Z","message":"starting scanner"}
```
Non-Release build:
```
{"level":"info","host":"scanner-v4-indexer-7d65dbc85-rmxfd","component":"main","version": …
```
=> chore(info): Add build flavor to Scanner V4 startup log

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.helpers.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approveRequestFlow.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/cancelRequestFlow.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx
This PR will filter out cancelled requests within the `Approved deferrals`, `Approved false positives`, and `Denied requests` tables.
https://github.com/stackrox/stackrox/assets/4805485/9ae8fe4b-fe93-4220-8722-efe1b8a49f95
=> ROX-21467: Cancelled requests should not show in tables

pkg/auth/authproviders/oidc/backend_impl.go, pkg/auth/authproviders/oidc/backend_impl_test.go
This PR provides a fix for the generic OIDC provider when used in combination with GitLab applications (i.e. using GitLab as the OIDC provider).
GitLab at some point has moved its supported response types to `code` flow only, and additionally imposes the following restrictions on the `groups` claim value: https://docs.gitlab.com/ee/integration/openid_connect_provider.html#shared-information.
The ID token will only have _direct_ group memberships in a claim `groups_direct`, whereas the userinfo endpoint claims will have all _direct and indirect_ group memberships in the claim `groups`. This indirection has led to a couple of users not being able to leverage GitLab in combination with our OIDC providers.
The solution is somewhat simple: in the flows where we previously only assumed the ID …
=> ROX-21611: Fix GitLab OIDC groups

ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx
Required attributes can be already set up via API and declaratively. This PR allows to do that via UI.
1. Deploy code changes(for example, on infra)
2. Create auth provider of OIDC type
3. In create form, specify required attributed(see screenshot)
4. After `Save` reload the page to force UI to pull data from the backend and check that required attributes are present
After save: 
Before save: 
No attributes edit mode: 
No attributes view mode:
=> ROX-14550: UI for configuring auth provider required attributes

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveListExceptionFlow.test.js, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/ExceptionRequestTableCells.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ExceptionRequestModal/ExceptionScopeField.tsx
Handles the display of exception scope field, when the "just for this image tag" option is selected for an image that does not have an explicit tag, but is referenced by hash.
This isn't fully supported by the backend, and is effectively the same as choosing "all tags", so this is displayed as a wildcard as well.
In addition, this removes the "just for this image tag" option from the form UI when the image in scope does not have a tag.
**Note** - this is easier to review with "hide whitespace" on.
Create an exception at:
- global scope
- image scope for an image with no tag (`gke.gcr.io/fluent-bit`)
- single tag scope for an image with no tag (`gke.gcr.io/fluent-bit`)
- image scope for an image with a tag
- single tag scope for an image …
=> ROX-21477: Update "scope" field to handle sha based image tags

ui/apps/platform/cypress/integration/clusters/redirectFromDashboard.test.js, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Clusters/NoClustersPage.tsx
A few more changes than I had intended because during manual testing, an unexpected GET /v1/init-bundles request directed attention at a loophole in complicated conditional rendering because
* `fetchingClusters` has initial value `false`
* `pollingCount` has initial value `0`
* `currentClusters.length` has initial value `0`
Which rendered NoClustersPage **before** first successful response.
1. Visit or redirect to /main clusters which makes GET /v1/clusters request every 5 seconds.
2. Before first successful response, render either error message or spinner.
3. After first successful response:
* If no clusters and not filtered, render NoClustersPage.
* If clusters or filtered, render clusters table and so on.
1. Replace `fetchingClusters` with opposite `hasFetchedClusters` to simplify …
=> ROX-21131: Add conditional rendering for no clusters page

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Clusters/ClusterDetails.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Clusters/ClusterDetailsContent.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Clusters/ClusterDetailsHeader.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/ClustersCoverageTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Components/RadioButtonWithStats.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/compliance.coverage.utils.ts, ui/apps/platform/src/Containers/ComplianceEnhanced/Status/Dashboard/ScanResultsOverviewTable.tsx, ui/apps/platform/src/css/trumps.css, ui/apps/platform/src/services/ComplianceEnhancedService.ts
Create cards that allow users to toggle between cluster results according to the scan configurations.
* Calls to fetch both overall cluster results and cluster results by scan configuration will kick off at the same time
* A loading indicator will display below the cluster details header during the loading of scan overview card details. We'll need that scan info before we can fetch compliance check results.
* Each scan configuration setup that includes the cluster in view should display as a card on this page
* Each card should display pass count, fail count, and other count
* The initial scan results card is automatically selected upon loading. When a user chooses a card, a URL query parameter is updated (`selectedScan`), ensuring that …
=> ROX-21879: Scan results by cluster card selector

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Table/ScanConfigsTablePage.tsx, ui/apps/platform/src/services/ComplianceEnhancedService.ts
Update the scan configurations table to use the newly created endpoint for scan configurations count to accurately display total scans count in pagination. Update query parameter used for sorting by the scan configuration name
note: the 'last run' column is no longer sortable, it has not been implemented in the backend.
* Clicking the name column properly sorts the results
* Pagination displays the correct total count regardless of number of entries currently displaying
=> fix(ui): pagination/sort compliance scan configs

scanner/config/config.go, scanner/config/config_test.go
This is causing CI failures. For example: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-master-merge-gke-upgrade-tests/1751358746904236032
CI. TODO verify this passes when the config secret is deleted and scanner v4 is restarted …
=> fix(scanner): ignore non-existent proxy config

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/EditScanConfigDetail.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/ScanConfigDetailPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/ScanConfigsPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Table/ScanConfigsTablePage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ClusterSelection.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ProfileSelection.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ReviewConfig.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ScanConfigOptions.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ScanConfigWizardFooter.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ScanConfigWizardForm.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/useFormikScanConfig.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/compliance.scanConfigs.utils.test.ts, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/compliance.scanConfigs.utils.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/components/ScanConfigParameterView.tsx, ui/apps/platform/src/services/ComplianceEnhancedService.ts
These code changes add an edit flow to the scan configurations in Compliance 2.0.
(I would have included the delete flow, but the changes were already extensive, so I added a TODO comment for that.)
This builds on the wizard/form of the create flow, with some minor changes to make that flow conditional on whether an ID is already present for the scan configuration. (An ID sends the user down the edit flow path.)
**Important note:** 
To make the data structure of the form work with the Wizard component, we were already converting the form structure to the shape the API needed for a create action. Rather than try to change that pattern, I simply added converter functions to go the other other, from a scan configuration retrieved through the API into the data structure expected by the form. …
=> ROX-21949: Add flow to edit existing Scan Config

ui/apps/platform/src/Containers/SystemHealth/DashboardPage.js, ui/apps/platform/src/services/CertGenerationService.ts, ui/apps/platform/src/types/credentialExpiryService.proto.ts, ui/apps/platform/src/utils/credentialExpiry.ts
This PR includes these main changes:
1. Rename the `Scanner certificate` card to `StackRox Scanner certificate`
2. Add another card for `Scanner V4 certificate` for the new scanner
3. Modify the API service function to explicitly state which component we need to query for
=> ROX-20411: Adding Scanner V4 Certificate Expiration Status

.github/workflows/scanner-build.yaml, .github/workflows/scanner-mapping-update.yaml
We want to make building Scanner images a requirement for CI. Changing these names makes this easier and clearer.
CI
=> chore(scanner): rename CI jobs

ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedScanConfigs.test.js, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/useFormikScanConfig.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/components/ScanConfigClustersTable.tsx
UX enhancement to make troubleshooting easier
Manual testing with a scan config that has an error in a cluster
=> chore(ui): Add popover when cluster-compliance error in scan config

.github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-pr-vuln-update.yaml, .github/workflows/scanner-release-vuln-update.yaml, scanner/config/config.go, scanner/enricher/nvd/nvd.go, scanner/enricher/nvd/nvd_test.go, scanner/enricher/nvd/testdata/feed.json, scanner/mappers/mappers.go, scanner/mappers/mappers_test.go, scanner/matcher/matcher.go, scanner/updater/export.go, tools/allowed-large-files
The NVD enricher can:
1. Pull CVE items from NVD, and populate (a.) the enrichment table , and (b.) the vulnerability bundle with the items keyed by CVE tags.
2. Retrieve those enrichments from the DB during vulnerability matcher and populate the VR.
We use the NVD data to:
1. Populate CVSS scores that were not provided by the related security source.
2. Populate description of vulns when not provided by the security source.
The updaters were modified to run the NVD enricher so the vulnerability definitions file will contain enrichments. Basically, the enricher reaches out to the NVD V2 API to grab only the information we need. This information is then combined with other vulnerabilities and sent to the Scanner tool in the same bundle as the other. It's all handled seamlessly and consumed …
=> ROX-21264: Add the NVD enricher

ui/apps/platform/cypress/integration/compliance/Compliance.helpers.js, ui/apps/platform/cypress/integration/configmanagement/ConfigurationManagement.helpers.js, ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceDashboardPage.tsx, ui/apps/platform/src/Containers/Compliance/Dashboard/ComplianceScanProgress.tsx, ui/apps/platform/src/Containers/Compliance/Dashboard/useComplianceRunStatuses.ts, ui/apps/platform/src/Containers/ConfigManagement/Dashboard/widgets/ComplianceByControls.js
Updates the Scan button in **Config Management** that was missed (doh) when updating the Compliance page to async scans. I chose to add the progress indicator to the widget instead of the top of the page due to that widget being the only context on this page that was dependent on the compliance scan.
This also fixes the tests to await the correct requests and assert on the presense/absence of the scan progress indicator where necessary.
e2e CI
Triggering the compliance scan via ConfigMgmt will display the in progress indicator within the widget on that page. The state will sync between this page and Compliance 1.0 if the user visits either before the scan is complete.
Triggering a scan via ConfigMgmt does not disable the button, allowing …
=> fix(ui): Update ConfigMgmt for async compliance scans

ui/apps/platform/cypress/integration/clusters/delegatedScanning.test.js, ui/apps/platform/cypress/integration/clusters/redirectFromDashboard.test.js, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx, ui/apps/platform/src/Containers/Clusters/Components/ManageTokensButton.tsx, ui/apps/platform/src/Containers/Clusters/NoClustersPage.tsx
Marcin reported:
1. Lack of a link on NoClustersPage for legacy method to install secured cluster services.
2. After entering /main/clusters/new in address bar, redirect back to /main/clusters and NoClustersPage.
1. Unintended side effect of https://github.com/stackrox/stackrox/pull/9365
* Positive change: separated no clusters from clusters per mocks
* Negative change: my bad to forget to replace irrelevant link with **Legacy installation method** link which had been on **Install cluster** dropdown in clusters heading.
2. Redirect to /main/clusters
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/MainPage/MainPage.tsx#L50-L67
* does prevent entering /main/clusters/new in address bar directly as a work around.
* does not prevent React Router links to init …
=> ROX-22078: Add link for legacy installation to NoClustersPage

pkg/grpc/server.go
The gRPC threshold of 12MB has been reached by a few users, rather than constantly asking them to raise the environment variable, this PR bumpts the default to 24MB. 
No need.
=> ROX-22081: Update default max gRPC payload

ui/Makefile
Before the change, `REACT_APP_ROX_PRODUCT_BRANDING` is obtained from the parent Makefile (the one in repository root) by invoking its `product-branding` target which returns a value of `ROX_PRODUCT_BRANDING` environment variable if set, or `STACKROX_BRANDING` as default.
A problem with that is that the parent Makefile imports bunch of stuff which at some point even uses `go` binary. In RHTAP/Konflux context I'm trying to use vanilla NodeJS image from Red Hat as a UI builder, and this image does not have `go` (unlike builders used upstream and downstream). Again, `go` is needed only for the parent Makefile to load, it does not participate in "solving" `ROX_PRODUCT_BRANDING` values.
This PR allows to drop a dependency on `go` by trying to use `ROX_PRODUCT_BRANDING` environment variable …
=> chore(ui): Don't call parent Makefile if `ROX_PRODUCT_BRANDING` is set

central/detection/service/service_impl.go
This PR introduces a guard to ensure Central doesn't return applied Network Policies for `roxctl deployment check` if `--cluster` is not provided in the call. 
If no cluster is provided by the user, we cannot guarantee to return the correct Network Policies for any given deployment, as they are cluster-specific.
I manually tested this by observing centrals debug output. We log Network Policies that central found to the Debug loglevel.
- Deploy locally
- Apply a deployment with a matching Network Policy (see attachment)
- Set central `LOGLEVEL` env to debug
- `roxctl deployment check --cluster remote --namespace stackrox --file ./nginx.yaml`
- Observe central generating debug output "Found applied network policies ..."
- `roxctl deployment …
=> ROX-21997: Guard enriching netpols behind cluster check

operator/README.md
Doc-only change, tested manually:
```
$ `make which-operator-sdk` run
make[1]: Entering directory '/home/mowsiany/go/src/github.com/stackrox/stackrox/operator'
make[1]: '/home/mowsiany/go/src/github.com/stackrox/stackrox/operator/.gotools/bin/operator-sdk' is up to date.
make[1]: Leaving directory '/home/mowsiany/go/src/github.com/stackrox/stackrox/operator'
This command has subcommands that will deploy your Operator with OLM.
Usage:
operator-sdk run [command]
Available Commands:
bundle           Deploy an Operator in the bundle format with OLM
bundle-upgrade   Upgrade an Operator previously installed in the bundle format with OLM
Flags:
-h, --help   help for run
Global Flags:
--plugins strings   plugin keys to be used for this subcommand execution
--verbose           Enable verbose …
```
=> docs(operator): replace hardcoded operator-sdk path

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/cancelRequestFlow.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestDetailsPage.tsx
This PR should display the request details a little differently when a request is canceled. You should see an alert at the top now.
https://github.com/stackrox/stackrox/assets/4805485/046487fe-e4c3-41ab-85d5-4f15189b56bc
=> ROX-21471: Request details for canceled request should look different

.openshift-ci/get_latest_helm_chart_versions.py, scripts/ci/jobs/gke_version_compatibility_tests.py
3.74 and 4.1 are both out of support and are both affected by the issue where network entities are too large so remove them from the version compatibility matrix.
Version compatibility test
=> fix(test): Remove failing compatibility tests

ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersPage.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersTable.tsx
Update to most recent design as prerequisite to render data as soon as service is available.
1. Add `currentDatetime` in DiscoveredClustersPage to provide as prop so DiscoveredClustersTable is stateless presentation component.
2. Update table head columns with `width` prop and the following:
* Add **State** column.
* Combine **Provider** and **Region** columns to follow example of other products.
* Add **Cloud source** column.
* Add **First discovered** column.
3. Add missing `Tbody` element.
4. Add placeholder for **First discovered** data cell.
1. Destructure properties from response as soon as service is available.
2. Add DiscoveredClusters.utils.tsx file:
* Export `DiscoveredClusterStateMap` for **State** columm.
* Export helper function for **Provider (region)** column.
Before you …
=> ROX-22050: Update DiscoveredClustersTable before service is available

ui/apps/platform/cypress/integration/clusters/redirectFromDashboard.test.js, ui/apps/platform/src/Containers/Clusters/NoClustersPage.tsx
Redirect to /main/clusters in MainPage when there are no clusters
* prevents opening /main/clusters/secure-a-cluster in a new tab
* does not prevent opening the corresponding docs pages in a new tab
```sh
```
main.css: 0 = 3950646 - 3950646
total: 378 = 10477777 - 10477399
0 = 90 - 90 files
1. Visit /main/clusters with simulated no clusters.
Before you `yarn cypress-open` in ui/apps/platform folder:
```sh
export CYPRESS_ROX_MOVE_INIT_BUNDLES_UI=true
```
* clusters/redirectFromDashboard.test.js
=> ROX-22117: Link to installing secured clusters services docs pages

ui/apps/platform/src/Containers/Clusters/ClusterEditForm.tsx
Adapted from first draft by Simon.
1. Visit /main/clusters, click **Secure a cluster** and then click **Legacy installation method**
See /main/clusters/new with **Legacy installation method** warning alert instead of **Cluster Summary** section.
2. Visit /main/clusters and click a row to see /main/clusters/id with **Cluster Summary** section instead of warning alert.
=> ROX-22119: Add warning alert to ClusterEditForm

central/detection/service/service_impl.go, pkg/features/list.go
This PR enables the feature flag for roxctl deployment check improvements on by default (`ROX_CLUSTER_AWARE_DEPLOYMENT_CHECK`)
Run deployed image and observe log output to ensure the feature is active by default …
=> ROX-21992: Flip Feature Flag to on by default

tests/common_test.go
Test is failing with a timeout. Let's increase it to give pod more time to be stopped.
CI
=> ROX-21963: increase timeout in nongroovy test

central/pruning/pruning.go, sensor/common/networkflow/manager/manager_impl.go, sensor/common/networkflow/manager/manager_impl_test.go, sensor/common/networkflow/manager/testing_test.go, sensor/common/networkflow/metrics/metrics.go
This PR will enable sensor to track active connections. In-memory active connections will be deleted once `lastseen` is set to something other than `InfiiniteFuture` or if we failed the container lookup and the time elapsed since `firstseen` is greater than `maxContainerResolutionWaitPeriod`. In the second case sensor will send the last known active connection with `lastseen` set to `now`.
This is needed for offline v3 due to the following scenario:
1. Sensor goes offline
2. Pod A is created
3. Pod A connects to something
4. Collector reports active connection for Pod A
5. Pod A is deleted
6. Sensor goes back online (clears in-memory stores)
7. Active connection for Pod A gets reported to central
8. Collector reports close connection for Pod A
9. Sensor fails to find the Pod in the stores …
=> ROX-21938: Keep track of active flows

operator/tests/central/central-basic/990-assert-pods-debug.yaml, operator/tests/central/central-basic/990-errors-no-pods-left.yaml, operator/tests/central/central-misc/990-assert-pods-debug.yaml, operator/tests/central/central-misc/990-errors-no-pods-left.yaml, operator/tests/common/central-cr-assert.yaml, operator/tests/common/no-pods-left.yaml, operator/tests/common/pods-debug.yaml, operator/tests/common/secured-cluster-cr-assert.yaml, operator/tests/securedcluster/sc-basic/990-assert-pods-debug.yaml, operator/tests/securedcluster/sc-basic/990-errors-no-pods-left.yaml, operator/tests/upgrade/upgrade/990-assert-pods-debug.yaml, operator/tests/upgrade/upgrade/990-errors-no-pods-left.yaml
The ticket was a case where the test timed out due to a stray pod left in a namespace.
This change adds checks for existence of such pods as the last step of each test, and if some are founds, gathers debug info so we can troubleshoot this more in case it repeats in the future.
It also adds `collector` log/description collection on errors that was missing so far.
=> ROX-21603: check for stray pods at test end

roxctl/central/login/login.go, roxctl/central/login/login_test.go, roxctl/common/flags/endpoint.go
The `roxctl central login` command can only be used with auth providers which are not of the type `basic`.
Currently, we open the local browser irrespective of whether only a single auth provider is configured or not.
Instead, we can fail fast in case the login auth providers contain only auth providers of the type basic. This can be done because the API is anonymous.
N/A.
=> fix(roxctl): fail fast in central login

image/templates/helm/stackrox-central/config/proxy-config.yaml.default, pkg/httputil/proxy/config.go, pkg/httputil/proxy/proxy_test.go
We are using kube-api in different places. This PR adds kubernetes host:port to proxy exclude list when default excludes are enabled. 
https://github.com/stackrox/stackrox/pull/9566#pullrequestreview-1851723122
=> ROX-21625: add kube-api to proxy default excludes

ui/apps/platform/src/Containers/MainPage/MainPage.tsx
This PR displays the credential expiry banner for Scanner V4. This builds off the changes made in the following PRs:
https://github.com/stackrox/stackrox/pull/9532
https://github.com/stackrox/stackrox/pull/9551
=> ROX-21614: Show Scanner V4 Credential Expiry Banner

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/FilterAutocomplete.tsx
Scopes queries on the Workload CVE single page to use the exact CVE name as the search filter.
Previously, the query was sent with a bare string e.g. `"CVE-2020-123"`, which would match any CVE that _starts_ with `CVE-2020-123`. There are no examples in my local environment where this would be a problem, but if there were overlapping substrings in any environment this would lead to incorrect data. (A page would show data for the combination of `"CVE-2020-123"` and `"CVE-2020-12345"`, if they existed.)
This bug was not caused by the move to regex filter values, but in theory could have triggered the issue more often.
Since there is no data that matches in my test system, verify that `query` parameter based CVE ID values are contained …
=> ROX-22029: Scope CVE queries to exact match only

.github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-pr-vuln-update.yaml, scanner/config/config.go, scanner/matcher/updater/updater.go, scanner/updater/export.go
Matcher logs have been showing:
```
{"level":"error","host":"scanner-v4-matcher-cdcd57d9d-wqb9w","component":"matcher/updater/Updater.Start","error":"updating enrichements: failed to finish batch enrichment insert: failed in exec iteration 823, ERROR: null value in column \"enrich\" of relation \"uo_enrich\" violates not-null constraint (SQLSTATE 23502)","time":"2024-01-31T20:47:07Z","message":"errors encountered during updater run"}
```
This is because we are running the built-in ClairCore CVSS enricher, accidentally. This PR stops using the default updaters.
Side effects:
* CI was silently failing before. This resolves that issue
* The compressed file is now 149MB instead of 286MB
* The decompressed file is now 22GB instead of 43GB
While we're at it, I've been wanting to switch the file …
=> fix(scanner): do not use default updaters

ui/apps/platform/src/Containers/VulnMgmt/Entity/Component/VulnMgmtComponentOverview.js, ui/apps/platform/src/Containers/VulnMgmt/Entity/TableWidgetFixableCves.js
While troubleshooting an issue that Ross noticed while testing Scanner V4, I noticed a logic error in the code, so I'm assuming certain paths have had a broken Fixable CVEs section for a while. (On the bright side, we now know which paths get practically no usage in our app.)
All Findings sections that show Observed/Deferred/False Positive are good, because they don't use that buggy conditional.
These are the paths I found broken:
- Clusters > Single cluster: Findings->Fixable Node CVEs tab
- Namespace > (0 or more intervening entities) > Single Image: Findings
- Image Components > Single component: Findings
- Node > Single node: Findings
This change fixes the buggy conditional, and makes the code cleaner.
I elected not to add automated tests for two reasons:
- The VM 1.0 section is …
=> ROX-22132: Correct Fixable CVEs errors on certain VM1.0 pages

central/complianceoperator/v2/compliancemanager/manager_impl.go, central/complianceoperator/v2/compliancemanager/manager_impl_test.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl_test.go, central/complianceoperator/v2/scanconfigurations/datastore/mocks/datastore.go, tests/compliance_operator_v2_test.go
This PR adds checks when creating a new scan config, we check if the new scan config has referenced any profile that is in any existing scan configurations.
* Added unit test in scanconfigurations datastore to test checking if there are duplicate profile scan
* Added unit test in compliancemanager implementation to test create duplicate profile scan 
* Addded e2e test to test create two scan with same profile
=> ROX-21432: Validate scan config does not contains duplicate profile

pkg/clientconn/client.go, pkg/grpc/server.go, sensor/common/centralclient/client_test.go, sensor/common/centralclient/grpc_connection.go
Backports configurability of max gRPC message sizes.
This is causing 3.74 installations to panic on startup and there is no way of working around it. This is due to a Network Entities message that is sent on startup which goes above the (then) default of 4MB for sensor received messages.
=> ROX-19885: Set gRPC max receive size for client connection (#7930)

image/templates/helm/shared/templates/_scanner-v4_volume.tpl, image/templates/helm/shared/templates/_storage_classes.tpl, image/templates/helm/stackrox-central/internal/config-shape.yaml, image/templates/helm/stackrox-secured-cluster/internal/config-shape.yaml, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, pkg/helm/charts/tests/centralservices/flavor/testdata/helmtest/suite.yaml, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml, pkg/helm/charts/tests/centralservices/testdata/helmtest/suite.yaml, pkg/helm/charts/tests/securedclusterservices/flavor/testdata/helmtest/suite.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/suite.yaml
Implement fallback for environments not having a default StorageClass configured. …
=> feat(scanv4): Fallback if no default StorageClass

qa-tests-backend/src/test/groovy/RbacAuthTest.groovy
Test is failing on ROSA and OSD since Nov 2023. Let's skip it and enable once we debug why it started failing.  …
=> ROX-21171: skip test on rosa and osd

scripts/ci/jobs/gke_scanner_v4_tests.py, scripts/ci/jobs/ocp_scanner_v4_tests.py, tests/e2e/lib.sh, tests/e2e/yaml/central-cr.envsubst.yaml
These changes allow the operator install of scanner v4 to be configurable, defaulting to being disabled.
Related to https://github.com/openshift/release/pull/48344
CI
=> fix(ci): allow scanner v4 installation to be configurable

deploy/charts/monitoring/dashboards/central.json, deploy/charts/monitoring/dashboards/stackrox-core-dashboard.json, deploy/charts/monitoring/templates/grafana.yaml, deploy/charts/monitoring/templates/prometheus-role.yaml, deploy/charts/monitoring/templates/prometheus.yaml
This is part of the work to add monitoring to the long running secured cluster, running collector and load created by kube-burner. These are the changes needed in stackrox/stackrox to make this possible. Other changes are made to stackrox/actions to enable monitoring for the secured cluster. This PR enables Prometheus to monitor CPU and memory usage of  containers running on a cluster. This is true for both the cluster with fake load and central and the cluster with real load created by kube-burner. This PR also adds the dashboards to Grafana to display the CPU and memory usage of stackrox pods.
The PR to turn on monitoring for the secured cluster is here https://github.com/stackrox/actions/pull/43
~~- [ ] Evaluated and added CHANGELOG entry …
=> ROX-21548: long running collector should be monitored

ui/apps/platform/cypress/integration/compliance-enhanced/complianceEnhancedDashboard.test.js, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Clusters/ClusterDetails.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Clusters/ClusterDetailsContent.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Clusters/ClusterDetailsTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Components/CheckStatusDropdown.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/compliance.coverage.utils.tsx, ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationSidebar.tsx, ui/apps/platform/src/services/ComplianceEnhancedService.ts
This adds the table for viewing cluster compliance check results by scan configuration
Notes:
- Mocks show the compliance checks filtering as a dropdown with prefilled checks, however, we don't have an endpoint to get the list of checks currently. So we went with a free form input field instead for now
Default table view:
Filtered:
=> ROX-21880: Compliance cluster results table

central/complianceoperator/v2/scanconfigurations/service/service_impl.go, central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go
Validate that the compliance scan configuration has clusters and profiles associated with it.
Added UT.  Also tested locally to verify 
```
dashrews-mac:stackrox dashrews$ roxcurl /v2/compliance/scan/configurations -d '{"scanName":"shrewstest6","scanConfig":{"profiles":["rhcos4-moderate"],"oneTimeScan":false,"scanSchedule":{"intervalType":"DAILY","hour":0,"minute":0},"description":"testing"}}' -u admin:****** | json_pp …
```
=> ROX-22205: compliance configuration validation

deploy/common/k8sbased.sh, image/templates/common/setup-scanner-v4.sh, image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl, image/templates/helm/stackrox-central/templates/_init.tpl.htpl, pkg/renderer/readme.go, pkg/renderer/render_new.go, scripts/style/shellcheck_skip.txt
Deploying Stackrox using manifest bundles is done in 3 independent steps, where steps (2) and (3) are optional:
1. install Central
2. install Scanner
3. install Scanner-v4
However, when installing Central in step (1), the deployment will have `ROX_SCANNER_V4=true`, even though there is no Scanner v4 installed.
This PR skips setting `ROX_SCANNER_V4=true` when generating the manifest bundles. Instead, the env var will be set via the `scanner-v4/scripts/setup.sh` which is executed during step (3) above.
I generated a manifest bundle using `roxctl` and deployed it to an infra cluster, and verified that:
* the README file is generated correctly
* `ROX_SCANNER_V4=true` is not enabled until the Scanner-v4 installation step
* the deployment is …
=> ROX-22068: Add scanner-v4 setup script to manifest-based install

central/notifiers/cscc/convert.go, central/notifiers/cscc/cscc.go, central/notifiers/cscc/cscc_test.go
This PR fixes a few misbehaviors of the CSCC notifier, namely the following:
- when receiving an alert from a cluster that is _not_ deployed on GCP, the notifier would fail to send the violation to CSCC due to missing project ID information.
- when receiving an alert from a cluster that _is_ deployed on GCP, the notifier would always assume as a linked resource to the finding a GKE cluster.
The first issue can happen pretty often, in the case of OpenShift clusters deployed on GCP the metadata is currently always failing (is fixed in [pull/9659](https://github.com/stackrox/stackrox/pull/9659)).
To overcome the first issue, and also fixing the second one, the following is now established:
- In case the associated cluster is not running on GCP (either plain or GKE), the resource name will be …
=> ROX-21024: fix cscc notifier resource name

sensor/kubernetes/clusterstatus/openshift.go, sensor/kubernetes/clusterstatus/updater.go, sensor/kubernetes/clusterstatus/updater_test.go
OpenShift blocks access to the metadataservice of cloud providers. In case OpenShift is deployed using GCP / Azure / AWS, it currently is not possible to correctly attribute the clusters since the metadata call will fail.
The PR will now read metadata, in case none can be identified from metadata services of cloud providers, from the `config.openshift.io/v1/Infrastructure` CR. The CR contains basic information about the underlying provider that was used as well as the cluster name.
While there may be some issues (i.e. cloud provider specific things like subscription ID & region for Azure, account ID for AWS, zone for all) aren't available, this is definitely an improvement. Additionally, the fields that were left unset are not used
by any code part other than the CSCC notifier and …
=> ROX-21024: fetch metadata from infra CR on OpenShift

migrator/main.go
Try to access the database for a total of 5 minutes. This will help the tests fail less and give more leniency to the database start up time on installs and upgrades.
Trivial 
=> chore(fix): Be more lenient during initial DB connection

.github/workflows/check-pr-title.yaml
I never remember whether it should be plural or singular. How about allowing both forms?
=> test: allow both plural and singular tests, docs

qa-tests-backend/src/main/groovy/common/Constants.groovy, qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
Introducing "Internal Entities" required to update one assertion. It was missed on the PR as the check was not executed.
- CI - [link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/9723/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1753847053257019392)
=> ROX-22203: Fix "Verify intra-cluster connection via internal IP"

scripts/ci/logcheck/restart-ok-patterns.json
Adds restarted due to slow postgres startup, for pod restart CI check.
CI pod restart fails on some s390x ci runs, with scanner pod error
```{"Event":"Failed to open database.","Level":"error","Location":"database.go:81","Time":"2023-11-16 20:07:20.304992","error":"pgsql: could not open database: dial tcp 172.30.252.85:5432: connect: connection refused"}
{"Attempt":18,"Event":"Retrying connection to DB","Level":"warning","Location":"database.go:83","Time":"2023-11-16 20:07:20.305061"}
```
CI run is passing otherwise
Relying on CI
Relying on CI
=> ROX-19849: Add scanner pod restart pattern for slow db init 

ui/apps/platform/src/Containers/Clusters/Components/CredentialExpirationWidget.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundlesRoute.tsx, ui/apps/platform/src/Containers/Clusters/NoClustersPage.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/AuthenticationTokensSection.tsx
Replace placeholder `'Administration'` resource with `'Admin'` role according to:
https://github.com/stackrox/stackrox/blob/master/central/clusterinit/service/service_impl.go#L21
Here is the code snippet:
```ts
const { currentUser } = useAuthStatus();
const hasAdminRole = Boolean(currentUser?.userInfo?.roles.some(({ name }) => name === 'Admin')); // optional chaining just in case of the unexpected
```
1. Edit src/Containers/Clusters/Components/CredentialExpirationWidget.tsx
* Add conditional rendering for `ManageTokensButton` element.
2. Do not (yet) rename src/Containers/Clusters/Components/ManageTokensButton.tsx
* To minimize changes, if we need to revert this commit in case of emergency.
3. Edit src/Containers/Clusters/NoClustersPage.tsx
* Write comments about possibility after 4.4 …
=> ROX-22193: Use Admin role for access to cluster init bundles

image/templates/common/setup-scanner-v4.sh
Follow-up to [this comment](https://github.com/stackrox/stackrox/pull/9642#discussion_r1476286530) by @dcaravel 
I generated a manifest bundle using `roxctl` and deployed it to an infra cluster, and verified that:
* `ROX_SCANNER_V4=true` is set after the Scanner-v4 installation step
* the deployment is successful
=> ROX-22068: simplify scanner-v4 setup script

ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleWizardStep1.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleWizardStep2.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterPage.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterUsingHelmChart.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterUsingOperator.tsx
Goal to merge either end of day Friday or morning US Eastern time on Monday as prerequisite to turn on feature flag.
We can follow up with a second round of review if needed.
For cross-functional content review:
* Simon especially for correct and complete for primary audience.
* Kerry especially for clear and complete for primary audience, also that is aligned with docs and follows style guide.
* Mansur especially for user experience.
UI team can review component refactoring. Here are the 2 important files for content review:
* SecureClusterUsingOperator.tsx
* SecureClusterUsingHelmChar.tsx
Here are specific points for improvement from my viewpoint:
* Similar depth of detail between Operator and Helm chart.
* Order of prerequisites. See TODO for Helm chart.
* What is prerequisite to do …
=> ROX-21841: Add instructions for wizard step 2

sensor/common/processsignal/pipeline_test.go
Testing is failing and created: https://issues.redhat.com/browse/ROX-22262
Unit tests
=> fix(test): Disable TestProcessPipelineOnline due to timeout

image/templates/helm/shared/templates/02-scanner-v4-07-indexer-deployment.yaml, image/templates/helm/shared/templates/02-scanner-v4-07-matcher-deployment.yaml, scanner/cmd/scanner/main.go, scanner/indexer/indexer.go, scanner/indexer/mocks/indexer.go, scanner/matcher/matcher.go, scanner/matcher/mocks/matcher.go, scanner/matcher/updater/vuln/updater.go, scanner/matcher/updater/vuln/updater_test.go, scanner/services/matcher.go, scanner/services/matcher_test.go
Introduce HTTP routes to probe Scanner (Matcher, Indexer, or Combo) readiness based on the status provided by each backend.
1. **Indexer**: Database connection is OK.
2. **Matcher**: Database connection is OK, and vulnerability store is initialized (i.e. there are some vulnerabilities).
3. ~**Remote Indexer**: gRPC connection is ready or idle. Please give your opinion on keeping or removing this since the `Matcher` can perform Secured Cluster scans even if the Remote Indexer is not up.~ Check was removed after discussion in the PR.
Adding a gRPC endpoint for Health might make the Remote Indexer check more robust. I can do that separately.
1. Build Helm charts using `roxctl`:
```
roxctl helm output $(notdir $(@D)) \
--image-defaults=development_build \
--debug \
--debug-path image \ …
```
=> feat(scanner): Add readiness and liveness

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ComponentLocationTd.tsx
Before Scanner v4, `location` was always an empty string when the source was "OS". Now, we can have both 🎉 
View a CVE with a source of `"OS"` and a non-empty location:
=> ROX-22192: Remove location field tooltip when value is present

scanner/matcher/matcher.go
Staging uses release builds, which still requires access to the data, directly, instead of through Central/Sensor. For now, disable the requirement of going through Central/Sensor in release builds until ROX-19004 is complete.
CI …
=> chore(scanner): stop blocking traffic until Central is ready

tests/complianceoperator/crds/compliancesuites.yaml
Sensor in nongroovy was broken because there wasn't a compliancesuites CRD which caused Sensor never to fully sync. The addition of the CRD fixes it
Non groovy tests passing
=> fix(test): Add compliancesuites CRD for nongroovy tests

central/debug/service/service.go, pkg/k8sintrospect/collector.go, pkg/k8sintrospect/config.go
Disable the log file limits imposed by the `k8sintrospect` package when collectiong logs for the Central cluster / instance.
There are cases in bigger scale environments where this size limit hurts debugging issues, and since there's no danger of hitting the GRPC message size limit due to it being collected locally, we can safely ignore the max log size for Central cluster collection.
N/A.
=> fix(diag-bundle): ignore log limits for Central logs

.github/workflows/scanner-build.yaml, .github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-pr-vuln-update.yaml, .github/workflows/scanner-release-vuln-update.yaml
Cleanup docker resources in hopes we won't run out of disk space. We don't use the `scanner-test` CI image for most of these jobs because it hasn't been needed, it seems. 
CI
performed testing and you …
=> ci(scanner): cleanup docker resources

operator/apis/platform/v1alpha1/common_types.go, operator/pkg/central/values/translation/translation.go, operator/pkg/securedcluster/values/translation/translation.go, operator/pkg/securedcluster/values/translation/translation_test.go, operator/pkg/values/translation/translation.go, operator/pkg/values/translation/translation_test.go
Change SecuredCluster value translation to set `scannerV4.db.persistence.none = true` for scanner v4 DB if no default storage class is available which will instruct the helm chart to use an emptyDir volume.
On an infractl ocp:
```
export tag=4.3.x-nightly-20240205
export RELATED_IMAGE_SCANNER_V4_MATCHER=quay.io/rhacs-eng/scanner-v4:$tag
export RELATED_IMAGE_SCANNER_V4_INDEXER=quay.io/rhacs-eng/scanner-v4:$tag
export RELATED_IMAGE_SCANNER_V4_DB=quay.io/rhacs-eng/scanner-v4-db:$tag 
export RELATED_IMAGE_SCANNER=quay.io/rhacs-eng/scanner:$tag
export RELATED_IMAGE_SCANNER_DB=quay.io/rhacs-eng/scanner-db:$tag
export RELATED_IMAGE_MAIN=quay.io/rhacs-eng/main:$tag
export RELATED_IMAGE_CENTRAL_DB=quay.io/rhacs-eng/central-db:$tag
export …
```
=> feat(scanv4): operator SecuredCluster fallback for scanner v4 pvc

.github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-pr-vuln-update.yaml, .github/workflows/scanner-release-vuln-update.yaml, scanner/cmd/updater/main.go
We don't want to mess with the "dev" vulns, so disallow branches named "dev". Also, to avoid accidentally overwriting similarly named PRs, swap / for -
This PR also adds a link to the Slack notification for failed builds. See Slack for proof.
Lastly, this also extends the timeout for vuln data from 35 minutes to 1 hour
CI. Check the bucket to find `ross-harden-pr-vulns` instead of just `harden-pr-vulns` (which is what it …
=> ci(scanner): vuln update hardening

ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx
My bad to omit from #9728
Replace `hasWritePermissionForIntegration` with `hasAdminRole` to conditionally render `ManageTokens` element.
1. Visit /main/clusters with role other than **Admin** that has READ_WRITE_ACCESS for all resources
* Before change: see **Init bundles** button and click to see GET /v1/cluster-init/init-bundles has 403 Forbidden status
* After change: see absence of button
2. Visit /main/clusters with **Admin** role
* Before and after change: see **Init bundles** button and click to see GET /v1/cluster-init/init-bundles has 200 OK status
=> ROX-22341: Render Init bundles button for Admin role only

.openshift-ci/begin.sh
We currently have 92 UI and 42 QA OCP 4.14 jobs queued in CI. These will take many days to clear as due to a misconfig on the openshift/release side they are set to run serially. This change will cause the jobs to exit quickly and should drain the queue within 24 hours after which point this PR can be reverted.
=> tests: drain stuck OCP 4.14 jobs

image/templates/helm/shared/config-templates/scanner-v4/matcher-config.yaml.tpl, scanner/config.yaml.sample, scanner/config/config.go, scanner/config/config_test.go, scanner/matcher/updater/vuln/updater.go, scanner/matcher/updater/vuln/updater_test.go
We want to be able to support running Scanner v4 as a StackRox service and separate from the rest of the services. To do that, the `vulnerabilities_url` must be configurable. Unfortunately, not all endpoints are created equally, and it's hard to determine the correct URL.
This approach attempts to make this simple for users. Scanner v4 vuln data is versioned, and requiring every user to update the configured version, themselves, is not feasible. Hence, this PR introduces `ROX_VERSION`, which, if added to the `vulnerabiltiies_url` will be replaced with the version of Scanner v4. This also allows for queries to Central to look like `https://central.stackrox.svc/api/extensions/scannerdefinitions?version=ROX_VERSION` and direct queries to GCP to look like …
=> ROX-19005: pull vulnerabilities from a configurable URL

generated/internalapi/scanner/v4/indexer_service.pb.go, pkg/scannerv4/client/client.go, proto/internalapi/scanner/v4/indexer_service.proto, scanner/services/indexer.go, scanner/services/indexer_test.go
When implementing client-side load balancing for Scanner v4, it was determined we'd have to build a customer load balancer to choose connections in a way that makes sense for our particular use case (https://github.com/stackrox/stackrox/pull/9643). Specifically, we wanted to balance calls to `CreateIndexReport`, as that requires more resources than `GetIndexReport`.
With this PR, we reduce the calls from Central to Scanner v4 Indexer from 2 to 1 call, via `GetOrCreateIndexReport`. This way, we only have a single request to Scanner v4 Indexer, and we can revert back to the builtin round-robin load balancer.
Note: it is still possible we get unlucky with the normal round_robin load balancer. For example:
Let's say there are two indexers.
1. Central requests an image to be scanned
2. Indexer …
=> chore(scanner): add GetOrCreateIndexReport endpoint to Indexer

.openshift-ci/begin.sh
Reverts stackrox/stackrox#9796
The original PR does not work as intended because the queued jobs are tested in relation to their commit (of course - doh!)
=> Revert "tests: drain stuck OCP 4.14 jobs"

ui/apps/platform/cypress/integration/integrations/integrations.helpers.js, ui/apps/platform/src/sagas/index.js
Follow up #9711 and #9728
To bad, so sad, sagas do not support feature flags.
Therefore, comment out instead of delete so we could uncomment in the unlikely case we needed to turn off `ROX_MOVE_INIT_BUNDLES_UI` feature flag.
When we delete `ROX_MOVE_INIT_BUNDLES_UI` feature flag after 4.4 release.
1. Delete src/reducers/clusterInitBundles.js
2. Delete src/sagas/clusterInitBundleSagas.js
1. Visit /main/integrations with role that has only Integration resource with  READ_ACCESS level
* Before change: see GET /v1/cluster-init/init-bundles has 403 Forbidden status
* After change: see absence of request
=> ROX-22339: Remove init-bundle request from clusterInitBundleSagas

pkg/features/list.go
This feature flag adds STS and workload identities to various AWS and GCP integrations. The feature flag has been active in CI for a while.
=> chore: enable cloud credentials feature flag

sensor/kubernetes/complianceoperator/utils.go, tests/compliance_operator_v2_test.go
Add label and annotation to ScanSetting (SS) and ScanSettingBinding (SSB) created by StackRox. …
=> ROX-18452: Add ACS labels to SS and SSB CR

go.mod, go.sum, scanner/indexer/indexer.go, scanner/indexer/indexer_test.go
These changes update the ClairCore version to an unreleased version containing the feature to disable the Java PackageScanner from reaching out to Maven. This configuration is intended to air gap the Java indexer.
A unit test was added to ClairCore to for disabling the HTTP client from reaching out to Maven. The unit test included in this PR ensures we add that the ClairCore configuration.
=> ROX-16918: Ensure Java scanner is air gapped

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/ViewScanConfigDetail.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ClusterSelection.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ProfileSelection.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/useFormikScanConfig.tsx, ui/apps/platform/src/hooks/useAlert.test.ts, ui/apps/platform/src/hooks/useAlert.ts, ui/apps/platform/src/services/ComplianceEnhancedService.ts
This change adds a Re-scan button to the Detail View page for a scan configuration.
(Note: I'm using this PR to add a re-usable hook for managing Alert state, because we do that in several places in the app with bespoke code on each page. If we find this useful, we could replace the bespoke code with this pattern.)
I tested that the new button is on the read-only detail view when the user has Write permission for Compliance.
I clicked the button, and observed in the Network panel of the browser's developer tools, that the correct API call is made to trigger a new scan. I also disable the Re-scan and edit buttons, and show a progress indicator in the Re-scan button.
If the API call succeeds, I show a dismissible Success Alert below the toolbar, near the button that triggered it.
I blocked …
=> ROX-21818: Add Scan Now functionality to Compliance 2.0

central/complianceoperator/v2/compliancemanager/manager_impl.go, central/complianceoperator/v2/compliancemanager/manager_impl_test.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl_test.go, central/complianceoperator/v2/scanconfigurations/datastore/mocks/datastore.go, tests/compliance_operator_v2_test.go
Updates to inform the user where they can find the config executing a duplicate profile and what profile is conflicting.
UT and executed on a local cluster …
=> ROX-22187:  compliance name conflicting profile

pkg/registries/ecr/ecr.go, pkg/registries/ecr/transport.go, pkg/registries/ecr/transport_test.go, pkg/registries/google/google.go, pkg/registries/google/transport.go
I caught this embarrassing bug while testing the new STS feature set. The order in the token validity check is reversed, which causes the token to become stale eventually.
The bug went unnoticed because the initial token exchange works as expected, and subsequent requests even refresh the token. A continuous 12 hour period of no scans is required for the token to become permanently broken.
To fix it I flipped the logic from `isExpired` to `isValid` in analogy to Google and other tokens.
Wait for token to expire, and then perform an image scan. …
=> fix: ecr registry token expiry

sensor/kubernetes/complianceoperator/handler_impl.go, sensor/kubernetes/complianceoperator/handler_impl_test.go, sensor/kubernetes/complianceoperator/utils.go
The Update compliance message had assumed that all the objects had been created.  However it is possible for an update of a scan configuration to add a cluster.  In those cases the compliance operator CRs would not have been created.  So in those cases we need to treat those as adding resources instead of updating the resources.  This could also occur in an instance where there was an error that was encountered writing the CRs and then the configuration was updated after the error was resolved.  
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into …
=> ROX-22253:  compliance update add

go.mod, go.sum, operator/bundle/manifests/rhacs-operator-manager-config_v1_configmap.yaml, operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/bundle_helpers/patch-csv.py, operator/config/default/kustomization.yaml, operator/config/manager/controller_manager_config.yaml, operator/config/manager/manager.yaml, operator/config/rbac/kustomization.yaml, operator/main.go
Its functionality is now built into the controller-runtime library, so the manager can serve the metrics endpoint directly. This lets us get rid of a dependency that proved to be problematic (see ticket's parent for more background) and make a tiny dent in operator pod's RAM/CPU needs.
AFAICT the `go.mod` changes are a result of importing "sigs.k8s.io/controller-runtime/pkg/metrics/filters" which has additional dependencies.
I hope making `--replace-rbac-proxy` in the `patch-csv.py` script into a no-op is a reasonable migration strategy, @msugakov ? Additional downstream cleanup will be tracked in [ROX-22355](https://issues.redhat.com/browse/ROX-22355).
This change should be transparent to users.
CI should be enough with the recently added metrics test mentioned above.
As requested by …
=> ROX-22289: drop kube-rbac-proxy sidecar

central/convert/storagetov1/discovered_cluster.go, central/convert/typetostorage/discovered_cluster.go, central/discoveredclusters/datastore/datastore.go, central/discoveredclusters/datastore/datastore_impl_postgres_test.go, central/discoveredclusters/service/service.go, central/discoveredclusters/service/service_impl.go, central/discoveredclusters/service/service_impl_postgres_test.go, central/discoveredclusters/service/service_impl_test.go, central/discoveredclusters/service/singleton.go, central/main.go, pkg/fixtures/discovered_cluster.go
The service for the discovered cluster API. Discovered clusters are returned by cloud source integrations (e.g. PaladinCloud, OCM) and represent a cloud provider inventory of potential clusters to secure. We want to fetch these clusters and show them along with their status in a discovered cluster list in the UI.
What's potentially missing is populating the `source.name` field with the cloud source name depending on UI need.
CI integration test
=> ROX-21773: discovered clusters service

generated/api/v1/image_service.pb.go, generated/api/v1/image_service.swagger.json, proto/api/v1/image_service.proto
It was wrong before
Before:
After:
~[ ] Investigated and inspected CI test results~
I looked at the docs.
=> fix(docs): Incorrect API doc for CountImages

central/sensor/service/connection/connection_impl.go
Since it doesn't matter to ACS if the delete of a scan configuration failed, swallow the error.
That said I did write https://issues.redhat.com/browse/ROX-22399 for later. …
=> ROX-22390: compliance silent delete message

central/complianceoperator/v2/profiles/service/service_impl.go, central/convert/storagetov2/compliance_profile_service.go
When the profile refactoring was done to better fit with SAC, there was a comment to not build a query to get distinct summaries in the datastore layer but to get the data and reduce it in the storage layer.  Apparently when I implemented that, I made all the updates except the reduce part.  It was difficult to see because you need multiple clusters to drive the condition.  This PR resolves that by reducing it to unique profiles for the given clusters.
If any of these …
=> ROX-22404:  compliance profile fix summary

pkg/scannerv4/client/client.go, pkg/scannerv4/client/options.go, pkg/scannerv4/client/options_test.go, scanner/cmd/scannerctl/main.go
This allows us to use `scannerctl --insecure-tls-verify` again.
https://github.com/stackrox/stackrox/pull/9555 enabled mTLS between StackRox services, but broke this workflow due to `clientconn.UseInsecureNoTLS(o.skipTLS)`. In that PR, this line was accidentally added because I thought `o.skipTLS` meant to skip TLS. It turns out it meant `skipTLSVerify`, so I updated the name and stopped using `UseInsecureNoTLS`. We don't actually want to disable TLS, just the cert/host name verification.
Before this change I found `./bin/scannerctl --insecure-tls-verify scan https://quay.io/stackrox-io/scanner:4.3.0` would error:
Client:
```
{"level":"debug","method":"GetOrCreateImageIndex","image":"quay.io/stackrox-io/scanner@sha256:6d9067814d1b6959c992aa925efbedc5ae8e39564f464791b26231f092b838a6","compo …
```
=> fix(scanner): scannerctl --insecure-skip-tls-verify

central/administration/events/service/service_impl.go, central/cloudsources/service/service_impl.go, central/cloudsources/service/service_impl_postgres_test.go, central/discoveredclusters/service/service_impl.go, central/discoveredclusters/service/service_impl_postgres_test.go, central/resourcecollection/service/service_impl.go, pkg/fixtures/cloud_sources.go, pkg/fixtures/discovered_cluster.go
I noticed a bug while looking at the pagination code of some services. Confusingly, `paginated.FillDefaultSortOption` does not behave like `paginated.FillPagination` and does not modify the input query. Instead it returns a copy of the filled query.
Tested sort options for admin events and cloud sources API.
=> fix: pagination default sort

central/cloudsources/datastore/internal/store/postgres/gen.go, central/cloudsources/datastore/internal/store/postgres/store.go, pkg/search/postgres/store_cache.go
This PR fixes a difference in behavior of the cached store and the generic store: when using the cached store with global resources, it currently fails the generated tests.
The tests expect during a Delete to return `sac.ErrResourceAccessDenied` when write isn't allowed. The generic store returns no error for namespace / cluster scoped resources, but an error for global resources.
For the time being, this fixes the behavior of failing tests, as well as enables the `cached-store` for the cloud-sources which were initially blocked by it.
A follow-up should be created to fix the behavior for _all_ stores: either return `sac.ErrResourceAccessDenied` for _all permission failures_ irrespective of resource scope, or return nil.
- see CI passing …
=> fix(cache-store): fix Delete for global resources.

pkg/net/endpoint.go, pkg/net/ip_port.go, pkg/net/ip_port_test.go, pkg/netutil/private_subnet.go, sensor/common/networkflow/manager/manager_impl.go, sensor/common/networkflow/manager/manager_impl_test.go
Collector reports network flows to Sensor using the [`NetworkAddress` proto message](https://github.com/stackrox/stackrox/blob/master/proto/internalapi/sensor/network_connection_info.proto#L54-L61).
The message has two fields for carrying IP data information:
```proto
message NetworkAddress {
bytes address_data = 1; // semantics determined by socket_family of the given connection
uint32 port = 2; // may be 0 if not applicable (e.g., icmp).
// Represents an IPV4 or IPV6 network. First 4/16 bytes representing network address whereas following byte represents
// the length of network prefix. If used, this field must have 5 or 17 bytes; otherwise it should be discarded.
// `ip_network` and `address_data` usage should be mutually exclusive.
bytes ip_network = 3;
}
```
Most of the times, …
=> ROX-22206: Improve decision about internal vs. external IP address

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/general.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ExceptionRequestsPage.tsx
This PR retains the search filters when switching between tabs in Exception Management
https://github.com/stackrox/stackrox/assets/4805485/0dd354a1-aa82-46df-91ad-7b60388f58e5
=> ROX-21472: Don't clear filters when switching tabs

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Clusters/ClusterDetailsTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Components/CheckStatusModal.css, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Components/CheckStatusModal.tsx, ui/apps/platform/src/services/ComplianceEnhancedService.ts
Work for the compliance v2 check details modal
When a user clicks on the status of an individual check result, we want to provide them more information on the selected compliance check.
=> ROX-21881: compliance check details modal

central/cloudsources/manager/manager.go, central/cloudsources/manager/manager_test.go, central/cloudsources/manager/singleton.go, central/cluster/datastore/datastore.go, central/cluster/datastore/datastore_impl.go, central/cluster/datastore/mocks/datastore.go, pkg/cloudsources/paladin/client.go, pkg/cloudsources/paladin/client_test.go, pkg/cloudsources/paladin/testdata/response.json
This PR adds the matching logic to match discovered clusters with existing secured clusters.
This will ensure that discovered clusters will have their status (i.e. whether they are already secured or not) populated based on existing secured clusters known to Central.
Matching currently works as follows:
- In case secured clusters do not have any `ProviderMetadata` associated with them, they will not be considered for matching.
- In case secured clusters have partial `ProviderMetadata` (this can mean either that the `ClusterMetadata` type is unspecified _or_ the name / ID of the cluster is empty), the provider type will be marked as `Unspecified` during matching. The reason we decided to go with this is to avoid having false-positives (i.e. mark a cluster Unsecured even though it _may_ be …
=> feat(cloud-sources): discovered cluster matching

deploy/common/k8sbased.sh
The find invocation in `k8sbased.sh` was bogus. This PR adjust the parameters for the find invocation.
* Manually tested that the find invocation lists the files it it supposed to list.
* It was confirmed that these tests fix the scale tests run locally.
* CI.
=> fix(scanv4): Fix find invocation

pkg/renderer/readme.go
Due to the fact that Scanner V4 installation is optional in 4.4, this PR changes the README in the `central-bundle` of roxctl manifest-based installs to show:
```
- Deploy Scanner components
- Run scanner/scripts/setup.sh
- Run oc create -R -f scanner
- Optional: Deploy Scanner V4 components
- Run scanner-v4/scripts/setup.sh
- Run oc create -R -f scanner-v4
```
Note that this only makes it clear to the user that the Scanner V4 step is optional. Not installing Scanner V4 is already supported.
```bash
make cli
roxctl central generate openshift pvc
```
And verified that the `README` file is generated as expected.
performed one …
=> fix(scanv4): Mark Scanner V4 as optional in manifest based install

roxctl/connectivity-map/command.go, roxctl/generate/generate.go, roxctl/netpol/connectivity/connectivity.go, roxctl/netpol/connectivity/diff/README.md, roxctl/netpol/connectivity/diff/command.go, roxctl/netpol/connectivity/map/README.md, roxctl/netpol/connectivity/map/command.go, roxctl/netpol/generate/README.md, roxctl/netpol/generate/generate.go, roxctl/netpol/netpol.go
As in the title.
- Running the commands locally and making sure that the tech preview warning is not visible
- Running the commands with `-h` argument and checking that help texts do not contain any tech preview text
=> ROX-18443: Remove tech-preview warning for NP-Guard integrated code

central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl.go
The error for when a profile was used in multiple scan configurations was showing an array of scan configurations.  Meaning if you had a conflict on multiple clusters it would list the offending configuration once per cluster.  See this:
Switched the map to use a set to the offending configuration on shows up once.
See screenshots above from actual runs and execution of the scenario. …
=> ROX-22433: scan config profile error duplicate

pkg/features/list.go, tests/e2e/lib.sh, ui/apps/platform/README.md, ui/apps/platform/cypress/constants/apiEndpoints.js, ui/apps/platform/cypress/integration/integrations/integrations.helpers.js, ui/apps/platform/src/Containers/Integrations/CreateIntegrationPage.tsx, ui/apps/platform/src/Containers/Integrations/EditIntegrationPage.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/MachineAccessIntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationForm/IntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationPage.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/AuthenticationTokensSection.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/IntegrationTile.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/MachineAccessTile.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsListPage.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsTable.tsx, ui/apps/platform/src/Containers/Integrations/hooks/useFetchIntegrations.ts, ui/apps/platform/src/Containers/Integrations/hooks/useIntegrationActions.ts, ui/apps/platform/src/Containers/Integrations/hooks/useIntegrations.ts, ui/apps/platform/src/Containers/Integrations/utils/integrationUtils.test.ts, ui/apps/platform/src/Containers/Integrations/utils/integrationUtils.ts, ui/apps/platform/src/Containers/Integrations/utils/integrationsList.ts, ui/apps/platform/src/Containers/Integrations/utils/tableColumnDescriptor.ts, ui/apps/platform/src/reducers/index.js, ui/apps/platform/src/reducers/machineAccessConfigs.js, ui/apps/platform/src/sagas/index.js, ui/apps/platform/src/sagas/machineAccessSagas.js, ui/apps/platform/src/services/IntegrationsService.ts, ui/apps/platform/src/services/MachineAccessService.ts, ui/apps/platform/src/types/featureFlag.ts, ui/apps/platform/src/types/integration.ts
Implementation of mocks by @mansursyed. 
A few differences: 
* There's no documentation on configuration types, so that is left out
* The format used for token expiration is the same as the backend one (example: `3h20m30s`). 
This PR implements list view, as well as create/update/view page for [M2M authentication configs](https://github.com/stackrox/stackrox/blob/master/proto/api/v1/auth_service.proto#L37-L82). Backend is already implemented by @dhaus67.
Epic link: [ROX-20100](https://issues.redhat.com/browse/ROX-20100)
1. Deployed backend with  latest `master` version on infra
2. Enabled `ROX_AUTH_MACHINE_TO_MACHINE` env flag
3. Deployed UI locally and connected to infra backend
4. Verified that create, update, delete, view, list …
=> ROX-20222: M2M auth config UI forms

central/metrics/central.go, central/metrics/init.go, central/sensor/enhancement/broker.go, sensor/common/deploymentenhancer/component.go, sensor/common/metrics/init.go, sensor/common/metrics/metrics.go
This PR adds two new metrics:
- **[Sensor]** the enhancement queue size, to track if sensors are getting more requests that they can handle
- **[Central]** histogram of the roudtrip time (i.e. how long it takes in average to get a sensor enhancement from sensor 
=> ROX-21344: Add deployment enhancement metrics

.github/workflows/nightly-tag.yml
Replaces https://github.com/openshift/release/blob/master/ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml#L225-L240.
OSCI jobs failed multiple times in the last few days due to insufficient test capacity and other scheduling issues.
We cannot retry or manually dispatch this job in OSCI. Switching to GHA solves those issues. 
Tested workflow run with a push to `tm/ROX-15193-move-nightly-tag-to-gha` triggered https://github.com/stackrox/stackrox/actions/runs/7870585089/job/21472067866, which is what I expected.
This rebased the `nightlies` branch and created https://github.com/stackrox/stackrox/releases/tag/4.3.x-nightly-20240212. 
Afterwards, I removed the branch trigger again.  …
=> ROX-15193: move nightly tag action to GHA

central/auth/datastore/datastore.go, central/auth/datastore/datastore_impl.go, central/auth/datastore/datastore_impl_test.go, central/auth/datastore/singleton.go, central/auth/m2m/exchanger.go, central/auth/m2m/mocks/exchanger.go, central/auth/m2m/mocks/set.go, central/auth/m2m/set.go, central/auth/service/service_impl.go, central/auth/service/service_impl_test.go, central/auth/store/store.go
This changes the auth m2m datastore to use a transaction during the update of m2m configs.
This is required due to the nature of the issuer store, which is an in-memory store for token issuer sources.
It would happen in cases where an existing configuration would be updated that:
- a new token exchanger from the config is created, since it is an existing token exchanger the token source will be unregistered, otherwise this fails during creation.
- in case DB upsert fails or any other operation, we would be left in a broken state: a token exchanger with no existing source will be left.
This would then also lead to failures in the removal, since the token issuer store cannot find the associated source, and will error out. …
=> fix(auth): use transaction during m2m config update / delete

generated/internalapi/central/compliance_operator.pb.go, proto/internalapi/central/compliance_operator.proto, sensor/kubernetes/complianceoperator/updater.go
Rename function for better readability to `getComplianceOperatorDeployment`
- CI
=> fix(compliance): Rename function to `getComplianceOperatorDeployment`

pkg/renderer/templates/public_values.yaml.tpl, tests/e2e/run-scanner-v4.bats
Our installation tests check if scanner-v4 is deployed (or not), but they do not check if Central is configured correctly to use scanner-v4 or not.
The checks revealed a problem when doing a fresh installation of HEAD Helm chart with Scanner V4 disabled and enabling it later, and the PR includes a fix for this.
The issue was the following:
* `ROX_SCANNER_V4` is registered as a feature flag, and we have an env var in CI with the same name, and so it gets pulled into the public-values.yaml. (see [here](https://github.com/stackrox/stackrox/blob/daa61eafc079a2b908d064b2ddf555f77ee19028/roxctl/central/generate/generate.go#L185) and [here](https://github.com/stackrox/stackrox/blob/daa61eafc079a2b908d064b2ddf555f77ee19028/pkg/renderer/templates/public_values.yaml.tpl#L200))
* this causes …
=> test(scanv4): Check that scannerv4 Central env var is set correctly

ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersPage.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersTable.tsx, ui/apps/platform/src/services/DiscoveredClusterService.ts
Follow up backend changes in #9837
1. Edit src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersPage.tsx
* Add `useEffect` to call `fetchCloudSources` and instantiate `sourceNameMap` if user role has `'Integration'` resource.
2. Edit src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersTable.tsx
* Add `sourceNameMap` prop and replace `source.name` with `sourceNameMap.get(source.id) ?? 'Not available'`
* Replace TODO with `nameField` and `firstDiscoveredAtField` as args in `getSortParams` function calls.
3. Edit src/services/DiscoveredClusterService.ts
* Delete `name` property from `DiscoveredClusterCloudSource` type according to service proto:
https://github.com/stackrox/stackrox/blob/master/proto/api/v1/discovered_cluster_service.proto#L68-L70
* Replace TODO for …
=> ROX-21984: Update source name and sorting in discovered clusters

central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl_test.go
When a cluster was removed we were deleting all the status rows for a scan config instead of just the rows for the cluster being deleted.
Updated the unit test
Tested locally with 2 clusters.  Created a scan configuration applied to both clusters.  Deleted one of the clusters.  Ensured that the details of the scan configuration showed that the remaining cluster was still in the scan configuration.
Before after 1 of 2 …
=> ROX-22455: compliance prune cluster status bug

central/complianceoperator/v2/checkresults/datastore/datastore_impl.go
The sort ordered wasn't being applied.  it was only applied if pagination was nil.  But the service layer adds the default pagination to the max number of pages.  As such the pagination was never nil and thus sort order was not applied.
Ran scans and verified the sort order of the cards is now as one would expect.
Before:
After:
In addition to reviewing code here, reviewers **must** also review testing and request …
=> ROX-22459:  compliance results card sort

ui/apps/platform/cypress/integration/clusters/Clusters.selectors.js, ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx
Because Tailwind spacing seemed questionable for conditional rendering of anywhere between all and none of the buttons, I took a chance to replace classic page layout above the table with PatternFly:
* Except for `AutoUpgradeToggle` element.
* Tailwind `h-full` for table concerned me, so I temporarily cloned the one row to see whether scrolling worked for 10 rows. Because there was indeed a scrolling problem with a mix of PatternFly `PageSection` and class panel components, I took one more step to replace `div` with `PageSection` element which has `isFilled` prop.
```sh
export ROX_CLOUD_SOURCES=true
```
main.js 28 = 3950590 - …
=> ROX-22049: Conditionally render Discovered clusters button

ui/apps/platform/src/Components/PatternFly/SearchFilterChips.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersToolbar.cy.jsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersToolbar.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/SearchFilterNames.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/SearchFilterStatuses.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/SearchFilterTypes.tsx, ui/apps/platform/src/services/DiscoveredClusterService.ts
Modifies the existing "By type" search filter to be a checkbox multi-select instead of a single, and adds search components to allow the addition of multiple name and type filters.
Via automated testing:
- Verify the behavior of the name input text box independently
- Verify the behavior of the multiselect dropdowns with "select all" option
- Verifies that the full set of search components correctly tracks search state in the URL and displays the current state via chips
Video of manual testing verifying the behavior of the filters in combination together and with the URL:
https://github.com/stackrox/stackrox/assets/1292638/55386475-91e0-44df-91cf-2020893f9ec4
=> ROX-22048: Add search filters for DiscoveredClusters

pkg/grpc/server_ratelimit_test.go, pkg/grpc/server_test.go
This PR aims to improve the test stability, however, I couldn't reproduce the failing tests as they fail rarely.
These tests can flake sometimes with a panic where gRPC port is already in use. This can be due to multiple tests conflicting with each other, or failing to call stop properly. 
- Ran tests multiple times locally
- CI
=> ROX-21632: Make gRPC tests more robust

ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx
Follow up #9881
Direct classic-to-PatternFly replacement emphasizes difference in arrangement compared to recent table pages.
1. Violations
* Heading
* Filter violations
* Table row actions (also known as bulk actions) and pagination
2. Workload CVEs
* Default vulnerability filters
* Heading and tagline with **Manage watched images** button at the right
* Search filters
* Toggle, bulk actions, and pagination
3. Policy Management
* Heading
* Tabs
* Tagline with **Create policy** and **Import policy** buttons at the right
* Search filter, bulk actions, **Reassess all** button, and pagination
4. Collections
* Heading and tagline with **Create collection** button at the right
* Search filter and pagination
5. Administration Events
* Heading and tagline
* Search filters, last updated, and …
=> ROX-22478: Rearrange elements at upper edge of Clusters page

deploy/common/deploy.sh
A minor fix for when deploy/common/deploy.sh is run from outside of the stackrox repository. 
There is automation for deploying long running clusters in the stackrox/actions repository. When I run the following script in the stackrox/actions directory 
```
#!/usr/bin/env bash
set -eou pipefail
export MAIN_IMAGE_TAG=0.0.9
export API_ENDPOINT=localhost:8000
export STORAGE=pvc
export STORAGE_CLASS=faster
export STORAGE_SIZE="100"
export MONITORING_SUPPORT="true"
export LOAD_BALANCER=lb
export ROX_ADMIN_USERNAME=admin
export PAGERDUTY_INTEGRATION_KEY=adfsasdf
export REGISTRY_USERNAME=jvirtane@redhat.com
export REGISTRY_PASSWORD="*********"
export KUBECONFIG=/tmp/artifacts-long-fake-load-0-0-9/kubeconfig
export STACKROX_DIR=/${HOME}/go/src/github.com/stackrox/stackrox
export …
```
=> fix: Run deploy script in stackrox repo

pkg/cloudproviders/gcp/auth/cred_manager_impl_test.go, pkg/k8scfgwatch/cfg_watcher_test.go, pkg/metrics/server_test.go, pkg/metrics/tls_test.go, pkg/secretinformer/informer_test.go
I noticed a bug in several tests using `assert.EventuallyWithT` - the wrong testing context was used (parent instead of inner most one). The fix should also rid of us another open test flake related to this issue (https://issues.redhat.com/browse/ROX-22198). 
Verified eventually calls with explicit fails.
=> ROX-22198: fix `EventuallyWithT` tests

deploy/common/k8sbased.sh, tests/e2e/run-scanner-v4.bats
Currently `launch_sensor()` attempts to generate scanner deployment bundles unconditionally.
This PR changes the behaviour so that this bundle is only generate if
1) `roxctl` is found (and the version matches)
and
2) the variable `GENERATE_SCANNER_DEPLOYMENT_BUNDLE` is set to `true` in the environment.
CI testing should be sufficient for this change.
=> fix(deploy-tooling): Generate scanner bundles if roxctl exists

image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl, operator/tests/central/central-misc/080-assert-non-openshift.yaml, operator/tests/central/central-misc/080-assert-openshift.yaml
This PR sets an environment variable to enable collection of API endpoint metrics for `/api/splunk/ta`, which is a non-standard endpoint only our Splunk TA uses.
This enables us to get an idea how many centrals are running with a set up connection to Splunk, allowing us to better prioritize RFEs and bug reports for the TA.
- Automated E2E tests
- Manual testing in Amplitude by setting up a dev central with dev telemetry key
=> ROX-22239: Add Splunk TA to API metrics

roxctl/scanner/generate/generate.go
Scanner manifest bundles also contain V4 manifests nowadays. Hence the slight adjustment in the description of the sub command.
=> docs(roxctl): Mention Scanner V4 in roxctl doc string

central/complianceoperator/v2/compliancemanager/manager.go, central/complianceoperator/v2/compliancemanager/manager_impl.go, central/complianceoperator/v2/compliancemanager/manager_impl_test.go, central/complianceoperator/v2/compliancemanager/mocks/manager.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore.go, central/complianceoperator/v2/scanconfigurations/datastore/datastore_impl.go, central/complianceoperator/v2/scanconfigurations/datastore/mocks/datastore.go, central/complianceoperator/v2/scanconfigurations/service/service_impl.go, central/complianceoperator/v2/scanconfigurations/service/service_impl_test.go
When a scan configuration was updated such that it removed a cluster, we were not deleting the configuration on the deleted sensor nor were we removing the cluster from the scan configuration status.  This PR does both and refactors things slightly to separate the creation of a scan configuration from the update.
Added some unit test cases.  
Additionally did some testing running on 2 clusters to ensure that the delete …
=> ROX-22371, ROX-22372: compliance update scan config delete cluster

ui/apps/platform/cypress/integration/clusters/Clusters.helpers.js, ui/apps/platform/cypress/integration/clusters/discovered-clusters/DiscoveredClusters.helpers.js, ui/apps/platform/cypress/integration/clusters/discovered-clusters/DiscoveredClustersPage.test.js, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersTable.tsx
Replaced one occurrence of **State** (as in visual mock) with **Status** (arguably clearer and also consistent with query and response).
```sh
export ROX_CLOUD_SOURCES=true
```
Before you `yarn cypress-open` in ui/apps/platform folder:
```sh
export CYPRESS_ROX_CLOUD_SOURCES=true
```
* clusters/discovered-clusters/DiscoveredClustersPage.test.js
=> ROX-22489: Add regression tests for discovered-clusters route in UI

CHANGELOG.md, central/resourcecollection/service/service_impl.go, central/resourcecollection/service/service_impl_test.go
This PR adds the capability to show the names of references objects and which type they have.
The errors appear not in the same windows because of formatting problems. 
The error message before only mentioned that something referenced the collection, but lacked any information about the source of the reference.
**✅ Report configuration:**
**✅ Collections:**
**❌🗑️ Combined error output, but abandoned because of lack of readability: ❌**
- Added and adjusted unit tests
- Deletion blocked by report config should display report config name
1. Create a collection
2. Configure report configuration, add the created collection to it. 
3. Try to delete the collection
4. **Expected:** Error message should contain the report configuration which …
=> ROX-21729: Enhance collection delete error message

.github/dependabot.yaml
We want full control over the ClairCore dependency, so do not allow Dependabot to touch it.
no
=> chore(deps): dependabot ignore claircore

central/complianceoperator/v2/profiles/datastore/datastore_impl.go, central/convert/storagetov2/compliance_profile_service.go
Profile summaries weren't being sorted.
Before:
After:
=> ROX-22519: compliance sort profiles summaries

qa-tests-backend/src/main/groovy/util/Env.groovy, qa-tests-backend/src/test/groovy/AuditLogAlertsTest.groovy, qa-tests-backend/src/test/groovy/DeploymentTest.groovy, qa-tests-backend/src/test/groovy/RoutesTest.groovy, scripts/ci/jobs/rosa_qa_e2e_tests.py
Various e2e tests fixes for ROSA HCP:
- AuditLogAlertsTest - disabled due to lack of access under HCP. ROX-22448 opened to cover "Ensure audit log policy collection cannot be enabled under HCP" which may require additional test coverage.
- DeploymentTest - use the openshift-console namespace. ROSA HCP does not surface the apiserver in the openshift-apiserver namespace.
- RoutesTest - LoadBalancers are stuck in Pending under HCP. Disabled the test for now and opened ROX-22502 to investigate ROSA HCP + service LoadBalancer support.
CI+: …
=> fix(tests): add ROSA HCP support

central/complianceoperator/v2/compliancemanager/manager_impl.go, central/complianceoperator/v2/compliancemanager/manager_impl_test.go
API requests to create Scan Configs currently lack details about why a request failed validation. This change tacks an error message onto the return string bubbled up to the HTTP API if the cluster used in the request doesn't exist. Otherwise, the user doesn't know exactly why their request failed.
This change might be a good place to discuss additional validation cases we want to test, and how we can do that consistently for a better user experience. Additionally, these validation errors could be useful to the front end.
~~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into …
=> ROX-22083: Provide validation details through API for ScanConfig

ui/apps/platform/cypress/integration/clusters/init-bundles/InitBundleForm.test.js, ui/apps/platform/cypress/integration/clusters/init-bundles/InitBundles.helpers.js, ui/apps/platform/cypress/integration/clusters/init-bundles/InitBundlesPage.test.js
Before you `yarn cypress-open` in ui/apps/platform folder:
```sh
export CYPRESS_ROX_MOVE_INIT_BUNDLES_UI=true
```
* clusters/init-bundles/InitBundleForm.test.js
* clusters/init-bundles/InitBundlesPage.test.js
=> ROX-21840: Add regression tests for cluster init bundles route in UI

scripts/ci/gke.sh
GKE clusters are broken in CI. `calico-node` pods do not reach a Ready state. This
PR reverts the version pin to v1.26 in the hopes that the stable channel is more
stable :).
Ref: https://redhat-internal.slack.com/archives/CC5UHD0KA/p1708015656314549
and: https://github.com/stackrox/stackrox/pull/7537
=> fix(tests): unpin GKE version

tests/common_test.go
`--grace-period=1` to delete things faster
Non-groovy tests
=> fix(test): Delete deployments faster in nongroovy tests

CHANGELOG.md, pkg/env/image_scan.go
This gives us more time to handle larger images. It also aligns with Quay's timeout when reaching out to Clair: https://github.com/quay/quay/blob/v3.10.3/util/secscan/v4/api.py#L26
nah
=> chore(scanner): bump scan timeout from 6m to 10m

.tekton/main-pull-request.yaml, .tekton/main-push.yaml, image/rhel/konflux.Dockerfile, scripts/konflux/subscription-manager/.dockerignore, scripts/konflux/subscription-manager/.gitignore, scripts/konflux/subscription-manager/bro.self-test-demo.Dockerfile, scripts/konflux/subscription-manager/bro.self-test-multiple-targets.Dockerfile, scripts/konflux/subscription-manager/bro.self-test.Dockerfile, scripts/konflux/subscription-manager/subscription-manager-bro.sh
The use of entitled packages required inventing something new. I hope it does not live for long and we'll be able to use Konflux solution for that. That said, I tested the script many times in different combinations, locally and in Konflux, and I'm fairly confident in it for the time being.
See commit messages where I tried supplying relevant info.
These aren't needed and won't be done:
- ~~[ ] Unit test and regression tests added~~ - not this time, see notes on testing below.
Check that Konflux CI is green, including EC.
Used `subscription-manager-bro.sh self-test` to test locally. Decided to not put this in CI for the following reasons, I hope having it as a local-only tool is ok.
1. It takes ~10 minutes to run on my machine.
2. Automating in CI requires setting up secrets.
3. I hope …
=> ROX-20160: Install RHEL packages into Konflux-built main

ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersToolbar.cy.jsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersToolbar.tsx
1. Because several testers expected **Name** search filter to have partial match, but it has exact match, comment out **Name** filter for MVP.
2. Because a tester complained about flicker, comment out `isDisabled={isDisabled}` prop for filters and pagination.
1. Although a tester commented about change in table height as a result of search filter, defer for MVP to be safe. Quick comparison to other recent pages have similar behavior, but much less apparent because those tables are in lower half of the page.
```sh
export ROX_CLOUD_SOURCES=true
```
1. Visit /main/clusters and click **Discovered clusters** button.
* See absence of name filter.
* Tested filtering to see absence of flicker.
Before you `yarn cypress-open` in ui/apps/platform folder:
```sh …
```
=> ROX-22558: Make changes after team test of discovered clusters UI

image/templates/helm/shared/internal/scanner-v4-config-shape.yaml, image/templates/helm/shared/templates/_scanner-v4_init.tpl.htpl, image/templates/helm/stackrox-central/internal/defaults.yaml.htpl, image/templates/helm/stackrox-central/templates/NOTES.txt.htpl, image/templates/helm/stackrox-secured-cluster/internal/defaults/70-scanner-v4.yaml.htpl, image/templates/helm/stackrox-secured-cluster/templates/NOTES.txt.htpl, image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml
[ROX-22542](https://issues.redhat.com/browse/ROX-22542)
Sorry to iterate on this, but...
Let me begin with the status quo: Currently there are three Scanner V4 related `disable` toggles: `scannerV4.disable`, `scannerV4.indexer.disable` and `scannerV4.matcher.disable`. Initially, when Scanner V4 has been integrated into the Helm charts, we (or, I?) thought it might be a good idea to enable the use of all three such toggles with the following semantics:
* The primary switch that should be primarily relevant to users is `scannerV4.disable`, it should cause the Helm chart to pick the right selection of Scanner V4 components to be deployed. On central side that is indexer *and* matcher. On secured-cluster side that is only indexer and now matcher..
* The idea was that even though these …
=> fix(scanv4): Reduce flexibility in Scanner V4 config

deploy/common/deploy.sh
Adds a popd at the end of a script that has a pushd at the beginning. This can cause errors in some cases, for example if the KUBECONFIG is a relative path. This bug was preventing the long running clusters from being deployed correctly.
The workflow for the long running clusters can be found here https://github.com/stackrox/test-gh-actions/actions/runs/7926610760
The …
=> fix: Directory change in deploy script

image/templates/helm/shared/internal/scanner-v4-config-shape.yaml, image/templates/helm/shared/templates/02-scanner-v4-07-db-deployment.yaml, image/templates/helm/shared/templates/02-scanner-v4-07-indexer-deployment.yaml, image/templates/helm/shared/templates/02-scanner-v4-07-matcher-deployment.yaml, image/templates/helm/stackrox-central/internal/defaults.yaml.htpl, image/templates/helm/stackrox-secured-cluster/internal/defaults/70-scanner-v4.yaml.htpl
This does the following:
* Bump the minimum replicas for Indexer to 2
* Bump the minimum replicas for Matcher to 2
* Add `affinity` configurations for Indexer and Matcher
* Move `affinity` configuration for Scanner V4 DB into a separate location to match Indexer and Matcher
CI …
=> chore(scanner): update Scanner V4 installation configurations

ui/apps/platform/src/Components/DashboardLayout/DashboardLayout.js, ui/apps/platform/src/Components/ScannerV4IntegrationBanner.tsx, ui/apps/platform/src/Containers/VulnMgmt/Dashboard/VulnMgmtDashboardPage.js, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx, ui/apps/platform/src/types/imageIntegration.proto.ts
Adds a banner to the UI in VM 1.0 and VM 2.0 when a Scanner V4 integration does not exist. If the user does not have integration permissions, this banner will not be shown and the request will not be sent.
1. Thoughts on a `<Banner variant="info" />` (shown below) vs an `<Alert />`? The Banner seems semantically correct, but VM 2.0 does use an Alert to declare that the feature is tech preview. Using two persistent Alerts may look odd though.
2. Currently a new request will be sent and the banner will flicker each time the user navigates back to the VM 1.0 dashboard from within another VM 1.0 page. In contrast, VM 2.0 shows the banner persistently which results in no flicker and a single network request (until the user leaves that Container). Thoughts on making the banner persistent across …
=> ROX-22559: Add banner when a scanner v4 integration is not present

central/cloudsources/datastore/datastore.go, central/cloudsources/datastore/datastore_impl.go, central/cloudsources/datastore/datastore_impl_postgres_test.go, central/cloudsources/datastore/singleton.go, central/cloudsources/service/service_impl.go
Previously, discovered clusters associated with specific cloud sources have been kept upon removal.
This PR ensures that we remove the associated discovered clusters once we remove a cloud source.
- see CI tests.
=> fix(cloud-sources): remove discovered clusters with cloud sources

tests/roxctl/authz-trace.sh, tests/roxctl/token-file.sh
The roxctl tests failed due to the token not being fetched properly:
```sh
curl: (7) Failed to connect to 34.41.81.139 port 443: Connection timed out
```
In Central I found a suspicious log
```
2024/02/17 04:46:14 http: TLS handshake error from 35.227.122.18:39774: tls: first record does not look like a TLS handshake
```
I'm not sure what the root cause of this error is since the `curl` does specify `https`, but in general retries have successfully reduced the flakes in these roxctl tests. So I think it's worth a shot and won't hurt.
CI tests pass …
=> ROX-22583: retry api token generation

sensor/upgrader/preflight/access.go
This should prevent really chatty error messages like here: https://redhat-internal.slack.com/archives/C02HX541YQN/p1707422841968359
- Manually on GKE using the following steps:
- Install ACS from this branch
- Set Sensor image manually to 4.2
- Let the Sensor Upgrader run and attempt to upgrade Sensor
- Navigate to URL/main/clusters to check the upgrade status
- Notice Sensor Upgrade error as in the picture below:
=> fix(chatty-errors): Compact error msg for long list of k8s resources

ui/Makefile
When I ran a UI `Makefile`, it produced the following error on the console
```
$ make lint
find: ‘packages’: No such file or directory
```
Apparently, this comes from
```Makefile
SOURCES := $(shell find packages -type d \( -name node_modules \) -prune -o -print)
```
line trying to work on `packages` directory which no longer exists.
The last files from this directory were removed in this commit <https://github.com/stackrox/stackrox/commit/4d7209c1c374366b28dcd86d7d4de2be427a5c6c>. Compare the tree
- as of this commit https://github.com/stackrox/stackrox/tree/4d7209c1c374366b28dcd86d7d4de2be427a5c6c/ui - no `packages`
- and as of its parent (previous) https://github.com/stackrox/stackrox/tree/87a59e845f7bf1aaeb1b5856d968eb73f3ea8834/ui - `packages` were there before.
In this change I …
=> fix: Eliminate `find: ‘packages’` error in `ui/Makefile`

operator/apis/platform/v1alpha1/central_types.go, operator/apis/platform/v1alpha1/common_types.go
Removed an useless `default` annotation [see here](https://github.com/kubernetes-sigs/kubebuilder/pull/2288)
- The annotations are used to generate the CRD jsonSchema, and no changes to the schema were observed after removing this annotation.
=> ROX-7805: Remove useless defaults

qa-tests-backend/src/main/groovy/objects/ImageIntegration.groovy, qa-tests-backend/src/main/groovy/util/Env.groovy, qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
Use the ci workload identity to test short-lived credentials for GCP image integrations. I also added a test case for long lived tokens for Artifact registry because those tests were missing before.
QA tests.
=> ROX-21034: qa-e2e test for wif image integrations

central/cloudsources/manager/manager.go, central/cloudsources/service/service_impl.go, central/cloudsources/service/service_impl_postgres_test.go, go.mod, go.sum, pkg/cloudsources/client.go, pkg/cloudsources/ocm/client.go, pkg/cloudsources/ocm/client_test.go, pkg/cloudsources/ocm/testdata/response.json, pkg/cloudsources/paladin/client.go, sensor/kubernetes/clusterstatus/openshift.go, sensor/kubernetes/clusterstatus/updater_test.go
This introduces OCM support for cloud sources, and covers the following pieces:
- Adding the cluster ID to the cluster metadata collected by Sensor, this is required for matching discovered clusters with secured clusters (where the type is OCP, ARO, ROSA, OSD).
- implement the client for interacting with the OCM API.
- improve the matching to only rely on the ID for matching instead of the tuple of ID & provider type (we can match on ID only since for our known cluster types the IDs have a distinct format irrespective of cluster type).
A few caveats to point out:
The `accounts_mgmt` API was used in favor of the `clusters_mgmt` API; I have found that this is way more performant compared to the cluster one, and also what `console.redhat.com/openshift` does.
The search query to limit the …
=> feat(cloud-sources): add OCM support

scanner/config.yaml.sample, scanner/services/common.go, scanner/services/indexer.go, scanner/services/indexer_test.go, scanner/services/matcher.go, scanner/services/matcher_test.go
Change Scanner APIs to return "not found" when the Index Reports in the DB are not successful.
This should allow re-scanning and avoid image scanning being blocked by failed IRs in the workflow such as `GetOrCreateIndexReport.` Also, `GetVulnerabilities` will correctly report "not found" instead of empty scans. 
```
make build
./bin/scanner --conf config.yaml &
./bin/scannerctl --insecure-skip-tls-verify scan https://quay.io/quay-qetest/python3-test-image:latest | tee /tmp/r.json
```
This image has a permanent error that prevents it from being Indexed. Expect "not found" from the Matcher call, but successful `CreateIndex` calls. Inspect the logs to confirm.
Indexer:
```
{"level":"error","host":"descending","component":"scanner/service/inde …
```
=> fix(scanner): Return not found when IRs are unsuccessful

deploy/common/k8sbased.sh
These changes make it clearer when docker is used and what container image it's using for `roxctl` when using the deploy scripts.
- ~~[ ] Investigated and inspected CI test results~~
- ~~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))
These changes only affect local development.
New log:
```
❯ ./deploy/deploy-local.sh
...
Generating central config...
Using docker with quay.io/stackrox-io/roxctl:latest for install. Set …
```
=> chore(deploy-tooling): log when docker is used in deploy script

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveListExceptionFlow.test.js
Every changing CVE data has resulted in flakes in the e2e tests due to there being no CVEs that match the default applied filters. This clears the filters in the failing tests when the feature flag is enabled.
Also fixes an incorrect assertion on image scope that honestly I'm not sure how it was passing at all until this point...
See relevant failure here: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/9979/pull-ci-stackrox-stackrox-master-gke-ui-e2e-tests/1758512955600670720
Local Cypress run.
Await CI
=> fix(ui): Clear default filters before running exception flow test

tests/e2e/lib.sh
The logic to grep out pod descriptions from the restart check output was missing "". `echo` condenses unquoted multiline strings to a single line and so the cut logic matched on the initial part of the output. This PR changes it to use "" and grab only the first part of the pod name - a compromise to deal with the vagaries of pod names and otherwise we end up with e.g. sensor-ztyvd. 
Validated with the output found in:
https://issues.redhat.com/issues/?jql=project%20%3D%20ROX%20AND%20summary%20%20~%20%22Pod%20Restarts%22%20ORDER%20BY%20created%20DESC
performed …
=> fix(tests): use container names for pod restart description

qa-tests-backend/src/test/groovy/ReconciliationTest.groovy, qa-tests-backend/src/test/groovy/VulnReportingTest.groovy
https://issues.redhat.com/browse/ROX-22586 - is missing debug for the test namespace which makes it hard to determine root cause. `collect-qa-service-logs.sh` will gather from all namespaces starting `qa`.
=> fix(CI): add qa- prefix to tests namespaces

central/complianceoperator/v2/compliancemanager/manager_impl.go, central/complianceoperator/v2/compliancemanager/manager_impl_test.go, central/complianceoperator/v2/compliancemanager/singleton.go, tests/compliance_operator_v2_test.go
Added validation to the scanrequest so it does not contains any incompatible profiles, ex. we want to prevent scan being created if it contains both rhcos and ocp node profiles as they are not yet supportted by Compliance Operator
Added e2e test and unit test to test creating scan config with both rhcos4 and ocp4 node profiles in single request.
=> ROX-21599: Prevent scan configurations with incompatible profiles

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ClusterSelection.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ProfileSelection.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ScanConfigWizardForm.tsx
This addresses validation concerns with the scan config wizard
Included:
- An alert banner now appears and scrolls into view if a user does not select a profile or cluster from the table but proceeds to click the "Next" button
- Alerts on the review step related to submission will now be reset if a user changes steps
- Profiles/Clusters step: alert should not appear until either the user clicks the next button without a selection, or if a user makes a selection then goes back to a state where nothing is selected
- Review step: alerts triggered by submission should go away if user navigates away from the review step by either hitting "Back", or clicking on another step in the wizard nav
=> ROX-22274: Compliance scan config wizard validation

ui/apps/platform/cypress/integration/clusters/redirectFromDashboard.test.js, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterModal.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterPage.tsx, ui/apps/platform/src/Containers/Clusters/NoClustersPage.tsx
Thanks to Zhenpeng for clear changes. Adjusted somewhat to fit the context:
1. Update empty state text pre and post bundle to make clearer where trial user is in the process and what to expect next.
2. Change primary button text, especially replace **Review** with **View**.
3. Add link to create another init bundle in case of lost YAML file.
Temporarily edit code to simulate no clusters and no bundles.
1. Visit /main/clusters with simulated no clusters and no bundles.
* See **Clusters** heading element at upper left for consistency whenordinary clusters page displays secured clusters (see step TODO).
* See updated pre-bundle text which has xl size.
* See **Create init bundle** button.
* See **Legacy installation method** link.
2. Click **Legacy installation method** link.
* See …
=> ROX-22496: Make critical improvements to usability on NoClustersPage

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Clusters/ClusterDetailsTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/compliance.coverage.utils.tsx, ui/apps/platform/src/services/ComplianceEnhancedService.ts, ui/apps/platform/src/utils/searchUtils.ts
Addresses the following issues related to the cluster coverage page
* Add a tooltip to the status indicator to provide more information about what the status means.
* Add the regex prefix (`r/`) to the search filter “Compliance Check Name”. This performs a “contains” search as opposed to a “starts with” search.
* Added a new utility function to help with this.
* Go to the first page automatically when the search filter changes or when selecting results by a different scan.
* Use the new `GetComplianceScanConfigurationResults` endpoint for getting cluster results by scan configuration. 
* This endpoint was created due to the discovery of a bug when fetching results where one scan’s name started with the name of another entire scan. For example, `my-scan` and `my-scan-2` led to results for …
=> ROX-22601: address compliance cluster details issues

qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy
Update hard coded CVE counts for defaultPolicesTests with regex for power and s390x image layers
Relying on CI
=> fix(tests): Update multiarch image CVE counts for DefaultPolicesTest

central/cloudsources/service/service_impl.go, central/cloudsources/service/service_impl_postgres_test.go, pkg/cloudsources/client.go, pkg/cloudsources/mocks/client.go, pkg/cloudsources/ocm/client.go, pkg/cloudsources/opts/options.go, pkg/cloudsources/paladin/client.go
This PR fixes an issue observed with the test API: the API itself currently calls the default `GetDiscoveredClusters`, and in case more clusters are fetched it may take more than 10 seconds.
10 seconds is the timeout by the UI, which means we do not get a clear error message in case things aren't working as expected.
Instead, we introdcue now a separate ping function which should be used for such purposes. The ping function itself provides a 10 second timeout via context.
For OCM, we will attempt to fetch the current account information (essentially mimicking `ocm whoami`), for Paladin Cloud the API call will stay as-is, unless we find a more appropriate API call to use. …
=> fix(cloud-sources): use lower timeout for test API

ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredCluster.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersPage.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersTable.tsx
Rewrote tooltips:
* to remove reference to product branding
* in parallel form
* with input from Stephan about undetermined status ~and added link via info alert~
```sh
export ROX_CLOUD_SOURCES=true
```
main.js 0 = 3951581 - 3951581
total 1346 = 10544860 - 10543514
files 0 = 92 - 92
Disregard info alert with link which has been deleted.
1. Visit /main/clusters/discovered-clusters with temporary data for request.
* Secured
* Unsecured
* Undetermined
Tooltip simplified to delete duplicated word and second sentence:
> This cluster has been discovered by a cloud source, but …
=> ROX-22625: Add tooltip for discovered cluster status and date

pkg/scannerv4/client/client.go
Ignore proxy settings when Central/Sensor talks to Scanner V4
ACSCS test instance has a squid proxy set up. Deployed this PR to this test instance and found fetching the Vuln update time no longer times out (nor receives 403 status codes). We now see the vuln update time
Used the same instance to scan a few images after verifying the proxy environment variables were set in the indexer containers
In addition to reviewing code …
=> fix(scanner): disable proxy-use when talking to Scanner V4

image/templates/helm/shared/templates/_scanner-v4_init.tpl.htpl, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml
Small bug fix. Noticed while installing secured-cluster-services, that the post-install notes contained an inconsistency:
```
Secured Cluster Configuration Summary:
[...]
Scanner V4:                                  disabled
Please take note of the following:
[...]
- Scanner V4 is enabled and Scanner V4 components are already deployed.
```
It is acceptable to assume trust and keep this section light, …
=> fix(scanv4): Helm chart lies about Scanner V4 being enabled

ui/apps/platform/src/Components/CveType/CveType.tsx, ui/apps/platform/src/Containers/VulnMgmt/Entity/Cve/VulnMgmtCveOverview.js
Reported by @RTann in a chat thread.
> I noticed in the VM 1.0 Images list > CVE single Overview view taht CVE Type is Unknown but when I am in top-level CVE single Overview view (no idea the terminology, but I pressed the box with the arrow facing up and to the right. can someone tell me the proper terms?) it says Image CVE.
In the "sidebar" view, the CVE is in the context of an image. In the "external" view the CVE is the top-level entity seen in isolation.
It a conflict between some code to allow for multiple "vulnerability types" added three years ago, and some conditional code added 20 months ago when we split the CVE datastore into image, node, and cluster. My guess is that this has been broken since the migration to Postgres, but there could have been other changes since then--even …
=> fix(ui): Fix CVE Type in VM 1.0 nested Overview pages

tests/e2e/yaml/compliance-operator/subscription.yaml
We're experiencing an issue with upstream CO installs where the content doesn't parse correctly during installation, leading to the following trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x78a916]
```
Let's use the downstream compliance operator until we fix the upstream regression.
ACS v2.0 compliance e2e testing should pass successfully.
=> Install Compliance Operator from downstream sources

image/templates/helm/shared/config-templates/scanner-v4-db/postgresql.conf.default, image/templates/helm/shared/templates/02-scanner-v4-07-db-deployment.yaml, image/templates/helm/shared/templates/02-scanner-v4-07-matcher-deployment.yaml, image/templates/helm/stackrox-central/internal/defaults.yaml.htpl, image/templates/helm/stackrox-secured-cluster/internal/defaults/70-scanner-v4.yaml.htpl, pkg/helm/charts/tests/centralservices/testdata/helmtest/scanner-v4.test.yaml
Resource updates:
* Matcher's soft memory limit set to 3.80GiB instead of 4.75GiB
* This is an attempt to minimize memory usage and avoid OOMs
* This tells the Go runtime to do its best to keep memory usage to at most 3.80GiB, but we will have a 1.2GiB buffer, if needed
* Setting it to a level below the requested memory in an attempt to ensure we can still update vulnerabilities when we cannot use more than the requested amount of memory
* Bump DB memory request to 3GiB. Testing with the following postgres settings showed higher memory usage, so might as well require more memory
Postgres configuration changes:
* max_connections 100 -> 500
* This is computed via 1.25 *(40 * maxIndexers + 40 * maxMatchers) in the Central Cluster
* SecuredCluster is 1.25 * 80 * maxIndexers
* Increase …
=> chore(scanner): update resources and postgres configs

.github/workflows/scanner-offline-bundle-update.yaml, .github/workflows/scanner-release-vuln-update.yaml, .github/workflows/scripts/scanner-update-offline-bundle.sh
* Remove workflow triggering by branches called `scanner/*`
* Use the job-preamble to optimize space availability and also ensure checkout is done first. There are currently some warnings about this
* Add a link to the failed workflow
CI
performed one does not seem sufficient. As a reviewer, you must not approve …
=> ci(scanner): minor offline vuln feed updates

.github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-release-vuln-update.yaml, .github/workflows/scripts/scanner-update-offline-bundle.sh, central/scannerdefinitions/handler/handler.go, central/scannerdefinitions/handler/updater_test.go, scanner/config.yaml.sample, scanner/config/config.go, scanner/updater/version/RELEASE_VERSION
Store vuln bundle in definitions.stackrox.io instead of test bucket 
```
curl --insecure -u admin:[pwd] https://localhost:8000/api/extensions/scannerdefinitions?version=dev > dev.json.zst
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  149M  100  149M    0     0  39.2M      0  0:00:03  0:00:03 --:--:-- 39.2M
yli3-mac:stackrox yili$ ls -lh dev.json.zst 
-rw-r--r-- 1 yili staff 150M Feb 21 09:01 dev.json.zst
yli3-mac:stackrox yili$ 
```
```
curl --insecure -u admin:[pwd] https://localhost:8000/api/extensions/scannerdefinitions?version=4.3.0 > 4.3.0-defs.json.zst
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  138M  100  138M    0 …
```
=> ROX-22121: migrate vuln bucket

compliance/collection/compliance/compliance.go, sensor/common/compliance/service_impl.go
Recently, we are getting error reports from the code that handles Sensor-Compliance connection. Many of the error logs read strange due to the duplicated word `error`. This PR corrects 3 such places.
I have not.
=> style(log): Avoid duplicate 'error' word in error messages

roxctl/central/initbundles/revoke.go, roxctl/central/initbundles/revoke_test.go, roxctl/common/flags/confirm.go
Fixing the `roxctl initbundle revoke` command to include affected cluster ids …
=> ROX-16618: Fix roxctl initbundle revoke

deploy/common/monitoring.sh
This adds Scanner V4 support to the `deploy/common/monitoring.sh` script, which can be used for setting up monitoring for StackRox manifest bundle deployments.
It is also acceptable to skip testing …
=> ROX-22631: Support Scanner V4 in monitoring script

central/networkbaseline/manager/manager_impl.go, central/networkbaseline/manager/manager_impl_test.go
Apparently I missed one place in code that needed to be updated with the new constant ID of Internal Entities.
=> ROX-22680: Let baseline manager recognize Internal Entities

sensor/kubernetes/clustermetrics/cluster_metrics_test.go
Saw a flake here: https://github.com/stackrox/stackrox/actions/runs/8001439883/job/21852650205
This is not a bullet-proof solution (for that we would need to use a time-independent ticker), but it should help.
=> fix(flake): ClusterMetrics TestOfflineMode

pkg/images/enricher/enricher_impl.go, pkg/images/enricher/util.go
In CI we have seen the following:
```
scan could not be completed. Please check that an applicable registry and scanner is integrated
```
This is very vague, and not very helpful. This PR adds some more context to help us determine what the issue may be.
nah
performed one does not seem sufficient. As a reviewer, …
=> chore(central): improve scan error messaging

image/templates/helm/stackrox-secured-cluster/templates/sensor.yaml.htpl, pkg/env/sensor.go, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/scanner-v4.test.yaml, sensor/common/scannerclient/grpc_client.go
ROX_SCANNER_V4_GRPC_ENDPOINT -> ROX_SCANNER_V4_INDEXER_ENDPOINT
It's wordier, but specific
Just used GoLand to search for all instances of `ROX_SCANNER_V4_GRPC_ENDPOINT` and replaced them. One instance was a Helm test …
=> ROX-21709: use ROX_SCANNER_V4_INDEXER_ENDPOINT

pkg/scanners/scannerv4/convert.go, pkg/scanners/scannerv4/convert_test.go, scanner/mappers/mappers.go, scanner/mappers/mappers_test.go
Scanner V2 falls back to NVD data when the vendors do not provide severities/scores. We already do that here, too, except for OSV, which we originally assumed would populate the `Severity` field. Unfortunately, not every entry in OSV populates this, so we will fall back to NVD data for this case.
Note: it's still possible we do not see any CVSS score/severity when falling back, as the vuln may not have an NVD entry. This makes sense for a brand new vulnerability, but this may also be the case for OSV vulns which cannot be attributed to a CVE in any way.
For example: https://osv-vulnerabilities.storage.googleapis.com/Go/GO-2023-2375.json
Though the alias says `CVE-2023-45287`, we miss this, as ClairCore does not read the aliases at this time. We at least will no longer skip this …
=> ROX-22422: fall back to NVD for CVSS scores/severities when missing

pkg/cloudproviders/gcp/auth/cred_manager_impl_test.go
In https://github.com/stackrox/stackrox/pull/9845 blocking code in the informer setup was removed. As a result, we must now wait in the test until the informer has synced. Otherwise we may lose events.
CI + `gotest -v ./... -count=100`.
=> ROX-22678: wait for informer sync in test

central/cloudsources/manager/manager.go, central/cloudsources/manager/manager_postgres_test.go, central/cloudsources/manager/manager_test.go, central/cloudsources/manager/mocks/singleton.go, central/cloudsources/manager/singleton.go, central/convert/storagetotype/discovered_clusters.go, central/sensor/service/pipeline/clusterstatusupdate/pipeline.go
This PR adds support to react on the cluster status health change, i.e. when a cluster is becoming unhealthy.
Previously, clusters that haven't been secured anymore (i.e. they have become unhealthy) would still show up as secured in the discovered clusters section.
This now adds hooks to the manager to ensure we react on the events of sensor disconnects correctly and set the discovered cluster state, if any exists, to unsecured.
- see CI.
Manual tests:
1. Create a cloud source integration which contains a cluster of your choice.
2. Make this cluster as secure, logs should be shown for marking the cluster as secure; also verify this in the UI:
```log
cloudsources/manager: 2024/02/19 01:30:10.158088 manager.go:101: Info: Marking discovered …
```
=> fix(cloud-sources): react on secured cluster status health

central/cloudsources/manager/manager.go, pkg/cloudsources/discoveredclusters/discovered_cluster.go
Remove the `discoveredCluster.GetType()` from the UUID generation. We don't really need it to be apart of the UUID since the ID of the cluster and cloud source ID shall be enough.
This also aligns with the matching logic.
=> chore(cloud-sources): remove type from uuid

pkg/features/list.go
Enable the `Cloud Sources` feature flag by default, since we also plan to release it with 4.4.
=> chore(cloud-sources): enable feature flag by default

central/scannerdefinitions/handler/handler.go, central/scannerdefinitions/handler/handler_test.go
Update scanner definitions handler to support v4 vuln bundle file
1. Support scanner-v4-defs upload via POST
2. Support reading scanner-v4-defs while scanner request for vuln file
0. Deploy
`export OFFLINE_MODE=true`
use this PR's image
run deploy-local.sh
1. 
```
unzip -l scanner-vuln-updates.zip
Archive:  scanner-vuln-updates.zip
Length      Date    Time    Name
---------  ---------- -----   ----
140154404  02-14-2024 11:41   scanner-defs.zip
248088  02-14-2024 11:41   k8s-istio.zip
144211510  02-14-2024 11:41   scanner-v4-defs-4.3.zip
---------                     -------
284614002                     3 files
```
2. Upload
`curl --insecure -u admin:[PWD] -F "file=@scanner-vuln-updates.zip" https://localhost:8000/api/extensions/scannerdefinitions -v`
```
...
* Server auth using Basic …
```
=> ROX-21981: Support v4 offline bundle in Central

scanner/enricher/nvd/nvd.go, scanner/enricher/nvd/nvd_test.go
`TotalResults` gives you the total number of unpaginated results for the query, while `ResultsPerPage` tells you how many results were given in the paginated query. For each query, we determined the next startIdx by the `TotalResults` field instead of `ResultsPerPage`.
Because of this, we missed about 100k vulnerabilities.
This PR adds some logs, and we can see the difference between commits in this PR:
[Using `TotalResults`](https://github.com/stackrox/stackrox/actions/runs/8023040607/job/21918675476):
```
{"level":"debug","updater":"nvd","component":"enricher/nvd/Enricher/ParseEnrichment","count":115412,"time":"2024-02-23T18:23:49Z","message":"decoded enrichments"}
```
This (almost) matches what I found when I checked the DB in my test cluster:
```
postgres=# SELECT COUNT(*) FROM …
```
=> fix(scanner): read all NVD CVEs

.openshift-ci/begin.sh
These changes add ocp-stable in our OSCI node settings since I wrongly changed the pattern in this PR: https://github.com/openshift/release/pull/48519. This should eventually be removed after scanner v4 is enabled by default in CI (or when this file is removed: https://github.com/openshift/release/blob/a14f76e0918b047d2406e9eb6baac82b55ced05a/ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-stable-scanner-v4.yaml
- ~~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rh …
=> fix(ci): add ocp-stable in OSCI node settings

central/cloudsources/datastore/datastore.go, central/cloudsources/datastore/datastore_impl.go, central/cloudsources/datastore/datastore_impl_postgres_test.go, central/cloudsources/datastore/internal/store/mocks/store.go, central/cloudsources/datastore/internal/store/postgres/gen.go, central/cloudsources/datastore/internal/store/postgres/store.go, central/cloudsources/datastore/internal/store/postgres/store_test.go, central/cloudsources/datastore/internal/store/store.go, central/cloudsources/manager/manager.go
This introduces the `GetAll` function on the cloud sources store / datastore. The reason for it is that a) we expect this to be a low cardinality store, hence `GetAll` is applicable and b) we want to make use of the cached store behavior in the manager.
In case searches are performed (i.e. by passing a `v1.Query`) the cached store currently will _always_ call the underlying store, effectively skipping the cache. Hence, the manager will resort to use `GetAll` now which will make use of the cache.
Alternative to introducing `GetAll` would have been to use `Walk` instead, however I've chosen the `GetAll` due to its simplicity and the only current use-case being the manager. …
=> chore(cloud-sources): use GetAll with cache

central/cluster/datastore/datastore_impl.go
This fixes a data race in the `Walk` function of the cluster datastore. Similar to other functions where the clusters will be returned, `ds.collectClusters` will be used which clones each cluster
and afterwards applies the cluster health and priority to it. We have to do the same for the `Walk` function since we want to expose the health status.
- see CI passing (specifically race tests)
=> ROX-22697: Fix data race in cluster walk

sensor/common/component.go
The `SyncFinished` notification was not handled by `LogSensorComponentEvent`. This led to sensor logging the following messages: 
```
Info: Component runs now in unknown (sync-finished) mode
``` …
=> fix(logging): Handle the SyncFinished event in the logger

central/notifiers/awssh/notifier.go
AWS Security Hub notifier has 3 data items in credentials: `AccessKeyId`, `SecretAccessKey` and `StsEnabled`. Among these, `StsEnabled`  is not a secret and thus, its value will not be kept up-to-date in the encrypted string. The credentials are re-encrypted only if fields that are considered secret are changed. Since `StsEnabled` is not one, changes to its value will not trigger a re-encryption. Furthermore, when sending notifications, the decryption function should only be used to decrypt data that is considered secret. Thus the decryption function will only decrypt and return secret values. Non-secret values can directly be fetched from the notifier object.
- ~[ ] Determined and …
=> fix(be): Do not use AWSSH decrypt function  to get value of StsEnabled

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameTd.tsx
Updates the icon of the copy button and fixes alignment so that icon is not right aligned to table cell.
Before:
After:
=> fix(ui): Fix visuals of image name copy button

ui/apps/platform/src/services/DiscoveredClusterService.ts
The pagination offset was not being calculated correctly when the user hits `>` in the pagination component. This PR fixes that.
The network calls should look as below:
=> ROX-22684: Fixing pagination for Discovered Clusters table

ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleForm.tsx, ui/apps/platform/src/Containers/Clusters/InitBundles/InitBundleForm.utils.ts, ui/apps/platform/src/Containers/Clusters/NoClustersPage.tsx
Also adding prefix to the cluster init bundle file name as requested by UX for easier search for the user
=> ROX-22666: Adding link to cluster init bundles from empty clusters

pkg/cloudsources/client.go, qa-tests-backend/src/main/groovy/services/CloudSourcesService.groovy, qa-tests-backend/src/main/groovy/services/DiscoveredClustersService.groovy, qa-tests-backend/src/main/groovy/util/Env.groovy, qa-tests-backend/src/test/groovy/CloudSourcesTest.groovy
This adds BAT tests for the cloud sources feature: we are going to create a valid OCM cloud source, verify that the test functionality on the integration works, and that we get discovered clusters from the cloud source.
=> test(cloud-sources): add BAT for OCM cloud sources

pkg/auth/tokensource/tokensource.go, pkg/auth/tokensource/tokensource_test.go, pkg/cloudproviders/gcp/auth/client_manager_impl.go, pkg/cloudproviders/gcp/auth/client_manager_impl_test.go, pkg/cloudproviders/gcp/utils/util.go, pkg/registries/docker/config.go, pkg/registries/docker/docker.go, pkg/registries/ecr/ecr.go, pkg/registries/ecr/transport.go, pkg/registries/ecr/transport_test.go, pkg/registries/google/google.go, pkg/registries/google/transport.go, pkg/registries/ibm/ibm.go, pkg/registries/quay/quay.go
We noticed a potential issue with short-lived registry tokens and cached code paths when looking into scanner v4 on acs-cs. Some context: In 4.4, we are introducing short-lived tokens as authentication for registry image integrations. Contrary to the previous statically held long-lived tokens, the short-lived tokens have a validity of 1h (GCP) or 12h (AWS), and must be refreshed to keep access to the registry.
The token refresh is handled as part of the docker registry transport. This means that it is refreshed automatically upon usage of the docker registry client. The problem is now the following: In addition to usage in the docker client, the docker credentials are also passed around by themselves - in particular they are passed to scanner in the enrichment step.
When Central has ran a …
=> fix: ensure access tokens are valid

central/scannerdefinitions/handler/handler.go
If the matcher is requesting "dev" vuln file, Central should make sure the offline vuln is also "dev"
Note the "dev" offline bundle needs to be created manually at this moment
=> fix(scanner): include dev in offline mode

qa-tests-backend/src/main/groovy/services/ClusterService.groovy, qa-tests-backend/src/test/groovy/BaseSpecification.groovy, qa-tests-backend/src/test/groovy/TLSChallengeTest.groovy
OCP 3.x is no longer supported in QA e2e tests. Nor are there any jobs running that [_think_](https://search.dptools.openshift.org/?search=.*isOpenShift3.+true.*&maxAge=336h&context=1&type=build-log&name=.*stackrox.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job) they are openshift 3.x. This API call can be flaky, so lets remove it where it is not needed. 
=> ROX-22693: remove isOpenShift3()

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/ExceptionManagement.helpers.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/approveRequestFlow.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/cancelRequestFlow.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/denyRequestFlow.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/general.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/pendingRequestsTable.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/requestDetails.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/updateRequestFlow.test.ts, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/cveListExceptionFlow.test.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/deploymentSingle.test.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageCveSingle.test.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js, ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/workloadCveOverviewPage.test.js
A frequent source of UI e2e test flakes is a limited number of CVEs being available in CI when the tests run. This has been amplified by the addition of default filters, which only display `Critical` and `Important` CVEs by default in the Workload CVE sections. Since these are the first CVEs to be fixed, the default filters can sometimes return zero results, depending on the state of the images being used.
Previously this was handled ad-hoc in the following ways:
- Skipped tests if the `ROX_WORKLOAD_CVES_FIXABILITY_FILTERS` flag was off
- Manually click the "Clear filters" button if `ROX_WORKLOAD_CVES_FIXABILITY_FILTERS` was on
- Sometimes wait on the table data to load, sometimes not
This PR makes the following changes:
- Removes all of the above implementations
- Adds a single …
=> fix(ui): Move clearFilters functionality to single location in tests

pkg/grpc/server.go
Availability of v2 API endpoints should not depend on whether reporting 2.0 feature flag is set to true or not.
Manually check if v2 APIs are reachable
In addition to reviewing code here, reviewers **must** also review testing and request further testing in …
=> fix(be): v2 APIs availability should not depend on Reporting 2.0 FF

image/templates/helm/stackrox-secured-cluster/Chart.yaml.htpl
Kubernetes has a limit of 63 characters for labels (names and values).
When using dirty images, we're currently exceeding that length for secured clusters: e.g the `helm.sh/chart` label has values like `stackrox-secured-cluster-services-400.3.0-1194-ga7a64cdef9-dirty`, which has 64 characters.
This causes local deployments (i.e. `deploy/k8s/deploy-local.sh`) to fail when using dirty images. This PR implements a workaround, by replacing "dirty" with "d".
Executed the following commands successfully, on a dirty tag:
```
make image
deploy/k8s/deploy-local.sh
``` …
=> ROX-22612: fix local deployments

operator/bundle.Dockerfile, operator/bundle.Dockerfile.extra
This repeats the exercise of https://github.com/stackrox/stackrox/pull/8531, now moving to 4.12 as 4.11 went EOL on Feb 24th.
This is done as part of our [procedure](https://docs.engineering.redhat.com/display/StackRox/Add+support+for+new+OpenShift+version#AddsupportfornewOpenShiftversion-RemovesupportforOpenShiftversionwentEOL).
None of these are needed and so won't be done:
I will not test this in any particular way besides looking at CI. It should just work like https://github.com/stackrox/stackrox/pull/8531 did.
Note that `ocp-4-11-operator-e2e-tests` passed because the label, to my best belief, only influences where (in which indexes) the image gets released by the downstream tools. It apparently does not prevent the operator from …
=> chore: Move operator lower bound OCP version 4.11 -> 4.12

ui/apps/platform/src/services/AdministrationEventsService.ts
Fix administration events same as discovered clusters in https://github.com/stackrox/stackrox/pull/10090/files
My bad to make the original mistake, and then duplicate it!
Thanks to Stephan for seeing it and to Linda for fixing it.
1. Visit /main/administration-events on stagingdb
* See initial request with `pagination.limit=10&pagination.offset=0` in query string.
* Click right arrow and see request with `pagination.limit=10&pagination.offset=1` in query string (inconsistent and incorrect) for page address with `?page=2` in query string.
2. Visit /main/administration-events?page=2&perPage=1 in local deployment with code change.
* See the second event. Although impossible to set `perPage=1` through UI, this is page address query string consistent …
=> fix(ui): Fix pagination offset for administration events table

operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/manager/manager.yaml
This enables Scanner V4 images get cached for disconnected installs and also be overridden.
Found these are missing through this thread <https://redhat-external.slack.com/archives/C04UNQPLNAC/p1708979138937469>. Did a similar thing for central-db before - <https://github.com/stackrox/stackrox/pull/3643>. How do we not forget doing that in the future?
These aren't needed and won't be done:
This one is possible to test manually, but tedious. I will rely on the fact that env variables seem to be plugged in the operator code and that this may soon be tested by IBM colleagues in <https://redhat-external.slack.com/archives/C04UNQPLNAC/p1708979138937469>.
I will check that the downstrteam build injects the default image reference in these new …
=> feat: Add RELATED_IMAGE_ environment variables for Scanner V4 images

ui/apps/platform/scripts/cypress-component.sh, ui/apps/platform/scripts/cypress.sh
Two changes in component tests to help get these more stable/diagnose why they are failing ~20% of the time:
1. Changes `DEBUG=*` to `DEBUG=cypress:`. The former was logging all debug output from webpack, babel, etc. and creating an unusable amount of noise in the log file. Scoping to just cypress logs brings the file size from ~1GB to ~500**KB**
2. Adds a parameter to increase the timeout when a browser reconnect occurs, based on https://www.github.com/cypress-io/cypress/issues/27623. I'm not sure this is the issue, but I do get similar error messages to our CI failures when I set the timeout to a very low number and I can see ` Timed out waiting for the browser to connect. Retrying again... ` in the CI logs. If this has no impact, or a negative impact, we can revert later.
If any of …
=> fix(ui): Update debug log for component tests

.github/workflows/scanner-build.yaml, .github/workflows/scanner-e2e-test.yaml, scanner/Makefile, scanner/e2etests/helmchart/templates/db-deployment.yaml, scanner/e2etests/helmchart/templates/scanner-config.yaml, scanner/e2etests/helmchart/templates/scanner-deployment.yaml, scanner/e2etests/helmchart/values.yaml, scanner/e2etests/image_test.go, scanner/e2etests/testdata/image_tests.json
1. Update the E2E test description to match the expected results for Scanner V4 (diff from previous Scanner V2 results can still be inspected by `diff -du scanner/e2etests/testdata/*.json`).
2. Update `e2e` make rules to build and execute E2E tests in a cluster.
3. Create a GitHub workflow that runs the tests in a minikube instance after image builds are completed successfully.
4. Updated the E2E test cases not to fill in empty values to compare but to log when expected packages are not found.
5. Add a DEBUG flag to print the whole Matcher Vuln Report when the tests fail.
You will notice the images stored in registry.redhat.io are failing. The reason is credentials: We are missing a secret to registry.redhat.io. Other failures are legit. …
=> feat(scanner): Enable stand-alone E2E tests

image/templates/helm/shared/config-templates/scanner-v4/indexer-config.yaml.tpl, image/templates/helm/shared/config-templates/scanner-v4/matcher-config.yaml.tpl
Having trailing whitespace or lines consisting only of whitespace in a `ConfigMap` data results in the data being shown as a difficult to read string, when retrieving it using `kubectl`, e.g.:
```yaml
data:
config.yaml: "# Configuration file for Scanner v4 Matcher.\nstackrox_services: true\nindexer:\n  enable: false\nmatcher:\n  enable: true\n  database:\n    conn_string: >\n      host=scanner-v4-db.stackrox.svc\n      port=5432\n      sslrootcert=/run/secrets/stackrox.io/certs/ca.pem\n      user=postgres\n      sslmode=verify-full\n      \n      \n      \n      client_encoding=UTF8\n    password_file: /run/secrets/stackrox.io/secrets/password\n  indexer_addr: scanner-v4-indexer.stackrox.svc:8443\nlog_level: info\ngrpc_listen_addr: 0.0.0.0:8443\nhttp_listen_addr: 0.0.0.0:9443\nproxy:\n …
```
=> fix(scanv4): indexer/matcher config map pretty display

ui/apps/platform/cypress/integration/accessControl/accessControlAuthProviders.test.js, ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx, ui/apps/platform/src/Containers/AccessControl/AuthProviders/authProviders.utils.ts, ui/apps/platform/src/services/AuthService/AuthService.ts
Introduce claim mappings to auth provider UI. 
Since claim mappings are presented in the backend as `map[string]string`, re-ordering of elements is possible. To give customer some consistency, UI sorts claim mappings alphabetically by key. It also checks that any key used is unique.
=> ROX-22505: claim mappings UI

central/pod/datastore/datastore_impl_real_test.go, central/postgres/pruning.go, central/postgres/pruning_test.go, central/processindicator/datastore/datastore_impl.go, central/processlisteningonport/datastore/datastore.go, central/processlisteningonport/datastore/datastore_impl.go, central/processlisteningonport/datastore/datastore_impl_test.go, central/processlisteningonport/datastore/mocks/datastore.go, central/processlisteningonport/datastore/pruning.go, central/processlisteningonport/datastore/singleton.go, central/pruning/pruning.go, central/pruning/pruning_test.go, central/pruning/singleton.go
Currently there is a bug in which postgresql tries to run two queries that delete the same rows from the listening_endpoints table at the same time. One query tries to delete listening endpoints by pod. This query is run when a pod is deleted. The other query is a result of trying to update the listening endpoint when it is reported closed. An upsert is performed, but in the current implementation this involves doing a deletion. To fix this situation locks are added to  AddProcessListeningOnPort and RemovePlopsByPod, so that the deletes that they perform are not done at the same time.
~~- [ ] Documented user facing changes (create PR based on …
=> ROX-21575: Listening endpoints should not be deleted multiple times

ui/apps/platform/src/Containers/Clusters/InitBundles/SecureClusterUsingHelmChart.tsx
Thank you Kerry for identifying this inconsistency:
1. Docs (as source of truth) has `stackrox-secured-cluster-services` with `--create-namespace`
* https://docs.openshift.com/acs/4.3/installing/installing_other/install-secured-cluster-other.html
* https://docs.openshift.com/acs/4.3/installing/installing_ocp/install-secured-cluster-ocp.html#installing-secured-cluster-services-quickly_install-secured-cluster-ocp
2. Platform UI has `stackrox-secured-cluster-services` without `--create-namespace`
3. RedHatInsights UI (as indirect source, but with unknown provenance) has `rhacs-secured-cluster-services` without `--create-namespace`
https://github.com/RedHatInsights/acs-ui/blob/main/src/routes/GettingStartedPage/Wizard/InstallWithHelm.js#L50
Because successful installation during team test …
=> fix(ui): Make helm install in UI consistent with docs

scanner/mappers/mappers.go, scanner/mappers/mappers_test.go
1. Create a map of NVD vulns keyed by CVE name and map V4 report vulnerabilities to NVD vulnerabilities by name.
2. Apply different vulnerability name patterns based on the vuln updater name. In particular, if RHEL or AMZN are applied, they are only applied if such updates are found. Otherwise, the previous matching patterns are used.
Why: To fix the NVD enricher, which matches [in multiple fields in the vulnerability](https://github.com/stackrox/stackrox/blob/master/scanner/enricher/nvd/nvd.go#L398-L406), and the enrichment map may contain unrelated NVD vulns. Right now, we pick the first NVD vuln in the results. And we might pick the wrong vuln. Example:
Example of a description that would cause this:
```
end_pattern (called from internal_fnmatch) in the GNU C Library (aka glibcor …
```
=> fix(scanner): Fix vuln naming per updater + better NVD matching

pkg/printers/sarif_test.go
The SARIF test currently asserts on the output without the taking into account of the version.
Currently, the version is being replaced by a regex and expects it to start with either 3.X or 4.X. While this is expected, we do have some people running the release pipeline with different tags and it's easier to just replace with `version.GetMainVersion()` to make things more robust.
=> ROX-18561: fix flake during version replacement

pkg/printers/sarif.go, pkg/printers/sarif_test.go, pkg/printers/testdata/empty_sarif_report.json
We've received an issue where the SARIF report couldn't be generated in case no violations have been found during image / deployment check.
The reason is that the JSON path expressions we use with GJSON, particularily the `help` one, is returning a `-` as value. This is our "empty value" replacement string, which is needed to be returned for array values.
We didn't handle this properly during evaluating the JSON path expressions, so this is now being handled correctly.
_Note: this should be merged after #10148 since it also fixes the version replacement_
- see CI.
Manual test:
Run roxctl for a deployment which doesn't have violations and expect no errors being returned, just an empty SARIF report:
```bash
roxctl image check …
```
=> ROX-22760: fix SARIF printer for empty results

operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/manager/manager.yaml, operator/pkg/images/env.go
This follows up on https://github.com/stackrox/stackrox/pull/10128 in attempt to get successful downstream build with V4.
`RELATED_IMAGE_*` populated values are needed for users to be able to mirror containers for air-gapped/disconnected usage. They also provide means to override operand images used by the operator.
The way they are populated downstream is a bit convoluted and for the most part outside of our control. Here's what I can remember about it.
1. In the downstream build, all operands and operator are built before operator bundle.
2. Operator bundle build is triggered after that, and information about all containers built by the pipeline before that is passed in environment variables like `RHACS_SCANNER_V4_RHEL8_CONTAINER_BUILD_INFO_JSON`.
This goes by _container image_ actually …
=> fix: Unify RELATED_IMAGE_SCANNER_V4_* to just RELATED_IMAGE_SCANNER_V4

central/scannerdefinitions/handler/handler.go, central/scannerdefinitions/handler/handler_test.go
Validate offline bundle version in v4 mode
Add tests for mapping json download
1. Deploy
```
export OFFLINE_MODE=true
export ROX_SCANNER_V4=true
KUBECONFIG=/path/to/artifacts/kubeconfig deploy/k8s/deploy-local.sh
```
2. Check vuln data
```
unzip -l scanner-vuln-updates.zip
Archive:  scanner-vuln-updates.zip
Length      Date    Time    Name
---------  ---------- -----   ----
140154404  02-14-2024 11:41   scanner-defs.zip
248088  02-14-2024 11:41   k8s-istio.zip
144211510  02-14-2024 11:41   scanner-v4-defs-4.3.zip
---------                     -------
284614002                     3 files
```
3. Upload
`curl --insecure -u admin:[PWD] -F "file=@scanner-vuln-updates.zip" https://localhost:8000/api/extensions/scannerdefinitions -v`
4. Successful results
```
* * We are completely uploaded and …
```
=> fix(Scanner): validate updates bundle version in v4 mode

.github/workflows/unit-tests.yaml
Reverts stackrox/stackrox#9804
Due to 
- https://github.com/codecov/codecov-action/issues/1311
=> chore(deps): Revert bump codecov/codecov-action from 3 to 4

image/templates/helm/stackrox-central/internal/defaults.yaml.htpl, image/templates/helm/stackrox-secured-cluster/internal/defaults/70-scanner-v4.yaml.htpl, image/templates/helm/stackrox-secured-cluster/templates/sensor-netpol.yaml, pkg/helm/charts/tests/centralservices/testdata/helmtest/monitoring.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/monitoring.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/sensor-netpol.test.yaml
This enables traffic from Scanner V4 Indexer to Sensor when `localImageScanning` is enabled and adds tests for that.
This also adds tests for Scanner V4 monitoring.
CI
=> chore(scanner): update sensor netpol and test monitoring

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/ClustersCoverageTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/Components/CheckStatusModal.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ClusterSelection.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ProfileSelection.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/components/ComplianceClusterStatus.tsx, ui/apps/platform/src/services/ComplianceEnhancedService.ts
These are all improvements made thanks to the bug bash:
- Clusters coverage table:
- Can sort by cluster name 
- Correctly display the total count of clusters
- Check status modal:
- Add a "Close" button at the bottom of the modal
- Move the rationale to the description list below the header
- Cluster status
- Remove the padding from the button when the status is unhealthy to keep consistent with the healthy status indicator
- Cluster and Profile selection for scan config:
- Remove "at least one * is required" caption because it is redundant with the alert
---
=> chore(ui): Compliance v2 UX improvements

pkg/images/enricher/enricher_impl.go, pkg/signatures/public_key_verifier.go
This PR brings two improvements to the signature things:
- we streamlined the verified signature references now to not have the special case of `len(verifiedReferences==0)` and defaulting to the image name, but instead do it within the `getVerifiedImageReferences`.
- we also make sure to not have duplicated signatures being added to the image, this has been seen on one occurrence where an image has more than one signature with the same payload assigned.
- see CI.
=> chore(signatures): minor improvements to signatures

scanner/e2etests/testdata/image_tests.json, scanner/matcher/matcher.go
Because in ClairCore [Node.js is not part of the default matchers](https://github.com/quay/claircore/blob/71855026a39be574e338c9cbccc5170630189ec9/matchers/defaults/defaults.go#L46), so we need to register the Node.js matcher factory manually.
```
make e2e-run
```
=> fix(scanner): Enable Node.js matcher and update E2E cases

qa-tests-backend/src/test/groovy/SACTest.groovy
As [proposed](https://github.com/stackrox/stackrox/pull/10106#issuecomment-1966648185) use Image SHA to have all benefits of image caching and reduce possibility of a flake.
CI 
=> ROX-19953: use image SHA in SAC test

tests/networkflows_test.go
This PR aims to counter flakes in the nongroovy test `TestStackroxNetworkFlows`.
We introduced a retry for the initial check to give the cluster more time to spin up before we run the test.
It is …
=> ROX-22621: Introduce retry for flaky test

scanner/updater/manual/vulns.go
Add CVE-2022-29885 and CVE-2023-28708, as osv.dev does not track them as Maven vulns. See https://osv.dev/vulnerability/CVE-2022-29885 and https://osv.dev/vulnerability/CVE-2023-28708.
TODO
performed …
=> chore(scanner): add tomcat vulns

tests/compliance_operator_v2_test.go
We're noticing timeouts with the existing compliance e2e tests where the compliance scan doesn't finish within a five minute window.
While we're investigating why this is taking longer than normal, let's update the test to use a smaller profile the runs faster, especially since the ACS functionality doesn't depend on the contents of the profile.
The compliance e2e tests for v2.0 should pass. The contents of the profile are not part of the e2e assertions.
=> ROX-22610: Use smaller profiles for compliance e2e testing

scripts/ci/lib.sh
Adds a retry for the retag operation for scanner and collector images. This operation (retag) was missed in earlier PRs to retry quay.io actions e.g. #8844. (`hack [c]` from build failures [analysis](https://docs.google.com/spreadsheets/d/13gSYdmxLyUHl0CZgrN5ux-H7R3bgVCd9jT2C6-dbQqE/edit#gid=0))
=> fix(CI): retry retag operation

qa-tests-backend/src/test/groovy/SACTest.groovy
It looks like sensor does not have a presisten internet connection. Let's exclude `sensor -> INTERNET` connection from tests to keep them stable.
Refs:
- 49402f16a1c32f56cc1345f92b0ecef8ab992de5
CI
=> ROX-19782: Skip sensor -> INTERNET connection

.github/workflows/build.yaml, scripts/ci/lib.sh
The use of herestrings for logins with the `retry()` wrapper is problematic because <<< only provides the password for the first attemps. [e.g.](https://github.com/stackrox/stackrox/actions/runs/8070705260/job/22049086776) - the first failure is a timeout, subsequent attempts fail as the login gets no password.
=> fix(CI): provide password for docker login retries

qa-tests-backend/src/test/groovy/BuiltinPoliciesTest.groovy, qa-tests-backend/src/test/groovy/ImageManagementTest.groovy, qa-tests-backend/src/test/groovy/PaginationTest.groovy
All e2e tests that rely on the "No CPU request or memory limit specified" policy fail today. Disable until resolved.
No need
=> ROX-22846: Disable failing e2e tests for power and z architectures

qa-tests-backend/src/main/groovy/services/ExternalBackupService.groovy, qa-tests-backend/src/main/groovy/util/Env.groovy, qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
Add qa-e2e test for GCS external backups using both a service account key and a workload identity.
See tests.
=> ROX-21034: qa-e2e test for GCS backup integration

central/authprovider/datastore/datastore_impl.go, central/authprovider/datastore/datastore_impl_test.go
This PR adds validation of the authprovider to add / update within the datastore.
Previously this kind of validation was only done within the service layer. However, when using the datastore through different clients such as the declarative config approach, the validation was skipped before upserting and it was possible to add invalid auth providers to the database, rendering Central effectively unable to start up.
This change adds the basic validation to the datastore ensuring that no invalid entries may be added before upserting.
- see CI. …
=> ROX-22852: validate provider in datastore

image/rhel/Dockerfile
This PR removes the RPM binary from our main image.
RPM was originally introduced in the context of Node Scanning, as that code requires RPM to work.
We ended up moving the Node Scanning code to its own container, eliminating the need for RPM in the main image.
Our Downstream images already contain this change ([see here](https://gitlab.cee.redhat.com/stackrox/rhacs-midstream/-/blob/rhacs-4.3-rhel-8/distgit/containers/rhacs-main/Dockerfile.in?ref_type=heads#L79)).
Manual test by running any recent main version manually and running `rpm --version`.
This fails with `rpm: command not found` in the main image created by this PR. …
=> ROX-21016: Remove RPM binary from main image

go.mod, go.sum
This PR updates used gogoproto with fixed comments propagation for OneOf fields.
**Note:**
This PR should not change the code. In generated files, only comments can be added, but no actual functionality changes.
1. CI pipeline …
=> chore(proto): Bump gogoproto version with fixed comments propagation

.github/workflows/build.yaml
One source of build failures are errors fetching base images during docker builds. [1](https://github.com/stackrox/stackrox/actions/runs/8070705260/job/22049085260), [2](https://github.com/stackrox/stackrox/actions/runs/8070705260/job/22049087561). This PR increases the attempts to 6.
=> fix(CI): increase retries for builds

.openshift-ci/post_tests.py
For the compliance tests it will be helpful to gather the `openshift-compliance` namespace in order to see if there are. issues with the compliance operator when the tests are executed.
Snippet of files that were collected with the gather now that the `openshift-compliance` namespace was included.
```
./1764714308874276864-pull-ci-stackrox-stackrox-master-ocp-4-15-compliance-e …
```
=> ROX-18444:  add openshift-compliance to gather

scripts/ci/jobs/osd_aws_qa_e2e_tests.py, scripts/ci/jobs/osd_gcp_qa_e2e_tests.py, tests/e2e/lib.sh
~Currently sensor's memory limit is 500Mi when we deploy with the deploy scripts. This is causing sensor to OOM in some instances. Until we have a better way to debug these OOMs, let's bump sensor's memory limits to match operator installs (4Gi/8Gi).~
~Additionally,~ the OSD jobs were not being deployed via operator.
In addition to reviewing code here, reviewers **must** also …
=> fix(ci): Use Operator in the OSD jobs

central/complianceoperator/v2/profiles/datastore/datastore.go, central/complianceoperator/v2/profiles/datastore/datastore_impl.go, central/complianceoperator/v2/profiles/datastore/datastore_impl_test.go, central/complianceoperator/v2/profiles/datastore/mocks/datastore.go, central/complianceoperator/v2/pruner/pruner.go, central/complianceoperator/v2/pruner/singleton.go, central/complianceoperator/v2/rules/datastore/datastore.go, central/complianceoperator/v2/rules/datastore/datastore_impl.go, central/complianceoperator/v2/rules/datastore/datastore_impl_test.go, central/complianceoperator/v2/rules/datastore/mocks/datastore.go, central/complianceoperator/v2/scans/datastore/datastore.go, central/complianceoperator/v2/scans/datastore/datastore_impl.go, central/complianceoperator/v2/scans/datastore/datastore_impl_test.go, central/complianceoperator/v2/scans/datastore/mocks/datastore.go, central/complianceoperator/v2/scansettingbindings/datastore/datastore.go, central/complianceoperator/v2/scansettingbindings/datastore/datastore_impl.go, central/complianceoperator/v2/scansettingbindings/datastore/mocks/datastore.go, central/complianceoperator/v2/suites/datastore/datastore.go, central/complianceoperator/v2/suites/datastore/datastore_impl.go, central/complianceoperator/v2/suites/datastore/datastore_impl_test.go, central/complianceoperator/v2/suites/datastore/mocks/datastore.go
This pr deletes compliance v2 objects for a cluster when secured cluster is deleted from acs
This change is validated manually by deleting cluster from UI and validating related compliance objects are pruned from db
=> ROX-22466:  Prune compliance objects when cluster is deleted

qa-tests-backend/Makefile, qa-tests-backend/build.gradle, qa-tests-backend/src/main/groovy/services/DetectionService.groovy, qa-tests-backend/src/test/groovy/DeploymentCheck.groovy, tools/generate-helpers/bootstrap-migration/migration.go.tpl
Add E2E groovy tests for the new features in `roxctl deployment check` that were introduced in [ROX-20907](https://issues.redhat.com/browse/ROX-20907).
Namely, the tests assert on the addition of correct remarks. 
Remarks consist of the following information per deployment:
- Permission level
- Applied Network Policies
Running groovy tests on CI and manually against OS4 cluster
=> ROX-21656: roxctl deployment check E2E tests

qa-tests-backend/src/test/groovy/CloudSourcesTest.groovy
In https://issues.redhat.com/browse/ROX-22848 we observed a case where 10 * 10s retries were not sufficient to populate the discovered clusters.
CI
=> ROX-22848: increase cloud source wait time

pkg/renderer/images_test.go, pkg/renderer/kubernetes_helm_test.go, pkg/renderer/kubernetes_test.go, pkg/renderer/render_test.go
The pkg/renderer tests had not been Scanner V4 aware. So this is including Scanner V4 and Scanner V4 DB images into those tests.
Running automated tests.
=> test(scanv4): Make renderer tests Scanner V4 aware

qa-tests-backend/src/main/groovy/util/Env.groovy, qa-tests-backend/src/test/groovy/IntegrationsTest.groovy
When the location is loaded from environment secrets, it causes strings to be obfuscated. In the worst case, `location: us`, every word with `us` in it will be starred like so: `ref**ed`. That is annoying and unnecessary, therefore we simply hard code the bucket location.
CI
=> fix: hard code bucket location

scripts/ci/lib.sh
For example if scanner-db image build fails (like it's [happening to be](https://github.com/stackrox/stackrox/pull/10254) right now) then the test starts and then fails mid-way, and it takes a bit of digging to find the cause.
CI is enough.
Works as intended:
```
[...]
INFO: Wed Mar  6 09:34:20 UTC 2024: Checking for scanner-v4 using https://quay.io/api/v1/repository/rhacs-eng/scanner-v4/tag?specificTag=4.4.x-64-g9c19e44585
{"tags": [], "page": 1, "has_additional": false}
INFO: Wed Mar  6 09:34:20 UTC 2024: scanner-v4 does not exist
ERROR: Timed out waiting for images after 3600 seconds
``` …
=> chore(tests): poll for more images before operator e2e

.github/workflows/scanner-build.yaml
S390x scanner-db builds (They are built differently from the other architectures) are broken:
```
#12 88.14 Error: Unable to find a match: postgresql postgresql-private-libs postgresql-server postgresql-contrib
```
This prevents the image manifest push from running, in turn breaking many e2e tests for *all* architectures.
Let's drop this build until it is fixed by its maintainers, in order to allow all other architectures to build and e2e-test successfully. cc @RTann @kcrane 
CI is enough.
=> fix(build): drop broken s390x scanner builds for now

roxctl/patch_flag_usage.go, tests/roxctl/bats-tests/local/central-boolean-defaults.bats
Notice the default value hints in the end of the help message:
```console
michael@work$ roxctl
...
--plaintext                  Use a plaintext (unencrypted) connection; only works in conjunction with --insecure. Alternatively can be enabled by setting the ROX_PLAINTEXT environment variable to true (default false) (default false)
...
```
After the change:
```console
$ roxctl
...
--plaintext                  Use a plaintext (unencrypted) connection; only works in conjunction with --insecure. Alternatively can be enabled by setting the ROX_PLAINTEXT environment variable to true (default false)
...
```
performed one does not …
=> ROX-22613: Duplicated hint with default value for boolean flags

ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx, ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPoliciesYAML.tsx, ui/apps/platform/src/Containers/NetworkGraph/simulation/NetworkPolicySimulatorSidePanel.tsx, ui/apps/platform/src/Containers/NetworkGraph/simulation/SimulateNetworkPolicyButton.tsx, ui/apps/platform/src/Containers/NetworkGraph/utils/networkGraphURLUtils.test.ts, ui/apps/platform/src/Containers/NetworkGraph/utils/networkGraphURLUtils.ts, ui/apps/platform/src/hooks/useAnalytics.ts
This PR adds "event" analytics calls to certain button clicks to handle requirements 1, 2, and 4 of the epic:
>1) I want to be able to see how many users use the "Network policy generator" on a cluster level, generate NW policies for the entire cluster and download the Network policies configuration (see pictures). 
>I want to see how many unique users are using the functionality but also the recursive users (this means, users that use the functionality several times). 
> 2) I want to be able to see how many users use the "Network policy generator" on a given scope (that is, they fill cluster + namespace, or cluster+namespace+deployment), generate NW policies for the entire cluster and download the Network policies configuration (see pictures)
> I want to see how many unique users are …
=> ROX-22471: Add analtyics for specific button clicks in Network Graph

ui/apps/platform/cypress/integration/vulnerabilities/exceptionManagement/cancelRequestFlow.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/hooks/getTableUIState.ts, ui/apps/platform/src/utils/getTableUIState.test.ts, ui/apps/platform/src/utils/getTableUIState.ts
This PR adds empty states for the Exception Management tables (Pending requests, Approved deferrals, Approved false positives, and Denied requests). I added a new function that takes certain values and returns a page state value that we can use to determine what happens on the page (loading, showing an error, showing the table data, etc.). This is based on the work in [this Design Doc](https://docs.google.com/document/d/1biNKn8QWvlWVHE2lO8lGFvmJ-moJbuvm2mWT3akQZgw/edit#heading=h.6lix4so2w8p1).
=> ROX-20884: Empty states for Exception Management

ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ObservedCVEs/ObservedCVEs.tsx, ui/apps/platform/src/Containers/VulnMgmt/RiskAcceptance/ObservedCVEs/ObservedCVEsTable.tsx
In VM 1.0, at some point, we specified the wrong API sort field name for the column labeled "Discovered" in the Observed CVEs table of Image Findings. (In main CVE tables, it uses the "CVE Created Time" sort field for the Discovered column.)
This small change causes clicking on the table header to use the correct API sort field name.
I verified that, after this change, the correct sort field was being passed in the API call, and the correctly sorted data was now coming back.
Before
After
=> ROX-21948: Fix sorting Discovered Time on Observed CVEs table

pkg/registries/quay/quay.go
A 4 year old nil panic. If `err == nil`, we cannot assume that `resp != nil`. See https://redhat-internal.slack.com/archives/CELUQKESC/p1709683503070829.
It is also acceptable to skip testing for …
=> fix: quay test panic

.github/workflows/ci-failures-report.yml, scripts/ci/metrics.sh
- show % of failures rather than their count: this is more meaningful without prior knowledge (100% failure rate invokes a :fire: reaction, while `<some number>` is like meh 😐 because of lack of context)
- however still order results by the absolute number of failures, because some failures (suspicious log checks, some `initializationErrors` in groovy, and some `before each` clauses in UI tests) are never reported as passing, and therefore computed to be 100% failing. I did some research into what would be necessary to properly compute their error rates (it's complicated), and I don't think it's worth the effort.
- fix channel name in workflow_dispatch description
- change rendering to include the "fields" feature which provides _some_ column-like formatting (unfortunately only up to two …
=> docs(tests): show failure frequency and other fixes

tests/external_backup_test.go
Move the golang backup test to the new `acs-san-stackroxci` project as part of the `stackrox.com -> redhat.com` GCP migration.
CI
=> ROX-22847: use V2 bucket in golang backup test

.github/workflows/batch-load-test-metrics.yml, scripts/ci/lib.sh, scripts/ci/metrics.sh
Test metrics were not always saved to BigQuery due to quota limits [e.g.](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-master-merge-gke-qa-e2e-tests/1763256628238356480). These limits cannot be raised. The remedy is to batch load.  https://cloud.google.com/bigquery/docs/troubleshoot-quotas#ts-table-import-quota
=> fix(CI): batch load test metrics

.github/workflows/build.yaml, govulncheck-allowlist.json
Ignore vulns which can only be fixed via a minor version bump. We will do that at a later time.
These vulns were all evaluated to only be at a Medium/Moderate severity, so we are ok with waiting.
I didn't
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand …
=> chore(vulncheck): ignore vulns until we can bump Go version

qa-tests-backend/src/main/groovy/common/Constants.groovy, qa-tests-backend/src/test/groovy/BaseSpecification.groovy, qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy, qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy, qa-tests-backend/src/test/groovy/IntegrationsSplunkViolationsTest.groovy, qa-tests-backend/src/test/groovy/IntegrationsTest.groovy, qa-tests-backend/src/test/groovy/NetworkBaselineTest.groovy, qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy, qa-tests-backend/src/test/groovy/ProcessBaselinesTest.groovy, qa-tests-backend/src/test/groovy/Services.groovy
I've seen an image taking 4m to download on one node and 7s on another. This PR drastically increases the overall wait timeout for deployments to come online.
As per @gavin-stackrox 's suggestion, it also bumps `globalTimeout` proportionally and removes all overrides for it to consolidate and simplify.
CI run
=> ROX-22699: Increase the wait time for deployments

tests/e2e/lib.sh, tests/e2e/run.sh, tests/upgrade/legacy_to_postgres_run.sh, tests/upgrade/lib.sh, tests/upgrade/postgres_run.sh
Update the database snapshot used for most tests to be based off 4.1.  4.1 was chosen because the upgrade test goes through a backward compatibility test and 4.1 is where we introduced that requirement for the data.  
There remains a specific test test `legacy_to_postgres` that still uses the 3.56 snapshot.  This is because the purpose of that test is solely to test going from RocksDB to Postgres.  That test will be removed with ROX-22872 as will the rest of the references to the 3.56 snapshot.  Once that is complete we should be able to begin the rest of the RocksDB removal beginning with the migrations. 
Note:  I could have probably made some of these changes more elegant but it didn't seem worth it since some of these things are going to be removed entirely anyway.
~- [ ] Unit test and …
=> ROX-20125: new base snapshot

sensor/kubernetes/eventpipeline/resolver/resolver_bench_test.go
This PR adds a benchmark to the process of deployment references.
```bash
go test -bench=. -timeout 1h -count 5 -run=^# github.com/stackrox/rox/sensor/kubernetes/eventpipeline/resolver -test.bench BenchmarkProcessDeploymentReferences -benchtime=30s -benchmem
``` …
=> ROX-17931: Benchmark process deployment references in the resolver

scripts/ci/metrics.sh
This is a followup to #9828 where I insufficiently tested the happy case (I had only looked at UI output which was empty, but in fact the raw JSON is an _empty list_).
```
$ bq --project_id acs-san-stackroxci --quiet --format=json query --use_legacy_sql=false "select 1 from ci_metrics.stackrox_tests__extended_view where false" > a
$ if [[ $(cat a) = "[]" ]]; then echo yes;else echo nope;fi
yes
$
```
Also ran the workflow manually and checked the result [here](https://redhat-internal.slack.com/archives/C068WMY4SEQ/p1710148369326869).
performed one does not seem sufficient. As a reviewer, you must not approve the change until …
=> fix(CI): properly recognize the no results case

qa-tests-backend/README.md, qa-tests-backend/src/main/groovy/objects/ImageIntegration.groovy, qa-tests-backend/src/main/groovy/util/Env.groovy, qa-tests-backend/src/test/groovy/AdmissionControllerNoImageScanTest.groovy, qa-tests-backend/src/test/groovy/BaseSpecification.groovy, qa-tests-backend/src/test/groovy/BuiltinPoliciesTest.groovy, qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy, qa-tests-backend/src/test/groovy/ImageScanningTest.groovy, qa-tests-backend/src/test/groovy/IntegrationsTest.groovy, qa-tests-backend/src/test/groovy/LocalQaPropsTest.groovy, qa-tests-backend/src/test/groovy/PolicyFieldsTest.groovy, qa-tests-backend/test-images/fail-compliance/ssh/Makefile, qa-tests-backend/test-images/trigger-policy-violations/alpine/Makefile, qa-tests-backend/test-images/trigger-policy-violations/more/Makefile, qa-tests-backend/test-images/trigger-policy-violations/most/Makefile, scripts/ci/clair/clair-kubernetes.yaml, scripts/ci/clairv4/Dockerfile, scripts/ci/clairv4/clairv4-kubernetes.yaml, scripts/ci/openshift-gcr-secrets.sh
Migrate the GCR test images from `stackrox-ci` to `acs-san-stackroxci`. Needs additional container analysis roles from https://github.com/stackrox/automation-iac/pull/73.
QA tests are passing.
=> ROX-20038: migrate GCR qa test images

central/vulnerabilityrequest/datastore/datastore_impl.go, central/vulnerabilityrequest/datastore/datastore_impl_test.go
When an update requests to a VM 2.0 exception request is approved, the desired updates must be applied to the original request.
performed one does not seem sufficient. As a reviewer, you …
=> ROX-22411: Apply exception updates to original req on approval

qa-tests-backend/scripts/migrate_protos.sh
As we removed gogoproto from proto files we don't need to remove gogo references in qa proto migration step.
This PR simplifies migration code by just copying protos. 
`make style` is enough as for qa it generates java classes from protos.
=> chore: cleanup qa protos migration script

operator/bundle/manifests/rhacs-operator.clusterserviceversion.yaml, operator/config/manifests/bases/rhacs-operator.clusterserviceversion.yaml
These are needed because CVP tests fail without these labels.
Example: http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/rhacs-operator-bundle-container-4.4.0-9/57bac96c-1a9a-45b9-aad9-af94adcef146/operator-infrastructure-feature-bundle-image-output.txt
Documentation https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs
Context threads:
- https://redhat-internal.slack.com/archives/C06K8MT821Y/p1710150581879999
- https://redhat-internal.slack.com/archives/C02HTD51SMD/p1693403960061209
None of the following will be done.
- ~~[ ] Evaluated and added CHANGELOG entry if required~~ - I don't think it's worth documenting since we had former …
=> ROX-19523: Set `features.operators.openshift.io` annotations

qa-tests-backend/src/test/groovy/CSVTest.groovy, qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
Skipping known failed tests for CSVTest and NetworkFlowTest. Will be reenanble once test case error is resolved
ROX-21491
ROX-16337
relying on CI
=> fix(qa): Skip known failures on PZ 

ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/Wizard/ProfileSelection.tsx
Selecting all profiles will likely always results in a configuration error, so removing that feature would be wise.
=> chore(ui): Remove compliance scan config profile's select all option

ui/apps/platform/cypress/integration/policies/policiesTable.test.js, ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.tsx, ui/apps/platform/src/Containers/Policies/Table/PoliciesTable.utils.ts, ui/apps/platform/src/Containers/Policies/Table/PoliciesTablePage.tsx
This PR refactors the client-side sorting on the Policies table, by moving it up from the `PoliciesTable.tsx` component file, up to its parent `PoliciesTablePage.tsx` component. This is done to prevent the layout shift that occurs when the table was being rendered with an empty array, and then fed an unsorted API response, and then immediately re-rendered with the sorted list, which was sorted in a useEffect block. The initial render did not have wide empty header for the turndown triangle column--PatternFly did not render that header if there were no rows--and the subsequent layout shift was causing frequent "element is animating" failures in CI.
I decided move the sorting up into the promise-resolved block for the `/policies` API call in the parent, because that API call gets refreshed …
=> ROX-20291: Move FE sorting of Policies table to avoid re-render

.github/CODEOWNERS
Let's add codeowners for netpoll part of roxctl.
=> chore: set owners for roxctl netpol

central/scannerdefinitions/handler/handler.go, pkg/errox/utils.go, pkg/postgres/pgutils/error.go
As we prepare to remove `pkg/errorhelpers` (see https://github.com/stackrox/stackrox/pull/10099), move error utils to the new home under `errox`.
Build success is sufficient. …
=> refactor: Move errorhelpers/utils under errox

.github/contributing.md
Made a few changes to our contributing guide to reconcile it with the current state of affairs. Examples of what have changes:
* timezone remarks are removed 
* semantic PR titles suggested
* links updated 
The style of the document has been updated for readability as well.
None: not a functional change. Rendered md file can …
=> chore: Rework contributing.md

tests/e2e/run-scanner-v4.bats
Subject says it all.
Goal of this change is that in case running into the 4h runtime timeout for the test pod, bats will hopefully mark the running test as failed and we will get logs.
It is also …
=> tests(scanv4): Set timeout for Scanner V4 install tests

.editorconfig
After #9130, all protobuf files are formatted with 2 spaces for indentation. This is different to the configuration provided in .editorconfig and causes editors that use this file to use 4 spaces instead. Easy fix is to set the indentation to 2 spaces in editorconfig so everything stays consistent.
Opened a protobuf file with the .proto extension on NeoVim and indentation was properly configured.
=> fix(editorconfig): protobuf configuration matches buf format

tools/deserialize-proto/README.md, tools/deserialize-proto/init.go, tools/deserialize-proto/main.go
We sometimes find ourselves needing to read serialized protobuf objects from the central database, particular when debugging CI issues.
These changes introduce a tool to deserialize such objects by reading the serialized object from stdin and using a user-provided storage type.
- ~~Investigated and inspected CI test results~~
- ~~Unit test and regression tests added~~
- ~~Evaluated and added CHANGELOG entry if required~~
- ~~Determined and documented upgrade steps~~
- ~~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~
Checklist doesn't apply since this is an internal tool meant only for developers.
I had loaded a postgres …
=> chore: add internal deserialize proto tool

ui/apps/platform/src/Containers/MainPage/AuthenticatedRoutes.tsx
Based on a customer bug report, I investigated why the query string portion of a link was being dropped if a user visited the link, was not already logged in, and was redirected to the login page before then getting to the followed link.
What I thought might involve significant refactoring or a change to routing dependencies, turned out to be much simpler: where we were manually saving the original link before the redirect to the login page, we had only bothered to save the URL path part **before** the query string `?...`.
(This code dates back 6 years, when almost all of each page's internal state was being held in redux or memory, and not reflected in the URL.)
This PR simply saves both the path AND the query string before redirect.
Before this change
1. Log out
2. Follow this link, …
=> ROX-23118: Include query string in login redirect URL

pkg/registries/google/google_integration_test.go, pkg/registries/google/google_test.go, pkg/scanners/google/google_integration_test.go
Migrates the GCR images from the deprecated `ultra-current-825` GCP project to `acs-san-stackroxci`, which is part of the redhat.com GCP organization. A service account with suitable permissions is `stackrox-ci-qa-gcr-tests@acs-san-stackroxci.iam.gserviceaccount.com`.
Note that these tests are currently skipped in our CI pipeline. We should reevaluate the need for the tests and either re-enable them or delete them. That is outside the scope of this PR however.
`gotest -v ./... -tags=integration`
performed testing …
=> ROX-20036: migrate google scanner integration test images

operator/main.go, operator/pkg/central/extensions/common.go, operator/pkg/central/extensions/common_test.go, operator/pkg/central/extensions/reconcile_admin_password.go, operator/pkg/central/extensions/reconcile_central_db_password.go, operator/pkg/central/extensions/reconcile_pvc.go, operator/pkg/central/extensions/reconcile_scanner_db_password.go, operator/pkg/central/extensions/reconcile_scanner_v4_db_password.go, operator/pkg/central/extensions/reconcile_tls.go, operator/pkg/central/extensions/reconcile_tls_test.go, operator/pkg/central/reconciler/reconciler.go, operator/pkg/common/extensions/reconcile_scanner_db_password.go, operator/pkg/common/extensions/reconcile_scanner_v4_db_password.go, operator/pkg/common/extensions/secret_reconciliator.go, operator/pkg/common/extensions/secret_reconciliator_test.go, operator/pkg/common/labels/labels.go, operator/pkg/legacy/secrets.go, operator/pkg/proxy/extension.go, operator/pkg/reconciler/reconciler_factory.go, operator/pkg/securedcluster/extensions/cluster_name.go, operator/pkg/securedcluster/extensions/common.go, operator/pkg/securedcluster/extensions/reconcile_scanner_db_password.go, operator/pkg/securedcluster/extensions/reconcile_scanner_v4_db_password.go, operator/pkg/securedcluster/reconciler/reconciler.go, operator/pkg/securedcluster/values/translation/translation.go, operator/pkg/securedcluster/values/translation/translation_test.go, operator/pkg/utils/api.go, operator/pkg/values/translation/translation.go
The operator consumes a lot of memory, especially in large Kubernetes clusters. There have been several customer issues where this led to OOMKilled errors, see ROX-18969 for linked tickets. Heap profiles show that all cases are related to the operator caching objects in all namespaces, especially secrets. 
This is because we don't limit the cache by namespace, label or field selectors. In all of the customer cases we had so far, caching of secrets seems to cause the majority of memory consumption. In this PR I've added a label selector to the controller-runtime cache and modified the operator code to label all created secrets accordingly.
Also some parts where we access secrets not owned by the operator had to be adjusted to use a non-cached client, because we can't control that labels …
=> ROX-18969: add label selector to operator cache

sensor/debugger/k8s/fake.go, sensor/debugger/k8s/k8sclient.go
Enhance local-sensor `clientset` to also include openshift and the dynamic clients.
performed …
=> feat(enhancement): Enhance local-sensor clientset with ocp clients

central/vulnerabilityrequest/datastore/internal/store/postgres/store.go, central/vulnerabilityrequest/manager/requestmgr/manager_impl.go, central/vulnerabilityrequest/manager/requestmgr/manager_impl_create_req_test.go, central/vulnerabilityrequest/utils/util.go, generated/storage/vuln_requests.pb.go, pkg/postgres/schema/vulnerability_requests.go, pkg/search/options.go, proto/storage/vuln_requests.proto
A race condition in approval workflow allowed creating multiple vuln requests with same CVEs and scope. Below is an example flow that allowed to create multiple approved vuln requests with same CVEs and scope:
1) Create deferral req v1 : cves: cve1, scope: global
2) Create deferral req v2 : cves: cve2, scope: global
3) Approve req v1
4) Approve req v2
5) Update req v1 : Remove cve1 and add cve3 : status becomes APPROVED_PENDING_UPDATE
6) Update req v2 : Remove cve2 and add cve3 : status becomes APPROVED_PENDING_UPDATE
7) Approve updated req v1
8) Approve updated req v2
9) Now we have two vuln requests with same CVEs and scope
This PR fixes the race condition by automatically denying any pending update request with same CVEs and scope as the request being approved. The vuln request proto …
=> ROX-22868: Fix race condition allowing multiple vuln reqs with same CVEs

pkg/protocompat/time.go, pkg/protocompat/time_test.go, pkg/protoconv/time.go
Add conversion functions to convert between go time and proto timestamp. …
=> ROX-22101: New conversion functions in proto compatibility layer

tests/backup_test.go, tests/common_test.go, tests/excluded_scopes_test.go
This PR fixes the flaky test.
It does the following changes:
1. **Decoupling of tests:** Currently, failure of cleanup for `BackupTest` will cause the failure of `TestExcludedScopes`. We are decoupling them by using different deployment names, and on top of that, we are using random names per run, so even multiple cleanup failures will not impact the actual test.
2. **Make cleanup optional:** We should not test if `kubectl` works properly. Changed that test does not fail on timed out cleanup. …
=> ROX-22207: Isolate test

scanner/Makefile, scanner/image/db/Dockerfile, scanner/image/scanner/Dockerfile
Add expiry label to non-release builds, so we do not continue to blow up the quay registry. See https://github.com/stackrox/scanner/pull/1446 for Scanner v2
CI …
=> chore(scanner): add quay tag expiry label to images

ui/apps/platform/src/Containers/Clusters/ClustersTablePanel.tsx
Changes a rogue tertiary button to secondary to match others in the same UI section. This is a holdover from when there were two buttons (one secondary one tertiary) but seems out of place now that there are four.
Before:
After:
=> chore(ui): Swap button style from tertiary to secondary

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/WorkloadCves.helpers.js, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WorkloadCvesPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/DefaultFilterModal.tsx, ui/apps/platform/src/routePaths.ts
- Renders the "Namespace overview" button in the top right section of the page
- Relocates the "Default filters" button
- Clicking on the button should take you to a new page
- The page should include breadcrumbs that navigate back to Workload CVEs
- The page should include a page header and subtitle
=> ROX-22734: Add a namespace overview page

pkg/postgres/pgutils/utils.go, pkg/protocompat/time.go
The goal is to remove direct calls to the gogo protobuf layer and have all of them happen through an abstraction layer in order to ease the migration to a new protobuf library.
This PR moves the timestamp conversion logic from the `pgutils` package to the `protocompat` one.
It is acceptable to skip testing in …
=> ROX-22101: move pgutils.NilOrTime logic to protocompat

go.mod, go.sum
This PR creates a new `replace` section in `go.mod` and keep all replaces that are owned by @stackrox/merlin
CI
=> chore(go.mod): extract replaces owned by 🧙

sensor/debugger/certs/cert_fetcher.go, sensor/tests/connection/runtime/runtime_test.go, sensor/tests/helper/helper.go, tools/local-sensor/main.go
Retrieve sensor's certificates and configuration from go code.
=> ROX-22769: fetch sensor's certificates in go code

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCvesPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/utils/searchUtils.ts, ui/apps/platform/src/Containers/Vulnerabilities/types.ts
Adds routing and a page component for the Node CVE single page.
Directly visit a URL ending in `vulnerabilities/node-cves/cves/<cve_id>`:
Click the breadcrumb link and verify it navigates back to the Node CVE overview page:
=> ROX-23036: Add route and page component for NodeCVEs - CVE Single page

deploy/common/deploy.sh
I could not find any references to the removed functions anywhere in the stackrox org.
- https://github.com/search?q=org%3Astackrox%20get_identity&type=code
- https://github.com/search?q=org%3Astackrox+get_authority&type=code
- https://github.com/search?q=org%3Astackrox+get_central_feature_flag_enabled&type=code
- https://github.com/search?q=org%3Astackrox+setup_license&type=code
Background: cleaning up uses of curl_central before trying to make it more robust (ROX-12746).
=> chore: Drop some dead code.

Makefile, ui/apps/platform/src/Containers/MainPage/Header/CLIDownloadMenu.tsx, ui/apps/platform/src/Containers/Policies/Wizard/Step2/DownloadCLIDropdown.tsx
Add options in Central's UI to download ARM binaries for Darwin and Linux.
I became interested in the ARM builds as preparation for our new roxctl GitHub action, which might use ARM binaries. I noticed that we already build ARM binaries in the Makefile but don't expose them. I don't see a reason to not make them available in Central given the increasing popularity of ARM chips.
Downloaded the ARM binaries from the UI.
=> ROX-23081: add roxctl ARM binary download

scripts/ci/gke.sh, scripts/ci/lib.sh
The cluster versions and GKE logs explorer panels are of less utility nowadays. Keep them in artifacts but hide them from the prow UI.
=> chore(CI): hide unnecessary panels

scripts/ci/roxctl-publish/prepare.sh
Publish roxctl ARM binaries to https://mirror.openshift.com.
Ran `make cli-build` and `prepare.sh` locally and verified that the binaries were copied.
=> ROX-23081: publish roxctl ARM binary

.github/workflows/build.yaml, govulncheck-allowlist.json
Extend the vuln ignore until go1.21 lands #10305. Also run the job on PRs if `scan-go-binaries` label is present.
=> chore(GO): extend vuln ingore

ui/apps/platform/src/Containers/Vulnerabilities/components/EntityTypeToggleGroup.tsx, ui/apps/platform/src/hooks/useURLSort.ts
Fixes two issues introduced by a recent refactoring, discovered by @pedrottimark (TY!).
1. Missing React `key` prop for an array of children
2. `useEffect` render loop due to referential change of identical sort parameters
Instead of extracting the sort parameters as constants again, I opted to update the useURLSort() hook itself to use a deep comparison effect since this issue has popped up a handful of times and behaviorally this is what we intend. If the incoming sort fields are an identical string array each time, there is no need to constantly rebuild the hook's local state. This makes checking for infinite render loops no longer the responsibility of the caller.
It would be nice if we could catch these types of errors more easily before merges to master. I see there is a disabled …
=> fix(ui): Fix rendering performance issues in Workload CVEs

central/declarativeconfig/updater/notifier_updater.go, central/notifier/datastore/datastore_impl.go, central/notifier/datastore/datastsore_test.go, central/notifiers/validation/validate.go, central/reports/config/datastore/datastore_impl_v2_test.go, central/reports/config/service/config_separation_test.go, central/reports/service/v2/config_separation_test.go, central/reports/snapshot/datastore/datastore_impl_test.go
The validation of different notifier types is encoded within the creator function of each notifier type, not within the notifiers datastore.
Hence, we should attempt to create the notifier beforehand (note that this does not persist the notifier in any form) before upserting the notifier within the datastore as well as within the processor.
=> fix(declarative-config): validate notifiers before upserting

ui/apps/platform/src/Containers/AccessControl/AccessScopes/EffectiveAccessScopeTable.tsx
As titled. See more information in https://www.github.com/patternfly/patternfly-react/issues/10185
If needed, we can add this to the patch release milestones for supported ACS versions.
Override the response of `computeeffectiveaccessscope` when visiting an individual access scope or attempting to create an access scope, and ensure the response has an empty string for a cluster or namespace name. Instead of a runtime error, the cluster/namespace should show up in the "Allowed resources" section as a single dash `-`.
=> fix(ui): Add workaround for bug in access scopes to avoid crash

central/networkgraph/flow/datastore/flow.go, central/networkgraph/flow/datastore/flow_impl.go, central/networkgraph/flow/datastore/internal/store/flow.go, central/networkgraph/flow/datastore/internal/store/mocks/flow.go, central/networkgraph/flow/datastore/internal/store/postgres/store.go, central/networkgraph/flow/datastore/internal/store/postgres/store_test.go, central/networkgraph/flow/datastore/internal/store/testcommon/flow.go, central/networkgraph/flow/datastore/mocks/flow.go, central/networkgraph/service/service_impl.go, central/networkgraph/service/service_impl_test.go, central/networkpolicies/generator/generator_impl.go, central/networkpolicies/generator/generator_impl_test.go, central/sensor/service/pipeline/networkflowupdate/flow_store_updater.go, central/sensor/service/pipeline/networkflowupdate/flow_store_updater_impl.go, central/sensor/service/pipeline/networkflowupdate/flow_store_updater_impl_test.go, central/sensor/service/pipeline/networkflowupdate/pipeline.go
The goal is to remove direct calls to the gogo protobuf library and have all of them happen through an abstraction layer in order to ease the migration to a new protobuf library.
The current PR aims at changing the functions around network graph management in central to use time rather than gogo timestamps as parameters or return values.
It is acceptable to assume trust and keep this section light, …
=> ROX-22101: Remove gogo protobuf imports from central NetworkGraph

central/cve/cluster/datastore/datastore.go, central/cve/cluster/datastore/datastore_impl.go, central/cve/cluster/datastore/datastore_impl_test.go, central/cve/cluster/datastore/mocks/datastore.go, central/cve/cluster/datastore/store/postgres/full_store.go, central/cve/cluster/datastoretest/datastore_sac_test.go, central/cve/cluster/service/service_impl.go, central/cve/common/types.go, central/cve/common/utils.go, central/cve/fetcher/manager_impl_postgres_test.go, central/cve/image/datastore/datastore.go, central/cve/image/datastore/datastore_impl.go, central/cve/image/datastore/datastore_impl_test.go, central/cve/image/datastore/mocks/datastore.go, central/cve/image/service/service_impl.go, central/cve/node/datastore/datastore.go, central/cve/node/datastore/datastore_impl.go, central/cve/node/datastore/datastore_impl_test.go, central/cve/node/datastore/mocks/datastore.go, central/cve/node/service/service_impl.go, central/image/datastore/store/postgres/store.go, central/node/datastore/store/postgres/store.go, central/vulnerabilityrequest/manager/requestmgr/manager_impl.go, central/vulnerabilityrequest/manager/requestmgr/manager_impl_reobserve_test.go, central/vulnerabilityrequest/manager/requestmgr/manager_impl_test.go
The goal is to remove direct calls to the gogo protobuf library and have all of them happen through an abstraction layer in order to ease the migration to a new protobuf library.
The current PR aims at changing the functions around vulnerability management in central and migrator to use time rather than gogo timestamps as parameters or return values.
It is acceptable to assume trust and keep this …
=> ROX-22101: remove gogo protobuf from vulnerability management

image/roxctl/konflux.Dockerfile, operator/konflux.Dockerfile
This follows up on https://github.com/stackrox/stackrox/pull/10305 otherwise `roxctl` and `operator` builds fail like [here](https://console.redhat.com/preview/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/roxctl-on-pull-request-gzftv).
I'd love to make a check around `EXPECTED_GO_VERSION` but it's not clear what the value should be (see [this thread](https://redhat-internal.slack.com/archives/CELUQKESC/p1711456341751489)).
Will only check Konflux CI.
=> fix: Switch Konflux golang builder from 1.20 to 1.21

ui/apps/platform/src/Components/PatternFly/SeverityIcons.tsx, ui/apps/platform/src/Containers/Collections/CollectionForm.tsx, ui/apps/platform/src/Containers/Collections/RuleSelector/ByLabelSelector.tsx, ui/apps/platform/src/Containers/Collections/RuleSelector/ByNameSelector.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/DeploymentSelector.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/NamespaceSelector.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesForm.tsx, ui/apps/platform/src/css/trumps.css
1. [A change in where the global default font-family is applied results in our Tailwind font-family overriding the Red Hat font.](https://github.com/stackrox/stackrox/pull/10505/commits/aaa98443656e0c443c201048bcf4b1bf80194557)
2. A global checkbox size override relied on CSS vars that are no longer valid (at least at the scope we were using them from). [Removing the rules entirely fixes the issue.](https://github.com/stackrox/stackrox/pull/10505/commits/58cb0baa6fef849f7fc3e5327b9af8883af03b16)
3. [The color prop passed to Icon components previously was set](https://github.com/stackrox/stackrox/pull/10505/commits/5ca155fe1bbbd93c8ff70e59ef9da793c852fe44) as the svg's `fill` attribute. Now, that attribute has a value of `currentColor` and a wrapper element with the style: `color: …
=> fix(ui): pf5 visual glitches

ui/apps/platform/src/Components/PatternFly/TechPreviewLabel.tsx, ui/apps/platform/src/Components/ScannerV4IntegrationBanner.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationPage.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/ImageIntegrationsSection.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationTiles/IntegrationTile.tsx, ui/apps/platform/src/Containers/Integrations/IntegrationsListPage/IntegrationsListPage.tsx, ui/apps/platform/src/Containers/MainPage/Sidebar/NavigationContent.tsx
As titled.
With `ROX_SCANNER_V4` set to `false`:
Verify the correct display of the Workload CVE Tech Preview label in the navigation and verify updated wording in the Scanner V4 banner:
Verify that existing integrations have the correct layout and no Tech Preview label:
https://github.com/stackrox/stackrox/assets/1292638/fc42d80a-8708-431a-ae24-ed16ce11a6ca
With `ROX_SCANNER_V4` set to `true`:
The banner is no longer visible in the Workload CVE section:
Existing integrations again have the same layout and no Tech Preview label, but Scanner V4 _does_ have the Tech Preview label:
https://github.com/stackrox/stackrox/assets/1292638/580f3bf1-81d1-40d5-995f-104dd6aa91a1
=> ROX-23353: Add tech preview label to ScannerV4 UI components

deploy/common/deploy.sh, deploy/common/k8sbased.sh
Improve retries around `curl` which is a subtle topic:
1. ~replace `--retry-connrefused` with `--retry-all-errors` which retries "all **transfer** errors"~ nope, [our base image is from the previous decade, and bumping it is a bigger effort](https://redhat-internal.slack.com/archives/CELUQKESC/p1710939795485529)
2. use `--fail` which is necessary for 4xx and 5xx to be retried, since it turns out these are not transfer errors 🤦🏻‍♂️ 
3. do our own retry loop on top to prevent further ~unexpected corner cases of~ failures popping up 
4. don't retry in `wait_for_central` which has its own retry logic
5. in `launch_sensor` do a custom retry loop with different name every time when fetching init bundle, to cover rare situations where bundle would be created on central but `curl` failed to read …
=> ROX-12746: Fix curl retries, related improvements.

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePageHeader.cy.jsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/utils/textUtils.ts
Adds the main page layout and header rendering to the Node CVE single page.
Visit a Node CVE page by manually entering a URL ending with `node-cves/cve/<cve-id>` and view the simulated loading state:
After the metadata loads, see the rendered header:
=> ROX-23037: Add page layout and header to node cve single page

pkg/env/sensor.go, pkg/sensor/queue/scaler.go, pkg/sensor/queue/scaler_test.go, sensor/common/deploymentenhancer/component.go, sensor/common/detector/detector.go, sensor/common/networkflow/manager/manager_impl.go, sensor/kubernetes/sensor/options.go, sensor/kubernetes/sensor/sensor.go
The default values for Sensor queues and buffers are roughly based on expected 4GB of memory limit at runtime.
If we have more (or less) memory available, Sensor now tweaks the queue and buffer sizes relatively.
This means that we halve the queue sizes at 2GB and double them at 8GB.
The introduced scaling function will only scale each queue/buffer size, if it wasn't changed from its default value.
Introduced unit tests plus manual testing.
The manual testing was concluded by deploying to a cluster, enabling debug logs and looking for correct scaling operations.
The deployment shown was locally to Minikube, with 500MB memory (12.5% of default 4GB):
```
pkg/sensor/queue: 2024/03/13 13:41:13.748213 scaler.go:56: Info: Scaling …
```
=> ROX-22764: Scaling Sensor queues based on available memory

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCvesPage.tsx
Adds routing and a simple page component for the Node CVEs - Node single page.
Visit `/node-cves/nodes/<placeholder-node-id>':
=> ROX-23044: Add route and page component for Node single page

scripts/ci/lib.sh
We can revert changes to lib.sh that installs custom go version once following PR is merged
- https://github.com/openshift/release/pull/49962
CI (prow)
=> chore(ci): revert go version replace

.github/actions/junit2jira/action.yaml, .github/workflows/build.yaml, .github/workflows/unit-tests.yaml
This PR enhance junit2jira action with uploading test metrics into bigquery.
```sql 
SELECT JobName FROM `acs-san-stackroxci.ci_metrics.stackrox_tests`
WHERE BuildTag = '10474/merge@ffeacd0b325c0fcc4a9c997c325db4d549377317'
GROUP BY JobName
```
```
Row	| JobName
1       | ui
2       | shell-unit-tests
3       | go
4       | local-roxctl-tests
5       | go-postgres
```
=> fix(test): load unit test metrics into bq

tests/upgrade/legacy_to_postgres_run.sh
In upgrade test we checkout to 4.4 release that is not ready for Go 1.21. This PR runs `go mod tidy` and commit changes to ensure we will have no issues with modules.
https://github.com/stackrox/stackrox/blob/211318441a1a3958acf5e5b3cd44fb67795cf435/tests/upgrade/legacy_to_postgres_run.sh#L17-L18
Upgrade test
=> fix: upgrade test with Go 1.21

.konflux/.gitignore, .konflux/README.md, .tekton/main-pull-request.yaml, .tekton/main-push.yaml, image/rhel/konflux.Dockerfile
For now it's just built and not linked further.
We _may_ have rocksdb source _not_ included in the resulting source container due to the custom way I clone it. I don't know how to quickly check that but I don't think this is a big issue since we plan getting rid of rocksdb soon.
These aren't needed and won't be done.
1. Checked that CI is green.
2. Examined resulting container to see the files inside:
```
$ podman run --rm -it --entrypoint=/bin/bash quay.io/redhat-user-workloads/rh-acs-tenant/acs/main:on-pr-e3ababc59b2eaa5967ce4a8d34b8b0c7ab1d715c
bash-4.4$ ls -lh /lib/rocksdb    
total 587M
drwxr-xr-x 3 root root 4.0K Mar 26 15:11 include
-rw-r--r-- 1 root root 587M Mar 26 14:58 librocksdb.a
```
`rocksdb` static library is huge although it's the same for upstream builds.
```
$ podman run …
```
=> ROX-20160: Add `rocksdb` build to `main` in Konflux

tests/upgrade/legacy_to_postgres_run.sh
This PR have a better fix for upgrade test. Instead of relying on existence of some artificial branch it just changes the toolchain to 1.20.10
Upgrade test
=> fix: upgrade test

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/DeploymentFilterLink.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/LabelsModal.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/searchOptions.ts
This PR includes the following:
1. Adding the namespaces table
2. Adding sorting for the table
3. Adding pagination for the table
4. Adding search filters for the table
5. Clicking on the Deployment link will take you to the Workload CVEs Deployments table and filter by Namespace and Cluster
6. Clicking on the Labels link will open up a modal and display a list of labels
https://github.com/stackrox/stackrox/assets/4805485/8e542a47-050b-469a-8db1-be1283b0acc3
This is what shows up when there is an error while polling. Once we settle on the table UI state management work, a lot of this boilerplate work should become unnecessary.
=> ROX-22735: Adding a namespace table to the Namespace view

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/ClustersTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCvesPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/types.ts
Adds routing and the main layout for the Platform CVE Overview/List page.
Visit Platform CVEs from the sidebar, the "CVE" tab should be the default and reflected in the URL:
Click the "Cluster" tab, and see the placeholder text change and the URL update:
=> ROX-23063: Platform CVE overview page

ui/apps/platform/src/Components/PatternFly/BacklogListSelector.tsx, ui/apps/platform/src/Components/PatternFly/IconText/ExternalLink.tsx, ui/apps/platform/src/Components/PatternFly/IconText/PolicyStatusIconText.tsx, ui/apps/platform/src/Components/PatternFly/SeverityIcons.tsx, ui/apps/platform/src/Components/TooltipFieldValue/TooltipFieldValue.tsx, ui/apps/platform/src/Containers/AccessControl/AccessScopes/EffectiveAccessScopeStateIcon.tsx, ui/apps/platform/src/Containers/AccessControl/AccessScopes/RequirementRow.tsx, ui/apps/platform/src/Containers/AccessControl/AccessScopes/RequirementRowAddKey.tsx, ui/apps/platform/src/Containers/AccessControl/PermissionSets/AccessIcons.tsx, ui/apps/platform/src/Containers/Administration/Events/AdministrationEvent.tsx, ui/apps/platform/src/Containers/Clusters/ClusterLabelsTable.tsx, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredCluster.tsx, ui/apps/platform/src/Containers/Collections/RuleSelector/ByLabelSelector.tsx, ui/apps/platform/src/Containers/Collections/RuleSelector/ByNameSelector.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/Coverage/compliance.coverage.utils.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/ClusterCompliance/ScanConfigs/components/ComplianceClusterStatus.tsx, ui/apps/platform/src/Containers/ConfigManagement/List/utilities/NoEntitiesIconText.tsx, ui/apps/platform/src/Containers/SystemHealth/CardHeaderIcons.tsx, ui/apps/platform/src/Containers/SystemHealth/ClustersHealth/ClustersHealthTable.tsx, ui/apps/platform/src/Containers/User/RolesForResourceAccess.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/WatchedImages/WatchedImagesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ComponentLocation.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/DynamicIcon.tsx
Fixes icon colors throughout.
Why?
The codemod wraps all icons in an `<Icon>` component, and moves the color prop from the specific icon to this wrapper. Due to the way these props are handled, the color does not get applied on the inner icon, so we move the `color` prop back to its original location.
Attached collections:
External link icon:
Policy status icons:
Access scope state icons:
Access scope label selector:
Permission sets icons:
Administration event icons:
Fix clusters label table:
Fix collection trash icons:
Fix Compliance V2 icons:
TODO - Need to test this in another environment
Fix "no entities" icons in Config Mgmt:
Fix system health card header icons:
User role icons:
Workload CVE Icons:
Watched images table:
=> chore(ui): pf5 tweaks round 3 icon colors

central/metrics/central.go, central/metrics/init.go, central/reprocessor/reprocessor.go
Add a duration gauge metric for the reprocessor loop. This will help us determine the effects of future performance optimizations of the reprocessor loop.
Verified the Prometheus metric contains the duration.
=> ROX-22724: add reprocessor duration metric

pkg/env/registry.go, pkg/registries/docker/config.go, pkg/registries/docker/docker.go, pkg/registries/docker/docker_integration_test.go, pkg/registries/google/google_integration_test.go, pkg/registries/ibm/ibm_integration_test.go, pkg/registries/nexus/nexus_integration_test.go, pkg/registries/quay/quay_integration_test.go, pkg/registries/rhel/rhel_integration_test.go, pkg/scanners/google/google_integration_test.go, pkg/scanners/quay/quay_integration_test.go, tests/e2e/lib.sh
Make the registry timeouts configurable via environment variables. This is to cover our bases in case it causes issues for a user. It also allows to easily fine tune or experiment with different values in our CI.
=> ROX-22724: registry timeout env vars

pkg/env/registry.go, pkg/registries/docker/config.go, pkg/registries/docker/docker.go, pkg/registries/docker/docker_integration_test.go, pkg/registries/google/google_integration_test.go, pkg/registries/ibm/ibm_integration_test.go, pkg/registries/nexus/nexus_integration_test.go, pkg/registries/quay/quay_integration_test.go, pkg/registries/rhel/rhel_integration_test.go, pkg/scanners/google/google_integration_test.go, pkg/scanners/quay/quay_integration_test.go, tests/e2e/lib.sh
Reverts stackrox/stackrox#10431
This broke OCP installs. Possibly due to dupe of envVar name.
=> Revert "ROX-22724: registry timeout env vars"

central/administration/events/datastore/internal/writer/writer_impl.go, central/deploymentenvs/manager_impl.go, central/networkpolicies/graph/diff.go, central/networkpolicies/graph/diff_test.go, pkg/concurrency/key_fence.go, pkg/concurrency/sortedkeys/serialization.go, pkg/dbhelper/db.go, pkg/grpc/client/authn/servicecerttoken/client_creds.go, pkg/ioutils/chan_writer.go, pkg/istioutils/istio_api_resources.go, pkg/mtls/ca.go, pkg/printers/csv.go, pkg/sliceutils/clone.go, pkg/sliceutils/clone_test.go
With the release of go1.21 the [slices](https://pkg.go.dev/slices@go1.21.8) package has been added, and we can replace a few of our internal slice utils with it.
=> chore(slices): use stdlib slices.Clone

central/tlsconfig/tlsconfig_test.go, pkg/sliceutils/map.go, pkg/sliceutils/reverse.go, pkg/sliceutils/reverse_test.go
With the release of go1.21 the [slices](https://pkg.go.dev/slices@go1.21.8) package has been added, and we can replace a few of our internal slice utils with it.
=> chore(slices): use stdlib slices.Reverse

central/clusterinit/backend/render.go, central/debug/service/db_diagnostics.go, central/notifiers/cscc/convert.go, central/notifiers/email/email.go, compliance/collection/command/command_test.go, pkg/bolthelper/bolt.go, pkg/compliance/checks/kubernetes/control_plane_config_test.go, pkg/compliance/checks/kubernetes/etcd_test.go, pkg/compliance/checks/kubernetes/master_api_server_test.go, pkg/compliance/checks/kubernetes/master_config_test.go, pkg/compliance/checks/kubernetes/worker_node_config_test.go, pkg/compliance/checks/nist800-190/check421/check_test.go, pkg/netutil/default_port_test.go, pkg/notifiers/format.go, pkg/services/convert.go, pkg/stringutils/wrap.go, pkg/testutils/db_name.go, pkg/version/compare.go, roxctl/central/generate/file_format.go, scanner/updater/rhel/updaterset.go
Use `strings.ReplaceAll` instead of `strings.Replace`
https://pkg.go.dev/strings#ReplaceAll
CI
=> chore(strings): use ReplaceAll

scripts/ci/lib.sh
The interop team use firewatch to file JIRAs for test failures. The ACS team uses other jobs to onboard new OCP versions where junit2jira will still run.
=> chore(CI): skip junit2jira for interop jobs

qa-tests-backend/src/test/groovy/DefaultPoliciesTest.groovy, qa-tests-backend/src/test/groovy/Services.groovy
The `DefaultPoliciesTest.Verify that alert counts API is consistent with alerts` test flakes because the alerts count API is 1 less compared to the alerts API. e.g. [1](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-master-ocp-4-11-merge-qa-e2e-tests/1768047113523957760) & [2](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stackrox-stackrox-nightlies-aro-qa-e2e-tests/1775317181928574976). I suspect this is due to the `Verify policy X is triggered` test enabling and disabling a policy. This PR adds a wait to that test for the alert to clear before proceeding. If all is well that will avoid the flake and if not it will help with debug.
CI+:
- `ci-all-qa-tests` to exercise the alert count API test
- OCP QA to verify …
=> fix(CI): DefaultPoliciesTest: wait for violations to clear

central/declarativeconfig/health/datastore/datastore.go, central/declarativeconfig/health/datastore/datastore_impl_test.go, central/declarativeconfig/updater/access_scope_updater_test.go, pkg/declarativeconfig/context.go, pkg/uuid/uuid.go, pkg/uuid/uuid_test.go
Improve the test coverage of the access scope updater for declarative config.
- see CI.
=> chore(dec-config): add tests to access scope updater

roxctl/central/central.go, roxctl/central/login/login.go, roxctl/central/m2m/exchange/exchange.go, roxctl/central/m2m/exchange/exchange_test.go, roxctl/central/m2m/m2m.go, roxctl/common/client.go, roxctl/common/config/config.go
This adds the machine-to-machine access token exchange as a roxctl command, which also neatly integrates with the configuration store for roxctl.
This will allow people to call the command within scripts and benefit from setting up authentication later on, without requiring them to execute API calls manually but rather
have everything bundled within the CLI.
- see CI.
Create a m2m config:
```json
{ …
```
=> feat(roxctl): add m2m exchange as a command

central/declarativeconfig/updater/permission_set_updater_test.go
Increase test coverage for the permission set updater in declarative config.
- see CI.
=> chore(dec-config): add tests to perm set updater

qa-tests-backend/src/test/groovy/DeclarativeConfigTest.groovy
Fixes a CI flake which occasionally occurred when the ordering of groups wasn't as expected. This should now be more stable and less flaky.
- see CI.
=> ROX-22964: Assert groups without ordering

.github/dependabot.yaml, tools/retest/main.go
As discussed auto-merge label is not a best name for auto retest feature. This PR changes the label name and adds it to dependabot so we do not need to retest manually.
See: https://redhat-internal.slack.com/archives/CELUQKESC/p1711383807553069?thread_ts=1711124692.089649&cid=CELUQKESC
N/A
=> chore: change label for auto retest

qa-tests-backend/src/test/groovy/SACTest.groovy
Previous PR that tried to fix this issues didn't solve the problem. Let's retry so we get more time to update summaries.
- https://github.com/stackrox/stackrox/pull/10106
CI
=> ROX-19953: retry get summary counts

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageHeader.tsx
Adds a header to the Node detail page.
Visit a Node page via direct URL and see the loading state:
After loading, the data is displayed:
=> ROX-23045: Add header to Node detail page

.tekton/main-pull-request.yaml, .tekton/main-push.yaml, image/rhel/konflux.Dockerfile, image/roxctl/konflux.Dockerfile, operator/konflux.Dockerfile
Onboarding the Go binary builds into the main image build on Konflux.
Konflux build succeeds.
Running image `quay.io/redhat-user-workloads/rh-acs-tenant/acs/main:on-pr-e7a2cd4e454aecc8b6f3e0f5e2a09ab3ff2b9345` with Docker/Podman locally and testing that all binaries can be executed (failures expected due to missing configuration files). 
=> ROX-20160: Add Go build to main in Konflux

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx, ui/apps/platform/src/css/trumps.css
Adds Vulnerability and Detail tabs to node detail page with URL integration.
Visit a node detail page and see that Vulnerabilities is the default selected tab:
Switch to the Details tab and see that the container and URL are updated accordingly:
=> ROX-23046: Add node detail page tabs

central/detection/lifecycle/manager_impl.go, central/policy/datastore/datastore_impl.go, central/policy/service/service.go, central/policy/service/service_impl.go, central/policy/service/service_impl_test.go, central/policy/service/singleton.go, qa-tests-backend/src/main/groovy/services/PolicyCategoryService.groovy, qa-tests-backend/src/test/groovy/DeploymentCheck.groovy
Currently, if you attempt to filter policies by category when using e.g. `roxctl deployment check` (i.e. the detection service), it won't be possible to filter for policies _iff_ they have been either added or updated _without_ a Central restart.
The culprit lies within the datastore implementation and the policy sets used for the build-time and deploy-time detectors: the same reference that is stored in the policy set is beforehand passed to the datastore.
Within the datastore, the policy reference's `policy_categories` field is being reset due to the categories being stored in the policycategories edge store. This leads to the reference that finally gets upserted to the policy set to not contain any policy categories, thus making it unable to filter by categories.
After Central has been …
=> ROX-23523: Fix policy categories filter

central/sensor/service/pipeline/networkflowupdate/pipeline.go, pkg/centralsensor/caps_list.go, sensor/common/networkflow/manager/manager_impl.go
Central has now a capability to mark that it is able to display the 'Internal Entities' node on the network graph. If this cap is missing, Sensor would return all internal entities as external entities (as those are supported by older centrals). 
I manually deployed various combinations of Central and Sensor and looked at the Network Graph for the `stackrox` namespace. Here are the results:
Result: ❌  Network Graph does not load
Result: ✅ Network Graph works, all unknown flows are treated as external (default behavior for versions 4.3 and older)
Result: All good, internal entities are visible. Adding Central capability first in this PR, does not prevent 4.4.0 Sensor from sending flows of type 5 (internal).
Result: ✅ Sensor sends only …
=> ROX-23540: Add Central cap to display Internal Entities in the NWG 

qa-tests-backend/src/test/groovy/DeploymentCheck.groovy, qa-tests-backend/src/test/groovy/ImageManagementTest.groovy
After [#10649](https://github.com/stackrox/stackrox/pull/10649) has landed, the policy API now correctly returned the categories. Previously this field was empty. A test tried to workaround this issue and thus started failing due to duplicating categories now.
This has gone unnotice due to the prow outage.
- see CI.
=> fix(ROX-23596): fix policy creation in test

ui/apps/platform/cypress/integration/vulnerabilities/workloadCves/imageSingle.test.js
Fixes a e2e test flake after the PF5 merge.
The test is a consistency check that verifies the total of all CVEs by severity is equal to the total number of results found for an image:
The flake would occur when any of "Important", "Moderate", or "Low" CVE counts is equal to zero. This is due to the test code incorrectly returning `0` instead of the currently accumulated count when parsing the text results in `NaN`. Note that this doesn't happen when there are only zero "Critical" CVEs, as that is the first entry parsed and the accumulated value would be equal to `0`!
This is an intermittent error because the image chosen is non-determinisitc and will depend on the underlying platform as well as the currently detected CVEs for that image. …
=> ROX-23153: Return accumulated count in e2e test when parsed int is NaN

scanner/indexer/indexer.go
This is inspired by https://github.com/quay/clair/pull/2031. Ideally we should have a better way to track this, but for now, we can at least add a log to let us know if the `Range` query was respected. Ideally, it is, and we only pull layer contents once; however, it is possible not all registries support this.
To avoid potential log spam, the log is a debug log
trivial
In addition to reviewing code here, reviewers **must** …
=> chore(scanner): log when registry does not support Range header

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCvesPage.tsx
Adds routing and placeholder component for Platform CVEs: Cluster single page.
Via direct visit in URL:
Click the breadcrumb link and ensure the page navigates back to the cluster overview list:
=> ROX-23070: Add routing for Platform CVE cluster page

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageHeader.tsx
Adds the metadata query and loading headers to the Platform CVEs cluster page.
Visit a cluster page manually by editing the URL with a valid cluster id:
Loading:
Loading complete:
=> ROX-23071: Platform cves cluster page layout

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/CvePageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/HeaderLoadingSkeleton.tsx
Refactors nearly identical code used in 5 (so far) places in VM 2.0 into a common component.
Visit each of the Workload/Node/Platform CVE pages that currently exist and verify the loading skeletons are still displayed while the data is in transit.
=> chore(ui): Refactor header loading skeleton

.openshift-ci/begin.sh, scripts/ci/lib.sh
The AWS user in the CI context is different from the provisioning (create step) user. This PR gives the CI user access to the cluster. 
https://github.com/stackrox/automation-iac/pull/90 is also required.
/test eks-qa-e2e-tests
```
>>> Add user ARNs to aws-auth
User: arn:aws:iam::XXXXXXXXXXXX:user/automation/stackrox-ci-general-test-user
configmap/aws-auth patched
```
=> fix(CI): give the CI user access to EKS clusters

.tekton/main-pull-request.yaml, .tekton/main-push.yaml, image/rhel/konflux.Dockerfile
`main` builds started failing roughly after <https://github.com/stackrox/stackrox/pull/10551>. Even though its CI succeeded, its merge failed.
It's hard for me to explain why, but the recommendation I received as part of the investigation thread <https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1712851558680229> was to reduce the number of unique `FROM` stages.
It looks like aliases don't count as unique stages and so I reduce the usage of `ubi8/ubi` (the only one possible, it seems).
Three successful runs:
1. https://console.redhat.com/preview/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-on-pull-request-xcvrc
2. https://console.redhat.com/preview/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-on-pull-reque …
=> fix: Repair failing `main` build in Konflux

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/CvePageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/HeaderLoadingSkeleton.tsx
Adds "Vulnerability" and "Details" tabs to the cluster single page.
Refactors the tabs on the node single page to reduce noise in the code.
Visit a cluster single page. The tab parameter should default to "Vulnerabilities" and be visible in the URL.
Click on "Details" to view the tab, content, and URL change:
=> ROX-23072: Add detail tabs to cluster single page

pkg/env/roxctl.go, roxctl/common/environment/environment-impl.go, roxctl/common/io/io.go, roxctl/common/io/io_test.go
The roxctl image is a bare image. It is the base image for some tekton actions.
Currently, tekton does not allow output redirection out of the box. In order to allow users to process roxctl output (e.g. open a ticket if CVEs are reported in an image scan output), it would be good to allow roxctl to redirect the standard output and the standard error without the standard shell output redirections.
The choice of environment variables rather than command line flags is driven by the fact that the roxctl environment (including output and error stream initialization) is setup before the command line flags are actually parsed.
Use this space to explain **how you validated** that **your change functions exactly how you expect …
=> feat(roxctl): allow writing output and error streams to files

sensor/common/internalmessage/internal_message_pubsub.go, sensor/common/internalmessage/message.go, sensor/common/sensor/central_communication_impl.go, sensor/common/sensor/sensor.go, sensor/kubernetes/eventpipeline/pipeline.go, sensor/kubernetes/eventpipeline/pipeline_impl.go, sensor/kubernetes/sensor/sensor.go
Components can request connection to restart. 
This is required due to dynamic starting of compliance operator listeners. By restarting the connection Sensor will run reconciliation again.
Example changes made to event pipeline:
```go
func (p *eventPipeline) Start() error {
+       go func() {
+               for {
+                       <-time.After(10 * time.Second)
+                       if err := p.pubSub.Publish(&internalmessage.SensorInternalMessage{
+                               Kind:     internalmessage.SensorMessageSoftRestart,
+                               Text:     "just messing with the connection",
+                               Validity: p.getCurrentContext(),
+                       }); err != nil {
+ …
```
=> ROX-23574: Allow soft-restart of Sensor connection

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodesTable.tsx
Minor refactor that extracts `<TableEntityToolbar>` from the Node and NodeCVE tables to the parent component, as also done in Platform CVEs, in order to make follow up PRs smaller.
Minimal change - test that the WIP Node page still loads without error:
=> chore(ui): node cves table component refactor

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/ClustersTable.tsx
Adds the cluster list to the Platform CVEs overview page.
Visit platform CVEs and click the cluster tab:
Loading:
Error:
Empty without filters:
Empty with filters:
Success:
Clicking the link in the table takes you to the correct Cluster single page:
=> ROX-23060: Add cluster list table to Platform CVEs

ui/apps/platform/package.json, ui/apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersToolbar.cy.jsx, ui/apps/platform/src/Containers/Dashboard/ScopeBar.cy.jsx, ui/yarn.lock
See if we can move forward again after downgrade from 13.2.0 to 12.17.4 to in #7920
https://docs.cypress.io/guides/references/changelog#13-7-1
https://docs.cypress.io/guides/references/changelog#13-7-2
https://docs.cypress.io/guides/references/changelog#13-7-3
* compliance/hideScanResults.test.js
* apps/platform/src/Containers/Clusters/DiscoveredClusters/DiscoveredClustersToolbar.cy.jsx TODO fails locally
* vulnmanagement/clusterVCves.test.js
* vulnmanagement/clusters.test.js
* vulnmanagement/deployments.test.js
* vulnmanagement/imageComponents.test.js
* vulnmanagement/imageCves.test.js
* vulnmanagement/images.test.js
* vulnmanagement/namespaces.test.js
* …
=> chore(e2e): Update cypress 13.7.3 devDependencies in ui

qa-tests-backend/scripts/workload-identities/workload-identities.sh
The `gcloud` calls may fail when race conditions are detected. See https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-ocp-4-15-merge-qa-e2e-tests/1780578263538601984 for an example.
CI
=> fix: add gcloud retry in wif setup

.github/workflows/retest_periodic.yml, tools/retest/github.go, tools/retest/main.go, tools/retest/main_integration_test.go
Fixes:
- broken action that after splitting main.go needs to run `./...` 
- error on empty comment body when we do not want to comment
- search filters by failing statues which is ok for `retest` but not for `retest-times`
https://github.com/stackrox/stackrox/actions/runs/8723885263/job/23933147486?pr=10788
=> fix: retest action

pkg/registries/docker/metadata_v1.go
Messages in proto v2 contains a mutex co copying them like that may lead to races.
CI
=> fix: do not copy image layer object

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/utils/searchUtils.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/utils/searchUtils.tsx
Adds the Node CVE list table to the Node CVE overview page.
Note: This is currently using simulated data until the APIs are in place.
Visit the Node overview page:
Loading:
Error:
Empty without filter:
Empty with filter:
Success:
Click a CVE link within the table and ensure it navigates to the correct page:
=> ROX-23032: Add node cves list table

qa-tests-backend/README.md, qa-tests-backend/src/test/groovy/AutocompleteTest.groovy, qa-tests-backend/src/test/groovy/BaseSpecification.groovy, qa-tests-backend/src/test/groovy/CSVTest.groovy, qa-tests-backend/src/test/groovy/GlobalSearch.groovy, qa-tests-backend/src/test/groovy/SACTest.groovy, qa-tests-backend/src/test/groovy/UpgradesTest.groovy, qa-tests-backend/src/test/groovy/VulnMgmtSACTest.groovy, qa-tests-backend/src/test/groovy/VulnMgmtTest.groovy, qa-tests-backend/src/test/groovy/VulnReportingTest.groovy, qa-tests-backend/src/test/groovy/VulnScanWithGraphQLTest.groovy
Removing the `ROX_POSTGRES_DATASTORE` environment variable from `qa-tests` as well as the `isPostgresRun()` and the different queries we had to use when we supported both rocksDB and postgres.
=> chore(qa-tests): remove ROX_POSTGRES_DATASTORE

pkg/registries/docker/metadata_v1.go, sensor/common/admissioncontroller/settings_manager_impl.go
New version of protobuf puts a mutex into a message. This causes copying mutex which could lead to race condition.
```go
pkg/registries/docker/metadata_v1.go:75:13: copylocks: assignment copies lock value to latest: github.com/stackrox/rox/generated/storage.ImageLayer contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)
latest = *layer
^
pkg/booleanpolicy/augmentedobjs/construct.go:197:9: copylocks: assignment copies lock value to img: github.com/stackrox/rox/generated/storage.Image contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)
img := *image
^
sensor/common/admissioncontroller/settings_manager_impl.go:46:15: copylocks: assignment copies lock value to *settings: …
```
=> fix(proto): clone instead of copy

central/summary/service/service_impl_test.go
Fix the test to use common struct field tags instead of custom generator internal fields.
CI only, since test is changed
=> fix(proto): Remove usage of internal gogoproto generated fields

central/imageintegration/datastore/telemetry.go
Report 0 by default for image integrations to allow for better rendering in our telemetry charts.
N/A.
=> fix(imageintegrations): report 0 by default in telemetry

ui/apps/platform/package.json, ui/package.json, ui/yarn.lock
Quarterly update has no breaking changes for ui code.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/
* https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/#preserved-narrowing-in-closures-following-last-assignments
> TypeScript can usually figure out a more specific type for a variable based on checks that you might perform. This process is called narrowing.
> One common pain-point was that these narrowed types weren’t always preserved within function closures.
> When parameters and `let` variables are used in non-hoisted functions, the type-checker will look for a last assignment point. If one is found, TypeScript can safely narrow from outside the containing function.
* https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/#objectgroupb …
=> chore(ui): Upgrade TypeScript 5.4.5 and related devDependencies in ui

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.cy.jsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeComponentsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx
Adds the affected node table on the Node CVE single page.
_Note that the data is mocked until the query is fully implemented._
Visit a Node CVE single page:
Table states and properties are tested via automated tests below.
Added component tests to validate table state and the more interesting properties of this table:
- Severity is the highest severity of all vulns in all components affected by the CVE
- CVE status is "Fixable" when _any_ of the vulns in any component has a non-empty fixedByVersion
- CVSS is the highest calculated CVSS of all vulns in all components affected by the CVE
=> ROX-23034: Add affected node table to CVE single page

ui/apps/platform/cypress/integration/integrations/integrations.helpers.js, ui/apps/platform/src/Components/TabNav/TabNavSubHeader.tsx, ui/apps/platform/src/Containers/AccessControl/AccessScopes/AccessScopes.css, ui/apps/platform/src/Containers/AccessControl/AuthProviders/AuthProviderForm.tsx, ui/apps/platform/src/Containers/AccessControl/AuthProviders/ConfigurationFormFields.tsx, ui/apps/platform/src/Containers/Audit/ListeningEndpoints/ListeningEndpointsPage.tsx, ui/apps/platform/src/Containers/Clusters/Components/ClusterStatusPill.tsx, ui/apps/platform/src/Containers/Collections/CollectionResults.tsx, ui/apps/platform/src/Containers/ExceptionConfiguration/VulnerabilitiesConfiguration.tsx, ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx, ui/apps/platform/src/Containers/NetworkGraph/components/NetworkBreadcrumbs.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ComponentLocation.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SeverityCountLabels.tsx, ui/apps/platform/src/css/trumps.css
Addressing follow up style regressions in this PR. 
1) Network graph: Last update time block/breadcrumb is not vertically centered in toolbar
Before: 
After:
2) VM 2.0 - Workload CVEs: Severity count spacing is incorrect
Before:
After:
3) VM 2.0 - Exception Mgmt: The request name link doesn’t show an underline when you hover over it
Before:
After:
4) Clusters: Classic StackRox-style pills in Cluster Status column no longer wrap
Before:
After:
5) Policy Mgmt: Spacing is odd in the header above the table
Before: 
After:
6) Collections: Deployment preview sidebar search button is always enabled, even when no text is present:
Unfixed because this is the expected behavior according to `SearchInput` component in PF5 documentation (https://www.patternfly.org/components/search-input)
7) …
=> ROX-23624: PF5 style fixes follow up

ui/apps/platform/src/Containers/SystemConfig/Form/SystemConfigForm.tsx, ui/apps/platform/src/global/initializeAnalytics.js, ui/apps/platform/src/reducers/telemetryConfig.js
Segment connection should pass through RedHat proxy
* Verified analytic events were still coming through
* Verified that the obfuscated ip received by segment changed before and after the update
=> ROX-23469: Update UI segment endpoint

sensor/common/sensor/central_communication_impl.go, sensor/kubernetes/eventpipeline/pipeline.go, sensor/kubernetes/eventpipeline/pipeline_impl.go, sensor/kubernetes/listener/listener.go, sensor/kubernetes/listener/listener_impl.go, sensor/kubernetes/listener/resource_event_handler.go, sensor/kubernetes/listener/utils/utils.go, sensor/kubernetes/listener/watcher/complianceoperator/availabilitychecker.go, sensor/kubernetes/listener/watcher/crd/crdwatcher.go, sensor/kubernetes/listener/watcher/crd/crdwatcher_test.go, sensor/kubernetes/listener/watcher/crd/handler.go, sensor/kubernetes/listener/watcher/status.go, tests/complianceoperator/crds/scansetting.yaml
Adds a new CRD watcher that will trigger an event if the CRDs for CO become/stop-being available.
=> ROX-22389: add CRD watcher

pkg/images/enricher/enricher_impl.go, pkg/images/enricher/enricher_impl_test.go
This fixes an issue in the current behavior of the image enricher where unconditionally the image name of the image to-enrich was used as the top-level image name, irrespective of whether one is retrieving cached values or not.
This leads to an issue where the to-be-enriched image has an invalid image reference (e.g. a name that isn't pointing to the correct image) but specified via digest. This would result
in an image being upserted which has a top level name which cannot be enriched but still all other valid cached fields like image scan, metadata, sigs etc.
The behavior has now changed to the following within this PR:
- instead of overwriting the image's top-level name with the to-be-enriched image name; this will now only be done when we use the force option; i.e. we disregard cached …
=> fix(ROX-23214): overwrite image name only when not cached

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodesTable.tsx, ui/apps/platform/src/messages/common.ts
Adds the nodes table to the Node CVE overview page.
This PR relies on simulated data until the BE queries are in place.
Visit the Node CVE page:
Click the Nodes tab:
Loading:
Error:
Empty no filter:
Empty with filter:
Success:
Clicking a Node link takes you to the node detail page:
Table view with a severity filter applied:
=> ROX-23042: Add node list table to CVE overview page

ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedDeferrals.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/ApprovedFalsePositives.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/DeniedRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/PendingRequests.tsx, ui/apps/platform/src/Containers/Vulnerabilities/ExceptionManagement/components/RequestCVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/constants.ts
Adds pagination component to Node CVE detail page.
Node counts and node data are simulation, this is specifically for the Pagination component and interaction with the URL parameters.
Visit a Node CVE page and see the pagination component:
Page over, and the URL is updated (data is still simulated though):
Change the perPage:
Goto end of pages:
=> ROX-23039: Add pagination to Node CVE detail page

ui/apps/platform/src/Containers/NetworkGraph/NetworkGraphPage.tsx
Fixes a crash and rendering error in the Network Graph when using `central` version < 4.4.0 but a `sensor` version >= 4.4.0.
The crash is due to an internal entity node with type `5` being saved in central and passed to the UI. In 4.4.0 this value would be passed to the UI as the enum value `INTERNAL_ENTITIES`. Regardless, the UI in 4.3.x does not know how to handle either type and ignores it. The side effect of ignoring this entity is that there are edge connections in the graph where the target node does not exist, causing the error.
The fix is to convert entities of type `5` to `INTERNET`, which is incorrect, but consistent with the behavior expected in all versions of ACS <= 4.4
**Note that this PR is specifically targets to `release-4.3` and should not be merged to `master`.**
If any …
=> ROX-23661: Net graph internal entity patch

pkg/booleanpolicy/evaluator/pathutil/augmented_obj_meta.go, pkg/postgres/walker/walker.go, pkg/protocompat/oneof.go, pkg/protocompat/oneof_test.go, pkg/search/fieldmap/field_visitor.go, pkg/search/walker.go
This PR cleans up usage of internal `XXX_OneofWrappers` function.
Made changes:
- added function (with tests) to get oneof types by interface
- refactor function name use to get oneof type by field index
- remove all usages of `XXX_OneofWrappers`
- adjust comments and clean them up too
- Introduced unit test
- CI run
performed one does not seem sufficient. …
=> ROX-22019: Cleanup usage of XXX_OneofWrappers internal func

govulncheck/main.go, govulncheck/main_test.go, govulncheck/testdata/vulns
Fixes the scan-go-binaries job that has been failing the last couple of days.
Culprit was the update to v1.1.0 of [x/vuln](https://github.com/golang/vuln/releases/tag/v1.1.0) however the underlying issue has already been added within [v1.0.2](https://github.com/golang/vuln/releases/tag/v1.0.2):
Previously, the JSON output only contained the OSV entry and the associated module findings. With the latest changes the behavior has been changed to first stream _all_ potential OSV entries _irrespective_ of whether
they are associated with the current module version _and_ the findings which are associated with the current module version.
The code has now been changed to do the following:
- Store all OSV entries in-memory when parsing the JSON stream.
- De-duplicate all module findings (since …
=> fix: scan-go-binaries job

central/graphql/generator/codegen/schema.go, central/graphql/generator/codegen/typewalk.go
This PR removes usage or `XXX_` fields in the GraphQL generator.
*Note for reviewers*
- check in `schemaType` looks redundant because all proto structs are populated by `walkField`.
- we are getting mix of proto structs and internal structs in `walkField` (list is in: `central/graphql/resolvers/gen/main.go`). The way to differentiate them is by `isInputType` properly.
Style checks because generated files will be different if …
=> ROX-22019: Prepare graphql codegen for proto V2

.github/workflows/build.yaml, scripts/ci/jobs/test-binary-build-commands.sh, scripts/ci/lib.sh, scripts/ci/test_state.sh, tests/e2e/lib.sh, tools/check-workflow-run/go.mod, tools/check-workflow-run/go.sum, tools/check-workflow-run/main.go
It is not clear to all users of stackrox CI that `Image_Availability` job failures are typically due to build failures in github actions. This PR improves the situation somewhat given the constraints of the openshift CI results UI.
It:
- Explicitly mentions github actions in the junit failure
- Checks the status of the GHA build workflows to include in the junit failure body and highlight in the prow UI. This is imperfect as different jobs require different workflows or parts of workflow to generate the images they need. I'll leave perfection to the next PR.
A forced build failure results in:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/10773/pull-ci-stackrox-stackrox-master-gke-nongroovy-e2e-tests/1781001763793408000
The body has the details …
=> fix(CI): link to build status for missing image failures

sensor/kubernetes/complianceoperator/updater.go
If the cached namespace is empty do not query in that namespace and instead try to find the CO deployment in all namespaces. Checking for the deployment to not be `nil` is not enough to make sure the call to `Get` was successful, `Get` could return a non-nil deployment even if the call failed. Check for `err == nil` instead.
- Install ACS (with logs level Debug)
- Check in …
=> ROX-22389: Do not query with an empty namespace

ui/apps/platform/cypress/integration/integrations/machineAccessConfigs.test.ts, ui/apps/platform/src/Containers/Integrations/IntegrationForm/Forms/MachineAccessIntegrationForm.tsx, ui/apps/platform/src/Containers/Integrations/utils/tableColumnDescriptor.ts
Change spelling from `Github` -> `GitHub`.
CI
=> fix(ui): GitHub spelling in m2m ui

.github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-release-vuln-update.yaml
After https://github.com/stackrox/stackrox/pull/10740 the vuln pipeline was broken due to a typo in the conditions and a premature move to multi-bundle in the release pipeline. This PR fixes these problems.
It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change …
=> fix(scanner): Fix vuln generation workflows

sensor/kubernetes/listener/watcher/crd/crdwatcher_test.go
This PR should fix some unexpected test failures for the `Test_CreateDeleteCRD` test.
1% (in theory 😄 ) of our unit test runs are failing with the following error:
```
2024-04-24T17:39:23.2786934Z panic: non-positive interval for NewTicker
2024-04-24T17:39:23.2787381Z 
2024-04-24T17:39:23.2787555Z goroutine 24 [running]:
2024-04-24T17:39:23.2788006Z time.NewTicker(0x0)
2024-04-24T17:39:23.2788477Z 	/usr/local/go/src/time/tick.go:22 +0x1c8
2024-04-24T17:39:23.2789744Z github.com/stackrox/rox/sensor/kubernetes/listener/watcher/crd.(*watcherSuite).createWithRandomTicker.func1()
2024-04-24T17:39:23.2791476Z 	/__w/stackrox/stackrox/sensor/kubernetes/listener/watcher/crd/crdwatcher_test.go:72 +0x5b
2024-04-24T17:39:23.2793465Z created by …
```
=> fix(test): Ensure that timer is not zero in Test_CreateDeleteCRD

.openshift-ci/post_tests.py, Makefile, operator/tests/run.sh, scripts/ci/lib.sh, tools/test/go.mod, tools/test/go.sum, tools/test/tools-import.go
This is just a first step, although already useful.
Two commits, reviewable separately:
- refactor generation of list of images that are expected for a CI job to avoid tricky substitutions
- start prefetching as early as possible, and then verify it completes right before upgrade step
Another improvement could be to start another instance that prefetches the base images (i.e. the ones from last release) since that can happen even before the build of the current commit completes. But that can be done later.
CI is enough.
Judging from the logs of a few jobs deploying the pre-fetcher added 7-18 seconds, and waiting for pulls to complete 1-4 seconds to the job runtime, but likely provided a moderate net speed-up, since non-prefetched stackrox …
=> ROX-23308: Run image prefetcher before operator e2e tests.

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/ClustersTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/AffectedClustersTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/useAffectedClusters.ts, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/utils/stringUtils.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx
Title.
Visit Platform CVEs, and click the link of a CVE to view the affected clusters list.
Loading:
Error:
Empty (should never occur here though...):
Filtered Empty:
Success:
Test clicking the cluster link:
Test clicking the breadcrumb link in the header:
=> ROX-23068: Add cluster list to Platform CVE detail page

pkg/images/enricher/enricher_impl.go, pkg/images/enricher/enricher_impl_test.go
Fix a case where mistakenly the metadata was taken from the cache instead of correctly ignore when scanning images via roxctl with the `--force` option.
- see CI for the added unit test.
=> fix: metadata should be re-fetched if disregarding cached values

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.cy.jsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodeCves.ts, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodes.ts, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useTotalNodeCount.ts, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/usePlatformCves.ts, ui/apps/platform/src/utils/searchUtils.test.js, ui/apps/platform/src/utils/searchUtils.ts
Refactors Node and Platform CVE pages for readability and consistency with recent merged pull requests.
1. Replaces manual table state logic throughout with `<TbodyUnified>` component that encapsulates this logic
2. Extracts `useQuery` calls, query definitions, and query request/response types to de-clutter the component in which they are used
Manual smoke testing of existing Node and Platform CVE pages, ensuring that data loads correctly.
=> chore(ui): Refactor Node/Platform CVE tables

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/DeliveryDestinationsDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/DeliveryDestinationsForm.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/NotifierSelection.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/hooks/useEmailTemplateModal.ts, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/utils.ts
The frontend-only `DeliveryDestination` type:
* requires conversion functions
* hinders potential reuse of delivery destination components
https://github.com/stackrox/stackrox/blob/master/ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx#L61-L71
```ts
export type DeliveryDestination = {
notifier: ReportNotifier | null;
mailingLists: string[];
customSubject: string;
customBody: string;
};
export type ReportNotifier = {
id: string;
name: string;
};
```
The frontend-only type seems to be a compromise between:
Vulnerability Reports 1.0 which has `notifierId` but not name property:
https://github.com/stackrox/stackrox/blob/master/proto/storage/report_configuration.proto#L96-L101
Vulnerability Reports 2.0 which has notifier both `notifierId` and …
=> ROX-23776: Replace DeliveryDestination with NotifierConfiguration

.github/workflows/check-image-vulnerabilities.yml
Make sure that the release vulnerability check fails if either a `Critical` or `Important` vulnerability has been found. Unfortunately we cannot pass such an error condition to `roxctl` today, so we have to scan again with `json` output and then do some `jq` parsing. Note that the image scan is cached by Central, so there is no performance penalty for scanning twice.
See example run https://github.com/stackrox/stackrox/actions/runs/8837151755.
=> ROX-23767: fail on high severity vulns

pkg/images/enricher/enricher_impl.go, pkg/protocompat/message.go, pkg/protocompat/message_test.go
We have a PR that generates protobuf V2 structs. V2 includes locks in a struct, and we had a few linter failures:
https://github.com/stackrox/stackrox/actions/runs/8483665309/job/23245169186?pr=10333
In order to fix that we should avoid shallow struct copy and use provided functions and interfaces by protobuf framework in such cases.
This PR fixes one situation where structs are copied. It is a bit trickier problem because we are not able to use `Clone` because the caller expects object modification. We can not allocate a new object. That's why the `Merge` function is used.
The `Merge` function is a bit slower (`~20us`) than copying, but this section is not in the critical execution path. It will only be executed in situations where delegated scanning is triggered, and a call to the …
=> ROX-22019: Fix protobuf V2 copylock linter errors for enricher

sensor/kubernetes/fake/fake.go
Fake workloads are failing because the dynamic client is not configured.
=> fix(fake-workloads): Add fake dynamic client

pkg/booleanpolicy/augmentedobjs/construct.go, sensor/common/detector/enricher.go
We have a PR that generates protobuf V2 structs. V2 includes locks in a struct, and we had a few linter failures:
https://github.com/stackrox/stackrox/actions/runs/8483665309/job/23245169186?pr=10333
In order to fix that we should avoid shallow struct copy and use provided functions and interfaces by protobuf framework in such cases.
For these two identified cases, we can use `Clone`.
**Benchmark**
I did some benchmarking on my local machine:
```
BenchmarkPointer
BenchmarkPointer-12                  	125648763	         9.551 ns/op
BenchmarkCustomShallowCopy
BenchmarkCustomShallowCopy-12        	60597052	        20.10 ns/op
BenchmarkReflectionShallowCopy
BenchmarkReflectionShallowCopy-12    	  126420	      9274 ns/op
BenchmarkClone
BenchmarkClone-12                    	  674404	      1727 …
```
=> ROX-22019: Fix protobuf V2 copylock linter errors

pkg/env/telemetry.go
The endpoint value is propagated to the UI, and the manifests.
UI doesn't make use of this value though, will be fixed separately.
* I set the variable, and checked the arrival of the events from my installation on Segment.
* I set an incorrect variable value, and confirmed the appearance of communication errors in the central logs.
=> ROX-23397: Set the default telemetry endpoint to RH proxy

central/auth/datastore/telemetry.go, central/main.go, image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl, operator/tests/central/central-misc/080-assert-non-openshift.yaml, operator/tests/central/central-misc/080-assert-openshift.yaml
Add telemetry information for machine-to-machine configurations as well as track the amount of `exchange` calls.
- manual test to observe that the API calls are correctly tracked in Segment + the total amount of machine-to-machine configs is there as well.
```json
{
...
"Total Generic Machine-to-Machine configurations": 0,´
"Total Github_actions Machine-to-Machine configurations": 0,
"Total Machine-To-Machine Configurations": 0
}
```
When two distinct types are created:
```json
{
...
"Total Generic Machine-to-Machine configurations": 1,
"Total Github_actions Machine-to-Machine configurations": 1,
"Total Machine-To-Machine Configurations": 2
}
```
In addition to reviewing code here, reviewers **must** also review testing and request …
=> chore(auth): add telemetry for m2m

.tekton/main-pull-request.yaml, .tekton/main-push.yaml
This is to address a failure during UI build
https://console.redhat.com/preview/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-on-push-dwflt
6Gi appears not enough occasionally, giving it +1 more.
None, just CI.
=> fix: Bump memory for `main` container builds in Konflux

tests/e2e/run-ui-e2e.sh
Install CO before stackrox in the UI tests to avoid problems with CO not being ready on time.
=> fix(test): Install CO before stackrox

central/postgres/pruning.go, pkg/env/postgres_default_timeout.go
=> ROX-23200: comments on query performance

sensor/common/centralclient/client.go, sensor/common/centralclient/grpc_connection.go, sensor/common/scannerdefinitions/http_handler.go, sensor/common/sensor/sensor.go, sensor/debugger/central/grpc_client.go, sensor/kubernetes/main.go, sensor/kubernetes/sensor/options.go, sensor/kubernetes/sensor/sensor.go, sensor/tests/connection/connection_test.go, sensor/tests/helper/helper.go, sensor/tests/helper/http.go, tools/local-sensor/main.go
This change adds trusted TLS certificates to HTTP connections in addition to gRPC, allowing you to connect to Central running behind a proxy/load balancer without configuring additional CA certificates.
There is functionality in sensor to allow loading and trusting a user's TLS certificate when Central is running behind a proxy or load balancer (see [ROX-5710](https://issues.redhat.com/browse/ROX-5710)).
This seems to work only for a persistent grpc connection, but not for proxying collector calls to load kernel modules from Central (see [ROX-19868](https://issues.redhat.com/browse/ROX-19868)).
Tested manually on an infra cluster.
1. Install Central on an infra cluster. I used Stackrox operator v4.4.0
2. Create a re-encrypt route for …
=> ROX-19974: Add trusted TLS certs for Sensor-Central HTTP connection

central/imageintegration/store/postgres/gen.go, central/imageintegration/store/postgres/store.go
Use a cached store for signature integrations. The reason for it is that during reprocessing for _each_ image the signature integrations will be fetched during verification.
Since signature integrations are expected to be a low cardinality store and also no frequent changes are expected, this poses a good candidate to make use of the cached store due to its frequent reads.
- N/A; see CI passing.
=> chore(signatureintegration): use a cached store

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/AffectedClustersSummaryCard.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/ClustersByTypeSummaryCard.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/usePlatformCveMetadata.ts
Adds the metadata request for the Platform CVE page and corresponding summary cards.
Visit a platform CVE page:
Loading state:
Error state:
Success (generic should not occur, but I am accounting for it in the payload)
=> ROX-23067: platform CVE summary cards

.github/workflows/build.yaml
Currently the image scan may fail with
```
[getting metadata from registry: "rhacs-eng": failed to get the manifest digest: Head "https://quay.io/v2/rhacs-eng/collector-slim/manifests/4.4.x-541-gbf46aba436": http: non-successful response (status=404 body="")
```
Increase the `roxctl` retry time to make sure the images are actually available during scanning.
retried workflow and it succeeded after images was there.
=> ROX-23767: increase retry time

central/telemetry/centralclient/instance_config.go, central/telemetry/centralclient/instance_config_test.go
Segment does not respect the processing order of events in a batch, which causes out-of-order processing by the analytics platform.
This PR disables batching, as per Segment support recommendation. The hope is to reduce the number of `(none)` values.
A disadvantage is that central will communicate more often, making calls per event. A possible advantage is that central events will be better correlated in time with related UI events.
Run the central in local, enable telemetry, check that the events appear immediately, with no batching.
`roxctl central whoami` command issued two events with the following timestamp:
```json
"properties": {
"Code": 0,
"Method": "/v1.AuthService/GetAuthStatus",
"Path": "/v1.AuthService/GetAuthStatus", …
```
=> chore: do not batch telemetry events

pkg/gjson/slices.go, pkg/printers/sarif.go, pkg/printers/sarif_test.go
This is a follow-up from #10150 where we fixed an issue with the SARIF report generation when an empty value in the form of the replacement string was given.
In the case of all arrays being nil we receive from the JSON path expressions (e.g. when violations during image scan are nil) then we previously had for the result and help text an empty array with the `-` value in it.
This lead to the report being failed to generated.
Now the logic of the slice mapper, which will retrieve data from the JSON path expression, has changed: in case we receive a nil array in a GJSON result, we will just return nil.
This fixes the report generation for SARIF.
- see CI (changed the unit test to have the same JSON path expression as the image scan call)
In …
=> fix(sarif): nil array should not have placeholder value

.github/workflows/build.yaml
A couple more fixes to the roxctl check in the build pipeline.
* Unfortunately my last attempt in #10918 alone was not sufficient. The reason is that some of the images are only pushed in the `push-main-manifests` step.
* I also disabled the `roxctl` job temporarily due to the bug discovered in #10928 (roxctl fails if no vulnerabilities are found). `roxctl` image currently has no vulnerabilities.
* The `stackrox-operator` image uses a slightly different format. We need to use `make -C operator tag` here.
Tested re-running the failed jobs *after* `push-main-manifests` was done. See https://github.com/stackrox/stackrox/actions/runs/8884874794/job/24396114650 for that run.
In addition to reviewing code here, reviewers **must** also review …
=> ROX-23767: scan after main manifests

central/alert/datastore/datastore_sac_test.go, central/cluster/datastore/datastore_sac_test.go, central/namespace/datastore/datastore_sac_test.go, central/node/datastore/datastore_sac_test.go, central/pod/datastore/datastore_impl_real_test.go, central/pod/datastore/datastore_sac_test.go, central/processbaseline/datastore/datastore_impl_test.go, central/processbaseline/datastore/datastore_sac_test.go, central/processbaselineresults/datastore/datastore_sac_test.go, central/processindicator/datastore/datastore_sac_test.go, central/processlisteningonport/datastore/datastore_impl_test.go, central/rbac/k8srole/datastore/datastore_sac_test.go, central/rbac/k8srolebinding/datastore/datastore_sac_test.go, central/risk/datastore/datastore_sac_test.go, central/secret/datastore/datastore_sac_test.go, central/serviceaccount/datastore/datastore_sac_test.go
In some case, this can lead to copy of objects which hold locks.
responsible for …
=> chore(test): Do not dereference pointers in assertions

.github/workflows/build.yaml
Make `make` silent because otherwise the `Entering directory` is logged to stdout (not stderr...) and gets assigned to the variable value.
```
❯ make -C operator tag
make: Entering directory '/Users/stephan/go/src/github.com/stackrox/stackrox/operator'
4.4.0-555-g44426a701b
make: Leaving directory '/Users/stephan/go/src/github.com/stackrox/stackrox/operator'
```
This should now make it green finally, see https://github.com/stackrox/stackrox/actions/runs/8888325330.
=> ROX-23767: silent operator make

.openshift-ci/end.sh, scripts/ci/lib.sh
For job metrics it was originally determined that canceled openshift-ci jobs did not propagate data saved by the terminated step to `SHARED_DIR` for use in future steps. Based on results however it appears that this is only the case when a terminated step does not exit before the openshift-ci grace period ([example](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/10836/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1783457015998189568)). Currently, steps that exit before the termination grace period propagate a failed value for `JOB_DISPATCH_OUTCOME` which results in an incorrect overall job outcome record of failed ([example](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/10713/pull-ci-stackrox-stack …
=> fix(CI): better cancelation support

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/CVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageHeader.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.cy.jsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/AffectedNodesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/components/NodeComponentsTable.cy.jsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/components/NodeComponentsTable.tsx
Adds the nested table of node components to both of the Node CVE single pages: CVE and Node.
Visit a Node CVE single page and expand table rows to view the table (mocked data):
Visit a Node single page and expand table rows to view the table (mocked data):
Table sorting tested via included component tests
=> ROX-23911: Add node components table

ui/apps/platform/src/Components/EmailNotifier/EmailNotifierForm.tsx, ui/apps/platform/src/Components/EmailNotifier/EmailNotifierModal.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/NotifierSelection.tsx
Prerequisite to factor out delivery destinations from Vulnerability Reports to reuse in Compliance Reports.
Start with `EmailNotifierForm` and `EmailNotifierModal` because they do not import anything from src/Containers/Vulnerabilities/VulnerablityReporting folder.
1. Move and rename EmailIntegrationForm.tsx as EmailNotifierForm.tsx
* Delete ESLint disable comment and delete `void` from function calls: early work-around to obsolete typescript-eslint error.
* Replace `variant={AlertVariant.warning}` with `variant="warning"` prop because enumerated string type is source of truth.
2. Move and rename EmailIntegrationFormModal.tsx as EmailNotifierModal.tsx
* Delete `size={TitleSizes.xl}` prop that specifies 20px instead of PatternFly default size 24px.
3. Edit NotifierSelection.tsx
* Change …
=> ROX-23929: Factor out email notifier from vulnerability reporting

pkg/deduperkey/key_test.go
Add test to check that SensorEvent was added as a deduper key
- CI
=> chore(test): Check that SensorEvent was added as a deduper key

central/telemetry/centralclient/instance_config.go, central/telemetry/centralclient/instance_config_test.go, pkg/env/telemetry.go, pkg/telemetry/phonehome/key_management.go, pkg/telemetry/phonehome/key_management_test.go
When configuring the telemetry key on a release central version, the current implementation ignores the provided value in favor of the hardcoded one.
This PR disables "downloading" of the hardcoded value if:
* a key is provided;
* the telemetry configuration URL is set to an empty value.
Tests have been added to cover some testable code paths.
Unit tests.
=> chore: telemetry: allow custom key for release versions

pkg/grpc/requestinfo/requestinfo.go, pkg/grpc/requestinfo/requestinfo_test.go, pkg/telemetry/phonehome/interceptor.go, pkg/telemetry/phonehome/interceptor_test.go
This is another try to refactor `requestinfo` after #10614.
The added tests exercise the three call flows:
* HTTP
* gRPC
* HTTP->gRPC gateway->gRPC
=> refactor: `requestinfo`

.golangci.yml
When running golangci-lint locally with one of the latest versions, you will get complaints about a couple of fields being deprecated in the config:
```log
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`.
WARN [config_reader] The configuration option `output.format` is deprecated, please use `output.formats`
WARN [config_reader] The configuration option `linters.staticcheck.go` is deprecated, please use global `run.go`
```
This PR fixes those occurrences and also bumps the go version to check against to 1.21. …
=> chore(lint): remove deprecated golangci-lint configs

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/useNodeExtendedDetails.ts, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/useClusterExtendedDetails.ts, ui/apps/platform/src/Containers/Vulnerabilities/components/ExpandableLabelSection.tsx
As titled
Visit a cluster single page and click the details tab.
Loading:
Error:
Success:
Test expand/collapse labels:
=> ROX-23079: Add details tab to cluster page

pkg/signatures/cosign_sig_fetcher.go, pkg/signatures/cosign_sig_fetcher_test.go, pkg/signatures/cosign_sig_verifier.go, pkg/signatures/cosign_sig_verifier_test.go, pkg/signatures/factory.go, pkg/signatures/factory_test.go
The previously existing signature fetcher / verifier abstractions were too tightly cut: we initially had plans to also add things like GPG signature fetcher / verifier. However, since this plan has been
cut _and_ in case of extending cosign signature verification support, it doesn't make sense to abstract in the way of `public key, certificate, rekor` if the fetching and verification mechanism will be the same just depending on the
input given by the signature integration.
Also cleaned up a couple of the factory functions for simplification. …
=> chore(signatures): refactor existing abstractions

qa-tests-backend/src/test/groovy/NetworkFlowTest.groovy
This test is failing on P/Z - see https://issues.redhat.com/browse/ROX-19615
- CI
=> ROX-19615: Skip 'Verify connections from external sources' on P/Z

.github/workflows/build.yaml
The scan workflow currently fails to scan images for nightly branches. Central returns 404 errors upon scanning (see https://github.com/stackrox/stackrox/actions/runs/8916679405/job/24489250757). The issue seems to be that the image uploaded by the previous build step is tagged differently to the one being scanned.
We need to run the `handle-tagged-build` action, which sets the `BUILD_TAG` env variable. This then changes the behavior of `make tag`.
Before:
```
make tag
4.4.x-586-g6341b5717a
```
After:
```
export BUILD_TAG=4.4.x-nightly-20240502
make tag
4.4.x-nightly-20240502
```
see explanation above
performed one does not …
=> fix: nightly tag roxctl scan

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SummaryCardLayout.cy.jsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SummaryCardLayout.tsx
Extracts the layout and logic for summary cards across VM 2.0.
- Removes duplication of `error`/`loading`/`data` checking logic
- Reduces layout duplication switching between `Skeleton` components and rendered data during loading states
- Makes the `isLoading` behavior consistent throughout VM 2.0 (previously we would display stale data when the request was refetched)
- Switches from `Grid` to `Gallery` based layout to ensure we have matching heights of all cards, regardless of content, without explicit height setting
- Avoids null checks on `data` at the call site by encapsulating this in a render prop
- Tests 🎉 
Manual testing of all VM 2.0 pages with summary cards to ensure the data still loads and displays correctly.
Component tests …
=> chore(ui): Abstract out summary card layout and logic

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/useNodeSummaryData.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/DeploymentPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/ImageCve/ImageCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SummaryCardLayout.cy.jsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SummaryCardLayout.tsx
Adds summary cards to the Node detail page.
Visit a Node detail page.
While the data is loading:
When error:
When success:
Test the hiding of severities and statuses when filters are applied (manually via the URL until the filter bar is complete):
=> ROX-23049: Add node detail page summary cards

roxctl/central/login/login.go
I don't think this is a big deal since `roxctl` just runs a command and then terminates, but I figure it's good hygiene to close response bodies once done with them.
no …
=> fix: close response body once done

CHANGELOG.md, roxctl/image/scan/cve.go, roxctl/image/scan/cve_test.go, roxctl/image/scan/scan.go, roxctl/image/scan/scan_test.go
Adds the `--severity` flag to the `roxctl image scan` command to filter CVE severities with it.
By default, all severities are taken into account.
- see CI.
Some manual tests:
```
roxctl image scan --image=quay.io/stackrox-io/roxctl:4.4.1 -o table
Scan results for image: quay.io/stackrox-io/roxctl:4.4.1
(TOTAL-COMPONENTS: 2, TOTAL-VULNERABILITIES: 2, LOW: 1, MODERATE: 1, IMPORTANT: 0, CRITICAL: 0)
+--------------------------+----------------------+----------------+----------+----------------------------------------------------------------------+
|        COMPONENT         |       VERSION        |      CVE       | SEVERITY |                                 LINK                                 | …
```
=> ROX-23852: add filtering for severity in image scan

pkg/complianceoperator/api.go, sensor/kubernetes/listener/resource_event_handler.go, sensor/kubernetes/listener/watcher/complianceoperator/availabilitychecker.go, sensor/kubernetes/listener/watcher/complianceoperator/availabilitychecker_test.go
Adds a test to check whether all the Compliance Operator resources are added to the AvailabilityChecker.
=> chore(test): Check all CO resources are in the AvailabilityChecker

CHANGELOG.md, pkg/features/list.go, pkg/registries/docker/registry_without_digest_call.go, pkg/registries/docker/registry_without_digest_call_test.go
Attempts to scan images from Nexus or Red Hat registries _may_ fail with `unsupported digest algorithm` errors when referenced by `tag` and Scanner V4 is active (not always, depends on multiple factors such as if a manifest list is present or not)
Scanner V4 requires a valid digest to scan an image (the "Stackrox Scanner" did not), a bug (arguably) has existed for some time where the image tag is set to the `Digest` field in image metadata ([here](https://github.com/stackrox/stackrox/blob/49a2532e939ab72c671bccf69026a71477a7e751/pkg/registries/docker/metadata_v2.go#L68-L70) and [here](https://github.com/stackrox/stackrox/blob/49a2532e939ab72c671bccf69026a71477a7e751/pkg/registries/docker/metadata_v2.go#L104-L106)) which is [later …
=> ROX-23953: Attempt Manifest Digest

README.md
The hyperlinks to `contributing.md` and `go-coding-style.md` are changed from `github/<filename>` to `.github/<filename>`. Those hyperlinks are now functional.
The files `contributing.md` and `go-coding-style.md` are located in `.github/` instead of `github/`
```sh
.github/api_guidelines.md        .github/contributing.md          .github/go-coding-style.md       .github/pull_request_template.md
```
=> fix: hyperlinks in README.md

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodeCveEntityCounts.ts, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/useNodes.ts, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/usePlatformCveEntityCounts.ts
Adds queries to get the counts for entity buttons on the overview pages.
**Note this is still mocked data**
Visit Platform CVEs and see that the entity counts load correctly:
Visit Node CVEs and see that the entity counts load correctly:
=> feat(ui): Add queries for node and platform cve entity counts

image/templates/helm/stackrox-central/templates/01-central-13-deployment.yaml.htpl, operator/tests/central/central-misc/080-assert-non-openshift.yaml, operator/tests/central/central-misc/080-assert-openshift.yaml
Start tracking the download API calls for roxctl.
This will give us insight in a) the general amount of downloads we see from Central and b) with the introduction of a custom user-agent for the roxctl-installer action it will also give us insights into the usage of the action itself and for which OS roxctl is mostly used.
- see CI pass.
Manual testing to see that the API calls are received in telemetry:
Taking the sample action run [here](https://github.com/dhaus67/test-repo/actions/runs/8956167238) which does:
- central login
- roxctl install
- run roxctl
We receive the following within amplitude:
_An event for the exchange API call from the central login action:_
```json
"event_properties": {
"Code": 200,
"Method": "POST",
"Path": …
```
=> ROX-23639: track central download API

pkg/postgres/pool_impl.go, pkg/stringutils/default.go, tools/deserialize-proto/README.md, tools/deserialize-proto/main.go, tools/deserialize-proto/main_test.go
Improve proto tooling to automatically resolve a proto to the configure database.
Changelist:
- to read from stdin added  `--stdin` flag (breaking change)
- automatically resolve proto `storage.XYZ` to its table name
- automatically connect to the database, configure it like a testing databases
- added `--id` flag to easily provide an id
- added `--where` to add where clauses to the query
- added `--debug` flag
This allows to easily run a database locally or port-forwarded, connect to it and print a de-serialized proto for a table entry.
- tested documented queries locally from `README.md`
=> feat(tooling): Improve proto tooling

ui/apps/platform/src/Components/DynamicIcon.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/NamespaceView/NamespaceViewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SeverityCountLabels.css, ui/apps/platform/src/Containers/Vulnerabilities/components/SeverityCountLabels.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/TableEntityToolbar.tsx
Fixes assorted minor visual issues in VM 2.0. Descriptions in testing section below.
1. The `<Divider>` element to the right of the Bulk Actions dropdown was not within the conditionally rendered block, so it previously would show up in Deferred and False Positive tabs:
2. Fixes the spacing between severity count labels that was a regression after upgrading to PF5:
3. Changes the "Filtered view" label to the compact variant to match the mocks, and fixes the vertical centering:
4. Fixes the pagination offset in the namespace view that previously would only increment the offset by `1` on each page:
=> fix(ui): Fix a handful of minor visual issues in VM 2.0

roxctl/image/scan/cve.go, roxctl/image/scan/scan.go, roxctl/image/scan/scan_errors.go, roxctl/image/scan/scan_test.go
Add a new flag `--fail`, which if enabled, causes `roxctl image scan` to fail if vulnerabilities have been found. The number of vulnerabilities is indicated in the error message and `roxctl` exits with code 1. If no vulnerabilities are found, `roxctl` exits normally with code 0.
see CI
```
roxctl image scan --fail --image=quay.io/rhacs-eng/main:4.4.1 -o table
WARN:	A total of 2 unique vulnerabilities were found in 2 components
ERROR:	image scan failed: vulnerabilities found: found 2 vulnerabilities
```
performed …
=> ROX-22475: add `--fail` flag to `roxctl image scan`

ui/apps/platform/cypress/integration/risk/deploymentTimeline.test.js, ui/apps/platform/cypress/integration/risk/podTimeline.test.js
Tests of PatternFly 5 versions of tooltips in ui-e2e-tests have been disabled because they have a high, but not predictable, flake rate–around 5% of runs.
A more thorough investigation should be done to determine why the tooltips sometimes don't open, or to adapt the timeline info to a more consistent display of info.
I created an internal ticket to track re-enabling, or adapting these tests:
https://issues.redhat.com/browse/ROX-24049
CI doesn't flake
=> chore(ci): Disable tooltip checks in Process Timeline e2e tests

central/convert/internaltov2storage/compliance_rule.go, central/convert/testutils/compliance_rules.go
Process compliance operator controls and persist them into the Central database. 
Each Control is associated with a standard and persisted denormalized.
This results in following structure:
| RuleID | Standard | Control |
|--------|----------|---------|
| uuid-1 | OCP-CIS  | 1.2.1   |
| uuid-1 | OCP_CIS  | 1.2.2   |
| uuid-1 | OCP_CIS  | 1.2.3   |
- Run Sensor in a cluster with CO installed imports control data
- Upgrade test case
- Install StackRox, install CO + run scan, upgrade StackRox 
- Should not duplicate results without controls 
- Mapping controls to standard should be correct
**Before State**
**After State**
=> ROX-23970: Process ComplianceOperator controls

central/postgres/pruning.go, central/postgres/pruning_test.go, central/processindicator/datastore/datastore.go, central/processindicator/datastore/datastore_impl.go, central/processindicator/datastore/datastore_impl_test.go, central/processindicator/datastore/mocks/datastore.go, central/pruning/pruning.go, central/pruning/pruning_test.go
Indicator pruning has become all or nothing.  Additionally changes to `DeleteMany` made using that an all or nothing as one batch was used for all transactions.  This PR is meant to chunk the deletion of process indicators.
The idea is to get the indicators orphaned by deleted deployments and prune those indicators.
Then get the indicators orphaned by deleted pods and prune those indicators.
Additionally an error with a batch should not stop all pruning, we should just move on to the next batch.  If there are issues, any pruning we can successfully complete is less we have to prune later.  If we keep the all or nothing approach, if the database begins to have issues with pruning, the problem snowballs as each pruning interval we have to prune the failed intervals records plus all the new …
=> ROX-23630: indicator pruning

scripts/ci/lib.sh
Example:
```
INFO: Wed May 8 10:01:20 UTC 2024: Polling for images required for system tests
awk: cmd. line:1: print $1
awk: cmd. line:1: ^ syntax error
INFO: Wed May 8 10:01:20 UTC 2024: Will poll for:
```
Introduced in #10750 🤦🏻 
=> test: Fix awk syntax error.

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragePage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CoveragesPageHeader.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.css, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.routes.ts, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/CoverageTableViewToggle.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/ProfilesTableToggleGroup.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/StatusCountIcon.tsx, ui/apps/platform/src/services/ComplianceResultsService.ts
Creates a table to display a single profiles check results
Notable changes:
- All coverage routes have been pulled into their own file for reusability - `compliance.coverage.routes.ts`
- Taking advantage of the newly created `getTableUIState` utility for table state 
- Added a placeholder for the benchmark controls column since that info is not available yet
- `CoverageTableViewToggle` component created for going between `ProfileChecksPage` and `ProfileClustersPage`
- `StatusCountIcon` component created for displaying status counts with their respective icon. Intended to also be used in `ProfileClustersPage` and `ProfileClusterDetails`
- Sorting, pagination, filtering will come later
wip
=> ROX-23691: Profile check results table

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/CheckDetailsPage.tsx
This PR adds the breadcrumbs to the `CheckDetailsPage` component
Note: For now I put `Compliance coverage` as the first breadcrumb. I need clarity on what we want to do there (cc: @bradr5 )
=> ROX-23998: Adding check details page breadcrumbs

.github/workflows/add-new-pr-to-oss-triaging.yml
Remove defunct adding to triaging board, done by project automation instead.
=> fix: update external-contributor triaging workflow

Makefile
When running the `make image` command on an M3 Mac, you get the following error:
```
failed to initialize build cache at /linux-gocache: mkdir /linux-gocache/00: permission denied
```
This happens during building the components (i.e. sensor central etc.) within the dockerized build.
On closer inspection, the mounted directory within the container has the permissions of the directory set to `root` instead of the UID of the user.
There were two options to fix this:
- when starting the container, make sure to chown the go cache directory to the UID within the container
- instead of using a standalone docker volume (i.e. one created by calling `docker volume create`) use a bind mount which preserves the UIDs on the directory
The latter seemed like the more fitting option. One thing to …
=> fix(build): make image on M3

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ComplianceProfilesProvider.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileChecksTable.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/compliance.coverage.utils.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/components/CheckStatusModal.tsx, ui/apps/platform/src/services/ComplianceCommon.ts, ui/apps/platform/src/services/ComplianceResultsService.ts, ui/apps/platform/src/services/ComplianceResultsStatsService.ts
The backend recently divided the compliance results service into two parts: one for stats and the other for results. This change aligns UI services with the backend proto counterpart.
Manually tested endpoints to ensure they still work
=> chore(ui): Split up compliance results service

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/DeploymentsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImagesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/utils/sortUtils.tsx
As titled, the return of the risk `priority` column in order to allow better prioritization of the Image and Deployment lists until we can get Olympic style sorting of the severity columns.
Also makes this column the default sort for each of the two tables.
Visit Workload CVEs and view the image table:
Sort risk:
Visit Workload CVEs and view the deployment table:
Sort risk:
Simulate a large number for Risk to ensure the centered layout looks good:
=> ROX-24103: Adds the Risk Priority column to image and deployment lists

ui/apps/platform/package.json, ui/yarn.lock
https://docs.cypress.io/guides/references/changelog#13-9-0
* We now pass the same default Chromium flags to Electron as we do to Chrome.
* Updated electron from 27.1.3 to 27.3.10 to address CVE-2024-3156
https://docs.cypress.io/guides/references/changelog#13-8-1
* Fixed a regression introduced in 13.6.0 where Cypress would occasionally exit with status code 1, even when a test run was successful, due to an unhandled WebSocket exception
* Updated zod from 3.20.3 to 3.22.5
https://docs.cypress.io/guides/references/changelog#13-8-0
* Added support for webpack-dev-server v5 to cypress/webpack-dev-server.
Prerequisite for integeration testing:
```sh
export CYPRESS_ROX_COMPLIANCE_ENHANCEMENTS=true
```
* …
=> chore(e2e): Update cypress 13.9.0 devDependencies in ui

ui/apps/platform/package.json, ui/yarn.lock
Version 1.3.3 was published 5 months ago and 1.4.0 was published 2 months ago.
Update with 2 sprints before next release while we are paying close attention to validation in compliance wizard steps.
https://github.com/jquense/yup/blob/master/CHANGELOG.md#140-2024-03-06
* add optional message to `nonNullable` schema methods
* `string`: Create `.datetime()`
3. `yarn lint` in ui/apps/platform
4. `yarn start` in ui
Prerequisite: create at least one collection.
Create e-mail notifiers on the fly.
1. Visit /main/vulnerabilities/reports and test validation.
* Does not display validation error if distribution lists is empty.
Confirmed on staging, so investigate in vulnerability reports after we merge #11062
Prerequisites:
```sh
export …
```
=> chore(ui): Update yup 1.4.0 dependencies in ui

pkg/retry/retryable.go, roxctl/central/db/restore/v2_restorer.go, roxctl/common/errors.go, roxctl/common/errors_test.go, roxctl/deployment/check/check.go, roxctl/image/check/check.go, roxctl/image/scan/scan.go
The ticket originally was filed due to an error not being thrown when an invalid endpoint was used. Since we fixed that in 4.4.0, I used this opportunity to fix the retry logic within roxctl.
Previously we just retried every error, which is a bit awkward especially if we are dealing with invalid arguments, unauthenticated creds or missing permissions.
This has been now fixed and all places relying on our `retry` package have been refactored to accomodate this.
- see CI.
performed testing and you are satisfied with …
=> ROX-23995: improve roxctl retries

central/reprocessor/mocks/reprocessor.go, central/reprocessor/reprocessor.go, central/signatureintegration/service/service_impl.go, pkg/images/enricher/enricher_impl.go, pkg/images/enricher/enricher_impl_test.go
In case no signature integration exist for verification, let's skip fetching signatures for the time being.
This won't really have any impact on the feature itself, since the reprocessing loop will short-circuit and force fetching sigs + verifying them once a signature integration is added.
This optimization only applies to the Central part of enrichment, since we do not sync signature integrations with Sensor and thus have to eagerly fetch signatures even if we don't need them (for the time being at least).
- see CI + added unit tests. …
=> ROX-23759: skip fetching signatures with no signature integrations

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/CVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/CVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/ImageVulnerabilitiesTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/CVESelectionTd.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/CVESelectionTh.tsx, ui/apps/platform/src/Containers/Vulnerabilities/hooks/useCanSnoozeCves.ts, ui/apps/platform/src/Containers/Vulnerabilities/hooks/useHasLegacySnoozeAbility.ts
Adds row selection checkboxes and row actions to the Platform CVE table when the user has the ability to snooze/unsnooze CVEs.
Visit the Platform CVE page with a user with `VulnManagementApprovals` READ_WRITE access and the feature flag enabled:
Test row selection and bulk dropdown:
Test opening row actions (currently empty):
Test the UI with the feature flag disabled:
Test the UI with insufficient `VulnManagementApprovals` permissions:
Test Workload CVE selection after the component refactor:
=> feat(ui): Add platform CVE row actions

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Node/NodePageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/NodeCve/NodeCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/components/NodeCveFilterToolbar.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Cluster/ClusterPageVulnerabilities.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SnoozedCveToggleButton.cy.jsx, ui/apps/platform/src/Containers/Vulnerabilities/components/SnoozedCveToggleButton.tsx, ui/apps/platform/src/Containers/Vulnerabilities/searchOptions.ts
Adds the show/hide Snoozed CVEs option to Node and Platform CVE overview pages. Clicking on the button is a shortcut for applying the "CVE Snoozed: true" filter in the upcoming advanced filters toolbar.
This button enables the read-only support of the same legacy feature in VM 1.0 (the ability to _write_ snooze CVE requests will be gated behind a runtime feature flag).
Visit Node CVEs:
Click the button in the top right, the button's text will change, a filter will be applied, and the network request will include this new filter:
Clicking the button again removes the filter:
Visit Platform CVEs:
Click the button in the top right, the button's text will change, and the network request will include this new filter:
Clicking the button again …
=> ROX-23818: Add CVE snoozed toggle option

ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/AffectedClustersTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/PlatformCvePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/PlatformCve/useAffectedClusters.ts
Adds sorting to the Platform CVE single page's table.
Load a Platform CVE single page and verify that the default sort is by cluster name, ascending alphabetical order. (There is only one record on my system, so we can verify the correct parameters are passed via the query and visible in the URL.)
Verify "Cluster" sort descending.
Verify "Cluster Type" sort descending.
Verify "Cluster Type" sort ascending.
Verify "Cluster Kubernetes Version" sort descending.
Verify "Cluster Kubernetes Version" sort ascending.
=> ROX-23069: Add sorting to Platform CVE single page table

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Deployment/ImageResourceTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Image/ImagePage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ImageNameLink.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/utils/images.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/utils/images.ts
Fixes image name display issue in cases where an image does not have a tag. This will display either:
- registry/remote:tag
- registry/remote@sha
depending on the presence of a non-empty tag field for an image name in the Workload CVEs section.
Prior to this change, images without a tag simply displayed a trailing `:` character.
Visit Workload CVEs and view the images tab.
Image names contain either a tag:
or a digest:
Manually verify that the copy button functionality also copies the correct full name.
Note that images that have no tag still do not have a menu option to "Watch image".
Verify tag/hash behavior in a CVE single page:
Verify behavior in Deployment page -> Details tab:
Verify the behavior in the header of an Image single …
=> ROX-23632: Use image SHA in name when tag does not exist

pkg/features/list.go, sensor/kubernetes/eventpipeline/resolver/resolver_test.go
Disable the aggregator queue until we figure out why the SummaryTests are flaking.
=> chore(resolver): Disable the aggregator queue

Makefile
> [When GOTOOLCHAIN is set to local, the go command always runs the bundled Go toolchain.](https://go.dev/doc/toolchain#:~:text=When%20GOTOOLCHAIN%20is%20set%20to%20local%2C%20the%20go%20command%20always%20runs%20the%20bundled%20Go%20toolchain.)
[Discussion](https://redhat-internal.slack.com/archives/C02CFR7GQUS/p1714740069768599)
- https://github.com/dependabot/dependabot-core/issues/9422
```go
➜  stackrox git:(ROX-24073-Use-GOTOOLCHAIN-local) go get -u k8s.io/api
go: k8s.io/api@v0.30.0 requires go >= 1.22.0; switching to go1.22.3
go: upgraded go 1.21 => 1.22.0
go: upgraded toolchain go1.21.9 => go1.22.3
go: upgraded k8s.io/api v0.29.3 => v0.30.0
go: upgraded k8s.io/apimachinery v0.29.3 => v0.30.0
go: upgraded k8s.io/kube-openapi …
```
=> ROX-24073: Use GOTOOLCHAIN local

tests/compliance_operator_test.go
Flakes were caused by a way time which was too short. Could reproduce the failure by setting the time to 0.
Eventually we would want to use Gomega and Ginkgo for tests which require eventual consistency. In this case however I'll not refactor it as we are going to remove the v1 co integration anyway.
- CI
=> ROX-24061: Fix compliance_operator flakes

image/templates/helm/shared/templates/02-scanner-v4-05-indexer-network-policy.yaml, image/templates/helm/shared/templates/02-scanner-v4-05-matcher-network-policy.yaml, image/templates/helm/shared/templates/02-scanner-v4-07-indexer-deployment.yaml, image/templates/helm/shared/templates/02-scanner-v4-07-matcher-deployment.yaml, image/templates/helm/shared/templates/02-scanner-v4-08-indexer-service.yaml, image/templates/helm/shared/templates/02-scanner-v4-08-matcher-service.yaml, image/templates/helm/shared/templates/99-shared-openshift-monitoring.yaml.htpl, image/templates/helm/stackrox-central/templates/_labels.tpl, image/templates/helm/stackrox-secured-cluster/templates/_labels.tpl, pkg/helm/charts/tests/centralservices/testdata/helmtest/openshift-monitoring.test.yaml, pkg/helm/charts/tests/securedclusterservices/testdata/helmtest/openshift-monitoring.test.yaml
This will change what is necessary to serve a secure metric endpoint based on Openshfit's service-serving certificates. It also enables metrics scrapping using a `ServiceMonitors` akin to Central and Sensor. But we use separate endpoints for matcher and indexer and match the service by component, which is "scanner-v4"--due to how the `_label` template parses it from the template filename. The ServiceMonitor seems to ignore services based on the service port existence. I noticed that from Central's SM.
I adopted ClusterRoles to access the monitoring secrets, so this also fixes ROX-22188.
I deployed these changes using Helm on a clean Openshift cluster:
1. Installing the central chart and secured cluster chart in the same namespace.
2. …
=> feat(scanner): Enable openshift metrics

tests/upgrade/validation.sh
Similar to:
- https://github.com/stackrox/stackrox/pull/9990
https://curl.haxx.se/docs/manpage.html
> `--retry`
> 
> If a transient error is returned when curl tries to perform a transfer, it will retry this number of times before giving up. Setting the number to 0 makes curl do no retries (which is the default). Transient error means either: a timeout, an FTP 4xx response code or an HTTP 5xx response code.
CI
=> ROX-21570: retry curls in validation.sh

ui/apps/platform/src/queries/serviceAccount.js
USER PROBLEM
- Browse to the service accounts for the "cluster-admin" role: Choose Configuration Management from the left menu. Navigate to "Role Based Access Control" dropdown, choose Roles. Scroll down and click on "cluster-admin"
- "maximise" the window with the arrow-square control.
- Click on "service accounts" tab at the top
- Note that every service account has "Disabled" in the "Cluster Admin Role" column despite having "cluster-admin" in the "Role" column
CONDITIONS
- This particular page exhibits this issue, but other pages that show cluster-admin roles do not
- URL path is something like /main/configmanagement/role/{id}/serviceaccounts
ROOT CAUSE
it looks like the response to the network call to /api/graphql?opname=getRole_SERVICE_ACCOUNT does not include an attribute for the …
=> ROX-24122: Add graphQL prop for clusterAdmin in Service Accounts table

ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/CVEsTable.tsx, ui/apps/platform/src/Containers/Vulnerabilities/NodeCves/Overview/NodeCvesOverviewPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/PlatformCves/Overview/PlatformCvesOverviewPage.tsx
Adds the ability to snooze/unsnooze Node CVEs via the UI.
This PR uses code common with Platform CVEs, so the implementation and UX is nearly identical. Re-use testing steps in:
1. https://github.com/stackrox/stackrox/pull/11041 to validate that permissions and feature flags correctly gate the row action and bulk dropdown functionality
2. https://github.com/stackrox/stackrox/pull/11040 to validate the snooze and unsnooze workflows for single and multiple CVEs
For further verification, the following screenshots show that requests when using the testing steps above are sent under the `nodecves` endpoint instead of the `clustercves` endpoint used in Platform CVEs:
Snooze single
Snooze multiple
Unsnooze single
Unsnooze multiple
=> ROX-23820: Add ability to snooze node cves in VM 2.0

ui/apps/platform/src/hooks/useURLPagination.test.tsx, ui/apps/platform/src/hooks/useURLPagination.ts, ui/apps/platform/src/hooks/useURLParameter.ts, ui/apps/platform/src/hooks/useURLSearch.ts, ui/apps/platform/src/hooks/useURLSort.ts, ui/apps/platform/src/hooks/useURLStringUnion.ts
We have a general purpose `useURLParameter()` hook that allows setting arbitrary values in the URL state and allows the caller to choose whether to `"push"` the history state, or `"replace"` it in place. Dependent on this hook are a handful of purpose built URL state hooks that we use throughout the application:
- `useURLSearch()`
- `useURLStringUnion()`
- `useURLPagination()`
- `useURLSort()`
The first two allow the caller to pass the history action when setting the state, which defaults to `"push"` and is rarely, if ever, called with `"replace"`. The latter two hooks omit this ability even though support for it can be easily added without needing to change any call sites.
The lack of this parameter becomes a problem when we want to change multiple URL parameter states at once and use …
=> fix(ui): Allow passing of "action" to sort and pagination hooks

image/rhel/konflux.Dockerfile, image/roxctl/konflux.Dockerfile, operator/konflux.Dockerfile, scanner/image/scanner/konflux.Dockerfile
As a workaround, we need to build Konflux images without release GOTAG. 
That is to use the SCANNER_VERSION and COLLECTOR_VERSION files to find the respective images. …
=> ROX-22474: Do not build Konflux images with release GOTAG

roxctl/common/client.go, roxctl/common/client_test.go
HTTP headers with no values are discouraged:
* RFC 2616 (HTTP/1.1 Specification):
According to RFC 2616, each header field consists of a name followed by a colon (":") and the field value. Empty field values can lead to undefined or non-standard behaviors.
* Mozilla Developer Network (MDN):
The MDN documentation specifies that headers should have valid values. An empty value may lead to incorrect handling or rejection of the request by the server.
* OWASP (Open Web Application Security Project):
OWASP guidelines emphasize the importance of proper HTTP header values to ensure secure communication and avoid potential security risks.
Let's not add `Rh-Execution-Environment` header if no value is provided.
```console
me@work$ bin/linux_amd64/roxctl central whoami --plaintext --insecure -e …
```
=> fix: drop execution environment header with no value

qa-tests-backend/src/test/groovy/K8sRbacTest.groovy
Moved the check into the retry loop and gave it an extra iteration.
~- [ ] Unit test and regression tests added`
provided convince any reviewer or any external reader that you …
=> ROX-23468:  rbac test flake

ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/CVEsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/DeploymentsTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/ImagesTableContainer.tsx, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Overview/WorkloadCvesOverviewPage.tsx
Small refactor in preparation for adding a "no CVEs" view to Workload CVEs.
This moves the construction of the search filter sent to CVE, Image, and Deployment queries to the top level where it is already being create elsewhere, in order to avoid duplication and out-of-sync issues.
CI
Manual testing of the Workload CVE tables.
=> chore(ui): Lift up construction of workload cves query

central/complianceoperator/v2/checkresults/datastore/datastore_impl.go
Sort order was overwritten when the default sorts should have only been applied if there was no sort options present.
```
curl --insecure "https://central-stackrox.apps.ds-05-17-cooing-color-intere.ocp.infra.rox.systems:443/v2/compliance/scan/results/profiles/rhcos4-e8/checks?query.pagination.sortOption.field=Compliance%20Check%20Name&query.pagination.sortOption.reversed=true" -u admin:XXX | json_pp > …
```
=> ROX-24285:  compliance fix overwritten sort

ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CloneVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/CreateVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/ModifyVulnReport/EditVulnReportPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/VulnReports/VulnReportsPage.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/EmailTemplatePreview.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/components/ReportParametersDetails.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/ReportParametersForm.tsx, ui/apps/platform/src/Containers/Vulnerabilities/VulnerablityReporting/forms/useReportFormValues.tsx
This change to some of the labels in Reporting in VM 2.0 addresses the last request, a bug, for the Epic "Collections In-use".
> The vulnerability reporting menus are referencing collections as "report scopes". While I think this is the intention of the collections it was confusing because I looked for "collections" and searched via ctrl + F and couldn't find it.
I asked the ACS docs teams to decide, and this is what @kcarmichael08 suggested in a comment on the Jira ticket:
> Maybe it's called "scope" because collections replaced "access scopes" in reporting? The page where you're setting up the report parameters isn't too confusing because the guidance says "Select a collection" in the drop-down list, but if you wanted to be more clear, an alternative would be "Collection included" in …
=> ROX-21732: Standardize on collection label for VM report in UI

ui/apps/platform/src/Components/CompoundSearchFilter/components/CheckboxSelect.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundFilterInputField.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.cy.jsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilter.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/CompoundSearchFilterInputField.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/components/EntitySelector.tsx, ui/apps/platform/src/Components/CompoundSearchFilter/types.ts, ui/apps/platform/src/Components/CompoundSearchFilter/utils/utils.test.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/Tables/table.utils.ts, ui/apps/platform/src/Containers/Vulnerabilities/WorkloadCves/components/ComponentLocation.tsx, ui/apps/platform/src/types/image.proto.ts
This PR adds different search filter inputs to the compound filter. We begin by adding the `text` and `select` inputs.
=> ROX-23508: Adding text input and select for advanced filters

.github/workflows/scanner-dev-vuln-update.yaml, .github/workflows/scanner-release-vuln-update.yaml
This will publish multi-bundle vulns in addition to existing single-bundle vulns. The release workflow was updated to continue publishing single-bundle vunls for `4.4.*` releases and switching to multi-bundle for newer releases.
Run workflows based on this PR's branch:
- Release workflow: https://github.com/stackrox/stackrox/actions/runs/9008637193
- Dev workflow: https://github.com/stackrox/stackrox/actions/runs/9024320501
=> feat(scanner): updater: Publish multi-bundle vulns

ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersPage.tsx, ui/apps/platform/src/Containers/ComplianceEnhanced/Coverage/ProfileClustersTable.tsx, ui/apps/platform/src/services/ComplianceResultsStatsService.ts
Adds pagination to the Compliance V2 Profile Clusters table
=> ROX-24100: Profile clusters table pagination

scripts/ci/gke.sh
If you're really unlucky, you can get a `.` at the end of the `tags` variable, which will be substituted for `-` _after_ we replace the last `-` with `x`.  GKE doesn't allow for `-` at the end of the string, which is why we change the last `-`.
See https://github.com/openshift/release/pull/47789 for a real-world example of this problem.
These changes reorders the shell expansion so we first replace all `.` with `-`, _then_ delete the last `-`.
- ~~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into …
=> fix(ci): reorder gke tags and labels variable expansions

central/networkgraph/entity/datastore/datastore_impl.go, central/networkgraph/entity/datastore/internal/store/mocks/store.go, central/networkgraph/entity/datastore/internal/store/store.go
When a cluster is deleted, it calls `DeleteExternalNetworkEntitiesForCluster` in networkEntity's in a go routine. When multiple clusters are deleted, there are multiple routines calling `DeleteExternalNetworkEntitiesForCluster`. This function acquires lock on `netEntityLock` and walks through all the network entities. This can be slow and cause other routines to timeout waiting on `netEntityLock` . This is probably causing "TestClusterDeletion" failures in CI because that test creates 58083 network entities. This is an attempt at a quick fix to filter out some of the entities before walking through them to reduce contention. A more complete solution would be to make `clusterID` searchable in `NetworkEntity` proto but that would require migration and thus more time to fix.
- ~[ ] Unit test …
=> ROX-23847: Attempt at reducing lock contention in network entities datastore

CHANGELOG.md
Updates for rmoving RocksDB
~- [ ] Investigated and inspected CI test results~
provided convince any reviewer or any external reader …
=> ROX-23220:  rocksdb changelog

scripts/ci/metrics.sh
Since `bq` is running in a function in a `while` loop, `set -e` has no effect and does not stop execution.
This change explicitly tests the exit code and skips the move with a loud message easy to grep for.
Plan:
```
INFO: Tue May 21 06:58:58 UTC 2024: Gathering a batch of image-prefetches-metrics to load
INFO: Tue May 21 06:58:59 UTC 2024: Found 1 metric(s) for this batch load
INFO: Tue May 21 06:58:59 UTC 2024: Moving the batch to gs://stackrox-ci-artifacts/image-prefetches-metrics/processing/2024-05-21-06-58-59.745974966
Copying gs://stackrox-ci-artifacts/image-prefetches-metrics/upload/bla [Content-Type=application/octet-stream]...
/ [0/1 files][    0.0 B/  160.0 B]   0% Done                                    
/ [1/1 files][  160.0 B/  160.0 B] 100% Done …
```
=> test: stop moving failed batches to done location
